### ISSUE TITLE
Support for filtering by label

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1001]
---

Author Name: **Daniel Molina** (Daniel Molina)
Original Redmine Issue: 4262, https://dev.opennebula.org/issues/4262
Original Date: 2015-12-22

---

None

**Comment by trenton42** [comment]
This would be very helpful. Is there any way to do this or any plan to add this?

**Comment by tinova** [comment]
Now is possible to filter by one label (by clicking on it). Does this involve filtering by more than one label?

**Comment by trenton42** [comment]
Oh sorry, I didn't look closely at this issue. I was trying to filter with `onevm` on the command line. Is that possible?

**Comment by tinova** [comment]
Well, no, apologies, this is indeed a CLI feature. Currently is not possible (you can onevm list -x, and parse the result). Bumping this to evaluate for 5.10.

**Comment by trenton42** [comment]
Thank you! We can use that workaround for now.

**Comment by tinova** [comment]
In 5.8, with a mysql backend, the following is possible:

   onevm list --search "LABEL=xxx"

**Comment by tinova** [comment]
Implemented as part of #2671

**Comment by tinova** [comment]
Turns out this only works if there is only one label per resource, or if the search is done for the first label of the resource. We'll investigate this further in future releases #2906
