### ISSUE TITLE
Uploading big image via sunstone got error message

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1002]
---

Author Name: **Rolandas Naujikas** (Rolandas Naujikas)
Original Redmine Issue: 4266, https://dev.opennebula.org/issues/4266
Original Date: 2015-12-23

---

[ImageAllocate] Error allocating a new image. NAME is already taken by IMAGE 34. 

After all this image is uploaded successfully.
It looks like in some case (probably some timeout) sunstone tries register again image (after successful upload).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Rolandas Naujikas** (Rolandas Naujikas)
Original Date: 2015-12-23T08:06:48Z

---

At least it is for the case when BRIDGE_LIST is used.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Anton Todorov** (Anton Todorov)
Original Date: 2015-12-31T13:30:06Z

---

Hi,

I hit similar issue when defining new datastore. It was with same wording, but for the DATASTORE name. The datastore was created and I was in a hurry to reproduce/catch another issue so I do not take enough care for the message.

It occurred on sunstone process running on highly loaded CPU core so with high probability it is some timeout or race condition during high load?

Regards,
Anton Todorov

**Comment by kvaps** [comment]
I think this issue is closed.

**Comment by rsmontero** [comment]
Yes it seems so, will reopen if needed
