### ISSUE TITLE
Flow wizard: the VM template search box of roles should be filled with content of the previous one

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1006]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 4281, https://dev.opennebula.org/issues/4281
Original Date: 2016-01-10

---

Hello,

When adding roles to a service, the user:

* fill the search box to narrow the VM template list
* select the wanted VM template
* click on *@+Add another role@*
* the search box is empty

Sunstone could remember the content of the last search box and fill the search box of the new role with it to avoid maximum of keystrokes.

If templates are named consistently, the user:

* will enter the common part of several templates, for example *@app-foo@* which returns all the VM templates related to application *@foo@* (*@app-foo-frontend@*, *@app-foo-db@*, *@app-foo-backend@*, …)
* select the *@app-foo-db@* and configure the role
* click on *@+Add another role@*
* select the *@app-foo-backend@*, define *@app-foo-db@* as parent and configure the role
* click on *@+Add another role@*
* select the *@app-foo-frontend@*, define *@app-foo-backend@* as parent and configure the role

Regards.

**Comment by al3xhh** [comment]
This text box (and the complete dialog) was revamped on latest version, closing this as it might not apply right now.
