### ISSUE TITLE
Allow user to have multiple SSH keys

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1008]
---

Author Name: **Vincent Van der Kussen** (Vincent Van der Kussen)
Original Redmine Issue: 4287, https://dev.opennebula.org/issues/4287
Original Date: 2016-01-13

---

Hi, 

I'm not sure if this has been requested before, but the ability to have multiple ssh keys available per user would be a nice addition.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Molina** (Daniel Molina)
Original Date: 2016-01-13T09:39:37Z

---

Hi Vincent,

You can include more that one public key adding a \n among them. The only problem is that you won't be able to select an specific ssh key for each VM as you do in EC2.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Vincent Van der Kussen** (Vincent Van der Kussen)
Original Date: 2016-01-13T09:42:15Z

---

That was the idea actually.

**Comment by sbbarragan** [comment]
PRs to merge:
- doc: https://github.com/OpenNebula/docs/pull/1431

**Comment by sbbarragan** [comment]
will reopen if additional feedback is given
