### ISSUE TITLE
Support to outsource Virtual Machines to OpenStack providers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1014]
---

Author Name: **Carlo Daffara** (Carlo Daffara)
Original Redmine Issue: 4302, https://dev.opennebula.org/issues/4302
Original Date: 2016-01-21

---

As much as I love OpenNebula, I had to witness several major IT services standardizing on OpenStack to create their own IaaS public services. It would greatly extend the range of available hybrid providers if OpenNebula provided a set of VMM_MAD remotes for openstack. A ruby library for low-level interfacing is already available ( https://github.com/ruby-openstack ) and is relatively similar to the AWS one.
A reasonable alternative would be a (not abandoned) multicloud driver, like jclouds or deltacloud.

**Comment by tinova** [comment]
hybrid drivers are no longer maintained, out of the scope of the project
