### ISSUE TITLE
vmm: specify "--mode" parameter to virsh commands for KVM drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1016]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 4306, https://dev.opennebula.org/issues/4306
Original Date: 2016-01-22

---

Hi,

This is some kind of a mix between bug report and feature request. In /var/lib/one/remotes/vmm/kvm/reboot, I had to specify "--mode acpi" otherwise KVM tries and fails to reboot the VM with agent method. (qemu guest agent is not installed...)
```
exec_and_log "virsh --connect $LIBVIRT_URI reboot $deploy_id --mode acpi" \
    "Could not reboot domain $deploy_id"

```

Surprisingly, there is no problem with shutdown, acpi seems to be the KVM default in this case.
Maybe the modes (agent, acpi...) could be declared in /var/lib/one/remotes/vmm/kvm/kvmrc and tried in that specified order.

Many thanks,

Laurent

**Comment by dann1** [comment]
Having the VCPUs set is enough, as if they aren't being used the virtualization node can multiplex them for other processes.

A better approach for this would be implementing live capacity resize

**Comment by dann1** [comment]
There
