### ISSUE TITLE
disk snapshots for vcenter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1018]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4309, https://dev.opennebula.org/issues/4309
Original Date: 2016-01-26

---

In both TM and DS drivers

**Comment by tinova** [comment]
Not straightforward due to vCenter offered functionality, too convoluted to be considered realistically at this moment.

**Comment by tinova** [comment]
Need to research into clone disk functionality

**Comment by tinova** [comment]
can't be reasonably implemented, no vCenter support
