### ISSUE TITLE
Better handling of optional roles (min/default cardinality 0)

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1019]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 4310, https://dev.opennebula.org/issues/4310
Original Date: 2016-01-27
Original Assignee: Abel Coronado

---

Hello,

I just created a service with optional roles:

```
<code class="javascript">
    {
      "name": "PC_admin",
      "cardinality": 0,
      "vm_template": 12780,
      "parents": [
        "Horus"
      ],
      "min_vms": 0,
      "max_vms": 5,
      "elasticity_policies": [

      ],
      "scheduled_policies": [

      ]
    },
</code>

```

Here is my review:

* the cloud view does not support well:
** the *@0@* cardinality, the cursor is outside the cardinality bar
** it's not possible to reset the cardinality *@0@*
* starting the service works as expected, the _optional_ VMs are not deployed but their status is *@RUNNING@*:
```
ROLE PC_admin
ROLE STATE          : RUNNING
PARENTS             : Horus
VM TEMPLATE         : 12780
CARDINALITY         : 0
MIN VMS             : 0
MAX VMS             : 5
NODES INFORMATION
 VM_ID NAME                    STAT UCPU    UMEM HOST                       TIME


```
* scaling the _optional_ VMs works, but I can not set it to *@0@*

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2016-07-19T10:19:00Z

---

I tested with 5.0 and the issue is still present.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2017-06-08T14:30:35Z

---

I tested with 5.4 and things are a little better except for cloud view:

* We can define a role with *@Min VMs@* at *@0@*: attachment:flow-define-role-with-min-0-max-1.png
* The service can be deployed with a cardinality of *@0@*: attachment:flow-service-OK-without-VM.png
* The cloud view does not permit to scale the role, either up or down: attachment:flow-cloud-view-can-not-scale.png
* The user view permit to scale the role
** Scale up
*** attachment:flow-user-view-can-scale-up.png
*** attachment:flow-user-view-scaling-up.png
** Scale down
*** attachment:flow-user-view-can-scale-down.png
*** attachment:flow-user-view-scaling-down.png
* The user view permit to choose a value outside *@Min VMs@* and *@Max VMs@*: attachment:flow-user-view-do-not-limit-scale.png

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2017-06-08T14:31:15Z

---

Add missing screenshots.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2017-06-08T14:32:40Z

---

Note that the error message when I tried to scale too much is not very informative.

Regards.

**Comment by tinova** [comment]
Relevant for OneFlow revamp

**Comment by rsmontero** [comment]
Onflow handles this type of flows. This issue is about rendering 0 VMs roles in Sunstone/Cloud view

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/docs/pull/1428
- doc: https://github.com/OpenNebula/one-ee/pull/722

**Comment by tinova** [comment]
needs testing
