### ISSUE TITLE
Enable showback for imported VMs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1020]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4311, https://dev.opennebula.org/issues/4311
Original Date: 2016-01-27

---

The showback attributes are not in the user template section of the VM and hence cannot be injected.

**Comment by tinova** [comment]
Duplicated by #1220
