### ISSUE TITLE
Do not pass clear text password as authenticate module parameter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1021]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 4313, https://dev.opennebula.org/issues/4313
Original Date: 2016-01-28

---

Hello,

Doing some sysadmin stuff on the frontend, I see in a *@ps@* output the password of users:

```
 2256 ?        SNl    0:00  \_ ruby /usr/lib/one/mads/one_auth_mad.rb --authn ssh,x509,ldap,server_cipher,server_x509
 2441 ?        SN     0:00      \_ sh -c /var/lib/one/remotes/auth/ldap/authenticate dad uid\=dad,ou\=utilisateurs,ou\=eole,ou\=education,o\=gouv,c\=fr SomePasswordInClearText ; echo ExitCode: $? 1>&2
 2444 ?        SNl    0:00      |   \_ ruby /var/lib/one/remotes/auth/ldap/authenticate dad uid=dad,ou=utilisateurs,ou=eole,ou=education,o=gouv,c=fr SomePasswordInClearText
 2475 ?        SN     0:00      \_ sh -c /var/lib/one/remotes/auth/ldap/authenticate dad uid\=dad,ou\=utilisateurs,ou\=eole,ou\=education,o\=gouv,c\=fr SomePasswordInClearText ; echo ExitCode: $? 1>&2
 2477 ?        SNl    0:00          \_ ruby /var/lib/one/remotes/auth/ldap/authenticate dad uid=dad,ou=utilisateurs,ou=eole,ou=education,o=gouv,c=fr SomePasswordInClearText

```

Two options to avoid it:

* use an environment variable
* use stdin

Regards.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This should be fixed through stdin, in fact drivers are now by default reading from stdin.
