### ISSUE TITLE
Enhance Host moniroting Graphs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1022]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4318, https://dev.opennebula.org/issues/4318
Original Date: 2016-02-04

---

Real memory and CPU allocation are now shown in Sunstone, but ideally it should be depicted against real memory and CPU consumption from VMs running in the host. In this way, overcommitment hazards can be spotted visually.

**Comment by rsmontero** [comment]
Done
