### ISSUE TITLE
Enhance overcommitment configuration

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1026]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4354, https://dev.opennebula.org/issues/4354
Original Date: 2016-02-22

---

Instead of using negative values for RESERVED_* attributes

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tino Vázquez** (Tino Vázquez)
Original Date: 2016-04-25T17:28:30Z

---

Honor this as well in vertical resizing (increase RAM and CPU of VM)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-04-26T15:16:22Z

---

This could be implemented using a policy like, using a dynamic expression, much like RANK

**Comment by rsmontero** [comment]
Already implemented in current versions
