### ISSUE TITLE
ONE_AUTH variable not honored by x509 login

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1028]
---

Author Name: **Daniel Kouril** (Daniel Kouril)
Original Redmine Issue: 4379, https://dev.opennebula.org/issues/4379
Original Date: 2016-03-22

---

The ONE_AUTH variable seems to be ignored while authentication token is being created using 'oneuser login USER --x509' and the outcome is always stored in $HOME/.one/one_auth. Other subsequent commands (like onehost) tries to read the file referred to by ONE_AUTH, which yields weird errors.

**Comment by al3xhh** [comment]
Another bug related has been found:

```
$ oneuser login USER --x509      
undefined method `call' for [-1, "no implicit conversion of nil into String"]:Array
```

**Comment by al3xhh** [comment]
I have tested it and it works for me in the current master version:

```
$ export ONE_AUTH=/tmp/one_auth

$ oneuser login test --x509 --cert cert.pem -k key.pem
Enter PEM pass phrase:
  * Do you want to overwrite the file /tmp/one_auth? (Y|N): 
N
File /tmp/one_auth exists, use --force to overwrite.
Authentication Token is:
test:e5e1ace4dc9fd93555df55c514b4c9aad1b1499430109282c1392dd51842fee8
```
