### ISSUE TITLE
Ease VNC access in production environments

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1034]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4423, https://dev.opennebula.org/issues/4423
Original Date: 2016-04-21

---

Take into consideration:

  - Enable changing port from 29876 to either 80 or 443 (privileged)
  - Route all VNC traffic through a different IP address in the front-end

**Comment by tinova** [comment]
Too disrupting, please reopen with a valid use case

**Comment by atodorov-storpool** [comment]
> Enable changing port from 29876 to either 80 or 443 (privileged)
> Route all VNC traffic through a different IP address in the front-end

IMO this functionality is implemented with #878 almost entirely.

But for completeness, the path to `/websockify` in sustone should be normalized. So the following workaround shouldn't be needed (nginx example):

```
    location / {
        if ($args ~* "host=.+&port=.+&token=.+&encrypt=.+") {
            rewrite ^/$ /websockify/ last;
        }
        ...
   }
```

For some context see https://forum.opennebula.io/t/sunstone-with-nginx-proxy-working-configuration/8952/2?u=atodorov_storpool

**Comment by tinova** [comment]
Hi @atodorov-storpool , good point, targeting for 6.0.

**Comment by tinova** [comment]
Covered by #2781
