### ISSUE TITLE
Refresh Sunstone after an action is perfrmed

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1040]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 4438, https://dev.opennebula.org/issues/4438
Original Date: 2016-04-29

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Jaime Melis** (@jmelis)
Original Date: 2016-04-29T13:17:04Z

---

Example: you instantiate a VM, and Sunstone refreshes the VM datatables a few times until it's in STATE != PENDING.

**Comment by rsmontero** [comment]
done
