### ISSUE TITLE
Add and remove security group from a NIC

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1049]
---

Author Name: **Guillaume Oberlé** (Guillaume Oberlé)
Original Redmine Issue: 4499, https://dev.opennebula.org/issues/4499
Original Date: 2016-05-28

---

Add the possibility to add and remove security groups on an attached NIC (without detaching and reattaching the NIC).

**Comment by paczerny** [comment]
Duplicate of #5612
