### ISSUE TITLE
Sunstone Views should not be hypervisor specific

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1050]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 4504, https://dev.opennebula.org/issues/4504
Original Date: 2016-05-30

---

There is currently functionality in admin_vcenter for instance that is not present in admin.

The admin view should have a vCenter import functionality, and show the valid options per VM dynamically looking if they are intended for KVM or vCenter.

**Comment by rsmontero** [comment]
duplicates #1270
