### ISSUE TITLE
Do not "click" in Sunstone when selecting text

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1052]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 4522, https://dev.opennebula.org/issues/4522
Original Date: 2016-06-07

---

When selecting some text in the Sunstone GUI the "select click" is interpreted as a "click" and the resource is selected (vm, image, template, etc.). This is quite annoying. Is it possible to change this behaviour? For example with a seperate icon you can click?

**Comment by FlorianHeigl** [comment]
+1 highly annoying for all users I know.
