### ISSUE TITLE
Keep a registration of "Keepalive ID / virtual_router_id" for Virtual Routers per virtual network

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1054]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 4532, https://dev.opennebula.org/issues/4532
Original Date: 2016-06-08

---

When creating a virtual router HA pair there is the possiblity to specify the "Keepalive ID / virtual_router_id". To avoid duplicate MAC's in a given network OpenNebula should keep track of these id's. Very much like how IP leases work.

**Comment by hydro-b** [comment]
I see you closed this issue. Can you give a short explanation why this idea is abandoned? Thx.

**Comment by rsmontero** [comment]
Hi sorry @hydro-b just purging the backlog, not sure if this was still a need. I'll reopen it.

As a possible strategy of implementation we can leverage the bitmap (as in VNC ports or VLAN_ID's) per cluster. 

Please let me know if you are still interested in tackling this
