### ISSUE TITLE
Possibility to update context files

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1067]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4639, https://dev.opennebula.org/issues/4639
Original Date: 2016-07-13

---

Right now the only way to change a file in the files datastore is deleting it and adding a new one with the same name. This causes problems with already created VMs. There should be a way to upload new versions of the same file.

**Comment by rsmontero** [comment]
Should work on current versions
