### ISSUE TITLE
novnc mouse doesn't work when a touchscreen is present

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1069]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 4652, https://dev.opennebula.org/issues/4652
Original Date: 2016-07-19

---

With touch aware browsers normal mouse does nor move or click in VNC.

The new release of novnc fixes this problem.

https://groups.google.com/forum/#!topic/novnc/bOpKeuZCd7s

**Comment by rsmontero** [comment]
Closing this as duplicate, we'll update sunstone dependencies #1565
