### ISSUE TITLE
Missing share action for service templates

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1073]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 4678, https://dev.opennebula.org/issues/4678
Original Date: 2016-07-25

---

Hello,

Using ONE 5.0.2-2, the VMs and Virtual Routers templates has the *@share@* actions, useful for the group administrator but the Service templates does not.

This requires to enable the *@chmod@* action.

Is it possible to add the *@share@* action to Services templates?

**Comment by rsmontero** [comment]
share button not in use
