### ISSUE TITLE
onevnet man page inconsistency

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1076]
---

Author Name: **Alvaro Simon** (Alvaro Simon)
Original Redmine Issue: 4692, https://dev.opennebula.org/issues/4692
Original Date: 2016-07-28
Original Assignee: Ruben S. Montero

---

Hi

This is just a small issue in the onevnet man page, in updatear section we can read:

```
updatear vnetid ar_id [file] Update Address Range variables. SIZE, IP, MAC and TYPE cannot be updated

```

but this is not 100% accurate, it is possible to change the SIZE value using the onevnet command or from sunstone frontend.

**Comment by al3xhh** [comment]
The size can be changed using Sunstone and the CLI. 

To update it in Sunstone, just go to the address tab inside the network, click on the AR and then on update button.

To update it using the CLI, just use `onevnet updatear` command, it will prompt an editor where you can change the size.

Closing this.
