### ISSUE TITLE
Documentation: Update BOOT section within VM template reference for ONE5

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1078]
---

Author Name: **Alvaro Simon** (Alvaro Simon)
Original Redmine Issue: 4700, https://dev.opennebula.org/issues/4700
Original Date: 2016-08-03
Original Assignee: Ruben S. Montero

---

Hi

Since OpenNebula 5.0.0 the boot section was changed to specify the boot order with: nic0,disk0.. etc. 
This change should be included also in the documentation within VM template reference page:
http://docs.opennebula.org/5.0/operation/references/template.html#os-and-boot-options-section

Cheers and thanks!
Alvaro

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-08-03T15:46:07Z

---

Good catch thanks!

**Comment by al3xhh** [comment]
Information already added in the documentation, closing this.
