### ISSUE TITLE
Default keyboard layout for vm

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1080]
---

Author Name: **Yannick MOLINET** (Yannick MOLINET)
Original Redmine Issue: 4709, https://dev.opennebula.org/issues/4709
Original Date: 2016-08-16

---

By default, the VNC keyboard layout is en_us.
This can be change only on each VM Template individualy.
It could be great to change this setting for all VM.

In my case, I keep the language interface is English, but use an french keyboard.
So each template must be set with fr in the VNC keymap.
Have a global setting could be a good feature.

Thanks,
Yannick

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Armin Deliomini** (Armin Deliomini)
Original Date: 2017-04-19T08:27:59Z

---

It would be awesome to have the general possibility to set default values for all the fields in the templates (e.g. i/o options, nic type, ...)

**Comment by AdriMenendezM** [comment]
This would be very usefull form imported VMs too. When a VM is imported on running state it required a poweroff cycle just for set the vnc keymap languaje...

**Comment by tinova** [comment]
this is covered in the new React Sunstone
