### ISSUE TITLE
Change the date format without change the language

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1091]
---

Author Name: **Yannick MOLINET** (Yannick MOLINET)
Original Redmine Issue: 4746, https://dev.opennebula.org/issues/4746
Original Date: 2016-08-25

---

Be able to change the date format (in charts) from YY/MM/DD to DD/MM/YY (for example) without to change the sunstone language.

**Comment by rsmontero** [comment]
Done already
