### ISSUE TITLE
Do not reset search fields data

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1094]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 4757, https://dev.opennebula.org/issues/4757
Original Date: 2016-09-01
Original Assignee: Daniel Molina

---

Hello,

When I instantiate VMs, each time I need to redo my template filter.

In user view, the search fields are kept per resources, so when moving from *@Templates > VMs@* to *@Templates > Services@* then moving back, the same filtering apply.

I think it could be better to keep the last search filter after instantiate a VM/service in cloud view too.

Regards.

**Comment by rsmontero** [comment]
It is preserved during tab changes. We will close this and if there are more people looking for this will reopen
