### ISSUE TITLE
Update fields once in multiple templates/images/vms.

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1101]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 4787, https://dev.opennebula.org/issues/4787
Original Date: 2016-09-17

---

Hi!

I have often the problem when need to update the one field once in multiple templates. For example: change image to new image, or change value of custom field in conextulisation.
Doing this manually for each template is very tedious, I would like to be able to select all needed templates by tick, then press the UPDATE button, then change field and save the image.

Now this action returns:
> Please select one (and just one) resource to update.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2016-09-17T23:08:56Z

---

Ouch! Sorry, wrong title, please change it to "Update fields once in multiple templates/images/vms." :-[

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlos Martín** (Carlos Martín)
Original Date: 2016-09-19T08:59:59Z

---

Hi,

I don't think this is a reasonable thing to do in sunstone, it looks more like something to be scripted using the API.

Let's say you select 2 templates to update with these disks:

Template 1
```
DISK = [ IMAGE = ubuntu ]
DISK = [ IMAGE = data ]

```

Template 2
```
DISK = [ IMAGE_ID = 17 ]

```

How would the wizard disks section look?

**Comment by kvaps** [comment]
Hi @carlosms, I think we can return an error in this case
