### ISSUE TITLE
Allow to Save As a vm disk while the vm is in any state (such as undeployed)

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1112]
---

Author Name: **John Noss** (John Noss)
Original Redmine Issue: 4828, https://dev.opennebula.org/issues/4828
Original Date: 2016-09-28

---

Currently a vm disk can only be saved (via Save As in Sunstone, or onevm disk-saveas from cli) if the vm is running (or in suspended/poweroff state), but not if the vm is undeployed (or any other state). For Ceph datastore, the vm disk is accessible in all cases, so it would be nice if OpenNebula could Save As a vm disk while the vm is in any state.

Current output when trying to run onevm disk-saveas for a disk on an undeployed vm:
[VirtualMachineDiskSaveas] VM has to be RUNNING, POWEROFF or SUSPENDED to save disks.

Desired result: OpenNebula controller supports Save As for a vm disk while the vm is in any state.

Also, the ceph driver scripts will be able to access the ceph disk from any host in the bridge list, so the disk saveas to a new image could happen on any of them, not necessarily just the hypervisor it was most recently running on.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tino Vázquez** (Tino Vázquez)
Original Date: 2016-11-16T15:10:13Z

---

This feature needs to be considered in vCenter

**Comment by rsmontero** [comment]
Check support in Sunstone

**Comment by paczerny** [comment]
Allow disk-saveas in undeployed and stopped, PRs (merge to master):
* src: https://github.com/OpenNebula/one-ee/pull/591
* deployment: https://github.com/OpenNebula/development/pull/1242
* docs: https://github.com/OpenNebula/docs/pull/1398
