### ISSUE TITLE
Document ec2 and azure contextualization

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1115]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 4840, https://dev.opennebula.org/issues/4840
Original Date: 2016-10-03

---

EC2 packages are not linked in the documetation. In the EC2 guide it links to the KVM packages:
http://docs.opennebula.org/5.0/advanced_components/cloud_bursting/ec2g.html#context-support

It would be a good idea to add two new guides to the contextualization guide, similar to KVM and vCenter, with information about EC2 context packages, and the Azure contextualization method (no package, just a boot script).

**Comment by vholer** [comment]
EC2/Azure cloudbursting deprecated.
