### ISSUE TITLE
Limit the number of snapshots a user can maintain on each of their VMs 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1116]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4842, https://dev.opennebula.org/issues/4842
Original Date: 2016-10-03

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Anton Todorov** (Anton Todorov)
Original Date: 2017-10-02T19:15:53Z

---

+1
The workaround implemented in addon-storpool is working for our customers but it is ugly hack so I'd be happy to get rid of it in the future.

Best Regards,
Anton Todorov

**Comment by christian7007** [comment]
Duplicated https://github.com/OpenNebula/one/issues/3769
