### ISSUE TITLE
Service VM "drain" before terminate 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1121]
---

Author Name: **Taavi K** (Taavi K)
Original Redmine Issue: 4851, https://dev.opennebula.org/issues/4851
Original Date: 2016-10-06

---

Currently there's no option in Sunstone for service VM-ms to gracefully finish serving clients before terminating VMs during auto-scaling down. 
I propose optional custom shutdown action in service template with attributes and step duration time (before VM termination).

For example I'd like to trigger external http get/post request to tell loadbalancer not to route new clients (and terminate their tcp connections) to VM-ms which are about to be terminated.

Sure, it all can be done through OneFlow API , but not within Sunstone.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-10-19T13:34:53Z

---

Hi,

Before moving this to the backlog, Couldn't this be done by hooking in the shutdown process of the VM? You can add a custom script to be executed when the VM enters the desired runlevel. Note also the timeout part is handled by the KVM driver or it could be added to the shutdown script.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Taavi K** (Taavi K)
Original Date: 2016-10-20T19:31:29Z

---

Those custom hooks would fall into same category as using OneFlow API.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-10-21T07:50:10Z

---

I was thinking about the init runlevel, related to context. Now we have an start script, so we could have a shutdown script.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Taavi K** (Taavi K)
Original Date: 2016-10-21T09:37:24Z

---

Yes, this would do the trick :)

Also would be nice to have extra ability to scale down node role by vm's individual values.
For example: "expression" : "ATT < 5" would power down ONLY nodes matching that expression.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Taavi K** (Taavi K)
Original Date: 2016-10-21T10:08:40Z

---

And also scale up if ANY node's value in role matches expression.
For example: in 3 node role "expression" : "ATT > 25" would trigger scale up if any node evaluates true.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Taavi K** (Taavi K)
Original Date: 2016-10-21T10:15:40Z

---

Forgot "ALL" criteria :)

So role scaling based on AVG, ANY and ALL expressions.

**Comment by tinova** [comment]
Relevant for OneFlow revamp
