### ISSUE TITLE
Check behavior of MAC/IP spoofing checkboxes for OpenvSwtich

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1126]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 4862, https://dev.opennebula.org/issues/4862
Original Date: 2016-10-10

---

As discussed in this thread:

https://forum.opennebula.org/t/vms-secondary-ip-address-isnt-working/2787/6

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
PRs for merge:
- https://github.com/OpenNebula/one/pull/1719
- https://github.com/OpenNebula/docs/pull/199
