### ISSUE TITLE
Reintroduce support for CentOS 6 in OpenNebula 5.2.0

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1134]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 4883, https://dev.opennebula.org/issues/4883
Original Date: 2016-10-27
Original Assignee: Jaime Melis

---

None

**Comment by vholer** [comment]
CentOS 6 is EoL next year, we should more focus on future RHEL/CentOS 8 support.
