### ISSUE TITLE
No field validation when modifying a VM template

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1145]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 4931, https://dev.opennebula.org/issues/4931
Original Date: 2016-11-18

---

Hello,

Step to reproduce:

1. use a browser in a language where decimal separator is not dot (french use comma)
1. change the *@CPU@* field of a VM template to *@0.5@*, with a dot.
1. click *@Update@* to save the modification
1. the *@CPU@* vanish from the template, checked with *@onetemplate show@*

Now try the following:

1. use a browser in a language where decimal separator is not dot (french use comma)
1. change the *@CPU@* field of a VM template to *@0,5@*, using the key *@decimal separator@* from the keypad, a comma is displayed by the browser
1. click *@Update@* to save the modification
1. the *@CPU@* is set to *@0.5@* in the template displayed by *@onetemplate show@*

The javascript is expecting a *@comma@* as decimal separator, this *@comma@* is then translated somewhere a *@dot@* to save it.

The problem is that there is no feedback, I found nothing in the logs.

I can even enter *@foobar@* as value in Sunstone.

I'm not a web developper but a solution could be to defining different "input types":https://www.w3.org/TR/html-markup/input.html, I see that the form only use *@text@*.

Regards.

**Comment by rsmontero** [comment]
Closing this and moving all the related work to #708
