### ISSUE TITLE
Enhance Showback attributes

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1146]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4933, https://dev.opennebula.org/issues/4933
Original Date: 2016-11-21

---

With at least:

   - Add a base cost to be calculated per hour

Memory to be expressed in GB to be implemented in other ticket (#3717)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Date: 2016-11-21T11:51:03Z

---

Also:

  - Lease from tagged networks (for instance, public network)

**Comment by tinova** [comment]
Covered by #1416 and #1095, closing
