### ISSUE TITLE
Reactivate LV's on rebooted hosts

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1152]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 4951, https://dev.opennebula.org/issues/4951
Original Date: 2016-12-15

---

LVs are not activated by default when using fs_lvm. These should be activated only on the host that will run the VM.

A hook to fix this is contributed in this forum topic:

https://forum.opennebula.org/t/issues-with-fs-lvm/3425

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
The activation is done by one-shot script `fs_lvm/activate`, triggered by an on-reboot cronjob.

Following PRs are ready to merge:
- https://github.com/OpenNebula/one/pull/1698
- https://github.com/OpenNebula/packages/pull/11
- https://github.com/OpenNebula/docs/pull/190
