### ISSUE TITLE
vCenter: Add user or group ID to the VM prefix

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1155]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 4963, https://dev.opennebula.org/issues/4963
Original Date: 2016-12-31

---

VM prefix can substitute @$i@ with the VM id. Add another variable with the user/group id or even the user/group name.

**Comment by rsmontero** [comment]
will develop this in #1973
