### ISSUE TITLE
honor DISPOSE=YES in market_mad/remotes/http/import

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1159]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 4975, https://dev.opennebula.org/issues/4975
Original Date: 2017-01-11

---

Hi,

I've implemented the marked_mad scripts for our storage but there are snapshots left on the storage because they are not cleaned up after import.

I think that this commented out code should be revisited: https://github.com/OpenNebula/one/blob/master/src/market_mad/remotes/http/import#L83

Probably the oned should run datastore_mad/rm after successful marketplace_mad/import. I am not sure that the marketplace_import is the right place to issue deletion of the exported image tough.

I'll disable the marketplace export in our default configuration until there is an update.

Kind Regards,
Anton Todorov

**Comment by atodorov-storpool** [comment]
Following https://forum.opennebula.org/t/migrating-vmdk-to-from-qcow2-disks-with-opennebula/6672
would like to note that the feature is still not usable by addon datastores...

**Comment by atodorov-storpool** [comment]
Pong :)

Needs to be implemented to have full integration in the addons.

**Comment by atodorov-storpool** [comment]
Pong

**Comment by atodorov-storpool** [comment]
Trying OpenNebula 5.13.80 (6.0-beta)
looks like this is not fixed...
There is sparse documentation regarding the VM Backups. It looks like this interface is used for them, but still can't figure out how to make something working without this...
