### ISSUE TITLE
onedb fsck does not detect discrepancy between UID / GID in database for resources (XML)

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1165]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 4984, https://dev.opennebula.org/issues/4984
Original Date: 2017-01-16

---

We detected a discrepancy between the UID / GID of a VM TEMPLATE in the XML (body), and the uid / gid columns in the database. There were uid / gid values of non-existing users / groups in the database for several VM TEMPLATES. This should be found by a onedb fsck operation. To avoid creating uid / gid in the database for non-existing users in the first place (that might come into existence later on in the cloud life) a check during database operations regaring uid / gid could be incorporated.

These discrepancies are only there for resources (VM Templates) that have been created with OpenNebula 4.4.0 AFAICT (I cheched unix epoch times of VM Template and onedb upgrade (db_versioning table)).

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/2207)
- [docs](https://github.com/OpenNebula/docs/pull/2348)
