### ISSUE TITLE
addar allows to create the same AR template several times

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1171]
---

Author Name: **Alvaro Simon** (Alvaro Simon)
Original Redmine Issue: 4993, https://dev.opennebula.org/issues/4993
Original Date: 2017-01-24

---

Hi

I don't know if this is done on purpose, but we found that addar command allows to include the same AR template several times within the same VNET. It seems that OpenNebula does not detect if the AR configuration already exits in the VNET database and only increases the id number. That could be confusing for the admin, if for some reason, the same AR appears several times within the VNET conf. The algorithm should make a quick check if the same AR (IP, MAC, lease number) it's already included and refuse to include the same AR or at least show a warning message.

Cheers and thansk!
Alvaro

**Comment by rsmontero** [comment]
Closing, this is the expected behavior. Several AR could be added with the same IP addresses but different VLANs for example or bridges.
