### ISSUE TITLE
Migrate VM to different ESX clusters

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1172]
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 4997, https://dev.opennebula.org/issues/4997
Original Date: 2017-01-27

---

Currently this migrate operation can only be performed from vCenter and it should be added to OpenNebula.

**Comment by Semedi** [comment]
duplicated #1371
