### ISSUE TITLE
Cloning an imported VM from vCenter will result in a VM that cannot be imported again

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1173]
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 4998, https://dev.opennebula.org/issues/4998
Original Date: 2017-01-27

---

This is a current limitation. Though the work around is instantiate from templates and import the resulting VMs, instead of cloning already imported VMs, this behavior should be added to OpenNebula.

**Comment by rsmontero** [comment]
to be solved as part #2016
