### ISSUE TITLE
add vmdk images into VM folders

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1174]
---

Author Name: **Keith Harding** (Keith Harding)
Original Redmine Issue: 5002, https://dev.opennebula.org/issues/5002
Original Date: 2017-02-01

---

Currently creating an "empty disk image" placed the image in the root of the datastore.
Can an option be added to allow the disk to be created in a specific VM folder? alternatively allow selection of a VM to attach the disk to, so that the disk creation process knows which VM folder the disk should reside in.
In a multi tenant environment we cant have disks being dropped all over the place, they need to be associated into specifc VM folders alongside the vmx files etc.

**Comment by tinova** [comment]
Will be addressed as part of #2762.
