### ISSUE TITLE
Editing ACLs on-the-fly in Sunstone for vOneCloud

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1179]
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 5019, https://dev.opennebula.org/issues/5019
Original Date: 2017-02-11

---

As requested in:
https://support.vonecloud.com/hc/en-us/community/posts/115000396705-Couple-of-Newbie-Questions

**Comment by rsmontero** [comment]
duplicate of #721
