### ISSUE TITLE
EyeOS spice web client as spice client in Suntone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1182]
---

Author Name: **Xavier Peralta** (Xavier Peralta)
Original Redmine Issue: 5025, https://dev.opennebula.org/issues/5025
Original Date: 2017-02-15

---

Hi, I've discovered this spice web client that has less errors than spice-html5. It works as spice-html5, with a websockify instance. For us it would be useful to be able to press "special characters" as backslash, pipe, etc.

https://github.com/eyeos/spice-web-client

Thanks,

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2017-02-20T15:04:05Z

---

+1

It could be great to have a good graphical console.

Regards.

**Comment by tinova** [comment]
This can be revisit in relation on #2312

**Comment by tinova** [comment]
project doesn't seem to be maintained
