### ISSUE TITLE
VM Instantiate as Persistent - allow disk size change

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1185]
---

Author Name: **Kristian Feldsam** (Kristian Feldsam)
Original Redmine Issue: 5030, https://dev.opennebula.org/issues/5030
Original Date: 2017-02-17

---

Hello, should be fine to able resize disk also when instantiating VM as persistent. Thank you.

**Comment by rsmontero** [comment]
We want to revisit the save_as and instantiate to persistent feature. Adding to 5.6 to consider this request

**Comment by rsmontero** [comment]
Related to #1327

**Comment by Snowmanko** [comment]
Great! Looking forward to see this implemented in 5.6/8 [()](https://forum.opennebula.org/t/persistent-image-sizing-on-vm-creation/5942)

**Comment by paczerny** [comment]
I think this one already works in 6.0 (and master)
