### ISSUE TITLE
Limit system disk size on cloud view

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1187]
---

Author Name: **Vy Nguyen Tan** (Vy Nguyen Tan)
Original Redmine Issue: 5033, https://dev.opennebula.org/issues/5033
Original Date: 2017-02-19

---

Hello,

By default system disk limit in range from system image size to 500GB + system image size. I think it'd be better to limit maximum system disk at system disk quota instead.

**Comment by rsmontero** [comment]
There was a bug related to this recently solved, it should work better now.
