### ISSUE TITLE
Add option to create snapshots without memory dumps in vCenter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1188]
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 5036, https://dev.opennebula.org/issues/5036
Original Date: 2017-02-20

---

Currently, VM snapshots performed using the CreateSnapshot_Task has the memory option set to true which dumps the memory state into the snapshot. That memory dump consume time and resources so it would be good to have the chance to create snapshots without memory. If no memory dump would be created, then a disk snapshot feature would be better to have in vCenter.

This has been mentioned in the vOneCloud forum: https://support.vonecloud.com/hc/en-us/community/posts/115000425929-snapshot-functionality

**Comment by tinova** [comment]
Support from oned needed

**Comment by tinova** [comment]
Needs documentation

**Comment by carloshm91** [comment]
[DOC] https://github.com/OpenNebula/docs/pull/980
