### ISSUE TITLE
When instantiating a VM, show only datastores that can be accesible to user's groups or have the chance to add VCENTER_DATASTORE to groups

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1189]
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 5037, https://dev.opennebula.org/issues/5037
Original Date: 2017-02-20

---

This has been discussed here: https://support.vonecloud.com/hc/en-us/community/posts/115000403565-Group-based-variable-VCENTER-DATASTORE-?page=1

**Comment by rsmontero** [comment]
Already implemented using datastores natively
