### ISSUE TITLE
Differentiate created templates on vCenter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1193]
---

Author Name: **Adrian Menendez** (Adrian Menendez)
Original Redmine Issue: 5053, https://dev.opennebula.org/issues/5053
Original Date: 2017-03-09

---

When create a template making a vm persistent, add an attribute to know if has alredy been created on vCenter (vm has been deleted) or is still only in OpenNebula. Another option is to add an attribute while is waiting and delete it when it's created, so all of the created templates have the same attributes and the only different ones are those who has been created making a vm as persistent.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Jaime Melis** (@jmelis)
Original Date: 2017-06-08T09:42:05Z

---

Can you please elaborate? We are having difficulties understanding this issue.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Adrian Menendez** (Adrian Menendez)
Original Date: 2017-06-09T10:21:46Z

---

When a vm is deployed as persistent, OpenNebula creates a template too. Meanwhile the vm is up and running, the template is only on OpenNebula, just a registry, not a real vCenter template. It would be interesting to be able to differentiate which of them really exists on vCenter.

**Comment by tinova** [comment]
Check if VM Template in OpenNebula is locked until the vCenter VM is converted to VM Template. If not, lock it.

With this functionality, locked VM Templates are the ones not present in vCenter.

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4394

[DOC]
* https://github.com/OpenNebula/docs/pull/1064
