### ISSUE TITLE
VM USER_TEMPLATE messed up

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1195]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 5057, https://dev.opennebula.org/issues/5057
Original Date: 2017-03-12

---

Hi,

Not sure is this bug or feature, but it is sort of confusing so I am classifying it as bug.

How to reproduce:
1. Instantiate a VM
2. Goto VM info
3. Delete all available Attributes (on centos7.2 I have HYPERVISOR and LOGO)
* The Attributes will be populated with the data form the VM TEMPLATE
4. Editing any of the attributes or add new attribute will update the USER_TEMPLATE with TEMPLATE plus the changes.

Expected behavior:
- Empty Attributes with option/interface to create a new one.

Kind Regards,
Anton Todorov

**Comment by rsmontero** [comment]
It seems this solved, at least we cannot reproduce it
