### ISSUE TITLE
Allow the definition of thinness or thickness of vCenter VM disks

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1200]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5072, https://dev.opennebula.org/issues/5072
Original Date: 2017-03-22

---

Using an attribute like VCENTER_PROVISIONING_TYPE. Study the implications for OPENNEBULA_MANAGED yes and no disks.

**Comment by tinova** [comment]
Only at creation time.

**Comment by carloshm91** [comment]
PR 
* [ONE] https://github.com/OpenNebula/one/pull/3876

**Comment by tinova** [comment]
Implemented by VCENTER_DISK_TYPE, only valid for image (VMDK) creation
