### ISSUE TITLE
Wizard dialog mangles information input in CLI or Advance dialog

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1201]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5076, https://dev.opennebula.org/issues/5076
Original Date: 2017-03-23

---

Needs to append instead of update

**Comment by rsmontero** [comment]
Not enough details, cannot reproduce
