### ISSUE TITLE
Allow system snapshots in poweroff state

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1205]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5086, https://dev.opennebula.org/issues/5086
Original Date: 2017-03-29

---

At least in vCenter.

Evaluate KVM.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Anton Todorov** (Anton Todorov)
Original Date: 2017-05-16T08:25:48Z

---

+1

As we are using only the interface(to do disk snapshots only) an option to enable them is welcome.

BR,
Anton

**Comment by christian7007** [comment]
Duplicated https://github.com/OpenNebula/one/issues/5304
