### ISSUE TITLE
custom vnet driver using ovswitch is not possible

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1209]
---

Author Name: **Edouard Bourguignon** (Edouard Bourguignon)
Original Redmine Issue: 5094, https://dev.opennebula.org/issues/5094
Original Date: 2017-04-04

---

I tried to add a new custom vnet driver. Everything is ok when hotplugging the interface to a running VM. But you have to modify the attach_nic script (which is I guess a bad idea? since it's outside of the vnet driver scope).

But when a new vm is DEPLOYed, ovswitch vn_mad type is hardcoded in the src/vmm/LibVirtDriverKVM.cc, meaning that you won't have the virtualport line in the libvirt XML vm definition. So the port of the VM won't be attached to the OVS bridge. And since it's hardcoded in the LibVirtDriverKVM.cc, you can't use custom drivers to deal with OVS type port. Am I wrong ?

It should be great if we can deal with OVS inside custom drivers.

ps: forum discussion is here https://forum.opennebula.org/t/custom-vnet-driver/4046

**Comment by rsmontero** [comment]
This will be revisited with the new OpenVswitch enhancements e.g. #792
