### ISSUE TITLE
context script to activate swap when attaching swap disk

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1210]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 5095, https://dev.opennebula.org/issues/5095
Original Date: 2017-04-04

---

IMO good approach could be to add an udev rule on disk add to call context script.

BR,
Anton

**Comment by vholer** [comment]
Similar to OpenNebula/addon-context-linux#85, we may cover this requirement as well. Let's track this problem in that issue and close this one.
