### ISSUE TITLE
Ceph mkimage fails with incompatible rbd features

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1222]
---

Author Name: **Gerben Meijer** (Gerben Meijer)
Original Redmine Issue: 5116, https://dev.opennebula.org/issues/5116
Original Date: 2017-04-19
Original Assignee: Vlastimil Holer

---

mkimage in the Ceph TM driver does an 'rbd map' to create a swap filesystem.

This does not work with all kernels; for example:

```
[2451939.802702] rbd: image one-10-3-0: image uses unsupported features: 0x38

```

A possible workaround is to depend on libguestfs and use guestfish to create it. Basic example:

```
    if [ "$FSTYPE" = "swap" ]; then
        export LIBGUESTFS_BACKEND=direct
        ( echo set-attach-method appliance
          echo add-drive /dev/null
          echo config -set drive.hd0.file=rbd:$RBD_SOURCE
          echo run
          echo mkswap /dev/sda label:swap ) | $SUDO /usr/bin/guestfish
    fi

```

Note that this will also require the addition of /usr/bin/guestfish to sudoers.

I think it's the most elegant solution since it becomes kernel and distro independent.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Roy Keene** (Roy Keene)
Original Date: 2017-04-19T16:43:57Z

---

A simpler solution is to use "qemu-nbd" to create an NBD that corresponds to the RBD.  If QEMU is compiled with RBD support then the QEMU tools have the ability to map RBD devices.

Failing that, it can be done by creating a sparse file and writing the header to it, then reading that header into a new RBD image:

```
(
        tmpfile="$(mktemp)" && \
                dd if=/dev/zero of="${tmpfile}" bs=$[1024*1024] seek=$[${SIZE} - 1] count=1 2>/dev/null && \
                mkswap "${tmpfile}" && \
                dd if="${tmpfile}" bs=$(getconf PAGESIZE) count=1 2>/dev/null | rbd import - $RBD && \
                rbd resize --size ${SIZE}M $RBD
        rm -f "${tmpfile}"
)

```

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Roy Keene** (Roy Keene)
Original Date: 2017-04-19T18:46:08Z

---

Also attached is a wrapper script called "mkswap-qemu" which uses "qemu-img" to handle both RBD and QCOW2 (and any other format QEMU supports, if properly extended) and run "mkswap"

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2017-08-28T15:55:22Z

---

I'm marking this to be done in the next major release.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tobias Rehn** (Tobias Rehn)
Original Date: 2017-09-21T07:08:05Z

---

We are also experiencing this issue also. I don't think that it is a good idea to create the swap file locally. For virtualization host with small HDDs such a way can fill up the HDD and lead to further issues.

We are using the following workaround:

```
if [ "$FSTYPE" = "swap" ]; then
    $SUDO $RBD map $RBD_SOURCE --image-feature layering || exit \$?
    $SUDO $MKSWAP -L swap /dev/rbd/$RBD_SOURCE
    $SUDO $RBD unmap /dev/rbd/$RBD_SOURCE
fi

```

By only using the rbd feature "layering" it works without any issues on older kernels like 3.10 (rhel7 / centos7). Most of the newer features like "deep-flatten", "fast-diff" or "object-map" are only available in newer kernels. Even the latest mainline kernel 4.13 does not support all features. This is because the krbd features are lacking behind the features of rbd.

When using latest ceph luminious you want to use all new features for your images as these have enormous speed enhancements for clones, etc. But you will never ever clone a swap disk - so layering is enough for this type of storage disk.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tobias Rehn** (Tobias Rehn)
Original Date: 2017-09-21T07:10:36Z

---

I had a failure in my workaround:

```
MKIMAGE_CMD=$(cat <<EOF
    export PATH=/usr/sbin:/sbin:\$PATH

    if [ "$FSTYPE" = "swap" ]; then
        $RBD create $FORMAT_OPT $RBD_SOURCE --size ${SIZE} --image-feature layering || exit \$?
        $SUDO $RBD map $RBD_SOURCE || exit \$?
        $SUDO $MKSWAP -L swap /dev/rbd/$RBD_SOURCE
        $SUDO $RBD unmap /dev/rbd/$RBD_SOURCE
    fi

    $RBD create $FORMAT_OPT $RBD_SOURCE --size ${SIZE} || exit \$?

EOF
)

```

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tobias Rehn** (Tobias Rehn)
Original Date: 2017-09-21T08:26:48Z

---

After some further testing I have come the result that I see no advantage from distinguishing between swap or normale volatile disk. I thought the swap disk were automatically mounted but that is not the case and I see no advantage. So we working with the following:

```
MKIMAGE_CMD=$(cat <<EOF
    export PATH=/usr/sbin:/sbin:\$PATH
    $RBD create $FORMAT_OPT $RBD_SOURCE --size ${SIZE} || exit \$?
EOF
)

```

**Comment by vholer** [comment]
Following PR https://github.com/OpenNebula/one/pull/1677 introduces changes to avoid using `rbd map`, as the kernel and user-space Ceph versions usually differ.
