### ISSUE TITLE
Option to disable instantiate_pers switch

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1223]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5117, https://dev.opennebula.org/issues/5117
Original Date: 2017-04-20

---

Sunstone views config must have option to disable instantiate_pers switch

**Comment by rsmontero** [comment]
This is implemented and available as a configuration option in yamls:

`# True to show the option to make an instance persistent
    instantiate_persistent: true
`
