### ISSUE TITLE
Allow SCHEDULED ACTIONS in VM Templates

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1224]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5118, https://dev.opennebula.org/issues/5118
Original Date: 2017-04-20
Original Assignee: Abel Coronado

---

Also in Sunstone at instantiation time, and at VM creation time

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Need merging
