### ISSUE TITLE
OneGate Server package is not provided needed gems or install_gems script

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1225]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5122, https://dev.opennebula.org/issues/5122
Original Date: 2017-04-21
Original Assignee: Vlastimil Holer

---

I use Ubuntu 16.04, after installation opennebula-flow package, it is not runs properly.

This steps sloves problem fully:

    apt install opennbula
/usr/share/one/install_gems
apt remove opennbula

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2017-08-24T14:03:34Z

---

@install_gems@ is right now packaged in @opennebula-tools@. We will review where is the best place to package the script in the next release. Meanwhile you can do as stated or install @opennebula-tools@ in that machine.

**Comment by vholer** [comment]
OneGate package now depends on `opennebula-rubygems` package which brings all the packaged Ruby gems dependencies. Fixed by #2799.
