### ISSUE TITLE
addon-context-linux: Add openSUSE support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1234]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5141, https://dev.opennebula.org/issues/5141
Original Date: 2017-05-04
Original Assignee: kvaps kvaps

---

Hi, I added support for openSUSE for rpm package and documentation:
https://github.com/OpenNebula/addon-context-linux/pull/75
https://github.com/OpenNebula/docs/pull/95

**Comment by vholer** [comment]
Already merged.
