### ISSUE TITLE
Host Monitoring does not fail if probe does not come back

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1236]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5146, https://dev.opennebula.org/issues/5146
Original Date: 2017-05-08

---

For instance, if IM drivers run outs of threads, host never goes into ERROR state, and thus prevents the correct use of hooks.

Take care of FT hook, triggering it on this error might not be the best path.

**Comment by vholer** [comment]
PR to merge: https://github.com/OpenNebula/one/pull/2041
