### ISSUE TITLE
Disable VM -> Templates click to show datatable

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1237]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5147, https://dev.opennebula.org/issues/5147
Original Date: 2017-05-08

---

Only honor clicking on labels.

That is, never show the full datatable with VM Templates of all labels, but rather only VM Templates of specific labels.

Make it configurable in .yaml files

**Comment by rsmontero** [comment]
This is now the default behavior
