### ISSUE TITLE
Hybrid VMs in poweroff --> terminate are not removed from public cloud provider

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1243]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5164, https://dev.opennebula.org/issues/5164
Original Date: 2017-05-22

---

Since they are PUBLIC_CLOUD VMs they lack epilog phase.

**Comment by rsmontero** [comment]
A possible solution would be to move the VM to shutdown from poweroff for these hybrid VMs

**Comment by al3xhh** [comment]
Public cloud integration has been deprecated in flavor of oneprovision, closing.
