### ISSUE TITLE
sunstone lacks management of VM's security groups

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1244]
---

Author Name: **Arnaud Abélard** (Arnaud Abélard)
Original Redmine Issue: 5167, https://dev.opennebula.org/issues/5167
Original Date: 2017-05-23

---

While the user is allowed to choose security groups on VM creation, sunstone doesn't provide any way for the user to view or manage those security groups after creation. The user only has access to the network's security groups, not the VM's.

On the network tab of the VM, sunstone should allow users to add/remove/view security groups explicitely applied to the VM (if the current view's definition allows it, of course).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Arnaud Abélard** (Arnaud Abélard)
Original Date: 2017-05-23T13:18:23Z

---

actually, I just noticed it is possible to view the security groups affected to a NIC by clicking on the ">" by the NIC, but it is not possible to manage them.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Arnaud Abélard** (Arnaud Abélard)
Original Date: 2017-05-23T14:21:20Z

---

There is actually a way to add/remove security groups from sunstone: removing the NIC and adding it again, expand the advanced configuration, scroll all the way down and set the security groups again. It is of course not user friendly at all and there might be a risk of losing the current ip or/and mac address.

**Comment by rsmontero** [comment]
Sunstone supports all the current operations related to SG
