### ISSUE TITLE
Network creation dialog should feature a dropdown

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1247]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5177, https://dev.opennebula.org/issues/5177
Original Date: 2017-06-05
Original Assignee: Javi Fontan

---

Filled with the bridges information of the KVM hosts (makes sense in vCenter as well) coming from the monitoring probes

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tino Vázquez** (Tino Vázquez)
Original Date: 2017-07-21T10:05:29Z

---

Monitoring probes need to return host bridges

**Comment by rsmontero** [comment]
Duplicates #1199
