### ISSUE TITLE
libfs.sh function get_destination_host() to check bridge host availability

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1248]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 5181, https://dev.opennebula.org/issues/5181
Original Date: 2017-06-08

---

Besides the round-robin the function should check is the bridge host available to do the task.

The simplest resolution is to issue few ICMP pings and if there is no response to try the next one...

More advanced should be to call a script in variable CHECK_BRIDGE=/path/to/check/script with the bridge host as argument.

This way each datastore driver can implement own check-script that do additional testss for the services and return ok more reliable.

For example if it is the SDS storage and the software has issue on the given host, the host will answer on pings but the script should check is the SDS service up too...

I 'll try to draft a pull request but not sure when will have the time to do it though.

Best Regards,
Anton Todorov

**Comment by xorel** [comment]
get_destination_host now filter out a disabled, error and power-off hosts (https://github.com/OpenNebula/one/issues/1136)
