### ISSUE TITLE
MarketPlace for vCenter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1249]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5183, https://dev.opennebula.org/issues/5183
Original Date: 2017-06-08

---

Images downloaded from the marketplace are not useful unless we add the chance in OpenNebula to create a VM from scratch using an empty vcenter template. Add empty vcenter template when importing clusters so they can be used as a skel for new VMs.

**Comment by tinova** [comment]
Needs testing & documentation

**Comment by tinova** [comment]
Testing done

Needs documentation
