### ISSUE TITLE
Support Dynamic Resize in vCenter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1250]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5184, https://dev.opennebula.org/issues/5184
Original Date: 2017-06-08

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-06-21T15:27:31Z

---

This also includes "external" resizes perform directly through the vCenter interface.

**Comment by tinova** [comment]
Duplicated by #1660 and #1542
