### ISSUE TITLE
Azure driver auth system

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1251]
---

Author Name: **Sergio Semedi** (Sergio Semedi)
Original Redmine Issue: 5189, https://dev.opennebula.org/issues/5189
Original Date: 2017-06-09
Original Assignee: Sergio Semedi

---

Will be nice to change azure_driver auth to work in a similar way of ec2.

Storing credentials directly on disk is not secure.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-08-01T11:47:32Z

---

Needs to update documentation

**Comment by rsmontero** [comment]
review documetation

**Comment by Semedi** [comment]
#415
[Doc](https://github.com/OpenNebula/docs/commit/688c97f3e87112d7958bb7d9059ce2c3dccdef3a)
