### ISSUE TITLE
ON reports successful monitoring of KVM-HV's, although it fails due to ulimit being hit

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1253]
---

Author Name: **Christian Wehrlin** (Christian Wehrlin)
Original Redmine Issue: 5199, https://dev.opennebula.org/issues/5199
Original Date: 2017-06-22
Original Assignee: Vlastimil Holer

---

If you have a KVM-Hypervisor in your setup, that has reached, or is about to reach the ulimit, OpenNebula will probably fail trying to do the run_probes, but instead of throwing an error, it will simply report that the machine was successfully monitored.

While trying to open a remote shell manually, you'll get the Error:

@Resource temporarily unavailable@

But in the oned.log, all you just see is basically something like

@Wed Jun 21 12:36:54 2017 [Z0][InM][D]: Host node18.blafasel (23) successfully monitored.@

Of course, the quick fix is to increase the ulimits on the Hypervisor to more suitable values, nonetheless, it should be expected for OpenNebula to report an issue when trying to remote-execute run_probes

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Vlastimil Holer** (Vlastimil Holer)
Original Date: 2017-10-30T10:10:07Z

---

Hello Christian,

I have tried to reproduce the problem with ONE 5.4, but couldn't. Do you have any chance to confirm it doesn't happen for you on 5.4?

What kind of resources are you limiting?

Best regards,
Vlastimil Holer

**Comment by jmelis** [comment]
Closing because we haven't been able to reproduce it. If you can provide further information please address it in forum.opennebula.org
