### ISSUE TITLE
libvirt 2.0 xml metadata

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1254]
---

Author Name: **Denis LDV** (Denis LDV)
Original Redmine Issue: 5201, https://dev.opennebula.org/issues/5201
Original Date: 2017-06-23

---

Not sure it is important or not
I upgraded node and now metadata section in xml is empty 

Centos 7

*before upgrade:*

```
virsh dumpxml one-XXX
...
<metadata>
    <system_datastore><![CDATA[/var/lib/one//datastores/XXX/XXX]]></system_datastore>
</metadata>
...


1. virsh version
Compiled against library: libvirt 1.2.17
Using library: libvirt 1.2.17
Using API: QEMU 1.2.17
Running hypervisor: QEMU 1.5.3




```
*after upgrade:*
```


1. virsh dumpxml one-XXX
...
<metadata/>
...

1. virsh version
Compiled against library: libvirt 2.0.0
Using library: libvirt 2.0.0
Using API: QEMU 2.0.0
Running hypervisor: QEMU 2.6.0



```

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2017-08-23T16:54:26Z

---

A prefix must be added to all the tags in metadata.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-10-26T07:47:38Z

---

As discussed with Javi Fontan and Anton Todorov during the ONE EU CONF 2017: There is a clear need for metadata support in libvirt XML's created by OpenNebula. Especially the "NAME" of the virtual machine should be present in the libvirt XML. External tools (for example to do Disaster Recovery) can than make a mapping between ONE-ID and Name. Libvirt allows for Metadata to be added: https://libvirt.org/formatdomain.html#elementsMetadata

A mapping prooposal:

OpenNebula VM "NAME" => libvirt Title
OpenNebula VM Description => libvirt Description
OpenNebula VM Metadata => libvirt Metadata

**Comment by hydro-b** [comment]
We are in the process of migrating to telegraf (libvirt plugin based on PR 3592) for collecting VM metrics and sending them to influxdb instead of ONE. Having a "human readable" aka "VM NAME" send with those metrics would be really valuable.

**Comment by christian7007** [comment]
Duplicated #2205
