### ISSUE TITLE
Add NSX-T support to OpenNebula's vCenter drive

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1256]
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 5210, https://dev.opennebula.org/issues/5210
Original Date: 2017-07-03

---

As requested here in the forum: https://forum.opennebula.org/t/vmware-nsx-t-support/4530

**Comment by mouyaq** [comment]
Added basic support into OpenNebula 5.8.4 to NSX-T Opaque Networks. 
Support to:
Import Opaque Networks
Import Templates with Opaque Networks
Import Wild VMs with Opaque Networks
Attach/Detach Opaque Network nics
Poweron/Poweroff.. Instances with Opaque Networks

**Comment by mouyaq** [comment]
We're working to support more features in next releases.
