### ISSUE TITLE
Add cross-cluster checks for oneimage clone.

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1258]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5212, https://dev.opennebula.org/issues/5212
Original Date: 2017-07-04

---

oned should no allow you to clone images from datastores in different clusters. As reported in #5208

**Comment by rsmontero** [comment]
After discussing this, we thing this is a nice feature to have as it is interested to move files from a DS to another one without the need of both of them to be on the same cluster (e.g. for scheduling reasons)
