### ISSUE TITLE
[spice] add native remote-viewer (virt-viewer) support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1262]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5231, https://dev.opennebula.org/issues/5231
Original Date: 2017-07-12

---

Remote-viewer this is part of virt-viewer. It is native software for connecting via spice protocol.
And it is really beautiful: It is support multiple monitors, securing, usb passtrough and have very good speed. It can be used for VNC too.

It is already done by oVirt and Proxmox,
Both uses spiceproxy for proxyng spice connections outside of network (it is simpe configured squid)
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.5/html/Installation_Guide/chap-Proxies.html

I want to have the support in the OpenNebula too.
The main think is the next:

- Create vm with spice support
- Go to the sunstone, and click "connect to the vm"
- The folowing file will be downloaded:

console.vv (example)
```
[virt-viewer]
type=spice
host=10.34.63.223
port=5905
proxy=http://10.36.20.1:3128
password=Ak9XhlMF/A3W
tls-port=5906
fullscreen=1
title=wxp-apt-53011:%d - Press SHIFT+F12 to Release Cursor
enable-smartcard=0
enable-usb-autoshare=1
delete-this-file=1
usb-filter=-1,60186,10000,256,1|-1,1118,245,-1,1|-1,1133,2245,-1,1|-1,1133,2242,5,1|8,-1,-1,-1,1|7,-1,-1,-1,1|-1,-1,-1,-1,0
tls-ciphers=DEFAULT
host-subject=O=rhev.lab.eng.brq.redhat.com,CN=10.34.63.223
ca=-----BEGIN CERTIFICATE-----\nMIIEMDCCAxigAwIBAgICEAAwDQYJKoZIhvcNAQEFBQAwajELMAkGA1UEBhMCVVMxJDAiBgNVBAoT\nG3JoZXYubGFiLmVuZy5icnEucmVkaGF0LmNvbTE1MDMGA1UEAxMsamItcmhldm0zNC5yaGV2Lmxh\nYi5lbmcuYnJxLnJlZGhhdC5jb20uNDgyNDUwIhcRMTQwMzAzMTYwMzQyKzAwMDAXDTI0MDMwMTE2\nMDM0MlowajELMAkGA1UEBhMCVVMxJDAiBgNVBAoTG3JoZXYubGFiLmVuZy5icnEucmVkaGF0LmNv\nbTE1MDMGA1UEAxMsamItcmhldm0zNC5yaGV2LmxhYi5lbmcuYnJxLnJlZGhhdC5jb20uNDgyNDUw\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCiO9Q+VlWrd8Ms7UNU8xAVtqmzoV8U/mV7\nRio6rAEhUHeEdDKZWmPZhgn3steucceSUeJcII47JqWZz67AK6nauDLC7GaWAvy0YTm1hy9w6Ybd\n23GQv3yWyD3fNqyIJsNV1FP1qJcG2EyttvuBG8+IHtlzkLZt52DwEKYSR2OnEwCOSEfcW0njsvOW\nwFTLIlKcN9rLEIjNSK94eGoHyKXG9nEe3o9vapZtxlf+2tCTYHgVfssWiGbxpYUbM6IYxvfQaBkj\nmCHGDvfuoZWXoQ19rJJb4L2jComHvtdf2diNP1FBvio9wSIw4nb/yl1YpYcihR3dPuiQa6CHfb4p\nxGwpAgMBAAGjgdswgdgwHQYDVR0OBBYEFAnb71GWXghUTTaEZ3Z1kWEIohb9MIGVBgNVHSMEgY0w\ngYqAFAnb71GWXghUTTaEZ3Z1kWEIohb9oW6kbDBqMQswCQYDVQQGEwJVUzEkMCIGA1UEChMbcmhl\ndi5sYWIuZW5nLmJycS5yZWRoYXQuY29tMTUwMwYDVQQDEyxqYi1yaGV2bTM0LnJoZXYubGFiLmVu\nZy5icnEucmVkaGF0LmNvbS40ODI0NYICEAAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\nAQYwDQYJKoZIhvcNAQEFBQADggEBAJYxITlXbt3/yQhSuNZLDwBRObkeQGupcH+s08Ygu4q8W6UK\n3k0AXY73g3w5xzFDKk7T31r9SHSGUXY2BBoNkjomUmrmS8jw5ahu40JyAAk7RV8wUjCuIEHIMzt6\naziWCiaro3MKVZ0Oy9ym5cfL9CHItPf0PY0fmMhI1GV9dldHM/7RLoAd8cyIKiJgQc7+4wJgou1Z\n2l7O0u1meCjw+GugmBAe++nBJO8p3EoJJxqZc9K6gZ99vXZWjJ54pbEktUIezyFLE8L10Ux+Zzoj\nFf4dE0/q5BCbeK1uKLKOoqxcaO9Y0PA9FL1TPyhHNVk2zaFCosrvclmZI6SVvA0QpvA=\n-----END CERTIFICATE-----\n
toggle-fullscreen=shift+f11
release-cursor=shift+f12
secure-attention=ctrl+alt+end
secure-channels=main;inputs;cursor;playback;record;display;usbredir;smartcard

```

- After you openned this file via remote-viewer it will be connected to the vm

More about syntax here:
https://github.com/SPICE/virt-viewer/blob/master/man/remote-viewer.pod

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-07-12T11:19:34Z

---

For now I deveoped this script for todo this:
https://github.com/kvaps/one-connect

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2017-08-21T13:57:42Z

---

+1

Hello,

It could be cool to have a *@onevm console@* tool with configurable utilities to use (ssvncviewer, spicy, …) that can pass by the websocketproxy since the hypervisors are not always reachable by clients (like in our setup).

Regards.

**Comment by kvaps** [comment]
This feature request is still active

**Comment by baby-gnu** [comment]
We are still interested in this feature ;-)

**Comment by RussianNeuroMancer** [comment]
Any progress on this? We are also very interested.

**Comment by lillypad** [comment]
Also interested.

**Comment by rsmontero** [comment]
We've scheduled this for 5.12. Thanks for the feedback!

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4626 
- development: OpenNebula/development/pull/946
