### ISSUE TITLE
NoVNC is fully unuseful with live resizing of desktop (spice)

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1263]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5232, https://dev.opennebula.org/issues/5232
Original Date: 2017-07-12

---

Step for reproduce:
- Setup VM using spice
- Install SPICE guest agent inside
- Open Console

You will see that desktop resolution will endlessly change, and you can not do anything via console.
This is because the spice tries to adjust the resolution to the client window but this is have no fixed size.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2017-08-21T10:18:41Z

---

Hello,

It may be related to #5025 which seems to be a better spice web client:

> Full QXL Support of the entire spice protocol, including clipping, masking, scaling etc (accelerated mode)

Regards.

**Comment by RussianNeuroMancer** [comment]
In OpenNebula 5.10.1 integrated Spice client is still unusable with desktops that support Spice dynamic resolution, such as Gnome Shell and KDE. Tested on (K)Ubuntu 19.10.

**Comment by sbbarragan** [comment]
OpenNebula 5.14 will bring support for Guacamole. SPICE through noVNC will be maintained for backwards compatiblity, but not new developments will be perfomed
