### ISSUE TITLE
recover --retry does not work for a vm that failed to resume from undeploy

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1264]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5234, https://dev.opennebula.org/issues/5234
Original Date: 2017-07-12

---

None

**Comment by al3xhh** [comment]
I have recreated it following these steps:

- Download an Alpine Linux from Marketplace.
- Instantiate it.
- Wait until the VM is in **running** state.
- Undeploy the VM.
- Wait until the VM is in **undeployed** state.
- Make the resume fail (deleting the disk.0)
- Wait until the VM is in **failure** state.
- Execute `onevm recover --delete`.

After doing those steps, everything worked correctly.

Closing it, reopen if it's needed.
