### ISSUE TITLE
vCenter Resource pool tab in host

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1269]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5240, https://dev.opennebula.org/issues/5240
Original Date: 2017-07-13

---

Also, expose the Resource Pool functionality in the VM Template and VM instantiation dialogs

**Comment by carloshm91** [comment]
[DEV]
* https://github.com/OpenNebula/development/pull/829

[ONE]
* https://github.com/OpenNebula/one/pull/4108

[DOC]
* https://github.com/OpenNebula/docs/pull/913
