### ISSUE TITLE
Update gemfile to require rack > 2.0

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1273]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5244, https://dev.opennebula.org/issues/5244
Original Date: 2017-07-13
Original Assignee: Abel Coronado

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-07-13T14:58:25Z

---

Support for rack 1 should be preserved

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Abel Coronado** (Abel Coronado)
Original Date: 2017-09-05T14:07:54Z

---

```
if RUBY_VERSION < '2.4.0'
    gem 'rack', '< 2.0.0'
else
    gem 'rack', '> 2.0.0'
end

```

**Comment by rsmontero** [comment]
Should we add a note on compatibility guide to run install-gems after the upgrade?

**Comment by vholer** [comment]
> Should we add a note on compatibility guide to run install-gems after the upgrade?

Step with `install_gems` is part of all deployment procedures (fresh new installs or upgrade). I don't think it's necessary to specify it explicitly in the compatibility, but we may tell the Debian* packages are now in conflict with following packages:

- thin
- ruby-rack
- ruby-rack-protection
- ruby-sinatra

This is something good to know before upgrade. I'll update the docs...

**Comment by vholer** [comment]
Fixed in https://github.com/OpenNebula/docs/pull/484. Closing.
