### ISSUE TITLE
Update FT hook flags

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1275]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5250, https://dev.opennebula.org/issues/5250
Original Date: 2017-07-18

---

In http://docs.opennebula.org/5.4/advanced_components/ha/ftguide.html

**Comment by tinova** [comment]
https://github.com/OpenNebula/docs/pull/2294
