### ISSUE TITLE
Add OneFlow mention to Cloud Servers Authentication guide

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1276]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5252, https://dev.opennebula.org/issues/5252
Original Date: 2017-07-18

---

http://docs.opennebula.org/5.2/deployment/sunstone_setup/cloud_auth.html

**Comment by al3xhh** [comment]
Apart from updating the documention, we will:

- Delete all `occi_auth` references in the code and the packages.
- Delete all `ec2_auth` references in the code and the packages.

**Comment by vickmp** [comment]
PRs to merge:
- [Code](https://github.com/OpenNebula/one-ee/pull/2201)
- [Docs](https://github.com/OpenNebula/docs/pull/2345)
