### ISSUE TITLE
Include information about association of vm operation to an usage right class

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1278]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5254, https://dev.opennebula.org/issues/5254
Original Date: 2017-07-18

---

In Section "Managing Permission through the CLI" of http://docs.opennebula.org/5.4/operation/users_groups_management/chmod.html

**Comment by tinova** [comment]
cannot understand this any longer, please reopen with further feedback
