### ISSUE TITLE
Image datastores should be able to specify a list of compatible system datastores

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1287]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5282, https://dev.opennebula.org/issues/5282
Original Date: 2017-07-25

---

None

**Comment by rsmontero** [comment]
This is implemented through the TM_MAD_SYSTEM parameter
