### ISSUE TITLE
Support nested groups in ldap

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1289]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5294, https://dev.opennebula.org/issues/5294
Original Date: 2017-07-28

---

Currently the ldap driver does not support groups withing groups.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Strahinja Kustudic** (Strahinja Kustudic)
Original Date: 2017-08-15T08:13:13Z

---

Besides supporting nested groups in LDAP, which should probably be a setting like:
```nested_groups: true
```

It would probably be better to replace the @group@ option with something like @ldap_access_filter@ (check the "sssd.conf":https://linux.die.net/man/5/sssd-ldap man page), where you can write any LDAP filter which needs to be matched for a user to allow the user to login. This will give more flexibility on who to allow to login, then just setting a single group.

**Comment by RamblingCookieMonster** [comment]
Ping!  This would be valuable for both a security (it better enables role based access controls) and convenience

**Comment by xorel** [comment]
While OpenNebula does not support nested groups, we can probably easily modify the LDAP driver to extend the user groups by the nested groups (transitively), keeping the structure flat in ONE. What do you think?

Also, this could be addressed on the LDAP level, e.g.: [memberOf plugin](https://directory.fedoraproject.org/docs/389ds/design/memberof-skip-nested.html) for dirsrv.
