### ISSUE TITLE
personalise the name of the VMs in vcenter

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1293]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5304, https://dev.opennebula.org/issues/5304
Original Date: 2017-08-04

---

As requested by:
https://support.vonecloud.com/hc/en-us/community/posts/115003099049-VM-Name-Prefix-per-Group

**Comment by rsmontero** [comment]
duplicated by #1155
