### ISSUE TITLE
HA: vip.sh arping parameter insuficcient

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1295]
---

Author Name: **Sledge Sulaweyo** (Sledge Sulaweyo)
Original Redmine Issue: 5309, https://dev.opennebula.org/issues/5309
Original Date: 2017-08-11

---

In larger environments the switch of the floating IP to a different host has to be announced via a unsolicited ARP packet to ensure that the switch updates it's ARP table accordingly. Without that a leader change is not propagated to the switch and on leader change access from other networks ends up at the wrong router port.

The change needed is minimal as just the parameter of the arping command has to be switched from -A to -U (https://github.com/OpenNebula/one/pull/425)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Sledge Sulaweyo** (Sledge Sulaweyo)
Original Date: 2017-08-18T07:56:40Z

---

I have added sudo as well as arping will not send the request without sudo

**Comment by juanmont** [comment]
It's working current version > 5.4.2. Reopen if needed
