### ISSUE TITLE
Make column order configurable

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1296]
---

Author Name: **Strahinja Kustudic** (Strahinja Kustudic)
Original Redmine Issue: 5310, https://dev.opennebula.org/issues/5310
Original Date: 2017-08-11

---

Currently it's possible to show/hide columns (of e.g. VMs list) by modifying views, but it's not possible to change in which order they are displayed. It would be really useful if the order is configurable, it would give a lot more flexibility.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Strahinja Kustudic** (Strahinja Kustudic)
Original Date: 2017-08-11T13:48:50Z

---

If making columns configurable is a big effort, it would be really nice if at least the Name column is displayed before the Owner and Group columns, because it's more important than those two.

**Comment by tinova** [comment]
Keeping this for Sunstone revamp
