### ISSUE TITLE
Cache Images in Hosts when using Local Storage to speed Launch Time

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1298]
---

Author Name: **Jonathan Philipos** (Jonathan Philipos)
Original Redmine Issue: 5312, https://dev.opennebula.org/issues/5312
Original Date: 2017-08-15

---

When an image is launched, opennebula checks the host if the image exists or not - if it doesn’t exists or the MD5 hash doesn’t match, then starts transferring that image to OpenNebula host, afterwards sends the instructions (template, etc.) for the disk to be created directly by the host, followed by the VM launching.

If the image already exists, it simply sends the instructions to create the disk and then deploys the disk locally.

Thus only one transfer is required on the host, meaning that for deployments that do not have a fast private network (or has multiple clusters that are not in the same region) then the image must be only transferred once.

This saves bandwidth, as well as time for the user.

**Comment by hale177** [comment]
This is an excellent feature with simple implementation - it just checks whether the image exists or if the hash value changes, then fetches the image from Sunstone and transfers it to the host when needed.

It's far superior to your official OneStor Datastore solution. OneStor Datastore is utterly stupid and cumbersome!! We're extremely disappointed with you.
