### ISSUE TITLE
Saving a template from a VM that has been instatiated to persistent does not work

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1299]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5314, https://dev.opennebula.org/issues/5314
Original Date: 2017-08-16

---

None

instantiate to persistent (generate template), instantiate new vm, save as new template

**Comment by Semedi** [comment]
it is working (5.8)

**Comment by tinova** [comment]
:) the refactor is giving its fruits, well done
