### ISSUE TITLE
add disk snapshots as scheduled/periodic action

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1300]
---

Author Name: **Arnaud Abélard** (Arnaud Abélard)
Original Redmine Issue: 5315, https://dev.opennebula.org/issues/5315
Original Date: 2017-08-17

---

It would be really useful to be able to schedule periodic disk snapshots from sunstone. Disk snapshoting isn't currently possible from scheduled actions so it would first requires to implement this then eventually add a way to schedule periodic actions.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-13T10:17:18Z

---

Makes sense, moving this to the backlog category and evaluating this for 5.6

**Comment by tinova** [comment]
Add also all possible actions to scheduled actions

**Comment by juanmont** [comment]
This would be implemented as periodic scheduled actions, tracked in #1548
