### ISSUE TITLE
vCenter error messages should be clearer

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1302]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5319, https://dev.opennebula.org/issues/5319
Original Date: 2017-08-22

---

For instance, if a VM Template is erased in vCenter, and a VM is instantiated in OpenNebula, the error message should make that clear.

**Comment by carloshm91** [comment]
PRs for merge:
- one: https://github.com/OpenNebula/one/pull/3499 into 5.8 and master
- docs: https://github.com/OpenNebula/docs/pull/694 into one-5.8-maintenance
