### ISSUE TITLE
RDP file for Windows VM connection

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1303]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5322, https://dev.opennebula.org/issues/5322
Original Date: 2017-08-24

---

On Windows VM, Sunstone should offer the possiblity to download an RDP conf file to directly connect to the VM, if possible incluing the credentials

**Comment by rsmontero** [comment]
Duplicated #591
