### ISSUE TITLE
SSH connection line

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1304]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5323, https://dev.opennebula.org/issues/5323
Original Date: 2017-08-24

---

Sunstone should offer for Linux VMs the SSH connection line (including credentials if available) to copy and paste onto a terminal and gain access.

**Comment by rsmontero** [comment]
Duplicated #591
