### ISSUE TITLE
Unable to delete system snapshots for a powered-off VM

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1306]
---

Author Name: **Roy Keene** (Roy Keene)
Original Redmine Issue: 5326, https://dev.opennebula.org/issues/5326
Original Date: 2017-08-25
Original Assignee: Abel Coronado

---

There should be no reason that a system snapshot could not be deleted for a powered off VM, but it's not currently accepted.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Abel Coronado** (Abel Coronado)
Original Date: 2017-09-14T08:37:40Z

---

Enabled 'Delete' buttom in snapshot-tab when the vCenter VM is in POWEROFF (Sunstone).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Anton Todorov** (Anton Todorov)
Original Date: 2017-09-14T18:43:56Z

---

Hi,

I believe that it should better to link the exception to VM_MAD's _KEEP_SNAPSHOTS=YES_ attribute instead of VM_MAD's _NAME_.

The interface usable with KVM for VM disk snapshots(for backups) just by replacing the relevant scripts because the disk resize is not locked (like the disk snapshots do) and is a single (atomic) transaction for all VM disks. ;)

Kind Regards,
Anton

**Comment by rsmontero** [comment]
Should be done
