### ISSUE TITLE
Improvements in Cashback Reports

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1308]
---

Author Name: **Jose Miguel Casado** (Jose Miguel Casado)
Original Redmine Issue: 5334, https://dev.opennebula.org/issues/5334
Original Date: 2017-08-30
Original Assignee: Tino Vázquez

---

Hi all,
after our first implementation on a big customer, we think it would be great to improve cashback reporting options, for instance:
1.- It would be fantastic being able to obtain cashback reports for every service deployed in OpenNebula (actually it's only possible to see a cost per hour estimation at service creation, but it's impossible to see that cost after it's created)
2.- It would be also great being able to choose the currency (€, $, etc.) for those costs.
3.- It would be also nice offering customers the possibility to calculate CPU, RAM and Disk costs based on the actual usage of those resources, not only based on the assigned amount of CPU, RAM or Disk per VM.

**Comment by rsmontero** [comment]
This is partially done.

1. Showback can be updated and reflect ongoing consumption
2. currency will be address as part of biling
3. monitor values are not planned to use in showback
