### ISSUE TITLE
Add possibility to use local storage with Ceph drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1310]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5343, https://dev.opennebula.org/issues/5343
Original Date: 2017-09-04

---

Instead of using Ceph as the system DS, offer an alternative to use local disk in the hypervisor.

**Comment by rsmontero** [comment]
Related issues: #660

**Comment by juanmont** [comment]
# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
