### ISSUE TITLE
Disk IO(PS) / Network charts in Sunstone do not reflect actual situation

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1313]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5352, https://dev.opennebula.org/issues/5352
Original Date: 2017-09-06
Original Assignee: Abel Coronado

---

While doing disk IOPS / network benchmarking on some VM's we notice that the storage and network charts in Sunstone (Storage: (Disk read bytes, 
Disk write bytes, Disk read IOPS, Disk write IOPS), ) do not reflect the actual IO(PS) usage at all. Counters collected by probes on the hypervisor are getting correct values from libvirt (we double checked that) and are also correctly reported to oned frontend. It seems to be a query / visualiation issue.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-09-08T09:51:05Z

---

Here are the performance counters at that time as collected by hv / one-frontend (started a read intesive ls in a directory with 1 million files):


Sep  8 11:31:44 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: DISK_SIZE=[ID=1,SIZE=1]
Sep  8 11:31:53 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=1.01 MEMORY=663636 NETRX=4424638 NETTX=19913634 
DISKRDBYTES=5703692856 DISKWRBYTES=5829128192 DISKRDIOPS=1346227 DISKWRIOPS=1322368
Sep  8 11:32:13 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=1.01 MEMORY=663636 NETRX=4427680 NETTX=19927710 
DISKRDBYTES=5704008248 DISKWRBYTES=5829132288 DISKRDIOPS=1346294 DISKWRIOPS=1322369
Sep  8 11:32:14 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: DISK_SIZE=[ID=1,SIZE=1]
Sep  8 11:32:33 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=0.0 MEMORY=663636 NETRX=4430386 NETTX=19942156 
DISKRDBYTES=5704196664 DISKWRBYTES=5829132288 DISKRDIOPS=1346296 DISKWRIOPS=1322369
Sep  8 11:32:43 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: DISK_SIZE=[ID=1,SIZE=1]
Sep  8 11:32:53 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=0.0 MEMORY=663636 NETRX=4437682 NETTX=19960516 
DISKRDBYTES=5704368696 DISKWRBYTES=5829132288 DISKRDIOPS=1346298 DISKWRIOPS=1322369
Sep  8 11:33:13 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=149.59 MEMORY=663792 NETRX=4439302 NETTX=19973110 
DISKRDBYTES=6261924408 DISKWRBYTES=5829132288 DISKRDIOPS=1482294 DISKWRIOPS=1322369
Sep  8 11:33:14 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: DISK_SIZE=[ID=1,SIZE=1]
Sep  8 11:33:33 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=161.62 MEMORY=663792 NETRX=4440790 NETTX=19985566 
DISKRDBYTES=6937739832 DISKWRBYTES=5829132288 DISKRDIOPS=1647221 DISKWRIOPS=1322369
Sep  8 11:33:45 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: DISK_SIZE=[ID=1,SIZE=1]
Sep  8 11:33:58 one-frontend oned[1978]: [Z0][VMM][D]: VM 618 successfully monitored: STATE=a CPU=143.9 MEMORY=663792 NETRX=4442176 NETTX=19997956 
DISKRDBYTES=7706067512 DISKWRBYTES=5829132288 DISKRDIOPS=1834792 DISKWRIOPS=1322369

**Comment by abelCoronado93** [comment]
I can not reproduce it.
