### ISSUE TITLE
Additional confirmation level for critical actions/VMs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1319]
---

Author Name: **Alexander Vyssochin** (Alexander Vyssochin)
Original Redmine Issue: 5362, https://dev.opennebula.org/issues/5362
Original Date: 2017-09-13

---

 I am think that  additional confirmation, like manually entering VM name, or action name will be very usefull. I think this should be as option in VM/Template. For example if confirmation-specific option is set, then operation which may lead to mailfunction  request this type of confirmation.

**Comment by rsmontero** [comment]
We added confirmation dialog to most relevant actions, if more is needed we can reopen this
