### ISSUE TITLE
Option to not store monitoring data to the DB

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1324]
---

Author Name: **Mariano Guezuraga** (Mariano Guezuraga)
Original Redmine Issue: 5372, https://dev.opennebula.org/issues/5372
Original Date: 2017-09-18

---

After setting VM_INDIVIDUAL_MONITORING = 'no' and 'VM_MONITORING_EXPIRATION_TIME' = 0 I can see in the database queries updating history, like: 'REPLACE INTO history <stuff>' or 'REPLACE INTO vm_pool <stuff>'.

This is also visible when running DEBUG=3, doing:
"sudo systemctl status opennebula" shows:

[Z100][VMM][D]: VM XXX successfully monitored: STATE=a CPU=13.08 MEMORY=16777216 NETRX=31621747954 NETTX=6476584120

However, Sunstone doesn't display anymore individual VM stats (which is expected)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-09-18T08:50:05Z

---

This is for disabling  OpenNebula polling each VM individually. The default behavior is to gather monitor data from the host information. This is not  disable with this command but removing the probe from the monitor probe directory.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Mariano Guezuraga** (Mariano Guezuraga)
Original Date: 2017-09-18T10:39:47Z

---

Thanks for clarifying.

Is there a feature or flag to disable writing VM information back to the DB? (Which is what I'm looking for)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-09-19T14:23:11Z

---

Not out of the box. You can however modify the poll probe to only send the VM state information. I'm moving this to request to evaluate this feature for a future version. Could you elaborate a bit about your use case (i.e. no wanting to write monitor data in the database)?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Mariano Guezuraga** (Mariano Guezuraga)
Original Date: 2017-09-19T15:17:28Z

---

We have other ways to monitor VMs (sending metrics to graphite, for example). Right now we have ~1400 VMs running and these probes are generating a lot of data in MySQL binlogs as 'REPLACE INTO vm_pool' / 'REPLACE INTO history' queries:

For example:

mguezuraga@ourdatabase$ sudo mysqlbinlog -vvv binlog.023501 | grep UPDATE | sort | uniq  -c
      4 ### UPDATE `opennebula`.`datastore_pool`
   5448 ### UPDATE `opennebula`.`history`
   1293 ### UPDATE `opennebula`.`host_pool`
   5451 ### UPDATE `opennebula`.`vm_pool` 

(binlog files are rotated every minute)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Mariano Guezuraga** (Mariano Guezuraga)
Original Date: 2017-09-19T15:23:11Z

---

Actually, it's not only monitoring information, these updates also store the entire VM template, which in our case tends to be a bit verbose, so we have big update statements

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-24T09:02:47Z

---

This issue is to add a flag to optionally disable the storage of monitoring data to DB.

**Comment by paczerny** [comment]
Obsolete. In new monitoring (5.12+), setting VM_MONITORING_EXPIRATION_TIME=0 disables monitoring insert querries
