### ISSUE TITLE
Improve VM save_as logic

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1326]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5374, https://dev.opennebula.org/issues/5374
Original Date: 2017-09-18
Original Assignee: Juan Jose Montiel Cano

---

This issue is to move to oned the control logic when saving a VM. This will relax the VM state constraints as well as some sync issues when copying the VM disks.

**Comment by rsmontero** [comment]
This issue needs to address comments included in:
* #1426
* #1312 
* #1311 
* #1112
