### ISSUE TITLE
Error in group update

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1328]
---

Author Name: **Abel Coronado** (Abel Coronado)
Original Redmine Issue: 5376, https://dev.opennebula.org/issues/5376
Original Date: 2017-09-19
Original Assignee: Abel Coronado

---

When you update a group for the first time, DEFAULT_IMAGE_PERSISTENT_NEW and DEFAULT_IMAGE_PERSISTENT are not defined.

**Comment by abelCoronado93** [comment]
DEFAULT_IMAGE_PERSISTENT_NEW and DEFAULT_IMAGE_PERSISTENT have 3 states (yes, no and not exist). The check box must be replaced by a drop-down menu with 3 states.
