### ISSUE TITLE
Cannot instantiate new virtual machine with normal user

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1332]
---

Author Name: **Juan Jose Montiel Cano** (Juan Jose Montiel Cano)
Original Redmine Issue: 5380, https://dev.opennebula.org/issues/5380
Original Date: 2017-09-21
Original Assignee: Abel Coronado

---

When you try to instantiate a new virtual machine with an user with primary group USERS, Sunstone shows an error.

"[one.template.instantiate] User [2] : User Template includes a restricted attribute DISK."

**Comment by al3xhh** [comment]
The bug is fixed in the last version, closing this.
