### ISSUE TITLE
Sunstone: Can not navigate when hash in end in sunstone url

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1339]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5394, https://dev.opennebula.org/issues/5394
Original Date: 2017-09-25
Original Assignee: Abel Coronado

---

If you hover any url in sunstone, right mouse click on it and select "open in new tab" you will get sunstone on url with hash in ending. Any links and buttons will not work form here. (if hash in ending)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-09-25T11:37:22Z

---

Please set category to: Sunstone and connect issue with #5395

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Abel Coronado** (Abel Coronado)
Original Date: 2017-10-25T08:43:03Z

---

Same as #5395

**Comment by rsmontero** [comment]
This cannot be implemented with the current design in Sunstone

**Comment by kvaps** [comment]
This error will be nevercaused, if we will have right urls in href parameters.
I described it in this issue:
https://github.com/OpenNebula/one/issues/1340#issuecomment-349395153
