### ISSUE TITLE
Sunstone: Open url in new tab

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1340]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5395, https://dev.opennebula.org/issues/5395
Original Date: 2017-09-25
Original Assignee: Abel Coronado

---

If you hover any url in sunstone, right mouse click on it and select "open in new tab" you will get sunstone on url with hash in ending, But not url wanted by you.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Abel Coronado** (Abel Coronado)
Original Date: 2017-10-25T08:41:22Z

---

Sunstone loads the entire html at first. And then use # to move around that html. It's not possible to load only a hunk of that html in a new tab by the Sunstone architecture. It would have to do a restructuring of the whole front to get this. We will not make this change at this time.

**Comment by rsmontero** [comment]
We want Sunstone to be a self-contained application. The current implementation assumes this and this requests breaks the current model

**Comment by kvaps** [comment]
This is wrong, for make it working we just need to add right url into `href` parameter, example:
replace each `<a href="#">` to `<a href="#images-tab">` respectively.

As I know, the true way is to fill `href` parameter with right url (not just `#`), and take this url when js event was called.
