### ISSUE TITLE
OpenNebula: Snapshots per/user enable or disable feature

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1341]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5396, https://dev.opennebula.org/issues/5396
Original Date: 2017-09-25

---

This is really needed feature for allow or disallow selected user or group for use snapshots functionality.

I think it may be reached alowing override VM_ADMIN_OPERATIONS, VM_MANAGE_OPERATIONS and VM_USE_OPERATIONS variables per user group or per single user.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-10-13T22:52:19Z

---

Yes, it is very necessary to have possibility for override this parameters via VM template.

**Comment by rsmontero** [comment]
This should be implemented with the user/group level user/group wise API call-right permission mapping
