### ISSUE TITLE
Cpu  configuration  on air

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1343]
---

Author Name: **Alexander Vyssochin** (Alexander Vyssochin)
Original Redmine Issue: 5400, https://dev.opennebula.org/issues/5400
Original Date: 2017-09-25

---

In kvm is possible to increase number of vcpus without downtime. Opennebula doesn't provide a capability to set current cpu  and max cpu  as different values. But this feature is great for VMs with growing load.

**Comment by dann1** [comment]
Having the VCPUs set is enough, as if they aren't being used the virtualization node can multiplex them for other processes.

A better approach for this would be implementing live capacity resize
