### ISSUE TITLE
Improve onevcenter import CLI

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1348]
---

Author Name: **Sergio Semedi** (Sergio Semedi)
Original Redmine Issue: 5410, https://dev.opennebula.org/issues/5410
Original Date: 2017-09-27
Original Assignee: Sergio Semedi

---

When u are trying to import something with the tool onevcenter (cli) the driver wont stop of asking you about all the resources until you find the desired one.
This proccess could turn into something tedious.

**Comment by Semedi** [comment]
duplicated #1037
