### ISSUE TITLE
CPU Overcommitment on ESXi Hosts

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1353]
---

Author Name: **Jose Miguel Casado** (Jose Miguel Casado)
Original Redmine Issue: 5420, https://dev.opennebula.org/issues/5420
Original Date: 2017-09-29
Original Assignee: Jaime Melis

---

Real CPU (actuallyutilized) is usually much lower than Allocated CPU.

On previous OpenNebula versions we had configured via Sunstone CPU OverCommitment to allow the creation of more VMs than the Real amount of CPU could allow based on the calculations OpenNebula does.

On version 5.4.1, the maximum amount for CPU overcommitment via Sunstone is much lower than the amount we actually have, inherited from ONE 5.2.1 and we need to increase this CPU Reservation amount to allow the creation of more VMS (If you reach the alocated CPU limit, OpenNebula does not allow the creation of more VMs).

Please. don't limit CPU Overcommitment, I think is better that you suggest a limit but allow the admins and architects decide if their environment can support this overcommitment. For instance, in our environment, we have a Real CPU usage of 2% and 5% in both ESXi Clusters.

**Comment by rsmontero** [comment]
Already done, also related to https://dev.opennebula.org/issues/5390
