### ISSUE TITLE
XML-RPC method one.vm.diskresize is not documented

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1356]
---

Author Name: **Venko Moyankov** (Venko Moyankov)
Original Redmine Issue: 5423, https://dev.opennebula.org/issues/5423
Original Date: 2017-10-03

---

XML-RPC method one.vm.diskresize is missing in API reference for v.5.4 http://docs.opennebula.org/5.4/integration/system_interfaces/api.html

**Comment by kvaps** [comment]
PR here:
https://github.com/OpenNebula/docs/pull/152

**Comment by tinova** [comment]
Merged, thanks!
