### ISSUE TITLE
Race condition in the datastore monitoring drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1361]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5428, https://dev.opennebula.org/issues/5428
Original Date: 2017-10-04

---

If a VM is treminated in the middle of a monitoring cycle, the following error appears:

[Z0][ONE][E]: Error parsing host information: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 1, columns 5:11. Monitoring information: 
ls: cannot access /var/lib/one//datastores/0/xxx: No such file or directory 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This issue can be fixed by properly handling stderr streams. This issues are probably related:  #1525 and #1524
