### ISSUE TITLE
Improve Sunstone dashboard load times

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1364]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5431, https://dev.opennebula.org/issues/5431
Original Date: 2017-10-04

---

Currently all the accounting information is used to print 7 days graphs. Explore how to improve this to avoid slowness when the VM , host, network and other pools have a significant size.

**Comment by rsmontero** [comment]
Duplicated #1511
