### ISSUE TITLE
sql opennebula.logdb table grows indefinitely in solo mode

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1365]
---

Author Name: **Laurence Gill** (Laurence Gill)
Original Redmine Issue: 5432, https://dev.opennebula.org/issues/5432
Original Date: 2017-10-04
Original Assignee: Ruben S. Montero

---

Running a federation in solo mode appears to let the logdb table grow to an very large size.

It seems that the cleanup job is only run when HA is configured, so when the server_id is -1 the housekeeping doesn't run.  If you set the server_id to 0 so it is a lone master the database is cleaned.

Is this a bug?  Should the database not be growing in solo mode, or should the cleaning happen in all modes?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-13T11:16:56Z

---

Yes I can confirm this is a bug, cleaning should happen in all modes. The log is used to sync the federated instances also.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-13T15:29:26Z

---

Fix now in one-5.4 and master

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Laurence Gill** (Laurence Gill)
Original Date: 2017-10-19T08:18:36Z

---

Ruben S. Montero wrote:
> Fix now in one-5.4 and master

Excellent thanks.

Is it safe to truncate this table? It has grown so large the clean up job does not complete within a sensible amount of time.  It took several hours to manually batch delete the old data, but a second instance is much larger.

Thanks

**Comment by hydro-b** [comment]
running 5.4.11 and see this is still hapening. Changed from a HA cluster to "solo" mode due to HA issues (will create seperate issues for that). ID set to "-1", logdb growing and not shrinking ...

**Comment by hydro-b** [comment]
@rsmontero what is the safest way to "shrink" the size of the table? Does ONE in solo mode still use te logdb? Is it safe to truncate the table? Our backup is getting huge ...

**Comment by rsmontero** [comment]
For the records, we've found this could be solved by tuning the purge parameters. Currently there is no need to reopen this issue
