### ISSUE TITLE
Keep pointer to last restored snapshot

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1366]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5433, https://dev.opennebula.org/issues/5433
Original Date: 2017-10-04

---

Currently this reference is not saved and it is not possible to know which one is the latest restored system snapshot.

**Comment by rsmontero** [comment]
worksforme
