### ISSUE TITLE
Clone VM on running state

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1367]
---

Author Name: **Adrian Menendez** (Adrian Menendez)
Original Redmine Issue: 5434, https://dev.opennebula.org/issues/5434
Original Date: 2017-10-05

---

On vCenter you can just clone a running VM. Since this functionality is widly used on production enviroments, it would be very useful to do it through ONE.

**Comment by tinova** [comment]
won't implement, will reopen for KVM
