### ISSUE TITLE
Non Interactive User Input for the CLI

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1368]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5435, https://dev.opennebula.org/issues/5435
Original Date: 2017-10-05

---

Add a new flag to onetemplate instantiate to pass values to user inputs:

  --user-input MYSQL_PASSWORD=dummypass

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4297
- docs: https://github.com/OpenNebula/docs/pull/976
