### ISSUE TITLE
Allow appending to the template instead of replacing

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1370]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5437, https://dev.opennebula.org/issues/5437
Original Date: 2017-10-05
Original Assignee: Jaime Melis

---

Currently, if you define an item in the VM template content textarea of the OneFlow service template and it already exists in the original template it will be replaced instead of appended.

For example:

VM template content: DISK = [...]

This will replace all the disks with those defined in the VM template content.

This will be fixed by adding a special parameter called "APPEND=<key>,<key2>,...". It that special key is present in the VM template content, those resources will be appended to those that exist in the source template.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-27T15:55:39Z

---

This issue is fixed for 5.4.3. It'll remain open to propose a migration path for 5.6

**Comment by al3xhh** [comment]
This issues doesn't apply, because this section has been removed in the new OneFlow. If the user wants to modify the VM template contents he has to do it manually, so he can append or modify.

Closing it.
