### ISSUE TITLE
Migrate VMs between different vCenter clusters

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1371]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5438, https://dev.opennebula.org/issues/5438
Original Date: 2017-10-05

---

OpenNebula should provide this functionality, which is already present in vCenter.

**Comment by tinova** [comment]
[ ] Testing
 [ ] Documentation: Explain requirements cluster migration: shared networks and datastores between OpenNebula clusters
