### ISSUE TITLE
onedb change-body should support history tables

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1372]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5439, https://dev.opennebula.org/issues/5439
Original Date: 2017-10-06

---

Since the VM XML is reconstructed from the history table, this needs to be changed as well if there is any issue.

**Comment by rsmontero** [comment]
This is done via the command onedb update-history
