### ISSUE TITLE
Disk resize is limited to 500GB in sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1373]
---

Author Name: **Venko Moyankov** (Venko Moyankov)
Original Redmine Issue: 5440, https://dev.opennebula.org/issues/5440
Original Date: 2017-10-06

---

When trying to resize disk to size larger than 500GB on existing VM using sunstone, new size is limited to 500GB. Any subsequent try returns error: New disk size has to be greater than current one.
When using XML-RPC everything is OK.

To reproduce:
- create VM
- start VM
- on running VM, resize disk
- enter new size 550GB using the text box
disk will be resized to 500GB
- on running VM resize disk
- enter new size 550GB using the text box

The code with the limit of 500GB is located at:
src/sunstone/public/app/tabs/vms-tab/dialogs/disk-resize.js:85
        max: Humanize.sizeToMB("500GB")*1024,

**Comment by rsmontero** [comment]
This is already solved in #1486
