### ISSUE TITLE
User should be able to select Wild VM networks at import time

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1374]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5441, https://dev.opennebula.org/issues/5441
Original Date: 2017-10-06

---

If for any particular reason the vnet/AR needs to be different from the previously imported network, or the network that is going to be created as part of the import process.

**Comment by tinova** [comment]
OpenNebula identifies the network in vCenter and creates it in OpenNebula. If it features IP, it searches for the appropriate AR. Need a use case to justify this, closing until we find (or rather, rediscover) one.
