### ISSUE TITLE
FILES_DS template variable disappears if update the configuration.

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1375]
---

Author Name: **Sergio Milanese** (Sergio Milanese)
Original Redmine Issue: 5442, https://dev.opennebula.org/issues/5442
Original Date: 2017-10-06
Original Assignee: Abel Coronado

---

Hello,

in Sunstone, if you update configuration, for example, you change the variable SET_HOSTNAME, the variable containing the FILES_DS contextualization scripts disappears.
This makes it impossible for the next boot to run these scripts because the contextual cdrom only has context.sh.
You can also resolve this problem by adding the Sunstone option to also select additional contextualization files that are added later, for example in the files section  in this time that only has the execution order (INIT_SCRIPTS variable).
Thank you

Sergio

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-27T09:56:21Z

---

It seems that we cannot reproduce in the last version 5.4.2. We'll reopen if fixed. As a side note we found a related issue.

**Comment by christian7007** [comment]
It fails when the VM configuration it's updated (Conf tab). 

It seems that the existing files are not being loaded leaving files sections empty, so it overwrite the information on update deleting the FILES_DS content.

**Comment by jloboescalona2** [comment]
@tinova PR's to approve
-ONE: https://github.com/OpenNebula/one/pull/3810
-Docs: https://github.com/OpenNebula/docs/pull/794
