### ISSUE TITLE
New VM state "LOCKED" or "BACKUP"

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1377]
---

Author Name: **Kristian Feldsam** (Kristian Feldsam)
Original Redmine Issue: 5444, https://dev.opennebula.org/issues/5444
Original Date: 2017-10-07

---

Hello, I written backup script to backup images from qcow2 datastores. That script reads info from xml-rpc api and in case that image is used and is persistent tmp VM snapshot is created -> backup images -> blockcommit and delete snapshot.

I like to "lock" VM to prevent user manipulation with VM and also, user can see that VM is backing up

**Comment by juanmont** [comment]
See what happens if the action needs an external resource, we must also check the blocking of this resource.

**Comment by rsmontero** [comment]
Doc: https://github.com/OpenNebula/docs/pull/186
