### ISSUE TITLE
add entry with onedb change-body

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1379]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 5448, https://dev.opennebula.org/issues/5448
Original Date: 2017-10-10

---

For example after upgrade of OpenNebula to add ALLOW_ORPHANS with value 'YES' to the disks definition of all VMs.

Best Regards,
Anton Todorov

**Comment by rsmontero** [comment]
We now include update-body that covers this functionality
