### ISSUE TITLE
Users can not terminate own VMs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1380]
---

Author Name: **Venko Moyankov** (Venko Moyankov)
Original Redmine Issue: 5449, https://dev.opennebula.org/issues/5449
Original Date: 2017-10-10

---

If user is not a member of oneadmin group, he can not create a VM with admin rights for the owner and can not terminate own VMs, created by himself. The problems seems to be caused of improper working UMASK for non-oneadmin users.

To reproduce the problem:
1) $ oneuser create test test --group users
2) $ oneuser umask test 017
3) $ oneuser show test -x | grep UMASK  # note Umask is set correctly <UMASK><![CDATA[017]]></UMASK>
4) In Sunstone login as user test
5) create new VM instance 
6) check VM permissions: 
   $ onevm show <VM_ID> -x | grep OWNER_
   Note <OWNER_A>0</OWNER_A> owner does not have admin permission
7) try to terminate VM in sunstone as user test. Error is returned:
[one.vm.action] User [11] : Not authorized to perform ADMIN VM [291].

Tested on 5.4.1. Not tested on earlier versions.

**Comment by paczerny** [comment]
Version 6.4: The VM terminate action needs MANAGE privileges, so the user can terminate the VM.

Also the VM ``OWNER_A`` permissions are correct as default permissions for non oneadmin users are 660. Only oneadmin user can add admin permissions to resources

The only bug I can see here is that the default permissions are not mentioned in the [documentation](https://docs.opennebula.io/6.4/management_and_operations/users_groups_management/chmod.html#setting-default-permissions-with-umask). The default permissions are:
* 666 for regular users 
* 660 for regular users with ``ENABLE_OTHER_PERMISSIONS="NO"`` set in ``oned.conf``
* 777 for oneadmin user/group
