### ISSUE TITLE
Integrate L3 services

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1383]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5452, https://dev.opennebula.org/issues/5452
Original Date: 2017-10-11

---

Like DNS, Firewall, Load Balancing, straight from Sunstone.

**Comment by rsmontero** [comment]
Covered  by VR appliance.
