### ISSUE TITLE
Enhance scheduled actions

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1384]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5453, https://dev.opennebula.org/issues/5453
Original Date: 2017-10-11

---

At least in two ways:

 - Make them relative (two weeks as opposed to, for instance, 6th October)
 - Recurrent (for instance, for backups)

**Comment by juanmont** [comment]
This would be implemented as periodic scheduled actions, tracked in #1548
