### ISSUE TITLE
oneacct should not halt on malformed registers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1387]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5456, https://dev.opennebula.org/issues/5456
Original Date: 2017-10-13

---

Failing to process one item should not interrupt the whole output of a pool

For instance, oneacct should not halt execution if one register is malformed.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Date: 2017-10-13T10:53:19Z

---

Example attached

**Comment by rsmontero** [comment]
In this issue we will update the behavior of oneacct. Other commands do work as described onevm delete 4..10 for example will continue processing VMs in case of failure
