### ISSUE TITLE
Support empty attributes in merges, this will remove any instance on current template. This will allow to Instantiate VM without VNets even if the original template includes them

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1392]
---

Author Name: **Abel Coronado** (Abel Coronado)
Original Redmine Issue: 5461, https://dev.opennebula.org/issues/5461
Original Date: 2017-10-17
Original Assignee: Abel Coronado

---

When instantiate to VM without vnets (erasing in wizard), one tries to create the VM with the associated vnets in Template.

Therefore, you can't remove vnets when instantiating.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-17T14:39:14Z

---

This needs:
* Sunstone to make use of this feature to enable removal of template attributes
* Update documentation (compatibility) to spell out the new behavior of ATTR=[], prior verions produce a parser error. Now empty attributes are just ignored or removed when merged.

**Comment by abelCoronado93** [comment]
- Needs documentation.
