### ISSUE TITLE
Implement a find by criteria for OpenNebula resources

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1393]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5462, https://dev.opennebula.org/issues/5462
Original Date: 2017-10-17

---

For instance, find a VM with a particular tag, or a particular NIC.

**Comment by treywelsh** [comment]
What is the status of this issue? 

I was writing a new issue and I found this.
FYI, I paste the content of the issue I was writing:

It may be useful to have an additional filter abilty when retrieving entity instance (VM, image ...)

Here is how we filter on instances for now:
We fetch all the instances (as VM), then we loop on list of instances with some tests to filter and keep what we needs.

To do this, we call the XML-RPC method "one.XXXpool.info", which retrieve a shortened versions of informations per instance.
But, it does not return our custom tags, so we have to iterate on all ID and call one.XXX.info methods to retrieve all informations and filter.

It seems a bit heavy and may be improved with little efforts ?

For instance it could be as simple as allowing a kind of instance tagging, in allowing to fetch instances based on a TEMPLATE defined key (just checking the key presence)

For the XML-RPC interface of this feature, it could be an additional "key string" parameter to "one.XXXpool.info" XML-RPC methods.
It should reduce the overall RPC traffic and simplify the user side code when filtering instances.

By the way, we see that the "document" entity has already a "type" field, which allow a more basic way to filter.
So an other idea could be to use the "Document" entity to have a kind of entities index, but it does not seen the proper way to do this.
To keep track of intances, it leads to store some comma separated values like VM_IDS = "1,15,..."

**Comment by christian7007** [comment]
This filter is implemented for VMs (#2671). You can find more info here http://docs.opennebula.org/5.8/operation/vm_management/vm_instances.html?highlight=search#searching-vm-instances in the docs. It is not implemented for other pools because the size of them use to be smaller, but we can consider that.

**Comment by treywelsh** [comment]
Thank you, I didn't aware of this issue.

However, it does not seems documented in the [XML-RPC API documentation of the vmpool.info method](https://docs.opennebula.org/5.6/integration/system_interfaces/api.html#one-vmpool-info) ?

Does it replace the "state" filtering parameters in a more global way ?
I'm looking at [this commit](https://github.com/OpenNebula/one/commit/5f7fb402aa21766bbc642ec2fb3ee439b7085f6d#diff-7ba0a58fb3aa2ff0e57df97509c51914)

**Comment by treywelsh** [comment]
Using this feature give us the following error:
> Full text search is not supported by the SQL backend

Looking in the code, regarding our DB, I found this function:
`bool MySqlDB::fts_available()
{
    unsigned long version;

    version = mysql_get_server_version(db_escape_connect);

    if (version >= 50600)
    {   
        return true;
    }   
    else
    {   
        return false;
    }   
}`

It's due to the database version but the documentation doesn't seems to recommend any database version.

It should be documented.

**Comment by treywelsh** [comment]
Ok, thank you, I was looking in the deployment section of the front servers to have more informations on databases versions. :)

Maybe a short warning to redirect the users could be useful ?

**Comment by christian7007** [comment]
Sure, it makes sense.
 I've open an issue in docs repo for adding this information (https://github.com/OpenNebula/docs/issues/594)

**Comment by treywelsh** [comment]
>  It is not implemented for other pools because the size of them use to be smaller, but we can consider that.

To me it's not only a performance problem, it's also for the convenience.
It may be interesting to add this feature at least for some resources commonly used with VMs like images, template, or even virtual network.

This filter feature could be used to regroup and then quickly filter some resources for a given "project" or user defined entity (like a catalog).
For instance, if we have some catalogs of images with various linux distros and versions, or a catalog of templates.

From the XML-RPC point of view, it require to make a request for each entity and then filter in a loop right ? (pool.info methods never returns user defined template tags ?)
With this feature, it's done in only one XML-RPC call, without a loop and a bunch of tests.

From the GOCA point of view, filter with key-value to filter the code is really easy to update and it simplify the user code.

It would be nice to have this feature on all pool info methods but I can understand that may represent a lot of works and may seems useless.

**Comment by nugsolot** [comment]
What is the exact requirements for the SQL backend for this to work with vmpool?

The Docs say this:
```
This feature is only available for MySQL backend with a version higher or equal than 5.6
```

I have used both MariaDB10 and now MYSQL-community Server 8 after hitting this problem on MariaDB 5.5 and both of them still produce the same error:


Currently on Mysql 8:

[root@u90c04p08-sunstone ~]# mysql -V
mysql  Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)

And still seeing this:
[root@u90c04p08-sunstone ~]# onevm list --search NAME=1
[one.vmpool.info] Full text search is not supported by the SQL backend

**Comment by christian7007** [comment]
As said in the documentation, the only requirement is `MySQL backend with a version higher or equal than 5.6`

Are you sure you have correctly configured OpenNebula for working with MySQL instead of SQLite? If you have a new installation the default value for DB backend is SQLite.

**Comment by nugsolot** [comment]
Yes is certainly helps to not have 2 DB statements in the oned.conf >.< doh.

After commenting out the first one which happened to be the one poitning to SQLite this works a expected on MariaDB 10.3

thanks Christian

**Comment by christian7007** [comment]
you are welcome!
