### ISSUE TITLE
Host selection in VM template not visible

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1394]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5463, https://dev.opennebula.org/issues/5463
Original Date: 2017-10-17
Original Assignee: Abel Coronado

---

When a VM template is edited the "host" selection is not displayed. It is still there in the template, just not visually selected. So it _looks_ like the selection is not there.

**Comment by jloboescalona2** [comment]
Stefan Kooman, You can try the new versions, and if you find this error you can tell us the steps to replicate it
