### ISSUE TITLE
Deleting a group that owns images used by running VMs breaks those VMs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1395]
---

Author Name: **Roy Keene** (Roy Keene)
Original Redmine Issue: 5464, https://dev.opennebula.org/issues/5464
Original Date: 2017-10-17

---

In OpenNebula 5.2.0 (and likely newer) deleting a group that owns images used by VMs prevents snapshots (and likely) other operations from being performed on those VMs due to quota look operations failing.

Solutions I have investigated:
  1. Soft-delete of groups;
  2. Chown images found in this state (to whom?); but most likely answer:
  3. Return an error deleting groups that own resources (like is done if there are members)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Roy Keene** (Roy Keene)
Original Date: 2017-10-17T18:14:13Z

---

Output with patch (attached) applied:

```
[test] root@aurae-dashboard:~# onegroup create x
ID: 100
[test] root@aurae-dashboard:~# onegroup delete 100
[test] root@aurae-dashboard:~# onegroup create x
ID: 101
[test] root@aurae-dashboard:~# oneimage chgrp 0 101
[test] root@aurae-dashboard:~# onegroup list
  ID NAME                          USERS       VMS            MEMORY         CPU
   0 oneadmin                          2         -                 -           -
   1 users                             0   0 /   -      0M /       -  0.0 /    -
 101 x                                 0   0 /   -      0M /       -  0.0 /    -
[test] root@aurae-dashboard:~# onegroup delete 101
[one.group.delete] Cannot delete group. Group 101 owns images
[test] root@aurae-dashboard:~#

```

A better solution would be to add a method to each class (or to PoolSQL) to find all objects owned by a given UID/GID, a later patch may implement that

**Comment by tinova** [comment]
reopening to apply in 5.6

**Comment by juanmont** [comment]
I have tried to instantiate templates that use images whose owners do not exist and also to make Snapshots, but it does not fail me at any time.

We have decided not to report any errors if you delete a user or group that has associated resources.

I've tried it on the latest version of OpenNebula.

**Comment by rsmontero** [comment]
it seems that VMs are not affected and working. closing as works for me and we will reopen if needed
