### ISSUE TITLE
Disk size is reset to image size after delete-recreate VM

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1398]
---

Author Name: **Venko Moyankov** (Venko Moyankov)
Original Redmine Issue: 5467, https://dev.opennebula.org/issues/5467
Original Date: 2017-10-18

---

When VM is recovered with delete-recreate option, all disks are recreated with the size of the image, no matter what was the actual disk size. 

For example VM before delete-recreate:
DISK = [
  ...
  ORIGINAL_SIZE = "2252",
  SIZE = "3072",
  ...
]

after delete-recreate:
DISK = [
  ...
  ORIGINAL_SIZE = "2252",
  SIZE = "2252",
  ...
]

To reproduce with Sunstone:
1. Create new VM from template
2. On instantiate, define disk size larger than the image size
3. After VM is in status running, select recover and 'delete-recreate' option
4. After VM is recreated, check disk size is now smaller. it is the same as the image size.

tested on 5.4.0, 5.4.1. Not tested on 5.4.2

**Comment by rsmontero** [comment]
duplicated by #1398

**Comment by vholer** [comment]
Still the issue with 5.4.10

**Comment by rsmontero** [comment]
Fixed for 5.4.11.
