### ISSUE TITLE
On refresh, sunstone loses the current dataTable page

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1399]
---

Author Name: **Edouard Bourguignon** (Edouard Bourguignon)
Original Redmine Issue: 5468, https://dev.opennebula.org/issues/5468
Original Date: 2017-10-18

---

When you click on refresh in the vm list view, the page is lost, and you are back to page 1.

It's a regression cf bug #2803

**Comment by rsmontero** [comment]
We cannot reproduce this on current versions
