### ISSUE TITLE
services instances view, table columns names are in wrong order

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1400]
---

Author Name: **Edouard Bourguignon** (Edouard Bourguignon)
Original Redmine Issue: 5469, https://dev.opennebula.org/issues/5469
Original Date: 2017-10-18

---

The columns name are :

ID > NAME > OWNER > GROUP > STATE

But the data are in this order :

ID > OWNER > GROUP > NAME > STATE

This is just a minor display bug.

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
-ONE: https://github.com/OpenNebula/one/pull/3807
-Docs: https://github.com/OpenNebula/docs/pull/792
