### ISSUE TITLE
Make VM_*_OPERATIONS configurable at user and group level

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1401]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5470, https://dev.opennebula.org/issues/5470
Original Date: 2017-10-18

---

By adding the following attributes in the user and/or group template:

VM_ADMIN_OPERATIONS
VM_MANAGE_OPERATIONS
VM_USE_OPERATIONS

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-10-22T01:17:50Z

---

Agree, I already wrote about it:
https://dev.opennebula.org/issues/5396

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-10-22T12:51:02Z

---

Same with *_RESTRICTED_ATTR:
https://dev.opennebula.org/issues/5487

**Comment by kvaps** [comment]
ref #1341
ref #1418

**Comment by paczerny** [comment]
PRs for merge:
* one: #3638 into master
* development: OpenNebula/development#701 into master
* docs: OpenNebula/docs#729 into master
