### ISSUE TITLE
Sunstone: There is no possibility for disable "Advanced options" for resources creating (Images, NICs)

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1407]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5476, https://dev.opennebula.org/issues/5476
Original Date: 2017-10-19
Original Assignee: Abel Coronado

---

!1.png!

**Comment by rsmontero** [comment]
We'll address in #1406
