### ISSUE TITLE
vcenter should have credentials system centralized

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1408]
---

Author Name: **Sergio Semedi** (Sergio Semedi)
Original Redmine Issue: 5477, https://dev.opennebula.org/issues/5477
Original Date: 2017-10-19
Original Assignee: Sergio Semedi

---

vcenter_user && vcenter_password are located inside host and datastore, this info is redundant ALSO its difficult to know if your datastore its failing.

opennebula should has the credendials in a single place, this will permit us to have more control speaking about vcenter resources.

**Comment by rsmontero** [comment]
duplicated by #1806

**Comment by Semedi** [comment]
is not really duplicated, the issue refers to have vCenter credentials in both hosts and datastores.

For the moment we are keeping this behaviour but should be avoided.

**Comment by sergiojvg** [comment]
https://github.com/OpenNebula/one/pull/3226 --> master

**Comment by tinova** [comment]
In order to close this we need:

  * pointer to test
  * change documentation: http://docs.opennebula.org/5.8/deployment/vmware_infrastructure_setup/datastore_setup.html#the-vcenter-transfer-manager
  * review Sunstone & import creation to drop credentials info

**Comment by sergiojvg** [comment]
docs: https://github.com/OpenNebula/docs/pull/605  (--> one-5.8-maintenace, --> master)

**Comment by tinova** [comment]
LGTM 📷
