### ISSUE TITLE
OpenNebula: VM_HIDDEN_ATTR and posibility for hide some flieds from user

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1410]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5479, https://dev.opennebula.org/issues/5479
Original Date: 2017-10-19

---

I want to hide some flieds from user, so only oneadmin can see or edit this. 
I suggest you entering the following variables in the config file:
 
```
VM_HIDDEN_ATTR
VNET_HIDDEN_ATTR
INHERIT_HIDDEN_ATTR
INHERIT_HIDDEN_ATTR
USER_HIDDEN_ATTR

```

It will work like VM_RESTRICTED_ATTR and VNET_RESTRICTED_ATTR but will prevent showing this flieds for user.

**Comment by rsmontero** [comment]
This will somehow break the current data model. We'll close this and if a good use case need this will reopen to implement it.
