### ISSUE TITLE
OpenNebula: Image should downloads on BRIDGE_LIST node

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1413]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5482, https://dev.opennebula.org/issues/5482
Original Date: 2017-10-19

---

This is really strange for download image on core server and after transfer it via pipeline to the one of BRIDGE_LIST nodes.
Why not download image directly on node?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-10-30T07:29:49Z

---

As can I see, this patch can break uploading images via sunstone interface, be careful.
May be some option for enable it?

**Comment by rsmontero** [comment]
We do not require Internet or external access to the bridge-list nodes
