### ISSUE TITLE
IPs in vms-tab 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1417]
---

Author Name: **Anton Zubkov** (Anton Zubkov)
Original Redmine Issue: 5486, https://dev.opennebula.org/issues/5486
Original Date: 2017-10-21

---

Change the IP display as a drop-down list. When the client has several IP addresses, everything looks bad

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4677
- Docs: https://github.com/OpenNebula/docs/pull/1103
