### ISSUE TITLE
no feedback when creating a service with missing network

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1420]
---

Author Name: **Markus van Dijk** (Markus van Dijk)
Original Redmine Issue: 5489, https://dev.opennebula.org/issues/5489
Original Date: 2017-10-23

---

In the "create service" dialog to start a service, I should specify a network to use.
If I do not do that and click on the "Create" button, I get NO feedback, and (of course) no service is created.
Other required fields give a feedback when omitted. I would appreciate this het here well...
Thanks and regards, Markus

**Comment by jloboescalona2** [comment]
We cannot replicate the error, you can test if it occurs in recent versions, in the case that it is positive, tell us how to replicate the error to reopen the issue
