### ISSUE TITLE
Add additional information for virtual network drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1423]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5493, https://dev.opennebula.org/issues/5493
Original Date: 2017-10-24
Original Assignee: Jaime Melis

---

Extend the list of attributes send to the OpenNebula network drivers. The list of attributes could be also made configurable. For example:

```
--- a/src/vmm_mad/exec/one_vmm_exec.rb
+++ b/src/vmm_mad/exec/one_vmm_exec.rb
@@ -139,7 +139,7 @@ class VmmAction
     # List of xpaths required by the VNM driver actions. TEMPLATE/NIC is
     # also required but added separately to the driver xml
     XPATH_LIST = %w(
-        ID DEPLOY_ID
+        ID DEPLOY_ID TEMPLATE/CONTEXT USER_TEMPLATE
         TEMPLATE/SECURITY_GROUP_RULE
         HISTORY_RECORDS/HISTORY/HOSTNAME
         HISTORY_RECORDS/HISTORY/VM_MAD


```

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-24T12:37:08Z

---

This issue is more general and could be useful for all the actions in the one_vmm_exec.rb

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Jaime Melis** (@jmelis)
Original Date: 2017-10-27T13:08:56Z

---

https://github.com/OpenNebula/one/pull/545

**Comment by atodorov-storpool** [comment]
I should check the notes but I have a feeling this should be applied to the image drivers too...
