### ISSUE TITLE
Backup interface

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1428]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5498, https://dev.opennebula.org/issues/5498
Original Date: 2017-10-24

---

This is to implement a backup interface for OpenNebula. It should consists in two parts:

* Abstract logic to specify different policies at datastore or/and   VM level. This will include basic backup operations

* Driver calls to execute the backup operations.

This backups maybe associated to a new special datastore for backups separated from system and images data-store.

**Comment by rsmontero** [comment]
Also consider integration with third party tools like veeam

**Comment by jp-pro** [comment]
This feature is really a must have on production platform. For the moment we have to play with snapshot and save as. But It is really difficult to create a correct backup on a different Data store (It is impossible actually). 
A save as on another datastore is not possible RUNNING or event POWER OFF state. 

Based on the last update, this feature is plan for 5.10. It would be really nice if it is really the case :).

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/852)

**Comment by tinova** [comment]
test with s3 marketplace

**Comment by tinova** [comment]
test with vCenter

**Comment by tinova** [comment]
not working with vCenter in 6.0 

already tested in s3
