### ISSUE TITLE
Catchall for HOOKs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1435]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5505, https://dev.opennebula.org/issues/5505
Original Date: 2017-10-26

---

If an admin is interested in _EVERY_ STATE change in OpenNebula he/she would need to write all possible STATE changes for all different HOOK types (VM, USER, GROUP, HOST, VNET, etc.). Use cases: log all STATE changes to irc channel. Log all STATE changes to external system (audit, time series database)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-11-14T07:48:52Z

---

As dicussed on IRC:

15:18 < hydro-b> I want to create a VM_HOOK that get's triggered by a "chown chgrp" operation. Is that possible? What state change would the VM go through?
15:41 < rkeene> I don't think it changes state for that
16:28 < hydro-b> rkeene: me too, would be nice to capture events like this. I would like to be able to capture any change to any resource
16:29 < rkeene> Patchy patch patch
17:18 < rkeene> Seems like a good thing to add somewhere as an official feature
Day changed to 10 Nov 2017
12:33 <@tinova> @hydro-b, @rkeene, that's a very interesting feature request
12:33 <@tinova> could you open a ticket in dev.opennebula? (I'll do it if you rather have me opening it)

**Comment by vholer** [comment]
Also, state(s) not covered by hook:
- NIC hotplug when VM is powered off
