### ISSUE TITLE
VM "Save as Template" enhancements

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1436]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5506, https://dev.opennebula.org/issues/5506
Original Date: 2017-10-26

---

Currently only the option of doing a VM "Save as Template" when the VM has STATE "POWEROFF". Most probably because of all referenced disks being cloned when doing a "Save as Template". I would like to propose the following enhancement options:

- "Save as Template" _WITHOUT_ DISKS (extra checkbox in sunstone)
- "Save as Template" --force existing_template (Overwrite the contents of an already existing Template with this one)
- "Save as Template" --update (variant on above: overwrite existing template _REFERENCED_ in this template: TEMPLATE_ID. So overwrite "TEMPLATE_ID"). --update can be considered to be "linked" to originating template.

Our use case: we have a TEMPLATE for _every_ VM running. If, for some reason or the other, we need to re-instantiate the VM we can do so. Every Template has a fixed IP in it for example, which could be lost if VM's were just re-instantiated / delete-recreated for example.

More general use case: Keep changes in template to golden template VM's in sync with the template

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-10-26T11:41:53Z

---

Javi Fontan suggested I could hack the the ruby library (mad) disabling the actions checking / cloning the DISKS in the template. This works for CLI. See attached file virtual_machine.rb. This if of course a hack and disables the ability to clone with DISKS, but shows it's possible.

**Comment by rsmontero** [comment]
Closing this an adding link into #1326 to track all the SAVE_AS changes there
