### ISSUE TITLE
Sunstone SNAPSHOT UI improvements

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1437]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5507, https://dev.opennebula.org/issues/5507
Original Date: 2017-10-26

---

People tend to get confused when making a VM / DISK SNAPSHOT in Sunstone. Maybe rework the "SNAPSHOT" tab and have two subsections in there:

VM SNAPSHOT
DISK SNAPSHOT

With a clear description / title what action will be performed on the VM / DISKS

**Comment by tinova** [comment]
We'll add some more context in the new Sunstone (#5422).

"Snapshots in this tab refer to System Snapshots, which includes all disks and the memory state of the VM. For disk snapshots, see the Storage tab"

as a hint on the Snapshot subtab

**Comment by sbbarragan** [comment]
PR to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/2216
