### ISSUE TITLE
DISK IOPS / Throughput burst support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1439]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5509, https://dev.opennebula.org/issues/5509
Original Date: 2017-10-26

---

Since QEMU => 2.6 and LIBVIRT 0.8.8 there is support for IOPS bursting. For a specified amount of time a VM DISK can consume more IOPS / Throughput. See https://blogs.igalia.com/berto/2016/05/24/io-bursts-with-qemu-2-6/. So this is basically an extension of the already posibility in ONE to limit read, write, total IOPS / Bandwidth.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-10-26T15:27:05Z

---

Relates to issue #5510

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-10-26T15:41:00Z

---

relates to issue #5511

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Kristian Feldsam** (Kristian Feldsam)
Original Date: 2017-11-09T12:18:04Z

---

+1

**Comment by tobzsc** [comment]
Hey @rsmontero, are there any plans for this feature? Can we speed up the realization by doing a sponsoring here?

**Comment by rsmontero** [comment]
It seems we lost tracking during the issue triage, after the redmine migration. I'll increase it's priority. No short-term plans for this right now

**Comment by rsmontero** [comment]
Done in 5.6
