### ISSUE TITLE
creating vcenter net does not allow you to choose real host

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1442]
---

Author Name: **Sergio Semedi** (Sergio Semedi)
Original Redmine Issue: 5512, https://dev.opennebula.org/issues/5512
Original Date: 2017-10-27
Original Assignee: Sergio Semedi

---

This is cuz vcenter cluster are treated by opennebula as a host so u do not really know where are u deploying the new network.

You should be able to have this option, at least if u are not creating a distributed port group.

**Comment by Semedi** [comment]
duplicated #1541
