### ISSUE TITLE
You can download app from marketplace in LOCKED state

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1445]
---

Author Name: **elder one** (elder one)
Original Redmine Issue: 5515, https://dev.opennebula.org/issues/5515
Original Date: 2017-10-27

---

I have local http marketplace. 
When you create new app from disk image and image being exported to local maretplace (app in Sunstone at locked state), 
buttons for downloading and importing app are enabled. And can download (partial/empty) app through Sunstone.

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4665 
- docs: OpenNebula/docs/pull/1101
