### ISSUE TITLE
hashing names does not work properly

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1446]
---

Author Name: **Sergio Semedi** (Sergio Semedi)
Original Redmine Issue: 5516, https://dev.opennebula.org/issues/5516
Original Date: 2017-10-30
Original Assignee: Sergio Semedi

---

There is a problem regarding vcenter and the imported resources:

    When u import a resource a hash process start to give unique name to the one object,
    The hash process has input values like vsphere location,
    This location is not properly defined due vsphere API problems, we are always catching same
    cluster location, so its possible to create collissions easily.

**Comment by rsmontero** [comment]
duplicated by #1808
