### ISSUE TITLE
QEMU 2.10 file locking breaks commands underneath the running QEMU

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1449]
---

Author Name: **Vlastimil Holer** (Vlastimil Holer)
Original Redmine Issue: 5519, https://dev.opennebula.org/issues/5519
Original Date: 2017-10-31

---

QEMU 2.10 comes with enabled builtin file locking to prevent image corruption (https://wiki.qemu.org/ChangeLog/2.10):
> Image locking is added and enabled by default. Multiple QEMU processes cannot write to the same image as long as the host supports OFD or posix locking, unless options are specified otherwise.

If some operation with file image (resize/snapshots management) is done under hands of the running QEMU, it fails on lock acquire:

```
$ qemu-img resize /var/lib/one/datastores/0/39/disk.0 11264M
qemu-img: Could not open '/var/lib/one/datastores/0/39/disk.0': Failed to get "write" lock
Is another process using the image?

```

To disable locking, *<code>share-rw=on</code>* or *<code>file.locking=off</code>* (??) should be specified as parameters of particular <code>-device</code> or <code>-drive</code> on QEMU commandline, e.g.:
https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1716028
https://lists.gnu.org/archive/html/qemu-devel/2017-07/msg05288.html

Don't see a way how to configure this via libvirt.

**Comment by atodorov-storpool** [comment]
> Don't see a way how to configure this via libvirt.

There is slightly weird interface to add qemu commands via  domain XML. 
Hint could be found in an obsolete tool to enable the virtio-data-plane for virtio-blk (when it was in the experimental phase)
[TweakVirtioBlkDataPlane.py](https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/vmTweakVirtioBlkDataPlane.py)

I am not sure which is the issue# that address the feature request to have an interface to alter the VM XML. @rsmontero could hint here - something like a template interface or similar for the domain XML could be used in this case too...

**Comment by vholer** [comment]
Qcow2 resize was fixed in https://github.com/OpenNebula/one/issues/1585. This ticket addressed problems related to the Qcow2 save-as. For now, I can't see any problems with QEMU/libvirt on upcoming Ubuntu 18.04, which we are targeting with these fixes.

**Comment by MichaelJTokarev** [comment]
despite this bug is closed, it's still worth to mention that the whole initial "issue" here is wrongly understood, it seems. It is (or was, at the time) a Very Bad Idea ™ to resize an image which is currently in use. If you resize it using external qemu-img while it is open and used by a qemu-system process, you'll likely have one or another way or data corruption. If you want to resize it, you need to ask the qemu instance which is using it to resize it, so it also know about the new size. So removing locking is definitely NOT a solution.
