### ISSUE TITLE
Improve vip.sh 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1450]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5520, https://dev.opennebula.org/issues/5520
Original Date: 2017-10-31

---

This issue is to include the list of all single-instance service in a HA cluster in the vip.sh. This script needs to start/stop those services on leadership changes.

```
--- a/share/hooks/raft/vip.sh
+++ b/share/hooks/raft/vip.sh
@@ -23,12 +23,22 @@ leader)
         sudo arping -c 1 -A -I $INTERFACE ${IP%%/*}
         sleep 1
     done
-    oneflow-server start
+    #---------------------------------------------------------------------------
+    # This services MUST run one instance per cluster. Uncomment those you are
+    # services in your cloud
+    #---------------------------------------------------------------------------
+    #oneflow-server start
+    #onegate-server start
     ;;
 
 follower)
     sudo ip address del $IP dev $INTERFACE
-    oneflow-server stop
+    #---------------------------------------------------------------------------
+    # This services MUST run one instance per cluster. Uncomment those you are
+    # services in your cloud
+    #---------------------------------------------------------------------------
+    #oneflow-server stop
+    #onegate-server stop
     ;;
 
 *)

```

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-31T15:06:25Z

---

Maybe it would be a good idea to rename this script to vip.sh.skel and let admins to copy and customize it

**Comment by vholer** [comment]
`vip.sh` was improved as part of #1737 to better deal with ONE Flow/Gate services. Closing.
