### ISSUE TITLE
Make OpenNebula a first class citizen of OpenNebula

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1454]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5524, https://dev.opennebula.org/issues/5524
Original Date: 2017-11-01

---

OpenNebula should be able to use other OpenNebula cloud: as a hybrid cloud host like for example "Amazon EC2". Use Case: build a hybrid cloud based on OpenNebula spread across different OpenNebula intances _WITHOUT_ a mutual trust relationship as is required for Federation. OpenNebula providers can sell unused capacity easily to 3rd party.

**Comment by juanmont** [comment]
## Description
This new feature may provide the possibility of creating a new virtual machine instance in a remote cloud through local OpenNebula cloud.

## Use case
You need to create a new VM in a remote Cloud but you want to work with it through OpenNebula.

The users need it when they need create a VM in another Cloud infrastructure.

## Interface Changes
You need to include a new driver for manage VMs and Images, also need to add this new managers to oned.conf. For other hand, you need to add new inputs in Sunstone to permit add the remote credentials and endpoint into the local host.







# Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
