### ISSUE TITLE
Ceph volatile disks

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1456]
---

Author Name: **Anton Zubkov** (Anton Zubkov)
Original Redmine Issue: 5526, https://dev.opennebula.org/issues/5526
Original Date: 2017-11-01

---

Try add volatile disks to VM but get error:
@Mon Oct 30 22:36:56 2017 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy ‘/var/lib/one//datastores/100/106/deployment.1’ ‘node4’ 106 node4
Mon Oct 30 22:36:56 2017 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/100/106/deployment.1
Mon Oct 30 22:36:56 2017 [Z0][VMM][I]: error: Cannot access storage file ‘/var/lib/one//datastores/100/106/disk.2’ (as uid:9869, gid:9869): No such file or directory
Mon Oct 30 22:36:56 2017 [Z0][VMM][E]: Could not create domain from /var/lib/one//datastores/100/106/deployment.1
Mon Oct 30 22:36:56 2017 [Z0][VMM][I]: ExitCode: 255
Mon Oct 30 22:36:56 2017 [Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
Mon Oct 30 22:36:56 2017 [Z0][VMM][E]: Error deploying virtual machine: Could not create domain from /var/lib/one//datastores/100/106/deployment.1@

**Comment by jonathan-dove** [comment]
This is still an issue

**Comment by rsmontero** [comment]
Hi @jonathan-dove

Could you share your datastore configuration. Also could you share the complete log file for the VM?
