### ISSUE TITLE
vcenter network should use ONE_MANAGED attribute

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1463]
---

Author Name: **Sergio Semedi** (Sergio Semedi)
Original Redmine Issue: 5533, https://dev.opennebula.org/issues/5533
Original Date: 2017-11-03
Original Assignee: Sergio Semedi

---

We can use ONE_MANAGED attribute in networks context so:

U import a vcenter network => ONE_MANAGED should be 0
U create a vcenter network from opennebula => ONE_MANAGED should be 1

Also the proper hooks needs to be modified to adopt the new behaviour

**Comment by tinova** [comment]
Merged, let's wait for the tests
