### ISSUE TITLE
Error checking capacity while importing image

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1467]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 5537, https://dev.opennebula.org/issues/5537
Original Date: 2017-11-07

---

The CHECK_CAPACITY flag should be disabled, but only for vCenter datastores, and only for import.

**Comment by rsmontero** [comment]
duplicated  #1880
