### ISSUE TITLE
Cluster update dialog breaks RESERVED_* attributes

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1468]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5538, https://dev.opennebula.org/issues/5538
Original Date: 2017-11-07

---

RESERVED_CPU, if set to -20000, changes to -100%

**Comment by rsmontero** [comment]
Merge to master+one-5.4. Updated documentation  (fixed issues for next hot-fix)
