### ISSUE TITLE
Sunstone: Autorefresh feature

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1472]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5542, https://dev.opennebula.org/issues/5542
Original Date: 2017-11-08
Original Assignee: Abel Coronado

---

Need to implement caching and "autorefresh" feature, for see state updates in live time

Connected with this thread:
https://forum.opennebula.org/t/autorefresh-feature-is-not-working/4206/7

And this bug report:
https://dev.opennebula.org/issues/5135

**Comment by rsmontero** [comment]
Caching is implemented, autorefresh may stress the server with unneeded requests

**Comment by kvaps** [comment]
Hey, this is really wanted function.

I have seen many times how a user creates a new machine,
and then he sit and clicks on the refresh button (about 25 times) when vm is not going to running state

This adds 25 additional XML-RPC requests to main server.
But with this function it can be far less.

About implementation:
We can add only one common request for states for all existing resources regardless of the user.
For example run `one.vmpool.info` each time in 15 seconds period by oneadmin account, and cache only states information somewhere in sunstone backend.
Frontend can query theese statuses any time automatically.
So, for each resource sunstone know current state, and can ask backend for "if state is changed", and if it so, sunstone can ask new detail information directly from server.

**Comment by daledude** [comment]
Having to click a refresh button is, to be frank, ridiculous. 1990 want's it refresh button back.

**Comment by abelCoronado93** [comment]
We have added this feature to the roadmap 

https://github.com/OpenNebula/one/issues/2410
