### ISSUE TITLE
Premigrator: images registered through templates must have the same permissions

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1474]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5544, https://dev.opennebula.org/issues/5544
Original Date: 2017-11-13
Original Assignee: Tino Vázquez

---

In OpenNebula 5.2:

- Template in vCenter and in OpenNebula
- The vCenter template contains a disk
- This disk does not exist in OpenNebula
- The template in OpenNebula has a specific owner/group/permissions

When running the premigrator for 5.2 -> 5.4

- The image is registered in OpenNebula
- The owner/group/permissions are oneadmin/oneadmin/0600 instead of that of the Template

**Comment by tinova** [comment]
Fixed in this PR https://github.com/OpenNebula/one/pull/2264
