### ISSUE TITLE
Display quotas in Cloud View

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1478]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5548, https://dev.opennebula.org/issues/5548
Original Date: 2017-11-13

---

In:

 - Dashboard
 - VM creation dialogs

**Comment by abelCoronado93** [comment]
Duplicated https://github.com/OpenNebula/one/issues/1546
