### ISSUE TITLE
CPU monitoring in EC2 (CloudWatch) intermittent failures

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1484]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5554, https://dev.opennebula.org/issues/5554
Original Date: 2017-11-15

---

Due to no datapoint set returned on some API calls.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Date: 2017-11-15T15:22:07Z

---

The attached driver does not clear the CPU value if the API call does not return datapoints

**Comment by tinova** [comment]
fixed in one-5.4 and master
