### ISSUE TITLE
Disk size slider should allow TB units

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1487]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5557, https://dev.opennebula.org/issues/5557
Original Date: 2017-11-16

---

Now only MB and GB are allowed.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- One: https://github.com/OpenNebula/one/pull/4804
- Docs: https://github.com/OpenNebula/docs/pull/1144
- Tests: https://github.com/OpenNebula/development/pull/1025

**Comment by jloboescalona2** [comment]
@tino PR to approve:

ONE: #4855
TEST: OpenNebula/development#1046
