### ISSUE TITLE
Security Groups should not be enabled when creating an Open vSwitch network

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1491]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 5561, https://dev.opennebula.org/issues/5561
Original Date: 2017-11-17

---

Currently the Security Groups tab is disabled when the user selects a vCenter network. The same thing should happen with Open vSwitch.

**Comment by rsmontero** [comment]
master + one-5.4. 5.4.6 release notes updated
