### ISSUE TITLE
RFE for openvswitch over vxlan

### ISSUE THREAD

**Issue by Madko** [OpenNebula/one#1498]
Hi,

This is more a RFE than a bug report 

# Bug Report
## Version of OpenNebula
_Mark the relevant versions affected with [X]_
- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component
_Mark the relevant versions affected with [X]_
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [X] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter

# Enhancement Request
## Description

I've made some modification on the ovswitch driver to be able to use VXLAN under OVS. The main benefit is that you can isolate VLAN inside a VXLAN (or VNI). Which mean we can use 4096 VLANs x Number of VNI (which means a LOT).

I first tried to make a new custom vnet driver, because I didn't want to break the original ovswitch driver. But it's not possible since the generated XML can only be ovs tainted if the vnet driver is called "ovs". cf https://forum.opennebula.org/t/custom-vnet-driver/4046
So I had to modify the ovs vnet driver. 

With those modifications in the ovs driver you can use the ovs driver the same way as before (ie specifying VLAN_ID, VLAN_TAGGED_ID). But you can also add some attributes like VNI. If this VNI attribute is present, it will create a new OVS bridge (brvxVNI) with a special interface inside for the vxlan tunnel. I took the same logic from the vxlan vnet driver for calculating VXLAN Multicast group address.

It works now for maybe 6 months and we are very happy with it. So I was wandering if you were interested ?

Best regards,
Edouard

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by hydro-b** [comment]
> 
> I've made some modification on the ovswitch driver to be able to use
> VXLAN under OVS. The main benefit is that you can isolate VLAN inside
> a VXLAN (or VNI). Which mean we can use 4096 VLANs x Number of VNI
> (which means a LOT).
> 
> I first tried to make a new custom vnet driver, because I didn't want
> to break the original ovswitch driver. But it's not possible since the
> generated XML can only be ovs tainted if the vnet driver is called
> "ovs". cf https://forum.opennebula.org/t/custom-vnet-driver/4046 So I
> had to modify the ovs vnet driver. 
> 
> With those modifications in the ovs driver you can use the ovs driver
> the same way as before (ie specifying VLAN_ID, VLAN_TAGGED_ID). But
> you can also add some attributes like VNI. If this VNI attribute is
> present, it will create a new OVS bridge (brvxVNI) with a special
> interface inside for the vxlan tunnel. I took the same logic from the
> vxlan vnet driver for calculating VXLAN Multicast group address.
> 
> It works now for maybe 6 months and we are very happy with it. So I
> was wandering if you were interested ?

Yes. I have tested combining "OVS" and linux kernel "VXLAN" to use VXLAN
on a otherwise "OVS" host. This works, but I would rather have
"everything" OVS really. So this OVS-VXLAN driver would be a nice
"intermediate" solution between "OVS VLAN" on one side and "OVS / OVN"
(incl. L2 / L3) on the other side of the networking spectrum (no support
in ONE for OVN as of yet).

Can you share your driver somewhere? I would be happy to test it.

On a technical note: how do you make sure all P2P vxlan tunnel(s) are
available between all hypervisors. Is that covered by the current vxlan
methodology?

On a side note: do you have any issues with network traffic leaks
during VM live-migration
(https://github.com/OpenNebula/one/issues/1177#issuecomment-345665758).

Would integrating the "network" part directly into the VM libvirt XML
make you driver easier to implement?

Gr. Stefan

**Comment by Madko** [comment]
When a VM is started on an hypervisor the driver pre script is executed. This pre script use a lightly modified class OpenvSwitchVXLAN instead of the OpenvSwitch. In this class, it ensures that the bridge dedicated to the VNI is up (create_bridge), and checks for the tunnel interface (create_vxlan_tunnel). This create_vxlan_tunnel is mostly from the VXLAN driver. So now on this hypervisor you should have

```
brvxXXXXX (VNI)
  + vxXXXXX (tunnel end-point, with VNI and associated multicast group)
  + one-yyyy-0
```

So if another VM on the same VNET is created on an other hypervisor, same logic. So it will end with 2 ovs bridge on different host, but using the same multicast group to discover each other. If I recall correctly the multicast group is calculated from the VNI, this logic is from the vnet VXLAN driver. So on the second hypervisor:

```
brvxXXXXX (same VNI)
  + vxXXXXX (tunnel end-point, with VNI and associated multicast group, same as hypervisor 1)
  + one-zzzz-0
```

Real life example:
```
	brvx30600:
		brvx30600 65534/27: (internal)
		one-3887-1 2/30: (system)
		one-3887-2 3/31: (system)
		vx30600 1/28: (system)

# ip -d a show dev vx30600
194: vx30600: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8950 qdisc noqueue master ovs-system state UNKNOWN qlen 1000
    link/ether ee:6b:ae:70:ce:a5 brd ff:ff:ff:ff:ff:ff promiscuity 1 
    vxlan id 30600 group 239.0.119.136 dev vlan4060 srcport 0 0 dstport 8472 ttl 16 ageing 300 
    openvswitch_slave
```

The PHYDEV attribute is used to know which physical interface (here vlan4060) is used on the hypervisor for the overlay traffic (vxlan tunnels). Of course, the name of this interface must be the same on all the hypervisors.

And as you may know, multicast is only use for the broadcasted traffic between the VM. As soon as the FDB is populated (thanks mostly to arp broadcasts from the VMs), it's then unicast traffic between the hypervisors having the concerned VM interface MAC address. 

I haven't notice any particular issue during live-migration. Sometimes we loose 1 or 2 packets, but it's the same with any kind of live migration so... I will look more into details about the comment #1177 

My concern with OVN is that you can't use VLAN tagging anymore inside the VM, because vlan tagging is reserved exclusively for containers (at leat last time I checked, some openflow rules use vlan tagging to route the traffic to containers, using vlan ID as containers ID I guess). Our use case with this OVS+VXLAN driver is to isolate VM inside a VLAN domain (=one VNI for 4096 vlan), to reproduce/simulate datacenter and/or real production environment. So we need to tag interfaces inside the VM.

If it was possible to integrate the OVS part in the VM libvirt XML from any kind of vnet driver, it would be nice, so anyone would be able to keep the official OVS driver (ovswitch), and add this one aside. And maybe people will be interested to have this ability, to copy ovswitch and adapt it more easily. But concerning this OVS+VXLAN driver, it won't change anything, since the OVS part in the VM libvirt XML is the same.

I will add my driver soon, but it's a quick and dirty hack, I have to clean it a bit. Sorry for the long post ;)

**Comment by Madko** [comment]
The file is here https://drive.google.com/open?id=14F4D7Il7SDZRyFeKik8GYExv9F1crMYj

And you have to add:
`INHERIT_VNET_ATTR       = "VNI"`

in the oned.conf to pass this attribute to the vnet driver.

**Comment by hydro-b** [comment]
On Tue, Nov 21, 2017 at 01:04:45PM +0000, Edouard Bourguignon wrote:
> 
> I haven't notice any particular issue during live-migration. Sometimes
> we loose 1 or 2 packets, but it's the same with any kind of live
> migration so... I will look more into details about the comment #1177 

I guess with your VXlan method the NIC gets added to the vxlan "bridge"
(vlan4096 in your example) instead of the real OVS bridge and traffic
might be ignored in that VLAN if it's not vxlan tagged (VNI).

> My concern with OVN is that you can't use VLAN tagging anymore inside
> the VM, because vlan tagging is reserved exclusively for containers
> (at leat last time I checked, some openflow rules use vlan tagging to
> route the traffic to containers, using vlan ID as containers ID I
> guess). Our use case with this OVS+VXLAN driver is to isolate VM
> inside a VLAN domain (=one VNI for 4096 vlan), to reproduce/simulate
> datacenter and/or real production environment. So we need to tag
> interfaces inside the VM.

You cant' use VLAN tagging, as in a true "TRUNK" port at the moment in
ONE, see:
https://github.com/OpenNebula/one/issues/1433#issuecomment-345678823

In your simulation of production traffic inside the "VXlan
VLAN" you don't need this I guess.

> If it was possible to integrate the OVS part in the VM libvirt XML
> from any kind of vnet driver, it would be nice, so anyone would be
> able to keep the official OVS driver (ovswitch), and add this one
> aside. And maybe people will be interested to have this ability, to
> copy ovswitch and adapt it more easily. But concerning this OVS+VXLAN
> driver, it won't change anything, since the OVS part in the VM libvirt
> XML is the same.
> 
> I will add my driver soon, but it's a quick and dirty hack, I have to
> clean it a bit.

Cool, I'll watch out for it then.

> Sorry for the long post ;)

NP, I'm one of those rare folks that appreciate a "wall of text" with
detailed info ;).

Gr. Stefan

**Comment by Madko** [comment]
I forgot to add a vnet definition example :
```
BRIDGE = "brvx10001"
DESCRIPTION = "datacenter 1"
PHYDEV = "vlan4060"
SECURITY_GROUPS = "0"
VLAN_ID = "1300"
VLAN_TAGGED_ID = "1200,1210,1220,1230,1300,1310,1320,1330"
VNI = "10001"
VN_MAD = "ovswitch"
```

This create a vnet inside the VXLAN 10001, and allowing traffic on VLANs  200,1210,1220,1230,1300,1310,1320,1330, with default VLAN ID 1300 for untagged traffic.

You can mix that with other VNET, and if you share the same VNI + VLAN the VMs will be able to communicate.

**Comment by Madko** [comment]
Hi
just to mention that if VNI means 1 multicast group, which is working fine (and more simple to deal with), you could end with many multicast groups on your hypervisor. Linux kernel limits by default to 20 MG memberships. So that would be great to mention that in the documentation. The kernel error message is not very trivial to understand (ie RNET_LINK no space buffer available or something like that).
Hopefully, the max number of multicast group membership can be overriden with net.ipv4.igmp_max_memberships (we have set something like 400 instead of 20 and it works fine so far).

If you need to deal with even more networks (and less multicast groups), I guess multiple VXLAN can use the same multicast group. Then the VNI + UDP port could be used to differentiate VNETs.

Best regards,
Edouard

**Comment by vholer** [comment]
Hi Edouard, the multicast groups limitation is already mentioned in the documentation http://docs.opennebula.org/5.6/deployment/open_cloud_networking_setup/vxlan.html#concurrent-vxlans-host-limit. User of the new Open vSwitch VXLAN driver needs to be familiar with both OvS and VXLAN drivers as mentioned in the documentation http://docs.opennebula.org/5.6/deployment/open_cloud_networking_setup/openvswitch_vxlan.html. Thank you, Vlastimil

**Comment by Madko** [comment]
Oops sorry, this doc is perfect :)

**Comment by Madko** [comment]
Sorry guys, I spoke too fast again. It works with VLAN_TAGGED_ID. So I will just open a ticket about sunstone about that.

**Comment by vholer** [comment]
You mean this ticket? https://github.com/OpenNebula/one/issues/2300

I do understand there is no problem with the driver and everything is clear now. If not, plesae don't hesitate to reopen the issue. It's hard to track the conversations in closed issues. Thanks.
