### ISSUE TITLE
Instantiate VM instance persistent

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#1501]
# Bug Report
## Version of OpenNebula
_Mark the relevant versions affected with [X]_
- [X] 5.2.2
- [X] 5.4.0
- [X] 5.4.1
- [X] 5.4.2
- [X] 5.4.3
- [X] Development build

## Component
- [X] Core (oned)

## Description
Just like "IMAGES" (DEFAULT_IMAGE_PERSISTENT / DEFAULT_IMAGE_PERSISTENT_NEW), it should be possible to instantiate VMs persistent by default. In sunstone views there is the possibility to show the "instancd persistence", but no option to make it the default for all newly created instances:

"# True to show the option to make an instance persistent
   instantiate_persistent: true"

## How to reproduce
N/A

# Enhancement Request
## Description
When "DEFAULT_INSTANCE_PERSISTENT_NEW=true" all created VMs should be instantiated with persistent disks. Using a template with a non-persistent disk should result in VMs with a persistent CLONE (copy) of this IMAGE. When the size of this IMAGE is changed during instantiation, it should be resized on the fly. Relates to https://github.com/OpenNebula/one/issues/1185.

## Use case
In environments where most, if not all, created VMs are pets (as opposed to cattle) it makes sense to create all instances with persistent disks.

**Comment by juanmont** [comment]
This is in fact a reasonable feature. However in 5.6 we want to revisit the whole concept of save_as template and instantiate as persistent.

Rigth now we have two options to achieve the same thing, let a user preserve this changes, namely:
* Copy the VM state (disk, template...) **before** instantiaing it
* Copy the VM **after** making the modifications

We aim at keeping one and improve it. We'll keep this issue open to take this into consideration for 5.6 discussions.

**Comment by rsmontero** [comment]
Related to #1327

**Comment by jloboescalona2** [comment]
@tinova PR to approve:

Code: OpenNebula/one-ee#948
Docs: OpenNebula/docs#1509
