### ISSUE TITLE
onevm disk-resize should specify units in man page and give correct error message

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#1509]
_Complete **only one section**: Bug Report -OR- Enhancement Request_

# Bug Report
## Version of OpenNebula

- [?] 5.4.0
- [?] 5.4.1
- [?] 5.4.2
- [ ] 5.4.3

## Component
- [X] Command Line Interface (CLI)
## Description
1) onevm disk-resize command does not specify the allowed units in which you can resize the DISK IMAGE.
2) onevm disk-resize command gives an error about "argument 2", but according to man page this should be "argument 3", as "<size>" is the 3rd argument:

* disk-resize <vmid> <diskid> <size>
        Resizes a VM disk. The new size should be larger than the old one.

### Expected Behavior
1) Documentation should be clear on which units are available.
2)onevm disk-resize 1592 0 1T
Size value malformed
command disk-resize: argument 3 must be one of size

### Actual Behavior
$ onevm disk-resize 1592 0 1T
Size value malformed
command disk-resize: argument 2 must be one of size
## How to reproduce
Try to resize a VM DISK IMAGE like in Actual behaviour. 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
Hello,

We have decided to introduce only the change about accepting Terabytes as size, but we do not think it is a good practice to change the number of the argument that will be shown, because always the first element is the element 0.

Regards!
