### ISSUE TITLE
Better DashBoard for Sunstone

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#1511]
# Enhancement Request
## Description
Redesign the Dashborad to include sensible information. Also for a big number of VMs the accounting widget is taking too much time to load. 

## Use case
N/A

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment]
To replace the current dashboard without HISTORY_RECORDS, we have the information of the VMs.
I have thought about a lighter redesign, where the different states of the VMs will be represented with the amount of them. 
![donut-states](https://user-images.githubusercontent.com/11613052/33208478-f494a820-d111-11e7-84d2-036a1f6188ce.png)
e.g.:
- Red: FAILURE
- Green: RUNNING
- Orange: PENDING
- Blue: POWEROFF

It's just an idea to improve high load times with large clouds. 
Any opinion will be well received.
