### ISSUE TITLE
Premigrator fiddles with DB encoding

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1519]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter
- [X] Upgrade

## Description

vCenter premigrator changes DB encoding, causing oned and sched errors

## How to reproduce

upgrade from 5.2 to 5.4 with non-extended ASCII

**Comment by rsmontero** [comment]
Duplicated by #1557
