### ISSUE TITLE
Monitoring error. Any stderr from `virsh domblkstat` command should be filtered.

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1524]
# Bug Report
## Version of OpenNebula
- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [X] 5.4.3
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [X] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter

### Expected Behavior
Monitoring script should return clean information for each host.

And even virsh have some stderr stream it should be filtered.

### Actual Behavior
All stderr returned with monitoring information so opennebula can not parse this outuput and we have errors like that:

```
Sat Nov 25 20:45:57 2017 [Z0][ONE][E]: Error parsing host information: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 1, columns 5:11. Monitoring information:
error: internal error: cannot find statistics for device 'ide0-0-1'
ARCH=x86_64
MODELNAME="Intel(R) Xeon(R) CPU E3-1284L v4 @ 2.90GHz"
HYPERVISOR=kvm
TOTALCPU=800
...
```

## How to reproduce

* Just add empty cdrom into kvm's `RAW=` into vm
* Or eject cd from existing cdrom using `virsh change-media` command

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
PR here:
https://github.com/OpenNebula/one/pull/1526

**Comment by rsmontero** [comment]
to be backported to one-5.4
