### ISSUE TITLE
onedb show-body update-body change-body datastore support

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#1528]
# Enhancement Request
onedb show-body update-body change-body datastore support

## Description

Extend commands by support datastores

## Use case

I periodically need to update BRIDGE_LIST when I do rolling updates of compute nodes. I have 8 gfs2 datastores and I found, that if I did not remove node from BRIDGE_LIST pacemaker stop opperation can fail result in node fence. So I have to each time for each node update BRIDGE_LIST manualy.

**Comment by atodorov-storpool** [comment]
I think it is not needed because if I am not wrong the `onedb <something>-body` tools are for altering the metadata entries in the database (the <something>_pool tables). For the datastore I am successfully updating datastore with append from template file as follow:

```bash
echo "BRIDGE_LIST=\"host1 host3\"" >ds.template
onedatastore update $DS_ID --append ds.template
```
BR,
Anton

**Comment by feldsam** [comment]
Thank you for hint
