### ISSUE TITLE
DHCP configuration for networks

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#1529]
# Enhancement Request
## Description
Option to configure the network interfaces as DHCP clients via the contextualization 

## Use case
Useful  when OpenNebula is used to assign only MAC address to the VM networks and external DHCP is managing the IP addresses.

**Comment by rsmontero** [comment]
Should consider motorization of used IP's see #1279

**Comment by hydro-b** [comment]
+1. We also have certain VM's using external DHCP.

**Comment by atodorov-storpool** [comment]
Also it could be handy to display the MAC in sunstone and cli for the networks that has no IP assigned by ONE (and the qemu-ga probe has no updates)

**Comment by rsmontero** [comment]
This should be implemented as part of #1383 , we'll use that to track changes
