### ISSUE TITLE
Interface to tell OpenNebula that there are issues from third party services in a host

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#1530]
# Enhancement Request
## Description
Interface to tell OpenNebula that there are issues with additional services.

## Use case
An alarm should be set for a host when there are issues with third-party but relevant services:
* shared datastore (say NFS) is not actually mounted or is inaccessible(readonly, etc...)
* CEPH or other SDS service has issues that could be reported by additional script

At first glance setting the host state to ERROR when such a "flag" is found should be sufficient. In this case the FT script on HOST_ERROR should take care how to deal with the situation. It just needs to be notified that it is the case.

**Comment by rsmontero** [comment]
Hi @atodorov-storpool 

Maybe I'm missing something but I think we can implement this with the current interface. For example in the past we have automated the addition of new hosts by executing onehost commands from the hypervisor.

For example, you can develop a probe like:

```
ERROR_CONDITION=$(third_party_monitor)

if [ -n "$ERROR_CONDITION" ] ; then
  onehost offline $hostname
fi

echo "ERROR_THIRD_PARTY=\"$ERROR_CONDITION\"" 
```
This way you'll have the ERROR_THIRD_PARTY string as well as the hostname set offline.

**Comment by rsmontero** [comment]
Yes I'd just drop it in kvm-probes.d
