### ISSUE TITLE
Sunstone is killed by OOM Killer when uploading large images

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1532]
# Bug Report
## Version of OpenNebula
- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1 (from ubuntu repo)
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter

## Description
If you upload large image file through web-uploader, ruby process is eat all available memory in RAM.
Often it was killed by OOM Killer.
```
/usr/bin/ruby /usr/lib/one/sunstone/sunstone-server.rb
```

### Expected Behavior

Sunstone, when uploading large image, is loading it gradually without puting all image into RAM.

### Actual Behavior

Sunstone dead because no free memory in RAM

## How to reproduce

* Reduce machine memory to 4GB
* Upload image large than 4GB
* If not work, upload multiple images in one time

**Comment by kvaps** [comment]
Yes, I forgot to say that I use nginx-server as https-proxy with configuration like that:
https://forum.opennebula.org/t/vnc-with-sunstone-behind-nginx-proxy/426/27?u=kvaps

There is no problem with nginx, the problem only with `sunstone-server.rb` process

**Comment by tinova** [comment]
did you try  using Apache with Phusion Passenger? Closing for the time being until confirmation.
