### ISSUE TITLE
Import multi-cluster networks

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#1538]
# Enhancement Request
## Description

Networks and distributed switches in vCenter can span across multiple vCenter clusters, which are modeled as OpenNebula clusters.

At network import time, if more than one vCenter cluster is imported in OpenNebula, and the network belongs to these clusters, an option to import the virtual network into the different OpenNebula clusters should be presented

## Use case

Full use of Networks that span across different vCenter clusters

## Interface Changes

* onevcenter import 
* Sunstone network from vcenter import dialogs

**Comment by Semedi** [comment]
Whe should improve this feature following the next use case:

## Use case
* You need to import a net that belongs to two or more clusters.
* You dont have all of these cluster imported into ONE.
* ONE should ask you about import the other clusters

**Comment by tinova** [comment]
# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
[ ] Sunstone network import in multiple cluster will be treated in #1653
 [ ] Hooks for network creation won't support multi cluster creation
 [ ] Improve hooks for network creation opportunistically
 [ ] Merge multi network creation functionality (Sergio's knows)

**Comment by tinova** [comment]
Sunstone missing

**Comment by rsmontero** [comment]
Sunstone network import in multiple cluster will be treated in #1653
