### ISSUE TITLE
Permit to rename disks and disk-snapshots inside created VM

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1539]
# Enhancement Request
## Description
It would be nice for allow rename of disks inside vm, basically if it non persistent.

## Use case
Users can set self user-friendly names for disk after attaching

## Interface Changes

**XML-RPC API:**

 * add new `one.vm.diskrename` method, it will same like `one.vm.disksaveas`
 * add new `one.image.snapshotrename` method with `string:<session>` `i4:<image_id>` `i4:<snap_id>`, `string:<new_name>` arguments

**Sunstone:**

 * Add new button: 🖉 -  for rename disk or disk-snapshots 

**Cli:**

*
    ```
    onevm disk-rename <vmid> <diskid> <name>
          -s, --snapshot snapshot   ID of the Snapshot to rename.
    ```
*
    ```
    oneimage rename <imageid> <name>
          -s, --snapshot snapshot   ID of the Snapshot to rename.
    ```

**Comment by juanmont** [comment]
It's a good idea but, for the moment, you can use the command `onedb update-body vm --id <vmid>` and change the attribute SNAPSHOT/NAME.

release 5.4.3
