### ISSUE TITLE
Migrate VM between vCenter Datastores

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#1540]
# Enhancement Request
## Description

VMs should be allowed to migrate between different vCenter datastores

## Use case

dynamic rebalance of load between a loaded DS and an empty one

## Interface Changes

Needs new XMLRPC option (maybe we can reuse migrate). Also support from Sunstone and CLI

**Comment by atodorov-storpool** [comment]
I think #1425 looks like a corner case of this one?
It is possible to do this with storpool on kvm but I think a new state/flag/whatever is needed so vmm/kvm/migrate and tm/{pre/post/fail}migrate to recognize and handle the state/command.

**Comment by amenendezASAC** [comment]
+1

**Comment by tinova** [comment]
A flag needs to be ser per driver (in oned.conf) to allow live DS migration. It should be disabled in KVM and enabled in vCenter.

**Comment by tinova** [comment]
waiting for tests to close
