### ISSUE TITLE
vCenter hot disk resize

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#1542]
# Enhancement Request
## Description

vCenter allows for hot disk resize, OpenNebula should as well

## Use case

Want to grow my disk while VM is running (probably makes sense for non OS disks)

## Interface Changes

Options in Sunstone and CLI

**Comment by xBytez** [comment]
+1 This is really something critical we need in order to start using one in production.

**Comment by tinova** [comment]
See what support comes from OpenNebula core

See what support do we have in current vCenter drivers

**Comment by xBytez** [comment]
I hacked around in sunstone and removed the frontend if checks that disables live disk resizing for VMware. Nebula resizes the disk live just fine. 

The VM just gets stuck in DISK_RSZ status which you can fix with `onevm recover id --success`

**Comment by tinova** [comment]
Thanks a lot for the feedback! Looks like we are close ;)

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4199

[DOC]
* https://github.com/OpenNebula/docs/pull/945

[TEST]
* https://github.com/OpenNebula/development/pull/847
