### ISSUE TITLE
Federation switch is not work

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1552]
# Bug Report
## Version of OpenNebula
- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1 (from ubuntu repo)
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter

## Description

Can not select another zone from top menu.
![e2ecb144-b5ab-47c0-yb0d-5e3eed0767e7](https://user-images.githubusercontent.com/7556217/33376074-8cf60ba6-d50c-11e7-99e0-d50d3a1e48af.gif)

### Expected Behavior
Switched to the new zone

### Actual Behavior
Not switched to the new zone
No errors in log
No errors in console

## How to reproduce
I used sunstone packages from the ubuntu repo,
and installed federation master and slave nodes using this guide:
https://docs.opennebula.org/5.4/advanced_components/data_center_federation/federationconfig.html

**Comment by kvaps** [comment]
I just checked CLI, and I've got same problem, can not change zone there.

I just see:
```
$ onezone set 100
Endpoint changed to "http://10.29.36.186:2633/RPC2" in /home/kvaps/.one/one_endpoint

$ cat /home/kvaps/.one/one_endpoint
http://10.29.36.186:2633/RPC2
```

but nothing changed, no error output, how to debug it?

**Comment by rsmontero** [comment]
Please check that you are actually pointing to different opennebula instances in your zone configuration (i.e. output in ``onezone show``). You can also look at the oned.log of each OpenNebula to see the API queries. 

Please note that there are some federated information like users, those would be the same. (oneuser list should be the same onehost list should be different).

Also please review that the replication process have been properly done (you may have ended to just clone the master DB).

**Comment by kvaps** [comment]
Hi @rsmontero, I spent a lot of time for find where is problem.

I found that CLI switch is not work if you have `ONE_XMLRPC` variable set in your environment.
If you unset it zone switching will working fine, But you need to have direct access XMLRPC interface from both zones from the client. So probably it's OK.

Next, Sunstone is not requeres direct connection from client to XMLRPC interface, but requeres on server side, this is fine too.

I found bug that sunstone can not be switched to another endpoint if it is run behind nginx proxy server.
So, please move bug from `Core & System` to `Sunstone` category.

**Comment by rsmontero** [comment]
In order to reproduce this, do you have both sunstone-server proxy'ed or just the master or just the slave? Also can you comment on your nginx configuration, is it using SSL, for example?

**Comment by kvaps** [comment]
Hi, I have one susntone-server on separated os, sunstone connected to the master oned.
I have tried to install another one directly on the master and found out that switch is working there.
Then I switched down the proxy, and tried on old one - it's started working too.
Then I have tried to run sunstone directly on `:80` - working too.
Today I have tested to run it behind https proxy - same problem, is not switching.

Configuration:
https://forum.opennebula.org/t/vnc-with-sunstone-behind-nginx-proxy/426/11?u=kvaps

**Comment by rsmontero** [comment]
Can you post your onezone list output? Does the endpoint point to xmlrpc or http proxy?

**Comment by kvaps** [comment]
```
# onezone list
C    ID NAME                      ENDPOINT                                     
*     0 OpenNebula                http://opennebula:2633/RPC2
    100 opennebula2-db            http://opennebula2-db:2633/RPC2
```
> Does the endpoint point to xmlrpc or http proxy?
I have proxy only only for proxing sunstone interface, not xmlrpc so entpoints is set directly to opennebulas.

**Comment by rsmontero** [comment]
OK, thank you we'll try to reproduce your setup to solve this issue

**Comment by aschwoerer** [comment]
Hi, I ran into the same problem with the zone not changing in sunstone interface. I serve the interface with apache2 and mod-passenger. It looks like the problem occurs, because passenger drops the header ZONE_NAME in recent versions, as there were some security issues with underscores in header-names. Could this also be the issue here?

Docs state, that when using nginx as proxy "underscores_in_headers on;" must be set. I guess, this addresses the same issue, as nginx defaults to dropping headers with underscores in its name.

I couldnt find a way to configure passenger to allow underscores.

Would it be possible to change the used header to ZONE-NAME?

It looks like sunstone-server.rb already tries to use ZONE-NAME and only falls back to ZONE_NAME because sunstone sends it clientside.

Thanks 
Andreas

**Comment by tinova** [comment]
We cannot reproduce this. Is it also happening in 5.6?

**Comment by kvaps** [comment]
I can not say for sure, right now I have no federation.

**Comment by tinova** [comment]
Thanks, closing this issue until someone can aids us in reproducing the problem.
