### ISSUE TITLE
Do not resize AR's and let leases out of range

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1553]
_Complete **only one section**: Bug Report -OR- Enhancement Request_

# Bug Report
## Version of OpenNebula

- [X] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [X] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter

## Description

Leases can be let outside of an AR range after a resize

### Expected Behavior
Do not allow AR resize

### Actual Behavior
AR is resized and leases cannot be deleted

## How to reproduce
1. Create AR size > 0
2. Place VMs in that AR-vnet
3. Set AR size == 0
4. Leases are outside of the range and leases > size. Those leases are note freed

**Comment by paczerny** [comment]
It's already fixed in 6.2.0. Solved by [this commit](https://github.com/OpenNebula/one-ee/commit/e8f1a7641cf36831bf5426b1d2f17120ab893d2a)
