### ISSUE TITLE
NetFilter basic tunning

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#1558]
Hello, we are enabling NetFilter on compute nodes in following conf file:

https://github.com/OpenNebula/one/blob/master/share/etc/sysctl.d/bridge-nf-call.conf

Will be good to include some basic netfilter tunning, because on hight traffic sites netfilter is bottleneck and I consider virt-host as high traffic. So what about including some shorter tcp timeouts?

Something like this?

    # default 10
    net.netfilter.nf_conntrack_tcp_timeout_close = 10
    
    # default 60
    net.netfilter.nf_conntrack_tcp_timeout_close_wait = 30
    
    # default 432000
    net.netfilter.nf_conntrack_tcp_timeout_established = 600
    
    # default 120
    net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 60
    
    # default 30
    net.netfilter.nf_conntrack_tcp_timeout_last_ack = 15
    
    # default 300
    net.netfilter.nf_conntrack_tcp_timeout_max_retrans = 150
    
    # default 60
    net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 30
    
    # default 120
    net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 60
    
    # default 120
    net.netfilter.nf_conntrack_tcp_timeout_time_wait = 60
    
    # default 300
    net.netfilter.nf_conntrack_tcp_timeout_unacknowledged = 150

**Comment by rsmontero** [comment]
Hi feldsam,

I think this is a good suggestion, however not sure about doing this by default. I'm going to move this issue to the documentation, and include this hints in the network/tunning guides

**Comment by feldsam** [comment]
makes sense
