### ISSUE TITLE
Missing dependency rubygem-nokogiri causes installation of opennebula-ruby to fail on RHEL 7

### ISSUE THREAD

**Issue by GeraldScott** [OpenNebula/one#1559]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
Installation of opennebula-ruby fails with a missing dependency on rubygem-nokogiri because it is not available in any repos that are available to RHEL 7 subscribers, despite having enabled the RHEL equivalent of the EPEL repo.

### Expected Behavior
Successful installation of all packages with their dependencies when executing
`yum -y install opennebula-ruby`

### Actual Behavior
Installation fails with error message:
`Error: Package: opennebula-ruby-5.4.1-1.x86_64 (opennebula)`
`           Requires: rubygem-nokogiri`

## How to reproduce
Add OpenNebule repo to yum on a RHEL 7 implementation and execute 
`yum -y install opennebula-ruby`

## Work around
Manually download the RPM for rubygem-nokogiri from the RHEL 6 repo [here](https://access.redhat.com/downloads/content/ruby-nokogiri/1.5.0-0.9.beta4.el6cf/x86_64/fd431d51/package) and install it with local install:
`yum localinstall rubygem-nokogiri-1.6.1-1.el7.1.x86_64.rpm`

**Comment by vholer** [comment]
Hi @GeraldScott ,

I'm not sure what RHEL channel equivalent of the EPEL you mean. Can you please provide more details?

Anyway, the EPEL is required for both CentOS and RHEL targets:
http://docs.opennebula.org/5.4/deployment/opennebula_installation/frontend_installation.html?highlight=epel#step-3-installing-the-software

Best regards,
Vlastimil Holer
