### ISSUE TITLE
Saving a relatively big Service Template in SunStone will fail with a "RangeError"

### ISSUE THREAD

**Issue by groothuyse** [OpenNebula/one#1560]
# Bug Report
## Version of OpenNebula
- [ ] 5.2.2
- [X] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
When creating a Service Template in the SunStone client of any substantial size, upon saving, the SunStone server will throw a parsing error. This is solely related to the size of the request and not the format.

Please see: [OneFlowSunStoneRangeErrorForServiceTemplate.zip](https://github.com/OpenNebula/one/files/1526492/OneFlowSunStoneRangeErrorForServiceTemplate.zip) for all relevant error reports and input.

### Expected Behavior
A Service Template should be saved even with a reasonable large size.

### Actual Behavior
The OneFlow API webserver throws a parsing error called 'RangeError'. The complete HTML stacktrace is wrapped by SunStone server in a JSON error. Both of which are attached to this report.

## How to reproduce

1. Download the OpenNebula 5.4.0 VM (https://s3.amazonaws.com/opennebula-sandbox/OpenNebula-5.4-Sandbox-VBOX.ova)
2. Start the VM
3. Login to OpenNebula SunStone client interface
4. Go to: Templates > Services > Hit the [+] sign to add a new service template
5. Add the template from the Advanced tab using the attached ServiceTemplate.json
6. Hit save.

**Comment by denys152** [comment]
The issue appears to happen during form data parsing at oneflow server side. Rack middleware parses parameters into nested array where every parameter points to the next one and then recursively calls normalize_params(...). If depths of recursion reaches 100, the error is raised. Rack performs this action only for 'application/x-www-form-urlencoded' and 'multipart/form-data' content-type. Post requests from gui to /service_template* are sent with content-type 'application/json;encoding=utf8' but when sunstone server resends them to oneflow server by constructing NET:HTTP client, it does not set content-type field of the client despite having default content-type ('application/json') prepared in sunstone-server.rb. This results in NET:HTTP setting the default content-type which is 'application/x-www-form-urlencoded'. This in turn triggers rack form data processing and failure. 
The proposed fix sets content-type to 'application/json' only for /service_template* requests from sunstone to oneflow:
https://github.com/OpenNebula/one/pull/1730

**Comment by rsmontero** [comment]
Thanks for the patch applied to master and one-5.4 branches
