### ISSUE TITLE
KVM Host node network monitoring

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#1566]
https://github.com/OpenNebula/one/blob/8b18be92e3b521dfd3ce4e83cd0efa0c76d25fc2/src/im_mad/remotes/kvm-probes.d/kvm.rb#L70

Hello, I figure out that on one host we have NETRX and NETTX equals zero. So I look into monitoring script and see above line. On that node we have interfaces ens1f0, ens1f1 and ens2. Also we use teaming instead of bonding. So I temporary added `ens` to that regex, but I have question.

Why there is calculating sum of all devices? For ex. if we have eth0 and eth1 bonded to bond0, them there is calculated double NETRX and NETTX. I am right? Is it feature or bug?

**Comment by feldsam** [comment]
Hello @juanmont , regarding to this, above regex should be at least extended to match new interfaces like `ens` and `team`

**Comment by vholer** [comment]
FYI: We'll update the list of new predictable NIC names + drop `bond` (and don't add `team`).
