### ISSUE TITLE
In sunstone when updating the context of a VM the user should be able to update $FILE_DS in "Wizard" mode

### ISSUE THREAD

**Issue by ArnY** [OpenNebula/one#1569]
# Bug Report
## Version of OpenNebula

- [X] 5.2.2
- [X] 5.4.0
- [X] 5.4.1
- [X] 5.4.2
- [X] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

When creating or modifying a template in wizard mode (as opposed to "advanced" mode) the user can select files to add to the context from a table listing all the file the user has access to.  But when the user wants to add files to the context of an existing VM in wizard mode, the only available field is the "init script" field. The FILES_DS selection table and fields are missing.

### Expected Behavior
When a VM has been created, the wizard view should allow the user to select new files to add to the context of the VM by presenting the same selection table as in the template configuration.

### Actual Behavior
The user can only modify the FILE_DS value from the advanced view

## How to reproduce

1- instantiate a VM from an existing template
2- stop the VM
3- click on the "Conf" tab of the VM, then on the "Update configuration" button then on the "Context" tab and then on the "Files" vertical tab
4- The only available file is "init scripts" when the user should also have the FILES_DS field and file selection table.

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment]
Hello,

The context file is generated before the VM is launched. With the VM already instantiated it is no longer possible to add a FILE.

Regards.
