### ISSUE TITLE
add DEFAULT_ATTACH_IO when attaching a disk

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#1570]
# Enhancement Request
## Description
Add default value for IO on attached disks

## Use case
It is needed to set io=native when hot attaching VM disks

## Interface Changes
A variable should be set in _/var/lib/one/remotes/vmm/kvm/kvmrc_ `DEFAULT_ATTACH_IO=native`

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
The pull request is following shortly

**Comment by vholer** [comment]
Already fixed by #1769, closing.
