### ISSUE TITLE
Enhancement Request: hook for NIC actions : attach/dettach

### ISSUE THREAD

**Issue by ArnY** [OpenNebula/one#1575]
# Enhancement Request
## Description
It would be useful to be able to trigger hooks when attaching / dettaching NICs. For exemple to update or delete the IP associated with the NIC from the DNS. This would not conflict with the IPAM driver since it would not be involved with the ip pool management.

## Use case

We are currently creating a DNS record when the VM is instantiated with the CREATE hook. But when a user update the security groups associated with their VM's NIC(s) the ip might of the NIC(s) might change and the DNS record is then obsolete. Hooks on NIC attach/dettach would allow us to keep our  DNS in sync with the VMs

## Interface Changes
This would not require any interface change as far as I know?

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
For online action you can use this hook:

```#VM_HOOK = [
#   name      = "update_dns",
#   on        = "CUSTOM",
#   state     = "ACTIVE",
#   lcm_state = "HOTPLUG_NIC",
#   command   = "update_dns.sh",
#   arguments = "$ID $TEMPLATE",
#   remote    = "no" ]
```
For offline attach nic, there is no way for call hook now, but you can call it each time when vm is booting.
There is another feature request for make it possible even for offline mode:
https://github.com/OpenNebula/one/issues/655

**Comment by ArnY** [comment]
Thanks @kvaps this is good enough for me. I'll close the issue!
