### ISSUE TITLE
DevOps tools integration

### ISSUE THREAD

**Issue by izenk** [OpenNebula/one#1578]
### Please do not judge strictly - this is not a bug report, but a question.

Unfortunately, I tried to ask it on official forum https://forum.opennebula.org/, but process stuck on review for a 2 weeks.. So, please if there are any other resources with actual info, please guide me.

Im looking at opennebula as possible candidate for private cloud. One of the major criteria is existence of different integrations with devops tools, to simplify and automate infrastructure provisioning:

- terraform providers
- chef/ansible modules and libraries
- python/ruby/etc libraries and so on..

I couldn't find any examples of ready to use integrations.
Some of them are present (for example [python](https://github.com/python-oca/python-oca),[terraform](https://github.com/runtastic/terraform-provider-opennebula), but they are out of date and look like not supported. What is the situation with it for opennebula? Did I miss some information.

**Comment by juanmont** [comment]
First inform you that the forum is not a forum with reviews, each one is free to open a topic at any time, if your topic has not been published, it could have been due to some problem, Can you put here the link of your subject in forum?
Later I will close this issue because it is not an issue, if you do not care.

**Comment by izenk** [comment]
I have no link to topic, I only have private message:
<pre>
Our automated spam filter, Akismet, has temporarily hidden your post in OpenNebula devops tools integration for review.
A staff member3 will review your post soon, and it should appear shortly.
We apologize for the inconvenience.
</pre>

And after it no any new feedbacks..

**Comment by juanmont** [comment]
sorry for the problem of the revision, we have already published your topic and we have modified the date so that it is more visible.

This is the link: https://forum.opennebula.org/t/opennebula-devops-tools-integration/5317

**Comment by izenk** [comment]
Greate! Thank you. Im closing this "issue"
