### ISSUE TITLE
 Resize disk leads to qcow2 corruption 

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#1585]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [x] 5.4.3 (proably 5.4.x as well)
- [x] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [x] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
Resize disk leads to qcow2 corruption and VM interruption

### Expected Behavior
Disk IMAGE gets resized without VM interruption / IMAGE corruption
## How to reproduce
Use disk-resize on a VM with a Qocw2 image while it is in the "RUNNING" state. Some disk IMAGES get corrupted instantly but OpenNebula will report succes and report new size. You will find qemu logging with corruption message:

qcow2: Marking image as corrupt: Preventing invalid write on metadata (overlaps with active L1 table); further corruption events will be suppressed

See also this forum thread: https://forum.opennebula.org/t/resize-disk-leads-to-qcow2-corruption/5358

Solution: use "virsh blockresize one-$ID vda --size $SIZE" instead of qemu-monitor command.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
PR to merge: https://github.com/OpenNebula/one/pull/1822
