### ISSUE TITLE
PCI probe configuration should not be overwritten by upgrades

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1588]
# Bug Report
## Version of OpenNebula

- [X] 5.2.2
- [X] 5.4.0
- [X] 5.4.1
- [X] 5.4.2
- [X] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [X] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

When pci.rb is modified to include custom pci devices, the file is overwritten and the configuration is lost.

### Expected Behavior
PCI device configuration is not lost after upgrade

### Actual Behavior
preserve modification to pci.rb

## How to reproduce

1. Modify pci.rb
2. Upgrade OpenNebula

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Configuration from `pci.rb` has been moved into `pci.conf`, all the remote scripts configuration files have been moved into `/var/lib/one/remotes/etc/`.

```
# cat /var/lib/dpkg/info/opennebula.conffiles | grep remotes
/var/lib/one/remotes/etc/datastore/ceph/ceph.conf
/var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf
/var/lib/one/remotes/etc/vmm/kvm/kvmrc
/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf

# rpm -qc opennebula-server | grep remotes
/var/lib/one/remotes/etc/datastore/ceph/ceph.conf
/var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf
/var/lib/one/remotes/etc/vmm/kvm/kvmrc
/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf
```

3 merges required into master:

* Code: https://github.com/OpenNebula/one/tree/bug-1588
* Packages: https://github.com/OpenNebula/packages/tree/bug-1588
* Documentation: https://github.com/OpenNebula/docs/pull/182
