### ISSUE TITLE
Remove VLAN_ID from save_as templates

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1591]
# Bug Report
## Version of OpenNebula

- [X] 5.2.2
- [X] 5.4.0
- [X] 5.4.1
- [X] 5.4.2
- [X] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
When saving a VM temaplate that includes VLAN_IDs, those are copied to the saved template. VLAN_ID is a restricted attribute and hence the copied template cannot be instantiated

### Expected Behavior
A user can instantiate a saved template with VLAN_IDs

### Actual Behavior
User cannot intantiate because of Cannot update template. ``User Template includes a restricted attribute NIC.``

## How to reproduce
1. Create VM with VLAN_ID
2. Save the VM as a new template 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
Probably the list of removed attributes should be made configurable

**Comment by rsmontero** [comment]
VLAN_ID removed. Changes in master and one-5.4 branches
