### ISSUE TITLE
Duplicated NIC when save a template

### ISSUE THREAD

**Issue by juanmont** [OpenNebula/one#1600]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [X] 5.4.0
- [X] 5.4.1
- [X] 5.4.2
- [X] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

When you save a virtual Machine with two or more nics associated, the template generated has double the nics of the original machine.

## How to reproduce

Save a Virtual Machine with two NICs associated.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Code committed to master - one-5.4
