### ISSUE TITLE
Unable to create/update/clone VM template if showback feature is disabled

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#1608]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
We can create, update or clone a VM template if the showback feature of the view is disabled.

### Expected Behavior
We can create, update or clone a VM template when the showback feature of the view is disabled.

### Actual Behavior

We have a spinner

## How to reproduce
1. `sed -i -E 's,(showback: ).*,\1false,' /etc/one/sunstone-views/user.yaml`
2. `service opennebula-sunstone restart`
3. Connect to opennebula
4. Try to create a new VM template

![Error when creating a VM template in a view with showback feature disabled](https://user-images.githubusercontent.com/1233212/34264955-caa45650-e674-11e7-94c7-89aeb201819c.png)

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
Hello.

The problem exists on 5.6.1 too.

Regards.

**Comment by jloboescalona2** [comment]
We cannot replicate the error. Try the new versions of opennebula. If you find the bug again, please tell us the steps you took to replicate it and we will reopen the issue.
