### ISSUE TITLE
OpenNebula HA config single node stays follower

### ISSUE THREAD

**Issue by nils-smits** [OpenNebula/one#1609]
# Bug Report
## Version of OpenNebula

- [ ] 5.4.3

## Component
- [ ] Federation and HA

## Description
The problem is i wanted to change the ip address of the endpoints in the HA onezone config, the problem is remove all of the node and add a new one but i stays in the follower state an does not change to leader.

How can i change it back to leader?

## onezone show 0 output.
ZONE 0 INFORMATION
ID                : 0
NAME              : one01.test01

ZONE SERVERS
ID NAME            ENDPOINT
 0 kvm-server-01           http://10.110.0.151:2633/RPC2

HA & FEDERATION SYNC STATUS
ID NAME                         STATE      TERM       INDEX        COMMIT     VOTE  FED_INDEX
 0 kvm-server-01            follower     4035      1020384    1020384      -1         -1

ZONE TEMPLATE
ENDPOINT="http://localhost:2633/RPC2"

## Config 
/var/one/oned.conf

FEDERATION = [
    MODE          = "STANDALONE",
    ZONE_ID       = 0,
    SERVER_ID     = 0, 
    MASTER_ONED   = ""

RAFT = [
    LOG_RETENTION        = 500000,
    LOG_PURGE_TIMEOUT    = 600,
    ELECTION_TIMEOUT_MS  = 2500,
    BROADCAST_TIMEOUT_MS = 500,
    XMLRPC_TIMEOUT_MS    = 0 

 RAFT_LEADER_HOOK = [
     COMMAND = "raft/vip.sh",
     ARGUMENTS = "leader eth0 10.110.0.150/24" 
 ]

 RAFT_FOLLOWER_HOOK = [
     COMMAND = "raft/vip.sh",
     ARGUMENTS = "follower eth0 10.110.0.150/24"
 ]

**Comment by rsmontero** [comment]
What is the current state of your cluster (e.g. output of onezone show)? Note that there is no way to force the election of a specific leader; you can however, somehow trick the algorithm by shutting down the cluster and starting first the wanted leader. Finally you may also need to increase the ELECTION_TIMEOUT_MS, so short network outages or workload peaks do not force a new term.

**Comment by bogdanparvu18** [comment]
Hi Ruben,

It looks like I hit the same case using new version 5.6.0. After I removed servers from HA and added back following the process on the official docs the leader of the zone is missing under "HA & FEDERATION SYNC STATUS" . Please see below output:

onezone show 0
ZONE 0 INFORMATION                                                              
ID                : 0                   
NAME              : OpenNebula          


ZONE SERVERS                                                                    
ID NAME            ENDPOINT                                                       
 0 server0          http://server0:2633/RPC2

HA & FEDERATION SYNC STATUS                                                     
ID NAME            STATE      TERM       INDEX      COMMIT     VOTE  FED_INDEX 
 0 server0          follower   18004      921729     921729     1     -1

ZONE TEMPLATE                                                                   
ENDPOINT="http://localhost:2633/RPC2"

I have a 3 server HA and it looks like the the voting works fine in RAFT ie, I'm able to trigger transitions from follower to leader for the above ID 0 server, but cannot see the status for the other two servers added.

I see the following logs : 

server0: 

Wed Jul 18 22:40:54 2018 [Z0][ReM][I]: Leader term (18153) is outdated (18154)
Wed Jul 18 22:40:57 2018 [Z0][ReM][D]: Req:4272 UID:0 one.zone.voterequest invoked , 18155, 1, 929475, 18153
Wed Jul 18 22:40:57 2018 [Z0][ReM][I]: New term (18155) discovered from candidate 1
Wed Jul 18 22:40:57 2018 [Z0][RCM][I]: oned is set to follower mode
Wed Jul 18 22:40:57 2018 [Z0][ReM][D]: Req:4272 UID:0 one.zone.voterequest result SUCCESS, 18154
Wed Jul 18 22:40:57 2018 [Z0][ReM][I]: Leader term (18154) is outdated (18155)
Wed Jul 18 22:40:57 2018 [Z0][ReM][D]: Req:7888 UID:0 one.zone.info invoked , 0
Wed Jul 18 22:40:57 2018 [Z0][ReM][D]: Req:7888 UID:0 one.zone.info result SUCCESS, "<ZONE><ID>0</ID><NAM..."
Wed Jul 18 22:40:57 2018 [Z0][ReM][D]: Req:1024 UID:0 one.zone.raftstatus invoked 
Wed Jul 18 22:40:57 2018 [Z0][ReM][D]: Req:1024 UID:0 one.zone.raftstatus result SUCCESS, "<RAFT><SERVER_ID>0</..."
Wed Jul 18 22:40:59 2018 [Z0][ReM][D]: Req:1552 UID:0 one.zone.voterequest invoked , 18156, 2, 929080, 18152
Wed Jul 18 22:40:59 2018 [Z0][ReM][I]: New term (18156) discovered from candidate 2
Wed Jul 18 22:40:59 2018 [Z0][RCM][I]: oned is set to follower mode

Wed Jul 18 22:36:44 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:37:14 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:37:44 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:38:14 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:38:44 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:39:14 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:39:44 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:40:14 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:40:44 2018 [Z0][SCHED][E]: oned is not leader
Wed Jul 18 22:41:14 2018 [Z0][SCHED][E]: oned is not leader

server1:

Wed Jul 18 22:39:54 2018 [Z0][RRM][E]: Failed to get heartbeat from leader. Starting election proccess
Wed Jul 18 22:39:54 2018 [Z0][RCM][I]: Got vote from follower 0. Total votes: 1
Wed Jul 18 22:39:54 2018 [Z0][RCM][I]: Got majority of votes
Wed Jul 18 22:39:54 2018 [Z0][RCM][I]: Becoming leader of the zone. Last log record: 929409 last applied record: 0
Wed Jul 18 22:39:54 2018 [Z0][RCM][I]: oned is now the leader of the zone
Wed Jul 18 22:39:54 2018 [Z0][RCM][I]: Replicating log to followers
Wed Jul 18 22:39:54 2018 [Z0][RCM][I]: Leader log replicated
Wed Jul 18 22:39:57 2018 [Z0][RCM][I]: Follower 0 term (18040) is higher than current (18039)
Wed Jul 18 22:39:57 2018 [Z0][RCM][I]: oned is set to follower mode
Wed Jul 18 22:39:57 2018 [Z0][RCM][I]: Replication thread stopped
Wed Jul 18 22:39:57 2018 [Z0][RCM][I]: Replication thread stopped
Wed Jul 18 22:39:57 2018 [Z0][HKM][D]: Message received: EXECUTE SUCCESS -1 RAFT_FOLLOWER_HOOK: 

Wed Jul 18 22:39:57 2018 [Z0][HKM][D]: Message received: LOG I -1 Command execution failed (exit code: 2): /var/lib/one/remotes//hooks/raft/vip.sh leader em1 192.168.100.12/24

Wed Jul 18 22:39:57 2018 [Z0][HKM][D]: Message received: LOG I -1 bind: Cannot assign requested address

Wed Jul 18 22:39:57 2018 [Z0][HKM][D]: Message received: EXECUTE FAILURE -1 RAFT_LEADER_HOOK: -

Wed Jul 18 22:40:00 2018 [Z0][RRM][E]: Failed to get heartbeat from leader. Starting election proccess
Wed Jul 18 22:40:00 2018 [Z0][RCM][I]: Got vote from follower 0. Total votes: 1
Wed Jul 18 22:40:00 2018 [Z0][RCM][I]: Got majority of votes
Wed Jul 18 22:40:00 2018 [Z0][RCM][I]: Becoming leader of the zone. Last log record: 929409 last applied record: 0
Wed Jul 18 22:40:00 2018 [Z0][RCM][I]: oned is now the leader of the zone
Wed Jul 18 22:40:00 2018 [Z0][RCM][I]: Replicating log to followers
Wed Jul 18 22:40:00 2018 [Z0][RCM][I]: Leader log replicated
Wed Jul 18 22:40:03 2018 [Z0][RCM][I]: Follower 0 term (18042) is higher than current (18041)
Wed Jul 18 22:40:03 2018 [Z0][RCM][I]: Replication thread stopped
Wed Jul 18 22:40:03 2018 [Z0][RCM][I]: oned is set to follower mode
Wed Jul 18 22:40:03 2018 [Z0][RCM][I]: Replication thread stopped
.............


Wed Jul 18 22:47:22 2018 [Z0][SCHED][D]: Dispatching VMs to hosts:
        VMID    Priority        Host    System DS
        --------------------------------------------------------------

Wed Jul 18 22:47:52 2018 [Z0][SCHED][E]: oned is not leader
.........

server2:

Wed Jul 18 22:49:26 2018 [Z0][DBM][E]: Tried to modify DB being a follower
Wed Jul 18 22:49:26 2018 [Z0][InM][D]: Host cloud3.techadviser.ro (2) successfully monitored.
Wed Jul 18 22:49:26 2018 [Z0][HKM][D]: Message received: LOG I -1 Command execution failed (exit code: 2): /var/lib/one/remotes//hooks/raft/vip.sh leader em1 192.168.100.12/24

Wed Jul 18 22:49:26 2018 [Z0][HKM][D]: Message received: LOG I -1 bind: Cannot assign requested address

Wed Jul 18 22:49:26 2018 [Z0][HKM][D]: Message received: EXECUTE FAILURE -1 RAFT_LEADER_HOOK: -

Wed Jul 18 22:49:29 2018 [Z0][RRM][E]: Failed to get heartbeat from leader. Starting election proccess
Wed Jul 18 22:49:29 2018 [Z0][RCM][I]: Got vote from follower 0. Total votes: 1
Wed Jul 18 22:49:29 2018 [Z0][RCM][I]: Got majority of votes
Wed Jul 18 22:49:29 2018 [Z0][RCM][I]: Becoming leader of the zone. Last log record: 929125 last applied record: 0
Wed Jul 18 22:49:29 2018 [Z0][RCM][I]: oned is now the leader of the zone
Wed Jul 18 22:49:29 2018 [Z0][RCM][I]: Replicating log to followers
Wed Jul 18 22:49:29 2018 [Z0][RCM][I]: Leader log replicated
Wed Jul 18 22:49:32 2018 [Z0][RCM][I]: Follower 0 term (18231) is higher than current (18230)
Wed Jul 18 22:49:32 2018 [Z0][RCM][I]: Replication thread stopped
Wed Jul 18 22:49:32 2018 [Z0][RCM][I]: oned is set to follower mode
Wed Jul 18 22:49:32 2018 [Z0][RCM][I]: Replication thread stopped
Wed Jul 18 22:49:32 2018 [Z0][HKM][D]: Message received: EXECUTE SUCCESS -1 RAFT_FOLLOWER_HOOK: 

Wed Jul 18 22:49:32 2018 [Z0][HKM][D]: Message received: LOG I -1 Command execution failed (exit code: 2): /var/lib/one/remotes//hooks/raft/vip.sh leader em1 192.168.100.12/24

Wed Jul 18 22:49:32 2018 [Z0][HKM][D]: Message received: LOG I -1 bind: Cannot assign requested address

Wed Jul 18 22:49:32 2018 [Z0][HKM][D]: Message received: EXECUTE FAILURE -1 RAFT_LEADER_HOOK: -

Wed Jul 18 22:49:34 2018 [Z0][RRM][E]: Failed to get heartbeat from leader. Starting election proccess
Wed Jul 18 22:49:34 2018 [Z0][RCM][I]: Got vote from follower 0. Total votes: 1
Wed Jul 18 22:49:34 2018 [Z0][RCM][I]: Got majority of votes
Wed Jul 18 22:49:34 2018 [Z0][RCM][I]: Becoming leader of the zone. Last log record: 929126 last applied record: 0
Wed Jul 18 22:49:34 2018 [Z0][RCM][I]: oned is now the leader of the zone
Wed Jul 18 22:49:34 2018 [Z0][RCM][I]: Replicating log to followers
Wed Jul 18 22:49:34 2018 [Z0][RCM][I]: Leader log replicated
Wed Jul 18 22:49:34 2018 [Z0][ReM][D]: Req:3488 UID:0 one.zone.raftstatus invoked 
Wed Jul 18 22:49:34 2018 [Z0][ReM][D]: Req:3488 UID:0 one.zone.raftstatus result SUCCESS, "<RAFT><SERVER_ID>2</..."
Wed Jul 18 22:49:34 2018 [Z0][ReM][D]: Req:2320 UID:0 one.vmpool.info invoked , -2, -1, -1, -1
Wed Jul 18 22:49:34 2018 [Z0][ReM][D]: Req:2320 UID:0 one.vmpool.info result SUCCESS, "<VM_POOL><VM>
  <ID>..."
Wed Jul 18 22:49:34 2018 [Z0][ReM][D]: Req:4320 UID:0 one.vmpool.info invoked , -2, -1, -1, -1
Wed Jul 18 22:49:34 2018 [Z0][ReM][D]: Req:4320 UID:0 one.vmpool.info result SUCCESS, "<VM_POOL><VM>
  <ID>..."


Can you confirm if this is a bug or I'm missing any certain configuration step?

Thanks,
Bogdan

**Comment by rsmontero** [comment]
This should be fixed as per 5.8.5, any additional issue is being discussed in #3021
