### ISSUE TITLE
Can't instantiate Vm with volatile image

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#1612]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [X] 5.4.5
- [ ] Development build

Probably other versions affected, not tested.

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

Not sure is it a sunstone issue or core issue.

## Description
Tried instantiating a VM from template with defined volatile swap disk

### Expected Behavior
VM is instantiated on first try

### Actual Behavior
Instantiate denied with error message:
`[one.template.instantiate] Error allocating a new virtual machine template. DISK 2: SIZE attribute must be a positive integer value.`

But just hitting the Create button again - the VM is instantiated.

## How to reproduce
Create а VM template with disks as follow
disk0 - non-persistent
disk1 - volatile, SIZE:2GB, TYPE:swap, BUS: scsi, CACHE:none

VM template:
```
CONTEXT = [
  NETWORK = "YES",
  PASSWORD = "storpool",
  SSH_PUBLIC_KEY = "$USER[SSH_PUBLIC_KEY]" ]
CPU = "1"
DISK = [
  CACHE = "none",
  DEV_PREFIX = "sd",
  DISCARD = "unmap",
  DRIVER = "raw",
  IMAGE_ID = "58",
  IO = "native" ]
DISK = [
  CACHE = "none",
  DEV_PREFIX = "sd",
  DRIVER = "raw",
  FORMAT = "raw",
  IO = "native",
  SIZE = "2048",
  TYPE = "swap" ]
...
```

Create/Instantiate a VM - it will fail with error message.
Just hitting the create/instantiate again - the VM is instantiated.

**Comment by laurencegill** [comment]
This seems to be an issue in 5.4.6.  I have tried the patch above but it doesn't seem to work, are there other files that need changing also?

Thanks

**Comment by atodorov-storpool** [comment]
@laurencegill 
After applying the patch you need to "compile" the change in the main.js. Usially I do the following(I am using CentOS):

```bash
yum install npm
npm install bower -g
npm install grunt-cli -g

cd /usr/lib/one/sunstone/public
npm install
bower --allow-root install
grunt sass
grunt requirejs
```
And then restart opennebula-sunstone service

**Comment by laurencegill** [comment]
Thanks! That has now fixed the issue, every day's a school day :)
