### ISSUE TITLE
ip6tables not in sudoers

### ISSUE THREAD

**Issue by rogierm** [OpenNebula/one#1628]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ X ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [X ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

When starting a VM after the upgrade from 5.2 to 5.4.1 I got the following error:
Thu Jan 4 00:21:14 2018 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/12/deployment.3
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: ExitCode: 0
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: pre: Executed "sudo brctl addbr onebr0".
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: pre: Executed "sudo ip link set onebr0 up".
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: pre: Executed "sudo ip link add br200.1400 mtu 1500 type vxlan id 1400 group 239.0.5.120 ttl 16 dev br200 ".
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: pre: Executed "sudo ip link set br200.1400 up".
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: pre: Executed "sudo brctl addif onebr0 br200.1400".
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: ExitCode: 0
Thu Jan 4 00:21:20 2018 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Thu Jan 4 00:21:21 2018 [Z0][VMM][I]: ExitCode: 0
Thu Jan 4 00:21:21 2018 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Thu Jan 4 00:21:21 2018 [Z0][VMM][I]: ExitCode: 0
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: Command execution fail: /var/tmp/one/vnm/vxlan/post PFZNPjxJRD4xMjwvSUQ+PERFUExPWV9JRD5vbmUtMTI8L0RFUExPWV9JRD48VEVNUExBVEU+PFNFQ1VSSVRZX0dST1VQX1JVTEU+PFBST1RPQ09MPjwhW0NEQVRBW0FMTF1dPjwvUFJPVE9DT0w+PFJVTEVfVFlQRT48IVtDREFUQVtPVVRCT1VORF1dPjwvUlVMRV9UWVBFPjxTRUNVUklUWV9HUk9VUF9JRD48IVtDREFUQVswXV0+PC9TRUNVUklUWV9HUk9VUF9JRD48U0VDVVJJVFlfR1JPVVBfTkFNRT48IVtDREFUQVtkZWZhdWx0XV0+PC9TRUNVUklUWV9HUk9VUF9OQU1FPjwvU0VDVVJJVFlfR1JPVVBfUlVMRT48L1RFTVBMQVRFPjxURU1QTEFURT48U0VDVVJJVFlfR1JPVVBfUlVMRT48UFJPVE9DT0w+PCFbQ0RBVEFbQUxMXV0+PC9QUk9UT0NPTD48UlVMRV9UWVBFPjwhW0NEQVRBW0lOQk9VTkRdXT48L1JVTEVfVFlQRT48U0VDVVJJVFlfR1JPVVBfSUQ+PCFbQ0RBVEFbMF1dPjwvU0VDVVJJVFlfR1JPVVBfSUQ+PFNFQ1VSSVRZX0dST1VQX05BTUU+PCFbQ0RBVEFbZGVmYXVsdF1dPjwvU0VDVVJJVFlfR1JPVVBfTkFNRT48L1NFQ1VSSVRZX0dST1VQX1JVTEU+PC9URU1QTEFURT48SElTVE9SWV9SRUNPUkRTPjxISVNUT1JZPjxIT1NUTkFNRT5rdm0xLjQyc2VjLm5ldDwvSE9TVE5BTUU+PC9ISVNUT1JZPjwvSElTVE9SWV9SRUNPUkRTPjxISVNUT1JZX1JFQ09SRFM+PEhJU1RPUlk+PFZNX01BRD48IVtDREFUQVtrdm1dXT48L1ZNX01BRD48L0hJU1RPUlk+PC9ISVNUT1JZX1JFQ09SRFM+PFRFTVBMQVRFPjxOSUM+PEFSX0lEPjwhW0NEQVRBWzBdXT48L0FSX0lEPjxCUklER0U+PCFbQ0RBVEFbYnI1MDFdXT48L0JSSURHRT48Q0xVU1RFUl9JRD48IVtDREFUQVswXV0+PC9DTFVTVEVSX0lEPjxJUD48IVtDREFUQVsxODUuMTc1LjI1LjM0XV0+PC9JUD48SVA2X0dMT0JBTD48IVtDREFUQVsyYTBiOmM5MDA6MTpmOjQwMDpiOWZmOmZlYWY6MTkyMl1dPjwvSVA2X0dMT0JBTD48SVA2X0xJTks+PCFbQ0RBVEFbZmU4MDo6NDAwOmI5ZmY6ZmVhZjoxOTIyXV0+PC9JUDZfTElOSz48TUFDPjwhW0NEQVRBWzAyOjAwOmI5OmFmOjE5OjIyXV0+PC9NQUM+PE1PREVMPjwhW0NEQVRBW3ZpcnRpb11dPjwvTU9ERUw+PE5FVFdPUks+PCFbQ0RBVEFbNDJzZWMgT3Blbm5idWxhIHB1YmxpYzFdXT48L05FVFdPUks+PE5FVFdPUktfSUQ+PCFbQ0RBVEFbMl1dPjwvTkVUV09SS19JRD48TklDX0lEPjwhW0NEQVRBWzBdXT48L05JQ19JRD48U0VDVVJJVFlfR1JPVVBTPjwhW0NEQVRBWzBdXT48L1NFQ1VSSVRZX0dST1VQUz48VEFSR0VUPjwhW0NEQVRBW29uZS0xMi0wXV0+PC9UQVJHRVQ+PFZOX01BRD48IVtDREFUQVtkdW1teV1dPjwvVk5fTUFEPjwvTklDPjwvVEVNUExBVEU+PFRFTVBMQVRFPjxOSUM+PEFSX0lEPjwhW0NEQVRBWzBdXT48L0FSX0lEPjxCUklER0U+PCFbQ0RBVEFbb25lYnIwXV0+PC9CUklER0U+PENMVVNURVJfSUQ+PCFbQ0RBVEFbMF1dPjwvQ0xVU1RFUl9JRD48RklMVEVSX0lQX1NQT09GSU5HPjwhW0NEQVRBW1lFU11dPjwvRklMVEVSX0lQX1NQT09GSU5HPjxGSUxURVJfTUFDX1NQT09GSU5HPjwhW0NEQVRBW1lFU11dPjwvRklMVEVSX01BQ19TUE9PRklORz48SVA+PCFbQ0RBVEFbMTAuMjAwLjEwMC4zXV0+PC9JUD48SVA2X0dMT0JBTD48IVtDREFUQVsyYTBiOmM5MDA6MToxMDo0MDA6YWZmOmZlYzg6NjQwM11dPjwvSVA2X0dMT0JBTD48SVA2X0xJTks+PCFbQ0RBVEFbZmU4MDo6NDAwOmFmZjpmZWM4OjY0MDNdXT48L0lQNl9MSU5LPjxNQUM+PCFbQ0RBVEFbMDI6MDA6MGE6Yzg6NjQ6MDNdXT48L01BQz48TU9ERUw+PCFbQ0RBVEFbdmlydGlvXV0+PC9NT0RFTD48TkVUV09SSz48IVtDREFUQVs0MnNlY19wcml2YXRlIGludGVyY29ubmVjdF1dPjwvTkVUV09SSz48TkVUV09SS19JRD48IVtDREFUQVswXV0+PC9ORVRXT1JLX0lEPjxOSUNfSUQ+PCFbQ0RBVEFbMV1dPjwvTklDX0lEPjxQSFlERVY+PCFbQ0RBVEFbYnIyMDBdXT48L1BIWURFVj48U0VDVVJJVFlfR1JPVVBTPjwhW0NEQVRBWzBdXT48L1NFQ1VSSVRZX0dST1VQUz48VEFSR0VUPjwhW0NEQVRBW29uZS0xMi0xXV0+PC9UQVJHRVQ+PFZMQU5fSUQ+PCFbQ0RBVEFbMTQwMF1dPjwvVkxBTl9JRD48Vk5fTUFEPjwhW0NEQVRBW3Z4bGFuXV0+PC9WTl9NQUQ+PC9OSUM+PC9URU1QTEFURT48VEVNUExBVEU+PE5JQz48QVJfSUQ+PCFbQ0RBVEFbMF1dPjwvQVJfSUQ+PEJSSURHRT48IVtDREFUQVticmRtel1dPjwvQlJJREdFPjxDTFVTVEVSX0lEPjwhW0NEQVRBWzBdXT48L0NMVVNURVJfSUQ+PElQPjwhW0NEQVRBWzEwLjIwMC4xLjEwMF1dPjwvSVA+PElQNl9HTE9CQUw+PCFbQ0RBVEFbMmEwYjpjOTAwOjA6MTo0MDA6YWZmOmZlYzg6MTY0XV0+PC9JUDZfR0xPQkFMPjxJUDZfTElOSz48IVtDREFUQVtmZTgwOjo0MDA6YWZmOmZlYzg6MTY0XV0+PC9JUDZfTElOSz48TUFDPjwhW0NEQVRBWzAyOjAwOjBhOmM4OjAxOjY0XV0+PC9NQUM+PE1PREVMPjwhW0NEQVRBW3ZpcnRpb11dPjwvTU9ERUw+PE5FVFdPUks+PCFbQ0RBVEFbNDJTZWMgRE1aXV0+PC9ORVRXT1JLPjxORVRXT1JLX0lEPjwhW0NEQVRBWzFdXT48L05FVFdPUktfSUQ+PE5JQ19JRD48IVtDREFUQVsyXV0+PC9OSUNfSUQ+PFNFQ1VSSVRZX0dST1VQUz48IVtDREFUQVswXV0+PC9TRUNVUklUWV9HUk9VUFM+PFRBUkdFVD48IVtDREFUQVtvbmUtMTItMl1dPjwvVEFSR0VUPjxWTl9NQUQ+PCFbQ0RBVEFbZHVtbXldXT48L1ZOX01BRD48VlJPVVRFUl9NQU5BR0VNRU5UPjwhW0NEQVRBW1lFU11dPjwvVlJPVVRFUl9NQU5BR0VNRU5UPjwvTklDPjwvVEVNUExBVEU+PC9WTT4= 'one-12'
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: We trust you have received the usual lecture from the local System
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: Administrator. It usually boils down to these three things:
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: 
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: #1) Respect the privacy of others.
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: #2) Think before you type.
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: #3) With great power comes great responsibility.
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: 
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: sudo: no tty present and no askpass program specified
Thu Jan 4 00:21:23 2018 [Z0][VMM][E]: post: Command Error: sudo ip6tables -S
Thu Jan 4 00:21:23 2018 [Z0][VMM][E]: post: ["/var/tmp/one/vnm/command.rb:62:in `block in run!'", "/var/tmp/one/vnm/command.rb:59:in `each'", "/var/tmp/one/vnm/command.rb:59:in `run!'", "/var/tmp/one/vnm/security_groups_iptables.rb:255:in `info'", "/var/tmp/one/vnm/security_groups_iptables.rb:509:in `nic_deactivate'", "/var/tmp/one/vnm/sg_driver.rb:128:in `block in deactivate'", "/var/tmp/one/vnm/sg_driver.rb:125:in `each'", "/var/tmp/one/vnm/sg_driver.rb:125:in `deactivate'", "/var/tmp/one/vnm/sg_driver.rb:75:in `activate'", "/var/tmp/one/vnm/vxlan/post:32:in `
'"]
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: ExitCode: 1
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: ExitCode: 0
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: Successfully execute virtualization driver operation: cancel.
Thu Jan 4 00:21:23 2018 [Z0][VMM][I]: Failed to execute network driver operation: post.
Thu Jan 4 00:21:23 2018 [Z0][VMM][E]: Error deploying virtual machine: dummy: - vxlan: -
Thu Jan 4 00:21:23 2018 [Z0][VM][I]: New state is POWEROFF
Thu Jan 4 00:21:23 2018 [Z0][VM][I]: New LCM state is LCM_INIT

The file /etc/sudoers.d/opennebula contained the following line:
Cmnd_Alias ONE_NET = /usr/sbin/brctl, /sbin/ebtables, /sbin/iptables, /sbin/ip, /usr/sbin/ipset

I have updated this to:
Cmnd_Alias ONE_NET = /usr/sbin/brctl, /sbin/ebtables, /sbin/iptables, /sbin/ip, /usr/sbin/ipset, /sbin/ip6tables

Now the VM's start succesfully. 

## How to reproduce

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by canance** [comment]
Same issue here on a fresh install of 5.4.6.  Adding /sbin/ip6tables to the /etc/sudoers.d/opennebula resolved it!

**Comment by vholer** [comment]
I have checked `opennebula-common` packages for all platforms we shipped versions 5.4.1 and 5.4.6, all contain `ip6tables` in the `sudo` configuration. Please check you are using correct versions on the nodes, check the new configuration files weren't created as rpmnew or similar, and if you still see a problem, provide more details about your environment (platform, source of the packages) and a steps to reproduce.

Thank you. Closing for now.
