### ISSUE TITLE
Do not mark disks as error if a disk-modifying state wasn't reached

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#1632]
# Bug Report
## Version of OpenNebula

- [x] 5.2.2
- [x] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build
(since they're no longer in repo, anything >5.4.0 is your business)

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [x] Scheduler
- [x] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

If you instantiate a VM and hit an error, it'll mark the disks as failed.
This is done even if the VM was never *started* and the disks were never *modified*

### Expected Behavior
Be aware of what ONE is doing on i.e. the disks. If they never were modified, do not mark them in ERROR.

### Actual Behavior
Disks are put in error, user uses a lot of time
User has to fix multiple errors instead of the original one

## How to reproduce

Default behaviour

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FlorianHeigl** [comment]
how the fuck did you decide to autoclose tickets that weren't even worked on.

**Comment by tinova** [comment]
The stale bot has been activated in order to detect feedback and contributions that are relevant but have been left behind. Simply a comment (as you see) is enough to not autoclose the ticket, and put it under our radar again. We'd love to have the resource to take all feedback and contributions in, but resources are limited and having hundreds of issues and PRs in the backlog does not help anyone.

**Comment by FlorianHeigl** [comment]
I had opened these bugs because someone on the dev team asked me to bring attention to old negative-UX issues. I'll not make the mistake of investing time into such contributions again.
