### ISSUE TITLE
Live CPU and MEMORY resize

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#1660]
# Enhancement Request
## Description

CPU resize should be supported in both KVM and vCenter VMs.

Needs to take into account VCPU and CPU. Only allow VCPU definition in cloud view, and create a VCPU/CPU ratio that can be defined in the VM Template by the admin

Needs to take into account quotas (need to figure out a way to present the CPU quotas to users)

## Use case

Increase the amount of VCPU available for the guestOS.

## Interface Changes

Changes in Sunstone and in CLI to allow for live CPU resize. Also changes in sunstone to reflect quotas

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by hydro-b** [comment]
I would say this is a duplicate of https://github.com/OpenNebula/one/issues/949

**Comment by tinova** [comment]
Also memory should be dynamically resized.

**Comment by tinova** [comment]
Needs Sunstone support

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- one: https://github.com/OpenNebula/one-ee/pull/575

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Tests: https://github.com/OpenNebula/development/pull/1246

**Comment by tinova** [comment]
ok, we just need this in the What's New. Assigning it to @paczerny as he did the documentation.
