### ISSUE TITLE
Showback hours slightly inaccurate

### ISSUE THREAD

**Issue by tkald** [OpenNebula/one#1662]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [x] 5.4.5
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
Showback in sunstone and oneshowback cli command report slightly inaccurate hours for VM usage.
In november, there's 720 hours but some vm-s have managed to use 720.02 and 720.01 hours of if.
![image](https://user-images.githubusercontent.com/8062491/35070237-4b6e7b14-fbe5-11e7-9de7-cfa63c79408e.png)
Also some records are in decimal format others aren't...

### Expected Behavior
Correctly show / calculate vm usage

### Actual Behavior
Some records are'nt valid.

## How to reproduce

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
I have been checking this issue and there is no "real" issue, let me explain this:

The value that is shown there are the **hours + extra minutes** that the VM has been used. So for example if we have 720.01 hours, this means that the VM has been used 720 hours and 30 seconds. So if we had 720.10 hours, this would mean that the VM has been used 720 hours and 6 minutes, because 6 minutes is the 10% of and hour, so 0.10.

So, this is working as expected, but it's true that some users might want to only show full hours. So an option to do this will be added in the CLI and in Sunstone.

Best,
Álex.

**Comment by tkald** [comment]
It's not an issue if there's a month longer than 720 hours.
But for example november has 720 hours - so how vm can run longer than 720 hours in november?

**Comment by al3xhh** [comment]
Hello @tkald 

If you calculate the showback without specifying the start and end date, the hours is the total hours since the VM was created. If you specify the month it will contain only the month usage. 

Are you calculating the showback with limits and it's failing for you?

Best,
Álex.

**Comment by tkald** [comment]
I'm calculating showback daily for previous day:

`oneshowback calculate -s $(date +"%m/%Y" -d "- 1 days") -e $(date +"%m/%Y" -d "- 1 days")`

**Comment by al3xhh** [comment]
I have done more tests and if I calculate the showback per month, I get the following:

```
# Showback for 4/2020                                                           

USER_NAM GROUP_NA  VM_ID VM_NAME         MONTH  YEAR  HOURS            COST
admin    oneadmin     29 services            4  2020    720               0
```

These tests have been done in OpenNebula 5.10.4 version.

Best,
Álex.

**Comment by al3xhh** [comment]
Hello @tkald 

What OpenNebula version are you running?

**Comment by tkald** [comment]
I'm running version 5.6.2. Last "error" seems to be in January when 1 vm used 744.02 hours of month.
Redacted output here:
[nifi.txt](https://github.com/OpenNebula/one/files/4589480/nifi.txt)

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4674/files
- tests: https://github.com/OpenNebula/development/pull/969
