### ISSUE TITLE
Google Cloud Engine (GCE) Integration

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1668]
# Enhancement Request
## Description

Google Cloud Engine is a popular IaaS service. OpenNebula hold support it at the same level of integration as AWS and Azure.

## Use case

Cloud admins interested in outsource VMs to GCE in a hybrid cloud model

## Interface Changes

The functionality should be offered in Sunstone, in the VM Template hybrid section

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dkorzhevin** [comment]
Hello guys,

Can you please share progress on this task?
