### ISSUE TITLE
Can't resize vm disk - [one.vm.diskresize] New disk size has to be greater than current one

### ISSUE THREAD

**Issue by tkald** [OpenNebula/one#1671]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [x] 5.4.5
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [x] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
When I try to resize (increase) disk on running VM through Sunstone, I get error:
[one.vm.diskresize] New disk size has to be greater than current one
Both for persistent and nonpersitent disks on Ceph backend.

In oned.log there's same error:
Fri Jan 19 16:26:32 2018 [Z0][ReM][D]: Req:2080 UID:0 one.vm.diskresize invoked , 3030, 0, "0"
Fri Jan 19 16:26:32 2018 [Z0][ReM][E]: Req:2080 UID:0 one.vm.diskresize result FAILURE [one.vm.diskresize] New disk size has to be greater than current one

Setting larger disk size on VM creation works however.

### Expected Behavior
Able to resize disk on running VM

### Actual Behavior
I get error "New disk size has to be greater than current one"

## How to reproduce

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Hi, affects to me too, after updating to 5.6.5

**Comment by kvaps** [comment]
works for me via command line:
```
onevm disk-resize 5891 0 20480
```

**Comment by Madko** [comment]
same here with 5.4.6

**Comment by sergiojvg** [comment]
Same for me. OpenNebula 5.4.6 compiled from source

**Comment by ArnY** [comment]
commit  a0e1b4e does not seem to fix the problem with 5.4.6. I patched our one instance and we are still getting the error.

**Comment by mosharaflink** [comment]
@kvaps  while this command shows disk resize done but inside VM we find only 2TB of disk size. I am using OpenNebula 5.6.1. Is there any issues?

**Comment by kvaps** [comment]
OpenNebula 5.6 have no this issue, try check your drive via `qemu-img info` maybe you need to resize partitions manually there.
