### ISSUE TITLE
VM Template - CPU Model - Not loading actual selected one

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#1689]
# Bug Report
## Version of OpenNebula

- [X] 5.4.6
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
VM Template edit - OS & CPU Tab - CPU Model dropdown - no entry selected

### Expected Behavior
Select previously selected CPU model

### Actual Behavior
No CPU is selected, so there is great probability, that CPU model will be accidentally unset on VM Template edit

**Comment by abelCoronado93** [comment]
Hi @feldsam,

I tried to reproduce this but I don't get it.
Can you give me the steps to follow?

**Comment by feldsam** [comment]
Hello, hmm, interesting, it is working for me too now.
