### ISSUE TITLE
Deadlock of libvirt daemon can block VM actions on another hosts

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1702]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.6
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [X] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Sometimes the libvirt process can hang on compute nodes and report nothing.
So if you go to the host and run `virsh list` command, you will see nothing, it will just hang for long-long time. Why it's happend - this is another question to libvirt.
The main problem - that when opennebula face with this broken libvirt, it can affect the main OpenNebula daemon and block deploing of new VMs on another hosts. Restart of opennebula daemon temporary solves this issue.
I still not found the way for fully catch this bug, but I have something:

When problem is occured, usualy I see these messages in OpenNebula daemon log:

```
Wed Jan 31 12:45:03 2018 [Z0][MKP][I]: --Mark--
Wed Jan 31 12:46:43 2018 [Z0][ImM][I]: --Mark--
Wed Jan 31 12:52:33 2018 [Z0][VMM][I]: --Mark--
Wed Jan 31 12:53:24 2018 [Z0][InM][I]: --Mark--
Wed Jan 31 12:55:20 2018 [Z0][MKP][I]: --Mark--
Wed Jan 31 12:56:46 2018 [Z0][ImM][I]: --Mark--
Wed Jan 31 13:05:33 2018 [Z0][MKP][I]: --Mark--
Wed Jan 31 13:06:29 2018 [Z0][VMM][I]: --Mark--
```
And start to have wrong states on my VMs:

### Actual Behavior

When you deploy new VM, It's state changes like:
DEPLOYING --> BOOT --> RUNNING (and stay RUNNING)

But:
 * VNC-console is not working
 * If you will go to the host which runs this vm
    * `virsh list` will not display this VM
    * `ps aux` will not display qemu process of this VM
* If you will run some action in OpenNebula interface it will hang
* This VM will continue to have RUNNING state until reboot of oned daemon.

Same thing is happend with any other VM even it is already deployed.

### Expected Behavior

Host with broken libvirt daemon marked to have ERROR or UNKONOWN state.
Newly created and old VMs is always working fine not depends of other hosts.

## How to reproduce

You just need to have node with hanged libvirt daemon in your cluster.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
I'm not sure but may be wrong, my problem well described in this topic:
https://forum.opennebula.org/t/5-4-1-memory-issue-in-oned-closed/4990/7

**Comment by kvaps** [comment]
Probably this issue occurs when some oned daemon execute some command on a host through ssh.
But command are hung for a while.
In time when command is not response it blocks any other operations on cluster.

**Comment by sulaweyo** [comment]
Is there actually a plan to fix this issue or will it be moved to the next release for another 2 years?

**Comment by rsmontero** [comment]
I'd say it is a worksforme. We have not seen it in a while (probably bug fixed in recent libvirt versions). 

Are you still experimenting this?

**Comment by rsmontero** [comment]
I'll close this as works for me, we'll reopen if needed
