### ISSUE TITLE
 Problem with changing language other than settings (TR)

### ISSUE THREAD

**Issue by ruagunn** [OpenNebula/one#1712]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Hello, I want to change language as Turkish from Settings tab on sunstone. 
### Expected Behavior
Add language
### Actual Behavior
Firstly, tr.js file (there is tr.po file in default) have not been existed in the language directory that is "/usr/lib/one/sunstone/public/locale/languages". I translated every word from English to Turkish.

Then, I configured `:lang: tr` in "/etc/one/sunstone-server.conf", after that I restarted service of opennebula sunstone which command is `sudo service opennebula-sunstone restart`.

**A lot of words changed as Turkish, but some words did not changed that some are "Storage" and "Network" and "showing page information ...".**

I expected that Turkish language will be in Settings part as a language after I add tr.js file. But there is not Turkish language in language part on SUNSTONE.

In addition, there is 
lang="tr"
datatable_lang="tr_datatable.txt"
on all of language.js file ( instead of tr, there is default languages that some of them are en, fr, de etc. ).

I filled the fancy nail in tr_datatable.txt according to Turkish language, but it does not affected anything.

**When I changed the a language from Settings part on Sunstone, I could not return Turkish language.**

# Enhancement Request
Could you add TURKISH LANGUAGE to languages in Settings Tab?

## Interface Changes
Just language as Turkish expect some words on sunstone that could not be changed.

**Comment by abelCoronado93** [comment]
Hello @ruagunn,

OpenNebula uses Transifex for translations. We currently have a few official languages ​​at 100% but the Turkish is not among them (33%). 

I suggest you do the translations in the portal: https://www.transifex.com/opennebula/one/
So, the community will benefit from your work.

Thanks.

**Comment by ruagunn** [comment]
Hi @abelCoronado93, translated for Turkish. (Now 100%)

Will affect in next release?

Thanks for reply.

**Comment by abelCoronado93** [comment]
Hi @ruagunn,

Thanks for your help. In the next release turkish language will be into Sunstone. I've solved the problem with several strings too (Storage, Network...).

Could you provide me your "tr datatable.txt" to add it to the repo?

Regards.

**Comment by ruagunn** [comment]
Again, Hi @abelCoronado93 

tr_datatable.txt as 

```
{
    "sProcessing":   "İşleniyor...",
    "sLengthMenu":   "_MENU_",
    "sZeroRecords":  "Hiçbir eşleşen kayıt bulunamadı",
    "sInfo":         "Gösteriliyor _START_ dan _END_ e kadar toplam _TOTAL_ kayıt",
    "sInfoEmpty":    "Gösteriliyor 0 dan 0 e kadar toplam 0 kayıt",
    "sInfoFiltered": "(_MAX_ kayıt üzerinden filtrelenen kayıtlar)",
    "sInfoPostFix":  "",
    "sSearch":       "Arama:",
    "sUrl":          "",
    "oPaginate": {
        "sFirst":    "İlk",
        "sPrevious": "Önceki",
        "sNext":     "Sonraki",
        "sLast":     "Son"
    }
}

```

Is tr_TR.js or tr.js necessary? If you want, I can also send it.

**Comment by abelCoronado93** [comment]
Thanks. 

I just needed the datatable.txt, the .po and the .js files are generated by OpenNebula automatically thanks to Transifex.

**Comment by ruagunn** [comment]
Thank you very much for your help.
