### ISSUE TITLE
VM import should take into account state

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1715]
# Bug Report
## Version of OpenNebula
- [ ] Development build

## Component
- [ ] vCenter

## Description

Importing a VM in poweroff sets its state to RUNNING until the next monitor cycle

### Expected Behavior

VM should be imported as running

### Actual Behavior

VM is imported in RUNNING and then set to POWEROFF

## How to reproduce

Import a VM that is powered off in vCenter

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
We are going to address this by setting the VM to UNKNOWN state, and let the monitoring process to set the corresponding state for the new VM

**Comment by rsmontero** [comment]
oned already considers this with IMPORT_STATE variable, this issue is for vCenter monitor to include this variable set to  "POWEROFF" when needed.
