### ISSUE TITLE
building from sources - missing dependency on ronn (the Ruby gem)

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#1731]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [X] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
Can't build man pages

### Expected Behavior
./build.sh in share/man should succeed

### Actual Behavior
Unknown comand: ronn

## How to reproduce
Build the master branch without ronn (the Ruby gem)

I think that the README.md should be reworded - there is ruby gem dependency to build from current sources. Took some time to figure out because there is a nodejs module named 'ronn' which doesn't work. It was marked as deprecated by 'marked-man' nodejs module which also doesn't work. But there was a reference to 'ronn' (the Ruby gem) in the documentation of marked-man that pointed to right direction...

**Comment by vholer** [comment]
Thank you, Anton. I have updated the README.md to mention the `ronn` is a Ruby gem.
