### ISSUE TITLE
Mysql database name problem

### ISSUE THREAD

**Issue by kazh000** [OpenNebula/one#1741]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [x] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Component is "core".
If the name of mysql database consists char "-" or "_" the oned does not run.
### Expected Behavior
to run oned
### Actual Behavior
error message "Could not create the database." and exit.
## How to reproduce

0. install opennebula on Debian 9 according installation manual
0. install mariadb on Debian 8 or 9 (both tested)
1. set database to mysql
2. set the name of database with char "-" or "\_" and other credentials
    when the name of database is changed to a name without char "-" or "\_" it works fine.
3. try to run oned
#### another way to reproduce
MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS test-test;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''test-test'' at line 1
#### right command
MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS \`test-test\`;
Query OK, 1 row affected (0.00 sec)
## Explanation
oned tries to check of existing database https://github.com/OpenNebula/one/blob/master/src/sql/MySqlDB.cc
by SQL command "CREATE DATABASE IF NOT EXISTS db_name"
if the name of mysql database consists char "-" or "_" right SQL command is "CREATE DATABASE IF NOT EXISTS \`db_name\`"

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
Hello! For the moment we have decided that it's not a good idea to change the code to accept these kinds of Database names because MySQL can have problems to manage these kind of names.

If you can, we prefer that you use names without "-" or "_".

Regards!
