### ISSUE TITLE
Configurable VNC import options

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1754]
# Enhancement Request
## Description

Be able to configure some aspects like for instance keymap setting

## Use case

Import VMs from vCenter

## Interface Changes

The recommended implementation is through a configuration file, with global variables. This is an admin operation.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
committed in c596b187df3c6486a5651ca00192a222a3d4605f
