### ISSUE TITLE
RAFT sync leads to Duplicate key on case sensitive login

### ISSUE THREAD

**Issue by sulaweyo** [OpenNebula/one#1761]
# Bug Report
## Version of OpenNebula
- [ ] 5.2.2
- [ ] 5.4.0
- [x] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [x] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component
- [x] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [x] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
3 node Cluster via RAFT
Users are coming from ldap
mysql on each master node
There seems to be a difference between login and database in regards to case sensitive logins. If a user with capital letters logs in without them and already exists in the DB this login will result into a duplicate key in the logdb

### Expected Behavior
The login fails and that's it

### Actual Behavior
The login fails but the cluster no longer works as all DB operations are blocked by the duplicate key

## How to reproduce
user name in ldap: 'John.Tester’
login once with correct credentials so the user gets created, logout
login as: ‘john.tester’
-> login fails and then the whole cluster is dead as the logdb tries to insert the same user again but with lower case which results into "Duplicate entry ‘john.tester’ for key ‘name’"

**Comment by sulaweyo** [comment]
Looks related to #602

**Comment by rsmontero** [comment]
Duplicated keys are now handled here: https://github.com/OpenNebula/one/blob/master/src/sql/LogDB.cc#L382
