### ISSUE TITLE
 No way for attach new files from FILES_DS to already created VMs

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1763]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
No way for set FILES_DS variable via Graphic Wizard for already created VMs

### Expected Behavior
![image](https://user-images.githubusercontent.com/7556217/36386664-cd1d4c6a-1596-11e8-8357-5b7561697104.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/7556217/36386679-dd4db962-1596-11e8-96e4-879a0f9d491b.png)

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mzealey** [comment]
This is a really annoying bug, sunstone even has an option to add FILES_DS to a running vm but any config you put in gets ignored. What is the reason for stripping FILES_DS out of any config updates? I am setting it like `$FILE[IMAGE="test.sh", IMAGE_UNAME="oneadmin"]`

**Comment by Th0masL** [comment]
It looks like this problem is still happening on v6.0.

Is there a workaround that could be implemented to bypass this limitation ?

**Comment by paczerny** [comment]
Duplicate #5317, solved, fix should be in 6.0.3
