### ISSUE TITLE
Update configuration for running VM 

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1764]
# Enhancement Request

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
There is need posibility for update configuration when VM in running state.

### Actual Behavior
```
[one.vm.updateconf] configuration cannot be updated in state RUNNING
```

## How to reproduce
* Start VM
* `onevm updateconf <vmid>`

## Use case
It is needed for update some contextulization variables (eg. remove PASSWORD variable imminently after first start) or attach new init scripts.
User should be noticed that he still need completely shutdown his VM for apply new configuration.

## Interface Changes
Maybe small warning in sustone interface for user, that new configuration will be applied only after shutdown VM.

# Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
This problem is still there

**Comment by rsmontero** [comment]
This issue will require:
* Generate new context CD
* Change CD media with new CD
* Trigger context scripts on udev rule (change CD)

**Comment by atodorov-storpool** [comment]
Currently as a workaround I am working with a patched _onedb_live.rb_ to allow adding entries 
https://github.com/OpenNebula/addon-storpool/blob/onedb_livePatch/patches/ruby/5.8.1/onedb_live.rb.patch

With it I can add/change[*]/delete context entries in any VM state.

[*] the changed entry has no CDATA element. So I am considering to use delete-then-add of an element instead because the patched function do insert the value in CDATA element.

Yeah, it is not perfect at all but is doing the job until this is resolved...

**Comment by paczerny** [comment]
PRs for merge:

* one already merged
* docs: OpenNebula/docs#712 into master
* development: OpenNebula/development#685 into master

**Comment by tinova** [comment]
check with vlasta about context reconfigure trigger in OS over vCenter

https://docs.microsoft.com/en-us/windows/win32/power/power-setting-guids

**Comment by tinova** [comment]
adding issue to vmware context repo
