### ISSUE TITLE
Add support for IOPs attributes for attach disks

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1769]
# Enhancement Request
## Description

IOPs are not honored when attaching a disk. This issue is to add this attributes to the disk XML generated to attach the disk.

Also this issue is to review any missing attributes not used in attach disks

## Use case
NaN

## Interface Changes
None
 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
PR to merge: https://github.com/OpenNebula/one/pull/1779

**Comment by rsmontero** [comment]
Needs to add the [default options in documentation](http://docs.opennebula.org/5.4/deployment/open_cloud_host_setup/kvm_driver.html#disk-nic-hotplugging).
