### ISSUE TITLE
Can not save volatiled disk into persistent storage

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1770]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [X] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Can not save volatiled disk into persistent storage:

```
onevm disk-saveas 5878 0 "mydrive"
```

### Expected Behavior
disk will saved

### Actual Behavior
```
[one.vm.disksaveas] Cannot use DISK. DISK does not have a valid IMAGE_ID.
```

## How to reproduce
* Create VM with volatiled disk
* Try to save it

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
It was in mail lists since 2012 also:
http://lists.opennebula.org/pipermail/users-opennebula.org/2012-July/037178.html

**Comment by atodorov-storpool** [comment]
The volatile disks are created in the SYSTEM datastore. This type of datastores doesn't hold images. So there should be an interface to point in addition at which IMAGE datastore to save the volatile image.
