### ISSUE TITLE
Can not change vm disk parameters for created VMs

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1771]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [X] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
No way for change disk paramters for already created VMs.
I can't even change the driver options for it. (eg. virtio/sata/ide)

It can be implemented via command:
```
onevm updateconf <vmid>
```

### Expected Behavior
`onevm updateconf <vmid>` - returns array for changing disk parameters

### Actual Behavior
`onevm updateconf <vmid>` - fully ignored any disk parameters

## How to reproduce
Just try to change driver option for already created VM

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
For we this isn't a bug, is a new feature, the `updateconf` command is only to update the Virtual Machine Configuration, not the disks. I'm going to change this issue to backlog. we will study this new feature to add, if is possible, in the release one-5.8.

You can use the `onedb update-body` for the moment

**Comment by hydro-b** [comment]
On Wed, Apr 04, 2018 at 10:15:08AM +0000, juanmont wrote:
> For we this isn't a bug, is a new feature, the `updateconf` command is
> only to update the Virtual Machine Configuration, not the disks. I'm
> going to change this issue to backlog. we will study this new feature
> to add, if is possible, in the release one-5.8.
> 
> You can use the `onedb update-body` for the moment

IMAGE in use by a VM is part of the VM (aka DISK IMAGE) and not a
"standalone" IMAGE. And hence part of the updateconf of the VM as I am
concerned. It should not be needed to re-instantiate a VM, or
detach / attach disks for already running VMs just to change a
parameter. I Have discussed with Javi Fontan last ONE conf and he agreed
it should not be needed to re-instantiate VMs to change things like this.

Besides this, "silently" ignoring changes is not user friendly. User
still *thinks* the change is succesful. We've run into this ourselves
multiple times.

Gr. Stefan

**Comment by juanmont** [comment]
yes you are right we'll be probably reusing the updateconf interface or, alternatively specific disk/nic operation. Also we'll take a look to improve the user feedback when we implement this issue. Thanks for your comments

**Comment by rsmontero** [comment]
This issue will be implemented as part #5529
