### ISSUE TITLE
Consider opportunity for not lock images when creating VMs from it.

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1781]
# Enhancement Request
## Description
When using non-persistent images, this image is marks as USED and it is can't be removed or replaced.
But in many cases used filesystem file-based storage. 
New drives creates like simple files and when instantiating just copy from images to system datastore as simple files. There is no need for lock them, because any new image have no refference on old one and old image can be simple removed or replaced without prejudice to the referrenced images.

We can add  option for disable locking non-persistent images on some storage drivers.
Example:
`shared` and `ssh` - have locking disabled
`qcow` and `ceph` storage - have locking enabled

## Use case
When locking is disabled you don't need to store base image until it have at least one child, you can update or remove it without any problems.

## Interface Changes
I think it can be specific driver option like `RELEASE_PARENTS = "YES"`, and if it exist opennebula will not mark new images as USED

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
If I am not wrong the "golden" non-persistent image is locked/protected because it is needed for rocover:delete-recreate action.

**Comment by kvaps** [comment]
Hm I didn't thought about that, but even so any way there is need some opportunity for replace used drives.
Even the VMs will be recreated from them, they can use newer image for that.
