### ISSUE TITLE
 Sunstone: No way for update VM configuration if it have restricted vector atributes.

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1790]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [x] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
If you have `VM_RESTRICTED_ATTR` with some variables inside vector attributes it can refuse you for changing another allowed parameters.

## How to reproduce
Let's say you want to refuse users for change graphic console options, but allow changes on input methods.

* Define in `oned.conf`:
```
VM_RESTRICTED_ATTR = "GRAPHICS/LISTEN"
VM_RESTRICTED_ATTR = "GRAPHICS/PASSWD"
VM_RESTRICTED_ATTR = "GRAPHICS/PORT"
VM_RESTRICTED_ATTR = "GRAPHICS/TYPE"
```
* Restart opennebula service
* Create new VM from template with enabled graphic console
* Open sunstone and go to the any VM as user
* On "Conf" tab click "Update configuration button"
* Go to the "Input/Output" tab
* Try to add tablet pointer device

### Actual Behavior
You will see this error:
```
[one.vm.updateconf] User [356] : Template includes a restricted attribute LISTEN.
```

### Expected Behavior
Sunstone should allow for change INPUT parameters because they are allowed.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Same problem with RAW parameter if VM have seted RAW parameter which restricted by `VM_RESTRICTED_ATTR` in `oned.conf`
You will recive error even you try to update any other parameter.

**Comment by abelCoronado93** [comment]
Same in CLI

updateconf sends all the conf attributes and the core interprets that everything has changed
