### ISSUE TITLE
Sunsone: There is no possibility for disable Graphics on Input/Output tab

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1791]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
There is no possibility for disable Graphics console configuration on Input/Output tab but leave Inputs options.

![image](https://user-images.githubusercontent.com/7556217/36676689-af500a30-1b0c-11e8-947e-c3192494436f.png)

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment]
This isn't a bug. Thanks for the suggestion. We will consider this new feature for future releases.

**Comment by sbbarragan** [comment]
That option appears in the sunstone views [configuration files](https://github.com/OpenNebula/one/blob/master/src/sunstone/etc/sunstone-views/mixed/admin.yaml#L268)

We close until further feedback is provided.
