### ISSUE TITLE
Remove resource references from VDC when erased

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1815]
# Bug Report
## Version of OpenNebula
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [X] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

When for instance a vnet is deleted, its reference is not removed from the VDCs containing it.

### Expected Behavior

To be removed from VDC when the object is removed

### Actual Behavior

It is not removed from VDC when the object is removed

## How to reproduce

Create vnet A. Add it to VDC B.

Remove vnet A. Check VDC B resources.

**Comment by paczerny** [comment]
PRs for merge:
* one: #3458 into master
* docs: OpenNebula/docs#680 into master
* development: OpenNebula/development#664 into master
