### ISSUE TITLE
Importing network from vSphere doesn't accept the MAC address range

### ISSUE THREAD

**Issue by tsarajar** [OpenNebula/one#1817]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [x] vCenter

## Description

Importing network from vSphere doesn't accept the MAC address range.

onevcenter networks --vcenter (our address) --vuser 'foobar'
Password:

Connecting to vCenter: (our address)...done!

Looking for vCenter networks...done!

Do you want to process datacenter DC [y/n]? y

  * Network found:
      - Name                  : ON1-Prod
      - Type                  : Port Group
      - Cluster               : ON1-Mac
      - Cluster location      : CI/Mac
      - OpenNebula Cluster ID : 101
    Import this Network (y/[n])? y
      - vcenter vlan id = 629
    How many VMs are you planning to fit into this network [255]? 2048
    What type of Virtual Network do you want to create (IPv[4],IPv[6],[E]thernet)?E
    Please input the first MAC in the range [Enter for default]: 02:04:43:e0:46:09

### Expected Behavior
It accepts the input

### Actual Behavior
Error: undefined local variable or method `first_mac_answer' for VCenterDriver::Importer:Class
Did you mean?  first_mac/
["/usr/lib/one/ruby/vcenter_driver/importer.rb:757:in `block (2 levels) in import_networks'", "/usr/lib/one/ruby/vcenter_driver/importer.rb:641:in `each'", "/usr/lib/one/ruby/vcenter_driver/importer.rb:641:in `block in import_networks'", "/usr/lib/one/ruby/vcenter_driver/importer.rb:628:in `each'", "/usr/lib/one/ruby/vcenter_driver/importer.rb:628:in `import_networks'", "/usr/bin/onevcenter:156:in `block (2 levels) in <main>'", "/usr/lib/one/ruby/cli/command_parser.rb:449:in `run'", "/usr/lib/one/ruby/cli/command_parser.rb:76:in `initialize'", "/usr/bin/onevcenter:57:in `new'", "/usr/bin/onevcenter:57:in `<main>'"]

## How to reproduce

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Semedi** [comment]
this problem is solved in 5.6
