### ISSUE TITLE
vm migration between vCenter clusters warning.

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#1820]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [x] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [x] vCenter

## Description

Migrate running (--live) machines from CLI works but you will not notice anything in case of vCenter failure (CLI behaviour).

This bug consist in:

* Check through cli whenever the vCenter migration fail
     - Its the machine still usable?
     - Check vcenter_attributes (specially VCENTER_CCR_REF)

* Display through stdout an error telling the user the reason of the failed migration (example: couldn't migrate due to incompatibility)

* Check vm migration on sunstone.
      - normal migrate (poweroff)
      - live migration (running)
   
see if the feedback provided by sunstone is good enough (same as cli).
 

### Expected Behavior

Proper messages when you fail to migrate the machine

### Actual Behavior

CLI does not tell u anyhing about the failure.

## How to reproduce

migrate a vm between clusters with any vCenter error.

**Comment by jgarriuni** [comment]
Contained in #1837
