### ISSUE TITLE
Offending XML with provided XSD

### ISSUE THREAD

**Issue by Madko** [OpenNebula/one#1821]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [x] 5.4.7
- [ ] Development build

## Component

- [x] API
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

While trying to use pyone we find out that some XML from VMpool/VM info XML RPC call are offending the [XSD](https://github.com/OpenNebula/one/blob/release-5.4.7/share/doc/xsd/vm.xsd) provided by OpenNebula

### Expected Behavior

XSD should match XML

### Actual Behavior

Some part of the actual XML are not described in the XSD. Maybe the XSD is out of date ?
More information here https://github.com/OpenNebula/addon-pyone/issues/6

## How to reproduce

Not sure from where the offending part of the XML came from. Cf previous link about ALLOW_ORPHANS. Perhaps this part comes from the fact this VM has a snapshot.

- Try to define some VM, make a snapshot
- Parse the XML with the XSD

I can also provide other offending XMLs, like this [one](https://pastebin.com/EKJj5XjH) (cf line 475)

Best regards,
Edouard

# Enhancement Request
## Interface Changes

 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mmeroberts** [comment]
With the introduction of ip6 into an environment it became clear that the xsd no longer match the values we receive when using the API. As you have chosen to use an xml rpc it is reasonable for the users of the API to expect it to be described in xsd.  Sadly in the latest releases there has been a mismatch between the API and its description.  This means that layered tooling that relies on the xsd for accuracy is now failing and this looks is a real problem to those of us who need to drive Opennebula from an API.  Up to this point Opennebula has proven to be so much better than openstack for managing a cloud and it is sad to see these descrepencies creeping in.

**Comment by juanmont** [comment]
I'm going to start to working on this issue. Can you tell me more offending cases that your had found?

Regards

**Comment by mmeroberts** [comment]
This is the modified XSD I am using for vnet.xsd.

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified"
  targetNamespace="http://opennebula.org/XMLSchema" xmlns="
http://opennebula.org/XMLSchema">
  <xs:element name="VNET">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ID" type="xs:integer"/>
        <xs:element name="UID" type="xs:integer"/>
        <xs:element name="GID" type="xs:integer"/>
        <xs:element name="UNAME" type="xs:string"/>
        <xs:element name="GNAME" type="xs:string"/>
        <xs:element name="NAME" type="xs:string"/>
        <xs:element name="PERMISSIONS" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="OWNER_U" type="xs:integer"/>
              <xs:element name="OWNER_M" type="xs:integer"/>
              <xs:element name="OWNER_A" type="xs:integer"/>
              <xs:element name="GROUP_U" type="xs:integer"/>
              <xs:element name="GROUP_M" type="xs:integer"/>
              <xs:element name="GROUP_A" type="xs:integer"/>
              <xs:element name="OTHER_U" type="xs:integer"/>
              <xs:element name="OTHER_M" type="xs:integer"/>
              <xs:element name="OTHER_A" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="CLUSTERS">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:integer" minOccurs="0"
maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="BRIDGE" type="xs:string"/>
        <xs:element name="PARENT_NETWORK_ID" type="xs:string"/>
        <xs:element name="VN_MAD" type="xs:string"/>
        <xs:element name="PHYDEV" type="xs:string"/>
        <xs:element name="VLAN_ID" type="xs:string"/>
        <xs:element name="VLAN_ID_AUTOMATIC" type="xs:string"/>
        <xs:element name="USED_LEASES" type="xs:integer"/>
        <xs:element name="VROUTERS">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:integer" minOccurs="0"
maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="TEMPLATE" type="xs:anyType"/>
        <xs:element name="AR_POOL">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="AR" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="AR_ID" type="xs:string"/>
                    <xs:element name="GLOBAL_PREFIX" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP" type="xs:string" minOccurs="0"/>
                    <xs:element name="MAC" type="xs:string"/>
                    <xs:element name="PARENT_NETWORK_AR_ID"
type="xs:string" minOccurs="0"/>
                    <xs:element name="SIZE" type="xs:integer"/>
                    <xs:element name="TYPE" type="xs:string"/>
                    <xs:element name="ULA_PREFIX" type="xs:string"
minOccurs="0"/>
                    <xs:element name="VN_MAD" type="xs:string"
minOccurs="0"/>
                    <xs:element name="MAC_END" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP_END" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP6_ULA" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP6_ULA_END" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP6_GLOBAL" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP6_GLOBAL_END" type="xs:string"
minOccurs="0"/>
                    <xs:element name="IP6" type="xs:string" minOccurs="0"/>
                    <xs:element name="IP6_END" type="xs:string"
minOccurs="0"/>
                    <xs:element name="USED_LEASES" type="xs:string"/>
                    <xs:element name="LEASES" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="LEASE" minOccurs="0"
maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="IP" type="xs:string"
minOccurs="0"/>
                                <xs:element name="IP6" type="xs:string"
minOccurs="0"/>
                                <xs:element name="IP6_GLOBAL"
type="xs:string" minOccurs="0"/>
                                <xs:element name="IP6_LINK"
type="xs:string" minOccurs="0"/>
                                <xs:element name="IP6_ULA" type="xs:string"
minOccurs="0"/>
                                <xs:element name="MAC" type="xs:string"/>
                                <xs:element name="VM" type="xs:integer"
minOccurs="0"/>
                                <xs:element name="VNET" type="xs:integer"
minOccurs="0"/>
                                <xs:element name="VROUTER"
type="xs:integer" minOccurs="0"/>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

**Comment by rvalle** [comment]
@juanmont let me know when you are done with the changes in XSDs. Since the elements do exist in the current release I can include the updated XSDs in Pyone as soon as you are done and before the 5.6 is released.

**Comment by rsmontero** [comment]
It seems that xsd's are now updated. Closing this issue. We'll reopen if needed
