### ISSUE TITLE
allow scheduled disk snapshots 

### ISSUE THREAD

**Issue by ArnY** [OpenNebula/one#1829]
# Enhancement Request
## Description
It would be really useful if, from the actions tab of sunstone we could create and schedule automatic disk snapshots. Deleting the oldest ones would also be great if we could schedule removal of the oldest snapshots automatically, maybe with a number of snapshot and an automatic rollover in order to prevent performance loss due to a large number of snapshot. I know VM snapshot can be scheduled, but some are using ceph datastores which prevent VM snapshoting.

## Use case
If the VM is running a critical application, disk snapshots would provide a way to secure the data over time.  Creating a scheduled disk snapshot, for example every day at midnight, would allow the user to roll back in time if something bad happens. And to avoid having too many snapshots, the user could decide to only have one week worth of snapshots.

## Interface Changes
In sunstone, in the VM interface, in the "actions" tab, a "disk snapshot" entry should be added.

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by lbtq** [comment]
Adding on to this instead of opening a new issue.  This has not been added in OpenNebula 5.6, though there was another issue closed for it previously: #1300 which was rolled into: #1548

**Comment by OpenNebulaSupport** [comment]
Closing, duplicated in #2340
