### ISSUE TITLE
Integrating docker machine addon

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#1838]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [x] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
Evaluate packaging, to decide if a separate package for docker-machine makes sense to allow deployments in other machines than the OpenNebula front-end.

## How to reproduce

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Need to evaluate which image we use: CoreOS, Ubuntu, etc

**Comment by FlorianHeigl** [comment]
I've been using this with the boot2docker image whenever i need to launch containers. But it was mostly non-persistent stuff, I have not gone further (say, with a distributed storage backend and so on).
CoreOS probably has the best chances for solving kubernetes support along the way?

**Comment by tinova** [comment]
We need to have OpenNebula as a provider in CoreOs's ignition. We'll get there eventually. Meanwhile we'll use a Ubuntu based docker engine. boot2docker seems to have been deprecated.

**Comment by FlorianHeigl** [comment]
@rsmontero can we at least have a single comment along with the close?
