### ISSUE TITLE
Improve error message when Import Wild or VM Template with disks without back reference

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1841]
# Enhancement Request
## Description

If for instance a VM Template with a CD drive without a backing ISO is imported, the import process fails with the following error:

There was an error trying to create an image for disk in vcenter template. Reason: undefined method `_ref' for nil:NilClass 
["/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:252:in `block in import_vcenter_disks'", "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:251:in `each'", "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:251:in `import_vcenter_disks'", "/usr/lib/one/ruby/vcenter_driver/importer.rb:38:in `import_wild'", "/usr/lib/one/ruby/opennebula/host.rb:234:in `import_wild'", "/usr/bin/onehost:271:in `block (3 levels) in <main>'", "/usr/lib/one/ruby/cli/one_helper.rb:558:in `call'", "/usr/lib/one/ruby/cli/one_helper.rb:558:in `perform_action'", "/usr/bin/onehost:267:in `block (2 levels) in <main>'", "/usr/lib/one/ruby/cli/command_parser.rb:449:in `call'", "/usr/lib/one/ruby/cli/command_parser.rb:449:in `run'", "/usr/lib/one/ruby/cli/command_parser.rb:76:in `initialize'", "/usr/bin/onehost:36:in `new'", "/usr/bin/onehost:36:in `<main>'"]

## Use case

Having broken VM Templates orWild VMs

## Interface Changes

Improve error message

# Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Semedi** [comment]
merged and closed
