### ISSUE TITLE
Simplified user created virtual networks

### ISSUE THREAD

**Issue by canance** [OpenNebula/one#1853]
# Enhancement Request
## Description
Add the ability for users to create a virtual network with a predefined VN_MAD and interface/bridge.    

## Use case

For our use case, users don't have knowledge of the underlying infrastructure.  It would be great if an admin could set up a way for users to provision their own LAN segment / networks.  For example, the VN_MAD could be preconfigured to use VXLAN on a specific interface.  The VLAN id could be automatically assigned.  Then users would simply create a new network and not need to be aware of the underlying configuration.

## Interface Changes

 
Admins would have a form that they could set up a predefined configuration for users' to provision their own networks.  Users would then be presented with a simplified version of the form used to create virtual networks.  Additionally, an option could be made available in the cloud view to allow users to create their own networks.  

The CLI could also have a simplified command to set up a default network configuration (similar to the defaultquota) and create a new network.  For example:
`$ onevnet defaultnet --VN_MAD VXLAN --interface em3`
`$ onevnet autocreate`

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Totally, This is the main idea of #826 . Our design goal is to store those default attributed in the VNET and users can just make other vnets from it. Much more like (and probably reusing) vnet reservations, but letting the user define the complete address range.

I'll close this and keep the reference from #826

**Comment by canance** [comment]
Sounds good, thanks!
