### ISSUE TITLE
[openvswitch] support VLAN ID range for VLAN_TAGGED_ID

### ISSUE THREAD

**Issue by Madko** [OpenNebula/one#1865]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [x] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## How to reproduce

# Enhancement Request
## Description

The VLAN_TAGGED_ID of the ovswitch driver has to be a range which is  in fact a coma separated list of ID.

This is the function that validate the VLAN_TAGGED_ID:
def range?(range)
        !range.to_s.match(/^\d+(,\d+)*$/).nil?
end

Since a couple of major version (I don't exactly know which one), OpenVswitch support VLAN range notation (ie start-end). This range function actually prevents this new notation.

## Use case

With current opennebula version, if you want to set a vland range, let's say from VLAN 10 to 15, you have to set
VLAN_TAGGED_ID=10,11,12,13,14,15
Imagine you want to set vlan 10 to 3000...

With range notation you could set this more easily:
VLAN_TAGGED_ID=10-15

And of course you can combine:
VLAN_TAGGED_ID=10,100-200,300,4000-4500

I've try to comment the range test in the tag_trunk_vlans function (/var/lib/one/remotes/vnm/ovswitch/OpenvSwitch.rb) and it works as needed. 

Best way would be to find a good regexp that would match all those cases.

Best regards,
Edouard

## Interface Changes

 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
PRs to merge:
- https://github.com/OpenNebula/one/pull/1879 (pls, squash commits)
- https://github.com/OpenNebula/docs/pull/252

We can consider cherrypick into one-5.4 as well.
