### ISSUE TITLE
LDAP authentication server groups

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1870]
# Enhancement Request
## Description

The goal of this issue is to reduce the number of connections/authentication requests to LDAP servers. Currently OpenNebula always uses the full list of servers.

## Use case

Improve LDAP management to define "availability" groups. The logic would be as follows: Password is check only once per group and:

* If authentication succeed answer is returned to OpenNebula
* If authentication fails proceed to next group
* Connection failed, test next server in group

## Interface Changes

 
Update ldap.conf file to define server groups as:

```
LDAP_GROUP_1 = serverA1, serverB1
LDAP_GROUP_2 = serverA2, serverB2
```

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
PRs to merge:
* https://github.com/OpenNebula/one/pull/1998
* https://github.com/OpenNebula/docs/pull/262
