### ISSUE TITLE
Let ACL VDC rules to be configurable by admins.

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1872]
# Enhancement Request
## Description

Let users for example to list their own VDCs requires to grant VDC use to them. Currently this permission is not granted. Also for some setups it may be interesting to let the users check the assigned clusters (and their characteristics like number of hosts) to the VDC.

Also when a cluster is added to a VDC a set of automatic rules are generated to let users access all cluster resources. Sometimes it's better to fine grain tune these rules.

## Use case

Fine grain control on ACL rules for VDCs

## Interface Changes

 
oned.conf should include a list of rules to add:

VDC_DEFAULT_ACLS = "defalt acls generated to access VDC resources"
VDC_CLUSTER_DEFAULT_ACLS = "default acl generated when a cluster is added to a VDC"

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
@rsmontero would it work in case of specify in VDC template?

**Comment by kvaps** [comment]
Probably don't
