### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by yekm** [OpenNebula/one#1874]
I see no problem adding PostgreSQL support to both C++ and ruby backend.

I am not sure about sql statements. Are they compatible with PostgreSQL? Can somebody comment on that?

I see no logic related to multiplexing various sql queries to suitable databases in source code. Am I missing something? (I hope this is not the reason why you still haven't added pg support)

**Comment by juanmont** [comment]
Sorry, but we think that this is not an issue, you can put your question in our [forum](https://forum.opennebula.org/).
