### ISSUE TITLE
Setuid/Setgid for VM Templates

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1897]
# Enhancement Request
## Description

This feature intends to enhance the user and group ownership of a VM instantiated from a particular VM Template.

This entails the creation of a new way of defining special permission for owners (similar to setuid in unix filesystems) and groups (similar to setgid in unix filesystems).

## Use case

This feature enables the use case of a VM Template that will get instantiated always under a particular username or group, inheriting the permissions and visibility of those users/groups.

## Interface Changes

This new setting would be available through special attributes in the VM Template, that will be made available in Sunstone in the VM Template editions and VM instantiation from VM Template dialogs, as well as in the CLI “onetemplate instantiate” command

Sunstone extensions
The following dialogs would be enhanced to offer the setuid/setgid functionality:
VM Template instantiation. Two dropdowns to select instantiate as user and/or group.
VM Template update. Two dropdowns to select instantiate as user and/or group.

CLI extensions

Two new flag for the “onetemplate instantiate” operation:
--instantiate_as_uid
--instantiate_as_gid

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
duplicated #1913
