### ISSUE TITLE
Allow to resize a disk in the cloud view

### ISSUE THREAD

**Issue by abelCoronado93** [OpenNebula/one#1910]
# Enhancement Request
## Description
Allow to resize a disk in the cloud view

## Use case
N/A

## Interface Changes
Add resize-disk button and dialog in cloud view

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by astronode** [comment]
Hi team, just wanted to point out that whilst it's possible to add the disk resize button in the yaml view file, it doesn't actually work. 
Looking forward to this feature in 5.6.
Thanks
