### ISSUE TITLE
setuid/setgid for VM Templates

### ISSUE THREAD

**Issue by juanmont** [OpenNebula/one#1913]
# Enhancement Request
## Description
This feature intends to enhance the user and group ownership of a VM instantiated from a particular VM Template.
This entails the creation of a new way of defining special permission for owners (similar to setuid in unix filesystems) and groups (similar to setgid in unix filesystems).
This feature enables the use case of a VM Template that will get instantiated always under a particular username or group, inheriting the permissions and visibility of those users/groups.

## Interface Changes
This new setting would be available through special attributes in the VM Template, that will be made available in Sunstone in the VM Template editions and VM instantiation from VM Template dialogs, as well as in the CLI “onetemplate instantiate” command

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment]
# VM Instantiation
- [ ] Modular advanced options

# Template upgrade
- [ ] PCI -> Input / Output
- [ ] Rename tab 'Other' to 'Tags'
- [ ] Instantiate as user/group into tab 'General' as advaced options
