### ISSUE TITLE
802.1Q drivers should check that there is no other tagged interface in the network bridge

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1914]
# Enhancement Request
## Description

This issue is to prevent that more than one tagged interface is added to a network bridge when using 802.1Q drivers. This may come in handy when changing VLAN_ID's in existing networks.

## Use case

See above

## Interface Changes

 
None

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Closing as this is already implemented.

```
# Set to true to check that no other vlans are connected to the bridge.
# Works with 802.1Q and VXLAN.
:validate_vlan_id: false
```
