### ISSUE TITLE
opennebula deletion of logdb table is not chunked and delays startup

### ISSUE THREAD

**Issue by sjmudd** [OpenNebula/one#1927]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [x] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

Not sure the exact component related but this is related to `LogDB::purge_log()` which I think is called on startup.

## Description

On startup colleagues have seen that opennebula seems to hang waiting on the database.
Further investigation showed that it was trying to delete 23,000,000 rows from the logdb table
in a single transaction. Supposedly auto-purging is enabled (I'm told). I'm the DBA that manages
this database.

This took the MySQL server about 15 minutes to execute and resulted in 150MB of binlogs being generated (using minimal RBR) on mysql-community-server-5.7.18. The full binlogs would have been much larger.

### Expected Behavior

It seems to me that a few things are being done incorrectly here:
* do not do large transactions but delete rows in smaller chunks (even if you have to delete this number of rows)
* delete in small chunks giving a small delay between each one, thus not consuming all I/O on the server
* background this process as I guess it shouldn't affect other tasks that are ongoing and would allows the processes to start up with an interruption.

### Actual Behavior

* one potentially huge DELETE statement.

## How to reproduce

Startup opennebula and see that it seems to hang for a long time.
* requires having a large unpurged logdb table.

For many large busy MySQL systems where replication may be involved it's convenient always to break large transactions into smaller chunks.

My suggestion would be to:
* run the `DELETE` statement in a loop with a `LIMIT X` (where X is configurable but something like 10000 by default)
* record the number of rows deleted. Most DB drivers provide this information. I'm not sure if the interface you are using provides it.
* add a small configurable delay (2ms?) if the number of rows deleted > 0
* exit the loop when number of deleted rows  = 0

Related to: https://github.com/OpenNebula/one/issues/1365

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by sjmudd** [comment]
Some more info on what was observed:

From `SHOW ENGINE INNODB STATUS\G`

```
---TRANSACTION 7940344005, ACTIVE 968 sec fetching rows, thread declared inside InnoDB 4998
mysql tables in use 1, locked 1
6013405 lock struct(s), heap size 849305808, 34055728 row lock(s), undo log entries 1
MySQL thread id 36110863, OS thread handle 140294443403008, query id 10000295629 onefrontend.example.com 10.1.2.3 opennebula_user updating
DELETE FROM logdb WHERE timestamp > 0 AND log_index >= 0 AND log_index < 35405467
```
Note:

* ACTIVE 968 sec - time the query had taken to run (so far)
* heap size 849305808 - this is about 900MB. MySQL has to record how to unwind this transaction if the commit fails so it takes 900 MB of memory to manage this , all of which gets stored in the undo log (ibdata1 file) prior to the commit and has to be flushed out afterwards.
* managing 34 million rows locks also requires resources and may block other mysql clients which try to access these rows.

The MySQL server itself was dedicated to opennebula but on a shared platform a transaction this big would affect other users.

Server was configured with the following settings:
```
binlog_format = ROW
binlog_row_image = minimal
```

Here you can see the binlogs generated before and after this transaction:

```
-rw-r----- 1 mysql mysql 101M Apr  3 14:19 binlog.253891
-rw-r----- 1 mysql mysql 101M Apr  3 14:20 binlog.253892
-rw-r----- 1 mysql mysql 203M Apr  3 15:00 binlog.253893   <=======
-rw-r----- 1 mysql mysql 101M Apr  3 15:06 binlog.253894
-rw-r----- 1 mysql mysql 101M Apr  3 15:08 binlog.253895
```
Looking in the binlogs I can see the number of rows deleted:

```
[root@host log]# mysqlbinlog -vvv binlog.253893 | grep -c '### DELETE FROM `one`.`logdb`'
29721217
```

So 29,721,217 rows in 142MB on disk (I checked where in the binlog this transaction started).

**Comment by rsmontero** [comment]
Thank you very much for the detailed information. We are going to follow the proposed approach to purge log entries in small chunks.

We'll address this issue by:
1. Adding a configuration parameter with the max number of log rows to delete every purge timeout
2. Limiting the delete query to this max number of log rows.

**Comment by rsmontero** [comment]
Merged upstream.
