### ISSUE TITLE
[bug] Sunstone ignored the SIZE parameter of a DISK in a VM template

### ISSUE THREAD

**Issue by wind0204** [OpenNebula/one#1937]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
I think I found 2 bugs in 5.4.6

There is no problem when I instantiate the template using "onetemplate" command.

But when I used Sunstone today, it ignored the SIZE part of the DISK resulting in creating a virtual disk of 1 MiB, as the same size of the original blank dummy image.

Well, it also ignored the default value for the USER_INPUTS variables as well which I set earlier this morning, using old default values, but I could easily find those errors immediately in the instantiation stage, but the SIZE part wasn't very prominent.

***After the discovery of the new bug, I encountered another one, I shut down the VM, and tried to resize the volume from 1 MB to 8192MB in Sunstone, but Sunstone actually changed it to 8MB. Then I tried to change it using GB metric, (i.e. 8GB) when I input 8GB it said something like 'it's already in the same size'.

### Expected Behavior
It should not ignore the parameters I set.

The new image should be resized to the size I have input in SIZE in the DISK section.

The Sunstone web app should show me the newly set default values for the CPU and MEMORY USER_INPUTS input forms not showing the old previous values.

### Actual Behavior
"But when I used Sunstone today, it ignored the SIZE part of the DISK resulting in creating a virtual disk of 1 MiB, as the same size of the original blank dummy image.

Well, it also ignored the default value for the USER_INPUTS variables as well which I set earlier this morning, using old default values, but I could easily find those errors immediately in the instantiation stage, but the SIZE part wasn't very prominent.

***After the discovery of the new bug, I encountered another one, I shut down the VM, and tried to resize the volume from 1 MB to 8192MB in Sunstone, but Sunstone actually changed it to 8MB. Then I tried to change it using GB metric, (i.e. 8GB) when I input 8GB it said something like 'it's already in the same size'.
"

## How to reproduce
I'm sorry but I don't really know... and have the time and scripts to find out how to reproduce it and the factors required to reproduce it. but I did try restarting oned and sunstone together in vain.

**Comment by iandk** [comment]
@wind0204 Is this the same Issue? https://github.com/OpenNebula/one/issues/1936

**Comment by wind0204** [comment]
@iandk I guess one of the issues I reported here is the same issue. I don't know what the author of #1936 did when he "increased the 'Size on instantiate' ", but what I did is having the SIZE value in the template changed in advance.

**Comment by abelCoronado93** [comment]
@wind0204, It's okay, I fixed #1936.

I close this issue for the moment.

Regards!

**Comment by wind0204** [comment]
This problem has never happened since when I started trying OpenNebula 5.2, and I upgraded it from 5.4.1 to 5.4.6 on Feb. 27. I've tried to figure out the cause a little just now clicking around..

 I found out that you can write SIZE parameter and Sunstone does read it and show the text 8192MB and the input form at the preparation phase of a template instantiation - with the draggable knob in which the minimum leftmost position is 8192MB- . but the thing is after clicking Instantiate, it instantiates with no "Size change on instantiate"... i.e. the cloned image has only 1 MB as the original image does.
DISK = [
  CACHE = "none",
  DEV_PREFIX = "sd",
  DISCARD = "unmap",
  DRIVER = "raw",
  IMAGE = "empty-ceph",
  IMAGE_UNAME = "oneadmin",
  ORIGINAL_SIZE = "1",
  SIZE = "8192" ]
But, changing the value of the disk size in instantiation preparation page from "8GB" to 8193MB, does make Sunstone clone the image resizing to 8193MB.

And I guess the second issue I reported is just a change of policy on Sunstone, it ignores the default variables of USER_INPUTS but doesn't ignore the real value like CPU, MEMORY at least.

The last issue I wrote is really weird... and I found how to reproduce it and have made another post : https://github.com/OpenNebula/one/issues/1949
