### ISSUE TITLE
Add "UPDATE" button to top of page for VM actions

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#1940]
# Enhancement Request
## Description
In larger cloud deployments with lots of (several hundreds) of templates / images / network interfaces you have to scroll down a very long page to click the "UPDATE" button. Adding a "UPDATE" button to top the top of the page saves some time here. For example when hot-adding a (newly creadted) DISK IMAGE in the top of the list, you then have to scroll down all the way to the bottom to click the "update" button.

## Use case

For every VM action where I normally would have to scroll down.

Save time, avoid frustration, minor UI improvement.

## Interface Changes

 
Duplicate already existing button to top of page. Or make the existing button "floating", i.e. that it scrolls down / up.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
will be redesigned in #5422
