### ISSUE TITLE
Storage quotas and IP's quotas

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1946]
# Enhancement Request
## Description
Add Storage quotas and IP's quotas in the Sunstone dashboard

## Use case
More information for the admins

## Interface Changes
Add two widgets with the respective quotas in the dashoboard

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by astronode** [comment]
This would be awesome!

**Comment by jloboescalona2** [comment]
@tino PR to approve:
- Test: https://github.com/OpenNebula/development/pull/1054
- ONE: https://github.com/OpenNebula/one/pull/4877

**Comment by jloboescalona2** [comment]
- docs: https://github.com/OpenNebula/docs/commit/95bd5cf54bda141561cf460c3802d1998f22b63d
