### ISSUE TITLE
Sunstone thinks the unit of the image size is GB when it's actually MB.

### ISSUE THREAD

**Issue by wind0204** [OpenNebula/one#1949]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
1. Sunstone thinks a virtual disk image of nMB is as big as nGB. As a result refuses to resize when you try to resize the image from nMB to an amount bigger than nMB

2. Sunstone resizes a virtual disk image to nMB when the user has actually input nGB.

### Expected Behavior
1.Resize to 2048MB when I input 2048MB. not 2MB.
2.Correctly recognize the current size, i.e. if it's 2MB don't think it as 2GB and refuse to resize it to 1GB.

### Actual Behavior
When I try to resize an image of 1MB to 1024MB, Sunstone says "[one.vm.diskresize] New disk size has to be greater than current one" because it thinks the original size was in GB, when it's in MB, so when it's 1MB you can't input 1024MB, you should input more than around 1024MB so that Sunstone would think it as 2GB, I succeeded it with writing about 1688MB having failed with 1500MB.  but then, what Sunstone does after the retrieval of the parameter 1688MB or 2048MB.. is resizing the image to 2MB from 1MB instead of resizing it to 2GB.. I've made another issue

## How to reproduce
1. Deploy a VM with a virtual block disk image of 2MB.
2. Try to resize it to 2048MB
3. Try again and again Increasing it from 2048 to another bigger number until Sunstone resize it to 3MB instead of 3GB.

**Comment by abelCoronado93** [comment]
duplicated? https://github.com/OpenNebula/one/issues/1671

**Comment by abelCoronado93** [comment]
solved in #1671
