### ISSUE TITLE
Automatic network selection

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1953]
# Enhancement Request
## Description

The scheduler should be able to select a vnet for NIC based on the user reachable set of vnets, and the available resources.

## Use case

Instead of having end users selecting networks, or maintaining a large set of VM Templates, having the ability in the scheduler to select a proper virtual network

## Interface Changes

Placeholder in NIC for "usable networks"

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Is this issue deprecated? We already have:
```
NIC=[
  NETWORK_MODE="auto"
]
```

**Comment by al3xhh** [comment]
We already have this functionality, closing.
