### ISSUE TITLE
Non-persistent IMAGE even when DEFAULT_IMAGE_PERSISTENT_NEW=YES

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#1960]
# Enhancement Request
## Description
Be able to create non-persistent images when the default in oned.conf is to create persistent images.

## Use case

Existing feature, just able to use "non-persistent" when creating new IMAGE

When persistent is not "enabled" in dialogue, you might think that the image will be not persistent. While it ends up being persistent because ONE admin had configured so.

## Interface Changes

Maybe an extra "check box" in sunstone IMAGE dialogue to force non-persistent image to override the oned.conf defaults (when in effect). Or tick the checkbox with "persistent" so you know it will end up being persistent and manual action later is needed.

In our environment we have mostly persistent images, and don't want to risk data loss, so we set the following:

DEFAULT_IMAGE_PERSISTENT     = "YES"
DEFAULT_IMAGE_PERSISTENT_NEW = "YES"

This works great, but sometimes you want to make a non-persistent image (GOLDEN image mainly) and in this case there is no way to do that without, at a later point in time (after creation), change that to non-persisent.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Hi, 

Please note that there is a bug that maybe affecting you. #1328. Basically, this values may be set in the user/group attributes. 

In any case value in the template of the new image should take precedence to the default provided for user or group.

**Comment by rsmontero** [comment]
Merged upstream. Sunstone now presents three states for Image persistent attribute (unset, the default, will follow DEFAULT_IMAGE_PERSISTENT_NEW; and either YES/NO to overwrite this default
