### ISSUE TITLE
SSH or LocalCommand hangs on large stderr

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#1964]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [X] 5.4.10

### Actual Behavior
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [X] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACLon large stderr
- [ ] vCenter

## Description

If command execution via `SSHCommand`, or `LocalCommand` from the `CommandManager.rb` get long stderr (>65k), the execution infinitely hangs. 

## How to reproduce

Example:

```ruby
#!/usr/bin/ruby

$: << '/usr/lib/one/ruby'

require 'CommandManager'

exec = LocalCommand.run('"head -1000 /var/log/syslog >&2"')
puts "Done"
```

This test run never reaches the `Done` message.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Also, remove verbosity `-x` specified as part of the shebang command in the remote scripts. Applies at least for `remotes/tm/ssh/mvds`.

**Comment by kvaps** [comment]
Hi, can it be connected with https://github.com/OpenNebula/one/issues/1702?
I mean, can these hanged commands hang oned daemon itself?

**Comment by vholer** [comment]
These hung commands (like the above) shouldn't hang the oned daemon itself. But, they block any other operation with the VM. If there are more such VMs with blocked actions, they can hang the associated daemons (one_vmm_exec, one_tm etc.), the daemons can go out of their thread pools. Checking the process list and killing just the particular Ruby daemon, not the oned itself, should be enough to work around the situation. oned will start the daemon again.

I would leave both problems as separate issues, #1702 needs further investigation.

**Comment by kvaps** [comment]
Probably this is completely what you said, I have no hanged oned daemon itself, but have blocked actions on VMs.
I'll try to kill only specific processes next time, thanks!

**Comment by vholer** [comment]
PR to merge:
- https://github.com/OpenNebula/one/pull/1977

**Comment by vholer** [comment]
One more PR to merge:
* https://github.com/OpenNebula/one/pull/2006
