### ISSUE TITLE
AR Size change in reservations should be disabled in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1967]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [X] 5.4.10
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

The option is not disabled so the user receives the error from OpenNebula core instead

### Expected Behavior

The option to resize ARs should not be present in reservations

### Actual Behavior

You can resize the AR in Sunstone, but the core disallows it with an error.

## How to reproduce

Resize the AR of a reservation

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
I think It also about adding new ranges, that also allowed but unacceptable for network reservations.

**Comment by rsmontero** [comment]
Adding new ranges is in fact the mechanism to extend a reservation, no need to disable this.
