### ISSUE TITLE
vCenter custom names for Vms

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#1973]
# Enhancement Request
## Description

Original Post from Dave: https://forum.opennebula.org/t/vcenter-attribute-of-vm-suffix/5920
vCenter driver handles by his own the name of the created vms (one-$id-$name).

Would be nice to have the capability of choose the prefix/suffix of the vm name inside the template

## Use case

VM_SUFFIX = ($i)
Which would generate a vCenter VM name of "www-prd-01(456)" for a VM named “www-prd-01” w/ ID of 456

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
VM_PREFIX already possible at host level.

It would be nice to have it as well VM Template. Also add VM_SUFFIX.

**Comment by carloshm91** [comment]
[DOC]
* https://github.com/OpenNebula/docs/pull/896

[TEST]
* https://github.com/OpenNebula/development/pull/815/

[ONE]
* https://github.com/OpenNebula/one/pull/4084
