### ISSUE TITLE
KVM Driver - vcpu placement = auto

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#1983]
# Enhancement Request
## Description
I am playing little bit with vcpus and pinning. According to libvirt docs, when no vpcu placement is defined, them qemu pins all vcpus to all processor cores(threads in case of HT). On modern numa systems should be better to by default set <vcpu placement="auto">{number}</vcpu>, which instruct qemu to pins vcpus to advisory nodeset by quering numad.

I try to overwrite this setting via RAW data, but without success, because XML tags are not merged.

Looks like simple change in `LibVirtDriverKVM.cc`

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
Probably no need this. https://forum.opennebula.org/t/automatic-vcpu-pinning-using-vm-hooks/5944

**Comment by feldsam** [comment]
Hello, I am reviewing this issue, in meanwhile I figure out that is sufficient use 

```
<numatune>
    <memory mode='strict' placement='auto'/>
</numatune>
```

which automatic pins vcups to only in one numa node, so memory access is optimized.

**Comment by rsmontero** [comment]
should be cover by NUMA feature, any missing functionality not covered by the current NUMA support should be re-formulated in a new issues
