### ISSUE TITLE
Ubuntu installation instructions do not work

### ISSUE THREAD

**Issue by turnupdigital** [OpenNebula/one#1988]
I am relatively new to the game here but... I still feel the installation instructions should work as described.

That command which you have listed for Ubuntu does not work
wget -q -O- https://downloads.opennebula.org/repo/repo.key | apt-key add -

I am getting a "No valid OpenPGP data found"

This one seem to go through ok...

This command says it cant locate packages...
apt-get install opennebula opennebula-sunstone opennebula-gate opennebula-flow

I followed the instructions carefully... If anyone could help me it would be appreciated... I'll be searching for solutions but there doesnt seem to be a ton of people having the issue.

I dont understand.... what has changed? The one video I found he was following your instructions as I did but with a very different result.

**Comment by turnupdigital** [comment]
The issue is obviously something OpenGPG it looks like its installed in the system but I am trying another install of the developer tools. 
sudo apt install gnupg pbuilder ubuntu-dev-tools apt-file

There is very little info out there on this

**Comment by turnupdigital** [comment]
Got the same package not found error when running 

sudo apt install gnupg pbuilder ubuntu-dev-tools apt-file

and that came directly from Ubuntu... so the issue is not directly related to OpenNebula

**Comment by turnupdigital** [comment]
I have manually added deb https://downloads.opennebula.org/repo/5.4/Ubuntu/16.04 stable opennebula
to /etc/apt/sources.list... let's see what happens... that didnt work its already configured now IM getting an error for it being configured twice

I figured out the problem... its my machine... its only in the internal network with no connection to the outside... thats why it cant find any packages.

**Comment by juanmont** [comment]
Hello, Sorry but we think that this problems is not a bug or feature.This question is perfect for our forum.

you can ask to our community: [HERE](https://forum.opennebula.org/)

Regards
