### ISSUE TITLE
High mysql connections usage

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#2000]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [x] 5.4.11
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

After upgrade I see high mysql connections usage. I had limit of 50 on db server, but opennebula won't start. After raising to 100, opennebula starts and I see many connections in sleep state.

### Expected Behavior
Smaller count of opened connections to DB.

### Actual Behavior
Big count of opened connections to DB or it is normal?

## How to reproduce
Upgrade to 5.4.11 and start opennebula service.

      3 opennebula localhost opennebula Sleep 4  <null>
      4 opennebula localhost opennebula Sleep 4  <null>
      5 opennebula localhost opennebula Sleep 4  <null>
      6 opennebula localhost opennebula Sleep 4  <null>
      7 opennebula localhost opennebula Sleep 4  <null>
      8 opennebula localhost opennebula Sleep 4  <null>
      9 opennebula localhost opennebula Sleep 4  <null>
      10 opennebula localhost opennebula Sleep 4  <null>
      11 opennebula localhost opennebula Sleep 4  <null>
      12 opennebula localhost opennebula Sleep 4  <null>
      13 opennebula localhost opennebula Sleep 4  <null>
      14 opennebula localhost opennebula Sleep 4  <null>
      15 opennebula localhost opennebula Sleep 4  <null>
      16 opennebula localhost opennebula Sleep 4  <null>
      17 opennebula localhost opennebula Sleep 4  <null>
      18 opennebula localhost opennebula Sleep 4  <null>
      19 opennebula localhost opennebula Sleep 4  <null>
      20 opennebula localhost opennebula Sleep 4  <null>
      21 opennebula localhost opennebula Sleep 4  <null>
      22 opennebula localhost opennebula Sleep 4  <null>
      23 opennebula localhost opennebula Sleep 4  <null>
      24 opennebula localhost opennebula Sleep 4  <null>
      25 opennebula localhost opennebula Sleep 4  <null>
      26 opennebula localhost opennebula Sleep 4  <null>
      27 opennebula localhost opennebula Sleep 4  <null>
      28 opennebula localhost opennebula Sleep 4  <null>
      29 opennebula localhost opennebula Sleep 4  <null>
      30 opennebula localhost opennebula Sleep 4  <null>
      31 opennebula localhost opennebula Sleep 4  <null>
      32 opennebula localhost opennebula Sleep 4  <null>
      33 opennebula localhost opennebula Sleep 4  <null>
      34 opennebula localhost opennebula Sleep 4  <null>
      35 opennebula localhost opennebula Sleep 4  <null>
      36 opennebula localhost opennebula Sleep 4  <null>
      37 opennebula localhost opennebula Sleep 4  <null>
      38 opennebula localhost opennebula Sleep 4  <null>
      39 opennebula localhost opennebula Sleep 4  <null>
      40 opennebula localhost opennebula Sleep 4  <null>
      41 opennebula localhost opennebula Sleep 4  <null>
      42 opennebula localhost opennebula Sleep 4  <null>
      43 opennebula localhost opennebula Sleep 4  <null>
      44 opennebula localhost opennebula Sleep 4  <null>
      45 opennebula localhost opennebula Sleep 4  <null>
      46 opennebula localhost opennebula Sleep 4  <null>
      47 opennebula localhost opennebula Sleep 4  <null>
      48 opennebula localhost opennebula Sleep 4  <null>
      49 opennebula localhost opennebula Sleep 4  <null>
      50 opennebula localhost opennebula Sleep 4  <null>
      51 opennebula localhost opennebula Sleep 4  <null>
      52 opennebula localhost opennebula Sleep 4  <null>
      53 opennebula localhost <null> Sleep 202  <null>

**Comment by rsmontero** [comment]
Well, this is in fact on purpose and a new feature that boots scalability on large deployments. The increase on DB connections allows a better concurrency on oned threads when accessing the DB. You can limit this with CONNECTIONS on the DB attribute:

https://github.com/OpenNebula/docs/blob/master/source/deployment/references/oned_conf.rst#daemon-configuration-attributes

This new feature has been backported to one-5.4 branch.

**Comment by feldsam** [comment]
Thank you for info
