### ISSUE TITLE
Sunstone: wrong behavor when empty USER_TEMPLATE

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2003]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [x] 5.4.7
- [x] 5.4.8
- [x] 5.4.9
- [x] 5.4.10
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
When you remove all VM attributes, after removing last one, sunstone immideatly replaces them by full VM template.

### Expected Behavior
Empty attributes list.

### Actual Behavior
A lot of attributes from VM template

## How to reproduce
Try to remove all VM attributes

**Comment by abelCoronado93** [comment]
Needs documentation about the behavior change in a OCA function
