### ISSUE TITLE
vCenter clean function (FS related)

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2016]
# Enhancement Request
## Description

Every time that opennebula register any vCenter template/vm it writes inside the conf file (vmx, vmtx...) some options that allow the driver to operate properly.

Will be nice to have a method for rollback this action. 

## Use case

You import a wild, opennebula generate inside the vmx a opennebula.vnc.port that allow us to give vnc service.

You clone the machine (with the conf) -> you should delete the opennebula.vnc option of this new machine if u want to import it again into one.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Also clean metadata when importing a VM to consider #1173
