### ISSUE TITLE
Incorrect group assignment for oneadmin on Debian 9

### ISSUE THREAD

**Issue by v-p-b** [OpenNebula/one#2040]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [x] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [x] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [x] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
I'm installing a KVM node + Frontend on Debian 9 (stretch) according to the official manuals:

https://docs.opennebula.org/5.4/deployment/node_installation/kvm_node_installation.html
https://docs.opennebula.org/5.4/deployment/opennebula_installation/frontend_installation.html

Creating domains fail with "Permission denied" errors (command line extracted from the `deploy` script): 

```
oneadmin@mynode:/var/log/one$ virsh --connect qemu:///system create /var/lib/one//datastores/0/6/deployment.0 

error: Failed to create domain from /var/lib/one//datastores/0/6/deployment.0
error: internal error: process exited while connecting to monitor: Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied
```
I tried several things to fix this, eventually putting the `oneadmin` user to the `libvirt-qemu` group solved the problem (the user is only in the `libvirt` group by default). 

### Expected Behavior

Permissions are correctly set during package installation, domains can be created with the `oneadmin` user.

### Actual Behavior

At least the oneadmin user misses some groups that prevents it from creating domains.

## How to reproduce

Follow the "Debian" steps of the official manual (see links above) and try to instantiate any VM template.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
I'm afraid I can't reproduce this on clean Debian 9.

If this is reproducible on your environment, please provide:
- initial system state
- precisely all the steps you are doing on command line
- `ls -la /dev/kvm`
- `grep oneadmin /etc/group`
- any custom changes in `/etc/libvirt/libvirtd.conf`, `/etc/libvirt/qemu.conf`
- version of packages: `libvirt-daemon` and `qemu-system-x86`
- anything interesting about the system (selinux, apparmor; any custom changes related to the groups, udev, configuration, etc.)

Ideally, have a clean operating system as a base.

Note: The system group `libvirt-qemu` is used as an identity of running QEMUs. With the OpenNebula installed, the libvirt/QEMU identity is reconfigured to the `oneadmin` (`/etc/libvirt/qemu.conf`). The `libvirt-qemu` group shouldn't be used for anything.
