### ISSUE TITLE
XML containing single quotes in any attribute may break DB related tools

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#2042]
# Bug Report
## Version of OpenNebula

- [X] Development build

## Component

- [X] Upgrades

## Description

For instance, vcenter premigrator for 5.4 breaks if a VM has a single quote in CONTEXT/PASSWORD

Things to check

  * fsck
  * premigrator

in general, look for @db.run commands

### Expected Behavior

This should be handled in 'naked' sequel calls, like @db.run, where the input string is not escaped

### Actual Behavior

Execution halts

## How to reproduce

CONTEXT/PASSWORD="TRY'THIS"

# Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jgarriuni** [comment]
We tried this with fsck and it works fine.
