### ISSUE TITLE
Onegate error when trying to poweroff a VM that is not part of a service.

### ISSUE THREAD

**Issue by jeovanevs** [OpenNebula/one#2047]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [X] 5.4.2
- [X] 5.4.3
- [X] 5.4.4
- [X] 5.4.5
- [X] 5.4.6
- [X] 5.4.7
- [X] 5.4.8
- [X] 5.4.9
- [X] 5.4.10
- [X] 5.4.11
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [X] Orchestration (OpenNebula Flow)
- [ ] Packages
- [X] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

 I can’t poweroff the VMs that are not part of a OneFlow service through onegate. 
### Expected Behavior
Poweroff without restriction as stated here:[ http://dev.opennebula.org/issues/4255]( http://dev.opennebula.org/issues/4255
)
### Actual Behavior
When I run the poweroff command from inside the VM that I want to turn off I get the error:
```
sudo onegate vm poweroff 57
ERROR:
Empty or invalid SERVICE_ID
```
## How to reproduce

Enable OneGate server.
Deploy a VM
Install Ruby
Try to poweroff the VM from inside using the OneGate command: onegate vm poweroff $VMID

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jeovanevs** [comment]
https://github.com/OpenNebula/one/blob/098ce33e79571646e60c1aca66a5de1bef2b32ea/src/onegate/onegate-server.rb#L158

It is comparing String with Integer, so it never pass over this condition. It cause errors when trying to poweroff the VM through onegate when the VM is not part of a service, as discussed on this thread: [https://forum.opennebula.org/t/onegate-client-not-working-as-advertised/1601/8](https://forum.opennebula.org/t/onegate-client-not-working-as-advertised/1601/8)

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

code: https://github.com/OpenNebula/one/pull/3399
docs: https://github.com/OpenNebula/docs/pull/642
