### ISSUE TITLE
Misleading error message when deleting a VM template with image

### ISSUE THREAD

**Issue by tomaxuser** [OpenNebula/one#2053]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

SunStone displays a misleading error message in the notification area when I try to delete a virtual machine template that has attached an image that I don't have right to delete.

### Expected Behavior

`[one.template.delete] Cannot delete image while deleting virtual machine template: 508` or something like that is displayed.

### Actual Behavior

`[one.template.delete] Cannot delete virtual machine template. Cannot delete image: 508` is displayed.

## How to reproduce

* use *User view*
* Create VM Template
* in Storage tab add an image that you can only Use but not Manage/Admin
* click on *Create*
* try to delete the template you've just created
* choose *Delete all images*
* observe an error message `[one.template.delete] Cannot delete virtual machine template. Cannot delete image: 508`
* observe successful deletion of the template and expected preservation of the image

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tomaxuser** [comment]
Hi, I'd like to ask if some progress is possible towards fixing this misleding bug. I still observe it using ONe 5.8.1.

To make it more clear, the Sunstone incorrectly claims the VM template cannot be deleted while in fact it has been deleted, albeit the recursive part of the deletion did not succeed.

**Comment by Yenya** [comment]
This is still present in 5.10.1 - the error message appears, saying "Cannot delete template", but the template gets removed as expected, and the image remains undeleted, also as expected. There is no point in displaying this error message.

**Comment by rsmontero** [comment]
Fixed for 6.0.0.3/6.0.3

**Comment by rsmontero** [comment]
commit: ff089908d18dfaa4dc0ad7e1208f02b733181a43
