### ISSUE TITLE
Ec2 Driver Instance tagging on creation

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2061]
# Enhancement Request
## Description

Opennebula only allows you to create ec2 instance tags after the creation of the instance.

Should be useful to have a mechanism to add instance tags on creation.

## Use case

You have organized your ec2 portal with policies to allow or not allow users to create instances.
You need to attach tags on instance creation if you want this behaviour to work. 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Public cloud integration has been deprecated in flavor of oneprovision, closing.
