### ISSUE TITLE
Sinatra doesn’t know this ditty after upgrade to 5.4.12

### ISSUE THREAD

**Issue by samuelbernardo** [OpenNebula/one#2069]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [x] 5.4.11
- [x] 5.4.12
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

After upgrading to opennebula 5.4.12 can't do login from the initial page. It shows the login page but after clicking login button it returns a page with the message "Sinatra doesn’t know this ditty"

The console logs collected in chromium Version 66.0.3359.139 (Developer Build) (64-bit) are:
```
opennebula.casa.local/:15 GET http://opennebula.casa.local:9869/dist/login.js 401 (Unauthorized)
opennebula.casa.local/:1 Refused to execute script from 'http://opennebula.casa.local:9869/dist/login.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
opennebula.casa.local/:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
```

### Expected Behavior

Appear dashboard page as usual after login.

### Actual Behavior

After clicking on login button it returns the following code:
```
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  body { text-align:center;font-family:helvetica,arial;font-size:22px;
    color:#888;margin:20px}
  #c {margin:0 auto;width:500px;text-align:left}
  </style>
</head>
<body>
  <h2>Sinatra doesn&rsquo;t know this ditty.</h2>
  <img src='http://opennebula.casa.local:9869/__sinatra__/404.png'>
  <div id="c">
    Try this:
    <pre>post &#x27;&#x2F;&#x27; do
  &quot;Hello World&quot;
end
</pre>
  </div>
</body>
</html>
```

## How to reproduce

Install opennebula in gentoo configured with profile default/linux/amd64/17.0 (stable) from the following ebuild from my personal overlay:
[opennebula-5.4.12.ebuild](https://github.com/samuelbernardo/ssnb-overlay/blob/master/app-emulation/opennebula/opennebula-5.4.12.ebuild)

Using sinatra current version dev-ruby/sinatra 1.4.8 and ruby 2.3.7.

The other dependencies came from gentoo portage and my overlay for some missing ruby gems.

Configured opennebula using KVM and remaining options with defaults.

After accessing the opennebula web interface it appears the login page. Then after clicking on login button it appears the sinatra error page.

The logs in sunstone.log are:
```
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET / HTTP/1.1" 200 - 0.0023
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET /css/login.css HTTP/1.1" 200 - 0.0010
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET /dist/login.js HTTP/1.1" 401 - 0.0011
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET /images/ajax-loader.gif HTTP/1.1" 200 - 0.0006
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET /images/panel.png HTTP/1.1" 200 - 0.0063
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET /images/login.png HTTP/1.1" 200 - 0.0041
Mon May 07 21:45:30 2018 [I]: 192.168.0.1 - - [07/May/2018:21:45:30 +0100] "GET /images/opennebula-5.0.png HTTP/1.1" 200 - 0.0036
```

The sched.log have some errors when it started up related to libcurl:
```
Mon May  7 18:27:28 2018 [Z0][SCHED][I]: XML-RPC client using 1073741824 bytes for response buffer.

Mon May  7 18:27:28 2018 [Z0][SCHED][E]: Cannot contact oned, will retry... Error: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to localhost port 2633: Connection refused
Mon May  7 18:27:30 2018 [Z0][SCHED][E]: Cannot contact oned, will retry... Error: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to localhost port 2633: Connection refused
Mon May  7 18:27:32 2018 [Z0][SCHED][E]: Cannot contact oned, will retry... Error: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to localhost port 2633: Connection refused
Mon May  7 18:27:34 2018 [Z0][SCHED][I]: oned successfully contacted.
Mon May  7 18:27:34 2018 [Z0][SCHED][I]: Configuring scheduler for Zone ID: 0
Mon May  7 18:27:34 2018 [Z0][SCHED][I]: Starting scheduler loop...
Mon May  7 18:27:34 2018 [Z0][SCHED][I]: Scheduler loop started.
```

The other log files have no errors.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by samuelbernardo** [comment]
This issue from sinatra could be related with reported error:

https://github.com/sinatra/sinatra/issues/876

**Comment by himbeere** [comment]
For the hotfix releases you need a few more steps to get them running.

```
 * Package 'app-emulation/opennebula-5.4.12' merged despite file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.
 * If you wish to use the sunstone server, please issue the command
 * npm install
 * bower install
 * grunt sass
 * grunt requirejs
 * as oneadmin user in /usr/lib/one/sunstone/public
 * 
 * also you need to issue this beforehand:
 * 
 * npm install -g bower
 * npm install -g grunt
 * npm install -g grunt-cli
 * as root
```

I guess this could be included in the ebuild as well but I'm to lazy. :-)

**Comment by samuelbernardo** [comment]
Hi himbeere
Thanks for your feedback.

I'll try that steps manually after install.

I just remove those steps because npm is a package manager that doesn't respect file collision. I'll search for a solution to install those necessary packages temporarily to create the minified files for the installation.

Anyway, I think the problem with sinatra could be another, since it fails immediately accessing existing scripts.

I'll leave here the feedback after doing those steps manually.

**Comment by samuelbernardo** [comment]
hi @himbeere 

Sorry for the delay in my answer.
As you mentioned, for this version it's necessary to compile nodejs files for sunstone. Since I wasn't compiling those, sunstone is missing files.

I created npm.eclass all dependency modules for npm using ebuilds. I'll need more time to finish the update because there are many dependencies to solve for the required modules.

In the end I'll use scons option to build directly all necessary files for sunstone without any user manual steps.
