### ISSUE TITLE
Give more info in sunstone when changing the password.

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#2078]
# Enhancement Request
## Description

Sunstone should alert that it's necessary to change the one_auth file when changing the password.

## Interface Changes
Add alert in sunstone.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
obsoleted by #4327
