### ISSUE TITLE
Support for veeam using vCenter annotations

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2079]
# Enhancement Request
## Description

Apparently veeam uses vCenter annotations to know which VMs to backup.

## Use case

Being able to mark VMs for veeam backup within OpenNebula.

## Interface Changes

Annotations section in the VM Template displayed in Sunstone

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by amenendezASAC** [comment]
Just a point, Veeam uses vCenter annotations to show info, like the job name, date, backup folder..., about the last backup done, not to know if the VMs need to backup.

**Comment by tinova** [comment]
addressed in #4662 3912
