### ISSUE TITLE
require: cannot load such file -- sinatra (LoadError)

### ISSUE THREAD

**Issue by aysabzevar** [OpenNebula/one#2105]
First I tried to install OpenNebula from source, then I changed my mind and tried to install from repository. Installation was successful and I tried to re-install on a fresh server.

I followed [this instruction](http://docs.opennebula.org/5.4/deployment/opennebula_installation/frontend_installation.html) to install OpenNebula on a fresh (network)installed CentOS 7.
Everything was just fine but, opennebula-econe, opennebula-flow, opennebula-gate.service and opennebula-sunstone didn't start successfully. 

> [root@OpenNebula ~]# systemctl status opennebula-sunstone
> ● opennebula-sunstone.service - OpenNebula Web UI Server
>    Loaded: loaded (/usr/lib/systemd/system/opennebula-sunstone.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sun 2018-05-20 15:23:10 +0430; 10s ago
>   Process: 3136 ExecStart=/usr/bin/ruby /usr/lib/one/sunstone/sunstone-server.rb (code=exited, status=1/FAILURE)
>   Process: 3134 ExecStartPre=/usr/sbin/logrotate -s /tmp/logrotate.state -f /etc/logrotate.d/opennebula (code=exited, status=0/SUCCESS)
>  Main PID: 3136 (code=exited, status=1/FAILURE)
> 
> May 20 15:23:10 OpenNebula systemd[1]: Starting OpenNebula Web UI Server...
> May 20 15:23:10 OpenNebula systemd[1]: Started OpenNebula Web UI Server.
> May 20 15:23:10 OpenNebula ruby[3136]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
> May 20 15:23:10 OpenNebula ruby[3136]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
> May 20 15:23:10 OpenNebula ruby[3136]: from /usr/lib/one/sunstone/sunstone-server.rb:86:in `<main>'
> May 20 15:23:10 OpenNebula systemd[1]: opennebula-sunstone.service: main process exited, code=exited, status=1/FAILURE
> May 20 15:23:10 OpenNebula systemd[1]: Unit opennebula-sunstone.service entered failed state.
> May 20 15:23:10 OpenNebula systemd[1]: opennebula-sunstone.service failed.

> [root@OpenNebula ~]# systemctl status opennebula-econe.service opennebula-flow.service opennebula-gate.service opennebula-novnc.service opennebula-scheduler.service 
> ● opennebula-econe.service - OpenNebula econe Server
>    Loaded: loaded (/usr/lib/systemd/system/opennebula-econe.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sun 2018-05-20 15:07:17 +0430; 16min ago
>   Process: 950 ExecStart=/usr/bin/ruby /usr/lib/one/ruby/cloud/econe/econe-server.rb (code=exited, status=1/FAILURE)
>  Main PID: 950 (code=exited, status=1/FAILURE)
> 
> May 20 15:07:16 OpenNebula systemd[1]: Started OpenNebula econe Server.
> May 20 15:07:16 OpenNebula systemd[1]: Starting OpenNebula econe Server...
> May 20 15:07:17 OpenNebula ruby[950]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
> May 20 15:07:17 OpenNebula ruby[950]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
> May 20 15:07:17 OpenNebula ruby[950]: from /usr/lib/one/ruby/cloud/econe/econe-server.rb:49:in `<main>'
> May 20 15:07:17 OpenNebula systemd[1]: opennebula-econe.service: main process exited, code=exited, status=1/FAILURE
> May 20 15:07:17 OpenNebula systemd[1]: Unit opennebula-econe.service entered failed state.
> May 20 15:07:17 OpenNebula systemd[1]: opennebula-econe.service failed.
> 
> ● opennebula-flow.service - OpenNebula Flow Service
>    Loaded: loaded (/usr/lib/systemd/system/opennebula-flow.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sun 2018-05-20 15:07:17 +0430; 16min ago
>   Process: 952 ExecStart=/usr/bin/ruby /usr/lib/one/oneflow/oneflow-server.rb (code=exited, status=1/FAILURE)
>  Main PID: 952 (code=exited, status=1/FAILURE)
> 
> May 20 15:07:16 OpenNebula systemd[1]: Started OpenNebula Flow Service.
> May 20 15:07:16 OpenNebula systemd[1]: Starting OpenNebula Flow Service...
> May 20 15:07:17 OpenNebula ruby[952]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
> May 20 15:07:17 OpenNebula ruby[952]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
> May 20 15:07:17 OpenNebula ruby[952]: from /usr/lib/one/oneflow/oneflow-server.rb:18:in `<main>'
> May 20 15:07:17 OpenNebula systemd[1]: opennebula-flow.service: main process exited, code=exited, status=1/FAILURE
> May 20 15:07:17 OpenNebula systemd[1]: Unit opennebula-flow.service entered failed state.
> May 20 15:07:17 OpenNebula systemd[1]: opennebula-flow.service failed.
> 
> ● opennebula-gate.service - OpenNebula Gate Service
>    Loaded: loaded (/usr/lib/systemd/system/opennebula-gate.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sun 2018-05-20 15:07:17 +0430; 16min ago
>   Process: 955 ExecStart=/usr/bin/ruby /usr/lib/one/onegate/onegate-server.rb (code=exited, status=1/FAILURE)
>  Main PID: 955 (code=exited, status=1/FAILURE)
> 
> May 20 15:07:16 OpenNebula systemd[1]: Started OpenNebula Gate Service.
> May 20 15:07:16 OpenNebula systemd[1]: Starting OpenNebula Gate Service...
> May 20 15:07:17 OpenNebula ruby[955]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
> May 20 15:07:17 OpenNebula ruby[955]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
> May 20 15:07:17 OpenNebula ruby[955]: from /usr/lib/one/onegate/onegate-server.rb:43:in `<main>'
> May 20 15:07:17 OpenNebula systemd[1]: opennebula-gate.service: main process exited, code=exited, status=1/FAILURE
> May 20 15:07:17 OpenNebula systemd[1]: Unit opennebula-gate.service entered failed state.
> May 20 15:07:17 OpenNebula systemd[1]: opennebula-gate.service failed.
> 
> ● opennebula-novnc.service - OpenNebula noVNC Server
>    Loaded: loaded (/usr/lib/systemd/system/opennebula-novnc.service; enabled; vendor preset: disabled)
>    Active: active (running) since Sun 2018-05-20 15:23:10 +0430; 55s ago
>   Process: 3126 ExecStart=/usr/bin/novnc-server start (code=exited, status=0/SUCCESS)
>  Main PID: 3130 (python2)
>    CGroup: /system.slice/opennebula-novnc.service
>            └─3130 python2 /usr/share/one/websockify/websocketproxy.py --target-config=/var/lib/one/sunstone_vnc_tokens 29876
> 
> May 20 15:23:09 OpenNebula systemd[1]: Starting OpenNebula noVNC Server...
> May 20 15:23:10 OpenNebula novnc-server[3126]: VNC proxy started
> May 20 15:23:10 OpenNebula systemd[1]: Started OpenNebula noVNC Server.
> 
> ● opennebula-scheduler.service - OpenNebula Cloud Scheduler Daemon
>    Loaded: loaded (/usr/lib/systemd/system/opennebula-scheduler.service; enabled; vendor preset: disabled)
>    Active: active (running) since Sun 2018-05-20 15:20:15 +0430; 3min 50s ago
>   Process: 2594 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=0/SUCCESS)
>  Main PID: 2611 (mm_sched)
>    CGroup: /system.slice/opennebula-scheduler.service
>            └─2611 /usr/bin/mm_sched
> 
> May 20 15:20:15 OpenNebula systemd[1]: Started OpenNebula Cloud Scheduler Daemon.
> May 20 15:20:15 OpenNebula systemd[1]: Starting OpenNebula Cloud Scheduler Daemon...

I remembered from the dirty install that I installed some package and gems so, I simply downloaded [release-5.4.12.tar.gz](https://github.com/OpenNebula/one/archive/release-5.4.12.tar.gz) , extracted it and ran `share/install_gems/install_gems`. It solved the problem and earlier mentioned services ran successfully. I didn't continue installation from source and deleted source package.

Something is missing from installing from repository on CentOS/RHEL 7.

**Comment by aysabzevar** [comment]
I found that installing required GEMs is mentioned here [here](http://docs.opennebula.org/5.4/deployment/sunstone_setup/sunstone.html#requirements) ,but the question is that isn't it better that `/usr/share/one/install_gems sunstone` runs by scriplet after installing `opennebula-sunstone` rpm package?

**Comment by tinova** [comment]
install_gems needs to be executed manually
