### ISSUE TITLE
Reduce number of history requests to database.

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2111]
# Enhancement Request
## Description

Hi I just found that i have a lot requests to my database like:
```sql
SELECT body FROM history WHERE vid = 1234 AND seq = 200;
SELECT body FROM history WHERE vid = 1234 AND seq = 199;
SELECT body FROM history WHERE vid = 1234 AND seq = 198;
SELECT body FROM history WHERE vid = 1234 AND seq = 197;
SELECT body FROM history WHERE vid = 1234 AND seq = 196;
...
```
I not understand why just not use:
```sql
SELECT body FROM history WHERE vid = 1234 AND seq <= 200;
```

## Use case
Only one request instead of many will greatly increase the productivity of operations.
It should bring more performance for db connection with less load.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
up

**Comment by paczerny** [comment]
Not only that we use slow method to read the history, but we read it very often. E.g. for `onevm undeploy` we read all history records 9 times :-(

Possible improvements:
* use `SELECT body FROM history WHERE vid = 1234 AND seq <= 200;` to read history [here](https://github.com/OpenNebula/one/blob/master/src/vm/VirtualMachine.cc#L689)
* Do some kind of lazy loading of history records, we usually don't need them, load just last 2 records. Use explicit call to load all records when needed
* Review code for subsequent calls of `vm_pool->get` or `vm_pool->get_ro`. `basic_authorization` method is a good candidate by replacing the first parameter `id` by pointer to object.
