### ISSUE TITLE
onezone show command should warn about inconsistent status of HA in a Zone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2113]
# Enhancement Request
## Description

If a member of the HA is lagging behind, oneshow show should mark it in red, and add a warning message at the end

## Use case

OpenNebula admin that wants to do a health check

## Interface Changes

onezone show command

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Duplicate of #2143
