### ISSUE TITLE
Limit the Sunstone notification box content size

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2126]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
In case of some terrible error, the Sunstone notification box can get a server stack trace to show. Such large output doesn't have any sense for the user and even can't be confirmed / closed. There should be some limit to show just first X lines.

![image](https://user-images.githubusercontent.com/414850/40611768-f4b4b8b6-6277-11e8-9e76-ca7980aba276.png)

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova  PR to approve:
- ONE: https://github.com/OpenNebula/one/pull/4683
- Docs: https://github.com/OpenNebula/docs/pull/1113/files
