### ISSUE TITLE
OpenNebula Federation not working with sqlite

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#2144]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ x ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ x ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
OpenNebula's federation not working when using SQLite as DB backend.

### Expected Behavior
When adding a new user in one endpoint, it should automatically replicate it to the other endpoints.

### Actual Behavior
New users can only be seen and interacted inside the endpoint where they were created.

## How to reproduce

Install 2 basic OpenNebula's frontends using SQLite as DB backend. Add one frontend as federation master and the other one as slave. Create a new user on the master's endpoint and it should be replicated to the other endpoint, but it doesn't.

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
This problem can be caused by a problem when OpenNebula attempts to capture the number of affected rows of the last query and that query is SELECT.

The function that is causing this problem is: sqlite3_changes ()
