### ISSUE TITLE
Option to append IP from caller in logs

### ISSUE THREAD

**Issue by juanmont** [OpenNebula/one#2150]
# Enhancement Request
## Description
Add the possibility to show the Client IP when a client does a new request to the server.
The method to capture IP information can be: [callinfo](http://xmlrpc-c.sourceforge.net/doc/libxmlrpc_server++.html#callinfo)

## Interface Changes
Add new parameter in oned.conf to capture IP.

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by pfak** [comment]
Hello,

Can you please provide support for X-Forwarded-For as part of this feature request? Running the XMLRPC behind a reverse proxy is a very common use case.

Thank you.
