### ISSUE TITLE
Do `onehost flush` command more configurable

### ISSUE THREAD

**Issue by juanmont** [OpenNebula/one#2153]
# Enhancement Request
## Description

Add the ability to specify which action you want OpenNebula to run when you run the command `onehost flush`, now OpenNebula executes the action` resched`.

## Use case

If you want OpenNebula to execute the Delete-recreate action instead of Resched, you can not do it.

## Interface Changes
Changes over OpenNebula configuration files.

# Progress Status
- [ ] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
commit 070b7a98f44fdba4dc4780f5bff397d2ef8431c3
Author: Christian González <cgonzalez@opennebula.systems>
Date:   Wed Jun 6 15:58:54 2018 +0200
