### ISSUE TITLE
IPv6 support (AAAA label) for marketplace.opennebula.systems

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#2158]
# Enhancement Request
## Description
IPv6 support (AAAA label) for marketplace.opennebula.systems

## Use case
For IPv6 only environments (yes, they exist) it's not possible to use the public marketplace. Every monitoring cycle the following will be logged by oned:

Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to marketplace.opennebula.systems:80 (Network is unreachable - connect(2) for "marketplace.opennebula.systems" port 80) (Errno::ENETUNREACH)
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /var/lib/one/remotes/market/one/monitor:54:in `get'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /var/lib/one/remotes/market/one/monitor:66:in `get_appliances'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: from /var/lib/one/remotes/market/one/monitor:173:in `<main>'
Thu Jun  7 10:15:49 2018 [Z0][MKP][I]: ExitCode: 1
Thu Jun  7 10:15:49 2018 [Z0][MKP][E]: Error monitoring marketplace 0: -

#ipv6allthethings!

**Comment by vholer** [comment]
Marketplace now works over IPv6.
