### ISSUE TITLE
Consistent state naming for VMs

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2160]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [X] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

All the interfaces should comply with the same state semantics as the OpenNebula core:

  TOTAL -- total number of VMs that NOT in the DONE state
  ACTIVE -- VMs that are NOT in a final state (s, if left alone, will revert to RUNNING if there are not changes)
  RUNNING -- VMs that are in RUNNING state

### Expected Behavior

Interfaces to be consistent with this

### Actual Behavior

- There is no TOTAL in Dashboard
- Host template has RUNNING_VMS which should be TOTAL_VMS
- onehost list outputs RVM and should output TVM (Total VMs) (or just, VM)

## How to reproduce

Have a VM pool with mixed VM states and look at the above issues

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
Also, RUNNING VM quotas should be TOTAL VM quotas

**Comment by rsmontero** [comment]
Juan: onehost list outputs RVM and should output TVM (Total VMs) (or just, VM)
