### ISSUE TITLE
Support Azure Germany

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2184]
# Enhancement Request
## Description

Azure Germany uses different endpoints for all resources

## Use case

Be able to use resources from Azure Germany

## Interface Changes

Expected changes only in configuration files

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by smangelkramer** [comment]
Hi, are there any updates on this topic? Best Sebastian

**Comment by xorel** [comment]
In OpenNebula 5.12 new Azure driver chooses the endpoint automatically, for Germany region use:
`AZ_REGION="germanywestcentral"`

Details about the revamped Azure driver: 
http://docs.opennebula.io/5.12/advanced_components/cloud_bursting/azg.html
