### ISSUE TITLE
IPv6 Address Range (no-SLAAC) should not ask for SIZE

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#2187]
# Enhancement Request
## Description
For IPv6 Ranges (no-SLAAC) where a prefix is given, i.e. /64 it does not make sense to ask for "SIZE" (should not be mandatory).

## Use case

Be able to use a /64 instead of a subset of the "18,446,744,073,709,551,616" IPv6 addresses that are available in a /64.

**Comment by rsmontero** [comment]
Also SIZE is limited to /32

**Comment by kepi** [comment]
This should be priority as not only it is currently impossible to use full IPv6 ranges, because they are too large (SIZE limit) but administrator shouldn't need to count number of IPs in IPv6 range, its quite a challenge (not enough fingers :D ). Thanks for considering.

**Comment by tinova** [comment]
moving (tentatively) to 5.12

**Comment by lgrawet** [comment]
We also really need this enhancement. Too sad to see it being pushed back again and again.
Let's hope 5.12.3 will be the good one

Many thanks OpenNebula team :-)

**Comment by kvaps** [comment]
Also related issue https://github.com/OpenNebula/one/issues/5032

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1338)
- [Docs](https://github.com/OpenNebula/docs/pull/1908)
