### ISSUE TITLE
Current snapshot is backing itself (backing store is self-referential)

### ISSUE THREAD

**Issue by Madko** [OpenNebula/one#2189]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [x] 5.4.13
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [x] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
When using disk snapshots on qcow2 files, it's quiet easy to end up with an unbootable VM because it's current disk has a backing file pointing to the same file.

### Expected Behavior
snapshots should work as expected.

### Actual Behavior
We have at least 2 situations:
1) with missing disk.# on the datastore. I don't know yet how to reproduction. In sunstone this snapshots can't be deleted and has a missing file size
2) VM can't boot, backing file is self-referential

## How to reproduce

I will open a new issue for situation 1 with missing snapshot on datastore, as soon as I understand how to reproduice.

Here is for situration 2 with backing file that is self-referential:
- Create a VM on a QCOW2 datastore
- Stop the VM
- In the storage tab, do 1 snapshot (let's call it origin)
- Run the VM, do some stuff
- Stop the VM
- In the storage tab, do 1 new snapshot (let's call it snap2)
- Run the VM, do some stuff
- Stop the VM
- In the storage tab, do 1 new snapshot (let's call it snap3)
- Stop the VM
- in the storage tab, revert to first snapshot (origin)
- Run the VM, do some stuff
- Stop the VM
- in the storage tab, delete snap3
- Run the VM, do some stuff
- Stop the VM
- in the storage tab, create a new snapshot (snap4)
- Current disk.0.snap is self referential, VM can't boot.

```
juin 15 15:17:53 h003 libvirtd[2231]: 2018-06-15 13:17:53.922+0000: 2248: error : virStorageFileGetMetadataRecurse:3269 : internal error: backing store for /var/lib/one//datastores/104/5802/disk.0.snap/3 (/var/lib/one/datastores/104/5802/disk.0.snap/3) is self-referential
-(ven. juin 15 15:16:50)--(h003:/var/lib/one/datastores/104/5802/disk.0.snap)-
[root] # ll ..
total 392K
-rw-rw-r-- 1 oneadmin oneadmin 1,1K 14 juin  14:17 deployment.0
-rw-rw-r-- 1 oneadmin oneadmin 1,1K 15 juin  14:56 deployment.1
-rw-rw-r-- 1 oneadmin oneadmin 1,1K 15 juin  15:00 deployment.2
-rw-rw-r-- 1 oneadmin oneadmin 1,1K 15 juin  15:02 deployment.3
-rw-rw-r-- 1 oneadmin oneadmin 1,1K 15 juin  15:04 deployment.4
lrwxrwxrwx 1 oneadmin oneadmin   13 15 juin  15:07 disk.0 -> disk.0.snap/3
drwxrwxr-x 2 oneadmin oneadmin 4,0K 15 juin  15:05 disk.0.snap
-rw-r--r-- 1 oneadmin oneadmin 364K 15 juin  15:04 disk.1
-(ven. juin 15 15:17:30)--(h003:/var/lib/one/datastores/104/5802/disk.0.snap)-
[root] # qemu-img info 3
image: 3
file format: qcow2
virtual size: 8.0G (8589934592 bytes)
disk size: 200K
cluster_size: 65536
backing file: disk.0.snap/3
backing file format: qcow2
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```
It seems that snapshots management goes south as soon as we delete one of them. File numbers on datastore seem to not match the ID in sunstone. Not sure it's relevant with the problem.

Best regards
Edouard

**Comment by rsmontero** [comment]
After an upgrade VM metadata is updated but any previous VM presenting this issue will have a NEXT_SNAPSHOT that will overwrite an existing one:

1. Safety check in drivers to not overwrite in this situation
2. Add a manual upgrade procedure for this VMs.

**Comment by rsmontero** [comment]
As a reference existing VMs can be recovered by updating the metadata with onedb update-body and increasing the NEXT_SNAPSHOT value.
