### ISSUE TITLE
Federation: VNC should be enable to zone VMs if accessing zone Sunstone

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#2191]
# Enhancement Request
## Description

Be able to access VM VNC when using the zone Sunstone service. Current check only enable VNC buttons when using the MASTER zone.

## Use case
NaN

## Interface Changes
NaN

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Duplicated by #738
