### ISSUE TITLE
Live Migration --enforce default in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2202]
# Enhancement Request
## Description

Currently the default behaviour for live migrate in Sunstone is to *not* use enforce, which causes that the target host capacity is not checked.

## Use case

Live migrations not to cause unintended overcommitment.

## Interface Changes

sunstone views yaml option to change the default behaviour

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Note: I find confusing using just "Enforce" title, it could be understood as to enforce the migration no matter what problems with capacity may occur. It might be better to use longer and explanatory "Enforce capacity checks" (or something like that).

![image](https://user-images.githubusercontent.com/414850/41610178-cf01b1a6-73ec-11e8-9e80-a8d50f30cc70.png)

**Comment by tinova** [comment]
totally agree with @vholer here, please @abelCoronado93 do the needful
