### ISSUE TITLE
Extend KVM XML domain metadata

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2205]
# Enhancement Request
## Description

Right now, the custom domain metadata contains just:

```
<metadata>
    <system_datastore>...</system_datastore>
</metadata>
```

It might be helpful to add some more (list is expected to grow):

* date/time domain XML was generated (epoch?)
* owner / group
* VM creation date/time (epoch?)
* VM title
* OpenNebula version

Names are just suggestions, may change.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
I suggest to add the following information to the metadata field:

`<metadata>
    <one:vm xmlns:one=\"http://opennebula.org/xmlns/libvirt/1.0\">
        <one:system_datastore>path</one:system_datastore>
        <one:name>vm name</one:name>
        <one:owner>user</one:owner>
        <one:group>group</one:group>
        <one:version>5.8</one:version>
        <one:vmtime>vm_creation_time</one:vmtime>
        <one:xmltime>xml_creation_time</one:xmltime>
    </one:vm>
<metadata>`

And the "title" field with the VM name.
