### ISSUE TITLE
Imposible to update user group settings

### ISSUE THREAD

**Issue by BcTpe4HbIu** [OpenNebula/one#2225]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [X] 5.4.12
- [X] 5.4.13
- [ ] 5.4.14
- [ ] 5.4.15
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [X] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Imposible to update user group settings.

### Expected Behavior
Group should be updated with new settings.

### Actual Behavior
Error reported:
```
[one.group.update] Cannot update template. Parse error: syntax error, unexpected CBRACKET, expecting VARIABLE at line 7, columns 161:163
```
Payload for that request:
```
{"action":{"perform":"update","params":{"template_raw":"SUNSTONE = [\n  VIEWS = \"cloud\",\n  DEFAULT_VIEW = \"cloud\",\n  GROUP_ADMIN_VIEWS = \"cloud,groupadmin\",\n  GROUP_ADMIN_DEFAULT_VIEW = \"groupadmin\" ]\nOPENNEBULA = [\n ]\n"}},"csrftoken":"37e65c61a923ba5a3bb3bb34397ce200"}
```
HAR: [group_update.zip](https://github.com/OpenNebula/one/files/2138012/group_update.zip)

## How to reproduce

1. Create user group
1. Open group settings
1. Press "Update"
1. Don't change anything and press "Update"

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment]
This bug is already solved for 5.6 release. 

Thanks for your feedback.

**Comment by smangelkramer** [comment]
@abelCoronado93 will this be fixed in 5.4.x too? Currently we`re running 5.4.15 and discovered this bug too ;-) best, sebastian.

**Comment by abelCoronado93** [comment]
@smangelkramer the bug disappears in 5.6.x

**Comment by smangelkramer** [comment]
@abelCoronado93 right, but currently no upgrade from 5.4.15 is planned - thats why i`m asking. but we can wait for our upgrade. best sebastian

**Comment by abelCoronado93** [comment]
@smangelkramer for 5.4.x the fix isn't going to be applied, the best solution is to update
