### ISSUE TITLE
Name instead of id in vnet leases datatable

### ISSUE THREAD

**Issue by abelCoronado93** [OpenNebula/one#2236]
# Enhancement Request
## Description
In lease datatable show the name of VM instead of ID.

## Use case
It would be easier to redeploy all the virtual machines in a specific VLAN if you know the names instead of having to search the virtual machines for their ID.

## Interface Changes
Name instead of ID.

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Closing as this implies a severe performance hit. Please reopen with a valid use case.
