### ISSUE TITLE
Add support to vCenter 6.7

### ISSUE THREAD

**Issue by ccesario** [OpenNebula/one#2242]
# Enhancement Request
## Description
Add support to vCenter 6.7, according the documentation the most recent vCenter supported version is 6.5

## Use case

Support the most recent vCenter stable version

## Interface Changes

 
API

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
5.8 will feature have 6.7 support

**Comment by Scanz-beep** [comment]
And now need 7.0

**Comment by tinova** [comment]
Keep track with #4933
