### ISSUE TITLE
VMs created from images inside a Ceph datastore with EC_POOL_NAME are not created in that EC pool

### ISSUE THREAD

**Issue by vitalif** [OpenNebula/one#2246]
# Bug Report
## Version of OpenNebula
- [X] Development build

## Component
- [x] Storage & Images

## Description
When you have an image in a Ceph datastore which has EC_POOL_NAME set and do not specify "Deploy VM in a specific datastore", the image is not necessarily created inside the correct pool.

In my case, I have the following datastores:
- ID 102 ceph_data (data) and ID 103 ceph_system (system) with a single "cache tiered pool" `tierpool`
- ID 104 ceph_ssd (system) and ID 105 ceph_ssd_data (data) with EC/replicated pool pair: `rpool_ssd`/`ecpool_ssd`
- ID 107 ceph_hdd_data (data) and ID 108 ceph_hdd (system) with EC/replicated pool pair: `rpool_hdd`/`ecpool_hdd`

I have an image in ID 107. When I create a VM from it without specifying datastore, OpenNebula tries to create a COW-clone from it in datastore ID 103. It does not have "EC_POOL_NAME" option, so `/var/lib/one/remotes/tm/ceph/clone` does not pass it to `rbd clone`. But since it's a COW-child, it does not use ID 103's pool either and it ends up being created in the same pool as the original image (rpool_hdd), but without the EC pool.

### Expected Behavior
VM disks created from images should reside on the same Ceph pools by default. In particular, if the original RBD image has --data-pool option, its children should also have the same --data-pool option.

I think `/var/lib/one/remotes/tm/ceph/clone` could take --data-pool not only from OpenNebula datastore information, but also from `rbd` metadata of the parent image - that would fix this issue.

### Actual Behavior
VM disk RBD images are created without --data-pool option so they end up being replicated instead of erasure-coded.

## How to reproduce
- Create two "system" Ceph datastores: the first one (one with lesser ID) without EC_POOL_NAME and the second one with it
- Create one "data" Ceph datastore with EC_POOL_NAME
- Put some image inside it, create a VM template
- Instantiate the template without selecting "deploy VM in a specific datastore"
- Run `rbd ls -p your_replicated_pool`
- Run `rbd info your_replicated_pool/your_image` and check that it has "data_pool" option
- Run `rbd info your_replicated_pool/your_image-24-0` and check that it doesn't have the same option

**Comment by rsmontero** [comment]
Thanks for the feedback @vitalif. We are thinking to address this as follows:

1. Add a new Datatastore attribute for (image datastores): `COMPATIBLE_SYSTEM_DS`. With this attribute you can list which system datastores can be used in combination with this image datastore.
2. The list of requirements will include the `CLUSTER` constraints the list of `COMPATIBLE_SYSTEM_DS`
3. The scheduler will pick a system DS in this list.

If the  correct combination is used, also the correct image parameters should be used. And this is enforced by the scheduler and the ACL systems.

What do you think? Would this solve your issue?

**Comment by vitalif** [comment]
Yes, that's a nice solution, thanks :)

**Comment by rsmontero** [comment]
This is now ready for 5.6.2

**Comment by vitalif** [comment]
In fact there's a similar issue with the snapshot script: it forgets abour the EC pool when creating a layer from old snapshot
