### ISSUE TITLE
sunstone logs unauthorized login attempt if backend is down.

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2249]
# Bug Report
## Version of OpenNebula

I assume all, but do not know.
- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [ ] 5.4.12
- [ ] 5.4.13
- [ ] 5.4.14
- [ ] 5.4.15
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

if there's a backend issue, sunstone will log about that issue, but then ignore that there was an opennebula issue and instead will log an additional message saying there was an unauthorized login attempt. it was a failure to authorize. this (for people who actually protect their systems) would then lead to locking legitimate users because the backend is down.

### Expected Behavior

A log entry is written to the sunstone error log
The log entry indicates a timeout

### Actual Behavior

no entry is written to error log
log entry for an unauthorized attempt is written to main log file

```
==> log/sunstone.log <==
Tue Jul 03 13:12:28 2018 [E]: User admin could not be authenticated
Tue Jul 03 13:12:28 2018 [E]: Net::ReadTimeout
Tue Jul 03 13:12:28 2018 [I]: Unauthorized login attempt
Tue Jul 03 13:12:28 2018 [I]: 192.168.zzzzz - - [03/Jul/2018:13:12:28 +0200] "POST /login HTTP/1.0" 401 - 60.0598
```

## How to reproduce

try to login when oned doesn't respond to requests

**Comment by FrederickBor** [comment]
Hi @FlorianHeigl 

On the latest version of OpenNebula 5.10.5 when you try to log in this message of "" is not anymore at the log file. I just tried and this was the result:

<pre>Mon May 11 12:23:52 2020 [E]: User oneadmin could not be authenticated
Mon May 11 12:23:52 2020 [E]: Failed to open TCP connection to localhost:2633 (Connection refused - connect(2) for &quot;localhost&quot; port 2633)
Mon May 11 12:23:52 2020 [E]: Failed to open TCP connection to localhost:2633 (Connection refused - connect(2) for &quot;localhost&quot; port 2633)
Mon May 11 12:23:52 2020 [I]: 127.0.0.1 - - [11/May/2020:12:23:52 +0200] &quot;POST /login HTTP/1.1&quot; 500 - 0.0070
</pre>

We will close this issue until we receive further information.
