### ISSUE TITLE
Support image import from storage backend

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2251]
# Enhancement Request
## Description

In certain storage backends, like Ceph, it is interesting to import images existing already in the backend. 

## Use case

This is useful for instance for backup restore

## Interface Changes

A new datastore operation in the XMLRPC interface, exposed through Sunstone and the CLI

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
It is already supported for:

http://*|https://* Image from http server                                     
ssh://* Image from ssh host                                                 
s3://* Image from S3
rbd:// Image from Ceph pool
vcenter:// Image in vCenter
lxd:// Image from linux cotainers
docker:// Image from docker hub
