### ISSUE TITLE
Add PyONE to upstream OpenNebula

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#2258]
# Enhancement Request
## Description
Use PyONE as a way to interact with XML-RPC using Python, with a stock OpenNebula

## Use case
More languages API clients for OpenNebula

## Interface Changes
New API Client

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Following pull. req. are ready:
https://github.com/OpenNebula/one/pull/2706
https://github.com/OpenNebula/infra/pull/154
https://github.com/OpenNebula/packages/pull/45/
https://github.com/OpenNebula/development/pull/443
https://github.com/OpenNebula/docs/pull/446

What remains is to upload the package to the pip during the release.
