### ISSUE TITLE
Cannot get log details for slave zone in Federation

### ISSUE THREAD

**Issue by nos1kg7at** [OpenNebula/one#2268]
**Description**
When I’m in a slave zone I cannot get Log details for particular VM.
It shows “Log for VM YOUR_ID_HERE not available”
But if ID is the same like in master zone, then I can see log for VM from master zone.
Seems due to logs are stored locally on leader

**Use case**
Should we share the logs’ storage across all zone DB servers?

**Interface Changes**
This will be a Sunstone only feature, so login page in Sunstone to be changed  

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
The vm_pool table is local for each zone into the federation. The Federation tables are:
- group_pool
- user_pool
- acl
- zone_pool
- vdc_pool
- marketplace_pool
- marketplaceapp_pool
