### ISSUE TITLE
When an image is cloned from a Ceph datastore its size is not register well.

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2269]
**Description**
When an image is cloned from a Ceph datastore to another Ceph datastore, its size is not register well.

**Expected behavior**
The size of the image should be correct in the destiny datastore.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
We have been doing some tests, and it's working correctly.

The monitoring data is get using `ceph df --format xml`, the important parameters are: **bytes_used** and **max_avail**.
