### ISSUE TITLE
Remove disk not affected by snap on vCenter

### ISSUE THREAD

**Issue by amenendezASAC** [OpenNebula/one#2275]
**Description**
vCener allows to remove disks from a VM if it has been attached after a snapshot creation, OpenNebula instead, doesn't allow it. ONE shows the message 

> vCenter doesn't allow to remove a virtual disk if it's part of a snapshot of the virtual machine.

on oned.log file, even if the diskis not part of the snapshot.

vCenter doesn't allow to remove a virtual disk if it's part of a snapshot of the virtual machine.

on oned.log file, even if the volume is not part of the snapshot.

**To Reproduce**
Create a snap on a VM.
Attach disk.
Detach disk.

**Expected behavior**
ONE should allow disk detaching if disk is not part of the snap.

**Details**
 - Hypervisor: vCenter
 - Version: 5.4.15

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
https://github.com/OpenNebula/one/pull/3187 --> master

**Comment by tinova** [comment]
#3187 --> commited to master and one-5.8
OpenNebula/development#582 --> commited to master and one-5.8
5d74cc0 --> one-5.8-maintenance
