### ISSUE TITLE
Add meaningful log when host fencing isn't configured yet

### ISSUE THREAD

**Issue by jsfrerot** [OpenNebula/one#2282]
**Description**
Add meaningful log when host fencing isn't configured.

**Use case**
When using host fencing for the first time, it is very easy to forget to configure it. When not configured, the current logging doesn't indicate the fencing is not configured and can lead to waste of time for the user.

**Interface Changes**
Simply add the following line in ft/fence_host.sh before the "exit 1" line at the beginning of the file:
"Fence host not configured, please edit ft/fence_host.sh"

**Additional Context**
Reference: https://forum.opennebula.org/t/host-error-hook-not-working-5-4-13/6147

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
took a while but...added for next release
