### ISSUE TITLE
Use "%i" in custom attributes

### ISSUE THREAD

**Issue by iandk** [OpenNebula/one#2287]
**Description**
When deploying multiple VMs and using a custom attribute for e.g. the hostname, it would be useful if we could also use the "%i" counter in the custom attributes section.

**Use case**
Deploying multiple VMs where the number is used.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Implement also #2377.

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2052)
- [docs](https://github.com/OpenNebula/docs/pull/2275)
