### ISSUE TITLE
Allow altering Image Template metadata from the datastore driver during/after import

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2292]
**Description**
It is not exactly a new feature because altering image's template was working on 5.4.x but it is blocked in 5.6.x because the image is 'locked'.

**Use case**
When there is a data conversion during import and the Image Template should be updated to match the true image format.

**Interface Changes**
Add a permission to allow altering the image template while the IMAGE is locked while importing for oneadmin user/group.

**Additional Context**
For example, the Marketplace image has `FORMAT=qcow2` but it is stored as `raw` on the storage. Currently the Image Template continue to have `FORMAT=qcow2` and any altering during import is blocked because the image is 'locked'.

opennebula-5.4:

> Tue Jul 17 15:30:46 2018 [Z0][ReM][D]: Req:9008 UID:0 one.image.update invoked , 160, "FORMAT=raw", 1
> Tue Jul 17 15:30:46 2018 [Z0][ReM][D]: Req:9008 UID:0 one.image.update result SUCCESS, 160
> Tue Jul 17 15:30:46 2018 [Z0][ImM][I]: Image (160) copied and ready to use.

opennebula-5.6:

> Tue Jul 17 10:19:30 2018 [Z0][ReM][D]: Req:8752 UID:0 one.image.update invoked , 0, "FORMAT=raw", 1
> Tue Jul 17 10:19:30 2018 [Z0][ReM][E]: Req:8752 UID:0 one.image.update result FAILURE [one.image.update] User [0] : IMAGE is locked. [0].
> Tue Jul 17 10:19:30 2018 [Z0][ImM][I]: Image (0) copied and ready to use.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
We would like to know, why do you use the FORMAT attribute of the image?

This attribute is only an informative attribute, now OpenNebula changes the attributes DRIVER and FS_TYPE according to the datastore destination.

**Comment by atodorov-storpool** [comment]
Hi @juanmount,

FORMAT is indeed just informative, but could mislead because actually the image was converted to raw during the import. So it is not qcow2 anymore.

Could you elaborate a bit or point me where to see how DRIVER and FS_TYPE were changed? Do you mean the DRIVER attribute form TM_MAD_CONF of the destination datastore? Also, I couldn't find more references to FS_TYPE than https://github.com/OpenNebula/one/blob/master/src/sunstone/public/app/tabs/images-tab/panels/info-common.js#L64 isn't it obsolete?

**Comment by atodorov-storpool** [comment]
Following #2626 [comment](https://github.com/OpenNebula/one/issues/2626#issuecomment-443167213) a workaround with unlock/lock was implemented.

Closing the issue.
