### ISSUE TITLE
NIC Model is ignored on VM vCenter Template

### ISSUE THREAD

**Issue by ccesario** [OpenNebula/one#2293]
**Description**
In VM Template even forcing usage the **e1000** network driver in field **Default hardware model to emulate for all NICs**  in Sunstone GUI, the VM is created with **vmxnet3**.

**To Reproduce**
1 - Using Sunstone, create a VM Template
2 - In Network option, put in field **Default hardware model to emulate for all NICs** the e1000 value
3 - Instantiate the VM using this template

**Expected behavior**
The VM instantiated should usage the e1000 network driver

**Details**
 - Affected Component: [One]
 - Hypervisor: [vCenter - vMware]
 - Version: [5.6]

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by ccesario** [comment]
Only to update it.
Even when I try attach the NIC to a Running VM and choosing "Hardware model to emulate" to e1000 (In advanced screen) the NIC it is atached to the VM as VMXNET3

**Comment by fm4991** [comment]
First i thougt thats the issue we got... but reading it the second time i saw that we have the problem in the other direction we want vmxnet3 nics but we always get e1000 no matter what we do. We tried to set the default nic in the vmware driver, in the one vm template and in the vmware vm template. But nothing helped for us, we always get an e1000.

**Comment by Semedi** [comment]
Hi!

I think the issue is solved in the next commit 3c8de8a6f257e2571cccc73f145df6554cb1aacb .

It will be available in the next OpenNebula release.

**Comment by Semedi** [comment]
The issue is going to be closed. However there is a small issue related to this, you can follow it here:
https://github.com/OpenNebula/one/issues/2827
