### ISSUE TITLE
Newly set VNET attributes don't get applied in VM VNET

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#2294]
**Description**
If a new Attribute gets added (MTU in our case) to the VNET, and / or to the "AR" belonging to it, this attribute gets not applied to the VM when it undergoes the state change "RUNNING -> POWEROFF (new deployment file) -> RUNNING

**To Reproduce**
Create a VNET, an AR in it and deploy a VM using this VNET. Add a new VNET attribute, i.e. MTU. Poweroff the VM, and resume it again. Observe that MTU attribute is not set.

**Expected behavior**
New attributes get applied when VM undergoes the state change "RUNNING -> POWEROFF (new deployment file) -> RUNNING

**Details**
 - tested with sunstone (but should not matter)
- tested on KVM
 - Version: 5.6.0

**Additional context**
Editing the "MTU" section of the VM directly (conf update) is (also) ignored. This might be related to #2293. In fact, they might all be the same issue.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
To do these changes over NIC section in the Virtual Machine, from now, you have to do an updateconf.

If you have another problem with this new change, you can reopen the bug.

**Comment by hydro-b** [comment]
@juanmont Please reopen: updateconf > Context > Custom vars > Change ETH0_MTU to 1250
click "update". Setting is discarded, ETH0_MTU is still empty.

Removing an attibute (cross sign on the right of attribute) and clicking "update" will just ignore action as well. Attribute is still there when viewing VM template afterwards.

Add Network contextualization checkbox is present (CONTEXT active).
