### ISSUE TITLE
Error executing image transfer script after stopping VM

### ISSUE THREAD

**Issue by iandk** [OpenNebula/one#2303]
**Description**
Stopping a VM results in the error "Error executing image transfer script: Error copying disk directory to target host".
`Command execution failed (exit code: 2): /var/lib/one/remotes/tm/ssh/mv localhost:/var/lib/one//datastores/0/51 virt.xxxx.de:/var/lib/one//datastores/0/51 51 0`

**To Reproduce**
Create VM and stop it afterwards. 

**Expected behavior**
The VM is stopped and can then be restarted normally.

**Details**
OpenNebula Version: OpenNebula 5.6.0
OS: Debian 9

**Additional context**

VM Log: https://pastebin.com/jzjGU1JS
Output after running the failing command: https://pastebin.com/x8WatHkN

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by iandk** [comment]
Changing the datastore to shared seems to fix the issue, but unfortunately OpenNebula isn't able to to figure out himself  that it's the same host.
Seems to be a bug.

**Comment by iandk** [comment]
Ahy feedback on this?

**Comment by juanmont** [comment]
This bug, we think that is not a OpenNebula bug. We think that can be a problem with your Datastore configuration.

**Comment by nakogleba** [comment]
Hello.
I have the same problem. And I don't know how to fix it.
Are there some one to help me?
Thanks
