### ISSUE TITLE
vCenter - Add support to HTML5 Console 

### ISSUE THREAD

**Issue by ccesario** [OpenNebula/one#2312]
**Description**
As new vCenter versions already support HTML5 console, it would interesting support it instead VNC.

**Use case**
This will usage less config, no need config injection in VM config file, better security once a VNC weill not enabled, the VM deployment will be more fast and other advantages.

**Interface Changes**
I think that will need changes on Sunstone and API  

**Additional Context**
Perl example code https://github.com/lamw/vghetto-scripts/blob/master/perl/generateHTML5VMConsole.pl
Ruby example code https://gist.github.com/bthornto/bfce98039e845fa44e9b

https://www.vmware.com/support/developer/html-console/
ManageIQ Code - https://github.com/ManageIQ/manageiq-ui-classic/pull/410/files

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
more resources: https://github.com/ManageIQ/manageiq/issues/13798

**Comment by tinova** [comment]
https://github.com/OpenNebula/one/pull/2973/commits/eb31ce8bda1d308d97fafb15e5c528d9481e3a0d

**Comment by tinova** [comment]
Also revisit this #1182

**Comment by tinova** [comment]
Multiple problems:

  * no way to do a proper ws to wss websocket
  * need to accept a cookie interactively, no easy way to do this programatically
  * connection needs to be done directly to ESX, so no gain with VNC in this aspect

too many effort already spent in this issue, closing it for the time being.

**Comment by tinova** [comment]
Need to reopen this due to vSphere 7.0 dropping VNC support.

Requirements:

  - Connection from web UI to sunstone server, never straight to vCenter/ESX
  - Embedded in Web UI
  - Need to handle cookies

We can start by connecting sunstone server to ESX if needs be, no need to route through vCenter (which is probing difficult). Still need a web socket proxy in sunstone server for this.

**Comment by FrederickBor** [comment]
@tinova PR to be approved:

- one-ee:  https://github.com/OpenNebula/one-ee/pull/232

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Docu: https://github.com/OpenNebula/docs/pull/1323

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/350

**Comment by tinova** [comment]
last bit to close this ticket:

  * sunstone_vnc_tokens should be renamed to sunstone_tokens
  * noVNC tokens to be saved in sunstone_tokens/vnc
  * vmrc tokens to be saved in sunstone_tokens/vmrc
