### ISSUE TITLE
Sunstone: Accounting data does not display since the 5.6 update

### ISSUE THREAD

**Issue by trenton42** [OpenNebula/one#2315]
**Description**
When viewing the accounting tab, clicking the "Get Accounting" button does nothing, and accounting data is not displayed.

**To Reproduce**
Go to the settings tab in Sunstone, click on Accounting, then click the Get Accounting button

**Expected behavior**
Accounting data should be displayed

**Details**
 - Affected Component: Sunstone
 - Version: 5.6.0 (from debian repository -- Version 5.6.0-1)

**Additional context**
No accounting data is displayed:
![screenshot_20180724_153634](https://user-images.githubusercontent.com/1412655/43162206-4c65a3e2-8f58-11e8-95ff-5e020716c22a.png)

Errors are appearing in the browser console when pushing the Get accounting button, however, while watching the network console in the browser, it is apparent that the data is being fetched (just not displayed).

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment]
Hi @trenton42 ,
Can you provide me the console error of your browser?

**Comment by trenton42** [comment]
Hi @abelCoronado93, this is what Chrome spit out
```
jquery.dataTables.js:9213 Uncaught TypeError: Cannot read property 'parentNode' of null
    at _Api.<anonymous> (jquery.dataTables.js:9213)
    at _Api.iterator (jquery.dataTables.js:6978)
    at _Api.<anonymous> (jquery.dataTables.js:9212)
    at _Api.destroy (jquery.dataTables.js:7141)
    at jQuery.fn.init.DataTable.fnDestroy (jquery.dataTables.js:412)
    at _fillAccounting (accounting.js:583)
    at success (accounting.js:211)
    at Object.success (action.js:353)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
```

**Comment by abelCoronado93** [comment]
I was able to reproduce the problem and I can confirm that it's an error. For the next release, it will be fixed.

Thanks for your help @trenton42 .
