### ISSUE TITLE
Migrate images to/from KVM / vCenter DS

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#2320]
**Description**

Automatic conversion to/from .vmdk to .raw/.qcow2/etc upon "oneimage clone" operations can be implemented

**Use case**

To facilitate smooth transitions between KVM and VMware based infrastructures, a

**Interface Changes**

None

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
applied in 5.6 as well

**Comment by tinova** [comment]
* qcow2 format attribute in image if target DS is qcow2
* check bus attribute
* add two 'guides' or 'sections'
   * from vmdk to qcow2/raw
   * from qcow2/raw to vmdk 
          * add note in documentation vmware tools

**Comment by joseangelgm** [comment]
be able to change the driver and format is done.

**Comment by joseangelgm** [comment]
PR test: https://github.com/OpenNebula/development/pull/403
PR code: https://github.com/OpenNebula/one/pull/2555

**Comment by tinova** [comment]
Automatic conversion  .vmdk to .qcow2/.raw needs to be implemented

**Comment by tinova** [comment]
doc reverted commit: 6cd72cbd24e6b81cee9f6af57819956257a5d653
