### ISSUE TITLE
Be able to choose what types of network modes you want to use

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2326]
**Description**
Would be useful to be able to choose what type of network modes you want to see in sunstone.

**Use case**
When you create a network, you only can restrict the network modes comment the drivers in oned.conf

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
oned.conf mechanism is general for all drivers, adding this functionality will overly complicate the logic.
