### ISSUE TITLE
vCenter: update memoize cache

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2335]
**Description**

vCenter driver has a Memoize class, a memory that is used to store vCenter API queries and values.

We do not have any method to update this memory.

**To Reproduce**

with the current Memoize behaviour:

instanciate a vCenterDriver::vm object
perform a has_snapshots query
call vm delete_snapshots method
perform the same query again, it will provide you the wrong results.

**Expected behavior**

new methods to update memory cache (memoize):

get(property): updates a single property performing the real query to vCenter api
refresh(): updates all stored properties.

**Details**
 - Affected Component: VMM component
 - Hypervisor: KVM
 - Version: Development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
PR: https://github.com/OpenNebula/one/pull/3313 --> master
Docs: https://github.com/OpenNebula/docs/pull/615 --> one-5.8-maintenance
