### ISSUE TITLE
option to pin VM's vCPUs to threads on same CPU cores (L1TF mitigation)

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2349]
**Description**
OpenNebula should know the CPU's HT topology and offer option for manual pinning of vCPUs to hyper-threads if not automatic algo was developed.

**Use case**
The mitigation against [L1TF](https://www.intel.com/content/www/us/en/architecture-and-technology/l1tf.html) ([RedHat's description](https://www.redhat.com/en/blog/understanding-l1-terminal-fault-aka-foreshadow-what-you-need-know#)) recommends to map all VM's vCPU threads to threads on same cores. This will mitigate the case with a rogue VM accessing memory from VM on the other HT on same CPU core.

**Interface Changes**
The monitoring probe should report the host CPU topology to OpenNebula.
OpenNebula should show the HT topology and offer an interface to select to which HT to pin the vCPUs in both CLI and sunstone

**Additional Context**
I believe it is related to issue [#590](https://github.com/OpenNebula/one/issues/590)

In any case the (live) migration with pinned vCPUs is becoming (lets say) complicated. 

( We are living in a very interesting time :) )

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This feature will be implemented through the CORE policy where just one VM vCPU is assigned to a server CORE, making use of one cpu thread.
