### ISSUE TITLE
Volatiled disks creates as files for fs_lvm

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2353]
**Description**
I'm not sure is it bug or feature, but better to take clear with it.
Volatile disk in fs_lvm creates as file in system datastore.

**To Reproduce**
* Use fs_lvm driver
* Create volatiled disk for the VM

**Expected behavior**
Disk will be created as lvm partition

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Version: 5.6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
> So is that normal behavior?

It's a normal behavior, volatile disks are created as filesystem images.

> We can close this issue if so.

We can leave it opened for tracking purposes. I think it makes sense to improve this, unify the behavior and store also volatile disks on LVM.

**Comment by rsmontero** [comment]
merged in master for 5.8
