### ISSUE TITLE
fs_lvm offline migration does not work

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2359]
**Description**
No way for offline migrate VM with system drive on fs_lvm
VM is going to the FAILED state after migration, because lvm volume is not activated on target node.

Probably it is should be done by `tm/fs_lvm/premigrate` script, but it seems it is called only for online migration

**To Reproduce**
Try to offline migrate.

**Expected behavior**
VM succesful migrated

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Version: 5.6.0

**Additional context**

For solve this problem need to activate volume after migration and before resuming VM:
```
lvchange -ay /dev/vg-one-137/lv-one-6446-0 
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
I can't reproduce.

When offline migration is done, pre/post migrate scripts aren't called, that's correct. But, the "mv" action script is triggered and should do the device activation. Please check you have the same code:
https://github.com/OpenNebula/one/blob/7c916ebe600da9e0da77104ce4dfc06d70cae6bd/src/tm_mad/fs_lvm/mv#L133-L144

**Comment by kvaps** [comment]
@vholer for me this script is not called for some reason

**Comment by kvaps** [comment]
solved for me, by this patch
https://github.com/OpenNebula/one/issues/2342

**Comment by nos1kg7at** [comment]
Same behaviour in 5.6.1. Fixed temporary by workaround
adding manual activate part into /var/lib/one/remotes/vmm/kvm/deploy:
++
Activate LVM
VMID=cat $domain | grep '<name>one-' | sed -e 's/.*<name>one-\(.*\)<\/name>/\1/'
DS_DIR=/var/lib/one/datastores

$SUDO $SYNC >> /dev/null
$SUDO $LVSCAN >> /dev/null

for disk in find $DS_DIR/*/$VMID/disk.*; do
if [ -L "$disk" ]; then
DEVICE=readlink "$disk"
$SUDO $LVCHANGE -ay $DEVICE
fi
done
++

**Comment by xorel** [comment]
I can't reproduce as well.

Can we check how your setup differs from the [doc](https://docs.opennebula.org/5.6/deployment/open_cloud_storage_setup/lvm_drivers.html)? Do you have CLVM enabled for instance?

Regarding the proposed patches, we strongly prefer not to mix vmm and tm driver functions so let's try to find another solution.

**Comment by kvaps** [comment]
HI @xorel. I have no CLVM, but as can I see, OpenNebula just not calls this action during API call

**Comment by rsmontero** [comment]
So still we cannot reproduce this. Let me summary the issue:
* Problem is not LV not being activated lvchange
* OpenNebula performs this operation in the MV script
* This MV command should be performed for any VM migrating in proglog poweroff
* For some reason this is not the case for @kvaps  + @nos1kg7at 

@kvaps could you send the following information:

* The log file for the VM (/var/log/one/<vm_id>.log file). We want to check the actual states transition in your test case
* transfer files for your VM. This are located in /var/log/one/vms/<vm_id>/. Please send output of `ls` in this directory and `cat transfer.*.prolog`


Thanks!

**Comment by kvaps** [comment]
@rsmontero sure!

Try to do that:

* Power off the VM
* Try to migrate it

Can reproduce this on 5.8.0

- Log:

```
[Z0][VM][I]: New LCM state is PROLOG_MIGRATE_POWEROFF
[Z0][VM][I]: New state is ACTIVE
[Z0][VM][I]: New state is POWEROFF
[Z0][VM][I]: New LCM state is LCM_INIT
[Z0][HKM][I]: Success executing Hook: vps_tasks: .
[Z0][VM][I]: New state is ACTIVE
[Z0][VM][I]: New LCM state is BOOT_POWEROFF
[Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/36/deployment.11
[Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
[Z0][VMM][I]: ExitCode: 0
[Z0][VMM][I]: Successfully execute network driver operation: pre.
[Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/103/36/deployment.11' 'new-node' 36 new-node
[Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/103/36/deployment.11
[Z0][VMM][I]: error: Cannot access storage file '/var/lib/one//datastores/103/36/disk.0': No such file or directory
[Z0][VMM][E]: Could not create domain from /var/lib/one//datastores/103/36/deployment.11
[Z0][VMM][I]: ExitCode: 255
[Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
[Z0][VMM][E]: Error deploying virtual machine: Could not create domain from /var/lib/one//datastores/103/36/deployment.11
[Z0][VM][I]: New state is POWEROFF
[Z0][VM][I]: New LCM state is LCM_INIT
```

- Directory content:
```bash
new-node:~# ls -l /var/lib/one//datastores/103/36
total 392
-rw-rw-r-- 1 oneadmin oneadmin   1538 Mar  8 13:59 deployment.0
-rw-rw-r-- 1 oneadmin oneadmin   1977 Mar 26 10:45 deployment.11
-rw-rw-r-- 1 oneadmin oneadmin   1531 Mar 13 21:26 deployment.5
-rw-rw-r-- 1 oneadmin oneadmin   1531 Mar 13 21:38 deployment.6
-rw-rw-r-- 1 oneadmin oneadmin   1543 Mar 13 21:39 deployment.7
-rw-rw-r-- 1 oneadmin oneadmin   1543 Mar 13 21:40 deployment.8
lrwxrwxrwx 1 oneadmin oneadmin     27 Mar  8 13:59 disk.0 -> /dev/vg-one-103/lv-one-36-0
-rw-r--r-- 1 oneadmin oneadmin 374784 Mar 26 10:45 disk.1
```

- `.host` file:
```bash
new-node:~# cat /var/lib/one//datastores/103/36/.host
<old-node>
```

- Block device:
```bash
old-node:~# file /dev/vg-one-103/lv-one-36-0
/dev/vg-one-103/lv-one-36-0: symbolic link to ../dm-9

new-node:~# file /dev/vg-one-103/lv-one-36-0
/dev/vg-one-103/lv-one-36-0: cannot open `/dev/vg-one-103/lv-one-36-0' (No such file or directory)
```
* `cat transfer.*.prolog`
```
new-node:~# cat transfer.*.prolog
cat: 'transfer.*.prolog': No such file or directory
```

**Comment by rsmontero** [comment]
VM directory for the prolog scripts are: 
`ls -l /var/lib/one/vms/36`

There should be the .prolog files

**Comment by vholer** [comment]
Related issue I guess https://github.com/OpenNebula/one/issues/3130. Root cause described there as a single image datastore architecture and two different system datastores (filesystem and LVM based).

**Comment by kvaps** [comment]
@rsmontero  There is no prolog files, only migrate
```
opennebula-oned-0:/$ ls -l /var/lib/one/vms/36
-rw-r--r-- 1 oneadmin oneadmin  998 Mar 26 11:13 context.sh
-rw-r--r-- 1 oneadmin oneadmin 1976 Mar 26 10:45 deployment.11
-rw-r--r-- 1 oneadmin oneadmin 1976 Mar 26 11:13 deployment.13
-rw-r--r-- 1 oneadmin oneadmin   25 Mar 26 11:13 token.txt
-rw-r--r-- 1 oneadmin oneadmin  196 Mar 26 10:45 transfer.10.migrate
-rw-r--r-- 1 oneadmin oneadmin  196 Mar 26 11:13 transfer.12.migrate
```

I presume it is because i'm running opennebula inside docker containers, and `/var/lib/one/vms` is nowhere mounted so changes are losing every restart, this VM was  probably deployed before last restarted of oned container.

I was prepared new VM, with the same storage, here is output of transfer.*.prolog file (it's just one):

```
opennebula-oned-0:/$ cat /var/lib/one/vms/57/transfer.0.prolog 
CLONE fs_lvm opennebula-oned-0:/var/lib/one//datastores/100/5db3ed3c0f2b783897334f0cc79aca81 m1c6:/var/lib/one//datastores/103/57/disk.0 57 100
```

**Comment by kvaps** [comment]
@vholer not related,

I have normal configuration according the docs:

```
ALLOW_ORPHANS="NO"
BRIDGE_LIST="m1c4 m1c5 m1c6 m1c7 m1c8 m1c9"
CLONE_TARGET="SYSTEM"
DISK_TYPE="BLOCK"
DRIVER="raw"
DS_MAD="fs"
DS_MIGRATE="YES"
LN_TARGET="SYSTEM"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
TM_MAD="fs_lvm"
TYPE="IMAGE_DS"
```

```
ALLOW_ORPHANS="NO"
BRIDGE_LIST="m1c4 m1c5"
DRIVER="raw"
DS_MIGRATE="YES"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
SHARED="YES"
TM_MAD="fs_lvm"
TYPE="SYSTEM_DS"
```

**Comment by kvaps** [comment]
@vholer sorry, you're right, related!
After changing `/VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/TYPE` to `BLOCK`
`.host` file were updated to new node

**Comment by rsmontero** [comment]
@kvaps yes sorry, I wrote prolog, but I meant migrate, what is in your migrate files?

**Comment by rsmontero** [comment]
I've read the related issue #3130 , and yes they are the same thing, I guess that your migrate files do include the MV statement, but this MV operation is by passed because of the TYPE/DISK_TYPE check.

I'll close the other one and focus on this github issue to solve this bug

**Comment by kvaps** [comment]
Fully agree that

**Comment by vholer** [comment]
Last thing for now, can you please @kvaps share with us XML template of some affected VM

```
onevm show ${ID} --xml
```

Just the `<DISK>` sections are enough. Thank you!

**Comment by kvaps** [comment]
Sure, sorry for long delay
```
    <DISK>
      <ALLOW_ORPHANS>NO</ALLOW_ORPHANS>
      <CLONE>YES</CLONE>
      <CLONE_TARGET>SYSTEM</CLONE_TARGET>
      <CLUSTER_ID>102,103,104,105</CLUSTER_ID>
      <DATASTORE>images</DATASTORE>
      <DATASTORE_ID>100</DATASTORE_ID>
      <DEV_PREFIX>vd</DEV_PREFIX>
      <DISK_ID>0</DISK_ID>
      <DISK_SNAPSHOT_TOTAL_SIZE>0</DISK_SNAPSHOT_TOTAL_SIZE>
      <DISK_TYPE>FILE</DISK_TYPE>
      <DRIVER>raw</DRIVER>
      <IMAGE>Alpine Linux 3.8 [5.6.0-0.20181019]</IMAGE>
      <IMAGE_ID>1419</IMAGE_ID>
      <IMAGE_STATE>2</IMAGE_STATE>
      <IMAGE_UNAME>oneadmin</IMAGE_UNAME>
      <LN_TARGET>SYSTEM</LN_TARGET>
      <ORIGINAL_SIZE>512</ORIGINAL_SIZE>
      <READONLY>NO</READONLY>
      <SAVE>NO</SAVE>
      <SIZE>8192</SIZE>
      <SOURCE>/var/lib/one//datastores/100/e2024556262275ff7c97f61e4fb0690d</SOURCE>
      <TARGET>vda</TARGET>
      <TM_MAD>fs_lvm</TM_MAD>
      <TYPE>FILE</TYPE>
    </DISK>
```

**Comment by kvaps** [comment]
The worst thing is that after removing this check `undeploy` operations is stopping working, because opennebula tries to run `mv` on the controller:

```
...
[Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY
[Z0][TM][I]: Command execution failed (exit code: 255): /var/lib/one/remotes/tm/fs_lvm/mv m1c6:/var/lib/one//datastores/103/63/disk.0 opennebula-oned-0:/var/lib/one//datastores/103/63/disk.0 63 100
```

**Comment by rsmontero** [comment]
Thanks, this confirms the problem is ``` <TYPE>FILE</TYPE>``` We'll revisit the scripts and consider when the behavior should be exteneded to accomodate this. 

Thanks. 

Replanning this to 5.8.2 till we have a clear picture of what is needed in terms of actions

**Comment by atodorov-storpool** [comment]
The hard-coded `TYPE=FILE` for the volatile disks rise other issues with recent libvirt. At least on CentOS7 libvirt is blocking the live-migration because it is assuming that the disks of type "file" are not  on shared filesystem. But in fact this is just the definition, the real device is not file after all, but libvirt desn't know that.

As a workaround I've created alternate [deploy](https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks) script that use a trivial [helper](https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks.d.example/volatile2dev.py) to alter the domain XML and replaces the definition from _file_ to block _dev_. 

IMO there should be a `DISK_TYPE` option in the `TM_MAD_CONF` instead of the hard-coded type, just like it is for the IMAGE datastore.
