### ISSUE TITLE
improve auto-increment in VM name

### ISSUE THREAD

**Issue by jsfrerot** [OpenNebula/one#2377]
**Description**
When creating multiple VMs it is possible to use %i which will increment starting from 0.
In an environment where VM names are very important, it would be useful to be able to have more control over the automatic increment variable.

**Use case**
If I have already existing VMs "myvm-001", "myvm-002", "myvm-003" and I would like to create 3 new VMs  following the same scheme, I would like to be able to start from 4 and have the possibility to have 0s prefixing the ID. So I could create "myvm-%i" starting from 004 to 015 for example.

**Interface Changes**
add an optional startID field
add an optional prefix field

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This is still interesting

**Comment by jsfrerot** [comment]
I'm still interested in the feature.
Thank you.

**Comment by al3xhh** [comment]
This will be implemented using #2287, closing this.
