### ISSUE TITLE
VM save As refactor

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2386]
**Description**
vCenter driver, save as Rework.

**Use case**
You have a VM running and you want to save it into a template.

**Interface Changes**
None

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
great work
