### ISSUE TITLE
vCenter TM Refactor

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2387]
**Description**
All the TM operations of vCenter driver are being reworked.

**Use case**
This feature is going to disable two major functionalities: 
* instantiate as persistent
* save as

**Additional Context**
Also we are going to separate opennebula resources shared with vCenter and make additional logic:
- resource subclass
    * checks one_managed attribute
    * common methods
- disk < resource
    * operations related to vCenter disks
- nic   < resource
    * operations related to vCenter nics

 
## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
This has been huge! kudos 💃
