### ISSUE TITLE
Onehost sync should ignore vCenter hosts

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2398]
**Description**
onehost sync make a syncing to every hosts

**To Reproduce**
make a onehost sync with vCenter hosts

**Expected behavior**

**Details**
 - Affected Component: Cli
 - Hypervisor: vCenter
 - Version: 5.6

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
applied in 5.6 and master
