### ISSUE TITLE
Live-Migration with preselected target hosts

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2407]
**Description**
When you want to live-migrate a VM through sunstone, you have to choose the target host. It would be useful to have pre-selected those suitables target hosts, take into account the cluster that the hosts belong to etc.

**Use case**
Live migrate a VM from sunstone.

**Interface Changes**
Sunstone

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
to be addressed in FireEdge sunstone #5724
