### ISSUE TITLE
Delete VMs folder from the frontend when the VM reach DONE state

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2408]
**Description**
Delete the VM folder from /var/lib/one/vms when the VM associated reach DONE state.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Folders are left for auditing purposes. An externa tool or script can be used to clean unneeded folders.

**Comment by baby-gnu** [comment]
For the records, we have now [a little tool](https://forum.opennebula.io/t/cleanup-old-done-vms-folders-and-log-files/10364) added to `oneadmin` crontab.
