### ISSUE TITLE
VM autorefresh

### ISSUE THREAD

**Issue by abelCoronado93** [OpenNebula/one#2410]
**Description**
Autorefresh of a specific VM in its individual view to update the status and possible actions to perform on it (e.g. attach, detach...)

Configurable time via yaml files (default 5 seconds)

**Use case**
Autorefresh will help the user experience to be able to see the VM status and what actions are available.

**Interface Changes**
Improve feedback when autorefresh is executed.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
need refresh test

**Comment by rsmontero** [comment]
The current implementation breaks the VM widgets, we have reverted the changed and postpone the issue to look for a better implementation strategy

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- ONE: https://github.com/OpenNebula/one-ee/pull/180

**Comment by tinova** [comment]
needs documentation

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Docs: https://github.com/OpenNebula/docs/pull/1286

**Comment by FrederickBor** [comment]
Needs evaluation to reuse it on Hosts, Images, Datastores, etc

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/308

**Comment by tinova** [comment]
needs test

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/332
- Test: https://github.com/OpenNebula/development/pull/1195
