### ISSUE TITLE
Poweroff all VM on the host provides bridge interface disable

### ISSUE THREAD

**Issue by Maunty** [OpenNebula/one#2412]
**Description**

Poweroff  last VM on host that use hosts bridge interface via sunstone provides disabling of bridge interface. 

**To Reproduce**
Steps to reproduce the behavior.

I used intallation tarball package for Ubuntu. Downloaded Leap15 template. Initiate 1 vm with attched bridge host interface, then i poweroff vm and lose my connection to host. If i have more then 1 vm, poweroff one of them dont give me this result, but if i poweroff all of them i also lose my connection to host coz this disable bridge interface.
For managing is used sunstone interface.

**Expected behavior**

I dont expect disabling my bridge interface and losing remote access to host.

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
Sunstone
 - Hypervisor: [e.g. KVM]  
KVM
 - Version: [e.g. 5.4.12 or development]
5.6.0

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Maunty** [comment]
migrating to ifupdown from netplan solve this issue.

**Comment by amravyan** [comment]
We have the same problem: bridge destorys after the last VM is powered off. By the way, it happens only if VM was poweroffed from nebula's web ui. 
After correct power off from guest OS (systemctl poweroff) no problems occur.
**:keep_empty_bridge:** in var/lib/one/remotes/etc/vnm/OpenNebulaNetwork is set to **true**.
Centos 7.5.1804, OpenNebula 5.6.1.

poweroff from OS
```
Mon Oct  8 16:34:16 2018 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Mon Oct  8 16:34:16 2018 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Mon Oct  8 16:34:16 2018 [Z0][VM][I]: New state is POWEROFF
```
**start**
```
Mon Oct  8 16:34:16 2018 [Z0][VM][I]: New LCM state is LCM_INIT
Mon Oct  8 16:38:55 2018 [Z0][VM][I]: New state is ACTIVE
Mon Oct  8 16:38:55 2018 [Z0][VM][I]: New LCM state is BOOT_POWEROFF
Mon Oct  8 16:38:55 2018 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/2/deployment.14
Mon Oct  8 16:38:55 2018 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Mon Oct  8 16:38:56 2018 [Z0][VMM][I]: ExitCode: 0
Mon Oct  8 16:38:56 2018 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Mon Oct  8 16:38:56 2018 [Z0][VMM][I]: ExitCode: 0
Mon Oct  8 16:38:56 2018 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Mon Oct  8 16:38:56 2018 [Z0][VMM][I]: ExitCode: 0
Mon Oct  8 16:38:56 2018 [Z0][VMM][I]: Successfully execute network driver operation: post.
Mon Oct  8 16:38:56 2018 [Z0][VM][I]: New LCM state is RUNNING
```
**poweroff from webui**
Mon Oct  8 16:43:53 2018 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Mon Oct  8 16:43:53 2018 [Z0][VMM][I]: ExitCode: 0
Mon Oct  8 16:43:53 2018 [Z0][VMM][I]: Successfully execute virtualization driver operation: cancel.
**Mon Oct  8 16:44:46 2018 [Z0][VMM][I]: clean: Executed "sudo ip link delete br0".**
Mon Oct  8 16:44:46 2018 [Z0][VMM][I]: ExitCode: 0
Mon Oct  8 16:44:46 2018 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Mon Oct  8 16:44:46 2018 [Z0][VM][I]: New state is POWEROFF
Mon Oct  8 16:44:46 2018 [Z0][VM][I]: New LCM state is LCM_INIT

**Comment by amravyan** [comment]
The problem was in difference between config files:
in _/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf_ :keep_empty_bridge: was set to **true**
in _/var/tmp/one/etc/vnm/OpenNebulaNetwork.conf_ :keep_empty_bridge: was set to **false**.

After fixing _/var/tmp/one/etc/vnm/OpenNebulaNetwork.conf_ problem was sovled
The main question: **why configs are different?** Restarted oned and rebooted host a few time after setting :keep_empty_bridge: true in _/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf_

**Comment by Maunty** [comment]
> The problem was in difference between config files:
> in _/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf_ :keep_empty_bridge: was set to **true**
> in _/var/tmp/one/etc/vnm/OpenNebulaNetwork.conf_ :keep_empty_bridge: was set to **false**.
> 
> After fixing _/var/tmp/one/etc/vnm/OpenNebulaNetwork.conf_ problem was sovled
> The main question: **why configs are different?** Restarted oned and rebooted host a few time after setting :keep_empty_bridge: true in _/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf_

Nebula is buggy ) once after an minor update it deleted /var/lock/oned/ and vnc proxy didnt worked without it. I spent a couple of hours while trying to fix this problem

**Comment by algiar** [comment]
I have found that getting the PHYDEV variable undefined while creating the virtual networks do not trigger the issue, just as a workaround...

**Comment by rsmontero** [comment]
Since version 5.8 Opennebula features two different drivers:
* dummy does not do anything with the bridges (nor creating them nor deleting them)
* bridge OpenNebula will take care of the life-cycle of the bridge

Additionally, there is a configuration option to not delete empty bridges for the bridge driver:
```
################################################################################ 
# Bridge and Interface Creation Options                                          
################################################################################ 
                                                                                 
# Don't delete bridge with no virtual interfaces left                            
:keep_empty_bridge: false  
```
(This is in OpenNebulaNetwork.conf file)

Finally, for security reasons, It'd be better not to put VMs on the same bridge where the management interface is attahed.

Closing...

**Comment by rightkick** [comment]
Although this is a closed issue, it is important to note that after adjusting the option `:keep_empty_bridge: true` at `/var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf` you need to sync the change to the hosts by force syncing with `su oneadmin -c 'onehost sync --force'`
