### ISSUE TITLE
Migrate bower to Yarn

### ISSUE THREAD

**Issue by abelCoronado93** [OpenNebula/one#2417]
**Description**
The bower package manager is deprecated. It would be better to use Yarn.

**Use case**
N/A

**Interface Changes**
N/A

**Additional Context**
N/A

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Ruby sunstone deprecated
