### ISSUE TITLE
No way for create big IPv6 address ranges

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2449]
**Description**
Following [RFC3177](https://tools.ietf.org/html/rfc3177), we want to provide `/64` subnet for each customer, for make him possible to use any address from his network.
`/64` network it is **281474976710656** addresses, but opennebula can't handle so large number.

**To Reproduce**

Create IPv6 network, then:
```
onevnet addar -s 281474976710656 --ip6 2001::1/16 983
[one.vn.add_ar] Wrong SIZE for address range
```

**Expected behavior**
Created address range.

**Details**
 - Affected Component: Core
 - Hypervisor: kvm
 - Version: 5.6

**Additional context**
The same problem will be if you will try to create larger prefix IPv6 network for the rent.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Closing this as duplicate for #2187
