### ISSUE TITLE
Catch monitor errors

### ISSUE THREAD

**Issue by joseangelgm** [OpenNebula/one#2453]
**Description**

#<SystemExit: exit>
/usr/lib/one/ruby/vcenter_driver/vi_helper.rb:34:in `exit'
/usr/lib/one/ruby/vcenter_driver/vi_helper.rb:34:in `return_if_error'
/usr/lib/one/ruby/vcenter_driver/vi_helper.rb:74:in `one_item'
/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3327:in `get_vm'
/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3390:in `new_from_ref'
/usr/lib/one/ruby/vcenter_driver/host.rb:482:in `block in monitor_vms'
/usr/lib/one/ruby/vcenter_driver/host.rb:459:in `each'
/usr/lib/one/ruby/vcenter_driver/host.rb:459:in `monitor_vms'
./poll:56:in `<main>'
[one.vm.info] Error getting virtual machine [205].
#<SystemExit: exit>
/usr/lib/one/ruby/vcenter_driver/vi_helper.rb:34:in `exit'
/usr/lib/one/ruby/vcenter_driver/vi_helper.rb:34:in `return_if_error'
/usr/lib/one/ruby/vcenter_driver/vi_helper.rb:74:in `one_item'
/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3327:in `get_vm'
/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3390:in `new_from_ref'
/usr/lib/one/ruby/vcenter_driver/host.rb:482:in `block in monitor_vms'
/usr/lib/one/ruby/vcenter_driver/host.rb:459:in `each'
/usr/lib/one/ruby/vcenter_driver/host.rb:459:in `monitor_vms'
./poll:56:in `<main>'

**To Reproduce**
Execute manually vcenter poll

**Expected behavior**
Catch this error to not display them

**Details**
 - Affected Component: tm mad
 - Hypervisor: vCenter
 - Version: 5.6.2

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
PR: https://github.com/OpenNebula/one/pull/3319 --> master
Doc: https://github.com/OpenNebula/docs/pull/616 --> one-5.8-maintenance

**Comment by tinova** [comment]
fixed in bf3938d76f334aa2b6dfc50ece5d264e9ba50e74
