### ISSUE TITLE
Datastores and VNET intermittently loose cluster membership under heavy load on HA environments.

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#2455]
**Description**
Datastores and VNET intermittently loose cluster membership under heavy load on HA environments.

**To Reproduce**
HA environment, aggressive scheduler configs, instantiate high number of vms.

**Expected behavior**
Every VM gets successfully instantiated.

**Details**
 - Affected Component:
* Core ?
* RAFT ?

 - Hypervisor: [KVM]
 - Version: [5.6.0.1]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This should be solved in 5.8
