### ISSUE TITLE
CentOS 7.5: mm_sched does not stop when opennebula processes are stopped

### ISSUE THREAD

**Issue by fgc92** [OpenNebula/one#2457]
On a machine running CentOS 7.5.1804, mm_sched process does not stop when opennebula processes are stopped. 

root@opennebula-center:/var/log/one> ps -aux|grep mm_sched
oneadmin  2136  0.1  0.1 267356  6692 ?        Ssl  14:27   0:18 /usr/bin/mm_sched
root@opennebula-center:/var/log/one> systemctl stop opennebula
root@opennebula-center:/var/log/one> ps -aux|grep mm_sched
oneadmin  2136  0.1  0.1 267356  6692 ?        Ssl  14:27   0:18 /usr/bin/mm_sched

When opennebula processes are requested to stop or restart, mm_sched should follow the same request. 

CentOS 7.5.1805
OpenNebula 5.6 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
OpenNebula scheduler has own service description and its lifecycle is managed independently to the OpenNebula oned daemon. Usually, it's not necessary to restart scheduler on `opennebula` restart. If you need to restart also the scheduler, please use:

```
systemctl restart opennebula-scheduler.service
```

For the backward compatibility, start of the `opennebula` service also triggers start of `opennebula-scheduler` service. But, this weak dependency can be easily broken and this way scheduler can easily run on a dedicated machine.

Closing the issue.
