### ISSUE TITLE
vCenter uploader incorrect file names

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2464]
**Description**
vCenter uploader for vCenter driver does not process file names properly.

**To Reproduce**
Steps to reproduce the behavior.

Create a image in OpenNebula to store in vCenter datastore:

    oneimage create --name cdromPrueba --type cdrom
     --path http://tinycorelinux.net/8.x/x86/release/Core-current.iso -d 100

Check the final file in the destination datastore, the name will be: Core-current.iso.iso

**Expected behavior**

The final filename remains unchanged.

**Details**
 - Affected Component: vCenter ds_mad (cp)
 - Hypervisor: vCenter
 - Version: development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
.iso extension needs to be added, we need to check if the current filename ends in .iso in order not to duplicate it
