### ISSUE TITLE
Host and Images autorefresh

### ISSUE THREAD

**Issue by abelCoronado93** [OpenNebula/one#2468]
**Description**
Host and Images autorefresh

**Use case**
N/A

**Interface Changes**
N/A

**Additional Context**
N/A

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
VMs and Host autorefresh are implemented in this [issue](https://github.com/OpenNebula/one/issues/2410)

Finally, images aren't included on autorefresh
