### ISSUE TITLE
Network model is not working in vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2474]
**Description**
Network model is not working when using vCenter. The attribute is not taken from the template.

**To Reproduce**
Add a network model to the template and instantiate it.

**Details**
 - Affected Component: network
 - Hypervisor: vCenter

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by joseangelgm** [comment]
PR test https://github.com/OpenNebula/development/pull/381

**Comment by tinova** [comment]
good work!
