### ISSUE TITLE
VCENTER_ESX_HOST fail with DRS in vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2477]
**Description**
With DRS, VCENTER_ESX_HOST in USER_TEMPLATE doesnt have the real host. Only the monitoring.

**To Reproduce**
With DRS in vCenter, launch a VM and VNC doesn't work.

**Details**
 - Hypervisor: vCenter
 - Version: 5.6.1

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
needs changes ported to master

**Comment by tinova** [comment]
changes already ported to master, good!

**Comment by tinova** [comment]
https://github.com/OpenNebula/docs/pull/398
