### ISSUE TITLE
Case insensitive LDAP username matching

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2479]
**Description**
Based on the description on community forum:
https://forum.opennebula.org/t/ldap-user-duplication-with-case-is-changed/4337
user name is case insensitive for the LDAP authentication and can result in having multiple different ONE users just with different casing (or leading/trailing spaces).

**Details**
 - Affected Component: Authentication
 - Version: 5.6, development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Observations:

1.  LDAP login is usually really case in-sensitive
2. Change proposed by @jfontan (escaped_user=URI_PARSER.escape(user).downcase) works as follows:
 * during the first login any case for username is accepted
 * user created in OpenNebula afterwards is always lower-case
 * any further login is successful only if the lower-case username is used

IMHO, this is quite acceptable, slightly better might be if OpenNebula still accepts any case username for LDAP user, but all maps to a single user
