### ISSUE TITLE
Add force IPV4 field to cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2496]
**Description**
The force IPV4 input text doesn't appear in the cloud view.

**Use case**
Users can force an IPV4.

**Interface Changes**
Sunstone

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- One: https://github.com/OpenNebula/one/pull/4755
- Docs: https://github.com/OpenNebula/docs/pull/1125
- Dev: https://github.com/OpenNebula/development/pull/984
