### ISSUE TITLE
Running VMs in Groupadmin dashboard should be Total VMs

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2504]
**Description**

The count includes all active VMs, not just running VMs

**To Reproduce**

Deploy 2 VMs, power one off.

**Expected behavior**

Dashboard to report 2 TOTAL VMs, not 2 RUNNING VMs

**Details**
 - Affected Component: Sunstone
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4566
- docs: OpenNebula/docs/pull/1069
