### ISSUE TITLE
Be able to delete in vCenter templates instantiate as persistent from OpenNebula

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2512]
**Description**
When instantiate a template as persistent, if you delete the new persistent template is not delete in vCenter.

**Use case**
- Instantiate as persistent
- Try to remove the new template

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
This will implemented as part of #1148
