### ISSUE TITLE
Newlines removed from template parameters

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2515]
**Description**
Newlines are removed from all template parameters, which breaks their content.

**To Reproduce**

Following simple use-cases:

1. user with SSH_PUBLIC_KEY could have multiple SSH keys inside, now all are merged into a single line

2. VM template could have START_SCRIPT in the context section with a plain shell script; now again all lines are merged into single line

![image](https://user-images.githubusercontent.com/414850/47077035-5b655280-d200-11e8-81cd-fbf6dd0eb89f.png)

![image](https://user-images.githubusercontent.com/414850/47077079-76d05d80-d200-11e8-87f3-821b32d12e08.png)

![image](https://user-images.githubusercontent.com/414850/47077133-94052c00-d200-11e8-97c3-45ee6207e96e.png)

**Expected behavior**

**Details**
 - Affected Component: Core
 - Version: 5.6.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Observations:
1. content with preserved newlines is stored into the database
2. on object read from database, the newlines are stripped and this broken content is presented to the user
3. if user modifies the broken content, it's persisted in the database

**Comment by feldsam** [comment]
This problem is also when saving multiple ssh keys to user profile. It is saved ok, but when you try edit, everything is in one line and you have to fix it before saving.
