### ISSUE TITLE
Oneadmin can't change "other" permissions, with ENABLE_OTHER_PERMISSIONS=YES

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2563]
**Description**
Admins can't change "other" permissions, even if they are belongs to oneadmin group.

**To Reproduce**

* set `ENABLE_OTHER_PERMISSIONS = "YES"` in `oned.conf`
* try to mark/unmark some image permission for others by oneadmin account
* You will have output:
```
[one.image.chmod] User [305] : 'other' permissions is disabled in oned.conf.
```

**Expected behavior**

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: 5.6.0

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by hydro-b** [comment]
I ran into this same issue. A (oneadmin) cloud admin should be able to set "USE" for others to share golden IMAGES / TEMPLATES etc.

**Comment by christian7007** [comment]
I've tested it and it seems to works fine. I just follow the steps mentioned above in a clear installation of ONE 5.6.

**Comment by hydro-b** [comment]
I've tested it in a clean (setup by minione) OpenNebula installation version 5.8.0 and it gives me: [one.image.chmod] User [0] : 'other' permissions is disabled in oned.conf.

**Comment by hydro-b** [comment]
Tro to set "USE" for "OTHER" on the default image installed by minione.

**Comment by hydro-b** [comment]
ENABLE_OTHER_PERMISSIONS = "NO" <- this setting should be set to "NO". Then the oneadmin user is not able to set permissions for other

**Comment by hydro-b** [comment]
Not sure if "ENABLE_OTHER_PERMISSIONS=NO" should be enforced for everybody including oneadmin, or only users not a member of the oneadmin group. So it can be either a bug or a feature. For what I want: always allow oneadmin to set permissions, and enforce only for less privileged users (not a member of group oneadmin).

**Comment by paczerny** [comment]
PRs for merge:

    one: #3449 into 5.8 and master
    docs: OpenNebula/docs#672 into one-5.8-maintenance
    development: OpenNebula/development#658 into one-5.8 and master
