### ISSUE TITLE
CLI paging issues

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2565]
**Description**

Since 5.6.x with CLI commands paging via `less`, I experience few things which can be irritating to the user. I don't say they are necessary bugs.

1. CSV output (`--csv`) is paged
2. CSV output contains extra header lines inside
![image](https://user-images.githubusercontent.com/414850/47780975-e3695300-dcfc-11e8-8b3e-12f605b98640.png)
- moreover, these extra headers aren't on first line of the pages
- regular tabular output doesn't provide these extra headers
3. if I compare `onevm list` and `onevm list | less`, the first one waits for each page from the server and is much less interactive than the second one with explicit less.
4. when I quit from the very first page, it still (probably) fetches all the rest pages and takes few more seconds until command exits
5. when I terminate with  ^C, it breaks the terminal
![image](https://user-images.githubusercontent.com/414850/47781711-aef69680-dcfe-11e8-9681-dfe4158e71bc.png)
6. there is probably no detection if `less` is even installed (https://github.com/OpenNebula/packages/issues/51)

**Details**
 - Affected Component: CLI
 - Version: 5.6

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
about 6) Use `more` as the most likely fallback if `less` is not available. So, the evaluation should be:

If pager is not disabled (`--no-pager`) or the execution is not part of the pipe:
1. take env. variable `ONE_PAGER`
2. check and use `less`
3. check and use `more` <--- NEW
4. fallback to no pager.

**Comment by vholer** [comment]
> I have another issue related to paging:
> 
> 1. paging broken for oneimage show with lots of VMs
> 
> This probably happens only for oneadmin or another user which can access many VMs. For unused image, "oneimage show " returns the unpaged output. However, for an image used by some VMs, "oneimage show " displays unpaged output related to the image properties, and then runs pager displaying ALL vms in the system (or maybe all owned by this user). So the result of "oneimage show 498" on my system is a paged equivalent of "onevm list" (and the oneimage output related to the image is lost outside of the pager), but "oneimage show 498 | less" (pager explicitly added) displays the image-related data as well as only the two VMs which use this particular image).

@Yenya, I think this was fixed by https://github.com/OpenNebula/one/pull/2446 when the paging was disabled for the inner lists of VMs with onehost / oneimage commands.

**Comment by rsmontero** [comment]
1. Added option nopager (alternatively | cat) so --csv can use no pager 
2. Fixed extra headers in csv output
3. It should be much more interactive. Pages are of a few elements they should be quick onevm list | less with large pools may take minutes to output a line. This is the main benefit of using pagination.
4. Command fetches pages and send them to pager, if the pager dies no more pages are fetched. This break in the fetch-page loop:
https://github.com/OpenNebula/one/blob/master/src/cli/one_helper.rb#L626
5. Fixed, tools now properly finishes the pager if interrupted e.g. via SIGINT
6. Reverted to more as default. more is POSIX standard (http://pubs.opengroup.org/onlinepubs/009695399/utilities/more.html) I guess it is safe to assume it is present.
