### ISSUE TITLE
kvm pci probe does not change hyp database values after pci.rb changes

### ISSUE THREAD

**Issue by alvarosimon** [OpenNebula/one#2574]
**Description**
This issue is related with this thread:

https://forum.opennebula.org/t/how-to-request-two-different-pci-devices-with-same-vendor-class-values/6572

We want to use 2 PCI cards in the same hypervisor  with a round robin scheduling to avoid to use twice the same pci virtual function from the same VM. We have changed the pci.rb probe to "fake" the second PCI vendor as workaround.

**To Reproduce**
* Change pci.rb probe for KVM, in our case, change vendor for a specific pci device:
```
...
# vendor / device => incr value per different bus
rename = {
  '15b3' => { # Mellanox
    '1014' => '1000', # connectx4 VF
  }
}
...
```
* Execute as oneadmin `onehost sync --force`   to update the hypervisor probes 
* Execute `onehost show <hyp>`
The PCI values are not changed from the database.

The workaround is just remove the host and add it again.
* `onehost delete <hyp>`
* `onehost create <hyp>`
After this the hypervisor takes into account the pci.rb "vendor" name changes:
* `onehost show <hyp>`

> ...
> PCI DEVICES
> 
>    VM ADDR    TYPE           NAME                                              
>       5e:00.0 15b3:1013:0207 MT27700 Family [ConnectX-4]
>       5e:00.1 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:00.2 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:00.3 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:00.4 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:00.5 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:00.6 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:00.7 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       5e:01.0 15b3:1014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.0 15b3:1013:0207 MT27700 Family [ConnectX-4]
>       d8:00.1 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.2 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.3 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.4 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.5 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.6 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:00.7 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]
>       d8:01.0 15b3:2014:0207 MT27700 Family [ConnectX-4 Virtual Function]

**Expected behavior**
After the pci.rb changes the host PCI values should change running `onehost sync --force`    as oneadmin. We do not need to re-create the host again to take into account any PCI probe change.

**Details**
 - Affected Component: Scheduler, OpenNebula probes
 - Hypervisor: KVM
 - Version: 5.6.1

**Additional context**
https://forum.opennebula.org/t/how-to-request-two-different-pci-devices-with-same-vendor-class-values/6572

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
The pci devices are saved by ADDRESS so when you change the pci vendor the address does not change and the device is not updated. If you want to use your hack without deleting and creating all the hosts you can use "onedb update-body host --id <host-id>" and delete the pci device you've modified.

**Comment by alvarosimon** [comment]
@christian7007 ok, thanks a lot for the clarification!
