### ISSUE TITLE
Sunstone is not showing well security groups for ICMP6

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2580]
**Description**
Sunstone is not showing well security groups for ICMP6.

**To Reproduce**
Add a security group for ICMP6

**Expected behavior**
The protocol should be set to ICMP6 and is empty.

**Details**
 - Affected Component: Sunstone

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by joseangelgm** [comment]
PR ONE: https://github.com/OpenNebula/one/pull/2653
