### ISSUE TITLE
VNC usability

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2583]
**Description**
On the right column in VM tab, we can open VNC sessions.
I would suggest multiple things, I put them into one issue since I have no idea which are possible.
All of that feels plain "omg why" at the moment.

1. They open in a new tab, always, when clicked
2. They present a (60s-ish old) screenshot on mouseover (useful especially since now console blanking seems to be in some context scripts)
3. That _AT LEAST_ hard reset is added to the full screen view, not just the ctrl-alt-del
4. That ctrl-alt-del is no longer a plain html button that can be easily triggered by mistake with a little of tab (to select) and space (to press)
5. That all VM actions that equal what a VM itself are available there (so, power on / off, reset / hard reset) are added here
6. <bonus such a crazy idea but why doesn't anyone do it>. Solve the keymapping nightmares by being able to select the virtual keyboard language that is passed on to noVNC.
(I assume that just doesn't work, but wanted to suggest it in case)
7. mounting and unmounting CD's. I know this is really complicated. and yet, it would be beautiful thing.
8. be able to see the VNC resolution, and oh wait
9. auto-scaling and resizing, since it is a horror at the moment
10. see the VM log in the lower bottom part of the viewer.
11. choosing the currently selected boot device (I would hope that isn't an unsolved mystery how to do)

**Use case**
I would use this daily and be very happy.

**Interface Changes**
Extend Sunstone VNC bits to be a bit more "stable" and "solid" and "complete"

**Additional Context**
It's a standard feature set available anywhere. It should be available "as well as possible", knowing there are HV & Cloud dependant constraints.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FlorianHeigl** [comment]
Ah. And selecting the _currently_ chosen boot device. Really.

**Comment by tinova** [comment]
Some of them are covered by the noVNC update already. Valuable insights in other, keeping this in the backlog.

**Comment by tinova** [comment]
will be addressed in #5766
