### ISSUE TITLE
OneFlow / onegate detail

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2584]
**Description**
First, oneflow only gives reasonably useful info using the --json flag.
Even without that, it should at least return the name of the service we're in.
Second, more problematic, it shows the instantiated name of the running service, but the ID of the template. We can't assume that a VM / onegate will have access to ONE, so the service template ID is not information that can be processed. We need the name instead.

**Use case**
I'd like to be able to change system behaviour based on the template + instance name we use.
i.e., in a very basic example, behave differently if we're called "prod" vs. "prod-standby"

**Interface Changes**
Modification/Extension of data returned by onegate.

**Additional Context**
There's no workarounds to use here, as far as I grasp it.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Service name is now included and can be queried through onegate

```oneflow list      
  ID USER     GROUP    NAME                                                   STARTTIME STAT            
   3 oneadmin oneadmin teeest                                            03/10 15:35:22 RUNNING         
   1 oneadmin oneadmin service-test                                      03/10 15:24:24 FAILED_DEPLOYING
oneflow-template list
  ID USER     GROUP    NAME                                                                      REGTIME
   0 oneadmin oneadmin service-test                                                       03/10 15:24:15
#Inside the VM
localhost:~# onegate service show --json
{
  "SERVICE": {
    "name": "teeest",
    "id": "3",
    "state": 2,
    "roles": [
      {
        "name": "master",
        "cardinality": 1,
        "state": 2,
        "nodes": [
          {
            "deploy_id": 2,
            "running": null,
            "vm_info": {
              "VM": {
                "ID": "2",
                "UID": "0",
                "GID": "0",
                "UNAME": "oneadmin",
                "GNAME": "oneadmin",
                "NAME": "master_0_(service_3)"
              }
            }
          }
        ]
      }
    ]
  }
}```
