### ISSUE TITLE
SHUTDOWN should not disable SHUTDOWN_HARD

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2586]
**Description**
The most annoying issue of opennebula.

**To Reproduce**
Regarding:

- Shutdown
- Power Off
- Reset

Try to shut down a VM. Find out it won't shut down.
Now sit and wait a few minutes so you can force shutdown it.
Optionally, be educated that you want to do something invalid,
while in reality SW failed.
Also applies to trying a hard reset if a VM didn't boot off i.e. PXE.

**Expected behavior**
More intrusive "power actions" are not blocked by lighter ones.
I can pull the power cable on a server if it hangs during shut down.
There's nothing that will first block me from doing that and suddenly, without notice it will allow it.

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
We'll tackle this tentatively in the following stable release.

Meanwhile please note that you can issue a recover --failure in order to perform a hard shutdown.

**Comment by rsmontero** [comment]
Fix in master, it allows to shutdown --hard a previously shutdown VM (same for undeploy...)
