### ISSUE TITLE
Context ISO attachment vs. KVM hw models

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2587]
**Description**
If you select a Q35 chipset in Sunstone, ONE will still put a "HDA" type context iso.
KVM will then 'inform you' that you don't got a IDE controller in your VM and not boot.
In other words, ONE, simply by using sunstone, lets the generate an invalid config.

**To Reproduce**
Select the HW model and contextualization

**Expected behavior**
ONE automatically decides it needs to attach a SATA virtual CDROM instead of IDE.
It also calculates the device offset correctly, so that the context iso is put _behind_ any other virtual ISO/cdrom/dvd drive, as to not block booting.

**Details**
 - Affected Component: no idea
 - Hypervisor: KVM
 - Version: 5.4??

**Additional context**
For this issue I got no idea if it's maybe already fixed in upstream :-)
But I'm really glad I thought of opening this, it's very very odd design-wise.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by wusel42** [comment]
Is there a way to fix/modify the generated deployment file? As it stands, q35 cannot be used with ONe.

**Comment by FlorianHeigl** [comment]
I would also love to know since this is involved in an issue that forces a customer to run with a config that lets the VMs die. Tsssssssss.

**Comment by wusel42** [comment]
FTR, @FlorianHeigl, this works for me (both for pc- and q35-type VMs):

```
root@host04:~# diff -u /var/tmp/one/vmm/kvm/deploy.bak /var/tmp/one/vmm/kvm/deploy
--- /var/tmp/one/vmm/kvm/deploy.bak	2017-01-04 17:58:12.000000000 +0100
+++ /var/tmp/one/vmm/kvm/deploy	2019-02-22 17:09:41.838546050 +0100
@@ -22,7 +22,7 @@
 domain=$1
 
 mkdir -p `dirname $domain`
-cat > $domain
+sed -e "s%<target dev='hda'/>%<target dev='hda' bus='sata'/>%" > $domain
 
 data=`virsh --connect $LIBVIRT_URI create $domain`
 
```

It's an ugly hack that replaces the first `<target dev='hda'/>` with `<target dev='hda' bus='sata'/>` at deployment time, which over here just works (context-image becomes `/dev/sr0`). If you actually use VMs with IDE disks, **this hack might break your VMs** — you have been warned ;)

**Comment by rsmontero** [comment]
You can set the TARGET & DEV_PREFIX in the [context section](http://docs.opennebula.org/5.8/operation/references/template.html#context-section)

However this currently let's libvirt to select the actual bus. You can try to add:

```
CONTEXT = [ DEV_PREFIX = "sd" .... ] 
```

But this probably will pick SCSI and not SATA.

This issue is to:
* Be able to set SATA disks, probably we can still use DEV_PREFIX="sata" and handle internally the BUS attribute
* Add missing DEV_PREFIX in context

**Comment by lgrawet** [comment]
Hi,

Yes it picks SCSI instead of SATA. This is an 'issue' with windows machines which require virtio-scsi driver to be installed.

Also Q35 is the default machine type in RHEL8 so you won't be able to boot new VMs without a custom template.

Thanks,

Laurent

**Comment by FlorianHeigl** [comment]
This really needs to work automatically from start to end. 
Choosing the machine model MUST set the correct bus for the context. 
Enabling the context iso MUST correctly deal with drive slots so we don't get overlapping sda/hda/vda scenarios
Disk order SHOULD also be correct such that an OS ISO is always located in a lower slot than the context ISO.
Everything SHOULD be adjusted to default to Q35 instead of  defaulting to an architecture that is now over 20 years old and in following causes all these problems.

**Comment by xorel** [comment]
PRs:
* one https://github.com/OpenNebula/one/pull/3700
* docs https://github.com/OpenNebula/docs/pull/757

**Comment by FlorianHeigl** [comment]
@rsmontero @xorel thank you. You have no idea how much this will improve life for users.
