### ISSUE TITLE
Sunstone's support page fails loading with 401 Unauthorized

### ISSUE THREAD

**Issue by tsarajar** [OpenNebula/one#2588]
**Description**
Right after a fresh install of openNebula 5.6.1 you open the webpage which sunstone represents. Log in and inspect the console output when the dashboard appears. It will say
<quote>
GET http://xxx.xxx.xxx.xxx/support/request?timeout=false&pool_filter=-2&csrftoken=d90f4863eed9dcaf27b4f3fa0e87e306 401 (Unauthorized)
</quote>

**To Reproduce**
Just install opennebula 5.6.1 and look at the webpage sunstone provides.

**Expected behavior**
Error's shouldn't appear in the console output.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: None so far.
 - Version: 5.6.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment]
Hello, this is only a console error to say you that your support credentials not exists or are wrong.
