### ISSUE TITLE
OneFlow variables access from templates

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2591]
**Description**
It would be very helpful if one could refer to OneFlow variables from the templates itself.

**Use case**
I'm pointing at a git repo depending on the name of the service that was behind instantiating the VM. Right now I need to script a lot to access that, I think it could be a lot easier to just reference a variable :)
It would also allow for more flexible hostname definitions.

**Interface Changes**
Need to introduce variables, and define how they behave if not set (when instantiated outside of a service)

**Additional Context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FlorianHeigl** [comment]
*nag*

**Comment by tinova** [comment]
relevant

**Comment by baby-gnu** [comment]
Hello.

As a work around, I personally use the `onegate`:

```
# onegate vm show --json | jq .VM.USER_TEMPLATE.ROLE_NAME
"master"
# onegate service show --json | jq .SERVICE.name
"Kubernetes 1.21 - KVM"
```

But this requires to have a working OneGate reachable from within the VM which may not always be possible.

Regards.

**Comment by al3xhh** [comment]
We have recently implemented a method to reference parent's attributes from the children, as follows:

```
${PARENT_NAME.XPATH}
```

So, you can use this to reference all the attributes that the VM has. For more information, please check [this](https://github.com/OpenNebula/one/issues/1176).

I think this covers this use case, we are going to close for now, if the use case is not covered, we can open again and rethink.

THANKS a lot for opening these feature requests :heart: :rocket:
