### ISSUE TITLE
VM can utilize more CPU than allocated

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2602]
**Description**
There is some problem with resources allocation for VM, 
If you will load CPU high, it can utilize more resources than alloceted for it:
![image](https://user-images.githubusercontent.com/7556217/48495319-06812000-e830-11e8-8a2d-c0bc0ccf5cd7.png)

**To Reproduce**
* Create new template.
* Put forkbomb into starting script:
```
:(){ :|:& };:
```
* Instantiate VM

**Expected behavior**
VM can't use resources more than allocated

**Details**
 - Affected Component: Libvirt
 - Hypervisor: KVM
 - Version: 5.6.1

Libvirt versions:
- `libvirtd (libvirt) 4.6.0` (compiled and installed on ubuntu xenial and bionic)
- `libvirt.x86_64 3.9.0-14.el7_5.8` (another guy with same problem)

**Additional context**
If I run `systemd-cgtop`, I see nothing on CPU column for VM
```
Control Group                        Tasks   %CPU   Memory  Input/s Output/s
/machine/qemu-12-one-1234.libvirt-qemu  -      -   353.3M        -        -
```
But parent cgroup shows some values
```
Control Group                        Tasks   %CPU   Memory  Input/s Output/s
/system.slice/libvirtd.service        225  387.3    34.7G        -        -
```
Zabbix shows something weird:
![image](https://user-images.githubusercontent.com/7556217/48497569-ae98e800-e834-11e8-8112-b7ac430ab14d.png)

I think it can be connected with software interruptions.

Any ideas?

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Madko** [comment]
As far as I know, OpenNebula just pass the cpu value to the cpu shares in cgroup. So it's just a weight to give a higher priority to specific VM. It's not a way to enforce CPU limitation. cf https://docs.opennebula.org/5.6/deployment/open_cloud_host_setup/kvm_driver.html?highlight=cgroup#working-with-cgroups-optional

**Comment by tinova** [comment]
closing, CPU is for allocation, vCPU applies to guestOS perception.

**Comment by zed** [comment]
The docs suggest that CPU may affect how much CPU is available at runtime (i.e., it is not just for allocation) https://docs.opennebula.io/5.10/deployment/open_cloud_host_setup/kvm_driver.html?highlight=vcpu#working-with-cgroups-optional
