### ISSUE TITLE
KVM NICs can only be of type bridge

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#2604]
**Description**
All network drivers either generate or require a BRIDGE name. This prevents the use of interfaces of type ethernet. 

**To Reproduce**
No network driver let BRIDGE to be empty

**Expected behavior**
Ethernet interfaces types should be supported

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: >= 5.4.x (probably earlier versions also)

**Additional context**

Relevant code section:

https://github.com/OpenNebula/one/blob/master/src/vmm/LibVirtDriverKVM.cc#L1052

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by nikentic** [comment]
This went very fast. Very pleased, thank you!
