### ISSUE TITLE
oneimage show / list

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2605]
**Description**
Be able to look up images by PATH/SOURCE

**Use case**
How are you going to use this new feature? Why do you need it? 
I want to look up if a running VM was instantiated-as-persistent from the right base image.

**Interface Changes**
Should either be queryable or be visible somehow.
Since there could be tree-like structures, one might need more than this simple thing I propose.
but I would prefer the simple over nothing.

**Additional Context**

```
:~# oneimage show 89
IMAGE 89 INFORMATION                                                            
ID             : 89                  
NAME           : gitlab.int.deepthink.ag-disk-0
USER           : tze                 
GROUP          : oneadmin            
DATASTORE      : default             
TYPE           : OS                  
REGISTER TIME  : 11/05 21:16:09      
PERSISTENT     : Yes                 
SOURCE         : /var/lib/one//datastores/1/5e54a219d9a0fcf223968a8b911cf3fb
PATH           : /var/lib/one//datastores/1/d2cffb4397f9d57dee8d076352eabad7
FSTYPE         : raw                 
SIZE           : 50G                 
STATE          : used                
RUNNING_VMS    : 1                   
```

So in this case, I'd expect to be able to see:

```
SOURCE         : /var/lib/one//datastores/1/5e54a219d9a0fcf223968a8b911cf3fb 
PATH           : /var/lib/one//datastores/1/d2cffb4397f9d57dee8d076352eabad7 [ image ID: 25 ]
```

Not to mention that the naming "source and path" is absolutely horrible and outside of the TM driver devs noone is safe from mixing up the two, especially since SOURCE *is in fact* a (filesystem) path, too.

It's hurts as many times as you use it.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Hi @FlorianHeigl, you can use xmlstarlet as workaround:
```
# oneimage list -x | xmlstarlet sel -t -m IMAGE_POOL/IMAGE -v ID -o " " -v SOURCE -n
```

**Comment by FlorianHeigl** [comment]
can we have some feedback if there'll always just be the workaround or if it is something that could be added without going against ONE's cli design.

**Comment by rsmontero** [comment]
Currently, except vmpool all filtering is performed client side, I'd say yes this is a design decision. VM pool uses DB support (Full text search) to reduce the bandwidth demanded by a potentially huge pool.

So I'd say that the current approach for small pools is list + client side parsing. Note that the oneimage and the rest of the cli commands includes some native filter options

```
 -f, --filter x,y,z        Filter data. An array is specified with
                               column=value pairs.
-l, --list x,y,z          Selects columns to display with list command
```

I'm aware that not all the possible values of every object can be filterd out, so a proposal like the one of @kvaps or simply (--csv + grep) is recommended.

Note that server side filtering will also increase the FTS search indexes.

**Comment by rsmontero** [comment]
Agree that PATH vs SOURCE could be misleading (note that PATH is the original FS path used to register the image) and SOURCE the actual datastore reference for the image. SOURCE in general is not a FS path as can be a rbd volume reference or a device name (agree that usually all of them are written in path form) but just to give you some context....
