### ISSUE TITLE
No way to use Floating IP with BRIDGE interfaces

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2607]
**Description**
There is still issues with Floating IP, no way to use it with bridged networks as non privileged user.

**To Reproduce**
Steps to reproduce the behavior.

Make sure that you have this option on your `oned.conf`:
```
VM_RESTRICTED_ATTR = "NIC/BRIDGE"
```
Create network with BRIDGE attribute

Login as user without admin rights

Create new Virtual Router

Attach NIC to Virtual Router (Mark Floating IP checkbox)

You will see how new NIC appears, but you will get this message:
```
[one.vrouter.attachnic] NIC includes a restricted attribute BRIDGE
```
Ok, try to remove this adapter, no, another error:

```
[one.vrouter.detachnic] Could not detach NIC with NIC_ID 0, it does not exist.
```

You should remove whole VR then

**Expected behavior**
Working Floating IP

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: `5.6.0`

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
@juanmont can you assign labels for this bug please?

**Comment by al3xhh** [comment]
Hi @kvaps, I follow your steps to reproduce the issue, but I was able to add the nic, here you have the output of the log and the rest of the commands. Could you give me more information about the issue, to try to reproduce it?

Thu Nov 29 11:31:26 2018 [Z0][ReM][D]: Req:7520 UID:2 one.vrouter.attachnic result SUCCESS, 0
Thu Nov 29 11:31:26 2018 [Z0][ReM][D]: Req:7584 UID:2 one.vrouter.info invoked , 0
Thu Nov 29 11:31:26 2018 [Z0][ReM][D]: Req:7584 UID:2 one.vrouter.info result SUCCESS, "<VROUTER><ID>0</ID><..."

VM NICS                                                                         
 ID NETWORK              BRIDGE       IP                                          MAC                       PCI_ID  
  0  testing_net               virbr0           192.168.122.3                       02:00:c0:a8:7a:03
                                                           192.168.122.2 (VRouter)

$ oneuser show testing_user
USER 2 INFORMATION                                                              
ID                            : 2                   
NAME                     : testing_user       
GROUP                  : users               
PASSWORD          : 975840c5f7301446b158a4b3d1444cc855995f7e
AUTH_DRIVER      : core                
ENABLED               : Yes
