### ISSUE TITLE
save as template doesn't take into account iso cd

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2610]
**Description**

save as template feature does not take into account iso cds of the vm. This can lead into many problems due to cds are RO so you do not need to create a new cd.

**To Reproduce**
Steps to reproduce the behavior.
run a machine with a cd connected, make save as template operation.

**Expected behavior**

template disk remains the same in the new template (pointing to the original cd).

**Details**
 - Affected Component: OCA
 - Hypervisor: any
 - Version: development

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
try to add this to save_as test
