### ISSUE TITLE
Can't remove resources from VDC

### ISSUE THREAD

**Issue by AdriMenendezM** [OpenNebula/one#2623]
**Description**
Can't remove resources from VDCs by clicking on the labels.

**To Reproduce**
Go to VDCs.
Click on Update.
On any resources' tab, try to remove the element by clicking on the times sign of the label.

**Expected behavior**
Resource is removed from the VDC.

**Details**
 - Affected Component: Sunstone
 - Version: 5.6.2

**Additional context**
The main problem is if you have removed resources from your infrastructure while they are on a VDC. As they don't appear on the resources table, you can't remove them.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR's to approve:
-ONE: https://github.com/OpenNebula/one/pull/3789
-Docs: https://github.com/OpenNebula/docs/pull/785

**Comment by tinova** [comment]
Needs testing

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- Test: https://github.com/OpenNebula/development/pull/767
