### ISSUE TITLE
dropdown menus on VM info page are mostly unusable because of page refresh

### ISSUE THREAD

**Issue by Madko** [OpenNebula/one#2627]
**Description**
When you want to select a new owner or group on a VM, from the info page, the select menu works as usual, the dropdown list is displayed. Then you scroll the list of your hundreds of users, looking for the right one, but you have 5s to do so, because the page refresh will reset the dropdown list. 

**To Reproduce**
- Have a log of users (but that's not mandatory)
- Go to any VM
- click on the owner, dropdown list is displayed
- wait
- see the dropdown list disappears when the page is refreshed

**Expected behavior**
Do not refresh info page

**Details**
 - sunstone 5.6.2

**Additional context**
It was working fine before 5.6.2.
Is there a way to disable auto refresh ? Because it also prevents us to read the log.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Madko** [comment]
In fact all the buttons are impacted (poweroff, migrate, recover etc)

**Comment by atodorov-storpool** [comment]
> Is there a way to disable auto refresh ? Because it also prevents us to read the log.

https://docs.opennebula.org/5.6/deployment/sunstone_setup/suns_views.html#autorefresh

Even if not possible to disable, setting to relatively high value should reduce the issue.

**Comment by Madko** [comment]
Thanks Anton, I've set the value to 50s and it's more usuable. Sorry I should have read the doc...
Since this workaround is quite ok, I let you decide what to do with this ticket. I'm ok if you close it.

**Comment by juanmont** [comment]
We have received many people with this problem, we have decided to reverse these commits.
