### ISSUE TITLE
Clear VM DEPLOY ID attribute 

### ISSUE THREAD

**Issue by slntopp** [OpenNebula/one#2641]
**Description**
Hi, i'm trying to develop "reinstall" algorithm, so one of the way, is delete-recreate vm and deploy it once again. But deploy id not deletes even if i do vm.undeploy, and this causes an error, when trying to deploy vm,

How to clear this attribute?
Or is any other way to recreate vm with the same IP-lease exists?

**Details**
 - Affected Component: Core or vCenter Driver
 - Hypervisor: VMWare vCenter
 - Version: 5.4

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Can you provide information on the error you are getting?

**Comment by rsmontero** [comment]
OK, So this may be an issue that IDs cannot be reused in vCenter

**Comment by slntopp** [comment]
Maybe, but I think that logic of deploy id is to be unique for every deployment, so if you delete resource and create the same but new, deploy id should be another at the any hypervisor or cloud. So delete-recreate action should clear this attribute.
Solution maybe to force make deploy id empty on any **create** action(vm.create, vm.recover(delete-recreate) etc.).

**Comment by rsmontero** [comment]
OK, we are going to take a look at the deploy phase, as this deploy-id, is overwritten on every deploy. Maybe this is somehow interfering in the deploy logic that should not be using any existing deploy ID... Thanks

**Comment by slntopp** [comment]
If i'm not mistaken, drivers resuming VMs using deploy action(i mean script at ~oneadmin/remotes/vmm/%driver_name%/deploy), so it could be hard to not to use existing deploy id, cause it is the main search key at many drivers.
I hope you'll make a right decision, good luck and thanks for ONe

**Comment by tinova** [comment]
* Need test vCenter delete -- recreate
* Core needs to clear DEPLOY_ID attribute
