### ISSUE TITLE
ons-vsctl missing

### ISSUE THREAD

**Issue by fgc92** [OpenNebula/one#2669]
On a fresh installation of CentOS 7.5.1804, with a fresh installation of OpenNebula 5.6.1, and using ovswitch, the binary ovs-vsctl is missing.

Also, if ons-vsctl was present, there is no one admin in the /etc/sudoers file, therefore it won't allow oneadmin to run this command. 

Must add:
%oneadmin ALL=(root) NOPASSWD: /usr/bin/ovs-vsctl 
%oneadmin ALL=(root) NOPASSWD: /usr/bin/ovs-ofctl

**Comment by Madko** [comment]
Very strange.
How did you install openvswitch ? Since ovs is not mandatory for OpenNebula, you have to install it yourself I guess. Easiest way is to use openvswitch package from centos-release-openstack-* repo.

The sudo is in /etc/sudoers.d/opennebula
here is mine on a fresh centos 7 installation:
```
Defaults:oneadmin !requiretty
Defaults:oneadmin secure_path = /sbin:/bin:/usr/sbin:/usr/bin

Cmnd_Alias ONE_MISC = /sbin/mkfs, /bin/sync, /sbin/mkswap
Cmnd_Alias ONE_NET = /usr/sbin/brctl, /sbin/ebtables, /sbin/iptables, /sbin/ip6tables, /sbin/ip, /usr/sbin/ipset, /usr/sbin/arping
Cmnd_Alias ONE_LVM = /sbin/lvcreate, /sbin/lvremove, /sbin/lvs, /sbin/vgdisplay, /sbin/lvchange, /sbin/lvscan, /sbin/lvextend
Cmnd_Alias ONE_ISCSI = /sbin/iscsiadm, /usr/sbin/tgt-admin, /usr/sbin/tgtadm
Cmnd_Alias ONE_OVS = /usr/bin/ovs-ofctl, /usr/bin/ovs-vsctl
Cmnd_Alias ONE_XEN = /usr/sbin/xentop, /usr/sbin/xl, /usr/sbin/xm
Cmnd_Alias ONE_CEPH = /usr/bin/rbd
Cmnd_Alias ONE_HA = /usr/bin/systemctl start opennebula-flow, /usr/bin/systemctl stop opennebula-flow, /usr/bin/systemctl start opennebula-gate, /usr/bin/systemctl stop opennebula-gate, /usr/sbin/service opennebula-flow start, /usr/sbin/service opennebula-flow stop, /usr/sbin/service opennebula-gate start, /usr/sbin/service opennebula-gate stop

oneadmin ALL=(ALL) NOPASSWD: ONE_MISC, ONE_NET, ONE_LVM, ONE_ISCSI, ONE_OVS, ONE_XEN, ONE_CEPH, ONE_HA
```

```
# rpm -qf /etc/sudoers.d/opennebula
opennebula-common-5.6.1-1.noarch
```

I hope this will help.

Best regards,
Edouard

**Comment by fgc92** [comment]
I did not install it al all. I thought it would come with the package since ovSwitch is available.
There should be a mention somewhere that ovSwitch needs to be installed if this type of setting is going to be used. Since the documentation explains how to use it, one would assume that it is part of OpenNebula.
