### ISSUE TITLE
vCenter snapshots and tm_mad

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2672]
**Description**

vCenter driver is not working like always when snapshots are used.

We need to make a solution when Vms are using snapshots and vCenter (tm_mad related: persistency, templates, terminate ...)

**To Reproduce**

Import a template, instantiate, make snapshots, terminate
import a template, instantiate as persistent, make snapshots, terminate...
import template, instantiate, add managed disk, make snapshot, detach managed disk
....

**Details**
 - Affected Component: TM_MAD vCenter
 - Hypervisor: vCenter
 - Version: development

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
add to 5.8 known issues
