### ISSUE TITLE
DB Replication for HA

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#2673]
**Description**
Heavy load clouds may require a great number of replication records. This replication is performed through the API server that may impose additional load on leader/followers. Also there are some sites that use a HA/high-performance DB cluster that is not currently used by OpenNebula HA implementation.

**Use case**
Apart from leverage HA SQL clusters this will allow an easier vertical scalability of OpenNebula:
 +----------------------+
 | API Clients / Server |
 | (or balancer)        |
 +----------------------+
     |
     +----------------------------+
     |             |              |
  +--------+  +----v-----+  +-----v----+
  | oned   |  | oned     |  | oned     |
  | leader |  | follower |  | follower |
  +--------+  +----^-----+  +----^-----+
     |             |             |
     |             |             |
 +---v---------------------------------+
 | DB cluster (HA/replicated)          |
 +-------------------------------------+

**Interface Changes**
oned.conf: include a new attribute to select the replication mode:

                                                                                     
RAFT = [
    REPLICATION_MODE     = < DB | ONE >                                                                              
    LIMIT_PURGE          = 100000,                                                    
    LOG_RETENTION        = 500000,                                                    
    LOG_PURGE_TIMEOUT    = 600,                                                       
    ELECTION_TIMEOUT_MS  = 2500,                                                      
    BROADCAST_TIMEOUT_MS = 500,                                                       
    XMLRPC_TIMEOUT_MS    = 450                                                        
] 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
After working on some prototypes we are abandoning this feature. There is no performance gain (in terms of decreasing write latency) by moving the replication to the DB core. In order to prevent any split brain condition followers needs to ACK the state changes, so the leader <-> follower communication needed to make RAFT work makes the proposed approach redundant.
