### ISSUE TITLE
Sunstone - Accounting blanck values

### ISSUE THREAD

**Issue by jaypif** [OpenNebula/one#2681]
**Description**
On Sunctone, the Accounting page returns nothing while the CLI give feedback.
On the browser console I have a JS error. This might me linked.

**To Reproduce**
Go on Sunstone with a user in "oneadmin" group.
Then go on Settings and Accounting tab. Select date range with values you are sure you have VMs and click on the button "Get Accounting".
There is nothing.
On browser console I have:
```
TypeError: aoColumns[srcCol] is undefined main.js:25053:4
_fnSortFlatten
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:25053:4
_fnSortingClasses
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:25391:14
DataTable/<
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:20444:4
each
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:798:10
each
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:570:10
DataTable
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:20068:3
_fillAccounting
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:53864:40
success
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:53500:11
success
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:35431:29
fire
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:3620:11
fireWith
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:3750:7
done
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:9218:5
callback/<
https://ig1-onepoc-00-front-01.sadm.ig-1.net/dist/main.js:9584:9
```
Connect in SSH to the front and play with `oneacct`, it returns results

**Expected behavior**
On susntone, I expect to have all accounting actions for the range selected.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.6.0

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This issue cannot be replicated, closing until more feedback is provided.
