### ISSUE TITLE
CLI tools should report error into stderr and have user friendly outputs

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2689]
**Description**
For now if there is some error it is reported to stdout. This is wrong it should be reported to stderr.

**Use case**
Better for scripting and for errors handling

**Interface Changes**
Need to update next CLI commands:

```
oneacct
oneacl
onecluster
onedatastore
onedb
oneflow
oneflow-template
onegroup
onehost
oneimage
onemarket
onemarketapp
onesecgroup
oneshowback
onetemplate
oneuser
onevcenter
onevdc
onevm
onevmgroup
onevnet
onevrouter
onezone
```

**Additional Context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Extending request also to review and limit the content of error outputs, esp. **eliminate Ruby stack traces** on places we can handle safely. E.g.,

```
$ oneuser list
ONE_AUTH file not present
```

but

```
$ onevm list
Traceback (most recent call last):
	10: from /home/holer/bin/onevm:23:in `<main>'
	 9: from /home/holer/bin/onevm:23:in `load'
	 8: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/bin/onevm:39:in `<top (required)>'
	 7: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/bin/onevm:39:in `new'
	 6: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/lib/command_parser.rb:84:in `initialize'
	 5: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/lib/command_parser.rb:466:in `run'
	 4: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/bin/onevm:46:in `block (2 levels) in <top (required)>'
	 3: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/lib/one_helper.rb:512:in `set_client'
	 2: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/lib/one_helper.rb:454:in `get_client'
	 1: from /home/holer/.gem/ruby/gems/opennebula-cli-5.10.1/lib/one_helper.rb:454:in `new'
/home/holer/.gem/ruby/gems/opennebula-5.10.1/lib/opennebula/client.rb:134:in `initialize': ONE_AUTH file not present (RuntimeError)
```

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4294
- docs: https://github.com/OpenNebula/docs/pull/975
