### ISSUE TITLE
Reduce amount of decimal places for cost per month on templates 

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#2692]
**Description**
On Sunstone, when defining costs on a template, it shows too many decimal places when calculating cost per month if result is not exact.

![deepinscreenshot_select-area_20181206165330](https://user-images.githubusercontent.com/13242848/49617068-b0a81f80-f978-11e8-9b85-e0f7f6b1b272.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Fixed
