### ISSUE TITLE
onevcenter list -o datastores doesn't show the full REF

### ISSUE THREAD

**Issue by fm4991** [OpenNebula/one#2703]
**Description**
In a big vCenter environment, where you have large MOB IDs (6 digits and above) for the datastores the OpenNebula CLI cuts after the 5 digit. For example datastore-12345 is shown but the actual REF is datastore-123456.

**To Reproduce**
You need a vCenter where the datastore REF IDs are more than 5 digits long. Execute the following command as oneadmin: `onevcenter list -o datastores -h X` 

**Expected behavior**
The whole REF ID should be shown no matter which length.

**Details**
 - Affected Component: CLI
 - Hypervisor: vCenter
 - Version: 5.6.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PR to merge in 5.12 in master:

- [code](https://github.com/OpenNebula/one-ee/pull/21)

PR to merge in 5.12:

- [docs](https://github.com/OpenNebula/docs/pull/1210)
