### ISSUE TITLE
Update Virtual Network Context Wizard is not working

### ISSUE THREAD

**Issue by fm4991** [OpenNebula/one#2711]
**Description**
It's not possible to update the context of a virtual network within the wizard.

**To Reproduce**
1.  Open a virtual network
2.  Press the blue "Update" button
3.  Click on the "Context" button
4.  Fill one or more of the predefined fields like netmask, dns and gateway
5.  Click on the green "Update" button
--> You will get the error message "One or more required fields are missing or malformed."

**Expected behavior**
There shouldn't be an error message and the changed fiels should be updateable like in the "Advanced" Section.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: VMware vSphere
 - Version: 5.6.1

**Additional context**
[logs.zip](https://github.com/OpenNebula/one/files/2671114/logs.zip)
[screencapture.zip](https://github.com/OpenNebula/one/files/2671117/screencapture.zip)
![screenshot](https://user-images.githubusercontent.com/45791688/49858652-d0669a00-fdf5-11e8-83b8-48fb7e3025e5.png)

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Thanks for the description. Can you also paste the full VM XML output to reproduce the problem?

**Comment by fm4991** [comment]
@tinova since it is only the virtual network context there is no VM XML if am right... What i found out is that the problem seems to occur only with vmware networks

**Comment by tinova** [comment]
@fm4991 yes of course, you are right. Please send over the full VNET XML.

**Comment by fm4991** [comment]
<VNET>
  <ID>5</ID>
  <UID>0</UID>
  <GID>0</GID>
  <UNAME>oneadmin</UNAME>
  <GNAME>oneadmin</GNAME>
  <NAME>vm-network-86</NAME>
  <PERMISSIONS>
    <OWNER_U>1</OWNER_U>
    <OWNER_M>1</OWNER_M>
    <OWNER_A>0</OWNER_A>
    <GROUP_U>0</GROUP_U>
    <GROUP_M>0</GROUP_M>
    <GROUP_A>0</GROUP_A>
    <OTHER_U>0</OTHER_U>
    <OTHER_M>0</OTHER_M>
    <OTHER_A>0</OTHER_A>
  </PERMISSIONS>
  <CLUSTERS>
    <ID>104</ID>
  </CLUSTERS>
  <BRIDGE><![CDATA[vm-network-86]]></BRIDGE>
  <PARENT_NETWORK_ID/>
  <VN_MAD><![CDATA[vcenter]]></VN_MAD>
  <PHYDEV/>
  <VLAN_ID/>
  <OUTER_VLAN_ID/>
  <VLAN_ID_AUTOMATIC>0</VLAN_ID_AUTOMATIC>
  <OUTER_VLAN_ID_AUTOMATIC>0</OUTER_VLAN_ID_AUTOMATIC>
  <USED_LEASES>1</USED_LEASES>
  <VROUTERS/>
  <TEMPLATE>
    <BRIDGE><![CDATA[vm-network-86]]></BRIDGE>
    <OPENNEBULA_MANAGED><![CDATA[NO]]></OPENNEBULA_MANAGED>
    <PHYDEV><![CDATA[]]></PHYDEV>
    <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
    <VCENTER_INSTANCE_ID><![CDATA[c504e36f-b609-40f9-9fb6-3ba92b98c107]]></VCENTER_INSTANCE_ID>
    <VCENTER_NET_REF><![CDATA[network-856]]></VCENTER_NET_REF>
    <VCENTER_PORTGROUP_TYPE><![CDATA[Port Group]]></VCENTER_PORTGROUP_TYPE>
    <VCENTER_VLAN_ID><![CDATA[86]]></VCENTER_VLAN_ID>
    <VN_MAD><![CDATA[vcenter]]></VN_MAD>
  </TEMPLATE>
  <AR_POOL>
    <AR>
      <AR_ID><![CDATA[0]]></AR_ID>
      <MAC><![CDATA[02:00:5e:ae:1b:9d]]></MAC>
      <SIZE><![CDATA[255]]></SIZE>
      <TYPE><![CDATA[ETHER]]></TYPE>
      <MAC_END><![CDATA[02:00:5e:ae:1c:9b]]></MAC_END>
      <USED_LEASES>0</USED_LEASES>
      <LEASES/>
    </AR>
    <AR>
      <AR_ID><![CDATA[1]]></AR_ID>
      <MAC><![CDATA[00:50:56:8e:15:03]]></MAC>
      <SIZE><![CDATA[1]]></SIZE>
      <TYPE><![CDATA[ETHER]]></TYPE>
      <MAC_END><![CDATA[00:50:56:8e:15:03]]></MAC_END>
      <USED_LEASES>0</USED_LEASES>
      <LEASES/>
    </AR>
    <AR>
      <AR_ID><![CDATA[2]]></AR_ID>
      <IP><![CDATA[172.24.86.55]]></IP>
      <MAC><![CDATA[02:00:ac:18:56:37]]></MAC>
      <SIZE><![CDATA[5]]></SIZE>
      <TYPE><![CDATA[IP4]]></TYPE>
      <MAC_END><![CDATA[02:00:ac:18:56:3b]]></MAC_END>
      <IP_END><![CDATA[172.24.86.59]]></IP_END>
      <USED_LEASES>0</USED_LEASES>
      <LEASES/>
    </AR>
    <AR>
      <AR_ID><![CDATA[3]]></AR_ID>
      <IP><![CDATA[172.24.86.90]]></IP>
      <IP6><![CDATA[fe80::250:56ff:fe8e:203e]]></IP6>
      <MAC><![CDATA[00:50:56:8e:20:3e]]></MAC>
      <PREFIX_LENGTH><![CDATA[64]]></PREFIX_LENGTH>
      <SIZE><![CDATA[1]]></SIZE>
      <TYPE><![CDATA[IP4_6_STATIC]]></TYPE>
      <MAC_END><![CDATA[00:50:56:8e:20:3e]]></MAC_END>
      <IP_END><![CDATA[172.24.86.90]]></IP_END>
      <IP6_END><![CDATA[fe80::250:56ff:fe8e:203e]]></IP6_END>
      <USED_LEASES>0</USED_LEASES>
      <LEASES/>
    </AR>
    <AR>
      <AR_ID><![CDATA[4]]></AR_ID>
      <IP><![CDATA[172.24.86.105]]></IP>
      <IP6><![CDATA[fe80::250:56ff:fe8e:2b5a]]></IP6>
      <MAC><![CDATA[00:50:56:8e:2b:5a]]></MAC>
      <PREFIX_LENGTH><![CDATA[64]]></PREFIX_LENGTH>
      <SIZE><![CDATA[1]]></SIZE>
      <TYPE><![CDATA[IP4_6_STATIC]]></TYPE>
      <MAC_END><![CDATA[00:50:56:8e:2b:5a]]></MAC_END>
      <IP_END><![CDATA[172.24.86.105]]></IP_END>
      <IP6_END><![CDATA[fe80::250:56ff:fe8e:2b5a]]></IP6_END>
      <USED_LEASES>1</USED_LEASES>
      <LEASES>
        <LEASE>
          <IP><![CDATA[172.24.86.105]]></IP>
          <IP6><![CDATA[fe80::250:56ff:fe8e:2b5a]]></IP6>
          <MAC><![CDATA[00:50:56:8e:2b:5a]]></MAC>
          <VM><![CDATA[317]]></VM>
        </LEASE>
      </LEASES>
    </AR>
  </AR_POOL>
</VNET>

**Comment by jloboescalona2** [comment]
@fm4991 , apparently you have the virtual network created incorrectly, now when this happens, the form show you the error
