### ISSUE TITLE
[vCenter] fix ide disk controller

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2716]
**Description**
A clear and concise description of what the bug is

Right now vcenter driver hw controller management is asking about TYPE property of the disk xml so you can't really choose for a normal hard disk with IDE controller. 

**To Reproduce**
Steps to reproduce the behavior.

Add/attach template/vm a normal hard disk with DEV_PREFIX='ide' using vCenter driver.

**Expected behavior**

one manage properly ide controllers for hard disks in vCenter.

**Details**
 - Affected Component: VMM Drivers
 - Hypervisor: vCenter
 - Version: Development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Semedi** [comment]
reference: https://github.com/Semedi/one/commit/2ea7beda774ffff6e850c77010e8ab95175261b1

**Comment by tinova** [comment]
Needs test

**Comment by tinova** [comment]
Reverted, check live migration issues

**Comment by tinova** [comment]
addressed in #3225, closing
