### ISSUE TITLE
Evaluate guacamole HTML for VNC access

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#2755]
**Description**

Replace current VNC Sunstone integration

**Use case**

Provide better end user experience

**Interface Changes**

Change Sunstone VNC console

**Additional Context**

https://guacamole.apache.org/

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Worth looking into: https://github.com/BarrieAlmond/GuacNebula

**Comment by smangelkramer** [comment]
Just deployed this (https://github.com/BarrieAlmond/GuacNebula) very cool solution in my lab. 
The VNC, and especially the RDP connection profile is exactly what many of my customers are querying for. +1 on this!

**Comment by tinova** [comment]
Thanks for the feedback! we'll give it priority

**Comment by tinova** [comment]
Moving to backlog, guacamole agent may be too heavy on the hypervisors. Maybe we are missing something, but in our tests it pulls a tomcat?

**Comment by cloudweavers** [comment]
Yes, it requires a java application server like Tomcat or Jetty.

**Comment by tinova** [comment]
Thanks for the confirmation.

Seems like an overkill for a light VNC feature. We'll evaluate its optional inclusion. 

Meanwhile, we keep on the lookout.

**Comment by smangelkramer** [comment]
That’s true. I’m running it inside Docker Containers in my environments. But it’s not that “lightweight” as NoVNC ;-)

Perhaps as (well documented) Add-On / Extension with integration via Marketplace?

Best 
Sebastian

**Comment by BarrieAlmond** [comment]
You're right that as a VNC client it isn't exactly lightweight. I think the biggest benefit of Guacamole comes from using it for in-browser RDP connections to provide functions not available with NoVNC. Using RDP it can adjust the remote resolution to match the browser's display area, provide a form of clipboard redirection (text only, from pasting in to the ctrl-alt-shift menu), bi-directional audio redirection, print redirection, and file transfers from dragging on to the browser and downloading from a virtual drive via the ctrl-alt-shift menu.

It of course needs RDP to be enabled on the VM - easy enough with Windows, and can work with xrdp on Linux. It also needs the VM to be on an IP range contactable by the Guacamole server (could possibly be circumvented on KVM with VM port forwarding similar to what is mentioned [here](https://serverfault.com/questions/401739/remote-desktop-to-my-kvm-virtual-machine). 

All I can say is it worked a treat for the virtual lab that I put together, running it inside Docker containers. Whether this is of any benefit to a particular environment depends on their requirements. Unfortunately I've now moved on from that project so can't contribute any more.

**Comment by kvaps** [comment]
Wow @BarrieAlmond , it looks so cool!
It would be nice to containerize it and provide with [Kube-OpenNebula](Kube-OpenNebula) as ready VDI solution!

**Comment by kvaps** [comment]
> Using RDP it can adjust the remote resolution to match the browser's display area, provide a form of clipboard redirection (text only, from pasting in to the ctrl-alt-shift menu), bi-directional audio redirection, print redirection, and file transfers from dragging on to the browser and downloading from a virtual drive via the ctrl-alt-shift menu.

Nevertheless, native spice-client support can provide all of this with less changes, see https://github.com/OpenNebula/one/issues/1262

**Comment by tinova** [comment]
closing in favor of the spice approach

**Comment by tinova** [comment]
reopening and putting this on the backlog as an alternative to noVNC

**Comment by tinova** [comment]
"A deployment scenario could be: one guacamole server on the frontend and guacd proxies on each hypervisor. The guacamole server can reach each guacd proxy and each guacd proxy can reach any VM on its own hypervisor. When creating a connection, some parameter needs to be set in order to use a particular guacd proxy" by @km4cus

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/92
- docs: OpenNebula/docs/pull/1243
- dev: OpenNebula/development/pull/1137

**Comment by tinova** [comment]
superb job Sergio!
