### ISSUE TITLE
vCenter information VM attributes cannot be deleted

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2763]
**Description**

Attributes like VCENTER_ESX_HOST cannot be deleted

**To Reproduce**

Try to delete a vCenter specific attribute

**Expected behavior**

Value to be deleted

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by fborges-opennebula** [comment]
@tinova PR to be aproved:
- One: https://github.com/OpenNebula/one/pull/4455
- Docs: https://github.com/OpenNebula/docs/pull/1024
