### ISSUE TITLE
Improve ONE_PAGER documentation and functionality

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2764]
**Description**

ONE_PAGER does not work properly and is not properly documented

**Use case**

Disable pagination

**Interface Changes**

Evaluate --no-paginated flag  

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
Also, empty filtered pages display headers

**Comment by vholer** [comment]
Related issue https://github.com/OpenNebula/one/issues/2565
