### ISSUE TITLE
Cloud View network and datastore activation depends on quotas and vms

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2766]
**Description**

Is not possible to activate network and DS features without quotes

**To Reproduce**

Activate network on cloud.yml and select quotas to false 

**Expected behavior**

Network and DS to be active on cloud view

**Details**
 - Affected Component: Sunstone
 - Hypervisor: -
 - Version: 5.62, development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
Unable to replicate the error in version 5.8
