### ISSUE TITLE
datastore not marked for remote monitoring by tm/ssh/mv

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2767]
**Description**
When un-deploying a VM, when deploying VM, the `.monitor` tag is placed in BASE_PATH instead of the datastore's home.

**To Reproduce**
1. Configure OpenNebula with ssh tm_mad with two hosts
1. Create a VM and the undeploy in (look for `/var/lib/one/datastores/.monitor` file)
1. Deploy a VM on the other host (look for `/var/lib/one/datastores/.monitor` file)

**Expected behavior**
`.monitor` should be placed in `/var/lib/one/datastores/$SYSTEM_DS_ID/`

**Details**
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [5.x]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
First of all - Happy New Year!

There is another issue that I am not sure how to complete though.

When the SSH tm_mad is used in combination with addon-storage, the `tm/addon/mv` (also `ln` and `clone`) is called before the the `tm/ssh/mv`. Here are two sub-issues as follow:

issue-A. The `tm/ssh/mv` is called only on undeploy and then on resume. The tm/addon scripts create _SYSTEM_DS/VM_ folder (to place symlinks to the disks for example). But current code in [ssh_make_path](https://github.com/OpenNebula/one/blob/master/src/mad/sh/scripts_common.sh#L459) do not add the .monitor file because the SYSTEM_DS folder is already created. The following patch resolves this issue https://github.com/atodorov-storpool/one/commit/828559e5d35ed6fa365c23c532e0e1b2551cf4c6

issue-B. In addition to `tm/ssh/mv` I think that `ssh_make_path()` should be called in `tm/ssh/ln` and `tm/ssh/context` too. But they are "common" with the ceph's tm_mad. Here is my doubt - updating the common will update the ceph's SYSTEM Datastore as "remote monitored" by the `ssh` tm_mad. This is not bat after all - the "exported on local ssd" images will be monitored then. What do you think?

Also I don't think that is it good idea implementing the logic to place the `.monitor` tag in the tm/addon because there is a lot for complexity. In addon-storpool, for example, the system datastore is always "shared=yes" even when there is no real shared filesystem...

Best Regards,
Anton Todorov

**Comment by vholer** [comment]
Hello @atodorov-storpool , I have following proposal https://github.com/OpenNebula/one/compare/master...vholer:bug-2767:

- `ssh/mv`: Your fix with DST_DIR -> DST_PATH is correct, thank you!!

- issue A - I took your idea a slightly changed (you're right with double backlashes)

- issue B - I can see `ssh_make_path` is already called in `tm/ssh/ln` (with `ssh`) and `tm/ssh/context` (without monitor content)

- issue B
a) I have forced the `ceph/clone` and `clone/ln` with TM_MAD_SYSTEM=ssh to create a local monitoring lock --> this should fix the issue when local images aren't monitored
b) I have made a change in `ssh/mv` which now preserves content of `.monitor` between hosts (I'm not sure if it's necessary when a) above is now fixed)

I'll give it a little more testing before merging, your comments are very welcomed! Thank you.

**Comment by atodorov-storpool** [comment]
Hi @vholer ,

I have no remarks on the changes. Just reading them they should work :+1: 

The only case that I think is not covered is relevant to #2791 . Currently after a default installation if an user add a _shared_ IMAGE datastore the non-persistent VM disks will not be monitored, because they are copied(?!) to the SYSTEM datastore using `tm/shared/clone` but the SYSTEM datastore will not be tagged for remote monitoring... A script that could be called is `tm/ssh/context`, but if there is no contextualization enabled even this script will be omitted. Well this is totally a corner case but is possible ...

Cheers,
Anton

**Comment by vholer** [comment]
Thanks!

Let's finish for now this issue, PRs to merge:
- https://github.com/OpenNebula/one/pull/2873
- https://github.com/OpenNebula/docs/pull/480
