### ISSUE TITLE
Allow updating Image metadata while being copied/saved/imported to the Datastore

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2770]
**Description**
Images are locked while being copied to prevent leaking storage. Images cannot be deleted but metadata cannot be updated either. 

**Use case**
Update image metadata (e.g. owner, permissions, template) while the image is being saved/copied 

**Interface Changes**
None

**Additional Context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Could you add image import too? Currently as workaround I am unlocking-updating-locking the image in the driver https://github.com/OpenNebula/addon-storpool/blob/master/datastore/storpool/cp#L264

**Comment by kvaps** [comment]
Already reported it here https://github.com/OpenNebula/one/issues/2626

**Comment by rsmontero** [comment]
Images are no longer locked (i.e. add a user locked) while being "created". In order to prevent leaking storage only users with ADMIN rights are allowed to delete the image in the LOCKED state.
