### ISSUE TITLE
Show vCenter name

### ISSUE THREAD

**Issue by AdriMenendezM** [OpenNebula/one#2771]
**Description**
Brief description of the new functionality

Add VM name on vCenter to vCenter information section.

**Use case**
How are you going to use this new feature? Why do you need it? 

In order to find VMs on vCenter, you can use the ID because is present on the vCenter VM name, but if the VM is an imported one and its name has been modified, the only way to identify it is by its MoRef, which is not present on interfaces like vSphere Client

**Interface Changes**
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API  

N/A

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[DOC]
* https://github.com/OpenNebula/docs/pull/897

[TEST]
* https://github.com/OpenNebula/development/pull/815

[ONE]
* https://github.com/OpenNebula/one/pull/4084
