### ISSUE TITLE
Unify /websockify path used for vnc connections

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2781]
**Description**
In continue to https://github.com/OpenNebula/one/issues/878

Sunstone uses two different addresses for establish websocket connections with novnc.

If you call vnc console from the vm page, sunstone will call:

```
https://example.org:<port>/?token=jkkg7cdyc7...
```

Unlike, if you click ![image](https://user-images.githubusercontent.com/7556217/50742062-8e6b2100-1206-11e9-89c9-922eb84746cc.png), sunsone will call:

```
https://example.org:<port>/websockify/?token=jkkg7cdyc7...
```

**To Reproduce**
1. Configure sunstone:
   
   ```
   :vnc_proxy_port: 29876
   :vnc_client_port: 443
   :vnc_proxy_support_wss: no
   ```

2. Configure nginx reverse-proxy, use config file from https://github.com/OpenNebula/one/issues/878

3. Login to sunstone, and try to connect via vnc
   ```
   vnc server disconnected (code: 1006)
   ```
4. Click ![image](https://user-images.githubusercontent.com/7556217/50742062-8e6b2100-1206-11e9-89c9-922eb84746cc.png), and sunstone will successful establish vnc connection 

**Expected behavior**

All connections will use `/websockify` path.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.6.1

**Additional context**

I found working workaround, just specify missing path in `vnc_client_port` variable:

```
:vnc_client_port: 443/websockify
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
Many thanks @kvaps for the `:vnc_client_port: 443/websockify` trick.

It's working like a charm.

In #878, I proposed to define a new configuration option to set the URL path, based on the existing ones, maybe `vnc_client_path`? For example:

```
:vnc_client_port: 443
:vnc_client_path: /websockify
```

Regards.

**Comment by baby-gnu** [comment]
Since it's working, I figure out that I needed to tweak a little the nginx timeouts.

When you keep a fixed image (like a login screen), no packet pass and the noVNC client do not seems to send ping to maintain the connection, so nginx close the connection after a time (60s by default).

I increase that to 15 minutes:

```nginx
        location /websockify {
                proxy_pass http://websocketproxy;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
		proxy_send_timeout 15m;
		proxy_read_timeout 15m;
        }
```

**Comment by tinova** [comment]
Evaluate in the context of the Sunstone revamp

**Comment by tinova** [comment]
More context: https://github.com/OpenNebula/one/issues/1034#issuecomment-730165007

**Comment by tinova** [comment]
noVNC to be fully deprecated in #5422
