### ISSUE TITLE
AUTOSTART = YES to restart all the VMs automaticallly

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2787]
**Description**
Add AUTOSTART = YES to use `virsh autostart` in /kvm/deploy to restart the VMs automatically.

**Use case**
When the host is rebooted, the VMs don't start automatically, you need to start them manually.

**Interface Changes**
Core and drivers changes.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
virsh autostart does not fir the OpenNebula model, other approaches (hooks) are needed

**Comment by Githopp192** [comment]
that's true -->

   autostart [--disable] domain
       Configure a domain to be automatically started at boot.

       The option --disable disables autostarting.
But this will not work on OpenNebula controlled VMs -->

error: Failed to mark domain 2 as autostarted
error: Requested operation is not valid: cannot set autostart for transient domain
