### ISSUE TITLE
Ceph with shared fs DS broken

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2802]
**Description**
In current master (5.7.80), the deployment with Ceph when used with the shared fs DS is broken (legacy mode: http://docs.opennebula.org/5.4/deployment/open_cloud_storage_setup/ceph_ds.html#create-a-system-datastore)

**Details**
 - Affected Component: Core
 - Version: master (5.7.80)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Closing this as the latest version works with the shared tests. The problem was a miss-configuration in the stock oned.conf. It has been updated to work in the shared mode.
