### ISSUE TITLE
vm state documentation

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/one#2805]
**Description**
In the VM file source of GOCA, I found three LCM_STATE not documented:
```
// DiskResize lcm state
DiskResize LCMState = 62

// DiskResizePoweroff lcm state
DiskResizePoweroff LCMState = 63

// DiskResizeUndeployed lcm state
DiskResizeUndeployed LCMState = 64
```

Are they deprecated ?
They are just not documented here: [vm states ONe 5.6](https://docs.opennebula.org/5.6/operation/references/vm_states.html)

By the way, the link given to document the STATE and LCM_STATE values in the XSD file is dead.
The link is in this file: [vm.xsd](https://github.com/OpenNebula/one/blob/master/share/doc/xsd/vm.xsd)
FYI, it's this link:  http://docs.opennebula.org/stable/user/references/vm_states.html

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Fixed here: https://github.com/OpenNebula/docs/pull/488, https://github.com/OpenNebula/one/pull/2894
