### ISSUE TITLE
Error monitoring LXD host

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2824]
**Description**

```
> Fri Jan 18 09:29:02 2019 [Z0][ONE][E]: Error monitoring Host one-lxd1 (0): ../../vmm/lxd/poll:134:in `read': No such file or directory @ rb_sysopen - /sys/fs/cgroup/memory/lxc/one-1/memory.usage_in_bytes (Errno::ENOENT)
>         from ../../vmm/lxd/poll:134:in `get_memory'
>         from ../../vmm/lxd/poll:84:in `block in get_values'
>         from ../../vmm/lxd/poll:68:in `each'
>         from ../../vmm/lxd/poll:68:in `get_values'
>         from ../../vmm/lxd/poll:59:in `get_all_vm_info'
>         from /var/tmp/one/vmm/lib/poll_common.rb:99:in `print_all_vm_template'
>         from ../../vmm/lxd/poll:270:in `<main>'
> ERROR MESSAGE --8<------
> Error executing poll.sh
> ERROR MESSAGE ------>8--
> ARCH=x86_64
> MODELNAME="Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz"
> HYPERVISOR=lxd
> TOTALCPU=400
> CPUSPEED=1999
> TOTALMEMORY=5972408
> USEDMEMORY=796328
> FREEMEMORY=5176080
> FREECPU=380
> USEDCPU=20
> NETRX=25162228991
> NETTX=2221148784
> DS_LOCATION_USED_MB=10417
> DS_LOCATION_TOTAL_MB=59371
> DS_LOCATION_FREE_MB=48938
> DS = [
>   ID = 0,
>   USED_MB = 10417,
>   TOTAL_MB = 59371,
>   FREE_MB = 48938
> ]
> VM=[ID=1,POLL="DISK_SIZE=[ID=0,SIZE=5121] DISK_SIZE=[ID=1,SIZE=1] "]
> DS = [
>   ID = 100,
>   USED_MB = 10417,
>   TOTAL_MB = 59371,
>   FREE_MB = 48938
> ]
> HOSTNAME=ds1lxd1
```

**To Reproduce**
Setup LXD host with Ubuntu 18.04 and add to OpenNebula.
Instantiate a container.
Wait one monitoring interval.
The container LCM_STATE becomes UNKNOWN, the above message is logged.

**Expected behavior**
The container should be monitored.

**Details**
 - Affected Component: [VMM_MAD]
 - Hypervisor: [LXD]
 - Version: [5.7.80]

**Additional context**
The monitoring is recovered after changing the cgroup path from `.../lxd/...` to `.../sysdefault/lxd/...`
IMO the cgroup path should be configurable per host in `remotes/etc/vmm/lxdrc` or alike.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Monitoring fails if there is a container in the host that has no memory assigned. This will likely be a container not managed by opennebula. The OpenNebula-node-lxd package modifies the default profile to avoid this, however, there could be a situation where you have previous containers.

**Comment by dann1** [comment]
Sorry, I missed the last part of the issue, I agree we should patch the hard-coding.

**Comment by dann1** [comment]
I think it is preferable to avoid configuration files as much as possible, so I'm trying to auto-detect cgroups, would this be a good enough condition ?

```
 ~  findmnt -f -J -t cgroup
{
   "filesystems": [
      {"target":"/sys/fs/cgroup/systemd", "source":"cgroup", "fstype":"cgroup", "options":"rw,nosuid,nodev,noexec,relatime,xattr,name=systemd"}
   ]
}

```

**Comment by atodorov-storpool** [comment]
`findmnt` is stopping on first match, but we need the path to *memory* and *cpu,cpuacct*.

one place to find the cgroup paths in the container processes (/proc/$pid/cgroup)

But I am proposing an reduced and no so complex resolution - option to extend the path via environment variable. In my test lab it works. I believe it is not breaking nothing from default code-workflow.

Cheers!

**Comment by dann1** [comment]
OK, thanks a lot for the testing!!

**Comment by rsmontero** [comment]
Merged the commit, @dann1 will take care of the documentation to include the use of the environment variable.
