### ISSUE TITLE
Unable to instantiate LXD container with disk of type BLOCK

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2825]
**Description**

The following error message is rised because the patch 284a6ed2e47cbfe9b587d776b5f233955056d8f9 is not applied

```
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 Command execution fail: cat << EOT | /var/tmp/one/vmm/lxd/deploy '/var/lib/one//datastores/100/2/deployment.0' 'one-docker' 2 one-docker
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 /var/tmp/one/vmm/lxd/container.rb:353:in `public_send': undefined method `map' for nil:NilClass (NoMethodError)
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 from /var/tmp/one/vmm/lxd/container.rb:353:in `setup_disk'
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 from /var/tmp/one/vmm/lxd/container.rb:235:in `block in setup_storage'
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 from /var/tmp/one/vmm/lxd/container.rb:234:in `each'
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 from /var/tmp/one/vmm/lxd/container.rb:234:in `setup_storage'
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 from /var/tmp/one/vmm/lxd/deploy:71:in `<main>'
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 ExitCode: 1
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: LOG I 2 Failed to execute virtualization driver operation: deploy.
Fri Jan 18 09:32:24 2019 [Z0][VMM][D]: Message received: DEPLOY FAILURE 2 -

```

**To Reproduce**
Instantiate a container with disk of type BLOCK

**Expected behavior**
The container should be instantiated

**Details**
 - Affected Component: [VMM_MAD]
 - Hypervisor: [LXD]
 - Version: [5.7.80]

**Additional context**
The patch is in the master branch, but probably was merged after 5.7.80 was released.
With patch applied the container started.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Fixed in beta2
