### ISSUE TITLE
Add --force option when removing IP leases from OpenNebula

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2837]
**Description**
The IPAM driver depends on an external service, it may (and will) fail, hence the free_address call can fail, but if it fails the lease will be stuck for ever.
This leads to a "trapped" situation: the AR cannot be removed because there are active leases and the lease cannot be removed by design. If the AR is attempted to be removed, it will fail: "Address Range has leases in use".

OpenNebula should incorporate a **--force** option to remove leases without any validation from the database. Optionally, it can also attempt to release IP from remote IPAM server but the action must not be stopped if it fails. Another option is to skip completely the call to the driver when using **--force** option.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge:
* one https://github.com/OpenNebula/one/pull/4511
* developement https://github.com/OpenNebula/development/pull/917
* docs https://github.com/OpenNebula/docs/pull/1044

**Comment by tinova** [comment]
Sunstone: https://github.com/OpenNebula/one/blob/master/src/sunstone/models/OpenNebulaJSON/VirtualNetworkJSON.rb#L100, need to add a params['force'] and use it from the client

vCenter: evaluate if force is advisable on importer rm_ar functionality

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4591
- Docs: https://github.com/OpenNebula/docs/pull/1076
- Dev: https://github.com/OpenNebula/development/pull/934
