### ISSUE TITLE
Administrator unable to create scoped token for another user

### ISSUE THREAD

**Issue by Misenko** [OpenNebula/one#2843]
**Description**
Oneadmin (or another privileged user) cannot create scoped token (restricted to a group) for another user unless he belongs to the same group as the said user. 

**To Reproduce**
In Sunstone:
1. Login as oneadmin
2. Select user which belongs to some arbitrary group, e.g. group with id 105 (oneadmin CANNOT belong to the same group)
3. Select Auth tab and click Manage login tokens
4. Select group 105
5. Click Get a new token

With Ruby library (oneadmin credentials and XML RPC set in env variables):
```ruby
require 'opennebula'
client = OpenNebula::Client.new
user = OpenNebula::User.new(OpenNebula::User.build_xml, client)
user.login('username', '', 3600, 103)
```

**Expected behavior**
Oneadmin should be able to create scoped token for other users.

**Details**
 - Version: [5.4.7 and higher]

**Additional context**
Error message given by OpenNebula is `[one.user.login] EGID is not in user group list`.
I suspect that this issue was introduced in an effort to fix another issue in PR https://github.com/OpenNebula/one/pull/1679.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
right. fixed in master
