### ISSUE TITLE
Add option for scheduling disk snapshot

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2857]
**Description**
Add option for scheduling disk snapshot

**Use case**
It would be useful to be able to schedule disk snapshot action.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Already done
