### ISSUE TITLE
Add more functionality to VM search option

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#2906]
**Description**
Ir will be useful to add more functionality to the VM search option, like searching VM by multiple fields (for example IP and MAC).

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
covered by #5861
