### ISSUE TITLE
Add support for vlan_filtering attribute for bridges created by OpenNebula

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#2907]
**Description**
It would be useful to be able to set vlan_filtering option to the bridges created by OpenNebula when creating a Virtual Network.

**Use case**
Have multiple bridges with the same name of VLAN o VXLAN type.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This is no needed. We'll reopen if needed
