### ISSUE TITLE
Sunstone doesn't offer AR remove in vnet 

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2912]
**Description**

Using sunstone it is not possible to delete Ars from a imported vCenter vnet.

**To Reproduce**
Steps to reproduce the behavior.

Import a vCenter vnet, go to vnet section -> try to delete any AR, delete button will not show.

**Expected behavior**

delete button appears to delete the AR, just like KVM.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Doesn't affect only vCenter.

Manually created virtual network with AR doesn't have an option to remove the AR:

![image](https://user-images.githubusercontent.com/414850/54213943-9769be80-44e5-11e9-9eec-f551b5592dd7.png)

**Comment by fborges-opennebula** [comment]
This bug is already solved in current version of OpenNebula.
I will proceed to close this issue.
