### ISSUE TITLE
Opennebula datastore/network loses attachment to its cluster while trying to allocate VM

### ISSUE THREAD

**Issue by akeskimo** [OpenNebula/one#2913]
**Description**
While calling one.vm.allocate, the request fails due to errors

opennebula.opennebula.ONEException: (8192, '[one.vm.allocate] Missing clusters. Datastore for DISK 0 is not in any cluster')

opennebula.opennebula.ONEException: (8192, '[one.vm.allocate] Missing clusters. Network for NIC 0 is not in any cluster')

The allocation will succeed after retry.

**To Reproduce**
Do multiple request one.vm.allocate with same parameters in short period of time.

**Expected behavior**
After allocating VM, a clone is created and is accessible via Opennebula

**Details**
 - Affected Component: Scheduler
 - Hypervisor: KVM
 - Version: 5.4.13

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Thanks for the information, we will check it.

**Comment by nierob** [comment]
Downstream bug report: https://bugreports.qt.io/browse/QTQAINFRA-1545

**Comment by christian7007** [comment]
We've already fix the bug. The fix will be released with OpenNebula 5.8

**Comment by nierob** [comment]
Thanks!

**Comment by rsmontero** [comment]
Closing, this should be fixed in 5.8
