### ISSUE TITLE
All dirs and files inside lxd container has owner nobody:nogroup

### ISSUE THREAD

**Issue by lexore** [OpenNebula/one#2923]
**Description**
After i created new LXD container i can see that all dirs and files inside container has owner nobody:nogroup.
```
# lxc exec one-10 -- ls -la /
total 86
drwxr-xr-x  23 nobody nogroup  4096 Feb 11 12:53 .
drwxr-xr-x  23 nobody nogroup  4096 Feb 11 12:53 ..
drwxr-xr-x   2 nobody nogroup  4096 Feb  7 13:49 bin
drwxr-xr-x   2 nobody nogroup  4096 Apr 12  2016 boot
drwxr-xr-x   2 nobody nogroup  2048 Feb 11 12:53 context
drwxr-xr-x   9 root   root      500 Feb 11 12:53 dev
drwxr-xr-x  78 nobody nogroup  4096 Feb  7 13:50 etc
drwxr-xr-x   3 nobody nogroup  4096 Feb  7 07:44 home
drwxr-xr-x  11 nobody nogroup  4096 Feb  7 07:44 lib
drwxr-xr-x   2 nobody nogroup  4096 Feb  7 07:44 lib64
...
```

**To Reproduce**
OS: ubuntu 16.04
Opennebula ver: 5.7.85-1

Install LXD packages on host node (from xenial-backports):
```
apt-get install lxd=3.0.3-0ubuntu1~16.04.1 \
liblxc1=3.0.3-0ubuntu1~16.04.1 \
lxcfs=3.0.3-0ubuntu1~16.04.1 \
lxd-client=3.0.3-0ubuntu1~16.04.1
```
Install openenbula deb packages on host node:
```
dpkg -i opennebula-common_5.7.85-1_all.deb \
opennebula-node_5.7.85-1_all.deb \
opennebula-node-lxd_5.7.85-1_amd64.deb
```

Via sunstone:
Import app "ubuntu_xenial" from "Linux Containers" marketplace.
Use it as template.
Create LXD container from this template.
On host node run
`lxc exec one-10 -- ls -la /`

**Expected behavior**
```
# lxc exec one-10 -- ls -la /
total 86
drwxr-xr-x  23 root root  4096 Feb 11 12:53 .
drwxr-xr-x  23 root root  4096 Feb 11 12:53 ..
drwxr-xr-x   2 root root  4096 Feb  7 13:49 bin
drwxr-xr-x   2 root root  4096 Apr 12  2016 boot
drwxr-xr-x   2 root root  2048 Feb 11 12:53 context
drwxr-xr-x   9 root root   500 Feb 11 12:53 dev
drwxr-xr-x  78 root root  4096 Feb  7 13:50 etc
drwxr-xr-x   3 root root  4096 Feb  7 07:44 home
drwxr-xr-x  11 root root  4096 Feb  7 07:44 lib
drwxr-xr-x   2 root root  4096 Feb  7 07:44 lib64
```

**Details**
 - Affected Component: LXD plugin
 - Hypervisor: LXD
 - Version: 5.7.85

**Additional context**
Here log and conf files: https://gist.github.com/lexore/a1c08517d776aa15c0f9b374531467ac
* /var/log/lxd/one-10/console.log
* /var/log/lxd/one-10/lxc.conf

As you can see, that it's problem since container create moment - systemd generate many errors "Operation not permitted".

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Hello, can you try adding `LXD_SECURITY_PRIVILEGED = true` to the VM_TEMPLATE ?

**Comment by lexore** [comment]
Yes it helped!
I added `LXD_SECURITY_PRIVILEGED=true` to template and now i see right owner:
```
# lxc exec one-11 -- ls -la /
total 86
drwxr-xr-x  23 root root  4096 Feb 11 15:28 .
drwxr-xr-x  23 root root  4096 Feb 11 15:28 ..
drwxr-xr-x   2 root root  4096 Feb  7 13:49 bin
drwxr-xr-x   2 root root  4096 Apr 12  2016 boot
drwxr-xr-x   2 9869 9869  2048 Feb 11 15:28 context
drwxr-xr-x   9 root root   500 Feb 11 15:28 dev
drwxr-xr-x  79 root root  4096 Feb 11 15:33 etc
drwxr-xr-x   3 root root  4096 Feb  7 07:44 home
drwxr-xr-x  11 root root  4096 Feb  7 07:44 lib
drwxr-xr-x   2 root root  4096 Feb  7 07:44 lib64
```
Container works well.
Only weird thing - is hostname "LXC_NAME" in container.
Wrong work without LXD_SECURITY_PRIVILEGED - is this a bug?

**Comment by bmullan** [comment]
OpenNebula is going to support Unprivileged LXD containers isn't it?

**Comment by dann1** [comment]
> Only weird thing - is hostname "LXC_NAME" in container.

that is the default hostname the lxd image has on the public lxd image serve. You can change it by setting `SET_HOSTNAME` variable in the [context configuration](https://docs.opennebula.org/5.2/operation/references/template.html#context-section)

> Wrong work without LXD_SECURITY_PRIVILEGED - is this a bug?

No, it's a condition. The drivers don't perform id mappings right now, so, you need to tell the container to use the same as the host.

> OpenNebula is going to support Unprivileged LXD containers isn't it?

We support both variants, but marketplace images (both from the official marketplace and the LXD one) need this setting

One way to workaround this is to [create your own image](https://github.com/OpenNebula/addon-lxdone/blob/master/Image.md) by creating it from a  container spawned via `lxc launch`
