### ISSUE TITLE
[GOCA] externalize client and modify the way to access to the resources (warning: breaking changes )

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/one#2940]
**Description**
This pull request make some changes on the client, and the whole API.
/!\ It's an important breaking change /!\

As this imply breaking changes, I added some documentation (PR in the docs repository, and added some examples)

1. This pull request adds a controller notion.
It's a cheap layer added between the client and the entities API (host, vm ...).
It allows to rework the way to access to the resources via the API in a way that seems more intuitive to use.

For instance, to make requests, now, it's like this:
```
vm, err := ctrl.VM(id).Info()                              // Retrieve VM informations
err := ctrl.VM(id).Delete()                                // Delete a VM
err := ctrl.VMs().Create(template, boolean)    // Create a VM
vms, err := ctrl.VMs().Info()                            // Retrieve a list of VM informations (with less informations per instance)
id, err := ctrl.ByName("vm_name")            // Retrieve an ID by name
``` 

2.  The controller embed a client:
this pull request also externalize the client and allow to redefine it (For instance you may want to define a pool of clients to enabling some concurrency, or make a client that retry if the request fails ... ).
If the RPCCaller interface is implemented, the controller can use the external client.

3. By the way, I also added some other changes/fixes breaking the API:
    -  lock part to be more maintainable, add added some missing methods
    -  change parameters of some methods: permissions for chmod, typed parameter for Update methods
    -  ID are signed integers

**Use case**
Users of GOCA may want more flexibility on the client, and a more natural way to access the resources

**Interface Changes**
A great part of the API change.

**Additional Context**
I will provide a pull request in this way.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by eripa** [comment]
This is a very useful improvement. Any feedback from the OpenNebula team whether or not this is something that will be merged?

**Comment by treywelsh** [comment]
Thank you very much for your feedback :)
It's not perfect, but it proposes some changes that we need.

I discuss with the OpenNebula member in charge of the Go binding, he seems busy but as far as I know it's being reviewed and some other pull request have been merged these days.
