### ISSUE TITLE
Counting used/disk size for images, not the max/virtual size

### ISSUE THREAD

**Issue by Avatat** [OpenNebula/one#2974]
**Description**
At this moment, we can't create qcow2 images larger than available space in image datastore. I think, that we should allow for it because qcow2 images are "thin provisioned", and when they're new, they weight only a few KB, not hundreds of GB, for example:
```
$ qemu-img info /var/lib/one/datastores/1/3f0b3e2dcfc15f4b839ec525cee74a5c
image: /var/lib/one/datastores/1/3f0b3e2dcfc15f4b839ec525cee74a5c
file format: qcow2
virtual size: 200G (214748364800 bytes)
disk size: 196K
```
OpenNebula doesn't allow for creating such qcow2 images, and it's reporting `Not enough space in datastore` error. It counts the virtual size of the image (so hundreds of GB, not the real one) in the total size of datastore. But the real/used size is available in disk info in VM storage settings.
As a workaround, I had to create a sparse file, format it, and mount as the whole datastore.

I will start to work on it and will update you.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Avatat** [comment]
I found `DATASTORE_CAPACITY_CHECK` property which can be used as a workaround (much better than mentioned sparse file and filesystem on it).

**Comment by tinova** [comment]
The proper practice is to expect always the max size. for other scenarios there is, as you say, the capacity check disable flag.
