### ISSUE TITLE
Create a VM bridge between to isolated groups

### ISSUE THREAD

**Issue by Septisse13** [OpenNebula/one#2976]
**Vulnerability Details**
Use case : I use your solution to provide to my users isolated "environments" for development and test purpose. To do this, one VDC and one Virtual Network is created for each environment. The Host and the Cluster are shared between all environments. Environments are implemented with groups, one group for each environment.

Scenario: Some users must access several environments, they are in two groups, say group A an group B (for environment A and B). When an such user create a VM in the env. A, he can use a Virtual Network of the env. B and assign it to the VM. This VM can be used as a bridge between A and B, a forbidden situation in my case.

**To Reproduce**
1. Create in vCenter two Ports Group (Net-A and Net-B) in the same vSwitch
2. Import vCenter Host, Cluster, Datastore, Templates and the two Ports Groups
3. Create two groups, A and B
4. Create one user "user" with primary group A and secondary groups A and B
5. Assign Net-A to group A and Net-B to group B without permissions to "other"
6. Login in Sunstone (for instance) with user
7. Set primary group to A (user/Groups/A with the start)
8. Create a VM from template
9. Add one NIC with Net-A and one other with Net-B
10. Create the VM
11. The VM belong to user/A and use Net-B

**Version**
Completed for affected components
 - Affected Component: one 
 - Hypervisor: vCenter
 - OpenNebula Version: 5.6.1
 - Browser: NA

**Additional context**
Suggestion: When a resource is assigned to a VM, the rights can be evaluated compared to the user rights and only his primary group (the group of the VM). With this design, Net-B can not be assign to a VM of user/A.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Septisse13** [comment]
A similar issue has already created  #1154, but the creation of the VM fail because of interactions between KVM and vCenter.

**Comment by rsmontero** [comment]
This scenario can be implemented with some ACLs:
1. Remove Group access to resources (There ir a oneuser umask that can help with this)
2. Manually implement your access policies with ACLs. Like granting access to a VM a given group etc...

Closing
