### ISSUE TITLE
Configurable server IP for collectd-client

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2980]
**Description**
Right now collectd is always using IPv4-address from `SSH_CLIENT`  variable for sending metrics, but if you have High Available installation and you move `oned` process to neighbors node, `SSH_CLIENT` will be changed.
Metrics will not reach destination until new oned will go node and run collectd again.

**Use case**
Faster switch and faster recovery

**Interface Changes**
There is should be configurable option for specify IP address for sending metrics

**Additional Context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
this problem is still actual

**Comment by rsmontero** [comment]
New monitoring system includes this change in particular. However the HA script would also need to include rotating the IP monitoring address
