### ISSUE TITLE
option to set migration type for rescheduling

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2983]
**Description**
Option to set the cold migration type when _LIVE_RECHEDS_ is set to 0
VMs with enabled PCI pass-through could be migrated only with migrate -poweroff/-poweroff_hard

**Use case**
For example when flushing a host for maintenance using `onehost flush {host}`, OS upgrade for example.

**Interface Changes**
Option to set the migration type for the scheduler. Something like
`COLD_MIGRATE_POWEROFF=<0|1>`
or better
`COML_MIGRATE_MODE=<poweroff|poweroff-hard>`

or something like that?

**Additional Context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Makes sense

**Comment by alvarosimon** [comment]
We are also waiting for this nice feature at UGent :wink: . 
We need to migrate PCI pt VMs with `onehost flush` command automatically, this scheduler change per VM will help us a lot to define the way to migrate specific VMs.

**Comment by hydro-b** [comment]
Funny enough, this feature would be very useful to have just now :-). We are migrating (cold) VMs to new hypervisors (different CPU). Normally a live-migrate is what we use, but in this specific scenario cold migration is used. So yeah, there are definitely use cases for this feature.

**Comment by paczerny** [comment]
PRs for merge:
* one-ee: https://github.com/OpenNebula/one-ee/pull/152 to one-5.12 and master
* developement: https://github.com/OpenNebula/development/pull/1152 to one-5.12 and master
* docs: https://github.com/OpenNebula/docs/pull/1265 to one-5.12-maintanence and master?

**Comment by paczerny** [comment]
PRs for merge:
* one-ee to master: https://github.com/OpenNebula/one-ee/pull/153
* developement to master: https://github.com/OpenNebula/development/pull/1153
* docs to master: https://github.com/OpenNebula/docs/pull/1266
