### ISSUE TITLE
"[object Object]" in the "IPs" column is shown for VMs that are in STATE "POWEROFF" 

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#2995]
**Description**
In sunstone for VMs that are in STATE "POWEROFF" in the "IPs" column: "[object Object]" is shown

**To Reproduce**
Set a VM in "POWEROFF" STATE. Notice the "

**Expected behavior**
The IPs configured for the VM are shown

**Details**
Sunstone
 - Version: 5.8.0
**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
@hydro-b beat me this time :)

IMO it a bug in the database migrator. Because it is affecting only the non-running VMs.

After power-cycling a VM the issue disappear.

 The only difference I could spot is in the VM metadata (in VM/TEMPLATE):
```    <AUTOMATIC_NIC_REQUIREMENTS><![CDATA[("CLUSTERS/ID" @> 0)]]></AUTOMATIC_NIC_REQUIREMENTS>
```
The above line is missing in the troubling VMs...

**Comment by rsmontero** [comment]
This is now solved in the repo. Workaround is also mentioned here http://docs.opennebula.org/5.8/intro_release_notes/release_notes/known_issues.html
