### ISSUE TITLE
Failure during undeploy on the same host as sunstone

### ISSUE THREAD

**Issue by alitvak69** [OpenNebula/one#3010]
**Description**
When I run undeploy from athe Sunstone server I get an error if VM located on the same host as Sunstone.  It doesn't happen if VM is deployed on the different node.

**To Reproduce**
Login into Sunstone web interface and execute undeploy of the VM instance located on the same node

**Expected behavior**
VM instance becomes shutdown first and then changes status to undeployed.

**Details**
 - Affected Component:  Storage
 - Hypervisor: KVM
 - Version: 5.6.1,5.8.0

**Additional context**
Here is the log from that node
```
Fri Mar 1 17:19:48 2019 [Z0][VM][I]: New LCM state is PROLOG_UNDEPLOY
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: Command execution failed (exit code: 2): /var/lib/one/remotes/tm/ceph/mv virt1n1-chi:/var/lib/one//datastores/100/145 virt1n2-chi.xcastlabs.net:/var/lib/one//datastores/100/145 145 100
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: mv: Moving virt1n1-chi:/var/lib/one/datastores/100/145 to virt1n2-chi.xcastlabs.net:/var/lib/one/datastores/100/145
Fri Mar 1 17:19:50 2019 [Z0][TM][E]: mv: Command "set -e -o pipefail
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: 
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: tar -C /var/lib/one/datastores/100 --sparse -cf - 145 | ssh virt1n2-chi.xcastlabs.net 'tar -C /var/lib/one/datastores/100 --sparse -xf -'
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: rm -rf /var/lib/one/datastores/100/145" failed: Warning: Permanently added 'virt1n1-chi' (ECDSA) to the list of known hosts.
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: tar: 145: Cannot stat: No such file or directory
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: tar: Exiting with failure status due to previous errors
```

All of my VMs are using shared ceph store.  A similar issue may be discussed at the forum

https://forum.opennebula.org/t/error-during-undeploy/6026/13

But no resolution in sight.

Here is my store config

```
$ onedatastore show 100
DATASTORE 100 INFORMATION                                                       
ID             : 100                 
NAME           : ceph_system         
USER           : dbaley              
GROUP          : oneadmin            
CLUSTERS       : 0                   
TYPE           : SYSTEM              
DS_MAD         : -                   
TM_MAD         : ceph                
BASE PATH      : /var/lib/one//datastores/100
DISK_TYPE      : RBD                 
STATE          : READY               

DATASTORE CAPACITY                                                              
TOTAL:         : 5.4T                
FREE:          : 5.2T                
USED:          : 200.3G              
LIMIT:         : -                   

PERMISSIONS                                                                     
OWNER          : uma                 
GROUP          : uma                 
OTHER          : ---                 

DATASTORE TEMPLATE                                                              
ALLOW_ORPHANS="YES"
BRIDGE_LIST="virt1n1-chi"
CEPH_HOST="10.1.40.61 10.1.40.62 10.1.40.63"
CEPH_SECRET="6c5c629c-271e-46b5-bbee-e543168188db"
CEPH_USER="libvirt"
DISK_TYPE="RBD"
DS_MIGRATE="NO"
POOL_NAME="one"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
SHARED="YES"
TM_MAD="ceph"
TYPE="SYSTEM_DS"
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by alitvak69** [comment]
The same issue is reproducible in 5.8.0

**Comment by dann1** [comment]
mv has a check that verifies the source and destination are the same, but it does it based on string comparison

if `virt1n1-chi` == `virt1n2-chi.xcastlabs.net` in `mv virt1n1-chi:/var/lib/one//datastores/100/145 virt1n2-chi.xcastlabs.net:/var/lib/one//datastores/100/145 145 100` it isn't skipped and then fails.

I managed to reproduce it calling the frontend node localhost, while the "real" name is `ubuntu1804-lxd-ceph-luminous-e8941-0.test`, so the undeploy attempts to move from `localhost` to `ubuntu1804-lxd-ceph-luminous-e8941-0.test` and fails doing so.

**Comment by dann1** [comment]
So, the check could be improved to identify if both hosts are the same

**Comment by dann1** [comment]
In my scenario `ubuntu1804-lxd-ceph-luminous-e8941-0.test` is the frontend, and it was added as a host twice, with that name and also localhost.

```
oneadmin@ubuntu1804-lxd-ceph-luminous-e8941-0:~$ onehost list
  ID NAME            CLUSTER   TVM      ALLOCATED_CPU      ALLOCATED_MEM STAT  
   4 ubuntu1804-lxd- default     0       0 / 100 (0%)   0K / 985.4M (0%) on    
   2 localhost       default     1     10 / 100 (10%) 128M / 985.4M (12% on    
   1 ubuntu1804-lxd- default     0       0 / 100 (0%)   0K / 985.4M (0%) dsbl
   0 ubuntu1804-lxd- default     0       0 / 100 (0%)   0K / 985.4M (0%) dsbl
```

I successfully undeployed the VM 16, which was deployed on `ubuntu1804-lxd-ceph-luminous-e8941-0.test`

![image](https://user-images.githubusercontent.com/16429804/57544849-32341d00-731e-11e9-946f-ab349d413a29.png)

And VM 15 failed, when undeploying from localhost

![image](https://user-images.githubusercontent.com/16429804/57545070-d322d800-731e-11e9-840d-cfd53f190281.png)

Can you check that is your case ?

**Comment by alitvak69** [comment]
Nope.  This is not my case.

root@virt1n1-chi:~# onehost list --csv

 ID,NAME,CLUSTER,TVM,ALLOCATED_CPU,ALLOCATED_MEM,STAT
7,virt1n5-chi.xcastlabs.net,default,6,3000 / 4000 (75%),28G / 125.6G
(22%),on
6,virt1n4-chi.xcastlabs.net,default,5,2800 / 4000 (70%),26G / 125.6G
(20%),on
3,virt1n3-chi.xcastlabs.net,default,5,1600 / 2400 (66%),22G / 94.4G (23%),on
2,virt1n2-chi.xcastlabs.net,default,4,1400 / 2400 (58%),20G / 94.4G (21%),on
1,virt1n1-chi.xcastlabs.net,default,3,1200 / 2400 (50%),12G / 94.4G (12%),on

They are all unique and fqdn

**Comment by dann1** [comment]
Well, in your case, `/var/lib/one/remotes/tm/ceph/mv virt1n1-chi:/var/lib/one//datastores/100/145 virt1n2-chi.xcastlabs.net:/var/lib/one//datastores/100/145 145 100` the first host corresponds to `BRIDGE_LIST="virt1n1-chi"`, is this host (which is absent on your virtualization cluster) the same as one of the hosts ?

**Comment by alitvak69** [comment]
virt1n1-chi = virt1n1-chi.xcastlabs.net

So possible issue with trying to handle fqdn vs short host?

**Comment by dann1** [comment]
https://github.com/OpenNebula/one/blob/d93615811bf6acf5fd3ca69ac957157b5e3844d1/src/tm_mad/ssh/mv#L63-L66

The comparison is done by literal strings, and it seems fails to run under your conditions

**Comment by alitvak69** [comment]
So what do I do in this case?

**Comment by dann1** [comment]
What is odd in this case is the fact that even with FQDN

```
Fri Mar 1 17:19:50 2019 [Z0][TM][I]: mv: Moving virt1n1-chi:/var/lib/one/datastores/100/145 to virt1n2-chi.xcastlabs.net:/var/lib/one/datastores/100/145
```

virt1n1 != virt1n2 and the issue you are experiencing happens to me when they are the same, that's the way I can reproduce your issue.

**Comment by dann1** [comment]
Can you update 
```
BRIDGE_LIST="virt1n1-chi"
CEPH_HOST="10.1.40.61 10.1.40.62 10.1.40.63"
```
with FQDNs like the output of `onehost list` ?

**Comment by alitvak69** [comment]
Do you mean to keep both fqdn and short entries?

**Comment by dann1** [comment]
one or the other, just to be the same

**Comment by dann1** [comment]
We haven't had more feedback, we can reopen if necessary

**Comment by alitvak69** [comment]
Sorry for the delay and confusion.  The bridge list was changed to virt1n1-chi.xcastlabs.net.  I am also in the process of installing a new opennebula system in a different DC.  For this one I have built packages for 5.8.3, was the issue resolved?

**Comment by alitvak69** [comment]
Sorry, could you reopen this?

**Comment by dann1** [comment]
So, with, `virt1n1-chi.xcastlabs.net` still happens ?

**Comment by alitvak69** [comment]
Became worse.  I can no longer migrate.  BTW I am still on 5.8.0

Tue Jun 25 08:43:23 2019 [Z0][VM][I]: New LCM state is SHUTDOWN_UNDEPLOY
Tue Jun 25 08:43:30 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:43:30 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: shutdown.
Tue Jun 25 08:43:30 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:43:31 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:43:31 2019 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Tue Jun 25 08:43:31 2019 [Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: Command execution failed (exit code: 2): /var/lib/one/remotes/tm/ceph/mv virt1n1-chi.xcastlabs.net:/var/lib/one//datastores/100/147 virt1n1-chi:/var/lib/one//datastores/100/147 147 100
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: mv: Moving virt1n1-chi.xcastlabs.net:/var/lib/one/datastores/100/147 to virt1n1-chi:/var/lib/one/datastores/100/147
Tue Jun 25 08:43:33 2019 [Z0][TM][E]: mv: Command "set -e -o pipefail
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: 
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: tar -C /var/lib/one/datastores/100 --sparse -cf - 147 | ssh virt1n1-chi 'tar -C /var/lib/one/datastores/100 --sparse -xf -'
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: rm -rf /var/lib/one/datastores/100/147" failed: Warning: Permanently added 'virt1n1-chi.xcastlabs.net' (ECDSA) to the list of known hosts.
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: tar: 147: Cannot stat: No such file or directory
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: tar: Exiting with failure status due to previous errors
Tue Jun 25 08:43:33 2019 [Z0][TM][I]: Warning: Permanently added 'virt1n1-chi' (ECDSA) to the list of known hosts.
Tue Jun 25 08:43:33 2019 [Z0][TM][E]: Error copying disk directory to target host
Tue Jun 25 08:43:33 2019 [Z0][TM][E]: Error executing image transfer script: Error copying disk directory to target host
Tue Jun 25 08:43:33 2019 [Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY_FAILURE
Tue Jun 25 08:44:23 2019 [Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY
Tue Jun 25 08:44:23 2019 [Z0][VM][I]: New state is UNDEPLOYED
Tue Jun 25 08:44:23 2019 [Z0][VM][I]: New LCM state is LCM_INIT
Tue Jun 25 08:45:02 2019 [Z0][VM][I]: New state is PENDING
Tue Jun 25 08:45:03 2019 [Z0][VM][I]: New state is ACTIVE
Tue Jun 25 08:45:03 2019 [Z0][VM][I]: New LCM state is PROLOG_UNDEPLOY
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: Command execution failed (exit code: 2): /var/lib/one/remotes/tm/ceph/mv virt1n1-chi:/var/lib/one//datastores/100/147 virt1n5-chi.xcastlabs.net:/var/lib/one//datastores/100/147 147 100
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: mv: Moving virt1n1-chi:/var/lib/one/datastores/100/147 to virt1n5-chi.xcastlabs.net:/var/lib/one/datastores/100/147
Tue Jun 25 08:45:05 2019 [Z0][TM][E]: mv: Command "set -e -o pipefail
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: 
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: tar -C /var/lib/one/datastores/100 --sparse -cf - 147 | ssh virt1n5-chi.xcastlabs.net 'tar -C /var/lib/one/datastores/100 --sparse -xf -'
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: rm -rf /var/lib/one/datastores/100/147" failed: Warning: Permanently added 'virt1n1-chi' (ECDSA) to the list of known hosts.
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: tar: 147: Cannot stat: No such file or directory
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: tar: Exiting with failure status due to previous errors
Tue Jun 25 08:45:05 2019 [Z0][TM][I]: Warning: Permanently added 'virt1n5-chi.xcastlabs.net,10.0.28.21' (ECDSA) to the list of known hosts.
Tue Jun 25 08:45:05 2019 [Z0][TM][E]: Error copying disk directory to target host
Tue Jun 25 08:45:05 2019 [Z0][TM][E]: Error executing image transfer script: Error copying disk directory to target host
Tue Jun 25 08:45:05 2019 [Z0][VM][I]: New LCM state is PROLOG_UNDEPLOY_FAILURE
Tue Jun 25 08:45:47 2019 [Z0][VM][I]: New LCM state is BOOT_UNDEPLOY
Tue Jun 25 08:45:47 2019 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/147/deployment.2
Tue Jun 25 08:45:48 2019 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Tue Jun 25 08:45:49 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:45:49 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:45:49 2019 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Tue Jun 25 08:45:51 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:45:51 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Tue Jun 25 08:45:53 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:45:53 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:45:53 2019 [Z0][VMM][I]: Successfully execute network driver operation: post.
Tue Jun 25 08:45:53 2019 [Z0][VM][I]: New LCM state is RUNNING
Tue Jun 25 08:48:24 2019 [Z0][VM][I]: New LCM state is MIGRATE
Tue Jun 25 08:48:26 2019 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_premigrate.
Tue Jun 25 08:48:26 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:48:27 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 08:48:27 2019 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Tue Jun 25 08:48:27 2019 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/migrate 'one-147' 'virt1n1-chi.xcastlabs.net' 'virt1n5-chi.xcastlabs.net' 147 virt1n5-chi.xcastlabs.net
Tue Jun 25 08:48:27 2019 [Z0][VMM][E]: migrate: Command "virsh --connect qemu+tcp://localhost/system migrate --live one-147 qemu+ssh://virt1n1-chi.xcastlabs.net/system" failed: error: unsupported configuration: Unable to find security driver for model apparmor
Tue Jun 25 08:48:27 2019 [Z0][VMM][E]: Could not migrate one-147 to virt1n1-chi.xcastlabs.net
Tue Jun 25 08:48:28 2019 [Z0][VMM][I]: ExitCode: 1
Tue Jun 25 08:48:28 2019 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_failmigrate.
Tue Jun 25 08:48:28 2019 [Z0][VMM][I]: Failed to execute virtualization driver operation: migrate.
Tue Jun 25 08:48:28 2019 [Z0][VMM][E]: Error live migrating VM: Could not migrate one-147 to virt1n1-chi.xcastlabs.net
Tue Jun 25 08:48:28 2019 [Z0][VM][I]: New LCM state is RUNNING
Tue Jun 25 08:48:28 2019 [Z0][LCM][I]: Fail to live migrate VM. Assuming that the VM is still RUNNING (will poll VM).

**Comment by alitvak69** [comment]
I fixed apparmor issue.  It was not related.  However, after making bridge list on ceph datastores virt1n1-chi.xcastlabs.net, I still see this 

Tue Jun 25 12:03:17 2019 [Z0][VM][I]: New LCM state is SHUTDOWN_UNDEPLOY
Tue Jun 25 12:03:25 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 12:03:25 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: shutdown.
Tue Jun 25 12:03:26 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 12:03:26 2019 [Z0][VMM][I]: ExitCode: 0
Tue Jun 25 12:03:26 2019 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Tue Jun 25 12:03:26 2019 [Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: Command execution failed (exit code: 2): /var/lib/one/remotes/tm/ceph/mv virt1n1-chi.xcastlabs.net:/var/lib/one//datastores/100/147 virt1n1-chi:/var/lib/one//datastores/100/147 147 100
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: mv: Moving virt1n1-chi.xcastlabs.net:/var/lib/one/datastores/100/147 to virt1n1-chi:/var/lib/one/datastores/100/147
Tue Jun 25 12:03:29 2019 [Z0][TM][E]: mv: Command "set -e -o pipefail
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: 
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: tar -C /var/lib/one/datastores/100 --sparse -cf - 147 | ssh virt1n1-chi 'tar -C /var/lib/one/datastores/100 --sparse -xf -'
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: rm -rf /var/lib/one/datastores/100/147" failed: Warning: Permanently added 'virt1n1-chi.xcastlabs.net' (ECDSA) to the list of known hosts.
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: tar: 147: Cannot stat: No such file or directory
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: tar: Exiting with failure status due to previous errors
Tue Jun 25 12:03:29 2019 [Z0][TM][I]: Warning: Permanently added 'virt1n1-chi' (ECDSA) to the list of known hosts.
Tue Jun 25 12:03:29 2019 [Z0][TM][E]: Error copying disk directory to target host
Tue Jun 25 12:03:29 2019 [Z0][TM][E]: Error executing image transfer script: Error copying disk directory to target host
Tue Jun 25 12:03:29 2019 [Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY_FAILURE
 
So I don't understand where virt1n1-ch (short name) is coming from.

**Comment by alitvak69** [comment]
I think problem may be somewhere in host attributes.

HOSTNAME | virt1n1-chi
I  changed it via web to FQDN but as I came back to the page the change reverted back to a short host name.

**Comment by alitvak69** [comment]
After changing hostnames via hostctl on every node, I restarted opennebula and opennebula-sunstone on virt1n1-chi.xcastlabs.net.  I also restarted libvirtd on the same node just in case.  I then migrate VM to the virt1n1-chi.xcastlabs.net and then undeploy worked without failure.

**Comment by alitvak69** [comment]
Still, I believe your software needs to detect node via both short and FQDN names.

**Comment by dann1** [comment]
Glad things worked out in the end. Could you open a feature request regarding this situation ? You can always reference this issue for the additional context.

**Comment by alitvak69** [comment]
Sorry,

I am having a hard time to describe this feature.   Match localhost to FQDN and short host names perhaps?

**Comment by dann1** [comment]
Yes, somehow take into account short and FQDN to avoid false checks.

**Comment by dann1** [comment]
Great!!
