### ISSUE TITLE
VM user template values wiped by scheduler message

### ISSUE THREAD

**Issue by tkald** [OpenNebula/one#3011]
**Description**
When I boot more vm-s/containers than scheduler can handle at once, it overwrites VM user template section with error message. Most of user defined template data is lost when scheduler dispatches VM at next cycle. It doesn't happen every time though and seems to be template content dependent. Maybe related to double quotes?

Original user template section:
```
User template
DESCRIPTION = "testin lxd-d"
HYPERVISOR = "lxd"
INPUTS_ORDER = ""
LOGO = "images/logos/ubuntu.png"
LXD_PROFILE = ""
LXD_SECURITY_NESTING = "no"
LXD_SECURITY_PRIVILEGED = "yes"
MEMORY_UNIT_COST = "MB"
READY = "YES"
SCHED_REQUIREMENTS = "HYPERVISOR=\"lxd\""
```
And after scheduler has written an error message:
```
User template
SCHED_MESSAGE = "Sat Mar 2 13:37:28 2019 : Cannot dispatch VM to any Host. Possible reasons: Not enough capacity in Host or System DS, or dispatch limit reached"
SCHED_REQUIREMENTS = "HYPERVISOR=\"lxd\""
```

**To Reproduce**
Boot more VM-s/containers at once than MAX_DISPATCH scheduler value.

**Expected behavior**
Don't overwrite user template data.

**Details**
 - Affected Component: Sunstone, Scheduler
 - Hypervisor: only tesed with LXD containers
 - Version: 5.8.0

**Additional context**
Sched.conf
```
MESSAGE_SIZE = 1073741824
TIMEOUT      = 60

ONE_XMLRPC = "http://localhost:2633/RPC2"

SCHED_INTERVAL = 3

MAX_VM       = 8
MAX_DISPATCH = 8
MAX_HOST     = 1

LIVE_RESCHEDS  = 1

MEMORY_SYSTEM_DS_SCALE = 0

DIFFERENT_VNETS = YES

DEFAULT_SCHED = [
    policy = 1
]

DEFAULT_DS_SCHED = [
   policy = 1
]

DEFAULT_NIC_SCHED = [
   policy = 1
]

#DEFAULT_SCHED = [
#   policy = 3,
#   rank   = "- (RUNNING_VMS * 50  + FREE_CPU)"
#]

LOG = [
  system      = "file",
  debug_level = 3
]
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
We've been trying to reproduce this without success. Could you send the oned.log file for the process where the error shown up.

**Comment by tkald** [comment]
Couldn't find any error in oned.log in that time frame as those containers were booted up after minor delay, only as unprivileged ones. They did get ip addresses as result of missing LXD_SECURITY_PRIVILEGED key.

I've unforunately modified that template since then I can't produce that issue either at the moment.

**Comment by rsmontero** [comment]
closing this as worksforme, we'll reopen it with more information as could not be reproduced. Thanks!
