### ISSUE TITLE
Marketplace appliances list not cleaned properly

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3017]
**Description**
It may happen the list of Marketplace appliances in the OpenNebula isn't cleaned properly, if there is clash in the names. E.g.:

```
$ onemarketapp list --csv | grep openSUSE
7,openSUSE 42 - KVM,5.6.0,10G,rdy,img,07/19/17,OpenNebula Public,0
36,openSUSE 42 - KVM,5.8.0-1.20190222,10G,rdy,img,02/26/19,OpenNebula Public,0
33,openSUSE 15 - KVM,5.6.0,10G,rdy,img,07/19/17,OpenNebula Public,0
38,openSUSE 15 - KVM,5.8.0-1.20190222,10G,rdy,img,02/26/19,OpenNebula Public,0
```

But, they refer to different appliance UUIDs, one of them doesn't exist anymore:

```
$ onemarketapp  show 7 | egrep 'SOURCE|IMPORT_ID'
SOURCE         : http://marketplace.opennebula.systems//appliance/d98fbbda-a621-4bae-8e82-db13828d3cd2/download/0
IMPORT_ID="d98fbbda-a621-4bae-8e82-db13828d3cd2"

$ onemarketapp  show 36 | egrep 'SOURCE|IMPORT_ID'
SOURCE         : http://marketplace.opennebula.systems//appliance/1da8e400-8f08-4f58-aa09-cd1a2a425bed/download/0
IMPORT_ID="1da8e400-8f08-4f58-aa09-cd1a2a425bed"
```

**Expected behavior**
1. duplicate names shouldn't be allowed
2. obsolete appliances are cleaned

**Details**
 - Affected Component: Marketplace
 - Version: 5.6+

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Names are unique, there is a constraint in the table:

`CREATE TABLE marketplaceapp_pool (oid INTEGER PRIMARY KEY, name VARCHAR(128), body MEDIUMTEXT, uid INTEGER, gid INTEGER, owner_u INTEGER, group_u INTEGER, other_u INTEGER, UNIQUE(name,uid));`

**Comment by vholer** [comment]
Maybe the change affected the functionality and other tests:

```
This command didn't succeed as expected:
  onemarketapp delete 455
  [one.marketapp.delete] Error getting marketplaceapp [455].
```

Reopening to validate the fix again.

**Comment by rsmontero** [comment]
Merged additional fix
