### ISSUE TITLE
Creating persistent image via sunstone (web)

### ISSUE THREAD

**Issue by pumpkineggs** [OpenNebula/one#3018]
**Description**
Creating new persistent image from sunstone does not work.

**To Reproduce**
Just create a new empty datablock and set persistent to YES.
After creating check out details about the image (Info tab, Persistent - No).

**Expected behavior**
The new image should be persistent. 

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.6 to 5.8

**Additional context**
Creating new persistent image via cli works fine.
It seems like it is because of misspelling in html template for select element:
sunstone/public/app/tabs/images-tab/form-panels/create/wizard.hbs
Section:
```
          <div class="large-4 columns">
            <select id="img_persistent">
              <option val=""></option>
              <option val="YES"> {{tr "YES"}}</option>
              <option val="NO"> {{tr "NO"}}</option>
            </select>
          </div>
```
We changed all "val=" to "value=" and rebuild sunstone - this fixed the problem.
The issue started when dropdown list appeared in code instead of checkbox.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Need testing + docu

**Comment by jloboescalona2** [comment]
PR for merge: 
- one: #3200 into master and one-.8
- docs: OpenNebula/docs#579 into one-5.8-maintenance
- development: OpenNebula/development#590 into master and one-5.8

**Comment by tinova** [comment]
good job!
