### ISSUE TITLE
LXD Template Wizard: Clean OS & CPU section

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3025]
**Description**
Leave only boot order field in BOOT section, the rest of the fields are meaningless for LXD drivers.

![2019-03-05-000617_1007x625_scrot](https://user-images.githubusercontent.com/16429804/53785656-e65c9600-3ede-11e9-9705-18d0dc64946f.png)

**Use case**
Improve VM Template GUI user experience

**Interface Changes**
Sunstone

**Additional Context**
Maybe root device field can be left just in case it might be used later.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4490
- Docs: https://github.com/OpenNebula/docs/pull/1036
- Tests: https://github.com/OpenNebula/development/pull/915
