### ISSUE TITLE
LXC config sudo failures

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3029]
**Description**
On Ubuntu < 18.10, the LXD drivers run `lxc config show` which is not enabled for the oneadmin:

Example:

```
Mar 05 11:30:38 ubuntu1804-61499 sudo[8268]: pam_unix(sudo:session): session closed for user root
Mar 05 11:30:38 ubuntu1804-61499 sudo[8275]: oneadmin : TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/bin/lsblk -J
Mar 05 11:30:38 ubuntu1804-61499 sudo[8275]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 05 11:30:38 ubuntu1804-61499 sudo[8275]: pam_unix(sudo:session): session closed for user root
Mar 05 11:30:39 ubuntu1804-61499 sudo[8292]: pam_unix(sudo:auth): conversation failed
Mar 05 11:30:39 ubuntu1804-61499 sudo[8292]: pam_unix(sudo:auth): auth could not identify password for [oneadmin]
Mar 05 11:30:39 ubuntu1804-61499 sudo[8292]: oneadmin : command not allowed ; TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/usr/bin/lxc config show one-2
Mar 05 11:30:39 ubuntu1804-61499 sudo[8293]: oneadmin : TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/sbin/brctl show
Mar 05 11:30:39 ubuntu1804-61499 sudo[8293]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 05 11:30:39 ubuntu1804-61499 sudo[8293]: pam_unix(sudo:session): session closed for user root
Mar 05 11:30:39 ubuntu1804-61499 sudo[8301]: pam_unix(sudo:auth): conversation failed
Mar 05 11:30:39 ubuntu1804-61499 sudo[8301]: pam_unix(sudo:auth): auth could not identify password for [oneadmin]
Mar 05 11:30:39 ubuntu1804-61499 sudo[8301]: oneadmin : command not allowed ; TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/usr/bin/lxc config show one-2
Mar 05 11:30:39 ubuntu1804-61499 sudo[8302]: oneadmin : TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/sbin/iptables -S
Mar 05 11:30:39 ubuntu1804-61499 sudo[8302]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 05 11:30:39 ubuntu1804-61499 sudo[8302]: pam_unix(sudo:session): session closed for user root
```

Obviously, the failed command run is ignored and only generates a lot of authentication errors. 

Looks like this command is enabled only on Ubuntu 18.10+ to workaround some problem with snaps:
https://github.com/OpenNebula/packages/commit/b6c3d3b9c56a89eecf3c79de7336923796ead3e2

**Expected behavior**
1. No authentication failures
a) command must be enabled everywhere
b) or, command is run only on platforms it's expected to work
2. OpenNebula doesn't ignore the command failure

**Details**
 - Affected Component: Virtualization Driver
 - Hypervisor: LXD
 - Version: 5.8.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Steps to reproduce:

1. get clean Ubuntu 18.04
2. get MiniONE `wget https://github.com/OpenNebula/minione/releases/download/v5.8.0/minione`
3. deploy `bash minione --lxd`
4. login Sunstone, run available C7 template
5. grep authentication log `egrep 'fail|identify|allowed' /var/log/auth.log | tail`

And, get e.g.:

```
Mar  6 09:41:24 ubuntu sudo: oneadmin : command not allowed ; TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/usr/bin/lxc config show one-0
Mar  6 09:42:22 ubuntu sudo: pam_unix(sudo:auth): conversation failed
Mar  6 09:42:22 ubuntu sudo: pam_unix(sudo:auth): auth could not identify password for [oneadmin]
Mar  6 09:42:22 ubuntu sudo: oneadmin : command not allowed ; TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/usr/bin/lxc config show one-0
Mar  6 09:42:22 ubuntu sudo: pam_unix(sudo:auth): conversation failed
Mar  6 09:42:22 ubuntu sudo: pam_unix(sudo:auth): auth could not identify password for [oneadmin]
Mar  6 09:42:22 ubuntu sudo: oneadmin : command not allowed ; TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/usr/bin/lxc config show one-0
Mar  6 09:47:24 ubuntu sudo: pam_unix(sudo:auth): conversation failed
Mar  6 09:47:24 ubuntu sudo: pam_unix(sudo:auth): auth could not identify password for [oneadmin]
Mar  6 09:47:24 ubuntu sudo: oneadmin : command not allowed ; TTY=unknown ; PWD=/var/lib/one ; USER=root ; COMMAND=/usr/bin/lxc config show one-0
```

I confess I don't know how the drivers work inside, but if this is the responsible part of code:
https://github.com/OpenNebula/one/blob/214ec6b491cd7a2fb47ea41a7f72c527e55cae47/src/vnm_mad/remotes/lib/nic.rb#L115-L120
... it obviously doesn't get any valid result on the first try even on Ubuntu 18.04 and fall back to sudo, which also fails (because, sudo is not enabled on Ubuntu 18.04). Then, I would expect the **result is tested again for nil** and whole operation should most likely fail, because you didn't get anything from those 2 commands and only silently continue... ?

**Comment by rsmontero** [comment]
Before applying this I want to understand the issue, if the suggested part of the code is responsible for this, dumpxml is going to be nil and the drivers are not going to find the tap's. However the network configuration is working. 

@dann1 please can you bring some light?
