### ISSUE TITLE
LXC: Support for snapshots

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3034]
**Description**
Allow LXC nodes to create VM snapshots

**Interface Changes**
Virtualization Drivers

**Additional Context**
Live snapshots require CRIU

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Jason-2020** [comment]
Besides snapshot, is there any way to backup LXD VMs?

**Comment by christian7007** [comment]
Evaluate this for LXC

**Comment by tinova** [comment]
wontfix
