### ISSUE TITLE
LXD: Support for migration

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3035]
**Description**
Allow LXD nodes to migrate VMs using `migrate` and `migrate live` actions

**Interface Changes**
Virtualization Drivers

**Additional Context**
Live migration requires CRIU

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by alitvak69** [comment]
Have you tried the migration manually?  Does it work?

**Comment by dann1** [comment]
only poweroff migration works, 	`migrate` and `migrate_local` actions in LXD are currently, basically `exit 1`

**Comment by alitvak69** [comment]
I wanted to play with lxd features and noticed that you currently support a stable 3.0.4.  Any sense to move to 3.0.14 for bug fixes and more features?  If so will your code support  it?

**Comment by dann1** [comment]
I believe you mean lxd 3.14, the stable no LTS, it's simply untested,
however, I believe the packaging enforces lxd LTS, lxd 3.12 broke
operations with snap based setups. You can try with version 5.8.1 which
doesn't enforce a specific LXD version and automatically installs latest
stable snap on 1810

**Comment by alitvak69** [comment]
Thank you.  Will do.

**Comment by Jason-2020** [comment]
LXD Live migration is much needed feature for sure! :D

**Comment by ilhaan** [comment]
Does this being closed mean LXD containers in ONE will never get live migration?

**Comment by dann1** [comment]
At the moment we are working on a LX**C** driver, any major feature related to containers will be implemented on that driver instead.

**Comment by ilhaan** [comment]
Awesome. Thanks @dann1!
