### ISSUE TITLE
Add option to upload files in Sunstone support integration

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3037]
**Description**
Currently in Sunstone there is no option to upload a file using the support integration, you have to go to the support portal and upload there.

**Use case**
Upload files using the integration. 

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
to be considered in https://github.com/OpenNebula/one/issues/5905
