### ISSUE TITLE
Review sudoers and merge LXD commands

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3046]
**Description**
This is a follow up of https://github.com/OpenNebula/one/pull/577. Sudoers should be updated:

- obsolete: mkfs
- obsolete: mkswap
- LXD: merge LXD commands into main sudoers, but don't include them automatically https://github.com/OpenNebula/one/blob/master/src/vmm_mad/remotes/lib/lxd/opennebula-lxd
- LXD: get rid of hack on Ubuntu 18.10+ 
https://github.com/OpenNebula/packages/blob/800dac0c66bf93783fb04e1edfb74d09d779ad62/templates/ubuntu1810-debian/opennebula-node-lxd.postinst#L8
- update LXD node package just to include ONE_MAPPER command list
- update or maybe drop(??) oficially oficially unsupported platforms
- perhaps obsolete: iscsiadm (https://github.com/OpenNebula/one/issues/794)

**Details**
 - Affected Component: Packaging
 - Version: 5.8, development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Does https://github.com/OpenNebula/one/blob/acff31e2404901f96e4513c1bb182d3b1be3f202/share/sudoers/sudo_commands.rb#L35 classifies as obsolete as well ?

**Comment by vholer** [comment]
I would drop it.

There is a dedicated add-on for the Xen, so this should be added into the information about what commands the OpenNebula requires access over sudo.

**Comment by vholer** [comment]
Final PRs to be merged into master:
- one https://github.com/OpenNebula/one/pull/3786
- packages https://github.com/OpenNebula/packages/pull/108
- docs https://github.com/OpenNebula/docs/pull/776
