### ISSUE TITLE
No VNC after upgrade

### ISSUE THREAD

**Issue by UAnton** [OpenNebula/one#3056]
**Description**
After update 5.6 to 5.8 VNC stop working on all VMs.

**To Reproduce**
Update 5.6 with working VNC to 5.8.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: ESXi 6.7U2
 - Version: 5.8

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Can you send us the output of a onevm show -x, of a VM with VNC activated (that is currently not working)?

**Comment by UAnton** [comment]
`<VM>
  <ID>34</ID>
  <UID>0</UID>
  <GID>0</GID>
  <UNAME>oneadmin</UNAME>
  <GNAME>oneadmin</GNAME>
  <NAME>web.skillserver.net - CL1</NAME>
  <PERMISSIONS>
    <OWNER_U>1</OWNER_U>
    <OWNER_M>1</OWNER_M>
    <OWNER_A>0</OWNER_A>
    <GROUP_U>0</GROUP_U>
    <GROUP_M>0</GROUP_M>
    <GROUP_A>0</GROUP_A>
    <OTHER_U>0</OTHER_U>
    <OTHER_M>0</OTHER_M>
    <OTHER_A>0</OTHER_A>
  </PERMISSIONS>
  <LAST_POLL>1552550321</LAST_POLL>
  <STATE>3</STATE>
  <LCM_STATE>3</LCM_STATE>
  <PREV_STATE>3</PREV_STATE>
  <PREV_LCM_STATE>3</PREV_LCM_STATE>
  <RESCHED>0</RESCHED>
  <STIME>1552314391</STIME>
  <ETIME>0</ETIME>
  <DEPLOY_ID>vm-14172</DEPLOY_ID>
  <MONITORING>
    <CPU><![CDATA[2.97]]></CPU>
    <DISKRDBYTES><![CDATA[0]]></DISKRDBYTES>
    <DISKRDIOPS><![CDATA[0]]></DISKRDIOPS>
    <DISKWRBYTES><![CDATA[3297280]]></DISKWRBYTES>
    <DISKWRIOPS><![CDATA[28]]></DISKWRIOPS>
    <GUEST_IP_ADDRESSES><![CDATA[62.149.20.2,62.149.20.3,fe80::250:56ff:fead:3a41,172.16.11.55,fe80::250:56ff:feb7:8fbc]]></GUEST_IP_ADDRESSES>
    <MEMORY><![CDATA[2308096]]></MEMORY>
    <NETRX><![CDATA[20480]]></NETRX>
    <NETTX><![CDATA[757760]]></NETTX>
    <STATE><![CDATA[a]]></STATE>
    <VCENTER_ESX_HOST><![CDATA[172.16.20.103]]></VCENTER_ESX_HOST>
    <VCENTER_GUEST_STATE><![CDATA[running]]></VCENTER_GUEST_STATE>
    <VCENTER_RP_NAME><![CDATA[Resources]]></VCENTER_RP_NAME>
    <VCENTER_VMWARETOOLS_RUNNING_STATUS><![CDATA[guestToolsRunning]]></VCENTER_VMWARETOOLS_RUNNING_STATUS>
    <VCENTER_VMWARETOOLS_VERSION><![CDATA[10336]]></VCENTER_VMWARETOOLS_VERSION>
    <VCENTER_VMWARETOOLS_VERSION_STATUS><![CDATA[guestToolsUnmanaged]]></VCENTER_VMWARETOOLS_VERSION_STATUS>
  </MONITORING>
  <TEMPLATE>
    <AUTOMATIC_DS_REQUIREMENTS><![CDATA[("CLUSTERS/ID" @> 100)]]></AUTOMATIC_DS_REQUIREMENTS>
    <AUTOMATIC_NIC_REQUIREMENTS><![CDATA[("CLUSTERS/ID" @> 100)]]></AUTOMATIC_NIC_REQUIREMENTS>
    <AUTOMATIC_REQUIREMENTS><![CDATA[(CLUSTER_ID = 100) & !(PUBLIC_CLOUD = YES)]]></AUTOMATIC_REQUIREMENTS>
    <CONTEXT>
      <DISK_ID><![CDATA[2]]></DISK_ID>
      <ETH0_CONTEXT_FORCE_IPV4><![CDATA[]]></ETH0_CONTEXT_FORCE_IPV4>
      <ETH0_DNS><![CDATA[]]></ETH0_DNS>
      <ETH0_EXTERNAL><![CDATA[]]></ETH0_EXTERNAL>
      <ETH0_GATEWAY><![CDATA[]]></ETH0_GATEWAY>
      <ETH0_GATEWAY6><![CDATA[]]></ETH0_GATEWAY6>
      <ETH0_IP><![CDATA[62.149.21.6]]></ETH0_IP>
      <ETH0_IP6><![CDATA[fe80::250:56ff:fead:3a41]]></ETH0_IP6>
      <ETH0_IP6_PREFIX_LENGTH><![CDATA[64]]></ETH0_IP6_PREFIX_LENGTH>
      <ETH0_IP6_ULA><![CDATA[]]></ETH0_IP6_ULA>
      <ETH0_MAC><![CDATA[00:50:56:ad:3a:41]]></ETH0_MAC>
      <ETH0_MASK><![CDATA[]]></ETH0_MASK>
      <ETH0_MTU><![CDATA[]]></ETH0_MTU>
      <ETH0_NETWORK><![CDATA[]]></ETH0_NETWORK>
      <ETH0_SEARCH_DOMAIN><![CDATA[]]></ETH0_SEARCH_DOMAIN>
      <ETH0_VLAN_ID><![CDATA[]]></ETH0_VLAN_ID>
      <ETH0_VROUTER_IP><![CDATA[]]></ETH0_VROUTER_IP>
      <ETH0_VROUTER_IP6><![CDATA[]]></ETH0_VROUTER_IP6>
      <ETH0_VROUTER_MANAGEMENT><![CDATA[]]></ETH0_VROUTER_MANAGEMENT>
      <ETH1_CONTEXT_FORCE_IPV4><![CDATA[]]></ETH1_CONTEXT_FORCE_IPV4>
      <ETH1_DNS><![CDATA[]]></ETH1_DNS>
      <ETH1_EXTERNAL><![CDATA[]]></ETH1_EXTERNAL>
      <ETH1_GATEWAY><![CDATA[]]></ETH1_GATEWAY>
      <ETH1_GATEWAY6><![CDATA[]]></ETH1_GATEWAY6>
      <ETH1_IP><![CDATA[172.16.11.55]]></ETH1_IP>
      <ETH1_IP6><![CDATA[fe80::250:56ff:feb7:8fbc]]></ETH1_IP6>
      <ETH1_IP6_PREFIX_LENGTH><![CDATA[64]]></ETH1_IP6_PREFIX_LENGTH>
      <ETH1_IP6_ULA><![CDATA[]]></ETH1_IP6_ULA>
      <ETH1_MAC><![CDATA[00:50:56:b7:8f:bc]]></ETH1_MAC>
      <ETH1_MASK><![CDATA[]]></ETH1_MASK>
      <ETH1_MTU><![CDATA[]]></ETH1_MTU>
      <ETH1_NETWORK><![CDATA[]]></ETH1_NETWORK>
      <ETH1_SEARCH_DOMAIN><![CDATA[]]></ETH1_SEARCH_DOMAIN>
      <ETH1_VLAN_ID><![CDATA[]]></ETH1_VLAN_ID>
      <ETH1_VROUTER_IP><![CDATA[]]></ETH1_VROUTER_IP>
      <ETH1_VROUTER_IP6><![CDATA[]]></ETH1_VROUTER_IP6>
      <ETH1_VROUTER_MANAGEMENT><![CDATA[]]></ETH1_VROUTER_MANAGEMENT>
      <NETWORK><![CDATA[YES]]></NETWORK>
      <SSH_PUBLIC_KEY><![CDATA[]]></SSH_PUBLIC_KEY>
      <TARGET><![CDATA[hda]]></TARGET>
    </CONTEXT>
    <CPU><![CDATA[4]]></CPU>
    <DISK>
      <ALLOW_ORPHANS><![CDATA[NO]]></ALLOW_ORPHANS>
      <CLONE><![CDATA[NO]]></CLONE>
      <CLONE_TARGET><![CDATA[SYSTEM]]></CLONE_TARGET>
      <CLUSTER_ID><![CDATA[100]]></CLUSTER_ID>
      <DATASTORE><![CDATA[SSD(IMG)]]></DATASTORE>
      <DATASTORE_ID><![CDATA[100]]></DATASTORE_ID>
      <DEV_PREFIX><![CDATA[sd]]></DEV_PREFIX>
      <DISK_ID><![CDATA[0]]></DISK_ID>
      <DISK_SNAPSHOT_TOTAL_SIZE><![CDATA[0]]></DISK_SNAPSHOT_TOTAL_SIZE>
      <DISK_TYPE><![CDATA[FILE]]></DISK_TYPE>
      <IMAGE><![CDATA[web.skillserver.net]]></IMAGE>
      <IMAGE_ID><![CDATA[55]]></IMAGE_ID>
      <IMAGE_STATE><![CDATA[8]]></IMAGE_STATE>
      <LN_TARGET><![CDATA[NONE]]></LN_TARGET>
      <OPENNEBULA_MANAGED><![CDATA[NO]]></OPENNEBULA_MANAGED>
      <ORIGINAL_SIZE><![CDATA[51199]]></ORIGINAL_SIZE>
      <PERSISTENT><![CDATA[YES]]></PERSISTENT>
      <READONLY><![CDATA[NO]]></READONLY>
      <SAVE><![CDATA[YES]]></SAVE>
      <SIZE><![CDATA[51199]]></SIZE>
      <SOURCE><![CDATA[web.skillserver.net/web.skillserver.net.vmdk]]></SOURCE>
      <TARGET><![CDATA[sda]]></TARGET>
      <TM_MAD><![CDATA[vcenter]]></TM_MAD>
      <TYPE><![CDATA[FILE]]></TYPE>
      <VCENTER_DS_REF><![CDATA[datastore-101]]></VCENTER_DS_REF>
      <VCENTER_INSTANCE_ID><![CDATA[cce41cb8-f4e1-489d-ba08-484ca617caa4]]></VCENTER_INSTANCE_ID>
    </DISK>
    <DISK>
      <ALLOW_ORPHANS><![CDATA[NO]]></ALLOW_ORPHANS>
      <CLONE><![CDATA[NO]]></CLONE>
      <CLONE_TARGET><![CDATA[SYSTEM]]></CLONE_TARGET>
      <CLUSTER_ID><![CDATA[100]]></CLUSTER_ID>
      <DATASTORE><![CDATA[SSD(IMG)]]></DATASTORE>
      <DATASTORE_ID><![CDATA[100]]></DATASTORE_ID>
      <DEV_PREFIX><![CDATA[sd]]></DEV_PREFIX>
      <DISK_ID><![CDATA[1]]></DISK_ID>
      <DISK_SNAPSHOT_TOTAL_SIZE><![CDATA[0]]></DISK_SNAPSHOT_TOTAL_SIZE>
      <DISK_TYPE><![CDATA[FILE]]></DISK_TYPE>
      <IMAGE><![CDATA[web.skillserver.net_1]]></IMAGE>
      <IMAGE_ID><![CDATA[56]]></IMAGE_ID>
      <IMAGE_STATE><![CDATA[8]]></IMAGE_STATE>
      <LN_TARGET><![CDATA[NONE]]></LN_TARGET>
      <OPENNEBULA_MANAGED><![CDATA[NO]]></OPENNEBULA_MANAGED>
      <ORIGINAL_SIZE><![CDATA[51200]]></ORIGINAL_SIZE>
      <PERSISTENT><![CDATA[YES]]></PERSISTENT>
      <READONLY><![CDATA[NO]]></READONLY>
      <SAVE><![CDATA[YES]]></SAVE>
      <SIZE><![CDATA[51200]]></SIZE>
      <SOURCE><![CDATA[web.skillserver.net/web.skillserver.net_1.vmdk]]></SOURCE>
      <TARGET><![CDATA[sdb]]></TARGET>
      <TM_MAD><![CDATA[vcenter]]></TM_MAD>
      <TYPE><![CDATA[FILE]]></TYPE>
      <VCENTER_DS_REF><![CDATA[datastore-101]]></VCENTER_DS_REF>
      <VCENTER_INSTANCE_ID><![CDATA[cce41cb8-f4e1-489d-ba08-484ca617caa4]]></VCENTER_INSTANCE_ID>
    </DISK>
    <GRAPHICS>
      <LISTEN><![CDATA[0.0.0.0]]></LISTEN>
      <PORT><![CDATA[5901]]></PORT>
      <TYPE><![CDATA[vnc]]></TYPE>
    </GRAPHICS>
    <IMPORTED><![CDATA[YES]]></IMPORTED>
    <MEMORY><![CDATA[4096]]></MEMORY>
    <NIC>
      <AR_ID><![CDATA[2]]></AR_ID>
      <BRIDGE><![CDATA[External]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[vcenter_port_groups]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[100]]></CLUSTER_ID>
      <IP><![CDATA[62.149.21.6]]></IP>
      <IP6><![CDATA[fe80::250:56ff:fead:3a41]]></IP6>
      <MAC><![CDATA[00:50:56:ad:3a:41]]></MAC>
      <NAME><![CDATA[NIC0]]></NAME>
      <NETWORK><![CDATA[External]]></NETWORK>
      <NETWORK_ID><![CDATA[0]]></NETWORK_ID>
      <NIC_ID><![CDATA[0]]></NIC_ID>
      <OPENNEBULA_MANAGED><![CDATA[NO]]></OPENNEBULA_MANAGED>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-34-0]]></TARGET>
      <VCENTER_INSTANCE_ID><![CDATA[cce41cb8-f4e1-489d-ba08-484ca617caa4]]></VCENTER_INSTANCE_ID>
      <VCENTER_NET_REF><![CDATA[dvportgroup-143]]></VCENTER_NET_REF>
      <VCENTER_PORTGROUP_TYPE><![CDATA[Distributed Port Group]]></VCENTER_PORTGROUP_TYPE>
      <VN_MAD><![CDATA[vcenter]]></VN_MAD>
    </NIC>
    <NIC>
      <AR_ID><![CDATA[1]]></AR_ID>
      <BRIDGE><![CDATA[Skillvps]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[vcenter_port_groups]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[100]]></CLUSTER_ID>
      <IP><![CDATA[172.16.11.55]]></IP>
      <IP6><![CDATA[fe80::250:56ff:feb7:8fbc]]></IP6>
      <MAC><![CDATA[00:50:56:b7:8f:bc]]></MAC>
      <NAME><![CDATA[NIC1]]></NAME>
      <NETWORK><![CDATA[Skillvps]]></NETWORK>
      <NETWORK_ID><![CDATA[2]]></NETWORK_ID>
      <NIC_ID><![CDATA[1]]></NIC_ID>
      <OPENNEBULA_MANAGED><![CDATA[NO]]></OPENNEBULA_MANAGED>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-34-1]]></TARGET>
      <VCENTER_INSTANCE_ID><![CDATA[cce41cb8-f4e1-489d-ba08-484ca617caa4]]></VCENTER_INSTANCE_ID>
      <VCENTER_NET_REF><![CDATA[dvportgroup-870]]></VCENTER_NET_REF>
      <VCENTER_PORTGROUP_TYPE><![CDATA[Distributed Port Group]]></VCENTER_PORTGROUP_TYPE>
      <VN_MAD><![CDATA[vcenter]]></VN_MAD>
    </NIC>
    <SECURITY_GROUP_RULE>
      <PROTOCOL><![CDATA[ALL]]></PROTOCOL>
      <RULE_TYPE><![CDATA[OUTBOUND]]></RULE_TYPE>
      <SECURITY_GROUP_ID><![CDATA[0]]></SECURITY_GROUP_ID>
      <SECURITY_GROUP_NAME><![CDATA[default]]></SECURITY_GROUP_NAME>
    </SECURITY_GROUP_RULE>
    <SECURITY_GROUP_RULE>
      <PROTOCOL><![CDATA[ALL]]></PROTOCOL>
      <RULE_TYPE><![CDATA[INBOUND]]></RULE_TYPE>
      <SECURITY_GROUP_ID><![CDATA[0]]></SECURITY_GROUP_ID>
      <SECURITY_GROUP_NAME><![CDATA[default]]></SECURITY_GROUP_NAME>
    </SECURITY_GROUP_RULE>
    <TM_MAD_SYSTEM><![CDATA[vcenter]]></TM_MAD_SYSTEM>
    <VCPU><![CDATA[4]]></VCPU>
    <VMID><![CDATA[34]]></VMID>
  </TEMPLATE>
  <USER_TEMPLATE>
    <DESCRIPTION><![CDATA[vCenter Template imported by OpenNebula from Cluster ]]></DESCRIPTION>
    <HYPERVISOR><![CDATA[vcenter]]></HYPERVISOR>
    <LOGO><![CDATA[images/logos/ubuntu.png]]></LOGO>
    <VCENTER_CCR_REF><![CDATA[domain-c7]]></VCENTER_CCR_REF>
    <VCENTER_DS_REF><![CDATA[datastore-101]]></VCENTER_DS_REF>
    <VCENTER_ESX_HOST><![CDATA[172.16.20.103]]></VCENTER_ESX_HOST>
    <VCENTER_INSTANCE_ID><![CDATA[cce41cb8-f4e1-489d-ba08-484ca617caa4]]></VCENTER_INSTANCE_ID>
  </USER_TEMPLATE>
  <HISTORY_RECORDS>
    <HISTORY>
      <OID>34</OID>
      <SEQ>0</SEQ>
      <HOSTNAME>CL1</HOSTNAME>
      <HID>0</HID>
      <CID>100</CID>
      <STIME>1552314392</STIME>
      <ETIME>0</ETIME>
      <VM_MAD><![CDATA[vcenter]]></VM_MAD>
      <TM_MAD><![CDATA[vcenter]]></TM_MAD>
      <DS_ID>101</DS_ID>
      <PSTIME>1552314392</PSTIME>
      <PETIME>1552314392</PETIME>
      <RSTIME>1552314392</RSTIME>
      <RETIME>0</RETIME>
      <ESTIME>0</ESTIME>
      <EETIME>0</EETIME>
      <ACTION>0</ACTION>
      <UID>-1</UID>
      <GID>-1</GID>
      <REQUEST_ID>-1</REQUEST_ID>
    </HISTORY>
  </HISTORY_RECORDS>
</VM>
`

**Comment by tinova** [comment]
all seems fine in the XML.

* Is the VM running in 172.16.20.103?
* Can you telnet 172.16.20.103 from the font-end, port 5901?
* is there any error in /var/log/one/novnc.log?

**Comment by UAnton** [comment]
After upgrade to 5.8.1 and reboot all ESXi hosts all works fine.
