### ISSUE TITLE
LXD Marketplace Wizard: Allow to set parameters

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3059]
**Description**
Whe creating/updating a LXD marketplace there is no graphic field for its [configurable attributes](http://docs.opennebula.org/5.8/advanced_components/marketplace/market_lxd.html#configuration) it has to be done via advanced view

**Use case**
Increase usability

**Interface Changes**
Sunstone

**Additional Context**
![2019-03-09-141717_915x374_scrot](https://user-images.githubusercontent.com/16429804/54146782-58107480-43f6-11e9-9483-45e3ce738078.png)
![2019-03-09-141141_924x328_scrot](https://user-images.githubusercontent.com/16429804/54146783-58a90b00-43f6-11e9-8571-9712ef58c7a2.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:

- One: https://github.com/OpenNebula/one/pull/4524
- Docs: https://github.com/OpenNebula/docs/pull/1050
- Tests: https://github.com/OpenNebula/development/pull/920
