### ISSUE TITLE
Migrate from Ruby amazon-ec2 to supported aws-sdk* gems

### ISSUE THREAD

**Issue by shaba** [OpenNebula/one#3061]
amazon-ec2 not supported sinse 2010 year.
on homepage https://github.com/grempe/amazon-ec2 i can see:
`WARNING : You probably don't want this code. Its archived and ancient and probably doesn't work. Try the official AWS Ruby SDK instead.
`

**Comment by rsmontero** [comment]
IPAM and new Elastic AWS Drivers now uses:

require 'aws-sdk-ec2'

**Comment by vholer** [comment]
The comment was more targetting econe, `amazon-ec2` is still in Gemfiles. Reopening.

**Comment by tinova** [comment]
no longer applies, econe has been discontinued
