### ISSUE TITLE
API - create one.vmpool.infoextended

### ISSUE THREAD

**Issue by futzi** [OpenNebula/one#3076]
**Description**
In 5.8 the API call one.vmpool.info was changed to return only a subset of information of the XML. This is a good idea in general to speed up the API calls.
The issue is now: If you rely on additional information which is not returned you need additional API calls for each VM the additional information is required for.
This finally increases massively the time for external processes.

Perhaps it is possible to enhance the API in two ways (optionally)
- Create a one.vmpool.infoextended call which behaves as until 5.6 (return all information). This should be faster anyway if you create the right filters so you reduce the amount of data returned and also the overall number of API calls
- Alternatively allow adding the required data/xml as parameter

**Use case**
API driven additional interfaces/tools, monitoring etc.

**Interface Changes**
API: Add one.vmpool.infoextended call

**Additional Context**
none

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
I think the first option may be better. (At least straight-forward to implement)

I don't know the specific workflow of your application, but getting the whole list of VMs will sooner or later impact the response time. So I'd recommend either caching the pool (using the new proposed API call) or using the new search functionality in 5.8. You can list VMs with a specific attribute IP="10.0.0.1" for example, that would probably give you a much sorter list... 

[See the documentation here.
](http://docs.opennebula.org/5.8/operation/vm_management/vm_instances.html?highlight=search#searching-vm-instances)

**Comment by futzi** [comment]
Hi Ruben - yes - I think, option 1 is the better way to go and also easy to be implemented on client side.
We are already caching the lists for a certain time  - and using the new filter it has boosted the calls really well - many thanx for this.
