### ISSUE TITLE
Problem importing vCenter template using Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3081]
**Description**
When the username in vCenter has a backslash (`\`), Sunstone codify it so the username is not valid.

**To Reproduce**
Have a username with (`\`) on it.

**Expected behavior**
The backslash doesn't have to be codified.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 5.8 and development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@OpenNebulaSupport  need more information for replicate this error

**Comment by tinova** [comment]
closing as we cannot reproduce, please add more info on how to create the problematic user
