### ISSUE TITLE
Service JSON body is corrupted after updating the body of the document

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3085]
**Description**
After updating the body of the service document by onedb update command the JSON files get corrupted.

**To Reproduce**
Update one service by using the onedb command.

**Expected behavior**
The body gets update and the JSON is not corrupted.

**Details**
 - Affected Component: flow
 - Version: 5.8

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
We cannot reproduce it.
