### ISSUE TITLE
Undefined method error shown whith oneflow show command.

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3086]
**Description**
An undefined method error is shown when oneflow command is executed.

**Details**
 - Affected Component: CLI
 - Version: 5.8.0

**Additional context**
Here is the trace:

/bin/oneflow:283:in `block in show_service': undefined method `emtpty?' for []:Array (NoMethodError)
	from /bin/oneflow:255:in `each'
	from /bin/oneflow:255:in `show_service'
	from /bin/oneflow:461:in `block (2 levels) in <main>'
	from /usr/lib/one/ruby/cli/command_parser.rb:470:in `call'
	from /usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
	from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
	from /bin/oneflow:389:in `new'
	from /bin/oneflow:389:in `<main>

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
The bug was fixed here: https://github.com/OpenNebula/one/commit/7702af2e392ee7cb624f1c23bb93157147c6cbb3
