### ISSUE TITLE
When using VLAN with vCenter the vlan id is not shown on Sunstone

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3087]
**Description**
When using VLAN with vCenter the vlan id is not shown on Sunstone. This happens because the vlan id for vCenter is stored in VCENTER_VLAN_ID tag instead of VLAN_ID

**Details**
 - Affected Component: Sunstone

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova,  PRs to approve:
-ONE: https://github.com/OpenNebula/one/pull/3711
-Docs: https://github.com/OpenNebula/docs/pull/763
