### ISSUE TITLE
Misleading non persistent message in instantiate message

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3095]
**Description**

"Non-persistent disk. The changes will be lost once the VM is shut down"

should read

"Non-persistent disk. The changes will be lost once the VM is terminated (ie changes to DONE state)"

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Code and documentation updated (see commits above)

No test needed.
