### ISSUE TITLE
Make configurable the number of VM Templates displayed in Cloud View

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3096]
**Description**

Now there is a fixed number of choices and pages.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
duplicated by #4126
