### ISSUE TITLE
Disable Network "Automatic selection" on VM template instantiation screen

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3102]
Allow administrators to remove Network "Automatic selection" on Sunstone's VM template instantiation screen:

![image](https://user-images.githubusercontent.com/33811723/54711913-9998d200-4b10-11e9-8856-04eec7838d0d.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- ONE: https://github.com/OpenNebula/one/pull/4723
- Docs: https://github.com/OpenNebula/docs/pull/1121

**Comment by tinova** [comment]
test pending

**Comment by sbbarragan** [comment]
PRs to merge:
- dev: OpenNebula/development/pull/1041
