### ISSUE TITLE
VM hook not getting related history record

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3108]
**Description**
When VM hook is triggered (at least for NIC hot-plug), the only HISTORY_RECORD entry contained in the passed VM XML is not related to the (NIC hot-plug) action, but is the stub record placed after the related action.

E.g.,

```
      <RETIME>0</RETIME>
      <ESTIME>0</ESTIME>
      <EETIME>0</EETIME>
      <ACTION>0</ACTION>
      <UID>-1</UID>
      <GID>-1</GID>
      <REQUEST_ID>-1</REQUEST_ID>
    </HISTORY>
  </HISTORY_RECORDS>
```

Notes about steps done inside:
1. Closes the current record to signal the change in the VM. Updates action
2. Creates a new history entry for the new status
3. Updates operation
4. Hook is invoked with VM template including only the last history record, which is the new open one, no action defined.

**Expected behavior**
History record in the passed XML template is related to the action which triggers the hook.

**Details**
 - Affected Component: Core
 - Version: 5.8.0, development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Note. Last history record may relate to the new action and relevant information may be included in the previous system record. This should be address with the improvements in the hook system
