### ISSUE TITLE
Problem adding schedule actions with no end

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#3109]
**Description**
When you try to add an schedule action in Sunstone withtout end, you get the following error:

```
[one.vm.update] Cannot update template. Error END_VALUE defined but not valid END_TYPE found)
```

**To Reproduce**
Add and schedule action without end.

**Details**
 - Affected Component: Sunstone
 - Version: development 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Also, the first action has the ID empty and it should be 0.

**Comment by jloboescalona2** [comment]
@tinova PR to aprove:
-ONE: https://github.com/OpenNebula/one/pull/3792
-Docs: https://github.com/OpenNebula/docs/pull/786

**Comment by jloboescalona2** [comment]
only the id was repaired because I can't create scheduled action without an end date
