### ISSUE TITLE
Manage IP address information when a VM is imported from vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3112]
**Description**
When a VM is imported from vCenter OpenNebula only takes care about MAC addresses information, it will be useful to manage also IP addresses information.

**Use case**
Import a VM from vCenter and assign the virtual network lease corresponding to the IP address of the VM to it.  

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
PR: https://github.com/OpenNebula/one/pull/3301 --> master, -->one-5.8??
Doc: https://github.com/OpenNebula/docs/pull/608 --> one-5.8-maintenance

**Comment by tinova** [comment]
well done!!
