### ISSUE TITLE
Consider for compact memory before running VM

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3124]
**Description**
Somtimes my VMs can't start with the next error:

```
[Z0][VMM][I]: error: internal error: process exited while connecting to monitor: ioctl(KVM_CREATE_VM) failed: 12 Cannot allocate memory
[Z0][VMM][I]: failed to initialize KVM: Cannot allocate memory
```

But after `echo 1 > /proc/sys/vm/compact_memory `everything start working fine.

My idea is to add this action to the kvm driver, and call it before any VM is start.

**Use case**

Avoid problems caused with high memory fragmentation on the host.

More info here:
https://stackoverflow.com/questions/46464785/cannot-allocate-memory-despite-free-reporting-available

**Interface Changes**

Modify `deploy` action for the kvm driver.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Today we faced with the same problem, even with the compact memory enabled. I just found another trick, which is working fine for me:

```
echo 3 > /proc/sys/vm/drop_caches
echo 1 > /proc/sys/vm/compact_memory
```

@vholer consider adding `sysctl vm.drop_caches=3` as well 

FYI

**Comment by RussianNeuroMancer** [comment]
@kvaps, as someone who seen similar issue I would like to ask you:

> even with the compact memory enabled

Do you mean you running modified build of OpenNebula in production, or compact_memory action could be added via some configuration file or hook?

**Comment by kvaps** [comment]
Yes, we're using the patch https://github.com/OpenNebula/one/pull/3126, and set `COMPACT_MEMORY=yes` already for one year, we are started having less problem connected with this error, but sometimes they are still happening. Today I've tried `echo 3 > /proc/sys/vm/drop_caches` as well and my VM is started working fine after that

**Comment by RussianNeuroMancer** [comment]
[Hopefully relevant news](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-2020-RAM-Compaction).

**Comment by vholer** [comment]
Implemented as configurable feature by @paczerny 
http://docs.opennebula.io/5.13/installation_and_configuration/open_cloud_host_setup/kvm_driver.html#compact-memory-optional
