### ISSUE TITLE
LXD Centos6 container images fail to SET_HOSTNAME after 1st deployment 

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3132]
**Description**
Containers from the public LXD image server fail to correctly set hostname by SET_HOSTNAME contextualization variable.

**To Reproduce**
- Deploy the centos6 app with `SET_HOSTNAME` context variable from the LXD marketplace
- poweroff the vm and boot it again
	- hostname will be `vm_name`

**Expected behavior**

**Details**
 - Affected Component: Hypervisor
 - Hypervisor: LXD
 - Version: 5.8.0

**Additional context**
vanilla centos6 containers from public LXD image servers pack with a `/etc/init/lxc-sysinit.conf` file

```
[root@one-12 ~]# cat /etc/init/lxc-sysinit.conf 
start on startup
env container

pre-start script
    if [ "x$container" != "xlxc" -a "x$container" != "xlibvirt" ]; then
        stop;
    fi

    rm -f /var/lock/subsys/*
    rm -f /var/run/*.pid
    [ -e /etc/mtab ] || ln -s /proc/mounts /etc/mtab
    mkdir -p /dev/shm
    mount -t tmpfs -o nosuid,nodev tmpfs /dev/shm

    initctl start tty TTY=console
    telinit 3
    exit 0
end script
```

Commenting `telinit 3` seems to solve the issue 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This issue has been documented in the knwon issues page. closing
