### ISSUE TITLE
Ceph (RBD) trash support

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#3147]
**Description**
Since Ceph Luminous (12.2.x) there is support for putting RBD images in a "trash" bin (namespace). Instead of directly deleting an image from a pool the image can be put in the "trash" instead.

**Use case**
By putting an IMAGE in the "trash" it provides the user / admin the possibility to undo unwanted delete actions without relying on backups. This might avoid accidental data loss in case someone accidentally deletes an IMAGE or a TEMPLATE including disk images.

**Interface Changes**
This change will need adjustments from drivers, Sunstone as well as CLI / API commands. An overview of IMAGES in "trash" as well as a way to definitively get rid of them.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Merge to master:
* https://github.com/OpenNebula/one/pull/3341
* https://github.com/OpenNebula/infra/pull/258
* https://github.com/OpenNebula/development/pull/627
* https://github.com/OpenNebula/docs/pull/627

**Comment by rsmontero** [comment]
Hi @hydro-b 

The target implementation is roughly as follows:

* New CEPH_TRASH attribute for the ceph datastores

**Comment by rsmontero** [comment]
Hi @hydro-b 

Overview of the implementation

* New CEPH_TRASH attribute for the datastores and disk
* A disk includes CEPH_TRASH = yes all rbd rm operations are replaced by rbd trash move
* This attribute can be set per DISK to only move to trash that given disk, or globally at DS level
* When a disk contains snapshots all the snapshots are also moved to trash

Compared with your original request we are not implementing an OpenNebula side inspection of the CEPH_TRASH.
