### ISSUE TITLE
ZONE_NAME header gets stripped by passenger

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#3157]
**Description**
ZONE_NAME header gets stripped by passenger

**To Reproduce**
change zone using sunstone + passenger

**Expected behavior**
zone should be changed

**Details**
 - Affected Component: Sunstone

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Needs testing
