### ISSUE TITLE
unexpected boolean in XMLRPC one.vmpool.calculateshowback method response

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3174]
**Description**
Following the XMLRPC API documentation the method [one.vmpool.calculateshowback](http://docs.opennebula.org/5.8/integration/system_interfaces/api.html#one-vmpool-calculateshowback) should have "empty" or the error _string_ as its second argument but _boolean_ is returned:

```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param>
    <value>
      <array>
        <data>
          <value>
            <boolean>1</boolean>
          </value>
          <value>
            <boolean>1</boolean>
          </value>
          <value>
            <i4>0</i4>
          </value>
        </data>
      </array>
    </value>
    </param>
  </params>
</methodResponse>
```

**To Reproduce**
Do XMLRPC call for _one.vmpool.calculateshowback_ 

```
<?xml version="1.0"?>
<methodCall>
  <methodName>one.vmpool.calculateshowback</methodName>
  <params>
    <param>
    <value>
      <string>oneadmin:a3bb9df47c0c5e12b9f4073ef0a791098ad88c36</string>
    </value>
    </param>
    <param>
    <value>
      <i4>-1</i4>
    </value>
    </param>
    <param>
    <value>
      <i4>-1</i4>
    </value>
    </param>
    <param>
    <value>
      <i4>-1</i4>
    </value>
    </param>
    <param>
    <value>
      <i4>-1</i4>
    </value>
    </param>
  </params>
</methodCall>
```
And look at the method response.

**Expected behavior**
Expecting a string

**Details**
 - Affected Component: [api]
 - Hypervisor: [n/a]
 - Version: [5.8.0]

**Additional context**
If could be a documentation issue, though.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs to merge to 5.8 and master:
* code: #3718
* docs: OpenNebula/docs#764
