### ISSUE TITLE
VM Groups are malformed when creating through Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3192]
**Description**
When a VM Group is created using Sunstone, the host affinity is not present after the creation.

**To Reproduce**
Create a VM Group through Sunstone and set host affinity.

![Untitled](https://user-images.githubusercontent.com/33811723/55615022-a95e1a80-578e-11e9-8669-9b10559cc1c4.png)

```
ROLES                                                                           
ID   NAME     POLICY       AFFINED_HOSTS      ANTI_AFFINED_HOST  VIRTUAL_MACHINES    
0    testing_ AFFINED      -                  -
```

**Expected behavior**
There should be a list of affined hosts.

```
ROLES                                                                           
ID   NAME     POLICY       AFFINED_HOSTS      ANTI_AFFINED_HOST  VIRTUAL_MACHINES    
0    apps     -            0,1                -
```

**Details**
 - Affected Component: Sunstone
 - Version: development

**Additional context**
Through the CLI it works perfectly, for example, with this template:

```
NAME = "testing"

ROLE = [
    NAME         = "apps",
    HOST_AFFINED = "0,1"
]
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This issue cannot be replicated.
Will reopen if additional feedback is given.
![image](https://user-images.githubusercontent.com/59608355/81266267-c7a6e180-9044-11ea-813d-b288b19ed973.png)
