### ISSUE TITLE
Lock VM mark disappears after reload

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#3193]
**Description**
VM lock mark (black stripe) disappears in Sunstone after the page reload

**To Reproduce**
Lock VM, reload page

**Expected behavior**
Lock mark still visible

**Details**
 - Affected Component: Sunstone
 - Version: 5.8

**Additional context**
The `onevm show <id> | grep LOCK` still shows `LOCK: Use` correctly. Looks like sunstone only issue.

Originally reported in forum:
https://forum.opennebula.org/t/locked-vm-are-no-longer-visible-in-sunstone/7113

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
It seems that Sunstone is using the new short body field and locks are not included in this field.
