### ISSUE TITLE
support-tab visibility not manageable via sunstone yaml files

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3204]
**Description**
The (not)supported tab is always hovering in the sunstone views even when the _support-tab_ is not listed in the _enabled_tabs_ in _/etc/one/sunstone-views/\*/\*.yaml_ files.

**To Reproduce**
Comment-out the _support-tab_ and restart sunstone in the yamls.
The support tab is visible or hovering around in all views - admin, groupadmin, user and cloud

**Expected behavior**
The support-tab should disappear from the interface

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.8.1]

**Additional context**
It looks like the bug is introduced with commit 78604cc8.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mathijsmm** [comment]
I would really like to see this fixed in 5.8.2 or atleast some info on a workaround

**Comment by Madko** [comment]
you can add:
`display: none;`
line 90 in /usr/lib/one/sunstone/public/css/custom.css
(block #menu #li_support-tab a)

**Comment by atodorov-storpool** [comment]
Thanks it definitely works ! But I believe that the current state is a bug that should be fixed...

**Comment by atodorov-storpool** [comment]
Thank you for the efforts @shaba !

Would you mind to check the Cloud view too?

**Comment by atodorov-storpool** [comment]
Confirming the patch is working! (first test does not replaced the sunstone package...)

**Comment by kvaps** [comment]
@shaba thank you for your fix, I can confirm that it is working.

Quick solution to apply it on running instances:
```
sed 's/\(!SunstoneCfg.tabs\[support_tab\]\)/\1 \&\& Config.isTabEnabled(support_tab)/' \
  -i /var/lib/one/sunstone/main.js
```

**Comment by mzealey** [comment]
> @shaba thank you for your fix, I can confirm that it is working.
> 
> Quick solution to apply it on running instances:
> 
> ```
> sed 's/\(!SunstoneCfg.tabs\[support_tab\]\)/\1 \&\& Config.isTabEnabled(support_tab)/' \
>   -i /var/lib/one/sunstone/main.js
> ```
> 
> however it will work until next service restart

below should keep it persistent over restarts...

```
sed 's/\(!SunstoneCfg.tabs\[support_tab\]\)/\1 \&\& Config.isTabEnabled(support_tab)/' -i /usr/lib/one/sunstone/public/dist/main-dist.js /usr/lib/one/sunstone/public/dist/main.js
```

**Comment by sbbarragan** [comment]
@tinova PRs to merge:
- one: #4585 
- docs: OpenNebula/docs/pull/1075

**Comment by kvaps** [comment]
Why this PR is not merged? 🤔

**Comment by atodorov-storpool** [comment]
ONE 5.13.80 (6.0 beta) docs still says that this is possible:
http://docs.opennebula.io/5.13/configuration_guide/web_interfaces_configuration/sunstone_configuration.html#commercial-support-integration
