### ISSUE TITLE
Way to disable migrate poweroff/poweroff-hard option in Sunstone groupadmin view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3215]
**Description**
Groupadmin and normal users shouldn't be able to see infrastructure details, so this option should be disable by default in Sunstone groupadmin and user views.

**To Reproduce**
Click on the migrate button in Sunstone.

**Expected behavior**
Groupadmin and normal users shouldn't see that option by default.

**Details**
 - Affected Component: Sunstone
 - Version: development

**Additional context**
![](https://opennebula.zendesk.com/attachments/token/NTccI2NDZNv9AceVcGA0xFZq6/?name=migrate-option.PNG)

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tais** [comment]
This is mainly just the part of two missing lines in the view files, you can add the following to the VM part of the view files, works like a charm in 5.8.1.
```
            VM.migrate_poff: false
            VM.migrate_poff_hard: false
```

Add this somewhere in the same location as the other two migrate options, eg the link

https://github.com/OpenNebula/one/blob/master/src/sunstone/etc/sunstone-views/kvm/user.yaml#L374
