### ISSUE TITLE
vm and template CDROM info is not imported 

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#3224]
**Description**
When you import a vcenter template or a wild vm with a cdrom drive, this information is not imported into opennebula.

**To Reproduce**
Import a vcenter template having a cdrom drive or create a vm with a cdrom drive into vcenter, after that import it into opennebula. 
"onetemplate show <template_id>" and "onevm show <vm_id>" will not show info about the existing cdrom drive.

**Expected behavior**
"onetemplate show <template_id>" and "onevm show <vm_id>" should show information about the cdrom drives.

**Details**
 - Affected Component: Sunstone, Scheduler
 - Hypervisor: ESXi
 - Version: All versions

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
This is already fixed in master and one-5.10.

We are closing this issue until any one report any problem about it.
