### ISSUE TITLE
vcenter vm can't boot due to invalid cdrom config

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#3225]
**Description**
A vcenter vm will not boot if there is an invalid cdrom configuration such as having a cdrom drive as slave in a bus without master. For example, having only a drive in bus IDE[0:1] is an invalid configuration.
When you import a template or a wild vm with a cdrom and you add a cdrom image from opennebula, this situation can be produced.

**To Reproduce**
1. Create a vm in vcenter server with a cdrom drive attached to SATA[0:0].
2. Import this wild vm from opennebula
3. Attach a cdrom image to the instance, ( opennebula usually set as IDE[0:1] )
4. Try to power on the instance, it'll probably returns a "Module 'DevicePowerOn' power on failed." because IDE[0:1] doesn't have a master associate ( IDE[0:0] )

**Expected behavior**
The cdrom image should be attached to the existing cdrom drive or take care about the bus positions to avoid those invalid configurations.

**Details**
 - Affected Component: Core, Scheduler, Sunstone
 - Hypervisor: ESXi
 - Version: All versions

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Related to #3224

**Comment by mouyaq** [comment]
Branch created:
https://github.com/OpenNebula/one/tree/b-3225

**Comment by mouyaq** [comment]
PR crated: https://github.com/OpenNebula/one/pull/3424

**Comment by tinova** [comment]
Nice! Needs docs + testing

**Comment by mouyaq** [comment]
PR to Doc (resolved issues 583 ) https://github.com/OpenNebula/docs/pull/661

**Comment by mouyaq** [comment]
PR to Doc ( add comments about limitations on IDE Devices ) https://github.com/OpenNebula/docs/pull/662

**Comment by mouyaq** [comment]
PR to Development: new test created
https://github.com/OpenNebula/development/pull/649
