### ISSUE TITLE
[GOCA] Migrate from glide to Go Modules

### ISSUE THREAD

**Issue by eripa** [OpenNebula/one#3227]
**Description**
The GOCA library should use the official Go modules functionality to manage dependencies instead of Glide.

**Use case**
Using Go modules enables better tool and system integration. https://github.com/golang/go/wiki/Modules

**Interface Changes**
N/A

**Additional Context**
`go mod init` supports automatic migration of glide managed dependencies.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by treywelsh** [comment]
Note to the reviewer, it needs at least the version 1.11 of Go
