### ISSUE TITLE
Parse error when saving VM in new template

### ISSUE THREAD

**Issue by jakubjancicka** [OpenNebula/one#3232]
**Description**
When you want to save VM as a template in cloud view and use multi-word description, you'll get parse error.

**To Reproduce**
In cloud view, create and shutdown VM. Then use the "Save in a new Template" button. Type multi-word description and save Virtual Machine to Template. You'll get error:
 `[one.template.update] Cannot update template. Parse error: syntax error, unexpected COMMA, expecting EQUAL or EQUAL_EMPTY at line 543520288, column 30:32`

**Expected behavior**
VM Template saved successfully.

**Details**
 - Affected Component: [Sunstone]
 - Version: [5.4,5.8]

**Additional context**
Problem is in file `one/src/oca/ruby/opennebula/virtual_machine.rb` on line 819 `replace << "DESCRIPTION = #{description}\n"` - variable description is not escaped. 

Fix: `replace << "DESCRIPTION = \"#{description}\"\n"`

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Thanks a lot for the fix!
