### ISSUE TITLE
Provision template extends multiple templates

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3237]
**Description**
We already support chaining of several provision templates with the `extends:` parameter. This parameter can contain only reference to a single template. It would be useful to support a list of multiple templates to extend from and recursively evaluate them in the order they are written. For example:

```
---
extends:
  - template1.yaml
  - template2.yaml
  - template3.yaml
  - template4.yaml
...
```

**Use case**
Provide a separate templates for virtual networks and datastores, and be able to include both of them from a single template.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

Code: https://github.com/OpenNebula/one/pull/3352
Docs: https://github.com/OpenNebula/docs/pull/632

**Comment by vholer** [comment]
Consider this Ruby gem to implement the extends in a clear and sane way:
https://www.rubydoc.info/gems/yaml_extend/0.2.5

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4470
- docs: https://github.com/OpenNebula/docs/pull/1034
- tests: https://github.com/OpenNebula/development/pull/909
