### ISSUE TITLE
Deleting an active snapshot does not selects previous one as active

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3248]
**Description**
When you remove snapshot which is marked as active, we have no any active snapshots anymore.

**To Reproduce**
* Make sure that disk have `ALLOW_ORPHANS=yes`
* Create snap0
* Create snap1
* Remove snap1

**Expected behavior**
* Snap0 marked with `ACTIVE=YES`

**Details**

 - Affected Component: oned
 - Hypervisor: kvm
 - Version: 5.8.1

**Additional context**

## Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Can you specify using which datastore you observe this issue? Supposing it's the same setup also for https://github.com/OpenNebula/one/issues/3250, right?

**Comment by kvaps** [comment]
I developing new driver for linstor, and faced with this problem.
https://github.com/OpenNebula/addon-linstor_un

> Supposing it's the same setup also for #3250, right?

Yes, but problem is more global, and will affect all datastores with `ALLOW_ORPHANS=yes` option

**Comment by paczerny** [comment]
Tested with ssh datastore and selecting previous snapshot as active doesn't make sense.
Data are stored in working copy of the disk. The snapshot is just a copy of the disk in the past. It does not store any new data. Deleting the active snapshot has no effect on actual working copy.
In ssh storage marking snapshot as active is kind of useless and should be removed.

@kvaps Don't know how snapshot works in Linstor, have you consider using ALLOW_ORPHANS=mixed?

**Comment by paczerny** [comment]
Marking previous snapshot as active is not a good solution as allow_orphans=yes can be used also for ssh datastorage, where marking previous snapshot as active doesn't make sense
