### ISSUE TITLE
NUMA aware placement for KVM

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#3256]
**Description**
This issue is to implement placement constraints on NUMA nodes. A VM can be pinned on a node based on:

* PCI affinity
* Memory affinity
* Manual node assigment

**Use case**
Improve performance of VM by making memory and/or I/O access to the same NUMA node.

**Interface Changes**
New atrributes to set NUMA placement preferences:
```
NUMA = [
   NODE_POLICY = <PCI | MEMORY | AUTO | MANUAL >
   ALLOCATION_POLICY = <DEDICATED | NODE >
   NUMA_NODE_ID = <>
   HUGE_PAGE_SIZE_MB = <>
]
```

NUMA node selection (`NODE_POLICY` attribute):
* PCI affinity. Place the VM in the same numa node as the PCI passthrough devices. If multiple devices are present the VM will be placed in the node of the first one.
* MEMORY guided. Place the VM in the first numa node with enough free memory
* MANUAL place the VM in the given node 
* AUTO: : As assgined by numad implies (default):
```
<numatune>
        <memory mode='strict' placement='auto'/>
</numatune>
...
<vcpu placement='auto'>2</vcpu>
```
vCPU and Memory will be assigned according to `ALLOCATION_POLICY` as follows: 
* NODE: OpenNebula will pin the vCPUs an memory to the selected NUMA core resources. (default)
```
<vcpu placement='static' cpuset='0-13,28-41'>2</vcpu>
...
<numatune>
        <memory mode='strict' nodeset='0'/>
</numatune>
```
Other VMs can be assigned to the same NUMA cores in the node.

* DEDICATED: Same as node but each vCPU is pinned to an specific NUMA core. OpenNebula will also mark this node as used and will not be assigned to any other VM.  
```
<cputune> 
  <vcpupin vcpu='0' cpuset='0'/> 
  <vcpupin vcpu='1' cpuset='2'/> 
 </cputune> 
 ```

**Additional Context**
N/A

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
IMHO #2349 could be counted as extension to this topic?

When selecting a cpuset to prefer HT on same core.
For this to work the Host monitor shuld be extended to report the cpu topology (neded for NUMA anyway)

The tricky part will be the (live)migration because a new set of cpus should be provided via domain XML for libvirt to know how to remap the processors during the migration.

Also, a VCPU topology should be considered too - to resolve the limit of sockets in the Windows guests, for example.

**Comment by rsmontero** [comment]
Thanks Anton. Definitely the other two #2349 + detailed virtual cpu topology needs to be addressed with this one.

**Comment by rsmontero** [comment]
For the records, in this issue we'll track:
* #590 
* #2349

**Comment by atodorov-storpool** [comment]
I'd like to note that AMD EPYC has NUMA topology that differ from Intel's one. Not sure will it be handled by the monitoring probe, but probably should be taken in account for the scheduler...
```bash
[root@s29 ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          4
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD EPYC 7251 8-Core Processor
Stepping:              2
CPU MHz:               2100.000
CPU max MHz:           2100.0000
CPU min MHz:           1200.0000
BogoMIPS:              4199.47
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              4096K
NUMA node0 CPU(s):     0,1,8,9
NUMA node1 CPU(s):     2,3,10,11
NUMA node2 CPU(s):     4,5,12,13
NUMA node3 CPU(s):     6,7,14,15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid amd_dcm aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb hw_pstate retpoline_amd ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
```
```bash
[root@s29 ~]# lscpu -e
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE MAXMHZ    MINMHZ
0   0    0      0    0:0:0:0       yes    2100.0000 1200.0000
1   0    0      1    1:1:1:1       yes    2100.0000 1200.0000
2   1    0      2    2:2:2:2       yes    2100.0000 1200.0000
3   1    0      3    3:3:3:3       yes    2100.0000 1200.0000
4   2    0      4    4:4:4:4       yes    2100.0000 1200.0000
5   2    0      5    5:5:5:5       yes    2100.0000 1200.0000
6   3    0      6    6:6:6:6       yes    2100.0000 1200.0000
7   3    0      7    7:7:7:7       yes    2100.0000 1200.0000
8   0    0      0    0:0:0:0       yes    2100.0000 1200.0000
9   0    0      1    1:1:1:1       yes    2100.0000 1200.0000
10  1    0      2    2:2:2:2       yes    2100.0000 1200.0000
11  1    0      3    3:3:3:3       yes    2100.0000 1200.0000
12  2    0      4    4:4:4:4       yes    2100.0000 1200.0000
13  2    0      5    5:5:5:5       yes    2100.0000 1200.0000
14  3    0      6    6:6:6:6       yes    2100.0000 1200.0000
15  3    0      7    7:7:7:7       yes    2100.0000 1200.0000
```

```bash
[root@s29 ~]# numactl -H
available: 4 nodes (0-3)
node 0 cpus: 0 1 8 9
node 0 size: 0 MB
node 0 free: 0 MB
node 1 cpus: 2 3 10 11
node 1 size: 16297 MB
node 1 free: 12799 MB
node 2 cpus: 4 5 12 13
node 2 size: 0 MB
node 2 free: 0 MB
node 3 cpus: 6 7 14 15
node 3 size: 16370 MB
node 3 free: 14962 MB
node distances:
node   0   1   2   3 
  0:  10  16  16  16 
  1:  16  10  16  16 
  2:  16  16  10  16 
  3:  16  16  16  10 
```
Also note that it is possible to have NUMA node without directly attached memory...

Similar topology could be emulated with custom cpu configuration for a VM on intel KVM host ;)

**Comment by rsmontero** [comment]
Currently the probes are accesing to sysfs, as described here:

https://www.kernel.org/doc/Documentation/cputopology.txt

This generate a list of CORES as:
CORE = [ NODE_ID = "0", ID = "0", CPUS = "0,2"]                                
CORE = [ NODE_ID = "0", ID = "1", CPUS = "1,3"]  

This CPUS to CORE relationship is used to generate viable topologies based on the VM template and the desired schedule policy. So far the scheduler is not assuming any topology, just that defined in the host.

**Comment by rsmontero** [comment]
About memory, its currently WIP but also using sysfs  /sys/devices/system/node/node0/meminfo

Not really sure about your comment on "node without directly attached memory..."

**Comment by atodorov-storpool** [comment]
Attacging the content of _/sys/devices/system/node_ on an EPYC node
[numa-node.tar.gz](https://github.com/OpenNebula/one/files/3173274/numa-node.tar.gz)

**Comment by rsmontero** [comment]
Anton, I was thinking maybe its easier to just run :

https://github.com/OpenNebula/one/blob/f-3256/src/im_mad/remotes/node-probes.d/numa.rb

Its a simple ruby scripts no dependencies. It should output the information that would be sent to OpenNebula

**Comment by rsmontero** [comment]
There are some strange links in the cpus folders, (e.g. no topology information for the CPUs)

Also meminfo lists 0 KB of memory. I guess that's what you are refereing to....

BTW, We're developing against 4.10 and 3.10  kernels,

**Comment by atodorov-storpool** [comment]
The host is CentOS 7 so the kernel is 3.10.0
the script is failing on the hugepages:

```bash
[root@s29 anton]# ./numa.rb
./numa.rb:68:in `open': No such file or directory - /sys/bus/node/devices//node0/hugepages (Errno::ENOENT)
	from ./numa.rb:68:in `foreach'
	from ./numa.rb:68:in `block in <main>'
	from ./numa.rb:57:in `foreach'
	from ./numa.rb:57:in `<main>'
```
Because numa0 has no memory... IMO you should check for memory only on the NUMAs listed in _/sys/devices/system/node/has_memory_

It is a little bit weird setup with memory sticks not populated on all DIMMs but a working one and perfect for such tests ;)

**Comment by atodorov-storpool** [comment]
commented-out the failing loop in hugepages and here is the output:
```bash
[root@s29 anton]# ./numa.rb
CORE = [ NODE_ID = "0", ID = "0", CPUS = "0,8"]
CORE = [ NODE_ID = "0", ID = "4", CPUS = "1,9"]
CORE = [ NODE_ID = "1", ID = "8", CPUS = "2,10"]
CORE = [ NODE_ID = "1", ID = "12", CPUS = "3,11"]
CORE = [ NODE_ID = "2", ID = "16", CPUS = "4,12"]
CORE = [ NODE_ID = "2", ID = "20", CPUS = "5,13"]
CORE = [ NODE_ID = "3", ID = "24", CPUS = "6,14"]
CORE = [ NODE_ID = "3", ID = "28", CPUS = "7,15"]
```

**Comment by rsmontero** [comment]
Perfect thanks Anton, specially for the memory setups. CPU wise seems ok. We'll work on the memory part later. I'll sync back with you....

Thanks again for testing

**Comment by rsmontero** [comment]
@atodorov-storpool The code for NUMA topologies and pinning is now merged. Documentation is here:

http://docs.opennebula.org/5.9/advanced_components/numa/numa.html

and code is in the master branch. It'd be great if you could give it a try ;)

**Comment by feldsam** [comment]
Hello, great work! I tested in in lab, and it is working good, but have one problem with this setup.

I have mixed hosts in infrastructure. Some have pinning enabled, and some not. Pinning and topology setup is suitable for some usages, but not all, because of missing ability to overprovision.

To gain the best performance in CPU overprovision setup, I use following defaults in `vmm_exec_kvm.conf` file:

```
RAW      = "
<cpu mode='custom' match='exact'>
    <model fallback='forbid'>Haswell-noTSX-IBRS</model>
    <feature policy='require' name='vmx'/>
    <feature policy='require' name='rdrand'/>
    <feature policy='require' name='pcid'/>
    <feature policy='require' name='pdpe1gb'/>
    <feature policy='require' name='md-clear'/>
</cpu>
<numatune>
    <memory mode='strict' placement='auto'/>
</numatune>
<memoryBacking>
    <hugepages/>
</memoryBacking>
<devices>
    <memballoon model='none'/>
</devices>
"
```

but I hit problem with incompatibility with OpenNebula Numa topology setting, because there is conflict in <numatune> and <memoryBacking> XML nodes. The only solution is to define this XML per VM basis in the VM template, which is not handy.

I am calling for extending this issue to have an ability set defaults when VM is deploying to non-pinning hosts. Probably extending mentioned config vmm_exec_kvm.conf or some per-host configuration?

Thank you in advance for considering this.

**Comment by paczerny** [comment]
Hi, I'm currently working on #3673. Not only CPU_MODEL, but all configuration options from vmm_exec_kvm.conf will be possible to specify in cluster or in the host.
The priority of the values will be VM > Host > Cluster > config file

But the RAW configuration option works slightly different now. The RAW from the config file is added to the VM RAW. This behavior must preserve. So the logic for RAW will be: use VM RAW and add first RAW option from Host, Cluster or config file.

**Comment by feldsam** [comment]
Hi, thanks for reply. I think that my request is more related to this #3664 because what I doing in raw xml, is de facto pinning to numa node and enabling hugepages.
