### ISSUE TITLE
Allow LXD drivers to remap the image filesystem

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3258]
**Description**
Through the use of `security.privileged` LXD can start a container as **privileged** or **unprivileged**. When the key is set to true/false, on the next start action, the container will be started as privileged or unprivileged. On the next start action, if the value of `security.privileged` differs, at the time of starting, differs from the last value when the container started, the container rootfs will be remapped accordingly. 

Currently, the LXD drivers do not perform that remmaping, due to the fact that the container is deleted during the OpenNebula shutdown action. This limits the support to deploying privileged and unprivileged containers to the conditions of the image rootfs. If the image has the set of ids belonging to the root user, like the KVM images and the images from the LXD marketplace, the VM created from that image will only work properly under `LXD_SECURITY_PRIVILEGED = true`. Then, in order to create an unprivileged container, the user would have to provide an image with the set of ids stated in the default lxd profile. 

**Use case**
- Deploy a privileged or unprivileged container regardless of the image id set.
- More compatibility with KVM apps from the marketplace by avoiding stating `LXD_SECURITY_PRIVILEGED = true`

**Additional Context**
There is a tool called fuidshift that could help with this

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by JPaulMora** [comment]
Hi, I too am interested in running/converting all my images to unprivileged. Could we move this up the priority list as a way to make ON safer by default?

**Comment by dann1** [comment]
Could you add an emoji upvote for the description ? It helps us keep track on interest.
