### ISSUE TITLE
Unify overcommitment info in one guide

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3266]
**Description**
It would be useful to have the overcommitment information along with the meaning of values like CPU or VCPU, for make easier to understand some tricky concepts.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Hopefully is is clearer now http://docs.opennebula.io/5.13/management_and_operations/capacity_planning/overcommitment.html
