### ISSUE TITLE
I have Sunstone errors when I disable support endpoint

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#3268]
**Description**

If I disable the `support` endpoint in `sunstone-server.conf`, I have error messages on the web interface:

* `Action Support.check not defined`
* `Action Support.checkversion not defined`

**To Reproduce**

1. Disable `support` endpoint `sed -i -e 's,\(- support\),# \1,'  /etc/one/sunstone-server.conf`
2. Restart Sunstone
3. Connect to the sunstone as cloud view user

**Expected behavior**

When I disable the `support` endpoint in the server configuration I should not have any errors in the cloud view.

Maybe related: note that disabling the `support-tab` in the admin/users views do not hide the `Not officially supported` link in the menu.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**

It looks like the API call are made [regardless of the configuration of the view](https://github.com/OpenNebula/one/blob/release-5.8.1/src/sunstone/public/app/tabs/support-tab.js#L68)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by AndrewV666** [comment]
Can you try https://github.com/OpenNebula/one/pull/3569 ?

**Comment by jloboescalona2** [comment]
@tinova, PRs to approve
-ONE: https://github.com/OpenNebula/one/pull/3907
-Docs: https://github.com/OpenNebula/docs/pull/825
