### ISSUE TITLE
OOM killer: onedb purge-done eat too much RAM

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#3269]
**Description**

After upgrading to 5.8.1, I wanted to shrink a little my MySQL database (12GB on disk for 5.6GB uncompressed SQL file).

I tried the `onedb purge-done` command but it was killed by the kernel, causing an Out Of Memory Killer run.

**To Reproduce**

We have 211 768 VMs in our MySQL database since 2014, I just ran `onedb purge-done`.

**Expected behavior**

The command should not eat all the memory.

**Details**
 - Affected Component: Database
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**

@xorel told me to use the `--start` and `--end` option, so I did a purge 3 months by 3 months. It take around 6GB of RAM on our 12GB frontend to run.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
I did not have the same issue with `onedb purge-history`.

**Comment by al3xhh** [comment]
PRs to merge in master and 5.8:

Code: https://github.com/OpenNebula/one/pull/3376
Docs: https://github.com/OpenNebula/docs/pull/635

**Comment by al3xhh** [comment]
Hello @baby-gnu 

I have made an improvement on this, could you please try it and let me know if it works for you?

Thanks!
