### ISSUE TITLE
extend save/restore on KVM VMM_MAD to have both pre and post hooks

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3271]
**Description**
Brief description of the new functionality
Extend VMM_MAD save/restore to call tm_mad pre and post scripts

**Use case**
On System datastores with TM_MAD backed by block devices it is possible to store the checkpoint file directly on block device, skipping the step of storing the file on Host filesystem first.

**Interface Changes**
Extend save and restore on VMM_MAD to have both "pre" and "post" hooks to SYSTEM DS's TM_MAD. With the change the _vmm/save_ script will look for _vmm/save.<tm_mad>-pre_ and _vmm/restore_ will look for _vmm/restore.<tm_mad>-post_. Both pieces of code are borrowed from the existing parts of current save/restore

**Additional Context**
Following the [forum discussion](https://forum.opennebula.org/t/shared-mode-for-the-ceph-based-system-datastires/7164/5)

I think that the ceph TM_MAD could be updated to use this functionality but have no ceph cluster to test it, though.

Pull request #3270

There is alternative solution by @kvaps introduced in #3272 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
link https://github.com/OpenNebula/one/issues/3272

**Comment by atodorov-storpool** [comment]
I am closing #3270 and #3271 in favour of #3272 because this solution could be implemented faster and at the moment with a configuration change that does not violate the OpenNebula Polices.
