### ISSUE TITLE
Import vCenter cluster as host needs to check existing OpenNebula clusters

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3280]
**Description**

If a vCenter cluster is imported as a host, and then deleted, an OpenNebula cluster remains. Upon reimporting, an error is given.

**To Reproduce**

Import a vCenter cluster, delete it, try to reimport again

**Expected behavior**

OpenNebula cluster to be reused, not exception given

**Details**
 - Affected Component: Import mechanism
 - Hypervisor: vCenter
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jmdelafe** [comment]
- [x] Branch created
- [x] Code committed to development branch

**Comment by jmdelafe** [comment]
one: #3317 into 5.8 and master
docs:  OpenNebula/docs#629
development: OpenNebula/development#630

**Comment by tinova** [comment]
LGTM 👍

**Comment by tinova** [comment]
Reverting changes. It's better not to change the semantics of the create cluster function, since we are losing the ability to identify duplicate name creation and state an appropiate error.

Checking should be done in the JS side.

Also, refactoring onevcenter CLI importing function
