### ISSUE TITLE
Import Wild VM in vCenter from Sunstone defaults to host 0

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3281]
**Description**

Importing a Wild VM fails if host id is not 0

**To Reproduce**

Import from a vCenter host with id != 0

**Expected behavior**

To be imported in the right host

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jmdelafe** [comment]
- [x] Branch created #3281
- [x] Code committed to development branch
- [x] Tested using sunstone

**Comment by jmdelafe** [comment]
Some methods needs the first key of the @list hash to be the host_id.

**Comment by jmdelafe** [comment]
one: #3339 into 5.8 and master
docs: OpenNebula/docs#629

**Comment by tinova** [comment]
closing, well done!!
