### ISSUE TITLE
Read driver action on attach_disk using STDIN for vcenter drivers

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#3292]
**Description**
Drv_action is currently being read from an argument. It should be read from STDIN to maintain homogeneity and remove "broken pipe" issue.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
PR: https://github.com/OpenNebula/one/pull/3293   --> master, --> one-5.8

**Comment by tinova** [comment]
perfect, thanks!!
