### ISSUE TITLE
 Allow "reschedule" for VMs in Poweroff State #2138 

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#3298]
**Description**
Currently the scheduler is only able to reschedule VMs in RUNNING or UNKNOWN state. This issue is to be able to reschedule them in POWER-OFF state

**Use case**
When a resize operation is performed a VM is powered-off. if the VM does not fit in the current hypervisor it has to be migrated manually. This issue will allow to resize+reschedule the VM to a new host.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge:
* one: #3681  into master
* development: OpenNebula/development#713 into master
* docs: OpenNebula/docs#747 into master
