### ISSUE TITLE
Alternate deployment mode set by sunstone is not saved

### ISSUE THREAD

**Issue by sam-wouters** [OpenNebula/one#3303]
**Description**
For combining for shared & SSH transfer modes, following attribute must be set in a template: TM_MAD_SYSTEM="ssh".
Through the cli this can be easily set, the sunstone gui has a dropdown "deploy mode" for this, but when setting this to "ssh", the attribute isn't added to the template.

**To Reproduce**
Configure a shared image datastore and a SSH system datastore.
Create or update an existing template through sunstone; under storage options set the deployment mode to "ssh" and save/update the template.

**Expected behavior**
The template should have the following attribute set: TM_MAD_SYSTEM="ssh".

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**
-

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova, PRs to approval:
-ONE: https://github.com/OpenNebula/one/pull/3703
-Docs: https://github.com/OpenNebula/docs/pull/758

**Comment by tinova** [comment]
Needs testing

**Comment by jloboescalona2** [comment]
@tinova, PR test to approval:
-Tests: https://github.com/OpenNebula/development/pull/724
