### ISSUE TITLE
VM custom attributes for some hypervisors are not in the short body

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3308]
**Description**
VMs custom attributes for some hypervisors (vCenter, AWS, ...) like IP addresses are saved in the VM template so they are not included in the short version of the body. This attributes might be necessary like IP addresses for example for be shown in Sunstone.

**To Reproduce**
Go to Instances > VMs view y Sunstone the IP address for a vCenter VM is not shown.

**Expected behavior**
The IP address should be shown.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter, AWS, Azure
 - Version: 5.8.X

**Additional context**
Forum thread: https://forum.opennebula.org/t/ips-not-showing-up-after-upgrade-from-5-6-0-to-5-8-1/7185/4

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
opening a new one for short body fix
