### ISSUE TITLE
Encoding issues on VDCs descriptions

### ISSUE THREAD

**Issue by AdriMenendezM** [OpenNebula/one#3315]
**Description**
VDC's description may have an encoding problem generating de XML file sent through the API. The Java library is not able to decode the file and sets the pullElements attribute to null.

The unhandled exception is:

[Fatal Error] :1:2519: Invalid byte 2 of 3-byte UTF-8 sequence.

**To Reproduce**
Set a VDC description with an accent mark, ie. "máquina", and make a request to the API to get the VDC pool from the Javalibrary.

**Details**
 - Affected Component: XML RPC API
 - Version: 5.8.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Check if related to #3232

**Comment by rsmontero** [comment]
Seems duplicated and fixed
