### ISSUE TITLE
Migrated disk location not reflected in ONE

### ISSUE THREAD

**Issue by AdriMenendezM** [OpenNebula/one#3316]
**Description**
When a migration is done on VM with a persistent image attached to it, the new location of this disk on the vCenter datastore (inside the VM folder) is not reflected in ONE. It shows the original location and path on the DATASTORE and SOURCE attributes of the DISK entry of the VM template. The information of the image shows the original datastore too.

**To Reproduce**
1. Instantiate a VM.
2. Create a persistent empty datablock and attach it to the VM.
3. Migrate the VM between datastores.
4. Try to find the new location of the persistent disk in one.

**Expected behavior**
The VM info of the disk and the image one, should reflect the real location of the disk.

**Details**
 - Affected Component: Storage
 - Hypervisor: vCenter
 - Version: 5.8.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Related to #2762

**Comment by tinova** [comment]
See if we can add this information to existing DISKs

  DISK=[MIGRATED_PATH=""...]

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4476

[DOC]
* https://github.com/OpenNebula/docs/pull/1062
