### ISSUE TITLE
Sometimes the zone changing does not take effect in federation.

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3330]
**Description**
In federation environment, sometimes the zone change does not take effect causing errors like, deleting a VM with the same ID in other zone. 

**Details**
 - Affected Component: Sunstone
 - Version: 5.8.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
cannot reproduce, please add details on how to reproduce if available
