### ISSUE TITLE
Sunstone support token configuration not working behind a proxy

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3331]
**Description**
When Sunstone is configured to use a proxy server, support token configuration is not using that proxy. 

**Details**
 - Affected Component: Sunstone
 - Version: 5.8.1

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
https://github.com/OpenNebula/one/pull/3332 --> master, --> one-5.8
