### ISSUE TITLE
Add Default Zone Endpoint for users

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3335]
**Description**
Store on the user template the last zone it used, allowing it to use the same zone next time it logs in.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
A new bug was introduced in 5.8.3, changing he image of a disk on a VM Template of a vCenter VM causes a JS error due to missing imports. Fixed in repo.
