### ISSUE TITLE
VN_MAD=fw IP spoofing block NIC Aliasses

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3354]
**Description**
Added IPs as NIC aliases are blocked by the firewall on the host

**To Reproduce**
Add a NIC alias to VM interface with `VN_MAD=fw` and try to ping the address from internet.

**Expected behavior**
The alias IP should be reachable.

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [5.8.x]

**Additional context**
The alias IPs are not included in the ipset on the host. Manually adding them to the ipset makes them reachable.
The alias IPs are missing from the libvirt filter too. I mean the _clean-trafic_ rule in the domain XML - there is param entry for the primary ip only.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Looks like it is related related to #3079 
But the IP spoofing filter

**Comment by atodorov-storpool** [comment]
The patch for MAC spoofing filter for #3079 is not so trivial, though. At least on first read. So the patch is for this issue only...

**Comment by atodorov-storpool** [comment]
The above patch resolve the case of VM resume.
Attaching nic is not resolved, trying to handle it with VM_HOOK on HOTPLUG_NIC but it is hard due to #3357 

On a side note - the VM's Template passed to the VM_HOOK on HOTPLUG_NIC event contain flag ATTACH=YES when detaching a nic...

**Comment by atodorov-storpool** [comment]
And the [net_fw_hook](https://github.com/OpenNebula/addon-storpool/blob/master/hooks/net_fw_hook) that handle the hotplug add/remove of a NIC alias

**Comment by rsmontero** [comment]
After discussing this with the team, it is probably a better idea to have pre_alias, post_alias, clean_alias scripts to configure any thing related to the alias interface in the network.

**Comment by atodorov-storpool** [comment]
Working on this (also addressing #869)...

But there is no nokogiri on the nodes. So I am in doubt to install _opennebula-ruby_ on the nodes or to install and use the OS package for _ruby-nokogiri_?

**Comment by atodorov-storpool** [comment]
Forgot to clarify - nokogiri is needed for the HOTPLUG_NIC hook that will handle the live IP ALIAS add/remove

**Comment by atodorov-storpool** [comment]
Some comments on the above commit

In the case when the primary NIC is Ethernet only the iptables rules to handle the ipset(s) are not created - just a sink hole is defined. So the script try to patch these chanis...

Wrote as a separate driver because in the default classes there is no information for the IP aliases.

Using ebtables instead of arptables because ebtables are already installed/available on the hosts.

Also, having everything in separate files allow to add this functionality to current 5.10.0 just by dropping files and defining a hook...

Any comments/sugstions are welcome

**Comment by rdiaz-on** [comment]
This issue has been [fixed](https://github.com/OpenNebula/one/commit/7011820d987b42023942e9c1c7a18da45160768a).
