### ISSUE TITLE
unconsistent NIC/ALIAS_ID

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3357]
**Description**
The value of _VM/TEMPLATE/NIC/ALIAS_IDS_ is broken after adding a second NIC alias

**To Reproduce**
Instantiate VM with single nic with `VN_MAD='fw'` 
    - as expected there is no ALIAS_IDS element
Add alias IP from same network
   - NIC/ALIAS_IDS='0'
   - NIC_ALIAS/ALIAS_ID=0
   - and there is CONTEXT/ETH0_ALIAS0
Add second alias from same network
   - NIC/ALIAS_IDS='1,2'  <-- Should be '0,2'
   - NIC_ALIAS/ALIAS_ID=0
   - NIC_ALIAS/ALIAS_ID=2
   - CONTEXT/ETH0_ALIAS0
   - CONTEXT/ETH0_ALIAS2

**Expected behavior**
I believe that NIC/ALIAS_IDS must match NIC_ALIAS/ALIAS_ID

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [5.8.2]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
NIC_ALIAS/NAME also becomes inconsistent with NIC_ALIAS/ALIAS_ID

NIC/ALIAS_IDS='5,6,7'
but
NIC_ALIAS/ALIAS_ID=0
NIC_ALIAS/NAME='NIC_4_ALIAS5'   <-- matching ALIAS_IDS index: 5
and
CONTEXT/ETH4_ALIAS0_*

**Comment by al3xhh** [comment]
Hello @atodorov-storpool 

The ALIAS_IDS is an array containing the NIC_ID of the ALIAS, not the ALIAS_IDS, that's why it's "1,2" (the same for the name)

I have fixed the bug with ALIAS_ID, so now the ALIAS_ID is consecutive 0,1,2,...

**Comment by al3xhh** [comment]
PRs to merge in master and 5.8:

code: https://github.com/OpenNebula/one/pull/3359
docs: https://github.com/OpenNebula/docs/pull/633

**Comment by atodorov-storpool** [comment]
Confirming that the patch is working :+1: 

So on detach in the HOTPLUG_NIC hook I should match the number after NIC_ALIAS/NAME and if it is missing in the NIC's ALIAS_IDS - it is detach operation?
For example `/NIC_ALIAS[ATTACH="YES"]/NAME` is `NIC4_ALIAS6` so if '6' is missing from the list in `/NIC[NAME="NIC4"]/ALIAS_IDS` (for example we have `5,7`) then the operation is detach
if the number is in the ALIAS_IDS the operation is attach.

Right?

**Comment by al3xhh** [comment]
Yes, you are right!
