### ISSUE TITLE
Sunstone lose NIC index

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3358]
**Description**
Trying to delete second nic (with ID 8)

![image](https://user-images.githubusercontent.com/11386997/57987975-2caea380-7a91-11e9-8849-71df8c8374e5.png)

**To Reproduce**
Add nic
Add some nic aliases to it
Add a second nic
Add some aliases to first nic - not sure is that
Try to delete the second nic

**Expected behavior**
The second nic should be deleted

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.8.2]

**Additional context**
Reloading the brouser (F5) do fix the issue

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve
-One: https://github.com/OpenNebula/one/pull/3795
-Docs: https://github.com/OpenNebula/docs/pull/788
