### ISSUE TITLE
Host stuck in MONITORING_INIT if remote VM has space in name 

### ISSUE THREAD

**Issue by ione-cloud** [OpenNebula/one#3360]
**Description**
Host stuck in MONITORING_INIT if remote VM has space in name, for example vm name is "name_part_1 - Hostname".

In this case receiving this at /var/log/one/oned.log:
Error parsing host 0 information: syntax error, unexpected VARIABLE, expecting COMMA or CBRACKET at line 32719, columns 835:841 

We've fixed it by replacing line 397 at src/vmm_mad/remotes/one/opennebula_driver.rb
from  vms_info << "  VM_NAME=#{vm.name},\n"
to      vms_info << "  VM_NAME=\"#{vm.name}\",\n"

**Details**
 - Affected Component: src/vmm_mad/remotes/one/opennebula_driver.rb
 - Hypervisor: OpenNebula
 - Version: 5.8

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Should be fixed for latest monitord.
