### ISSUE TITLE
Cannot create group with no permissions

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/one#3361]
**Description**
It is not possible to create a group with no permissions. Both Sunstone and "onegroup create" attempt to create an ACL entry for such group, but fail because there are no resources to be added to the ACL.

**To Reproduce**
In the command line: `onegroup create --name testgrp --resources ' '
`

In Sunstone: click on [+] in the Group screen, enter the group name, go to the Permissions tab, and uncheck all checkboxes there (VMs, VNets, Security groups, etc.). Click on Create.

In both cases, the action fails with the following error:
`Error creating group ACL's: [one.acl.addrule] Rule @113 /* CREATE * is malformed: [resource] type is missing`

**Expected behavior**
A new group should be created, with no additional ACL entries.

**Details**
 - Affected Component: Sunstone, onegroup command
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**
Previously discussed here:
https://forum.opennebula.org/t/groups-vdcs-or-clusters-best-practices-wanted/2184/7?u=yenya

I want to create a group intended to be used as a secondary group, with members of this group being able to access a particular VNet (using onevnet chgrp), apart from other resources accessible to the group members based on their primary group. So the group really doesn't need any special permissions.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4377
- docs: https://github.com/OpenNebula/docs/pull/1003
