### ISSUE TITLE
VNF Appliance

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#3375]
Create an appliance with several Virtual Network Functions (VNF).

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
Doc: https://github.com/OpenNebula/marketplace-docs/pull/5 --> master
PR: https://github.com/OpenNebula/infra/pull/264 --> master

**Comment by tinova** [comment]
Needs:

  - extend tests
  - recontextualization feature in framework
  - use Alpine

**Comment by tinova** [comment]
Related to #3375
