### ISSUE TITLE
Federation replication status should be shown in onezone list.

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3378]
**Description**
The information of the last commit replicated in the federation should be shown in `onezone list` command or in `one.zone.info` API call as it is available in an HA environment.

**Use case**
Check replication status o a federation environment.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
**PRs to merge in 5.8**:

code: https://github.com/OpenNebula/one/pull/3412
docs: https://github.com/OpenNebula/docs/pull/651

**PRs to merge in master**:

code: https://github.com/OpenNebula/one/pull/3412
code: https://github.com/OpenNebula/one/pull/3413
