### ISSUE TITLE
Redesign hook system to add new features

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3380]
**Description**
The goal of this new feature is to extend the current hook mechanism to address two common requests:
   - Better feedback on hook execution. Currently it is a fire-and-forget without any feedback (limited to oned.log) and no retry capabilities.
   - Being able to hook on API calls. Currently hooks are mainly based on state changes.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
nice to have hooks executed on device create and delete events
