### ISSUE TITLE
Susntone have no option for set FILTER for the NIC

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3383]
**Description**

I can set:
```
NIC_DEFAULT = [
  FILTER = "allow-arp"
]
```

via CLI but Sunstone interface have no this option.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

In my opinion it should be available to set for the:
- templates (classic vms)
- templates (vrouters)
- virtual networks itself

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs for merge:
• one: #4118  into 5.10 and master
• docs: OpenNebula/docs/pull/903 into one-5.10-maintenance
• development: OpenNebula/development/pull/823 into one-5.10 and master
