### ISSUE TITLE
PyONE ignores VM monitoring elements

### ISSUE THREAD

**Issue by karonpante** [OpenNebula/one#3392]
**Description**
PyONE drops the monitoring elements from a VM.

**To Reproduce**
one.vmpool.infoextended(-2, -1, -1, 3).get_VM()[0].get_MONITORING()

**Expected behavior**
Retrieve following monitoring elements: 'CPU', 'MEMORY', 'NETRX', 'NETTX'.

**Details**
 - Affected Component: PyONE
 - Version: 5.8.1

**Additional context**
The PyONE tool only accepts elements that are present in the XSD file.
As the monitoring elements are commented out in the vm.xsd file these are ignored.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
MONITORING data are no longer (if ever?) available via `one.vmpool.infoextended`. They need to be requested using `one.vm.info`
