### ISSUE TITLE
Reduce amount of disk size consumed by FTS index 

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3393]
**Description**
FTS index used for VM searching is consuming too much disk size.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
As a work around, we can [remove and add the indexes](https://stackoverflow.com/questions/41941925/any-way-to-reduce-fts-index-1-ibd-file-sizes-in-mysql-database-folder) to delete the files and recreate them. For me, it did not work when doing so in a single `ALTER` command:

```
mysql -u opennebula opennebula <EOF
alter table vm_pool drop index ftidx;
alter table vm_pool add fulltext index ftidx (search_token);
EOF
```

**Comment by rsmontero** [comment]
Code its now in one-5.8 and master.

Documentation needs update to include a note on DB maintenance.
