### ISSUE TITLE
Documentation error regarding installation for LXD use

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/one#3419]
**Description**
There is either a Documentation error or files missing from the Repository: 
http://docs.opennebula.org/5.8/deployment/node_installation/lxd_node_installation.html

Trying to install OpenNebula on Ubuntu 18.04 KVM VM to use with SNAP LXD on that VM.

States:  
> or, use LXD installed as snap (since OpenNebula 5.8.2):
> 
> sudo apt-get install opennebula-lxd-snap opennebula-node-lxd

**To Reproduce**
After installing the OpenNebula Repository info into /etc/apt/sources.list.d and doing an "apt update" I try to follow the steps in the above Documentation Link and get:
 
> $ sudo apt-get install opennebula-lxd-snap opennebula-node-lxd
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> **E: Unable to locate package opennebula-lxd-snap**

**Expected behavior**
I'd expect it to install opennebula-lxd-snap.   **I did check the repository and there are NO 5.8.2
files there just 5.8.1.1** and none of them are for LXD??

reference:  https://downloads.opennebula.org/repo/5.8/Ubuntu/18.04/

**Details**
see above

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Sorry, 5.8.2 is a [hotfix update](http://docs.opennebula.org/5.8/intro_release_notes/release_notes_hotfix/what_is_hotfix.html), however, you can still build the new packages.
