### ISSUE TITLE
Missing volatile disk selection in Sunstone disk hotplug wizard

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3422]
**Description**
When adding a disk via Sunstone the volatile selector sometimes is missing.

![2019-06-07-124607_1920x1080_scrot](https://user-images.githubusercontent.com/16429804/59371581-0932ed80-8d0b-11e9-8db0-25149170f682.png)

pressing ctrl+f5 corrects this, but it fails at some point, again.

**To Reproduce**
Keep attaching disks until you don't see it.

**Expected behavior**
Volatile disk selector should not be missing, ever.

Version: 5.8.2

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This issue cannot be replicated.
Will reopen if additional feedback is given.
