### ISSUE TITLE
Proposal saving federation endpoint for the sunstone interface

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3423]
**Description**
Allow setting opennebula endpoint for the sunstone in user template, the same way like other sunstone options:

```diff
 SUNSTONE=[
   DEFAULT_VIEW="admin",
   LANG="en_US",
+  ONE_ENDPOINT="https://api.example.org/RPC2",
   TABLE_DEFAULT_PAGE_LENGTH="100" ]
```

**Use case**
1) Assign default endpoint for the users.
2) Save user choice for the next sessions. 

**Interface Changes**
* If `SUNSTONE/ONE_ENDPOINT` is set, automatic connect to this endpoint
* Choosing API endpoint in sunstone should automatically add `SUNSTONE/ONE_ENDPOINT` to the user template.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
I believe this is covered by DEFAULT_ZONE_ENDPOINT

**Comment by kvaps** [comment]
Agree,

```ruby
SUNSTONE=[
  DEFAULT_ZONE_ENDPOINT="http://one4:2633/RPC2" ]
```
in user template is working fine
