### ISSUE TITLE
Wrong monitor of VMs without default VM_PREFIX in name

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3430]
**Description**

If the OpenNebula host includes a VM_PREFIX different to the default "one-$i-", launched VMs are not correctly monitored

**To Reproduce**

See description

**Expected behavior**

Correct monitoring of all VMs

**Details**
 - Affected Component:vCenter driver
 - Hypervisor: vCenter
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Doc: ea703be6d420629facd094c4f7e0726063087962
