### ISSUE TITLE
onedb upgrade eats too much RAM

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#3436]
**Description**
When running the onedb upgrade, it eats too much ram (e.g: 5GB) and may cause mysql goes down.

**To Reproduce**
Make the upgrade with a big database.

**Expected behavior**
Doesn't it too much ram.

**Details**
 - Affected Component: Core.
 - Version: 5.8 and development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
There is a memory leaking during the database upgrade as we are reading whole pools in the memory, not row by row, or paged. Mainly in https://github.com/OpenNebula/one/blob/79f28474e57de7848719d3cad846a4a9536b4fd9/src/onedb/local/5.6.0_to_5.7.80.rb#L39-L48
It's not a problem only on Ubuntu 18.04, all the systems are very close to memory limits of the testing frontends. Only Ubuntu 18.04 eats just a little more.

Very **SILLY workaround** is to trigger garbage collection after each upgrade phase, e.g.:

```
    def up
        feature_2944
        GC.start
        bug_2687         # MUST be run before 2489, which generates short body
        GC.start
        feature_2253
        GC.start
        feature_2489_2671
        GC.start
        feature_826
        GC.start
        feature_2966
        GC.start
        create_idxs      #MUST be the last one
        GC.start
        true
    end
```

Before workaround, upgrade process could usually get up to (and even above) 3 GB of total memory allocation. With the workaround, total memory allocation stays 2 GB at the most.

**Comment by vholer** [comment]
Maybe tuning the Ruby GC over environemnt variables RUBY_GC_* would be enough:
https://stackify.com/how-does-ruby-garbage-collection-work-a-simple-tutorial/

**Comment by christian7007** [comment]
I think probably the workaround commented by @vholer is good enough as 5.8 upgrade script is not probably going to be much used anymore.

We should be aware of this when developing new upgrade scripts to avoid this problem in the future.

**Comment by rsmontero** [comment]
Closing this for now....
