### ISSUE TITLE
onehost show - show if vCenter cluster have activated DRS and HA

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#3438]
**Description**
Know when the DRS is activated in vcenter hosts

**Use case**
In the execution of the command **onehost show**  if DRS and HA is activated.
Here you can find more info why is important.
http://docs.opennebula.org/5.8/deployment/node_installation/vcenter_node_installation.html#requirements

**Interface Changes**
The propose is when you execute command **onehost show** using the CLI add new field inside MONITORING INFORMATION called VCENTER_DRS and VCENTER_HA with two values, "on" and "off", for know when is active of disable respectively      
Next the change will be reflected also in Sunstone. 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
well done!
