### ISSUE TITLE
onevcenter tool polishments

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3439]
**Description**

Somethings to improve:

  * importing a resource with an id that does not exist in the list causes a gsub error:
 
```
# onevcenter import -o templates -h 8 200
undefined method `gsub' for nil:NilClass
```

   * importing a vcenter cluster using a non existing FQDN or IP dumps a backtrace (and it shouldn't)

```
Connecting to vCenter: vc4enter1...    Error: getaddrinfo: Name or service not known/
["/usr/share/ruby/net/http.rb:878:in `initialize'", "/usr/share/ruby/net/http.rb:878:in `open'", "/usr/share/ruby/net/http.rb:878:in `block in connect'", "/usr/share/ruby/timeout.rb:66:in `timeout'", "/usr/share/ruby/net/http.rb:877:in `connect'", "/usr/share/ruby/net/http.rb:862:in `do_start'", "/usr/share/ruby/net/http.rb:857:in `start'", "/usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/trivial_soap.rb:56:in `restart_http'", "/usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/trivial_soap.rb:20:in `initialize'", "/usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/connection.rb:31:in `initialize'", "/usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/vim.rb:43:in `new'", "/usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/vim.rb:43:in `connect'", "/usr/lib/one/ruby/vcenter_driver/vi_client.rb:29:in `initialize'", "/usr/lib/one/ruby/vcenter_driver/vcenter_importer.rb:412:in `new'", "/usr/lib/one/ruby/vcenter_driver/vcenter_importer.rb:412:in `import_clusters'", "/usr/bin/onevcenter:234:in `block (2 levels) in <main>'", "/usr/lib/one/ruby/cli/command_parser.rb:470:in `call'", "/usr/lib/one/ruby/cli/command_parser.rb:470:in `run'", "/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'", "/usr/bin/onevcenter:37:in `new'", "/usr/bin/onevcenter:37:in `<main>'"]
```

**Details**
 - Affected Component: CLI
 - Hypervisor: vcenter
 - Version: developmnet

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
When I execute this command on shell 

onevcenter import -o templates -h 81231123 2001231231

I get this message,

Could not get host info for ID: 81231123 - [one.host.info] Error getting host [81231123].

When you get that error?

**Comment by tinova** [comment]
Try using a valid host ID, but an invalid template id

**Comment by carloshm91** [comment]
PRs for merge:
- one: https://github.com/OpenNebula/one/pull/3475 into 5.8 and master
- docs: https://github.com/OpenNebula/docs/pull/692 into one-5.8-maintenance
