### ISSUE TITLE
VMs are hanging on DISK RESIZE POWER OFF

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3441]
**Description**
Sometimes during disk resize VMs are hanging on DISK RESIZE POWER OFF state.

Recover options (success or failed)  isn't working, due VM have same prev state variables:
```
  <STATE>3</STATE>
  <LCM_STATE>63</LCM_STATE>
  <PREV_STATE>3</PREV_STATE>
  <PREV_LCM_STATE>63</PREV_LCM_STATE>
```

**To Reproduce**
I'm not sure, but try to start resizing VM by hook immediately after it went into POWEROFF state.
Sometimes it work like so.

**Expected behavior**
VM resized without problems

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**
Currently the only way to solve this problem is hard replace it's state in db:

```
onedb change-body vm --id $VMID /VM/STATE 8
onedb change-body vm --id $VMID /VM/LCM_STATE 0
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by hydro-b** [comment]
I can reproduce this behaviour for "SNAPSHOT" as well. Taking new (Ceph) snapshots as well as reverting. As soon as I execute a script that performs quit a few operations after each other the VM might get stuck in a STATE. A "recover" operation won't help at that point in time. And I need to use "update-body vm --id $id" to fix STATES by hand.

**Comment by rsmontero** [comment]
AFAIU this is for fixing the recovery process for several transient operations.

**Comment by paczerny** [comment]
The problem is in the hook script. If I have hook on power off state:
```
VM_HOOK = [
 name      = "poweroff_hook",
 on        = "CUSTOM",
 state     = "POWEROFF",
 lcm_state = "LCM_INIT",
 command   = "/tmp/my_hook",
 arguments = "$ID $PREV_STATE $PREV_LCM_STATE" ]
```
The my_hook script:
`onevm disk-snapshot-create $1 0 generate_new_name`

The state transition after power of is:
POWEROFF -> hook trigger -> DISK_SNAPHOT_POWEROFF -> POWEROFF -> hook trigger -> DISK_SNAPSHOT_POWEROFF -> ... and so on forever

Solution to this might be to check the $PREV_LCM_STATE at the begining of the hook. If it is SHUTDOWN_POWEROFF then execute the script, if it is DISK_SNAPSHOT_POWEROFF exit
