### ISSUE TITLE
Node packages revert changes on uninstall

### ISSUE THREAD

**Issue by loveshack** [OpenNebula/one#3443]
This was observed with v5.8.1, but hasn't been changed in the repo.
The opennebula-node-kvm lacks rpm needs a %postun stanza to undo the %postin changes it makes in /etc/libvirt. Otherwise libvirtd won't start after removing opennebula because it references the oneadmin account.
To reproduce, install with minione and try to reinstall after minione --purge.

**Comment by vholer** [comment]
Fixed in https://github.com/OpenNebula/packages/pull/93, targets 5.10 release.
Thanks for the report!
