### ISSUE TITLE
Right drivers when importing market app to vCenter DS

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3444]
**Description**

Importing a qcow2 app into a vmdk DS ends up with the image with qcow2 drivers

**To Reproduce**

Import KVM image into vCenter DS

**Expected behavior**

Image to end up without 

-DRIVER  
-FORMAT 

and with DEV_PREFIX="sd"

**Details**
 - Affected Component: vCenter import
 - Hypervisor: vCenter
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
PRs for merge:
- one: https://github.com/OpenNebula/one/pull/3473 into 5.8 and master
- docs: https://github.com/OpenNebula/docs/pull/685 into one-5.8-maintenance
