### ISSUE TITLE
onevcenter command shows warning

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#3445]
**Description**
Using the onevcenter command in Ubuntu 1804 shows the following warning output besides its regular output, whenever used.

```
root@ubuntu1804-context-lxd-6fbc8-0:~# onevcenter import
/usr/lib/ruby/vendor_ruby/builder/xchar.rb:111: warning: constant ::Fixnum is deprecated
^[[ACould not get host info for ID:  - ID not defined
root@ubuntu1804-context-lxd-6fbc8-0:~# onevcenter list
/usr/lib/ruby/vendor_ruby/builder/xchar.rb:111: warning: constant ::Fixnum is deprecated
you need to use -o option!
```

The warning seems to be shown when loading the `vcenter driver`

```
root@ubuntu1804-context-lxd-6fbc8-0:~# grep vcenter_driver /usr/bin/onevcenter
require 'vcenter_driver'
root@ubuntu1804-context-lxd-6fbc8-0:~# vim /usr/bin/onevcenter 
root@ubuntu1804-context-lxd-6fbc8-0:~# grep vcenter_driver /usr/bin/onevcenter
#require 'vcenter_driver'
root@ubuntu1804-context-lxd-6fbc8-0:~# onevcenter list
you need to use -o option!
```

**To Reproduce**
Use the onevcenter command

**Expected behavior**
No warning

**Details**
 - Affected Component: CLI
 - Hypervisor: vCenter
 - Version: 5.8.1

**Additional context**
On centos7 doesn't fail, likely because of the different ruby version

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
I have investigated and as I can see the problem is in builder gem:

```
lib/builder/xchar.rb:  Builder.check_for_name_collision(Fixnum, "xchr")
lib/builder/xchar.rb:          when Fixnum
lib/builder/xchar.rb:  # Enhance the Fixnum class with a XML escaped character conversion.
lib/builder/xchar.rb:  class Fixnum
```

It's also related with the ruby version, that's why the message is only shown in some operative systems, because we have different versions. So the only thing we can do is wait until the gem is updated or we change the ruby version...

As a workaround you can use `export RUBYOPT="-W0` so the warnings messages are no longer shown on the terminal.
