### ISSUE TITLE
the upgrade link pointing to non-existent page

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3447]
**Description**
When a new version of OpenNebula is available there is a text `(new version available: 5.8.3)` but the hyperlink is pointing to https://opennebula.org/software which page is not available.

**To Reproduce**
Look at sunstone when there is new version released

**Expected behavior**
The hyperlink should point to existing page with information related to the new version

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.8.2]

**Additional context**
Or the site should have a landing page for the hyperlink in sunstone.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Thanks a lot for the heads up! We've added a redirection.
