### ISSUE TITLE
Sunstone does not highlighting states for the persistent images

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3450]
**Description**

![image](https://user-images.githubusercontent.com/7556217/59931360-13f52d00-9445-11e9-98d1-2c31282eb5b7.png)

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4141 
• docs: OpenNebula/docs/pull/917
