### ISSUE TITLE
Match FQDN with a short hostname to detect local host

### ISSUE THREAD

**Issue by alitvak69** [OpenNebula/one#3460]
**Description**
In a case where both short hostname and FQDN are present, I would like one to have the ability to check if they both are resolving to the same IP address.

**Use case**
I had cases where my node is defined as FQDN, however, Ubuntu set a short hostname by default.  This causes undeploy to fail because it uses ssh to copy files on the same node.  See issue #3010 for reference.

**Interface Changes**
I don't believe interface changes are needed.  I wonder if it is possible for undeploy or other scripts to resolve hostname and FQDN and if their IP match to use a local copy instead of SSH.
 
**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to address this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Few notes below related to original #3010 problem:

1. The short name

> So I don't understand where virt1n1-ch (short name) is coming from.

is the name of front-end node automatically guess by oned when copying data back. Currently, the detection of that hostname is equivalent to calling `hostname`. So, it's usually not a FQDN nor can't be configured. Improving this is part of https://github.com/OpenNebula/one/issues/3881.

2. Monitoring information gets just short names

> I think problem may be somewhere in host attributes.
> HOSTNAME | virt1n1-chi
> I changed it via web to FQDN but as I came back to the page the change reverted back to a short host name.

This is most likely not related to any problem, but monitoring should better return FQDN instead. Or, have new dedicated monitoring attribute for full name.

3. Extra checks if source / target aren't really same hosts or (**better**) same directories in case of misconfiguration with shared filesystem? E.g, here in `ssh/mvds` before removing the directory
```
 87 ssh_exec_and_log "$DST_HOST" "rm -rf '$DST_PATH'" \                             
 88     "Error removing target path to prevent overwrite errors"                    
```
which might be the same as as `$SRC_PATH`, do extra actions if `$DST_PATH` exists on `$DST_HOST` host
- create a state file inside `$DST_PATH`
- check a state file inside `$SRC_PATH` on `$SRC_HOST`
- if not, we can continue
This allows not to rely on DNS / hostnames, but the real behaviour of directory location.
