### ISSUE TITLE
Virtual Machine log tab shows master zone VM id corresponding log

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3465]
**Description**
When setting up a federation, the VM log tab of a VM belonging to the slave zone, seen through the master zone login session, shows the VM log of the VM in the master zone instead, if it doesn't exist, it shows

`Log for VM <id> not available`

 

**To Reproduce**
- Setup two zones
- Create a VM in the slave zone
- Create (or not) a VM with the same id in the master zone
- Log in through the frontend of the slave zone and lookg at the VM log
- Log in via the master zone
- Switch to the slave zone view
- The VM log seen will be the one corresponding to the VM with the same id existing in the master frontend. 

**Expected behavior**
View the log of the VM of the slave zone through the master zone login via the slave zone view.

**Details**
 - Affected Component: Sunstone
 - Version: 5.8.1, 5.8.2

**Additional context**
Two pictures of the same VM, seen from slave zone login session, and seen from the master zone login session but switching to the slave zone view. The logs are diffrent, but it show be the same.

![2019-06-28-132600_1236x683_scrot](https://user-images.githubusercontent.com/33811723/60371981-a905a200-99c0-11e9-9e09-c2c34f59dae5.png)
![2019-06-28-132554_1251x714_scrot](https://user-images.githubusercontent.com/33811723/60371983-a905a200-99c0-11e9-83a8-1f206ae67f05.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
Currently the VM logs are read from the frontend via its filesystem by the sunstone server
that limitation affects the info shown when the sunstone server and the oned managing the VM are not in the same server.

It will be added a check for the VM log, such that, when sunstone and oned are not in the same server, the last 15 lines of the VM log will be added to the VM template and that information will be shown in the VM log tab.

The master zone will still show its filesystem logs.

**Comment by tinova** [comment]
We'll do this in two phases

1) Disable VM log tab if the VM is remote on a federated oned
2) Add a new API call, one.vm.log, that includes log information. This will be useful in HA and federation scenarios

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4826
- doc: OpenNebula/docs/pull/1153
