### ISSUE TITLE
Not allowed to delete active snapshot in ALLOW_ORPHANS=mixed mode

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#3468]
**Description**
Not allowed to delete active snapshot in ALLOW_ORPHANS=mixed mode. While the same snapshot is allowed to be deleted when in ALLOW_ORPHANS=yes mode, so for the same VM / IMAGE and (Ceph) snapshots.

**To Reproduce**
Create a (Ceph) datastore which supports ALLOW_ORPHANS=mixed. Set ALLOW_ORPHANS=mixed. Create a VM. Create a disk snapshot. Try to delete the snapshot. You are not allowed to, with ONE logging "Cannot delete the active snapshot".

Set ALLOW_ORPHANS=yes in the VM template (onedb update-body vm --id $vmid) for all occurences of "ALLOW_ORPHANS=mixed". Try to delete the snapshot, this time it should be removed.

Proof:

ALLOW_ORPHANS=mixed

NAME             SIZE   PARENT                                                FMT PROT LOCK
one-1            10 GiB                                                         2      excl 
one-1@0          10 GiB                                                         2 yes

VM DISKS                                                                        
 ID DATASTORE  TARGET IMAGE                               SIZE      TYPE SAVE
  0 ceph_image sda    bionic01-disk-0                     -/10G     rbd   YES
  1 -          hda    CONTEXT                             -/-       -       -

VM DISK SNAPSHOTS                                                               
AC  ID DISK PARENT            DATE SIZE         NAME                            
=>   0    0     -1  07/01 16:11:27 -/10G        snap1

[one.vm.disksnapshotdelete] Cannot delete the active snapshot

The same VM, with updated template: ALLOW_ORPHANS=mixed -> ALLOW_ORPHANS=yes (onedb update-body vm --id $vmid)

ALLOW_ORPHANS=yes

one.vm.disksnapshotdelete result SUCCESS, 29

NAME             SIZE   PARENT                                                FMT PROT LOCK
one-1            10 GiB                                                         2      excl

VM DISKS                                                                        
 ID DATASTORE  TARGET IMAGE                               SIZE      TYPE SAVE
  0 ceph_image sda    bionic01-disk-0                     -/10G     rbd   YES
  1 -          hda    CONTEXT                             -/-       -       -

**Expected behavior**
The active snapshot can be deleted as it is not dependent on a parent image or a linked clone.

**Details**
 - Storage: datastores with ALLOW_ORPHANS=mixed (i.e. Ceph)
 - Hypervisor: KVM
 - Version: 5.8.x

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
ref https://github.com/OpenNebula/one/issues/3248

**Comment by paczerny** [comment]
PRs for merge:
    one: #3497  into 5.8 and master
    docs: OpenNebula/docs#691 into one-5.8-maintenance
    development: OpenNebula/development#675 into one-5.8 and master

**Comment by rsmontero** [comment]
Merged in master & 5.8
