### ISSUE TITLE
Image deletion fails to find parent RBD if ALLOW_ORPHANS=yes and snapshot 0 dele

### ISSUE THREAD

**Issue by noebi** [OpenNebula/one#3478]
**Description**
In cases with ALLOW_ORPHANS=Yes where a number of snapshots are present but the one with id '0' has been deleted, a revert will create a RBD clone whose parent is no more found by OpenNebula.

**To Reproduce**
- create VM with image and make sure ALLOW_ORPHANS==Yes
- make two disk snapshots
- delete snapshot 0
- revert to snapshot 1
- kill the VM and delete the image
- check the Ceph pool to verify that $pool/one-$imageid is gone but
$pool/one-$imageid-1 is still there

**Expected behavior**
Both the active clone and the parent image should have been deleted

**Details**
 - Affected Component: Server Ceph backend
 - Hypervisor: KVM
 - Version: >= 5.4.13, <= 5.8.3

**Additional context**
The culprit the the shell function rbd_top_parent() in ceph_utils.sh.
It loops through all matching RBD images to find the one that has the
snapshot with id '0':
  $RBD snap ls -p $pool --format json $vol | grep -Eq '"name":"0"'
This is not a solid test when ALLOW_ORPHANS==Yes.

A slightly more solid test would be to check all RBD images for the one
without parent:
  $RBD info -p $pool --format json $vol | grep -Eq '"parent":' || volume=$pool/$vol

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
I can confirm this bug. However, I can reproduce slightly different behavior.

For `ALLOW_ORPHANS=YES`, the VM ends up in a `failed` state when trying to terminate the VM in the last step.  For `ALLOW_ORPHANS=MIXED` the VM is terminated but the rbd image remains undeleted.

In both cases, trying `resume` instead of `terminate` always fails.

**Comment by xorel** [comment]
PRs for merge:
https://github.com/OpenNebula/one/pull/3501 master + 5.8
https://github.com/OpenNebula/development/pull/676 master + 5.8
https://github.com/OpenNebula/docs/pull/695 one-5.8-maintenance
