### ISSUE TITLE
Open VNC with secure boot enabled in ESXi hosts

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#3481]
**Description**
When Secure Boot is enable, the procedure to enable VNC described in OpenNebula doc doesn't work because changing to software acceptance level to CommunitySupported is not allowed.

**To Reproduce**
Try to run this command into an ESXi with secure boot enabled.

     esxcli software acceptance set --level CommunitySupported

**Expected behavior**
To be able to install the .vib provided by OpenNebula to enable VNC connections having a "CommunitySupported" level of the software acceptance. A way to enable this is needed in secure boot ESXi.

**Details**
 - Affected Component: Hypervisor
 - Hypervisor: ESXi
 - Version: ESXi with secure boot enabled.

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by raoulmorik** [comment]
Furthermore if you add the rules manualy (http://www.supermaru.com/2017/07/enabling-vnc-esxi/), ESXi removes the service entries after a reboot of ESX Host. We've tried that already - 89 ESX hosts upgraded to Secureboot and facing this problem now on all machines.

**Comment by tinova** [comment]
deprecated in favor of VMRC
