### ISSUE TITLE
IP alias variables not removed from context.sh when deleting IP alias

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3484]
**Description**
When removing an alias IP the re-contextualization is triggered but context.sh in the CDROM is not updated - the context variables for the removed alias are still there and the contextualization test do not find a difference and the ip is not removed.

**To Reproduce**
1. add some alias IPs
2. remove an alias IP
3. check the configured IPs in the VM

**Expected behavior**
The contextualization must step in and remove the alias IP from the VM

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [5.8.3]

**Additional context**
It looks like that *context.sh* is generated before the VM metadata is updated. Because deleting a second IP alias will trigger the contextualization in the VM. And *context.sh* will have missing the variables for the previously removed alias ip...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

Code: https://github.com/OpenNebula/one/pull/3487
Docs: https://github.com/OpenNebula/docs/pull/688

**Comment by al3xhh** [comment]
Thanks for reporting the bug @atodorov-storpool! It has been fixed and will be released in the 5.8.4 hotfix version.

**Comment by atodorov-storpool** [comment]
Thank you for the quick response!

Cheers,
Anton

**Comment by al3xhh** [comment]
Code: https://github.com/OpenNebula/one/pull/3518
Docs: https://github.com/OpenNebula/docs/pull/688

**Comment by al3xhh** [comment]
The context changes will be covered here: 

- https://github.com/OpenNebula/addon-context-linux/issues/174
- https://github.com/OpenNebula/addon-context-windows/issues/66

**Comment by atodorov-storpool** [comment]
Hi @al3xhh 

It looks like patch https://github.com/al3xhh/one/commit/2e667afb6d7234f48d9584014fd55b14a92b4f08 is not merged to one-5.8/master branches or there is another bug because `context.sh` in the VM's ISO is not updated on alias remove. There is no re-contextualization triggered in the VM.

Could you take another look on it? I think I've tested the patch against 5.8.3 and it worked...

**Comment by al3xhh** [comment]
Hello @atodorov-storpool we finally made a different solution, so now variables are not removed, but there is a new attribute in context to indicate that the alias is being detached. The changes in context packages aren't done yet, but there are issues for that in context repositories.

**Comment by atodorov-storpool** [comment]
Hello @al3xhh,
I've managed to have alias detach flag, but it is on all alias IPs in the context. Not only on the removed one. Here is the context.sh received by the VM when detaching ALIAS3:

```
# Context variables generated by OpenNebula
DISK_ID='1'
ETH0_ALIAS0_CONTEXT_FORCE_IPV4=''
ETH0_ALIAS0_DETACH='YES'
ETH0_ALIAS0_DNS=''
ETH0_ALIAS0_EXTERNAL=''
ETH0_ALIAS0_GATEWAY=''
ETH0_ALIAS0_GATEWAY6=''
ETH0_ALIAS0_IP='192.168.122.6'
ETH0_ALIAS0_IP6=''
ETH0_ALIAS0_IP6_PREFIX_LENGTH=''
ETH0_ALIAS0_IP6_ULA=''
ETH0_ALIAS0_MAC='02:00:c0:a8:7a:06'
ETH0_ALIAS0_MASK=''
ETH0_ALIAS0_MTU=''
ETH0_ALIAS0_NETWORK=''
ETH0_ALIAS0_SEARCH_DOMAIN=''
ETH0_ALIAS0_VLAN_ID=''
ETH0_ALIAS0_VROUTER_IP=''
ETH0_ALIAS0_VROUTER_IP6=''
ETH0_ALIAS0_VROUTER_MANAGEMENT=''
ETH0_ALIAS3_CONTEXT_FORCE_IPV4=''
ETH0_ALIAS3_DETACH='YES'
ETH0_ALIAS3_DNS=''
ETH0_ALIAS3_EXTERNAL=''
ETH0_ALIAS3_GATEWAY=''
ETH0_ALIAS3_GATEWAY6=''
ETH0_ALIAS3_IP='192.168.122.7'
ETH0_ALIAS3_IP6=''
ETH0_ALIAS3_IP6_PREFIX_LENGTH=''
ETH0_ALIAS3_IP6_ULA=''
ETH0_ALIAS3_MAC='02:00:c0:a8:7a:07'
ETH0_ALIAS3_MASK=''
ETH0_ALIAS3_MTU=''
ETH0_ALIAS3_NETWORK=''
ETH0_ALIAS3_SEARCH_DOMAIN=''
ETH0_ALIAS3_VLAN_ID=''
ETH0_ALIAS3_VROUTER_IP=''
ETH0_ALIAS3_VROUTER_IP6=''
ETH0_ALIAS3_VROUTER_MANAGEMENT=''
ETH0_CONTEXT_FORCE_IPV4=''
ETH0_DNS='1.1.1.1'
ETH0_EXTERNAL=''
ETH0_GATEWAY='192.168.122.1'
ETH0_GATEWAY6=''
ETH0_IP='192.168.122.4'
ETH0_IP6=''
ETH0_IP6_PREFIX_LENGTH=''
ETH0_IP6_ULA=''
ETH0_MAC='02:00:c0:a8:7a:04'
ETH0_MASK='255.255.255.0'
ETH0_MTU='1500'
ETH0_NETWORK='192.168.122.0'
ETH0_SEARCH_DOMAIN=''
ETH0_VLAN_ID=''
ETH0_VROUTER_IP=''
ETH0_VROUTER_IP6=''
ETH0_VROUTER_MANAGEMENT=''
ETH_ALIAS_DETACH='YES'
```

**Comment by atodorov-storpool** [comment]
And just noted that there is `ETH_ALIAS_DETACH='YES'`...

**Comment by al3xhh** [comment]
I will reopen the issue to take a look, thanks for noticing it @atodorov-storpool

**Comment by al3xhh** [comment]
@atodorov-storpool I have fixed it, thanks again for trying it!
