### ISSUE TITLE
API call to re-trigger the VM's contextualization

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3485]
**Description**
Interface to trigger VM re-contextualization on already running VMs.

**Use case**
For example to change the root password of the VM without restarting the VM. After updating the password with something like `onedb change-body`.
Or for any other contextualization related changes.

**Interface Changes**
API call like *one.vm.recontext*, for CLI something like `onevm recontext $VM_ID`.
Sunstone - nice to have but there is need it allow changing the contextualization first...

**Additional Context**
There is an workaround to trigger the re-contextualization by adding a dummy NIC or alias IP but we could agree that it is ugly as hell...

Also, an option to edit context variables via cli/api is welcome too ;)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
We currently have updateconf, to update context variables. The idea is to trigger the VM's contextualization on this API Call.

References:

http://docs.opennebula.org/5.8/integration/system_interfaces/api.html#one-vm-updateconf

@atodorov-storpool I think this request is covered by this API call and its planned extension in #1764 CLosing this one as duplicated.
