### ISSUE TITLE
XSD file for zone should match with the output of one.zone.info

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3495]
**Description**
XSD file for zone should match with the output of `one.zone.info` instead of `onezone show <zone_id> -x`. Also it is necessary to create a raftstatus.xsd file for defining the strucutre of the output of `one.zone.raftstatus`.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
solved here: 1988cb83697efa12d40ee02aac7d82305079eac4
