### ISSUE TITLE
onevm disk-snapshot operations should validate snap_id

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#3496]
**Description**
When calling `onevm disk-snapshot-(revert|delete|rename)` and giving snapshot name instead of id, it is converted to `0`. 
 
**To Reproduce**
create 2 snapshots:
```
onevm disk-snapshot-create 0  0 snap1
onevm disk-snapshot-create 0  0 snap2
```
try to delete snap2 using name
```
onevm disk-snapshot-delete 0 snap2
```
now snapshot1 (id=0) is deleted

**Expected behavior**
Error is given.

**Details**
 - Affected Component: cli
 - Version: 5.8

**Additional context**
It is ruby behavior, but it should validate input to prevent errors.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
The expected behavior doesn't have to be error. It would be nice to be able to use snapshot name. Not sure if it is possible to convert name to ID in ruby script.
