### ISSUE TITLE
VNM Hooks like to see output of hook script

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3509]
**Description**
I am testing new functionality VNM Hooks, writen some pre and clean hooks, but output of hooks is not shown in logs. There is just 

```
Fri Jul 12 22:49:28 2019 [Z0][VMM][I]: pre: Running /var/tmp/one/vnm/802.1Q/pre.d/pre
Fri Jul 12 22:49:28 2019 [Z0][VMM][I]: ExitCode: 0
Fri Jul 12 22:49:28 2019 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Fri Jul 12 22:49:31 2019 [Z0][VMM][I]: ExitCode: 0
```

**Use case**
It is good to have loged output from hooks.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
We are currently working in a hook system redesign and this feature is included in it. You can find more info here #3380.

**Comment by rsmontero** [comment]
Sorry after re-reading the issue, there is a misunderstanding, we'll look into it.
