### ISSUE TITLE
Scheduler cannot dispatch VM

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3513]
**Description**
There is a problem starting VM from an undeployed state. Scheduler error: `Cannot dispatch VM to any Host. Possible reasons: Not enough capacity in Host or System DS, dispatch limit reached, or limit of free leases reached.`

There is sufficient space on hosts and datastore. ONly manual deploy work. Instantiate of new VM working good.

**To Reproduce**
Instantiate VM, them undeploy and start again.

**Expected behavior**
It should be deployed like a new VM is instantiated.

**Details**
 - Affected Component: [Scheduler]
 - Hypervisor: [KVM]
 - Version: [5.8.3]

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
This behavior might be caused by many reasons. It might be:
1) permissions problem
2) mismatch of TM_MAD_SYSTEM parameter of images datastore and TM_MAD of system datastore
3) datastore, vnet and hosts might be located different clusters

please check your `/var/log/one/sched.log` for more details, if you still not understand, try to increase verbosity in `/etc/one/sched.conf`:

```
LOG = [
  system      = "file",
  debug_level = 3
]
```

**Comment by feldsam** [comment]
@kvaps thanks for the reply. I found that there is a syntax problem in `AUTOMATIC_DS_REQUIREMENTS`

```
Sun Jul 14 13:52:58 2019 [Z0][SCHED][D]: Match-making results for VM 548:
	Cannot schedule VM. Error in SCHED_DS_REQUIREMENTS: '(TM_MAD = 3par) & ("CLUSTERS/ID" @> 0)', error: syntax error, unexpected STRING, expecting '&' or '|' or ')' at line 1835361121, columns 12:15

Sun Jul 14 13:52:58 2019 [Z0][SCHED][D]: Match-making results for VM 548:
	Cannot schedule VM, there is no suitable system ds.
```

```
AUTOMATIC_DS_REQUIREMENTS = "(TM_MAD = 3par) & (\"CLUSTERS/ID\" @> 0)"
AUTOMATIC_NIC_REQUIREMENTS = "(TM_MAD = 3par) & (\"CLUSTERS/ID\" @> 0)"
AUTOMATIC_REQUIREMENTS = "(CLUSTER_ID = 0) & !(PUBLIC_CLOUD = YES)"
```
These values are created automatically durring VM instatiation.

**Comment by rsmontero** [comment]
Thanks @feldsam, It seems we didn't expect a driver starting by a number. Good catch

**Comment by paynpro** [comment]
> [@kvaps](https://github.com/kvaps) thanks for the reply. I found that there is a syntax problem in `AUTOMATIC_DS_REQUIREMENTS`
> 
> ```
> Sun Jul 14 13:52:58 2019 [Z0][SCHED][D]: Match-making results for VM 548:
> 	Cannot schedule VM. Error in SCHED_DS_REQUIREMENTS: '(TM_MAD = 3par) & ("CLUSTERS/ID" @> 0)', error: syntax error, unexpected STRING, expecting '&' or '|' or ')' at line 1835361121, columns 12:15
> 
> Sun Jul 14 13:52:58 2019 [Z0][SCHED][D]: Match-making results for VM 548:
> 	Cannot schedule VM, there is no suitable system ds.
> ```
> 
> ```
> AUTOMATIC_DS_REQUIREMENTS = "(TM_MAD = 3par) & (\"CLUSTERS/ID\" @> 0)"
> AUTOMATIC_NIC_REQUIREMENTS = "(TM_MAD = 3par) & (\"CLUSTERS/ID\" @> 0)"
> AUTOMATIC_REQUIREMENTS = "(CLUSTER_ID = 0) & !(PUBLIC_CLOUD = YES)"
> ```
> 
> These values are created automatically durring VM instatiation.

bro i too getting same error its there any solution??
Mon Jul 28 01:11:05 2025: Cannot dispatch VM: No system datastore meets capacity and SCHED_DS_REQUIREMENTS: ("CLUSTERS/ID" @> 106)

**Comment by feldsam** [comment]
Hello @paypro, this issue was only when TM MAD with name 3par was used and was fixed. You likely have more general problem with scheduling. You should write you exact issue with settings as forum port to https://forum.opennebula.io
