### ISSUE TITLE
Add new command for create/recreate FTS index for VM searching

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3530]
**Description**
It will be useful to have a command (e.g `onedb recreate-index`) for create/recreate the FTS index either for maintenance proposes or in case a DB that didn't support this feature get updated and start to support it. 

**Use case**
 - Facilitate DB maintenance task.
 - Help to add the index in case it doesn't exists (e.g update DB from a non supported version to a supported one)

**Interface Changes**
Add new option to onedb command at the CLI

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

code: https://github.com/OpenNebula/one/pull/3671
docs: https://github.com/OpenNebula/docs/pull/744
tests: https://github.com/OpenNebula/development/pull/708
