### ISSUE TITLE
Import Wild VMs  

### ISSUE THREAD

**Issue by UAnton** [OpenNebula/one#3533]
**Description**
Can't import Wild VMs. From Sunstone nothing happens. from cli I get the error:

```
/usr/lib/one/ruby/vcenter_driver/vmm_importer.rb:62:in `import':  (RuntimeError)
    There was an error trying to create an image for disk in vcenter template. Reason: datastore not found for VM's device
["/usr/lib/one/ruby/vcenter_driver/vm_template.rb:641:in `block in get_vcenter_disks'", "/usr/lib/one/ruby/vcenter_driver/vm_template.rb:620:in `each'", "/usr/lib/one/ruby/vcenter_driver/vm_template.rb:620:in `get_vcenter_disks'", "/usr/lib/one/ruby/vcenter_driver/vm_template.rb:232:in `import_vcenter_disks'", "/usr/lib/one/ruby/vcenter_driver/vmm_importer.rb:60:in `import'", "/usr/lib/one/ruby/opennebula/host.rb:243:in `import_wild'", "/usr/bin/onehost:285:in `block (3 levels) in <main>'", "/usr/lib/one/ruby/cli/one_helper.rb:799:in `call'", "/usr/lib/one/ruby/cli/one_helper.rb:799:in `perform_action'", "/usr/bin/onehost:281:in `block (2 levels) in <main>'", "/usr/lib/one/ruby/cli/command_parser.rb:470:in `call'", "/usr/lib/one/ruby/cli/command_parser.rb:470:in `run'", "/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'", "/usr/bin/onehost:36:in `new'", "/usr/bin/onehost:36:in `<main>'"]
        from /usr/lib/one/ruby/opennebula/host.rb:243:in `import_wild'
        from /usr/bin/onehost:285:in `block (3 levels) in <main>'
        from /usr/lib/one/ruby/cli/one_helper.rb:799:in `call'
        from /usr/lib/one/ruby/cli/one_helper.rb:799:in `perform_action'
        from /usr/bin/onehost:281:in `block (2 levels) in <main>'
        from /usr/lib/one/ruby/cli/command_parser.rb:470:in `call'
        from /usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
        from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
        from /usr/bin/onehost:36:in `new'
        from /usr/bin/onehost:36:in `<main>'
```

**To Reproduce**
Try import VM from vCenter

**Expected behavior**
Import VMs

**Details**
 - Hypervisor: ESXi 6.7
 - Version: 5.8.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
will reopen when more feedback is provided

**Comment by UAnton** [comment]
From Sunstone nothing happens, VM not importing. No errors in console or logs
Work from CLI. 
No IP addresses in One interface for imported VMs.

**Comment by tinova** [comment]
Maybe you are hitting a timeout. Are you using Sunstone with Apache? It may be worth a try, thin server has a default timeout of 30 seconds.

**Comment by UAnton** [comment]
I don't use apache or any proxy. When I press the import button in UI - nothing happens. No timeout or error. The Import work from CLI but without IP addresses. I was trying on 3 new deployments (Centos 7, 8, Ubuntu 18.04).

**Comment by tinova** [comment]
Please try with apache + phusion passenger:

  http://docs.opennebula.org/5.8/deployment/sunstone_setup/suns_advance.html#running-sunstone-with-passenger-in-apache

**Comment by UAnton** [comment]
I trying with Nginx. No changes.

**Comment by tinova** [comment]
Can you confirm that you are using Phusion Passenger as well?

**Comment by UAnton** [comment]
> Can you confirm that you are using Phusion Passenger as well?

I use Sunstone or Sunstone + Nginx. Why should I complicate and use Phusion Passenger?
Opennebula only works when used Phusion Passenger?

**Comment by UAnton** [comment]
After update to 5.10.1 - import works fine.

**Comment by tinova** [comment]
> I use Sunstone or Sunstone + Nginx. Why should I complicate and use Phusion Passenger?
> Opennebula only works when used Phusion Passenger?

In large environments, Phusion Passenger needs to be used to handle large collection of resources and avoid the 30 seconds timeout of thin server.

> After update to 5.10.1 - import works fine.

Good to know. It is weird since we haven't touched that part of the code between 5.10.0 and 5.10.1
