### ISSUE TITLE
Pass "host" arg to VNM pre and clean actions

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3534]
**Description**
Extend VNM actions by adding "host" as the last argument.

**Use case**
This additional argument can be used by new or customized VNM drivers. For example, when setting param based on hostname is needed, like a switch port.

**Interface Changes**
Just add host argument to pre and clean actions

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
MR #3535

**Comment by dann1** [comment]
host is already passed into the xml coming through STDIN, you can look at it in
```
    <HISTORY_RECORDS>
        <HISTORY>
            <HOSTNAME>ubuntu1804-lxd-marketplace-d1833-0.test</HOSTNAME>
        </HISTORY>
    </HISTORY_RECORDS>
```

Another argument only adds extra maintenance complexity for the network drivers.

**Comment by feldsam** [comment]
I know, but it is not usable, because in case of migration, clean action is called on source host and pre action on destination host, so we have to done some nasty checks in this history records to obtain right host
