### ISSUE TITLE
VNM Vlan driver extract delete dev to function

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3536]
**Description**
Need to update vlan.rb driver to also extract delete dev to separate function like create_vlan_dev is

**Use case**
Ability to write custom vlan driver and du custom action on create_vlan_dev and delete_vlan_dev. For example, creating and allowing vlan on a switch port.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
MR #3536

**Comment by rsmontero** [comment]
Merged for 5.10
