### ISSUE TITLE
Error importing vCenter VM with 2 disk with same name

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3547]
**Description**
When you try to import a VM with some disks with same name, OpenNebula fails.

**To Reproduce**
Import a VM with 2 disk with same name.

**Expected behavior**
Import should go well.

**Details**
 - Hypervisor: vCenter
 - Version: 5.8 and development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
We need more information of how reproduce this issue.
 Because we try many ways and works fine. 
If not we will close it.

**Comment by tinova** [comment]
cannot reproduce
