### ISSUE TITLE
Let me group VMs in SunStone

### ISSUE THREAD

**Issue by JPaulMora** [OpenNebula/one#3566]
**Description**
So we've been having success with ON in our production environment. However, that means we have tons of VMs all with probably similar names, but for different clients/purposes. I've included a screenshot that shows how boring/confusing it gets to search for VMs.

**Use case**
How are you going to use this new feature? Why do you need it? 

Easier to look for items, makes me more efficient.

**Interface Changes**
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API:

So the giant VM list gets very confusing very quickly, I suggest we add "categories" to the VMs so that they show kind of like this:

<img width="476" alt="Screen Shot 2019-07-27 at 10 19 33 PM" src="https://user-images.githubusercontent.com/8335656/62002213-9fa14f80-b0bc-11e9-849d-8c516469ac22.png">

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

<img width="955" alt="VM list" src="https://user-images.githubusercontent.com/8335656/62002179-27d32500-b0bc-11e9-8199-db88a26f7f6d.png">

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by slntopp** [comment]
Hello,
you can use labels to group your VMs.
Use this button: <img width="62" alt="Снимок экрана 2019-07-28 в 11 05 54" src="https://user-images.githubusercontent.com/32666515/62004627-bfba2880-b127-11e9-93a4-c75e7a6bc946.png">.
After you've created some labels, you'll see them in menu like here:
<img width="180" alt="Снимок экрана 2019-07-28 в 11 06 05" src="https://user-images.githubusercontent.com/32666515/62004637-e6785f00-b127-11e9-9ed7-7da3fc75beaa.png">
By clicking on label in menu or using it as a search filter you'll see VMs with clicked label only.
Also, you can add Label column in /etc/one/sunstone-views/<your_current_view>.yaml
You should restart sunstone after changing this file.

**Comment by JPaulMora** [comment]
I'd still be in favor of a unified view, but this will do it.
thanks.
