### ISSUE TITLE
Missing parameters when import a vcenter network

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#3567]
**Description**
After import a vCenter network, some mandatory parameters aren't imported, like switch name, and host id.

**To Reproduce**
Import a vCenter network, and try to update the network config. 
Switch name and OpenNebula's Host ID will be empty

**Expected behavior**
Those attributes must be set at network import or if those attributes are not mandatory change them.

**Details**
 - Affected Component: vCenter driver
 - Hypervisor: ESXi
 - Version: all

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
PR -> https://github.com/OpenNebula/one/pull/3838
