### ISSUE TITLE
Newer OneGate client broken with old OneGate servers

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3572]
**Description**

If new OneGate client (e.g., 5.9.80) is running against old OneGate server (e.g., 5.4.15), the update operation fails:

```
# onegate vm update --data key=value
ERROR: 
[one.vm.update] Cannot update template. Parse error: syntax error, unexpected EQUAL, expecting $end at line 0, columns 22:23
```

Related to changes introduced by #1414,  because format of data sent from client has changed:
https://github.com/OpenNebula/one/pull/3252/files#diff-25cc1e51ebff40297b9dd487dd43be4dR596

**To Reproduce**
Have old OneGate server and new OneGate client. Do update operation from inside VM.

**Details**
 - Affected Component: OneGate
 - Version: 5.9.80 (client), <5.9.80 (server)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in **master**:

code: https://github.com/OpenNebula/one/pull/3643
docs: https://github.com/OpenNebula/docs/pull/732
context: https://github.com/OpenNebula/addon-context-linux/pull/184

**Comment by vholer** [comment]
LGTM.

- Context merged
- Docs probably not necessary (this was a fix of feature introduced in master)
- **Pending just code PR**: #3643
