### ISSUE TITLE
No network mask in the alias context

### ISSUE THREAD

**Issue by vmoyankov** [OpenNebula/one#3578]
**Description**
When an alias interface is created or attached, no network mask is added to the context. `ETH<x>_ALIAS<y>_MASK` attribute is empty. The value is not copied from the address range attributes, nor from the network context.

**To Reproduce**
Create a virtual network. Don't add NETWORK_MASK in the network context.
Create an IP address range and add NETWORK_MASK="255.255.0.0" in the address range attributes.

Create a VM with two interfaces - one main interface (ETH0) and one alias to NIC0. Both interfaces are connected to the virtual network created before.

Now the context looks like:

```
CONTEXT = [
...
  ETH0_ALIAS0_IP = "192.168.0.2",
  ETH0_ALIAS0_MAC = "02:00:c0:a8:00:02",
  ETH0_ALIAS0_MASK = "",
...
  ETH0_IP = "192.168.0.1",
  ETH0_MAC = "02:00:c0:a8:00:01",
  ETH0_MASK = "255.255.0.0",
...
```

**Expected behavior**
ETH0_ALIAS0_MASK context variable shall get values form the address range and the context shall contain:

```
  ETH0_ALIAS0_MASK = "255.255.0.0",
```

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [5.8.4]

**Additional context**
The same issue exists when an alias is created during the VM instantiation and when attached to an existing VM.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

code: https://github.com/OpenNebula/one/pull/3635
docs: https://github.com/OpenNebula/docs/pull/727
