### ISSUE TITLE
build fails if Python 3 is used to drive scons

### ISSUE THREAD

**Issue by mwichmann** [OpenNebula/one#3584]
**Description**
Project will not build if Python 3 is used to drive `scons`. 

**To Reproduce**
`python3 /usr/bin/scons` 
(or wherever scons is).  Fails quickly with
```
scons: Reading SConscript files ...
  File "/home/mats/github/one/SConstruct", line 189

    except Exception, e:

                    ^

SyntaxError: invalid syntax
```

**Expected behavior**
Build proceeds normally instead of erroring out immediately.

**Details**
Someone turned up on the scons freenode IRC channel concerned that Arch Linux has switched their scons to be run by Python3, and this project wouldn't build as a result.  As a contribution, have attached a patchfile here that addresses the obvious issues without breaking the ability to run through Python 2, can't really push it further since on the local system there are complaints about xmlrpc and I don't have any incentive to push through to get a full build going.  Do with it what you want!

[0001-Port-build-scripts-to-Python3.patch.gz](https://github.com/OpenNebula/one/files/3486878/0001-Port-build-scripts-to-Python3.patch.gz)

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Yann-Kaelig** [comment]
Thx you very much for the report and the patch. That fix the issue.
