### ISSUE TITLE
Opennebula build fails when options sqlite=no mysql=yes are set

### ISSUE THREAD

**Issue by Yann-Kaelig** [OpenNebula/one#3585]
**Description**
Opennebula build fails when options sqlite=no mysql=yes are set.

**To Reproduce**
Build opennebula with options sqlite=no mysql=yes

```
g++ -o src/nebula/Nebula.o -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -Wall -std=c++11 -DMYSQL_DB -Iinclude -Isrc/parsers -I/usr/include/mysql -I/usr/include/mysql/mysql -I/usr/include -I/usr/include/libxml2 src/nebula/Nebula.cc
src/nebula/Nebula.cc: In member function 'void Nebula::start(bool)':
src/nebula/Nebula.cc:316:62: error: invalid new-expression of abstract class type 'SqliteDB'
  316 |             db_backend = new SqliteDB(var_location + "one.db");
      |                                                              ^
In file included from src/nebula/Nebula.cc:20:
include/SqliteDB.h:131:7: note:   because the following virtual functions are pure within 'SqliteDB':
  131 | class SqliteDB : public SqlDB
      |       ^~~~~~~~
In file included from include/LogDB.h:24,
                 from include/Nebula.h:20,
                 from src/nebula/Nebula.cc:17:
include/SqlDB.h:121:18: note: 	'virtual bool SqlDB::fts_available()'
  121 |     virtual bool fts_available() = 0;
      |                  ^~~~~~~~~~~~~
scons: *** [src/nebula/Nebula.o] Error 1
scons: building terminated because of errors.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Expected behavior**
Build proceeds normally

**Details**
 - Version: Opennebula 5.8.4

[opennebula-5.8.4.log.txt](https://github.com/OpenNebula/one/files/3487499/opennebula-5.8.4.log.txt)

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge:
* one: #3641 into one-5.8 and master
* docs: OpenNebula/docs#731 into one-5.8-maintanance
