### ISSUE TITLE
Sunstone: support X-Auth-Username header for external authentication

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3591]
**Description**
I'm going to enable OpenID Connect authentication for OpenNebula Sunstone using [keycloak-gatekeeper](https://github.com/keycloak/keycloak-gatekeeper) (external authorization proxy).

I've set `:auth: remote` in sunstone-server.conf, and runned sunstone behind keycloak-gatekeeper.

Now, after successful authentication keycloak-gatekeeper pass me access to the sunstone interface with extra headers set:

```
Authorization: Bearer <id_token_here>
X-Auth-Audience: opennebula
X-Auth-Email: kvapss@gmail.com
X-Auth-Expiresin: 2019-08-14 21:08:11 +0000 UTC
X-Auth-Groups: 
X-Auth-Roles: offline_access,uma_authorization,account:manage-account,account:manage-account-links,account:view-profile
X-Auth-Subject: 245de82b-e51c-4a05-99ca-91d8204fcd38
X-Auth-Token: <id_token_here>
X-Auth-Userid: kvaps
X-Auth-Username: kvaps
```

Problem is that Sunstone can't read and use them to perform authentication request.

I think we have to allow `X-Auth-Username` header using for username for sunstone authentication.

**Use case**

Working OpenID Connect authentication via external auth proxy.

**Interface Changes**

no at all

**Additional Context**

How is it looks like:
![image](https://user-images.githubusercontent.com/7556217/63059047-a1f20f00-beee-11e9-92ed-5a58f3e1dddf.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
ref https://github.com/OpenNebula/one/issues/729

**Comment by TafkaMax** [comment]
@kvaps  Have you tried using another instance after keycloak-gatekeeper has been archived?
