### ISSUE TITLE
When changing datastore's cluster, data table is not updated

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3594]
**Description**

When you change the datastore's cluster, it changes well, but the table under datastores-tab page is not updated, it remains with all datastore ID.

**To Reproduce**

- Tick one datastore ex: 105, 
- Assigned 105 to cluster ID 103, 
- It will refresh, 
- Cluster ID of the datastore is still 0 /#datastores-tab page, 
- Checked the details of datastore 105 /#datastores-tab/105, under Attributes, The "CLUSTER" is set to "103"

**Expected behavior**

The table should show the new cluster ID.

**Details**
 - Affected Component: Sunstone
 - Version: 5.8.4 and development.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approval:
- ONE: https://github.com/OpenNebula/one/pull/3777
- Docs: https://github.com/OpenNebula/docs/pull/781
