### ISSUE TITLE
save_as uses symlink instead of copy

### ISSUE THREAD

**Issue by mclei-asw** [OpenNebula/one#3601]
**Description**
I am using shared storage and when save_as of powered-off VM is used, only the symlink is created although separate image record is created. It leads then to data corruption, when mounted as both the original and copy is using same physical data disk.

**To Reproduce**
My datastorage config is:
```
ALLOW_ORPHANS="YES"
CLONE_TARGET="SYSTEM"
CLONE_TARGET_SHARED="SYSTEM"
DISK_TYPE="FILE"
DISK_TYPE_SHARED="FILE"
LN_TARGET="NONE"
LN_TARGET_SHARED="NONE"
TM_MAD_SYSTEM="shared"
TYPE="IMAGE_DS"
```

1. create VM with persistent disk
2. poweroff that VM
3. use save_as of the persistent disk from the VM

Then in result the symlink is created instead of the physical copy of the disk. (seems 'ln' is called instead of 'clone'

**Expected behavior**
Create physical copy of the disk.

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**
The 'ln' binary is used only in 'ln' transfer script and nowhere else.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
I replicated the same setup but can not reproduce the issue.

Did you find some more details meanwhile? 

Could you add line `echo $0 $@ >> /tmp/debug.log` to the begining of the `/var/lib/one/remotes/tm/tm_common.sh` to validate the theory that `ln` is being called instead `cpds`?

**Comment by mclei** [comment]
I have investigated it again, and I have to apologize. The main problem is, that the instance disk is symlink and in TM scripts, the symlink is not resolved, but just copied as is. And that's why the resulting disk is also symlink.
