### ISSUE TITLE
Can't disable "vCenter Deployment" and "Instantiate as different User / Group" visibility in Sunstone

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3604]
**Description**
There is no way to disable "vCenter Deployment" and "Instantiate as different User / Group" during VM instantiation.
![image](https://user-images.githubusercontent.com/7556217/63445717-2a196c80-c439-11e9-99db-30bcbce5756a.png)

**To Reproduce**
- Set option `vcenter_vm_folder` to `false`
- Set options `show_ds_instantiate` and `show_host_instantiate` both to `false`

**Expected behavior**
- No "vCenter Deployment" element
- No "Instantiate as different User / Group" element

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.8.4

**Additional context**
Entry of tab is disabled, but tab is still visible for users.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mzealey** [comment]
'Schedule Actions for VM' is also not possible to disable due to the same issue. I think it just needs some wrappers in the JS templates and some new config variables adding.

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4608
- Docs: https://github.com/OpenNebula/docs/pull/1085

@kvaps to disable `Instantiate as different User / Group` element you need to set `show_as_uid_instantiate` and `show_as_gid_instantiate` to false.
