### ISSUE TITLE
NoVNC connection fails on LXD

### ISSUE THREAD

**Issue by alitvak69** [OpenNebula/one#3606]
**Description**
noVNC console connection is failing on LXD.  Clicking on VNC produces a black screen on the page with a title VNC Loaded.   Screen stays on for a number of seconds and then disappears.  

**To Reproduce**
Run LXD instance.  Select NoVNC console from sunstone.

**Expected behavior**
noVNC console connects, stays on and allows for interactive keyboard operations.

**Details**
 - Affected Component: Sunstone, VNC
 - Hypervisor: LXD from snap
 - Version: 5.8.4
 - OS: Ubuntu 18.04

**Additional context**
novnc.log:

10.10.10.50 - - [21/Aug/2019 20:11:53] 10.10.10.50: Plain non-SSL (ws://) WebSocket connection
10.10.10.50 - - [21/Aug/2019 20:11:53] 10.10.10.50: Version hybi-13, base64: 'False'
10.10.10.50 - - [21/Aug/2019 20:11:53] 10.10.10.50: Path: '/?host=virt3n1-la.xcastlabs.net&port=29876&token=j73hpfow0sk1dljh8hk3&encrypt=no&title=alex-lxd-centos7&password=null'
10.10.10.50 - - [21/Aug/2019 20:11:53] connecting to: 10.0.22.5:5979
10.10.10.50 - - [21/Aug/2019 20:11:58] code 400, message Bad HTTP/0.9 request type ('\x82\x88-')
10.10.10.50 - - [21/Aug/2019 20:12:03] 10.10.10.50: Plain non-SSL (ws://) WebSocket connection
10.10.10.50 - - [21/Aug/2019 20:12:03] 10.10.10.50: Version hybi-13, base64: 'False'
10.10.10.50 - - [21/Aug/2019 20:12:03] 10.10.10.50: Path: '/?host=virt3n1-la.xcastlabs.net&port=29876&token=j73hpfow0sk1dljh8hk3&encrypt=no'
10.10.10.50 - - [21/Aug/2019 20:12:03] connecting to: 10.0.22.5:5979
10.10.10.50 - - [21/Aug/2019 20:12:11] code 400, message Bad request syntax ('\x88\x8f\\\xcb\x8aC_#\xde".\xac\xef7|\xa8\xe6,/\xae\xee')
10.10.10.50 - - [21/Aug/2019 20:26:25] 10.10.10.50: Plain non-SSL (ws://) WebSocket connection
10.10.10.50 - - [21/Aug/2019 20:26:25] 10.10.10.50: Version hybi-13, base64: 'False'
10.10.10.50 - - [21/Aug/2019 20:26:25] 10.10.10.50: Path: '/?host=virt3n1-la.xcastlabs.net&port=29876&token=vdgmbljvtxjgc8pfprcv&encrypt=no&title=alex-lxd-centos7&password=null'
10.10.10.50 - - [21/Aug/2019 20:26:25] connecting to: 10.0.22.5:5979
10.10.10.50 - - [21/Aug/2019 20:26:33] code 400, message Bad request syntax ("\x88\x8f'\x88\x18\x03$`LbU\xef}w\x07\xebtlT\xed|")
10.10.10.50 - - [21/Aug/2019 20:28:15] 10.10.10.50: Plain non-SSL (ws://) WebSocket connection
10.10.10.50 - - [21/Aug/2019 20:28:15] 10.10.10.50: Version hybi-13, base64: 'False'
10.10.10.50 - - [21/Aug/2019 20:28:15] 10.10.10.50: Path: '/?host=virt3n1-la.xcastlabs.net&port=29876&token=tuc81dvh73kcxhqkl57y&encrypt=no&title=alex-lxd-centos7&password=null'
10.10.10.50 - - [21/Aug/2019 20:28:15] connecting to: 10.0.22.5:5980
10.10.10.50 - - [21/Aug/2019 20:28:20] code 400, message Bad request syntax ('\x88\x8f2[2k1\xb3f')

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Can you check KVM VNC access in your setup ? I'm using the same scenario where I patched #3596 and I VNC is working properly.

**Comment by alitvak69** [comment]
I deleted/recreated a KVM VM and noVNC console works for me.  I  live migrated KVM to the same host  as lxd running on and console still works.

**Comment by alitvak69** [comment]
See a lot of 
Sun Aug 18 06:25:12 2019 [Z0][ONE][E]: Error parsing host 5 information: syntax error, unexpected COMMA, expecting EQUAL or EQUAL_EMPTY at line 0, columns 6:8. Monitoring information: 
Sorry, home directories outside of /home are not currently supported. 
See https://forum.snapcraft.io/t/11209 for details.

in omed.log, not sure if it has any relevance to the case.

**Comment by dann1** [comment]
That was the output that changed with the snap upgrade, make sure you upgrade [all the nodes](https://github.com/OpenNebula/one/issues/3596#issuecomment-524402381).

The behaviour you are experiencing with the centos containers is [known](http://docs.opennebula.org/5.8/deployment/open_cloud_host_setup/lxd_driver.html#guest-issues). If you want VNC on centos containers you should change the vnc command that is run through svncterm.
