### ISSUE TITLE
brctl is obsolete and should be replaced in code

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3613]
**Description**
`brctl` command is obsolete and `bridge-utils` package is not in REHL8, Oracle Linux 8 and in upcoming CentOS 8. There is also no package in EPEL-8.0 release.

`brctl` calls in VNM drivers should be replaced by `ip link` commands. 

**Details**
 - Affected Component: Network
 - Hypervisor: KVM, LXD
 - Version: All

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Also related to brctl #3522

**Comment by xorel** [comment]
PRs:
* one https://github.com/OpenNebula/one/pull/3654 to master
* docs https://github.com/OpenNebula/docs/pull/736 to master

**Comment by feldsam** [comment]
just note, bridge-utils dep have to be removed from packing spec files in this repo https://github.com/OpenNebula/packages
