### ISSUE TITLE
useless button in VM template info screen sunstone

### ISSUE THREAD

**Issue by mathijsmm** [OpenNebula/one#3614]
**Description**
The create new template button seems to also display in the vm template info screen, only it has no function at all and the menu underneath it is also empty.

**To Reproduce**
Display the info page of any existing VM template it will show a green button between the back and refresh button

**Expected behavior**
This button should not be here

**Details**
 - Affected Component: Sunstone
 - Hypervisor: n/a
 - Version: any 5.8 version so far

**Additional context**
n/a

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova, PR to approve:
-ONE: https://github.com/OpenNebula/one/pull/3860
-Docs: https://github.com/OpenNebula/docs/pull/808
