### ISSUE TITLE
spice client blurred lines

### ISSUE THREAD

**Issue by matthijs** [OpenNebula/one#3618]
**Description**
After we upgraded from 5.4 to 5.8 our spice console does not work as expected. The view is blurred.

**To Reproduce**
We use Debian buster as our Host and as backend qemu-kvm (managed through libvirt). All this software comes from the debian repositories. We have installed opennebula through the opennebula repository found at: https://downloads.opennebula.org/repo/5.8/Debian/9

Step 1) Instantiate a VM with spice enabled.
Step 2) Click on the instantiated VM
Step 3) Click on the spice button
Step 4) Got a blurred screen.

Screenshot:
<img width="1048" alt="Blurred Console" src="https://user-images.githubusercontent.com/36565/63864409-15485600-c9b0-11e9-9e76-12186acfbd6f.png">

**Expected behavior**
Obviously: a non blurred screen so that I can type my commands and that it shows the results correctly.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.8.1 (the one from the repository)

**Additional context**
The problem happened after we upgraded the Host from Debian Stretch to Debian Buster.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
I reproduce the issue.

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4601
- docs: OpenNebula/docs/pull/1078
