### ISSUE TITLE
Prevent race in iptables across different tools in the host

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3624]
**Description**
When deploying multiple VMs on a host with [multiple actions per host](http://docs.opennebula.org/5.8/deployment/open_cloud_host_setup/kvm_driver.html#multiple-actions-per-host) enabled the following lock in xtables is observed:
```
Wed Aug 28 17:04:45 2019 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vnm/802.1Q/post 'one-284'
Wed Aug 28 17:04:45 2019 [Z0][VMM][I]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Wed Aug 28 17:04:45 2019 [Z0][VMM][E]: post: Command Error: sudo iptables -I opennebula -m physdev --physdev-in one-284-0 --physdev-is-bridged -j one-284-0-o
Wed Aug 28 17:04:45 2019 [Z0][VMM][E]: post: ["/var/tmp/one/vnm/command.rb:64:in `block in run!'", "/var/tmp/one/vnm/command.rb:59:in `each'", "/var/tmp/one/vnm/command.rb:59:in `run!'", "/var/tmp/one/vnm/security_groups_iptables.rb:519:in `nic_pre'", "/var/tmp/one/vnm/sg_driver.rb:92:in `block in activate'", "/var/tmp/one/vnm/vnm_driver.rb:79:in `call'", "/var/tmp/one/vnm/vnm_driver.rb:79:in `block in process'", "/var/tmp/one/vnm/vm.rb:73:in `call'", "/var/tmp/one/vnm/vm.rb:73:in `block in each_nic'", "/var/tmp/one/vnm/vm.rb:72:in `each'", "/var/tmp/one/vnm/vm.rb:72:in `each_nic'", "/var/tmp/one/vnm/vnm_driver.rb:82:in `process'", "/var/tmp/one/vnm/sg_driver.rb:84:in `activate'", "/var/tmp/one/vnm/802.1Q/post:32:in `<main>'"]
```

**To Reproduce**
 - Enable [multiple actions per host](http://docs.opennebula.org/5.8/deployment/open_cloud_host_setup/kvm_driver.html#multiple-actions-per-host)
 - instantiate several VMs with several NICs enabled
 - monitor the VM's logs for the above error message

**Expected behavior**
The VM's should be deployed successfully

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [5.8.4]

**Additional context**

The suggested resolution by adding a timeout to the iptables works. A pull request is pending.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This was supposed to be addressed by the locking mechanism of the drivers. In particular the sg_driver has the locking enabled:

https://github.com/OpenNebula/one/blob/master/src/vnm_mad/remotes/lib/sg_driver.rb#L45

and iptables commands should be executed through the flock facilites see: https://github.com/OpenNebula/one/blob/master/src/vnm_mad/remotes/lib/vnm_driver.rb#L58

**Comment by rsmontero** [comment]
Are all VMs using the same network? If not, are the networks using different drivers o modes?

**Comment by atodorov-storpool** [comment]
Well it happened when only 3 VMs were instantiated simultaneously on the same host and with the _sg_driver_ and same VM Template...
Will try to reproduce it tomorrow with some more logging (any hints what to look for are welcome)

**Comment by vholer** [comment]
Hello Anton, when reproducing, pls check the locking code in `/var/lib/one/remotes/vnm/vnm_driver.rb`, if it's using (proper) locks:

```
        def lock
            if @locking
                driver_name = self.class.name.downcase
                @locking_file = File.open("/tmp/onevnm-#{driver_name}-lock","w")
                @locking_file.flock(File::LOCK_EX)
            end
        end
```

Also, I would try to experimentally change it to use a single hard coded driver independent lock name:

```
                @locking_file = File.open("/tmp/onevnm-ALL-lock","w")
```

Probably SG and VLAN drivers are competing for same resources, but using different lock names.

**Comment by atodorov-storpool** [comment]
Hi All.

Managed to reproduce, but the issue is not in the OpenNebula's control. The locking is fine - there are no issues observed. 

The xtables locking issue is caused by an external iptables call. In my case there was a 1 second poll of iptables started on same host by a colleague to monitor the iptables counters `watch -n1 'iptables -nvx -L'` that was racing with the VN MAD. 

So I think it is better to have the iptables lock enabled because opennebula could not relay that it is the only service using iptables on the host. It could race with [fail2ban](https://www.fail2ban.org) or any other service/tool that could use iptables...
The proposed patch will protect OpenNebula for these racing issues. With the patch applied the iptables polling was failing from time to time, not the OpenNebula's vn mad. (And yes the "other" service could fail too, but it is "their" job to handle the case and wait for the xtables lock too...)

**Comment by rsmontero** [comment]
OK THANKS @atodorov-storpool  for the information

**Comment by atodorov-storpool** [comment]
Just for reference, libvirt [is using](https://github.com/libvirt/libvirt/blob/master/src/util/virfirewall.c#L100) the *tables locking (if available)

**Comment by rsmontero** [comment]
We have added the wait lock for the iptables commands. ip_unpriv is needed by some drivers so it is kept in commands
