### ISSUE TITLE
Sunstone show "undefined" instead of IPv6 Alias address

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3626]
**Description**
Sunstone show "undefined" in the place of the IPv6 alias address

**To Reproduce**
 - add IPv6 alias to a VM NIC

**Expected behavior**
The IPv6 address should be shown in the relevant Alias row in sunstone

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.8.4]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
hi @atodorov-storpool, please u can send me a image for this issue and the VM Template

**Comment by atodorov-storpool** [comment]
Image of not-patched test instance:
![image](https://user-images.githubusercontent.com/11386997/64487430-53ad0300-d243-11e9-9dda-176308642774.png)

```
    <NIC>
      <ALIAS_IDS><![CDATA[1]]></ALIAS_IDS>
      <AR_ID><![CDATA[1]]></AR_ID>
      <BRIDGE><![CDATA[br2]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[linux]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[100]]></CLUSTER_ID>
      <MAC><![CDATA[52:54:00:12:00:1a]]></MAC>
      <MODEL><![CDATA[virtio]]></MODEL>
      <NAME><![CDATA[NIC0]]></NAME>
      <NETWORK><![CDATA[VM-ethernet]]></NETWORK>
      <NETWORK_ID><![CDATA[2]]></NETWORK_ID>
      <NIC_ID><![CDATA[0]]></NIC_ID>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-357-0]]></TARGET>
      <VN_MAD><![CDATA[dummy]]></VN_MAD>
    </NIC>
    <NIC_ALIAS>
      <ALIAS_ID><![CDATA[0]]></ALIAS_ID>
      <AR_ID><![CDATA[0]]></AR_ID>
      <BRIDGE><![CDATA[onebr.4004]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[linux]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[100]]></CLUSTER_ID>
      <IP6><![CDATA[2001:67c:21cc:50::1]]></IP6>
      <MAC><![CDATA[02:00:b4:e7:52:54]]></MAC>
      <MODEL><![CDATA[virtio]]></MODEL>
      <NAME><![CDATA[NIC0_ALIAS1]]></NAME>
      <NETWORK><![CDATA[v6-test]]></NETWORK>
      <NETWORK_ID><![CDATA[16]]></NETWORK_ID>
      <NETWORK_UNAME><![CDATA[oneadmin]]></NETWORK_UNAME>
      <NIC_ID><![CDATA[1]]></NIC_ID>
      <PARENT><![CDATA[NIC0]]></PARENT>
      <PARENT_ID><![CDATA[0]]></PARENT_ID>
      <PHYDEV><![CDATA[onebr]]></PHYDEV>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-357-1]]></TARGET>
      <VLAN_ID><![CDATA[4004]]></VLAN_ID>
      <VN_MAD><![CDATA[802.1Q]]></VN_MAD>
    </NIC_ALIAS>
```

With the patch applied it will show "2001:67c:21cc:50::1" instead of "undefined". For example a vm on patched sunstone(another cluster):
![image](https://user-images.githubusercontent.com/11386997/64487492-22810280-d244-11e9-80dc-dde3b36b7be9.png)

**Comment by jloboescalona2** [comment]
@tinova, PR by approval
- Test: https://github.com/OpenNebula/development/pull/734

**Comment by tinova** [comment]
thanks!
