### ISSUE TITLE
onecli list commands with -x option end in endless pager

### ISSUE THREAD

**Issue by mathijsmm** [OpenNebula/one#3628]
**Description**
When firing off the one cli commands to list items as XML (-x) and it goes into pager mode this will keep on scrolling forever, quitting it ends with a broken pipe error.

**To Reproduce**
Tested this with `oneacl list -x` and `oneuser list -x`, when output is longer than terminal height you get a pager, this can keep on going forever if you use the space bar to page down.
When quitting by pressing Q it fails with the following error.

```
/opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:717:in `write': Broken pipe (Errno::EPIPE)
	from /opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:717:in `puts'
	from /opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:717:in `puts'
	from /opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:717:in `block in list_pool_xml'
	from /opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:708:in `loop'
	from /opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:708:in `list_pool_xml'
	from /opt/opennebula/cli/58/lib/ruby/cli/one_helper.rb:774:in `list_pool'
	from /opt/opennebula/cli/58/bin/oneuser:547:in `block (2 levels) in <main>'
	from /opt/opennebula/cli/58/lib/ruby/cli/command_parser.rb:470:in `run'
	from /opt/opennebula/cli/58/lib/ruby/cli/command_parser.rb:84:in `initialize'
	from /opt/opennebula/cli/58/bin/oneuser:36:in `new'
	from /opt/opennebula/cli/58/bin/oneuser:36:in `<main>'
```

**Expected behavior**
The pager to stop paging at the end of data.

**Details**
 - Affected Component: CLI
 - Hypervisor: n.a
 - Version: 5.8.2 and 5.8.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

code: https://github.com/OpenNebula/one/pull/3640
docs: https://github.com/OpenNebula/docs/pull/730
