### ISSUE TITLE
Cluster-wide CPU/MEM reservations scratched on host update

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3630]
**Description**
When RESERVED_CPU and/or RESERVED_MEM is specified in cluster template, it reflects in the host object on next monitoring cycle. Unfortunately, if host template update is triggered, the core doesn't recompute available capacity including the reserved **cluster-wide** resources and releases those reservations until next monitoring cycle

On host update, recomputation happens only with reserved resources defined in the host template. E.g., if cluster defines CPU/MEM reservation, but host overrides only MEM reservation, the MEM reservation subtracts from the total, but non-overriden CPU is scratched until next monitoring cycle.

**To Reproduce**
1. in cluster template, have
```
RESERVED_CPU="100"
RESERVED_MEM="5000000"
```

2. wait until first monitoring cycle reflecting change happens, validate host. E.g.:
```
$ onehost show 4 | grep TOTAL
  TOTAL               : 15.4G               
  TOTAL +/- RESERVED  : 10.7G               
  TOTAL               : 200                 
  TOTAL +/- RESERVED  : 100                 
```

3. trigger dummy update
```
$ onehost update 4 -a $(mktemp)
```

4. check host object for scratched reservations

```
$ onehost show 4 | grep TOTAL
  TOTAL               : 15.4G               
  TOTAL +/- RESERVED  : 15.4G               
  TOTAL               : 200                 
  TOTAL +/- RESERVED  : 200             
```

**Details**
 - Affected Component: Core
 - Version: 5.8.4

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge:
* one: #3678  into master
* development: OpenNebula/development#711 into master
* docs: OpenNebula/docs#746 into master
