### ISSUE TITLE
Incorrect DEV_PREFIX when create image using command "oneimage create"

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#3631]
**Description**
When you use the command "oneimage create" using for the input image a qcow2 image and put the output to a vcenter datastore, you will get: 

DEV_PREFIX	hd	   
DRIVER	        qcow2

**To Reproduce**
You need have a instance of ONE running with a vcenter imported.
Then you can execute the next command

> oneimage create -d 'nfs(IMG)' --type OS --name 'Image Name' --path 'http://server/where/is/image/image.qcow2' --driver qcow2

**Expected behavior**
In the image template
DEV_PREFIX	sd

**Details**
 - Hypervisor: [vCenter]
 - Version: [one-5.8 and master]

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
needs change in oned.conf to inherit DEV_PREFIX from DS
also needs documentation in vcenter section

**Comment by carloshm91** [comment]
[DOC] 
* https://github.com/OpenNebula/docs/pull/766
[ONE] 
* https://github.com/OpenNebula/one/pull/3632
