### ISSUE TITLE
System Wide CPU model configuration

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3666]
**Description**
CPU_MODEL currently can be set on a per-template basis. It would be suitable to also have a global configuration option for this, like the ones already in `/etc/one/vmm_exec/vmm_exec_kvm.conf`

**Use case**
Usability

**Interface Changes**
None

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge:
* one: #3704  into master
* docs: OpenNebula/docs#759 into master
