### ISSUE TITLE
Cluster-wide CPU model configuration

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3673]
**Description**
Deployed VMs will inherit the CPU model value from the Cluster they are deployed on. 

**Use case**
Usability, for instance, if one cluster has Xeon virtualization nodes and another cluster has AMD Epyc virtualization nodes, it would be ideal to be able to set a different default CPU model for those without needing to encode it into templates.

**Interface Changes**
- Sunstone should show the CPU_MODEL parameter of the cluster.

**Additional Context**
The Cluster will also have a new CPU model attribute. The Scheduler needs to alter the VM template based on the Cluster selection.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
All values from vmm_exec_kvm.conf can be overriden in Cluster and Host
PRs for merge:
* one #3775 to master
* development OpenNebula/development#752 to master
* docs OpenNebula/docs#779 to master
