### ISSUE TITLE
Edit vCenter virtual network context fails

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3675]
**Description**
When updating the context section of a virtual network imported from vCenter, sunstone fails with the following error: `One or more required fields are missing or malformed`. This is because the fields "Switch name" and "OpenNebula's Host ID" under Conf are not filled.

**To Reproduce**
Import a vnet from vCenter and try to update the context section.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 5.8.x

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4395

[DOC]
* https://github.com/OpenNebula/docs/pull/1063
