### ISSUE TITLE
Duplicated option -p in some onedb cLI commands

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3696]
**Description**
The option `-p` is used for pages and password in `onedb purge` commands.

**Expected behavior**
The option `-p` should be just for password.

**Details**
 - Affected Component: CLI
 - Version: 5.8.4 and development.

**Additional context**
``` 
$ onedb purge-done --help 
## USAGE 
purge-done 
Deletes all VMs in DONE state

**WARNING**: This action is done while OpenNebula is running. Make 
a backup of the datasbase before executing. 
valid options: start_time, end_time, pages

## OPTIONS 
-s, --start TIME First time to process 
-e, --end TIME Last time to process 
-p, --pages pages Nummber of pages to purge VMs 
-v, --verbose Verbose mode 
-h, --help Show this message 
-V, --version Show version and copyright information 
-s, --sqlite file SQLite DB file 
-S, --server host MySQL server hostname or IP. Defaults to 
localhost 
-P, --port port MySQL server port. Defaults to 3306 
-u, --username user MySQL username 
-p, --password pass MySQL password. Leave unset to be prompted for it 
-d, --dbname dbname MySQL DB name for OpenNebula 
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

code: https://github.com/OpenNebula/one/pull/3708
docs: https://github.com/OpenNebula/docs/pull/760
