### ISSUE TITLE
Sunstone instantiate more VMs at once trigger history back too many times

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3715]
**Description**
When more that one instance is instantiated in Sunstone, the browser goes back too many times. There are also situations when cames back to another site. This also causes that not all requested instances are instantiated.

**To Reproduce**
Instantiate more VMs in Sunstone, for example, 10

**Expected behavior**
On hitting the Instantiate button, the browser should go back only one, to the previous page.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: ANY
 - Version: 5.6+

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR's to approval:
-ONE: https://github.com/OpenNebula/one/pull/3779
-Docs: https://github.com/OpenNebula/docs/pull/782
