### ISSUE TITLE
VN Template Issues in Sunstone

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3753]
**Description**
There are two issues in Virtual Network Templates.

1. In Info tab, only first attribute edit button works, other doesnt work and thereforce attribute can not be quckly  updated
<img width="693" alt="Screenshot 2019-09-22 at 21 30 38" src="https://user-images.githubusercontent.com/951648/65393389-3a966d00-dd80-11e9-9d95-5a68f3353007.png">

2. GUEST_MTU from Context tab is not saved

**Details**
 - Affected Component: Sunstone
 - Hypervisor: Any
 - Version: 5.8+

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@feldsam hi!, you can send a virtual network template, tell me a bit, how do you make this error, I can't reproduce it

**Comment by feldsam** [comment]
Hi, I just clicking via sunstone. I create VN Template and then I can not edit attributes via sunstone UI, just manually by editing template directly. Another thing is, that GUEST MTU is not saved. Probably because whole CONTEXT section is not save?

**Comment by jloboescalona2** [comment]
@tinova  PR's to approve:
-One: https://github.com/OpenNebula/one/pull/3811
-Docs: https://github.com/OpenNebula/docs/pull/795
