### ISSUE TITLE
Instance name in leases tab

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#3758]
**Description**
Show Instance name column after instance id

**Use case**
If you have a lot of leases you can see more easily the VMs that have this AR.

**Interface Changes**
Sunstone and CLI

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4808
- Docs: https://github.com/OpenNebula/docs/pull/1146
