### ISSUE TITLE
Support quotas for Snapshots

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3769]
**Description**
There is need some mechanism to tracking snapshots usage size and quotas for control this

**Use case**
We want to allow using snapshots but prevent abuse them.

**Interface Changes**
Snapshots size can be summarized with main disk size or counted separately.
BTW OpenNebula already having interface for display snapshots size, now we need to control it somehow.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
ref https://github.com/OpenNebula/one/issues/3343

**Comment by atodorov-storpool** [comment]
+1

I'd add the number of snapshots too

**Comment by rsmontero** [comment]
This is currently implemented as part of the SYSTEM_DS disk quota.

**Comment by paczerny** [comment]
> What is resolved actually?

The VM snapshot size is counted towards `VM_QUOTA/VM/SYSTEM_DISK_SIZE_USED`
The VM disk snapshots are counted either to `VM_QUOTA/VM/SYSTEM_DISK_SIZE_USED` or `DATASTORE_QUOTA/DATASTORE/SIZE_USED` depending on the CLONE_TARGET or LN_TARGET.

> Am I the only one that can not track the changes in the code?
Where are the commits that resolved this?

The VM snapshot part was solved by the #5524 issue, [commit](https://github.com/OpenNebula/one-ee/commit/5591f88a3b140a1da2ffa78bcd3f47b80cf5bf59)

**Comment by atodorov-storpool** [comment]
Hey @paczerny 
Thank you for the prompt response!

>Am I the only one that can not track the changes in the code?
>Where are the commits that resolved this?

>The VM snapshot part was solved by the #5524 issue, commit

I'd prefer pointing to a commit that is public...
Anyway, I found https://github.com/OpenNebula/one/commit/5591f88a3b140a1da2ffa78bcd3f47b80cf5bf59 hope we are on the same page.

>>What is resolved actually?

>The VM snapshot size is counted towards VM_QUOTA/VM/SYSTEM_DISK_SIZE_USED
>The VM disk snapshots are counted either to VM_QUOTA/VM/SYSTEM_DISK_SIZE_USED or >DATASTORE_QUOTA/DATASTORE/SIZE_USED depending on the CLONE_TARGET or LN_TARGET.

Thank you for the explanation it is clear now.

>\#  VM_SNAPSHOT_FACTOR: How much disk size is counted as disk snapshot
>\#  size. Default value 0 (0%) (Use 0.1 means 10%)
>VM_SNAPSHOT_FACTOR = "0"

I think the default value should be 100% (VM_SNAPSHOT_FACTOR = "1")? IMHO having accounted only the memory by default had no real use case?

Also, what about a variable like VM_SNAPSHOT_MEMORY_FACTOR to be available too?

Generally speaking, I think it is best for the vmm/snapshot_create script to report the stored size of the VM snapshot so no need to do math calculations or estimates...
