### ISSUE TITLE
Disk Save As not working with container and ssh TM drivers

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#3778]
**Description**
Disk Save as does not work on LXD containers if SSH TM driver is used. This is the log:

```
Thu Sep 26 16:18:21 2019 [Z0][VM][I]: New LCM state is HOTPLUG_SAVEAS 
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/tm/ssh/cpds ***********-lxd:/var/lib/one//datastores/102/34/disk.0 /var/lib/one//datastore
s/103/084494908d7cce93ba4cd2f9a01f92fe -1 34 103
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: cpds: VM is running, trying blockcopy, fsfreeze, suspend 
Thu Sep 26 16:18:23 2019 [Z0][TM][E]: cpds: Command "touch /var/lib/one/datastores/102/34/disk.0.vm6PFBJ7
Thu Sep 26 16:18:23 2019 [Z0][TM][I]:
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: if ! virsh -c qemu:///system blockcopy one-34 vda /var/lib/one/datastores/102/34/disk.0.vm6PFBJ7 --wait --finish; then
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: set -e -o pipefail
Thu Sep 26 16:18:23 2019 [Z0][TM][I]:
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: if virsh -c qemu:///system domfsfreeze one-34; then
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: trap "virsh -c qemu:///system domfsthaw one-34" EXIT TERM INT HUP
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: cp /var/lib/one/datastores/102/34/disk.0 /var/lib/one/datastores/102/34/disk.0.vm6PFBJ7
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: elif virsh -c qemu:///system suspend one-34; then 
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: trap "virsh -c qemu:///system resume one-34" EXIT TERM INT HUP
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: cp /var/lib/one/datastores/102/34/disk.0 /var/lib/one/datastores/102/34/disk.0.vm6PFBJ7
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: else
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: echo "Could not domfsfreeze or suspend domain" >&2
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: exit 1
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: fi
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: fi" failed: error: failed to get domain 'one-34'
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: error: Domain not found: no domain with matching name 'one-34'
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: error: failed to get domain 'one-34'
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: error: Domain not found: no domain with matching name 'one-34'
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: error: failed to get domain 'one-34'
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: error: Domain not found: no domain with matching name 'one-34'
Thu Sep 26 16:18:23 2019 [Z0][TM][I]: Could not domfsfreeze or suspend domain
Thu Sep 26 16:18:23 2019 [Z0][TM][E]: Error creating export for domain one-34 of disk vda at /var/lib/one/datastores/102/34/disk.0.vm6PFBJ7
Thu Sep 26 16:18:23 2019 [Z0][TM][E]: cpds: Exporting failed
Thu Sep 26 16:18:23 2019 [Z0][TM][E]: Error executing image transfer script: Error creating export for domain one-34 of disk vda at /var/lib/one/datastores/102/34/disk.0.vm6PFBJ7 
Thu Sep 26 16:18:23 2019 [Z0][VM][I]: New LCM state is RUNNING 
```

Problem is on *ssh/cpds*, it will try first to **blockcopy**, if it fails it will try to **domfreeze** and then to **suspend**. This is important on KVM VMs (https://github.com/OpenNebula/one/issues/2438) but will fail with LXD containers. Perhaps the script should not fail if all of these operations fail, but continue (this is assuming that the **continue** case will only happen for LXD containers (in the ideal case)).

**To Reproduce**
Launch a LXD container with a persistent image located on a SSH datastore and try "Disk Save as" while the container is running.

**Expected behavior**
TM operations should be agnostic to the hypervisor, so this should also work with LXD containers.

**Details**
 - Affected Component: Storage
 - Hypervisor: LXD
 - Version: .....all?

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
Instead of *Continue* a *lxc pause* could be added to guarantee consistency in containers.

**Comment by sergiojvg** [comment]
Problem when using lxc pause is that the container becomes completely unresponsive, and it will keep on that state until the backup finishes (which could take a long time). This is not the case when freezing a KVM (not completely sure, in this case writes are not permitted but reads are allowed.....I think....)

**Comment by sergiojvg** [comment]
A good strategy to avoid pausing the containers (and could also be extended to VMs) is to do the first scp (or whatever copy tool) and as soon as it finishes do an rsync, so it will only copy the differences that appeared during the copy. This should greatly reduce inconsistencies. By default rsync avoids delta-xfer algorithm if copy is local, so this would imply to copy the image again, this must be avoided.

**Comment by rsmontero** [comment]
Fixed. 6.0 will not allow live saveas operations to prevent corruption of disk images. We'll improve (e.g. lxc-freeze/unfreeze) in next release
