### ISSUE TITLE
UX bug in the VM creation form.

### ISSUE THREAD

**Issue by mhutchison89** [OpenNebula/one#3797]
Just wanted to point out a UX bug in the 5.8.0 build. In the Create Virtual Machine (from template) form is being filled out, the tool tip under Network Selection > Automation Selection has an EN spelling error, "The Schedule will decide which is the bets virtual network"

![OpenNebulaUX](https://user-images.githubusercontent.com/20227156/66007410-98f1d880-e46f-11e9-8057-2ae3e2c9d269.png)

Thanks!  Really like the new features.

**Comment by mhutchison89** [comment]
Cool.  I should have checked that.

Thanks.

**Comment by carloshm91** [comment]
Thanks to you for the help !!
