### ISSUE TITLE
Global quotas for storage

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#3813]
**Description**
Global quotas (aggregate of quotas) per user

**Use case**
This allow the users distribute their quota between several datastores

**Interface Changes**
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API  

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
duplicated: https://github.com/OpenNebula/one/issues/1344

**Comment by kvaps** [comment]
We're still need a solution for this

**Comment by tinova** [comment]
duplicated: https://github.com/OpenNebula/one/issues/1344 (thanks kvaps)
