### ISSUE TITLE
Upgrade to 5.8.5 sunstone doesn't finish loading

### ISSUE THREAD

**Issue by MaxDiOrio** [OpenNebula/one#3815]
**Description**
Using the CentOS RPM repository, I did a yum update and OpenNebula was upgraded to 5.8.5.  The upgrade went without issue and no errors were found.  Upon logging into OpenNebula, I get a spinning icon only, with nothing else loading on the page other than the footer with the open nebula version.

I am getting:  Failed to load resource: the server responded with a status of 403 (Forbidden) http://devportal/dist/main.js?v=5.8.5

In the httpd log, I'm getting:

[core:error] [pid 1496] [client 10.85.144.76:52684] AH00037: Symbolic link not allowed or link target not accessible: /usr/lib/one/sunstone/public/dist/main.js, referer: http://devportal/

If I copy the symlink destination main.js file to /usr/lib/one/sunstone/public/dist/main.js and chmod 777, it works fine.  But then I'm left with another issue:

Failed to load resource: the server responded with a status of 400 (Bad Request).  http://devportal/support/check?csrftoken=082395d18e7ee0fd32f95e1f97af3cc85f33c72dffd9a2ca9e232c50a8db99f5

This whole thing stems from the inability to import wilds from vCenter 6.7

**To Reproduce**
Yum update to 5.8.5 from the https://downloads.opennebula.org/repo/5.8/CentOS/7/x86_64 repo.  Was on 5.8.2 I believe before the upgrade.

**Expected behavior**
No errors, page should load fine.

**Details**
Sunstone

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
This is a permission error, the step for fixing it are explained here: http://docs.opennebula.org/5.10/deployment/sunstone_setup/suns_advance.html#configuring-memcached

Please follow the steps and if the error persist don't hesitate to reopen the issue.
