### ISSUE TITLE
Wrong values in running quotas when making a disk-snapshot

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3826]
**Description**
When a disk-snapshot is performed with the VM in **poweroff** state, running quotas are updated because after **snapshot** state the VM enters in poweroff again.

**To Reproduce**
Create a disk-snapshot while the VM is powered off.

**Expected behavior**
Running quotas shouldn't be updated on disk-snapshot operations.

**Details**
 - Affected Component: Core
 - Version: 5.8 series and development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge on master:

code: https://github.com/OpenNebula/one/pull/3829
docs: https://github.com/OpenNebula/docs/pull/797
