### ISSUE TITLE
Sunstone: template wizard wipes SCHED_RANK attribute

### ISSUE THREAD

**Issue by lgrawet** [OpenNebula/one#3832]
**Description**
SCHED_RANK containing expression such as "FREE_CPU * 100 - TEMPERATURE" (this example comes from official documentation) is wiped after template update.

**To Reproduce**
Steps to reproduce the behavior.
- Create a new template
- Click update
- Click on "Scheduling" tab then on "Policy" tab
- Fill "Host Rank" field with "FREE_CPU * 100 - TEMPERATURE"
- Click update to save the template
- The SCHED_RANK attribute is present in the template
- Click update to launch the wizard
- "Host Rank" field is now empty
- Click update to save the template
- The SCHED_RANK attribute is lost

**Expected behavior**
The SCHED_RANK attribute is preserved after template updates.

**Details**
 - Affected Component: Sunstone

 - Hypervisor: KVM

 - Version: 5.8.5

**Additional context**
We've just upgraded from 5.2 to 5.8.5 ans we are loosing all our placements rules!

Thanks for your help,

Laurent

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve
-One: https://github.com/OpenNebula/one/pull/3843
-Docs: https://github.com/OpenNebula/docs/pull/801

**Comment by tinova** [comment]
Needs testing

**Comment by lgrawet** [comment]
Hi,

Thanks for the fix. I've justed the patch on 5.8.5. It solves half the problem. 
- The SCHED_RANK attribute remains untouched in the template: OK
- The "Host Rank" field in the wizard remains blank while editing the template: NOK

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
-One: https://github.com/OpenNebula/one/pull/3879

**Comment by lgrawet** [comment]
I've just tested it on 5.8.5 and everything is fine now.
Many thanks @jloboescalona2 and @tinova!
