### ISSUE TITLE
Hover text on download buttons

### ISSUE THREAD

**Issue by myjapan** [OpenNebula/one#3836]
**Description**
It would be nice a hover text like "Add to datastore" and "Download" over the two cyan buttons on top of Apps page
![immagine](https://user-images.githubusercontent.com/10814527/66656347-166ed300-ec3e-11e9-8649-31d28ce70508.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
This has been already fixed in https://github.com/OpenNebula/one/issues/2728
