### ISSUE TITLE
vCenter:snapshot+poweron=disk metadata is corrupted and you have snapshots

### ISSUE THREAD

**Issue by crollorc** [OpenNebula/one#3844]
I'm using OpenNebula 5.8.5 to provide console and power control to a vCenter cluster.

All VMs are imported from Wilds.

Once imported, I've found that I can take a VM snapshot (Snapshots->Take snapshot).

However, following this it is not possible to poweron the VM from within OpenNebula due to the following error:
> Mon Oct 14 14:01:38 2019 [Z0][VMM][I]: Command execution failed (exit code: 255): /var/lib/one/remotes/vmm/vcenter/deploy '/var/lib/one/vms/71/deployment.1' 'vfcc1' 71 vfcc1
> Mon Oct 14 14:01:38 2019 [Z0][VMM][E]: deploy: Deploy of VM 71 on vCenter cluster vfcc1 with /var/lib/one/vms/71/deployment.1 failed due to "disk metadata is corrupted and you have snapshots"on the attempt #1.

**Comment by crollorc** [comment]
It has happened on both VMs which I tested so far.

The same problem happens for snapshots taken from vCenter and from OpenNebula.

Are there any particular logs or information which might help?

**Comment by tinova** [comment]
Can you provide the "onevm show -x" of the VM in a gist?

**Comment by crollorc** [comment]
Here you go: [onevm show -x 72](https://gist.github.com/crollorc/bc89cbda7146dc641bb9b76ea68fe543)

**Comment by tinova** [comment]
Thanks a lot. We need to check now the .vmx of the VM, can you also provide that?

**Comment by crollorc** [comment]
Here is the VMX: [colm-ubuntu1.vmx
](https://gist.github.com/crollorc/a21e6a3cb728ec6c861f91ea47b26c00)

**Comment by tinova** [comment]
The "opennebula.disk.*" attribute is missing from the .vmx, this is what is triggering the error. Can you import a new Wild, and check if the .vmx file has these parameters?

**Comment by crollorc** [comment]
I've imported a wild which was turned off and this resulted in the addition of the following attributes to the vmx file:
> remotedisplay.vnc.enabled = "TRUE"
> remotedisplay.vnc.port = "5974"
> remotedisplay.vnc.ip = "0.0.0.0"

If I turn that VM on and off from OpenNebula and check the vmx, I see the addition of the following attributes:

> opennebula.vm.running = "yes"
> guestinfo.opennebula.context = "IyBDb250ZXh0IHZhcmlhYmxlcyBnZW5lcmF0ZWQgYnkgT3Blbk5lYnVsYQpE|0ASVNLX0lEPScyJwpFVEgwX0NPTlRFWFRfRk9SQ0VfSVBWND0nJwpFVEgwX0RO|0AUz0nJwpFVEgwX0VYVEVSTkFMPScnCkVUSDBfR0FURVdBWT0nJwpFVEgwX0dB|0AVEVXQVk2PScnCkVUSDBfSVA9JycKRVRIMF9JUDY9JycKRVRIMF9JUDZfUFJF|0ARklYX0xFTkdUSD0nJwpFVEgwX0lQNl9VTEE9JycKRVRIMF9NQUM9JzAwOjUw|0AOjU2Ojg0OjZlOmU4JwpFVEgwX01BU0s9JycKRVRIMF9NVFU9JycKRVRIMF9O|0ARVRXT1JLPScnCkVUSDBfU0VBUkNIX0RPTUFJTj0nJwpFVEgwX1ZMQU5fSUQ9|0AJycKRVRIMF9WUk9VVEVSX0lQPScnCkVUSDBfVlJPVVRFUl9JUDY9JycKRVRI|0AMF9WUk9VVEVSX01BTkFHRU1FTlQ9JycKTkVUV09SSz0nWUVTJwpTU0hfUFVC|0ATElDX0tFWT0nJwpUQVJHRVQ9J2hkYicK|0A"
> uuid.location = "56 4d ee bd 81 d8 d2 6e-d3 8e df 20 9d d6 97 3b"

No sign of any opennebula.disk.* attributes.

**Comment by carloshm91** [comment]
We believe we have found the error in the code.
We will send you a patch as soon as we can so you can try.

**Comment by tinova** [comment]
Check documentation

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4055

[DOC]
* https://github.com/OpenNebula/docs/pull/961

[DEV]
* https://github.com/OpenNebula/development/pull/853
