### ISSUE TITLE
Unexpected behavior of `one.user.chgrp` method

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3846]
**Description**
Method `one.user.chgrp` have two different behaviors:

Eg:

```xml
<?xml version="1.0"?>
<methodCall>
    <methodName>one.user.chgrp</methodName>
    <params>
        <param><value>oneadmin:deadbeefdeadbeefdeadbeefdeadbeef</value></param>
        <param><value><i4>356</i4></value></param>
        <param><value><i4>156</i4></value></param>
    </params>
</methodCall>
```

**If user `356` is member of `1` group:**

OpenNebula will just switch current group for user.

**If user `356` is not member of `1` group:**

OpenNebula will remove user from the current group and add to new one.

**To Reproduce**

* Create user
* Create new group
* Run the method above

You will see: user will not be member of `users` group anymore.

**Expected behavior**

I expecting that OpenNebula will return an error, that user is not member of the group.
Or we should update the XML-RPC API documentation to describe both behaviors.

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: 5.8.5

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Yes this is the intended behavior in order to support primary and secondary groups. The user is removed from the old group only if the new group is not a  secondary one.

The idea is to use oneuser chgrp to change across the secondary groups (equivalent to unix newgrp) or change the primary.
