### ISSUE TITLE
KVM host CPU model

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3851]
**Description**
We gather `KVM_MACHINES` and `KVM_CPU_MODELS` to get supported (virtual) hardware specifications by the libvirt/QEMU. Regarding the `KVM_CPU_MODELS`, it's just a list of all available models, not the ones which can actually run on the machines.

It might be good to get also the actual hardware CPU model, which is closest to one of the available libvirt/QEMU CPU models:

```
virsh > capabilities
<capabilities>

  <host>
    <uuid>....</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>SandyBridge-IBRS</model>
```

the item is under `CAPABILITIES/HOST/CPU/MODEL` path.

Proposed parameter could be `KVM_CPU_MODEL` (without trailing `s`).

The extended machine models monitoring would look like:

```
KVM_MACHINES="pc-i440fx-rhel7.6.0 pc pc-i440fx-rhel7.0.0 ..."
KVM_CPU_MODELS="486 pentium pentium2 pentium3 pentiumpro coreduo ..."
KVM_CPU_MODEL="Skylake-Server-IBRS"
```

**Use case**
Better insight into what CPU model to choose (when not using the host passthrough).

**Additional Context**

Reference support ticket:
https://opennebula.zendesk.com/agent/tickets/11889

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches
__

**Comment by al3xhh** [comment]
PRs to merge in master:

code: https://github.com/OpenNebula/one/pull/3852
docs: https://github.com/OpenNebula/docs/pull/806
