### ISSUE TITLE
Can't update CPU model using Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3858]
**Description**
When try to update CPU model  using Sunstone, it doesn't update, the old one remains on it.

**To Reproduce**
Change the CPU model using Sunstone.

**Details**
 - Affected Component: Sunstone
 - Version: 5.6 5.8 and development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PRs to approve:
- ONE: https://github.com/OpenNebula/one/pull/3895
- Docs: https://github.com/OpenNebula/docs/pull/820
