### ISSUE TITLE
New Monitoring System

### ISSUE THREAD

**Issue by paczerny** [OpenNebula/one#3859]
**Description**
Monitoring system has limited scalability. For huge installations monitoring can slow down performance of the whole system.

Basic idea is to separate monitoring from oned to new monitoring daemon. Store monitoring data in separate (time series) DB. Reduce number of DB accesses.

**Use case**
Increase number of Host and VMs handled by oned

**Interface Changes**
xml-rpc API one.host.info and one.vm.info should have parameter to include monitor information.

**Additional Context**
More details [monitor design](https://docs.google.com/document/d/1cIw3lq3wwlzqlbGgxH2_1GakzIVk6uBSg9VcUiTtbaQ/edit#heading=h.q0xwvg9ykqqm) 

Also consider additional status mappings for every hipervisor in order to handle hipervisor-level status changes, for example, a VM that paused due to hipervisor node running out of space. This also would require new actions on the vmm drivers, like pausing and unpausing.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
> Store monitoring data in separate (time series) DB. Reduce number of DB accesses.
Consider also storing VM logs in tsdb
