### ISSUE TITLE
KVM time sync. after downtime

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3862]
**Description**

In the past, the libvirt introduced the `domtime XXXX --sync` command to instruct QEMU guest agent to synchronize the guest time from RTC. Although in general NTP server is recommended to run on both host and guest, the big time differences can't be automatically fixed by ntpd, or the fix doesn't happen fast enough.

Even in the oldest systems we support (Debian 9, Ubuntu 16.04), this feature is already supported.
https://forum.opennebula.org/t/fixing-windows-time-on-resume-in-kvm/3033

It might be good to follow the service `libvirt-guests` approach and optionally trigger `domtime XXX --sync` after resume, or migration. Although this doesn't fix all the time problems with the VMs, it might improve situation for some.

As described in `/etc/sysconfig/libvirt-guests`:

```
# If non-zero, try to sync guest time on domain resume. Be aware, that
# this requires guest agent with support for time synchronization
# running in the guest. For instance, qemu-ga doesn't support guest time
# synchronization on Windows guests, but Linux ones. By default, this
# functionality is turned off.
#SYNC_TIME=1
```

Proposed steps:

- in remote's `kvmrc`, introduce `SYNC_TIME` (default: `no`) parameter to allow global configuration of this new feature

- adapt KVM actions to trigger `domtime XXXX --sync` if `SYNC_TIME=yes`, but **ignore exit code** (operation might and will fail as it requires the domain to have qemu-ga running & RTC support !!!, this is just only helper, not a solution of all cases):
  - `restore`
  - maybe also `migrate` and `migrate_local`

- test the feature in **readiness** and **context**
  - break time
  - VM suspend / resume
  - check time is correct

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in **master**:

code: https://github.com/OpenNebula/one/pull/3874
docs: https://github.com/OpenNebula/docs/pull/816
tests: https://github.com/OpenNebula/development/pull/779
