### ISSUE TITLE
Make /usr/share/one/install_gems accept flags to allow an automated installation

### ISSUE THREAD

**Issue by HaehnleinMar** [OpenNebula/one#3865]
**Description**
Make /usr/share/one/install_gems accept flags to allow an automated installation

**Use case**
In our environment we want to install OpenNebula using Ansible. We currently pass the required input (Press Enter to continue, `Y` + Enter to install packages) via stdin. It would be more elegant to pass arguments to the executable to prevent interactive mode.
Also if the required packages are already present there is no need to pass `y` to the `yum install` command so it is not an elegant workarount passing the chars to stdin.

**Additional Context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
+1 for that, currently I'm using the next trick:
```bash
sed -i 's/apt-get install/apt-get -y install/g' /usr/share/one/install_gems
echo '0\n' | /usr/share/one/install_gems
```

**Comment by HaehnleinMar** [comment]
Actually this functionality is already present, just not well documented. You can invoke `install_gems` with the argument `--yes`.
