### ISSUE TITLE
Don't rely on `lsb_release` for `/usr/share/one/install_gems`

### ISSUE THREAD

**Issue by HaehnleinMar** [OpenNebula/one#3866]
**Description**
For `install_gems` in non-interactive mode the `lsb_release` command is necessary. This could be circumvented if `/etc/os-release` was parsed instead.

**Use case**
There would be one package that could be removed on CentOS / RHEL.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Already fixed by #4233.
