### ISSUE TITLE
Sunstone disk size slider on VM instantiate page fails sometimes

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#3868]
**Description**
The slider used for increase the size of a disk when instantiating the VM fails sometimes.

**To Reproduce**
- Go to instantiate page
- Change units from MB to GB
- Move the slider and take it back to the left (if decimals are used it will only let you take the next integer number)
- Instantiate the VM
- The disks size corresponds with the original one not with the next integer value whose value was in the text box.

**Details**
 - Affected Component: Sunstone
 - Version: 5.8.5

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
Solved in:
-ONE: #3884
-Docs: OpenNebula/docs#817

**Comment by tinova** [comment]
Thanks!
