### ISSUE TITLE
Storage migration fails on LVM datastore

### ISSUE THREAD

**Issue by sergjack** [OpenNebula/one#3872]
**Description**
When I'm trying to perform storage migration for vm it fails.
Command execution failed (exit code: 1): /var/lib/one/remotes/tm/fs_lvm/mv nebulanode3:/var/lib/one//datastores/101/722/disk.0 nebulanode3:/var/lib/one//datastores/106/722/disk.0 722 100
Thu Oct 17 17:36:49 2019 [Z0][TM][E]: mv: Command "dd if=/dev/vg-one-101/lv-one-722-0 of=/dev/vg-one-106/lv-one-722-0 bs=64k" failed: dd: failed to open '/dev/vg-one-101/lv-one-722-0': No such file or directory
Thu Oct 17 17:36:49 2019 [Z0][TM][E]: Error copying nebulanode3:/var/lib/one/datastores/101/722/disk.0 to nebulanode3:/var/lib/one/datastores/106/722/disk.0

Status of LV is inactive. Because script deactivating it before copy, so there is no such device.

**To Reproduce**
Pick vm on LVM datastore.
Choose vm. Choose migrate. Choose different datastore. Try to migrate.

**Expected behavior**
VM should migrate.

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
Storage
 - Hypervisor: [e.g. KVM]
KVM
 - Version: [e.g. 5.4.12 or development]
5.8.5 on Centos 7.

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This should be fixed in current version of OpenNebula. Closing as worksforme
