### ISSUE TITLE
race in "NIC is really absent after detach" check

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3873]
**Description**
Sometimes NIC detach fails on relatively loaded hosts.

**To Reproduce**
Attach NIC then try to detach it

**Expected behavior**
The NIC should be detached clearly. Also, if the interface is already not available the script must return success.

(pull request is on the way)

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [5.4+]

**Additional context**
After initial fail each try to delete the nic fails because the NIC is deleted.

Reproduction using the shell
```bash
[root@a1 ~]# time virsh detach-interface one-300 --type bridge --mac 02:00:51:0b:f2:8e; time virsh domiflist one-300
Interface detached successfully


real	0m5.027s
user	0m0.016s
sys	0m0.004s
Interface  Type       Source     Model       MAC
-------------------------------------------------------
one-300-0  bridge     br61       virtio      02:00:0a:02:01:c8
one-300-1  bridge     br219      virtio      02:00:51:0b:f2:8e

real	0m0.019s
user	0m0.013s
sys	0m0.005s
```
Running `virsh domiflist` again (a little bit later) the nic is detached:

```bash
[root@a1 ~]# time virsh domiflist one-300
Interface  Type       Source     Model       MAC
-------------------------------------------------------
one-300-0  bridge     br61       virtio      02:00:0a:02:01:c8

real	0m0.017s
user	0m0.012s
sys	0m0.005s
```

After the manual removal the NIC could not be deleted until the VM is powered down (and the delete operation is executed without calling `vmm_mad/detach_nic`.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
ref https://dev.opennebula.org/issues/5171

Hey wasn't this bug reported to libvirt team?

**Comment by kvaps** [comment]
ref #314
