### ISSUE TITLE
Configurable Frontend Hostname

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3881]
**Description**
OpenNebula frontend (`oned`) detects the frontend hostname simply via `gethostname`.

https://github.com/OpenNebula/one/blob/a1872c503e6713333c702818354979c89dadc107/src/nebula/Nebula.cc#L57

This hostname is used mainly in transfer manager operations to identify source

```
# cat transfer.0.prolog 
CLONE qcow2 frontend:/var/lib/one//datastores/1/f099ec28cb74235180f3df641d1c52d8 localhost:/var/lib/one//datastores/0/0/disk.0 0 1
            ^^^^^^^^
```

Unfortunately, `gethostname` doesn't have to provide full FQDN which might be good to have esp. when copying data back from nodes to frontend. Returned value is equivalent of simple `hostname` command, but not `hostname --fqdn`. **Note:** can be reproduced only if hostname and domain name are configured properly (see `man 1 hostname` section `THE FQDN`). Now it's very common that system hostname is configured with FQDN, which doesn't reveal the described problem.

Moreover, using detected frontend hostname for communication with nodes doesn't have to be appropriate when communication with nodes is expected to use different non-default NICs / IPs. It would be good if frontend hostname used in the drivers is configurable.

Tasks:
- improve FQDN detection
- have frontend hostname configurable via `oned.conf`

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4605
- docs: https://github.com/OpenNebula/docs/pull/1084
