### ISSUE TITLE
IPv4 address not shown in VM network tab

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#3882]
**Description**
There is no IPv4 address in VM network tab when dual stack is used. In place where was IP4 there is IP6_LINK. Caused by PR #3659

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: development

**Additional context**
![Screenshot 2019-10-27 at 00 32 33](https://user-images.githubusercontent.com/951648/67626855-a2454980-f851-11e9-89bf-5c987b440b41.png)
![Screenshot 2019-10-27 at 00 31 38](https://user-images.githubusercontent.com/951648/67626856-a2454980-f851-11e9-9e1d-daf625e63bb2.png)

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
What about this?

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4121 into 5.10 and master
• docs: OpenNebula/docs/pull/909 into one-5.10-maintenance
