### ISSUE TITLE
Allow disk resize greater than 1TB in Sunstone (firefox)

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3883]
**Description**
When using Firefox web browser, Sunstone fails to resize a disk greater than 1TB

**To Reproduce**
Try to resize a disk greater than 1TB in Sunstone using Firefox.

**Expected behavior**
The resize should be done.

**Details**
 - Affected Component: Sunstone

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PRs to approve:
-ONE: https://github.com/OpenNebula/one/pull/3884
-Docs: https://github.com/OpenNebula/docs/pull/817
