### ISSUE TITLE
Add option for creating VM in batches via API

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3904]
**Description**
It will be useful to be able to create VM in batches by using the API.

**Use case**
Deploy multiple VMs together to ensure that the scheduler take them all together.

**Interface Changes**
It would necessary to modify `one.template.instantiate` and `one.vm.allocate` API calls. 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This is implemented by two features:
* Multiple VMs can be instantiated with a single API call. [See onetempalte.instantiate.](https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#one-template-instantiate)
* VMGroups. Scheduler consider its allocation as a set
