### ISSUE TITLE
image's used quota doubles when changing its group

### ISSUE THREAD

**Issue by ArnY** [OpenNebula/one#3916]
**Description**
A user belongs to two groups (oneadmin and group1). The user create a 3TB image on a ceph datastore subjected to a quota. The user then change the image's group from oneadmin to group1. Group1's used quota should be 3TB but actually is 6TB.

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**
The datastore is a ceph datastore.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
This bug is still persist.

**Comment by paczerny** [comment]
@kvaps On which version you reproduced this bug?

I wasn't able to reproduce on 5.12.10 and 6.0.3. Maybe I'm doing something wrong. Is it limited only to ceph datastore or it applies also to other DS?

My steps, am I missing something?:
```
onegroup create ga
oneuser create a a
oneuser addgroup a ga
oneimage create -d 1 --name data --type DATABLOCK --size 32 --user a --password a
# There is no data usage for group ga yet
oneimage chgrp data ga  --user a --password a
onegroup show ga -x
... <SIZE_USED><![CDATA[32]]></SIZE_USED> ...
```

**Comment by rsmontero** [comment]
It seems this is works-forme, we'll reopen if needed
