### ISSUE TITLE
Custom inputs Forms

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#3920]
**Description**
A method is required so that by group or users the input data of the forms of all views can be shown or hidden

**Use case**
If you want to show an input, you only have to add it to the group or the user, a good idea is to save it in the group's template, but giving priority to the user's template.

Keep in mind: the creation of a default of each of the elements. each item in false

**Interface Changes**
all files .YAML

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
this is being redesign in #5422
