### ISSUE TITLE
Issue in 5.9.80 with bridge networking

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#3922]
**Description**

Running centos 7, have bridged networking with br0. Upgraded from 5.8.5 to 5.9.80 and tried creating a new vm. fails with:

```
Thu Nov  7 13:44:10 2019 [Z0][VMM][D]: Message received: LOG I 19 Successfully execute transfer manager driver operation: tm_context.

Thu Nov  7 13:44:11 2019 [Z0][VMM][D]: Message received: LOG I 19 Command execution fail: cat << EOT | /var/tmp/one/vnm/fw/pre

Thu Nov  7 13:44:11 2019 [Z0][VMM][D]: Message received: LOG I 19 /usr/share/ruby/base64.rb:58:in `decode64': undefined method `unpack' for nil:NilClass (NoMethodError)

Thu Nov  7 13:44:11 2019 [Z0][VMM][D]: Message received: LOG I 19 from /var/tmp/one/vnm/vnm_driver.rb:49:in `from_base64'

Thu Nov  7 13:44:11 2019 [Z0][VMM][D]: Message received: LOG I 19 from /var/tmp/one/vnm/fw/pre:28:in `<main>'

Thu Nov  7 13:44:11 2019 [Z0][VMM][D]: Message received: LOG I 19 ExitCode: 1

Thu Nov  7 13:44:11 2019 [Z0][VMM][D]: Message received: LOG I 19 Failed to execute network driver operation: pre.
```

**Details**
 - Affected Component: Scheduler
 - Hypervisor: KVM
 - Version: 5.9.80 from repo

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mzealey** [comment]
Appears that this was caused by /var/tmp on host servers still having the old scripts after the upgrade... should this not be automatically cleared by eg timestamp? `rm -fr /var/tmp/*` seems to fix it.

**Comment by atodorov-storpool** [comment]
```bash
su - oneadmin -c 'onehost sync --force --rsync'
```
