### ISSUE TITLE
Hook tables not getting created in upgrade

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#3925]
**Description**

Upgraded 5.8.5 to 5.9.80 and tried creating a hook:

```
Fri Nov  8 07:57:44 2019 [Z0][ReM][E]: Req:5168 UID:0 one.hookpool.info result FAILURE [one.hookpool.info] Internal error
Fri Nov  8 07:57:45 2019 [Z0][ReM][D]: Req:6784 UID:0 IP:127.0.0.1 one.hookpool.info invoked , -1, -1, -1
Fri Nov  8 07:57:45 2019 [Z0][ONE][E]: SQL command was: SELECT body FROM hook_pool WHERE (uid = 0 OR ( ( ( gid = 0 )))) ORDER BY oid DESC, error 1146 : Table 'opennebula.hook_pool' doesn't exist
```

and then

```
Fri Nov  8 07:58:59 2019 [Z0][ONE][E]: SQL command was: SELECT IFNULL(MAX(exeid), -1), COUNT(*) FROM hook_log WHERE hkid = 2, error 1146 : Table 'opennebula.hook_log' doesn't exist
```

**Expected behavior**

I would have expected that the db upgrade process create these tables. I have repeatedly run the db upgrade process with -f and fsck'd the database and no errors were reported.

**Details**
 - Affected Component: core
 - Hypervisor:KVM
 - Version: 5.9.80

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
This issue was fixed by this commit https://github.com/OpenNebula/one/commit/454863f61af044d45af2bea4c4b795f6f167d9ca. It will be released with OpenNebula 5.10 RC
