### ISSUE TITLE
Live snapshots on ssh datastore

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#3927]
**Description**

Allow qcow2 images on ssh datastore to have live snapshots taken

**Use case**

I'm admining a cluster of vm hosts with independent local storage. All images are based on qcow2. However due to the fact the datastore is ssh it seems impossible to snapshot without taking the vm offline and then it basically just copies the image file. As the backing image is qcow2 I'm unsure why the qcow2 data store drivers would not work for the snapshotting functionality?

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by myjapan** [comment]
Yes, I'm definitely into this.
We have a image_ds backed by ceph, VMs deployed locally on nodes using  ssh.
I asked in the forum, waiting for an answer.
https://forum.opennebula.org/t/unable-to-take-snapshot-with-ceph-image-ds-deploy-mode-ssh/7808

**Comment by xorel** [comment]
You can combine qcow2 image datastore with ssh transfer mode, in this setup you can use qcow2 features like live snapshots and still utilize the local storage.

Please, see here:
http://docs.opennebula.org/5.8/deployment/open_cloud_storage_setup/fs_ds.html

The image datastore is still qcow2 however the system datastore has option
`TM_MAD="ssh"`.

However, for Ceph it's different. When you use ssh transfer mode with Ceph, the image is exported on hypervisor from the Ceph to the raw format, so the live snapshots are not possible.
