### ISSUE TITLE
Problem deploying VM in vCenter due to different summary

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3940]
**Description**
Sometimes when a VM is going to be deployed in vCenter, the summary of some disks (the summary is the size in KB) doesn't match between the template and the VM, so the driver fails to deploy.

**To Reproduce**
Add different summary.

**Expected behavior**
It shouldn't fail, but it should show some message in the log.

**Details**
 - Hypervisor: vCenter

**Additional context**

```
failed due to "disk with path <path> not found in the vCenter VM"on the final attempt.
```

Problematic line, 875 in `src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb`
```
vcenter_disk  = vcenter_disks.select{|d| d[:key] == template_disk[:key] && d[:device].deviceInfo.summary == template_disk[:device].deviceInfo.summary}.first
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Closing as unsure i the summary check needs to be removed. Still need to see a valid case for it. Will reopen if needed.
