### ISSUE TITLE
MySQL Client Connection Encoding

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3946]
**Description**

Today, the MySQL database/tables encoding depends on MySQL server defaults (which is mostly `latin1`, since MySQL 8.0 changed to `utf8mb4`. OpenNebula doesn't propose any particular table encoding and depends on server side defaults. **Most of the users' tables will be most likely `latin1` these days,** unless changed defaults or converted them into `utf8`.

Client connection ("transfer") encoding depends mainly on client compiled-time defaults and can't be easily set, so they are mostly `latin1` for old versions and `utf8mb4` for new versions as well. **Client connection encoding might be different to tables encoding, but same connection encoding used to send data need to be preserved when receive the data back.**

Some clients respect locales or `my.cnf` client configuration for the connection encoding, but that doesn't look to me like a `oned` case which depends mainly on client library defaults. **Even if database is utf8, most clients will use (default) latin1 connection these days.**

If server **OR** client side version is upgraded with one with changed defaults, it's necessary to enforce connection defaults on the server side to old ones "not very nice way" with options like:

```
[mysqld]
init_connect='SET NAMES latin1'   # .... somehow doesn't work to me right now
character-set-server = latin1
skip-character-set-client-handshake
```

which obviously enforces all database clients to `latin1`.

It might be good to have parameter to specify connection (transfer/client) encoding on clients, if necessary to override the defaults. Which, should do at the end:

```
SET NAMES 'selected_encoding'
```

on the very first connect. CLI `onedb` should be covered as well.

Similar issue https://github.com/OpenNebula/one/issues/1557

**Steps to reproduce**
- Have installation with old `latin1` defaults (e.g., Ubuntu 19.04)
- Have UTF-8 characters in the templates
- In-place distribution upgrade to Ubuntu 19.10+ (with `utf8mb4` defaults)
- Reinstall same OpenNebula version from repository specific to the distribution version
- Have broken UTF-8 characters in the templates

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
^ @christian7007  probably a wrong commit was picked?

**Comment by christian7007** [comment]
What do you mean @atodorov-storpool ? It seems that your commit have merged this one https://github.com/OpenNebula/one/commit/f82fb5ec3d70b03e33bd3377c786cb26c7995647 with new changes.

**Comment by atodorov-storpool** [comment]
Ah, I see. I was just surprised when this thread popped up in my GitHub account.

Sorry for the noise.

**Comment by christian7007** [comment]
Don't worry
