### ISSUE TITLE
Error when attaching a disk to a VM using hybrid mode

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#3949]
**Description**
When a disk is attached to VM using [hybrid modes](http://docs.opennebula.org/5.8/deployment/open_cloud_storage_setup/fs_ds.html#combining-the-shared-ssh-transfer-modes) it fails.

**To Reproduce**
Attach a disk to a VM when there is two different DS types.

**Expected behavior**
The right driver is used and the image is attached to the VM.

**Details**
 - Version: 5.10

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Here is the diff from the VM xml when the disk is attached to already existing VM vs. disk is present already in the VM template during instantiate.

```
# Attched to running vm                        #  Instantiated with disk in template 
                                                                                                                                                                      
<CLONE_TARGET><![CDATA[SELF]]></CLONE_TARGET>  |  <CLONE_TARGET><![CDATA[SYSTEM]]></CLONE_TARGET> 
<DISK_ID><![CDATA[2]]></DISK_ID>               |  <DISK_ID><![CDATA[1]]></DISK_ID> 
<DISK_TYPE><![CDATA[RBD]]></DISK_TYPE>         |  <DISK_TYPE><![CDATA[FILE]]></DISK_TYPE> 
<LN_TARGET><![CDATA[NONE]]></LN_TARGET>        |  <LN_TARGET><![CDATA[SYSTEM]]></LN_TARGET> 
                                               >  <IMAGE_UNAME><![CDATA[oneadmin]]></IMAGE_UNAME> 
<TYPE><![CDATA[RBD]]></TYPE>                   |  <TYPE><![CDATA[FILE]]></TYPE>
```
