### ISSUE TITLE
[GOCA] Allow HTTP client configuration

### ISSUE THREAD

**Issue by eripa** [OpenNebula/one#3952]
**Description**
The GOCA library currently does not allow customizing the HTTP client parameters. It would be great to be able to, as a user, configure things like timeouts and the User Agent.

**Use case**
Sometimes your application using this library isn't on your local network, and the application needs longer timeouts. It would also be good to be able to tweak other parts of the HTTP connection. 

**Interface Changes**
The easiest way to allow this is to either a) have a method that allows you to configure the private HTTP client in [NewClient()](https://github.com/OpenNebula/one/blob/master/src/oca/go/src/goca/client.go#L95-L102), or b) grant public access to the struct field.

**Additional Context**
N/A

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by treywelsh** [comment]
**a)** A new method `NewClient` could be added, but as in Go there is no method overloading, a new name should be found.

If everyone is OK, we could rename the initial method `NewDefaultClient`, and then change the `NewClient` prototype to `NewClient(conf *OneConfig, httpClient *http.Client)`
If httpClient is nil, we could just make a call to `NewDefaultClient`.... ?
The new name `NewDefaultClient` reflect what the method do, i.e. returning a client with a default configuration. 
Personally, I prefer this solution (among others I see), but it introduce a breaking change.

Anyway, I find useful to have a default configuration for the user that don't want to deal with the http client at first.

**b)** Even with proposal a) I find this proposal still relevant.

In fact, I have no big argument to keep the http client private.
If the client only want to make partial changes (as modifying timeouts only) to the http client configured by default, I don't see any problem with this.

Feel free to criticize, this is only my point of view :)

**Comment by treywelsh** [comment]
For a) I can understand that people don't want breaking changes, we could just add a method named like: `NewClientAdvanced` or `NewClientWithHttp`.

If you see a better name ... :)

**Comment by eripa** [comment]
Thanks for the quick and elaborate response. I also agree that renaming `NewClient` to `NewDefaultClient` is the way to go. The main argument against is that this approach will break compatibility. If people are OK with that, then we should do it.

If not, I'd suggest using the the `NewCustomClient(conf *OneConfig, httpClient *http.Client)` approach. Either works for me, but the first approach is more natural.

**Comment by christian7007** [comment]
Hello @treywelsh and @eripa,

We are planning the OpenNebula 5.10 release for early next week. So if you can have those breaking changes ready for tomorrow they could be released in 5.10 with the other great changes made by @treywelsh

**Comment by eripa** [comment]
hey @christian7007 @treywelsh,

I submitted a PR, please review and propose changes as necessary.

**Comment by christian7007** [comment]
It looks good to me. What do you thing @treywelsh?

The only thing left is update the examples in `one/src/oca/go/share/examples/ha_raft_status.go` and `one/src/oca/go/src/goca/helper_test.go`. 

Probably you will need to update this last one in order to TravisCI accept your changes (https://travis-ci.org/OpenNebula/one/builds/614640903?utm_source=github_status&utm_medium=notification). But I can update the examples once the PR is merged.

Also, it would be nice if you could sign your commit: https://github.com/OpenNebula/one/pull/3965/checks?check_run_id=312212088

**Comment by treywelsh** [comment]
All the examples needs to be updated.

It's not specifically related to this issue, but it would be the case if the doc was up to date:  http://docs.opennebula.org/5.9/integration/system_interfaces/go.html#code-sample
