### ISSUE TITLE
let configuration be updated in state BOOT_FAILURE

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#3953]
**Description**
Updating a configuration should not be blocked by errors. But you're not allowed to do it.

```
[VirtualMachineUpdateConf] configuration cannot be updated in state BOOT_FAILURE
```

**To Reproduce**

1. Have an error in a xml config that blocks boot
2. click update vm configuration to fix it
3. fix it in the raw data
4. click save
5. opennebula won't let you fix the error

**Expected behavior**

That OpenNebula doesn't explicitly block the very functionality that allows to get the system booting without redeploying a template.
(Wait, no actually the expected behaviour is that I can express any configuration that is valid. And any configuration that is not valid will be reported. That would even mean instantiating KVM's parser on save, or launching a confined VM with all but the disks. Automatically, to give good feedback to the user. Checking the libvirt dtd before that. I'm not trying to be annoying. I just want to create a picture in your mind what "Update configuration" usually entails. In our case, we have zero sanity checks but then jump through hoops removing clearing ERROR states, redeploying etc. while there's, in fact no reason at all to do that...)

**Details**

 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
Sunstone, Scheduler
 - Hypervisor: [e.g. KVM]
KVM and any other where a BOOT_FAILURE state can be reached (though to be fair, that is most common with KVM)
 - Version: [e.g. 5.4.12 or development]
5.x-with-the-nodeweaver-patch-collection

**Additional context**

UX nightmare. Especially since there's a dozen other little issues in parallel.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Yeah. Permanently hitting this. Usually fixed with the following magic mantra: 'Recover-Success + Undeploy-Hard' ...

**Comment by FlorianHeigl** [comment]
Better than my mantra where the disks stay in ERROR without ever having been touched ;-)

**Comment by cloudweavers** [comment]
Strongly support this. From a UX point of view, it is one of the things a user is expected to be able to do.
