### ISSUE TITLE
Wrong PCI to VM association removed when undeploying and terminating a VM with PCI pass-through

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3964]
**Description**
There are PCI ADDRESS and PREV_ADDRESS variables implemented to solve the VM migration case #3230. 
Unfortunately the patch solved this case but introduced a new one for Undeploy and Terminate

**To Reproduce**
* create a VM with VF NIC
* migrate/undeploy/whatever to  have PCI/ADDRESS and PCI/PREV_ADDRESS differ
* undeploy the VM 
* monitor HOST/ HOST_SHARE. _OpenNebula will update PCI/PREV_ADDRESS from the HOST_SHARE list instead of the actual PCI/ADDRESS_

**Expected behavior**
OpenNebula must clear the actual PCI/ADDRESS on Undeploy and Terminate

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [5.8.5]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @atodorov-storpool,

We've merged a fix into master branch which will be released with the next major release 5.12.

**Comment by atodorov-storpool** [comment]
Hello @christian7007 
I've found the relevant chunks the 5.10 code so I'll test a patch ASAP :)

THANKS!

**Comment by christian7007** [comment]
Nice! if you find something wrong please let me know.

**Comment by rsmontero** [comment]
Meantime, I'll close this, will reopen if needed.
