### ISSUE TITLE
Support for RDP links in Sunstone

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3969]
**Description**

Windows VMs can benefit from RDP connections

**Use case**

Better UX than VNC for end users

**Interface Changes**

Current VNC button can be subsumed into a "Console" button that is really a "fancy" dropdown for:

  - VNC
  - RDP

(soon more to follow)

**Additional Context**

All Sunstone needs to do is opening a rdp:// link, pointing to the right NIC (more on this below). It is up to the browser and end user to have a correct configuration so a RDP client is launched.

Selecting the right IP can follow the next procedure:

  * if only one NIC, pick that
  * more than one NIC:
     * check for NIC with RDP=yes. This setting should be available on VM Template creation time (checkbox in the VM Template Network section that will add RDP=yes to the NIC). If more than one, pick the first one
     * if no NIC with RDP=yes, pick first one

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
check -> https://github.com/citronneur/mstsc.js?files=1

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4170
• docs: OpenNebula/docs/pull/927

**Comment by kvaps** [comment]
It would be nice to implement SPICE as well https://github.com/OpenNebula/one/issues/1262
