### ISSUE TITLE
 VM Leases / Housekeeping

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3971]
**Description**

Simple housekeeping solution for instantiated OpenNebula VMs and Services based on a relative counter (f.e. 7 days), based on “SCHED_ACTION”, but with deeper integration in OpenNebula like an overview of all VM leases in Sunstone and the possibility to modify the leases with “one klick” - a nice to have will be an email alerting.

**Use case**

Admins that want VM to expire to avoid multiple idle instances

**Interface Changes**

* Add special sched action combo “Lease”: suspend + terminate in VM and VM Template creation/update
* Present clock icon on special leases, with a hoover with remaining time. Clock color change taking into account:
  * Black: within suspension lease
  * Blue:  1 day (configurable) to suspension
  * Yellow: within terminate lease
  * Red: 1 day (configurable) to termination

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:

- Docs: https://github.com/OpenNebula/docs/pull/1057
