### ISSUE TITLE
Warning with list of affected VM on VM Terminate

### ISSUE THREAD

**Issue by sergjack** [OpenNebula/one#3985]
**Description**
Sometimes it happens when vm that you not mean to delete stays marked with checkbox.
And you don't see it, because vm list scrolled down.
Then you select some vm's to delete on top of the list and push Terminate.
So you can loose vm that you don't meant to delete.

**Use case**
I twice occasionally deleted vms because they was checked with checkbox that I wasn't able to see.

**Interface Changes**
When you perform some destructable actions (Terminate, Terminate hard) show the actual list of affected VMs in the warning message.

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
to be considered as part of #5422

**Comment by nomis** [comment]
Having just accidentally terminated all the VMs (which is odd because I'm quite sure I terminated two VMs and then undeployed the others) I'd like to be able to disallow bulk termination.

**Comment by tinova** [comment]
to be considered in React Sunstone, won't be implemented in current Sunstone.
