### ISSUE TITLE
System snapshot size

### ISSUE THREAD

**Issue by AdriMenendezM** [OpenNebula/one#3986]
**Description**
Retrieve size info of a vCenter snapshot through ONE.

**Use case**
Snapshot management and control of datastores.

**Interface Changes**
Snapshot value on snapshots' view in Sunstone.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
closing as this is included implicitly in # 3769
