### ISSUE TITLE
option to add elements via onedb change-body

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#3999]
**Description**
Currently onedb change-body could update and delete an XML element but cannot add a new one.

**Use case**
When there is a change that needs to be propagated to the VM's configuration. For example to add FILTER_*_SPOFING to a NIC

**Interface Changes**
onedb change body to add an element instead of update when the element is not found in the XML

**Additional Context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

code: https://github.com/OpenNebula/one/pull/4036
docs: https://github.com/OpenNebula/docs/pull/865

**Comment by al3xhh** [comment]
Thank you so much for your contribution @atodorov-storpool !!

I have changed a bit the code and used the opportunity to lint the Ruby code.

**Comment by rsmontero** [comment]
Merged in master and one-5.10 branch for 5.10.2 release

**Comment by feldsam** [comment]
Hello @atodorov-storpool , @rsmontero , how can I add 'ID' to list of 'IMAGES' in datastore? I tried this:

`onedb change-body datastore --id 109 /DATASTORE/IMAGES/ID 451 --append --dry`, but it changes IDs of all other images:

```
<DATASTORE>
  ...
  <IMAGES>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID>451</ID>
    <ID><![CDATA[451]]></ID>
  </IMAGES>
  ...
</DATASTORE>
```

Thank you for help!

**Comment by atodorov-storpool** [comment]
Hi @feldsam, @rsmontero 

Hey @feldsam does https://github.com/OpenNebula/one/pull/6170 work for you?

I'd guess You'd also need to delete from there too? That case i a little bit tricky because a value and the delete action are exclusive. Probably a different action like 'delete-value' should be introduced in that case ;)

**Comment by feldsam** [comment]
Hi @atodorov-storpool, deleting works without problems with this xpath

`onedb change-body datastore --id 103 /DATASTORE/IMAGES/ID[.=451] --delete`
