### ISSUE TITLE
Create empty VM Templates in vCenter for marketplace apps

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#4001]
**Description**

Currently the VM Template associated to an image is not valid if the underlying hypervisor is vCenter, since a reference to an existing template is needed.

The qcow2 to vmdk conversion process should also create an empty template in vCenter, so the VM Template defined in the marketplace can be updated and the reference for the new empty template be added to it.

**Use case**

User tries to deploy a marketplace app onto vCenter. Needs to go over this awkward process:

  http://docs.opennebula.org/5.8/advanced_components/marketplace/migrate_images.html#qcow2-image-to-vmdk-datastore

**Interface Changes**

No changes

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
In order not to interfere with older versions, a VERSION should be added to hosts by the vCenter IM probe.

 - for old users, it'll ensure the template can't be planned for any vcenter 
 - for new users (which matches VERSION>5.10.0), it'll plan the template

**Comment by tinova** [comment]
A direct way of implementing this is through a default VM Template ID

**Comment by carloshm91** [comment]
[DOC]
* https://github.com/OpenNebula/docs/pull/1418

[TEST]
* https://github.com/OpenNebula/development/pull/1260

[ONE]
* https://github.com/OpenNebula/one-ee/pull/629
