### ISSUE TITLE
NSX-V network imported as Distributed Port Group

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4004]
**Description**
When you import a VM or a template having an nsx-v logical switch attached, the vnet imported has the attribute VCENTER_PORTGROUP_TYPE = "Distributed Port Group". And there is no NSX attributes.
This not happens if you import the network first.

**To Reproduce**
Import a VM or a template having an nsx logical switch attached

**Expected behavior**
The attribute VCENTER_PORTGROUP_TYPE should have value "NSX-V" if it is a nsx-v logical siwtch and "Opaque Network" if it's nsx-t logical switch
The imported vnet should have also NSX attributes

**Details**
 - Affected Component: [vCenter driver]
 - Hypervisor: [ESXi]
 - Version: [5.10]

**Additional context**
Workaround: Before importing a VM or a template with NSX networks, import the networks to get all the information first.

## Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mouyaq** [comment]
Also in other network types when import a vm having a non imported network, some network attributes as vswitch info is not retrieved.

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4828

[DOC]
* https://github.com/OpenNebula/docs/pull/1170
