### ISSUE TITLE
LXD marketplace: Broken export on 5.10.0 due to extra double quotes

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4005]
**Description**

With https://github.com/OpenNebula/one/issues/3957, the source/target paths for downloader are always quoted to prevent split. LXD marketplace monitoring adds own extra `"` quotting, e.g.:

```
# onemarketapp show 65 --xml | grep SOURCE
  <SOURCE><![CDATA["lxd://https://uk.images.linuxcontainers.org//images/ubuntu/xenial/amd64/default/./20191129_07:42/rootfs.tar.xz?size=1024&filesystem=ext4&format=raw"]]></SOURCE>
```

https://github.com/OpenNebula/one/blob/d00c57cea9be62f7d4b21f24ffe6d93e8e3b7e7f/src/market_mad/remotes/linuxcontainers/monitor#L194

This results in 2x quotted parameter:

```
/var/lib/one/remotes/datastore/fs/../downloader.sh '"lxd://https://uk.images.linuxcontainers.org//images/alpine/3.7/amd64/default/./20191128_13:00/rootfs.tar.xz?size=1024&filesystem=ext4&format=raw"' '/var/lib/one//datastores/1/38ad0b27b1effa99dbb9443a23aa47c5'
Cannot read from "lxd://https://uk.images.linuxcontainers.org//images/alpine/3.7/amd64/default/./20191128_13:00/rootfs.tar.xz?size=1024&filesystem=ext4&format=raw"
```

... which evaluates the path as local file (instead of triggering LXD downloader) and fails.

**Details**
 - Affected Component: Marketplace
 - Version: 5.10.0, master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
Hi, I can confirm this bug and cause. I reverted libfs.sh changes and it is working now.
