### ISSUE TITLE
Failed xml-rpc build on CentOS 7 exited with error "fg: no job control "

### ISSUE THREAD

**Issue by djdejawu** [OpenNebula/one#4010]
**Description**
Build from src xml-rpc failed

**To Reproduce**
rpmbuild -ba centos7.spec

**Solution**
yum install -y epel-rpm-macros
or
Add "BuildRequires: epel-rpm-macros" in centos7.spec

**Details**
- Opennebula 5.10 src rpm

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Thank you for the report.
Dependency was added by https://github.com/OpenNebula/packages/commit/57202293d693c3b0c8c135ec6ebd2e5938d503f4.
