### ISSUE TITLE
Gemfile.lock incorrect YAML keycodes

### ISSUE THREAD

**Issue by djdejawu** [OpenNebula/one#4011]
**Description**
Incorrect YAML markup

**To Reproduce**
Uses <tab> keycode in file, not <space> keycode.

**Details**
Opennebula 5.10

**Solution**
Change \t keycode to \" "keycode

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Can you be please more specific about the problem?
- I don't see any tabs in the Gemfile.lock
- Files are not supposed to be YAMLs, it's a Bundler (generated) format
