### ISSUE TITLE
SPICE web windows rendering problems

### ISSUE THREAD

**Issue by djdejawu** [OpenNebula/one#4012]
**Description**
After opening console all input will incorrect rendering.

**To Reproduce**
Create VM with input SPICE

**Expected behavior**
Screenshot [https://ibb.co/VWR0S2X](https://ibb.co/VWR0S2X)

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
solved in #3618
