### ISSUE TITLE
Inconsistent VM snapshot metadata xml after snapshot-delete (KVM)

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#4017]
**Description**
Deleting snapshot breaks snapshot metadata xml

**To Reproduce**
* deploy qcow2 VM
* create VM snapshots snap-1, snap-2,
* delete snap-1
* power-off, resume
* snap-2 is missing in libvirt and can't be reverted, because the metadata.xml contains
`<parent><name>snap-1</name></parent>`

** Also check if suspend + resume redefine the snapshots **

**Expected behavior**
* snapshot is present in libvirt
* snapshot could be reverted
* possible fix: when deleting snapshot, recreate all snap metadata

**Details**
 - Affected Component: kvm vmm driver
 - Version:  5.8.5+ 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by fgadot** [comment]
I have about 15 VM where I do the same thing..
Create snapshot 0 with name DEFAULT
modify the VM
Create new snapshot 1 with name DEFAULT
Delete snapshot 0
snapshot 1 cannot be restored

**Comment by xorel** [comment]
**1. Issue**
**Can not revert to VM snapshot after a prior snapshot was deleted**

After the following scenario
* create VM snapshot 1, create VM snapshot 2
* delete VM snapshot 1
* stop VM
* start VM

Now, user can no longer revert to VM snapshot 2 due to inconsistency in snapshot metadata xml, which still contains a link to parent snapshot 1.

*Workaround*
After you delete the snapshot, fix the remaining snapshots metadata xml manually, for each one run following command on the hypervisor (DOMAIN and SNAP-NAME are in libvirt notation, VM_ID is OpenNebula VM number)
```
virsh -c qemu:///system snapshot-dumpxml  [DOMAIN] [SNAP-NAME] > /var/lib/one/datastore/[SYSTEM_DS_ID]/[VM_ID]/[SNAP_NAME].xml
```

**2. Issue**
**Can not revert to VM snapshots after suspend+resume**

After the following scenario
* create VM snapshot 1
* suspend VM
* resume VM

Now there is no snapshot visible for the libvirt for the VM due to missing snapshot redefine in VM resume action.

*Workaround*
Poweroff + poweron the VM.

**Comment by fgadot** [comment]
Jan,

Just a quick question, do you know if VoIP thought a PC using OpenVPN and setup as a gateway works by default?
Or Is there any trick for this?

Thank you.
