### ISSUE TITLE
The new NoVNC server doesn't show status

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4020]
**Description**
As NoVNC server was updated in the last release, there is no status in the console view (see attached images for more information)

**To Reproduce**
Click on VNC button in Sunstone.

**Expected behavior**
It should show the current VM status.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10 and master.

**Additional context**
![one-5 10-vnc-02](https://user-images.githubusercontent.com/33811723/70150607-90ee2900-16aa-11ea-8051-3389c3e32eaf.png)
![one-5 10-vnc-03](https://user-images.githubusercontent.com/33811723/70150612-9186bf80-16aa-11ea-8f65-16de71dbe6d1.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4151
• docs: OpenNebula/docs/pull/921
