### ISSUE TITLE
[GOCA] enable VM pool filtering

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/one#4021]
First, all opinions on how good/bad are there proposals are welcome :)

There is XML-RPC methods on VM pools allowing to filter using a key, value pair, but it's not 
possible to use it from Goca for now.

Current prototype of VM pool info method:  
```func (vc *VMsController) Info(args ...int) (*vm.Pool, error)```

The type for all parameters (variable number) is `int`.  
To filter using a tag, we need to add a last parameter of type string: "KEY=VALUE".  
As is, it's not possible to pass the last parameter as a string.

**Proposal 1**

To avoid breaking changes:  
```func (vc *VMsController) Info(args ...interface{}) (*vm.Pool, error)```

But using an `interface` remove compile time checks on types, if the user give a parameter with the wrong type, it will be detected at runtime (we'll need of type assertions inside the method).

I'm not happy with this solution, but this is the only one that would allow existing code to build.

**Proposal 2**

With breaking changes:  
```func (vc *VMsController) Info(who, start, end, state int, pair ...string) (*vm.Pool, error)```  

I would prefer to remove variable parameters as much as possible (for ALL pool methods):  
Methods are confuse to use without looking at documentation, or Goca code.
Here, there is still variable parameter stuff, but only for one optional value (Before, integer parameters were set to -1 by default inside Goca, so they were optional from Goca point of view, but mandatory for XML-RPC methods).

This break because it forces the user to pass almost all parameters (but developer could pass defaults values: -1).

This change would apply to: document, image, marketplace, marketplaceapp, securitygroup, template, virtualnetwork, virtualrouter, vm, vmgroup, vntemplate.  
Other entities does not take any parameters at all in their pool info methods.

**Proposal 3**

With breaking changes:  
It's the solution 2, with additional structs and helpers:  
```func (vc *VMsController) Info(v IDView, state int, pair ...string) (*VMPool, error)```

And related code:  
```
type IDView struct {
	Who int
	StartID int
        EndID int
}
```
EDIT: 
Or we could even introduce a filter struct to wrap all parameters:
```
type Filter struct {
	Who   int
	Start int
	End   int
}

type VMFilter struct {
	Filter

	State int
	Pair  string
}
```

Then:
```func (vc *VMsController) Info(filter *VMFilter) (*VMPool, error)```

**Comment by treywelsh** [comment]
A later improvement that could follow this change could be to extend pool filtering for user convenience:

Still about pool instances filtering, we could even add some more methods for the developer to avoid him to make a loop (when filtering has to be done on client side):

The API could be, for instance:  
For VMs:
```
func (vc *VMsController) ByName(name string, v View) (int, error)
func (vc *VMsController) ByState(state image.State, v View) ([]int, error)
func (vc *VMsController) ByPair(pair string, v View) ([]int, error)
```

For Images:
```
func (ic *ImagesController) ByName(name string, v View) (int, error)
func (ic *ImagesController) ByType(type image.Type, v View) ([]int, error)
func (ic *ImagesController) ByPair(p TemplatePair, v View) ([]int, error)
```

**Comment by christian7007** [comment]
Hello @treywelsh,

In order to add the 3rd proposal and avoid breaking changes you can add a new `info_filter` method or something like this for using the KeyValue filtering:

```
func (vc *VMsController) InfoFilter(v IDView, state int, pair ...string) (*VMPool, error)
```

This way we introduce the search filter without breaking other applications which do not use this feature.

**Comment by treywelsh** [comment]
Thank your for your comment :)

Yes it's a way to avoid breaking the API.

I forgot to mention, there is also this pool method concerned for VM pools:
`func (vc *VMsController) InfoExtended(filterFlag, startID, endID, state int) (*vm.Pool, error)`
But as you can see, the prototype is not the same than pool `Info` method.

It wouldn't break to enable filtering on pair with an optional parameter:
`func (vc *VMsController) InfoExtended(filterFlag, start, end, state int, pair ...string) (*vm.Pool, error)`

But it could be interesting to make a small breaking change to make their prototypes the same (only the level of information returned by the method differ, but they work the same way).
Moreover, it would be strange to add a `InfoFilter` method but not an `InfoExtendedFilter` method.

**More details on the initial idea**

I proposed to introduce an `IDView` struct, as I considered first three parameters of pool methods (resource belonging: group/user ..., start ID, end ID) as a window giving a view on various ranges of IDs.
These three parameters are shared by a set of pool methods (image, document ... ).
Only the VM method is an exception with these additional parameters: state and pair

To be consistent I wanted to apply these changes to other relevant pool methods, and allow the user to avoid using variable parameters.

For instance, on image pools:
`func (ic *ImagesController) Info(args ...int) (*image.Pool, error) {`

The method would become:
`func (ic *ImagesController) Info(v IDView) (*image.Pool, error) {`

We could name this method `InfoFilter`, but it could be a bit confusing ?
Here, it only change the way to pass the parameters to the method but does not add any filtering feature.
Without break something, I don't find this really satisfying.

**Proposal 4**

Working on it, I found an other way to do:

All proposals above will suffer if API evolve later on pool methods, it's already what's happening here.

To better illustrate [here is a branch I pushed to show how we could do this (only on VM)](https://github.com/iguanesolutions/one/commit/d51dac98a82a581b56810d6e688dc170407a8db5)

This adds a bit more of internal stuffs, but it's hidden from the user, and we have a more flexible way to handle the parameters.

A code sample that use the PR: 
```
	vms, err := controller.VMs().InfoFilter(goca.Who(goca.PoolAll), goca.Pair("ID", 3110))
	if err != nil {
		log.Fatal(err)
	}
```
There is some small helper functions that allow you to configure: `Who`, `Range`, `State`, `Pair`
I can understand that it could seems a bit more heavy.

But personally, I think that some last breaking changes would be interesting on this part.

**Comment by treywelsh** [comment]
Thank your for your comment :)

Yes, we could add a new method to avoid breaking the API if it's just to enable filtering on VM pool.
I proposed bigger changes because I wanted to avoid "variadic" parameters (it adds limitation on type, and isn't self explanatory), and I didn't want to introduce new exceptions in the API (i.e. I wanted to be consistent across the most of info pools methods).
But without some breaking changes I don't find any of my proposals interesting.

By the way, I forgot to mention, there is also this pool method concerned by VM pools filtering with a pair:
`func (vc *VMsController) InfoExtended(filterFlag, startID, endID, state int) (*vm.Pool, error)`
But as you can see, the prototype is not the same than pool `Info` method.

We could even enable filtering on pair with an optional parameter, without breaking changes:
`func (vc *VMsController) InfoExtended(filterFlag, start, end, state int, pair ...string) (*vm.Pool, error)`

But it could be interesting to make a small breaking change to make their prototypes the same (only the level of information returned by the method differ, but they work the same way, it's confusing).
Moreover, it would be confusing to add a `InfoFilter` method but not an `InfoExtendedFilter` method.

So if we add only two methods to vm.go, their prototype could be:
`func (vc *VMsController) InfoFilter(f *VMFilter) (*VMPool, error)`
`func (vc *VMsController) InfoExtendedFilter(f *VMFilter) (*VMPool, error)`

With:
```
type VMFilter struct {
	Who   int
	Start int
	End   int

	State int
	Pair  string
}
```

And, maybe, we could change :
`func (vc *VMsController) InfoExtended(filterFlag, startID, endID, state int) (*VMPool, error)`
to:
`func (vc *VMsController) InfoExtended(args ...int) (*VMPool, error)`
for consistency.

I should make a small PR to better illustrate this with some more additional helper to guide the user.

**Comment by treywelsh** [comment]
If someone is interested to give his point of view on the changes I propose:  https://github.com/OpenNebula/one/compare/master...iguanesolutions:F-4021

I didn't submitted this as a PR, comments are welcome.

Finally:
*  I tried to avoid breaking changes in adding `InfoFilter` et `InfoExtendedFilter` methods
*  I changed:  
   `func (vc *VMsController) InfoExtended(filterFlag, startID, endID, state int) (*vm.Pool, error)`  
   to:  
   `func (vc *VMsController) InfoExtended(args ...int) (*vm.Pool, error)`  
   in order to have all pool methods consistent.
*  I tried to reuse/mutualize some code parts around

**Comment by christian7007** [comment]
Hello @treywelsh,

I'll take a look at it as soon as I can but the idea looks good.
