### ISSUE TITLE
Put NSX info into NSX tab

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4022]
**Description**
Sunstone should show NSX info into NSX tab

**Use case**
To view more easily that information

**Interface Changes**
Sunstone 

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
duplicated by #4081
