### ISSUE TITLE
SD_DISK_BUS setting gets removed straight away

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4025]
**Description**
Upgraded from 5.8 to 5.10. Trying to set SD_DISK_BUS setting under OS for a given VM. But whether through sunstone or `onevm updateconf` the setting is removed straight away.

**To Reproduce**
- run `onevm updateconf`
- under OS add SD_DISK_BUS="sata", or scsi
- Save (says success)
- run `onevm updateconf` again and the setting has disappeared.

**Expected behavior**
setting should be retained

**Details**
 - scheduler
 - 5.10.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Fix, merged and ready for 5.10.1 Thanks!
