### ISSUE TITLE
Fetch disk capacity from server as well

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4029]
**Description**
When replacing a vm image manually on a server the used size updates in opennebula but the allocated size does not.

**To Reproduce**
- Create a small blank disk say 2mb and deploy it. Power down the vm
- On the server manually replace that with another disk image eg a qcow2 image using 1gb but with 100gb allocated to the file
- Sunstone shows the increased allocation as 1Gb/2Mb - it's updated the used but not the max size

**Expected behavior**
Max size should update as well.

**Details**
 - Hypervisor: libvirt, using ssh transport and local fs for storage
 - Version: 5.10

**Additional context**
 Both of these details can easily be got from `qemu-img info -U` or `virsh domstats` block.x.allocation / capacity bits.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
The supported way of performing this operation is through "onevm disk-resize". Closing until further details are provided.
