### ISSUE TITLE
Used CPU / Used Memory not sortable in sunstone

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4031]
**Description**
Used CPU and Used Memory columns are not sortable for some reason in sunstone?

Guessing this is tabs/vms-tab/datatable.js:66

```
          {"bSortable": false, "aTargets": ["check", 6, 7, 11]},
```

where 6 & 7 are these columns. But I have no idea why this would be the case? They should just be integer sorted like id column.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/37
