### ISSUE TITLE
NUMA aware placement for vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4039]
**Description**

This issue is to implement placement constraints on NUMA nodes. A VM can be pinned on a node based on:

- PCI affinity
- Memory affinity
- Manual node assigment

**Use case**
Improve performance of VM by making memory and/or I/O access to the same NUMA node.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
ESX takes care of the NUMA placement. We will only allow the definition of the virtual topology. Sunstone needs to deprecate the core per sockets dialog in favor of the NUMA one, with the following characteristics for vCenter:

 - Fix pin policy to 1
 - Calculate automatically the number of sockets, similar as what we do now in the General tab
  - Remove huge pages and memory access
  - Fix threads to 1

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [code](https://github.com/OpenNebula/one-ee/pull/750)
- [docs](https://github.com/OpenNebula/docs/pull/1441)
- Test: Pending
