### ISSUE TITLE
NIC Hotplugging fails on q35 machines

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4045]
**Description**

Create q35 machine on kvm. Try to hotplug a NIC and it returns `internal error: No more available PCI slots` error

**Expected behavior**
Should hotplug the nic

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 5.10.0

**Additional context**
This is because by default hotplugging is not supported in libvirt q35 per details at https://libvirt.org/pci-hotplug.html . Adding the following libvirt config solves this issue:

```
<devices>
<controller type='pci' model='pcie-root'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-root-port'/>
<controller type='pci' model='pcie-to-pci-bridge'/>
</devices>
```

The final bridge line is required to support `virtio` type hotplugging. Note that the many pcie-root-ports are required as all the other devices take up a port by default.

Is there a way to automate this in the ONE libvirt deployment? I believe openstack has a parameter along the lines of 'how many root ports do you want'.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
I hit this issue today.

Thanks for this issue, I changed the machine type and I can hotplug nics :+1:
