### ISSUE TITLE
systemctl restart opennebula doesnt restart onehem

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4046]
**Description**
`systemctl restart opennebula` doesnt restart onehem service. That needs restarting with `systemctl restart opennebula-hem`.

**Expected behavior**
As with the other opennebula services I would have expected this to restart as well eg after an upgrade

**Details**
 - Affected Component: hem
 - Version: 5.10.0 & .1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
It works the same way scheduler works:

https://github.com/OpenNebula/one/blob/99fd76c1567e82ef3df3b3e07ae0b36a1167690c/share/pkgs/services/systemd/opennebula.service#L5

They both are required for OpenNebula to start but they are different services, you may want to restart OpenNebula without restarting them.

**Comment by Leo-need** [comment]
Hi guys!

I didn't find any mention in docs, that I need to start and enable opennebula-hem.service

**Comment by christian7007** [comment]
Hello @Leo-need, there is no need to enable `opennebula-hem.service` it should be automatically started as `opennebula.service` dependency. Did you reload the service configuration file (http://docs.opennebula.org/5.10/intro_release_notes/upgrades/upgrade_58.html#step-8-start-opennebula)?

**Comment by rsmontero** [comment]
Closing as works for me. Reopen if needed...
