### ISSUE TITLE
docker-machine-driver-opennebula does not properly work with Rancher

### ISSUE THREAD

**Issue by meier-rene** [OpenNebula/one#4052]
**Description**
I'm using opennebula and the docker-machine-driver-opennebula to provision hosts for kubernetes/Rancher. I already reported this issue in https://github.com/OpenNebula/docker-machine-opennebula/issues/15 but recently figured out, that the docker-machine-driver-opennebula is maintained here.
If you delete a host in rancher, it deletes the host through opennebula and creates a new one. Unfortunately the new host is already created before the old one is finally removed. That's why rancher is failing with "Error creating machine: Error in driver during machine creation: Multiple resources with that name." 

**To Reproduce**
Provision a kubernetes cluster with Rancher with the help of opennebula. Delete one of the hosts and get the error: **"Error creating machine: Error in driver during machine creation: Multiple resources with that name."** during the provision of the new rancher node. Pls also check the issue in https://github.com/OpenNebula/docker-machine-opennebula/issues/15.

**Expected behavior**
The driver should make sure that no name clashes happen.

**Details**
 - Affected Component: docker-machine-driver-opennebula
 - Hypervisor: KVM
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
I can confirm that I having the same problem.
It is working fine for newly created clusters but throws the same error when you recreate the nodes.

**Comment by carloshm91** [comment]
@meier-rene , can you tell us the step by step to reproduce it? We try to recreate this `If you delete a host in rancher, delete it via opennebula and create a new one` and the host is deleted in rancher and opennebula without any error.
Tell us please the exact steps to recreate this `provision of a cluster of kubernetes with rancher`. Maybe we are doing other way.

@kvaps, can you provide the exact steps to `recreate the nodes` and reproduce the problem?

**Comment by meier-rene** [comment]
We working with rancher 2.3.5 and docker-machine-opennebula-5.10.1-1 on ubuntu 18.04. We use a template based on ubuntu-18.04 from the appstore. I can provision a new cluster like this:
![rancherui1](https://user-images.githubusercontent.com/25176376/76729639-e92cd080-6759-11ea-835d-9f3fdfb924d8.png)
and in sunstone it looks like this:
![openneb1](https://user-images.githubusercontent.com/25176376/76729681-02ce1800-675a-11ea-9e3b-5d0b1b4882c5.png)

Its working as expected. 

If I delete one of the worker with `Delete` from the menu like this:
![rancherui2](https://user-images.githubusercontent.com/25176376/76729812-458ff000-675a-11ea-91bf-58504bd01041.png)
In sunstone I can see the currently running testworker2 enters `EPILOG`and the new 
testworker2 is allready there `PENDING`
![openneb2](https://user-images.githubusercontent.com/25176376/76729997-9d2e5b80-675a-11ea-94d4-089310d8ceef.png)
In this Moment I get an error in Rancher:
![rancherui3](https://user-images.githubusercontent.com/25176376/76730052-bb945700-675a-11ea-8380-5ed9804ee715.png)

I can recover from this error by deleting all VMs named testworker2 in opennebula, wait until they are finally gone and then delete testworker2 again in rancher. Now everything works fine.

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4385

[DOC]
* https://github.com/OpenNebula/docs/pull/1060
