### ISSUE TITLE
Define group admins depending on LDAP group belonging

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4056]
**Description**
Make users, who belong to specific LDAP group, group admin of the OpenNebula groups they belongs to.

**Use case**
Being able to define the OpenNebula group admins just by including a user into specific LDAP group.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
PRs (to master)
 * one: https://github.com/OpenNebula/one/pull/4097
 * tests: https://github.com/OpenNebula/development/pull/824
 * docs: https://github.com/OpenNebula/docs/pull/911
