### ISSUE TITLE
Sunstone: Embed fonts local (not from Google Fonts)

### ISSUE THREAD

**Issue by vidister** [OpenNebula/one#4061]
**Description**
At the moment the Font "Lato" is fetched from Google Fonts. This makes things slower and collides with sane Content Security Policies.
Please evaluate if bundling the font with the software (as it's already happening with OpenSans at the moment) is an option.

I volunteer for a Pull Request.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@vidister  We would be very grateful for your contribution if you do the PR

**Comment by tinova** [comment]
thanks a lot for the contribution and apologies for the huge delay in addressing this. we will make sure this is the default in the new sunstone iteration #5422
