### ISSUE TITLE
premigrate/postmigrate script do not get BASE64 XML template anymore

### ISSUE THREAD

**Issue by rp-** [OpenNebula/one#4062]
**Description**
premigrate/postmigrate script don't get the VM template XML anymore, instead all I get is the string `ssh`.
I suspect this related to issue #3373.

**To Reproduce**
Try to live migrate a VM and check the premigrate parameters

**Expected behavior**
I would expect a better upgrade path or at least some mention in the documentation. The storage driver documentation still specifies the BASE64 string and no mention that now the XML template should be provided by STDIN.

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Yes, a note on the compatibility guide is missing and documentation was not updated. You can get the Template in base 64 just by reading STDIN.

Thanks for the head-ups and really sorry for the inconvenience.

**Comment by rsmontero** [comment]
documentation and compatibility updated in all relevant brances.
