### ISSUE TITLE
Cannot request both IP and MAC address when creating a VM

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4063]
**Description**
When creating a VM I canot specify both `<IP>` and `<MAC>` fields in the description even if a given IP/MAC pair exists in the address range table. Instead it returns an error "[one.vm.allocate] Cannot get IP/MAC lease from virtual network X"

**Expected behavior**
It would be nice to not have MAC enforcement in this case so I can specify custom macs, but at the very least if a IP/MAC pair does exist it should allow you to lease it.

https://github.com/OpenNebula/one/blob/e92c43d5012cbd0f7df0c14a4abdea8d734365cc/src/vnm/VirtualNetwork.cc#L872 seems to be the root cause as it checks if only 1 of ip/ip6/mac is specifically requested. I guess at minimum it should do a request based on 1 of those (probably mac -> ip6 -> ip4) and then check if the returned lease matches any of the other requirements.

**Details**
 - Affected Component: RPC
 - Hypervisor: KVM
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Once the AR is defined you cannot specify custom addresses. You can specify a range so ONE will automatically generate the addresses or specify a pair IP/MAC for the entire AR.

Regarding to existing IP/MAC, if you select the IP the MAC linked to that IP address will be automatically set for the VM so it would be redundant to allow you to specify a MAC address for specific IP when the only valid case is the one automatically generated by ONE.

So, to define custom IP/MAC pairs you have to define it in a single lease AR's. We do not plan to include in the roadmap a dynamic assigment for now.  As mentioned above, we think it is less confusing for the user not to add an option for specifying a MAC address when the only valid case is the one automatically generated.
