### ISSUE TITLE
Custom variables of type password are displayed in clear text

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4064]
**Description**
When adding the custom variable **PASSWORD** to set the root password for the VM, that password is showed in clear text in the **CONTEXT** section.

**To Reproduce**
Add the custom variable to the template and the instantiate the template.

**Expected behavior**
There should be a method to encrypt that information and decrypt it in the contextualization scripts.

**Details**
 - Affected Component: core and context scripts
 - Version: 5.8 5.10 and master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4528
- docs: https://github.com/OpenNebula/docs/pull/1052
