### ISSUE TITLE
Context disk contents is not updated on nic detach

### ISSUE THREAD

**Issue by alloran** [OpenNebula/one#4067]
**Description**
Context disk contents is not updated on nic detach

**To Reproduce**
1. Attach nic to vm
2. Detach it. 
Context cdrom update is triggered, but context.sh is the same, containing deleted nic context data.
So contextualization scripts is not triggered

**Expected behavior**

context.sh should be updated

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 5.10.1

**Additional context**
Guest one-contexd logs:
`Dec 25 16:16:35 76 one-contextd[9308]: Started for type all to reconfigure
Dec 25 16:16:35 76 one-contextd[9309]: Acquiring lock /var/run/one-context/one-context.lock
Dec 25 16:16:35 76 one-contextd[9311]: Acquired lock /var/run/one-context/one-context.lock
Dec 25 16:16:35 76 one-contextd[9320]: Mounting CD-ROM /dev/sr0 on /var/run/one-context/mount.LotA3d
Dec 25 16:16:35 76 one-contextd[9322]: Found context /var/run/one-context/mount.LotA3d/context.sh
Dec 25 16:16:35 76 one-contextd[9325]: Comparing /var/run/one-context/context.sh.zzjKId and /var/run/one-context/context.sh.local for changes
Dec 25 16:16:35 76 one-contextd[9327]: No changes in context, skipping
Dec 25 16:16:35 76 one-contextd[9328]: Comparing /var/run/one-context/context.sh.zzjKId and /var/run/one-context/context.sh.network for changes
Dec 25 16:16:35 76 one-contextd[9330]: No changes in context, skipping
Dec 25 16:16:35 76 one-contextd[9331]: Done
Dec 25 16:16:35 76 one-contextd[9332]: Unmounting /var/run/one-context/mount.LotA3d
Dec 25 16:16:35 76 one-contextd[9336]: Releasing lock /var/run/one-context/one-context.lock
`

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Already fixed in https://github.com/OpenNebula/one/issues/4130
