### ISSUE TITLE
Make Sunstone colors thresholds configurable

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4068]
**Description**
Currently the thresholds for colours in Sunstone are hard coded:

- green 0 - 33%
- Orange 33% - 66 %
- red 66% - 100%

It would be great if these values can be configurable via `sunstone-server.conf`.

**Use case**
These values might not be correct in some clouds deployment, sometimes the warning colour at 33% may confuse cloud administrator.

**Interface Changes**
Only Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:

- One: https://github.com/OpenNebula/one/pull/4612
- Docs: https://github.com/OpenNebula/docs/pull/1086

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Dev: https://github.com/OpenNebula/development/pull/951
