### ISSUE TITLE
PyONE vmpool.info missing vars in USER_TEMPLATE

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#4070]
**Description**
Hello, I rewriting some old code from NodeJS to Python. I use `pyone` lib installed by `pip install` on my Mac. I hit the problem with `vm.USER_TEMPLATE` dict returned when `vmpool.info()` function is called. There are only `LABELS` and `SCHED_REQUIREMENTS` keys. When I call `vm.info()` for each VM I get full `vm.USER_TEMPLATE`, but it is inefficient and slow.

**To Reproduce**
Install `pyone` using pip and write simple function to get all VMs. Check the content of `vm.USER_TEMPLATE`

**Expected behavior**
All vars in  `vm.USER_TEMPLATE` when called `vm.pool.info()`

**Details**
 - Affected Component: OCA Python
 - Hypervisor: All
 - Version: Current PIP version

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
The information returned by `one.vmpool.info` call was reduced in OpenNebula 5.8 in order to increase the scalability for large deployments.You can find more info here: http://docs.opennebula.org/5.8/intro_release_notes/release_notes/compatibility.html#xmlrpc-api-changes

You can use `one.vmpool.infoextended` to achieve the old behavior of `one.vmpool.info`.

**Comment by feldsam** [comment]
Hello, thank you!

This should be also better documented in xml-rpc api docs, https://docs.opennebula.org/5.10/integration/system_interfaces/api.html#one-vmpool-info here should be info about limited user template vars returned with suggestion to use `one.vmpool.infoextended ` method

**Comment by christian7007** [comment]
This was added in: https://github.com/OpenNebula/docs/commit/5f991554a3b846036f64f57b9cab529cfe89dbf5.

Thanks for the feedback!
