### ISSUE TITLE
The monitoring process might retrieve a bad number of processors.

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4072]
**Description**
Due to `nproc` does only return the `number of processing units available to the current process` if some kind of restriction is applied for the monitoring process it will not see the total number of processors which can lead to a miscalculation of the CPU usage.

**To Reproduce**
Limit the number of processors available for the monitoring process (e.g. by using cgroups) and check cpu monitoring info for VMs.

**Expected behavior**
The CPU monitoring info returned by the monitoring process shouldn't be affected by cpu access limitations.

**Details**
 - Affected Component: Monitroing
 - Hypervisor: KVM and LXD
 - Version: 5.10

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Hello and Happy New Year!

IMO Avoiding the cgroups is not the solution for this issue (also see #1353)! The monitoring probe should return the number of processors allocated for VMs. When cgroups are used then the value set in _machine.slice/cpuset.cpus_ should be accounted. Also, _machine.slice/cpuset.mems_ should be accounted for the memory too.
As discussed on OpenNebula Conf, the NUMA should be cgroup aware too...

I've just uploaded the monitoring "implant" that is gaming the OpenNebula monitoring system to count only the processors allocated for VMs in the cgroups. 
https://github.com/OpenNebula/addon-storpool/blob/master/misc/0reserved_resources.sh

Unfortunately it is not covering the NUMA that was introduced in OpenNebula 5.10+, though.

**Comment by rsmontero** [comment]
Happy new year!!

The problem in this case is how the CPU usage is computed. nprocs in fact returns the cgroups CPUs. Process cpu usage is computed as the ratio of jiffies used (during 1 sec) by the process in relation to that of the system. The jiffies used as base clock metric needs to consider the whole number of processors to render the right figure. 

With the proposed patch the CPU usage per KVM process is reported correctly in cgroups constrained sessiones.

Cheers.
