### ISSUE TITLE
move nsx attributes to its tab

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4081]
**Description**
Move nsx attributes represented as NSX_ from host info tab to nsx tab

**Use case**

**Interface Changes**

**Additional Context**

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- One: https://github.com/OpenNebula/one/pull/4816
- Docs: https://github.com/OpenNebula/docs/pull/1149
