### ISSUE TITLE
Sunstone VNC window doesn't cover whole page

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4083]
**Description**

Sunstone VNC window opened from the VM list doesn't always cover original page underneath:

![image](https://user-images.githubusercontent.com/414850/71903003-71dc2e80-3163-11ea-92fb-30d66e0b9b00.png)

**To Reproduce**
Open VNC console directly from VM list, try various browser window sizes.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10.1

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4201
• docs: OpenNebula/docs/pull/946
