### ISSUE TITLE
Add option to disable service button actions

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4088]
**Description**
Add option to disable delete/terminate actions in service tab.

**Use case**
Don't give users the ability to delete an existing service.

**Interface Changes**
Sunstone and its configuration files.

**Additional Context**
![Untitled](https://user-images.githubusercontent.com/33811723/72053208-d9f75580-32c6-11ea-9d1e-1d8a6a80535f.png)

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
Updating user view and restarting sunstone works.
Closing until more feedback is provided.
