### ISSUE TITLE
Add microVM support via Firecracker

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#4089]
**Description**
Create new Firecracker driver for supporting microVMs.

**Use case**
Allow microVMs deployment as an alternative for VMs and Containers.

**Interface Changes**
This new "hypervisor" should be added to Sunstone interface.

**Additional Context**
Firecracker repo: https://github.com/firecracker-microvm/firecracker
Firecracker docs: https://github.com/firecracker-microvm/firecracker/tree/master/docs

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
reopening for Sunstone interface changes
