### ISSUE TITLE
INHERIT_VNET_ATTR of complex type

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4090]
**Description**
It would be useful to being able to inherit custom attributes of complex type (i.e map).

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Doing the same also for INHERIT_DATASTORE_ATTR and INHERIT_IMAGE_ATTR.
It's not possible to create nested attributes, so the complex attribute is merged:
```
VNET attribute
TO_BE_MERGED=[A="a", B="b"]

VM template
NIC = [ NETWOTK = "THE_VNET" ]

Resulting VM NIC
NIC = [ NETWORK = "THE_VNET", IP = "10..., A="a", B="b" ]
```
PRs for merge to master:
* src https://github.com/OpenNebula/one-ee/pull/560
* doc https://github.com/OpenNebula/one-ee/pull/560
