### ISSUE TITLE
Add custom network context variables

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4091]
**Description**
It would be useful to be able to add new network context variable dynamically.

**Use case**
Customize context network scripts.

**Additional Context**
An approach could be to read the attributes hash from oned.conf.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Currently, NIC attach operations trigger a regeneration of context variables and processing of the guest. This combined with the ability to add into context any vairable from a NIC or NETWORK enables the use of dynamic network reconfiguration.

For example. A network may have a ROUTES attribute encoding the default gw and direct routes to networks. This can be added to the context when a NIC in that network is attached or triggering and updateconf operation. For example

ROUTES = "$NETWORK[ROUTES, NETWORK_ID=3]"

Note that this to be managed by the context scripts or custom start_script
