### ISSUE TITLE
install_gems for 5.10.1 does not include all required gems

### ISSUE THREAD

**Issue by sulaweyo** [OpenNebula/one#4092]
**Description**
I'm building OpenNebula from source for Arch and so far used the install_gems script to install the gems required to run OpenNebula. With the upgrade to 5.10 there are a bunch of dependencies missing now. I can add them to the install script in the PKGBUILD but imho the script should deliver the full dependency set.

I had to add the following gems manually:
- ffi-rzmq
- rqrcode
- rotp
- ipaddress

**To Reproduce**
Just run `/usr/share/one/install_gems --showallgems`
The ones listed above are missing from the list

**Expected behavior**
`/usr/share/one/install_gems --showallgems` gives a list of all required gems and not just some.

**Details**
 - Affected Component: dependency gems (/usr/share/one/install_gems)
 - Version: 5.10.1

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sulaweyo** [comment]
I'll just switch to use bundler to install the dependencies as the GEmfile contains everything. I still think that the script should return the full list though

**Comment by vholer** [comment]
PRs to merge:
- one - PR https://github.com/OpenNebula/one/pull/4230 into
    - **one-5.10**
    - cherry-pick into **master**
- docs - PR https://github.com/OpenNebula/docs/pull/953
