### ISSUE TITLE
5.10.1 sunstone remote login UI button size and alignment is off

### ISSUE THREAD

**Issue by josephmilla** [OpenNebula/one#4096]
**Description**
In OpenNebula 5.10.1, the sunstone remote login UI button is larger than 5.8.x and the alignment is also off by a wide margin

**To Reproduce**
Switch to remote auth, in `/etc/one/sunstone-server.conf` change the auth line to remote
```
# :auth: opennebula
:auth: remote
```
Restart `opennebula-sunstone` after doing so:
```
sudo service opennebula-sunstone restart
```

![5.10.x](https://i.imgur.com/KGYblad.png)

**Expected behavior**

Here's a photo of the login page in 5.8.x

![5.8.x](https://i.imgur.com/I7aiqMI.png)

**Details**
 - Affected Component: Sunstone
 - Hypervisor: N/A
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
-ONE: https://github.com/OpenNebula/one/pull/4102
-Docs: https://github.com/OpenNebula/docs/pull/899
