### ISSUE TITLE
Tabs can't be disable in Network tab

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4098]
**Description**
In create VNET dialog, the different tabs (like security) can't be disabled.

**To Reproduce**
Try to disable it via yaml.

**Expected behavior**
It should be disabled if the value in yaml is false.

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This issue cannot be replicated, if you want to configure the views:
1- Go to path and edit the view: ` /etc/one/sunstone-views/<mode>/<view>`
2- Restart sunstone on terminal: ` sunstone-server restart`

**Comment by tinova** [comment]
will reopen if additional feedback is given
