### ISSUE TITLE
SPICE PASSWD is too long

### ISSUE THREAD

**Issue by lvfaguo** [OpenNebula/one#4103]
**Description**
Instantiate VM Template Failed. Because of the SPICE PASSWD is too long.

VM Template:
```
...
GRAPHICS = [
  LISTEN = "0.0.0.0",
  RANDOM_PASSWD = "YES",
  TYPE = "SPICE" ]
...
```

VM Log:
```
Thu Jan 16 17:57:36 2020 [Z0][VM][I]: New state is ACTIVE
Thu Jan 16 17:57:36 2020 [Z0][VM][I]: New LCM state is PROLOG
Thu Jan 16 17:59:32 2020 [Z0][VM][I]: New LCM state is BOOT
Thu Jan 16 17:59:32 2020 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/236/deployment.0
Thu Jan 16 17:59:33 2020 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Thu Jan 16 17:59:34 2020 [Z0][VMM][I]: ExitCode: 0
Thu Jan 16 17:59:34 2020 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Thu Jan 16 17:59:36 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/101/236/deployment.0' 'node' 236 node
Thu Jan 16 17:59:36 2020 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/101/236/deployment.0
Thu Jan 16 17:59:36 2020 [Z0][VMM][I]: error: internal error: unable to execute QEMU command 'set_password': Could not set password
Thu Jan 16 17:59:36 2020 [Z0][VMM][E]: Could not create domain from /var/lib/one//datastores/101/236/deployment.0
Thu Jan 16 17:59:36 2020 [Z0][VMM][I]: ExitCode: 255
Thu Jan 16 17:59:36 2020 [Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
Thu Jan 16 17:59:36 2020 [Z0][VMM][E]: Error deploying virtual machine: Could not create domain from /var/lib/one//datastores/101/236/deployment.0
Thu Jan 16 17:59:36 2020 [Z0][VM][I]: New LCM state is BOOT_FAILURE
```

In OpenNebula 5.10.1, The GRAPHICS RANDOM_PASSWD is generated using sha256 instead of sha1. The length of generated password is 64. 
Acording  to https://gitlab.freedesktop.org/spice/spice-protocol/blob/master/spice/protocol.h , The SPICE_MAX_PASSWORD_LENGTH is 60.

**To Reproduce**
Instantiate VM Template with config 
`
GRAPHICS = [
  LISTEN = "0.0.0.0",
  RANDOM_PASSWD = "YES",
  TYPE = "SPICE" ]
`

**Expected behavior**

**Details**
 - Affected Component: VM
 - Hypervisor: KVM
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4618
- docs: https://github.com/OpenNebula/docs/pull/1088
