### ISSUE TITLE
vCenter hot attach/detach nics on poweroff nics

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4114]
**Description**

Attaching/detaching a nic from an instance has different behaviours if you do this with the instance in a poweroff state or if you do this in a poweron state.
Doing a hot attach invokes pre and post scripts
Doing a hot detach invokes clean script
Doing a cold attach/detach do not invoke those scripts
For vCenter could be useful treat both cases as hotplug invoking the scripts.

**Use case**
NSX security groups integration, needs add or delete rules into NSX Manager when a nic is attached or detached to apply the security groups on the fly. 

**Interface Changes**
Changes into core when attaching a nic with vcenter driver.

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge un master:

- code: https://github.com/OpenNebula/one/pull/4258
- docs: https://github.com/OpenNebula/docs/pull/964
