### ISSUE TITLE
Importing LXD image from marketplace is broken if admin/frontend is running in a container

### ISSUE THREAD

**Issue by yokem55** [OpenNebula/one#4124]
**Description**
It appears that importing a lxd image from the marketplace is broken if the admin/frontend node is itself running in a container. Looking at `/src/mad/sh/create_container_image.sh` the script unpacks the downloaded image from the marketplace, chroot's into it, works some magic to enable the contextualization stuff, and then loads it into an ext4 image by mounting the ext4 image via loop. 

This process breaks if run within a container because container systems don't have an easy way to use loop devices within the container as the linux loop driver is not namespaced. 

What ends up happening is that the mount of the empty ext4 image silently fails, the contents of the modified tarball are copied to where the mount point should have been, and then an empty image gets put into the datastore which naturally fails to boot when instantiated. 

There seem to be workarounds involving manually bringing the loop devices into the container, but this seems fragile as there is no easy way to  reserve them for exclusive use in the container and are likely to end up being used if the host is running the snap daemon. 

**To Reproduce**
1) Install sunstone/admin frontend within a container (lxd is what we are using, but I expect this to apply to all containerization systems)
2) Download a lxd container 'app' from the marketplace. The process will appear to work, and gets applied to the datastore.
3) The image won't boot.
4) Manually downloading the created image shows an empty ext4 image.

**Expected behavior**
A full image gets created and imported into the datastore.

**Details**
 - Affected Component: Sunstone/marketplace import
 - Hypervisor: LXD
 - Version: 5.8.5 - looking at the relevant code it hasn't been changed for over a year.

**Suggestions**
- Put a documentation warning about running the front-end in a container.
- ~~Use libguestfs to load the rootfs into the ext4 filesystem. This would likely work as fuse does work within a container. The process would likely be quite a bit slower though.~~ This is even less likely to work as it uses qemu and that is even less likely to work within the container.
- Add some validation and feedback in the image creation process to show the process is working instead of silently failing. 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Thanks for the feedback, we will work on your suggestions. Hopefully this limitation disappears on the future. It seems that the [latest LXD allows mounting devices inside the container](https://discuss.linuxcontainers.org/t/lxd-3-19-has-been-released/6529).

> Interception of the mount system call
Our system call interception layer has been extended to support intercepting the mount syscall.
This can be used to allow normally restricted filesystems to be mounted inside unprivileged containers, but maybe more importantly, it allows for transparent redirection of mount calls to FUSE drivers.
