### ISSUE TITLE
Allow to select the default number of templates shown in cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4126]
**Description**
The number of templates shown in cloud view are fixed (6,12,36,72). It would be useful to be able to customize the default value for that.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
duplicated by #3096

**Comment by jloboescalona2** [comment]
@tinova  PR to approve:
- ONE: https://github.com/OpenNebula/one/pull/4715
- Docs: https://github.com/OpenNebula/docs/pull/1121
