### ISSUE TITLE
Hooks execution information should be available in Sunstone UI

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4127]
**Description**
It would be useful to somehow show hooks execution information in Sunston UI.

**Interface Changes**
Sunstone

**Additional Context**
In older versions the hooks execution information was shown in VM log.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
closed in favour of #5724
