### ISSUE TITLE
Context ISO with old configuration on NIC detach

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4130]
**Description**

In the past when NIC detach happened, the OpenNebula didn't refresh the contextualization CD-ROM. Currently, the CD-ROM is refreshed, but still with old (pre-detach) 
NIC configuration.

E.g., see the CD-ROM change on NIC detach

```
Jan 29 09:08:01 debian10-280057 kernel: VFS: busy inodes on changed media or resized disk sr0
Jan 29 09:08:01 debian10-280057 kernel: VFS: busy inodes on changed media or resized disk sr0
Jan 29 09:08:02 debian10-280057 systemd[1]: Starting OpenNebula reconfiguration script...
Jan 29 09:08:02 debian10-280057 one-contextd[2249]: Started for type all to reconfigure
```

but, although we have detached NIC eth1, it's still on context.sh

```
...
ETH0_VROUTER_IP=''
ETH0_VROUTER_IP6=''
ETH0_VROUTER_MANAGEMENT=''
ETH1_CONTEXT_FORCE_IPV4=''
ETH1_DNS=''
ETH1_EXTERNAL=''
...
```

It's similar to NIC_ALIAS detach https://github.com/OpenNebula/one/issues/3484, but in both casese I would more prefer if the all entries just wanishes, instead of putting there extra DETACH=YES hintgs.

**To Reproduce**
1. Attach NIC
2. Detach NIC
3. Check context.sh and find detached NIC parameters

**Expected behavior**
`context.sh` contains current configuration.

**Details**
 - Affected Component: Core
 - Version: 5.8 and up

**Additional context**
Ref. https://opennebula.zendesk.com/agent/tickets/14277

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Note: Probably skip all DETACH=YES NIC's in context generation will fix the issues
