### ISSUE TITLE
Order wilds VMs list in Sunstone UI

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4131]
**Description**
It would be useful to show the list of wild VMs ordered in some way (e.g alphabetically).

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs for merge:
• one: #4145 into 5.10 and master
• docs: OpenNebula/docs/pull/919 into one-5.10-maintenance
