### ISSUE TITLE
Snapshots details not included in one.vmpool.infoextended

### ISSUE THREAD

**Issue by ahmedbilal** [OpenNebula/one#4136]
**Description**
Disk snapshot details are not present in output of  `one.vmpool.infoextended`.

**To Reproduce**
Try to perform the `one.vmpool.infoextended` XML-RPC and inspect the output.

**Expected behavior**
Snapshot details should be present in `one.vmpool.infoextended` output but it isn't.

**Additional context**
 Although, the detail can be obtained by individually getting it using `one.vm.info` but that is tiresome and takes too much time in case of hundreds of VMs.

https://github.com/OpenNebula/one/blob/2ff0324bb224dd73d246b864bd0cd9eea115e998/share/doc/xsd/vm.xsd

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Can you provide more information about how are you testing this issue and which OpenNebula version are you using?

I've tried for OpenNebula 5.10.1 by doing the XML-RPC directly and it does retrieve snapshots information:

```
pry(main)> @client.call('vmpool.infoextended', -1, -1, -1, -1)      
=> "<VM_POOL><VM>...</HISTORY_RECORDS><SNAPSHOTS><ALLOW_ORPHANS><![CDATA[NO]]></ALLOW_ORPHANS><CURRENT_BASE><![CDATA[-1]]></CURRENT_BASE><DISK_ID><![CDATA[0]]></DISK_ID><NEXT_SNAPSHOT><![CDATA[1]]></NEXT_SNAPSHOT><SNAPSHOT><ACTIVE><![CDATA[YES]]></ACTIVE><DATE><![CDATA[1580383845]]></DATE><ID><![CDATA[0]]></ID><NAME><![CDATA[sn0]]></NAME><PARENT><![CDATA[-1]]></PARENT><SIZE><![CDATA[256]]></SIZE></SNAPSHOT></SNAPSHOTS></VM></VM_POOL>"
```

**Comment by ahmedbilal** [comment]
> Can you provide more information about how are you testing this issue and which OpenNebula version are you using?
> 
> I've tried for OpenNebula 5.10.1 by doing the XML-RPC directly and it does retrieve snapshots information:
> 
> ```
> pry(main)> @client.call('vmpool.infoextended', -1, -1, -1, -1)      
> => "<VM_POOL><VM>...</HISTORY_RECORDS><SNAPSHOTS><ALLOW_ORPHANS><![CDATA[NO]]></ALLOW_ORPHANS><CURRENT_BASE><![CDATA[-1]]></CURRENT_BASE><DISK_ID><![CDATA[0]]></DISK_ID><NEXT_SNAPSHOT><![CDATA[1]]></NEXT_SNAPSHOT><SNAPSHOT><ACTIVE><![CDATA[YES]]></ACTIVE><DATE><![CDATA[1580383845]]></DATE><ID><![CDATA[0]]></ID><NAME><![CDATA[sn0]]></NAME><PARENT><![CDATA[-1]]></PARENT><SIZE><![CDATA[256]]></SIZE></SNAPSHOT></SNAPSHOTS></VM></VM_POOL>"
> ```

@christian7007 I re-verified your finding by doing xml-rpc directly as well in Python and snapshots does appear. But, when I use `pyone` OneNebula XML-RPC client for Python it does not show snapshots. I think there is bug in pyone's code.

**Comment by ahmedbilal** [comment]
@christian7007 Found the source of issue. https://github.com/OpenNebula/one/blob/master/share/doc/xsd/vm_pool.xsd is missing the `SNAPSHOT` element which can be found at https://github.com/OpenNebula/one/blob/master/share/doc/xsd/vm.xsd

**Comment by xorel** [comment]
Good catch, thanks! This should be fixed in the upcoming release.

**Comment by ahmedbilal** [comment]
> Good catch, thanks! This should be fixed in the upcoming release.

@xorel I have already created the PR https://github.com/OpenNebula/one/pull/4138

**Comment by xorel** [comment]
Sure, I closed my duplicate. If you want to make gitcop happy you need wrap whole commit message to max 50 chars per line.

**Comment by ahmedbilal** [comment]
> Sure, I closed my duplicate. If you want to make gitcop happy you need wrap whole commit message to max 50 chars per line.

@xorel Thanks. I edit it directly, is it possible to edit commit message after commit.

**Comment by xorel** [comment]
I guess you need to git amend and force push.
