### ISSUE TITLE
VM Stuck in SNAPSHOT state

### ISSUE THREAD

**Issue by lrodrin** [OpenNebula/one#4137]
![Screenshot from 2020-01-30 12-53-04](https://user-images.githubusercontent.com/7712795/73447685-8e811600-435f-11ea-831e-adcb3898c868.png)
Hi,

A VM stuck in the SNAPSHOT state. And I can't do anything with this VM :( I think it is dead.

There is a way to stop o recuperate the functionalities. I can't terminate, power off, etc.

Any help would be appreciated.

Thank you,
Laura

**Comment by rsmontero** [comment]
You can try recovering it (e.g. after checking the snaphost operation in the hypervisor you can fail or succeed it)

http://docs.opennebula.org/5.10/advanced_components/ha/ftguide.html#ftguide-virtual-machine-failures

**Comment by lrodrin** [comment]
Sorry Ruben, 

I'm not an admin on our platform installation. There is another solution?

The machine take's more than 24 hours doing the snapshot.

Thank you,
Laura
