### ISSUE TITLE
vRouter not showing floating IP

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#4147]
**Description**
When a vRouter is configured with a floating IP, this floating IP is not shown on the vRouter instance via Sunstone or CLI (although it can be seen on the XML output).

**To Reproduce**
Create a 2 instances vRouter, add a NIC with a floating IP. 

**Details**
 - Affected Component: Sunstone, CLI... OCA?
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by robmbrooks** [comment]
We are having a similar issue. Existing virtual routers (created prior to 5.10) are providing a floating IP, the .1 address, however the IP does not show in the UI and was allocated to a newly created guest.

The IP is definitely still present on the virtual router cluster, and acts as a gateway for guests and was visible in the UI at some point in the past.

**Comment by FrederickBor** [comment]
@tinova PR to be approved:

- One: https://github.com/OpenNebula/one/pull/4561
- Docs: https://github.com/OpenNebula/docs/pull/1068
