### ISSUE TITLE
name in vcenter templates

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4150]
**Description**
Depends on if a vcenter template is imported or if it's created instantiating a template as persistent the opennebula template name should be the same as vcenter template name.

**Use case**
Maintain consistency between names

**Interface Changes**
vCenter driver

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4350
* https://github.com/OpenNebula/one/pull/4365

[DOC]
* https://github.com/OpenNebula/docs/pull/1018
