### ISSUE TITLE
Error editing group admin in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4153]
**Description**
When selecting a user on "Edit administrators" dialog, the selected username displays with some html tags and CSS class info. 

**To Reproduce**
Edit group administrator in Sunstone.

**Expected behavior**
The username should appear instead of css and html tags.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10 and 5.10.1

**Additional context**

![Create_group_admin01](https://user-images.githubusercontent.com/33811723/73725507-ce644680-472d-11ea-9e0d-ef6ff0ebef2c.png)
![Create_group_admin02](https://user-images.githubusercontent.com/33811723/73725509-cf957380-472d-11ea-93b5-1c3c4b164739.png)
![Create_group_admin03](https://user-images.githubusercontent.com/33811723/73725512-d0c6a080-472d-11ea-993b-fa083ce63d2e.png)

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
