### ISSUE TITLE
Search box for wilds VMs in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4161]
**Description**
Add a text search box in wilds tab in Sunstone.

**Use case**
It is useful to search when you have too many wilds VMs and just want to import one or two VMs.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4632
- Docs: https://github.com/OpenNebula/docs/pull/1092
