### ISSUE TITLE
Increase number of wild VMs shown per page

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4162]
**Description**
Increase number of wild VMs shown per page or add option for shown all VMs in same page. Currently max is 100.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4176 
• docs: OpenNebula/docs/pull/931
