### ISSUE TITLE
detaching disk issue: "error detaching VM Disk: Could not detach sdc from"

### ISSUE THREAD

**Issue by pumpkineggs** [OpenNebula/one#4164]
**Description**
While detaching disk from VM in some cases an error could be thrown like: "error detaching VM Disk: Could not detach sdc from <domain>". 

**To Reproduce**
1) Create user with name sdaniel
2) Create a VM owned by the user and attach scsi disk (sda).
3) Try to detach the disk on running VM.
4) Get an error.

**Expected behavior**
Disk detached, no error thrown.

**Details**
 - Affected Component: vmm_mad 
 - Hypervisor: KVM
 - Version: 5.10.x

**Additional context**
We noticed that "detach_disk" script (vmm_mad/remotes/kvm/detach_disk) should use a more efficient way to check whether a disk detached or not.
While detaching disk from VM in some cases an error could be thrown like: "error detaching VM Disk: Could not detach sdc from <domain>". 
But in fact, the disk has been detached from the VM and it can be confirmed via "virsh dumpxml" command.
There is a piece of code in the script:
```
virsh --connect $LIBVIRT_URI dumpxml $DOMAIN | grep $TARGET > /dev/null 2>&1

if [ $? -eq 0 ] ; then
    error_message "Could not detach $TARGET from $DOMAIN"
    exit -1
fi
```
Here we have ```grep $TARGET``` part where $TARGET turns into a device name (i.e. vda, sda, sdc, etc...).
Let's say we are trying to detach a scsi disk "sda", so the script will run a check with ```grep sda```.
And an interesting part is if the owner of the VM is a user with a name: sdaniel, which is reflected in the domain xml metadata section, grep will return some data and ```if [ $? -eq 0 ] ;``` piece will return an error and script will exit with rc=-1 in spite the disk has been detached from the domain. 

Proposed changes for the script:
```virsh --connect $LIBVIRT_URI dumpxml $DOMAIN | grep dev=\'$TARGET\' > /dev/null 2>&1```
Just be more specific about what to grep and extend the regexp to ```dev=\'$TARGET\'```.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
merged
