### ISSUE TITLE
Clusters not working on Virtual Network Templates

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#4169]
**Description**
"When a network is created by instantiating a Virtual Network Template it is associated to the default cluster. You can control which clusters the networks will be in with the CLUSTER_IDS attribute." This is not working

**To Reproduce**
Create a Virtual Network Template with a similar config to this:

```
AUTOMATIC_VLAN_ID = "YES"
CLUSTERS = "0,100,101"
PHYDEV = "bond0"
VN_MAD = "802.1Q"
```

**Expected behavior**
Any vnet instantiated from the previous vnet template should belong to clusters 0, 100 and 101. It only belongs to default cluster (0), although an attribute is created called "CLUSTERS" with the cluster config set on the vnet template.

**Details**
 - Affected Component: Sunstone, CLI
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
The xmlrpc call vntemplate.instantiate does not have any parameter for cluster ID like vn.allocate. vntemplate.instantiate receives the call from the oca inserting the cluster id(s) on the template, which is later on used as an attribute of the newly created VM, it does not add the new vnet to those clusters

**Comment by christian7007** [comment]
Hello @sergiojvg, as you said:

> You can control which clusters the networks will be in with the CLUSTER_IDS attribute.

You have to use `CLUSTER_IDS` attribute for specifying the cluster which the newly created vnet will belong to. But you are using `CLUSTERS` instead.

Regarding the XMLRPC call, `one.vntemplate.instantiate` takes care of parsing this attribute and add the network to the specified clusters:

https://github.com/OpenNebula/one/blob/944f12446d639b1c3a725ab102d1daa8fcfeb9bd/src/rm/RequestManagerVNTemplate.cc#L198

**Comment by sergiojvg** [comment]
Hi @christian7007 , long time no see :) You are totally right, CLUSTER_IDS worked like a charm. I was looking in the wrong place by thinking the xmlrpc call could be related, but there is still a problem.

The vntemplate's template (that sounds weird) was not generated by me, but by Sunstone. This means that the fix is even easier but Sunstone should use CLUSTER_IDS instead of CLUSTERS when generating the template. To make things worst, the template can not be updated from sunstone, so users will need to use the CLI for this.

I did not try generating the vntemplate from the CLI, not sure if this issue will also arise if generated from the CLI.

**Comment by christian7007** [comment]
Hello @sergiojvg, yes it's nice to see you around. To create a vntemplate using CLI you need to provide a file with the vntemplate description so it should works fine but might by a bit tricky for some users.

As workaround, while Sunstone is fixed, you can keep creating the vntemplates via Sunstone and just updated the `CLUSTERS` attribute name to `CLUSTER_IDS` by using CLI.

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4182
• docs: _waiting for release_

**Comment by sergiojvg** [comment]
@tinova @sbbarragan , small issue on the PR, it says **CLUSTERS_IDS** when it should be **CLUSTER_IDS**. Besides this code works like a charm

**Comment by tinova** [comment]
Thanks for the heads up Sergio!

**Comment by sergiojvg** [comment]
:+1:
