### ISSUE TITLE
NIC Aliases are not removed when updating the template in Sunstone

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#4178]
**Description**
When a VM template is updated using Sunstone and you remove an alias, it isn't removed at the end.

**To Reproduce**
Have a template with alias, remove one of them and click on update. Finally check the template and the alias is there.

**Expected behavior**
The alias should be removed from the template.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10.x and master.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4180
• docs: _waiting for release_
