### ISSUE TITLE
Sunstone host tabs unclickable when one of the numa nodes is with 0 RAM

### ISSUE THREAD

**Issue by bgmastermind** [OpenNebula/one#4190]
**Description**
When you open host details tabs are unclickable, because of javascript error 
```
Uncaught ReferenceError: info is not defined
    at numa.js:196
    at Array.map (<anonymous>)
    at Panel._setup [as setup] (numa.js:127)
    at Panel.<anonymous> (sunstone.js:865)
    at Function.each (jquery.js:371)
    at Object._insertPanels [as insertPanels] (sunstone.js:864)
    at callback (common-actions.js:62)
    at Object.success (action.js:317)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
```

**To Reproduce**
Add a host with memory sticks only in one numa. Open host details in sunstone
Example host
```
numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 6 7 16 17 18 19 20 21 22 23
node 0 size: 64394 MB
node 0 free: 37929 MB
node 1 cpus: 8 9 10 11 12 13 14 15 24 25 26 27 28 29 30 31
node 1 size: 0 MB
node 1 free: 0 MB
node distances:
node   0   1
  0:  10  20
  1:  20  10
```

**Expected behavior**
working tabs

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by fborges-opennebula** [comment]
Can you please send us output for the following command: `onehost show -x [host_id]`

Where **host_id** is the id of the host that is presenting the Sunstone issue.

**Comment by bgmastermind** [comment]
Can't do it right now, because when I found that this is the issue, the servers memory was rearranged properly to both numas. So it's no longer in this hardware config. But I no longer remember which server it was, so probably will have to pick one and break it.

**Comment by fborges-opennebula** [comment]
Ok, thanks for your feedback. We are closing this ticket until we get further information on how to reproduce
