### ISSUE TITLE
vCenter context data not refreshed NIC (alias) detach

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4194]
**Description**

vCenter VM contextualization metadata, which are accessed from the VM via:
```
vmtoolsd --cmd 'info-get guestinfo.opennebula.context' | base64 -d
```
are not refreshed when:
- NIC is detached
- NIC alias is detached

This is a follow up of #4130 , similar problem we had on KVM (CD-ROM) recently.

**To Reproduce**
- Run VM
- Attach extra NIC (alias)
- Validate metadata via above cmd and find actual state
- Detach NIC (alias)
- Validate metadata via above cmd are find they are NOT refreshed

**Details**
 - Hypervisor: vCenter
 - Version: 5.10.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE] https://github.com/OpenNebula/one/pull/4316

[DOC] https://github.com/OpenNebula/docs/pull/982
