### ISSUE TITLE
Collectd continually SIGABRTs on Centos 8

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4195]
**Description**

Host is centos 8.1. When collectd received SIGHUP it normally crashes and coredumps. Selinux is disabled:

```
           PID: 7665 (ruby)
           UID: 9869 (oneadmin)
           GID: 9869 (oneadmin)
        Signal: 6 (ABRT)
     Timestamp: Sat 2020-02-15 14:46:51 SAST (14s ago)
  Command Line: ruby /var/tmp/one/im/kvm.d/collectd-client.rb kvm /var/lib/one//datastores 4124 60 7 xxx
    Executable: /usr/bin/ruby
 Control Group: /user.slice/user-9869.slice/session-30717.scope
          Unit: session-30717.scope
         Slice: user-9869.slice
       Session: 30717
     Owner UID: 9869 (oneadmin)
       Boot ID: fd91d89fde074f8c900cbafcbfa7eda3
    Machine ID: 6f4a95a7928c4e909fc2faa39c83029d
      Hostname: xxx
       Storage: /var/lib/systemd/coredump/core.ruby.9869.fd91d89fde074f8c900cbafcbfa7eda3.7665.1581770811000000.lz4
       Message: Process 7665 (ruby) of user 9869 dumped core.
                
                Stack trace of thread 7665:
                #0  0x00007f2551569b94 read (libpthread.so.0)
                #1  0x00007f2551919a3d rb_thread_io_blocking_region (libruby.so.2.5)
                #2  0x00007f25518404ba io_bufread (libruby.so.2.5)
                #3  0x00007f2551840528 bufread_call (libruby.so.2.5)
                #4  0x00007f2551819774 rb_ensure (libruby.so.2.5)
                #5  0x00007f255183ba9c io_fread (libruby.so.2.5)
                #6  0x00007f255183fbb6 read_all (libruby.so.2.5)
                #7  0x00007f255184b2a0 rb_f_backquote (libruby.so.2.5)
                #8  0x00007f25519414b8 vm_call_cfunc (libruby.so.2.5)
                #9  0x00007f25519476de vm_exec_core (libruby.so.2.5)
                #10 0x00007f255194b3ce vm_exec (libruby.so.2.5)
                #11 0x00007f255194e4dd vm_invoke_proc (libruby.so.2.5)
                #12 0x00007f255194e5f2 rb_vm_invoke_proc (libruby.so.2.5)
                #13 0x00007f255194ffb4 vm_call0_body.constprop.146 (libruby.so.2.5)
                #14 0x00007f2551950ebb rb_call0 (libruby.so.2.5)
                #15 0x00007f2551951792 rb_funcallv (libruby.so.2.5)
                #16 0x00007f2551951b3c rb_eval_cmd (libruby.so.2.5)
                #17 0x00007f25518e5035 signal_exec (libruby.so.2.5)
                #18 0x00007f255191834a rb_threadptr_execute_interrupts.part.60 (libruby.so.2.5)
                #19 0x00007f25518e5d19 rb_f_kill (libruby.so.2.5)
                #20 0x00007f25519414b8 vm_call_cfunc (libruby.so.2.5)
                #21 0x00007f25519476de vm_exec_core (libruby.so.2.5)
                #22 0x00007f255194b3ce vm_exec (libruby.so.2.5)
                #23 0x00007f255194ca47 loop_i (libruby.so.2.5)
                #24 0x00007f2551819150 rb_rescue2 (libruby.so.2.5)
                #25 0x00007f25519414b8 vm_call_cfunc (libruby.so.2.5)
                #26 0x00007f255194fa83 vm_call_general (libruby.so.2.5)
                #27 0x00007f2551946d5a vm_exec_core (libruby.so.2.5)
                #28 0x00007f255194b3ce vm_exec (libruby.so.2.5)
                #29 0x00007f255181683e ruby_exec_internal (libruby.so.2.5)
                #30 0x00007f25518188a1 ruby_exec_node (libruby.so.2.5)
                #31 0x00007f255181b022 ruby_run_node (libruby.so.2.5)
                #32 0x0000558a3fb60a4f main (ruby)
                #33 0x00007f2550771873 __libc_start_main (libc.so.6)
                #34 0x0000558a3fb60a9e _start (ruby)
                
                Stack trace of thread 7678:
                #0  0x00007f255083f591 __poll (libc.so.6)
                #1  0x00007f255191ae65 thread_timer (libruby.so.2.5)
                #2  0x00007f25515602de start_thread (libpthread.so.0)
                #3  0x00007f255084a4b3 __clone (libc.so.6)
```

**Details**
 - Affected Component: collectd
 - Hypervisor: KVM
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Collectd updates usage information when it receives SIGHUP. It seems there is an issue with centos8 and its ruby version. 

You can comment out the `ssh_exec_and_log_noerror` call in:

https://github.com/OpenNebula/one/blob/master/src/mad/sh/scripts_common.sh#L1021

**Comment by mzealey** [comment]
@rsmontero would that not stop collectd from sending anything though?

**Comment by rsmontero** [comment]
It will send the information based on the timer (you pass this command on -i option for collect.d)

**Comment by mzealey** [comment]
OK thanks. We should probably leave this ticket open to track the issue until either fixed in upstream ruby, or in the collectd code.

**Comment by xorel** [comment]
I can not reproduce. Does the collectd crashes always after receiving SIGHUP?

Can you share the config attrs from oned?
`MONITORING_INTERVAL_HOST`

and also

`IM_MAD = [`
`      NAME       = "collectd",`
`      EXECUTABLE = "collectd",`
`      ARGUMENTS  = "-p 4124 -f 5 -t 50 -i 60" ]`

Can you also remove `kvm-probes.d/collectd-client-shepherd.sh` on the hypervisor to see if this could be the source of the SIGABRT signal?

**Comment by mzealey** [comment]
no change to standard collectd setup as you quote above.

```
MONITORING_INTERVAL_HOST      = 30
```

It crashes at least 90% of the time although I saw once or twice when it didnt crash.

I'm guessing the `-i 60` is probably not helping; however this has always worked on centos 7 without issue. Dropping to 10 or 15 doesnt affect the crash.

```
# rpm -qa |grep ruby
ruby-libs-2.5.5-105.module_el8.1.0+214+9be47fd7.x86_64
rubygem-json-2.1.0-105.module_el8.1.0+214+9be47fd7.x86_64
rubygem-bigdecimal-1.3.4-105.module_el8.1.0+214+9be47fd7.x86_64
ruby-2.5.5-105.module_el8.1.0+214+9be47fd7.x86_64
rubygem-did_you_mean-1.2.0-105.module_el8.1.0+214+9be47fd7.noarch
rubygem-psych-3.0.2-105.module_el8.1.0+214+9be47fd7.x86_64
rubygem-io-console-0.4.6-105.module_el8.1.0+214+9be47fd7.x86_64
rubygem-rdoc-6.0.1-105.module_el8.1.0+214+9be47fd7.noarch
ruby-irb-2.5.5-105.module_el8.1.0+214+9be47fd7.noarch
rubygems-2.7.6.2-105.module_el8.1.0+214+9be47fd7.noarch
rubygem-openssl-2.1.2-105.module_el8.1.0+214+9be47fd7.x86_64
```

Perhaps this is the reason?

```
time /var/tmp/one/vmm/kvm/poll -t
...
real    0m47.898s
user    0m22.464s
sys     0m18.355s
```

**Comment by xorel** [comment]
Yes, those intervals and the fact that the KVM poll takes so long can make the problem.

ONE expects to receive monitor data every 30s as soon as they don't arrive, it falls back to the pull monitoring so ONE ssh to the hypervisor and restart collectd (collectd-client_control.sh) and it crashes.

`monitoring cycle` < `collectd cycle (-i)` < `MONITORING_INTERVAL_HOST`

Can you try changing the values to see if the crashses remain?
e.g:
MONITORING_INTERVAL_HOST = 120
collectd -i = 60 ( you will need to run onehost forceupdate + restart collectd on host)

**Comment by mzealey** [comment]
Yup switching to 60s intervals fixes the crashes so suspect it was the time the poll script takes on this server...

We wanted a lower value to get quicker monitoring if a host went offline to start a dr process. I'll try to figure out if its possible to speed up this script somehow.

**Comment by rsmontero** [comment]
BTW, new monitoring will feature a separate message to check host health status, decouple from the rest of the monitor information.. so you'll get that quicker information without stressing the monitoring system itself.

Also sometimes restarting libvirtd helps...
