### ISSUE TITLE
onehook CLI improvements

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4203]
**Description**

Following easy improvements might be considered for `onehook` CLI tool:
1. command doesn't expand to the terminal width as other commands
2. hook delete fails when provided with hook name

```
$ onehook delete refresh_dns_create-0
/usr/lib/one/ruby/cli/one_helper.rb:859:in `perform_actions': undefined method `each' for "refresh_dns_create-0":String (NoMethodError)
	from /usr/bin/onehook:175:in `block (2 levels) in <main>'
	from /usr/lib/one/ruby/cli/command_parser.rb:470:in `call'
	from /usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
	from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
	from /usr/bin/onehook:40:in `new'
	from /usr/bin/onehook:40:in `<main>'
```

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4206
- docs: https://github.com/OpenNebula/docs/pull/947

**Comment by vholer** [comment]
Note: change in config is not for one-5.10

**Comment by rsmontero** [comment]
ok will split in two so we can have the functionality 5.10.x

**Comment by al3xhh** [comment]
@rsmontero change done! @vholer thanks for the heads up!!
