### ISSUE TITLE
NICs are not removed from a template in Sunstone

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4204]
**Description**
Updating a template if you remove a NIC from sunstone the NIC is not removed. It works from CLI

**To Reproduce**
Import a template
Update template and add a NIC
Update template and remove a NIC
Check that NIC is still there

**Expected behavior**
NIC should be removed from template

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4213
• docs: OpenNebula/docs/pull/948
