### ISSUE TITLE
Provision failover mode combinations

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4205]
**Description**

Provision tool (in 5.10) supports selectable failure handling from

- retry failing operation
- skip failing operation
- quit and leave state as-is
- cleanup (= rollback changes) and exit

Selected failure handling method is exclusive, only one is respected. I.e., when retry 3x is chosen and operation fails after 3 tries, tool simply exists and leaves the state as-is. To make provision setup more robust, it would be good to support combination of failover methods.

For example, be eable to specify at least:
- retry 3x **and clean-up** if still failing

NICE TO HAVE: configurable sleep between retries

We can review existing `oneprovision` arguments and change them to support more flexibility.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/19)
- [docs](https://github.com/OpenNebula/docs/pull/1207)

PR to merge in 5.12:

- [docs](https://github.com/OpenNebula/docs/pull/1208)
