### ISSUE TITLE
Provision support of other object types

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4214]
**Description**
Provision can create as part of provision cluster, hosts, datastores and vnets (http://docs.opennebula.org/5.10/advanced_components/ddc/reference/provision/overview.html#provision-objects). We might need to extend the support for following more objects:

- templates
   - vm
   - vnet
- images
- marketapp
- oneflow template

All entities should be able to support also configuring:
- owner / group
- permissions mode

Notes:
- images and marketapps should support 2 operation modes
    - **asynchronous** -  just create the objects and continue (exit)
    - **synchronous** - create objects and wait until they are successfully imported
        - in case of failure, retry should delete the failed image and retry create again
- images/marketapp should be able to reference the newly created datastores, probably using ERB
- IMPORTANT: we now merge defaults+overrides for each supported objects (which makes perfect sense for infrastructure objects). I'm not sure if that makes sense to follow that with vnet template, but definitely NOT with end user objects (VM templates, images/marketapps).

**Use case**
New cluster with all necessary objects ready to start VM.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4374
- docs: https://github.com/OpenNebula/docs/pull/1001
- tests: https://github.com/OpenNebula/development/pull/891
