### ISSUE TITLE
Provision templates for complete cluster

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4215]
**Description**

Include examples of provision templates for complete cluster with datastores and vnets at least for Packet. Since they need to per-provider specific credentials, I propose to put them into a different directory than rest templates (not `/usr/share/one/oneprovision/templates`), probably here `/usr/share/one/oneprovision/examples`.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4498
- docs: https://github.com/OpenNebula/docs/pull/1042
