### ISSUE TITLE
oneimage create always validate image path on CLI client

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4221]
**Description**
When uploading an image to opennebula via CLI, the image existence is validate locally where the command is run, and then the datastore operations are executed on the frontend. If the frontend is not the same host as the CLI client, it is unnecessary to validate the image file locally. If the image is in the correct path on the frontend, but there is no equal path in the CLI client, `oneimage create` will fail due to this validation.

**To Reproduce**
- Setup an opennebula server and a CLI client on different hosts.
- put an image file on the opennebula server
- `oneimage create` with `--path` the path of the image in the frontend

**Expected behavior**
If the image exists in the frontend it shouldn't be validated locally. 

**Details**
 - Affected Component: CLI

**Additional context**
Maybe adding a flag, for example `--remote`, to `oneimage` in order to signal a remote path for the image would help, or don't check the image path at all in the CLI.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
IMO the cli tool should not validate image. There is a datastore MAD that will raise error if there is an issue with the file import

**Comment by dann1** [comment]
Code: https://github.com/OpenNebula/one/pull/4245
Docu: https://github.com/OpenNebula/docs/pull/960
