### ISSUE TITLE
Add link in Sunstone to go to Service VM tab

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4222]
**Description**
For specific operations on a VM you have to go to the VM because it is not possible to do from the service view.
It would be great if it is possible to simply click on the VM ID and will be redirected to the VM.

**Use case**
Specific VM operations.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This is alredy fixed here https://github.com/OpenNebula/one/commit/2526272c8b059bc4408ec2f8db78d99ea38081a5 by part of #4132
