### ISSUE TITLE
[object Object] in Address ranges for Virtual Network Templates

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4234]
**Description**
![image](https://user-images.githubusercontent.com/7556217/74954810-fdeca180-5403-11ea-959a-646fea996d4d.png)

**To Reproduce**
* Create Virtual Network Templates :
```
NAME = "blabla"
AUTOMATIC_VLAN_ID = "YES"
CLUSTERS = "100"
PHYDEV = "bond0.4"
VN_MAD = "vxlan"
AR = [
  IP = "192.168.1.1",
  SIZE = "254",
  TYPE = "IP4",
  AR_ID = "" ]
```
* Open Sunstone

**Expected behavior**

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.2

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4265
• docs: OpenNebula/docs/pull/966
