### ISSUE TITLE
Provision delegation to Terraform

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4247]
**Description**
The oneprovision is a wrapper above the provision drivers which allocates / releases the hosts and Ansible which takes care about the configuration part of the provision. A simple command abstracts the usage of more advanced tools. As we would like to deploy more advanced architectures in the provisioning phase, just the host provisioning mechanism doesn't have to be enough. Moreover, we are here limited to the drivers specific to the OpenNebula. The goal is to delegate provisioning logic to the some external tool which takes are of provisioning (same as Ansible does configuration).
The de facto standard for the infrastructure provision is Terraform.

(leaving without implementation details, as the idea needs to be prototyped first)

**Use case**
- Easy access to more cloud providers
- Deploy more advanced architectures

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
This has been implemented [here](https://github.com/OpenNebula/one/issues/5124).

Closing this.
