### ISSUE TITLE
Capacity bars show maximum CPU and RAM incorrectly

### ISSUE THREAD

**Issue by tsarajar** [OpenNebula/one#4256]
**Description**
If one configures "Reserved CPU" or RAM for the entire cluster (or perhaps adjust the individual host reservations, the Capacity bars for the host and the window where all the hosts are listed show incorrect values for the maximum capacity. If you reserve say 20%, the GUIs reduce the maximum amount by 20% not once, but twice.

In other words, let's say you have 100GB of ram and you reserve 20%. It shows that the maximum is 100*0,8*0,8 = 64GB of RAM. But it knows it can go for up to 80GB, so it might say you are currently using 74GB/64GB (115,6%) if you were using 74 GB that is. Thus telling us that we over commit over the max limit, even though we don't.

**To Reproduce**
Adjust the sliders for reserved capacity.

**Expected behavior**
Maximum values are adjusted only once.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:

- One: https://github.com/OpenNebula/one/pull/4514
- Docs: https://github.com/OpenNebula/docs/pull/1047
- Dev: https://github.com/OpenNebula/development/pull/918
