### ISSUE TITLE
Select partition to resize when resizing disk

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4257]
**Description**
Be able from sunstone or one cli, when resizing a VM disk, to select the partition to resize. A default value could be provided in the VM template.

**Use case**
Growing non `/` partitions.

**Interface Changes**
Partition (or mountpoint) should be selectable per disk on Sunstone and CLI.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by ospalax** [comment]
PRs:
- https://github.com/OpenNebula/docs/pull/1837
- https://github.com/OpenNebula/addon-context-linux/pull/228
- https://github.com/OpenNebula/addon-context-windows/pull/94
- https://github.com/OpenNebula/development/pull/1456
- https://github.com/OpenNebula/development/pull/1483
