### ISSUE TITLE
Can't add alias IP on NIC created with NETWORK_MODE=auto

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4262]
**Description**
Alias IP could not be added on NIC created with `NETWORK_MODE=auto` rising error

```
[one.vm.attachnic] Alias not found.
```

**To Reproduce**
1 Define a VM template with NIC assigned to any network
2 Set NETWORK_MODE=auto (The network details will disappear)
3. Instantiate a VM from the defined template
4. try to attach an IP Alias

**Expected behavior**
IP Alias should be added

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [5.10.2]

**Additional context**
The VM template had

```xml
    <NIC>
      <NETWORK><![CDATA[net-192.168.122]]></NETWORK>
      <NETWORK_MODE><![CDATA[auto]]></NETWORK_MODE>
      <NETWORK_UNAME><![CDATA[oneadmin]]></NETWORK_UNAME>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
    </NIC>
```

The alias NIC is failing because the `NAME` element is missing in the VM Metadata:
```xml
    <NIC>
      <AR_ID><![CDATA[1]]></AR_ID>
      <BRIDGE><![CDATA[virbr0]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[linux]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[0,100,101,102]]></CLUSTER_ID>
      <FILTER_IP_SPOOFING><![CDATA[YES]]></FILTER_IP_SPOOFING>
      <FILTER_MAC_SPOOFING><![CDATA[YES]]></FILTER_MAC_SPOOFING>
      <IP><![CDATA[192.168.122.16]]></IP>
      <MAC><![CDATA[02:00:c0:a8:7a:10]]></MAC>
      <NETWORK><![CDATA[net-192.168.122]]></NETWORK>
      <NETWORK_ID><![CDATA[0]]></NETWORK_ID>
      <NETWORK_MODE><![CDATA[auto]]></NETWORK_MODE>
      <NIC_ID><![CDATA[0]]></NIC_ID>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-211-0]]></TARGET>
      <VN_MAD><![CDATA[bridge]]></VN_MAD>
    </NIC>
```

After altering the VM Metadata manually by adding `<NAME><![CDATA[NIC0]]></NAME>` the IP alias was added without issues.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4266
- docs: https://github.com/OpenNebula/docs/pull/967

**Comment by al3xhh** [comment]
Thanks @atodorov-storpool !!
