### ISSUE TITLE
[one.template.instantiate] broken double quotes escape in sunstone for SCHED*REQUIREMENTS 

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4269]
**Description**
Unable to instantiate a VM with defined `SHED*REQUIREMENTS`

**To Reproduce**
1. Enable more detailed logging `LOG_CALL_FORMAT    = "Req:%i UID:%u IP:%A %m invoked %l1000"`
2. Try to instantiate a VM with `SCHED_REQUIREMENTS` or `SCHED_DS_REQUIREMENTS`
An error will be thrown(with full message):

```
Wed Feb 26 18:34:15 2020 [Z0][ReM][D]: Req:3872 UID:0 IP:127.0.0.1 one.template.instantiate invoked , 28, "", false, "DISK=[
  CACHE="none",
  DISCARD="unmap",
  IMAGE_ID="190",
  IO="native"
]

SCHED_REQUIREMENTS="CLUSTER_ID="102" | CLUSTER_ID="101""
SCHED_DS_REQUIREMENTS="ID="100" | ID="104""
NIC=[
  NETWORK_MODE="auto"
]

MEMORY="768"
CPU="1"
NIC_ALIAS = []", false
Wed Feb 26 18:34:15 2020 [Z0][ReM][E]: Req:3872 UID:0 one.template.instantiate result FAILURE [one.template.instantiate] Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 7, columns 117:127
```

**Expected behavior**
The VM should be instantiated

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**
Reverting the second part of https://github.com/OpenNebula/one/commit/a2018bcf083da009ce067068dd59d8d5228d27d9 (the change in `wizard-fields.js`) looks like resolving the issue:

```
Wed Feb 26 22:39:43 2020 [Z0][ReM][D]: Req:4336 UID:0 IP:127.0.0.1 one.template.instantiate invoked , 28, "", false, "SCHED_REQUIREMENTS="CLUSTER_ID=\"102\" | CLUSTER_ID=\"101\""
SCHED_DS_REQUIREMENTS="ID=\"100\" | ID=\"104\""
NIC=[
  NETWORK_MODE="auto"
]

MEMORY="768"
CPU="1"
NIC_ALIAS = []", false
Wed Feb 26 22:39:43 2020 [Z0][ReM][D]: Req:4336 UID:0 one.template.instantiate result SUCCESS, 213
```

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Forgot to clarify - tested on _one-5.10_ branch

**Comment by sbbarragan** [comment]
Hi @atodorov-storpool,
You are right, I forgot to include both values in the "escapeDoubleQuotes" function.

Sorry for the inconvenience and thanks!

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4275
• docs: OpenNebula/docs/pull/970
