### ISSUE TITLE
Wait gate to report ready breakes service labels

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4273]
**Description**
Having a service template with some labels in Sunstone and then update it to check wait gate to report ready breaks the labels.

**To Reproduce**
Have a template with some labels and update it to check the wait gate to report ready.

**Expected behavior**
Labels shouldn't be affected.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4349 
• docs: OpenNebula/docs/pull/991
