### ISSUE TITLE
Fail to remove sched requirements from Sunstone

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#4274]
**Description**
Having some custom sched requirements in template and then try to delete them is failing.

**To Reproduce**
Add the following sched requirements to the template

```
SCHED_REQUIREMENTS = "ROLE=prod"
```
Then update and delete it.

**Expected behavior**
The requirement should be deleted.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4333
• docs: OpenNebula/docs/pull/986

**Comment by tinova** [comment]
This can use a test
