### ISSUE TITLE
Fail to delete VNC information when updating VM template in Sunstone

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#4278]
**Description**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4333 
• docs: OpenNebula/docs/pull/986
