### ISSUE TITLE
man pages in source tarball

### ISSUE THREAD

**Issue by loveshack** [OpenNebula/one#4279]
**Description**
It would solve at least part of the confusion in https://github.com/OpenNebula/packages/issues/123 if the source tarball the built man pages.

**Details**
 - Version: 5.10.2

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Currently man pages are included with build script in git, Also the source tarball published at https://downloads.opennebula.io/ includes a compiled version of the manpages.  Closing this now
