### ISSUE TITLE
Network is lost after making a save as template

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4284]
**Description**
When a normal user make a save as of a virtual machine with a virtual network and then instantiate it, the network is lost.

**To Reproduce**

1. Login to sunstone with an non oneadmin user
2. Use the "save as" button on a powered off VM to save it as a template
3. Check the template for a network - it's there
4. Instantiate the template
5. check the new VM for a network - it's not there

**Expected behavior**
Virtual network should be present after instantiation.

**Details**
 - Affected Component: Sunstone
 - Version: tested on 5.10.1, but probably in master it happens too.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tino PR to approve:
- ONE: https://github.com/OpenNebula/one/pull/4522
- Docs: https://github.com/OpenNebula/docs/pull/1057
