### ISSUE TITLE
broken live-migrate in Sunstone [one-5.10, development]

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4286]
**Description**
Live migrate failing with the following error:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**To Reproduce**
Live migrate a vm

**Expected behavior**
Live migrate dialog should appear

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**
I think the issue is introduced with 345b074c16
Because patching `_onShow()` function from `migrate.js` in the  `main.js` with `var vmTemplate = false;` to define the variable to false "mitigate" the issue:

```
  function _onShow(context) {
    this.datastoresTable.resetResourceTableSelect();
    this.hostsTable.resetResourceTableSelect();
    var vmTemplate = false;
    if (
      this.live &&
      vmTemplate &&
      vmTemplate.USER_TEMPLATE &&
      vmTemplate.USER_TEMPLATE.HYPERVISOR &&
      Config && Config.onedConf && Config.onedConf.VM_MAD && Array.isArray(Config.onedConf.VM_MAD)
    ) {
```

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
The issue was hint-ed in the browser's debug console:
```
ReferenceError: vmTemplate is not definedmigrate.js:116
    _onShow migrate.js:116
    _insert dialog.js:28
    jQuery 7
    open foundation.js:6517
    foundation foundation.js:285
    _show dialog.js:56
    call actions.js:158
    _runAction sunstone.js:993
    _setupButtons sunstone.js:579
    jQuery 2
```

**Comment by sbbarragan** [comment]
PRs to merge:
• one: #4291
• docs: OpenNebula/docs/pull/974
