### ISSUE TITLE
Service template recursively cloning 

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#4287]
**Description**

It is a useful feature to be able to clone OneFlow Service Templates. This needs to be a recursive action, since the VM Templates associated with the OneFlow Service Template, and, in turn, the images associated with those VM Templates, all need to be cloned.

**Use case**

Clone a service template for other users.

**Interface Changes**

OneFlow server, CLI and Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4289
- docs: https://github.com/OpenNebula/docs/pull/973
- tests: https://github.com/OpenNebula/development/pull/861

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4299 
- tests: OpenNebula/development#862
