### ISSUE TITLE
IPs displayed per page reset to default value after release

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4290]
**Description**
In Sunstone, when a user wants to release IP addresses, the user can set the number of items to display from 10 (by default) to 100. After clicking "release" for some IP(s), the display items per page is reset to 10 (the default value), even if the user had selected another value.

**Use case**
It is useful to keep the selected value by the user (i.e. 100) when you have a large number of IP addresses (i.e. 1000) on a network.

**Interface Changes**
Only Sunstone requires changes.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- One: https://github.com/OpenNebula/one/pull/4783
- Docs: https://github.com/OpenNebula/docs/pull/1137
