### ISSUE TITLE
Provision template with multiple playbooks

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4292]
**Description**
It might come handy if it's possible to stack Ansible configuration playbooks easily within the single provision template. Oneprovision should execute them one by one, and handle the failures. E.g.:

```
playbook:
- default
- vxlan-evpn
- ceph
```

To Be Decided - how to deal with template inheritance:
- overwrite
- merge and insert on the top
- merge and append at the bottom

**Use case**
Increase provision template flexibility.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4479
- docs: https://github.com/OpenNebula/docs/pull/1035
- tests: https://github.com/OpenNebula/development/pull/914
