### ISSUE TITLE
error compiling opennebula 5.10.2 using scons

### ISSUE THREAD

**Issue by vizonyc** [OpenNebula/one#4293]
**Description**
include/Image.h:583:18: note: forward declaration of 'class ImagePool'
  583 |     friend class ImagePool;
      |                  ^~~~~~~~~
vm_var_syntax.y: In function 'void get_network_attribute(VirtualMachine*, const string&, const string&, const string&, std::string&)':
vm_var_syntax.y:156:5: error: 'VirtualNetwork' was not declared in this scope; did you mean 'VirtualNetworkPool'?
vm_var_syntax.y:156:26: error: 'vn' was not declared in this scope; did you mean 'vm'?
vm_var_syntax.y:230:16: error: invalid use of incomplete type 'class VirtualNetworkPool'
In file included from vm_var_syntax.y:29,
                 from vm_var_syntax.y:40:
include/Nebula.h:45:7: note: forward declaration of 'class VirtualNetworkPool'
   45 | class VirtualNetworkPool;
      |       ^~~~~~~~~~~~~~~~~~
scons: *** [src/parsers/vm_var_syntax.o] Error 1

**To Reproduce**
git clone https://github.com/OpenNebula/one opennebula-5.10.2
cd opennebula-5.10.2
share/install_gems/install_gems
scons mysql=yes parsers=yes new-xmlrpc=yes svncterm=yes
  ( this errors out with the above description)
**Expected behavior**

**Details**
Not sure but maybe a typo
(**vm_var_syntax.y:156:26: error: 'vn' was not declared in this scope; did you mean 'vm'?**)

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by KawaiDesu** [comment]
Got similar error trying to build 5.12.0:
```
vm_var_syntax.y: In function 'void get_image_attribute(VirtualMachine*, const string&, const string&, const string&, std::string&)':
vm_var_syntax.y:125:16: error: invalid use of incomplete type 'class ImagePool'
In file included from include/VirtualMachine.h:26,
                 from include/VirtualMachinePool.h:21,
                 from vm_var_syntax.y:27,
                 from vm_var_syntax.y:40:
include/Image.h:583:18: note: forward declaration of 'class ImagePool'
  583 |     friend class ImagePool;
      |                  ^~~~~~~~~
vm_var_syntax.y: In function 'void get_network_attribute(VirtualMachine*, const string&, const string&, const string&, std::string&)':
vm_var_syntax.y:156:5: error: 'VirtualNetwork' was not declared in this scope; did you mean 'VirtualNetworkPool'?
vm_var_syntax.y:156:26: error: 'vn' was not declared in this scope; did you mean 'vm'?
vm_var_syntax.y:230:16: error: invalid use of incomplete type 'class VirtualNetworkPool'
In file included from vm_var_syntax.y:29,
                 from vm_var_syntax.y:40:
include/Nebula.h:45:7: note: forward declaration of 'class VirtualNetworkPool'
   45 | class VirtualNetworkPool;
      |       ^~~~~~~~~~~~~~~~~~
scons: *** [src/parsers/vm_var_syntax.o] Error 1
scons: building terminated because of errors.

```

Build config: `scons new_xmlrpc=yes mysql=no sqlite=yes sunstone=yes parsers=yes systemd=yes`

**Comment by paczerny** [comment]
The issues is the `parser=yes`. Unfortunately this parameter doesn't work. Do you really need to generate the parsers? The generated files are included in the repository.

**Comment by paczerny** [comment]
Duplicate #5098
