### ISSUE TITLE
Error creating scheduled periodic actions

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4300]
**Description**
The creation of a periodic scheduled VM action without end is failing with the following error:

```
[one.vm.update] Cannot update template. Error END_VALUE defined but not valid END_TYPE found
```

**To Reproduce**
Try to schedule a repeatable action, _snapshot-create_ for example:
* Select _snapshot-create_ from the actions list
* Tick the _Periodic_ checkbox
* Set (for example) Weekly, Monday
* Leave "Ends" radio button to _Never_
* Click _Add_

The above error is logged

**Expected behavior**
The VM action should be scheduled

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.10.2]

**Additional context**

The following details are logged in the _oned_ log:

```
Wed Mar  4 15:27:06 2020 [Z0][ReM][D]: Req:1360 UID:0 IP:127.0.0.1 one.vm.update invoked , 221, "INPUTS_ORDER = ""
LOGO = "images/logos/centos.png"
MEMORY_UNIT_COST = "MB"
SCHED_DS_REQUIREMENTS = "ID=\"100\" | ID=\"104\""
SCHED_REQUIREMENTS = "CLUSTER_ID=\"102\" | CLUSTER_ID=\"101\""
SCHED_ACTION = [
  END_TYPE = "",
  END_VALUE = "1",
  TIME = "1583317800",
  DAYS = "0",
  REPEAT = "",
  ACTION = "snapshot-create",
  ID = "0" ]
", 0
Wed Mar  4 15:27:06 2020 [Z0][ReM][E]: Req:1360 UID:0 one.vm.update result FAILURE [one.vm.update] Cannot update template. Error END_VALUE defined but not valid END_TYPE found
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @atodorov-storpool,

I think this is solved here: https://github.com/OpenNebula/one/issues/4380. If not, please reopen.
