### ISSUE TITLE
Problem with HOST_HOOK and migration KVM VMs to other host. LVM

### ISSUE THREAD

**Issue by perrfect** [OpenNebula/one#4301]
**Description**
Hi.
I have 2 KVM nodes on LVM. 
I've configured the HOST_HOOK, but VMs can't transfer other node.

**To Reproduce**
HOST_HOOK in the config file - /etc/one/oned.conf
```
HOST_HOOK = [
    NAME      = "error",
    ON        = "ERROR",
    COMMAND   = "ft/host_error.rb",
    ARGUMENTS = "$ID -m -p 1 -u",
    REMOTE    = "no" ]
```
 When one node is not available, starts up the hook and in logs:
```
Message received: LOG I 84 Command execution failed (exit code: 5): /var/lib/one/remotes/tm/fs_lvm/mv node1:/var/lib/one//datastores/121/84/disk.0 node2:/var/lib/one//datastores/121/84/disk.0 84 119
Message received: LOG E 84 mv: Command " set -ex -o pipefail
Message received: LOG I 84 if [ -b “/dev/vg-one-121/lv-one-84-0” ]; then
Message received: LOG I 84 sync
Message received: LOG I 84 sudo lvscan
Message received: LOG I 84 sudo lvchange -an “/dev/vg-one-121/lv-one-84-0”
Message received: LOG I 84 fi
Message received: LOG I 84
Message received: LOG I 84 rm -f “/var/lib/one/datastores/121/84/.host” || :" failed: ssh: connect to host node1 26: No route to host
Message received: LOG E 84 Error deactivating disk /var/lib/one/datastores/121/84/disk.0
Message received: TRANSFER FAILURE 84 Error deactivating disk /var/lib/one/datastores/121/84/disk.0
```

Or when only stop the service libvirtd on one node get the error:
```
Message received: LOG I 84 Command execution failed (exit code: 5): /var/lib/one/remotes/tm/fs_lvm/mv node1:/var/lib/one//datastores/121/84/disk.0 node2:/var/lib/one//datastores/121/84/disk.0 84 119
Message received: LOG E 84 mv: Command " set -ex -o pipefail
Message received: LOG I 84 if [ -b “/dev/vg-one-121/lv-one-84-0” ]; then
Message received: LOG I 84 sync
Message received: LOG I 84 sudo lvscan
Message received: LOG I 84 sudo lvchange -an “/dev/vg-one-121/lv-one-84-0”
Message received: LOG I 84 fi
Message received: LOG I 84
Message received: LOG I 84 rm -f “/var/lib/one/datastores/121/84/.host” || :" failed: Warning: Permanently added ‘[node1]:26,[10.2.2.19]:26’ (ECDSA) to the list of known hosts.
Message received: LOG I 84 + ‘[’ -b /dev/vg-one-121/lv-one-84-0 ‘]’
Message received: LOG I 84 + sync
Message received: LOG I 84 + sudo lvscan
Message received: LOG I 84 + sudo lvchange -an /dev/vg-one-121/lv-one-84-0
Message received: LOG I 84 Logical volume vg-one-121/lv-one-84-0 in use.
Message received: LOG E 84 Error deactivating disk /var/lib/one/datastores/121/84/disk.0
Message received: TRANSFER FAILURE 84 Error deactivating disk /var/lib/one/datastores/121/84/disk.0
```
**Expected behavior**
When one node is not available or the service libvirtd is stopped, VMs are moving to other host. 

**Details**
 - Affected Component: Sunstone, 2 KVM Nodes, Datastore on LVM
 - Hypervisor: KVM
 - Version:  OpenNebula 5.10.1

**Additional context**
Why is it happening? Why hook runs a command on a node which is not available or can’t deactivate lvm, when a service - libvirtd stopped?

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @perrfect,

It would be useful if you can provide more info about you environment:

   - How do you have setup LVM, are the 2 hosts accessing the same SAN?
   - Can you share the details of the VM, how many disks? Type (e.g. volatile)?
   - Can you send the configuration of the datastores images/system being use by the VM?

**Comment by perrfect** [comment]
> Hello @perrfect,
> 
> It would be useful if you can provide more info about you environment:
> 
>     * How do you have setup LVM, are the 2 hosts accessing the same SAN?
> 
>     * Can you share the details of the VM, how many disks? Type (e.g. volatile)?
> 
>     * Can you send the configuration of the datastores images/system being use by the VM?

Hi. Thank you for reply.
Yes, of course I can provide more information.
1. All my servers (2 nodes for KVM and frontend) have access to the same SAN:
```
mpathh (36d4ae520009b25ac000016ff5e55d282) dm-3 
size=294G features='2 pg_init_retries 50' hwhandler='1 rdac' wp=rw
mpathg (36d4ae520009b25ac000016fc5e55d268) dm-2 
size=100G features='2 pg_init_retries 50' hwhandler='1 rdac' wp=rw
```
And on one of a node i've created physical volumes:
```
pvcreate /dev/mapper/mpathh
pvcreate /dev/mapper/mpathg
```
Then created VGS:
vgcreate vg-one-121 /dev/mapper/mpathh
vgcreate vg-one-119 /dev/mapper/mpathg

Physical volumes and volume groups are on all nodes and frontend.
In the lvm configuration file i've only changed - use_lvmetad = 0, disabled the lvm2-lvmetad service and added the user oneadmin to the disk group.

Then I've created config for a image datastore - /etc/one/images-ds.conf on NFS:
```
NAME = production
DS_MAD = fs
TM_MAD = fs_lvm
DISK_TYPE = "BLOCK"
TYPE = IMAGE_DS
SAFE_DIRS="/var/tmp /tmp"
```
and config for SystemStorage:
```
NAME   = lvm_system
TM_MAD = fs_lvm
TYPE   = SYSTEM_DS
```
```
onedatastore create /etc/one/system-ds.conf
onedatastore create /etc/one/images-ds.conf
```

My storages look like:
  ID NAME  SIZE AVA CLUSTERS IMAGES TYPE DS      TM      STAT
 119 production    9G 44% 0             0 img  fs      fs_lvm  on  
 121 lvm_system  293.7G 100 0             0 sys  -       fs_lvm  on  
   2 files                 9G 44% 0             0 fil  fs      ssh     on  

After that, via web-interface, on a frontend-server i created 2 images:
Type: operating system image
Image mapping driver: qcow2
Upload: iso-file with Centos7

Type: operating system image
Image mapping driver: qcow2
Empty disk image: size 5G, format qcow2

Then created a template from those 2 disk  and created a VM, where installed Centos7 from the iso-disk to the empty disk.
When Centos7 was installed i shutdown my VM and created the template from the disk with installed Centos7.

Finally, I've created more then 4 VMs from my Template disk. VMs  have been created on two KVM-nodes. Successfully launched.

Then i've created a host hook in files - /etc/one/oned.conf, /usr/share/one/examples/host_hooks/error_hook

```
ARGUMENTS = "$TEMPLATE -m -p 5"
COMMAND   = "ft/host_error.rb"
NAME      = "host_error"
STATE     = "ERROR"
REMOTE    = "no"
RESOURCE  = HOST
TYPE      = state
```
`onehook create /usr/share/one/examples/host_hooks/error_hook`

And launched my tests. Result you can see above.
Please, help me, decided the problem

**Comment by perrfect** [comment]
And when a node comes back from offline I want to recover my VM, but it is impossible

```
Message received: LOG I 84 ExitCode: 0
Message received: LOG I 84 Successfully execute network driver operation: pre.
Message received: LOG I 84 Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/121/84/deployment.1' 'node1' 84 node1
 Message received: LOG I 84 error: Failed to create domain from /var/lib/one//datastores/121/84/deployment.1
Message received: LOG I 84 error: Cannot access storage file '/var/lib/one//datastores/121/84/disk.0': No such file or directory
Message received: LOG E 84 Could not create domain from /var/lib/one//datastores/121/84/deployment.1
Message received: LOG I 84 ExitCode: 255
Message received: LOG I 84 Failed to execute virtualization driver operation: deploy.
Message received: DEPLOY FAILURE 84 Could not create domain from /var/lib/one//datastores/121/84/deployment.1
```

**Comment by feldsam** [comment]
Hello, I think there is problem with datastore configuration. The transfer manager tries to do move from error node to the new node. This is not needed when you have shared storage.

Add `SHARED = YES` to system DS and make sure /var/lib/one/ directory is shared across all nodes and frontend. You can use NFS for this or clustered filesystem. This ensure, that you have deployment files available on all nodes.
