### ISSUE TITLE
KVM Node Installation 

### ISSUE THREAD

**Issue by harsxv** [OpenNebula/one#4307]
Hello, I just want to know where is the **Step 7.** at this docs? https://docs.opennebula.org/5.4/deployment/node_installation/kvm_node_installation.html

Is it really gone?

**Comment by rsmontero** [comment]
Yes there are two Steps 8. Thanks for the headsup

**Comment by harsxv** [comment]
Nice, thanks for your confimation.

**Comment by dann1** [comment]
There is step 7 in 5.8 and 5.10 docu,you can submit a PR for 5.4 and we will gladly review it.
