### ISSUE TITLE
Documentation recommends copying SSH private key.

### ISSUE THREAD

**Issue by FSMaxB** [OpenNebula/one#4312]
In https://github.com/OpenNebula/docs/blob/a9a7442c2c0ea64eabcdf359585800f25e342491/source/deployment/node_installation/kvm_node_installation.rst#step-4-configure-passwordless-ssh you recommend your users to distribute private SSH keys all around the datacenter.

I don't really understand the setup, so I'm not making a pull request. But surely there's a better way to achieve what you are trying to achieve, than copying the private key `id_rsa` around. (e.g. making a separate keypair on each node and then putting the public key portion in the appropriate `authorized_keys` files.

**Comment by kvaps** [comment]
Private key still needed to perform the live migration

**Comment by atodorov-storpool** [comment]
Related to #2152  ?

**Comment by ospalax** [comment]
Done, this was solved in [#2152](https://github.com/OpenNebula/one/issues/2152). Documentation for 5.12 was adjusted and no longer requires or recommends copying SSH privkeys.
