### ISSUE TITLE
Review OneFlow API documentation

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4317]
**Description**
Review OneFlow API documentation to add missing things.

**Additional context**
Documentation [link](http://docs.opennebula.org/5.10/integration/system_interfaces/appflow_api.html).

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- docs: https://github.com/OpenNebula/docs/pull/1079
