### ISSUE TITLE
 Sunstone does not allow to input leading `0` in Two Factor Token 

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4321]
**Description**
Sunstone does not allow to input leading `0` in Two Factor Token 
![image](https://user-images.githubusercontent.com/7556217/76085236-ebe93200-5fb1-11ea-8483-32e6d976f793.png)

**To Reproduce**
* Enable Two Factor Auth
* Try to type code starting with `0`

**Expected behavior**
Tokens started with `0` are working

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.2

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Also `000123` is not working

**Comment by kvaps** [comment]
Also `Invalid username or password` isn't correct error message if Two Factor Token is wrong

![image](https://user-images.githubusercontent.com/7556217/76085851-22737c80-5fb3-11ea-9569-9c203dff0f67.png)

**Comment by tinova** [comment]
Fixed as part of #962
