### ISSUE TITLE
Restrict access to TOPOLOGY attributes

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#4340]
**Description**
Restrict access to TOPOLOGY attributes to make sure users do not allocate huge amounts of vCPUs.

**Additional Context**
https://forum.opennebula.org/t/restrict-topology-attributes-by-deault/8149

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Yep, sorry, had no time for that

**Comment by christian7007** [comment]
Don't worry, thanks for pointing that out in the forum!

**Comment by vholer** [comment]
IMHO sockets / cores / threads are not harmful, unless you start to play with pinning. So I'm not sure if whole topology should be blacklisted, I would say probably not.

**Comment by christian7007** [comment]
You are right @vholer, I've updated my PR, now only `PIN_POLICY` and `HUGE_PAGES` are restricted.
