### ISSUE TITLE
error state of a VM not evaluated correctly

### ISSUE THREAD

**Issue by philfry** [OpenNebula/one#4344]
**Description**
The "crashed" state is not evaluated correctly by OpenNebula.
For example, I have this VM on which I provoked a kernel panic. Libvirt shows:
```
$ virsh list
 Id    Name                           State
----------------------------------------------------
 4     one-45                         crashed
```
The polling scripts recognize that state and return an error state (`STATE=e`)
```
$ ssh -n mykvmnode /var/tmp/one/im/run_probes kvm \
  /var/lib/one/datastores 4124 60 0 mykvmnode | sed -n '/^VM=/,/]/p'
VM=[
  ID=45,
  DEPLOY_ID=one-45,
  POLL="STATE=e CPU=0.0 MEMORY=264576" ]
```
Unfortunately, OpenNebula seems to be ignoring this state and returning `STATE=ACTIVE` and `LCM_STATE=UNKNOWN`:
```
$ onevm show 45 | head
VIRTUAL MACHINE 45 INFORMATION                                                 
ID                  : 45                 
NAME                : example       
USER                : oneadmin           
GROUP               : oneadmin           
STATE               : ACTIVE             
LCM_STATE           : UNKNOWN            
LOCK                : None               
RESCHED             : No                 
HOST                : mykvmhost
```
As far as I saw the correct states `STATE=FAILED` and `LCM_STATE=FAILURE` are commented out in `include/VirtualMachine.h`, `src/sunstone/public/app/opennebula/vm.js` and probably other files. Also it looks like the code for processing these states is missing.

Is there a reason for that? Or is it just not implemented yet?

**To Reproduce**
1. Apply https://github.com/OpenNebula/one/pull/4332 to enable crash detection
2. set crash action to `preserve`
3. fire up a vm
4. login into the vm and run `echo c > /proc/sysrq-trigger`

**Expected behavior**
The VM to be shown with an error state instead of an unknown state.

**Details**
 - Affected Component: core, sunstone
 - Hypervisor: kvm
 - Version: 5.10.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by philfry** [comment]
well… "bump", I guess.

**Comment by christian7007** [comment]
Hi @philfry,

Sorry for the late reply, have you tried this on an environment with version >= 5.12.0. The monitoring subsystem was re-designed for that version and it seems this is already mapped into the `FAILURE` state (https://github.com/OpenNebula/one-ee/blob/7f000b89ed3a5dae4877d22f9e761afc92d2b6ee/src/im_mad/remotes/lib/kvm.rb#L260).

**Comment by philfry** [comment]
Hi @christian7007, thanks for your reply.
Unfortunately, I cannot see that repo (one-ee? enterprise edition?), but I'll take a look whether or not the bug is still valid for 5.12.0.1.

**Comment by christian7007** [comment]
Sorry @philfry, here you have the link to the public repo: https://github.com/OpenNebula/one/blob/eb49ad2e6f8a90c1247cf34eda09a1ad89bc63ce/src/im_mad/remotes/lib/kvm.rb#L260

**Comment by rsmontero** [comment]
Seems it is already fixed. We'll reopen if needed

THANKS for your feedback!
