### ISSUE TITLE
VM removed from SG having nics with that SG

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4354]
**Description**
When a VM has 2 NIC attached to the same vnet ( asocciated to a SG ), when detaching one of these nics the VM is removed from the associated SGs, having another NIC attached to the same vnet and with the same SG.

**To Reproduce**
Instantiate a VM
Create a SG and associate this SG to a vnet
Attach two NICS to that vnet
Detach one of this NICs, so the VM will have one nic more attached to the vnet.
type: onesecgroup show <sg_id> and that the VM ID is not showing in the list "VIRTUAL MACHINES" list:

SECURITY GROUP 153 INFORMATION
ID             : 153
NAME           : NSX-V_sg_1584032642
USER           : oneadmin
GROUP          : oneadmin
PERMISSIONS
OWNER          : um-
GROUP          : ---
OTHER          : ---

VIRTUAL MACHINES
UPDATED        :
OUTDATED       :
ERROR          :

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PR for merge https://github.com/OpenNebula/one/pull/4475, merge to master and to one-5.10 (after code freeze)

**Comment by paczerny** [comment]
Here's a doc PR https://github.com/OpenNebula/docs/pull/1032, if we want to include it in 5.10.4 release
