### ISSUE TITLE
Hooks: $ID variable is not working anymore

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4355]
**Description**
Previously we were using a lot of hooks based on simple action, eg:

```
NAME      = report_done
TYPE      = state
COMMAND   = report-done.sh
ARGUMENTS = "$ID"
ON        = CUSTOM
RESOURCE  = VM
STATE     = DONE
LCM_STATE = LCM_INIT
``` 

This hook should call `report-done.sh 123` where `123` is virtual machine id.

Now we forced to use `$TEMPLATE` instead and parse object ID from it manually

**To Reproduce**

* create hook `/var/lib/one/remotes/hooks/report-done.sh`:
```
#!/bin/sh
echo "ID=$1" >> /tmp/123
```
* configure hook template in opennebula
* try run hook
* check `/tmp/123`

**Expected behavior**
ID will be written into file

**Details**
 - Affected Component: hem
 - Hypervisor: kvm
 - Version: 5.10.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @kvaps,

Yes $ID is not supported anymore, you can use $API or $TEMPLATE (depending on the type of hook you are using) and retrieve it from it. Please check the upgrade guide and the documentation to find more info:

   - http://docs.opennebula.org/5.10/intro_release_notes/upgrades/upgrade_58.html#update-your-hooks
   - http://docs.opennebula.org/5.10/integration/infrastructure_integration/hooks.html

Any feedback is very welcome!
