### ISSUE TITLE
Sched logging to stdout is not working

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4359]
**Description**
Sched is stops writing any logs after successful startup

**To Reproduce**
Run sched daemon with:
```
LOG = [
  DEBUG_LEVEL = 3,
  SYSTEM = "std"
]
```

**Actual behavior**

No logs after:
```
Fri Mar 13 13:55:56 2020 [Z0][SCHED][I]: Init Scheduler Log system
Fri Mar 13 13:55:56 2020 [Z0][SCHED][I]: Starting Scheduler Daemon
----------------------------------------
     Scheduler Configuration File       
----------------------------------------
DEFAULT_DS_SCHED=POLICY=1
DEFAULT_NIC_SCHED=POLICY=1
DEFAULT_SCHED=POLICY=1
DIFFERENT_VNETS=YES
LIVE_RESCHEDS=0
LOG=DEBUG_LEVEL=3,SYSTEM=std
MAX_DISPATCH=30
MAX_HOST=1
MAX_VM=5000
MEMORY_SYSTEM_DS_SCALE=0
MESSAGE_SIZE=1073741824
ONE_XMLRPC=http://opennebula-oned:2633/RPC2
SCHED_INTERVAL=30
TIMEOUT=60
----------------------------------------
Fri Mar 13 13:55:56 2020 [Z0][SCHED][I]: XML-RPC client using 1073741824 bytes for response buffer.
Fri Mar 13 13:55:56 2020 [Z0][SCHED][I]: oned successfully contacted.
Fri Mar 13 13:55:56 2020 [Z0][SCHED][I]: Configuring scheduler for Zone ID: 0
```

**Expected behavior**
Sched continue logging all the acrions into stdout

**Details**
 - Affected Component: oned, sched
 - Hypervisor: KVM
 - Version: 5.10.3

**Additional context**
Oned is having the same bug, if I do:
```
ln -sf /dev/stdout /var/log/one/oned.log
```
see an **Additional Context** from https://github.com/OpenNebula/one/issues/3900 for more details

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Fix as per  c97f54281dc89a4164df9de98a8d9aa18bfd885d
