### ISSUE TITLE
Disable numa tab in Sunstone is not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4369]
**Description**
When setting these values:

```
Template.numa: false
numa: false
```
in `user.yaml` the numa tab is still visible in the template creation dialog.

**To Reproduce**
Set those values to false, restart Sunstone service and go to the template creation dialog.

**Expected behavior**
The numa tab should de disabled in the value is set to false.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10 and development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Duplicated https://github.com/OpenNebula/one/issues/4323
