### ISSUE TITLE
NIC aliases are not working with NETWORK_SELECT = "NO"

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4378]
**Description**

The contextualisation information of NIC aliases is missing when "Do not allow to modify network configuration" option (NETWORK_SELECT = "NO") is checked in general tab of sunstone template wizard.

**To Reproduce**
Select the option, add an alias to the template and instantiate it.

**Expected behavior**
NIC_ALIAS context should be generated.

**Details**
 - Affected Component: Sunstone
 - Version: 5.8, 5.10 and development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4379
- docs: https://github.com/OpenNebula/docs/pull/1004
