### ISSUE TITLE
Sunstone does not send END_TYPE properly when creating sched actions

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4380]
**Description**
When a new scheduled action is created Sunstone is not sending the END_TYPE value properly which makes the create process fails.

**To Reproduce**
Try to create a scheduled action as in the screenshot:
![Definition](https://user-images.githubusercontent.com/33811723/76983000-fa820280-693c-11ea-8e34-71ee15559c47.png)

**Expected behavior**
The scheduled action should be created.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10.3

**Additional context**
Here is the output from the browser console:
```
↵SCHED_ACTION = [↵  END_TYPE = "",↵  END_VALUE = "1",↵  TIME = "1584531000",↵  DAYS = "6",↵  REPEAT = "",↵  ACTION = "reboot",↵  ID = "0" ]
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4405 
- docs: OpenNebula/docs/pull/1008

**Comment by tinova** [comment]
Reopening to add a test
