### ISSUE TITLE
Error parsing host with NSX-T enabled

### ISSUE THREAD

**Issue by Lillecarl** [OpenNebula/one#4381]
**Description**
Error parsing host 0 information: syntax error, unexpected VARIABLE, expecting EQUAL at line 19, columns 381:385. Monitoring information:
---redacted----
L19 NSX_STATUS = OK
L20 NSX_TRANSPORT_ZONES = [tz-host-vlan="c5796483-c5d1-49d4-8669-73dbcfd378dc",tz-overlay="aef17969-e1e8-47dc-b6f8-18e9fcef385b"]
I don't know if this value is related at all, and following the code wasn't what I'm used to with cmake and QtCreator IDE superpowers, but it seemed like i ended up in some autogenerated parsing file that i presume is generated somehow to relate to host.xsd.

**To Reproduce**
VMware vCenter 6.7, NSX-T 2.5.1

**Expected behavior**
Monitoring shouldn't fail parsing the output.

**Details**
 - Affected Component: "oned"
 - Hypervisor: VMware 6.7, NSX-T 2.5.1
 - Version: Mix, sunstone is still on 5.10.12 because i can't get it to build even if following PKGBUILD precicely, npm is such a shit show. "oned" built from 5.10.3 release tag

**Additional context**
I tried adding this line
<xs:element name="NSX_TRANSPORT_ZONES" minOccurs="0" maxOccurs="unbounded"/>
just under this line
<xs:element name="VCENTER_RESOURCE_POOL_INFO" minOccurs="0" maxOccurs="unbounded"/>
without any success.
I used scons new_xmlrpc=yes mysql=yes parsers=yes to build 5.10.3 oned.

It's only once i enter the NSX-T password into sunstone that this error occurs and the "host" gets stuck on MONITORING_INIT.

I'm willing to test patches or git branches, I've been planning to evaluate ONE as VMware vCloud isn't very flexible. And in combination with NSX-T promotes really shitty networking with their builtin routers.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mouyaq** [comment]
Dash is not supported in Transport zone names.

http://docs.opennebula.io/5.10/deployment/vmware_infrastructure_setup/nsx_setup.html

Try to change the names with underscores for example

**Comment by Lillecarl** [comment]
@mouyaq I'm sorry, I've read through the docs regarding this a gazillion times by now but somehow that just flew way past me.

Changing the dashes to underscores made the "host" go into monitored state with nsx-t enabled.

Anyhow, now anyone else with the same error should be able to Google the error and find it here :)

**Comment by mouyaq** [comment]
Thanks for your feedback. 
Let me reopen this issue to evaluate the issue for future releases.
