### ISSUE TITLE
Sunstone avoid mountpoint on tmpdir 

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4384]
**Description**
In some cases when `/var/tmp` is mounted from nfs server sunstone silently avoiding it's usage.

Eg. if `/var/tmp` mounted it is trying to use `/tmp` even if `/var/tmp` is writable for oneadmin user, despite the fact that `/var/tmp` is described in configuration.

If I try to mount same share on `/tmp`, it will fail with the next trace:

```
/usr/lib/ruby/2.5.0/tmpdir.rb:35:in `tmpdir': could not find a temporary directory (ArgumentError)
	from /usr/lib/ruby/2.5.0/tmpdir.rb:106:in `tmpdir'
	from /usr/lib/ruby/2.5.0/tmpdir.rb:113:in `create'
	from /usr/lib/ruby/2.5.0/tempfile.rb:131:in `initialize'
	from /usr/share/one/gems-dist/gems/thin-1.7.2/lib/thin/request.rb:156:in `new'
	from /usr/share/one/gems-dist/gems/thin-1.7.2/lib/thin/request.rb:156:in `move_body_to_tempfile'
	from /usr/share/one/gems-dist/gems/thin-1.7.2/lib/thin/request.rb:87:in `parse'
	from /usr/share/one/gems-dist/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	from /usr/share/one/gems-dist/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	from /usr/share/one/gems-dist/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	from /usr/share/one/gems-dist/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	from /usr/share/one/gems-dist/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	from /usr/share/one/gems-dist/gems/rack-2.0.7/lib/rack/handler/thin.rb:22:in `run'
	from /usr/share/one/gems-dist/gems/sinatra-2.0.7/lib/sinatra/base.rb:1525:in `start_server'
	from /usr/share/one/gems-dist/gems/sinatra-2.0.7/lib/sinatra/base.rb:1459:in `run!'
	from /usr/lib/one/sunstone/sunstone-server.rb:990:in `<main>'
```

Repeat, both `/var/tmp` and `/tmp` are accesible for the sunstone, they are just located on NFS server:
```bash
# cat /proc/mounts | grep /var/tmp
10.96.113.129:/export/pvc-307c7fe3-ea0a-42b8-a0cd-ae145f155a25/tmp /var/tmp nfs rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.96.113.129,mountvers=3,mountport=20048,mountproto=udp,local_lock=none,addr=10.96.113.129 0 0
```

**To Reproduce**
* Mount nfs share on `/var/tmp`
* Restart sunstone
* Try to upload  any image via sunstone

**Expected behavior**
Image is uploaded

**Actual behavior**
* Sunstone is placing image into `/tmp` instead `/var/tmp`
* oned throws an error:
  ```
  Cannot parse image SIZE: File not found
  ```

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.3

**Additional context**
Looks like connected issue:
https://stackoverflow.com/questions/21117878/ruby-could-not-find-a-temporary-directory

Current workaround is to create another directory inside `/var/tmp`, eg. `/var/tmp/image` and update the sunstone-server.config:
```yaml
:tmpdir: /var/tmp/images
```

now it will works

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Docs (master, one-6.2-maintenance & one-6.2): https://github.com/OpenNebula/docs/pull/2051
- Docs (one-5.12-maintenance & one-5.2): https://github.com/OpenNebula/docs/pull/2050
