### ISSUE TITLE
NIC attributes of VM Template not kept on VM instantiation if NETWORK_MODE auto set

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4387]
**Description**
When instantiating a VM from a template with NETWORK_MODE auto, the NIC attributes -such as VIRTIO_QUEUES- are lost.

**To Reproduce**
Set `INHERIT_VNET_ATTR = "VIRTIO_QUEUES"` variable in `oned.conf` (requires OpenNebula service restart).

Define a virtual network as follows:

```
BRIDGE="br1"
BRIDGE_TYPE="linux"
GATEWAY="10.10.100.1"
NETWORK_ADDRESS="10.10.100.0"
NETWORK_MASK="255.255.255.0"
PHYDEV=""
SECURITY_GROUPS="0"
VIRTIO_QUEUES="8"
VN_MAD="bridge"
```

And the following VM template with VIRTIO_QUEUES set to $NIC[VIRTIO_QUEUES] in CONTEXT as follows:

```
CONTEXT=[
  NETWORK="YES",
  SSH_PUBLIC_KEY="$USER[SSH_PUBLIC_KEY]",
  VIRTIO_QUEUES="$NIC[VIRTIO_QUEUES]" ]
CPU="1"
DISK=[
  IMAGE="Alpine Linux 3.11",
  IMAGE_UNAME="oneadmin" ]
GRAPHICS=[
  LISTEN="0.0.0.0",
  TYPE="VNC" ]
MEMORY="128"
MEMORY_UNIT_COST="MB"
NIC=[
  NETWORK_MODE="auto" ]
NIC_DEFAULT=[
  MODEL="virtio" ]
OS=[
  BOOT="" 
```

On VM template instantiation, the VIRTIO_QUEUES value in CONTEXT is empty string:

```
$ onevm show 69
...
VIRTUAL MACHINE TEMPLATE
...                                                       
CONTEXT=[
  DISK_ID="1",
  ETH0_CONTEXT_FORCE_IPV4="",
  ETH0_DNS="",
  ETH0_EXTERNAL="",
  ETH0_GATEWAY="10.10.100.1",
  ETH0_GATEWAY6="",
  ETH0_IP="10.0.100.50",
...
  VIRTIO_QUEUES="" ] <---- EMPTY
...
VMID="69"
...
```

**Expected behavior**
On VM template instantiation, the VIRTIO_QUEUES value in CONTEXT should be set to the actual $NIC[VIRTIO_QUEUES] value:

```
$ onevm show 69
...
VIRTUAL MACHINE TEMPLATE
...                                                       
CONTEXT=[
  DISK_ID="1",
  ETH0_CONTEXT_FORCE_IPV4="",
  ETH0_DNS="",
  ETH0_EXTERNAL="",
  ETH0_GATEWAY="10.10.100.1",
  ETH0_GATEWAY6="",
  ETH0_IP="10.0.100.50",
...
  VIRTIO_QUEUES="8" ] <---- ACTUAL VALUE
...
VMID="69"
...
```

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: 5.10.1 and above]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rdiaz-on** [comment]
Real issue identified in https://github.com/OpenNebula/one/issues/4409
