### ISSUE TITLE
Problem with migrate VMs to another node in a cluster

### ISSUE THREAD

**Issue by perrfect** [OpenNebula/one#4390]
**Description**
Problem with migrate VMs to another node in a cluster.

**To Reproduce**
3 kvm nodes in a cluster.
Testing a host_hook. 
When one of nodes is shutdown, a host_hook starts and VMs are starting to migrate to another node, but the process finishes with the error:
```
rm -f "/var/lib/one/datastores/129/159/.host" || :" failed: ssh: connect to host node1 port 22: No route to host
```
The problem is solved by replacement `ssh_exec_and_log` to `ssh_exec_and_log_no_error` in the line `exclusive "${LOCK}" 120 ssh_exec_and_log "${SRC_HOST}" "${CMD}" \`  in the file `/var/lib/one/remotes/tm/fs_lvm/mv`

**Expected behavior**
VMs successfully migrate to another host

**Details**
 - Affected Component: Sunstone, Nodes
 - Hypervisor: KVM
 - Version: 5.10.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
It seem more a configuration issue. Works for me
