### ISSUE TITLE
Sunstone under Apache Passenger and SELinux doesn't detect running VNC proxy

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4392]
**Description**

As observed on 
- CentOS 8 
- Sunstone under Apache via Passenger (from EPEL)
- **enforcing** SELinux

Sunstone refuses to connect to the noVNC as it's not able to detect locally running noVNC due to restrictions introduced by SELinux.

![image](https://user-images.githubusercontent.com/414850/77202055-eb8e8200-6aed-11ea-8b60-1587a2ff84a5.png)

Following issues can be experienced:

- stat on the lock file doesn't work:
https://github.com/OpenNebula/one/blob/master/src/sunstone/OpenNebulaVNC.rb#L332
as Apache is only able to read the directory, not stat individual files there

```
# ls -la /run/lock/one/
-?????????? ? ?        ?         ?            ? .novnc.lock
-?????????? ? ?        ?         ?            ? one
```
Process running under SELinux context type `httpd_t` can't manipulate with files of type `var_lock_t`.

- even if stat above would work, the read wouldn't pass
https://github.com/OpenNebula/one/blob/45899f763d442d4087be71712506933057da4989/src/sunstone/OpenNebulaVNC.rb#L333

- even if read would pass, process would not be seen in the process list
https://github.com/OpenNebula/one/blob/45899f763d442d4087be71712506933057da4989/src/sunstone/OpenNebulaVNC.rb#L335
as `ps` command shows only Apache related processes (again those with type `httpd_t`).

**Solution Proposal**

For web requests (`def proxy`), have a simplified checking for running VNC
just based on the existence lock file, but detect lock by listing whole directory instead of statting individual file (as stat will fail `Errno::ENOENT - No such file or directory @ rb_file_s_stat - /var/lock/one/.novnc.lock`).

E.g., having this simplified test

```ruby
    def is_lockfile?
        dn = File.dirname(@lock_file)
        bn = File.basename(@lock_file)

        # Due to restrictions which doesn't allow to stat the lock file
        # when Sunstone is running under Apache with SELinux enabled,
        # as a workaround we read content of the whole lock directory.
        begin
            Dir.entries(dn).include?(bn)
        rescue StandardError
            false
        end
    end
```

and use this instead in proxy method:

```ruby
    def proxy(vm_resource)
        # Check configurations and VM attributes
        unless is_lockfile?
            return error(400, "VNC Proxy is not running")
        end
```

This simple workaround should be enough, as we pretty much rely on service manager that it cleans the locks in case of service stop or failure.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10, master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
I'm not using passanger, but I also forced to use some dirty workaround to run novnc on separated container in Kube-OpenNebula
https://github.com/kvaps/kube-opennebula/blob/master/helm/opennebula/templates/sunstone-deployment.yaml#L41-L44

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4432 
- docs: OpenNebula/docs/pull/1014
