### ISSUE TITLE
Instancing vNet template address range edit

### ISSUE THREAD

**Issue by IowaOrganics** [OpenNebula/one#4393]
**Description**
When "-vnets-templates-tab" is commented out in the sunstone view yaml configuration file, the "+ Address Range" button in the "Instantiate Virtual Network" wizard does not open a dialog.

**To Reproduce**
Edit a sunstone view yaml file like "user" and comment "-vnets-templates-tab" in the "enabled_tabs" section and restart opennebula-sunstone service. Then in sunstone, open the Virtual Networks tab and instantiate a vnet, select a template and then add an Address Range. The +Address Range button only functions when the "-vnets-templates-tab" is enabled, even though the wizard does not exit to change tabs to "Network Templates".

**Expected behavior**
The "New Address Range" dialog in the "Instantiate Virtual Network" wizard opens normally when  "-vnets-templates-tab" is commented out.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10.1

**Additional context**
This is part of a broader effort to limit what a group admin can view in a multi-tenant use case. Instancing a Virtual Machine without the templates tab enabled functions as expected.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4398 
- docs: OpenNebula/docs/pull/1007
