### ISSUE TITLE
SCHED Cannot schedule VM, there is no suitable host

### ISSUE THREAD

**Issue by bashsiz** [OpenNebula/one#4402]
**Description**
Scheduler can not choose host to deploy VM.

**To Reproduce**
I do these steps to create VM
1. create a group with quota
2. create a user assign to group created in 1 (The user has no quota for itself)
3. a cluster with all available hosts, VNets, Datastores (default) CLUSTER_ID=0
4. create a datastore assign to group created in 1
5. create an image OS type assign to group created in 1 in datastore created in 4
6. create VM-Template with following scheduling

> SCHED_DS_RANK = "FREE_MB"
SCHED_RANK = "FREE_CPU"
SCHED_REQUIREMENTS = "CLUSTER_ID=\"0\""

But when i want to create a VM with the user created in 2 the sched log is like following

> Tue Mar 24 12:35:56 2020 [Z0][VM][D]: Found 1 pending/rescheduling VMs.
Tue Mar 24 12:35:56 2020 [Z0][HOST][D]: Discovered 34 enabled hosts.
Tue Mar 24 12:35:56 2020 [Z0][VM][D]: VMs in VMGroups:
Tue Mar 24 12:35:56 2020 [Z0][VNET][D]: Discovered 5 vnets.
Tue Mar 24 12:35:56 2020 [Z0][SCHED][D]: Match-making results for VM 1401:
	Cannot schedule VM, there is no suitable host.
Tue Mar 24 12:35:56 2020 [Z0][SCHED][D]: Dispatching VMs to hosts:
	VMID	Priority	Host	System DS

**Expected behavior**
I really expect the opennebula choose one available hosts to deploy the VM

**Details**
 - Affected Component: Scheduler and Storage
 - Hypervisor: KVM
 - Version: OpenNebula 5.10.1

**Additional context**
The sched.conf is like

> DEFAULT_SCHED = [
    policy = 1
]
DEFAULT_DS_SCHED = [
   policy = 1
]
DEFAULT_NIC_SCHED = [
   policy = 1
]

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This is most probably you need to review VM resource requests are compatible with your configuration. Increase the scheduler debug level to get more information.

**Comment by bashsiz** [comment]
Thank you for your reply

For your information the scale of our opennebula
Hosts: 35
Active VM:  369

The VM resource is 
CPU: 4 VCPU: 4
Memory: 4G
Storage: 8 GB
And i am sure that we have enough resource on all of our hosts

**NOTE:** I changed the loglevel in sched.conf to 5 but there is no difference in logs it also shows me the same log like level 3

> LOG = [
  system      = "file",
  debug_level = 5
]

**NOTE:** When i want to deploy on template with admin user and admin area there is no problem and the VM's created successfully but when i want create the VM with created user in user view the problem happens

**Comment by rsmontero** [comment]
You may need to restart the scheduler to the changes to take effect. oneadmin vs user problems are usually related to group permission/ownership. In terms of hosts or system ds.

**Comment by bashsiz** [comment]
I restarted the scheduler (opennebula service) after changing the loglevel, but there was no difference in log level .
And about the permissions and ownership i want to inform you that 

- the group has permission on all hosts 

- datastore(system) are included into cluster(default)

- the image has been used by VM template, is stored on **default** datastore

- other users have use permission on both datastores (default & system) 

- the image and user are in same group

- the image has **use** permission for members in same group

I read all the documents but actually i do not understand where is my mistake that the admin user can create VM with VM-Template but the regular user who is owner of the VM-Template can not create the VM.
I think it is related to datastore but i can not t-shoot more.

**Comment by feldsam** [comment]
What type of permissions user and group has on host and datastore? USE or MANAGE ACL?

**Comment by bashsiz** [comment]
Thank you feldsam for you reply
I gave full permission for all data stores to my group (Grp_Test_Cuota) but there was no affect
and again i see the same error in sched.log

![image](https://user-images.githubusercontent.com/19620677/79202183-75600f80-7e4e-11ea-847e-ed993fc76d51.png)

**Comment by feldsam** [comment]
but you don't have any permissions for Hosts for your group

**Comment by bashsiz** [comment]
OMG
Thank you dude very much
This resolve my issue
I had to read more about it
The issue has been resolved

**Comment by feldsam** [comment]
Great to hear :)
