### ISSUE TITLE
Be able to change min_vms in flow service

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4403]
**Description**
It would be very convenient to be able to kill random VM's in each service role and have them automatically be replaced by leveraging min_vms.

**Use case**
Be able to update a running service role information, this is very useful in some situations.

**Interface Changes**
OneFlow server.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Related with #4912
