### ISSUE TITLE
User can increase his privileges to manage VMs

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4416]
**Description**
User can specify:

```
VM_USE_OPERATIONS  = "migrate, delete, recover, retry, deploy, resched, undeploy, hold, release, stop, suspend, resume, reboot, poweroff, disk-attach, nic-attach, disk-snapshot, terminate, disk-resize, snapshot, updateconf, rename, resize, update, disk-saveas"
```

In his template, and perform dangerous operations on his VMs if he have no any admin permissions.

**To Reproduce**
* Login as user
* Update your user template, specify:
  ```
  VM_USE_OPERATIONS  = "migrate, delete, recover, retry, deploy, resched, undeploy, hold, release, stop, suspend, resume, reboot, poweroff, disk-attach, nic-attach, disk-snapshot, terminate, disk-resize, snapshot, updateconf, rename, resize, update, disk-saveas"
  ```
* Remove Admin and Manage permissions from any VM
* Try to perform Admin or Manage operations for the VM

**Expected behavior**
User does not allow to edit attributes specified in USER_RESTRICTED_ATTR

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 5.10.3

**Additional context**
See https://github.com/OpenNebula/one/issues/1357

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PR for merge https://github.com/OpenNebula/one/pull/4433, to one-5.10 and master

Will update change log in documentation with related issue #4417

**Comment by kvaps** [comment]
ref https://github.com/OpenNebula/one/issues/1357
