### ISSUE TITLE
Potencial DoS by specifying wrong VM_*_OPERATIONS variable

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4417]
**Description**
OpenNebula becomes to non-operable state if `VM_USE_OPERATIONS` `VM_USE_OPERATIONS` or `VM_ADMIN_OPERATIONS` variables specified wrong.

**To Reproduce**

*As unprivileged user:*

```bash
EDITOR='echo " VM_USE_OPERATIONS=sssss" >>' oneuser update 3456
```

```bash
oneuser show 3456
[one.user.info] Error getting user [3456]
```

Afterwards user can't login and perform any action, admins can't show or update this user.

*As admin:*

If someone with admin privileges will assign the same variable to `oneadmin` account the whole frontend will fall, eg.

```bash
EDITOR='echo " VM_USE_OPERATIONS=sssss" >>' oneuser update 0
```
is enough to stop the whole cloud

**Expected behavior**
* User restricted to edit `VM_*_OPERATIONS` (see #4416 and #1357)
* Admin can see and update user and group objects after this destructive change
* Specified variables `VM_*_OPERATIONS` does make any effect if specified for `oneadmin` or someone in `oneadmin` group.

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 5.10.3

**Additional context**
Recovery action is:
```bash
EDITOR='sed -i '/VM_USE_OPERATIONS/d' ' onedb update-body user --id 3456
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge:
* one: https://github.com/OpenNebula/one/pull/4438 to one-5.10 and master
* development: https://github.com/OpenNebula/development/pull/902 to one-5.10 and master
* docs: https://github.com/OpenNebula/docs/pull/1017 to one-5.10-maintanance

Note:
> Specified variables VM_*_OPERATIONS does make any effect if specified for oneadmin or someone in oneadmin group.

  * This was not implemented. The admin should be able to do anything regardless the VM_*_OPERATIONS
