### ISSUE TITLE
No open tab Role in Service

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#4428]
**Description**
When browsing services you can no longer select and manually scale or expand the Role to see all

**To Reproduce**
instanciate service, go to "service" menu . select a service, open tab Role and select role.

**Expected behavior**
display role information

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
Resolved in the following PRs:
- https://github.com/OpenNebula/one/pull/4421
- https://github.com/OpenNebula/one/pull/4427

**Comment by tinova** [comment]
Doc:  https://github.com/OpenNebula/docs/pull/1010
