### ISSUE TITLE
Sunstone vms-tab infinite waiting loop if NIC_ALIAS attached

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4448]
**Description**
If a NIC_ALIAS is attached to a VM, the vms-tab for corresponding to that VM keeps in an infinite waiting loop.

**To Reproduce**
Instantiate a VM, and attach a NIC_ALIAS.

When clicking on the VM the following error is obtained:

```
TypeError: element.TEMPLATE.NIC_ALIAS.find is not a function vm.js:807
    groupByIpsStr vm.js:807
    forEach self-hosted:235
    groupByIpsStr vm.js:806
    reduce self-hosted:303
    groupByIpsStr vm.js:800
    ipsStr vm.js:787
    _elementArray datatable-common.js:219
    _elementArray datatable.js:124
    _updateElement tab-datatable.js:708
    callback actions.js:38
    success action.js:317
    jQuery 4
```
Screenshot:

![sunstone_vmtabs_nicalias_bug](https://user-images.githubusercontent.com/33811723/77944088-9c4f0b00-72be-11ea-9638-7a6713699c57.png)

**Expected behavior**
The VM information should be displayed.

**Details**
 - Affected Component: Sunstone
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PR's:
- one: #4450
