### ISSUE TITLE
Add support in Sunstone for adding Security Groups to Virtual Networks

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4453]
**Description**
Currently there is no support for adding a Security Group to a Virtual Network from Sunstone when updating a Virtual Network.

**Use case**
This use case is similar to the one for `+Add Range` in `Addresses` Tab when updating a Virtual Network. Sunstone should have a `+Security Group` option in `Security` tab to add a Security Group when updating a Virtual Network.

**Interface Changes**
Changes in Sunstone required.

As it happens with `Addresses` tab:
![image](https://user-images.githubusercontent.com/33811723/78014630-81c17400-7348-11ea-88ac-b3787be2d8a8.png)

Something similar should be placed in `Security` Tab:
![image](https://user-images.githubusercontent.com/33811723/78014780-b8978a00-7348-11ea-99d5-6e5d868053e3.png)

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- One: https://github.com/OpenNebula/one/pull/4747
- Docs: https://github.com/OpenNebula/docs/pull/1122
- Dev: https://github.com/OpenNebula/development/pull/982
