### ISSUE TITLE
Add support for RDP in alias interfaces.

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4458]
**Description**
Add RDP support in Sunstone for alias interfaces.

**Use case**
Connect to a VM using an address configured as alias via RDP. 

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs:
- one: #4460

**Comment by tinova** [comment]
thanks!

we need a test for this.
