### ISSUE TITLE
Add recover delete operation in OneFlow

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4468]
**Description**
Add the option `--delete` to recover operation in OneFlow.

**Use case**
Some times the current recover might no be enough and it might be useful to delete the current service and its VMs.

**Interface Changes**
OneFlow server, CLI and Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4472
- docs: https://github.com/OpenNebula/docs/pull/1028
- tests: https://github.com/OpenNebula/development/pull/911
