### ISSUE TITLE
Preparing vCPU for numa and pinning support for vcenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4474]
**Description**
Preparing for future numa and pinning support for vcenter, it is necessary to change the vCPU attribute assignment, which currently corresponds to the number of sockets in the VM, to number of cores, like KVM does.

**Use case**
Change required to maintain consistency between KVM and vcenter hosts

**Interface Changes**
There is no interface changes, only the assignment value into the rbvmomi API for vcenter.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/4614

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one/pull/4658
- Docs:  https://github.com/OpenNebula/docs/pull/1098
