### ISSUE TITLE
Remove DONE services from services tab in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4487]
**Description**
Service should disappear in Sunstone when they are deleted. Should be the same behavior than for VMs.

**To Reproduce**

1. Instantiate a service
2. terminate/delete the service
3. VM will be terminated
4. oneflow list -> service not available anymore
5. Service still visible in Sunstone with "DONE" state

**Expected behavior**
List shouldn't have the service.

**Details**
 - Affected Component: Sunstone
 - Version: development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4513
- docs: OpenNebula/docs/pull/1045
