### ISSUE TITLE
Service role terminate action is not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4491]
**Description**
When a role is terminated, the server is returning an error.

**To Reproduce**
Try to terminate a role.

**Expected behavior**
The VMs in the role should be terminated and the role information should be updated properly.

**Details**
 - Affected Component: OneFlow
 - Version: development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4492
- tests: https://github.com/OpenNebula/development/pull/916
