### ISSUE TITLE
Support for LXD 4.0

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#4499]
**Description**
LXD 4 [has been released](https://discuss.linuxcontainers.org/t/lxd-4-0-lts-has-been-released/7231). Being an LTS version it should be supported by OpenNebula with at least the same level of support as LXD 3. 

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by gu1ll0me** [comment]
Is this issue was closed because LXD 4.0 is now supported with OpenNebula 6.0?
