### ISSUE TITLE
Sunstone remove vm_template_contents when updating service template

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4500]
**Description**
Update of a Service template causes our custom "vm_template_contents" to be reverted to the auto-generated contents. We use this field to specify a NIC_ALIAS for the VM, which can't be done using the UI. When the Service Template is saved after an update, the field gets reset to have the two NICs from the two networks. 

**To Reproduce**
1. Create a new OneFlow service template
2. Make changes to the "vm_template_contents" for example:
```
{
"name": "Copy of ReuschATest",
"deployment": "straight",
"description": "",
"roles": [
{
"name": "A",
"cardinality": 1,
"vm_template": 3,
"vm_template_contents": "NIC = [\n NETWORK_ID = \"$private\", \n NAME = \"private\" ]\nNIC_ALIAS = [\n PARENT = \"private\", \n NETWORK_ID = \"$public\" \n]\n",
"elasticity_policies": [],
"scheduled_policies": []
},
{
"name": "B",
"cardinality": 1,
"vm_template": 0,
"vm_template_contents": "NIC = [\n NETWORK_ID = \"$public\" ]\nNIC = [\n NETWORK_ID = \"$private\" ]\n",
"elasticity_policies": [],
"scheduled_policies": []
}
],
"networks": {
"public": "O|network|| |id:0",
"private": "O|network|| |template_id:1:"
},
"ready_status_gate": true
}
```
3. Update the template by adding for example a new role
4. The change made to "vm_template_contents" we be removed
5. template look like this:
```
{
"name": "ReuschATest_PM_v1",
"deployment": "straight",
"description": "",
"roles": [
{
"name": "A",
"cardinality": 1,
"vm_template": 3,
"vm_template_contents": "NIC = [\n NETWORK_ID = \"$public\" ]\nNIC = [\n NETWORK_ID = \"$private\",\n NAME = \"private\" ]\n",
"elasticity_policies": [],
"scheduled_policies": []
},
{
"name": "B",
"cardinality": 1,
"vm_template": 0,
"vm_template_contents": "NIC = [\n NETWORK_ID = \"$public\" ]\nNIC = [\n NETWORK_ID = \"$private\" ]\n",
"elasticity_policies": [],
"scheduled_policies": []
},
{
"name": "demo1",
"cardinality": 1,
"vm_template": 85,
"elasticity_policies": [],
"scheduled_policies": []
}
],
"networks": {
"public": "O|network|| |id:0",
"private": "O|network|| |template_id::"
},
"ready_status_gate": true
}
```
**Expected behavior**
Already defined vm_template_contents for role should not be removed.

**Details**
 - Affected Component: Sunstone
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This is fixed in this commit 4a6dad8
