### ISSUE TITLE
Service scale is not working in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4502]
**Description**
Scaling a service in OneFlow causes error:

Sunstone:

```
Tue Apr 07 17:04:58 2020 [E]: [OneFlow] <!DOCTYPE html> <html> <head> <style type="text/css"> body { text-align:center;font-family:helvetica,arial;font-size:22px; color:#888;margin:20px} #c {margin:0 auto;width:500px;text-align:left} </style> </head> <body> <h2>Sinatra doesn’t know this ditty.</h2> <img src='http://localhost:2474/__sinatra__/404.png'> <div id="c"> Try this: <pre>put &#x27;&#x2F;service&#x2F;227&#x2F;role&#x2F;LeanFTClient&#x27; do &quot;Hello World&quot; end </pre> </div> </body> </html>Tue Apr 07 17:04:58 2020 [I]: 10.100.244.145 - - [07/Apr/2020:17:04:58 +0200] "PUT /service/227/role/LeanFTClient HTTP/1.1" 500 - 0.0039
```

**To Reproduce**
Scale the service in Sunstone.

**Details**
 - Affected Component: Sunstone
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PR to merge: 
- one: #4518
