### ISSUE TITLE
seg-fault  while executing xpath expression for non existing object in  the oned or mm_sched

### ISSUE THREAD

**Issue by Abdullahaml1** [OpenNebula/one#4503]
**Description**
segmentation fault happened when executing xpath expression for a non existing object in the pool. for example `/VM_POOL/VM[ID=555]/UID` if the vm id `555` does not exist the code will stuck because of seg-fault  

**To Reproduce**
for example: 
`object.xpaths(result, "/VM_POOL/VM[ID=555]/UID")`, and  vm id `555` does not exist

**Expected behavior**
If the id or the xml node does not exist it will return and the vector will be empty.

**Details**
 - Affected Component: oned, sched
 - Hypervisor: KVM
 - Version: 5.10.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
merged!

THANKS FOR THE CONTRIBUTION!

**Comment by Abdullahaml1** [comment]
YOU ARE WELCOME!
