### ISSUE TITLE
Add nic alias selection in Sunstone service dialog

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4506]
**Description**
The NIC_alias has to be added directly to "vm_template_contents" in JSON. It would be interesting to have this functionality available in Sunstone wizard.

**Use case**
For a user without JSON experience it is quit hard to add this option for the service.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
COMMENT TO PR IN ISSUE
PRs to merge:
- one: #4537 
- docs: OpenNebula/docs/pull/1056
