### ISSUE TITLE
Disable particular Marketplace

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4510]
**Description**
OpenNebula comes bootstrapped with few Marketplaces (ONE, LXD, TKL). If user doesn't want any of them, he has the only choice to delete them. It would be nice if particular Marketplace could be just to disabled (and enabled) to avoid monitoring. In case of disabled state, it should also delete any related appliances from the marketapp list.

**Use case**
Get rid of container MPs, but leave them defined in openenbula for some later use.

**Interface Changes**
API, CLI, Sunstone, MP drivers

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Currently if the corresponding `MARKET_MAD` section is commented at `oned.conf` the monitoring is disabled for the corresponding marketplace:

https://github.com/OpenNebula/one/blob/a5dce52f096c1ecd0fee48d577bf0a606e0fa7e3/src/market/MarketPlaceManager.cc#L252

**Comment by vholer** [comment]
That's just workaround, not a solution.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1290)
- [Docs](https://github.com/OpenNebula/docs/pull/1882)
