### ISSUE TITLE
VM Charters available in the CLI

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#4552]
**Description**

OpenNebula should allow VM Charters to be managed through the CLI

**Use case**

die hard terminal users want to also use VM Charters

**Interface Changes**

onevm create-chart
onevm delete-chart
onevm update-chart

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/15)
- [docs](https://github.com/OpenNebula/docs/pull/1205)

PRs to merge in master:

- [configuration file](https://github.com/OpenNebula/one-ee/pull/16)
- [tests](https://github.com/OpenNebula/development/pull/1096)

**Comment by tinova** [comment]
This implementation suffers from the same issue than the original sunstone one. @sbbarragan can you add more details please?

**Comment by sbbarragan** [comment]
**To Reproduce**
From the CLI: `onevm create-chart <id>`

And VM instantiated 2 days ago, for example.
The result is the following:
```
ID    ACTION  ARGS   SCHEDULED REPEAT   END  DONE                             MESSAGE CHARTER        
 0   suspend     - 01/15 01:00                 -                                   - In 12.16 days *
 1 terminate     - 01/29 01:00                 -                                   - In 26.16 days
```

**Expected behavior**
Charted should be in 14 and 28 days respect date time when create it from CLI.

And SCHEDULED column is wrong, eg:
today: `07/26/2021 16:40`
+14 days:  `08/09/2021 16:40`
```
ID    ACTION  ARGS   SCHEDULED REPEAT   END  DONE                             MESSAGE CHARTER        
 0   suspend     - 08/09 01:00                 -                                   - In 14 days *
 1 terminate     - 08/23 01:00                 -                                   - In 28 days
```

**Additional context**
By default config: `/etc/one/cli/onevm.yaml`
```
:charters:
  :suspend:
    :time: "+1209600"
    :warning:
      :time: 86400
  :terminate:
    :time: "+1209600"
    :warning:
      :time: 86400
```

**Comment by paczerny** [comment]
> And SCHEDULED column is wrong, eg:
today: 07/26/2021 16:40
+14 days: 08/09/2021 16:40

The `SCHEDULED` column in CLI output was already fixed
