### ISSUE TITLE
Option to store VM logs in `VMS_LOCATION`

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#4556]
**Description**
Add `oned` option to store VM longs inside `VMS_LOCATION` directory.

**Use case**
According to HA Frontend setup docs, VM logs should be somehow synced between frontend nodes. To do it easier, it would be fine to have the option to store VM logs inside `VMS_LOCATION` and sync the whole `VMS_LOCATION` directory.

Synchronization can be done by using `lsyncd` tool.

PR #3857

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Still relevant

**Comment by feldsam** [comment]
What about this and my PR?
