### ISSUE TITLE
logrotate configuration adding global defaults affecting other system logs

### ISSUE THREAD

**Issue by willx0** [OpenNebula/one#4557]
**Description**
Current logrotate configuration as included in the opennebula packages eg. /etc/logrotate.d/opennebula, is adding defaults to the global logrotate configuration changing the naming of other system logs.

**To Reproduce**
Running logrotate will add the date extension specified in the opennebula logrotate config on other system logs and cause them to be retained for 52 weeks unless explicitly configured otherwise.

**Expected behavior**
Logrotate options should only affect opennebula logs in /var/log/one directory.

**Details**
 - Affected Component: core
 - Version: 5.10.1

Current configuration:
https://github.com/OpenNebula/one/blob/424ab046b70df7bee0658bb0c3572a9f88e66bad/share/pkgs/logrotate/opennebula#L1-L13

Options should be moved into the log stanza:
```
/var/log/one/one_xmlrpc.log /var/log/one/oned.log {
    missingok
    notifempty
    copytruncate
    delaycompress
    dateext
    dateformat -%Y%m%d-%s
    compress 
    weekly
    rotate 52
}
```

**Additional context**
This problem applies to all other logrotate configs eg. opennebula-econe, opennebula-flow, etc.

A single configuration as follows would negate the need for separate configs for the other components:

```
/var/log/one/*.log {
    missingok
    notifempty
    copytruncate
    delaycompress
    dateext
    dateformat -%Y%m%d-%s
    compress 
    weekly
    rotate 52
}
```

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Nice catch, thanks @willx0 !

PRs to merge into master:
- one: https://github.com/OpenNebula/one/pull/4592
- docs: https://github.com/OpenNebula/docs/pull/1077
