### ISSUE TITLE
Check extra parameter one service instantiation

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#4564]
**Description**
when a service with a reserved network addresses without extra parameter is instantiated, an error occurs in sinatra:
`#<NoMethodError: undefined method 'empty?' for nil:NilClass>`

**To Reproduce**
Create a service template with a reserved network like:
```
{
  "name": "template-service1",
  "deployment": "straight",
  "description": "",
  "roles": [
    {
      "name": "master",
      "cardinality": 1,
      "vm_template": 2,
      "vm_template_contents": "NIC = [\n  NETWORK_ID = \"$public\" ]\n",
      "elasticity_policies": [],
      "scheduled_policies": []
    }
  ],
  "networks": {
    "public": "M|network|| |reserve_from:0:"
  },
  "ready_status_gate": false
}
```
Then instantiate without extra parameter.
![image](https://user-images.githubusercontent.com/59608355/79765732-4acaf680-8327-11ea-8245-409b2cbdc81e.png)

**Expected behavior**
Clear and concise message about the error and the reason

**Details**
 - Affected Component: Oneflow
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4586
