### ISSUE TITLE
Sunstone vCenter hot disk resize

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4569]
**Description**
Driver vCenter allows for hot disk resize, Sunstone should as well

**Use case**
Want to grow my disk while VM is running in Sunstone

**Interface Changes**
Sunstone

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
This issue is already solved for 5.12 release

**Comment by FrederickBor** [comment]
@tinova PR to be approved:

- ONE:  https://github.com/OpenNebula/one-ee/pull/177
- Docs: https://github.com/OpenNebula/docs/pull/1280

**Comment by tinova** [comment]
* Docs: https://github.com/OpenNebula/docs/commit/e61a834a45729af449ef1a5a7c5f2ea76187d4f2
