### ISSUE TITLE
src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value

### ISSUE THREAD

**Issue by samuelbernardo** [OpenNebula/one#4641]
**Description**
During compilation fails when compiling sunstone minified files.

**To Reproduce**
Compile source code with scons parsers=yes new_xmlrpc=yes mysql=yes sunstone=yes docker_machine=yes systemd=yes svncterm=yes

**Expected behavior**
The minified files for sunstone be created.

**Details**

In file included from ../src/binding.cpp:1:
../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DBUILDING_NODE_EXTENSION' -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/include/node -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/src -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/deps/openssl/config -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/deps/openssl/openssl/include -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/deps/uv/include -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/deps/zlib -I/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw  -O2 -pipe -march=native -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
In file included from ../src/create_string.cpp:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
In file included from /var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/create_string.cpp:1:
/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/include/node/v8.h:3267:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.node-gyp/14.1.0/include/node/v8.h:3267:5: note:   candidate expects 2 arguments, 1 provided
make: *** [binding.target.mk:127: Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/var/tmp/portage/app-emulation/opennebula-5.10.3/work/one-release-5.10.3/src/sunstone/public/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/tmp/portage/app-emulation/opennebula-5.10.3/work/one-release-5.10.3/src/sunstone/public/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.28-gentoox99
gyp ERR! command "/usr/bin/node" "/var/tmp/portage/app-emulation/opennebula-5.10.3/work/one-release-5.10.3/src/sunstone/public/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/tmp/portage/app-emulation/opennebula-5.10.3/work/one-release-5.10.3/src/sunstone/public/node_modules/node-sass
gyp ERR! node -v v14.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN opennebula-sunstone@0.0.1 No repository field.
npm WARN opennebula-sunstone@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/tmp/portage/app-emulation/opennebula-5.10.3/homedir/.npm/_logs/2020-05-02T18_30_34_602Z-debug.log
Error generating minifying Sunstone files

**Additional context**
The same error happens with version 5.10.4 when compiling node files.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sambhavsaggi** [comment]
Try creating a package instead of compiling from source. This eliminates the issue of dependencies. Follow instructions [here](https://github.com/opennebula/packages).

**Comment by samuelbernardolip** [comment]
@sambhavsaggi As I could review from sources, opennebula scripts dynamically links with system libraries. So using blindly the binary archive generated from centos 7 doesn't seem to be the best approach for all source (not only npm).
I will try to solve this compilation problems, or else try to get the centos rpm and get the files related to sunstone. I already also start to review the source rpm to review the details, but there are some sources that it uses besides the one archive.

There is another problem that is related to the build scripts require internet access. My solution was to ask for user permission to allow network sandbox breakage in Gentoo for the features that needs external network access by builder demand.
This is the current version that is failing in generating the minified files:
https://gitweb.gentoo.org/repo/user/ssnb.git/tree/app-emulation/opennebula/opennebula-5.10.4.ebuild
It was preferable that the archive contains all necessary sources.

**Comment by sambhavsaggi** [comment]
Apologies for the late reply. Try to compile the node modules first then run Scons.

```bash
cd src/sunstone/public
./build.sh -d
export PATH=$PATH:$PWD/node_modules/.bin
./build.sh
```

**Comment by samuelbernardolip** [comment]
> Apologies for the late reply. Try to compile the node modules first then run Scons.
> 
> ```shell
> cd src/sunstone/public
> ./build.sh -d
> export PATH=$PATH:$PWD/node_modules/.bin
> ./build.sh
> ```

I  corrected grunt-sass and node-sass versions and run both build commands as you mentioned, but is still failing:
```
Generating Sunstone minified files

npm WARN opennebula-sunstone@0.0.1 No repository field.
npm WARN opennebula-sunstone@0.0.1 No license field.

audited 2200 packages in 1.752s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '../lib/bin/bower'
Require stack:
- /usr/bin/bower
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/bin/bower:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/bin/bower' ]
}
Error generating minifying Sunstone files
```
Thanks for your help @sambhavsaggi

**Comment by sambhavsaggi** [comment]
It appears that you don’t have Bower installed. What is the output of `which bower`?

**Comment by samuelbernardolip** [comment]
> It appears that you don’t have Bower installed. What is the output of `which bower`?
# which bower
/usr/bin/bower

I've already installed before bower 1.8.4 as a dependency for opennebula.
Reviewing the build log I realized that it also fails when running build.sh with same error.

Could this be related to relative path since ./node_modules/bower/bin/bower only has
```
#!/usr/bin/env node

require('../lib/bin/bower');
```
Thanks @sambhavsaggi

**Comment by samuelbernardolip** [comment]
I think I just found the problem... In gentoo /usr/lib is /usr/lib64 and that relative path don't work because of that.
I need to correct bower ebuild for that lib mapping issue.

**Comment by sambhavsaggi** [comment]
Lol. I was in the process of installing Gentoo so I could replicate your environment.

**Comment by samuelbernardolip** [comment]
@sambhavsaggi Is working now with opennebula-5.10.4. nodejs minified files generated correctly. Thanks.

This issue can be closed.

**Comment by sambhavsaggi** [comment]
Only the repository owners or @samuelbernardo can close this issue.

**Comment by bpracht** [comment]
I'm still having this issue. I'm running under Ubuntu 20.04.1 (on WSL). I actually get the exact same error mentioned on the subject. I'm not yet able to tell where on the FS it's building the code so it's hard to step in and manually fix this. I got this error building the latest version of node-sass.

**Comment by sambhavsaggi** [comment]
Unfortunately, the OpenNebula packages repo was taken private (see #4844). Asking one of the maintainers for access would be the best way to go, unfortunately.
