### ISSUE TITLE
Unable to start LXD container: Invalid devices: Device validation failed disk1

### ISSUE THREAD

**Issue by sambhavsaggi** [OpenNebula/one#4642]
**Description**
When creating an LXD container (from the TurnKey marketplace), the contextualization errors out.

**To Reproduce**
1. Download and install CentOS 7
1. Install OpenNebula compiled from source from [packages](https://github.com/OpenNebula/packages)
1. Import TurnKey marketplace
1. Download Nginx LXD container from TurnKeyLinux marketplace and contextualization package from OpenNebula marketplace.

**Expected behavior**
Nginx container starts.

**Details**
 - Affected Component: Virt
 - Hypervisor: LXD
 - Version: 5.10.4

**Additional context**
[oned.log](https://paste.ubuntu.com/p/JQyQYTRbYH/)
[VM Logs](https://paste.ubuntu.com/p/WySwrtY4P3/)
[Template](https://paste.ubuntu.com/p/GT27ssy8cn/)
[VM/Template](https://paste.ubuntu.com/p/shnPsMNKXp/)
No issue from starting directly with `lxc` command and importing as wild.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Only LXD LTS versions are supported, at the moment lxd 3.0.x. More info about the issue [here](https://forum.opennebula.io/t/unable-to-deploy-instantiate-lxd-app-linux-vm/8392/16)

**Comment by sambhavsaggi** [comment]
Wonderful! This worked, but created another issue (#4662)
