### ISSUE TITLE
Service pool info is not working after upgrade from lower version

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4646]
**Description**
After upgrading from 5.10.4 (or lower) OneFlow list stop showing all the services.

**To Reproduce**
Upgrade from lower version and use `oneflow list`.

**Expected behavior**
All services should be displayed.

**Details**
 - Affected Component: OneFlow
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4647
