### ISSUE TITLE
Add or remove roles from a running service

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#4654]
**Description**
Currently in a running service, the roles are static, can't be modify, it would be nice to be able to add new roles or remove the existing one.

**Use case**
This is very useful for some use cases like K8s.

**Interface Changes**
OneFlow server, CLI and Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1191)
- [docs](https://github.com/OpenNebula/docs/pull/1823)
- [tests](https://github.com/OpenNebula/development/pull/1466)

PR to merge in 6.0 maintenance:

- [docs](https://github.com/OpenNebula/docs/pull/1824)

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1281)
- [Docs](https://github.com/OpenNebula/docs/pull/1877)
