### ISSUE TITLE
lsblk: invalid option -- 'O'

### ISSUE THREAD

**Issue by sambhavsaggi** [OpenNebula/one#4662]
**Description**
When creating an LXD container (Alpine Linux from the official LinuxContainers.org marketplace), the creation errors out.

**To Reproduce**
1. Download and install CentOS 7
1. Install OpenNebula compiled from source from [packages](https://github.com/OpenNebula/packages)
1. Download Alpine LXD container.
1. Launch from Sunstone

**Expected behavior**
Alpine container starts.

**Details**
 - Affected Component: Virt
 - Hypervisor: LXD
 - Version: 5.10.4
- LXC Version: 3.0.4

**Additional context**
[Container Log](https://paste.ubuntu.com/p/s7yBjTyddj)
[oned.log](https://paste.ubuntu.com/p/F6m9n4jMZS/)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
The supported operating systems for LXD should have the -O option in lsblk,

```
root@ubuntu1804-lxd-marketplace-5-10-4-0e3f4-0:~# lsblk --help | grep all
 -a, --all            print all devices
 -O, --output-all     output all columns
```

Can you check your lsblk version?

```
root@ubuntu1804-lxd-marketplace-5-10-4-0e3f4-0:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@ubuntu1804-lxd-marketplace-5-10-4-0e3f4-0:~# lsblk --version
lsblk from util-linux 2.31.1
```

**Comment by dann1** [comment]
Output [here](https://paste.ubuntu.com/p/s7yBjTyddj/) doesn't have the `-O` option

**Comment by sambhavsaggi** [comment]
Thanks! Switching to Debian 10 worked fine.

**Comment by dann1** [comment]
Once again, please read the documentation about the [LXD installation requirements](http://docs.opennebula.io/5.10/deployment/node_installation/lxd_node_installation.html#step-2-installing-the-software). So far you have had compatibility issues due to not having the correct OS/hypervisor version. Everything there states what works and what doesn't and where it should be run.
