### ISSUE TITLE
problem with vrouter command

### ISSUE THREAD

**Issue by thetrustabletechnologist** [OpenNebula/one#4685]
**Description**
the command line doesnt work https://github.com/OpenNebula/docs/blob/master/source/operation/network_management/vrouter.rst

onemarketapp export 'alpine-vrouter (KVM)' vrouter_alpine --datastore default --vmname vrouter_alpine

**To Reproduce**
onemarketapp export 'alpine-vrouter (KVM)' vrouter_alpine --datastore default --vmname vrouter_alpine

**Expected behavior**
supposed to download

**Details**
error message : MARKETPLACEAPP named alpine-vrouter (KVM) not found.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
The app name is Vrouter Alpine - KVM, closing.
