### ISSUE TITLE
KVM live migration fails but VM migrates

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4695]
**Description**

Due to a specific libvirt version and/or host misconfiguration (shared storage, SELinux)  we can observe strange errors when KVM virtual machine live-migration fails with error exit code, but VM itself actually migrates to another host.

But in the OpenNebula, VM remains assigned to the original host, but leaves running on target host out of control of OpenNebula.

Example:

```
$ virsh --connect qemu:///system migrate --live --unsafe one-36 qemu+ssh://hostB/system || echo Failed
Failed
$ virsh -c qemu:///system list
 Id   Name   State
--------------------

$ virsh -c qemu+ssh://hostB/system list
 Id   Name     State
------------------------
 75   one-36   running
```

Libvirt complain on source host:

```
libvirtd[951]: internal error: child reported (status=125):
libvirtd[951]: Unable to remove disk metadata on vm one-36 from /var/lib/one//datastores/0/36/disk.0 (disk target vda)
libvirtd[951]: internal error: child reported (status=125): internal error: child reported (status=125):
libvirtd[951]: Unable to remove disk metadata on vm one-36 from /var/lib/one/datastores/1/e2c4955559b71386ce00711353f7be64 (disk target vda)
libvirtd[951]: internal error: child reported (status=125): internal error: child reported (status=125): internal error: child reported (status=125):
libvirtd[951]: Unable to remove disk metadata on vm one-36 from /var/lib/one//datastores/0/36/disk.1 (disk target hda)
libvirtd[951]: internal error: child reported (status=125):
libvirtd[951]: Unable to remove disk metadata on vm one-36 from /var/lib/one//datastores/0/36/disk.0 (disk target vda)
libvirtd[951]: internal error: child reported (status=125): internal error: child reported (status=125):
libvirtd[951]: Unable to remove disk metadata on vm one-36 from /var/lib/one/datastores/1/e2c4955559b71386ce00711353f7be64 (disk target vda)
libvirtd[951]: internal error: child reported (status=125): internal error: child reported (status=125): internal error: child reported (status=125):
libvirtd[951]: Unable to remove disk metadata on vm one-36 from /var/lib/one//datastores/0/36/disk.1 (disk target hda)
```

**To Reproduce**
- Live migrate KVM VM

**Expected behavior**
While might (will) be a libvirt version specific problem, **at least OpenNebula should do an extra cleanup** on target host in case of failure - destroy and undefine domain if still running on target.

**Details**
 - Affected Component: KVM
 - Hypervisor: KVM
 - Version: 5.11.85 (master)
- libvirt: 6.1.0
- QEMU: 4.2.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by repsol** [comment]
I think I am having the same issues building new guest VM's in KVM. I am only mentioning this because I am using KVM on Ubuntu 20.04 and getting the same error, and wondering if it may be a bug in the new Ubuntu. 

 libvirtd[1355]: this function is not supported by the connection driver: virSecurityManagerMoveImageMetadata
 libvirtd[1355]: internal error: child reported (status=125): this function is not supported by the connection driver: virSecurityManagerMoveImageMetadata
 libvirtd[1355]: Unable to remove disk metadata on vm mosaic from /var/lib/libvirt/images/mosaic.img (disk target vda)

**Comment by engel75** [comment]
Having the same issue using Vagrant with libvirt on 20.04 when spinning up multiple VMs at the same time.

**Comment by elfosardo** [comment]
I'm seeing the same issue on Ubuntu 20.04, looks definitely like a bug or a breaking change:

2020-05-15 10:05:50.626+0000: 96089: error : virSecurityManagerMoveImageMetadata:476 : this function is not supported by the connection driver: virSecurityManagerMoveImageMetadata
2020-05-15 10:05:50.628+0000: 96089: error : virProcessRunInFork:1159 : internal error: child reported (status=125): this function is not supported by the connection driver: virSecurityManagerMoveImageMetadata
2020-05-15 10:05:50.628+0000: 96089: warning : qemuBlockRemoveImageMetadata:2629 : Unable to remove disk metadata on vm node-0 from /var/lib/libvirt/images/node-0.qcow2 (disk target vda)

**Comment by ingo-h** [comment]
Having this also on Debian 11 (bullseye) on every shutdown of a vm:

    Jun 29 20:57:31 harley-11 libvirtd[1200]: internal error: End of file from qemu monitor
    Jun 29 20:57:31 harley-11 systemd[1]: machine-qemu\x2d2\x2dvdeb03\x2d11\x2dbase.scope: Succeeded.
    Jun 29 20:57:31 harley-11 systemd-machined[721]: Machine qemu-2-vdeb03-11-base terminated.
    Jun 29 20:57:31 harley-11 audit[1444]: AVC apparmor="STATUS" operation="profile_remove" profile="unconfined" name="libvirt-7eec225c-9055-4c54-a7e0-fd375e153ab5" pid=1444 comm="apparmor_parser"
    Jun 29 20:57:31 harley-11 kernel: audit: type=1400 audit(1593457051.567:38): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="libvirt-7eec225c-9055-4c54-a7e0-fd375e153ab5" pid=1444 comm="apparmor_parser"
    Jun 29 20:57:31 harley-11 libvirtd[1200]: this function is not supported by the connection driver: virSecurityManagerMoveImageMetadata
    Jun 29 20:57:31 harley-11 libvirtd[1200]: internal error: child reported (status=125): this function is not supported by the connection driver: virSecurityManagerMoveImageMetadata
    Jun 29 20:57:31 harley-11 libvirtd[1200]: Unable to remove disk metadata on vm vdeb03-11-base from /mnt/data/var/lib/libvirt/images/vdeb03-11-base.qcow2 (disk target vda)

**Comment by paczerny** [comment]
It was probably a bug only in some verison of libvirt. Can't reproduce it in actual version of Ubuntu 20.04, 20.10 and Debian 10.
If you still have problem with this issue, please send as a version of libvirt you are using, we will reopen the ticket
