### ISSUE TITLE
Cannot unselect User/Group when previously selected when Instantiate from Susnstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4697]
**Description**
When doing a VM Template instantiation, once you have selected a User/Group, it is not possible to unselect the previously selected User/Group -i.e. return to default ones-.

**To Reproduce**
In Sunstone: _Templates -> VMs -> Instantiate as different User / Group_:

![image](https://user-images.githubusercontent.com/33811723/81583100-248df900-93b1-11ea-849a-c37ed01aa189.png)

Once you have the an User / Group selected, it is not possible to unselect clicking on it again.

**Expected behavior**
It must be possible to unselect a previously selected User/Group on VM Intantiate returning to default one values.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4716

**Comment by sbbarragan** [comment]
We had to revert the commit since it was affecting other datatables and Sunstone performance. This is not straightforward, we need to reevaluate.

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4756
