### ISSUE TITLE
Docker Machine driver breaking change

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#4734]
**Description**
PR #4385 introduced a breaking change in the docker-machine driver. After an update, all existing docker-machines are unusable.

**To Reproduce**
Update driver on a system with existing machines.

**Expected behavior**
After an update, existing machines have to work. We need to implement a fallback for old VM identification.

**Details**
 - Affected Component: docker_machine
 - Hypervisor: any
 - Version: 5.10.4+

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
I am proposing to add temporary falback using VM name until next major release, 5.12 or 5.14, and then remove it. So users will have time to recreate docker machines.

**Comment by carloshm91** [comment]
Hello @feldsam thanks for you interest in the docker-machine driver for OpenNebula.

We have the fix for this https://github.com/OpenNebula/one/pull/4789.

Test it if you want inside your environment and let us know how was.

**Comment by feldsam** [comment]
Hello @carloshm91 , thanks! I have just one comment about your code, check it. I will compile myself this updated version and test it

**Comment by carloshm91** [comment]
Hello @feldsam where do you put the comment? Yes, please test it and let us know.

**Comment by feldsam** [comment]
Hello @carloshm91, I wrote it on your PR

**Comment by feldsam** [comment]
Just tested, looks like working well. Tested with my changes https://github.com/OpenNebula/one/pull/4797

**Comment by tinova** [comment]
Thanks for this quality feedback
