### ISSUE TITLE
Opennebula fails to create VM due to conflicting VNC ports

### ISSUE THREAD

**Issue by telmich** [OpenNebula/one#4740]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
VMs are sometimes scheduled to have the same VNC port on the same host. This happens usually with hosts with > 100 VMs on them.

**To Reproduce**
Create a VM, it "randomly" fails - i.e. fails when the listening port is already in use by another VM's VNC listener.

**Expected behavior**
Select a free VNC port.

**Details**
 - Affected Component: VM
 - Hypervisor: KVM
 - Version: 5.8.5 (not yet seen on 5.10.1, but did not see a statement in the changelog that addressed it)

**Additional context**
```
Sun May 17 18:41:12 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/104/25803/deployment.0' 'serverXX.placeY.ungleich.ch' 25803 serverXX.placeY.ungleich.ch
Sun May 17 18:41:12 2020 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/104/25803/deployment.0
Sun May 17 18:41:12 2020 [Z0][VMM][I]: error: internal error: qemu unexpectedly closed the monitor: 2020-05-17T16:36:16.701135Z qemu-system-x86_64: -vnc [::]:4156: Failed to start VNC server: Failed to bind socket: Address already in use
Sun May 17 18:41:12 2020 [Z0][VMM][E]: Could not create domain from /var/lib/one//datastores/104/25803/deployment.0
Sun May 17 18:41:12 2020 [Z0][VMM][I]: ExitCode: 255
Sun May 17 18:41:12 2020 [Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
Sun May 17 18:41:12 2020 [Z0][VMM][E]: Error deploying virtual machine: Could not create domain from /var/lib/one//datastores/104/25803/deployment.0
Sun May 17 18:41:12 2020 [Z0][VM][I]: New LCM state is BOOT_FAILURE
Sun May 17 18:48:37 2020 [Z0][VM][I]: New LCM state is BOOT
Sun May 17 18:48:37 2020 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/25803/deployment.0
Sun May 17 18:48:38 2020 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Sun May 17 18:48:38 2020 [Z0][VMM][I]: ExitCode: 0
Sun May 17 18:48:38 2020 [Z0][VMM][I]: ExitCode: 0
Sun May 17 18:48:38 2020 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Sun May 17 18:48:40 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/104/25803/deployment.0' 'server11.place6.ungleich.ch' 25803 serverXX.placeY.ungleich.ch
Sun May 17 18:48:40 2020 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/104/25803/deployment.0
Sun May 17 18:48:40 2020 [Z0][VMM][I]: error: internal error: qemu unexpectedly closed the monitor: 0,data=...,keyid=masterKey0,i=...,format=base64 -drive 'file=rbd:ssd/one-322-25803-0:id=libvirt:auth_supported=cephx\;none:mon_host=ceph1\:6789\;ceph2\:6789\;ceph3\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,cache=none' -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -drive file=/var/lib/one//datastores/104/25803/disk.1,format=raw,if=none,id=drive-ide0-0-0,readonly=on -device ide-cd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0 -netdev tap,fd=104,id=hostnet0,vhost=on,vhostfd=106 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=...,bus=pci.0,addr=0x3 -netdev tap,fd=111,id=hostnet1,vhost=on,vhostfd=113 -device virtio-net-pci,netdev=hostnet1,id=net1,mac=....,bus=pci.0,addr=0x4 -vnc '[::]:4156' -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,
Sun May 17 18:48:40 2020 [Z0][VMM][E]: Could not create domain from```
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
check your oned config. there are reserved_ports setting.

**Comment by telmich** [comment]
@feldsam Thanks for the pointer. I am aware of that, however the problem is that the VNC port clashes with another VM started by opennebula. Not with a third party service

**Comment by atodorov-storpool** [comment]
@telmich 
Did you check the database for corruption? The VNC port assignment is a function of the VM_ID https://github.com/OpenNebula/one/blob/master/include/Cluster.h#L119 
So it is difficult to have a collision because it is not possible to have two VMs with the same VM_ID.

**Comment by telmich** [comment]
@atodorov-storpool I think I tend to disagree. The code in question is:

```
        unsigned int hint_port = base_port + (vmid % (65535 - base_port));
```
let's assume base_port = 5900


vmid = 0 and vmid = 59635 both give a hint_port of 5900. The port cannot be unique due to the modulo. Additionally when the base port is changed, collisions can happen in a different way, as the modulo differs.

```
unsigned int base_port = vnc_bitmap.get_start_bit();
```

I did not dig deeper into vnc_bitmap.get_start_bit(), but the source code you referenced clearly shows the possible collisions.

I am not saying we don't have a problem in the database, but above code certainly allows collisions per host.

**Comment by feldsam** [comment]
Day or two ago I was looking into the same code, but what I understand is that modulo is just used for initial port calculation, them passed to vnc bitmap function to get a free port. vnc bitmap is stored in database table. It checks if a port is free and if not it checks port - 1 and so on until it finds a free port.

**Comment by christian7007** [comment]
Hello @telmich, as @feldsam said, the `base_port` and `hint_port` are used just to save some time but before assigning the port `oned` always check the bitmap to ensure the port is free, if not it just looks for a free one:

https://github.com/OpenNebula/one/blob/ec252e2aaf08049d3546d8abcd6c8e91df145539/include/BitMap.h#L137

Could you please execute the following command and check if the port which is failing is marked as used at the `oned` bitmap?

```
mysql -u oneadmin -p<db_pass> opennebula -B -e"select map from network_vlan_bitmap where id=0" | tail -1 | ruby -e "require 'base64'; require 'zlib'; b=Zlib::Inflate.inflate(Base64.decode64(STDIN.read.chomp)); b.length.times{ |i| puts 4095-i if b[i] == '1' }"
```

**Comment by telmich** [comment]
@christian7007 I just tried to execute this -- which argument in the mysql/shell should be the port? If I run above command directly, I don't get any output. If I run the same command without the zlib expansion I get a base64 encoded string though

**Comment by christian7007** [comment]
Hello @telmich sorry for the error, the snippet I copied was for retrieving the VLAN bitmap, please use this one instead:

```
mysql -u oneadmin -p<db_pass> opennebula -B -e "select map from cluster_vnc_bitmap where id=0" | tail -1 | ruby -e "require 'base64'; require 'zlib'; b=Zlib::Inflate.inflate(Base64.decode64(STDIN.read.chomp)); b.length.times{ |i| puts i if b[i] == '1' }"
```

**Comment by telmich** [comment]
@christian7007 above query returns quite a long list:

```
37436
37569
37743
38258
38639
38924
39105
40540
41469
44774
45417
46391
48893
49334
49512
50494
52152
55454
55456
55459
55463
55464
55468
55470
55471
55472
55473
55474
55475
55476
55478
55479
55480
55481
55482
55483
55484
55485
55486
55487
55488
55489
55490
55491
55493
55494
55495
55496
55497
55499
55500
55502
55503
55504
55507
55509
55510
55511
55512
55513
55514
55515
55516
55517
55519
55520
55521
55522
55523
55524
55526
55528
55529
55530
55531
55532
55533
55534
55535
57240
```

**Comment by telmich** [comment]
Hello,

we are encountering this problem more and more on different hosts.

Latest log entry for the last 10 VMs that cannot be started:

```
Tue Jun 2 13:32:56 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/migrate 'one-23979' 'server11.place6.ungleich.ch' 'server4.place6.ungleich.ch' 23979 server4.place6.ungleich.ch
Tue Jun 2 13:32:56 2020 [Z0][VMM][E]: migrate: Command "virsh --connect qemu:///system migrate --live one-23979 qemu+ssh://server11.place6.ungleich.ch/system" failed: error: internal error: process exited while connecting to monitor: drive=drive-ide0-0-0,id=ide0-0-0 -netdev tap,fd=199,id=hostnet0,vhost=on,vhostfd=202 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=02:00:f0:a9:c4:07,bus=pci.0,addr=0x3 -vnc '[::]:4255' -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -incoming defer -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -msg timestamp=on
Tue Jun 2 13:32:56 2020 [Z0][VMM][I]: 2020-06-02T11:27:06.753969Z qemu-system-x86_64: -vnc [::]:4255: Failed to start VNC server: Failed to bind socket: Address already in use
Tue Jun 2 13:32:56 2020 [Z0][VMM][E]: Could not migrate one-23979 to server11.place6.ungleich.ch
Tue Jun 2 13:32:56 2020 [Z0][VMM][I]: ExitCode: 1
Tue Jun 2 13:32:56 2020 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_failmigrate.
Tue Jun 2 13:32:56 2020 [Z0][VMM][I]: Failed to execute virtualization driver operation: migrate.
Tue Jun 2 13:32:56 2020 [Z0][VMM][E]: Error live migrating VM: Could not migrate one-23979 to server11.place6.ungleich.ch
Tue Jun 2 13:32:56 2020 [Z0][VM][I]: New LCM state is RUNNING
Tue Jun 2 13:32:56 2020 [Z0][LCM][I]: Fail to live migrate VM. Assuming that the VM is still RUNNING (will poll VM).
```

Same error for at least 10 other VMs with different ports. No other processes running on the system besides opennebula VMs.

**Comment by telmich** [comment]
Interestingly using netstat -anp, the port 4255 seems not to be in use.

**Comment by telmich** [comment]
Is it possible that migrating VMs in parallel allocates the port in parallel?

**Comment by feldsam** [comment]
hmm, still, VM VNC port is unique across the cluster, so there is no possibility to have same port on two VMs on different hosts.

check with `netstat -tapn|grep -i listen`

**Comment by telmich** [comment]
So it gets more interesting. As long as I migrate only 2 VMs at the same time, this problem seems not to occur. As soon as I migrate 3+ VMs at the same time, the vnc port collision happens.

**Comment by telmich** [comment]
Now I found two direct cases with running qemu processes:

VM one-23938:

```
[11:26:29] server8.place6:~# netstat -anp | grep 10031
tcp6       0      0 :::10031                :::*                    LISTEN      1566170/qemu-system 
```

On another server:

VM one-24143
```
[10:01:34] server11.place6:~# netstat -anp | grep 10031
tcp6       0      0 :::10031                :::*                    LISTEN      2037157/qemu-system 
```

Is there anything I can do to debug this?

**Comment by telmich** [comment]
I just checked for double assigned VNC ports on two servers as follows:

```
[10:24] line:~% ssh root@server9.place6.ungleich.ch "netstat -lnp | grep tcp6 | grep qemu-system | awk '{ print \$4 }' | sed 's/::://' | sort" > vncports-server9.place9                                                            

[10:25] line:~% ssh root@server11.place6.ungleich.ch "netstat -lnp | grep tcp6 | grep qemu-system | awk '{ print \$4 }' | sed 's/::://' | sort" > vncports-server11.place9 

[10:26] line:~% while read port ; do  grep $port vncports-server11.place9; done < vncports-server9.place9 | wc -l
104
```

So on those two servers I see **104** duplicate VNC ports.

For instance ports
```
10000
10001
10002
10003
10004
10005
10007
10008
10009
```

Are used on both systems.

**Comment by feldsam** [comment]
Hello, when you select a few VMs with duplicate ports, look into OpenNebula to check what VNC port is assigned in it. VM name in the Libvirt is one-{ID} where {ID} is OpenNebula instance ID.

**Comment by paczerny** [comment]
I think it's fixed by this [commit](https://github.com/OpenNebula/one/commit/26498959bcfadc361617aee36d9956e1cfef1d84)
Included in one-5.12.5 EE and one-5.12.0.4 CE.
If anybody hits this issue in 5.12.5+, please make a comment here

**Comment by jaimeibar** [comment]
Hi, 

I'm having a similar issue in one 6.0.0.2.

It happens when I try to spin up a new vm and resume an undeployed vm

This is the error I'm getting

`[one.vm.deploy] No free VNC ports available in the cluster
`

**Comment by paczerny** [comment]
@telmich Which OpenNebula version you use? Is there any chance that you use `onevm recover --recreate` and the duplicate VNC port is caused by #5796 ?
