### ISSUE TITLE
broken URL in the LINK attribute in the marketplace apps

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4765]
**Description**
Cant download appliance from the marketplace.

**To Reproduce**
1. Build and install opennebula from the master branch (tested with commit 897795f)
2. try downloading KVM appliance from the marketplace

```
Tue May 19 18:58:34 2020 [Z0][ImM][I]: cp: Copying local image https:/marketplace.opennebula.io/appliance/154f6edf-47dc-4bcb-af77-e55c7d31e945/download/0 to the image repository
Tue May 19 18:58:34 2020 [Z0][ImM][E]: cp: Command "set -e -o pipefail; /var/lib/one/remotes/datastore/fs/../downloader.sh   'https:/marketplace.opennebula.io/appliance/154f6edf-47dc-4bcb-af77-e55c7d31e945/download/0' '/var/lib/one//datastores/1/845204ef8b0965c8e256edbd8dbeca0f'" failed: Cannot read from https:/marketplace.opennebula.io/appliance/154f6edf-47dc-4bcb-af77-e55c7d31e945/download/0
Tue May 19 18:58:34 2020 [Z0][ImM][E]: Error copying https:/marketplace.opennebula.io/appliance/154f6edf-47dc-4bcb-af77-e55c7d31e945/download/0 to /var/lib/one//datastores/1/845204ef8b0965c8e256edbd8dbeca0f
Tue May 19 18:58:34 2020 [Z0][ImM][E]: Error copying image in the datastore: Error copying https:/marketplace.opennebula.io/appliance/154f6edf-47dc-4bcb-af77-e55c7d31e945/download/0 to /var/lib/one//datastores/1/845204ef8b0965c8e256edbd8dbeca0f
```

**Expected behavior**
The appliance should be downloaded

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**

Note the broken URL in the `LINK` attribute:
![image](https://user-images.githubusercontent.com/11386997/82349210-7f9f9b80-9a02-11ea-80d1-bcf764022936.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @atodorov-storpool it seem like a bug fixed by https://github.com/OpenNebula/one/commit/7ff8aefb3a160db44bee0fe9a22ea1c1de826ad5.

I've just tested it in https://github.com/OpenNebula/one/commit/8337149d3369c14ed673f6ea331d00513ae7ff3d and seems to works fine. Could you please make sure that you have the commit with the fix? If you have it and the error keep appearing please reopen.

**Comment by atodorov-storpool** [comment]
It looks like I've do not bootstrapped when updated the packages and the DB was already messy

**Comment by christian7007** [comment]
Perfect, thanks for the feedback anyway!
