### ISSUE TITLE
Add custom LXD image store 

### ISSUE THREAD

**Issue by ilhaan** [OpenNebula/one#4769]
**Description**
LXD daemons act as image servers (refer to "Publishing your images" [here](https://stgraber.org/2016/03/30/lxd-2-0-image-management-512/)). Being able to add such a server to OpenNebula would make it easier to obtain LXD images. 

**Use case**
An image server can update and build new LXD images and make it available to OpenNebula to launch new guests. 

**Interface Changes**
Perhaps this can be added under "MarketPlaces" 

**Additional Context**
I tried to add a custom LXD image server using [this](https://docs.opennebula.io/5.10/advanced_components/marketplace/market_lxd.html) but the MarketPlaces feature seems to be specific to the two MarketPlaces currently available (Linux Containers and Turnkey). 

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
As it requires LXD daemon and LXD support have been deprecated in favor of LXC I think it doesn't apply anymore. Please, reopen if I'm wrong.
