### ISSUE TITLE
VMs don't appear in Sunstone, appear in onevm list

### ISSUE THREAD

**Issue by sambhavsaggi** [OpenNebula/one#4770]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When using Sunstone, on the dashboard, the VM numbers are blinking at 0. In the console, I get `ReferenceError: "ips is not defined"`. In the VMs and Service sections of the dashboard, I don't see services or VMs, even though I do have them running. I am also unable to switch to other tabs if running with Nginx / Passenger. This issue occurs with and without Passenger on Nginx. It was working fine before the upgrade.

**To Reproduce**
Upgrade OpenNebula from 5.10.5 to 5.11.80 (compile from source on clean Debian VM)

**Expected behavior**
Shows VMs and other information.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM / LXD
 - Version: 5.11.80 beta

**Additional context**
Nothing interesting in Sunstone logs. Everything is 200. However, the oned.log file is interesting: I see "Received message was: String can't be coerced into Integer". I will create a VM later and check if this is an issue with the upgrade or the code itself.

Logs

[oned.log](https://paste.ubuntu.com/p/TFFvXHfN3h/)

Edit: [This](https://imgur.com/HY5vPmd) is what I mean by blinking zeros.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
Hello @sambhavsaggi, 
Thanks for testing the beta upgrade. The bug that you comment has been solved in [master](https://github.com/OpenNebula/one/commit/2d3ef1be41d0b554e1af6ef2203c7806a6cf062a).

If you can update your installation again it should be fixed.

**Comment by sambhavsaggi** [comment]
Can confirm it works.
