### ISSUE TITLE
Sunstone Not Displaying Real CPU / Real Memory

### ISSUE THREAD

**Issue by sambhavsaggi** [OpenNebula/one#4790]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Sunstone does not display any CPU or RAM usage for the hosts (real). [example](https://i.imgur.com/yxLkPnG.png)

**To Reproduce**
Debian 10, packages from source.

**Expected behavior**
Shows current RAM / CPU use.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM / LXD
 - Version: 5.11.90 commit 783ec5c (latest)

**Additional context**
Nothing fishy in logs, fresh install. Using sqlite (issue also occurs with MariaDB).

[oned.log](https://paste.ubuntu.com/p/pz9rDJfZpX/)
[sunstone.log](https://paste.ubuntu.com/p/vrkvxSBdZP/)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4799
