### ISSUE TITLE
bribge interface is not created on the hypervisor

### ISSUE THREAD

**Issue by Ilyashestopalov** [OpenNebula/one#4794]
**Description**
working with iproute when creating a virtual machine does not create a bridge interface.
In instance logs.
```
Thu May 21 10:05:06 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vnm/vxlan/pre
Thu May 21 10:05:06 2020 [Z0][VMM][I]: link: extra operand ‘bridge’
Thu May 21 10:05:06 2020 [Z0][VMM][I]: Try 'link --help' for more information.
Thu May 21 10:05:06 2020 [Z0][VMM][E]: pre: Command "sudo -n ip link add name vx200 type bridge stp_state 0" failed.
Thu May 21 10:05:06 2020 [Z0][VMM][E]: pre: RTNETLINK answers: File exists
Thu May 21 10:05:06 2020 [Z0][VMM][E]: RTNETLINK answers: File exists
Thu May 21 10:05:06 2020 [Z0][VMM][E]:
Thu May 21 10:05:06 2020 [Z0][VMM][I]: ExitCode: 2
Thu May 21 10:05:06 2020 [Z0][VMM][I]: Failed to execute network driver operation: pre.
Thu May 21 10:05:06 2020 [Z0][VMM][E]: Error deploying virtual machine: vxlan: RTNETLINK answers: File exists
```

**To Reproduce**
The problem is not reproduced when the first virtual machine with a network in VXLAN is created on one hypervisor, this problem is observed when the second or more virtual machines in this VXLAN are created on one hypervisor

**Details**
 - Affected Component: [Deploy VM]
 - Hypervisor: [e.g. KVM]
 - Version: 5.11.85

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Ilyashestopalov** [comment]
can't send MR
[ianr@itsmy:~/Development/git/one]$  git push origin issue-4794
Username for 'https://github.com': Ilyashestopalov
Password for 'https://Ilyashestopalov@github.com': 
remote: Permission to OpenNebula/one.git denied to Ilyashestopalov.
fatal: «https://github.com/OpenNebula/one.git/» недоступно: The requested URL returned error: 403
diff:
`[ianr@itsmy:~/Development/git/one]$ git diff src/vnm_mad/remotes/lib/vlan.rb
diff --git a/src/vnm_mad/remotes/lib/vlan.rb b/src/vnm_mad/remotes/lib/vlan.rb
index a0329b18b..e0fed8201 100644
--- a/src/vnm_mad/remotes/lib/vlan.rb
+++ b/src/vnm_mad/remotes/lib/vlan.rb
@@ -147,7 +147,7 @@ module VNMMAD
             return if @bridges.key?(@nic[:bridge])
 
             OpenNebula.exec_and_log("#{command(:ip)} link add name " \
-                "#{@nic[:bridge]} type bridge #{list_bridge_options}")
+                "#{@nic[:bridge]} type bridge #{list_bridge_options}", nil, 2)
 
             @bridges[@nic[:bridge]] = []`

**Comment by xorel** [comment]
If the bridge already exists the driver should not try to create it but skip 
`147             return if @bridges.key?(@nic[:bridge])`

What OS + versoin do you run?

**Comment by Ilyashestopalov** [comment]
OS: CentOS Linux release 7.7.1908 (Core) 
Kernel: 4.4.182-1.el7.elrepo.x86_64
iproute: iproute-4.11.0-25.el7.x86_64

**Comment by xorel** [comment]
Can no reproduce, could you paste the VM and VNET template here?

**Comment by Ilyashestopalov** [comment]
VNET 
----------------------------
BRIDGE = "vx200"
BRIDGE_TYPE = "linux"
DNS = "10.99.9.2 10.99.9.1 10.99.9.3"
GATEWAY = "10.99.12.1"
GUEST_MTU = "1500"
MTU = "1500"
NETWORK_ADDRESS = "10.99.12.0"
NETWORK_MASK = "255.255.255.0"
OUTER_VLAN_ID = ""
PHYDEV = "eth0"
SEARCH_DOMAIN = "ad.rambler.tech"
SECURITY_GROUPS = "0"
VLAN_ID = "200"
VN_MAD = "vxlan"

VM
----------------------------
CONTEXT = [
  CM_ENVIRONMENT_U = "$CM_ENVIRONMENT_U",
  CM_NEED_AUTODEPLOY_U = "$CM_NEED_AUTODEPLOY_U",
  CM_NEED_REGISTER_U = "$CM_NEED_REGISTER_U",
  CM_PROJECT_U = "$CM_PROJECT_U",
  CM_SWITCH = "ONE-VX200",
  CM_ZABBIX_PROXY_SERVER_U = "$CM_ZABBIX_PROXY_SERVER_U",
  DNS_HOSTNAME = "YES",
  NETWORK = "YES",
  REPORT_READY = "YES",
  SSH_PUBLIC_KEY = "xxx",
  TOKEN = "YES",
  USERNAME = "ansible",
  VM_NEEDS_EMERGENCY_EVACUATION = "$VM_NEEDS_EMERGENCY_EVACUATION" ]
CPU = "1"
CPU_COST = "0.12"
CPU_MODEL = [
  MODEL = "host-passthrough" ]
DISK = [
  DEV_PREFIX = "vd",
  IMAGE = "CentOS-7.7-ADTECH-PROD",
  IMAGE_UNAME = "pppp",
  READ_BYTES_SEC = "62914560",
  WRITE_BYTES_SEC = "62914560" ]
DISK_COST = "0.00007421875"
GRAPHICS = [
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
HYPERVISOR = "kvm"
INPUTS_ORDER = "CM_PROJECT_U,CM_ENVIRONMENT_U,CM_ZABBIX_PROXY_SERVER_U,CM_NEED_REGISTER_U,CM_NEED_AUTODEPLOY_U,VM_NEEDS_EMERGENCY_EVACUATION"
LOGO = "images/logos/centos.png"
MEMORY = "4096"
MEMORY_COST = "0.000015625"
MEMORY_UNIT_COST = "GB"
NIC = [
  INBOUND_AVG_BW = "125000",
  NETWORK = "ONE-VX200",
  NETWORK_UNAME = "pppp",
  OUTBOUND_AVG_BW = "125000",
  SECURITY_GROUPS = "0" ]
NIC_DEFAULT = [
  MODEL = "virtio" ]
OS = [
  ARCH = "x86_64",
  BOOT = "" ]
SCHED_DS_REQUIREMENTS = "ID=\"156\" | ID=\"157\""
SCHED_REQUIREMENTS = "CLUSTER_ID=\"105\""
USER_INPUTS = []
VCPU = "2"

**Comment by xorel** [comment]
Although, this is already "fixed". Could you rember if you hit this issue when deploying more VMs in parallel? Also, could you run commands (as oneadmin)?
`ip link show type bridge`
`ip link show master vx200` 
and paste the output?

**Comment by Ilyashestopalov** [comment]
Hi, issue is when creating one instance if another instance in the same VxLAN exists on the host machine. If at the time of creation there is no other instance on the hypervisor in the same VxLAN network, then the creation of the bridge is successful.
Output:
```
[oneadmin@1node0002 ~]$ ip link show type bridge
14: br-ext: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ac:1f:6b:3a:64:94 brd ff:ff:ff:ff:ff:ff
15: vx200: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 9a:09:d3:00:7c:88 brd ff:ff:ff:ff:ff:ff
```
and
```
[oneadmin@1node0002 ~]$ ip link show master vx200
16: eth0.200: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 9a:09:d3:00:7c:88 brd ff:ff:ff:ff:ff:ff
23: one-962-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:01:b0:03 brd ff:ff:ff:ff:ff:ff
35: one-1039-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:01:b0:12 brd ff:ff:ff:ff:ff:ff
36: one-1036-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:01:b0:0f brd ff:ff:ff:ff:ff:ff
37: one-1035-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:01:b0:0e brd ff:ff:ff:ff:ff:ff
56: one-1237-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:01:b0:08 brd ff:ff:ff:ff:ff:ff
57: one-1240-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb master vx200 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:01:b0:1b brd ff:ff:ff:ff:ff:ff
```
