### ISSUE TITLE
can't change the number of characters in param list defined in LOG_CALL_FORMAT

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4819]
**Description**
When developing a driver I usually enable more details in the logs via `%l` parameter in the LOG_CALL_FORMAT

**To Reproduce**
Instantiate 5.12 beta
Configure the log format to something different than default, for example `%l200`
Restart opennebula and monitor the logs

```
Wed May 27 08:58:07 2020 [Z0][ReM][D]: Req:7296 UID:0 IP:127.0.0.1 one.vm.monitoring invoked , 8
Wed May 27 08:58:07 2020 [Z0][ReM][D]: Req:7296 UID:0 one.vm.monitoring result SUCCESS, "<MONITORING_DATA><MO..."
Wed May 27 08:58:15 2020 [Z0][ReM][D]: Req:3328 UID:0 IP:127.0.0.1 one.user.info invoked , 0, false
Wed May 27 08:58:15 2020 [Z0][ReM][D]: Req:3328 UID:0 one.user.info result SUCCESS, "<USER><ID>0</ID><GID..."
Wed May 27 08:58:33 2020 [Z0][ReM][D]: Req:8416 UID:0 IP:127.0.0.1 one.user.info invoked , 0, false
Wed May 27 08:58:33 2020 [Z0][ReM][D]: Req:8416 UID:0 one.user.info result SUCCESS, "<USER><ID>0</ID><GID..."
Wed May 27 08:58:33 2020 [Z0][ReM][D]: Req:3856 UID:0 IP:127.0.0.1 one.vm.info invoked , 3, false
Wed May 27 08:58:33 2020 [Z0][ReM][D]: Req:3856 UID:0 one.vm.info result SUCCESS, "<VM><ID>3</ID><UID>0..."
Wed May 27 08:58:34 2020 [Z0][ReM][D]: Req:7456 UID:0 IP:127.0.0.1 one.vm.monitoring invoked , 3
Wed May 27 08:58:34 2020 [Z0][ReM][D]: Req:7456 UID:0 one.vm.monitoring result SUCCESS, "<MONITORING_DATA><MO..."
Wed May 27 08:58:37 2020 [Z0][ReM][D]: Req:912 UID:0 IP:127.0.0.1 one.zone.raftstatus invoked 
Wed May 27 08:58:37 2020 [Z0][ReM][D]: Req:912 UID:0 one.zone.raftstatus result SUCCESS, "<RAFT><SERVER_ID>-1<..."
```

**Expected behavior**
The defined number of characters should be logged instead of the default 20

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @atodorov-storpool, the `%l` option of `LOG_CALL_FORMAT` attribute increase the length of the input parameters, so you can retrieve more info on how the API call was performed, but it do not modify the length of the output:

```
%l[number] -- param list and number of characters (optional) to print each parameter, default is 20. 
``` 
Having the parameters you can recreate the call by using the API and check the output.

(I've tested it using 648fe67f152b5602ef0615bf096d775c96d6bdc8)
