### ISSUE TITLE
ONE package definitions

### ISSUE THREAD

**Issue by Fnux** [OpenNebula/one#4844]
Hi!

I couldn't find where the RPM/DEB package definitions (e.g. specfile for RPM) are maintained. Either I missed them or they are not tracked here: in the later case, would it be possible to publish them?

I'm currently playing with alpine-based ONE hosts and might end up doing some packaging work which could be upstreamed here.

Thanks!

**Comment by kvaps** [comment]
Wow, it seems that repository was deleted (or moved to private repository).
Previously it was located on https://github.com/opennebula/packages/, now you can still find some forks on github, eg. my one with the latest changes which I managed to find: https://github.com/kvaps/packages

**Comment by sambhavsaggi** [comment]
How come? Using the package feature was very useful for easy testing / deployment.

**Comment by howels** [comment]
We are also baffled as to the disappearance of everything under https://github.com/OpenNebula/packages/releases and https://github.com/OpenNebula/packages without clear substitute anywhere else.  Is anyone able to comment on why part of the project is now hidden?

**Comment by sambhavsaggi** [comment]
Perhaps one of the owners / top contributers can chime in: @tinova @vholer @rsmontero @xorel @christian7007 @al3xhh

**Comment by albert0marti** [comment]
Hi guys! We are doing some changes in the structure of the repos, etc. in preparation for the release of **OpenNebula 5.12 "Firecracker"**. We'll be publishing a proper announcement and a summary of all these changes in a couple of days max. Thanks for your patience!

**Comment by howels** [comment]
@albert0marti excited to hear about the upcoming 5.12 release and congratulations to the team.  However please explain the situation to people in the community who are working to test and setup OpenNebula 5.10.x and 5.11.x and need the packaging resources. 
Right now it looks like resources have been hidden from the community or deleted by accident.  Understand you may want to lock a branch for new releases but keeping existing code in other branches available would be really helpful.
If there has been a change of policy and you are withdrawing the packaging code then we would like some warning to prepare for that before the code is removed instead of afterwards.  We were preparing for an upgrade when this happened. Thanks for your help.

**Comment by albert0marti** [comment]
Hi there!

Thank you all for your patience! Here you have the details about this decision: https://forum.opennebula.io/t/towards-a-stronger-opennebula-community/8506
Hope this helps to clarify the new scenario.

Just to make it clear: access to the packages repo is NOT one of the benefits that comes with the OpenNebula Subscription (https://opennebula.io/enterprise/). Although the repo is now private again, and only accessible in principle to the OpenNebula Team, **active members of the community** can request access.

**Comment by howels** [comment]
We are new users of Opennebula and unfortunately this aggressive open-core model will make us reconsider our choice. Sorry to hear that this was the path you chose.

**Comment by albert0marti** [comment]
Hi @howels,

The OpenNebula Community Edition is a **full-featured version of OpenNebula**, and OpenNebula CE and EE are synchronized at the end of each maintenance cycle, so we are not speaking here about an _open core_ model. Please refer to our [Release Policy](https://github.com/OpenNebula/one/wiki/Release-Policy) for more details. 

The **source code** (https://github.com/OpenNebula/one/) and the **binary and source packages** that we produce for the Community Edition (http://downloads.opennebula.io/repo/) are publicly available, given that the CE is under the [Apache License 2.0](https://github.com/OpenNebula/one/blob/master/LICENSE), but if you—for whatever reason—need access to our internal repo for package definitions, just send me a PM.
