### ISSUE TITLE
Missing /usr/lib/one/mads/collectd in 5.11.85-1 Ubuntu 20.04 package

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#4863]
**Description**

OpenNebula 5.12 beta can't start on Ubuntu 20.04.

The packaging of OpenNebula 5.11.85-1 for Ubuntu 20.04 is missing `/usr/lib/one/mads/collectd`

```
grep -F '[E]' /var/log/one/oned.log
Tue Jun  2 09:40:44 2020 [Z0][InM][E]: File not exists: /usr/lib/one/mads/collectd
Tue Jun  2 09:40:44 2020 [Z0][ONE][E]: Could not load driver
```

**To Reproduce**

- on an Ubuntu 20.04
- Install OpenNebula with packages from http://downloads.opennebula.io/repo/5.11
- Look in `/var/log/one/oned.log`

**Expected behavior**

The service should start.

**Details**
 - Affected Component: Controller daemon (opennebula.service)
 - Hypervisor: KVM
 - Version: 5.11.85-1

**Additional context**

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
can you double check with a 5.12 stock oned.conf?

**Comment by baby-gnu** [comment]
Ok, it's my fault, I badly adapt my configuration file.

Thanks and sorry.
