### ISSUE TITLE
Initial start monitor messages delayed on ubuntu 16.04

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#4867]
**Description**
Initial start monitor message delayed from FE -> H and also H -> FE on ubuntu 16.04

**To Reproduce**
Install OpenNebula 5.12 on Ubuntu 16.04
Create KVM host

_In logs:_
```
FE: Mon Jun  1 13:08:09 2020 [Z0][HMM][D]: Monitoring host ubuntu1604-kvm-ceph-ssh-luminous-5-11-90-b5d04-1.test(0)
H: 2020-06-01 13:10:25 run_once: start                                                
H: 2020-06-01 13:10:30 run_once: stop
H: 2020-06-01 13:10:30 run_once sending data: [<MONITOR_MESSAGES>...</MONITOR_MESSAGES>] 
FE: Mon Jun  1 13:11:27 2020 [Z0][MDP][D]: Received start monitor for host 0: <MONITOR_MESSAGES>
```

When the ControlMaster directives are commented in **.ssh/config** the messages delay disappear. 

**Expected behavior**
Not such a long delays between messages.

**Details**
 - Affected Component: .ssh/config
 - Hypervisor: KVM
 - Version: 5.12

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
On Ubuntu 16.04, the SSH process which serves as ControlMaster doesn't close the stderr properly (https://bugzilla.mindrot.org/show_bug.cgi?id=1988) and OpenNebula stuck on reading from the unclosed descriptor forever.

Fixed by https://github.com/OpenNebula/one/pull/4886
