### ISSUE TITLE
Implement update operation in OneFlow

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4912]
**Description**
Currently there is no way to update a running service.

**Use case**
It would be great to be able to update any parameters in a running service.

**Interface Changes**
OneFlow server, CLI and Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/89)
- [docs](https://github.com/OpenNebula/docs/pull/1240)
- [docs](https://github.com/OpenNebula/docs/pull/1241)
- [tests](https://github.com/OpenNebula/development/pull/1131)

**Comment by tinova** [comment]
merged only in master (no new features in one-5.12)
