### ISSUE TITLE
Allow multiple LDAP configurations based on username pattern

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#4924]
**Description**
Allow multiple LDAP configurations based on username pattern

**Use case**
Allow different organizations to use separate LDAP configuration based on username matching patterns.

**Interface Changes**
instead of the simple order
```
 :order:
     - server1
     - server2
     - server3
```
configuration can be
```
:match_user_regex:
    ".*@orgA.com":  serverA
    ".*@orgB.com":  serverB
```

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Great Idea!
It would nice to make this setting configurable globally for other authentication mechanisms too.

Eg I have two type of users: `public` (customers) and `ldap` (company employees) 

I want to allow customers authenticate over the public sunstone interface and API endpoint and allow employees authenticate only over the private sunstone interface and API endpoint.

Also It would be nice to have an opportunity to setup the default domain for some authentication method.

Eg. `public` users might use login without suffix, and `ldap` users must provide something like `@example.org` in their login.
