### ISSUE TITLE
error resizing disk is not reported in sunstone

### ISSUE THREAD

**Issue by mouyaq** [OpenNebula/one#4928]
**Description**
When an error is reporting in oned.log resizing disks, this error is not showing in sunstone.

**To Reproduce**
1.  Create an instance in vCenter.
2. Create a snapshot
3. Try to resize any instance disk.

A message should appear in oned.log indicating that the operation cannot be done because there is a snapshot, but sunstone doesn't show an error.

**Expected behavior**
Sunstone should show the error.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 5.12

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/49
- Docs: https://github.com/OpenNebula/docs/pull/1227
