### ISSUE TITLE
Support for vSphere 7.0

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#4933]
**Description**

OpenNebula support for 7.0 vSphere version

**Use case**

Being able to manage a 7.0 vSphere env from OpenNebula.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
We need to update to rbvmomi 3.0.0

**Comment by vholer** [comment]
Note: rbvmomi 3.0 requires Ruby>=2.4

**Comment by carloshm91** [comment]
https://rubygems.org/gems/rbvmomi
Ruby >= 2.4.1
