### ISSUE TITLE
docker-machine-driver-opennebula does not properly work with Rancher

### ISSUE THREAD

**Issue by meier-rene** [OpenNebula/one#4934]
**Description**
I reported the same issue in #4052, but this issue got closed and there were some commits, which should fix this. Now I tried it with 5.12, but unfortunately its not working. So here is the issue again:

I'm using opennebula and the docker-machine-driver-opennebula to provision hosts for kubernetes/Rancher. If I delete a host in rancher, rancher deletes the host through opennebula and creates a new one. Unfortunately the new host is already created before the old one is finally removed. That's why rancher is failing with " Error creating machine: Error in driver during machine creation: multiple resources with that name."

 **To Reproduce**
Please follow the steps I provided in #4052. Please note: I provided the new docker-machine-driver-opennebula from 5.12.0 with a tgz to rancher. 

**Expected behavior**
A new host should be created after the old one gets deleted.

**Details**
Opennebula 5.12.0
Rancher 2.4.4

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by km4rcus** [comment]
Hi @meier-rene 

we have followed the steps as described in #4052 and used the OpenNebula 5.12 docker machine driver, but we didn't get any error when deleting a Rancher node from the cluster. To try to reproduce the issue, we have created in OpenNebula VMs with the same name as the nodes in Rancher before deleting a node. 

We have also tested a release before the bugfix for #4052 and in that case we can reproduce the issue as you described.

We have uploaded on S3 the tgz of the docker machine driver for OpenNebula 5.12 (https://docker-machine-one.s3.eu-central-1.amazonaws.com/docker-machine-driver-opennebula.tgz);  can you please test your environment with this driver?

For the moment we are going to close the issue. In case let us know if you still encounter the issue described.

Thanks
