### ISSUE TITLE
Database version mismatch ( local_db_versioning). Installed OpenNebula 5.11.90  needs DB version '5.12.0', and existing DB version is '5.10.0'.

### ISSUE THREAD

**Issue by Githopp192** [OpenNebula/one#4938]
**Description**
Did make an upgrade to OpenNebula 5.11.90 from 5.10.1.
(same occurs when upgrading to ON 5.12)
Started "onedb -upgrade" 
But upgrade is writing "Database already uses version 5.10.0" !?

See also the errors in /var/log/one/oned.log
 
**To Reproduce**
Steps to reproduce the behavior --> repeat the the upgrade and run onedb upgrade

**Expected behavior**
After OpenNebula upgrade to a new version, the "onedb upgrade" should recognize the current opennebula installation and should do the db upgrade

**Details**
 - Affected Component: onedb database (mariadb: 5.5.5-10.3.17-mariadb)
 - Hypervisor: KVM
 - Version: 5.11.90

**Additional context**
Version read:
Shared tables 5.10.0 : OpenNebula 5.9.80 (354cdae4) daemon bootstrap
Local tables  5.10.0 : OpenNebula 5.9.80 (354cdae4) daemon bootstrap

MySQL dump stored in /var/lib/one/mysql_localhost_opennebula_2020-6-18_23:42:30.sql
Use 'onedb restore' or restore the DB using the mysql command:
mysql -u user -h server -P port db_name < backup_file

>>> Running migrators for shared tables
Database already uses version 5.10.0

>>> Running migrators for local tables
Database already uses version 5.10.0

Total time: 0.78s

/one/lib/one/oned.log -->

Thu Jun 18 22:49:12 2020 [Z0][ONE][I]: Log level:3 [0=ERROR,1=WARNING,2=INFO,3=DEBUG]
Thu Jun 18 22:49:12 2020 [Z0][ONE][I]: Support for xmlrpc-c > 1.31: yes
Thu Jun 18 22:49:12 2020 [Z0][ONE][I]: Using hostname: sunstone
Thu Jun 18 22:49:12 2020 [Z0][ONE][I]: Set up 50 DB connections using encoding latin1
Thu Jun 18 22:49:12 2020 [Z0][ONE][I]: Using 5.5.5-10.3.17-mariadb (100317) with:
Thu Jun 18 22:49:12 2020 [Z0][ONE][I]:  FTS enabled
Thu Jun 18 22:49:12 2020 [Z0][ONE][I]: Checking database version.
Thu Jun 18 22:49:12 2020 [Z0][ONE][E]: Database version mismatch ( local_db_versioning). Installed OpenNebula 5.11.90 (a4d7bebc) needs DB version '5.12.0', and existing DB version is '5.10.0'.
Thu Jun 18 22:49:12 2020 [Z0][ONE][E]: Use onedb to upgrade DB.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by bgmastermind** [comment]
I have the same issue.
Version read:
Shared tables 5.10.0 : Database migrated from 5.6.0 to 5.10.0 (OpenNebula 5.9.80) by onedb command.
Local tables  5.10.0 : Database migrated from 5.8.0 to 5.10.0 (OpenNebula 5.9.80) by onedb command.

MySQL dump stored in /var/lib/one/mysql_localhost_opennebula_2020-6-22_11:13:9.sql
Use 'onedb restore' or restore the DB using the mysql command:
mysql -u user -h server -P port db_name < backup_file


>>> Running migrators for shared tables
Database already uses version 5.10.0

>>> Running migrators for local tables
Database already uses version 5.10.0

**Comment by svdasein** [comment]
I believe what's going on here - and boy howdee I hope I'm wrong - is that the folks at opennebula are attempting to get commercial support contracts from people by gatekeeping the database migration logic to 5.12.  

Not being aware of what they're trying to do, I started a migration from 5.10.1 to 5.12.  I did all the manual config file merging and all that, and then ran the onedb upgrade - and it did nothing.  onedb fsck says "version mismatch".  

If you go here:  http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html  - you'll notice at Step 7 a little note saying that I may upgrade to 5.12 if I fill out a form stating that I'm either non-commercial or have made substantial contributions to the community.

The release package they're bundling contains code that migrates to 5.10 but no further.

If this is really what they're going for, it's just plain slimy.  Really. And if they're attempting to hide source code...

**Comment by bgmastermind** [comment]
No you are not wrong, that's exactly it. I learned it the same way. When I got to onedb upgrade, which failed. 
At least the message there should be updated. If you want to update pay up.

**Comment by albert0marti** [comment]
Hi there!

The final version of the migrators to 5.12 is now only available for customers with an active [OpenNebula Subscription](https://opennebula.io/subscriptions/) and for users with non-commercial deployments or with significant contributions to the OpenNebula Community.

We announced this change (among some others) on our blog, social media and Community Forum several weeks ago: https://forum.opennebula.io/t/towards-a-stronger-opennebula-community/8506 Sorry to hear you guys missed that announcement.

In any case, please have a look at our new [Release Policy](https://github.com/OpenNebula/one/wiki/Release-Policy) and, if you think your case qualifies as a **non-commercial deployment**, then you just need to submit the following form to request free access to the migrator packages: https://opennebula.io/get-migration/

Cheers!

**Comment by horstmannmat** [comment]
I find this outrageous to ALL open source community, and free (libre) Software.
How would you feel if  Linus decides to release a new version of kernel only to "members with an active subscription and non-commercial deployments or with significant contributions"? 

You probably use lot of open source binaries to develop your software, and we use yours to build ours, so why make things so hard? In our case, per example, we are the biggest open source mirror of the whole south hemisphere, and we user your software to do this, so now I need to request this migrator to run a simple upgrade, that would be 1 hour of our work, now can take longer than expected.

The open source community lives of this Mutualism, everybody using and helping each other software, that is a really win-win situation. Now I just don't know what to say, I just hope that you decides to revert this decision as soon as possible.

Makes no sense to give a "free car with no engine, and make they buy or ask for a extra-engine to make the car running"

**Comment by albert0marti** [comment]
Hi @horstmannmat,

Sorry to hear you disagree with these changes. Our Executive Director clarified the reasons behind this policy change in the [original announcement](https://opennebula.io/introducing-opennebula-enterprise-edition/), including the fact that "_We are big believers in open source. We have invested most of our time and resources over the last 10 years to create the best open source Cloud Management Platform for the enterprise world. However, **the original concept of open source has to be adapted** to the current circumstances because it is profoundly unfair for the community when large corporations adopt a successful open source project without contributing to make the project sustainable in the long term_."

As for the 5.10 > 5.12 migrators, community users (or corporate users with non-commercial deployments or with significant contributions to the OpenNebula Community) only need to submit a simple online form to **get access to the migration packages**: https://opennebula.io/get-migration/ Compared with the decade of hard work we've invested in developing OpenNebula, that sounds quite fair to us... Still, OpenNebula CE is released under the **Apache License 2.0**, so if you find that procedure unacceptable for whatever reason, just remember that your user rights remain intact, so you can keep using you current 'car' (OpenNebula 5.10, I guess?) for as long as you wish :)
