### ISSUE TITLE
OpenNebula community fourm in read only mode

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4940]
**Description**
Hi, is there something wrong with OpenNebula forum? I can't post to it:

![image](https://user-images.githubusercontent.com/7556217/85144434-739a3a00-b24b-11ea-81cf-1ee0c853104a.png)

**To Reproduce**
Try to write any message or put some ❤️

**Expected behavior**
Ability to post or giving the likes.

**Details**
 - Affected Component: OpenNebula Forum
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
IMHO it was some maintenance on Discourse side.
I have seen that as well, it's over already.
