### ISSUE TITLE
Ignore NIC configuration on EC2 deployments

### ISSUE THREAD

**Issue by rdiaz-on** [OpenNebula/one#4942]
**Description**
When using [hybrid VM templates](http://docs.opennebula.io/5.12/advanced_components/cloud_bursting/ec2g.html#hybrid-vm-templates) the NIC attribute -which must be interpreted on KVM deployments- is taken into account on EC2 deployments.

**To Reproduce**
Create and hybrid VM template with a NIC attached to a Virtual Nework with `VN_MAD=fw` and start the VM on a EC2 node. An error similar to this will occur:

```Wed Jun 3 16:23:00 2020 [Z0][VMM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/vnm/fw/post ‘i-0a45d912cacb04500’
Wed Jun 3 16:23:00 2020 [Z0][VMM][I]: iptables v1.6.1: interface name --physdev-is-bridged' must be shorter than IFNAMSIZ (15) Wed Jun 3 16:23:00 2020 [Z0][VMM][I]: Try iptables -h’ or ‘iptables --help’ for more information.
Wed Jun 3 16:23:00 2020 [Z0][VMM][E]: post: Command Error: sudo iptables -I opennebula -m physdev --physdev-out --physdev-is-bridged -j one-315-0-i
Wed Jun 3 16:23:00 2020 [Z0][VMM][E]: post: ["/var/lib/one/remotes/vnm/command.rb:61:in block in run!'", "/var/lib/one/remotes/vnm/command.rb:58:in each’", “/var/lib/one/remotes/vnm/command.rb:58:in run!'", "/var/lib/one/remotes/vnm/security_groups_iptables.rb:485:in nic_pre’”, “/var/lib/one/remotes/vnm/sg_driver.rb:92:in block in activate'", "/var/lib/one/remotes/vnm/vnm_driver.rb:81:in block in process’”, “/var/lib/one/remotes/vnm/vm.rb:64:in block in each_nic'", "/var/lib/one/remotes/vnm/vm.rb:63:in each’”, “/var/lib/one/remotes/vnm/vm.rb:63:in each_nic'", "/var/lib/one/remotes/vnm/vnm_driver.rb:84:in process’”, “/var/lib/one/remotes/vnm/sg_driver.rb:84:in activate'", "/var/lib/one/remotes/vnm/fw/post:32:in '”]
Wed Jun 3 16:23:34 2020 [Z0][VMM][I]: Successfully execute virtualization driver operation: cancel.
Wed Jun 3 16:23:34 2020 [Z0][VMM][I]: Failed to execute network driver operation: post.
Wed Jun 3 16:23:34 2020 [Z0][VMM][E]: Error deploying virtual machine: fw: -
Wed Jun 3 16:23:34 2020 [Z0][VM][I]: New LCM state is BOOT_FAILURE
```

**Expected behavior**
The NIC configuration should only be used in hybrid VM templates for KVM deployments.

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: development

**Additional context**
[Forum issue](https://forum.opennebula.io/t/error-while-deploying-ec2-via-opennebula-iptables-v1-6-1-interface-name-physdev-is-bridged-must-be-shorter-than-ifnamsiz-15/8373).

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Bug also applies for Azure driver.
