### ISSUE TITLE
Sunstone doesn't ask for user inputs

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4946]
**Description**
If VM template is defined with user inputs, Sunstone in 5.12.0 ignores them and doesn't show the area for Custom Attributes where user can place his choices. E.g., an example for `Service WordPress - KVM` downloaded from OpenNebula Public Marketplace:

![image](https://user-images.githubusercontent.com/414850/85392965-8a42d880-b54c-11ea-9afd-7d57835aac7d.png)

See no option to place blog name, etc.

**To Reproduce**
- Import Service WordPress appliance from OpenNebula Public Marketplace
- Try to instantiate template and don't find the "Custom Attributes" section

**Expected behavior**
Expect to see place to enter user inputs, e.g.:

![image](https://user-images.githubusercontent.com/414850/85392838-61224800-b54c-11ea-9473-32111f0f75e3.png)

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/46
- Docs: https://github.com/OpenNebula/docs/pull/1225

**Comment by Kazyini** [comment]
When will this be released in the normal version? I find it very unpleasant that such big bugs are only fixed in the paid version and you can't even fix it yourself because the pull request is not publicly visible. This is not a nice kind of OpenSource.

**Comment by tinova** [comment]
Commits are periodically synced for the master (main?) branch, usually there is a 1 week delay. This has been available for well over two months in the public repo.

This fix will make it into the next major version of OpenNebula, as well as the next maintenance release of the CE.

**Comment by TreZc0** [comment]
When is this next maintenance release planned? Apparently there is no milestone for it, the last release has been 3 months ago, and there have been multiple maintenance release for EE since then.
This is a gamebreaking bug, especially for more automated environments, for example with Ansible, that rely on User Inputs to define the directory.

**Comment by tinova** [comment]
Hi, please check the [Release Policy](https://github.com/OpenNebula/one/wiki/Release-Policy), in particular the section about the [Community Edition](https://github.com/OpenNebula/one/wiki/Release-Policy#opennebula-community-edition).

While we do not produce regular maintenance releases for the Community Edition, we are however planning a 5.12.0.2 release for next week that will include this particular fix. 

If a hardened and stable OpenNebula is needed to be run in a production environment with a critical workload, we recommend using the Enterprise Edition that implements a more frequent release cycle with the latest bugfixes.

**Comment by TreZc0** [comment]
Thanks for the update and the link to the release policy.
While I personally think that the sheer amount of commits I can see for 5.12.0.2 shows that this policy might not work out all that well and means significant flaws for a great community tool, I can get the switch in focus for ON. 

I highly appreciate that you push a release anyways, it will really help me. Given that I host the cluster in question for purely 
charitable non-profit means, EE is sadly not an option, and it's great to see that you still support these cases with maintenance releases if absolute need be.

**Comment by darkfritz2** [comment]
i find this attitude from opennebula not ok. it will destroy the community.
EE is at 5.12.4
while CE is at 5.12.0.1
that is a lot of bug fixing you did there which you're holding only for your paid customers.
of course the current version is working but it's like giving a car with 3 wheels because it somehow works, instead of the full 4 wheel car.

**Comment by albert0marti** [comment]
Hi guys! We've launched a **new CE Patch Release** a few days ago with a number of bug fixes, please check it out: https://forum.opennebula.io/t/ce-patch-release-5-12-0-3-is-available/8885

@darkfritz2, apart from the CE Patch releases, you'll see at our [Release Policy](https://github.com/OpenNebula/one/wiki/Release-Policy) that "_for each new major or minor release, OpenNebula Systems contributes to the Community Edition all bug fixes and software patches with minor enhancements that have been developed and incorporated into an Enterprise Edition version during the previous maintenance cycle_." So, to sum up, and using your own terms... 😜

![OpenNebula_ReleasePolicy](https://user-images.githubusercontent.com/57350829/96294360-8996ec00-0fec-11eb-877e-6c77084e8e2f.jpeg)
