### ISSUE TITLE
Sunstone VNC button doesn't show after VM switches to RUNNING

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4948]
**Description**

(I thought I have already reported this, but I can't find it) When VM details are opened when VM is not in RUNNING state yet (e.g., still in PROLOG), the button to connect to VNC/... doesn't show after VM switches into RUNNING. E.g. see no button for VNC here:

![image](https://user-images.githubusercontent.com/414850/85422583-0ef61c80-b576-11ea-845c-17b93dd07651.png)

when opened once again (while VM is RUNNING), it's already there:

![image](https://user-images.githubusercontent.com/414850/85423020-7f9d3900-b576-11ea-9634-3c7d16b3fd14.png)

**To Reproduce**
- run VM
- go into Instances -> VMs -> click on particular VM
- ensure VM is not yet RUNNING, don't find VNC
- wait and reload, until VM is RUNNING
- check there is no way to connect VNC

**Expected behavior**
VNC button appears.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee#39
- doc: OpenNebula/docs#1221

**Comment by vholer** [comment]
Reopening, should be backported also into CE.
