### ISSUE TITLE
CLI commands with JSON output

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4950]
**Description**
CLI commands provide formated, CSV or XML output. Introduce JSON output `--json` to allow easy processing over `jq` etc.

**Use case**
Easier processing for people which are less familiar with `xmllint`.

**Interface Changes**
None. Just CLI tools, serialize XML content (1:1) as JSON.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
It would be nice to consider also yaml output.

**Comment by kvaps** [comment]
Yeah, and also to replace OpenNebula specific template format by something more common: eg. JSON or YAML would be super cool!

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/54)
- [docs](https://github.com/OpenNebula/docs/pull/1229)
- [tests](https://github.com/OpenNebula/development/pull/1109)
