### ISSUE TITLE
User Running VM quotas are shown incorrectly on cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4951]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Setting a Running VM Quota for a user is not shown correcly on the dashboard.

**To Reproduce**
Set a quota on a user. Example:

```
root@ubuntu2004-context-kvm-5-12-0-1-a91e1-0:~# onevm list
  ID USER     GROUP    NAME                                                                                STAT  CPU     MEM HOST                                                           TIME
   1 test     poor_use alpine-lxd-1                                                                        runn    1    128K ubuntu2004-context-kvm-5-12-0-1-a91e1-0.test               0d 00h47
   0 oneadmin oneadmin alpine-lxd-0                                                                        poff    1    768K ubuntu2004-context-kvm-5-12-0-1-a91e1-0.test               0d 09h16
root@ubuntu2004-context-kvm-5-12-0-1-a91e1-0:~# oneuser show 2
USER 2 INFORMATION                                                              
ID              : 2                   
NAME            : test                
GROUP           : poor_users          
SECONDARY GROUPS: 1,100               
PASSWORD        : b065663b91df7176a5d6567fddde2eb91b3ea73a5055c1f0915909f764d92cc6
AUTH_DRIVER     : core                
ENABLED         : Yes                 

TOKENS                                                                          

USER TEMPLATE                                                                   
TOKEN_PASSWORD="ddf24d1264891013a911f4c5e05c17fe75e3f27d0dabe315da7fe8367331e6fe"

VMS USAGE & QUOTAS                                                              

              VMS               MEMORY                  CPU     SYSTEM_DISK_SIZE
      1 /       -      128M /        -      1.00 /        -     1024M /        -

VMS USAGE & QUOTAS - RUNNING                                                    

      RUNNING VMS       RUNNING MEMORY          RUNNING CPU
      1 /       3      128M /        -      1.00 /        -

DATASTORE USAGE & QUOTAS                                                        

NETWORK USAGE & QUOTAS                                                          

IMAGE USAGE & QUOTAS                                                            

          ID          RUNNING VMS
           0         1 /        -

```

User has 3 Running VMs quota.

Log into sustone using the cloud view. Quota is properly shown on the config

![image](https://user-images.githubusercontent.com/33811723/85582460-11528800-b603-11ea-8b9e-f00f7936da1d.png)

However, it is not correctly shown on the dashboard

![image](https://user-images.githubusercontent.com/33811723/85583109-963da180-b603-11ea-8b5d-34343a2a5579.png)

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/52
- Docs: https://github.com/OpenNebula/docs/pull/1228
