### ISSUE TITLE
Datastore quotas not working as expected

### ISSUE THREAD

**Issue by rdiaz-on** [OpenNebula/one#4957]
**Description**
When configuring quotas for a group/user with `onegroup/oneuser quota <ID>`, and set the datastore quotas with through the `DATASTORE` attribute [1]:

```
DATASTORE = [
  ID     = <ID of the datastore>
  IMAGES = <Max. number of images in the datastore>
  SIZE   = <Max. storage capacity (Mb) used in the datastore>
]
```
The datastore quota seems to be configured although it is not supported for users/groups.

**To Reproduce**
Assign datastore quotas for a group/user with `onegroup/oneuser quota <ID>` and check no error triggered after saving the changes.

**Expected behavior**
An error must be triggered when assigning datastore quotas for a group/user. The [documentation](http://docs.opennebula.io/5.12/operation/users_groups_management/quota_auth.html) must be updated accordingly.

**Details**
 - Affected Component: Core
 - Hypervisor: all
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Works for me
