### ISSUE TITLE
onedb update-body from a text/xml file from stdin

### ISSUE THREAD

**Issue by lcami** [OpenNebula/one#4959]
**Description**
A method to update the DB details of an instance by specifying an XML file instead of opening an editor

**Use case**
To restore an instance, by restoring the XML file that was taken during the backup back into the DB

**Interface Changes**
Maybe a --file option in the CLI to specify the XML file

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
try:
```
EDITOR="tee" onedb update-body
```

**Comment by lcami** [comment]
> Hey, try this:
> 
> ```
> EDITOR="tee" onedb update-body
> ```
 Hey @kvaps and thanks for your suggestion. so what would be the entire command say to use vm.xml if I was originally using:

onedb update-body vm --id 100

as running EDITOR="tee" onedb update-body vm --id 100 does not give any output

**Comment by kvaps** [comment]
> running EDITOR="tee" onedb update-body vm --id 100 does not give any output

Because it is expecting input on stdin

Try two another examples:

```bash
onedb show-body vm --id 100 | EDITOR=tee onedb update-body vm --id 100
```

```bash
onedb show-body vm --id 100 > /tmp/1.xml
EDITOR="cp /tmp/1.xml" onedb update-body vm --id 100
```

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2047)
- [docs](https://github.com/OpenNebula/docs/pull/2272)
