### ISSUE TITLE
Limit resources per VM

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4961]
**Description**
Hi it would be nice to make an opportunity to limit the highest plank of CPU, vCPU, RAM and Disk Space created for each VM.

**Use case**
Users might be confused by creating the VM larger than hosts capable to handle it. Customer will see the VM stuck on PENDING state.

**Interface Changes**
Additional quotas for user and groups:

```
#  VM = [
#    INSTANCE_MEMORY           = <Max. allocated memory (MB) for one VM>
#    INSTANCE_CPU              = <Max. allocated CPU for one VM>
#    INSTANCE_VCPU             = <Max. allocated VCPU for one VM>
#    INSTANCE_SYSTEM_DISK_SIZE = <Max. allocated system disk (MB) for one VM>
#  ]
```

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Duplicate #822
