### ISSUE TITLE
Spelling mistake when logging

### ISSUE THREAD

**Issue by llakssz** [OpenNebula/one#4962]
I noticed a spelling mistake when going through a log file.
https://github.com/OpenNebula/one/blob/7b6b054b1a30ee37e23fabad6d85ee16c9907f28/src/raft/ReplicaThread.cc#L218
First word 'Faild' -> 'Failed' 🍍
Thanks for the great project!

**Comment by rsmontero** [comment]
THANKS! Fixed 500017b3be2e7f936446912e4088ab432191a83e
