### ISSUE TITLE
Importing LXD image without privileged permissions silently fails reporting success

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/one#4964]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Importing LXD image in constrained environment (e.g.: container) will report success but actually will store only empty disk. The reason for it is that mounting of the file as fs will silently fail due to restricted permissions.

**To Reproduce**
Run OpenNebula frontend in the container and try to import LXD image (you can try to use my project https://github.com/ospalax/onedocker) - the import will seem ok - but when you look inside the actual file - you will see only empty ext4 fs.

**Expected behavior**
Just fail.

**Details**
 - Affected Component: Storage
 - Hypervisor: LXD
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Added it also to resolved issues
