### ISSUE TITLE
Add service template registration time

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4966]
**Description**
Have the registration time for a Service Template so it is available in Sunstone and in the CLI.

**Use case**
Be aligned with other resources like VM templates, vRouter templates images and files.

**Interface Changes**
- OneFlow server
- CLI
- Sunstone

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
It would be great to add also service registration time in CLI and Sunstone.

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/372)
- [docs](https://github.com/OpenNebula/docs/pull/1337)

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/466
 - doc: https://github.com/OpenNebula/docs/pull/1369
