### ISSUE TITLE
Delete VM templates associated to a service template when deleting it

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4967]
**Description**
Add option to delete all the VM templates associated to a service template when it is deleted.

**Use case**
House keeping.

**Interface Changes**
- OneFlow server
- CLI
- Sunstone

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/373)
- [docs](https://github.com/OpenNebula/docs/pull/1338)
- [tests](https://github.com/OpenNebula/development/pull/1204)

**Comment by tinova** [comment]
Needs sunstone support

**Comment by jloboescalona2** [comment]
@tinova PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/590)
- [docs](https://github.com/OpenNebula/docs/pull/1397)
- [tests](https://github.com/OpenNebula/development/pull/1241)
