### ISSUE TITLE
Disable network configuration for service template instantiation 

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4968]
**Description**
Be able to disable the network tab when a service template is going to be instantiated.

**Use case**
This is not useful for end users, so hiding it would be great for those cases.

**Interface Changes**
Sunstone

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/462
 - doc: https://github.com/OpenNebula/docs/pull/1367
 - test: _pending_
