### ISSUE TITLE
--as_gid and --as_uid arguments are not available for onevm create command

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#4969]
**Description**
The `oenvm create` command help shows that `--as_gid` and `--as_uid` arguments are available but they are not supported by the `oned` for that call.

**Expected behavior**
CLI help do not show incorrect information.

**Details**
 - Affected Component: CLI

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.2 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/1783)
- [docs](https://github.com/OpenNebula/docs/pull/2156)
