### ISSUE TITLE
Evaluation of puma app server (instead of passenger)

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/one#4970]
**Description**
Added/verified support/functionality with puma app server: https://puma.io/

**Use case**
Puma seems to be more feature-rich and popular while being 100% open-source (passenger is not and some features are missing from community version)

**Interface Changes**
None

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Consider also [Falcon](https://github.com/socketry/falcon).

**Comment by tinova** [comment]
not applicable in #5422
