### ISSUE TITLE
Fix version bower dependencies

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#4972]
**Description**
fix version for all dependencies in bower javascript

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
closed as ruby sunstone will be deprecated by #5422
