### ISSUE TITLE
Redesign network tab in VM template form

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#4973]
**Description**
Redistribute elements for a more defined and minimalist design

**Use case**
Make the UX more comfortable and attractive

**Interface Changes**
![redesign-network-tab](https://user-images.githubusercontent.com/59608355/86941809-aa75b880-c144-11ea-837e-175fd5398da4.png)

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
also consider changes to the attach nic dialog on virtual router view
![image](https://user-images.githubusercontent.com/59608355/88694274-9a784580-d100-11ea-90a9-618a42014540.png)

**Comment by tinova** [comment]
to be redesign in #5422
