### ISSUE TITLE
CLI output contains extra columns

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4974]
**Description**
There are 2 related problems:

1. `onedatastore list` in 5.12 doesn't fit into 80 wide long terminal (every command should deal with 80 characters as standard and minimal width):

![image](https://user-images.githubusercontent.com/414850/87018967-51546600-c1d2-11ea-8dd2-53469f6a6262.png)

2. `onedatastore list` (and maybe other commands?) contains extra columns USER/GROUP new in 5.12.x, but these are not configured for default view 

https://github.com/OpenNebula/one/blob/500017b3be2e7f936446912e4088ab432191a83e/src/cli/etc/onedatastore.yaml#L61-L71

Probably fixing of 2 fixes also 1.

**To Reproduce**
Run `onedatastore list` on standard 80x24 terminal.

**Expected behavior**
Output fits into width.

**Details**
 - Affected Component: CLI
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/951)
- [docs](https://github.com/OpenNebula/docs/pull/1510)
