### ISSUE TITLE
Sunstone - resizing VM memory to GB does not work, sets MB instead

### ISSUE THREAD

**Issue by bgmastermind** [OpenNebula/one#4975]
**Description**
Resize VM memory when selecting GB does not work.  Instead it sets MB
Works with onevm resize vm1 --memory 16GB

**To Reproduce**
Write 16 GB and select GB from the dropdown. Memory is resized to 16MB

**Expected behavior**
To set 16GB

**Details**
 - Sunstone
 - KVM
 - 5.12.0

Instantiation also, creates the VM with MB instead of GB.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Madko** [comment]
Even when instantiating we have this problem. VM starts with 1MB instead of 1GB from the template.

**Comment by tinova** [comment]
This has been fixed in recent releases, please reopen if you can reproduce it in 6.0.0.2
