### ISSUE TITLE
CLI onevm updateconf Ruby error message

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4982]
**Description**

`onevm updateconf` on invalid VM fails on Ruby error:

```
$ onevm show 666
[one.vm.info] Error getting virtual machine [666].

$ onevm updateconf 666
undefined method `elements' for nil:NilClass
```

During `updateconf` above should fail on Error getting VM in both cases.

**Details**
 - Affected Component: CLI
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/100)
- [docs](https://github.com/OpenNebula/docs/pull/1246)
