### ISSUE TITLE
Default GRAPHICS section

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4984]
**Description**
I would like to enable vnc with random password for all the vms.

**Use case**
This would make the vnc-console secure by default, problem is that most users not understand value of this options and leaving vnc unsecured in most cases.

**Interface Changes**
New section on [vmm_exec_kvm.conf](https://github.com/OpenNebula/one/blob/master/src/vmm_mad/exec/vmm_exec_kvm.conf) file

```bash
GRAPHICS = [
  LISTEN = "0.0.0.0",
  RANDOM_PASSWD = "YES",
  TYPE = "VNC" ]
```

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
+1

**Comment by paczerny** [comment]
Release 6.2
