### ISSUE TITLE
Sunstone create VM Template wizard for azure is outdated

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#4986]
**Description**
Although in https://github.com/OpenNebula/one/issues/1203 the azure driver was reworked, the create VM Template wizard for azure remained the same.

Also the generated part `HYPERVISOR = AZURE` needs to be switchted to lowercase.

**Expected behavior**
create VM Template wizard for azure is updated with new Azure template variables

**Details**
 - Affected Component: [e.g. Sunstone]
 - Version: [e.g. 5.12]

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
hybrid drivers deprecated
