### ISSUE TITLE
GRAPHICS section lost from VM template when updating VM config as regular user

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#4987]
**Description**
When a regular user updates the VM config using Sunstone, the GRAPHICS section is lost.

**To Reproduce**
As a regular user (not oneadmin, not part of oneadmin group) using the User view in Sunstone, update the VM config (for example, add a new context variable). Graphics section will be lost and VNC will be disabled.

**Expected behavior**
Graphics section can not be removed.

**Details**
 - Affected Component: Sunstone
 - Version: 5.10.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
Looks like if the view has **input_output** setting on the template creation tab enabled, this will not happen. For multitenant environments it usually not desirable that users have access to input/output settings, instead they should use the defaults provided by the admin. If the indeed do not have access to the input_output settings from their VMs, besides this issue occurring users will have no way to turn VNC back on.

**Comment by sbbarragan** [comment]
- one: OpenNebula/one-ee#109
- doc: OpenNebula/docs#1250

**Comment by sergiojvg** [comment]
Thanks @sbbarragan
