### ISSUE TITLE
Can not configure RDP during instantiation

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#4988]
**Description**
If a NIC is indicated in the template as RDP, this will work. But, when instantiating a template with no NIC, or with a NIC where the RDP is not selected, and selecting it during instantiation, the new VM will not get the RDP attribute on the NIC. 

**To Reproduce**
Instantiate a template with no NICs, add a NIC during instantiation and mark the RDP option. This is the result:

```
    <NIC>
      <AR_ID><![CDATA[1]]></AR_ID>
      <BRIDGE><![CDATA[br1]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[linux]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[100,101]]></CLUSTER_ID>
      <IP><![CDATA[162.251.151.221]]></IP>
      <MAC><![CDATA[02:00:a2:fb:97:dd]]></MAC>
      <NAME><![CDATA[NIC0]]></NAME>
      <NETWORK><![CDATA[Public IPv4]]></NETWORK>
      <NETWORK_ID><![CDATA[2]]></NETWORK_ID>
      <NIC_ID><![CDATA[0]]></NIC_ID>
      <PHYDEV><![CDATA[bond0]]></PHYDEV>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-803-0]]></TARGET>
      <VN_MAD><![CDATA[bridge]]></VN_MAD>
    </NIC>
```
(this was tested as oneadmin to exclude a permission issue)

**Expected behavior**
RDP parameter should be set.

**Details**
 - Affected Component: Sunstone
 - Version: 10.5.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
- one: OpenNebula/one-ee#107
- doc: OpenNebula/docs#1249

**Comment by sergiojvg** [comment]
Maaaaaan, you are fast!
