### ISSUE TITLE
Add option for formatting datablocks on creation

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#4989]
**Description**
Currently if a FS wants to be use within a datablock, the datablock have to be formatted manually when it's mounted in the VM. It would be useful to have an option for doing this during datablock creation process.

**Use case**
Facilitate the automation of adding formatted volumes avoiding the need of modifying them either from inside the VM or manually without OpenNebula knowing it (e.g modifying image file directly).

**Interface Changes**
The corresponding option should be added to both, CLI and Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
It seems that there are some changes missed in Sunstone:

- In the disk attach dialog the `Filesystem` attribute should be optional, currently it does not allow to leave it blank.
- The option for defining a filesystem have not been added to the image create dialog.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/893)
- [Docs](https://github.com/OpenNebula/docs/pull/1494)
