### ISSUE TITLE
Role actions buttons should respect role state

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4993]
**Description**
If there is a running service with a role and this role is shutdown all not possible buttons/functions should be disabled.

**To Reproduce**
1. Instantiate a OneFlow service
2. Poweroff a role.

**Expected behavior**
Just all possible buttons should be available for the enduser like in the VM tab.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/716
- doc: https://github.com/OpenNebula/docs/pull/1426
