### ISSUE TITLE
Add VM name and other information to VNC window

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4994]
**Description**
Add more information to the title of the VNC window like VM name, IP address, etc..

**Use case**
Be able to check VM information from VNC window without moving to another window.

**Interface Changes**
Sunstone.

## Progress Status
- [x] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- one: https://github.com/OpenNebula/one-ee/pull/622
- docs: https://github.com/OpenNebula/docs/pull/1406

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/742 https://github.com/OpenNebula/one-ee/pull/763

**Comment by tinova** [comment]
Needs testing
