### ISSUE TITLE
VM charter text is illegible in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#4997]
**Description**
VM charters are shown in Sunstone as an icon, when mouse is over it, it shows a message with the duration until the action is executed, this text is a bit illegible, it would be great to change it somehow so it is more usable.

**To Reproduce**
Put the mouse over the icon.

**Expected behavior**
Better text.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12 and development.

**Additional context**
<img width="202" alt="Bildschirmfoto 2020-07-22 um 15 06 58" src="https://user-images.githubusercontent.com/33811723/88517662-809b0d80-cfef-11ea-80ee-5ee44554e602.png">

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/307
- Docs: https://github.com/OpenNebula/docs/pull/1313
