### ISSUE TITLE
Upgrade: onehost sync works only on enabled hosts

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#4999]
**Description**

During the upgrade of OpenNebula `5.10.1` to `5.12`, the [update of the KVM hypervisors using `onehost sync`](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#step-11-update-the-hypervisors-lxd-kvm-only) does nothing.

I needed to `enable` the hosts for the command to do something.

**To Reproduce**

1. disable all hosts
2. execute `onehost sync`

**Expected behavior**

Either the [steps 11 and 12 of the documentation](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#upgrade-single) must be switched or `onehost sync` fixed to work on `offline` hosts.

**Details**
 - Affected Component: Documentation
 - Hypervisor: KVM
 - Version: 5.12

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Update documentation. THANKS!

**Comment by rsmontero** [comment]
Fix Thanks
