### ISSUE TITLE
S3 private marketplace is broken due to missing gem

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5003]
**Description**
```
Error: Mon Jul 27 17:28:43 2020 [Z0][MKP][I]: /usr/share/rubygems/rubygems/dependency.rb:310:in `to_specs': Could not find 'aws-sdk' (>= 2) among 110 total gem(s) (Gem::MissingSpecError)Mon Jul 27 17:28:43 2020 [Z0][MKP][I]: Checked in 'GEM_PATH=/usr/share/one/gems-dist', execute `gem env` for more information
```

**To Reproduce**
Use S3 backend.

**Expected behavior**
It should create the app without any problem.

**Details**
 - Affected Component: Marketplace
 - Version: 5.12 and development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/134)
- [docs](https://github.com/OpenNebula/docs/pull/1257)
