### ISSUE TITLE
Support for INIT_SCRIPTS in vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5004]
**Description**
When init script is configured, a list of scripts can be set as value to run them in order. Ex. “init.sh users.sh mysql.sh” [1]. However, this is not supported for vCenter. The scripts can be uploaded to File DS.

[1] http://docs.opennebula.io/5.12/operation/references/template.html?context-section

**Use case**
Same as for already supported hypervisors.

**Interface Changes**
Sunstone and core.

**Additional Context**

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
ONE
* https://github.com/OpenNebula/one-ee/pull/171

We need support in Sunstone to enable add files.

**Comment by sbbarragan** [comment]
- one (sunstone changes): OpenNebula/one-ee#173
