### ISSUE TITLE
Negative usage quotas for running VMs and running memory in vCenter

### ISSUE THREAD

**Issue by rdiaz-on** [OpenNebula/one#5006]
**Description**
In some circumstances the running usage and quotas for running VMs and running memory have negative values. Ending in a situation similar to this:

```
$ onegroup show 123
...
VMS USAGE & QUOTAS - RUNNING                                                    

      RUNNING VMS       RUNNING MEMORY          RUNNING CPU
     -4 /       8   -16384M /    62.5G      8.50 /    16.00
...
```

It is necessary to run `onedb fsck` to fix them:

```
 onedb fsck
MySQL dump stored in /var/lib/one/mysql_localhost_opennebula_2020-7-29_13:51:3.sql
Use 'onedb restore' or restore the DB using the mysql command:
mysql -u user -h server -P port db_name < backup_file


User 1 is in Group 1 users id list, but it should not
User 31 quotas: RUNNING_CPU_USED has -3 	is	1.00
User 31 quotas: RUNNING_MEMORY_USED has -2048 	is	2048
User 31 quotas: RUNNING_VMS_USED has -1 	is	1
User 47 quotas: RUNNING_CPU_USED has -2.50 	is	0.00
User 47 quotas: RUNNING_MEMORY_USED has -14336 	is	0
User 47 quotas: RUNNING_VMS_USED has -4 	is	0
User 53 quotas: RUNNING_CPU_USED has 11 	is	12.00
User 53 quotas: RUNNING_MEMORY_USED has -2048 	is	2048
User 53 quotas: RUNNING_VMS_USED has 0 	is	2
Group 1 quotas: RUNNING_CPU_USED has 2 	is	0.00
Group 1 quotas: RUNNING_MEMORY_USED has 2048 	is	0
Group 1 quotas: RUNNING_VMS_USED has 1 	is	0
Group 123 quotas: RUNNING_CPU_USED has 8.50 	is	12.00
Group 123 quotas: RUNNING_MEMORY_USED has -16384 	is	2048
Group 123 quotas: RUNNING_VMS_USED has -4 	is	2

Total errors found: 16
Total errors repaired: 16
Total errors unrepaired: 0
```

**To Reproduce**
Start VMs and import wilds from a vCenter host.

**Expected behavior**
Running quotas must be real.

**Details**
 - Affected Component:
 - Hypervisor: vCenter
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by feldsam** [comment]
Hi, looks like this issue is still existing. 
<img width="942" alt="Screenshot 2023-03-10 at 16 50 54" src="https://user-images.githubusercontent.com/951648/224361514-7f9c7f68-3b6f-41aa-8da2-9a59771e91ff.png">

**Comment by paczerny** [comment]
Hello @feldsam,
is there any chance that you now how to reproduce it?
If the user doesn't had too many VMs, can you share all his VM logs?
Alternatively can you share DB and all logs?
If you are willing share the info, we will contact you via email with connections details for the upload

**Comment by feldsam** [comment]
Hi @paczerny , thanks, yes I can share, this user have only one active VM with couple of VM deployed and terminated.
