### ISSUE TITLE
Sunstone is broken in Internet Explorer 11

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5008]
**Description**
When using current Sunstone in IE it doesn't work due to new Javascript.

**To Reproduce**
Run Sunstone on IE.

**Expected behavior**
It should work as expected.

**Details**
 - Affected Component: Sunstone.
 - Version: 5.10, 5.12 and development.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
will drop support for IE 11 in next release
