### ISSUE TITLE
subprocess installed package opennebula-common post-installation script returned error exit status 73

### ISSUE THREAD

**Issue by Marietto2008** [OpenNebula/one#5010]
root@zioma-z390aoruspro:/etc/xen/one# wget -q -O- https://downloads.opennebula.io/repo/repo.key | apt-key add -
OK

root@zioma-z390aoruspro:/etc/xen/one# echo "deb https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable opennebula" > /etc/apt/sources.list.d/opennebula.list

root@zioma-z390aoruspro:/etc/xen/one# apt update

Trovato:1 http://linux.teamviewer.com/deb stable InRelease
Trovato:2 http://ppa.launchpad.net/emoraes25/cid/ubuntu focal InRelease        
Trovato:3 http://archive.canonical.com/ubuntu focal InRelease                  
Scaricamento di:4 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Trovato:5 http://dl.google.com/linux/chrome/deb stable InRelease               
Trovato:6 http://archive.ubuntu.com/ubuntu focal InRelease                     
Trovato:7 https://repo.skype.com/deb stable InRelease                          
Scaricamento di:8 http://archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Scaricamento di:9 https://repo.pbis.beyondtrust.com/apt pbiso InRelease [3.112 B]
Trovato:10 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu focal InRelease
Trovato:11 http://packages.microsoft.com/repos/vscode stable InRelease         
Trovato:12 https://packages.microsoft.com/repos/ms-teams stable InRelease      
Scaricamento di:13 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98,3 kB]
Ignorato:14 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable InRelease
Scaricamento di:15 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [21,2 kB]
Scaricamento di:16 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [35,7 kB]
Scaricamento di:17 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable Release [1.757 B]
Scaricamento di:18 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [196 kB]
Scaricamento di:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [176 kB]
Scaricamento di:20 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2.468 B]
Scaricamento di:21 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1.972 B]
Scaricamento di:22 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable Release.gpg [490 B]
Scaricamento di:23 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula i386 Packages [4.617 B]
Scaricamento di:24 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 Packages [4.617 B]
Recuperati 765 kB in 4s (192 kB/s)                        
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Tutti i pacchetti sono aggiornati.

root@zioma-z390aoruspro:/etc/xen/one# apt upgrade

Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Calcolo dell'aggiornamento... Fatto
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.

root@zioma-z390aoruspro:/etc/xen/one# apt-get install opennebula opennebula-sunstone opennebula-gate opennebula-flow

Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti aggiuntivi saranno inoltre installati:
  augeas-lenses comerr-dev iputils-arping krb5-multidev libaugeas0 libkrb5-dev
  libnorm-dev libpgm-dev libsodium-dev libzmq3-dev opennebula-common
  opennebula-common-onescape opennebula-rubygems opennebula-tools
  python3-numpy ruby-opennebula
Pacchetti suggeriti:
  augeas-doc krb5-doc augeas-tools libnorm-doc mysql-server gfortran
  python-numpy-doc python3-pytest python3-numpy-dbg
I seguenti pacchetti NUOVI saranno installati:
  augeas-lenses comerr-dev iputils-arping krb5-multidev libaugeas0 libkrb5-dev
  libnorm-dev libpgm-dev libsodium-dev libzmq3-dev opennebula
  opennebula-common opennebula-common-onescape opennebula-flow opennebula-gate
  opennebula-rubygems opennebula-sunstone opennebula-tools python3-numpy
  ruby-opennebula
0 aggiornati, 20 installati, 0 da rimuovere e 0 non aggiornati.
È necessario scaricare 42,7 MB di archivi.
Dopo quest'operazione, verranno occupati 393 MB di spazio su disco.
Continuare? [S/n] s
Scaricamento di:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 augeas-lenses all 1.12.0-1build1 [308 kB]
Scaricamento di:2 http://archive.ubuntu.com/ubuntu focal/main amd64 iputils-arping amd64 3:20190709-3 [15,8 kB]
Scaricamento di:3 http://archive.ubuntu.com/ubuntu focal/main amd64 comerr-dev amd64 2.1-1.45.5-2ubuntu1 [39,9 kB]
Scaricamento di:4 http://archive.ubuntu.com/ubuntu focal/main amd64 krb5-multidev amd64 1.17-6ubuntu4 [120 kB]
Scaricamento di:5 http://archive.ubuntu.com/ubuntu focal/universe amd64 libaugeas0 amd64 1.12.0-1build1 [195 kB]
Scaricamento di:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 libnorm-dev amd64 1.5.8+dfsg2-2build1 [463 kB]
Scaricamento di:7 http://archive.ubuntu.com/ubuntu focal/universe amd64 libpgm-dev amd64 5.2.122~dfsg-3ubuntu1 [189 kB]
Scaricamento di:8 http://archive.ubuntu.com/ubuntu focal/main amd64 libsodium-dev amd64 1.0.18-1 [169 kB]
Scaricamento di:9 http://archive.ubuntu.com/ubuntu focal/main amd64 libkrb5-dev amd64 1.17-6ubuntu4 [11,8 kB]
Scaricamento di:10 http://archive.ubuntu.com/ubuntu focal/universe amd64 libzmq3-dev amd64 4.3.2-2ubuntu1 [455 kB]
Scaricamento di:11 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-numpy amd64 1:1.17.4-5ubuntu3 [2.725 kB]
Scaricamento di:12 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-common-onescape all 5.11.90-1 [5.328 B]
Scaricamento di:13 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-common all 5.11.90-1 [15,1 kB]
Scaricamento di:14 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-rubygems all 5.11.90-1 [15,7 MB]
Scaricamento di:15 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 ruby-opennebula all 5.11.90-1 [83,2 kB]
Scaricamento di:16 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-tools all 5.11.90-1 [174 kB]
Scaricamento di:17 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula amd64 5.11.90-1 [1.978 kB]
Scaricamento di:18 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-flow all 5.11.90-1 [37,1 kB]
Scaricamento di:19 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-gate all 5.11.90-1 [11,9 kB]
Scaricamento di:20 https://downloads.opennebula.io/repo/5.11/Ubuntu/20.04 stable/opennebula amd64 opennebula-sunstone all 5.11.90-1 [20,0 MB]
Recuperati 42,7 MB in 16s (2.725 kB/s)                                         
Selezionato il pacchetto augeas-lenses non precedentemente selezionato.
(Lettura del database... 386325 file e directory attualmente installati.)
Preparativi per estrarre .../00-augeas-lenses_1.12.0-1build1_all.deb...
Estrazione di augeas-lenses (1.12.0-1build1)...
Selezionato il pacchetto iputils-arping non precedentemente selezionato.
Preparativi per estrarre .../01-iputils-arping_3%3a20190709-3_amd64.deb...
Estrazione di iputils-arping (3:20190709-3)...
Selezionato il pacchetto comerr-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../02-comerr-dev_2.1-1.45.5-2ubuntu1_amd64.deb...
Estrazione di comerr-dev:amd64 (2.1-1.45.5-2ubuntu1)...
Selezionato il pacchetto krb5-multidev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../03-krb5-multidev_1.17-6ubuntu4_amd64.deb...
Estrazione di krb5-multidev:amd64 (1.17-6ubuntu4)...
Selezionato il pacchetto libaugeas0:amd64 non precedentemente selezionato.
Preparativi per estrarre .../04-libaugeas0_1.12.0-1build1_amd64.deb...
Estrazione di libaugeas0:amd64 (1.12.0-1build1)...
Selezionato il pacchetto libnorm-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../05-libnorm-dev_1.5.8+dfsg2-2build1_amd64.deb...
Estrazione di libnorm-dev:amd64 (1.5.8+dfsg2-2build1)...
Selezionato il pacchetto libpgm-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../06-libpgm-dev_5.2.122~dfsg-3ubuntu1_amd64.deb...
Estrazione di libpgm-dev:amd64 (5.2.122~dfsg-3ubuntu1)...
Selezionato il pacchetto libsodium-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../07-libsodium-dev_1.0.18-1_amd64.deb...
Estrazione di libsodium-dev:amd64 (1.0.18-1)...
Selezionato il pacchetto libkrb5-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../08-libkrb5-dev_1.17-6ubuntu4_amd64.deb...
Estrazione di libkrb5-dev:amd64 (1.17-6ubuntu4)...
Selezionato il pacchetto libzmq3-dev:amd64 non precedentemente selezionato.
Preparativi per estrarre .../09-libzmq3-dev_4.3.2-2ubuntu1_amd64.deb...
Estrazione di libzmq3-dev:amd64 (4.3.2-2ubuntu1)...
Selezionato il pacchetto python3-numpy non precedentemente selezionato.
Preparativi per estrarre .../10-python3-numpy_1%3a1.17.4-5ubuntu3_amd64.deb...
Estrazione di python3-numpy (1:1.17.4-5ubuntu3)...
Selezionato il pacchetto opennebula-common-onescape non precedentemente selezionato.
Preparativi per estrarre .../11-opennebula-common-onescape_5.11.90-1_all.deb...
chown: utente non valido: "oneadmin:oneadmin"
Estrazione di opennebula-common-onescape (5.11.90-1)...
Selezionato il pacchetto opennebula-common non precedentemente selezionato.
Preparativi per estrarre .../12-opennebula-common_5.11.90-1_all.deb...
Estrazione di opennebula-common (5.11.90-1)...
Selezionato il pacchetto opennebula-rubygems non precedentemente selezionato.
Preparativi per estrarre .../13-opennebula-rubygems_5.11.90-1_all.deb...
Estrazione di opennebula-rubygems (5.11.90-1)...
Selezionato il pacchetto ruby-opennebula non precedentemente selezionato.
Preparativi per estrarre .../14-ruby-opennebula_5.11.90-1_all.deb...
Estrazione di ruby-opennebula (5.11.90-1)...
Selezionato il pacchetto opennebula-tools non precedentemente selezionato.
Preparativi per estrarre .../15-opennebula-tools_5.11.90-1_all.deb...
Estrazione di opennebula-tools (5.11.90-1)...
Selezionato il pacchetto opennebula non precedentemente selezionato.
Preparativi per estrarre .../16-opennebula_5.11.90-1_amd64.deb...
Estrazione di opennebula (5.11.90-1)...
Selezionato il pacchetto opennebula-flow non precedentemente selezionato.
Preparativi per estrarre .../17-opennebula-flow_5.11.90-1_all.deb...
Estrazione di opennebula-flow (5.11.90-1)...
Selezionato il pacchetto opennebula-gate non precedentemente selezionato.
Preparativi per estrarre .../18-opennebula-gate_5.11.90-1_all.deb...
Estrazione di opennebula-gate (5.11.90-1)...
Selezionato il pacchetto opennebula-sunstone non precedentemente selezionato.
Preparativi per estrarre .../19-opennebula-sunstone_5.11.90-1_all.deb...
Estrazione di opennebula-sunstone (5.11.90-1)...
Configurazione di augeas-lenses (1.12.0-1build1)...
Configurazione di libnorm-dev:amd64 (1.5.8+dfsg2-2build1)...
Configurazione di iputils-arping (3:20190709-3)...
Configurazione di libpgm-dev:amd64 (5.2.122~dfsg-3ubuntu1)...
Configurazione di libaugeas0:amd64 (1.12.0-1build1)...
Configurazione di comerr-dev:amd64 (2.1-1.45.5-2ubuntu1)...
Configurazione di libsodium-dev:amd64 (1.0.18-1)...
Configurazione di python3-numpy (1:1.17.4-5ubuntu3)...
Configurazione di opennebula-rubygems (5.11.90-1)...
Configurazione di opennebula-common-onescape (5.11.90-1)...
Configurazione di krb5-multidev:amd64 (1.17-6ubuntu4)...
Configurazione di ruby-opennebula (5.11.90-1)...
Configurazione di libkrb5-dev:amd64 (1.17-6ubuntu4)...
Configurazione di opennebula-common (5.11.90-1)...
Aggiunta del gruppo «oneadmin» (GID 9869) ...
Fatto.
Attenzione: la directory home /var/lib/one indicata già esiste.
Aggiunta dell'utente di sistema «oneadmin» (UID 9869) ...
Aggiunta del nuovo utente «oneadmin» (UID 9869) con gruppo «oneadmin» ...
La directory home «/var/lib/one» già esiste. Copia da «/etc/skel» non effettuata.
adduser: Attenzione: la directory home «/var/lib/one» non appartiene all'utente che si sta creando.
/usr/lib/tmpfiles.d/opennebula.conf:2: Line references path below legacy directory /var/run/, updating /var/run/one → /run/one; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/opennebula.conf:3: Line references path below legacy directory /var/run/, updating /var/run/one/ssh-socks → /run/one/ssh-socks; please update the tmpfiles.d/ drop-in file accordingly.
Detected unsafe path transition / → /var during canonicalization of /var/lock.
Detected unsafe path transition / → /run during canonicalization of /run.
Detected unsafe path transition / → /run during canonicalization of /run/one.
dpkg: errore nell'elaborare il pacchetto opennebula-common (--configure):
 il sottoprocesso installato pacchetto opennebula-common script post-installation ha restituito lo stato di errore 73
Configurazione di libzmq3-dev:amd64 (4.3.2-2ubuntu1)...
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-tools:
 opennebula-tools dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-tools (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-sunstone:
 opennebula-sunstone dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.
 opennebula-sunstone dipende da opennebula-tools (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-tools non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-sunstone (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula:
 opennebula dipende da opennebula-common (Segnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                       Segnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                    Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                            Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                                    Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                                            = 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.
 opennebula dipende da opennebula-tools (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-tools non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-flow:
 opennebula-flow dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-flow (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-gate:
 opennebula-gate dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-gate (--configure):
 problemi con le dipendenze - lasciato non configurato
Elaborazione dei trigger per doc-base (0.10.9)...
Elaborazione 1 file doc-base aggiunto...
Elaborazione dei trigger per libc-bin (2.31-0ubuntu9)...
Elaborazione dei trigger per man-db (2.9.1-1)...
Elaborazione dei trigger per install-info (6.7.0.dfsg.2-5)...
Si sono verificati degli errori nell'elaborazione:
 opennebula-common
 opennebula-tools
 opennebula-sunstone
 opennebula
 opennebula-flow
 opennebula-gate
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@zioma-z390aoruspro:/etc/xen/one# ls /var/lib

AccountsService  cid		      flatpak	       libnss-ldap	misc		pam	    sgml-base		   ubuntu-release-upgrader  xfonts
acpi-support	 colord		      fwupd	       libreoffice	mlocate		pbis	    shim-signed		   ucf			    xkb
alsa		 command-not-found    gconf	       libvirt		motion		plymouth    snapd		   udisks2		    xml-core
app-info	 dbus		      gems	       libxml-sax-perl	mplayer		polkit-1    snmp		   update-manager
apt		 dhcp		      geoclue	       lightdm		msttcorefonts	private     sudo		   update-notifier
aspell		 dictionaries-common  ghostscript      lightdm-data	NetworkManager	python	    synaptic		   upower
avahi-autoipd	 dkms		      git	       locales		one		resolvconf  systemd		   usb_modeswitch
bluetooth	 doc-base	      grub	       logrotate	openvpn		rpm	    tpm			   usbutils
boltd		 dpkg		      initramfs-tools  man-db		os-prober	samba	    ubuntu-advantage	   vim
BrlAPI		 emacsen-common       ispell	       menu-xdg		PackageKit	sddm	    ubuntu-drivers-common  xen

root@zioma-z390aoruspro:/etc/xen/one# ls /var/lib/one

backups  datastores  remotes  sunstone	vms

root@zioma-z390aoruspro:/etc/xen/one# mv /var/lib/one /var/lib/one_

root@zioma-z390aoruspro:/etc/xen/one# ls /var/lib/one

ls: impossibile accedere a '/var/lib/one': File o directory non esistente
root@zioma-z390aoruspro:/etc/xen/one# ls /var/lib/one_
backups  datastores  remotes  sunstone	vms

root@zioma-z390aoruspro:/etc/xen/one# apt-get install opennebula opennebula-sunstone opennebula-gate opennebula-flow

Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
opennebula è già alla versione più recente (5.11.90-1).
opennebula-flow è già alla versione più recente (5.11.90-1).
opennebula-gate è già alla versione più recente (5.11.90-1).
opennebula-sunstone è già alla versione più recente (5.11.90-1).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
6 non completamente installati o rimossi.
Dopo quest'operazione, verranno occupati 0 B di spazio su disco.
Continuare? [S/n] s
Configurazione di opennebula-common (5.11.90-1)...
usermod: nessuna modifica
/usr/lib/tmpfiles.d/opennebula.conf:2: Line references path below legacy directory /var/run/, updating /var/run/one → /run/one; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/opennebula.conf:3: Line references path below legacy directory /var/run/, updating /var/run/one/ssh-socks → /run/one/ssh-socks; please update the tmpfiles.d/ drop-in file accordingly.
Detected unsafe path transition / → /var during canonicalization of /var/lock.
Detected unsafe path transition / → /run during canonicalization of /run.
Detected unsafe path transition / → /run during canonicalization of /run/one.
dpkg: errore nell'elaborare il pacchetto opennebula-common (--configure):
 il sottoprocesso installato pacchetto opennebula-common script post-installation ha restituito lo stato di errore 73
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-tools:
 opennebula-tools dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-tools (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-sunstone:
 opennebula-sunstone dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.
 opennebula-sunstone dipende da opennebula-tools (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-tools non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-sunstone (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula:
 opennebula dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-commonSegnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                                                                                             Segnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                                            Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                      Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                                                                                                              Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                                         non è ancora configurato.
 opennebula dipende da opennebula-tools (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-tools non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-flow:
 opennebula-flow dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-flow (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-gate:
 opennebula-gate dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-gate (--configure):
 problemi con le dipendenze - lasciato non configurato
Si sono verificati degli errori nell'elaborazione:
 opennebula-common
 opennebula-tools
 opennebula-sunstone
 opennebula
 opennebula-flow
 opennebula-gate
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@zioma-z390aoruspro:/etc/xen/one# apt-get remove opennebula opennebula-sunstone opennebula-gate opennebula-flow

Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti sono stati installati automaticamente e non sono più richiesti:
  augeas-lenses comerr-dev iputils-arping krb5-multidev libaugeas0 libkrb5-dev libnorm-dev libpgm-dev libsodium-dev libzmq3-dev opennebula-common
  opennebula-common-onescape opennebula-rubygems opennebula-tools python3-numpy ruby-opennebula
Usare "apt autoremove" per rimuoverli.
I seguenti pacchetti saranno RIMOSSI:
  opennebula opennebula-flow opennebula-gate opennebula-sunstone
0 aggiornati, 0 installati, 4 da rimuovere e 0 non aggiornati.
6 non completamente installati o rimossi.
Dopo quest'operazione, verranno liberati 172 MB di spazio su disco.
Continuare? [S/n] s
(Lettura del database... 432898 file e directory attualmente installati.)
Rimozione di opennebula (5.11.90-1)...
Rimozione di opennebula-flow (5.11.90-1)...
Rimozione di opennebula-gate (5.11.90-1)...
Rimozione di opennebula-sunstone (5.11.90-1)...
Configurazione di opennebula-common (5.11.90-1)...
usermod: nessuna modifica
/usr/lib/tmpfiles.d/opennebula.conf:2: Line references path below legacy directory /var/run/, updating /var/run/one → /run/one; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/opennebula.conf:3: Line references path below legacy directory /var/run/, updating /var/run/one/ssh-socks → /run/one/ssh-socks; please update the tmpfiles.d/ drop-in file accordingly.
Detected unsafe path transition / → /var during canonicalization of /var/lock.
Detected unsafe path transition / → /run during canonicalization of /run.
Detected unsafe path transition / → /run during canonicalization of /run/one.
dpkg: errore nell'elaborare il pacchetto opennebula-common (--configure):
 il sottoprocesso installato pacchetto opennebula-common script post-installation ha restituito lo stato di errore 73
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-tools:
 opennebula-tools dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-tools (--configure):
 problemi con le dipendenze - lasciato non configurato
Segnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                                                             Elaborazione dei trigger per man-db (2.9.1-1)...
Si sono verificati degli errori nell'elaborazione:
 opennebula-common
 opennebula-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@zioma-z390aoruspro:/etc/xen/one# apt-get purge opennebula opennebula-sunstone opennebula-gate opennebula-flow

Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti sono stati installati automaticamente e non sono più richiesti:
  augeas-lenses comerr-dev iputils-arping krb5-multidev libaugeas0 libkrb5-dev libnorm-dev libpgm-dev libsodium-dev libzmq3-dev opennebula-common
  opennebula-common-onescape opennebula-rubygems opennebula-tools python3-numpy ruby-opennebula
Usare "apt autoremove" per rimuoverli.
I seguenti pacchetti saranno RIMOSSI:
  opennebula* opennebula-flow* opennebula-gate* opennebula-sunstone*
0 aggiornati, 0 installati, 4 da rimuovere e 0 non aggiornati.
2 non completamente installati o rimossi.
Dopo quest'operazione, verranno occupati 0 B di spazio su disco.
Continuare? [S/n] s
Configurazione di opennebula-common (5.11.90-1)...
usermod: nessuna modifica
/usr/lib/tmpfiles.d/opennebula.conf:2: Line references path below legacy directory /var/run/, updating /var/run/one → /run/one; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/opennebula.conf:3: Line references path below legacy directory /var/run/, updating /var/run/one/ssh-socks → /run/one/ssh-socks; please update the tmpfiles.d/ drop-in file accordingly.
Detected unsafe path transition / → /var during canonicalization of /var/lock.
Detected unsafe path transition / → /run during canonicalization of /run.
Detected unsafe path transition / → /run during canonicalization of /run/one.
dpkg: errore nell'elaborare il pacchetto opennebula-common (--configure):
 il sottoprocesso installato pacchetto opennebula-common script post-installation ha restituito lo stato di errore 73
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-tools:
 opennebula-tools dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-tools (--configure):
 problemi con le dipendenze - lasciato non configurato
Segnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                                                             Si sono verificati degli errori nell'elaborazione:
 opennebula-common
 opennebula-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@zioma-z390aoruspro:/etc/xen/one# apt-get reinstall opennebula opennebula-sunstone opennebula-gate opennebula-flow

Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Pacchetti suggeriti:
  mysql-server
I seguenti pacchetti NUOVI saranno installati:
  opennebula opennebula-flow opennebula-gate opennebula-sunstone
0 aggiornati, 4 installati, 0 da rimuovere e 0 non aggiornati.
2 non completamente installati o rimossi.
È necessario scaricare 0 B/22,0 MB di archivi.
Dopo quest'operazione, verranno occupati 172 MB di spazio su disco.
(Lettura del database... 410503 file e directory attualmente installati.)
Preparativi per estrarre .../opennebula_5.11.90-1_amd64.deb...
Estrazione di opennebula (5.11.90-1)...
Preparativi per estrarre .../opennebula-flow_5.11.90-1_all.deb...
Estrazione di opennebula-flow (5.11.90-1)...
Preparativi per estrarre .../opennebula-gate_5.11.90-1_all.deb...
Estrazione di opennebula-gate (5.11.90-1)...
Preparativi per estrarre .../opennebula-sunstone_5.11.90-1_all.deb...
Estrazione di opennebula-sunstone (5.11.90-1)...
Configurazione di opennebula-common (5.11.90-1)...
usermod: nessuna modifica
/usr/lib/tmpfiles.d/opennebula.conf:2: Line references path below legacy directory /var/run/, updating /var/run/one → /run/one; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/opennebula.conf:3: Line references path below legacy directory /var/run/, updating /var/run/one/ssh-socks → /run/one/ssh-socks; please update the tmpfiles.d/ drop-in file accordingly.
Detected unsafe path transition / → /var during canonicalization of /var/lock.
Detected unsafe path transition / → /run during canonicalization of /run.
Detected unsafe path transition / → /run during canonicalization of /run/one.
dpkg: errore nell'elaborare il pacchetto opennebula-common (--configure):
 il sottoprocesso installato pacchetto opennebula-common script post-installation ha restituito lo stato di errore 73
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-tools:
 opennebula-tools dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-tools (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-sunstone:
 opennebula-sunstone dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.
 opennebula-sunstone dipende da opennebula-tools (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-tools non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-sunstone (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula:
 opennebula dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-commonSegnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                                                                                             Segnalazione apport non scritta poiché il messaggio di errore indica la presenza di un fallimento precedente.
                                                                                            Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                      Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                                                                                                              Segnalazione apport non scritta poiché è stato raggiunto il valore massimo di MaxReports
                                         non è ancora configurato.
 opennebula dipende da opennebula-tools (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-tools non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-flow:
 opennebula-flow dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-flow (--configure):
 problemi con le dipendenze - lasciato non configurato
dpkg: problemi con le dipendenze impediscono la configurazione di opennebula-gate:
 opennebula-gate dipende da opennebula-common (= 5.11.90-1); tuttavia:
  Il pacchetto opennebula-common non è ancora configurato.

dpkg: errore nell'elaborare il pacchetto opennebula-gate (--configure):
 problemi con le dipendenze - lasciato non configurato
Elaborazione dei trigger per man-db (2.9.1-1)...
Si sono verificati degli errori nell'elaborazione:
 opennebula-common
 opennebula-tools
 opennebula-sunstone
 opennebula
 opennebula-flow
 opennebula-gate
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by tinova** [comment]
cannot reproduce in current packages
