### ISSUE TITLE
Hide "Schedule action for VM" on VM deployment for "cloudadmin" view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5011]
**Description**
It is necessary to add new option to hide "Schedule action for VM" on VM deployment for "cloudadmin" view.

**Use case**
Cloud administrators who want to avoid configuring scheduled actions for virtual machines by cloud users.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Please consider all sunstone views

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/793)
- [Docs](https://github.com/OpenNebula/docs/pull/1464)
