### ISSUE TITLE
Sunstone groupadmin and cloud view quota widget configurable

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5012]
**Description**
Quota dashboard for "groupadmin" and "cloud" display a mix of Running VMs and Total CPU and Memory. It should be total VMs, total CPU, total Memory or Running VM, Running CPU, Running Memory.

**Use case**
Have it separated.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Closing as dashboards will be completely redesign in #5422
