### ISSUE TITLE
No CPU/Memory/Disk hours shown in Sunstone cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5014]
**Description**
When using the cloud view of Sunstone, in Dashboard for "Group Virtual Machines" (requires `groupvms: true` in `/etc/one/sunstone-views/mixed/cloud.yaml`), *CPU hours*, *Memory GB hours*, and *Disk MB hours* information is empty.

![image](https://user-images.githubusercontent.com/33811723/89271921-b10d2800-d63d-11ea-9215-b65d475fed46.png)

**To Reproduce**
Enable *groupvms* of cloud view, create a VM group, and create a VMs belonging to the group.

**Expected behavior**
CPU hours*, *Memory GB hours*, and *Disk MB hours* information must be shown

**Details**
 - Affected Component: Sunstone
  - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee#155
- doc: OpenNebula/docs#1268
