### ISSUE TITLE
Add option to disable raw section validation

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#5015]
**Description**
raw section is validated per driver. For KVM this means validation against RelaxNG schema. This option is to disable this validation (probably by template) when it is not covered by the provided schema

RAW = [
TYPE = "...."
RAW = "..."
VALIDATE = "yes|no"
]

**Use case**
Use raw sections not covered by schema

**Interface Changes**
New RAW attribute, would require a checkbox in Sunstone

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs for merge to master:
* one-ee https://github.com/OpenNebula/one-ee/pull/150
* development https://github.com/OpenNebula/development/pull/1151
* docs https://github.com/OpenNebula/docs/pull/1264

**Comment by tinova** [comment]
Sunstone: https://github.com/OpenNebula/one/issues/5173
