### ISSUE TITLE
Hooks missing exections record with postgress DB  backend

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5017]
**Description**
When using Postgres DB backend, hooks are executed, but the execution record is not created

**To Reproduce**
Create hook using template
```
CALL="one.zone.raftstatus"
COMMAND="/$(which echo) testing"
REMOTE="NO"
```
run `onezone list`
check hook execution record are missing

**Details**
In oned.log:
```
Thu Aug  6 10:36:09 2020 [Z0][HKM][E]: Error executing Hook 0
Thu Aug  6 10:36:09 2020 [Z0][ONE][E]: SQL command was: SELECT IFNULL(MAX(exeid), -1), COUNT(*) FROM hook_log WHERE hkid = 0, error ERROR:  function ifnull(integer, integer) does not exist
LINE 1: SELECT IFNULL(MAX(exeid), -1), COUNT(*) FROM hook_log WHERE ...

```
It seems in postgresql the IFNULL is called NULLIF (https://www.postgresqltutorial.com/postgresql-nullif/)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
https://github.com/OpenNebula/one/issues/5072 (duplicated)
