### ISSUE TITLE
Sunstone doesn't work with remote oned

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5019]
**Description**
With introduction of 2FA support since 5.12, the Sunstone doesn't work with remote (= running on different host) oned. At some point it still tries to connect to the localhost, but fails. The configuration snippet from `/etc/one/sunstone-server.conf` clearly instructs to use different host, e.g.:

```
# OpenNebula sever contact information
#
:one_xmlrpc: http://10.10.5.7:2633/RPC2
```

It's able to do initial authentication request over `serveradmin` user on the remote oned, but then fails as it tries to connect with default connection parameters (`localhost:2633`). The problem is manifested in following ways

- on UI

![image](https://user-images.githubusercontent.com/414850/89558016-faaf6b80-d813-11ea-96c8-21f27b3a524f.png)

- in Sunstone log

```
Thu Aug 06 16:12:51 2020 [I]: 10.0.0.2 - - [06/Aug/2020:16:12:51 +0000] "GET /images/apple-touch-icon-precomposed.png HTTP/1.1" 200 - 0.0007
Thu Aug 06 16:12:51 2020 [I]: 10.0.0.2 - - [06/Aug/2020:16:12:51 +0000] "GET /images/favicon.png HTTP/1.1" 200 - 0.0006
Thu Aug 06 16:12:56 2020 [E]: user.info error: Failed to open TCP connection to localhost:2633 (Connection refused - connect(2) for "localhost" port 2633)
Thu Aug 06 16:12:56 2020 [I]: 10.0.0.2 - - [06/Aug/2020:16:12:56 +0000] "POST /login HTTP/1.1" 500 - 0.1557
```

and

```
-- Logs begin at Thu 2020-08-06 16:06:57 UTC, end at Thu 2020-08-06 16:12:56 UTC. --
Aug 06 16:12:30 centos8-413840 systemd[1]: Starting OpenNebula Web UI Server...
Aug 06 16:12:30 centos8-413840 systemd[1]: Started OpenNebula Web UI Server.
Aug 06 16:12:31 centos8-413840 ruby[4920]: --------------------------------------
Aug 06 16:12:31 centos8-413840 ruby[4920]:          Server configuration
Aug 06 16:12:31 centos8-413840 ruby[4920]: --------------------------------------
Aug 06 16:12:31 centos8-413840 ruby[4920]: {:tmpdir=>"/var/tmp",
Aug 06 16:12:31 centos8-413840 ruby[4920]:  :one_xmlrpc=>"http://10.10.5.7:2633/RPC2",
Aug 06 16:12:31 centos8-413840 ruby[4920]:  :one_xmlrpc_timeout=>60,
...
Aug 06 16:12:31 centos8-413840 ruby[4920]: --------------------------------------
Aug 06 16:12:32 centos8-413840 ruby[4920]: == Sinatra (v2.0.8.1) has taken the stage on 9869 for production with backup from Thin
Aug 06 16:12:56 centos8-413840 ruby[4920]: 2020-08-06 16:12:56 - NoMethodError - undefined method `map' for nil:NilClass:
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/lib/one/sunstone/models/SunstoneWebAuthn.rb:95:in `getCredentialIDsForUser'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/lib/one/sunstone/sunstone-server.rb:378:in `build_session'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/lib/one/sunstone/sunstone-server.rb:708:in `block in <main>'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/share/one/gems-dist/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/share/one/gems-dist/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/share/one/gems-dist/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/share/one/gems-dist/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/share/one/gems-dist/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
Aug 06 16:12:56 centos8-413840 ruby[4920]:         /usr/share/one/gems-dist/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
```

When 2FA is disabled in the Sunstone code (`webauthn_avail = false`), I'm able to authenticate and work with the Sunstone against oned on different host. So, the problem probably comes from the following line

https://github.com/OpenNebula/one/blob/627e92c80b240552bac01e020000ba6a0b3472d2/src/sunstone/models/OpenNebula2FA/SunstoneWebAuthn.rb#L24

which creates its own OpenNebula client object, IMHO with default connection parameters not respecting the Sunstone configuration. Moreover, it looks like same problem is also with the **vCenter** Sunstone integration, e.g.:

https://github.com/OpenNebula/one/blob/627e92c80b240552bac01e020000ba6a0b3472d2/src/sunstone/routes/vcenter.rb#L65

![image](https://user-images.githubusercontent.com/414850/89557831-b6bc6680-d813-11ea-82ad-30a970382fea.png)

**To Reproduce**
- have 2 VMs
- run oned on 1st VM
- run Susntone on 2st VM
- have credentials (`~oneadmin/.one/`) same
- have Sunstone configured with against 1st VM IP (`one_xmlrpc`)
- get errors related to localhost connection
- try add vCenter cluster, get localhost connection errors

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 5.12

Affected are only newer platforms, older ones (CentOS 7, Debian 9, Ubuntu 16.04) doesn't come with webauthn Ruby modules.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/291 
Docs: https://github.com/OpenNebula/docs/pull/1310

**Comment by vholer** [comment]
Problem is not fixed, it still tries to contect `localhost` for authentication:

```
Fri Oct 09 13:18:28 2020 [I]: 10.0.0.2 - - [09/Oct/2020:13:18:28 +0000] "GET /images/opennebula-5.0.png HTTP/1.1" 200 - 0.0014
Fri Oct 09 13:18:32 2020 [E]: user.info error: Failed to open TCP connection to localhost:2633 (Connection refused - connect(2) for "localhost" port 2633)
Fri Oct 09 13:18:32 2020 [I]: 10.0.0.2 - - [09/Oct/2020:13:18:32 +0000] "POST /login HTTP/1.1" 500 - 0.2343
```

**Comment by jloboescalona2** [comment]
@vholer If you change the attribute :one_xmlrpc: (sunstone-server.conf) and put the content of the sunstone_auth (/var/lib/one/.one) of the remote zone in the sunstone_auth of the local sunstone it doesn't connect?

**Comment by jloboescalona2** [comment]
@vholer if you change the attribute **:one_xmlrpc** (sunstone-server.conf) and
replace the contents of your local sunstone_auth (/var/lib/one) with the remote sunstone_auth. does not connect?

**Comment by vholer** [comment]
That's what I'm doing.

If it works for you, you probably don't have Ruby gems for 2FA and part of code is skipped due to this detection:
https://github.com/OpenNebula/one/blob/master/src/sunstone/sunstone-server.rb#L245
