### ISSUE TITLE
Show current time when configuring scheduled actions

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#5023]
**Description**
When configuring a new scheduled action, there is no way to know the current time or timezone of the server. For private clouds and admins this might not be a huge issue, but for end users it is. By showing the current server time in the same window when creating the scheduled action, it would provide some feedback to the user. Optionally, the timezone of the client's browser could be considered, but this would add extra complexity. 

**Use case**
An end user creating a scheduled action on a public cloud based on OpenNebula.

**Interface Changes**
Show current time in Sunstone, in the same windows when creating a new scheduled action.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Already implemented, closing this.
