### ISSUE TITLE
Can not get monitoring information from locked VMs

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#5027]
**Description**
Trying to get monitoring information (capacity, disk or network tab) through Sunstone from a locked VM will fail with the following message:

```
Tue Aug 11 14:46:21 2020 [Z0][ReM][E]: Req:8016 UID:0 one.vm.monitoring result FAILURE [one.vm.monitoring] User [0] : VM is locked. [24].
```
Will not happen from CLI.

**Expected behavior**
Locked VMs should provide monitoring information.

**Details**
 - Affected Component: Sunstone - core
 - Version: 5.10.5

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
This issue has been fixed in #5200
