### ISSUE TITLE
Not available PDF documentation for 5.12

### ISSUE THREAD

**Issue by josem-amatriain** [OpenNebula/one#5028]
**Description**
The pdf documents linked in http://docs.opennebula.io/5.12/ are not available for download because the documents are not generated: 
The link [document](http://docs.opennebula.io/pdf/5.12/opennebula_5.12_intro_release_notes.pdf) and all links for version 5.12 are missing.

**To Reproduce**
Following the link
http://docs.opennebula.io/pdf/5.12/opennebula_5.12_intro_release_notes.pdf
Linked in http://docs.opennebula.io/5.12/

`The folder http://docs.opennebula.io/pdf/5.12/ was not found on the server.`

**Expected behavior**
The links provided must exist.

**Details**
 - Affected Component: Documentation in pdf format.
 - Hypervisor: ALL
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PDF documentation is abandoned, now everything is published on https://docs.opennebula.io/6.2/, closing this.
