### ISSUE TITLE
Add easy share option in Sunstone for resources

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5030]
**Description**
Currently, resources can be shared either by setting the permissions (group or all) or by setting ACL for allowing specific users to access specific resources.

It will be useful to have a **share** button in Sunstone which takes care of asking the user the ACL required information and create it under the hood.

**Use case**
Allow a final user to share resources with other users without the need of being aware of what ACLs are or how they work.

**Interface Changes**
Some kind of share button plus a dialog should be added to Sunstone. The dialog should be very similar to the ACL creation one.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
closed in favor of #5724
