### ISSUE TITLE
Allow charters configuration within service/vm Template

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5033]
**Description**
Currently, charters can only be set for an instantiated VM/Service. It would be useful to be able to define this configuration at template level.

**Use case**
Automatically set charter for every VM/Service instantiated from an specific template.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/740)
- [docs](https://github.com/OpenNebula/docs/pull/1456)

test pendings
