### ISSUE TITLE
Show charter information in Service list

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5034]
**Description**
Show charter information in Service list table the same way it's done for VMs.

**Interface Changes**
The charter information have to be shown in the Service datatable at Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/785)
- [docs](https://github.com/OpenNebula/docs/pull/1461)

test pendings
