### ISSUE TITLE
Delete service when every role have been terminated

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5035]
**Description**
As a result of charters or scheduled actions the VMs within a role can be automatically terminated. It would be useful to have an option for terminating the service when all the roles have been terminated (i.e all the VMs within each role are terminated).

**Use case**
It avoid to have empty, not used, services without any VM.

**Interface Changes**
This option needs to be set from Sunstone interface or directly modifying the Service template via CLI.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/377)
- [docs](https://github.com/OpenNebula/docs/pull/1340)
- [tests](https://github.com/OpenNebula/development/pull/1206)

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [code](https://github.com/OpenNebula/one-ee/pull/657)
- [docs](https://github.com/OpenNebula/docs/pull/1409)
- [tests](https://github.com/OpenNebula/development/pull/1256)
