### ISSUE TITLE
Sunstone ignores template VCPUs on instantiation

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5036]
**Description**

Despite the fact that VM template contains custom `VCPU` size (66), Sunstone doesn't respect it and instantiate templates with default one `VCPU`.

![image](https://user-images.githubusercontent.com/414850/90401313-0fa2bf00-e09e-11ea-926d-e1eb2e4056ed.png)

**To Reproduce**
- Have VM template with custom VCPU
- Instantiate VM template over Sunstone
- Find VCPU=1 in the wizard, and in the final VM.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.2 (most likely also CE)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
This issue is fixed in the last versions (5.12.6)
_Closing until more feedback is provided._
