### ISSUE TITLE
Sunstones view of multiple VM IPs malformed during filter

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5037]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**

When VM list is being filetered in Sunstone, the additional VM addresses are shown in malformed drop-down menu:

![image](https://user-images.githubusercontent.com/414850/90403682-9907c080-e0a1-11ea-945d-74f55875f4fa.png)

When filtered list is reloaded (via button ![image](https://user-images.githubusercontent.com/414850/90403957-fef44800-e0a1-11ea-9d2a-0dd4b79e8e9a.png)), the view is fixed to following:

![image](https://user-images.githubusercontent.com/414850/90403760-b50b6200-e0a1-11ea-973b-344d507bf96f.png)

**To Reproduce**
Filter list of VMs with multiple IPs, see broken view of additional IPs.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.2

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Similar misbehaviour when VMs change state on reload:
![image](https://user-images.githubusercontent.com/414850/90404790-2697e000-e0a3-11ea-887f-1de86303f75c.png)

**Comment by bgmastermind** [comment]
For me it looks like this 
![image](https://user-images.githubusercontent.com/24807093/90441903-6b8f3700-e0e2-11ea-9718-dbe0a1240509.png)

**Comment by dfelsch** [comment]
I don't know if that's a separate issue, but these buggy dropdown IP lists are only showing IPv4 addresses. In pre-5.12, IPv6 addresses were shown and they could be used for filtering. Both does not work in 5.12 anymore.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- One: https://github.com/OpenNebula/one-ee/pull/431
- Docs: https://github.com/OpenNebula/docs/pull/1364
