### ISSUE TITLE
Sunstone - Hosts -> Numa tab is empty and browser is unresponsive when working with sunstone

### ISSUE THREAD

**Issue by bgmastermind** [OpenNebula/one#5039]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Numa tab in hosts is empty.

**To Reproduce**
Open numa tab

**Expected behavior**
Show NUMA

**Details**
 - Sunstone
 - Version: 5.12.

**Additional context**
Console is filling with these errors.
Also browser is unresponsive when working with sunstone. Refresh fixes it for a while, but then it start to lag again.
Windows task manager or chrome task manager do not indicate heavy cpu or memory usage. But sunstone tab just lags. 
![image](https://user-images.githubusercontent.com/24807093/90442437-536be780-e0e3-11ea-9c3e-11ade70d5e06.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
Hi @bgmastermind,

that will appear fixed in the next release, you can see the solution in [this commit](https://github.com/OpenNebula/one/commit/cc4b241d6fda6c110a6441c7c0c4e80c3248f5ec)
