### ISSUE TITLE
OpenNebula go API does not work correctly (get vmID by vmName)

### ISSUE THREAD

**Issue by MortezaBashsiz** [OpenNebula/one#5044]
**Description**
I used Golang API repository for working with OpenNebula. But when i use the sample to get the vmID by vmName it does not work correctly and always return **-1** and logs err **resource not found**

**To Reproduce**
Use the example with my username and pass and endpoint same as the following link
https://github.com/OpenNebula/one/blob/master/src/oca/go/share/examples/vm_get_by_name.go

When i build and execution it returns 
**resource not found**

But when i use the command
`onevm list --csv | grep -i [vm_name]`
the vm with name exists

**Expected behavior**
Return me the vmID

Please pay attention that i can get the vminfo by vmID but the name does not work

**Details**
 - Version: 5.12.01

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by bashsiz** [comment]
This is my sample code
```
package main

import (
	"fmt"
	"log"

	"github.com/OpenNebula/one/src/oca/go/src/goca"
)

func main() {
	client := goca.NewDefaultClient(
		goca.NewConfig("USER", "PASS", "http://IPADDR:2633/RPC2"),
	)
	controller := goca.NewController(client)

	id, err := controller.VMs().ByName("test")
	if err != nil {
		log.Fatal(err)
	}


	vm, err := controller.VM(id).Info(false)
	if err != nil {
		log.Fatal(err)
	}

	// Do some stuffs on vm
	fmt.Printf("%+v\n", vm)
}
```

And the Result

```
$ onevm list --csv | grep -i test
262,morteza.bashsiz,oneadmin,test,runn,1,2M,hostname.compute.test.local, -1d 23h59m
```

**Comment by christian7007** [comment]
Hello @bashsiz,

I've just tested it, and it seems to works for me. Can you confirm that the user you are using for your scripts have enough permission for seeing the VM? You can check this by running:

```
onevm list --csv --user <USER> | grep -i test
```

**Comment by bashsiz** [comment]
Hi @christian7007 

Thank you for your response
I use the oneadmin user which has full permission.

For your information I have tested the other scripts (like get VM info by vmID), with the same user it works fine and returns the vm information

And about the command 

`onevm list --csv --user oneadmin`

It returns all VMs list successfully .

On the other hand, I think if there was a problem with permission it should return some messages related to authentication
But it returns
 **resource not found**
And the returned id is (-1)

What is your OpenNebula Version?

**Comment by christian7007** [comment]
I think returning `resource not found` is correct, as there's no VM with that name in the pool you're looking for (by default the pool of VMs belonging to the users is used).
