### ISSUE TITLE
Way to resync opennebula db from hosts ?

### ISSUE THREAD

**Issue by Denden54** [OpenNebula/one#5047]
Hello,

We have sometime issues with opennebula. When we add a disk, the disk is correctly added to the VM, but the one commands don't show the disks, or when we migrate a VM from a host to another, the host can be stuck in migrate state and not move.

Is there a way to resync the data in the opennebula db, by scanning hosts and/or VMs ? 

Thanks

**Comment by rsmontero** [comment]
Please use the forum at https://forum.opennebula.io/ for this questions. (As a side note, there is no way to resync the VM, we'd be interested why the successful attach was not reflected in OpenNebula the log file for the VM could be useful here)
