### ISSUE TITLE
Schdeduler hangs when executing sched actions

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5048]
**Description**
When a Virtual Machine has more than one sched action in repeat mode, the scheduler sometimes hangs finding the next action to execute.

**To Reproduce**
Have a virtual machine with more than one sched action and mark them as repeat.

**Expected behavior**
It shouldn't hang.

**Details**
 - Affected Component: Scheduler
 - Version: any.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
This issue has been fixed in this [commit](https://github.com/OpenNebula/one/commit/d4a62f15c45e93124ff7cfa749d6362fd5539e85).
