### ISSUE TITLE
Unable to login from Sunstone when quotes present in password

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5049]
**Description**
If a user set a password with quotes ("), that user get the following error when trying to login from Sunstone:

```
OpenNebula is not running or there was a server exception. Please check the server logs.
```

**To Reproduce**
Login from Susntone with a user who set a password with quotes. 

**Expected behavior**
Users with quotes present in their passwords must be able to log in from Sunstone.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
fixed in 2d31acad9918b6143d17dd3a8e6930239e0d0473
