### ISSUE TITLE
Set an option to avoid deleting a disk not managed by OpenNebula for vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5051]
**Description**
The current behavior of OpenNebula is to delete all non persistent disks attached to a VM. This is done in this way to avoid the zombie disks created by OpenNebula survive the VM. For a VM managed by OpenNebula for vCenter to which a pre-existing vCenter disk has been attached, that disk will be removed after restarting the VM.

**Use case**
Users with an OpenNebula managed VM with a disk attached that is not an OpenNebula managed disk but exists in vCenter, and they do not want the disk to be removed in case it was not detached before restarting the VM.

**Interface Changes**
Changes required for Sunstone, CLI or/and API

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one-ee/pull/753
