### ISSUE TITLE
Change the hardcoded encryption key for guacamole remote access

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5053]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
The encrypted encryption key used in guacamole remote access is static.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Generate random keys

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 5.12

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- one: https://github.com/OpenNebula/one-ee/pull/334
