### ISSUE TITLE
Refactor server classes for VMRC/VNC/Guac 

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5055]
**Description**

Lots of shared code on those

**Use case**

Mostly for devs

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1132)

**Comment by sbbarragan** [comment]
PRs to merge:
- one (master): OpenNebula/one-ee/pull/1140

**Comment by FrederickBor** [comment]
@tinova PRs to merge:
- [Code (master)](https://github.com/OpenNebula/one-ee/pull/1145)
- [Code (one-6.0)](https://github.com/OpenNebula/one-ee/pull/1141)
