### ISSUE TITLE
Add Dockerfile support for image create

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5056]
**Description**
Apart from DockerHub integration it will be useful to allow image creation from Dockerfiles. This will allow the user to create an image by passing a Dockerfile to OpenNebula, something similar to:

```
oneimage create --name <name> --type OS --datastore <ds_id> --dockerfile <path_to_dockerfile>
```

**Use case**

Allow user to create images directly from Dockerfiles.

**Interface Changes**

CLI: probably new `--dockerfile` attribute should be added.
Sunstone: image creation form should be modified to add the Dockerfile option.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/721)
- [docs](https://github.com/OpenNebula/docs/pull/1429)
- [tests](https://github.com/OpenNebula/development/pull/1271)

**Comment by al3xhh** [comment]
@jloboescalona2 all yours. Sunstone support is needed and also an screenshot in the documentation about how to use it.

**Comment by jloboescalona2** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/775)
- [docs](https://github.com/OpenNebula/docs/pull/1454)

test pendings
