### ISSUE TITLE
Add support for ENTRYPOINT and ENV variables to DH imported images

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5057]
**Description**
The current approach to downloading an image from DockerHub just exports the container filesystem. This approach delegates the works of configuring the `ENTRYPOINT` and possible required `ENV` variables to the user.

It will improve the user experience if the default information is retrieved during image creation and taking advantage of the contextualization process automate the execution of the `ENTRYPOINT` and the definition of the `ENV` variables.

**Use case**
Improve user experience with complex images with default `ENTRYPOINT` and `ENV` variables.

**Interface Changes**
No interface changes is required, it will be done automatically under the hood.

NOTE: The user should be able to modify this variables, probably defined as custom variables in the VM template.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1243)
- [docs](https://github.com/OpenNebula/docs/pull/1850)
- [tests](https://github.com/OpenNebula/development/pull/1523)
- [packages](https://github.com/OpenNebula/packages/pull/248)
- [context](https://github.com/OpenNebula/addon-context-linux/pull/232)
