### ISSUE TITLE
Improve image creation to respect files with holes 

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5058]
**Description**
Currently the [downloader.sh](https://github.com/OpenNebula/one-ee/blob/master/src/datastore_mad/remotes/) takes care of executing the specific downloader which prints the image in STDOUT. The image is then read and passed through different pipes to perform different actions.

The act of printing the images and the following pipes remove the holes making a larger file, this have an impact in the performance. It will help to improve the performance to make sure that those holes are not removed, specially for large empty images.

**Additional Context**
In order to fix this 3 main parts needs to be reworked:

- The specific downloaders should pass the image in a different way (not printing them)
- Pipes must be removed from the downloader.sh
- Usage of `scp` in transfer/drivers should be replaced by `rsync`

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Is backward compatibility considered? 
Looking forward to seeing how it will be implemented for ceph, for example :)

**Comment by christian7007** [comment]
Hi @atodorov-storpool, there's nothing decided yet, but probably the idea is to change this in the creation process so it will only affect newly created images.

**Comment by vholer** [comment]
PRs to merge into master:
- https://github.com/OpenNebula/one-ee/pull/240
- https://github.com/OpenNebula/docs/pull/1359
