### ISSUE TITLE
Force IP from Sunstone stop working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5061]
**Description**
Susntone allows to force the IP for a NIC in the instantiation dialog.

This is not working anymore.

**To Reproduce**
Force the IP for a NIC at the instantiate dialog.

**Expected behavior**
The specified IP should be set.

**Details**
 - Affected Component: Sunstone
 - Version: development

**Additional context**
Sunstone is not sending the information to `oned`.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/179
- doc: https://github.com/OpenNebula/docs/pull/1282
