### ISSUE TITLE
Opennebula sunstone problem with VM Memory size in GB

### ISSUE THREAD

**Issue by bashsiz** [OpenNebula/one#5064]
**Description**
Hi
When i create a VM with sunstone, I choose Memory on GB (for example 4 GB) but after creating VM the Memory is in MB (4 MB)

**Details**
 - Sunstone panel
 - Opennebula Version 5.12.0.1

**Additional context**
I choose the 4 GB in VM creation
![Screenshot from 2020-09-07 13-24-44](https://user-images.githubusercontent.com/19620677/92369612-7b60d080-f10e-11ea-99a3-a344a11d1b0e.png)

But after creation it has 4 MB
![Screenshot from 2020-09-07 13-25-28](https://user-images.githubusercontent.com/19620677/92369713-99c6cc00-f10e-11ea-9568-0d1084ae329a.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
Hi @bashsiz ,

That will be fixed in the next release, you can check the fix in [this commit](https://github.com/OpenNebula/one/commit/8a69b87b49b6b3c33540f2e1e3e6d287ad4084df)

**Comment by bashsiz** [comment]
Hi @sbbarragan 
Thank you for your fast response

**Comment by sbbarragan** [comment]
This issue is fixed in the last versions (5.12.7)
Closing until more feedback is provided.
