### ISSUE TITLE
Show state of asynchronous actions in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5065]
**Description**
Some asynchronous actions -like creating an snapshot, deleting an snapshot, etc.- don't provide feedback about their status in Sunstone. It would be great to visualize the state of the action (success, error, in progress, etc.) in Sunstone. Currently, that information is printed in the OpenNebula log.

**Use case**
Users that don't have access to the OpenNebula log would have feedback about the asynchronous operations they execute.

**Interface Changes**
Sunstone and Core & System.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [code](https://github.com/OpenNebula/one-ee/pull/697)
