### ISSUE TITLE
Improvement in Guacamole console access

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5071]
**Description**
Refactor Guacamole client code to add new features like:
 -  _Ctrl-Alt-Del_ button
 - Keyboard modal on screen
 ...

**Interface Changes**
![image](https://user-images.githubusercontent.com/59608355/92576504-e682e200-f289-11ea-903f-29619f447ad7.png)

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
also, bring all the other enhancements (IP, service name, etc) from noVNC dialog

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1118
- doc: _pending_
- dev: _pending_
