### ISSUE TITLE
No error is returned when disk-attaching a non-existent file to a VM

### ISSUE THREAD

**Issue by rdiaz-on** [OpenNebula/one#5074]
**Description**
When attaching a disk to a virtual machine using a disk instance file, if that file does not exist, no error is returned and the return code is 0.

**To Reproduce**

```
[oneadmin@frontend ~]$ rm /tmp/invent 
[oneadmin@frontend ~]$ oned -v
OpenNebula 5.12.2 (51c21c42) Enterprise Edition 
Copyright 2002-2020, OpenNebula Project, OpenNebula Systems 

Licensed under the OpenNebula Software License (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy
of the License at https://github.com/OpenNebula/one/blob/master/LICENSE.onsla
[oneadmin@frontend ~]$ 
[oneadmin@frontend ~]$ onevm disk-attach 5 --file /tmp/invent
[oneadmin@frontend ~]$ echo $?
0
[oneadmin@frontend ~]$ 
[oneadmin@frontend ~]$ touch /tmp/invent
[oneadmin@frontend ~]$ onevm disk-attach 5 --file /tmp/invent
[one.vm.attach] Internal error parsing DISK attribute
[oneadmin@frontend ~]$ echo $?
255
```
**Expected behavior**
An error must be returned when attaching a non-existent file to a virtual machine.

**Details**
 - Affected Component: CLI
 - Hypervisor: KVM
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [Code](https://github.com/OpenNebula/one-ee/pull/199)
- [Docs](https://github.com/OpenNebula/docs/pull/1285)
