### ISSUE TITLE
onehem cannot create hook for state DONE: Wrong LCM_STATE

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#5080]
**Description**

```
$ cat > hook.tmpl <<EOF 
NAME = "test"
ON = CUSTOM
STATE = DONE
ARGUMENTS = "\$TEMPLATE terminate"
COMMAND = "test"
RESOURCE = VM
TYPE = state
EOF
$ onehook create hook.tmpl
[one.hook.allocate] Wrong LCM_STATE: 
```

Trying `LCM_STATE = ""` produces the same result. Given the table on http://docs.opennebula.io/5.12/operation/references/vm_states.html#vm-states I would have expected this to work correctly. Iirc it was working on 5.10 but is definitely not working on 5.12 latest.

**Comment by rsmontero** [comment]
LCM_STATE = INIT should be the one you are looking for. But in this case you can use just "ON=DONE". More details: https://docs.opennebula.io/5.12/integration/infrastructure_integration/hooks.html#state-hooks
