### ISSUE TITLE
oned monitoring API bug with PostgreSQL

### ISSUE THREAD

**Issue by arg7** [OpenNebula/one#5081]
**Description**
When using PostgreSQL backend, SunStone monitoring of disk, network and CPU resources doesn't work.

Log file /var/log/one/oned.log contains:
**SQL command was: SELECT vm_monitoring.body FROM vm_monitoring INNER JOIN vm_pool WHERE vmid = oid AND oid = 2 ORDER BY vmid, vm_monitoring.last_poll;, error ERROR:  syntax error at or near "WHERE"**

**To Reproduce**
This bug reproduces always with PostgreSQL.

**Details**
 - Affected Component: Sunstone
 - Version: 5.14

**Additional context**
I've investigated this bug, the SQL is not formed properly.
The solution is pretty simple, here is patch:

```
git diff HEAD
diff --git a/src/vm/VirtualMachinePool.cc b/src/vm/VirtualMachinePool.cc
index 98e423bce..00d5aac09 100644
--- a/src/vm/VirtualMachinePool.cc
+++ b/src/vm/VirtualMachinePool.cc
@@ -338,12 +338,11 @@ int VirtualMachinePool::dump_monitoring(

     cmd << "SELECT " << one_db::vm_monitor_table << ".body FROM "
         << one_db::vm_monitor_table
-        << " INNER JOIN " << one_db::vm_table
-        << " WHERE vmid = oid";
+        << " INNER JOIN " << one_db::vm_table    << " ON vmid = oid";

     if ( !where.empty() )
     {
-        cmd << " AND " << where;
+        cmd << " WHERE " << where;
     }

     cmd << " ORDER BY vmid, " << one_db::vm_monitor_table << ".last_poll;";

```

Best regards,
A. Romanov

**Comment by christian7007** [comment]
Hello @arg7, thank you for the feedback!

Would you like to submit a PR with your patch?

**Comment by arg7** [comment]
Sure, but I need to learn how to do it properly first.
Wait a minute...

**Comment by arg7** [comment]
Looks like I've managed to complete due process with PR.
Here is link: https://github.com/OpenNebula/one/pull/5087

**Comment by wolfff** [comment]
How could this issue be closed when the solution is still not present in latest release-5.12.0.3 ?
