### ISSUE TITLE
onedb improve schema upgrade visibility

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5089]
**Description**

Following `onedb` parts needs to be improved:
- `version`: should return also OpenNebula code (~LATEST) schema version, not just database version (point 1 below)
- `upgrade`: avoid doing backup, if there is no schema upgrade (point 3 below)
- `upgrade-needed` or `needs-upgrade`: subcommand which returns exitcode 0 if no database upgrade is needed (NOTE: ??maybe this could be integrated into `version` command, which could return required exit code??)

Right now, it's not easy to tell if database upgrade is necessary by a simple command run, as

1. onedb version

```
$ onedb version
Shared: 5.10.0
Local:  5.10.0
```

returns current database schema versions, but doesn't say the upgrade to `5.12.0` is necessary.

2. onedb fsck complains about version mismatch, but in case version matches, it would proceed with fsck.

```
$ onedb fsck
Version mismatch: fsck file is for version
Shared: 5.12.0, Local: 5.12.0

Current database is version
Shared: 5.10.0, Local: 5.10.0
```

3. onedb upgrade does always full backup even when no upgrade is necessary.

```
$ onedb upgrade
Sqlite database backup stored in /var/lib/one/one.db_2020-9-15_17:48:24.bck       # <===========
Use 'onedb restore' to restore the DB.

>>> Running migrators for shared tables
Database already uses version 5.12.0

>>> Running migrators for local tables
Database already uses version 5.12.0
```

**Use case**
Unattended deployments, where we need to automatically and quickly decide if `onedb upgrade` should be triggered, or run it every time we start the OpenNebula, but avoid delays with backups.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
PRs:
https://github.com/OpenNebula/one-ee/pull/353
https://github.com/OpenNebula/docs/pull/1333 (docs)
