### ISSUE TITLE
onevm snapshot-create periodic schedule will run only once

### ISSUE THREAD

**Issue by Githopp192** [OpenNebula/one#5090]
**Description**
onevm snapshot-create periodic schedule will run only once

SCHED_ACTION=[
  ACTION="snapshot-create",
  ARGS="vm",
  DAYS="0,1,2,3,4,5",
  END_TYPE="0",
  END_VALUE="1",
  ID="0",
  REPEAT="0",
  TIME="1600131600" ]

OpenNebula Scheduler Service is running.
Last Schedule action was from "Sept 15 03:00:30" (Time, where ths snapshot was created for the very first time).

Mon Sep 14 10:29:37 2020 [Z0][SCHED][I]: oned successfully contacted.
Mon Sep 14 10:29:37 2020 [Z0][SCHED][I]: Configuring scheduler for Zone ID: 0
Mon Sep 14 10:29:37 2020 [Z0][SCHED][I]: Starting scheduler loop...
Mon Sep 14 10:29:37 2020 [Z0][SCHED][I]: Scheduler loop started.
Tue Sep 15 03:00:30 2020 [Z0][VM][D]: VMs with scheduled actions:

--> /var/log/one/29.log

Tue Sep 15 03:00:30 2020 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Tue Sep 15 03:01:08 2020 [Z0][VMM][I]: VM Snapshot successfully created.
Tue Sep 15 03:01:08 2020 [Z0][VM][I]: New LCM state is RUNNING

**To Reproduce**

Schedule new periodic snapshot-create job

**Expected behavior**
Snapshot should be created on a regular base when defining "periodic" & without end date

**Details**
Hypervisor: KVM
Version: 5.10.1 Opennebula Scheduler
OS: Centos 8.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This should be solved in: https://github.com/OpenNebula/one/commit/d4a62f15c45e93124ff7cfa749d6362fd5539e85
