### ISSUE TITLE
Make the default state of a VM configurable when removed by hypervisor in hybrid deployments

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5091]
**Description**
Currently the default state of a VM is *UNKNOWN* when the VM is removed by the hypervisor in hybrid deployments. This causes OpenNebula to continue considering the VM as *RUNNING*.

**Use case**
The user wants OpenNebula to consider a VM as *POWEROFF* when removed by the hypervisor. This configuration will survive upgrades.

**Interface Changes**
Configuration.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This can be already tuned for each driver:
* Azure: https://github.com/OpenNebula/one/blob/master/src/im_mad/remotes/az-probes.d/vm/status/probe_vm_status.rb#L47
* EC2: https://github.com/OpenNebula/one/blob/master/src/im_mad/remotes/ec2-probes.d/vm/status/probe_vm_status.rb#L47

It needs to reflect the actual desired behavior of each driver.
