### ISSUE TITLE
Contextualization of password broken since 5.12

### ISSUE THREAD

**Issue by caus909** [OpenNebula/one#5092]
**Description**
Since the 5.12 update I can no longer contextualize the VM root/Admin password.
I believe it's because of the solving of this bug: https://github.com/OpenNebula/one/issues/4064

**To Reproduce**
Create a VM template, and in the Context => Configuration => User inputs section, add this :
Name: PASSWORD
Type: password
Description: Password
Mandatory: Yes (checked)
In the Context => Configuration => Custom vars section, I also have a USERNAME = root or USERNAME = Administrator variable to complete the contextualization (root for Linux, Administrator for Windows), but I think it's irrelevant

**Expected behavior**
When instantiating, the interface should ask me for the root/admin password, but nothing is asked instead.
When looking at the template, I can see this:

`CONTEXT = [
  NETWORK = "YES",
  PASSWORD = "tDzRFHEHLOhCkJw9Xc78QQ==",`

That's why I linked the bug report above, because it seems that OpenNebula is wrongly encrypting the variable to "secure" it. In 5.10, we had:

`CONTEXT = [
  NETWORK = "YES",
  PASSWORD = "$PASSWORD",`

Sunstone was correctly prompting me for the password before. Now, it seems that Sunstone is not detecting the variable due to the encryption and as such, I can no longer correctly contextualize new VM from Sunstone.

**Details**
 - Affected Component: Sunstone + Contextualization
 - Hypervisor: KVM
 - Version: 5.12.0.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @caus909 

You can disable password encryption by removing `VM_ENCRYPTED_ATTR = "CONTEXT/PASSWORD"` from oned.conf file.

We have also a [ticket](https://github.com/OpenNebula/one/issues/4971) opened to fix this.

Best,
Álex.

**Comment by al3xhh** [comment]
Closing this, we will cover this issue [here](https://github.com/OpenNebula/one/issues/4971).
