### ISSUE TITLE
Some monitoring database queries take too long to execute

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#5093]
**Description**
The following query:

```
SELECT host_monitoring.body FROM host_monitoring INNER JOIN host_pool ON hid = oid WHERE (host_monitoring.last_mon_time = (SELECT MAX(last_mon_time) FROM host_monitoring AS t WHERE t.hid = host_monitoring.hid)) ORDER BY hid, host_monitoring.last_mon_time
```

Can take too long to execute and this cause problems in the scheduler and some other componentes.

**To Reproduce**
Have too many hosts.

**Details**
 - Affected Component: core
 - Version: 5.12 and development.

**Additional context**
The solution is create and index on last_mon_time column.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
duplicates #5147
