### ISSUE TITLE
Race condition when creating VDCs in a federated environment

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5110]
**Description**
When a VDC is created in Sunstone interface the VDC is created and after that the resources add added. Sometimes the replication can take long enough to make Sunstone fails retrieving the newly created VDC information

**To Reproduce**
Create a VDC containing resources y a federated environment with a user different than `oneadmin`

**Details**
 - Affected Component:Sunstone
 - Version: development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
code : https://github.com/OpenNebula/one-ee/commit/54c0ae12ffb60661e0458121dd28749b23fd4f57
doc: https://github.com/OpenNebula/docs/commit/a23863442725c5d87dd6d9958dfbfa7ec860ee0c
