### ISSUE TITLE
VNF external alias mapping

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5112]
**Description**

Enhance VNF (and potentially required OpenNebula services) to support the maping of external NIC aliases prototyped by https://github.com/OpenNebula/one/blob/master/share/start-scripts/map_vnets_start_script without the prerequisite of running router and network nodes within a OneFlow service.

**Use case**
More details: https://support.opennebula.pro/hc/en-us/articles/360043445132-Virtual-Network-Mapping

**Interface Changes**
Extend OneGate for VR instance type.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
OneGate PRs:
(master)
https://github.com/OpenNebula/docs/pull/1325 (docs)
https://github.com/OpenNebula/development/pull/1200 (tests)
https://github.com/OpenNebula/one-ee/pull/339 (one)
(5.12)
https://github.com/OpenNebula/one-ee/pull/338 (one)

**Comment by ospalax** [comment]
PRs:
https://github.com/OpenNebula/infra/pull/541
https://github.com/OpenNebula/development/pull/1203
https://github.com/OpenNebula/marketplace-docs/pull/16
