### ISSUE TITLE
Incorrect value of `USED (REAL)` attribute in vCenter hosts

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5113]
**Description**
The value of attribute `USED (REAL)` in vCenter hosts is set with vmware *Effective CPU* which provides the total of resources available without subtracting the resources already consumed by VMs.

**To Reproduce**
Run `onehost show -x <ID>` with an *ID* of a vCener host.

**Expected behavior**
The `USED (REAL)` attribute must be set with the actual used resources.

**Details**
 - Affected Component: Monitor
 - Hypervisor: vCenter
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
doc: https://github.com/OpenNebula/docs/pull/1360

**Comment by carloshm91** [comment]
In the sunstone view is still showing incorrect values in Total Real CPU and Total Real Memory. Right now show the values of allocated values. If you run:

```onehost show <host-id>```

You can see the right values.
