### ISSUE TITLE
Disk attributes remains in the template when changing image in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5115]
**Description**
When updating a VM template in Sunstone that has a disk and then the image is changed, instead of removing the disk and adding a new one, the old disk attributes remains in the template.

**To Reproduce**
- Update a template that contains a disk and some extra attributes in the disk like OPENNEBULA_MANAGE.
- Change the image.
- Check the template, the old attributes remain there.

**Expected behavior**
Old attributes should be removed, the same way as if the disk is removed and a new one is added.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12 and development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/279
Doc: https://github.com/OpenNebula/docs/pull/1308

**Comment by jloboescalona2** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/280
Docs: https://github.com/OpenNebula/docs/pull/1308
