### ISSUE TITLE
Capacity cannot be hide/disable in cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5116]
**Description**
The `capacity_select` attribute at `create_vm` section is not working for cloud view.

**Expected behavior**
The capacity section should be hidden/disabled when creating a VM.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.4

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/548
- docs: OpenNebula/docs/pull/1382
