### ISSUE TITLE
Cores per Socket not correctly parsed at Sunstone on create dialog

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5117]
**Description**
When a VM Template, with the Cores per Socket attribute defined, is instantiated, the field is not correctly filled with the tamplate values on the create dialog view.

**To Reproduce**
   - Create a vCenter VM template and set a value for Cores per Socket
   - Go to instantiate the template
   - The value of Cores per socket is not shown.

**Expected behavior**
The value of cores per socket correctly show the value set at the VM template.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.4

**Additional context**
Even the value is not show, it's set when the VM is instantiated.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: OpenNebula/one-ee/pull/553
 - doc: OpenNebula/docs/pull/1383

**Comment by sbbarragan** [comment]
Needs testing
