### ISSUE TITLE
Make configurable cores per socket on VMs

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5118]
**Description**
Once a VM is instantiated, the number of cores per socket cannot be changed. It is required to able to change the CPU topology to be effective on next VM reboot.  

**Use case**
VMs already created that need to modify the CPU topology.

**Interface Changes**
Sunstone, CLI or/and API

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
VMware doesn't allow this change through the API, closing.
