### ISSUE TITLE
Sunstone empty user input replaced by "text" placeholder

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5120]
**Description**

Empty user input (without default) of type `text` is provided with value `text` in the Virtual Machine, instead of empty value.

Applies both for CE and EE.

**To Reproduce**

- Have a template with user input of type `text`, e.g.:

```
CONTEXT = [
  MYINPUT = "$MYINPUT",
...
INPUTS_ORDER = "MYINPUT"
USER_INPUTS = [
  MYINPUT = "O|text|| |" ]
```

- Run VM via Sunstone without providing any value

![image](https://user-images.githubusercontent.com/414850/95091864-4359a700-0727-11eb-9e17-8cf4fcb27ed7.png)

- Check VM and find `text` value in `$MYINPUT` context variable:

![image](https://user-images.githubusercontent.com/414850/95092035-76039f80-0727-11eb-8f15-d628f7077dcb.png)

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.4, 5.12.0.2dev

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/287
 - doc: https://github.com/OpenNebula/docs/pull/1309

**Comment by tinova** [comment]
waiting for tests

**Comment by tinova** [comment]
good job Sergio, thanks! 👍
