### ISSUE TITLE
Fix change token in cloud view

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5122]
**Description**
The token cannot be updated when it is done from the cloud view

**To Reproduce**
Go to cloud view, then user settings and change the token

**Expected behavior**
change token

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
- [Code](https://github.com/OpenNebula/one-ee/pull/310)
- [Docs](https://github.com/OpenNebula/docs/pull/1883)
