### ISSUE TITLE
Ask for a new name when cloning a service if actual name exceed limitation

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5123]
**Description**
When cloning a service template with associated VM template if the name is longer than 128 chars it will fails with:

```
[one.template.clone] Error allocating a new virtual machine template. Invalid NAME, max length is 128 chars
```

It would be nice if instead of just failing a new name is asked to the user or an alternative name can be passed as parameter.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1112)
- [docs](https://github.com/OpenNebula/docs/pull/1787)
- [docs](https://github.com/OpenNebula/docs/pull/1788)
