### ISSUE TITLE
Set browser tab title for VNC tab

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5126]
**Description**
Actually if a VNC session is opened in a new tab there will be the URL display as tab title. It would be great to have instead of the URL the VM name or something similar to that.

**Use case**
This is useful for final user, so they can see more clear information.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Duplicated by #4994
