### ISSUE TITLE
Sunstone Labels Normalization

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5134]
**Description**
This is a follow-up of https://github.com/OpenNebula/one/issues/1333 as the part of the problem is still there.

Problems:
- User can create tags with different casing on different VMs, because tags are not checked across VMs. This probably doesn't have easy solution.

- List of tags shows all tags. Similar tags are not groupped (already mentioned in https://github.com/OpenNebula/one/issues/1333#issuecomment-426978320):
![image](https://user-images.githubusercontent.com/414850/96104417-1ea8c080-0ed9-11eb-838c-0624447a8937.png)

- When selecting a tag, the filtered VMs are not respecting the selected casing. On example below I select "Test", but it shows VMs with both "test" and "Test":
![image](https://user-images.githubusercontent.com/414850/96105036-dd64e080-0ed9-11eb-9cfe-b8ca46aa7c38.png)
This is a current misbehaviour and should be automatically fixed by previous point.

**Expected behavior**
- List of tags is normalized (e.g., "test" -> "Test", "test with spaces" -> "TestWithSpaces")

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.4

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Proposal: have Sunstone ignoring the labels case, and show them in lowercase with the first letter in upper case.

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/803
- doc: _pending_
- dev: _pending_

**Comment by tinova** [comment]
keeping for 6.2 to refactor code

**Comment by tinova** [comment]
will revisit in new React Sunstone
