### ISSUE TITLE
docker_machine driver depends on obsolete software to build

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5135]
**Description**
Golang 'dep' is used to build the docker_machine driver. It is an [archived ](https://github.com/golang/dep) tool.

**To Reproduce**
The build of docker_machine driver requires a historic tool.

**Expected behavior**
Build docker_machine driver using Go's modules

**Details**
 - Affected Component: [docker_machine]
 - Hypervisor: [docker]
 - Version: [5.12]

**Additional context**
Not sure is this a bug or a feature. For me - it is a bug. A pull request is pending...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
removing support for docker machine
