### ISSUE TITLE
Support for changing the IP address of an already instantiated VM

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5137]
**Description**
Currently, in order to change the IP address of a virtual machine, it is necessary to detach and attach the corresponding NIC to a virtual network. It is required to be able to change the IP address of a VM without having to detach and attach the NIC to a virtual network.

**Use case**
Change an IP address of a VM dynamically without having having to detach and attach it the NIC to a virtual network

**Interface Changes**
Sunstone, CLI or/and API

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
IMO the NIC and the IPs should be separated.
A workaround for this is to have eth only NIC and add the IP as an ALIAS...
In addition, this way the the NIC's MAC address could be different than the IP (well, it is known that the IPs are mapped as MACS internally in opennebula... ;-) )

**Comment by rsmontero** [comment]
Yes NICs automatically get an IP. Those scenarios that require IP management as a separated component can:

* Use IPAM drivers 
* Adopt the approach proposed by @atodorov-storpool Use an Ethernet AR and attach NIC_ALIAS for a IPv4 AR.

Closing.
