### ISSUE TITLE
Sunstone build update for current Node.js ecosystem

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5138]
**Description**
Current Sunstone build depends on Bower and legacy Node.js versions, while FireEdge requires recent Node.js/tools versions. The goal would be to align Sunstone build with FireEdge so that both components are built same way, by same tools and versions.

**Use case**
Build Sunstone within package build and make it more transparent.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
closing as current Sunstone will be be deprecated with #5422
