### ISSUE TITLE
Removing a virtual machine from OneFlow

### ISSUE THREAD

**Issue by Red967** [OpenNebula/one#5142]
**Description**
After removing the virtual machine from the OneFlow service. The service starts to delete all other virtual machines.

**To Reproduce**
Create new OneFlow Service and terminate-hard some VM from OneFlow Service

**Details**
 - Version: 5.12.0.1

**Additional context**
![Screenshot_2020-10-21 OpenNebula Sunstone Cloud Operations Center](https://user-images.githubusercontent.com/22501325/96707904-22d55200-13a1-11eb-9957-9c0ca021471b.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Red967** [comment]
@al3xhh Greetings. As I understand it, the problem is that the service is not updated and function done_wd_cb from LifeCycleManager.rb is called endlessly?

**Comment by al3xhh** [comment]
Hello @Red967 

Thanks for reporting the bug. Indeed it was related with done_wd_cb. I have already fixed it and it will be released in future releases.

[Here](https://github.com/OpenNebula/one/commit/5ec4d4116325058ef7e0c6fcbc655dec761e2c66) you can check the commit.

Best,
Álex.
