### ISSUE TITLE
OneFlow does not use monitoring information for elasticity rules

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5143]
**Description**
Elasticity rules do not apply for monitoring information.

**To Reproduce**
Add elasticity rule that references to a monitoring attribute like CPU.

**Expected behavior**
OneFlow should check monitoring information from VM.

**Details**
 - Affected Component: OneFlow
 - Version: 5.12 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/349)
- [docs](https://github.com/OpenNebula/docs/pull/1331)
- [docs](https://github.com/OpenNebula/docs/pull/1330)
