### ISSUE TITLE
Allow live migration for LVM datastores without shared storage

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5144]
**Description**
In order to support live migration when LVM datastores are used the storage under the datastore path `/var/lib/one/datastores/<id>` needs to be shared to allow all hosts to access plain text files stored there (e.g context disk).

It would be useful to improve the drivers to be aware of this and copy this files to the new hypervisor.

**Use case**
Support live migration with LVM datastores without the need of shared storage.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
fixed in 6.0.3
