### ISSUE TITLE
READY=YES, no visual feedbak in VM list (role view)

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#5146]
**Description**
When the "report ready" strategy is used for flow sync, Sunstone < 5.12 provided a visual feedback that the VM reached the READY status from the VM list in the role tab. This behavior is missing in 5.12

**To Reproduce**
See above

**Expected behavior**
Provide visual feedback about READY status in role VM list

**Details**
 - Affected Component: Sunstone - ONeFlow interface
 - Hypervisor: -
 - Version: 5.12.x

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/356
 - doc: https://github.com/OpenNebula/docs/pull/1332
