### ISSUE TITLE
Sunstone VM list not returning MONITORING data?

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#5148]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**

Viewing a VM directly in sunstone (/vm/10) produces monitoring data correctly in the xhr call:

```
MONITORING: {CPU: "3.0", DISKRDBYTES: "381226412", DISKRDIOPS: "13314", DISKWRBYTES: "2144691712",…}
```

However viewing the list (/vm?timeout=false&pool_filter=-2 xhr call) returns `MONITORING: {}` for everything.

`onevm list` also returns the monitoring details correctly.

**Details**
 - Affected Component: Sunstone Backend(?)
 - Version: 5.12.0.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
You should set `:get_extended_vm_info: true` on `/etc/one/sunstone-server.conf`, after that restart Sunstone or Apache to apply the changes, also clear your browser cache.

Closing it as it seems a configuration problem, reopen it if needed.
