### ISSUE TITLE
Add Sunstone option to avoid importing VM Template from the marketplace

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5149]
**Description**

Sometimes (like in vCenter envs) is preferable not to import the VM Template when importing an app from the marketplace

**Interface Changes**

Sunstone import flow from marketplace should include an option that works like the "--no" param added here: 

  44beefa77e3303189273d6b6d961643a554bfa59

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/736
- doc: https://github.com/OpenNebula/docs/pull/1436
- dev: _pending_
