### ISSUE TITLE
Sunstone Overcommit CPU does not change the Capacity

### ISSUE THREAD

**Issue by bashsiz** [OpenNebula/one#5150]
**Description**
Value of "Capacity CPU" in Sunstone is different from "Overcommitment CPU"

**To Reproduce**
Change CPU Overcommitment to 17600 but does not change the Capacity 

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12.0.3

![Screenshot from 2020-10-27 23-29-22](https://user-images.githubusercontent.com/19620677/97359713-6ef92880-18b2-11eb-95a1-5c6768723478.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by bashsiz** [comment]
Hi again
Could you please HELP me how can I fix it?

**Comment by tinova** [comment]
When you change the overcommitment value, you should be able to reach a situation where the capacity is overcommitted, ie, you reach more than 100 allocation. Can you confirm this is the case?

**Comment by bashsiz** [comment]
Aha
Yes thank you when i change the overcommitment  value, I can go more than 100% .
Same as following 
![image](https://user-images.githubusercontent.com/19620677/98674268-cfd23780-236d-11eb-9a55-fe4a2f6c843f.png)

**Comment by tinova** [comment]
ok, closing this as is working as expected. please reopen if there is any further nuance.
