### ISSUE TITLE
Sunstone user inputs with the same name are overwritten when instantiate flow template

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5152]
**Description**
When there are multiple roles with the same VM template, their user inputs values are overwritten.

**To Reproduce**
- Have a VM template with user input of type `text`, e.g.:

```
CONTEXT = [
  MYINPUT = "$MYINPUT",
...
INPUTS_ORDER = "MYINPUT"
USER_INPUTS = [
  MYINPUT = "M|text|my input description| |text_default_value" ]
```
- Instantiate a service with two or more roles with this VM template

![image](https://user-images.githubusercontent.com/59608355/97574279-44f75180-19eb-11eb-88b1-3537febef917.png)

- Check roles VM and find `text` value in $MYINPUT context variable

![image](https://user-images.githubusercontent.com/59608355/97574592-c4852080-19eb-11eb-8384-b0a17767b4a8.png)

**Expected behavior**
Each roles VM should have his user inputs values

**Details**
 - Affected Component: Sunstone
 - Version: 5.12

## Progress Status
- [x] Testing - QA
- [x] Code committed to development branch
- [x] Branch created 
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/374
 - doc: https://github.com/OpenNebula/docs/pull/1339
 - dev: _pending_

**Comment by tinova** [comment]
needs to be backported to one-5.12
