### ISSUE TITLE
HOST_SHARE combined disk stats missing in 5.12

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#5154]
**Description**

In 5.10 and previous, `HOST_SHARE` would include some values auto-calculated from the `DATASTORE` element such as `USED_DISK` and `MAX_DISK`. In the monitoring rewrite for 5.12 these appear to have been removed. We were using these for `DEFAULT_SCHED` so that we could spread VMs around the platform based on disk capacity of the hosts as well (for non-shared datastores). Is there a way to restore or emulate this behaviour?

Our rank expression was: `- ( (USED_CPU / MAX_CPU + MEM_USAGE / MAX_MEM) * 1000 + (USED_DISK / MAX_DISK) * 1000 )`

**Details**
 - Affected Component: Monitor
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Actually the information is still there.

```
  <HOST_SHARE>
    <MEM_USAGE>2097152</MEM_USAGE>
    <CPU_USAGE>100</CPU_USAGE>
    <TOTAL_MEM>8008180</TOTAL_MEM>
    <TOTAL_CPU>800</TOTAL_CPU>
    <MAX_MEM>8008180</MAX_MEM>
    <MAX_CPU>1600</MAX_CPU>
    <RUNNING_VMS>1</RUNNING_VMS>
    <VMS_THREAD>1</VMS_THREAD>
    <DATASTORES>
      <DISK_USAGE><![CDATA[0]]></DISK_USAGE>
      <FREE_DISK><![CDATA[25379]]></FREE_DISK>
      <MAX_DISK><![CDATA[110838]]></MAX_DISK>
      <USED_DISK><![CDATA[85459]]></USED_DISK>
    </DATASTORES>
```

Unfortunately the paths to evaluate the RANK expression was not updated to look into HOST_SHARE/DATASTORE. 

This will be solved in the next release. Sorry for the inconvenience...

In the meantime you can use the full xpath, but this need to be with double quotes

```
SCHED_RANK="\"DATASTORES/FREE_DISK\" / \"DATASTORES/MAX_DISK\")"
```

You are escaping the / in the Xpath from the / as math operator

**Comment by mzealey** [comment]
The problem is that this is not the same as before. Previously it was the sum of all the datastores, here it appears to be the host root filesystem. We have several datastores on different mount points (only 1 active atm) and the numbers are not the same:

```
    <DATASTORES>
      <DISK_USAGE><![CDATA[0]]></DISK_USAGE>
      <DS>
        <FREE_MB><![CDATA[6594574]]></FREE_MB>
        <ID><![CDATA[103]]></ID>
        <TOTAL_MB><![CDATA[6706690]]></TOTAL_MB>
        <USED_MB><![CDATA[112117]]></USED_MB>
      </DS>
      <FREE_DISK><![CDATA[193204]]></FREE_DISK>
      <MAX_DISK><![CDATA[204700]]></MAX_DISK>
      <USED_DISK><![CDATA[11496]]></USED_DISK>
    </DATASTORES>

```
