### ISSUE TITLE
Sunstone does not respect the "memcache_host" option when memcache-dalli is used

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/one#5156]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When I have config like this in `sunstone-server.conf`:
```
# Place where to store sessions, this value can be memory, memcache or memcache-dalli
# Use memcache when starting multiple server processes, for example,
# with passenger
#
# NOTE. memcache needs a separate memcached server to be configured. Refer
# to memcached documentation to configure the server.
:sessions: 'memcache-dalli'

# Memcache configuration
:memcache_host: opennebula-memcached
:memcache_port: 11211
:memcache_namespace: opennebula.sunstone
```
Then for some reason sunstone is trying to connect to 127.0.0.1 even despite the fact that `openebula-memcached` is resolved to 172.18.0.3:
```
App 1322 output: opennebula-memcached:11211
App 1457 output: W, [2020-09-23T12:44:36.297812 #1457]  WARN -- : 127.0.0.1:11211 failed (count: 0) Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 11211
App 1457 output: [ 2020-09-23 12:44:36.3085 1457/0x0000561ed883bf60(Worker 1) utils.rb ]: *** Exception Dalli::RingError in Rack application object (No server available) (process 1457, thread 0x0000561ed883bf60(Worker 1)):
```
With `:sessions: memcache` (not dalli) it works fine.

**To Reproduce**
1. Run memcache on a different host than sunstone.
2. Edit `sunstone-server.conf` to use `memcache-dalli` and setup `memcache_host` to point to the memcached server
3. Restart sunstone and try to connect to it

**Expected behavior**
Sunstone should work with a `memcache_host` pointing to any host different from localhost.

**Details**
 - Affected Component: Sunstone, memcache
 - Hypervisor: KVM
 - Version: opennebula-sunstone-5.12.0.1-1.ce.el8.noarch

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1753
- Docs: 
    - https://github.com/OpenNebula/docs/pull/2143
    - https://github.com/OpenNebula/docs/pull/2144
