### ISSUE TITLE
Non-shared datastore scheduling doesn't work?

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#5157]
**Description**

Specifying a custom rank for datastore doesn't seem to work (on non-shared datastores at least)? I thought it did in 5.10 but perhaps it was only ever for shared ones?

```
DEFAULT_DS_SCHED = [
    POLICY = 2,
    rank   = "- FREE_MB"
]
```

produces

```
Tue Nov  3 10:26:53 2020 [Z0][HOST][D]: Discovered Hosts (enabled):
ID          : 2
CLUSTER_ID  : 100
PUBLIC      : 0
MEM_USAGE   : 10027008
CPU_USAGE   : 480
MAX_MEM     : 263716864
MAX_CPU     : 4800
FREE_DISK   : 16779065
RUNNING_VMS : 3

 DSID         FREE_MB 
------------------------------
  101         3505976 
  102         6651704 
  103         6621385 
...
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: Rank evaluation for expression : - FREE_MB
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: ID: 101 Rank: 0
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: ID: 102 Rank: 0
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: ID: 103 Rank: 0
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: ID: 104 Rank: 0
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: ID: 105 Rank: 0
Tue Nov  3 10:26:53 2020 [Z0][RANK][D]: ID: 106 Rank: 0

```

**Details**
 - Affected Component: Scheduler
 - Version: 5.12.0.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
@mzealey Unfortunately you are right the scheduler DS policies doesn't work for non-shared DS. It never worked, not even in older releases.

Right now the DS are ranked globaly, compatibility between host and DS are solved later. Non-shared DS can have different size (total, free, used) on every host, so it's not clear how the policy should work for them. It would need quite a big code change to do DS policy after the host is chosen to be able to rank correctly non-shared DS.

Added just a small note to documentation, that scheduling DS policy works only for shared. [PR](https://github.com/OpenNebula/docs/pull/2092)
