### ISSUE TITLE
sunstone's kvm view has search_data column in VM list page

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5158]
**Description**
The sunstone's _kvm_ view mode has a column named _search_data_ in the VMs list

**To Reproduce**
set `:mode: kvm` in /etc/one/sunstone-server.conf
view the VM's list

**Expected behavior**
There should be no _search_data_ column or the containing base64 encoded string...

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.12.0.3]

**Additional context**

Digging further there are differences in the commented-out elements but I am not sure is this related or expected...
Running `diff -ur /etc/one/sunstone-views/{mixed,kvm}` will show all differences.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
This is happening because in the /etc/one/sunstone-views/kvm/<your_view>.yaml has that column uncommented:

https://github.com/OpenNebula/one-ee/blob/release-5.12.0/src/sunstone/etc/sunstone-views/kvm/admin.yaml#L371

In newer versions, this issue is already fixed.
Thank you for letting us know.
