### ISSUE TITLE
Sunstone doesn't allow to attach external NIC alias

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5159]
**Description**

All NIC aliasees attached over Sunstone are internal (directly configured IPs inside VM) and user doesn't have an easy way how to add external alias, which is not configured inside the VM, but some external mapping logic (VNF) ensures the traffic which targets the aliased IP gets into the VM.

External NIC aliases are added with ``EXTERNAL=yes`` template parameter.

Sunstone is missing a check box to easily select (internal=default / external) NIC alias type.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/718
- doc: https://github.com/OpenNebula/docs/pull/1427
- dev: https://github.com/OpenNebula/development/pull/1270
