### ISSUE TITLE
Wrong formatting in monitoring section in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5161]
**Description**

When keys are too long, the table showing monitoring information is malformed.

**To Reproduce**

Create a VM with a long monitoring key.

**Expected behavior**

Table should adapt to the content.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12 and development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
 - one: https://github.com/OpenNebula/one-ee/pull/393
 - doc: https://github.com/OpenNebula/docs/pull/1344

**Comment by tinova** [comment]
doc needs to be added to 5.12.7 RNs, it didn't make it in 5.12.6
