### ISSUE TITLE
Upgrade guide for federation has wrong steps

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5164]
**Description**

The process to upgrade a federation is wrong described in the documentation.

**Expected behavior**

Documentation should be updated with correct steps.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Also please add a reduced steps guide to upgrade from maintenance versions (5.12.1 -> 5.12.2). No need to upgrade DB for instance.

Basically, bring back this: http://docs.opennebula.io/5.10/intro_release_notes/upgrades/upgrade_510.html

**Comment by al3xhh** [comment]
PR to merge in 5.12 and master:

- [docs](https://github.com/OpenNebula/docs/pull/1351)
