### ISSUE TITLE
CLI fails to instantiate some VM templates with user inputs

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5170]
**Description**

There are 2 cases of VM templates with non-interactive user inputs which fails to run VM.

* Simple template with password:

```
$ cat <<"EOF" >/tmp/test
CONTEXT = [
  INPUT = "$INPUT",
  NETWORK = "YES",
  SSH_PUBLIC_KEY = "$USER[SSH_PUBLIC_KEY]" ]
CPU = "0.1"
GRAPHICS = [
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
INPUTS_ORDER = "INPUT"
MEMORY = "65536"
MEMORY_UNIT_COST = "MB"
NAME = "test"
OS = [
  BOOT = "" ]
USER_INPUTS = [
  INPUT = "O|password|Input something" ]
VCPU = "1"
EOF
$ onetemplate create /tmp/test
$ onetemplate instantiate --user-inputs INPUT=some test
undefined method `gsub' for nil:NilClass
```

* Complex K8s appliance from Marketplace (although password is used here as well, it's not the only problem)

```
$ onemarketapp export 'Service Kubernetes 1.18 - KVM' 'k8s' -d 1
$ onetemplate instantiate --user-inputs some=some k8s
undefined method `gsub' for nil:NilClass
```

Also, usage of CLI `--user-inputs` is
- not properly tested 
- doesn't have even mention in the documentation

**To Reproduce**
See examples above.

**Expected Behaviour**
It can fail, but not with unhandled Ruby error.

**Details**
 - Affected Component: CLI
 - Version: 5.12.6

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/415)
- [docs](https://github.com/OpenNebula/docs/pull/1357)
- [resolved issues](https://github.com/OpenNebula/docs/pull/1358)
- [tests](https://github.com/OpenNebula/development/pull/1218)
