### ISSUE TITLE
Add VALIDATE option to RAW part

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5173]
**Description**

RAW section in VM Template accepts a VALIDATE="YES|NO" to skip schema validation. Sunstone needs to expose this option.

Also, add it here: http://docs.opennebula.io/5.12/operation/references/template.html#hypervisor-section

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/713
- doc: _pending_
