### ISSUE TITLE
Onecfg integration into OpenNebula Enterprise Tools

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5175]
**Description**
Reallocate `onecfg` code to make use of existing libraries and achieve a better integration with the other enterprise tools.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
First set of PRs were already merged.

Second set of PRs, which adds `patch` subscommand follows and is expected to be merged into **master**:
- https://github.com/OpenNebula/one-ee/pull/581
- https://github.com/OpenNebula/one-ee-tools/pull/10
- https://github.com/OpenNebula/packages/pull/199
- https://github.com/OpenNebula/development/pull/1240
- https://github.com/OpenNebula/docs/pull/1394
