### ISSUE TITLE
Allow one.vm.updateconf in cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5176]
**Description**
Sunstone [cloud view](https://github.com/OpenNebula/one/blob/master/src/sunstone/etc/sunstone-views/mixed/cloud.yaml) doesn't have an option for updating the VM Conf section when [the section is enabled](https://github.com/OpenNebula/one/blob/master/src/sunstone/etc/sunstone-views/mixed/cloud.yaml#L51). Other views have it. If you force it by adding it to the yaml file and restart Sunstone, it adds a button, however the button is not functional.

![image](https://user-images.githubusercontent.com/33811723/98842024-8ede2f80-240e-11eb-95fe-d2531ff015b6.png)

**Use case**
Allow end users to reset their VM password.

**Interface Changes**
Make the button functional

**Additional Context**
In user.yaml the option is located [under the vms-tab identation](https://github.com/OpenNebula/one/blob/master/src/sunstone/etc/sunstone-views/mixed/user.yaml#L336-L408). In cloud.yaml the action would be [located under provision-tab](https://github.com/OpenNebula/one/blob/master/src/sunstone/etc/sunstone-views/mixed/cloud.yaml#L42-L101)

## Progress Status
- [x] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1737
- Conf files: https://github.com/OpenNebula/one-ee/pull/1738
- Docs: https://github.com/OpenNebula/docs/pull/2128
