### ISSUE TITLE
Error reducing memory overcommitment from Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5179]
**Description**
When reducing the memory overcommitment from Sunstone, the `RESERVED_MEM` attribute is not sending a correct value. Also, if memory overcommitment is not modified and click on update, Suntone is sending `RESERVED_MEM` empty causing the overcommitment is reset to the actual host memory.

**To Reproduce**
Reduce the memory overcommitent in Sunstone, note that the memory overcommitment value is not correct. Then click on update again without modifying the memory overcommitment value, note that the memory overcommitment is reset to the actual host memory.

**Expected behavior**
When reducing the memory overcommitment in Sunstone the `RESERVED_MEM` must be set with the actual target value. When clicking on update without modifying the memory value, the current configured value should be set in `RESERVED_MEM`.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/460
