### ISSUE TITLE
Using costs in OpenNebula

### ISSUE THREAD

**Issue by sysadmincaos** [OpenNebula/one#5182]
**Description**
Sometimes, when I apply a cost value for “Disk”, it disappears and, then, when I calculate VM cost, I get an incorrect value. 

**Description**
I’m assigning theses values:
-     Memory: 0.0015 per GB (and hour)
-     CPU: 0.01 per CPU (and hour)
-     Disk: 0.000768 per GB (and hour)

However, as you can see at attached files, total VM cost is the same…

**To Reproduce**
Assing value in a template, click on "Update" and then, recheck template

**Expected behavior**
When you recheck template, you could see values previously assigned.

**Details**
OpenNebula version: 5.10.1
Hypervisor: KVM

**Comment by tinova** [comment]
Consider also unifying the TOTAL calculations to reduce complexity

**Comment by sysadmincaos** [comment]
and how can I unify the TOTAL calculations in OpenNebula 5.10.1?

**Comment by tinova** [comment]
Sorry, my comment is an annotation to guide the development, Sunstone can show only the TOTAL cost and not split per VM attribute. This won't help with an OpenNebula 5.10.1 unfortunately.

**Comment by sbbarragan** [comment]
Hi @sysadmincaos,

This issue cannot be replicated,

Anyway, we recommend you update to a more recent version such as 5.12
You can check more information [here](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#upgrading-from-previous-extended-steps) about upgrading from 5.6.x+

Will reopen if additional feedback is given
