### ISSUE TITLE
Allow varibles inside SCHED_DS_REQUIREMENTS

### ISSUE THREAD

**Issue by mindwarex** [OpenNebula/one#5184]
**Description**
To allow input variables (user based) to be used within SCHED_DS_REQUIREMENTS - similar to how it's already implemented for SCHED_REQUIREMENTS 

We already user input in SCHED_REQUIREMENTS to determine cluster placement which works great, it seems the functionality is however missing for doing the same with datastores.

**Use case**
It would allow user input to determine specific datastores at the template level. For example, the user could choose between Tier1 or Tier2 storage as a template option, and the SCHED_DS_REQUIREMENTS places it accordingly when it's instantiated.

**Interface Changes**
None required - The Scheduler tab on the template pages already contain a "Expression" box for Datastore requirements. The input would go here.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
I think this works well. @mindwarex  try to explain more details for your use case.

This is a shortened list of my test:
```
$ onedatastore list
  ID USER     GROUP    NAME                        SIZE AVA CLUSTERS IMAGES TYPE DS      TM      STAT
 104 oneadmin oneadmin ds4                         4.6T 69% 0             0 sys  -       dummy   on  
 103 oneadmin oneadmin ds3                         4.6T 69% 0             0 sys  -       dummy   on  
 102 oneadmin oneadmin ds2                         4.6T 69% 0             0 sys  -       dummy   on  
 101 oneadmin oneadmin ds1                         4.6T 69% 0             0 sys  -       dummy   on  
 100 oneadmin oneadmin ds0                         4.6T 69% 0,100,10      0 sys  -       dummy   on

$ onedatastore show 103                                                
...
DATASTORE TEMPLATE                                                              
VAR="abc"        <----- Variable used for sched_ds_requirements

$ onevm show 12
...
VIRTUAL MACHINE HISTORY                                                         
SEQ UID  REQ   HOST         ACTION       DS           START        TIME     PROLOG
  0 -    -     host4        none        103  01/05 16:34:31   0d 00h06m   0h00m00s    <------ Correctly deploy on datastore 103

USER TEMPLATE                                                                   
SCHED_DS_REQUIREMENTS="VAR=abc"  <----- Request the variable value

```
