### ISSUE TITLE
Change NIC network on VM template instantiate dialog doesn't work

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5187]
**Description**
If the network of a VM template NIC is changed in the instantiate dialog the change doesn't take effect.

**To Reproduce**
- Define a VM template with at least one NIC.
- Click, on instantiate
- Before instantiate it, change the virtual network for the NIC
- Instantiate
- The VM is instantiated with the original network

**Expected behavior**
The new VM is instantiated with the modified network.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.6

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:

**Comment by tinova** [comment]
Needs testing
