### ISSUE TITLE
OpenNebula (oned) sometimes fails to remove lock file on exit and refuses to start

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/one#5189]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When oned process is restarted via service manager then sometimes it leaves its lock file behind (`/var/lock/one/one`). The restart will then fail or any subsequent start. The reason for failure is leftover lock file due to which oned thinks it is running already.

**To Reproduce**
This happened to me in container environment using the supervisord but it may have happen in other deployments:
```
[root@245ffd3d6172 /]# gpasswd -a oneadmin docker
Adding user oneadmin to group docker
[root@245ffd3d6172 /]# supervisorctl restart opennebula
opennebula: stopped
opennebula: ERROR (spawn error)
[root@245ffd3d6172 /]# ls -l /var/lock/one/one 
-rw-r----- 1 oneadmin oneadmin 0 Nov 27 05:38 /var/lock/one/one
[root@245ffd3d6172 /]# rm -f /var/lock/one/one 
[root@245ffd3d6172 /]# supervisorctl restart opennebula
opennebula: ERROR (not running)
opennebula: started
[root@245ffd3d6172 /]#
```

**Expected behavior**
The failed deletion on the exit is not so much an issue as the empty stale lock file - it would be better if lock file contained the pid number of the process and the oned would check if the lock file is stale or not on start and refused to start only if a process with such pid is actually running.

**Details**
 - Affected Component: oned
  - Version: 5.13.80

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
> and refused to start only if a process with such pid is actually running.

I'd add and the process with the given pid is oned...
