### ISSUE TITLE
LXD container status after reboot

### ISSUE THREAD

**Issue by wirwolf** [OpenNebula/one#5190]
**Description**

**To Reproduce**
reboot hots after creating new lxc container 
**Expected behavior**
Container status equals real status container

**Details**
 - Affected Component: Sunstone
 - Hypervisor: lxd
 - Version: OpenNebula 5.12.0.3
- Ubuntu Focal: 20.04

**Additional context**
![Screenshot_20201127_130330](https://user-images.githubusercontent.com/8457572/100443575-9eb66e80-30b2-11eb-8c00-ce7b44f564db.jpg)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by wirwolf** [comment]
@carlosms @dann1

**Comment by dann1** [comment]
The monitoring drivers should detect the container running after some time the node has been restarted. The following log belongs to a VM I created and restarted the node

```
Fri Nov 27 16:20:02 2020 [Z0][VM][I]: New state is ACTIVE
Fri Nov 27 16:20:02 2020 [Z0][VM][I]: New LCM state is PROLOG
Fri Nov 27 16:20:05 2020 [Z0][VM][I]: New LCM state is BOOT
Fri Nov 27 16:20:05 2020 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/13/deployment.0
Fri Nov 27 16:20:06 2020 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Fri Nov 27 16:20:06 2020 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: Processing disk 0
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: Using qcow2 mapper for /var/lib/one/datastores/0/13/disk.0
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: Mapping disk at /var/snap/lxd/common/lxd/storage-pools/default/containers/one-13/rootfs using device /dev/nbd0
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: Mounting /dev/nbd0p1 at /var/snap/lxd/common/lxd/storage-pools/default/containers/one-13/rootfs
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: Mapping disk at /var/lib/one/datastores/0/13/mapper/disk.1 using device /dev/loop2
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: Mounting /dev/loop2 at /var/lib/one/datastores/0/13/mapper/disk.1
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: deploy: --- Starting container ---
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: ExitCode: 0
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Fri Nov 27 16:20:12 2020 [Z0][VMM][I]: Successfully execute network driver operation: post.
Fri Nov 27 16:20:12 2020 [Z0][VM][I]: New LCM state is RUNNING
Fri Nov 27 16:25:11 2020 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Fri Nov 27 16:25:11 2020 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Nov 27 16:25:11 2020 [Z0][VM][I]: New state is POWEROFF
Fri Nov 27 16:25:11 2020 [Z0][VM][I]: New LCM state is LCM_INIT
```

You can see in the following entries, the 1st one being the last entry after starting the container
and the 2nd one when the monitoring drivers detect the container as STOPPED

> Fri Nov 27 16:20:12 2020 [Z0][VM][I]: New LCM state is RUNNING
Fri Nov 27 16:25:11 2020 [Z0][LCM][I]: VM running but monitor state is POWEROFF

You can adjust the monitoring intervals in [**oned.conf**](https://github.com/OpenNebula/one/blob/bce8f9f40f33304516a4779d0d7f606ef2866e14/src/monitor/etc/monitord.conf#L81-L100)

**Comment by dann1** [comment]
It should however not take that long to update the VM status

The previous log belonged to a single node (frontned + hypervisor) setup, the following log is a separated node forcibly rebooted.

```
Fri Nov 27 16:39:47 2020 [Z0][VM][I]: New LCM state is RUNNING
Fri Nov 27 16:43:06 2020 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Fri Nov 27 16:43:06 2020 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Nov 27 16:43:06 2020 [Z0][VM][I]: New state is POWEROFF
Fri Nov 27 16:43:06 2020 [Z0][VM][I]: New LCM state is LCM_INIT
```

Takes 1 less min, still a lot.

These are 2 logs for 2 containers forcibly powered off when the VM was reported RUNNING.

```
Fri Nov 27 16:48:07 2020 [Z0][VM][I]: New LCM state is RUNNING
Fri Nov 27 16:48:18 2020 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Fri Nov 27 16:48:18 2020 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Nov 27 16:48:18 2020 [Z0][VM][I]: New state is POWEROFF
Fri Nov 27 16:48:18 2020 [Z0][VM][I]: New LCM state is LCM_INIT
```

```
Fri Nov 27 16:45:37 2020 [Z0][VM][I]: New LCM state is RUNNING
Fri Nov 27 16:46:11 2020 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Fri Nov 27 16:46:11 2020 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Nov 27 16:46:11 2020 [Z0][VM][I]: New state is POWEROFF
Fri Nov 27 16:46:11 2020 [Z0][VM][I]: New LCM state is LCM_INIT
```

The time makes sense considering [the default value of the VM state monitoring probe](https://github.com/OpenNebula/one/blob/bce8f9f40f33304516a4779d0d7f606ef2866e14/src/monitor/etc/monitord.conf#L97)

**Comment by wirwolf** [comment]
I remove lxd container in console "lxd remove one-2" and after that I can not delete this container from frontend. In log file system write "container not found" but in interface status is steal runing

**Comment by dann1** [comment]
I can't use the `lxd remove` command, but if the container doesn't exist then the poweroff action will fail.

You can try the [recover](http://docs.opennebula.io/5.12/operation/vm_management/vm_instances.html?highlight=recover#life-cycle-operations-for-administrators) action. See the troubleshooting section.

**Comment by wirwolf** [comment]
i set all probes to 1 second, remove all vms(however when I run ```lxc ls``` in cli i see stopped containers that i deleted in UI interface)
```
root@node-master-2:/# cat /etc/one/monitord.conf | grep MONITOR_VM
    MONITOR_VM     = 1,
root@node-master-2:/# lxc ls
+-------+---------+------------------+------+------------+-----------+
| NAME  |  STATE  |       IPV4       | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+------------------+------+------------+-----------+
| one-5 | RUNNING | 10.0.20.0 (eth0) |      | PERSISTENT | 0         |
+-------+---------+------------------+------+------------+-----------+
root@node-master-2:/# lxc stop one-5
root@node-master-2:/# lxc ls
+-------+---------+------+------+------------+-----------+
| NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+------+------+------------+-----------+
| one-5 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
root@node-master-2:/# sleep 5
root@node-master-2:/# onevm list

  ID USER     GROUP    NAME                                                            STAT  CPU     MEM HOST                                             TIME
   5 oneadmin oneadmin debug                                                           runn    1    768M node-master-2                                    0d 00h08
root@node-master-2:/# 
```
