### ISSUE TITLE
Implement purge done operation in OneFlow server

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5191]
**Description**
Currently when a service is deleted, the service is left in the database in DONE state. This can lead to multiple problems in case there are too many services in DONE state.

**Use case**
Remove services in DONE.

**Interface Changes**
OneFlow server.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/569)
- [docs](https://github.com/OpenNebula/docs/pull/1389)
- [tests](https://github.com/OpenNebula/development/pull/1237)

**Comment by al3xhh** [comment]
Sunstone support is needed.

**Comment by tinova** [comment]
Needs button to trigger the purge DONE

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/935)
- [Docs](https://github.com/OpenNebula/docs/pull/1505)
