### ISSUE TITLE
Delete services when they are terminated

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5192]
**Description**
Currently services are left in DONE state when they are deleted. This can lead to multiple problems, by default services are going to be deleted. An option in the configuration file will be added to tune this feature.

**Use case**
Avoid having multiple services in DONE state.

**Interface Changes**
OneFlow server.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Sunstone missing

**Comment by FrederickBor** [comment]
Duplicated #5035
