### ISSUE TITLE
Consider DONE and POWEROFF in transient service state

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5194]
**Description**

When a service is in transient state, like scaling or deleting, the VMs should be locked, so any user can operate them until the flow is in an stable state.

**Use case**
Avoid problems when VMs are terminated behind the scenes.

**Interface Changes**
OneFlow server.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
After evaluating this, we have conclude that locking the VMs is not viable as locking them avoids the deployment.

We are going to follow a different approach. When the VM is **done** the service will continue with normal life cycle, but updating the cardinality in case it was an scaling operation. When the VM is **poweroff** the service will continue with normal life cycle.

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/562)
- [docs](https://github.com/OpenNebula/docs/pull/1388)
- [tests](https://github.com/OpenNebula/development/pull/1235)

**Comment by al3xhh** [comment]
Feature has been back-ported to 5.12, closing this.
