### ISSUE TITLE
UTF-8 string is not valid UTF-8

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5197]
**Description**

Sometimes, the `onetemplate list` command fails with the following error:

```
Unexpected error executing code for particular method, detected by Xmlrpc-c method registry code.  Method did not fail; rather, it did not complete at all.  6855658-byte supposed UTF-8 string is not valid UTF-8.  UTF-8 multibyte sequence contains character 0x73, which does not indicate continuation.
```

Then, I stop the OpenNebula services and start them again and then everything is working fine.

**To Reproduce**

I have no idea.

**Expected behavior**

**Details**
 - Affected Component: API
 - Hypervisor: KVM
 - Version: 5.12.0.3-1.ce

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Could you please provide more information about the problem, some logs, examples of the tempaltes, etc...

**Comment by baby-gnu** [comment]
I'm sorry that I can't provide usefull information:

- when the problem arrived there was no meaningful information in `oned.log`
- I was not able to determine on which template the error was raised since the command  produce no usefull output
- only restarting `opennebula.service` make things work again

Since then, I switch our OpenNebula to `6.0.0.2-1.ce`.

I'll not be offended if you close this issue without futher investigation since I have no clue about what is going on and I don't have the issue again since months 🤷
