### ISSUE TITLE
Error when hot add NIC_ALIAS in vCenter

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#5199]
**Description**
When you attach a NIC_ALIAS in a VM running in vCenter the NIC is attached on OpenNebula but not on vCenter

**To Reproduce**
* Create a VM in OpenNebula with the vCenter Driver
* Attach a NIC in the VM
* Attach a NIC_ALIAS to the VM
* Check in vCenter that VM not have that NIC attached

**Expected behavior**
NIC_ALIAS should be attached also on vCenter

**Details**
 - Affected Component: -
 - Hypervisor: vCenter
 - Version: 5.12

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
@carloshm91 can you check if this is due to the vcenter driver or rather the context packages?

**Comment by tinova** [comment]
to be solved as part of #5556
