### ISSUE TITLE
Can’t check logs in sunstone

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5203]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When the log have message with apostrophe (es_ES) no show log 

**To Reproduce**
you can add the line with accents in /var/log/one/$id.log (https://forum.opennebula.io/t/cant-check-logs/9002)

**Expected behavior**
show log without error

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Closing it.
Reason: Can't reproduce it
