### ISSUE TITLE
Decommission hybrid drivers (Packet, AWS, Azure) and Econe

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5204]
**Description**
Decommission hybrid drivers (Packet, AWS, Azure) and Econe. The functionality is replaced by hybird+ provision

**Interface Changes**
Remove drivers, Sunstone and packages related parts

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
addressed in #5275
