### ISSUE TITLE
VM scheduled actions via Sunstone 1/3: miss-spelled predefined action

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5207]
**Description**
(bug 1/3)
Not sure how to name the blue "thing" next to the green "Add Action" button but it has a lot of troubles...
When you click on it two actions are defined one of them with "suspense" in them ...
![image](https://user-images.githubusercontent.com/11386997/102350871-40442800-3fae-11eb-9e8a-9ea4dc63e1db.png)

**To Reproduce**
1. Select VM -> Actions tab
2. Click the blue clock-like thing
3. two actions are created one with wrong name "suspense"

**Expected behavior**
Two things expected here:
1. The miss-spelling is obvious, but
2. I think that API should validate the input and do not allow registration of invalid actions

**Details**
 - Affected Component: [Sunstone/Core]
 - Hypervisor: [KVM]
 - Version: [5.12.6]

**Additional context**
But this is not the critical issue there. Stay tuned...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Addressed in https://github.com/OpenNebula/one/issues/5209
