### ISSUE TITLE
VM scheduled actions via Sunstone 2/3: Duplicate scheduled actions when clicked again

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5208]
**Description**
(bug 2/3)
Not sure how to name the blue "thing" next to the green "Add Action" button but it has a lot of troubles...
When you click on it two actions are defined one of them with "suspense" in them. When you click again another two identical actions are defined...
![image](https://user-images.githubusercontent.com/11386997/102351804-b5642d00-3faf-11eb-9060-958454013b5b.png)

**To Reproduce**
1. Select VM -> Actions tab
2. Click the blue clock-like thing few times
3 Several identical actions are created

**Expected behavior**
IMHO The registration of identical duplicate actions must be forbidden...

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**
But this is not the critical issue there. Stay tuned...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @atodorov-storpool, the problem is that these actions are not exactly the same, as they are two weeks from slightly different moments, but as they time shown is rounded they look the same.
