### ISSUE TITLE
Sunstone milti IP view broken on the VM pages

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5212]
**Description**
The screenshot says everything:
![image](https://user-images.githubusercontent.com/11386997/102534879-1ecb6500-40b0-11eb-84e3-be6d52b63ade.png)

**To Reproduce**
Create 18 VMs (more than the default view of 10 per page), the first one with Alias IP
OpenVM's view and click on the next tab (or the number)
The result is in the screenshot of the description

**Expected behavior**
The expected dropdown menu/dialogue should appear.

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.12.7]

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Further observations:
Hitting the reload button, the page is fixed.
Then the issue re-appear when I switch back on the first page, again, hitting the reload button will fix the page.

**Comment by FrederickBor** [comment]
This issue is duplicated, and solved in #5037

**Comment by atodorov-storpool** [comment]
Please note the reported version **5.12.7** - IMO it is not solved with #5037

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/784)
- [Docs](https://github.com/OpenNebula/docs/pull/1460)

**Comment by tinova** [comment]
Needs testing

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Tests](https://github.com/OpenNebula/development/pull/1389)
