### ISSUE TITLE
Sunstone VMs view no data on Used{CPU,Memory} columns

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5213]
**Description**
![image](https://user-images.githubusercontent.com/11386997/102589496-c334c200-4117-11eb-9a24-5e1518976eb8.png)

**To Reproduce**
Enable UsedCPU and UsedMemory columns for vms_tab in admin.yaml
Open VMs - the columns are all zeroes '0'

**Expected behavior**
The columns must show the used values

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.12.7]

**Additional context**
This is regression against 5.10 (before the upgrade the columns worked)
Also in the VM's Capacity tab the graphs are showing data:

![image](https://user-images.githubusercontent.com/11386997/102590129-c4b2ba00-4118-11eb-9db6-2a4bb508761c.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
This is due to the change in monitoring. This information is no longer present in the VM Pool information, but rather on the individual info XML representation, due to performance reasons. Hence, that column cannot be activated in the VM datatable.
