### ISSUE TITLE
Sunstone hosts view - missing data in Real{CPU,MEM} columns

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5214]
**Description**
![image](https://user-images.githubusercontent.com/11386997/102599604-5ffe5c00-4126-11eb-8e97-4c1b242c92f0.png)

**To Reproduce**
Enable Real CPU and Real MEM columns in the admin.yaml
Restart sunstone and observe the hosts in sunstone - There is empty space in these columns

**Expected behavior**
Real CPU and Real MEM should show the relevant values

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.12.7]

**Additional context**
The data exists in the hosts details

![image](https://user-images.githubusercontent.com/11386997/102599918-d602c300-4126-11eb-9951-64afd2eefbae.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Closing, same reason as #5213

**Comment by atodorov-storpool** [comment]
Well then the option should be removed from the yaml files?

**Comment by tinova** [comment]
We'll remove it for 6.0, since our policy is not to change conf files in maintenance releases to ease the upgrades.

We'll review these two settings for removal, as well as Used CPU and Used Memory in the VM tab.

I'll reopen this to keep track of the removal for 6.0.

Thanks a lot for reporting this!

**Comment by FrederickBor** [comment]
Duplicated on #5162
