### ISSUE TITLE
OpenNebula integration with overt/RHV infrastructure

### ISSUE THREAD

**Issue by andrei-xdlab** [OpenNebula/one#5215]
I would like an ability to manage existing RHV 4.2/Ovirt infrasture with OpenNebula front-end. Can open nebula front-end work with existing RHV KVM hypervisors and networks or would I have to rebuild hundreds of existing hypervisors to be compatible with open nebula?

**Comment by tinova** [comment]
oVirt is currently not supported, and there is no automated migration process. I'd recommend contacting our service team (opennebula.io/contact) if you are interested in the evaluation of the effort needed to prepare such a process.
