### ISSUE TITLE
Rotate `vcenter_monitor.log`

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5216]
**Description**
Currently, the `/var/log/one/vcenter_monitor.log` doesn't have rotation capabilities, so a new file is created each time OpenNebula is restarted and the history is lost.

**Use case**
Debug problems with vCenter monitor that occurred before the last reboot.

**Interface Changes**

**Additional Context**

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by ospalax** [comment]
Fixed in: https://github.com/OpenNebula/one-ee/commit/f5a78e9b9cf0afb1a911005617d069896bdbc165
