### ISSUE TITLE
High CPU consumption by process onemonitord when receiving malformed messages

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5219]
**Description**
Upon receiving a malformed monitor message, `onemonitord` does not detect the error condition and an infinite loop occurs when the message is decompressed.

**To Reproduce**
Send an malformed monitor message to `onemonitord`.

**Expected behavior**
`onemonitor` process must detect the error condition and return.

**Details**
 - Affected Component: Monitoring
 - Hypervisor: all
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Fixed for one-5.12 and master
