### ISSUE TITLE
Can not set VCPU via Sunstone when instantiating a template 

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#5220]
When instantiating a template that has an allowed range for VCPU value, Sunstone will fail to instantiate it with the proper VCPU value defined when instantiating IF the value was entered  in the text box and not using the slider. 

For RAM value, for example, when a value is entered in the RAM text box (when instantiating a template with a range of allowed RAM values), the RAM slider will be automatically "moved" to the right position after loosing focus on the RAM text box. This does not happen for CPU. The CPU slider is never updated, and sunstone uses that slider for defining this value.

When VCPU is entered using the slider instead of the text box, it goes fine.

If the slider is used to set a cpu value, and then the text box is modified, the value entered using the slider is used (since the text box never updated the slider).

**To Reproduce**
Create a template with a "range" of possible values for VCPU. Instantiate that template (as any user, using any view) and try to define an allowed vcpu value using the text box.

**Expected behavior**
VCPU slider should be updated with the vcpu value entered in the vcpu text box, and that value should be used for the VM. 

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.6, 5.12.7

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [code](https://github.com/OpenNebula/one-ee/pull/726)
- [docs](https://github.com/OpenNebula/docs/pull/1432)
