### ISSUE TITLE
Networks could not be imported from vSphere

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#5221]
**Description**
When networks name contains "|" could not be imported from vSphere

**To Reproduce**
* Create a VMware Network with a name that contains "|"
* Import a new VMware host in vOneCloud
* Click on Virtual Networks
* Press on Import
* Select the cluster
* Press on Get Networks
* Select the network to import and click on import

**Expected behavior**
Import successful and maybe able to see the result on the dropdown list

**Details**
 - Affected Component: [Import]
 - Hypervisor: [vCenter]
 - Version: [5.12]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one-ee/pull/752

**Comment by tinova** [comment]
needs testing
