### ISSUE TITLE
Virtual Machine tabs not working on Sunstone

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#5223]
**Description**
Virtual Machine tabs not working on Sunstone

**To Reproduce**
* Go to Virtual Machine list
* Click on any VM
* You will see errors in console
* Click on any tab, will not work

**Expected behavior**
When you click in any tab show the content of the tab

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [vCenter]
 - Version: [master]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- one: https://github.com/OpenNebula/one-ee/pull/582
- docs: https://github.com/OpenNebula/docs/pull/1405
