### ISSUE TITLE
CLI tools running via ssh may provide a misleading error or different output

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/one#5224]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Running Opennebula CLI via ssh may return misleading error message:
```
laptop $ ssh jumphost onehost list
no implicit conversion of OpenNebula::Error into Integer
laptop $
```
But if I tell the ssh to use terminal with `-t` option then it fixes the problem and works as would locally:
```
laptop $ ssh -t jumphost onehost list
Failed to open TCP connection to localhost:2633 (Cannot assign requested address - connect(2) for "localhost" port 2633)
Connection to localhost closed.
laptop $
```

**To Reproduce**

1. Prepare opennebula host where CLI tools are installed and stop the oned daemon there.
2. Try to run Opennebula CLI tool like `onehost` via ssh from different host to this opennebula one as above
3. You should see the same output 

**Expected behavior**
The output of the CLI tool should not depend on the option `-t` or at least should return more meaningful message.

**Details**
 - Affected Component: CLI tools
  - Version: 5.13.80

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/637)
- [docs](https://github.com/OpenNebula/docs/pull/1407)
