### ISSUE TITLE
Add EXTERNAL NIC attribute to VM IPs

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5226]
**Description**

VMs with this XML

 ```
  <NIC>
      <AR_ID><![CDATA[0]]></AR_ID>
      <AWS_ALLOCATION_ID><![CDATA[eipalloc-06f87b0e6f030d761]]></AWS_ALLOCATION_ID>
      <BRIDGE><![CDATA[br0]]></BRIDGE>
      <BRIDGE_TYPE><![CDATA[linux]]></BRIDGE_TYPE>
      <CLUSTER_ID><![CDATA[105]]></CLUSTER_ID>
      <EXTERNAL><![CDATA[18.213.66.111]]></EXTERNAL>
      <GATEWAY><![CDATA[10.0.66.110]]></GATEWAY>
      <IP><![CDATA[10.0.66.111]]></IP>
      <MAC><![CDATA[02:00:0a:00:42:6f]]></MAC>
      <MODEL><![CDATA[virtio]]></MODEL>
      <NAME><![CDATA[NIC1]]></NAME>
      <NETWORK><![CDATA[aws-cluster-public]]></NETWORK>
      <NETWORK_ID><![CDATA[3]]></NETWORK_ID>
      <NETWORK_UNAME><![CDATA[oneadmin]]></NETWORK_UNAME>
      <NIC_ID><![CDATA[1]]></NIC_ID>
      <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
      <TARGET><![CDATA[one-15-1]]></TARGET>
      <VN_MAD><![CDATA[elastic]]></VN_MAD>
    </NIC>
```

IP EXTERNAL 18.213.66.111 should be also listed as a NIC IP.

**Use case**

Provisioned VMs with IPAM AWS

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/705
- doc: https://github.com/OpenNebula/docs/pull/1423
