### ISSUE TITLE
Sunstone error on marketplace import when no OneFlow

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5227]
**Description**

Sunstone raises error (which doesn't go automatically way) when importing into marketplace via "Create Marketplace App" while OneFlow server is not runing. The message is raised even when user doesn't select Type Service to import.

![image](https://user-images.githubusercontent.com/414850/104609256-2405da80-5683-11eb-8508-279b46ea200b.png)

**To Reproduce**
- Stop OneFlow
- open Storage -> Apps -> Create Marketplace App

**Expected behavior**
No server error. The usual behaviour is to handle the error with message inside relevant part:

![image](https://user-images.githubusercontent.com/414850/104609480-662f1c00-5683-11eb-8b01-c59292510cdc.png)

**Details**
 - Affected Component: Sunstone
 - Version: 5.13.80 / master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/791)
- [Docs](https://github.com/OpenNebula/docs/pull/1463)
