### ISSUE TITLE
Impossible to define vm_template_contents with sunstone wizard

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5230]
**Description**

In the [kubernetes service documentation](https://docs.opennebula.io/appliances/service/kubernetes.html#step-2-role-master), the procedure ask:

> In **Advanced role parameters**, set **VM template content** to: `ONEGATE_ENABLE="YES"`

But there is no **VM template content** under **Advanced role parameters**, only the **VM shutdown action**.

**To Reproduce**

Follow the procedure from  [kubernetes service documentation](https://docs.opennebula.io/appliances/service/kubernetes.html) to create a OneFlow service.

**Expected behavior**

I should have the **VM template content** to set `ONEGATE_ENABLE="YES"`.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12.0.3-1.ce

**Additional context**

I need to switch to the **Advanced** edition to set `"vm_template_contents": "ONEGATE_ENABLE=\"YES\""` directly in the RAW template.

## Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
When I'm doing this, I can't instantiate the OneFlow template:

```
Tue Jan 19 10:02:58 2021 [E]: [OneFlow] Error deploying role master: Error trying to instantiate the VM Template 95607 in Role master: [one.template.instantiate] Parse error: syntax error, unexpected EQUAL, expecting $end at line 1852403044, columns 33:36
```

**Comment by sbbarragan** [comment]
Hi @baby-gnu 

We have removed the "vm_template_contents" field because it added a lot of complexity to the code, now the way to enable ONEGATE is directly through the **"Advanced" tab** or an **user input in the VM template**.

by default it is added in the template [Service Kubernetes KVM](https://marketplace.opennebula.io/appliance/547ecdff-f392-43b9-abc9-5f10a9fa7aff)
```
"USER_INPUTS": {
    "ONEGATE_ENABLE": "M|boolean|Enable OneGate reporting? (req. for multi-node)| |NO",
    ...
```

thanks for warning us about this, we will update the documentation

**Comment by baby-gnu** [comment]
Ok, thanks a lot, so we can't force the `ONEGATE_ENABLE` with the use of OneFlow.

I'll try to define a `ONEGATE_ENABLE` user input with default to `YES` on the service and see if it override the one in the VM template.

Regards.

**Comment by baby-gnu** [comment]
> I'll try to define a `ONEGATE_ENABLE` user input with default to `YES` on the service and see if it override the one in the VM template.

So, it seems that the `Service` user inputs does not override the `VM` template ones.

Instantiating the `Service`, I have:

![service-input-onegate](https://user-images.githubusercontent.com/1233212/105714266-07379580-5f14-11eb-8548-b71e8ae5634e.png)

But, in the VM, the context is:

```
ONEGATE_ENABLE='NO'
REPORT_READY='NO'
TOKEN='NO'
```

So, no token is present.

I think we should a mechanism for `Service` to override any VM templates inputs or context values.

By the way, making some tests to write this comment, I found some weird behaviours:

1. there is no default value selected for `Enable OneGate reporting? (req. for multi-node)`.

	1. download the `Service Kubernetes 1.18 - KVM` from `Storage > Apps`
	2. select the VM template `Service Kubernetes 1.18 - KVM` and click on the blue button `Instantiate`

2. modification of context values just when saving the template

	1. select the VM template `Service Kubernetes 1.18 - KVM` and click on the blue button `Update`
	2. save the VM template without any modification

Then, I have hard coded values in `CONTEXT`:

- `REPORT_READY = "YES"` instead of `REPORT_READY = "$ONEGATE_ENABLE"`
- `TOKEN = "YES"` instead of `TOKEN = "$ONEGATE_ENABLE"`
- a `ONEGATE_ENABLE` at the start **and** end of `INPUTS_ORDER = "ONEGATE_ENABLE,ONEAPP_K8S_ADDRESS,ONEAPP_K8S_TOKEN,ONEAPP_K8S_HASH,ONEAPP_K8S_NODENAME,ONEAPP_K8S_PORT,ONEAPP_K8S_PODS_NETWORK,ONEAPP_K8S_ADMIN_USERNAME,ONEGATE_ENABLE"`

I always need to moved to `Advanced` instead of `Wizard` to update the template to keep the `CONTEXT` relative to the value of `$ONEGATE_ENABLE` user input.

This seems to be a another issue, not really related to this one. Should I open a new issue?

**Comment by sbbarragan** [comment]
> 2.modification of context values just when saving the template
>
> i. select the VM template Service Kubernetes 1.18 - KVM and click on the blue button Update
> ii.save the VM template without any modification

we have opened a new issue about this
https://github.com/OpenNebula/one/issues/5237

**Comment by baby-gnu** [comment]
Thanks.

**Comment by sbbarragan** [comment]
@baby-gnu,

if i understand your need, its to add the VM context through the Service custom attributes. Then, you can follow these steps:

1. VM template Kubernetes like this: (**without ONEGATE_ENABLE in user inputs**)
```
CONTEXT = [
  .....
  REPORT_READY = "$ONEGATE_ENABLE",
  TOKEN = "$ONEGATE_ENABLE" ]
```

2. Service template **with ONEGATE_ENABLE** custom attribute:
```
"custom_attrs": {
    "ONEGATE_ENABLE": "M|boolean|Enable OneGate reporting? (req. for multi-node)| |YES"
  },
```

3. Result on instance VM:
`onevm show <id> -x`
```
 <TEMPLATE>
    <CONTEXT>
      <REPORT_READY><![CDATA[YES]]></REPORT_READY>
      <TOKEN><![CDATA[YES]]></TOKEN>
    </CONTEXT>
```

**Comment by baby-gnu** [comment]
@sbbarragan,

Ok, it will work since single node kubernetes doesn't need ONEGATE, so it will be always disabled on single node, then I will force it to be enabled on the service.

Thanks, I'm closing this issue then.
