### ISSUE TITLE
Flow scaling is not working in cloud view

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5231]
**Description**

It's not possible to `Change Cardinality` in cloud view.

**To Reproduce**

- Create the [Kubernetes service](https://docs.opennebula.io/appliances/service/kubernetes.html#oneflow-integration)
- Instanciate the service
- In cloud view, select the `↔` to change the cardinality
- Set cardinality to 3

I have an error message in Sunstone:

```
It appears there was a server exception. Please check server's log.
```

In the OneFlow logs, in debug level, I have:

```
Tue Jan 19 10:44:22 2021 [I]: 127.0.0.1 - - [19/Jan/2021:10:44:22 +0100] "PUT /service/34/role/worker HTTP/1.1" 404 495 0.0014
```

**Expected behavior**

The cardinality of the role should be changed.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12.0.3-1.ce

**Additional context**

It's working fine with the user view:

- select the service, in my case `Kubernetes`
- in the `Roles` tab, select the role `worker`
- click on the green `+ Scale` button
- define the number of VMs

In the OneFlow logs, in debug level, I have:

```
Tue Jan 19 10:48:11 2021 [I]: 127.0.0.1 - - [19/Jan/2021:10:48:11 +0100] "POST /service/34/scale HTTP/1.1" 204 - 0.1641
```

Which is not the same endpoint than for the cloud view.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/703
- doc: https://github.com/OpenNebula/docs/pull/1421
