### ISSUE TITLE
Alias IPs are not shown in service role VM details

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5233]
**Description**
The alias IP is missing in the role VM information in Sunstone.

**To Reproduce**
Create a service with a NIC alias.

**Expected behavior**
The alias should appear along with the parent NIC.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.7

**Additional context**
#### 5.12.6
<img width="1645" alt="Bildschirmfoto 2021-01-20 um 09 44 16" src="https://user-images.githubusercontent.com/33811723/105163308-0a95e000-5b14-11eb-9632-6f5b98cced97.png">

#### 5.12.7
<img width="1674" alt="Bildschirmfoto 2021-01-20 um 09 44 30" src="https://user-images.githubusercontent.com/33811723/105163320-0e296700-5b14-11eb-98a5-7594b0385d93.png">

## Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
backport to 5.12

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/749
- doc: _pending_
