### ISSUE TITLE
Delete VM button within a OneFlow role is not working

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5234]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**

It should delete a VM but no action is performed

**To Reproduce**

1. launch a service
2. go to the role view
3. delete a VM

**Expected behavior**

The VM to be deleted

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Closing this issue, can't reproduce it on master
