### ISSUE TITLE
Marketplace images SIZE under 1MB are rounded to 0MB

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5236]
**Description**
![image](https://user-images.githubusercontent.com/11386997/105518991-990b8c80-5ce1-11eb-98bd-1ad0c9fe54b5.png)

**To Reproduce**
https://marketplace.opennebula.io/appliance/6f7a1735-5b88-4667-a319-07ffe5e684ee
Check the size of the "Contextualization Packages" in OpenNebula
The size is 0

**Expected behaviour**
The size of the image is 720896 bytes so should be rounded up to 1MB

**Details**
 - Affected Component: [Marketplace]
 - Hypervisor: [KVM]
 - Version: [5.12.x]

**Additional context**
Also, the size of 0 is passed to the storage drivers...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PR to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/863)

PR to merge in 5.12 maintenance:

- [docs](https://github.com/OpenNebula/docs/pull/1484)
