### ISSUE TITLE
Sunstone overrides VM Template instantiate XMLRPC API Call

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5238]
**Description**
When issuing a VM Template instantiation with no overrides (just instantiating the template) the API Call sent to one carries the extra template argument.

**To Reproduce**

Instantiate via Sunstone and get this example API Call

```
Thu Jan 21 15:48:35 2021 [Z0][ReM][D]: Req:7808 UID:5 IP:127.0.0.1 one.template.instantiate invoked , 0, "anker", false, "DISK=[
  ALLOW_ORPHANS="NO",
  CLONE="YES",
  CLONE_TARGET="SYSTEM",
  CLUSTER_ID="100",
  DATASTORE="OPENNEBULA-Datastore(IMG)",
  DATASTORE_ID="100",
  DEV_PREFIX="sd",
  DISK_ID="0",
  DISK_SNAPSHOT_TOTAL_SIZE="0",
  DISK_TYPE="FILE",
  DRIVER="vcenter",
  IMAGE="OpenNebulaTest-CentOS-Template",
  IMAGE_ID="0",
  IMAGE_STATE="2",
  LN_TARGET="NONE",
  OPENNEBULA_MANAGED="NO",
  READONLY="NO",
  SAVE="NO",
  SOURCE="OpenNebulaTest-CentOS-Template/OpenNebulaTest-CentOS-Template.vmdk",
  TM_MAD="vcenter",
  TYPE="FILE",
  VCENTER_DS_REF="datastore-5421",
  VCENTER_INSTANCE_ID="4cb8b32b-5687-48d8-bc2e-aa46b40b305c"
]

MEMORY="4096"
CPU="2"
VCPU="2"
NIC = []
NIC_ALIAS = []
SCHED_REQUIREMENTS = []
SCHED_DS_REQUIREMENTS = []", false

```

**Expected behavior**

CLI instantiation example

```
Thu Jan 21 16:33:52 2021 [Z0][ReM][D]: Req:7104 UID:5 IP:127.0.0.1 one.template.instantiate invoked , 1, "", false, "", false
```

The template is instantiated as it is, with no extra template override

**Details**
 - Version: 5.12

**Additional context**
This behavior can cause issues with features like restricted attributes due to the newly created attributes. Example error

```
oned.log_Last10000:Thu Jan 21 15:48:35 2021 [Z0][ReM][E]: Req:7808 UID:5 one.template.instantiate result FAILURE [one.template.instantiate] User [5] : User Template includes a restricted attribute DISK.
```

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/795)
- [docs](https://github.com/OpenNebula/docs/pull/1465)

pending tests

**Comment by kvaps** [comment]
Ah, I also faced with this problem in (see https://github.com/OpenNebula/one/commit/b9623af7696f6844acd585ca083c2e91604fd231#r54314658).

After few hours of debugging I found guest of honor, this is line:

```
VM_RESTRICTED_ATTR = "DISK/ALLOW_ORPHANS"
```

in my oned.conf file, after removing it, sunstone started working normaly

**Comment by OpenNebulaSupport** [comment]
This is still reproducible on OpenNebula 5.12.10:

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code:
    - https://github.com/OpenNebula/one-ee/pull/1751
    - https://github.com/OpenNebula/one-ee/pull/1752
- Docs: https://github.com/OpenNebula/docs/pull/2133

**Comment by tinova** [comment]
also needs fix for regular users

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2335
