### ISSUE TITLE
Sunstone service template update wizard don't save changes

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5239]
**Description**

Existing service template in Sunstone can't be **updated via Wizard**, as any changes in the template are not persisted. User has the only chance to switch on Advanced tab and edit directly the JSON.

![image](https://user-images.githubusercontent.com/414850/105847603-197e0600-5fde-11eb-8dce-cb733970ff87.png)

**To Reproduce**
1. Have a service template
2. Open template update, have wizard
3. Do any changes
4. Click on "Update"
5. Open service template again, see old values

Note: only master (5.13.80) looks affected!

**Details**
 - Affected Component: Sunstone
 - Version: 5.13.80
 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Issue fixed with: https://github.com/OpenNebula/one-ee/pull/696
