### ISSUE TITLE
Guacamole SSH provides authentication through private key authentication

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5241]
**Description**
Provide to users a remote connection through a **SSH private key** from Sunstone

**Interface Changes**
Add similar section as _Public SSH Key_
![image](https://user-images.githubusercontent.com/59608355/106169955-42de9380-6190-11eb-82e6-1d606233777f.png)

**Additional Context**
[Guacamole documentation](https://guacamole.apache.org/doc/0.9.7/gug/configuring-guacamole.html)

> **private-key**: The entire contents of the private key to use for public key authentication. If this parameter is not specified, public key authentication will not be used. The private key must be in OpenSSH format, as would be generated by the OpenSSH ssh-keygen utility.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1320)

In order to close this issue, #5431 must be closed first.

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Docs: https://github.com/OpenNebula/docs/pull/2053
