### ISSUE TITLE
Manage encoding at Java binding

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5243]
**Description**
Depending on the DB encoding a Java application might fail retrieving OpenNebula information. The JAVA OCA should be able to manage the encoding of the messages.

**Details**
 - Affected Component: oned, Java OCA
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by mnss8991** [comment]
@OpenNebulaSupport ,I would like work on the above issue and contribute my solution to the problem .Please provide me with the necessary requirements so that I will start working on it. Since it is mandatory for my course requirement I assure you for the completion of the issue.

**Comment by vickmp** [comment]
PRs to merge:
- [code](https://github.com/OpenNebula/one-ee/pull/2279)
- [docs](https://github.com/OpenNebula/docs/pull/2394)
