### ISSUE TITLE
vCenter host password cannot be changed from Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5247]
**Description**
According to [documentation](https://docs.opennebula.io/5.12/deployment/vmware_infrastructure_setup/vcenter_setup.html), the vCenter password can be changed from Sunstone. However, the `VCENTER_PASSWORD` attribute cannot be changed from Sunstone.

**To Reproduce**
In Sunstone, go to *Infraestructure -> Hosts* and click on an already added host. The `VCENTER_PASSWORD` field is not editable:
![image](https://user-images.githubusercontent.com/33811723/107203424-b76cca00-69fb-11eb-8c69-b8379c548ef2.png)

**Expected behavior**
Determine if vCenter password change should be allowed from Sunstone or just from CLI.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/768
- doc: https://github.com/OpenNebula/docs/pull/1452
