### ISSUE TITLE
monitoring driver for shared storages inconsistency

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5250]
**Description**
The monitoring of the shared storages directly from the FE is not documented in the [Monitoring Driver](http://docs.opennebula.io/5.12/integration/infrastructure_integration/devel-im.html) doc. There is a description for remote monitoring only and the communication is described with a monitor message format `MESSAGE_TYPE ID RESULT PAYLOAD` which doesn't work at all.

Looking at [send_to_monitor](https://github.com/OpenNebula/one/blob/26843abf44ccc441f11bbc2253eda4956bf8a443/src/mad/sh/scripts_common.sh#L128) function, it is sending a message with format `MESSAGE_TYPE RESULT ID PAYLOAD` which is also wrong(see below). Also, from the frontend, it is called with `-1` as ID.

Reading the code at [monitord_client.rb](https://github.com/OpenNebula/one/blob/master/src/im_mad/remotes/lib/monitord_client.rb#L38) it looks like the working message format is `MESSAGE_TYPE RESULT ID TIMESTAMP PAYLOAD`, but then, the monitoring daemon does not accept `-1` as the host ID. An active online host ID works, but what about when called from the frontend?

So, how all of this is expected to work?

**To Reproduce**
Read the docs
Read the code
Try to do shared storage disks monitoring from the FE

**Expected behavior**
The disk monitoring should work. 

**Details**
 - Affected Component: [Monitoring]
 - Hypervisor: [KVM]
 - Version: [5.12+]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
IMHO the documentation is clear:

```
Shared System Datastores
These datastores are monitored from a single point once (either the front-end or one of the storage bridges in BRIDGE_LIST). This will prevent overloading the storage by all the nodes querying it at the same time.

The driver plugin <tm_mad>/monitor will report the information for two things:

Total storage metrics for the datastore (USED_MB FREE_MB TOTAL_MB)
Disk usage metrics (all disks: volatile, persistent and non-persistent)
```

You have a detailed description of the montior TM action:

```
monitor data The monitoring information of the datastore, namely “USED_MB=…\nTOTAL_MB=…\nFREE_MB=…” which are respectively the used size of the datastore in MB, the total capacity of the datastore in MB and the available space in the datastore in MB.

monitor VMs data For each VM the size of each disk and any snapshot on those disks. This data are send by UDP to Monitor Daemon. The MONITOR parameter is encoded in base64 format. Decoded example: 
```

So documentation-wise I think we are good for the Datastores/TM.  The Monitor message is indeed missing the payload. And so is the send_monitor function.

**Comment by atodorov-storpool** [comment]
Hi @rsmontero, @paczerny,

Thank you for the answer but... Are we reading the same docs? Because there is no such information on the page I am referencing: http://docs.opennebula.io/5.12/integration/infrastructure_integration/devel-im.html

And there is no information in the MONITOR_VM message format how DISK_SIZE and SNAPSHOT_SIZE are encoded, in you decode the base64 encoded MESSAGE you have:

```bash
echo Q1BVPSIxLjAxIgpNRU1PUlk9IjE0MDgxNiIKTkVUUlg9IjAiCk5FVFRYPSIwIgpESVNLUkRCWVRFUz0iNDQxNjU0NDQiCkRJU0tXUkJZVEVTPSIxMjY2Njg4IgpESVNLUkRJT1BTPSIxMjg5IgpESVNLV1JJT1BTPSI4ODEiCg==|base64 -d
CPU="1.01"
MEMORY="140816"
NETRX="0"
NETTX="0"
DISKRDBYTES="44165444"
DISKWRBYTES="1266688"
DISKRDIOPS="1289"
DISKWRIOPS="881"
```
As you can see there is no TIMESTAMP it is in the monitoring structure actually. Also, these messages are sent successfully because they are sent by monitord_client.rb from the hosts where the VM UUID and the host ID is known.

So having the correct message(the VM UUD is not mandatory...):
```
PAYLOAD="DISK_SIZE[ID=$DISK_ID,SIZE=$disk_size]"
VM=[ID=$VMID,MONITOR="base64($PAYLOAD)"]
```
... there is still no information what to set for the ID in the message structure when the message is composed and sent from the FE? Reading the sources there is a reference to `-1` but that simply doesn't work! It is not an acceptable value by the monitord service...

> So documentation-wise I think we are good for the Datastores/TM. The Monitor message is indeed missing the timestamp. And so is the send_monitor function.

IMHO the order of the variables in the message structure is wrong too - the ID should be _after_ the RESULT...
And I could not agree that the message format is clear from the above doc.


Best,
Anton

p.s. actually chasing an issue where the disk sizes are reset to '0' but first I am trying to figure out how the monitoring works actually. I suspect a race condition with the data is sent from the different sources but to debug that you must have working monitoring setup following the documentation in the first place ;)

**Comment by rsmontero** [comment]
Information is here: https://docs.opennebula.io/5.12/integration/infrastructure_integration/sd.htm

I thinkn for all your questions

**Comment by atodorov-storpool** [comment]
Hey @rsmontero 

Thank you for your patience!
In the link, the content of the DISK_SIZE message is clearly described. Maybe a cross-reference pointing to the relevant parts from devel_im.html should help to clarify the things?

Also, in this doc (sd.html), I am seeing texts related to the old 5.10 monitoring:
https://docs.opennebula.io/5.12/integration/infrastructure_integration/sd.html#non-shared-system-datastores-ssh-like

`The plugins <tm_mad>/monitor_ds + **kvm-probes.d/monitor_ds.sh** will report the information for two things:`

Please correct me If I am wrong, but in 5.12+ there is `kvm-probes.d/vm/monitor/monitor_ds_vm.rb` that does not collect data/ It just calls _tm/(.monitor)/monitor_ds_ and blindly passes the returned data to stdout if there are no errors.

Best,
Anton

(p.s. and thank you for the heads up - the issue with the duplicated disk stats I was chasing was due to a .monitor file on the hosts left from default ONE setup... :) )

**Comment by atodorov-storpool** [comment]
Maybe I need to clarify what I was expecting from the http://docs.opennebula.io/5.12/integration/infrastructure_integration/devel-im.html doc:

description of the message structure (or name it the message header?)

For each message type an example with complete payload - all possible values, what is mandatory, what is optional and so on.

How the messages could be sent to the frontend - the TCP port, the UDP port, the optional encryption...
How to send messages originated from the frontend to the frontend? Currently, I am dumping the disk sizes with the ID of the first active host found and with destination IP address being the one, configured in monitorid.conf... But I am not sure is this the right thing to do? All of this is a wild guess and piecing bits from here and there...

Best Regards,
Anton Todorov

Best Regards,
Anton Todorov

**Comment by rsmontero** [comment]
Ok, this is the fix. Just sets timestamp to 0, that is the corresponding value for host -1. 

About the integration guides. Storage information including monitoring is described in the integration guide for storage (https://docs.opennebula.io/5.12/integration/infrastructure_integration/sd.html)

Also the overall architecture for monitoring is here: https://docs.opennebula.io/5.12/deployment/open_cloud_host_setup/monitoring.html

This guide covers:
* TCP/UDP. Both transport are used to bind the socket (also figure). 
* Encryption is as configured in monitord.conf in PUBKEY/PRIKEY

Low level functions to send data can be found in:

- https://github.com/OpenNebula/one/blob/master/src/mad/sh/scripts_common.sh#L1147
- https://github.com/OpenNebula/one/blob/master/src/mad/ruby/scripts_common.rb#L95

Although there should be no need to look into them, just probes as described in the guides above. And for the storage the monitor and monitor_ds scripts. Probably the monitoring guide is doing more harm than good.

Maybe we can add a simple monitor script for shared storage as an example

```
diff --git a/src/mad/ruby/scripts_common.rb b/src/mad/ruby/scripts_common.rb
index 8cd3b6945..0608923ee 100644
--- a/src/mad/ruby/scripts_common.rb
+++ b/src/mad/ruby/scripts_common.rb
@@ -163,7 +163,13 @@ module OpenNebula
                 result = "FAILURE"
             end

-            msg = "#{msg_type} #{result} #{oid} #{data64}"
+            if Integer(oid) == -1
+                ts = 0
+            else
+                ts = Time.now.to_i
+            end
+
+            msg = "#{msg_type} #{result} #{oid} #{ts} #{data64}"

             socket_udp = UDPSocket.new()
             socket_udp.send(msg, 0, mon_address, mon_port)
diff --git a/src/mad/sh/scripts_common.sh b/src/mad/sh/scripts_common.sh
index 787c7de86..6e8ce3950 100644
--- a/src/mad/sh/scripts_common.sh
+++ b/src/mad/sh/scripts_common.sh
@@ -1062,6 +1062,12 @@ function send_to_monitor {
         msg_result="FAILURE"
     fi

+    if [ $msg_oid = "-1" ]; then
+        msg_ts=0
+    else
+        msg_ts=$(date +%s)
+    fi
+
     # Read monitord config
     if [ -z "${ONE_LOCATION}" ]; then
         mon_conf=/etc/one/monitord.conf
@@ -1111,6 +1117,6 @@ function send_to_monitor {
     fi

     # Send message
-    echo "$msg_type $msg_result $msg_oid $payload_b64" |
+    echo "$msg_type $msg_result $msg_oid $msg_ts $payload_b64" |
         nc -u -w1 $mon_address $mon_port
 }
```

**Comment by rsmontero** [comment]
Moving this to the documentation module, to look into it in 6.0

**Comment by rsmontero** [comment]
Created new issue for updating the docs. in here (#5252). Closing this one for 5.12.8
