### ISSUE TITLE
Sunstone fails to print IP address in VM list when IPs are no defined in NIC

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5253]
**Description**
When the IP addresses are retrieved by the monitoring process and cannot be associated to a NIC Sunstone fails printing them and it prints `undefined` instead.

**To Reproduce**
   - Create a new VM
   - Add a new IP address from inside the VM (e.g `ip a add 192.168.123.1/24 dev eth0`)
   - Wait for the monitoring to add the information to the VM:
   ```
<GUEST_IP_ADDRESSES><![CDATA[192.168.122.100,192.168.122.130]]></GUEST_IP_ADDRESSES>
   ```

**Expected behavior**
Sunstone should print the IP addresses retrieved by the monitoring information in the list table.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 5.12

## Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one/master: https://github.com/OpenNebula/one-ee/pull/789
- one/one-5.12: https://github.com/OpenNebula/one-ee/pull/790
- doc: _pending_
- dev: _pending tests_
