### ISSUE TITLE
Cannot delete roles from a service template on Sunstone

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5254]
**Description**
After create a service template with multiple roles, it's impossible to delete one of the existing roles.

**To Reproduce**
- Create a simple service template with two roles, e.g:
```
{
  "name": "testing-update",
  "deployment": "straight",
  "description": "",
  "roles": [
    {
      "name": "master",
      "cardinality": 1,
      "vm_template": 0,
      "elasticity_policies": [],
      "scheduled_policies": []
    },
    {
      "name": "minion",
      "cardinality": 1,
      "vm_template": 0,
      "elasticity_policies": [],
      "scheduled_policies": []
    }
  ],
  "ready_status_gate": false
}
```
- Click to update button:
![image](https://user-images.githubusercontent.com/59608355/107613745-34d94a00-6c49-11eb-8585-dd7afc0d9ca1.png)

- Click remove one of roles:
![image](https://user-images.githubusercontent.com/59608355/107613796-520e1880-6c49-11eb-9dbd-e75948a2ac70.png)

- Then click to update button, and check that the template hasn't changed

**Expected behavior**
Be able to delete roles from Sunstone

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/862)
- [Docs](https://github.com/OpenNebula/docs/pull/1483)

**Comment by tinova** [comment]
Needs testing

**Comment by FrederickBor** [comment]
- [Tests](https://github.com/OpenNebula/development/pull/1388)
