### ISSUE TITLE
Can't start VM with IDE CDROM from block device when using alt-deployment configuration

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5255]
**Description**

When defining the alternate deployment of a IMAGE datastore with cdrom devices, for example with `DISK_TYPE_SSH=BLOCK` the domain XML have unsupported configuration of a read-only disk device instead of cdrom:

```xml
		<disk type='file' device='disk'>
			<source file='/var/lib/one//datastores/0/1/disk.0'/>
			<target dev='hda' bus='ide'/>
			<readonly/>
			<driver name='qemu' type='raw' cache='none' io='native' discard='unmap'/>
		</disk>
```

I think that the issue could be tested with the default Raw device mapper

**To Reproduce**
* define an Image datastore following the [Raw Device Mapper](http://docs.opennebula.io/5.12/deployment/open_cloud_storage_setup/dev_ds.html) doc
* register a CDROM image ( i think any block device could be served for the test - the error is in the libvirt's configuration)
* define a VM with a disk backed by the CDROM image
* try to instantiate/boot the VM

An error will be raised that the IDE disk drive could not be read-only.

**Expected behavior**
The VM should boot

**Details**
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [5.12]

**Additional context**
Looking at the code, the DISK_TYPE_* variable is passed to [VirtualMachineDisk::set_types()](https://github.com/OpenNebula/one/blob/master/src/vm/VirtualMachineDisk.cc#L528) function
in [Datastore::disk_attribute](https://github.com/OpenNebula/one/blob/master/src/datastore/Datastore.cc#L191)
and in the case of CDROM the returned DISK/TYPE is `BLOCK_CDROM`.
But the `BLOCK_CDROM` string is not handled in [LibVirtDriver::deployment_description_kvm](https://github.com/OpenNebula/one/blob/master/src/vmm/LibVirtDriverKVM.cc#L976) and an default disk XML is defined instead.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Hey, @paczerny 

I think the proposed patch solve the described case?

**Comment by paczerny** [comment]
Thanks @atodorov-storpool, patch merged
