### ISSUE TITLE
Add references to (both) MySQL/MariaDB across documentation

### ISSUE THREAD

**Issue by albert0marti** [OpenNebula/one#5257]
**Description**
Make sure that documentation displays, when appropriate, a parity of references to both MySQL and MariaDB ("MySQL/MariaDB") as supported DB solutions for OpenNebula.

**Use case**
This is part of an internal process to improve OpenNebula's documentation.

**Interface Changes**
Aiming at OpenNebula 6.0

**Additional Context**
N/A

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Added MariaDB references when generic DB server is mentioned
