### ISSUE TITLE
when undeploy-hard a VM the PCI/PREV_ADDRESS is removed from HOST_SHARE/PCI_DEVICES instead of PCI/ADDRESS

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5261]
**Description**
We are extensively using PCI passthrough of NIC VFs in our lab and from time to time there are PCI address reservation conflicts.

**To Reproduce**
* have a VM X with PCI NIC pass-through, `PCI/ADDRESS=0000:d8:03:6` and `PCI/PREV_ADDRESS=0000:d8:00:2` running on host 1
* on same host 1 we have another VM Y with  `PCI/ADDRESS=0000:d8:00:2` and `PCI/PREV_ADDRESS=0000:d8:00:2`
on host 1 in  /HOST/HOST_SHARE/PCI_DEVICES/PCI we have `0000:d8:03:6 -> X` and `0000:d8:00:2 -> Y`
after undeploy-hard of VM X in the host share the record for `0000:d8:00:2 -> Y` is *removed* instead of `0000:d8:03:6 -> X`
and when a new VM Z is deployed on the host there is conflict with the running VM -> Y

**Expected behavior**
the PCI devices used by the undeployed VM should be cleared from the HOST_SHARE

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [5.12.0.3]

**Additional context**
This is a continuation of previous issues on same topic, hopefully the last one...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
It's strange that VMs have `PCI/PREV_ADDRESS`, because it's just a temporary value.
IMHO the only way how to get to this situation is `onevm migrate` failure. It fails to revert the PCI devices on both hosts
