### ISSUE TITLE
Unreadable font in charter field

### ISSUE THREAD

**Issue by Notespeak** [OpenNebula/one#5263]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
The charter warning pop-up is almost unreadable, because of very thin font usage.

**To Reproduce**
Get a charter field output.

**Expected behavior**
The font should be readable.

**Details**
 - Affected Component:  Sunstone UI
 - Hypervisor: KVM
 - Version: 5.12.0.3

**Additional context**
I have added  screenshots of how the font looks like in chrome and edge browsers.
<img width="570" alt="Screenshot_3349" src="https://user-images.githubusercontent.com/27561950/108728429-a31be780-753a-11eb-918d-e1f4e54ef8f0.png">
<img width="1717" alt="Screenshot_3350" src="https://user-images.githubusercontent.com/27561950/108728432-a3b47e00-753a-11eb-8c57-e9268befb007.png">

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
This issue is resolved in recent versions, for example 5.12.8
