### ISSUE TITLE
Sunstone: Error getting virtual machine

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/one#5265]
**Description**
From time to time when I try to open the VM page in Sunstone (Instances/VMs, and then select a particular VM from the list), I get the red pop-up saying "Error getting a virtual machine". I suspect that it is from a VM that I have modified recently (e.g. hot-plug a new NIC), or maybe modified from a different browser, migrated, or whatever. But I don't know excatly. When I hit Back, return to the list of VMs, and try to select that VM again, I get the same error. However, when I refresh the list of VMs (the double circular arrows button near the [+] button), I can open the page of that VM without problem. This is under the "oneadmin" user in Sunstone.

**To Reproduce**
I cannot reliably reproduce it, but I see this problem every now and then.

**Expected behavior**
A page for the VM in question should be displayed, as long as that VM still exists (which it does).

**Details**
ONe 5.12.0.3 (also 5.12.0.1, IIRC) CE, CentOS 7, KVM, client "oneadmin" from Firefox running on Fedora Linux

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
Hi @Yenya,

Could you see what request the browser does from the `Network` tab in the **console** when this happens?
![image](https://user-images.githubusercontent.com/59608355/112338975-8ac8f500-8cbf-11eb-8cd9-ff191bcc4dd5.png)

If you could provide a few steps to reproduce it, we would appreciate it.

**Comment by sbbarragan** [comment]
Closing this for now, please reopen if you deem it necessary.
