### ISSUE TITLE
Sunstone VM warning box blocks other VM tabs

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5266]
**Description**

When VM displays error box:

![image](https://user-images.githubusercontent.com/414850/109037292-dc835d00-76ca-11eb-8b83-5b6bc3f5da69.png)

all other VM tabs are blocked and blank:

![image](https://user-images.githubusercontent.com/414850/109037545-194f5400-76cb-11eb-935f-05f8666d9ba6.png)

**To Reproduce**
Cause an error in VM deployment(??), get error message block.

**Expected behavior**
Tabs are working.

Actually, I could undestand this can be an expected behaviour to get user attention to the warning box at all costs, but the implementation looks more like a bug.

**Details**
 - Affected Component: Sunstone
 - Version: master(5.13.80)

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/883)
- [Docs](https://github.com/OpenNebula/docs/pull/1490)
