### ISSUE TITLE
KVM nic-attach errror

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5268]
**Description**
If the nic-attach fails due to libvirt [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1824722) (VM can not eject cdrom) the nic appears in the VM (although without proper configuration) but it's not visible on OpenNebla VM

**To Reproduce**
Setup OpenNebula on Centos8
run VM
onevm stop
onevm resume
onevm nic-attach
 

**Expected behavior**
Idally the nic-attaed is successful, but until the libvirt bug is fixed avoid inconsistent state where the nic is attached in the VM but in OpenNebula it's not.
 
**Details**
 - Affected Component: kvm drivers
 - Hypervisor: KVM
 - Version: 5.13

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2162)
- [docs](https://github.com/OpenNebula/docs/pull/2327)
