### ISSUE TITLE
CRYPTED_PASSWORD in VM context gets corrupted on "update configuration"

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/one#5273]
**Description**
The CRYPTED_PASSWORD parameter in the VM context gets corrupted when the VM configuration is updated - probably the `$6$...` string undergoes one more variable substitiution.

**To Reproduce**
Set the CRYPTED_PASSWORD user attribute in Sunstone to some SHA512 password hash (use `mkpasswd --method=sha512crypt` if needed - for the password `test` the hash could be `$6$jhg/4Vmfu3EzwEgU$BSIFW7Y.xQCd9WT6s3rMZ5ctFbhFrjMWAa1f6HMkTGOlFlU050jZTFjUQu5SLZAHRaYgdXirgATsoZzFI6Z4g.` ).

Have a VM template with `CRYPTED_PASSWORD = "$USER[CRYPTED_PASSWORD]"`in its `CONTEXT` section.

Instantiate the template, wait for the VM to boot.

Open the VM page in Sunstone (Instances/VMs), go to the "Conf" tab. The CRYPTED_PASSWORD variable should be set to `$6$...` password hash as expected.

Now click on `Update configuration`. Do not modify anything, just click on the green `Update` button near the top of the page.

Open the "Conf" tab again. The CRYPTED_PASSWORD now does not start with `$6$...`, but with the first non-letter of the password (for the `test` hash above, it starts with `/4Vmfu...`).

**Expected behavior**
The CRYPTED_PASSWORD parameter should remain the same (`$6$....`).

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12.0.3 CE, CentOS 7
 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Yenya** [comment]
It might be better to do a variable substitiution just once, before writing the context.sh file. Not earlier. So even after the instantiation, the `CRYPTED_PASSWORD` context variable could be `$USER[CRYPTED_PASSWORD]` literally without the variable substitution at all. The present way could lead to security holes.

**Comment by Yenya** [comment]
Or, alternatively, the password itself could be entered with escaped dollar characters, as `\$6\$...\$...`, provided that the escaping is kept as is through all steps till the context ISO image is created.

**Comment by flohoff** [comment]
The problem is that one cannot easily use "$" in password - You have to escape them for obvious shell reasons. The problem then is that chpasswd writes it "AS IS" into the shadow. So not escaping $ breaks the shell usage, escaping it breaks it in /etc/shadow.

```
root@vpnbridge2:~# cat /etc/shadow
root:\$5\$slJrZCvWmdHQEI8\$01De65pojj92lTgVSEXc3xBiqKXpbXNtNgveGJju\/C:18702:0:99999:7:::
```

**Comment by tinova** [comment]
This is a known issue, check the following for a workaround https://docs.opennebula.io/6.0/management_and_operations/references/template.html?highlight=crypted_password#context-section. We'll keep this open to track the fix.

**Comment by paczerny** [comment]
Partially solved, when you don't modify the password, the value won't be changed on updateconf.

It's still not possible to set new password in the format `$6$jhg/4Vm...`, you need to store it to user and use the form `$USER[CRYPTED_PASSWORD]`
