### ISSUE TITLE
FireEdge is not optional

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5274]
**Description**
According the [installation docs](http://docs.opennebula.io/5.13/quick_start/opennebula_installation/single_frontend_installation.html#fireedge-optional) the FireEdge module is "optional" but sunstone interface is rising error:
![image](https://user-images.githubusercontent.com/11386997/109655023-7d5e9600-7b6b-11eb-834e-965ba0db2eae.png)

Also, 
1. I can't see how to configure the fireedge service to listen to the localhost only. In the configuration file, there is an option to change only the listening port. 
2. I can't find how to use HTTPS for this service too. Usually, I configure Nginx as a reverse proxy to provide https. So I can't see how to expose the service to the internet with encryption. 

And no, firewall rules are not a working solution for me... (they are just moving the problem, not solving it)

**To Reproduce**
Install OpenNebula skipping the FireEdge because it is optional
login to sunstone

**Expected behavior**
I expect that the optional modules do not need additional configuration to disable/protect them

**Details**
 - Affected Component: [Sunstone,Fireedge]
 - Hypervisor: [KVM]
 - Version: [5.13.80]

**Additional context**

The oneflow service is not optional too - susntone complains but only when you try configuring flows. I could live with that...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Hi Anton,

Thanks for your feedback. This was indeed not coherent, FireEdge is no longer optional as you say, we've changed the documentation to state so.

If you want to disable FireEdge in Sunstone, please comment out both *_fireedge_endpoints.

Closing this for now, please reopen if you deem it necessary.

**Comment by atodorov-storpool** [comment]
Hi @tinova ,

As we have fireedge that is mandatory, what about the missing possibility to define the address where to bind the service?
I don't like the idea to have an internet-facing service without encryption by default and to rely on another service (firewall?) to protect it...


Should I open a separate issue about it?

Cheers,
Anton

**Comment by tinova** [comment]
Hi Anton,

No need for a separate issue. Indeed this makes sense, we just covered it in https://github.com/OpenNebula/one-ee/commit/8883d488b87cba37409a2b3fbd7e2c98c35af589.

**Comment by atodorov-storpool** [comment]
Hi Tino,

Can't see the commits in the private repo, just sharing that the following patch woks fine until I have access to the fix

```bash
sed -i 's/U,\"0\.0\.0\.0\",/U,"127.0.0.1",/' /usr/lib/one/fireedge/dist/index.js
```

Cheers,
Anton
