### ISSUE TITLE
Remove default hybrid support and econe server

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5275]
**Description**

OneProvision is the new default way of growing your OpenNebula cloud. Hybrid support will be disabled by default.

Also, econe server will be removed from OpenNebula.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Looks like a duplicate of https://github.com/OpenNebula/one/issues/5204

**Comment by tinova** [comment]
indeed, closing #5204 (sorry :) ) as I already created a feature branch

**Comment by tinova** [comment]
removed in 31f8df8ff82ed225ef987db65dda8c723586f16e
compatiblity guide note added in OpenNebula/docs@f5a20f6f407a80a4975c99317b0c8bf69a896ea3
