### ISSUE TITLE
Feature/Iothreads not working in Sunstone

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5279]
**Description**
Two issues here: wrong iothreads variable and wrong tooltip content

![image](https://user-images.githubusercontent.com/11386997/110116873-cf4c2980-7dc0-11eb-879e-d970fa10eba3.png)
![image](https://user-images.githubusercontent.com/11386997/110116964-ed198e80-7dc0-11eb-805a-0982b59c5d4a.png)

**To Reproduce**
define a VM Template with iothreads 1
instantiate a VM from the template
The VM's domain XML had no iothreads defined

**Expected behavior**
iothreads should be defined in the domain XML

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**
I think that the issue due to a wrong variable name in sunstone.It should be _IOTHREAD**S**_.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/937)

**Comment by tinova** [comment]
thanks for reporting this @atodorov-storpool
