### ISSUE TITLE
Set(pin?) VM disk controller to an iothread in Sunstone

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5280]
**Description**
Looking at the sources it should be possible to pin a given disk controller to an IOTHREAD when Feature/Iothreads is >0

**Use case**
Not practical use case. My observation is that moving all storage operations to a dedicated iothread(virtio data plane) is enough to improve the VM disk performance. But if the code already allows the iothread pinning, so why not? ;-P

**Interface Changes**
VM Template - Advanced disk attributes Iothread
VM attach virtio-blk disk - advanced disk attributes - Iothread
AFAIK in the case of the virtio-scsi disks there is a SCSI controller so will be tricky because there is no option to pin, or additional SCSI controller should be added? 

Note: I think this should depend on the value of Features/Iothread and should be an option only when `IOTHREADS > 1` (with a single iothread defined, the pinning is irrelevant)

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to address this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/986)
- [Docs](https://github.com/OpenNebula/docs/pull/1530)
- Test: Pending

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Tests](https://github.com/OpenNebula/development/pull/1396)
