### ISSUE TITLE
inconsistency in the create wizard for Images and Volatile disks

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5283]
**Description**
The create wizard for volatile disk image had a mandatory option to create a swap or fs disk with a filesystem. The Image create wizard had no mandatory option to create a filesystem when the image is created

![image](https://user-images.githubusercontent.com/11386997/110339349-c06bae00-8030-11eb-8ae2-d2a4691f95d7.png)

**To Reproduce**
Open the create Image wizard 
The user must type manually `FS=_filesystem_` that could lead to errors like spaces, mis-spelling, etc...

**Expected behavior**
Option to select the filesystem as with the Volatile disks

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**
This is actually the opposite of #5282 :) But the same logic applies - have the feature but with the option to disable the mkfs step...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hello @atodorov-storpool, this have been already fixed in the development branch. A dropdown have been added in order to facilitate the user the filesystem selection if needed.

![select_fs_create_image](https://user-images.githubusercontent.com/19222136/110461582-ebf1a580-80cf-11eb-90c3-68ee5201f88e.png)
