### ISSUE TITLE
missing VM Backup documentation 

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5286]
**Description**
The documentation on how to do VM backup is missing.
The operations guide is in the docs subproject but not populated.

Can't find a word on how to develop a backup module in the integrations guide, though. So working with trial and error...

**To Reproduce**
open http://docs.opennebula.io/5.12/operation/vm_management/index.html
there is no documentation

**Expected behavior**
the documentation should be visible in the docs

**Details**
 - Affected Component: [docs]
 - Hypervisor: [any]
 - Version: [5.13]

**Additional context**
the operations guide is here https://github.com/OpenNebula/docs/blob/master/source/operations_guide/vm_management/vm_backup.rst
but not populated on the docs site.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
The documentation is here:
http://docs.opennebula.io/5.13/operations_guide/vm_management/index.html
