### ISSUE TITLE
VM Backups to custom marketplace storage driver

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5287]
**Description**
Following the current [documentation](https://github.com/OpenNebula/docs/blob/master/source/operations_guide/vm_management/vm_backup.rst#requirements) and looking at the [code](https://github.com/OpenNebula/one/blob/master/src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general.js#L348) the _http_ and _s3_ Marketplace storage drivers are the only possible for the VM Backups, but they are not compatible/suitable with distributed block storages. Here should mention the ancient bug #1159 that renders the export of a block device to the http marketplace unusable. A custom driver could fit better, but the options are hard-coded currently so there is no way to define a custom driver at the moment.

**Use case**
Configure and use custom Marketplace Storage Drivers for VM Backups that fit better than the default file or object storage.

**Interface Changes**
Option to configure custom Marketplace storage drivers
Option to add the custom Marketplace driver in sunstone.

**Additional Context**
The current situation is locking the feature to the limited set of internal drivers only.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Hm. Then, the code is not using datastore/export (in combination with market/import) then? So the common flow to export a VM to the marketplace is not used? Maybe I am missing something...

**Comment by atodorov-storpool** [comment]
I am referencing http://docs.opennebula.io/5.12/integration/infrastructure_integration/devel-market.html#marketplace-drivers-structure and http://docs.opennebula.io/5.12/integration/infrastructure_integration/sd.html#datastore-drivers-structure

The issue in #1159  is that after import the Market driver do not call a datastore driver to do any cleanup. In our case we are exporting a symlink to readonly snapshot to be read by market/import and after import the driver just delets the symlink and the snapshot is left hanging in the storage forever...

**Comment by xorel** [comment]
OK, while trying to sort this out, Ruben suggested passing call-back command instead of running a driver action. So, the export would pass something like:
```
 <IMPORT_INFO>
....
<DISPOSE>YES</DISPOSE>
<DISPOSE_CMD>rm "$(readlink $SRC)"</DISPOSE_CMD>
</IMPORT_INFO
```
Does it fit your case?

**Comment by atodorov-storpool** [comment]
Hi @xorel ,
having a callback is better than nothing, so, yes it could fit.
