### ISSUE TITLE
CPU cost calculation in the VM Template wizard

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5288]
**Description**
First to clarify that I no familiar with the cost definitions in opennebula so I am not sure why tried to write down some COST values... Looking at the cost calculation does not feel it looks like a bug to not have any value for CPU/month:

![image](https://user-images.githubusercontent.com/11386997/110496858-95e82680-80fe-11eb-8976-8b431cb8afb7.png)

**To Reproduce**

- Update VM Template
- Set CPU cost
- The greyed field shows no value

**Expected behavior**
I _think_ that there should be some value in the calculated CPU cost/month...

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.13]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova:
- Code: https://github.com/OpenNebula/one-ee/pull/932
- Docs: https://github.com/OpenNebula/docs/pull/1504
