### ISSUE TITLE
VM Template wizard: Can't define sockets when defining NUMA topology

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5291]
**Description**
Defining NUMA topologin in Sunstone Update Template wizard do no allow defining the number of sockets.

**To Reproduce**
Import app from the Marketplace
Try to define a NUMA topology ![image](https://user-images.githubusercontent.com/11386997/110603449-b44a3280-818f-11eb-92f5-b660d8f05168.png)
Update the template and then Instantiate a VM wit the template will raise error:
 ![image](https://user-images.githubusercontent.com/11386997/110603764-09864400-8190-11eb-9f92-019acb7fd5eb.png)

**Expected behavior**
The VM Template should allow configuring the sockets.
And a VM should instantiate.

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**
The VM template view:
![image](https://user-images.githubusercontent.com/11386997/110603549-cd52e380-818f-11eb-91be-d0436f7c3414.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Hi @atodorov-storpool 
I tried to reproduce this issue but I'm not capable of doing it, can you provide more information about how to reproduce it?

**Comment by FrederickBor** [comment]
@tinova since I tried to reproduce it I found another issue and I fixed it here:
- [Code](https://github.com/OpenNebula/one-ee/pull/989)

**Comment by atodorov-storpool** [comment]
Import VM appliance
Templates - update template
select NUMA tab
tick the Numa topology checkbox
populate Threads (1)
populate VCPU (2)
click anywhere --> The Threads input becomes greyed out

So it looks like it is related to the VCPUrelated input :)

**Comment by atodorov-storpool** [comment]
reproducible with 5.13.85:
![image](https://user-images.githubusercontent.com/11386997/111481771-f5b48200-873b-11eb-8400-eb5f03739c92.png)

**Comment by FrederickBor** [comment]
Thanks for your quick answer @atodorov-storpool now I could reproduce it.

@tinova  PRs to be applied:
- [Code](https://github.com/OpenNebula/one-ee/pull/991)
- [Docs](https://github.com/OpenNebula/docs/pull/1541)
- Tests: Pending
