### ISSUE TITLE
VM Template Wizard: VCPU could be defined on two places

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5292]
**Description**
VM Template -> General
![image](https://user-images.githubusercontent.com/11386997/110617630-91734a80-819e-11eb-844d-048645350c22.png)

VM Template -> NUMA
![image](https://user-images.githubusercontent.com/11386997/110617427-5ec95200-819e-11eb-9658-14fd0c60a891.png)

**To Reproduce**
See the screenshots provided in the description above

**Expected behavior**
A single place to define _all_ (v)CPU related configuration
or synchronise the value in both places
or remove the duplicate?

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [5.13]

**Additional context**
Both entries define the VCPU variable in the VM Template.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Hi @atodorov-storpool 
The expected behavior is that both values refer to the same vCPU, so they should be in sync in both dialogs. I've run several tests and in all of them, the value is always correctly synchronized. We provide it in both places for convenience. Can you share the steps to follow to reproduce the issue (I understand you don't see the sync happening?)

**Comment by atodorov-storpool** [comment]
Can't reproduce at the moment, but having an editable field on two places for the same value is... Sounds weird to me...
Why don't pick one place (the general tab for historical reasons) as a source of truth and in the Numa tab let only the value, not in an editable box?
