### ISSUE TITLE
Do not Allow VCPU_MAX (resize) for VM with custom NUMA topology

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5293]
**Description**
There are a lot of issues on the subject.

**To Reproduce**
Play with CPU resizing and a basic NUMA topology, without CPU pinning

**Expected behavior**
Should it work?

**Details**
 - Affected Component: [Sunstone,Core]
 - Hypervisor: [KVM]
 - Version: [5.13]

**Additional context**
I am getting really tired of reporting issues...

For example deploying VM with
```xml
    <TOPOLOGY>
      <CORES><![CDATA[1]]></CORES>
      <PIN_POLICY><![CDATA[NONE]]></PIN_POLICY>
      <SOCKETS><![CDATA[1]]></SOCKETS>
      <THREADS><![CDATA[2]]></THREADS>
    </TOPOLOGY>
    <VCPU><![CDATA[2]]></VCPU>
    <VCPU_MAX><![CDATA[6]]></VCPU_MAX>
```
raise an error in libvirt:
```
error: Failed to create domain from deployment.3
error: unsupported configuration: CPU topology doesn't match maximum vcpu count
```

If you define the topology to match the max-vcpus -OpenNebula does not allow this combination... If you manage to workaround this manually editing the domain XML, then the hotplugged VCPUs are offline in the guest...

this sort of works - domain.xml
```xml
  <vcpu placement='static' current='2'>6</vcpu>
  <cpu>
    <topology sockets='1' cores='3' threads='2'/>
  </cpu>
```
in the guest we have

![image](https://user-images.githubusercontent.com/11386997/110626298-398e1100-81a9-11eb-89a4-28039298e732.png)

hot resize the cpus to 4, the domain XML had

```xml
  <vcpu placement='static' current='4'>6</vcpu>
  <vcpus>
    <vcpu id='0' enabled='yes' hotpluggable='no' order='1'/>
    <vcpu id='1' enabled='yes' hotpluggable='no' order='2'/>
    <vcpu id='2' enabled='yes' hotpluggable='yes' order='3'/>
    <vcpu id='3' enabled='yes' hotpluggable='yes' order='4'/>
    <vcpu id='4' enabled='no' hotpluggable='yes'/>
    <vcpu id='5' enabled='no' hotpluggable='yes'/>
  </vcpus>
  <cpu>
    <topology sockets='1' cores='3' threads='2'/>
  </cpu>
```

in the guest we have
![image](https://user-images.githubusercontent.com/11386997/110626842-e5376100-81a9-11eb-929a-4c9c1dae0636.png)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Yes resize, is not supported for pinned VMs https://github.com/OpenNebula/one/blob/master/src/rm/RequestManagerVirtualMachine.cc#L2147

For non-pinned VMs, VCPU_MAX is also not supported for custom topologies. It seems that the code does not enforce it

**Comment by atodorov-storpool** [comment]
missed the cpu definition:
```xml
  <vcpu current='2'>6</vcpu>
  <vcpus>
    <vcpu id='0' enabled='yes' hotpluggable='no' order='1'/>
    <vcpu id='1' enabled='yes' hotpluggable='no' order='2'/>
    <vcpu id='2' enabled='no' hotpluggable='yes'/>
    <vcpu id='3' enabled='no' hotpluggable='yes'/>
    <vcpu id='4' enabled='no' hotpluggable='yes'/>
    <vcpu id='5' enabled='no' hotpluggable='yes'/>
  </vcpus>
  <cpu>
    <numa>
      <cell cpus="0-1" id="0" memory="786432" unit="KiB" />
    </numa>
    <topology cores="3" sockets="1" threads="2" />
  </cpu>
```

**Comment by rsmontero** [comment]
VCPU_MAX is a new feature, and have this side effect on NUMA virtual definition. So for 6.0 the safest thing is not to allow use both. 

After 6.0, yes we can look to add the proper libvirt definition, and also test with the other resize operations increase/decrease current VCPU etc... And general compute of topology with and without VCPU_MAX:

About shares, no I don't get it. If you are talking about cpu shares in libvirt definition. They have nothing todo with VCPU nor VCPU_MAX. And definitely nothing todo with CPU hot-plugging. What shares are you talking about?

**Comment by atodorov-storpool** [comment]
<cpu/shares>
They are sort of bound tho the physical cpus. They are used to calculate the host resources too... so when we start a VM with a few cpus we had one cpu shares. but when we hotplug cpus, I think that the shares should be adjusted also? Or, am I totally wrong here?

**Comment by rsmontero** [comment]
Yes shares are computed based on CPU value (not vCPU/vCPU_MAX) that is used to assign the amount of physical to implement over-commitment, and it is separated for the virtual number of CPUs the VM sees. When the VM includes pinning CPU is set to VCPU. 

So you can use vCPU=8 and CPU=0.3
