### ISSUE TITLE
vCenter Virtual Network deletion

### ISSUE THREAD

**Issue by aros77** [OpenNebula/one#5298]
**Description**
The setup includes a vCenter host (and related resources) correctly imported inside ONE.
After successfully creating a vCenter Network inside ONE (which generates a Distributed Port Group inside vCenter), the deletion of the same network does not removes the related Distributed Port Group inside vCenter.

**To Reproduce**
1. Create a vCenter Network inside ONE (Sunstone)
         - Network mode=vCenter plus all the related parameters like Switch name, OpenNebula's host ID, Port Group type are correct.
         - the Network is correctly created inside ONE
         - the new Network successfully generates a Distributed Port Group inside vCenter with proper parameters
2. Delete the previously created Network inside ONE (Sunstone)
         - the new Network is successfully deleted from ONE (Sunstone)
         - the related Distributed Port Group is NOT deleted from vCenter

**Expected behavior**
The new Distributed Port Group should be deleted from vCenter as well. The same issue (with the very same imported vCenter) is NOT present in ONE 5.12.0.3.

**Details**
 - Affected Component: Sunstone, Networks
 - Hypervisor: vCenter/ESXi
 - Version: 6 / 5.13.80

**Additional context**
Imported vCenter host is running vCenter 7 (ESXi 7.0.1).

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
Thanks for the feedback @aros77 
We have not been able to reproduce the error, could you give us more information about exactly the data sent and the network created, to know if it is a specific combination?
Please send us the network xml as well as the log to know if it gave any errors during the removal.
Check the hooks to see if it ran successfully.

**Comment by aros77** [comment]
Hello,
Thanks a lot for your feedback.
Could you please specify:

-          Where I can find the network xml

-          How I can check Hooks
That would be of great help.

Thank you very much and Best Regards,
Andrea

**Comment by carloshm91** [comment]
Hello @aros77 

First of all reproduce the problem and then execute all this next commands.

> Where I can find the network xml

You can execute this command

```
onevnet show -x <ID>
```

Where ID is the ID of the network

> How I can check Hooks

Yo can see the hooks with this command

```
onehook list
```

You will see some thing like this

```
  ID NAME                                                    TYPE    
   2 vcenter_net_instantiate                                 api
   1 vcenter_net_delete                                      api
   0 vcenter_net_create                                      api
```

Please see the ID of `vcenter_net_delete` and then execute:

```
onehook show <HOOK_ID>
```

You will see some thing like this:

```
HOOK 1 INFORMATION                                                              
ID                : 1                   
NAME              : vcenter_net_delete  
TYPE              : api                 
LOCK              : None                

HOOK TEMPLATE                                                                   
ARGUMENTS="$API"
ARGUMENTS_STDIN="yes"
CALL="one.vn.delete"
COMMAND="vcenter/delete_vcenter_net.rb"
REMOTE="NO"

EXECUTION LOG
   ID       TIMESTAMP    RC EXECUTION
    0     03/25 03:48     0 SUCCESS
    1     03/25 05:09     0 SUCCESS
    2     03/25 05:10     0 SUCCESS
    3     03/25 05:13     0 SUCCESS
    4     03/25 05:16     0 SUCCESS
    5     03/25 05:21     0 SUCCESS
    6     03/25 05:22     0 SUCCESS
    7     03/25 05:24     0 SUCCESS
    8     03/25 05:28     0 SUCCESS 
```

Now send us the following command for the last 3 logs with the following command:

```
onehook show <HOOK_ID> -e <HOOK__LOG_ID>
```

In our case is 8, 7 and 6.

Thanks for your help.

**Comment by aros77** [comment]
Thanks for the info,
We found out that the issue was due to /etc/hosts file not populated with vcenter/esxi hosts entries. Once we put those entries inside /etc/hosts of ONE host, the network deletion started working correctly.
You can consider this issue solved.

Thanks a lot,
Andrea
