### ISSUE TITLE
Add support for configurable TLS version / CIPHERS in novnc (websockify)

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#5300]
**Description**
Since websockify version 0.9 there is support to specify the minimum TLS version websockify should use. By default it allows TLS 1.0, 1.1, 1.2 and 1.3. TLS 1.0 and 1.1 should not be used anymore (EOL / known insecure). The same goes for certain CIPHERS. 

**Use case**
We would use this feature to force novnc sessions to use TLS 1.2 and up.

**Interface Changes**
Two configuration options should be added to the sunstone-server.conf:
```
vnc_proxy_tls_version=
vnc_proxy_tls_ciphers=
```
I would suggest to use tlsv1_2 in the default configuration file to have a secure default.

**Additional Context**
To see if a newer version of websockify would work with OpenNebula 5.12, I did the following:
git clone https://github.com/novnc/websockify/
replace "run" with:
```
#!/usr/bin/env python

import websockify

websockify.websocketproxy.websockify_init()
```
Edited the VNC ruby file, /usr/lib/one/ruby/OpenNebulaVNC.rb, so it reads:
```
cmd ="python3 #{@proxy_path} #{proxy_options} #{@proxy_port} --ssl-version=tlsv1_2"
```
This version of websockify does not seem to work with Python 2.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
noVNC has been deprecated in favor of guacamole in recent opennebula versions
