### ISSUE TITLE
Docker-machine driver try to resume VM when it is in Pending state

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#5301]
Hello, I see error logs like this

```
Req:2720 UID:3 one.vm.action result FAILURE [one.vm.action] Error performing action "resume": This action is not available for state PENDING
```

I think it is related to following line:
https://github.com/OpenNebula/one/blob/051b36e0d91746d8e7ffc77cfb365d36e337ec9e/src/docker_machine/src/docker_machine/opennebula.go#L693

What is purpose of resume action?

**Comment by feldsam** [comment]
PR #5303

**Comment by al3xhh** [comment]
Changes are already merged, closing this, reopen it if needed.
