### ISSUE TITLE
IMAGE HOOK example typo

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5307]
**Description**

There is a typo in the image hooks example...

**To Reproduce**
open http://docs.opennebula.io/5.13/integration_and_development/system_interfaces/hook_driver.html#state-hook-example-image

**Expected behavior**
A working example

**Details**
 - Affected Component: [Docs]
 - Hypervisor: [KVM]
 - Version: [5.13]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
This is most probably becasue of missing dependencies. There is a warning at the beginning of the section. The error in this case is

```
EXECUTION STDERR
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- nokogiri (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /var/lib/one/remotes/hooks/image_ready.rb:4:in `<main>'
```

Using the snippet recommended at the beginning of the section, I get a clean run:

```
HOOK 0 INFORMATION
ID                : 0
NAME              : image-ready
TYPE              : state
LOCK              : None

HOOK EXECUTION RECORD
EXECUTION ID      : 3
TIMESTAMP         : 04/21 11:55:29
COMMAND           : /var/lib/one/remotes/hooks/image_ready.rb 
...
  </SNAPSHOTS>
</IMAGE>
EXIT CODE         : 0

EXECUTION STDOUT
Image 5 ready to use!!

EXECUTION STDERR

```
