### ISSUE TITLE
CLI error output not always on stderr

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5311]
**Description**
When working with non-existing object over CLI, the error goes to standard output, instead of **error** output:

```
# onevm show 123 2>/dev/null
[one.vm.info] Error getting virtual machine [123].
```

(all object types affected)

**Details**
 - Affected Component: CLI
 - Version: 5.10 and up

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PR to merge on 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1087)

PR to merge on 6.0:

- [docs](https://github.com/OpenNebula/docs/pull/1771)
