### ISSUE TITLE
ONE 6 vCenter - network creation on default cluster

### ISSUE THREAD

**Issue by aros77** [OpenNebula/one#5312]
**Description**
After importing all vCenter resources inside default ONE cluster 0, when we create new networks, they lose their Cluster ID membership and we need to manually re-assign the Cluster.

**To Reproduce**
1. Setup ONE and import vCenter resources (vCenter, Datastores).
2. Create a network specifying
   - Cluster ID = 0
   - Network mode = vCenter
   - Switch Name = <vCenter Distributed Switch Name>
   - Port group type = Distributed Port Group
   - Host ID = <vCenter Cluster>
3. Network is successfully created, but the CLuster ID is lost (right after creation you can see it, but after a refresh of the page the ID is gone)
At this stage, you need to manually re-assign the Cluster ID to the new network, otherwise no VM can be instantiated with that network interface.

**Expected behavior**
The new Network should keep the Cluster ID setting when created.

**Details**
 - Affected Component: Sunstone, Network
 - Hypervisor: vCenter/ESXi
 - Version: 5.12.0.3 and 5.13.80 (Beta 6)

**Additional context**
See attached screenshots.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
[vnet-creation-cluster-issue.docx](https://github.com/OpenNebula/one/files/6213089/vnet-creation-cluster-issue.docx)

**Comment by juanantonioesco** [comment]
- Doc: [https://github.com/OpenNebula/docs/blob/one-6.0-maintenance/source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst](url)

- PR: [https://github.com/OpenNebula/one-ee/pull/1240](url)

**Comment by aros77** [comment]
> 
> 
>     * Doc: [https://github.com/OpenNebula/docs/blob/one-6.0-maintenance/source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst](url)
> 
>     * PR: [https://github.com/OpenNebula/one-ee/pull/1240](url)

Hello,
The first link leads to a page listing resolved issues in 6.0.2. None of them seem to apply to this case, according to the title.
The second link leads to a non-existing web page.
Did I miss anything? Can you please provide some info?

Thank you very much

**Comment by juanantonioesco** [comment]
Hello,
Sorry, the links are updated now with the correct information.

**Comment by aros77** [comment]
> 
> 
> > ```
> > * Doc: [https://github.com/OpenNebula/docs/blob/one-6.0-maintenance/source/intro_release_notes/release_notes_enterprise/resolved_issues_602.rst](url)
> > 
> > * PR: [https://github.com/OpenNebula/one-ee/pull/1240](url)
> > ```
> 
> Hello,
> The first link leads to a page listing resolved issues in 6.0.2. None of them seem to apply to this case, according to the title.
> The second link leads to a non-existing web page.
> Did I miss anything? Can you please provide some info?
> 
> Thank you very much

OK, now I see you edited that page and now it shows this issue in the list of resolved issues for 6.0.2.
So, I assume that 6.0.2 will deliver the proper bug fix.

Thank you
