### ISSUE TITLE
[one.vm.chown] checks group quota twice on already owned resources

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#5315]
**Description**

Hi, OpenNebula terraform operator invokes **one.vm.chown** method for every created VM even in case if it is already owned by exact user and group.
*(see the discussion in https://github.com/OpenNebula/terraform-provider-opennebula/issues/111 for more details)*

In case if group has quota set and VM exceed this quota twice this operation will return an error:

```xml
<!---------- INPUT ------------>

<?xml version="1.0"?>
<methodCall>
    <methodName>one.vm.chown</methodName>
    <params>
        <param><value>oc4790:deadbeefdeadbeefdeadbeefdeadbeef</value></param>
        <param><value><i4>11756</i4></value></param>
        <param><value><i4>-1</i4></value></param>
        <param><value><i4>4577</i4></value></param>
    </params>
</methodCall>

<!--------- OUTPUT ------------>

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><array><data>
<value><boolean>0</boolean></value>
<value><string>[one.vm.chown] User [4787] : group [4577] limit of 4096 reached for MEMORY quota in VM.</string></value>
<value><i4>512</i4></value>
<value><i4>-1</i4></value>
<value><i8>-1</i8></value>
</data></array></value></param>
</params>
</methodResponse>

<!---------- END -------------->
```

**To Reproduce**

```bash
oneuser create quotatest quotatest
onegroup create quotatest
oneuser addgroup quotatest quotatest
EDITOR="echo 'VM = [ VMS = -2, CPU = 1, MEMORY = 1024 ]' >" onegroup quota quotatest
onevm create --memory 1000 --cpu 0.1 --name quotatest
onevm chgrp quotatest quotatest
onevm chgrp quotatest quotatest
```

While the first chown command will work with no problems, the second one will return the following error:
```
[one.vm.chown] User [0] : group [4606] limit of 1024 reached for MEMORY quota in VM.
```

**Expected behavior**
No error returned

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: 5.10.5

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Merge for 6.0.4 release
