### ISSUE TITLE
Unable to add files to FILES_DS once VM is instantiated

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/one#5317]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Trying to modify context for already created VM will not work with context files and therefore no way to add actual files to be used by ``INIT_SCRIPTS`` (this context value itself can be updated though). Also there is no way to pick files as is in VM template but even copy-pasting the right value (from another VM where ``FILES_DS`` was set in template and then instantiated) will not work.

**To Reproduce**

1. Add some scripts/files to OpenNebula (storage files)
2. Create one VM template with ``FILES_DS`` already set and instantiate it (we will need it) - ``VM1``
3. Instantiate another VM **without** ``FILES_DS`` - ``VM2``
4. Click on the ``VM1``, tab **Conf** and **Update Configuration** button, follow with tab **Context** and **Files**
5. Copy the field ``FILES_DS``
6. Click on the ``VM2``, tab **Conf** and **Update Configuration** button, follow with tab **Context** and **Files**
7. Here is ``FILES_DS`` empty (as expected) but no way to pick any files - we must paste the value what we copied before
8. Click on **Update** and check the ``FILES_DS`` again
9. ``FILES_DS`` was not set - it is still empty

**Expected behavior**
When I try to update context of already created VM then I would like to be able to pick files as is done in template and update the VM context with this new context.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: all
 - Version: 5.10 and 5.13.90

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Fixed in oned. If FILES_DS are changed they are parsed and included to context.
Needs update in sunstone, in the step 7 above, it should allow to pick files in similar way as they were selected in step 2.
Can't copy/paste FILES_DS from other VM, that would return parsing error.

For completeness two bugs with FILES_DS solved in the past: #1952 #2540

**Comment by jloboescalona2** [comment]
@tinova: PR to approve:
- code: https://github.com/OpenNebula/one-ee/pull/1279
- docs: https://github.com/OpenNebula/docs/pull/1876
