### ISSUE TITLE
Sunstone Image upload not working in Japanese

### ISSUE THREAD

**Issue by marimelon** [OpenNebula/one#5322]
**Description**
Sunstone Image upload not working in Japanese.

![screenshot](https://user-images.githubusercontent.com/29140293/113973830-e4aceb80-9877-11eb-8bb3-8c70709d689d.jpg)

**To Reproduce**
Change the language of Sunstone to Japanese.

**My idea of a solution**
https://github.com/OpenNebula/one/blob/8950f895254912e6cd3041620206c4c59ecf94bf/src/sunstone/public/app/tabs/images-tab/form-panels/create-common.js#L207

fix:

```
if(wizardTab.title === Locale.tr("Image")){
```

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
PRs:
-Code: https://github.com/OpenNebula/one-ee/pull/1084
-Docs: https://github.com/OpenNebula/docs/pull/1777

**Comment by FrederickBor** [comment]
@tinova PR for testing [here](https://github.com/OpenNebula/development/pull/1504)
