### ISSUE TITLE
Sunstone cut texts on sidebar menu

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#5325]
**Description**
When large text is showed on the sidebar menu the text is cut.

![image](https://user-images.githubusercontent.com/18015892/114044822-d6ff6200-9887-11eb-900d-557fc18bf549.png)

**To Reproduce**
Change language (i.e. Portuguese) open Networks and security groups will be cut. 

**Expected behavior**
The text not to be cut.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: N/A
 - Version: 6.0.1

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge
- one: OpenNebula/one-ee/pull/1090
- doc: OpenNebula/docs/pull/1774
