### ISSUE TITLE
Sunstone removes Security Group attribute on update

### ISSUE THREAD

**Issue by paczerny** [OpenNebula/one#5327]
**Description**
Custom attribute in Security group disappears if I update the Security Group in Sunstone.

**To Reproduce**
Add custom attribute on the Security Group page (see `HELLO=World` at the bottom of the picture)
![Screenshot from 2021-04-08 23-44-57](https://user-images.githubusercontent.com/28096759/114102004-dc2fd180-98c6-11eb-98a0-a0d9fb600fb2.png)
Now updating the security group: Click 'Update', don't change anything and again click 'Update' to confirm changes. The `HELLO=World` attribute disappears.

**Expected behavior**
Do not delete attributes

**Details**
 - Affected Component: Sunstone
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1089)
- [Docs][(https://github.com/OpenNebula/docs/pull/1772)
