### ISSUE TITLE
Fast logrotate on service start

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5328]
**Description**
With big historic logs, the log rotate on service start can vastly extend the start time or even timeout the service start as it tries to compress the old logs. The logrotate should be as quick as possible, the compression should be handled asynchronously on the OpenNebula services (e.g., as part of the nightly logrotates only).

**To Reproduce**
Generate a big log for oned/monitor (e.g. 20G), restart the service several times (first restart might be quick).

**Expected behavior**
Service restart is quick, no compression happens.

**Details**
 - Version: 5.12+

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Related support ticket: https://opennebula.zendesk.com/agent/tickets/23833

**Comment by onenhansen** [comment]
https://github.com/OpenNebula/one-ee/pull/2275

**Comment by onenhansen** [comment]
https://github.com/OpenNebula/one-ee/pull/2278
https://github.com/OpenNebula/docs/pull/2393
