### ISSUE TITLE
LDAP Auth when LDAP group has spaces or special characters

### ISSUE THREAD

**Issue by jimfreeman** [OpenNebula/one#5330]
**Description**

There appears to be an issue when enabling LDAP authentication in OpenNebula, when the LDAP group has a space, or potentially other special characters, in it.

In `/usr/lib/one/ruby/opennebula/ldap_auth.rb` the username is encoded. It is then used as a filter to find what groups the said user belongs to - but nothing is returned as the encoded spaces cause the filter to fail.

**To Reproduce**

- Configure LDAP in OpenNebula, connecting to an LDAP server where a user is part of an LDAP group that contains spaces in it (eg. "My LDAP Group")
- Try to authenticate the user via LDAP in OpenNebula

**Expected behavior**

User can authenticate and lookup the appropriate LDAP group as expected

**Details**
 - Affected Component: LDAP Authentication
 - Hypervisor: n/a
 - Version: 6.0

**Additional context**
n/a

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
I can't reproduce the issue. Group mapping and also mandatory group was working for me even if space is in the group name.

Can you elaborate and share specific config + group details?
