### ISSUE TITLE
onedb upgrade from 5.12 -> 6.0 fails with PostgreSQL

### ISSUE THREAD

**Issue by VMGuy** [OpenNebula/one#5334]
**Description**
When running `onedb upgrade -v -t postgresql -S localhost -u oneadmin -p <PASSWORD> -d opennebula` it returns with this error on PostgreSQL:
```
undefined method `delete_idx' for #<BackEndPostgreSQL:0x000055cbdd5894f0>
/usr/lib/one/ruby/onedb/onedb.rb:302:in `upgrade'
...
```

I tried commenting this call in onedb.rb but then I hit the next error message:
```
PG::UndefinedObject: ERROR:  type "mediumtext" does not exist
LINE 1: ...(oid INTEGER PRIMARY KEY, name VARCHAR(128), body MEDIUMTEXT...
                                                             ^
```

**To Reproduce**
Install OpenNebula 5.12 with PostgreSQL.
Upgrade to 6.0 using opennebula-migration-community_6.0.0-2.ee_all.deb

**Expected behavior**
DB upgrade should work as it does with MySQL/MariaDB.

**Details**
 - Affected Component: onedb
 - Hypervisor: KVM
 - Version: 6.0

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Fixed, the patch will be included in next release 6.0.1 for Enterprise Edition and 6.0.0.1 for Community Edition
