### ISSUE TITLE
Service template registration time is not added when cloning an existing one

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5338]
**Description**
When cloning an existing service template that have no registration time the time will not add any registration timestamp to the new template.

**To Reproduce**
1. Clone a service template from a template without registration time.
2. Verify JSON or Sunstone.

**Expected behavior**
Registration should be added to the new service template for new created or cloned service templates

**Details**
 - Affected Component: OneFlow server
 - Version: 6.0.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1106)
- [docs](https://github.com/OpenNebula/docs/pull/1783)
- [tests](https://github.com/OpenNebula/development/pull/1444)
