### ISSUE TITLE
Service start time not showed in Sunstone if template has no registration time

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5340]
**Description**
When instantiate an existing service template that have no registration time the start time of the service is not added to the service.

**To Reproduce**
1. Instantiate a service from a template without registration time.
2. Verify JSON or sunstone.

**Expected behavior**
Start time should be showed in Sunstone.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1174)
- [Docs](https://github.com/OpenNebula/docs/pull/1816)
