### ISSUE TITLE
oneimage shows invalid VMs running from image

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5343]
**Description**

When displaying image details via `oneimage show`, it shows also the VMs which are **not-running from that image**(!). The list of VMs is invalid and contains unrelated VMs, despite the XML looks correct. See:

```
$ oneimage show 0
IMAGE 0 INFORMATION                                                             
ID             : 0                   
NAME           : RHEL 8              
...

VIRTUAL MACHINES

  ID USER     GROUP    NAME                          STAT  CPU     MEM HOST                      TIME
  24 oneadmin oneadmin base_Alpine 3.10_bt6ap58-24   boot  0.1    768M centos7-ev-context-   0d 16h48
  22 oneadmin oneadmin base_RHEL 8_u6wwrmh1-22       poff  0.1    768M centos7-ev-context-   0d 16h48
   6 oneadmin oneadmin base_Windows 2012_w1sdigec-6  poff  0.1    768M centos7-ev-context-   0d 16h52
```

While the `oneimage list` tells correctly there is just one VM:

```
$ oneimage list --filter ID=0 --list ID,RVMS
  ID RVMS
   0    1
```

as it's in the XML:

```xml
<IMAGE>
  <ID>0</ID>
  <VMS>
    <ID>22</ID>
  </VMS>
...
</IMAGE>
```

**To Reproduce**

**Expected behavior**
`oneimage show` displays only VMs running from that image.

**Details**
 - Affected Component: CLI
 - Hypervisor: n/a
 - Version: 6.0.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1111)
- [docs](https://github.com/OpenNebula/docs/pull/1786)

**Comment by vholer** [comment]
Reopening, still hapens on 6.0.1 as seen on demo.

![image](https://user-images.githubusercontent.com/414850/116271730-8b522100-a780-11eb-8a97-3ce369e42b53.png)
