### ISSUE TITLE
Sunstone 2FA does not work with FireEdge enabled

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5347]
**Description**
When 2FA configured and Sunstone with FireEdge is eanbled, users with 2FA are not able to login. Non 2FA users can login.  

**To Reproduce**
Configure 2FA Sunstone with FireEdge enabled and try to login with a 2FA user.

**Expected behavior**
2FA should work with Sunstone with FireEdge enabled.

**Details**
 - Affected Component: Sunstone, FireEdge
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to merge:

- [master](https://github.com/OpenNebula/one-ee/pull/1113)
- [one-6.0](https://github.com/OpenNebula/one-ee/pull/1114)
- [doc](https://github.com/OpenNebula/docs/pull/1795)
