### ISSUE TITLE
Add support for virtualized Nvidia GPUs

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5351]
**Description**

Newer versions of Nvidia GPUs cannot be virtualized through OpenNebula.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/1779)
- [docs](https://github.com/OpenNebula/docs/pull/2153)
