### ISSUE TITLE
Poweroff/Resume  a VM in an edge cluster fails

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5352]
**Description**

Due probably to the elastic IP being rwquested again. This has been observed in Equinix.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Duplicated #5345. Closing this.
