### ISSUE TITLE
Add support for FILES in vCenter

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#5354]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
FILES are not supported in the vCenter driver in OpenNebula.

**To Reproduce**
Try to use a FILE the INIT_SCRIPTS. Then try run it, and will get error that they do not exist.

**Expected behavior**

That the INIT_SCRIPTS work correctly with FILES

**Details**
 - Affected Component: [Context]
 - Hypervisor: [vCenter]
 - Version: [6.2, 5.12]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
* https://github.com/OpenNebula/addon-context-windows/pull/95

**Comment by OpenNebulaSupport** [comment]
* https://github.com/OpenNebula/addon-context-windows/pull/91
