### ISSUE TITLE
Service charters can not be updated in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5355]
**Description**
Service charters can not be updated in Sunstone.

**To Reproduce**
Try to update service charters.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment]
If the VM charters are updated individually, the service charter is not updated. This should be covered in the issue.

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- Code: https://github.com/OpenNebula/one-ee/pull/1246
- Docs: https://github.com/OpenNebula/docs/pull/1851
- Tests: https://github.com/OpenNebula/development/pull/1528
