### ISSUE TITLE
PyONE vm.info API does not return scheduled actions

### ISSUE THREAD

**Issue by wikti** [OpenNebula/one#5358]
**Description**
PyONE library does not return scheduled actions data. After doing one.vm.info(vm_id) query, returned object does not have SCHED_ACTION attribute. Manual query to endpoint returns expected data.

**To Reproduce**
one.vm.monitoring(vm_id)['SCHED_ACTION']

**Expected behavior**
Above line should return list of scheduled action.

**Details**
Affected Component: PyONE
Version: PyONE 5.12.8 and OpenNebula 5.12.0.3

**Additional context**
Possible error with xml schema.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
SCHED_ACTION is a part of USER_TEMPLATE returned by the one.vm.info

```
In [3]: vm = one.vm.info(26) 
   ...: pp(vm.USER_TEMPLATE['SCHED_ACTION'])                                                  
OrderedDict([('ACTION', 'poweroff'),
             ('END_TYPE', '2'),
             ('END_VALUE', '1619778600'),
             ('ID', '0'),
             ('TIME', '1619778600')])
```

**Comment by wikti** [comment]
Sorry for wrong issue, my mistake.
