### ISSUE TITLE
Cannot instantiate vCenter template with multiple NICs after changing networks in the template (through ONE)

### ISSUE THREAD

**Issue by aros77** [OpenNebula/one#5360]
**Description**
If I edit a vCenter-imported Template with "multiple" virtual nics and change the networks attached to the nics (when I do this I select networks that correctly exist inside ONE and vCenter and that already work for other VMs), then the instantiation of the Template fails.

**To Reproduce**
Steps to reproduce behavior:
1. import a working Template from vCenter into ONE (the original template has two virtual nics)
2. edit the Template selecting different networks in place of the original ones
3. instantiate the Template
4. the instantiation fails with the following Log:
Mon Apr 26 09:34:48 2021 [Z0][VMM][E]: deploy: Deploy of VM 140 on vCenter cluster Cluster01 with /var/lib/one/vms/140/deployment.0 failed due to "InvalidArgument: A specified parameter was not correct: deviceChange[1].device.key"on attempt #0.
Plus, vCenter shows this error:
A specified parameter was not correct: deviceChange[2].device.key Cannot add multiplpe devices using the same device key.

**Expected behavior**
The VM should be regularly instantiated.

**Details**
 - Affected Component: Sunstone, VM Instances
 - Hypervisor: vCenter (v7.0)
 - Version: 5.12 and 5.13.80

**Additional context**
When I change the networks at step 2, the newly selected networks already exist in vCenter and work fine when being selected for VMs with a SINGLE virtual nic; plus, the selected networks also work fine if I import a template from vCenter that originally uses those two nics and then I instantiate the template.
Searching around I found something similar here, for an Ansible context though:
https://github.com/ansible-collections/community.vmware/issues/545
https://github.com/ansible-collections/community.vmware/pull/552
https://github.com/ansible-collections/community.vmware/issues/373
https://github.com/ansible-collections/community.vmware/issues/322
They say it should be due to some vSphere API behavior in v7.0.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanantonioesco** [comment]
Could you give us more detailed information about how to reproduce the error? We followed the same steps indicated but couldn't reproduce the error when we instantiated the VM

**Comment by aros77** [comment]
Hello,
Sorry for delay. I repeated the test with stable version of ONE 6.0.0.2 and it seems to work fine.
Thank you,
Andrea
