### ISSUE TITLE
CLI onevm (un)lock doesn't accept list

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5364]
**Description**
While it's pretty common to use CSV to address multiple entities in CLI actions (e.g., `onevm resume 1,2,3,4`), this is not supported by `onevm lock` (and unlock) commands.

```
# onevm unlock 454,563
VM named 454,563 not found.
```

:warning: All relevant subcommands in all commands should be reviewed.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1173)
- [docs](https://github.com/OpenNebula/docs/pull/1815)
