### ISSUE TITLE
vCenter imported wild description with extra backslash

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5366]
**Description**

Wrong line breaks (due to linting to 80 characters) visible in vCenter imported wild VMs, e.g.:

![image](https://user-images.githubusercontent.com/414850/116414955-3d4d2400-a839-11eb-9171-8bc1c7a6df0d.png)

i.e.,

https://github.com/OpenNebula/one/blob/bfc9632189c5bd0d85b379e4a099211337674b3b/src/vmm_mad/remotes/lib/vcenter_driver/vm_template.rb#L1576-L1578

**Details**
 - Affected Component: VMM vCenter
 - Hypervisor: vCenter
 - Version: 6.0+
 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
* [Code](https://github.com/OpenNebula/one-ee/commit/4c1deb51e1f01b45b4ebe7bfa95871ed1c9e0035)
* [Doc](https://github.com/OpenNebula/docs/commit/20d3528dfe34bed0326b9704f3ec90da7ae30c6d)
