### ISSUE TITLE
docker image start on kvm host?

### ISSUE THREAD

**Issue by Andrysky** [OpenNebula/one#5367]
**Description**
strange behavior

**To Reproduce**
Front-end(ubuntu 20.10)
```
wget 'https://github.com/OpenNebula/minione/releases/latest/download/minione'
echo yes | sudo bash minione -f
```
3)download  alpine  from apps( MarketPlace | DockerHub)
4)deploy (create instances)

**Сurrent behavior**
```
sudo docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
![image](https://user-images.githubusercontent.com/5894390/116417563-0a5c5d80-a844-11eb-8e85-89ba6b615d2b.png)
![image](https://user-images.githubusercontent.com/5894390/116417577-121c0200-a844-11eb-9fd6-7ac96c92ebc2.png)

**Expected behavior**
sucess deploy to docker
or if the host can only have 1 engine (for example kvm) then
1) why does he start the container and says that it has been successfully launched (although it is not) - and does not say that there are no hosts with the required engine
2) why is docker installed?

**Details**
 - Affected Component: ??
 - Hypervisor: ??
 - Version: 6.0.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
MiniONE only installs and setup KVM host/engine. Or none if run with --frontend. Other hosts need to be configured afterward manually or using FireEdge.

> 1. why does he start the container and says that it has been successfully launched (although it is not) - and does not say that there are no hosts with the required engine

Seems like a problem with the image, I suggest downloading the appliance from OpenNebula marketplace, such as

>  325 Alpine Linux 3.12                     6.0.0-1.20  256M  rdy  img 04/01/21 OpenNebula    0

> 2. why is docker installed?

Docker is only used to manage images from DocerHub marketplace, OpenNebula does not run docker containers but lxc/lcd

**Comment by Andrysky** [comment]
1) "Alpine Linux 3.12 6.0.0-1.20 ..... OpenNebula" it's kvm image
same situation with "alpine_3.13 - LXD" if set host(Front-end)
![image](https://user-images.githubusercontent.com/5894390/116506295-a8dcd300-a8c5-11eb-93a7-6cb0db89a7df.png)
perhaps need to mark the image type (docker / lxc) depending on which marketplace (OpenNebula / Linux Containers / DockerHub) the image was downloaded from, and when you try to deploy to the wrong host (or, if the host with the required engine does not exist), report error and not "RUNNING" as this is misleading


>Docker is only used to manage images from DocerHub marketplace, OpenNebula does not run docker containers but lxc/lcd

2) do I understand correctly that OpenNebula CAN run docker containers on the firecracker host?
https://opennebula.io/firecracker/
https://opennebula.io/deploying-container-based-applications-with-opennebula/

or can it somehow launch a docker container on lxc / lcd?

**Comment by xorel** [comment]
> perhaps need to mark the image type (docker / lxc) depending on which marketplace (OpenNebula / Linux Containers / DockerHub) the image was downloaded from, and when you try to deploy to the wrong host (or, if the host with the required engine does not exist), report error and not "RUNNING" as this is misleading

No, this should not be required, the appliances contain the limitations themselves. For example 

```
onemarketapp export "alpine_3.13 - LXD"  -d 1 alpine_lxd

onetemplate show alpine_lxd
...
SCHED_REQUIREMENTS="HYPERVISOR=\"lx*\""
```

But such a VM will remain in a `pending` state on MiniONE host, because there is only KVM hypervisor installed.

Preferably describe whole failing scenario.

**Comment by Andrysky** [comment]
what about the second point about docker?

> But such a VM will remain in a pending state on MiniONE host, because there is only KVM hypervisor installed.

well, the problem is that now he writes that he is running.

> Preferably describe whole failing scenario.

I described the steps in the section "To Reproduce"
or need some more information?

**Comment by xorel** [comment]
> what about the second point about docker?

as written before: Docker is only used to manage images from DocerHub marketplace, OpenNebula does not run docker containers

> well, the problem is that now he writes that he is running.

yes, to understand this issue, please, describe the complete scenario. What hosts do you have created(only kvm?) which appliance did you use etc. 

Also, please re-open the issue in https://github.com/OpenNebula/minione/issues where it belongs, thank you.
