### ISSUE TITLE
vCenter fails to import wild VM w/ snapshots, but VM is imported

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5368]
**Description**
vCenter driver fails to import wild VM wich snapshots, but VM is in the OpenNebula inventory:

![image](https://user-images.githubusercontent.com/414850/116418499-7cc93f80-a83c-11eb-9935-b294841c4da7.png)
(screenshot shows the the imported VM about which OpenNebula complains)

Depending on what is really expected to happen. If such VM
1. is expected be left in OpenNebula inventory, then the message is confusing and should be "could not be **completely** imported" OR
2. shouldn't be in OpenNebula at all, all import changes must be reverted.

Also, despite the error mensions "OpenNebula cannot manage this VM", I can still poweroff that one.

**To Reproduce**
Import wild VM with snapshots.

**Details**
 - Affected Component: VMM vCenter or Sunstone
 - Hypervisor: vCenter
 - Version: 6.0.1
 - 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
* doc: https://github.com/OpenNebula/docs/commit/a7cb57af663bf722465c893429461043eb0e705c
* code: https://github.com/OpenNebula/one-ee/commit/1f3efad9bd8bede116645d63bced060d88e385e2
