### ISSUE TITLE
Name with "|" char cannot be imported from vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5370]
**Pending**

- [ ] Add note about limitations in images

**Description**
Object names (e.g. networks) with "|" char cannot be imported from vCenter.

**To Reproduce**
Import a vCenter network with name containing character "|".

**Expected behavior**
Allow importing vCenter objects with names containing character "|".

**Details**
 - Hypervisor: vCenter
 - Version: 6.0.1

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE] 
* https://github.com/OpenNebula/one-ee/pull/1172

**Comment by tinova** [comment]
- [ ] doc
- [ ] test

**Comment by tinova** [comment]
needs to be committed in both master and one-6.2

**Comment by tinova** [comment]
6.2 and master: https://github.com/OpenNebula/one-ee/pull/1672
