### ISSUE TITLE
VN Templates Cluster Selection from Sunstone

### ISSUE THREAD

**Issue by slntopp** [OpenNebula/one#5375]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
OpenNebula has the feature to choose Cluster IDs for future VNs instantiated from VN Templates.
From [official documentation](https://docs.opennebula.io/6.0/management_and_operations/network_management/vn_templates.html), the attribute `CLUSTER_IDS` is responsible for that. However, if you would use a button "Select cluster" in Sunstone, it does write cluster ids to `CLUSTER` attribute:
Template before:

```
AUTOMATIC_VLAN_ID = "YES"
BRIDGE = "somebridge"
PHYDEV = "br0"
VN_MAD = "802.1Q"
```

Template after selecting cluster:

```
AUTOMATIC_VLAN_ID = "YES"
BRIDGE = "somebridge"
CLUSTER = "0,100"
PHYDEV = "br0"
VN_MAD = "802.1Q"
```

**Details**
 - Affected Component: Sunstone, VN Templates
 - Hypervisor: KVM
 - Version: 5.12.0.3

**Additional context**
Also want to note, even after selecting Clusters in right way(via `CLUSTER_ID` attribute), clusters aren't shown on VN Template Clusters tab.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Hi @slntopp,
we will close this issue since is already solved on 6.0
