### ISSUE TITLE
[documentation] build requirements (g++)

### ISSUE THREAD

**Issue by philfry** [OpenNebula/one#5378]
The documentation states g++ 4.0.0 as build requirement, see https://docs.opennebula.io/6.0/integration_and_development/references/build_deps.html#build-deps

OpenNebula 6.0.0 uses the compiler flag `-std=c++14`: https://github.com/OpenNebula/one/blob/bfc9632189c5bd0d85b379e4a099211337674b3b/SConstruct#L121
which is available since g++ 5.2ish.

**Comment by rsmontero** [comment]
Fixed THANKS!
