### ISSUE TITLE
FireEdge authentication error when login token expires in the middle of a session

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5380]
**Description**

Fireedge use a [login token](https://docs.opennebula.io/6.0/management_and_operations/users_groups_management/manage_users.html?#tokens) for authenticating the user against `oned` XML-RPC API. If the token expires in the middle of a session every action that needs a request to `oned` will fail with:

```
{"id":500,"message":"Internal Server Error"}
```

This might also affect any Sunstone action that requires interaction with FireEdge like VMRC access.

**To Reproduce**

   - Login into FireEdge.
   - Wait for the token to expires.
   - Perform any action that requires an XML-RPC request to `oned`-

**Expected behavior**

The token is automatically renovated (if possible). Or the session is closed and the user is redirected to the login page to create a new session.

**Details**
 - Affected Component: Sunstone, FireEdge
 - Version: 6.0.0.1 & 6.0.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/1189

**Comment by jloboescalona2** [comment]
PR to merge:
- one: OpenNebula/one-ee/pull/1196
