### ISSUE TITLE
unable to install opennebula-fireedge on CentOS 8 Stream

### ISSUE THREAD

**Issue by josephtingiris** [OpenNebula/one#5388]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**

Using any nodejs dnf module, including nodejs-1:14.16.0.2, fails with ...

```
# dnf install  opennebula-fireedge                                    
Last metadata expiration check: 0:18:46 ago on Fri 07 May 2021 02:31:09 PM EDT.
Error:
 Problem: conflicting requests
  - nothing provides nodejs(abi10) >= 10.24 needed by opennebula-fireedge-6.0.0.1-1.ce.el8.x86_64
```

**To Reproduce**

```
dnf install opennebula-fireedge
```

**Expected behavior**

Installation succeeds; nodejs(abi10) >= 10.24 is found (when using appropriate modules).

**Details**
 - Affected Component: fireedge
 - Hypervisor: front end
 - Version: 6.0.1

**Additional context**

By default, CentOS 8 Stream (currently) provides nodejs(abi) v10.23.1, and I'd expect that to fail.

However, CentOS 8 Stream also provides a nodejs:14 module, which includes nodejs(abi) v14.16.0.  This should succeed.

```
dnf -y remove nodejs
dnf -y module reset nodejs
dnf -y module enable nodejs:14
dnf -y install nodejs
```
```
# npm version
{
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.6',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.16.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}
```
My expectation was it would work, but it doesn't.  Maybe an issue with the c8s appstream version info, or maybe a problem with the opennebula-fireedge rpm spec.  In either case, this is the workaround I used ... and fireedge 6.0.1 works fine on c8s with nodejs:14.

```
dnf -y remove nodejs
dnf -y module reset nodejs
dnf -y module enable nodejs:14
dnf -y install nodejs
dnf -y download opennebula-fireedge
rpm -i opennebula-fireedge-6.0.0.*-1.ce.el8.x86_64.rpm --nodeps
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Yenya** [comment]
FWIW, I took the nodejs-10.24 and npm packages from AlmaLinux 8, installed them, and now also opennebula-fireedge can be installed:

```
rpm -Uvh http://ftp.linux.cz/pub/linux/almalinux/8.6/AppStream/x86_64/os/Packages/nodejs-10.24.0-1.module_el8.3.0+2047+b07ac28e.x86_64.rpm http://ftp.linux.cz/pub/linux/almalinux/8.6/AppStream/x86_64/os/Packages/npm-6.14.11-1.10.24.0.1.module_el8.3.0+2047+b07ac28e.x86_64.rpm
```
I plan to migrate to AlmaLinux anyway, but in the meantime, I hope somebody finds this information helpful.
