### ISSUE TITLE
Sunstone add option to select vCenter Template when importing a marketplace image

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#5389]
**Description**
Actually, when importing a marketplace image from Sunstone and instantiate it on vCenter will use a default template.

![image](https://user-images.githubusercontent.com/18015892/117649308-a7e25600-b18f-11eb-85e7-b516fc75d0cf.png)

**Use case**
Use vCenter with apps from the marketplace with a different template.

**Interface Changes**
Add option to select vCenter templates when importing an image.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Needs testing

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Tests](https://github.com/OpenNebula/development/pull/1533)
