### ISSUE TITLE
Failed to import wild with snapshot in vCenter

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#5390]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When a wild has a snapshot, it should not be allowed to import. An error is currently displayed, but the wild is imported into OpenNebula.

**To Reproduce**
Import a wild with snapshot in OpenNebula.

**Expected behavior**
When trying to import a wild from vCenter with a snapshot in OpenNebula, an error should be displayed and the wild should not be imported.

**Details**
 - Affected Component: []
 - Hypervisor: [vCenter]
 - Version: [master, 6.0, 5.12]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Duplicated by #5368
