### ISSUE TITLE
[packages] oneflow depends on opennebula

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#5391]
**Description**
Oneflow depends on ActionManager gem which persists only in opennebula package

**To Reproduce**

```bash
# apt-get install opennebula-flow
# /usr/bin/ruby /usr/lib/one/oneflow/oneflow-server.rb
Traceback (most recent call last):
	7: from /usr/lib/one/oneflow/oneflow-server.rb:60:in `<main>'
	6: from /usr/share/one/gems-dist/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /usr/lib/one/oneflow/lib/LifeCycleManager.rb:19:in `<top (required)>'
	2: from /usr/share/one/gems-dist/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ActionManager (LoadError)
```

**Expected behavior**
Oneflow can work separate from `opennebula`

**Details**
 - Affected Component: packages / oneflow
 - Hypervisor: KVM
 - Version: 5.12

**Additional context**
Installing opennebula package solves that problem

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in master:

- [packages](https://github.com/OpenNebula/packages/pull/266)
- [docs](https://github.com/OpenNebula/docs/pull/2163)
