### ISSUE TITLE
Sunstone federated view always shows master zone inflow services

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5395]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When using the federated view, listing the services of any zone always shows the services of the master zone.

**To Reproduce**
- Create a service on the master zone
- switch to another zone

Example:

![image](https://user-images.githubusercontent.com/33811723/117856499-4be00600-b251-11eb-847f-7e9ddf16adcd.png)

![image](https://user-images.githubusercontent.com/33811723/117856552-5f8b6c80-b251-11eb-9358-c5ad4f14dca9.png)
 

**Expected behavior**
When using the federated view, switching between available zones should always show the corresponding services of the zone. The same way VM instances are listed:

![image](https://user-images.githubusercontent.com/33811723/117856649-7df16800-b251-11eb-9d85-45ed53105b8c.png)

![image](https://user-images.githubusercontent.com/33811723/117856702-8cd81a80-b251-11eb-8508-f3a2e6bb1126.png)

**Details**
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- code: https://github.com/OpenNebula/one-ee/pull/1263
- test: https://github.com/OpenNebula/development/pull/1542
- doc: https://github.com/OpenNebula/docs/pull/1865 https://github.com/OpenNebula/docs/pull/1866 https://github.com/OpenNebula/docs/pull/1867

**Comment by tinova** [comment]
Pending

 * one-5.12 testing

**Comment by jloboescalona2** [comment]
@tino commits for testing in 5.12: https://github.com/OpenNebula/development/pull/1543/files and https://github.com/OpenNebula/development/pull/1547
