### ISSUE TITLE
Manage RDP resolution at Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5398]
**Description**
It would be useful to have a way of manage different resolutions for RDP in Sunstone.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/1260
- dev: OpenNebula/development/pull/1541
- doc: OpenNebula/docs/pull/1864
