### ISSUE TITLE
VM Snapshot is failing when 20+ NIC ALIAS IPs added

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5401]
**Description**
VM Snapshots not created if a VM has 20+ NIC Alias IPs

**To Reproduce**
* Create a VM with a single nic
* Create a VM Snapshot - will succeed
* Attach 20+ NIC alias IPs (In my case the VM snapshots are breaking when 21 alias IPs are added)
* Create a VM Snapshot
The VM snapshot will not be created and the following error is logged:

```
Fri May 14 12:37:55 2021 [Z0][VMM][I]: Internal error Broken pipe
Fri May 14 12:37:55 2021 [Z0][IPM][D]: Message received: SNAPSHOTCREATE FAILURE 0 Internal error Broken pipe
```

**Expected behavior**

VM Snapshots should work

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [5.12+]

**Additional context**

I'd speculate that the root cause is the big internal VM XML?

Reproducible on OpenNebula 5.12.0.4-CE, 5.12.8-EE, 6.0.0.1-CE, 6.0.1-EE

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Very strange error. I was able to create snapshot with 40+ NICs

> I'd speculate that the root cause is the big internal VM XML?

This might be a good guess. What's the size (in KB) of the VM XML? Do you have some active hooks?

**Comment by atodorov-storpool** [comment]
> This might be a good guess. What's the size (in KB) of the VM XML? Do you have some active hooks?

Just do a clean install of the fresh 6.0.0.2, no hooks defined.

Here are some more tests I've done:
- with 20 alias - broken
- with 19 alias and 2 volatile disks defined - works (the size of the VM XML should be bigger, right)
- added 20th alias - broken

Attached logs [5401-logs.tar.gz](https://github.com/OpenNebula/one/files/6544463/5401-logs.tar.gz)

one-0-broken+2volatile.xml - 20 alias ips
one-0-broken-oned.log - 20 alias ips
one-0-broken.xm  - 20 alias ips
one-0-working+1volatile.xml
[one-0-working+2volatile.xml]([url](url))
one-0-working-oned.log - 19 alias ips
one-0-working.xml - 19 alias ips

**Comment by atodorov-storpool** [comment]
Well with 3 volatile disks it is failing So it sounds like a VM XML size problem...
[one-0-broken+3volatile.xml.gz](https://github.com/OpenNebula/one/files/6544563/one-0-broken%2B3volatile.xml.gz)

Also, VM Snapshot delete is affected too (same "broken pipe").

**Comment by atodorov-storpool** [comment]
@paczerny did you manage to reproduce the issue?

**Comment by paczerny** [comment]
Unfortunately not. Your limit for the VM xml size is 65 KB, which is nice number. I have size over 100 KB and everything works fine.
From the `oned.log`, it seems the error is generated on the host in the `/var/tmp/one/vmm/kvm/snapshot_create`.

What Linux distribution you use? I've been testing only on Ubuntu 20.04

**Comment by atodorov-storpool** [comment]
Hi @paczerny ,

That is a good hint:
> From the oned.log, it seems the error is generated on the host in the /var/tmp/one/vmm/kvm/snapshot_create.

I am using scripts called on the frontend (with `ARGUMENTS = ... -l snapshotcreate=snapshot_create-storpool,snapshotrevert=snapshot_revert-storpool,snapshotdelete=snapshot_delete-storpool`)

So the bug is somewhere in the handling of the local actions.
To reproduce, create a simple scripts:
```bash
cat >/var/lib/one/remotes/vmm/kvm/snapshot_create.local <<EOF
#!/bin/bash
echo "TEST-${2}-${3}-${4}"
exit 0
EOF

cat >/var/lib/one/remotes/vmm/kvm/snapshot_delete.local <<EOF
#!/bin/bash
exit 0
EOF

chmod 755 /var/lib/one/remotes/vmm/kvm/*.local 
chown -R oneadmin.oneadmin /var/lib/one/remotes/
```
and define them as local actions in the VM_MAD configuration

```
VM_MAD = [
...
ARGUMENTS = "... -l snapshotcreate=snapshot_create.local,snapshotdelete=snapshot_delete.local"
...
```
IMHO something is breaking after the scrips were called, but can't figure-out what yet.

**Comment by paczerny** [comment]
Thanks, for perfect steps to reproduce.

I identified [the line raising the broken pipe exception.](https://github.com/OpenNebula/one/blob/master/src/mad/ruby/CommandManager.rb#L172)
Don't know how to fix it. If I replace the `Open3.popen3(*cmd, opts) { ...}` with `Open3.capture3(*cmd, opts)` it works. But the `popen3` is there to handle correctly huge stderr output and to implement timeout.

**Comment by paczerny** [comment]
The issue is in the `snapshot_create.local` script. It doesn't read the input and finishes, so it closes the pipe and raises 'Broken pipe' in the ruby.

Simple fix is to ignore the broken pipe error, should be in next release
