### ISSUE TITLE
Allow designated console/display interface for spice/vnc

### ISSUE THREAD

**Issue by cgrijs** [OpenNebula/one#5404]
**Description**

**Use case**
We have a setup with multi-homed hypervisors. I'd like to configure it so that SPICE connections are possible via a designated NIC on the hypervisors that is exposed to outside networks, with OpenNebula and other traffic going over an internal network. 

**Interface Changes**
This also requires the 'host=' line in the virtviewer file to contain the exposed IP of the hypervisor. It currently uses the hostname as defined in OpenNebula. 
Additionally I'd like to suggest placing the line 'delete-this-file=1'  in the virtviewer file, to prevent clogging clients with "hostname (1).vv"  files after subsequent downloads.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
Thanks for the feedback @cgrijs , moving to backlog

your suggestion about 'delete-file' will covered in that ticket: https://github.com/OpenNebula/one/issues/5393

**Comment by tinova** [comment]
we will be deprecating SPICE support in the new Sunstone #5422
