### ISSUE TITLE
All alias IPs threatened as External on migrate/resume_after_undeploy

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5406]
**Description**
The bug is related to the [IP Aliases - IP spoofing protection stops them working 802.1Q](https://forum.opennebula.io/t/ip-aliases-ip-spoofing-protection-stops-them-working-802-1q/9544) forum post.

The External flag for the alias IPs are described in the [Network Section of the Virtual Machine Template](https://docs.opennebula.io/6.0/management_and_operations/references/template.html#template-network-section):

> EXTERNAL	- It is used only on alias, it indicates if the alias is external to the VM or not. If it is set to “yes” it will call pre, post, clean and reconfigure actions. If it set to “no” or it is empty, it will just call reconfigure action.

It looks like the all alias IPs are threatened as _EXTERNAL_ when migrate or resume after undeploy.

**To Reproduce**
Instantiate a VM with a NIC network that have enabled spoofing filters
Add several "normal" IP aliases
Add several "external" IP aliases
_Inspect_: the created filtering rules on the host: Rules are created for the primary interface and for the external aliases
Migrate the VM
_Inspect_: the created filtering rules on the new host: Rules are created for all VM nics
Detach an external alias
_Inspect_: the filtering rules for the alias are cleared
Detach a "normal: alias
_Inspect_: the filtering rules are still defined
Undeploy the VM
_Inspect_: most of the filtering rules are cleared but the ones for the detached "normal" nic alias are still there (forgotten)

**Expected behavior**
The additional filtering rules should be created only for the _external_ alias IPs

**Details**
 - Affected Component: [Network]
 - Hypervisor: [KVM]
 - Version: [6.0+]

**Additional context**
It should be nice to have the EXTERNAL flag visible in the output of `onevm show $VMID` and in Sunstone...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
So this behavior:

> Detach a "normal: alias
> Inspect: the filtering rules are still defined
> Undeploy the VM
> Inspect: most of the filtering rules are cleared but the ones for the detached "normal" nic alias are still there (forgotten)

Is aligned with the definition of EXTERNAL (no clean actions are triggered).

However, We think this behavior is wrong and any rule set for an alias should be clean. We tend to think that actions should be triggered always for a NIC alias or not, and delegate the operations (or no-operations) to the network driver.

This allow the SG driver to clean iptables rules for alias while VLAN simply skip the alias interfaces (see [1] + [2])

So the goal for this issue is to actually clean any SG rule for alias NICs. right?

[1] https://github.com/OpenNebula/one/blob/master/src/vnm_mad/remotes/vxlan/post#L26
[2] https://github.com/OpenNebula/one/blob/master/src/vnm_mad/remotes/vxlan/vxlan_driver.rb#L32

**Comment by atodorov-storpool** [comment]
> So the goal for this issue is to actually clean any SG rule for alias NICs. right?

The documentation for the external alias is sparse so I am looking at the resulting rules (iptables, ipset) and trying to figure out what is the intended behaviour.

bug 1: On VM deploy and migrate rules are generated for all alias IPs just like they are tagged as "external".
bug 2: On hotplug detach only the rules for the "external" alias IPs are removed.
(missing feature?): on hotplug attach of a normal alias IP there are no rules updated.

With the proposed patch the "external" alias IPs are created, just like hotplug attach works. Also, bug 2 is naturally eliminated because there are no rules created for the "normal" alias IPs.

The missing feature is handled with addon-vnfilter from the time when the alias IPs were created...

So I think the goal of this issue is to separate the behaviour of the new feature (the "external" alias IPs) from the "normal" aliases.

Sidenote: Wondering why the external alias IPs need to be defined with so many rules, separated in dedicated chains, just like they are NIC interfaces? My understanding is that there should be a rule per VM NIC and all packet processing should be handled with a reduced, optimal set of chains within the VM NIC. Also, the use of the hashing(ipset) for optimal networking performance should be preferred...

**Comment by rsmontero** [comment]
I agree EXTERNAL is not consistently documented and probably confusing. So It is probably better to address the issue at a higher level

bug1. (related to your question also) We think this behavior is ok. Rules for ALIAS should be generated. After discussing it internally our idea is that NIC and NIC_ALIAS are separated entities at L3 so it make sense to manage them separately. For example I would like to restrict traffic on port 80 for the NIC IP but allow it for the ALIAS IP. This way an user can manage SG's decouple from the interfaces. To implement this we need to separate alias from nic traffic and hence the extra rules.

bug2. I think this is the real bug rules need to be cleaned.

So right now we plan to address this issue with:

* Consider deprecating EXTERNAL as it seems to be confusing and it functionality can be achieved by next point
* Deal NIC_ALIAS as a NIC in terms of driver operations.

**Comment by atodorov-storpool** [comment]
> So right now we plan to address this issue with:
> 
> Consider deprecating EXTERNAL as it seems to be confusing and it functionality can be achieved by next point
> Deal NIC_ALIAS as a NIC in terms of driver operations.

So, what do you think about separating the primary NIC to behave like ethernet only and any IP could be attached to them? Then there will be no Alias IPs thenb -  all IPs are attached to the Ethernet NIC? No matter are they v4 or v6. Something like just following the OSI model: the VM had Ethernet NIC(s) and could have or not IPs attached to them?

**Comment by rsmontero** [comment]
The current NIC_ALIAS model tries to follow that approach, built on the existing NIC model. I didn't try and probably will not work in all scenarios but you should be able to define a NIC of type Ethernet and then attach NIC_ALIAS of type IPv4 or IPV6...

**Comment by atodorov-storpool** [comment]
> The current NIC_ALIAS model tries to follow that approach, built on the existing NIC model. I didn't try and probably will not work in all scenarios but you should be able to define a NIC of type Ethernet and then attach NIC_ALIAS of type IPv4 or IPV6...

Confirm that it is working, but without SG because some rules are not created when the NIC had no IP assigned ;-)

**Comment by rdiaz-on** [comment]
This issue has been [fixed](https://github.com/OpenNebula/one/commit/7011820d987b42023942e9c1c7a18da45160768a).

**Comment by atodorov-storpool** [comment]
https://github.com/OpenNebula/one/commit/7011820d987b42023942e9c1c7a18da45160768a#diff-be558f5107eb5ef8a1e39f588c82ece420498cc25f81e61c13e9edfea0e77148R641
```ruby
        commands.add :ipset, "-q -D #{set} #{nic[:ip]} | true"
```
'-D'is a typo from iptables ;-) ? If the action is "delete" then _del_ should work....
Also adding _-exist_ option should reduce errors when called on a non-existent ipset. So the following line sounds better:

```ruby
        commands.add :ipset, "-q del -exist #{set} #{nic[:ip]} | true"
```
reference: https://ipset.netfilter.org/ipset.man.html

**Comment by rdiaz-on** [comment]
[Merged](https://github.com/OpenNebula/one/commit/62ddb9046e303b85ee217dd957953f8df97a7b35). Thanks @atodorov-storpool.
