### ISSUE TITLE
vSphere 7.0 erases snapshots on disk change

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5409]
**Description**

Adding or removing a disk automatically erases all snapshots. OpenNebula doesn't reflect this change.

**Expected behavior**

Do not allow changing disks if snapshots are present.

**Details**
 - Affected Component: vCenter drivers
 - Hypervisor: vSphere 
 - Version: 6.x
 - 
**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Also related, there is a problem with the rollback:

  * attach a disk triggers a disk copy
  * attach fails due to snapshot
  * tm_delete is called, but it also checks for snapshots, so it doesn't erase the disk

**Comment by al3xhh** [comment]
PRs to merge:

- [code](https://github.com/OpenNebula/one-ee/pull/1822)
- [docs](https://github.com/OpenNebula/docs/pull/2186)
