### ISSUE TITLE
Change elasticity parameters of a role on a service instance

### ISSUE THREAD

**Issue by rcampuz** [OpenNebula/one#5410]
**Description**
Allow to change the parameters of a service dynamically. Now it is possible to change values like elasticity parameters of a role (Max VMs, Min VMs, etc) in a service template, but that does not apply to a running instance.

**Use case**
Imagine you create the role of a service with autoscaling and setup the value of Max VMs with enough room for growing, but your load grows more than expected and you need to increase such limit. You can do it in the template, but you cannot do it in a running instance, without deploying a new one.

You can always force scaling manually, but if the traffic goes up and down (lower values during the night) then you should scale manually every day and you loose the automatic capabilities.

**Interface Changes**
It would require changes in all OneFlow interfaces, including SunStone, CLI and API.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @rcampuz,

Thanks for opening this feature request. The functionality you are asking for, was implemented as a part of this [issue](https://github.com/OpenNebula/one/issues/4912), please, let me know if you find something missing or any related bug.

Best,
Álex.

**Comment by rcampuz** [comment]
That's great, thank you! I was checking in the features before creating this one, but it is clear that I managed to miss it.
