### ISSUE TITLE
Add DockerHub private registry marketplace

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#5411]
**Description**
OpenNebula is currently integrated with DockerHub, the idea is to be able to have private registries available too.

**Use case**
Be able to have private registries marketplaces.

**Interface Changes**
New market driver will be added.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Needs Sunstone support.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1284)
- [Docs](https://github.com/OpenNebula/docs/pull/1878)
