### ISSUE TITLE
OneFlow CLI is broken when using username and password

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5413]
**Description**
When using OneFlow CLI command with the options `--user` and `--password` server fails to process it.

**To Reproduce**
Run any OneFlow command with those options.

**Expected behavior**
It should work and use the options.

**Details**
 - Affected Component: OneFlow
 - Version: 5.12, 6.0 and master.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vickmp** [comment]
PRs to merge:

- [Code](https://github.com/OpenNebula/one-ee/pull/1780)
- [Tests](https://github.com/OpenNebula/development/pull/1751)
- [Docs](https://github.com/OpenNebula/docs/pull/2154)
