### ISSUE TITLE
Sort user IDs in the VM tab's drop-down

### ISSUE THREAD

**Issue by ediosyncratic** [OpenNebula/one#5414]
**Description**
In the VM tab of the web UI, I'm shown all VMs by default.
There's a drop-down to select a user and display only that user's items.
Please sort those entries, or provide a site-config option to do so.

**Use case**
That drop-down's entries are currently unsorted.
This means I have to look closely at each entry in a long list until I find the one that's my user-ID in the system.
It would be *much* easier to find my entry if they were alphabetically sorted.
I could then just scan down the list to where the first letter of the alphabet is right and zoom in swiftly to the right entry.

**Interface Changes**
I have no idea how this would impact software interfaces.

**Additional Context**
The Qt project's continuous integration system is built on OpenNebula.
Internally, staff have access to the OpenNebula system to spawn debug machines when investigating platform-specific issues.
So I'm only a consumer of a service provided using OpenNebula, sending changes for integration and requesting debug VMs, that I need to be able to find in the system once they're provisioned and ready for use.
However, I would be able to persuade the admins to set a config option, if it exists (or is added).

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
adding a note for new sunstone interface, not implementing it in current Sunstone which will be deprecated soon
