### ISSUE TITLE
Error is raised for not setting values for optional custom attributes when instantiating a service

### ISSUE THREAD

**Issue by km4rcus** [OpenNebula/one#5415]
**Description**
When instantiating a service with optional custom attributes, the following error is raised when not setting any value:

`Every custom_attrs key must have its value defined at custom_attrs_value  `

**To Reproduce**
Create a service template with a custom attribute that is not mandatory and then instantiate the service.

**Expected behavior**
The service should be instantiated when not passing any value to an optional custom attribute

**Details**
 - Affected Component: Sunstone
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PRs to approve:
- Doc: https://github.com/OpenNebula/docs/pull/1875
- Code: https://github.com/OpenNebula/one-ee/pull/1277
