### ISSUE TITLE
RDP button in Sunstone not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5416]
**Description**
The RDP button within a service role desn't work

**To Reproduce**
Deploy a service and click on RDP button as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/33811723/120630807-76e00300-c467-11eb-9a0c-7bc951645c09.png)

**Expected behavior**
RDP connection must be started.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1270)
- [Docs](https://github.com/OpenNebula/docs/pull/1871)
