### ISSUE TITLE
Save_as button does nothing

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5417]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Clicking the save as button on the VM section does nothing.

![image](https://user-images.githubusercontent.com/33811723/120856959-34412800-c546-11eb-9f49-ccef2c7dfa30.png)

**To Reproduce**
- Poweroff a VM
- Click button

**Expected behavior**
Sunstone should issue a `one.vm.save` Call

**Details**
 - Version: 6.0

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/1276
- doc: OpenNebula/docs/pull/1874
