### ISSUE TITLE
Bug : Don't display remote connections options in Cloud View.

### ISSUE THREAD

**Issue by marimelon** [OpenNebula/one#5418]
**Description**
Don't show remote connection options in Cloud View when set to Japanese.

<img src="https://user-images.githubusercontent.com/29140293/120938426-9b7cf900-c74d-11eb-847f-a8e6a1b59866.jpg" width="400px">

**Additional context**

https://github.com/OpenNebula/one/blob/ff089908d18dfaa4dc0ad7e1208f02b733181a43/src/sunstone/public/app/tabs/provision-tab/vms/list.js#L337

fix : 
```
$('.dropdown-menu-css', context).toggle(state.str === Locale.tr("RUNNING"));
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
This is already fixed with this [commit](https://github.com/OpenNebula/one-ee/commit/c8cbe2016481a05a1d8b1b2442a941a1987acd73)
