### ISSUE TITLE
OneProvision GUI doesn't work in fedora34

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5419]
**Description**
After sign in to OneProvision GUI, FireEdge server fails to getting provisions/providers list with following error:
``WARNING: Nokogiri was built against libxml version 2.9.12, but has dynamically loaded 2.9.10``

**To Reproduce**
At Fedora v34, login to OneProvision GUI, then the error notifications should appear

**Expected behavior**
As it's a warning, it should not return an error with ``500 code``.
![image](https://user-images.githubusercontent.com/59608355/121001318-77d8a380-c78b-11eb-91f1-2be893ae8f57.png)

**Details**
 - Affected Component: FireEdge
 - Hypervisor: [e.g. KVM]
 - Version: development
 
**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- code: https://github.com/OpenNebula/one-ee/pull/1311
- docs: https://github.com/OpenNebula/docs/pull/1889
