### ISSUE TITLE
Real memory is not shown in Sunstone ESX information tab

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5420]
**Description**
When looking at ESX information under `Infrastructure/Hosts/<select cluster>/ESX`, the 'Real Memory' column is blank.

**To Reproduce**
Just check the tab.

**Expected behavior**
It should be filled with the information.

**Details**
 - Affected Component: Sunstone.
 - Version: 6.0.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1285)
- [Docs](https://github.com/OpenNebula/docs/pull/1881)
