### ISSUE TITLE
IPv6 alias not shown in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5425]
**Description**
When attaching an IPv6 NIC_ALIAS to a virtual machine, `undefined` string instead of the actual IPv6 address is shown in Sunstone.
 
**To Reproduce**
Attach an IPv6 NIC_ALIAS to a virtual machine.

**Expected behavior**
The actual IPv6 assigned to the NIC_ALIAS must be shown.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:

- one 5.12
  - [Code](https://github.com/OpenNebula/one-ee/pull/1303)
  - [Docs](https://github.com/OpenNebula/docs/pull/1886)
