### ISSUE TITLE
Advanced search in Sunstone is not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5426]
**Description**
The advanced search for VM/Services/Images/Templates is not working

**To Reproduce**
Steps to reproduce the behavior in Sunstone:
1. Go to VM or Service List.
2. Try to filter by owner/status (or use another filter).
3. See filtering is not working.

**Expected behavior**
Filters must work.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/1305
- doc: OpenNebula/docs/pull/1887
