### ISSUE TITLE
Sunstone version check fail

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5428]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**

Sometimes it doesn't correctly detect latest version

**To Reproduce**

OpenNebula EE 5.12.10 shows latest version to be 6.0.0.2 (which is CE) , while it should display latest EE version (6.0.2 as of today)

**Details**
 - Affected Component: Sunstone
 - Hypervisor: -
 - Version: 5.12.10

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/docs/pull/1903)
- [Docs 5.12](https://github.com/OpenNebula/docs/pull/1902)
- [Docs 6.0](https://github.com/OpenNebula/docs/pull/1903)
