### ISSUE TITLE
Allow custom mount options for LXC disks

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5429]
**Description**

There are two different things that can affect LXC disks mount options:

   - Image mapping options (use the default mount options)
   - LXC configuration attributes (i.e `lxc.rootfs.options`, `lxc.mount.entry`)

Both should be customizable in order to provide flexibility to cover different scenarios.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Also, it would be good to evaluate `idmap` option (`lxc.rootfs.options`) to replace `bindfs` for uid/gid mapping.

**Comment by dotkrnl** [comment]
bindfs is somehow unstable in my deployments and crashes containers frequently.  I would appreciate if idmap is used instead.  Thank you.
