### ISSUE TITLE
Add Encrypted Attributes to User Template

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#5431]
**Description**
Add encrypted attributes to the user template

**Use case**
Cipher sensitive information on user information.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
[PR src](https://github.com/OpenNebula/one-ee/pull/1574)
[PR tests](https://github.com/OpenNebula/development/pull/1669)
[PR docs](https://github.com/OpenNebula/docs/pull/2042)

**Comment by tinova** [comment]
needs oned.conf parameters added?

**Comment by paczerny** [comment]
As default there are no User encrypted attributes.
If user needs to encrypt something, he should add USER_ENCRYPTED_ATTR to oned.conf.

**Comment by tinova** [comment]
there should be the one associated with #5241, this needs to be present always (only in master as per the limitation of conf files in maintenance releases)

@FrederickBor please add it to oned.conf and check it works with Sunstone, then we can close the ticket.

**Comment by FrederickBor** [comment]
It's all working, here you have the PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1611
