### ISSUE TITLE
Can not change the network Custom Vars from the context of a VM

### ISSUE THREAD

**Issue by eXtrem0us** [OpenNebula/one#5433]
**Description**
I have defined two virtual networks on my OpenNebula instance, private and public, each of which have their own Gateways and DNS definitions.
So, I gonna create a VM that contains both of the networks. But as you know, it is not sensible to have two default gateways on a machine. Hence, a workaround about this issue is to create a VM and after that, remove the excess parts from context. (i.e. the DNS address from the public interface and Gateway from private interface)

**To Reproduce**
Following the above steps.

**Expected behavior**
The excess variables should be deleted. It seems everything is done successfully after I update the context. But right after that, when I see the custom vars again, nothing have been changed. It doesn't matter if the VM is on each of poweroff / running /hold state.

**Details**
 - Affected Component: Sunstone
 - Hypervisor:  KVM
 - Version: 6.0.1 and below

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Several issues:

  * Duplicated NICs and DISKs in context fail to render properly in updateconf dialog
  * Error in updateconf is not captured (or information not passed properly to the oned call)

probably a won't fix in RSunstone, need to be taken care of in FSunstone.
