### ISSUE TITLE
Disable autorefresh in Sunstone through FireEdge

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5434]
**Description**

Several issues with autorefresh feature: high impact on memory consumption, security considerations as well.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1326)

**Comment by sbbarragan** [comment]
PR to merge:
 - one: OpenNebula/one-ee/pull/1330
