### ISSUE TITLE
Unable to install opennebula-fireedge on Ubuntu 20.04

### ISSUE THREAD

**Issue by aded** [OpenNebula/one#5435]
**Description**
When installing opennebula-fireedge package, apt says the package has unmet dependencies (libnode64). If I manually install libnode64 before opennebula-fireedge, then apt says the package still has unmet dependencies (now is nodejs). If I manually try to install nodejs, apt says it will remove libnode64...

**To Reproduce**
sudo apt install opennebula-fireedge

**Expected behavior**
opennebula-fireedge installed, dependencies included.

**Details**
 - Affected Component: fireedge
 - Hypervisor: front end
 - Version: 6.0.0.2

**Additional context**
```
$ sudo apt install opennebula-fireedge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opennebula-fireedge : Depends: libnode64 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

After manually installing libnode64:
```
$ sudo apt install opennebula-fireedge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opennebula-fireedge : Depends: nodejs (>= 10)
E: Unable to correct problems, you have held broken packages.
```
When I try to manually install nodejs:
```
$ sudo apt install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libc-ares2
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  libnode64
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 1 to remove and 3 not upgraded.
Need to get 18.1 MB of archives.
After this operation, 70.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by aded** [comment]
I had to remove the NodeSource repository, this solved the issue.

**Comment by joelatrr** [comment]
Might want to reopen this as a documentation problem.  The single frontend steps have opennebula and nodesource repos referenced at various points

**Comment by tinova** [comment]
Hi! Thanks for reporting this.

I've checked and the documentation specifies the nodesource repo for ubuntu18 only: 

 https://docs.opennebula.io/6.0/installation_and_configuration/frontend_installation/install.html#step-3-add-3rd-party-repositories

Please let us know which places reference nodesource for other ubuntu versions.

**Comment by tinova** [comment]
closing until further feedback

**Comment by Comnenus** [comment]
I ran into this as well.  I see that the 6.0 guide specifies Ubuntu 18, but the new documentation (6.2) does not.
https://docs.opennebula.io/6.2/installation_and_configuration/frontend_installation/install.html

**Comment by tinova** [comment]
This has been fixed in 6.2 and master documentation, thanks for the heads up

**Comment by Githopp192** [comment]
btw - has got similar issue with CentOS Stream release 8:

 Problem: conflicting requests
  - nothing provides nodejs(abi10) >= 10.24 needed by opennebula-fireedge-6.2.0-1.ce.el8.x86_64

**Comment by tinova** [comment]
note that CentOS Stream is not supported

**Comment by dinkaz1** [comment]
This is the error i am getting trying to install opennebula-fireedge for opennebula 6.6.0 on ubuntu 22.10;
opennebula-fireedge : Depends: libnode72 (>= 12.22.9~dfsg) but it is not installable
                       Recommends: opennebula-guacd (= 6.6.0-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by tinova** [comment]
thanks for the feedback. please also note that [Ubuntu22.10 is currently not supported](https://docs.opennebula.io/6.6/intro_release_notes/release_notes/platform_notes.htm)

**Comment by aphorise** [comment]
> ... [Ubuntu22.10 is currently not supported](https://docs.opennebula.io/6.6/intro_release_notes/release_notes/platform_notes.htm)

Link is not working - does this also mean that Debian 12 Bookworm is not supported either?

I've tried manually installing all the libs that it's complaining about - but installing any version of node for `libnode72` or older .deb files still doesn't fix the issue. I'd imagine this would also be an issue in the case of host nodes but I havent been able to complete a front end installation yet.

```bash
uname -a && \
sudo apt-get -y install opennebula opennebula-sunstone opennebula-fireedge opennebula-gate opennebula-flow opennebula-provision
```
```
Linux user-linux 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opennebula-fireedge : Depends: libnode72 (>= 12.22.12~dfsg) but it is not installable
                       Recommends: opennebula-guacd (= 6.8.0-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by aphorise** [comment]
The correct link that outlines the OSs currently supported is:

https://docs.opennebula.io/6.8/intro_release_notes/release_notes/platform_notes.html

Debian 12 as well as latest versions as of 2023/24 do not seem to be supported.

**Comment by thefinisher2020** [comment]
Debian 12 is now supported  but yet this error still happening
