### ISSUE TITLE
Sunstone translates scheduled actions days wrongly

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5436]
**Description**
Scheduled actions days should be translated in the following way:

Monday: 1
Tuesday: 2
Wednesday: 3
Thursday: 4
Friday: 5
Saturday: 6
Sunday: 0

But, Sunstone is translating it:

Monday: 0
Tuesday: 1
Wednesday: 2
Thursday: 3
Friday: 4
Saturday: 5
Sunday: 6

**To Reproduce**
Add scheduled action with days.

**Expected behavior**
Should translate in the correct way.

**Details**
 - Affected Component: Sunstone
 - Version:5.12 and master.

**Additional context**
Scheduled actions documentation **must** be reviewed.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1327)
- [Docs](https://github.com/OpenNebula/docs/pull/1897)

**Comment by paczerny** [comment]
PRs to update sched action ranges description:
* [Code](https://github.com/OpenNebula/one-ee/pull/1328)
* [Docs](https://github.com/OpenNebula/docs/pull/1898)
