### ISSUE TITLE
PyONE strips white-spaces in VM attribute `TEMPLATE`

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5437]
**Description**
PyONE is stripping the white-spaces of `TEMPLATE` attribute when obtaining the VM info (`one.vm.info` call). If a user has VM with trailing spaces in `TEMPLATE/CONTEXT/FILES_DS`, when calling to `one.vm.updateconf` an exception is raised because the OpenNebula core doesn't allow to change/force the path set in `TEMPLATE/CONTEXT/FILES_DS` (it should be done using the `$FILE[IMAGE_ID=<ID>]` syntax in the same way that it is done for VM template).

**To Reproduce**
An instantiated VM has a `TEMPLATE/CONTEXT/FILES_DS` attribute with a trailing white-space like this:

```
<VM>
...
  <TEMPLATE>
  ...
   <CONTEXT>
    ...
    <FILES_DS><![CDATA[/var/lib/one//datastores/2/b776e106e914831ce019a680b2969340:'mycontext1.sh' ]]><
/FILES_DS>
    <IMAGE><![CDATA[Context]]></IMAGE>
    <INIT_SCRIPTS><![CDATA[mycontext1.sh]]></INIT_SCRIPTS>
    ...
   </CONTEXT>
  ...
  </TEMPLATE>
...
</VM>
```
The following `test.py` script call to `one.vm.info` and then call to `one.vm.updateconf` without any modification:

 ```
import pyone

one = pyone.OneServer("http://127.0.0.1:2633/RPC2", session="oneadmin:opennebula")

vm = one.vm.info(0, False)
print 'ALWAYS STRIPPED STRING: "%s"\n\n\n' % vm.TEMPLATE['CONTEXT']['FILES_DS']

conf = { 'template' : { key:value for (key, value) in vm.TEMPLATE.items() if key in ('OS', 'FEATURES', 'INPUT', 'GRAPHICS', 'RAW', 'CONTEXT', 'CPU_MODEL') } }

one.vm.updateconf(0, conf)
```

When running the script an exception is raised:

```
$ python test.py
ALWAYS STRIPPED STRING: "/var/lib/one//datastores/2/b776e106e914831ce019a680b2969340:'mycontext1.sh'"

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    one.vm.updateconf(0, conf)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/pyone/__init__.py", line 238, in _ServerProxy__request
    return self.__response(ret)
  File "/usr/local/lib/python2.7/dist-packages/pyone/__init__.py", line 290, in __response
    raise OneInternalException(message)
pyone.OneInternalException: [one.vm.updateconf] Error parsing: /var/lib/one//datastores/2/b776e106e914831
```

**Expected behavior**
PyONE must not strip white-spaces in VM attribute `TEMPLATE`.

**Details**
 - Affected Component: Python API
 - Hypervisor: KVM
 - Version: 5.12

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Fixed in [B #-: PyONE: don't strip whitespace in TEMPLATE (#1332)](https://github.com/OpenNebula/one/commit/e201188e064e4b7a35205a66cdf4c7c64ca243dd)
