### ISSUE TITLE
IP information is missing in some Sunstone views

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5438]
**Description**
The IP information does appear in some areas for the oneadmin account in admin view, but not everywhere in the Sunstone UI, but it doesn't appear for the user in cloud view 

**To Reproduce**
Add some extra IPs to the VM under `GUEST_IP_ADDRESSES`.

**Expected behavior**
All IPs should be shown.

**Details**
 - Affected Component: Sunstone.
 - Version: 5.12, 6.0 and master.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Dev and 6.0
  - [Code](https://github.com/OpenNebula/one-ee/pull/1336)
  - [Docs](https://github.com/OpenNebula/docs/pull/1906)
- 5.12
  - [Code](https://github.com/OpenNebula/one-ee/pull/1337)
  - [Docs](https://github.com/OpenNebula/docs/pull/1907)

**Comment by tinova** [comment]
needs testing

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Dev](https://github.com/OpenNebula/development/pull/1584)
