### ISSUE TITLE
Network issue when importing Wilds from vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5440]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When import a VM from vCenter 7 into OpenNebula 6, it works fine. But when try to import a second VM which is connected to the same network as the previously imported VM, you got the message: “Cannot get IP/MAC lease from virtual network”.
When importing the 1st VM, OpenNebula creates a virtual network. In the addresses you can see the IP and MAC of the failed VM, but the VM itself is missing.

**To Reproduce**
* import a VM from vCenter 7 into OpenNebula 6
* import a second VM which is connected to the same network as the previously imported

**Expected behavior**
VM should be imported correctly

**Details**
 - Affected Component: []
 - Hypervisor: [vCenter]
 - Version: [6.0, master]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
* [Doc](https://github.com/OpenNebula/docs/commit/c8da5b98ca147ad8805ff3993bdf0908f10dbb66)
