### ISSUE TITLE
Allow disabling fallocate for fs DS_MAD

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5441]
**Description**
Currently `fallocate -d` command is executed on every new image allocated in a `fs` datastore. The goal of this is to sparse the resulting files to save disk space and reduce copying times.

Two different behaviors have been found when the underlying filesystem doesn't support the `fallocate` call:

   - The command fails (this case is already controlled by the driver).
   - The command hung indefinitely.

As the advantages of calling `fallocate` usually don't apply to the file system which doesn't support the `fallocate` call it will be nice to allow disabling this call when necessary.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by harsxv** [comment]
Hello, how can I disable fallocate in my current ONE 6.2 ?
I facing this "command hung indefinitely." when try to store marketplace images to TrueNAS.

**Comment by rsmontero** [comment]
https://docs.opennebula.io/6.2/open_cluster_deployment/storage_setup/nas_ds.html?highlight=sparse
