### ISSUE TITLE
VM networks not working with CentOS 8.4+Advanced Virtualization

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5442]
**Description**
The Advanced Virtualization SIG for CentOS 8.4 provides libvirt 7.0.0 that have a different output when creating a domain from the cmd line with virsh.

**To Reproduce**
Setup OpenNebula KVM with CentOS8.4 + Advanced Virtualization
Instantiate a VM (with spoofing filters, think not important)
The VM and its networking is not working - no iptables rules are created

**Expected behavior**
The VM and its networking should work

**Details**
 - Affected Component: [VMM_MAD]
 - Hypervisor: [KVM]
 - Version: [5.12.10-EE]

**Additional context**
The root cause is that OpenNebula relies on a fuzzy/buggy parsing the output from an external program (libvirt/virsh) for data that is available in the deployment XML.

Patch pending to get the ID of the bug...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
Looks like the issue is fixed in 6.0.x but not in the current 5.12 LTS?

**Comment by rsmontero** [comment]
Thanks for the heads up, merged into one-5.12 ee
