### ISSUE TITLE
Migration failure deletes VM disk images on shared storage.

### ISSUE THREAD

**Issue by mgierlings** [OpenNebula/one#5444]
Affected Version: OpenNebula 6.0.0.2

A [bug in the kvm migrate script](https://github.com/OpenNebula/one/blob/e201188e064e4b7a35205a66cdf4c7c64ca243dd/src/vmm_mad/remotes/kvm/migrate#L240) deletes VM folders including disk images, when a shared datastore is used. In case the migration of a VM located on a shared datastore fails the migrate script deletes the VM folder on the target, which in this case is also the source folder. 

(This bug was found by @dfelsch)

**Comment by mgierlings** [comment]
Could you elaborate in which way the issue was resolved? I can not find any reference to a fix.

**Comment by rsmontero** [comment]
Yes it is resolved, It will be released in next community version. You can apply this patch meanwhile:


```
diff --git a/src/vmm_mad/remotes/kvm/migrate b/src/vmm_mad/remotes/kvm/migrate
index 0b7c1a9c0..3a59c5dd4 100755
--- a/src/vmm_mad/remotes/kvm/migrate
+++ b/src/vmm_mad/remotes/kvm/migrate
@@ -237,7 +237,9 @@ if [ $RC -ne 0 ]; then
         virsh --connect $QEMU_PROTOCOL://$DEST_HOST/system "${CLEAN_OP}" $DEPLOY_ID >/dev/null 2>&1
     done

-    ssh $DEST_HOST "rm -rf $VM_DIR"
+    if [ "$SHARED" != "YES" ]; then
+        ssh $DEST_HOST "rm -rf $VM_DIR"
+    fi

     error_message "Could not migrate $DEPLOY_ID to $DEST_HOST"
     exit $RC
```
