### ISSUE TITLE
CLI json/yaml output not wrapping single disk(...) by array

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5445]
**Description**
As part of implementation in https://github.com/OpenNebula/one/issues/4950 it was validated, that XSD is respected and entitites, which are expected to appear as multiple instances, must be represented as an array even if there is none or a single one. E.g., DISK, NIC, ...

A manual validation on 6.0.3 / CentOS 8 revels it's not true anymore:

Current output with single disk:

```
# onevm show 53 --json
...
      "DISK": {
        "ALLOW_ORPHANS": "YES",
        "CLONE": "YES",
...
```

and with hot-attached second disk:

```
# onevm show 53 --json
...
      "DISK": [
        {
          "ALLOW_ORPHANS": "YES",
...
```

\*\***Test must be extended to check these cases!!!****

**To Reproduce**
CLI show something with `--json` or `--yaml` and with single DISK/NIC.

**Expected behavior**
For none disk, output is like a (or missing)

```
"DISK": [ ],
```

For one disk, output is:

```
"DISK": [ { ... } ],
```

**Details**
 - Affected Component: CLI
 - Version: 6.0.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
for 6.0 + master
[fix](https://github.com/OpenNebula/one-ee/pull/1416)
[tests](https://github.com/OpenNebula/development/pull/1619)
