### ISSUE TITLE
onevm ssh doesn't respect CONTEXT/USERNAME

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5447]
**Description**

Name of custom contextualized user can be configured in 

```
CONTEXT=[
   USERNAME="non-root",
   ...
]
```

but, this is not respected by `onevm ssh` command.

Note:
- Yes, it can be manually set by second argument `onevm ssh ... non-root`, but user has to know it
- Exec function should be used instead here:
https://github.com/OpenNebula/one/blob/e201188e064e4b7a35205a66cdf4c7c64ca243dd/src/cli/onevm#L1601

**Expected behavior**
`onevm ssh $ID` works for custom non-root users.

**Details**
 - Affected Component: CLI
 - Version: 6.0.3dev
 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1451)
- [docs](https://github.com/OpenNebula/docs/pull/1966)
