### ISSUE TITLE
Snapshot remains after Recover: Delete-Recreate

### ISSUE THREAD

**Issue by eXtrem0us** [OpenNebula/one#5450]
**Description**
When you delete-recreate a VM, the previous snapshots remain.

**To Reproduce**
Take a snapshot from a VM
recover menu => delete-recreate

**Expected behavior**
The snapshot should be deleted from opennebula database.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2145)
* [doc](https://github.com/OpenNebula/docs/pull/2316)
