### ISSUE TITLE
Sunstone is not using oneflow_server variable

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5452]
**Description**
`oneflow_server`variable in `/etc/one/sunstone-server.conf` is not being used.

**To Reproduce**
Change this value to a different one from `localhost:2474`.

**Expected behavior**
Sunstone should use it.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12, 6.0 and master.

**Additional context**

Tried replacing this:

```
url = opts[:url] || ENV['ONEFLOW_URL'] || 'http://localhost:2474'
```

with that:

```
url = ENV['ONEFLOW_URL'] || 'http://localhost:2474'
```

And the ENV_VAR gets recognized correctly.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1437)
- [Docs 6.0](https://github.com/OpenNebula/docs/pull/1951)
- [Docs 5.12](https://github.com/OpenNebula/docs/pull/1952)
