### ISSUE TITLE
Piped and prematurely closed CLI output displays Ruby broken pipe

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5455]
**Description**

When using CLI with long enough output and piped to the other command, which closes the reading sonner than CLI writes the whole output, an annoying Ruby message `Broken pipe @ io_writev` displayed to the user. E.g.,

```
root@ubuntu1804-context-lxd-6-0-3-b65aa-802-0:~# onemarketapp list | head -3
  ID NAME                                            VERSION  SIZE STAT TYPE  REGTIME MARKET     ZONE
 542 hitch                                               1.0    2G  rdy  img 05/12/21 DockerHub     0
 541 almalinux                                           1.0    2G  rdy  img 06/28/21 DockerHub     0
Broken pipe @ io_writev - <STDOUT>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected behavior**
Broken pipe is not an error to bother the user with and shouldn't be shown.

**Details**
 - Affected Component: CLI
 - Version: 6.0.3dev

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1449)
- [docs](https://github.com/OpenNebula/docs/pull/1964)
