### ISSUE TITLE
k3s-cluster // Server role stuck in deploying status

### ISSUE THREAD

**Issue by htwalid** [OpenNebula/one#5459]
**Description**
k3s-cluster // server role stuck in deploying status.

During k3s cluster deployment, i have registered issue on server role which is stuck on deploying status, meanwhile the corresponding VM is running and in ready status.
I checked oneflow service logs which view exception as shown bellow in details.

**Details**
 - Affected Component: oneflow
 - Hypervisor: Firecracker
 - Version: 6.0.0.2

**Additional context**
Logs from oneflow services shown exceptions :

`oneadmin@node0:~$ journalctl -u opennebula-flow.service
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Sun 2021-07-11 20:54:21 MDT, end at Tue 2021-07-13 06:09:41 MDT. --
Jul 11 20:54:39 node0.testlab.cord-testdrive-pg0.apt.emulab.net logrotate[8847]: error: error renaming temp state file /var/lib/one/.logrotate.status.tmp
Jul 11 20:54:40 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[8875]: == Sinatra (v2.1.0) has taken the stage on 2474 for development with backup from Thin
Jul 12 05:43:45 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[8875]: == Sinatra has ended his set (crowd applauds)
Jul 12 05:43:45 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[8875]: 2021-07-11 20:54:40 -0600 Thin web server (v1.8.0 codename Possessed Pickle)
Jul 12 05:43:45 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[8875]: 2021-07-11 20:54:40 -0600 Maximum connections set to 1024
Jul 12 05:43:45 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[8875]: 2021-07-11 20:54:40 -0600 Listening on 0.0.0.0:2474, CTRL+C to stop
Jul 12 05:43:45 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[8875]: 2021-07-12 05:43:45 -0600 Stopping ...
Jul 12 05:45:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: == Sinatra (v2.1.0) has taken the stage on 2474 for development with backup from Thin
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: #<Thread:0x00005617d6edb1f8@/usr/lib/one/ruby/ActionManager.rb:198 run> terminated with exception (report_on_exception is true):
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: /usr/lib/one/oneflow/lib/EventManager.rb:439:in `check_nodes_event': undefined local variable or method `vm_state' for #<EventManager:0x00005617d68df1
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: Did you mean?  lcm_state
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]:                h_state
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]:         from /usr/lib/one/oneflow/lib/EventManager.rb:372:in `wait_report_ready'
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]:         from /usr/lib/one/oneflow/lib/EventManager.rb:107:in `wait_deploy_action'
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]:         from /usr/lib/one/ruby/ActionManager.rb:200:in `call'
Jul 12 22:23:27 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]:         from /usr/lib/one/ruby/ActionManager.rb:200:in `block in run_action'
Jul 13 05:53:10 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: == Sinatra has ended his set (crowd applauds)
Jul 13 05:53:10 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: 2021-07-12 05:45:27 -0600 Thin web server (v1.8.0 codename Possessed Pickle)
Jul 13 05:53:10 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: 2021-07-12 05:45:27 -0600 Maximum connections set to 1024
Jul 13 05:53:10 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: 2021-07-12 05:45:27 -0600 Listening on 0.0.0.0:2474, CTRL+C to stop
Jul 13 05:53:10 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[9614]: 2021-07-13 05:53:10 -0600 Stopping ...
Jul 13 05:53:11 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]: == Sinatra (v2.1.0) has taken the stage on 2474 for development with backup from Thin
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]: #<Thread:0x000055b19e30ac00@/usr/lib/one/ruby/ActionManager.rb:198 run> terminated with exception (report_on_exception is true):
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]: /usr/lib/one/oneflow/lib/EventManager.rb:439:in `check_nodes_event': undefined local variable or method `vm_state' for #<EventManager:0x000055b19e1ff
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]: Did you mean?  lcm_state
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:                h_state
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/oneflow/lib/EventManager.rb:372:in `wait_report_ready'
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/oneflow/lib/EventManager.rb:107:in `wait_deploy_action'
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/ruby/ActionManager.rb:200:in `call'
Jul 13 05:58:57 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/ruby/ActionManager.rb:200:in `block in run_action'
Jul 13 06:09:41 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]: #<Thread:0x000055b19e1fe370@/usr/lib/one/oneflow/lib/LifeCycleManager.rb:95 run> terminated with exception (report_on_exception is true):
Jul 13 06:09:41 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]: /usr/lib/one/oneflow/lib/ServiceAutoScaler.rb:46:in `block in start': undefined method `[]' for nil:NilClass (NoMethodError)
Jul 13 06:09:41 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/oneflow/lib/ServiceAutoScaler.rb:37:in `loop'
Jul 13 06:09:41 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/oneflow/lib/ServiceAutoScaler.rb:37:in `start'
Jul 13 06:09:41 node0.testlab.cord-testdrive-pg0.apt.emulab.net ruby[25248]:         from /usr/lib/one/oneflow/lib/LifeCycleManager.rb:99:in `block in initialize'`

VM instance status : 

`oneadmin@node0:~$ onevm list
  ID USER     GROUP    NAME                                                                                                     STAT  CPU     MEM HOST                                                                        TIME
  34 oneadmin oneadmin server_0_(service_22)                                                                                    runn    1      2G node3                                                                   0d 00h50`

Visualize service : 

`oneadmin@node0:~$ oneflow show 22
SERVICE 22 INFORMATION                                                          
ID                  : 22                  
NAME                : k3s-cluster         
USER                : oneadmin            
GROUP               : oneadmin            
STRATEGY            : straight            
SERVICE STATE       : DEPLOYING           
START TIME          : 07/13 05:54:54      

PERMISSIONS                                                                     
OWNER               : um-                 
GROUP               : ---                 
OTHER               : ---                 

ROLE server
ROLE STATE          : DEPLOYING           
VM TEMPLATE         : 3                   
CARDINALITY         : 1                   
MIN VMS             : 1                   
MAX VMS             : 1                   

NODES INFORMATION
 VM_ID NAME                     USER            GROUP          
    34 server_0_(service_22)    oneadmin        oneadmin

ROLE agent
ROLE STATE          : PENDING             
PARENTS             : server              
VM TEMPLATE         : 3                   
CARDINALITY         : 1                   
MIN VMS             : 1                   
MAX VMS             : 10                  

NODES INFORMATION
 VM_ID NAME                     USER            GROUP          

LOG MESSAGES                                                                    
07/13/21 05:54 [I] New state: DEPLOYING `

**Comment by al3xhh** [comment]
Hello @htwalid,

This error has been already fixed in [this](https://github.com/OpenNebula/one/commit/ea1f5eab39c52dd2bb98bc2a326ab4de20cde9c4) commit.

Closing this, open if needed.
