### ISSUE TITLE
EXTERNAL Alias deprecated but not for the VNF

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5462]
**Description**
EXTERNAL Alias was deprecated, remove also from Sunstone, tests, docs

**Expected behavior**
EXTERNAL alias are no longer in code/sunstone/docs/tests.

TASKS

- [x] Bring EXTERNAL attribute back for the VNF
- [x] Label it in Sunstone as "Skip network contextualizacion"
- [x] As hint "A virtual router can be configured to route SDNAT traffic for this NIC IP address"

**Additional context**
https://docs.opennebula.io/6.0/management_and_operations/references/template.html#template-network-section

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
External NIC_ALIAS is already removed, only references to external NIC are kept, because they are deprecated, but still used in some components. Closing.

**Comment by FrederickBor** [comment]
Related PR:
- Code: https://github.com/OpenNebula/one-ee/pull/2571
