### ISSUE TITLE
Implement mapping in OneProvision GUI

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5469]
**Description**

Sometimes the provider API needs an int, but this is not human readable. 

**Use case**

for instance, present Vultr instance OS as "Ubuntu 20.04" instead of an int

**Interface Changes**

This needs to be described in the yaml and properly understood by the front-end

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PR to merge **for OneProvision GUI**:
- one: OpenNebula/one-ee/pull/1382
