### ISSUE TITLE
Document Vultr bare metal provider

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5471]
**Description**

document it based on the virtual vultr provider

**Use case**
How are you going to use this new feature? Why do you need it?

**Interface Changes**
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.2 & master:

- [docs](https://github.com/OpenNebula/docs/pull/2157)
