### ISSUE TITLE
one.vn.update_ar method missing GLOBAL_PREFIX validation for non-slaac network

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#5472]
**Description**
Setting GLOBAL_PREFIX for address range makes whole virtual network inaccessible.

**To Reproduce**

```bash
onevnet create /dev/stdin <<\EOT
NAME   = "Test"
VN_MAD = "dummy"
BRIDGE = "dummy0"
AR=[
    TYPE = "IP6_STATIC",
    IP6  = "1::",
    PREFIX_LENGTH = "64",
    SIZE = "1"
]
EOT

ID=$(onevnet list -f NAME=Test -lID --no-header)

EDITOR="sed -i '1a GLOBAL_PREFIX=fuckoff'" onevnet updatear $ID 0

onevnet show $ID
# [one.vn.info] Error getting virtual network [625].
```

**Expected behavior**

* Message: `[one.vn.update_ar] Wrong format for IP6 global address prefix` on trying to specify unacceptable GLOBAL_PREFIX
* Тo broken vnet after all

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: 5.12.0.1 5.10.5

**Additional context**
recover:
```bash
EDITOR="sed -i '/GLOBAL_PREFIX/d'" onedb update-body vnet --id $ID
```

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Fix will be in release 6.0.4
