### ISSUE TITLE
Rename Packet provider to Equinix

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5474]
**Description**

OneProvision Packet provider should be renamed to Equinix.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1465)
- [packages](https://github.com/OpenNebula/packages/pull/254)
