### ISSUE TITLE
oneflow CLI command does not implement XML output

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5475]
**Description**

But it is included as an output option

```
## OPTIONS
     -j, --json                Show the resource in JSON format
     -x, --xml                 Show the resource in xml format
```

**Expected behavior**

either implement XML output or remove the -x flag

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1448)
- [docs](https://github.com/OpenNebula/docs/pull/1962)

The flag has been removed as all the API is written to use JSON.
