### ISSUE TITLE
Wrong logic in scheduled actions from Sunstone

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5476]
**Description**
Following the OpenNebula [documentation](https://docs.opennebula.io/6.1/management_and_operations/vm_management/vm_instances.html#periodic-punctual-actions):
- weekly: days separate with commas between **0 (Sunday) and 6 (Saturday). [0,6]**

However, from Sunstone the logic is between **0 (Monday) and 6 (Sunday)**
![image](https://user-images.githubusercontent.com/59608355/127020977-01f01f90-24eb-4d56-b952-c3bc928281c9.png)

**To Reproduce**
- Instantiate a VM. Then, following the example from documentation:
```shell
$ onevm suspend <id> --schedule "09/20" --weekly "1,5" --end 5
VM <id>: suspend scheduled at 2018-09-20 00:00:00 +0200
```

Finally go to Sunstone, and VM detail view > Actions tab.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: development

**Additional context**
Update compatibility guide.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
I think this was already solved in #5436, should be in 6.0.3 release

**Comment by tinova** [comment]
There are other parts of the code (check app/utils/humanize-js L65) where this applies, leaving open for the time being.

**Comment by FrederickBor** [comment]
For master, this problem has been fixed with new schedule actions [pull request](https://github.com/OpenNebula/one-ee/pull/1390).

@tinova PR to be approved for one-6.0:
- [one](https://github.com/OpenNebula/one-ee/pull/1411)
- [docs](https://github.com/OpenNebula/docs/pull/1937)
