### ISSUE TITLE
[GOCA] fix template Del method

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/one#5477]
**Description**

In Goca, there is some code around dynamic template management.
There is a problem in the method `Del` that give the capability to delete elements from a template or a vector.
When there is a sequence of the same item (consecutive), some items remains.
A simplified illustration of the bug with integers: https://play.golang.org/p/QjuX-l5wUUn

**To Reproduce**

Delete a sequence of template elements with the same name from a dynamic template (goca)

**Expected behavior**
The deleted item shouldn't appear anymore in the list of elements.

Here is a way to fix it: https://play.golang.org/p/N2YGfz5mkhA

**Details**
 - Affected Component: goca

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by treywelsh** [comment]
PR: #5480

**Comment by rsmontero** [comment]
merged for next release. THANKS!!!!!!
