### ISSUE TITLE
Advanced search in Sunstone not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5478]
**Description**
Filters are not working as expected in Services

**To Reproduce**
1) Go to Services
2) Open advanced search
3) Try to filter by "Owner"

The filter does not work for "Owner".

**Expected behavior**
Filter should work for all filter criteria.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: OpenNebula/one-ee/pull/1381
- doc: OpenNebula/docs/pull/1926
