### ISSUE TITLE
Show warning message in Sunstone when scheduled action fails

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5479]
**Description**
Currently if some driver action fails a warning message is shown in Sunstone. The same behavior could apply to scheduled actions.

**Use case**
User can easily know if the action has failed.

**Interface Changes**
Sunstone.

**Additional Context**
The error when the action fails is stored under `SCHEDULED_ACTION/MESSAGE`.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1435)
- [Docs](https://github.com/OpenNebula/docs/pull/1948)
