### ISSUE TITLE
Unable to instantiate a VM containing disk with resize option

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5481]
**Description**
A VM template with the SIZE attribute will fail when instantiated on Sunstone:

```
TEMPLATE CONTENTS
CONTEXT=[
  NETWORK="YES",
  SET_HOSTNAME="$NAME",
  SSH_PUBLIC_KEY="$USER[SSH_PUBLIC_KEY]" ]
CPU="1"
DISK=[
  IMAGE_ID="5" ]
GRAPHICS=[
  LISTEN="0.0.0.0",
  TYPE="vnc" ]
LXC_UNPRIVILEGED="FALSE"
MEMORY="768"
SCHED_REQUIREMENTS="HYPERVISOR=\"lx*\""
```

image 5 is 1G

```
root@minione-ee:~# oneimage show 5 | grep SIZE
SIZE           : 1024M
```

**To Reproduce**

Instantiate a template as described.

![image](https://user-images.githubusercontent.com/33811723/127664255-6e56a146-b7b3-4861-a4b9-6e1a2571adfe.png)

Browser console shows

```
instantiate.js:311 Uncaught TypeError: original_tmpl.TEMPLATE.DISK.find is not a function
    at instantiate.js:311
    at Array.forEach (<anonymous>)
    at String.<anonymous> (instantiate.js:309)
    at Function.each (jquery.js:365)
    at FormPanel._submitWizard [as submitWizard] (instantiate.js:290)
    at HTMLFormElement.<anonymous> (form-panel.js:72)
    at HTMLFormElement.dispatch (jquery.js:4737)
    at HTMLFormElement.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7807)
    at HTMLFormElement.<anonymous> (jquery.js:7875)
```

**Expected behavior**
VM instantiates with resize option

**Details**
 - Version: 6.0.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- [Code] https://github.com/OpenNebula/one-ee/pull/1407
- [Docs] https://github.com/OpenNebula/docs/pull/1936
