### ISSUE TITLE
Option to append Context Values to the VM, with the command 'onevm updateconf'

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/one#5482]
**Description**
It is not possible to import only the new VM Context Values with the command 'updateconf' without losing all the existing Context Values.

If we use the command 'updateconf' to import a file that contains only couple of variables, all the existing Context Variables will be deleted.

The only way to not lose everything is to first extract all the existing Context, add our new values to the Context file, and re-import everything.

**To Reproduce**
1. Create a varfile that contains only couple of variables :
```
# /tmp/context_varfile.txt
CONTEXT = [
  TEST_VARIABLE="test_value"
]
```

2. Run the `updateconf` command against a VM ID.
```
onevm updateconf --user username --password token --endpoint "https://endpoint.net" 100 /tmp/context_varfile.txt
```

3. Check on the VM, all the Context Variables are gone, and only the new variable is present

**Expected behavior**
It would be great to have a `--append` option that allow to append the imported Context Data to the existing Context Data, and also update the values if there is already a variable with an identical name.

**Details**
 - Affected Component: CLI
 - Hypervisor: KVM
 - Version: 6.0.0.2

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Th0masL** [comment]
I guess there could be some similar thing as with the `onevm update` command, that is already supporting the `append` option:

https://github.com/OpenNebula/one/blob/master/src/cli/onevm#L378-L386
```
           # Overview of onevm update function :
            if options[:append]
                str = OpenNebulaHelper
                      .append_template(args[0], obj, args[1], 'USER_TEMPLATE')
            else
                str = OpenNebulaHelper
                      .update_template(args[0], obj, args[1], 'USER_TEMPLATE')
            end
```

Something similar would need to be inserted around :
https://github.com/OpenNebula/one/blob/master/src/cli/onevm#L1318-L1335

**Comment by paczerny** [comment]
Release 6.2
