### ISSUE TITLE
OS and GRAPHICS values are deleted when updating VM CONTEXT with 'onevm updateconf'

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/one#5484]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
I have been testing updating the `CONTEXT` values on a VM from the CLI command `onevm updateconf`, and I have noticed that the `OS` and `GRAPHICS` blocks are being deleted when I update the `CONTEXT`.

**To Reproduce**
1. create a template file that only contains a `CONTEXT` block
```
# cat /tmp/context_varfile.txt
CONTEXT = [
  CONTEXT="true",
  DISK_ID="1",
  ETH0_CONTEXT_FORCE_IPV4="",
  ETH0_DNS="8.8.8.8",
  ETH0_EXTERNAL="",
  ETH0_GATEWAY="192.168.0.254",
  ETH0_GATEWAY6="",
  ETH0_IP="192.168.0.10",
  ETH0_MAC="02:00:ab:9b:5b:ab",
  ETH0_MASK="255.255.255.0",
  IMAGE="Context",
  NETWORK="YES",
  ONEGATE_ENDPOINT="http://192.168.0.1:5030",
  SET_HOSTNAME="server1",
  TARGET="hda",
  TEST_VAR="test_value",
  TOKEN="YES",
  VMID="100"
]
```

2. Use `onevm updateconf` to deploy this template to a VM
```
onevm updateconf --user username --password token --endpoint "https://endpoint.net" 100 /tmp/context_varfile.txt
```
3. Check on the VM, and you will see that the `OS` and `GRAPHICS` values are gone

**Expected behavior**
I'm expecting only the `CONTEXT` values of the VM to be updated, and the `OS` and `GRAPHICS` values to remains untouched.

4. The only way to not delete the `OS` and `GRAPHICS` block is to inject it at the same time as `CONTEXT` :
```
# cat /tmp/context_varfile_updated.txt
CONTEXT = [
  CONTEXT="true",
  DISK_ID="1",
  ETH0_CONTEXT_FORCE_IPV4="",
  ETH0_DNS="8.8.8.8",
  ETH0_EXTERNAL="",
  ETH0_GATEWAY="192.168.0.254",
  ETH0_IP="192.168.0.10",
  ETH0_MAC="02:00:ab:9b:5b:ab",
  ETH0_MASK="255.255.255.0",
  IMAGE="Context",
  NETWORK="YES",
  ONEGATE_ENDPOINT="http://192.168.0.1:5030",
  SET_HOSTNAME="server1",
  TARGET="hda",
  TEST_VAR="test_value",
  TOKEN="YES",
  VMID="100"
]
OS = [
  ARCH="x86_64",
  UUID="04100810-7316-4239-85ea-13a232973fa0"
]
GRAPHICS = [
  LISTEN="0.0.0.0",
  PORT="5901",
  TYPE="VNC"
]
```
**Details**
 - Affected Component: CLI (I guess)
 - Hypervisor: KVM
 - Version: 6.0.0.2

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Will be solved by `--append` flag for `onevm updateconf` command. See #5482
