### ISSUE TITLE
User password cannot start with space using LDAP authentication

### ISSUE THREAD

**Issue by cbr46** [OpenNebula/one#5487]
**Description**
When trying to log in to sunstone using LDAP authentication the login process fails with "Invalid username or password" if user passwords start with a space char. 
The option :encode_user_password: is set to true. 
Spaces within the password are encoded correctly.

**To Reproduce**
1. Configure LDAP authentication
2. Set user password
3. Try to log in

**Expected behavior**
Passwords with leading spaces can be used to log into sunstone.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.0.2

**Additional context**
Tested with Active Directory as LDAP server

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
* code: https://github.com/OpenNebula/one/issues/5487
* doc: https://github.com/OpenNebula/docs/commit/873ec9df640cdc5a37797cc99a27aa52a7d075f6
