### ISSUE TITLE
LDAP User DN containing special chars leads to login failure

### ISSUE THREAD

**Issue by cbr46** [OpenNebula/one#5488]
**Description**
Users whose DN contains special chars (e.g. "(" or "," ) fail to log into sunstone.
This only occurs when using the :group: config option since apparently only then the member filter is used (see below).
After removing all special characters from the DN the user can login again.

**To Reproduce**
1. Set :group: option in /etc/one/auth/ldap_auth.conf
2. Create user with special chars in Active Directory and add it to the group 
3. Try to log into sunstone with user

**Expected behavior**
Login should be possible without restrictions

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.0.2

**Additional context**
/var/log/one/oned.log
I added some additional debug output

Trying LDAP server server 1
CN=testgroup_1,OU=Groups,OU=TEST,DC=example,DC=com
member:
(member=CN=Test\, User1,OU=Users,OU=TEST,DC=example,DC=com)
Exception raised with LDAP server 1: Invalid filter syntax.
Could not authenticate user testuser1@example.com
_authenticate: -
Stopping
Auth Error:
Req:5440 UID:-1 IP:127.0.0.1 one.user.info invoked , -1, false
Req:5440 UID:- one.user.info result FAILURE [one.user.info] User couldn't be authenticated, aborting call.

Possible workaround:
/usr/lib/one/ruby/opennebula/ldap_auth.rb: Line 164
`username = Net::LDAP::Filter.escape(user.first.force_encoding(Encoding::UTF_8))`

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Thanks fixed for next release
