### ISSUE TITLE
Sunstone not showing report ready because extra space

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5490]
**Description**
If OneGate reports ready with extra space `READY= YES`, Sunstone won't show the tick in the view when the VM is ready.

**To Reproduce**
Add `READY= YES` to the `USER_TEMPLATE`.

**Expected behavior**
Sunstone should show a tick next to the VM name when it is ready.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12, 6.0 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
[master](https://github.com/OpenNebula/one-ee/pull/1403)
[one-6.0](https://github.com/OpenNebula/one-ee/pull/1404)
[one-5.12](https://github.com/OpenNebula/one-ee/pull/1402)
