### ISSUE TITLE
mistake in oneimage cli help-text 

### ISSUE THREAD

**Issue by rolanddenhollander** [OpenNebula/one#5493]
In the man-page or help-info for the oneiamge CLI tool, there is a misplaced bracket. 

            oneimage create -d 1 --name ubuntu --path /tmp/ubuntu.qcow2 \
                            --prefix sd --type OS --driver qcow2 \
                            --description "A OS plain installation \
                            --persistent"

Doesnt this create an image with the name "A OS plain installation \--persistent"
This should probably be: 

            oneimage create -d 1 --name ubuntu --path /tmp/ubuntu.qcow2 \
                            --prefix sd --type OS --driver qcow2 \
                            **--description "A OS plain installation" \
                            --persistent**

**Details**
 - oneimage help-page text
 - Hypervisor:KVM
 - Version: 5.12 

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Fix Thanks!
