### ISSUE TITLE
No information regarding VMs and host states

### ISSUE THREAD

**Issue by modir** [OpenNebula/one#5495]
In the documentation about [host states ](https://docs.opennebula.io/6.0/management_and_operations/host_cluster_management/hosts.html#host-states) it is not mentioned what is happening to the VMs running in this host, it only mentions if I can deploy new VMs there. E.g if I put a host in offline, will the VMs move away automatically? What If I put it back online. Will they automatically move back right after putting the host to on or will it take several hours / days?

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
`host disable` - running VMs are not modified, disable new deployments by Scheduler, manual deployment is still allowed, monitor enabled
`host offline` - running VMs are not modified, disable new deployments by Scheduler or manual, monitor disabled
`host flush` - disable the host and migrate all running VMs
`host enable` - enable monitor, enable new deployments by Scheduler. This doesn't mean old VMs will automatically return
