### ISSUE TITLE
CLI onevm ssh doesn't quote arguments passed to ssh

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5508]
**Description**

Subcommand `onevm ssh` doesn't quote arguments passed to the `ssh` properly. E.g.,

```
$ onevm ssh 1572 --cmd 'hostname; hostname'
priv150-100.testing
centos8-context-kvm-6-1-80-jnks859-859-0.test
```

Safer type of execution should be used
https://stackoverflow.com/questions/4650636/forming-sanitary-shell-commands-or-system-calls-in-ruby

**Details**
 - Affected Component: CLI
 - Version: 6.0.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1446)
- [docs](https://github.com/OpenNebula/docs/pull/1959)
