### ISSUE TITLE
Memory units change not taken into account when instantiating VM Template

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5509]
**Description**
When the memory units are changed in the VM Template dialog (e.g from MB to GB) after setting the value, the change is not taken into account.

**To Reproduce**

   - Open the VM Template instantiate dialog.
   - Change the memory value (e.g to `1`).
   - Change the units (e.g from MB to GB)
   - Instantiate the VM Template
   - Check VM memory:
      - Value: `<MEMORY><![CDATA[1]]></MEMORY>`
      - Expected value:  `<MEMORY><![CDATA[1024]]></MEMORY>`

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.3

**Additional context**
Ensure this failure is not affecting any other field.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [code](https://github.com/OpenNebula/one-ee/pull/1419)
- [docs](https://github.com/OpenNebula/docs/pull/1940)

**Comment by DarkSunOne** [comment]
The problem is still not solved with that commit

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1463)

**Comment by OpenNebulaSupport** [comment]
Needs to be back ported to 5.12 version.

**Comment by tinova** [comment]
backported in 7eb22c25ffde849ec5632a1dc5541d6dba1e160a
