### ISSUE TITLE
Make default path of output file in `onedb backup` command configurable

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5515]
**Description**
By default, the output file of `onedb backup` has a fixed path by default. It can be useful setting the that default path through configuration settings.

**Use case**
Users that want to change the default path for DB backup output files.

**Interface Changes**
No changes.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
This is already supported, the command `onedb backup` accepts an argument:

```
$ onedb backup -h
## USAGE
backup [<output_file>]
        Dumps the DB to a file specified in the argument
        valid options: federated, force

```

So it can be run in the following way:

```
$ onedb backup /tmp/test     
Sqlite database backup stored in /tmp/test
Use 'onedb restore' to restore the DB.
```

Closing.
