### ISSUE TITLE
Subnet mask defined in vCenter is incorrectly imported into OpenNebula

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5519]
/!\ To report a **security issue** please follow this procedure:
It is necessary that when importing a Wild from vCenter to OpenNebula, the parameters associated with the NIC such as Subnet Mask, DNS and all the parameters that define a Network must be imported correctly so that the Network and Address Ranges are generated correctly .

**Description**
If a Network is created in vCenter whose subnet mask is 255.0.0.0 when imported into OpenNebula, 255.255.255.0 is imported.

**To Reproduce**
* Create a network in vCenter with subnet mask 255.0.0.0
* Assign that network to a virtual machine
* Import that Wild to OpenNebula
* The subnet mask is 255.255.255.0

**Expected behavior**
The subnet mask should be 255.0.0.0

**Details**
 - Affected Component: [Network]
 - Hypervisor: [vCenter]
 - Version: [master, 6.0]

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
We have checked with vmware tools installed and there is no way to retrieve gateway and DNS information. We are going to close the issue, it can be reopened any time in case there is a use case that needs this information.
