### ISSUE TITLE
Snapshots space are not taken into account for system DS Quota.

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5524]
**Description**
System DS Quota can be defined in order to define a limit for the amount of disk space consumed at system DSs.

When creating a new snapshot for a VM (`one.vm.snapshotcreate`), the system DS Quota is not updated, hence the space consumed by the snapshot is not taken into account.

**Expected behavior**
The system DS Quota, should take into account everything consuming disk space for a VM.

**Details**
 - Affected Component: Quotas
 - Version: 6.0.3

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs to merge:
* src
* [tests](https://github.com/OpenNebula/development/pull/1688)
* [docs](https://github.com/OpenNebula/docs/pull/2070)
