### ISSUE TITLE
AR size update for VNTemplates fails in Sunstone.

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5525]
**Description**
The following error is shown in the browser console when trying to update the size of an AR of a Virtual Network Template:

```
foundation.js:294 Uncaught ReferenceError: We're sorry, 'close' is not an available method for this element.
    at jQuery.fn.init.foundation (foundation.js:294)
    at Dialog._hide [as hide] (dialog.js:61)
    at callback (actions.js:66)
    at Object.success (action.js:58)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at done (jquery.js:8757)
    at XMLHttpRequest.<anonymous> (jquery.js:9123)
```

**To Reproduce**
- Create a Virtual Network Template with an AR.
- Update Virtual Network Template's AR size.

**Expected behavior**
The AR size is properly udated.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.3

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1459)
- [Docs](https://github.com/OpenNebula/docs/pull/1971)

**Comment by tinova** [comment]
needs testing

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- https://github.com/OpenNebula/development/pull/1672
