### ISSUE TITLE
VM template NIC/GUEST_MTU dropped by Sunstone Wizard

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5527]
**Description**

Sunstone VM template wizard drops from VM template `GUEST_MTU` configured on the NIC.

**To Reproduce**

E.g., having following in the VM template snippet:

```
...
NIC = [
  GUEST_MTU = "1499",
  NETWORK = "service" ]
```

after updating the VM template via Sunstone wizard, the `GUEST_MTU` disappears:

```
...
NIC = [
  NETWORK = "service" ]
```

**Expected behavior**
`NIC/GUEST_MTU` is preserved.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.3

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1438)
- [Docs](https://github.com/OpenNebula/docs/pull/1953)
