### ISSUE TITLE
Safeguard terminate function with more information

### ISSUE THREAD

**Issue by rene-bayer** [OpenNebula/one#5528]
**Description**
To prevent an accidental deletion/termination of multiple selected VM's, 
it would be helpful to list the VM's which are going to be terminated in the confirmation modal.

**Use case**
It could be avoided that an co-admin, or admin remove vm's which shouldn't be deleted.
Especially when marking multiple vm's for removal

**Interface Changes**
![image](https://user-images.githubusercontent.com/11734245/131807237-f52cdffb-0dc2-4218-96c8-abce738a451e.png)

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
duplicated #3985
