### ISSUE TITLE
Apply network QoS without re-attaching the interface

### ISSUE THREAD

**Issue by rene-bayer** [OpenNebula/one#5529]
**Description**
If an administrator changes the QoS settings of a network interfaces, the changes should be applied without the need of reattach the whole interface

**Use case**
For an hosting provider, it can and will be necessary to change the allowed bandwidth for an vm.
Its pretty not usable, to remove and attach the network interface and cause a downtime for that.

Further there may be installations without the contextd tools. 
So for that you would need to poweroff the complete vm!

**Interface Changes**
From user sight, there's no need of changes in the gui ... the changes should be applied online

**Additional Context**
NaN

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Sunstone Testing - QA
- [ ] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by DarkSunOne** [comment]
Is there a possibility of a workaround?
For example, to set new values in the SunStone, and execute the corresponding libvirtd commands manually?
(See: [https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_administration_guide/sub-sect-domain_commands-setting_network_interface_bandwidth_parameters](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_administration_guide/sub-sect-domain_commands-setting_network_interface_bandwidth_parameters))

Will the changes persist a poweroff and start?
Would a poweroff and start be enough, or must it really be a detach/attach?

**Comment by tinova** [comment]
needs Sunstone tests
