### ISSUE TITLE
OpenNebula deletes virtual machine disk on migration failure

### ISSUE THREAD

**Issue by DarkSunOne** [OpenNebula/one#5531]
**Description**
When there's an (storage based?) migration error, OpenNebula deletes the complete folder within the system datastore

**To Reproduce**

- Create a Cluster with at least 2 nodes
- Provide a shared filesystem (NFS, Cephfs, glusterfs, etc.)
- Define a new system store (TM_MAD="qcow2" - this also happens with shared if theres an error)
- Also use this shared fs for the image store
- Download a new template from the app store and deploy a virtual machine on node1
- Prepare a migration error on node2 (for example: delete the qcow2 backing file, or unmount the system store)
- Live migrate the deployed vm from node1 to faulty node2
- the migration will fail and the disk is deleted in the datastore (on node1)

**Expected behavior**
Just throw an error **and dont delete anything, no matter whats the error**

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Storage: shared fs - TM_MAD="qcow2"
 - Version: 6.0.2

**Additional context**
NaN

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
This should be fixed in OpenNebula 6.0.3 (https://github.com/OpenNebula/one/issues/5444)

**Comment by DarkSunOne** [comment]
Search function could save lives ... sry and thank you
