### ISSUE TITLE
Services in WARNING state do not go back to RUNNING when the VMs are DONE

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5532]
/**Description**
when a service goes to WARNING state, and the VM that triggered the condition reaches the DONE state, oneflow detects the VM, removes it from the role VM list and updates the cardinality. But doesn't update the role and service status to RUNNING every VM remaining belonging to the service is RUNNING.

**To Reproduce**
- create a service
- put a running VM on POWEROFF using the hypervisor utilities
- wait for opennebula monitoring to detect the VM in POWEROFF when the VM is supposed to be RUNNING
- when oneflow puts the service in WARNING, remove the VM and make sure the VM gets the DONE state.
- service will be updated and stuck in WARNING

**Expected behavior**
oneflow should detect that every VM belonging to the service is on RUNNING state and should update the service status back to RUNNING.

**Details**
 - Version: 5.12, 6.0

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.2 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/1782)
- [docs](https://github.com/OpenNebula/docs/pull/2155)
