### ISSUE TITLE
CLI onevm ssh doesn't check VM running state

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5533]
**Description**

Subcommand `onevm ssh` doesn't check if **requested VM is still running or not**. It's able to reuse IP of already terminated VM and try to login there, if there is already different VM under same IP, obviously it's source of a confusions. 

See

```
$ onevm list
   ID USER     GROUP    NAME                            STAT  CPU     MEM HOST                        TIME
17738 oneadmin oneadmin base_Ubuntu 21.04_gpb4zg69-1773 runn  0.1    768M centos8-context-kvm-6   0d 00h01
```

but, using previous VM ID, but IP is already allocated by different VM:

```
$ onevm ssh 17737
Welcome to Ubuntu 21.04 (GNU/Linux 5.11.0-31-generic x86_64)
...
```

**Details**
 - Affected Component: CLI
 - Version: 6.0.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/1445)
- [docs](https://github.com/OpenNebula/docs/pull/1958)
- [tests](https://github.com/OpenNebula/development/pull/1632)
