### ISSUE TITLE
Add network interface breaks hover hints

### ISSUE THREAD

**Issue by rene-bayer** [OpenNebula/one#5534]
**Description**
As soon as you add an network interface to the vm deploy dialog, all the hints (hover the "?") aren't working anymore

**To Reproduce**
- Start deploying an VM
- Trigger the mouse hover at the "?"
- add an network interface
- Trigger the mouse hover at the "?"

**Expected behavior**
Correct hint shown

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0.2

**Additional context**
![image](https://user-images.githubusercontent.com/11734245/132676990-2bc97018-12a6-4b8f-b74b-39d2841cdec3.png)

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1669
- Docs: https://github.com/OpenNebula/docs/pull/2082
