### ISSUE TITLE
Remove GATEWAY6 from Context

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#5537]
**Description**
Make oned to not generate GATEWAY6 variable, the rest of the components should be already adapted to this change.

**Use case**
Consistent IPv6 naming.

**Interface Changes**
None, already done in 6.4

**Additional Context**
NaN

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
PR for the canonical/cloud-init#1045
