### ISSUE TITLE
Add option to keep MAC on imported Wild VM NICs

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5538]
**Description**

As OpenNebula links IP and MAC, importing a Wild VM may result in a change of MAC address on the NICs

**Use case**

This is useful to prevent MAC changes that may upset guest OS software.

**Interface Changes**

To be included in vcenterrc

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Added in 6e0ae88fd755a00e293925d2b599fd7e164e5d36
- [ ] missing doc
- [ ] missing 6.0 backport

**Comment by atodorov-storpool** [comment]
IMO IP and MAC should be decoupled entirely. With the availability of alias IPs it should be relatively easy?

**Comment by carloshm91** [comment]
[DOC]
* https://github.com/OpenNebula/docs/pull/1972
