### ISSUE TITLE
nginx-proxy don't work well with opennebula 6.02 - VNC does not open

### ISSUE THREAD

**Issue by chicco64** [OpenNebula/one#5541]
Hi,
i installed opennebula-mini with bash script on debian10;
I would also like to activate the https functionality through proxy-nginx;
I have a wildcard ssl certificate for my domain, and it works perfectly on other nginx-proxies.
The functionality of opennebula would appear to be respected except the error message below "fireedge public endpoint is not working" and the vnc panel not opening.

/etc/one/sunstone-server.conf

:vnc_proxy_port: 29876
:vnc_proxy_support_wss: only
:vnc_proxy_cert: /etc/ssl/private/example.com.crt
:vnc_proxy_key: /etc/ssl/private/example.com.key
:vnc_proxy_ipv6: false
:vnc_request_password: false
:allow_vnc_federation: no

/etc/nginx/sites-enabled/default

server {
    listen                        8443 ssl;
    server_name             test.example.com;
  
location / {
    proxy_pass      http://127.0.0.1:9869;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        host    $host;
    proxy_set_header        X-Forwarded-Server      $host;
    proxy_read_timeout 600s;
    proxy_connect_timeout 600s;
}
location /websockify {
    proxy_pass http://127.0.0.1:29876;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    add_header Access-Control-Allow-Origin *;
}
}
error_page 497 https://$host$request_uri;
ssl_certificate /etc/ssl/private/example.com.crt;
ssl_certificate_key /etc/ssl/private/example.com.key;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
keepalive_requests 150;

I am attaching screenshots
can you help me ?
Thank you

<img width="691" alt="opennebula-vnc" src="https://user-images.githubusercontent.com/59960414/133753196-f40fb298-a925-4c5c-95e4-ac040b2a05bf.PNG">
<img width="812" alt="opennebula-vnc2" src="https://user-images.githubusercontent.com/59960414/133753338-1c50e86f-a599-4d6c-977f-157cc6fe697e.PNG">

**Comment by al3xhh** [comment]
You can check documentation about how to configure FireEdge with Apache/Nginx [here](https://docs.opennebula.io/6.2/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.html#deploy-with-apache-passenger-recommended).

Also you can check specific FireEdge configuration [here](https://docs.opennebula.io/6.2/installation_and_configuration/opennebula_services/fireedge.html).

Closing this as it seems a configuration error, please reopen it if needed.
