### ISSUE TITLE
Sunstone wizard drops DISK/SIZE when selecting different image

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5543]
**Description**

When there is VM template with `DISK`, which has configured `SIZE`, e.g.:

```
DISK = [
  IMAGE = "Ubuntu 21.04",
  IMAGE_UNAME = "oneadmin",
  SIZE = "10000" ]
```

being updated via Sunstone VM Template Wizard, the `DISK/SIZE` attribute is dropped if different IMAGE is selected from a list of available images.

![image](https://user-images.githubusercontent.com/414850/134173491-d80adf49-9a8f-4fd8-acbc-e6f057dbb1dd.png)

**Expected behavior**
Parameters stay same across image changes.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12+

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1486)
- [Docs 5.12](https://github.com/OpenNebula/docs/pull/1982)
- [Docs 6.0](https://github.com/OpenNebula/docs/pull/1981)
