### ISSUE TITLE
vCenter VNETs with dpg does not set clusters correctly

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5545]
**Description**

When creating a vCenter VNET (noted when this network is created through ONeFlow from a vnet template) that entails the creation of distributed port groups, the vnet is only added in one vCenter cluster even if multiples are selected.

**Details**
 - Affected Component: networking
 - Hypervisor: vcenter
 - Version: 6.0, development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one-ee/pull/1680

[DOC]
* PENDING

**Comment by tinova** [comment]
to be tested as part of #5725
