### ISSUE TITLE
Sunstone cloud view hide VNC button does not work

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5547]
**Description**
When setting VNC button to false in cloud view YAML, the change is not reflected in the view.

**To Reproduce**
Disable that button in cloud view.

**Expected behavior**
It should hide the button.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12, 6.0 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
need fix for 5.12.x

**Comment by jloboescalona2** [comment]
@tinova PR tu approve:
- master: https://github.com/OpenNebula/one-ee/pull/1483
- one-5.12: https://github.com/OpenNebula/one-ee/pull/1482
