### ISSUE TITLE
Expose cleanup flag in oneprovision

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5552]
**Description**

Delete a provision fails if trying to delete a provision that contains virtual machines and images. To avoid this issue you need to use --cleanup flag in oneprovision, but this is not exposed through the GUI.

**Use case**

Erase a provision from the GUI

**Interface Changes**

Add a checkbox on the delete dialog to activate the flag.

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
needs testing

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1485
- dev: https://github.com/OpenNebula/development/pull/1645
- doc: _pending_
