### ISSUE TITLE
sc.exe as service manager of Windows contextualization

### ISSUE THREAD

**Issue by AdriMenendezM** [OpenNebula/one#5553]
**Description**
Use sc.exe as service manager of the OpenNebula Windows contextualization.

**Use case**
Users seriously concerned about no official software installed on their VMs that don't want services to be managed by third party software like NSSM.

**Interface Changes**
None

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
`sc.exe` is not equivalent of nssm/rhsrvany. The later tools allows to run any custom binary/script as a service and manage their lifecycle (in case of NSSM). OpenNebula Windows contextualization is a PowerShell script, which does not comply with the requirements for the services, it can't be run directly as a service and thus needs such wrapper which implements the service behaviour.

If you don't like NSSM, there is an option to build `.msi` package with provided `rhsrvany.exe`, which is distributed inside some Linux packages. See https://github.com/OpenNebula/addon-context-windows#requirements. NOTE: `rhsrvany.exe` doesn't stop the wrapped script on service stop correctly, so when doing service restarts you might end up with running several context scripts in parallel instead.

Closing.
