### ISSUE TITLE
vCenter dynamic context reconfiguration

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5556]
**Description**

Changing context values (including networking attributes) needs a reboot in vCenter VMs. 

**Use case**

Adding NIC or modify an existing one

**Interface Changes**

No need for interface changes

**Additional Context**

In KVM this is handled by udev rules that triggers the contextualization process on media change of the ISO that contains the context info. This approach needs to be adapted for vCenter environments

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Implemented in https://github.com/OpenNebula/addon-context-linux/issues/185
