### ISSUE TITLE
Sunstone labels are not correctly shown if there are more than five

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5557]
**Description**
When a user has more than 5 VM labels only the 5 first ones are being displayed in Sunstone. The rest of the left side menu overlap the remaining of the labels.

**To Reproduce**
Add more than 5 labels.

**Expected behavior**
 Either should the label list be scroll able or the rest of the left menu should be displayed after the label list.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1490
- doc: https://github.com/OpenNebula/docs/pull/1984
- doc one-6.0: https://github.com/OpenNebula/docs/pull/1985
