### ISSUE TITLE
Image size is not correctly shown in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5560]
**Description**
The image size is not correctly shown in VM storage tab.

![Untitled](https://user-images.githubusercontent.com/33811723/135636141-50df4aff-ce59-47fa-8d87-4f4547174a0b.png)

**To Reproduce**
Instantiate a VM with some disk on it.

**Expected behavior**
It should show the used size:

![Untitled](https://user-images.githubusercontent.com/33811723/135636360-e1f5b53f-134d-48b0-a45f-a3ab371f467c.png)

**Details**
 - Affected Component: Sunstone
 - Version: 5.12, 6.0 and master.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Reopening. When importing VMs from vCenter MONITORING.DISK_SIZE is not set.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1828
- Docs: https://github.com/OpenNebula/docs/pull/2192

**Comment by AlexProfi** [comment]
Hello
How enable MONITORING for ceph disk from system_storage or images_store 
I see - < not the size of disk content but after / i see disk size opennebula 6.0
