### ISSUE TITLE
Show running (powered on) hours of VMs in showback

### ISSUE THREAD

**Issue by fm4991** [OpenNebula/one#5561]
**Description**
Ticket ID 28394
Show running (powered on) hours of VMs in showback

**Use case**
Since you are able to configure showback that only running VMs are taken into account for the costs it would make sense to show the Powered On / Running hours in showback. This would be cool for transparency to the customers.
https://docs.opennebula.io/6.0/installation_and_configuration/opennebula_services/oned.html?highlight=showback%20power#default-showback-cost

**Interface Changes**
Show running (powered on) hours of VMs in Showback on the Web Interface and on CLI output.

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Needs update in Sunstone

**Comment by fm4991** [comment]
sorry for the duplicate... will this also be available in 6.x?

**Comment by tinova** [comment]
needed in 5.12, 6.2 and master

**Comment by paczerny** [comment]
> sorry for the duplicate... will this also be available in 6.x?
CLI version is already in 6.2 release

**Comment by fm4991** [comment]
@paczerny did i understand you correctly: this is already implemented in the CLI of 6.2 right?

**Comment by paczerny** [comment]
Yes, it is.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1612
- Docs: https://github.com/OpenNebula/docs/pull/2052

**Comment by fm4991** [comment]
@tinova it's only on the CLI now right? Will the feature also be available in sunstone?

**Comment by tinova** [comment]
yes, it has been added in the EE repo already
