### ISSUE TITLE
VMs monitored as POWEROFF instead of UNKNOWN just before a crash

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5564]
**Description**
In some circumstances (race condition), some VMs are monitored as POWEROFF instead of UNKNOWN just before a crash happens.

**To Reproduce**
It seems that for some reason before the host turn into ERROR state either the VMs or the Libvirt process are killed. This is causing the monitoring probes to return an empty list of VMs running in the host, so OpenNebula will assume they have been powered off. Anyway, the VMs should be correctly migrated in POWEROFF state.

**Expected behavior**
The VMs should be in UNKNOWN state when a crash happens.

**Details**
 - Affected Component: Monitor
 - Hypervisor: KVM
 - Version: 6.0 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Related issue #5581
