### ISSUE TITLE
Sunstone selectable IP conf. methods on VNET / VM NIC

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5568]
**Description**

So far, the NICs inside the guest VMs were all configured statically or skipped (in case of ethernet ranges). Newly introduced VM context parameters since 6.2, (`ETHx_`)`METHOD` and (`ETHx_`)`IP6_METHOD`, allows to select from a various dynamic configuration options, or explicitly set to skip the particular configuration, or even disable IPv6 on the NIC completely. The parameters can be specified on virtual network globally, or set/overriden in VM NIC.

References:
- https://docs.opennebula.io/6.1/management_and_operations/references/vnet_template.html#contextualization-attributes
- https://docs.opennebula.io/6.1/management_and_operations/references/template.html#context-section
- https://github.com/OpenNebula/addon-context-linux/issues/86#issuecomment-881591227
- https://github.com/OpenNebula/addon-context-windows/pull/96

The goal is to extend Sunstone wizards for to allow users to set both methods in
- Virtual Network - Context,
- VM (template) edit NIC / hot-attach NIC

**Use case**
User can set/override the IP configuration methods inside guest VMs without touching the (advanced) templates.

**Interface Changes**
All in oned core/context already, just Sunstone changes.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1696
- Docs: https://github.com/OpenNebula/docs/pull/2098
