### ISSUE TITLE
Allow deleting qcow2 disk snapshot using blockcommit

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5570]
**Description**
Currently deleting disk snapshots when using qcow2 DS is very limited. Users can not delete the active snapshots and also snapshots with children, so the only way how to delete the snapshot is to revert back.

**Use case**
e.g: when users get charged in terms of snapshot numbers, they need to delete them

**Interface Changes**
Deleting non-active snapshots with children could be achieved using `blockcommit` op.
https://wiki.libvirt.org/page/Live-disk-backup-with-active-blockcommit

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Related with: https://github.com/OpenNebula/one/issues/1507

**Comment by rsmontero** [comment]
see #1507

**Comment by rsmontero** [comment]
Finally we have implemented this feature as suggested details in #6265
