### ISSUE TITLE
Race condition when creating a scheduled action from Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5572]
**Description**
When creating a periodic `snapshot-create` action for a VM from Sunstone, an infinite loop of `create-snapshot` action is executed, having messages like these ones in the OpenNebula log:

```
Wed Oct  6 12:20:41 2021 [Z0][ReM][E]: Req:9680 UID:0 one.vm.update result FAILURE [one.vm.update] Cannot update template. Error parsing END_VALUE, times has to be greater than 0
Wed Oct  6 12:20:41 2021 [Z0][ReM][D]: Req:1888 UID:0 IP:127.0.0.1 one.vmpool.infoextended invoked , -2, -1, -1, -1
Wed Oct  6 12:20:41 2021 [Z0][ReM][D]: Req:1888 UID:0 one.vmpool.infoextended result SUCCESS, "<VM_POOL><VM><ID>129..."
Wed Oct  6 12:20:42 2021 [Z0][VMM][D]: Message received: SNAPSHOTCREATE SUCCESS 129 snap-3
```

**To Reproduce**
To reproduce the issue:

1. Go to "Action" tab
2. Specify the action (e.g snapshot-create) and time, and check the "Periodic" checkbox.
3. Specify "Repeat" as "Hourly" and "Each 1 hour".
4. Specify "End" as "After Each 2 times".
5. Add a action.

**Expected behavior**
Periodic actions must be executed just at the time they are scheduled.

**Details**
 - Affected Component: Sunstone & CLI
 - Hypervisor: KVM
 - Version: 5.12

**Additional information**
The same behavior occurs in the CLI.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
fixed in 6.2.0, closing
