### ISSUE TITLE
onesupport: Extend for priv. escalation via sudo on remote nodes

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5573]
**Description**

`onesupport` tool, which is part of Enterprise Edition, gathers all valuable information from the remote hypervisors hosts to help support understand the customers' environment. It tries to login remote hosts under *root* and if fails fallbacks to *oneadmin*. Under it *oneadmin* gathers only a minimum it expects it can access. But, some environments disable remote *root* login, but give *oneadmin* full control over the machine over sudo (despite this is not recommended in general!).

Goal is to introduce 3rd way to get into the data over remote *oneadmin* user with sudo (i.e., `ssh oneadmin@$HOST sudo ....`).

**Use case**
Flawless UX. Try as many common options to get as much information possible.

**Additional Context**
https://github.com/OpenNebula/infra/issues/118

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
With the revamp of the onesupport tool, I think this is no need, we currently get the needed information. So, I'm going to close it and if needed we can reopen it in the future.
