### ISSUE TITLE
Sunstone missbehave with context attributes filled by vm_template_contents

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5578]
**Description**

Sunstone:

- duplicates prefilled `attributes` when instanciating a service with `user` or `admin` views
- clear prefilled `attributes` when instanciating a service with `cloud` view

**To Reproduce**

1. Import ttylinux apps
2. Modify the ttylinux VM template with the following template
   ```
   CONTEXT = [
     CONFIG1 = "$CONFIG1",
     CONFIG2 = "$CONFIG2",
     NETWORK = "YES",
     SSH_PUBLIC_KEY = "$USER[SSH_PUBLIC_KEY]" ]
   CPU = "0.1"
   DISK = [
     IMAGE_ID = "0" ]
   GRAPHICS = [
     LISTEN = "0.0.0.0",
     TYPE = "VNC" ]
   HOT_RESIZE = [
     CPU_HOT_ADD_ENABLED = "NO",
     MEMORY_HOT_ADD_ENABLED = "NO" ]
   INPUTS_ORDER = "CONFIG1,CONFIG2,SERVICE_CONFIG1,SERVICE_CONFIG2"
   LOGO = "images/logos/linux.png"
   MEMORY = "128"
   MEMORY_UNIT_COST = "MB"
   OS = [
     BOOT = "" ]
   USER_INPUTS = [
     CONFIG1 = "M|text|first config| |",
     CONFIG2 = "M|text|second config| |" ]
   ```
3. Create a `test-service` with the following content
   ```
   {
     "name": "test-service",
     "deployment": "straight",
     "description": "",
     "roles": [
       {
         "name": "r1",
         "cardinality": 1,
         "vm_template": 0,
         "vm_template_contents": "NIC = [\n  NAME = \"_NIC0\",\n  NETWORK_ID = \"$Public\" ]\nCONFIG1 = \"foor1\"\nCONFIG2 = \"barr1\"\n ",
         "elasticity_policies": [],
         "scheduled_policies": []
       },
       {
         "name": "r2",
         "cardinality": 1,
         "vm_template": 0,
         "parents": [
           "r1"
         ],
         "vm_template_contents": "NIC = [\n  NAME = \"_NIC0\",\n  NETWORK_ID = \"$Public\" ]\nCONFIG1 = \"foor2\"\nCONFIG2 = \"barr2\"\n ",
         "elasticity_policies": [],
         "scheduled_policies": []
       },
       {
         "name": "r3",
         "cardinality": 1,
         "vm_template": 0,
         "parents": [
           "r1"
         ],
         "vm_template_contents": "NIC = [\n  NAME = \"_NIC0\",\n  NETWORK_ID = \"$Public\" ]\nCONFIG1 = \"foor3\"\nCONFIG2 = \"barr3\"\n ",
         "elasticity_policies": [],
         "scheduled_policies": []
       }
     ],
     "ready_status_gate": false,
     "automatic_deletion": false,
     "networks": {
       "Public": "M|network|Network with internet access| |id:"
     },
     "shutdown_action": "terminate-hard",
     "registration_time": 1634220409
   }
   ```
4. Instanciate the service with sunstone `admin` or `user` view

The VMs have several time each attributes:

<details><summary>Info for role1 VM</summary>

![service1-sustone-multi-attributes-role1](https://user-images.githubusercontent.com/1233212/137691677-27c4beef-b6e1-4a3a-a469-b071ba0ea3c9.png)
</details>

<details><summary>Info for role2 VM</summary>

![service1-sustone-multi-attributes-role2](https://user-images.githubusercontent.com/1233212/137691741-2fa1471e-7546-46af-8381-fcee3409ae21.png)
</details>

<details><summary>Info for role3 VM</summary>

![service1-sustone-multi-attributes-role3](https://user-images.githubusercontent.com/1233212/137691761-4013be3d-907f-45d8-8d2c-a3ff2668f835.png)
</details>

**Expected behavior**

When instanciating from command line, there is no issue here:

<details><summary>oneflow-template instantiate test-service</summary>

```
There are some networks that require user input. Use the string <<EDITOR>> to launch an editor (e.g. for multi-line inputs)
  * (Public) Network with internet access
    TYPE Existing(1), Create(2), Reserve(3). Press enter for default. 1
    VN ID. 0
ID: 8
```
</details>

<details><summary>Info for role1 VM</summary>

![service1-cli-attributes-role1](https://user-images.githubusercontent.com/1233212/137692255-1658f068-7822-4ac2-9283-f470a3559758.png)
</details>

<details><summary>Info for role2 VM</summary>

![service1-cli-attributes-role2](https://user-images.githubusercontent.com/1233212/137692282-edda8936-7743-4b6c-b8e3-c0c98c2c2d70.png)
</details>

<details><summary>Info for role3 VM</summary>

![service1-cli-attributes-role3](https://user-images.githubusercontent.com/1233212/137692295-e7541912-cc33-43f0-bf71-9452ca6a3eb2.png)
</details>

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0.0.2-1.ce on
 - OS: Debian GNU/Linux 10 (buster)

**Additional context**

With the cloud view, the input fields are not filled

<details><summary>Instanciate service with cloud view</summary>

![service1-sustone-cloud-instanciate](https://user-images.githubusercontent.com/1233212/137692810-de9bae1d-9223-4de1-927e-70bf6b88e02b.png)
</details>

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Reopening due to an error with the user inputs

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1593
