### ISSUE TITLE
Sunstone incomaptible with dalli 3.0+ Ruby gem

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5584]
**Description**

Sunstone is not compatible with newly released [dalli](https://rubygems.org/gems/dalli/) v3.0+ Ruby gem for Memcached. Problems:

1. gem `dalli` v3.0.2 itself is missing a run-time dependency on [connection_pool](https://rubygems.org/gems/connection_pool) gem,
2. Sunstone is using deprecated `:cache` option:

https://github.com/OpenNebula/one/blob/38d06a92aafc13ac5a9c75084bbef6f0147e46ca/src/sunstone/sunstone-server.rb#L234

**Proposed fix**
1. Sunstone is updated for Dali 3.0 and if required minimal dalli dependency in Gemfile is set to >= 3
OR
2. Sunstone is left on old Dali 2.7 and dalli dependency in Gemfile is set to <3

**Details**
 - Affected Component: Sunstone
 - Version: 6.1.90dev

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
pinning dalli 2.7.10 https://github.com/OpenNebula/one-ee/pull/1679
