### ISSUE TITLE
vCenter "save as" template of a linked clone does not produce linked clones

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5585]
## Missing actions

- [ ] need to fix bug with save_as_template with copy
- [x] need refactor (save_as_linked_clones to vcenter driver)

**Description**
When doing a *save as* VM template of a VM instantiated from a linked clone, and then deploy VMs from the *saved as* template, the resulting VMs are not linked clones.

**To Reproduce**
* Import VM template from vCenter with linked clones checked.
* Perfom SaveAs VM template from a deployed VM instance (requires poweroff).
* Deploy a VM from the saved template.
* The VM is not a linked clone

**Expected behavior**
VMs instantiated from the saved template should be linked clones as well.

**Details**
 - Affected Component: vCenter
 - Hypervisor: vCenter
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
need testing
need refactor (save_as_linked_clones to vcenter driver)

**Comment by tinova** [comment]
to be finished in #5660
