### ISSUE TITLE
Implement capability to mark timestamp of lease expiry for VM

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5587]
**Description**

The user can define the time and the actions of the VM Charter.

**Use case**

Definition of VM Charters per user, not relying in the system configuration.

**Interface Changes**

* New VM Charter creation dialog, prefilled with dates and actions from the configuration file

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1658
- Docs: https://github.com/OpenNebula/docs/pull/2074
