### ISSUE TITLE
Implement capability to extend timestamp of lease expiry date

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5588]
**Description**

A form is required that can modify the time of the charters, allowing a new definition of the dates and the actions.

**Use case**

Modify the VM Charter by the user.

**Interface Changes**

* New update Charter dialog.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
already present in 6.2.0
