### ISSUE TITLE
VMRC AltGr key does not work as expected

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5590]
**Description**
When using AltGR key in VMRC window, it doesn't print the characters it should print, it just prints the another key character, e.g: AltGr + 2, should print **@** but it prints **2**.

**To Reproduce**
Use a combination of keys in VMRC.

**Expected behavior**
It should print the correct character.

**Details**
 - Affected Component: FireEdge
 - Version: 6.0 & master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
PRs related to this:

- Code: 
  - https://github.com/OpenNebula/one-ee/pull/1609
  - https://github.com/OpenNebula/one-ee/pull/1578
  - https://github.com/OpenNebula/one-ee/pull/1577
- Docs: https://github.com/OpenNebula/docs/pull/2086
