### ISSUE TITLE
Oneflow should permit to tweak roles at instance

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5591]
**Description**

When instanciating a OneFlow service, it's not possible to adjust the memory or disk sizes.

**Use case**

We define a service usable by our users with “normal” personnal capacity.

Sometimes, we may need to deploy a bigger instance of the service.

**Interface Changes**

During instance of a OneFlow service, we should have the same optional capacity modifications of each roles as when instanciating a VM template.

This will have the advantage of having the modification limiters set in the VM templates

**Additional Context**

Today, when we define a service, we need to have several service and VM templates:

- `Service foo small`
- `Service foo big`
- `Service foo huge`

Which is limited as we do not provide all the possibility in the range between small and huge.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vickmp** [comment]
@tinova PRs to merge:
- [Code](https://github.com/OpenNebula/one-ee/pull/2465)
- [Test](https://github.com/OpenNebula/development/pull/2139)
- [Docs](https://github.com/OpenNebula/docs/pull/2485)

This functionality also needs to be implemented from the Sunstone side.
