### ISSUE TITLE
Some images can't boot after upgrade to 6.0.0.2-1.ce because FORMAT=save_as

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5597]
**Description**

I upgrade our infrastructure yesterday from 5.12.4 to 6.0.0.2, then some of our virtual machines can't boot with the following error:

```Fri Nov  5 10:06:55 2021 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/0/691372/deployment.0
Fri Nov  5 10:06:55 2021 [Z0][VMM][I]: error: unsupported configuration: unknown driver format value 'save_as'
Fri Nov  5 10:06:55 2021 [Z0][VMM][E]: Could not create domain from /var/lib/one//datastores/0/691372/deployment.0
```

A quick search using `xpath` from `libxml-xpath-perl` give the following:

```
oneimage list -x | xpath -e "/IMAGE_POOL/IMAGE[child::FORMAT='save_as']/ID/text()" 2> /dev/null
104724
104723
104722
104721
104720
104719
104718
104716
104714
104713
104712
104710
104709
104205
102957
101651
101279
101185
101092
100993
100992
94450
75366
74364
68283
67845
57557
```

Not that much compared to our 862 images in datastores.

**To Reproduce**

I don't know how it append but it looks to be related to images created with the `save_as` function.

**Expected behavior**

The migrator should fix those issue.

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 6.0.0.2-1.ce

**Additional context**

The oldest image was registered `14:47:14 16/12/2019` (I don't remember which version of ONE we had at that time) and the newest is `06:09:00 30/10/2021` (ONE version 5.12.3).

We do not do anything with that attribute so I think it comes for some bug since it's only few images.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
For now, I quickly fixed the issue by doing the following:

```sh
# Edit the attribute with sed
EDITOR="sed -i -e 's/<FORMAT><\!\[CDATA\[save_as\]\]>/<FORMAT>qcow2/'"

# Use xpath from `libxml-xpath-perl`
for IMG in $(oneimage list -x | xpath -e "/IMAGE_POOL/IMAGE[child::FORMAT='save_as']/ID/text()" 2> /dev/null)
do
    onedb update-body image --id ${IMG}
done
```

**Comment by baby-gnu** [comment]
I found what cause it, cloning a disk created by `disk-saveas`:

1. Import `Ttylinux - KVM` apps
2. Instanciate the `Ttylinux - KVM` template
3. Poweroff the `Ttylinux - KVM` VM
4. Save the disk
5. Clone the disk

Cloning the disk of the `Ttylinux - KVM` APP directly does not produce the error.

**Comment by rsmontero** [comment]
This has been address by the migrators from 5.12 to 6.0. It automatically search and fixes this. The patch was added mid April; and probably you got the migrators before that?

We are releasing 6.0.0.3 this/next week that will include the fix. Let me know if you think you may have the fixed version. I'm closing this for now, and will reopen if there might be an issue in the migrator

THANKS FOR THE FEEDBACK!!!!!!

**Comment by baby-gnu** [comment]
Thanks @rsmontero, I got the migration package mail `Date: Thu, 26 Aug 2021 09:15:20 +0200`, the migration package was named `opennebula-migration-community_6.0.0-2.ee_all.deb`.

I'll pass the `6.0.0.3` update as soon as possible and check if the above steps are fine.

Regards.
