### ISSUE TITLE
OneProvision GUI should only offer valid Providers

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5604]
**Description**

Currently, it offers metal providers if user wants a "virtual" provision, and the other way round

**Use case**

User should be presented with options that ensures a correct provision deployment

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1565
- doc: https://github.com/OpenNebula/docs/pull/2032
