### ISSUE TITLE
Flow scaling is not working in cloud view

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5605]
**Description**

Scaling in cloud view always set the cardinality to `0`.

**To Reproduce**

0. Connect as an admin user to Sunstone
1. Import `Ttylinux - KVM`
2. Create a simple `test-service` with the following content
   ```
   {
     "name": "test-service",
     "deployment": "straight",
     "description": "",
     "roles": [
       {
         "name": "r1",
         "cardinality": 1,
         "vm_template": 0,
         "elasticity_policies": [],
         "scheduled_policies": [],
         "vm_template_contents": ""
       },
       {
         "name": "r2",
         "cardinality": 1,
         "vm_template": 0,
         "elasticity_policies": [],
         "scheduled_policies": [],
         "vm_template_contents": ""
       }
     ],
     "ready_status_gate": false,
     "automatic_deletion": false,
     "registration_time": 1636377704
   }
   ```
3. Instanciate the service
   ```
   Mon Nov 08 14:33:49 2021 [I]: 127.0.0.1 - - [08/Nov/2021:14:33:49 +0100] "GET /service_template/0 HTTP/1.1" 200 1183 0.0049
   Mon Nov 08 14:33:54 2021 [I]: [EM] Waiting [7] to be (ACTIVE, RUNNING)
   Mon Nov 08 14:33:54 2021 [I]: [EM] Node 7 reached (PENDING,LCM_INIT)
   Mon Nov 08 14:33:54 2021 [I]: [EM] Waiting [8] to be (ACTIVE, RUNNING)
   Mon Nov 08 14:33:54 2021 [I]: 127.0.0.1 - - [08/Nov/2021:14:33:54 +0100] "POST /service_template/0/action HTTP/1.1" 201 1370 0.1458
   Mon Nov 08 14:33:54 2021 [I]: [EM] Node 8 reached (PENDING,LCM_INIT)
   Mon Nov 08 14:34:11 2021 [I]: [EM] Node 7 reached (ACTIVE, RUNNING)
   Mon Nov 08 14:34:24 2021 [I]: [EM] Timeout reached for VM [8] => (ACTIVE, RUNNING)
   Mon Nov 08 14:34:24 2021 [I]: [EM] Node 8 reached (ACTIVE,PROLOG)
   Mon Nov 08 14:34:25 2021 [I]: [EM] Node 8 reached (ACTIVE, RUNNING)
   ```
4. Using the `admin` view, scale the role `r2` to `3` VMs
   ```
   Mon Nov 08 14:34:56 2021 [I]: [EM] Waiting [9, 10] to be (ACTIVE, RUNNING)
   Mon Nov 08 14:34:56 2021 [I]: [EM] Node 9 reached (PENDING,LCM_INIT)
   Mon Nov 08 14:34:56 2021 [I]: 127.0.0.1 - - [08/Nov/2021:14:34:56 +0100] "POST /service/2/scale HTTP/1.1" 204 - 0.3165
   Mon Nov 08 14:34:56 2021 [I]: [EM] Node 10 reached (PENDING,LCM_INIT)
   Mon Nov 08 14:34:56 2021 [I]: 127.0.0.1 - - [08/Nov/2021:14:34:56 +0100] "GET /service/2 HTTP/1.1" 200 3697 0.2002
   Mon Nov 08 14:35:10 2021 [I]: [EM] Node 9 reached (ACTIVE, RUNNING)
   Mon Nov 08 14:35:26 2021 [I]: [EM] Node 10 reached (ACTIVE, RUNNING)
   Mon Nov 08 14:35:26 2021 [I]: [EM] Waiting 30s for cooldown for service 2 and role r2.
   ```
5. Switch to `cloud` view and scale the service to `5` VMs which should create 2 new VMS
   ```
   Mon Nov 08 14:41:32 2021 [I]: [EM] Waiting [8, 9, 10] to be (DONE, LCM_INIT)
   Mon Nov 08 14:41:32 2021 [I]: 127.0.0.1 - - [08/Nov/2021:14:41:32 +0100] "POST /service/2/scale HTTP/1.1" 204 - 0.0792
   Mon Nov 08 14:41:32 2021 [I]: [EM] Node 8 reached (ACTIVE,SHUTDOWN)
   Mon Nov 08 14:41:32 2021 [I]: [EM] Node 9 reached (ACTIVE,SHUTDOWN)
   Mon Nov 08 14:41:32 2021 [I]: [EM] Node 10 reached (ACTIVE,SHUTDOWN)
   ```

We see that all `r2` VMs are shutdown.

**Expected behavior**

The service role `r2` should have 5 VMS.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0.0.2-1.ce and 6.2.0-1.ce

**Additional context**

This is a follow up of #5231

<details><summary>The screenshot of <code>cloud</code> view before scaling</summary>

![cloud-view-scale](https://user-images.githubusercontent.com/1233212/140752802-c7b05c0d-660b-477d-9d36-ee0104c991e0.png)
</details>

<details><summary>The screenshot of <code>cloud</code> view after scaling</summary>

![cloud-view-scale-done](https://user-images.githubusercontent.com/1233212/140752902-df85cdd7-5721-46cb-864b-9d6790383fa1.png)
</details>

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1606
- Docs: https://github.com/OpenNebula/docs/pull/2049
