### ISSUE TITLE
Edge cluster based on Ceph storage

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#5620]
**Description**
Create ansible playbooks for deploying a Ceph based edge cluster. This edge cluster will be design in a hyperconvergent way, so monitors/rbds will be part of the hypervisors

**Use case**
Offer an storage solution with better HA for VM disks for Edge clusters that can afford this storage solution

**Interface Changes**
None.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Basic functionality is done for AWS and On-premises cluster in branch https://github.com/OpenNebula/one-ee/tree/ceph-hci

List of pending tasks
- [ ] use facts to set NIC for Edge clusters ([one-infra#269](https://github.com/OpenNebula/one-infra/issues/269))
- [ ] automatic RESERVED_MEM, RESERVED_CPU host settings
- [ ] add-host feature
- [ ] separate Ceph OSD/MON/MGR roles
- [ ] Fix Terraform + Ansible warnings
- [ ] allow empty array input in Fireedge (now requires ‘;’)
- [ ] create white paper
- [ ] update documentation
