### ISSUE TITLE
Download marketapps in fireedge 

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5625]
**Description**
Reimplement the logic of the download performed in sunstone (ruby) in nodejs 

**Use case**
Download marketapps

**Interface Changes**
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
* review if this is needed in datastores

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- Code: https://github.com/OpenNebula/one-ee/pull/1812
- Docs: https://github.com/OpenNebula/docs/pull/2178
