### ISSUE TITLE
Full testing VM tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5626]
- [x] Active waiting
- [x] Testing schedule actions
- [x] Test remaining bulk actions
  - [x] Deploy
  - [x] Migrate
  - [x] Migrate Live
  - [x] Hold
  - [x] Release
  - [x] Reschedule
  - [x] Unreschedule
  - [x] Recover 
  - [x] Change user / Change group
  - [x] Lock/Unlock
- [x]  create host with dummies drivers

When an action update the vm info, it only update the information in the row, but does not update the detail. This happens when using: 
- [x] reschedule
- [x] un-reschedule
- [x] change the owner
- [x] change the group

/!\ Need to enables tests (commented at the moment)

**Comment by sbbarragan** [comment]
The commented errors in client side are fixed after [implement the cache tool](https://github.com/OpenNebula/one/issues/5706)

**Comment by sbbarragan** [comment]
PRs to merge:
- dev: https://github.com/OpenNebula/development/pull/1749
