### ISSUE TITLE
Export VM Template from App tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5627]
- [x] Support to get docker tags from FireEdge server: https://github.com/OpenNebula/one/blob/master/src/sunstone/models/SunstoneServer.rb#L542-L587
- [x] Add requests to export form in client side

**Comment by sbbarragan** [comment]
PRs to merge into OpenNebula/one:
- https://github.com/OpenNebula/one-ee/pull/1601

**Comment by tinova** [comment]
need backend support
