### ISSUE TITLE
Add vCenter routes in FireEdge

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5631]
using onevcenter command functionality

**Comment by tinova** [comment]
https://github.com/OpenNebula/one-ee/pull/1639

**Comment by jloboescalona2** [comment]
- [ ] When the vcenter command is used (list or list_all) these do not list the clusters?
- [ ] If you need to import a vcenter host, the host command does not allow you to pass the id to be imported Note: I was checking that the import command could work, but I would need it to admit the host as a vobject
- [ ] Like the import_defaults of the templates, it is also required to place the flags for the import of the networks: (size, type, clusters to import)

**Comment by jloboescalona2** [comment]
@tinova PR to apply:
- Code: https://github.com/OpenNebula/one-ee/pull/1772

**Comment by al3xhh** [comment]
PR to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/1802)
