### ISSUE TITLE
Set correct attributes info on marketplace apps

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5634]
We need to evaluate if there is an issue that potentially affects all marketplace instances

- [ ] Check appliances (OSes, K8s and VNF) with vCenter
- [ ] Adjust titles and metadata (especially VM Templates) to be compatible with vCenter (ie SCHED_REQ not to avoid vCenter clusters)

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by onenhansen** [comment]
Images to test:
- AlmaLinux 8
- Alpine Linux 3.14
- Debian 11
- FreeBSD 13
- K3s 1.21.5
- Kubernetes 1.18
- Kubernetes 1.21
- Service Kubernetes 1.21
- Ubuntu 20.04
- Service VNF

---------

AlmaLinux8 - ✅ Login Screen
Alpine Linux 3.14 - ✅ Login Screen
Debian 11 - ✅ Login Screen
FreeBSD 13 - ✅ Login Screen
K3s 1.21.5+k3s2 - ⚠️
- Seemed to get stuck during boot on one-context, high mem usage
- Increase memory - Pulls up Login Screen
- K3s services crashes if networking is not configured

Kubernetes 1.18 - ⛔️ Crashed to busybox recovery console during boot
Kubernetes 1.21 - ✅ containerd and dockerd were running
Service Kubernetes 1.21 -  ⚠️✅
- Sunstone error when downloading from the marketplace stating the name was taken by the latest ID, however it still added the image just fine.
- Spawned 2 instances and both display the login screen.

Ubuntu 20.04 - ✅ Login Screen
Service VNS - ⚠️Services not running, but machine started up.

**Comment by tinova** [comment]
great, thanks for testing

i believe we can ditch k3s

**Comment by tinova** [comment]
wontfix
