### ISSUE TITLE
Action to create Marketplace App from VM & VM Template

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5638]
- [x] Support to import VM/VM Template from FireEdge server:
https://github.com/OpenNebula/one/blob/master/src/oca/ruby/opennebula/template_ext.rb#L49
- [x] Add requests to client side

**Comment by sbbarragan** [comment]
PRs to merge into one:
- https://github.com/OpenNebula/one-ee/pull/1617
- https://github.com/OpenNebula/one-ee/pull/1618

**Comment by tinova** [comment]
need backend support
