### ISSUE TITLE
Sunstone truncates supported advanced disk options when HYPERVISOR=LXC

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#5641]
**Description**
When the VM Template has HYPERVISOR=LXC it hides advanced options under the IMAGE section which are currently supported.  Cache and size on instantiate are implemented features on the driver.

There are also other sections whose contents are hidden but the sections are shown anyways.

![image](https://user-images.githubusercontent.com/16429804/143139258-9a74762b-e54a-437a-9bc1-a891045a321d.png)

**To Reproduce**
- Select LXC hypervisor on VM Template
- Click Advanced options on the disk section

**Expected behavior**
Features supported by the driver should not be hidden.
- cache
- size on instantiate

Truncated sections should hide the heading of the section as well.

**Details**
 - Version: 6.0, 6.2, master

## Progress Status
- [x] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved: 
- Code: https://github.com/OpenNebula/one-ee/pull/1709
- Docs: https://github.com/OpenNebula/docs/pull/2116
