### ISSUE TITLE
Shrink VM disk from OpenNebula

### ISSUE THREAD

**Issue by rdiaz-on** [OpenNebula/one#5648]
**Description**
Add support for shrinking qcow2 disk files from OpenNebula.

**Use case**
Some users can face problems performing actions on VMs (e.g. snapshot, deploy) if the VM disks are considerably large. The *qemu-img* tool can be used to shrink the disk size (if not full). Currently the procedure (consisting of powering off the VM, running the *qem-img* tool to actually shrink the disk and resuming the VM) has to be done manually. It can be useful for users to have an option to automatically shrink VM disks and images.

**Interface Changes**
KVM driver and CLI.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Duplicated #1266, closing.
