### ISSUE TITLE
xmllint: command not found

### ISSUE THREAD

**Issue by andybro19** [OpenNebula/one#5649]
**Description**
When deploying a KVM virtual machine an error occurs:

```
Fri Nov 26 16:33:27 2021 [Z0][VMM][I]: /var/tmp/one/vmm/kvm/deploy: line 43: xmllint: command not found
```

If the VM has a NIC that should connect to an Open vSwitch bridge (VN_MAD = "ovswitch") then the following error occurs and the NIC fails to attach to the bridge.

```
Fri Nov 26 16:33:27 2021 [Z0][VMM][E]: DEPLOY: ovswitch: No tap device found for nic 0 ExitCode: 1
```

This is presumably occurring because `libxml2-utils` does not get installed as a dependency for `opennebula-node-kvm`, which includes the `xmllint` program. In fact, by installing this package the problem stops persisting.

**To Reproduce**
1. Create a Open vSwitch virtual network (VN_MAD = "ovswitch")
2. Deploy a KVM virtual machine with a NIC on the vnet created in the previous step
3. Observe that an error occurs and the port is not added to the bridge

**Expected behavior**
The virtual machine should be deployed successfully and have a connection to the virtual network.

**Details**
 - Affected Component: KVM Hosts
 - Hypervisor: KVM
 - Version: 6.2.0 CE
 - OS: Debian 10, Debian 11

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
What OS is your hypervisor?

**Comment by andybro19** [comment]
> What OS is your hypervisor?

I have tried Debian 10 and Debian 11. This error appears on both.
