### ISSUE TITLE
Sunstone views Settings.ssh_key attributes not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5650]
**Description**
The `Settings.ssh_key` attribute is not working as expected when setting to false. The Public SSH Key section is not hidden.

**To Reproduce**
   - Update the corresponding view file and set `Settings.ssh_key: false`.
   - The Public SSH Key section is not hidden.

**Expected behavior**
The Public SSH Key section is hidden.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.10

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:

6.2 & master:
- Code: https://github.com/OpenNebula/one-ee/pull/1659
- Docs: https://github.com/OpenNebula/docs/pull/2075

5.12:
- Code: https://github.com/OpenNebula/one-ee/pull/1660
- Docs: https://github.com/OpenNebula/docs/pull/2076
