### ISSUE TITLE
New Sunstone VM card design

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5658]
- State
- ID
- Name
- Labels
- Start time
- IPs
- Disk Capacity 
- CPU
- Memory
- Remote Console buttons: (Guacamole VNC and/or Guacamole RDP and/or Guacamole SSH) or VMRC

**Comment by tinova** [comment]
https://github.com/OpenNebula/one-ee/pull/1639

**Comment by sbbarragan** [comment]
to be considered as part of https://github.com/OpenNebula/one/issues/5422
