### ISSUE TITLE
Document and improve EXTERNAL attribute usage

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#5659]
**Description**
External attribute is used by context package to not configure the IP address associated with a NIC, this can be useful for routers/proxy VMs. Past versions of OpenNebula used EXTERNAL also to setup networking on Edge Clusters. This issue is:

* Add documentation for this context attribute in the nic section
* Improve the description of the Sunstone dialog with a more descriptive text.

![image](https://user-images.githubusercontent.com/665074/144426028-46d33dec-624c-425c-b5b5-3a5906aa1b72.png)

**To Reproduce**
Not applicable

**Expected behavior**
Not applicable

**Details**
 - Affected Component: Sunstone
 - Hypervisor: -
 - Version: >= 6.0

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
I have checked the code and this external attribute is just used in the contextualization packages, but currently it's not used in the OneProvsion, so I think following actions should be:

- Review if other component is using it.
- Remove it from Sunstone.
- Remove if from context if any other component is using it.

Note: OneProvision use external in some providers, but this is just internal information, final user does not need to know about this external attribute, he/she just need to know the IP.

**Comment by ospalax** [comment]
I am using something called `EXTERNAL` in [vnf appliance](https://github.com/OpenNebula/one-infra/blob/c1b174e69420429e065caa50baa88a2216f66379/tools/building_images/scripts/service/lib/artifacts/vnf/one-vnf/lib/appliance/plugin/sdnat4.rb#L103) for `SDNAT4`:

```
                    if lease.key?('EXTERNAL') && lease['EXTERNAL']
                        new_map['EXTERNAL_ALIAS_VM'] = lease['VM']
                        new_map['EXTERNAL_ALIAS_IP'] = lease['IP']
                        new_map['EXTERNAL_ALIAS_PARENT_NIC'] = lease['PARENT']
                        new_map['EXTERNAL_ALIAS_PARENT_NETWORK'] = \
                            lease['PARENT_NETWORK_ID']
                        mapping.append(new_map)
                    end
```

I traverse the result given by `onegate vnet show --json --extended` and walk it via: `VNET` -> `AR_POOL` -> `AR` -> `LEASES` -> `LEASE` -> `EXTERNAL`

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1939
