### ISSUE TITLE
vCenter 6 and 7 back-compatibility issue while deploying

### ISSUE THREAD

**Issue by slntopp** [OpenNebula/one#5662]
**Description**
VMs are failing to deploy due to:

```
ERROR: deploy: Deploy of VM 1276 on vCenter cluster Cluster03 with /var/lib/one/vms/1276/deployment.0 failed 
due to "InvalidRequest:  Cannot parse "202112034918741" as an int value 
while parsing serialized value of type int at line 1, column 409  
while parsing property "key" of static type int  
while parsing serialized DataObject of type vim.vm.device.VirtualVmxnet3 at line 1, column 375  
while parsing property "device" of static type VirtualDevice 
 while parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec at line 1, column 300 
 while parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigSpec 
 while parsing serialized DataObject of type vim.vm.ConfigSpec at line 1, column 258 
 while parsing call information for method ReconfigVM_Task at line 1, column 177  
while parsing SOAP body at line 1, column 167  
while parsing SOAP envelope at line 1, column 0 
 while parsing HTTP request for method reconfigure on object of type vim.VirtualMachine at line 1, column 0"
on attempt #2.
```

Little bit debugging brought following:

Backtrace

```ruby
["/var/lib/gems/2.5.0/gems/rbvmomi-3.0.0/lib/rbvmomi/connection.rb:63:in `parse_response'",
 "/var/lib/gems/2.5.0/gems/rbvmomi-3.0.0/lib/rbvmomi/connection.rb:92:in `call'",
 "/var/lib/gems/2.5.0/gems/rbvmomi-3.0.0/lib/rbvmomi/basic_types.rb:213:in `_call'",
 "/var/lib/gems/2.5.0/gems/rbvmomi-3.0.0/lib/rbvmomi/basic_types.rb:76:in `block (2 levels) in init'",
 "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:1371:in `reference_unmanaged_devices'",
 "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:701:in `clone_vm'",
 "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3471:in `block in new_from_clone'",
 "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3470:in `tap'",
 "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3470:in `new_from_clone'",
 "/var/lib/one/remotes/vmm/vcenter/deploy:88:in `<main>'"]
```

And these lines generating "unparsable" IDs:
[this](https://github.com/OpenNebula/one/blob/6e0ae88fd755a00e293925d2b599fd7e164e5d36/src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb#L1986)
and [this](https://github.com/OpenNebula/one/blob/6e0ae88fd755a00e293925d2b599fd7e164e5d36/src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb#2132)

It seems this change been made in [a1fdf4c2776d](https://github.com/OpenNebula/one/commit/a1fdf4c2776d1fff9510e697913adafdd1598ef5) to bring vCenter 7 support. Though it seem to break back-compatibility with vCenter 6

Thanks for your attention!
Hope this could be resolved soon, let me know if I can anyhow help

**Details**
 - Affected Component: vCenter VMM Driver: deploy action 
 - Hypervisor: vCenter (6.5)
 - Version: 6.2.0 (c84c3303)

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
[DOC]
 * Add in commit f59a0e7f96f0d9903a8bbf03062f5f04e1a673f9
