### ISSUE TITLE
LXC Wild VM

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#5667]
**Description**
Allow importing running LXC instances, not managed by OpenNebula, on OpenNebula nodes. The instances should support almost every feature available for regular instances, except the ones involving storage operations.

**Use case**
Manage containers running prior to an OpenNebula deployment.

**Interface Changes**
none

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
wontfix
