### ISSUE TITLE
[Pyone] Pyone API does not accept dictionaries with root in updateconf

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5677]
**Description**
Updateconf API call does not allow to use dictionaries like:

```
{'CONTEXT': {'A': 'abc'}}
```

**To Reproduce**

```
one.vm.updateconf(0,{'CONTEXT': {'A': 'abc'}}, 1)
```

**Expected behavior**
It should update the VM template.

**Details**
 - Affected Component: Pyone
 - Version: 6.2 & master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by xorel** [comment]
Can not reproduce, it actually works with

```
one.vm.updateconf(0, {'TEMPLATE': {'CONTEXT': {'A': 'abc'}}}, 0)
```

**Comment by tinova** [comment]
closing until further instructions on how to reproduce are available
