### ISSUE TITLE
contextualization not working when the cdrom is already ejected

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5678]
**Description**
Same reasoning as described in #5442, but this time about the `vmm/kvm/prereconfigure` script.
If for some reason the contextualization CDROM is ejected, the ejected state is not detected by the script. depending on the libvirt version

**To Reproduce**
Instantite a VM
Eject(manually) the contextualization cdrom
Trigger any contextualization reconfiguration (add alias IP, change password, etc.)

The operation will fail.

**Expected behavior**
The operation should succeed

**Details**
 - Affected Component: [VMM_MAD]
 - Hypervisor: [KVM]
 - Version: [5.12.x]

**Additional context**
The issue is silently fixed for v6 in https://github.com/OpenNebula/one/commit/37265a731a7dad741a923c406adf5f9b2ae48fb6
but not backported to 5.12 LTS.
Also, an improved patch will be provided shortly.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Already back-ported to 5.12, closing it.
