### ISSUE TITLE
Warning message in Sunstone when adding an scheduled action

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5679]
**Description**
When instantiating a VM with already configured sched action a warning message appears in VM overview.

**To Reproduce**
Instantiate a VM with sched action.

**Expected behavior**
No warning message.

**Details**
 - Affected Component: Sunstone
 - Version: 6.2 & master

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
code: https://github.com/OpenNebula/one-ee/pull/1684
