### ISSUE TITLE
Failure when downloading a DH image without Config.Cmd

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5685]
**Description**
In order to automatically generate the [one_entrypoint.sh](https://docs.opennebula.io/6.2/management_and_operations/storage_management/marketplaces.html#entrypoint) script, some image information is gathered. The [current script](https://github.com/OpenNebula/one/blob/cf26a33ca1a696b650a9c0c57b17c534c2156a29/src/datastore_mad/remotes/docker_downloader.sh#L222) assumes that the image have an iterable `Config.Cmd` attribute. This triggers an error at the downloader script if the attribute is not set (or set to null) making the image downloading to fail.

**To Reproduce**
Try to export a docker image without `Config.Cmd` attribute (e.g `matrixdotorg/synapse`)

**Expected behavior**
The error should be managed properly to avoid failing the entire built.

**Details**
 - Affected Component: DockerHub Marketplae
 - Version: >=6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
duplicate of #6374
