### ISSUE TITLE
VM's in roles not listed in service

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5691]
**Description**
When opening a service and try to access the VM an error in the browser console appears and the VM is not listed.

**To Reproduce**
Create a service with multiple VMs.

**Expected behavior**
VMs should be listed

**Details**
 - Affected Component: Sunstone
 - Version: 6.2 & development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1699
- Docs: https://github.com/OpenNebula/docs/pull/2100
