### ISSUE TITLE
Sunstone does not allow to create scheduled action

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5693]
**Description**
When creating/updating VM Template Sunstone does not allow to create scheduled action. Throws the following console error:

<img width="1956" alt="Bildschirmfoto 2022-01-12 um 13 31 03" src="https://user-images.githubusercontent.com/33811723/149328494-36c5b29f-f24d-4fb7-87e2-e17d81caf0a5.png">

**To Reproduce**
Create a VM template with scheduled actions or try to add one to an existing VM template.

**Expected behavior**
Be able to add scheduled actions on VM templates

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.2, master

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- docs: https://github.com/OpenNebula/docs/pull/2101
- code: https://github.com/OpenNebula/one-ee/pull/1700
