### ISSUE TITLE
Error updating VM Templates with custom views

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5696]
**Description**
When setting a new Sunstone view with features -> showback to false and updating a VMTemplate, the new template deletes almost all the previous attributes

**To Reproduce**
Set features -> showback to false in a Sunstone view and update any template.

```
features:
    # True to show showback monthly reports and VM cost
    showback: false
```

**Expected behavior**
VMTemplates should keep all the previous fields and modify the ones that are being updated.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.2 and development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1714
- Docs: https://github.com/OpenNebula/docs/pull/2120
