### ISSUE TITLE
Mapping the information from one.system.config in resource pool requests

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5698]
**Description**
Currently, the `one.system.config` request returns the `oned.conf` but the oned configuration can only be retrieved by users in the oneadmin group.

However, the `oned.conf` is used to help Sunstone render certain parts of the interface. Therefore, all users should have access to the configurations used in the interface.

**Use case**
Eg: in [the form to create Marketplace Apps](https://github.com/OpenNebula/one/blob/master/src/fireedge/src/client/components/Forms/MarketplaceApp/CreateForm/Steps/BasicConfiguration/schema.js#L143-L150), the `oned.conf` is used to [filter the Marketplace allows export action](https://github.com/OpenNebula/one/blob/master/src/fireedge/src/client/models/Datastore.js#L74-L88).

**Interface Changes**
FireEdge server should assume the **filtering** (for security reasons) and **mapping** of the oned configuration required for the interface.

Eg: in the form to create Marketplace Apps, could be better to map the [actions allowed](https://github.com/OpenNebula/one/blob/master/share/etc/oned.conf#L1232-L1267) (`MARKETPLACE_ACTIONS`) in the `one.marketpool.info`.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

No specific test developed

**Comment by jloboescalona2** [comment]
@tinova PR to approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1734
- Code: https://github.com/OpenNebula/one-ee/pull/1742
