### ISSUE TITLE
Sunstone doesn’t show external IPs on VM datatable

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5701]
**Description**
When having External IPs, provided by the monitoring or by some other way, Sunstone is showing them neither in the IPs dropdown nor the VM info tab. 

**To Reproduce**
Configure a VM in vCenter with IPs, import it into OpenNebula, and try to inspect the IPs configured in vCenter.

**Expected behavior**
Sunstone to show all the external IPs.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 5.12.11, 6.2, development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: 
    - https://github.com/OpenNebula/one-ee/pull/1705
    - https://github.com/OpenNebula/one-ee/pull/1706 
- Docs: 
    - https://github.com/OpenNebula/docs/pull/2110
    - https://github.com/OpenNebula/docs/pull/2111
