### ISSUE TITLE
Bad practices for FireEdge REST API

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5703]
**Description**
The **action should be indicated by the HTTP request method** that we’re making: `GET`, `POST`, `PUT`, and `DELETE`.

**Expected behavior**
GET          `/fireedge/api/service`        retrieves resources
GET           `/fireedge/api/service/:id`  retrieves resource by `:id`
POST        `/fireedge/api/service`        submits new data to the server
PUT          `/fireedge/api/service/:id`    updates existing resource by `:id`
DELETE   `/fireedge/api/service/:id`    removes resource by `:id`

**Details**
 - Affected Component: FireEdge
 - Hypervisor: [e.g. KVM]
 - Version: 6.2 and development

**Additional context**
https://docs.opennebula.io/6.3/integration_and_development/references/react_sunstone_dev.html#methods

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- CODE: https://github.com/OpenNebula/one-ee/pull/1708
- DOCS: https://github.com/OpenNebula/docs/pull/2117
