### ISSUE TITLE
Implements data fetching and caching tool

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5706]
**Description**
FireEdge interfaces need to fetch data from a server in order to display it. They also usually need to make updates to that data, send those updates to the server, and keep the cached data on the client in sync with the data on the server.

The idea is implement [RTK Query](https://redux-toolkit.js.org/rtk-query/overview) as data fetching library.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Also revisit tester code between Jorge and Sergio

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1761
- dev: https://github.com/OpenNebula/development/pull/1743
