### ISSUE TITLE
When using vCenter, Sunstone should show only the available options.

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5707]
**Description**
When using vCenter, Sunstone should show only the available options.

**Use case**
Improve user interface and usage.

**Interface Changes**
Remove remote console options not available in vCenter.

**Additional Context**
As an example, when instantiating a vCenter image and opening the remote console options, `virt-viewer` is shown but this option is not supported.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1718
- Docs: https://github.com/OpenNebula/docs/pull/2121

**Comment by FrederickBor** [comment]
@tinova PR to be approved considering the fact that when you import vCenter machine comes without hypervisor attribute: 
- Code: https://github.com/OpenNebula/one-ee/pull/1807

**Comment by tinova** [comment]
Need tp implement hypervisor info request using HISTORY.HID instead of HYPERVISOR for Virt Viewer on the individual tab

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1832
- Test: pending

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1858
- Tests for KVM host: pending

**Comment by sbbarragan** [comment]
PRs to merge:
- https://github.com/OpenNebula/one-ee/pull/1887
