### ISSUE TITLE
VM monitoring should be reported as `UNKNOWN` when virsh can't connect to hypervisor instead of `POWEROFF`

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5708]
**Description**

When the `virsh` command can't connect to the hypervisor, running VMs should be reported as `UNKNOWN` instead of `POWEROFF`.

**To Reproduce**

1. Setup an OpenNebula and deploy several VMs
2. Modify OpenNebula for [multiple-actions per host](https://docs.opennebula.io/6.2/open_cluster_deployment/kvm_node/kvm_driver.html#multiple-actions-per-host) with TLS
3. Wait for successful monitoring 
4. Make sure the TLS certificate is expired
5. Wait for monitoring to fail

Another possibility is to just stop `libvirt` service after the VM is successfully monitored

**Expected behavior**

- the VM should be reported as `UNKNOWN` state
- a log message should indicate that the monitoring could not be done

**Details**
 - Affected Component: Monitoring
 - Hypervisor: KVM
 - Version: `6.2.0-1.ce`, `6.0.0.2-1.ce`

**Additional context**

The `virsh` standard error has the message:

- when the service is stopped
  ```
  error: failed to connect to the hypervisor
  error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Connection refused
  ```
- when the certificate has expired
  ```
  error: failed to connect to the hypervisor
  error: The client certificate /etc/pki/libvirt/clientcert.pem has expired
  ```
  
It's already correctly reported for deploy, as I see in logs:

```
Mon Jan 24 16:02:00 2022 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/0/714969/deployment.259' 'nebula82' 714969 nebula82
Mon Jan 24 16:02:00 2022 [Z0][VMM][I]: error: failed to connect to the hypervisor
Mon Jan 24 16:02:00 2022 [Z0][VMM][I]: error: The client certificate /etc/pki/libvirt/clientcert.pem has expired
Mon Jan 24 16:02:00 2022 [Z0][VMM][E]: Could not create domain from /var/lib/one//datastores/0/714969/deployment.259
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
Another option could be to have a new state like `LIBVIRT_ERROR` or a generic name, maybe `ENGINE_ERROR` and reporting the error message.

**Comment by mkutouski** [comment]
I wasn't able to reproduce that issue on OpenNebula 6.8.0 release.
As soon as client's certificate expires the host goes into `ERROR` state but VMs get status `UNKNOWN`.

**Comment by tinova** [comment]
closing until more instructions on how to reproduce are provided
