### ISSUE TITLE
Option to import Wild with non-persistent disk

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5711]
**Description**
In vCenter Wild are imported with persistent disks.

**Use case**
Add a new option to change that Wilds VMs be imported with non-persistent disks.

**Interface Changes**
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
developed in #5756
