### ISSUE TITLE
Sunstone shows NaN on each service without Registration Time and Start Time

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5714]
**Description**
When upgrading from v5.12 to v6.2, Sunstone shows NaN in services Start Time and service templates Registration Time.

**To Reproduce**
Create a service template and instantiate it in v5.12
Upgrade to 6.2
Check the data table for service templates and services on Sunstone.

**Expected behavior**
To not show NaN, and show "-" instead.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.2, development

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1727
- Docs: https://github.com/OpenNebula/docs/pull/2123
