### ISSUE TITLE
RAFT problems

### ISSUE THREAD

**Issue by w1llrock** [OpenNebula/one#5719]
**Description**
Hi, I have three Opennebula frontends, raft set up. I noticed that when the leader falls, the leader hook works on the new leader and fallower after 20-30 seconds, the logs show an example of the leader hook triggering after the fallower hook. help figure it out. 

**Details**

 - Hypervisor: KVM
 - Version: 6.0.0.3

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
[1.txt](https://github.com/OpenNebula/one/files/7984905/1.txt)
[2.txt](https://github.com/OpenNebula/one/files/7984906/2.txt)

**Comment by rsmontero** [comment]
RAFT code improved since 6.0 release, closing this as it was probably fixed
