### ISSUE TITLE
Sunstone does not link VMs to Datastores in Cloud View

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5721]
**Description**
When instantiating a VM Template and selecting a Datastore the VM is not associated with the selected datastore.

**To Reproduce**
1. Create a user with low privileges
2. Log in to Sunstone with the new user
3. Try to instantiate a VM Template and select the Datastore

**Expected behavior**
VM to be instantiated in the selected datastore

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.2 and development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1744
- Docs: https://github.com/OpenNebula/docs/pull/2132
