### ISSUE TITLE
QinQ support for OVS

### ISSUE THREAD

**Issue by mikhsam** [OpenNebula/one#5722]
**Description**
Capability to set additional VLAN tag on network interfaces and define inner VLAN tags for interfaces.

**Use case**
QinQ is an amendment to the [IEEE 802.1Q specification](http://www.ieee802.org/1/pages/802.1Q.html) that provides the capability for multiple VLAN tags to be inserted into a single Ethernet frame.  The 802.1Q tunneling expands the VLAN space by adding another layer of 802.1Q tags. Using Q-in-Q (aka dvlan) tunneling allows to create Layer 2 Ethernet connection between customers cloud infrastructure in OpenNebula cluster and with other customer clouds or hardware sites, or use a single service VLAN to bundle different customer VLANs. The customer 802.1Q (dot1Q) VLAN tags are prepended by the service VLAN tags (S-Tags). A port configured to support Q-in-Q tunneling becomes NNI (network node interface), other interfaces will become UNI (user-network interface).

**Interface Changes**
New settings for Sunstone, CLI and API for configuring network ports with OVS driver.
Describe any changed you'd like to see to current interfaces including Sunstone, CLI or/and API

**Additional Context**
[Link with example for support QinQ with OVS](https://developers.redhat.com/blog/2017/06/06/open-vswitch-overview-of-802-1ad-qinq-support)

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by hydro-b** [comment]
@mikhsam "Using Q-in-Q (aka dvlan) tunneling allows to create ..." <- I guess you want to say "Using Q-in-Q (aka C-VLAN) (from customer VLAN)
