### ISSUE TITLE
Support VMware encrypted disks

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5723]
**Description**
VMware offers the possibility to encrypt a disk, due to this encryption the name of the disk changes, this can lead to multiple issues in OpenNebula related to the sync of state (esp. disk) between OpenNebula and vCenter resources.

**Use case**

Be able to use encrypted disks with no issues.

**Interface Changes**
vCenter driver.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Fixed as part of #5740
