### ISSUE TITLE
Repository one missing 6.2.0 release tag

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5726]
**Description**

Public repository `OpenNebula/one` is missing release tag:

```
$ git tag | grep release-6.2.0 || echo fail
fail
```

Tag should be placed on commit `c84c33030`.

**Details**
 - Affected Component: OpenNebula/one repository

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Thanks for the heads up Vlastimil! Hugely appreciated.

Should be fixed now:

```
commit c84c33030bf7c8a419d5bac5ddb7c0509d4eadb5 (tag: release-6.2.0, origin/one-6.2, one-6.2)
```
