### ISSUE TITLE
VM Template creation in vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5731]
**Description**

Requiring an existing VM Template in vCenter is problematic, and possibly confusing whenever downloading apps from the marketplace.

OpenNebula should create a bare VM Template when needed if there are no references to existing VM Templates in vCenter.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1913
- dev: https://github.com/OpenNebula/development/pull/1820
