### ISSUE TITLE
Error when import and create images on Ubuntu because qemu-img

### ISSUE THREAD

**Issue by carloshm91** [OpenNebula/one#5732]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When we create images or import images from marketplace we get this kind of errors

```
Tue Feb 15 10:09:08 2022 : Error copying image in the datastore: 'qemu-img info' stderr: #<IO:0x0000556e0b7228c8> 'qemu-img info' output appears to be invalid.'               ' Cannot determine file type. Removing /var/lib/one/vcenter/one_9f82ad22-7beb-404e-9595-bf73e9c672bc/44/0.vmdk...
```

**To Reproduce**
Create or import images from Marketplace with Ubuntu

**Expected behavior**
Images should be imported and created with out errors

**Details**
 - Affected Component: [vCenter Driver]
 - Hypervisor: [vCenter]
 - Version: [master, 6.2]

**Additional context**

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
* code: 0ad7fd7fab491e7d6b2728e259e8161b0f08fac4
