### ISSUE TITLE
vCenter template importing QoL on Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5735]
**Description**
It would be nice to have a filter on vCenter object names when importing any resource via Sunstone. The selection list could also order said resources alphabetically. 

**Use case**
Ease of use at importing when the vCenter host has a high number of resrouces.

**Interface Changes**
- Add a name filter
- Add flexibility on sorting

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs To be approved
- Code: https://github.com/OpenNebula/one-ee/pull/1793
- Docs: https://github.com/OpenNebula/docs/pull/2166

**Comment by FrederickBor** [comment]
@tinova PR to be approved: 
- Docs: https://github.com/OpenNebula/docs/pull/2171

**Comment by FrederickBor** [comment]
This feature has been implemented for all resources where you can import from vCenter.
