### ISSUE TITLE
provision docuemnt get's broken after: onedb udpate document

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5742]
**Description**
When updating the oneprovision document with command like `onedb update document --id $ID`
the escape characters get broken like:

```
...
 "ar_template":"AR=[\\\\\\\\n  PROVISON_ID=\\\\\\\\"1\\\\\\\\",\\\\\\\\n  SIZE=\\\\\\\\"1\\\\\\\\",\\\\\\\\n  IPAM_MAD=\\\\\\\\"aws\\\\\\\\",\\\\\\\\n  PROVISION_ID=\\\\\\\\"1\\\\\\\\"\\\\\\
...
```

**To Reproduce**
Create a provision, try to edit it. 

**Details**
 - Affected Component: oneprovision
 - Version: 6.2
 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2045)
- [docs](https://github.com/OpenNebula/docs/pull/2271)
