### ISSUE TITLE
Present Error information in Sunstone

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5745]
**Description**

Currently, USER_TEMPLATE/ERROR, USER_TEMPLATE/SCHED_MESSAGE, and TEMPLATE/SCHED_ACTION/MESSAGE errors are presented in the Info tab, which is easily missed.

Improve this with:

   * Error to be presented in all info tab
   * Mark VMs with error with an exclamation mark in the datatable

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to e approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1814
- Docs: https://github.com/OpenNebula/docs/pull/2177
