### ISSUE TITLE
VM list with blank IDs in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5747]
**Description**
When I return to the list of VMs from a Virtual Network, it appears without IDs.

**To Reproduce**

- Login to Sunstone.
- Go to "Virtual Networks" from Dashboard.
- Select one of the virtual network and click.
- Click on "VMs" in Instances.
- VM list with blank IDs will be displayed.
- Click the VM on this state, the information of ID:0 will be displayed.

**Expected behavior**
Habitual behavior.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12 and development

**Additional context**
![image](https://user-images.githubusercontent.com/33811723/155487165-30607bd6-3976-4715-97fa-5cece3c3978b.png)

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment]
PRs to merge:
- one: https://github.com/OpenNebula/one-ee/pull/1810
- doc: https://github.com/OpenNebula/docs/pull/2172
