### ISSUE TITLE
Allow VMRC connections with VMs not in the local zone

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#5749]
**Description**
When having a federation with OpenNebula, it will be useful to allow VMRC connections through not local zone machines.

This should also be considered in #5422 

**Use case**
Improve VM connectivity and usability.

## Progress Status
- [x] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
wontfix, covered in 5763 for KVM
