### ISSUE TITLE
Problem with the serveradmin password after an update

### ISSUE THREAD

**Issue by vickmp** [OpenNebula/one#5751]
**Description**
There is an error after the update that breaks the serveradmin password.
It is necessary to review where in the process this happens and how to solve it.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by ONdboca** [comment]
Issue could not be replicated when performing upgrade procedure from 6.4 to 6.6.
