### ISSUE TITLE
Simplify live memory resize for KVM

### ISSUE THREAD

**Issue by paczerny** [OpenNebula/one#5753]
**Description**
The live memory resize was implemented in #1660 , using `virsh attach-device` [described here](https://medium.com/@juergen_thomann/memory-hotplug-with-qemu-kvm-and-libvirt-558f1c635972). But this implementation has a lot of limitations, especially for removing the memory.
To remove the limitation, use `virsh setmem` as [described here](https://www.unixarena.com/2015/12/linux-kvm-how-to-add-remove-memory-to-guest-on-fly.html/) 

**Use case**
Easier live memory resizing for kvm

**Interface Changes**
None. 

**Additional Context**
New implementation doesn't need the [MEMORY_SLOTS attribute](https://docs.opennebula.io/6.2/open_cluster_deployment/kvm_node/kvm_driver.html#live-resize-vcpu-and-memory)

I haven't find which QEMU version is needed for this implementation

## Progress Status
- [ ] Branch created
- [x] Code committed to development branch
- [ ] Sunstone Testing - QA
- [x] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
PRs:
* [sources](https://github.com/OpenNebula/one-ee/pull/1820)
* [docs remove memory slots](https://github.com/OpenNebula/docs/pull/2182)
* [docs update resolved issues](https://github.com/OpenNebula/docs/pull/2183)

**Comment by rsmontero** [comment]
There are some valid use cases for the hotplug method (e.g. PCI passtrhough devices to allow DMA, improved support across guest OS...).

This feature is to include a MEMORY_RESIZE_MODE:
* ``balloon`` the actual implementation
* ``hotplug`` the previous one

**Comment by paczerny** [comment]
Two options for memory resize implemented, PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2340)
* [tests](https://github.com/OpenNebula/docs/pull/2424)

**Comment by FrederickBor** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/2387

**Comment by FrederickBor** [comment]
FSunstone testing: https://github.com/OpenNebula/development/pull/2122
