### ISSUE TITLE
React Sunstone host tab functionality

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5755]
**Description**

Complete host tab functionality with:

- [x]  4 bulk actions (select cluster - with dialog, enable, disable, offline)
- [x]  4 info tabs (VMs, Wilds, Zombies, NUMA)
- [x]  creation dialogs for all hypervisors except vCenter
- [x] Test Zombie VM tab
- [x] Overcommitment dialog

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- test: https://github.com/OpenNebula/development/pull/2207
- code: https://github.com/OpenNebula/one-ee/pull/2606
