### ISSUE TITLE
Service role action are not working in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5758]
**Description**
In v6.2 with the new scheduled actions implementation and refactor, Oneflow services can't perform an action through Sunstone.

**To Reproduce**
1. Instantiate a service 
2. Go to the Actions tab
3. Try to perform an action

**Expected behavior**
To be able to perform an action on Services.

**Details**
 - Affected Component: Sunstone
 - Version: 6.2, development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1825
- Docs: https://github.com/OpenNebula/docs/pull/2189
