### ISSUE TITLE
Just check immutable attributes in OneFlow when user provides them

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5759]
**Description**

Hello 

I'm trying to update a OneFlown service template with the ruby API and I got the following response:

```
`Immutable value: `service_template/registration_time` can not be changed (Exception)`
```

I got the same on the CLI with:

```
$ oneflow-template update myservice myservice.json
```

**To Reproduce**

1. Create a simple service template, [like](https://docs.opennebula.io/6.2/management_and_operations/multivm_service_management/appflow_use_cli.html)
   ```json
   {
     "name": "my_service",
     "deployment": "straight",
     "ready_status_gate": true|false,
     "roles": [
       {
         "name": "frontend",
         "vm_template": 0
       },
       {
         "name": "db_master",
         "parents": [
           "frontend"
         ],
         "vm_template": 1
       },
       {
         "name": "db_slave",
         "parents": [
           "frontend"
         ],
         "cardinality": 3,
         "vm_template": 2
       },
       {
         "name": "worker",
         "parents": [
           "db_master",
           "db_slave"
         ],
         "cardinality": 10,
         "vm_template": 3
       }
     ]
   }
   ```
2. Create the service with the following command
   ```
   $ oneflow-template create my_service.json
   ```
3. Try to update the service with the same template file
   ```
   $ oneflow-template update my_service my_service.json
   Immutable value: `service_template/registration_time` can not be changed
   ```

**Expected behavior**

The service should be updated without any problem when `registration_time` is not present in the template file.

**Details**
 - Affected Component: OneFlow
 - Hypervisor: KVM
 - Version: 6.2.0-1.ce

**Additional context**

I managed to update the service by extracting the current `registration_time` and injecting it to the `.json` file.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @baby-gnu,

The problem there is that you are updating the service template with the same information as you created it and that information does not contain the registration time, so the server gives you an error because of that.

This is the expected behavior, you can't change the value of the registration time, as other attributes, you can check the full list [here](https://docs.opennebula.io/6.2/management_and_operations/multivm_service_management/appflow_use_cli.html#update-service).

Best,
Álex.

**Comment by baby-gnu** [comment]
> This is the expected behavior, you can't change the value of the registration time, as other attributes, you can check the full list [here](https://docs.opennebula.io/6.2/management_and_operations/multivm_service_management/appflow_use_cli.html#update-service).

It's about `You can update a service in RUNNING state`, that's not my use case, I want to update the service `TEMPLATE`.

In my tests, I do not even start the service.

**Comment by al3xhh** [comment]
I'm mean you can't update the service template changing the registration time.

In your case you have a JSON that does not have registration time, when you create the template, the registration time is automatically added so when you try to update with the same JSON, this value is not there and the flow gives an error.

**Comment by baby-gnu** [comment]
> In your case you have a JSON that does not have registration time, when you create the template, the registration time is automatically added so when you try to update with the same JSON, this value is not there and the flow gives an error.

Yes, instead of a bug it could became a feature request ;-)

Providing a different registration time should trigger an error but a template without should be fine, to my opinion ;-)

For now, we will inject the current registration time in the template before updating it.

**Comment by al3xhh** [comment]
That would be nice, I will convert the issue into a feature request. If the user provides a value to an immutable attribute it will give an error, if not, there will be no error.

Thanks a lot for opening it!!!!

**Comment by vickmp** [comment]
PRs to merge:
- [Code](https://github.com/OpenNebula/one-ee/pull/1837)
- [Docs](https://github.com/OpenNebula/docs/pull/2197)
