### ISSUE TITLE
Hide VM name set on instantiation and VM rename operation

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5760]
**Description**

On certain scenarios it is a requirement that the end user does not set or change the VM name

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
VM rename can be disabled with `VM.rename: false` in the YAML view

@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1859
- Docs: Pending
