### ISSUE TITLE
React Sunstone to support Guacamole SSH/RDP/VNC in a federation

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5763]
**Description**
Normally when a connection is made via VMRC, the connection is: 
```mermaid
  graph TD;
      FireEdge_Reverse_Proxy-->ESX;
```

In the case of federations, there must be an additional proxy to avoid having to expose the different ESX.

```mermaid
  graph TD;
      FireEdge1_Reverse_Proxy-->FireEdge2_Reverse_Proxy;
      FireEdge2_Reverse_Proxy-->ESX;
```

**Interface Changes**
FireEdge , maybe Sunstone

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Franco-Sparrow** [comment]
@jloboescalona2 thanks to redirect me to this issue and close the duplicated one I opened. So, is not yet implemented this functionality. Please, note that the documentation should be more clear on this.
