### ISSUE TITLE
Improvements for Guacamole Console

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5766]
**Description**
Each protocol supported by Guacamole has its own set of [configuration parameters](https://guacamole.apache.org/doc/gug/configuring-guacamole.html#configuring-connections).

Improvements include:

- [x] Reboot button in VNC console

- [ ] ~~Check clipboard (copy&paste) across all options~~(not supported by qemu VNC)
- [ ] VNC
  - [x] `autoretry`
  - [x] `read-only`
  - [ ] `enable-audio`
  - [ ] `clipboard-encoding`
- [ ] RDP
  - [ ] changes `security` mode
  - [ ] `disable-auth`
  - [x] `server-layout`
  - [x] `resize-method`
  - [ ] `remote-app`
  - [x] Performance flags: `enable-wallpaper`, `enable-theming`, etc
  - [x] Implement `save_rdp` to download [connection file](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files) by external software
- [ ] SSH
  - [x] `command`
  - [ ] [Internationalization/Locale settings](https://guacamole.apache.org/doc/gug/configuring-guacamole.html#internationalization-locale-settings): `locale` and `timezone`
- [ ] Telnet
- [ ] [Kubernetes](https://guacamole.apache.org/doc/gug/configuring-guacamole.html#kubernetes)
  - [ ] Kubernetes support for Guacamole is provided by the `libguac-client-kubernetes` library
- [ ] [Common configuration options](https://guacamole.apache.org/doc/gug/configuring-guacamole.html#common-configuration-options)
  - [ ] Disabling clipboard
  - [ ] File transfer via SFTP (drag&drop)
  - [x] Terminal display settings (used by SSH, telnet, and Kubernetes support): `color-scheme`, `font-name`, etc
- [x] Shared connections by link (instead of Sunstone)

**Interface Changes**
Improves the Virtual Desktop Infrastructure in new Sunstone

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
the attributes for RDP connection: `server-layout`, `resize-method`, and all the available performance flags on guacamole documentation were included in https://github.com/OpenNebula/one-ee/pull/2234
