### ISSUE TITLE
Sunstone change the disk size unit to MB when using disk slider

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5771]
**Description**
When using the slider to change the disk size on VM instantiation, Sunstone changes the unit to MB.

**To Reproduce**
Instantiate a VM and try to change the disk size with the slider.

**Expected behavior**
To get the slider value on the correct unit.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.2, development

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/1851
- Docs: https://github.com/OpenNebula/docs/pull/2203
