### ISSUE TITLE
Single Sign On URL for React Sunstone

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5779]
WHMCS module can be improved by automatically logging in the created user.

Sunstone needs a mechanism to implement this auto log in feature.

## Progress Status
- [x] Branch created
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- code https://github.com/OpenNebula/one-ee/pull/1890
- test https://github.com/OpenNebula/development/pull/1795
