### ISSUE TITLE
Small fixes on the OneProvision GUI

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5780]
**Description**

- [x] [`Feature`] Add/remove required attribute to inputs on the "create provision" form
- [x] [`Feature`] Make also the name of the provision a link to the provision details
- [x] Card images sometimes don't display on the first render
- [x] Card images aren't adjusted when the description is on two lines
- [x] [`Feature`] Increase cache time for OneProvision templates requests
- [x] [`Feature`] Add images for on-prem resources
- [x] [`Feature`] Improve log messages
- [Alex feedback](https://docs.google.com/document/d/1MQQjnURzlrVKVznyTn0X2VaF7MHbcCwzyg6WSDRp3ow/edit)
    - [x] Permissions and ownership sections don't make any sense here, therefore, can be removed.
    - [x] If there is a progress circle, we can remove the "There is no data available" message while loading data
    - [x] Remove summary when the delete provider button is clicked.
    - [x] When configuring a provision is missing the force option.
    - [x] Configure host button should lead to the log tab and show the log there.
    - Fix messages:
      - [x] Show the message that indicates the action in green only if the action has been completed successfully
      - [x] When adding an IP or HOST in CONFIGURING, the error message is not shown. That can happen in other states.
      - [x] When deleting a provision that is CONFIGURING or has VMs, the error message is not shown. That can happen in other states.

**Comment by FrederickBor** [comment]
[Feature] Inputs required in create provision form
- https://github.com/OpenNebula/one-ee/pull/1940

**Comment by FrederickBor** [comment]
Card images sometimes don't display on the first render
- https://github.com/OpenNebula/one-ee/pull/1942

**Comment by FrederickBor** [comment]
[Alex feedback](https://docs.google.com/document/d/1MQQjnURzlrVKVznyTn0X2VaF7MHbcCwzyg6WSDRp3ow/edit): Permissions and ownership sections don't make any sense here, they can be removed.
- https://github.com/OpenNebula/one-ee/pull/1944

**Comment by FrederickBor** [comment]
`Feature` Make also the name of the provision a link to the provision details:
- https://github.com/OpenNebula/one-ee/pull/1970

 Card images aren't adjusted when the description has 2 lines:
- https://github.com/OpenNebula/one-ee/pull/1971

**Comment by FrederickBor** [comment]
If there is a progress circle, we can remove the "There is no data available" message while loading data
- https://github.com/OpenNebula/one-ee/pull/2060

**Comment by FrederickBor** [comment]
Remove summary when the delete provider button is clicked.
- https://github.com/OpenNebula/one-ee/pull/2181

**Comment by FrederickBor** [comment]
Configure host button should lead to the log tab and show the log there.
- https://github.com/OpenNebula/one-ee/pull/2186
