### ISSUE TITLE
Improve upgrade documentation for maintenance upgrades of HA/Fed environments

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5788]
**Description**
When updating HA/Fed environments between two maintenance releases (e.g 6.0.0 -> 6.0.2) the current documentation might be misleading.

HA/Fed upgrade guides assume the upgrade is perform between two different minor/major releases, which require extra steps don't needed for maintenance upgrades..

**Details**
 - Affected Component: Docs

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge

- [master](https://github.com/OpenNebula/docs/pull/2229)
- [6.2](https://github.com/OpenNebula/docs/pull/2230)
