### ISSUE TITLE
Different range for limiting CPU at CgroupV2

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5792]
**Description**
In order to define the relative amount of CPU that a VM will use in an specific host, the `cpu.shares` attribute is set:

```
cpu.shares: The weight of each group living in the same hierarchy, that
translates into the amount of CPU it is expected to get. Upon cgroup creation,
each group gets assigned a default of 1024. The percentage of CPU assigned to
the cgroup is the value of shares divided by the sum of all shares in all
cgroups in the same level.
```
With the introduction of Cgroup V2 the `cpu.weight` attribute is used instead:

```
cpu.weight: A read-write single value file which exists on non-root cgroups.
The default is "100". The weight in the range [1, 10000].
``` 

As the ranges of `cpu.shares` and `cpu.weight` defers, the value of CPU behaves differently depending on the environment. Note the lower limit of `cpu.weight` which with the current implementation will lead into a limit for CPU attribute of 9.

**Expected behavior**
This behavior differences should be documented and the use of Cgroup V1 should be recommended. 

**Details**
 - Affected Component: VMM
 - Hypervisor: KVM
 - Version: master

**Additional context**
   - https://bugzilla.redhat.com/show_bug.cgi?id=2037734
   - https://kernel.googlesource.com/pub/scm/linux/kernel/git/glommer/memcg/+/cpu_stat/Documentation/cgroups/cpu.txt
   - https://www.kernel.org/doc/Documentation/cgroup-v2.txt

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
KVM 
* Add new CGROUP_VERSION attribute that can be defined in `vmm_exec_kvm.conf`, cluster or host. So this will allow to mix v1 and v2 in the same installation
* Based on version we set:
  - base 100 for v1 and 1024 v2
  - max 10000 and 262144 respectively 
  - min 1 and 2, respectively 
 * Defaults values would be v1, documentation will spell out this setup

**Comment by atodorov-storpool** [comment]
Being on the cgroups topic, what about #1354?

**Comment by atodorov-storpool** [comment]
Also

> Add new CGROUP_VERSION attribute that can be defined in vmm_exec_kvm.conf, cluster or host. So this will allow to mix v1 and v2 in the same installation

IMHO isn't better to have this reported by the host monitoring?

**Comment by rsmontero** [comment]
> Also
> 
> > Add new CGROUP_VERSION attribute that can be defined in vmm_exec_kvm.conf, cluster or host. So this will allow to mix v1 and v2 in the same installation
> 
> IMHO isn't better to have this reported by the host monitoring?

Yes it make sense

**Comment by rsmontero** [comment]
> Being on the cgroups topic, what about #1354?

So maybe it'd be better to discuss there, but let me summary the discussion here just to see if we can address this together.

#1354, you are proposing that we automatically set RESERVED_* from the configuration of the machine.slice?

**Comment by atodorov-storpool** [comment]
Well it was for a very old ONE version.

I think about monitoring to report the CPUs and memory available in the machine.slice cgroup. This way RESERVED_* will be used entirely for oversubscription purposes. For example, a host with 256GB RAM and 40 threads could have 196GB and 32 threads available in the machine.slice. So in OpenNebula a KVM host should have 196GB available for VMs and 32 threads. Also, the un-available resources that are omitted in the cpuset.cpus and cpuset.mems I think should be accounted as "isolated"(or unavailable) for the NUMA configuration by the monitoring. This way, with RESERVED_* a true oversubscription could be defined by the users, so they don't need to know that there is an additional math to have the final values for oversubscription...
