### ISSUE TITLE
Link in Docs to PyOne bindings is a 404.

### ISSUE THREAD

**Issue by bsanders** [OpenNebula/one#5797]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Dead link to PyOne bindings.

**To Reproduce**
Go to: https://docs.opennebula.io/6.2/integration_and_development/system_interfaces/python.html

At the very bottom, under the Credits header, the link to [PyONE](https://github.com/OpenNebula/addon-pyone) leads to a 404.

**Expected behavior**
I wanted to see the source for the pyone python code.

**Details**
It's in the live documentation.

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by bsanders** [comment]
Follow up, I found it (cuz I did actually want to look at it) here: https://github.com/OpenNebula/one/tree/master/src/oca/python

The README.rst there actually also contains the same 404 dead link.

**Comment by tinova** [comment]
link updated to point to the original pyone implementation
