### ISSUE TITLE
Be able to change currency test in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5799]
**Description**
Sunstones shows a `K` symbol when adding costs to the templates, it would be nice to be able to add some currency string via configuration YAMLs.

**Use case**
Show the cost in the local currency.

**Interface Changes**
Sunstone.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
to be addressed in FireEdge Sunstone only

**Comment by tinova** [comment]
addressed in https://github.com/OpenNebula/one-ee/commit/705e9779ee1893011b758c88154a39dd6fc5f2d9
