### ISSUE TITLE
No action allowed when VM import process fails

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5800]
**Description**
If something fails when a VM is being imported (e.g VNC port collisions) the VM will be left in `HOLD` state with no history record. 

This will cause every action to fail, as the VM is marked as `IMPORTED` but it has no history record. History records are used for retrieving the `VM_MAD` driver, so `oned` can check if the specific action is supported for imported VMs. As a result of this no action can be performed on the VM unless the `IMPORTED` mark is removed.

**Expected behavior**
Being able to remove or recover the VM if something fails during the import process.

**Details**
 - Affected Component: `oned`
 - Version: master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
In case of wild import failure fallback to user_template/hypervisor to be able to execute actions
PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2150)
* [doc](https://github.com/OpenNebula/docs/pull/2319)
