### ISSUE TITLE
Where is the source of opennebula-guacamole located?

### ISSUE THREAD

**Issue by Igorgro** [OpenNebula/one#5805]
Hi, i found out that opennebula uses its own implementation of guacamole client (https://www.npmjs.com/package/opennebula-guacamole) which is licensed under Apache License but I cannot find any source code repository for this package. Where can I get this source code?

**Comment by sbbarragan** [comment]
Hi @Igorgro, we redistribute compiled Guacamole just for OpenNebula needs

**Comment by Igorgro** [comment]
But the label says that it is licensed under Apache 2.0, so this is not a truth, is it?
