### ISSUE TITLE
Can't create token with lifetime `forever`

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#5806]
**Description**

I can't create a token with a liftetime of `forever` either with Sunstone or from CLI as described in `oneuser token-create --help`:

```
$ oneuser token-create --help
…
     --time x                  Token duration in seconds, defaults to 36000 (10
                               h). To reset the token set time to 0.To generate
                               a non-expiring token use -1 (not valid for ssh
                               and x509 tokens).
```

**To Reproduce**

1. `oneuser token-create me --time -1`

**Expected behavior**

The `--time -1` should produce a token with a lifetime of forever.

**Details**
 - Affected Component: Sunstone, CLI
 - Hypervisor: KVM
 - Version: 6.2.0-1.ce

**Additional context**

I manually edit the tokens with `onedb update-body user --id <USER_ID>`.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @baby-gnu,

Tried to reproduce it on 6.4, but I wasn't able to:

```
$ oneuser token-create alex --time -1    
Password: 
Authentication Token is:
alex:2e695b5096b6c942919f48630c24c96ce532014f64b3ee198e5274068a148192

TOKENS                                                                          
     ID EGID  EGROUP     EXPIRATION          
2e695b5 *1    users      forever
```

Could you please share with us what kind of error are you getting?

**Comment by baby-gnu** [comment]
> Could you please share with us what kind of error are you getting?

On OpenNebula 6.2, I create the token with `--time -1`:

```
$ oneuser token-create dad --time -1
Password: 
  * Do you want to overwrite the file /home/eole/.one/one_auth? (Y|N): 
n
File /home/eole/.one/one_auth exists, use --force to overwrite.
Authentication Token is:
dad:75e8efa7951c8b24eeca4bd72a661c8f0969dca5cfeb510392a51c95a30ce82e
```

But the `EXPIRATION_TIME` of that token is not `-1`:

```
$ oneuser show -x dad | xpath -e '/USER/LOGIN_TOKEN[TOKEN="75e8efa7951c8b24eeca4bd72a661c8f0969dca5cfeb510392a51c95a30ce82e"]'
Found 1 nodes in stdin:
-- NODE --
<LOGIN_TOKEN>
    <TOKEN>75e8efa7951c8b24eeca4bd72a661c8f0969dca5cfeb510392a51c95a30ce82e</TOKEN>
    <EXPIRATION_TIME>1654843958</EXPIRATION_TIME>
    <EGID>-1</EGID>
</LOGIN_TOKEN>
```

Regards.

**Comment by baby-gnu** [comment]
I confirm that it's working fine on `6.4.0-1`.

**Comment by al3xhh** [comment]
Thanks for testing it @baby-gnu! As 6.2.0 has reached EOL, I will close this issue.
