### ISSUE TITLE
command `oneprovision host ssh` fails

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5815]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
```
$ oneprovision host ssh 54.224.119.75

undefined method `info' for nil:NilClass
```

**To Reproduce**
install MiniONE + oneprovision AWS single node (hci) cluster

**Expected behavior**
ssh works

**Details**
 - Affected Component: oneprovision
 - Version: 6.4

**Additional context**

## Progress Status
- [ ] Code commited
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2136)
- [docs](https://github.com/OpenNebula/docs/pull/2309)
