### ISSUE TITLE
Downloading OneFlow service twice with the same name fails with 500

### ISSUE THREAD

**Issue by sk4zuzu** [OpenNebula/one#5818]
**Description**
When an app is downloaded from **one** markerplace (for example **Service Kubernetes 1.23**) and some resources already exist Sunstone fails and this criptic error is logged into the `/var/log/one/sunstone.log` file:
```
Mon May 09 16:31:21 2022 [I]: ::1 - - [09/May/2022:16:31:21 +0000] "POST /marketplaceapp/589/action HTTP/1.1" 500 - 0.0248
```

**To Reproduce**
- It is enough to download a service once and then retry keeping the same value in the **Name** box.
- The other way would be to instantiate a service from templates, then delete templates using **Delete Images and VM Templates**. Because VMs are running, disk images are not deleted and downloading the service again will cause the same conflict(s) and error.

**Expected behavior**
- User should be notified about the conflict with a human readable explanation, the error message should not be a raw 500..
- User should be informed what needs to be done to workaround the problem (it's either resource cleanup or service name change).

**Details**
 - Affected Component: Sunstone
 - Hypervisor: NA
 - Version: ALL

**Additional context**
NO

## Progress Status
- [x] Code commited
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by onenhansen** [comment]
PRs associated with this issue:
https://github.com/OpenNebula/development/pull/1975
https://github.com/OpenNebula/docs/pull/2355
https://github.com/OpenNebula/one-ee/pull/2215
https://github.com/OpenNebula/one-ee/pull/2227
