### ISSUE TITLE
oned.conf debug levels only covers 0-3, but oned has 0-5 levels

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5820]
```
    enum MessageType {
        ERROR   = 0,
        WARNING = 1,
        INFO    = 2,
        DEBUG   = 3,
        DDEBUG  = 4,
        DDDEBUG = 5
    };
```

Adjust oned.conf

## Progress Status
- [ ] Code commited
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/2135)
- [docs](https://github.com/OpenNebula/docs/pull/2308)
