### ISSUE TITLE
Can't instantiate VMTemplates when setting VM.instantiate_name to false

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5826]
**Description**
When setting VM.instantiate_name to false, users can't instantiate VM templates.

**To Reproduce**
Go to the view YAML configuration file and set `VM.instantiate_name` to false.

**Expected behavior**
To be able to instantiate VMTemplates when this setting is disabled.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4, development

## Progress Status
- [x] Code commited
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2059
- Docs (Known issues): https://github.com/OpenNebula/docs/pull/2277
- Docs (Resolved issues): https://github.com/OpenNebula/docs/pull/2278
