### ISSUE TITLE
onedb upgrade error ”Schema not found (acl) for version 5.12.0“

### ISSUE THREAD

**Issue by skCNA** [OpenNebula/one#5829]
5.10  version   upgrade    5.12 version

onedb upgrade -v /etc/one/oned.conf

mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
MySQL dump stored in /var/lib/one/mysql_localhost_opennebula_2022-5-19_8:54:12.sql
Use 'onedb restore' or restore the DB using the mysql command:
mysql -u user -h server -P port db_name < backup_file

>>> Running migrators for shared tables
Schema not found (acl) for version 5.12.0

exit
/usr/lib/one/ruby/onedb/database_schema.rb:150:in `exit'
/usr/lib/one/ruby/onedb/database_schema.rb:150:in `get_schema'
/usr/lib/one/ruby/onedb/database_schema.rb:163:in `create_table'
/usr/lib/one/ruby/onedb/shared/5.10.0_to_5.12.0.rb:43:in `feature_3600'
/usr/lib/one/ruby/onedb/shared/5.10.0_to_5.12.0.rb:31:in `up'
/usr/lib/one/ruby/onedb/onedb.rb:233:in `apply_migrators'
/usr/lib/one/ruby/onedb/onedb.rb:161:in `upgrade'
/usr/bin/onedb:419:in `block (2 levels) in <main>'
/usr/lib/one/ruby/cli/command_parser.rb:470:in `call'
/usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
/usr/bin/onedb:324:in `new'
/usr/bin/onedb:324:in `<main>'

The database will be restored
mysql: [Warning] Using a password on the command line interface can be insecure.
MySQL DB opennebula at localhost restored.

what should I do？

**Comment by atodorov-storpool** [comment]
>
> onedb upgrade -v /etc/one/oned.conf

mysqldump: [Warning] Using a password on the command line interface can be
> insecure.
> mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS
> privilege(s) for this operation' when trying to dump tablespaces


 what should I do？


You must follow exact procedure, described in the upgrade documentation.
https://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#step-7-upgrade-the-database-version

The issue is derailing from the topic! You could seek for help on the
Community forum https://forum.github.io

BR,
Anton

**Comment by skCNA** [comment]
thanks
