### ISSUE TITLE
When updating VM configuration in Sunstone the Input/Output tab is missing

### ISSUE THREAD

**Issue by bgmastermind** [OpenNebula/one#5831]
**Description**
When updating VM configuration in Sunstone the Input/Output tab is missing. It works in fireedge

**To Reproduce**
Click update configuration of existing VM. 

**Expected behavior**
To see the tab

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.4

**Additional context**
I have PCI devices on that VM

## Progress Status
- [ ] Code commited
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Hi @bgmastermind 

Could you please provide a screenshot of where React Sunstone is working with the update configuration?

**Comment by bgmastermind** [comment]
Old sunstone
![image](https://user-images.githubusercontent.com/24807093/170200164-f639278f-7307-4ae7-800c-8ab084b9beb3.png)

I would provide from react sunstone, but i can't find the button update configuration which somehow I found previous time. Should the button be visible if the VM is off?

**Comment by FrederickBor** [comment]
Hi @bgmastermind

This issue will need core support since PCI devices can't be updated with UpdateConf. You can find a list of the allowed actions (here)[https://docs.opennebula.io/6.4/integration_and_development/system_interfaces/api.html#one-vm-updateconf].

On React Sunstone, this functionality is still not implemented, that's the reason for this button to be hidden.

**Comment by bgmastermind** [comment]
Older versions allowed changing everything else, without the PCI devices. And Input/Output was available regardless.
I don't know what i saw in react version though. Probably was template update and got it confused with VM config update.

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2104

This will be considered in #5422 to only have the available options in VM.updateconf

**Comment by tinova** [comment]
closing, it will be activated in next versions of Ruby Sunstone, but fine tuned only for FireEdge Sunstone
