### ISSUE TITLE
FireEdge Sunstone Virtual Network Tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5832]
**Description**

Related to #5422.

FireEdge Sunstone needs a complete VNET tab:

- [x] Actions - buttons to operate over the datatable items
   - [x] Create / Instantiate / Reserve 
   - [x] Update / Clusters / Lock
   - [x] Change Owner/Group
 - [x] Infotabs - tabs to show extended information about one selected item from datatable
   - [x] Info
   - [x] Addresses
   - [x] Leases
   - [x] Security
   - [x] Virtual Routers
   - [x] Clusters
 - [x] Dialog Create / Update as Stepper
   - [x] General
   - [x] Conf
   - [x] Addresses
   - [x] Security
   - [x] QoS
   - [x] Context
  
## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by sbbarragan** [comment]
PRs to merge:
  - one:
     - https://github.com/OpenNebula/one-ee/pull/2222
     - https://github.com/OpenNebula/one-ee/pull/2221
  - dev: _pending_
  - doc: _pending_
