### ISSUE TITLE
zombie VMs due to wrong VNC port assignment

### ISSUE THREAD

**Issue by zinikh** [OpenNebula/one#5834]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
while importing multiple wild VMs, a large number of VMs were assigned already used ports resulting in these VMs becoming zombies

**To Reproduce**
import large number of VMs

**Expected behavior**
each VM should be assigned VNC port = 5900 + vm oid

**Details**
 - Affected Component: Sunstone, database,
 - Hypervisor: [VCenter server 6.7.2]
 - Version: [6.4]

**Additional context**
editing configuration using onevm updateconf <vmid> doesn't work, gives error "[one.vm.updateconf] Action "updateconf" is not supported for imported VMs"

## Progress Status
- [ ] Code commited
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by zinikh** [comment]
@tinova @carloshm91 why is this tagged as "feature" instead of "bug". the opennebula assigned the same VNC port to multiple VMs which is causing them to be zombies.

**Comment by tinova** [comment]
OpenNebula maintains a bitmap with all already used VNC ports. If the Wild VMs already have remotedisplay.* attributes, they may have a fixed VNC port, which if it happens to be in use by another VM known by OpenNebula, will cause the described behaviour. Could you please check this is the case in your scenario?

This is marked as a feature to implement a mechanism to automatically change/wipe these existing remotedisplay.* keys on wild import. If it turns out this is really a bug, then we'll create a separate ticket for the feature, and turn this into a bug ticket

**Comment by zinikh** [comment]
@tinova that is exactly what it is, all my VMs have a preset RemoteDisplay.vnc.port and opennebula assigned the same ports from the advanced configuration. so the port overlap is from vcenter not from opennebula.
any idea how to fix my environment ? i have 9 out of 41 VMs so far having this problem, i stopped importing additional VMs pending the fix.

**Comment by tinova** [comment]
quickest way is probably to use VMRC (VNC is deprecated in vSphere 7.0). OpenNebula 6.4 allows the use of VMRC through Sunstone and FireEdge.

to keep using VNC, i suggest removing the remotedisplay* attributes. There is a utility in OpenNebula (onevcenter cleartags), unfortunately only for imported VMs. However, with a bit of ruby scripting you can use it for non imported VMs in vCenter: https://github.com/OpenNebula/one/blob/master/src/cli/one_helper/onevcenter_helper.rb#L523

**Comment by zinikh** [comment]
thanks, i ended up reinstalling opennebula and starting from scratch after removing the three remotedisplay attributes using powercli. is there an easy way to remove VMs (in any state) and re-importing them again ? or at least a way to reset the environment ?

**Comment by tinova** [comment]
In order to remove the VM from OpenNebula without removing it from vCenter the recover command can be used:

`onevm recover --delete-db <vm_id>`

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one-ee/pull/2164

[DOC]
* https://github.com/OpenNebula/docs/pull/2343
