### ISSUE TITLE
Allow DISK_TYPE = BLOCK for system datastores

### ISSUE THREAD

**Issue by rp-** [OpenNebula/one#5838]
**Description**
Since [qemu 6.0](https://wiki.qemu.org/ChangeLog/6.0), it is no longer possible to use a block device as a normal file:
> * The file block driver no longer permits use with block devices

This is a problem e.g. if using a system DS that uses a DRBD block device (with live migration), until qemu 6.0 this just worked.
Mostly because qemu didn't care if the provided path was a file or a block device, but now they do.

**To Reproduce**
Try to create a system DS with DISK_TYPE = BLOCK

**Expected behavior**
Allowing system DS to have DISK_TYPE=BLOCK so DRBD(or other) block devices can be used.

**Details**
 - Affected Component: Storage
 - Hypervisor: KVM
 - Version: 6.0/6.2

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
The issue was opened _years_ ago as #3245 lately topped with the related #5681 and had workarounds implemented by dark magic and curses since then... :-/

**Comment by rsmontero** [comment]
Initial commit (together with other changes) now in master

**Comment by rsmontero** [comment]
I think the commit closes #3245 (DISK_TYPE will be inherited from the datastore setting when the VM is deployed, or disk attached) @atodorov-storpool

**Comment by atodorov-storpool** [comment]
not resolved entirely. see https://github.com/OpenNebula/one/issues/3245#issuecomment-1282238188

**Comment by megastallman** [comment]
Please reopen the issue. It still happens on system Linstor datastore, Opennebula 6.8, Ubuntu 22.04, Qemu 6.2+dfsg-2ubuntu6.15, DISK_TYPE=BLOCK.
See detailed logs in https://github.com/OpenNebula/addon-linstor/issues/18

**Comment by JavadHosseini** [comment]
I'm having the same issue, I added CONTEXT_DISK_TYPE = BLOCK to system ds but I still get 'file' driver requires disk.1 to be a regular file.
image_ds:
```
CONTEXT_DISK_TYPE	BLOCK	 
DISK_TYPE	BLOCK	 
DISK_TYPE_SSH	BLOCK	 
DRIVER	raw
TM_MAD	fs_lvm
```
system ds:
```
CONTEXT_DISK_TYPE	BLOCK
DISK_TYPE	BLOCK
TM_MAD	fs_lvm
```
