### ISSUE TITLE
The required inputs are hidden in the create vnet dialog

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5839]
**Description**
The form to create Virtual Networks is bugged after change the `Network mode` selector multiple times.
**Same for VNet Template create form.**

**To Reproduce**
- Go to vnet dialog
- Fill required inputs:
  - Name
  - Add 1 A.R.
- Then go to the `Conf` tab and change `Network mode` selector  several times.
Eg: `bridged` => `802.1Q` => `vCenter` => `bridged`
- Finally, press create button and see the error

**Expected behavior**
Error message shouldn't appear if the required inputs are hidden

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: development

**Additional context**
![image](https://user-images.githubusercontent.com/59608355/170075558-35f2d72e-2590-42e8-8452-d0809efc3ed9.png)

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2392
- Docs: https://github.com/OpenNebula/docs/pull/2439
