### ISSUE TITLE
FireEdge onprem HCI errors

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5840]
**Description**
HCI onprem cluster deployment is affected by a couple of minor error/typos:

   - The provider filed at `usr/share/one/oneprovision/edge-clusters/metal/provisions/onprem.d/fireedge.yml` should be `onprem` instead of `oneprem`.
   - When any of the `Hosts to run ...` fields are empty it will result in the creation of a host named `undefined`.

**Details**
 - Affected Component: FireEdge - OneProvision - HCI Deployment
 - Version: 6.4.0

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by sbbarragan** [comment]
PRs to merge:
- https://github.com/OpenNebula/one-ee/pull/2075
