### ISSUE TITLE
Extend onelog with object logs

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#5844]
**Description**
onelog could provide functionality to also get instances logs like VMs, vRouters, oneflow services

**Use case**
Usability

**Interface Changes**
```
onelog get --instance vm --id <vm_id>
```

`--instance` could be vm, vr, flow, for example

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2091)
- [docs](https://github.com/OpenNebula/docs/pull/2291)
