### ISSUE TITLE
KVM wilds are not correctly retrieved

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5846]
**Description**
KVM motorization does not return wilds correctly.

**To Reproduce**
Have a wild VM.

**Expected behavior**
Wilds should be returned with name and import template.

**Details**

 - Hypervisor: KVM
 - Version: 5.12, 6.2, 6.4

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2094)
- [docs](https://github.com/OpenNebula/docs/pull/2292)
