### ISSUE TITLE
Clicking on VMRC doesn't trigger any event or error

### ISSUE THREAD

**Issue by zinikh** [OpenNebula/one#5847]
**Description**
I have imported a vcenter with several test VMs with multiple operating systems (windows, linux, ...). when i login to the sunstone gui and try to connect to the VM console using VMRC nothing happens. I see a small message "VM startvmrc_action: _vmid_" at the bottom right of screen but no error message or anything but VMRC doesn't start.

**To Reproduce**
import Vcenter cluster, import VMs / datastores / network..., try to connect to VM console using VMRC

**Expected behavior**
VMRC window is launched and connects to the VM console.

**Details**
 - Affected Component: [e.g. Sunstone, VMRC]
 - Hypervisor: [e.g. Vcenter 6.7.2]
 - Version: [6.4]

**Additional context**
VM advanced config show the following graphics configuration:

LISTEN   0.0.0.0
PORT   5940
TYPE   vnc

</body>
</html>

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
common checks (assuming you are using Ruby Sunstone, port 9869):

 * is fireedge running?
 * are fireedge endpoints correctly configured in sunstone-server.conf?
 * any hints on sunstone and fireedge {.log, .error} files?

**Comment by zinikh** [comment]
I am running opennebula appliance, so i haven't configured anything manually. there are multiple ports used by Ruby but none of them is 9869.
- fireedge is running
- fireedge endpoints in sunstone-server.conf are ":private_fireedge_endpoint: http://localhost:2616" and ":public_fireedge_endpoint: http://172.16.100.121:80" - that's the local IP of opennebula
- fireedge.error is empty, fireedge.log has the below error whenever i click on VMRC 

GET /fireedge/api/vcenter/token/39?csrftoken=670d05f4ac065173ed851e328ff4399f3a8206b188440a3202d23155ff9ce275 HTTP/1.1" 500 89 "http://172.16.100.121/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

**Comment by tinova** [comment]
Thanks for the info. It seems to be configured properly.

Can you try the VMRC functionality from the FireEdge Sunstone interface? "http://172.16.100.121/fireedge/sunstone"

Please be aware that OpenNebual 6.4.0 is not tested over vSphere 6.7: https://docs.opennebula.io/6.4/intro_release_notes/release_notes/platform_notes.html#vcenter-nodes. If VMRC doesn't work in FireEdge Sunstone please consider upgrading your vSphere install.

**Comment by pmartins21** [comment]
I have the same issue. We are running VMware vCenter 7.x.

In the browser console I get following error:

error.js:30 Uncaught TypeError: Cannot set properties of undefined (setting 'http_status')
    at Error (error.js:30:1)
    at Object.error (vm.js:638:1)
    at fire (jquery.js:3187:1)
    at Object.fireWith [as rejectWith] (jquery.js:3317:1)
    at done (jquery.js:8759:1)
    at XMLHttpRequest.<anonymous> (jquery.js:9123:1)

Fireedge is running and is configured in sunstone-server.conf. VMRC is also not running in Fireedge:

"GET /fireedge/api/vcenter/token/0 HTTP/1.1" 500 89 "https://one01.vienna.lab.fullstacks.eu/fireedge/sunstone/wmks/0"

**Comment by FrederickBor** [comment]
Hi @pmartins21,
Could you please provide us with the following files so we can evaluate the error:
- sunstone-server.conf
- fireedge-server.conf
- Exact VMware vCenter 7.X that you have installed

**Comment by FrederickBor** [comment]
Hi @pmartins21,

Can you please confirm us that `http://one.local/` points directly to FireEdge?

If this is not the case, and it is the correct endpoint, please add the port to the endpoint (e.g. `http://one.local:2616/`).
The `public_fireedge_endpoint` configuration must be an accessible endpoint from all the browsers where Sunstone will be accessed.

**Comment by FrederickBor** [comment]
Hi @pmartins21

As you confirmed that you could access the VMRC through FireEdge, the problem should be in the configuration.

Can you please confirm that when you log in to Ruby Sunstone, you don't see any error messages referred to FireEdge? 

On the other hand, can you confirm that you have Sunstone & FireEdge on the same machine? If so, we recommend changing the private_fireedge_enpoint to localhost:2616 as it is used only for private communications. Otherwise, and they are on the same private network, we suggest changing it to <fireedge-server-ip>:2616.

If none of the above works, please provide us with your apache2 configuration.

**Comment by FrederickBor** [comment]
Hi @pmartins21,

Could you disable the apache2, configure both of the endpoints as `http://localhost:2616/` and try to connect through VMRC.

After that, if it's still not working, could you provide us with some screenshots for more information?
The ones that we'll need are: 
- Screenshot of the browser console where we can see the error thrown by Sunstone when you try to connect via VMRC.
- Screenshots of the network tab where we can see the call to the FireEdge server (click on it and take the screenshot of the Headers, Payload, and Response tab).

Regards,
Frederick
