### ISSUE TITLE
Bug in send_to_monitor function

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#5855]
**Description**
`send_to_monitor` function uses augtool command with `-l` option, which was introduced in augeus 1.5.* version of package.

EL7 (CentOS7, OracleLinux 7, RHEL7) have augeus 1.4 version, which doesnt support this `-l` option.

https://github.com/OpenNebula/one/blob/abb362f5c5b424b6cacd52b9cbba8fdaf9a3d869/src/mad/sh/scripts_common.sh#L1188

**To Reproduce**
Try to `tm/monitor` VM Disks on EL7 installation. Monitoring doesn't work with error about missing hostname (not read from monitord.conf properly)

**Expected behavior**
`tm/monitor` VM Disks on EL7 installation just works

**Details**
 - Affected Component: [Monitor]
 - Hypervisor: [ANY]
 - Version: [5.12+]

**Additional context**
I tried to compile augeus from sources, installed to `/usr/local/bin/augtool`. I also have to copy lens to `/usr/local/share/augeas/lenses/oned.aug`

When I tried to tm/monitor, it returns again with error `Ncat: Could not resolve hostname ""192.168.44.25"": Name or service not known. QUITTING.` - Double quoted hostname.
So I removed quotes from monitord.conf file and it is working now. I don't know, if other scripts will be working without quotes on `MONITOR_ADDRESS` value.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by feldsam** [comment]
What about removing augtool usage and do it only by grep

```
From 4f4be05386609ccc90946f3c17017216b4c23427 Mon Sep 17 00:00:00 2001
From: Kristian Feldsam <feldsam@gmail.com>
Date: Wed, 1 Jun 2022 19:57:27 +0200
Subject: [PATCH] send_to_monitor remove usage of augtool

Signed-off-by: Kristian Feldsam <feldsam@gmail.com>
---
 src/mad/sh/scripts_common.sh | 7 +++----
 1 file changed, 3 insertions(+), 4 deletions(-)

diff --git src/mad/sh/scripts_common.sh src/mad/sh/scripts_common.sh
index 0d2f5b5e2e..42275610cd 100644
--- src/mad/sh/scripts_common.sh
+++ src/mad/sh/scripts_common.sh
@@ -1185,10 +1185,9 @@ function send_to_monitor {
         mon_conf=$ONE_LOCATION/etc/monitord.conf
     fi
 
-    mon_config=$(augtool -L -l $mon_conf ls /files/$mon_conf/NETWORK)
-    mon_address=$(echo "$mon_config" | grep MONITOR_ADDRESS | awk '{print $3}')
-    mon_port=$(echo "$mon_config" | grep PORT | awk '{print $3}')
-    mon_key=$(echo "$mon_config" | grep PUBKEY | awk '{print $3}' | \
+    mon_address=$(cat $mon_conf | grep MONITOR_ADDRESS | cut -d , -f1 | awk '{print $3}')
+    mon_port=$(cat $mon_conf | grep PORT | cut -d , -f1 | awk '{print $3}')
+    mon_key=$(cat $mon_conf | grep PUBKEY | cut -d , -f1 | awk '{print $3}' | \
         sed 's/^"\(.*\)"$/\1/')
 
     if [[ $mon_address == *"auto"* ]]; then
-- 
2.32.1 (Apple Git-133)

```

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2124)
- [docs](https://github.com/OpenNebula/docs/pull/2300)

**Comment by tinova** [comment]
Thanks @feldsam for the suggestion!
