### ISSUE TITLE
Charters in sunstone shows non-sense times when action is not relative

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#5856]
**Description**
When VM action is added and is not relative, charter show wrong time left

<img width="264" alt="Screenshot 2022-06-01 at 22 58 08" src="https://user-images.githubusercontent.com/951648/171503214-34817160-21fd-412e-ae94-edcbe91d0fbd.png">

**To Reproduce**
Add VM action with non-relative time

**Expected behavior**
Proper time left shown

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [ANY]
 - Version: [5.12+]

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
added upstream, will be available in upcoming releases
