### ISSUE TITLE
double VM_POOL element in onevm list -x

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5858]
**Description**
The command is returning doubled/nested VM_POOL element:

```xml
$ onevm list -x
<VM_POOL>
<VM_POOL>
  <VM>
    <ID>3</ID>
    ...
  </VM>
  <VM>
    <ID>2</ID>
    ...
  </VM>
  <VM>
    <ID>1</ID>
    ...
  </VM>
</VM_POOL>
</VM_POOL>
```

**To Reproduce**
Run `onevm list -x`

**Expected behavior**
Only one VM_POOL element.

**Details**
 - Affected Component: [cli]
 - Hypervisor: [KVM]
 - Version: [6.4]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2122)
- [docs](https://github.com/OpenNebula/docs/pull/2298)

**Comment by rsmontero** [comment]
Thanks!
