### ISSUE TITLE
Sunstone wrong font-color on cloud view and admin view vm instatiate network

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#5859]
**Description**
Font color is light blue on white backround, which is not readable well

**Expected behavior**
Standard font color

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [ANY]
 - Version: [6.2]

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
New React Sunstone has a different color scheme, please reopen if the same issue is found in it. We won't be investing more in Ruby Sunstone.
