### ISSUE TITLE
Window server assign IPv4 is wrong (KVM)

### ISSUE THREAD

**Issue by dont32** [OpenNebula/one#5868]
I install window server 2016 on opennebula KVM but IPV4 from gateway and ethernet is different
![image](https://user-images.githubusercontent.com/23291353/172586301-3707ab11-e179-4bcd-8220-abb148f66e62.png)
Static IP config on ethernet is right
![image](https://user-images.githubusercontent.com/23291353/172586988-82f6202d-7b2b-4231-bac0-a51d9ef886ea.png)

**Comment by al3xhh** [comment]
Hello @dont32,

Have you install [OpenNebula context](https://github.com/OpenNebula/addon-context-windows) packages?

**Comment by dont32** [comment]
@al3xhh Yes, I installed addon-context-windows 6.2 .

**Comment by dont32** [comment]
I have fixed. I will close this thread
