### ISSUE TITLE
Sunstone does not create VM Templates with memory cost in GB

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5873]
**Description**
When creating a VM template and set memory cost in GB, Sunstone throws an error when clicking the create button.

**To Reproduce**
Try to create a VM Template and set memory cost in GB.

**Expected behavior**
The VM Template to be created.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4 and development

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2141
- Docs: https://github.com/OpenNebula/docs/pull/2312
