### ISSUE TITLE
Add JSON format to oneprovision subcommands

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#5883]
**Description**
`oneprovision` subcommands don't have the optional parameter `--json` this prevents showing logs correctly on Provision GUI
this need to be implemented for:
- `oneprovision host delete`

**Use case**
Improve CLI use and Provision GUI logs.

**Interface Changes**
CLI & Fireedge

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
Add JSON output to following commands too:

- `oneprovisision host add`
- `oneprovisision host configure`

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2167)
- [docs](https://github.com/OpenNebula/docs/pull/2332)
