### ISSUE TITLE
Select vGPU profile

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5885]
**Description**
Be able to select vGPU profile when using Nvidia vGPU integration.

**Use case**
The ability to define the vGPU profile is a key part of NVIDIA's solution. The vGPU profiles can depend on workload and licensing type.

**Interface Changes**
KVM VM management scripts.

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2169)
- [docs](https://github.com/OpenNebula/docs/pull/2333)

We need a text box to add the profile in Sunstone.

**Comment by al3xhh** [comment]
### Sunstone Changes

The monitoring will return something like this:

```
PCI = [
 TYPE = "10de:2236:0302" ,
 VENDOR = "10de" ,
 VENDOR_NAME = "NVIDIA Corporation" ,
 DEVICE = "2236" ,
 CLASS = "0302" ,
 CLASS_NAME = "3D controller" ,
 ADDRESS = "0000:41:00:7" ,
 SHORT_ADDRESS = "41:00.7" ,
 DOMAIN = "0000" ,
 BUS = "41" ,
 SLOT = "00" ,
 FUNCTION = "7" ,
 NUMA_NODE = "-" ,
 UUID = "f827da44-cb60-53b0-bca4-a487fea6db4d" ,
 DEVICE_NAME = "NVIDIA Corporation Device" ,
 PROFILES = "nvidia-588,nvidia-589,nvidia-590,nvidia-591,nvidia-592,nvidia-593,nvidia-594,nvidia-595,nvidia-596,nvidia-597,nvidia-598,nvidia-599,nvidia-600,nvidia-601,nvidia-602,nvidia-603,nvidia-604,nvidia-605,nvidia-610,nvidia-611,nvidia-612,nvidia-613,nvidia-614" 
]
```

It should show the field `DEVICE_NAME` as it's more clear. And it should also show the same information as the current PCI + a selector with the different profiles. The information about the profile, should be placed in a field called `PROFILE`, for example:

```
PCI=[
  CLASS="0302",
  DEVICE="2236",
  PROFILE="nvidia-602",
  VENDOR="10de" ]
```
