### ISSUE TITLE
Error to create Marketplace App from VM Template with volatile disks

### ISSUE THREAD

**Issue by sbbarragan** [OpenNebula/one#5887]
**Description**
Create marketplace apps from MV templates from the CLI that cause an error when they have only volatile disks.

The same error occurs from Sunstone.

**To Reproduce**
1. Create a simple VM Template with following attributes: `NAME`, `DISK` (volatile)
```
NAME = "name"
DISK = [
  FORMAT = "raw",
  SIZE = "10",
  TYPE = "fs" ]
```
2. Import VM Template to app from CLI or FireEdge Sunstone:
```
➜ onemarketapp vm-template import 30 --yes --market 100
undefined method `gsub!' for nil:NilClass
```

![image](https://user-images.githubusercontent.com/59608355/175509769-10dfcbaf-139f-4978-9fd2-7bb3fc775a87.png)

**Details**
 - Affected Component: CLI, FireEdge Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2185)
- [docs](https://github.com/OpenNebula/docs/pull/2338)
