### ISSUE TITLE
Non-Persistent Image shows #VMS in use

### ISSUE THREAD

**Issue by madmax01** [OpenNebula/one#5894]
**Description**
When deploying vm's from Template > the Base Image tells #VMs in use.. which cannot be. All Vm's are non-persistent. 

**To Reproduce**
i installed 6.4 and created Images for Iso + Datablock (used persistent yes)
i installed then OS and deleted the VM + changed Datablock to OS and persistent to no
then i changed template and deployed VM from it.
Base-Image shows then #VMS in use = 1

wheni rename the ID of the Image - the VM can still boot fine... so State is somehow wrong.

IMAGE_DS

ALLOW_ORPHANS="YES"
CLONE_TARGET="SYSTEM"
CLONE_TARGET_SSH="SYSTEM"
DISK_TYPE="FILE"
DISK_TYPE_SSH="FILE"
DRIVER="qcow2"
DS_MAD="fs"
LN_TARGET="SYSTEM"
LN_TARGET_SSH="SYSTEM"
SAFE_DIRS="/var/lib/one"
SPARSE="YES"
TM_MAD="ssh"
TM_MAD_SYSTEM="ssh"
TYPE="IMAGE_DS"

SYSTEM_DS

ALLOW_ORPHANS="YES"
CLONE_TARGET_SSH="SYSTEM"
DISK_TYPE="FILE"
DISK_TYPE_SSH="FILE"
DRIVER="qcow2"
DS_MIGRATE="YES"
LN_TARGET_SSH="SYSTEM"
SAFE_DIRS="/var/lib/one"
SHARED="NO"
SPARSE="YES"
TM_MAD="ssh"
TM_MAD_SYSTEM="ssh"
TYPE="SYSTEM_DS"

**Expected behavior**
Expected is that image is ONLY in us by persistent configs....    Issue with Image in use is > never possible to change image back to "persistent" to patch new security patches for new vms. non-persistent Image should be isolated/encapsulated

**Details**
- Base Image Bug
-Alma 8.6
-Opennebula 6.4

**Comment by atodorov-storpool** [comment]
I think this is expected behaviour :-) 
The "golden" image used for the non-persistent copies is sort of locked because it is expected to be able to use for recovery purposes (like the use of recover :delete-recreate)

>  ... Issue with Image in use is > never possible to change image back to "persistent" to patch new security patches for new vms. non-persistent Image should be isolated/encapsulated

You could use the Image save-as function to create a new image, tag it as persistent and do the updates. Then remove the persistent tag and reconfigure the VM Templates to use the new image as a "golden" image.

**Comment by atodorov-storpool** [comment]
Re-thinking, _maybe_ it could be an exciting feature to have an option to do "maintenance" tasks on the golden image...
So I think the OpenNebula devs could chime in :)

**Comment by atodorov-storpool** [comment]
> just looking for this "save-as" function... not finding this Function on the Gui. May i overlook it

My bad, sorry! I mean the _Image -> Clone_ function (it is almost the same as VM disk - Save-as)

**Comment by madmax01** [comment]
ah ok found an kinda working way

- deploy VM
- Patch it
- disk-saveas <vmid> <diskid> <img_name>
- oneimage list + oneimage show xx  (to see to which file the orig image mapped)
- done a copy of orig  (like a version logic)
- replaced the Image long ID with orig one + deleted the new Image

(ahh image clone may even more simpler).. but need to replace ids then anyway

**Comment by madmax01** [comment]
Aye so thinking an 

- Maintenance (with Copy Option for Go-Back)  would be faster to handle to avoid human typos.  

Say example you want to maintain 5 Versions of an Golden-Image.

@atodorov-storpool   thx for you're Hint.. That helped me to go an little cheat way ;).

Will open kinda Feature Request for it
