### ISSUE TITLE
Include cpu tune & topology parameters for qemu/libvirt drivers

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#590]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 796, https://dev.opennebula.org/issues/796
Original Date: 2011-09-06

---

This ticket is to match the CPU parameter with the new cputune attributes of libvirt. Xen drivers update the ticket-based scheduler to distribute physical cpu cycles among VMs (So VMs with higher CPU values will get more physical CPU). This new feature will level the KVM driver with the Xen one in this area.

Also we may include CPU-pin attributes. The Xen driver could implement this trough the hwloc utility

More Info:
http://libvirt.org/formatdomain.html#elementsCPUTuning

http://www.open-mpi.org/projects/hwloc/

**Comment by trenton42** [comment]
Would this also cover [block tuning][1], or should that be a separate ticket? 

[1]: https://libvirt.org/formatdomain.html#elementsBlockTuning

**Comment by rsmontero** [comment]
> Would this also cover [block tuning](https://libvirt.org/formatdomain.html#elementsBlockTuning), or should that be a separate ticket?

I think it is better to create a separate issue for that. 

THANKS!

**Comment by tinova** [comment]
Closed, covered by #3256
