### ISSUE TITLE
[Sunstone] Storage Files Tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5902]
**Description**

Implement Storage Files tab in FireEdge Sunstone

Related to https://github.com/OpenNebula/one/issues/5422

**Tasks**

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@tinova PRs to approve:
- [Code]: https://github.com/OpenNebula/one-ee/pull/2252
- [Tests]: https://github.com/OpenNebula/development/pull/1998
