### ISSUE TITLE
[Sunstone] Security Groups

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5903]
**Description**

Implement Security Groups tab. Related to #5422.

**Tasks**

- [x] Security Group recover operation should only be activated if the are VMs in error state after an update

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@tinova PR to approve: 

[Dev](https://github.com/OpenNebula/development/pull/2017)
[One-6.4](https://github.com/OpenNebula/development/pull/2017)
[master](https://github.com/OpenNebula/one-ee/pull/2288)

**Comment by tinova** [comment]
![image](https://user-images.githubusercontent.com/5102/196921785-11ea89c6-88ba-4277-93d7-eff629bf7ba8.png)

need to implement the VM update info

**Comment by tinova** [comment]
Recover switch 95342c3fa50c083d7c2ba1fa7025df71e22c8858
