### ISSUE TITLE
[Sunstone] Settings tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5904]
**Description**

Implement User Settings tab.

**Tasks**

## Progress Status
- [ ] Code committed
- [x] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
implemented as part of #5422

**Comment by FrederickBor** [comment]
Settings tab tests:
- https://github.com/OpenNebula/one-ee/pull/2225
- https://github.com/OpenNebula/development/pull/1970
