### ISSUE TITLE
Add an SSH console to compliment noVNC.

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#591]
---

Author Name: **Richard Palusaar** (Richard Palusaar)
Original Redmine Issue: 807, https://dev.opennebula.org/issues/807
Original Date: 2011-09-13

---

This feature would provide an ssh console for managing VMs.

Sunstone -> Virtual Machines, page:
Add an icon next to the noVNC connect icon that symbolizes an SSH remote login.
Each VM image would be prepared with an ssh public key to allow sunstone to connect to the VM.
The connection would be displayed in an interactive textera form element, or similar.

I am sure someone has come up with a way to run SSH sessions from a web page.

Possible benifits:
* Eease of administrative access to the host OS of each VM.
* Internode operability.
* Less network bandwidth intensive than running a VNC session when all you need is text.

The idea is to compliment the VNC session as and not to replace it.

**Comment by rsmontero** [comment]
---

Original Redmine Comment
Author Name: **Carlo Daffara** (Carlo Daffara)
Original Date: 2012-10-30T11:51:20Z

---

We are using the GateOne SSH proxy and web interface exactly for this purpose. It can be downloaded similarly to noVnc, and provides a very efficient web ssh service: https://github.com/liftoff/GateOne
and a demo here: http://liftoffsoftware.com/Products/GateOne
it's a python proxy to gate the SSH service and javascript shim for handling the connection.
Carlo Daffara
CloudWeavers

**Comment by rsmontero** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2012-10-30T21:39:03Z

---

Hi Carlos, Great pointers. I'll move this to the feature tracker, to evaluate its integration for 4.0

**Comment by sbbarragan** [comment]
SSH console is include on [Guagamole](https://github.com/OpenNebula/one/issues/2755)

Check [here](http://docs.opennebula.io/5.13/configuration_guide/sunstone_configuration/sunstone.html#accessing-your-vms-console-and-desktop) for more information
