### ISSUE TITLE
oneflow-template instantiate fails to authenticate

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5912]
**Description**
When issuing the credentials to the `oneflow-template instantiate` command using the CLI arguments `-u` and `-p` the CLI complains about one_auth not existing.

```
root@ubuntu2004-6355:~# oneflow-template instantiate 4 -u my_user -p my_password -s http://172.20.0.37:2474
ONE_AUTH file not present
```

It happens exactly with the `instantiate` argument
```
root@ubuntu2004-6355:~# oneflow-template list -u my_user -p my_password -s http://172.20.0.37:2474/
  ID USER     GROUP    NAME                                                                                                                                                REGTIME
   4 my_user  users    web-application                                                                                                                              07/11 15:34:25
   2 my_user  users    web-application                                                                                                                              07/11 15:28:37
root@ubuntu2004-6355:~# oneflow-template delete 4 -u my_user -p my_password -s http://172.20.0.37:2474/
root@ubuntu2004-6355:~# oneflow-template list -u my_user -p my_password -s http://172.20.0.37:2474/
  ID USER     GROUP    NAME                                                                                                                                                REGTIME
   2 my_user  users    web-application                                                                                                                              07/11 15:28:37
```

**To Reproduce**
- Setup the `opennebula-cli` gem in a machine separate from where oneflow is running
- Setup the required environmental variables
- Issue the commands described

**Expected behavior**
When passing credentials as CLI argument, ONE_AUTH shouldn't be required.

**Details**
 - Version: 6.4.0

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
PRs
- [code](https://github.com/OpenNebula/one-ee/pull/2232)
- [doc](https://github.com/OpenNebula/docs/pull/2360)

**Comment by paczerny** [comment]
Previous commit broke `oneflow-template instantiate` without the `-u` and `-p` arguments, here is [PR with fix](https://github.com/OpenNebula/one-ee/pull/2240)
