### ISSUE TITLE
[LVM] Error when migrating a VM between different DS

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5923]
**Description**
When migrating a VM to a different host, a different target DS can be selected too. When the same DS is used the VM migration works properly but it fail when a different DS is selected as the LV is deactivated.

**To Reproduce**
Try to migrate a VM between to different hosts including a DS change.

**Expected behavior**
The VM is properly migrating to the target host and DS.

**Details**
 - Affected Component: Storage (fs_lvm)
 - Version: 6.4

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
duplicated by https://github.com/OpenNebula/one/issues/5980
