### ISSUE TITLE
Live disk snapshot: domfsthaw error not handled correctly

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#5927]
**Description**
When `libvirt domfsthaw` fails in snapshot_create_live driver action, snapshot is created in datastore (ceph) but not in OpenNebula.

**To Reproduce**
Simulate somehow `error: Unable to thaw filesystems error: internal error: unable to execute QEMU agent command 'guest-fsfreeze-thaw'` which leads to inconsistency.

**Expected behavior**
Snapshot is either crated also in OpenNebula or rollbacked in Ceph.

**Details**
 - Affected Component: storage: ceph, qcow2
 - Hypervisor: kvm
 - Version: 6.2+
 
**Additional context**
https://opennebula.zendesk.com/agent/tickets/35577

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vickmp** [comment]
PRs to merge:
- [code](https://github.com/OpenNebula/one-ee/pull/2280)
- [docs](https://github.com/OpenNebula/docs/pull/2394)
