### ISSUE TITLE
Monitoring graphics (CPU, MEMORY, network, disk consumption, I/O, etc)

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5928]
- [x] Code
- [ ] Doc
- [ ] Tests

**Comment by jloboescalona2** [comment]
@tinova PRs to approve:
- [Code](https://github.com/OpenNebula/one-ee/pull/2260)

**Comment by Prashiksha** [comment]
I want to work on this issue. Getting some heads up/approval would be helpful. I am a Masters student trying to work on this open source project.
