### ISSUE TITLE
New FireEdge Sunstone Firecracker support

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5937]
**Description**
A list of the missing things is available below:

Template (update)

- [ ] [GENERAL] Make HYPERVISOR mandatory in VM Template create/update.
- [ ] [GENERAL] Hot resize of CPU/Mem not supported
- [ ] [ADVANCED][NETWORK] "Default hardware model to emulate for all NICs" not supported (only support virtio)
- [ ] [ADVANCED][OS&CPU] "Path to the bootloader executable" not supported.
- [ ] [ADVANCED][OS&CPU] The VM template Kernel image (i.e `KERNEL_DS="$FILE[IMAGE=\"kernel\"]"`) is not shown. Neither can I select an existing kernel from FILE Datastore (it asks for a path if I enable Customize with path).
- [ ] [ADVANCED][I/O] Only VNC protocol is supported.
- [ ] [ADVANCED][OS&CPU] Inputs and PCI Devices sections are not supported.
- [ ] [ADVANCED][NUMA] Number of threads (only between 1 or 2) is supported.

Datastore

- [ ] Cannot see files & kernels images

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Ask Christian to review FC again
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
wontfix
