### ISSUE TITLE
Disks removed from VM definition when instantiating a VM template using Sunstone

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5938]
**Description**
When a VM template containing multiple disks is instantiated using Sunstone disks are removed if any of the disks have defined the `SIZE` attribute, like in the example below:

```
CONTEXT = [
  NETWORK = "YES",
  SSH_PUBLIC_KEY = "$USER[SSH_PUBLIC_KEY]" ]
CPU = "1"
DISK = [
  DEV_PREFIX = "vd",
  IMAGE = "cdrom",
  IMAGE_UNAME = "oneadmin" ]
DISK = [
  IMAGE = "Alpine Linux 3.15",
  IMAGE_UNAME = "oneadmin",
  SIZE = "1024" ]
GRAPHICS = [
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
HOT_RESIZE = [
  CPU_HOT_ADD_ENABLED = "NO",
  MEMORY_HOT_ADD_ENABLED = "NO" ]
MEMORY = "2048"
MEMORY_UNIT_COST = "MB"
NIC = [
  NETWORK = "vnet",
  NETWORK_UNAME = "oneadmin",
  SECURITY_GROUPS = "0" ]
NIC = [
  NETWORK = "vnet",
  NETWORK_UNAME = "oneadmin",
  SECURITY_GROUPS = "0" ]
NIC = [
  NETWORK = "vnet",
  NETWORK_UNAME = "oneadmin",
  SECURITY_GROUPS = "0" ]
NIC = [
  NETWORK = "vnet",
  NETWORK_UNAME = "oneadmin",
  SECURITY_GROUPS = "0" ]
OS = [
  BOOT = "disk0",
  FIRMWARE = "",
  FIRMWARE_SECURE = "YES" ]
```

**To Reproduce**
- Create a VM template with multiple disks including one of them with the `SIZE` attribute defined.
- Instantiate the VM template using Sunstone interface.
- Check VM disks.

NOTE: It also happens when the size is changed at the instantiate dialog.

**Expected behavior**
The VM is deployed with every disk defined in the VM template.

**Details**
 - Affected Component: Sunstone
 - Version: 6.4.1

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by a31amit** [comment]
+ 1  facing the same issue.

**Comment by a31amit** [comment]
most likely a similar issue may be - https://github.com/OpenNebula/one/issues/5427 ?

**Comment by tinova** [comment]
related to: https://github.com/OpenNebula/one/issues/5970

**Comment by jloboescalona2** [comment]
resolved in this PR: https://github.com/OpenNebula/one-ee/pull/2335
