### ISSUE TITLE
Sunstone novnc not work if vnc password contain symbol "#"

### ISSUE THREAD

**Issue by kvakanet** [OpenNebula/one#5965]
**Description**
novnc into sunstone not connect to vm if vnc password contain symbol "#"

**To Reproduce**
Make VNC password : "=1DS#bnH"

**Expected behavior**
Connecting in vnc must with this password worked fine.

**Details**
 - Affected Component: Sunstone(novnc)
 - Hypervisor: KVM
 - Version: 6.4

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
won't fix for noVNC, please reopen if also applies to Guacamole VNC and/or VMRC
