### ISSUE TITLE
Pinning Policy: NUMA Affinity

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5966]
**Description**
Allow to isolate a VM in an specific NUMA node withing exclusively pinning the VM to the node. The node should be still available for other VMs, but the isolated VM shouldn't be able to run outside the specific node. 

It also needs to allow the allocation of hugepages in that node

**Use case**
Allow administrator to manually isolate VMs compute resources.

**Interface Changes**
The administrator should be able to manually specify the NUMA node where the VM is going to be isolated.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
dropdown "numa node affinity"
new field "node number"

**Comment by tinova** [comment]
FSunstone https://github.com/OpenNebula/one-ee/pull/2620
RSunstone https://github.com/OpenNebula/one-ee/pull/2619
