### ISSUE TITLE
 VMRC issue with passwords and duplicated endpoints

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5981]
**Description**
VMRC connections have connectivity issues with passwords with special characters and endpoints duplicated that are not working when using Apache.

**To Reproduce**
Create a user with special character password and try to connect through VMRC.

**Expected behavior**
VMRC connections to work properly.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 6.4.1

## Progress Status
- [X] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
PR applied:
- Code:
    - https://github.com/OpenNebula/one-ee/pull/2270
    - https://github.com/OpenNebula/one-ee/pull/2271

**Comment by FrederickBor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/sVOi0Rm9/1-test)

**Comment by FrederickBor** [comment]
- Docs: https://github.com/OpenNebula/docs/pull/2399
