### ISSUE TITLE
Hot update for Virtual Network

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5986]
**Description**
Propagate changes to `RUNNING` VMs when a Virtual Network is updated.

**Use case**
When a configurable attribute of a Virtual Network is updated, this should be propagated automatically to `RUNNING` VMs. For example if the `VLAN_ID` attribute is updated the VM traffic should be routed through the new `VLAN_ID` VLAN.

**Interface Changes**
No interface changes should be required.

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
branch "network-update"

**Comment by tinova** [comment]
https://github.com/OpenNebula/one-ee/tree/network_update

**Comment by FrederickBor** [comment]
Code:

- https://github.com/OpenNebula/one-ee/pull/2319
- https://github.com/OpenNebula/one-ee/pull/2323
- https://github.com/OpenNebula/one-ee/pull/2328

**Comment by tinova** [comment]
* [Leases status FSunstone](https://github.com/OpenNebula/one-ee/pull/2321)

**Comment by FrederickBor** [comment]
- https://github.com/OpenNebula/one-ee/pull/2345
