### ISSUE TITLE
VNC password is too long

### ISSUE THREAD

**Issue by harsxv** [OpenNebula/one#5989]
**Description**
The `RANDOM_PASSWD` for VNC graphic is too long.

```
Thu Oct 6 13:56:24 2022 [Z0][VMM][E]: DEPLOY: [deploy-tweaks] VM 3568 could not create domain from /var/lib/one/vms/3568/deployment.0 Warning: Permanently added '[##redacted.com]:##redacted,[192.168.0.6]:64000' (ECDSA) to the list of known hosts. error: Failed to create domain from /var/lib/one//datastores/101/3568/deployment.0 error: unsupported configuration: VNC password is 64 characters long, only 8 permitted Could not create domain from /var/lib/one//datastores/101/3568/deployment.0
```

**To Reproduce**
Use `RANDOM_PASSWD` on the VNC graphic.

**Expected behavior**
The VNC password needs to meet the requirements of password limitation on qemu.

**Details**
 - Affected Component: VM OpenNebula can't boot.
 - Hypervisor: QEMU emulator version 6.2.0 (qemu-kvm-6.2.0-11.module_el8.6.0+3071+a07c0ea5.2)
 - Version: 6.2.0

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
duplicated by #5842
