### ISSUE TITLE
[VCENTER] Undeploy/Stop actions leave the VM defined in vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5990]
**Description**
When a VM is undeployed/stopped it's left defined in the vCenter cluster, instead of being removed to free the compute resources while storing only the VM disks to be used when the VM is resumed.

**To Reproduce**
   - Deploy a VM.
   - Execute stop/undeploy action on the VM.

**Expected behavior**
The VM storage is saved but the VM is removed from the cluster so the compute resources are freed.

**Details**
 - Affected Component: VMM
 - Hypervisor: vCenter
 - Version: 6.4

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
Doc https://github.com/OpenNebula/docs/commit/1d5371f5a1b6c8a3f63ab11f61db0e47788a1979
