### ISSUE TITLE
OpenNebula 6.2.0 - does not/can not remove old snapshots (kvm) from time to time

### ISSUE THREAD

**Issue by Githopp192** [OpenNebula/one#5992]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
From time to time OpenNebula will not / can not remove old snapshots
I suppose, that OpenNebula has got some issues, when (re)naming snapshots!?

**To Reproduce**
don't know how to reproduce

May be the ONE GUI causes those ISSUES.
pure CLI (onevm snapshot-create <vmid-id> <vm-name> seems to run without these side-effects.

i think the ONE GUI, when creating snapshots will lead to those ISSUES.
pure cli (onevm snap

**Expected behavior**
OpenNebula should properly remove snapshots, which are listed per GUI, per CLI (onevm show <vmid> or qemu-img snapshot -l)

**Details**
 - Affected Component: onevm snapshot-delete (kvm/qemu-img)
 -  virsh --connect qemu:///system snapshot-delete 6b650fc1-60cb-4021-8040-75b41e78cf29 snap-236
 - Hypervisor: KVM
 - Version: 6.2.0
**Additional context**

* snapshot to be removed is properly shown in GUI-contect

![ScreenShot038](https://user-images.githubusercontent.com/32612067/195584614-01f20761-8c6d-4c5d-91cf-d1c0e270a21e.jpg)

* snapshot to be removed is properly shown via qemu-img snapshot -l:

file format: qcow2
virtual size: 50 GiB (53687091200 bytes)
disk size: 41.1 GiB
cluster_size: 65536
Snapshot list:
ID        TAG               VM SIZE                DATE     VM CLOCK     ICOUNT
237       **snap-236**              0 B 2022-09-29 01:58:08 00:15:58.827
246       snap-245              0 B 2022-10-09 01:58:09 10:51:55.691
247       snap-246              0 B 2022-10-10 01:58:09 08:36:31.100
248       snap-247              0 B 2022-10-11 01:58:08 00:15:54.524
249       snap-248              0 B 2022-10-12 01:58:09 00:15:45.961
250       snap-249              0 B 2022-10-13 01:58:09 00:15:55.723

* snapshot to be removed is shown via sunstone (onevm show <vmid>, but differs from other snapshot namings 
  (without prefix "snap-") ==> see snap: 236

ID
236  09/29 01:58 xxxx    **236**
245  10/09 01:58 xxxx    snap-245

[sunstone]# onevm snapshot-delete <vmid> snap-236
snap-236 not found or duplicated

onevm snapshot-delete <vmid> **236**

return RC = 0 (which is wrong, should be improved, too - that onevm cmd return rc=1 in case of errors):

hu Oct 13 13:01:31 2022 [Z0][VMM][E]: SNAPSHOTDELETE: ERROR: snapshot_delete: Command "virsh --connect qemu:///system snapshot-delete 6b650fc1-60cb-4021-8040-75b41e78cf29 236" failed: error: Domain snapshot not found: no domain snapshot with matching name '236' Could not delete snapshot **236** for domain 6b650fc1-60cb-4021-8040-75b41e78cf29.

Run this command manuallly on the KVM-Hypervisor has got same effect:

virsh --connect qemu:///system snapshot-delete 6b650fc1-60cb-4021-8040-75b41e78cf29 236
error: Domain snapshot not found: no domain snapshot with matching name '**236**'

BUT:running the qemu command with snap-name: snap-236 will succeed:

virsh --connect qemu:///system snapshot-delete 6b650fc1-60cb-4021-8040-75b41e78cf29 **snap-236**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Hi @Githopp192 

Thanks for the feedback! It seems that at some point the snapshot name in OpenNebula and in KVM differed, as you can see snapshot 236 actually does not exists it is 237. Do you have any hint when this could happen? We will try to reproduce the issue anyway

As for the API call, not that the result is for the operation start phase, ie. all checks passed, user has rights to perform the action and the action is queued to be executed.The actual result on the current opertation is returned in the TEMPLATE in case of ERROR.

**Comment by Githopp192** [comment]
Very welcome Ruben!
I could not reproduce this error - i will use a daily script (cmd: onevm snapshot-create "$vmid" "$vmname"), where i will create the KVM-Snapshots. I did now create some monitoring-scripts, which will check qem-img / virt-snaps if they are older than 10 days - because, if somebody is unaware of these old snapshots, it could become a huge space problem on the Datastore (or image itself). 

I understood now the behave or "one" error handling. But what do you mean with "current operation is returned in the TEMPLATE in case of ERROR." - which log or template it could be ? (one the CLI site).

**Comment by Githopp192** [comment]
Issue ocurred again. In this case one did remove some virsh snapshot and then got a inconsisent state with itself 
(snapshot missmatch). 

This bug can have disastrous effects under certain circumstances (i.e. when a restore is needed, but some snapshots are not available anymore).



After creating a one snap on sunstone GUI, after re-powering the VM the following happened:

snap-100,snap-101,snap-102 marked as invalid by ONE !


Sun Dec 4 10:55:54 2022 [Z0][VM][I]: New LCM state is BOOT_POWEROFF
Sun Dec 4 10:55:54 2022 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/99/deployment.13
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/mkdir -p.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one//datastores/0/99/vm.xml.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one//datastores/0/99/ds.xml.
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-99 for moment snap-100 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-100 for moment snap-101 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-101 for moment snap-102 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: Successfully execute network driver operation: post.
Sun Dec 4 10:55:57 2022 [Z0][VM][I]: New LCM state is RUNNING


snap-xml Files are still there: 

[root@xxx.xxx.xxx ~]# ls -alt /var/lib/one//datastores/0/99
total 504
drwxr-xr-x 1 oneadmin oneadmin    562 Dec  4 10:55 .
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 10:55 snap-99.xml
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 10:55 snap-98.xml
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 10:55 snap-97.xml
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 10:55 snap-96.xml
-rw-r--r-- 1 oneadmin oneadmin   4865 Dec  4 10:55 snap-95.xml
-rw-r--r-- 1 oneadmin oneadmin   4186 Dec  4 10:55 snap-102.xml
-rw-r--r-- 1 oneadmin oneadmin   4915 Dec  4 10:55 snap-101.xml
-rw-r--r-- 1 oneadmin oneadmin   4914 Dec  4 10:55 snap-100.xml
-rw-r--r-- 1 oneadmin oneadmin   2229 Dec  4 10:55 deployment.13
-rw-r--r-- 1 oneadmin oneadmin    977 Dec  4 10:55 ds.xml
-rw-r--r-- 1 oneadmin oneadmin   9178 Dec  4 10:55 vm.xml
-rw-r--r-- 1 oneadmin oneadmin 372736 Dec  4 10:55 disk.2
-rw-r--r-- 1 oneadmin oneadmin   2229 Nov 27 02:28 deployment.12
-rw-r--r-- 1 oneadmin oneadmin   2229 Nov  6 17:41 deployment.11
-rw-r--r-- 1 oneadmin oneadmin   2227 Nov  6 11:14 deployment.10
-rw-r--r-- 1 oneadmin oneadmin   2227 Oct 24 00:29 deployment.9
-rw-r--r-- 1 oneadmin oneadmin   2227 Oct 23 02:30 deployment.8
-rw-r--r-- 1 oneadmin oneadmin   2227 Oct  9 14:22 deployment.7
-rw-r--r-- 1 oneadmin oneadmin   2227 Oct  9 13:12 deployment.5
-rw-r--r-- 1 oneadmin oneadmin   2227 Sep 29 02:03 deployment.4
-rw-r--r-- 1 oneadmin oneadmin   2227 Sep 29 01:19 deployment.3
-rw-r--r-- 1 oneadmin oneadmin   2361 Aug 28 02:29 deployment.2
-rw-r--r-- 1 oneadmin oneadmin   2361 Aug 28 01:17 deployment.1
-rw-r--r-- 1 oneadmin oneadmin   2353 Aug 27 22:45 deployment.0
lrwxrwxrwx 1 oneadmin oneadmin     68 Aug 27 22:45 disk.1 -> /var/lib/one//datastores/100/2222222222222222222222222222222.snap/0
lrwxrwxrwx 1 oneadmin oneadmin     66 Aug 27 22:45 disk.0 -> /var/lib/one//datastores/1/11111111111111111111111111111111111111111.snap/0
drwxrwxr-x 1 oneadmin oneadmin     12 Aug 27 22:45 ..

QEMU-Reports existence of the snaps, too 

[root@xxx.xxx.xxx ~]# qemu-img info /mnt/datastores/nfs-ds-SAN-Storage/1/11111111111111111111111111111111111111111
image: /mnt/datastores/nfs-ds-SAN-Storage/1/11111111111111111111111111111111111111111
file format: qcow2
virtual size: 250 GiB (268435456000 bytes)
disk size: 213 GiB
cluster_size: 65536
Snapshot list:
ID        TAG               VM SIZE                DATE     VM CLOCK     ICOUNT
96        snap-95          9.52 GiB 2022-11-28 01:59:18 23:31:08.089
97        snap-96          9.54 GiB 2022-11-29 01:59:18 47:23:37.548
98        snap-97          9.43 GiB 2022-11-30 01:59:18 71:17:34.685
99        snap-98          9.42 GiB 2022-12-01 01:59:18 95:09:43.473
100       snap-99          9.48 GiB 2022-12-02 01:59:18119:03:34.223
101       snap-100         9.48 GiB 2022-12-03 01:59:19142:54:28.906
102       snap-101         9.47 GiB 2022-12-04 01:59:18166:45:21.185
103       snap-102         9.51 GiB 2022-12-04 09:50:56174:27:38.717
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
[root@xxx.xxx.xxx ~]# qemu-img info /mnt/datastores/nfs-ds-SAN-Storage/100/2222222222222222222222222222222
image: /mnt/datastores/nfs-ds-SAN-Storage/100/2222222222222222222222222222222
file format: qcow2
virtual size: 4 TiB (4398046511104 bytes)
disk size: 1.03 TiB
cluster_size: 65536
Snapshot list:
ID        TAG               VM SIZE                DATE     VM CLOCK     ICOUNT
96        snap-95               0 B 2022-11-28 01:59:18 23:31:08.089
97        snap-96               0 B 2022-11-29 01:59:18 47:23:37.548
98        snap-97               0 B 2022-11-30 01:59:18 71:17:34.685
99        snap-98               0 B 2022-12-01 01:59:18 95:09:43.473
100       snap-99               0 B 2022-12-02 01:59:18119:03:34.223
101       snap-100              0 B 2022-12-03 01:59:19142:54:28.906
102       snap-101              0 B 2022-12-04 01:59:18166:45:21.185
103       snap-102              0 B 2022-12-04 09:50:56174:27:38.717
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false



Now checking via virsh - we just know, why ONE got troubles with the snapshots !
snap-100,snap-101,snap-102 are gone.


[root@xxx.xxx.xxx ~]# virsh --connect qemu:///system snapshot-list 45c924ae-4786-4a59-9ca2-4db8298f5036
 Name      Creation Time               State
------------------------------------------------
 snap-95   2022-11-28 01:59:18 +0100   running
 snap-96   2022-11-29 01:59:18 +0100   running
 snap-97   2022-11-30 01:59:18 +0100   running
 snap-98   2022-12-01 01:59:18 +0100   running
 snap-99   2022-12-02 01:59:18 +0100   running



of course, removing will fail, be cause snaps are gone:

trying to remove snapshot snap-102

Sun Dec 4 11:35:27 2022 [Z0][VM][I]: New LCM state is RUNNING
Sun Dec 4 11:40:41 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sun Dec 4 11:40:42 2022 [Z0][VMM][I]: Command execution failed (exit code: 1): 'if [ -x "/var/tmp/one/vmm/kvm/snapshot_delete" ]; then /var/tmp/one/vmm/kvm/snapshot_delete 45c924ae-4786-4a59-9ca2-4db8298f5036 snap-102 99 xxx.xxx.xxx; else exit 42; fi'
Sun Dec 4 11:40:42 2022 [Z0][VMM][E]: snapshot_delete: Command "virsh --connect qemu:///system snapshot-delete 45c924ae-4786-4a59-9ca2-4db8298f5036 snap-102" failed: error: Domain snapshot not found: no domain snapshot with matching name 'snap-102'
Sun Dec 4 11:40:42 2022 [Z0][VMM][I]: Could not delete snapshot snap-102 for domain 45c924ae-4786-4a59-9ca2-4db8298f5036.
Sun Dec 4 11:40:42 2022 [Z0][VMM][E]: SNAPSHOTDELETE: ERROR: snapshot_delete: Command "virsh --connect qemu:///system snapshot-delete 45c924ae-4786-4a59-9ca2-4db8298f5036 snap-102" failed: error: Domain snapshot not found: no domain snapshot with matching name 'snap-102' Could not delete snapshot snap-102 for domain 45c924ae-4786-4a59-9ca2-4db8298f5036.
Sun Dec 4 11:40:42 2022 [Z0][VM][I]: New LCM state is RUNNING

Now beginning the CLEANUP manually :
============================
qemu still sees the snaps:

[root@xxx.xxx.xxx ~]# (perform from snap-100 - snap-102)

qemu-img snapshot -d snap-102 /var/lib/one//datastores/100/2222222222222222222222222222222
[root@xxx.xxx.xxx ~]# qemu-img snapshot -l /var/lib/one//datastores/100/2222222222222222222222222222222
Snapshot list:
ID        TAG               VM SIZE                DATE     VM CLOCK     ICOUNT
96        snap-95               0 B 2022-11-28 01:59:18 23:31:08.089
97        snap-96               0 B 2022-11-29 01:59:18 47:23:37.548
98        snap-97               0 B 2022-11-30 01:59:18 71:17:34.685
99        snap-98               0 B 2022-12-01 01:59:18 95:09:43.473
100       snap-99               0 B 2022-12-02 01:59:18119:03:34.223


qemu-img snapshot -d snap-102 /mnt/datastores/nfs-ds-SAN-Storage/1/11111111111111111111111111111111111111111

[root@xxx.xxx.xxx ~]# qemu-img snapshot -l /mnt/datastores/nfs-ds-SAN-Storage/1/11111111111111111111111111111111111111111
Snapshot list:
ID        TAG               VM SIZE                DATE     VM CLOCK     ICOUNT
96        snap-95          9.52 GiB 2022-11-28 01:59:18 23:31:08.089
97        snap-96          9.54 GiB 2022-11-29 01:59:18 47:23:37.548
98        snap-97          9.43 GiB 2022-11-30 01:59:18 71:17:34.685
99        snap-98          9.42 GiB 2022-12-01 01:59:18 95:09:43.473
100       snap-99          9.48 GiB 2022-12-02 01:59:18119:03:34.223
[root@xxx.xxx.xxx ~]#

update db body : remove snaphot snap-100 - snap 102

    <SNAPSHOT>
      <HYPERVISOR_ID><![CDATA[snap-100]]></HYPERVISOR_ID>
      <NAME><![CDATA[swiss7cloud]]></NAME>
      <SNAPSHOT_ID><![CDATA[100]]></SNAPSHOT_ID>
      <TIME><![CDATA[1670029158]]></TIME>
    </SNAPSHOT>
    <SNAPSHOT>
      <HYPERVISOR_ID><![CDATA[snap-101]]></HYPERVISOR_ID>
      <NAME><![CDATA[swiss7cloud]]></NAME>
      <SNAPSHOT_ID><![CDATA[101]]></SNAPSHOT_ID>
      <TIME><![CDATA[1670115558]]></TIME>
    </SNAPSHOT>
    <SNAPSHOT>
      <HYPERVISOR_ID><![CDATA[snap-102]]></HYPERVISOR_ID>
      <NAME><![CDATA[swiss7cloud]]></NAME>
      <SNAPSHOT_ID><![CDATA[102]]></SNAPSHOT_ID>
      <TIME><![CDATA[1670143856]]></TIME>
    </SNAPSHOT>



update body did remove some removed snaps, but not all! - remove snap.101.xml:


[root@xxx.xxx.xxx ~]# ls -alt /var/lib/one//datastores/0/99
total 492
drwxr-xr-x 1 oneadmin oneadmin    540 Dec  4 11:45 .
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 11:35 snap-99.xml
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 11:35 snap-98.xml
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 11:35 snap-97.xml
-rw-r--r-- 1 oneadmin oneadmin   4913 Dec  4 11:35 snap-96.xml
-rw-r--r-- 1 oneadmin oneadmin   4865 Dec  4 11:35 snap-95.xml
-rw-r--r-- 1 oneadmin oneadmin   4915 Dec  4 11:35 snap-101.xml

remove snap-101.xml

Final:

* restart vm: OK
* create new one-snap (NOT by GUI !) - succeed
  onevm snapshot-create <vm-id> <vm-name>

**Comment by Githopp192** [comment]
this is the gui- / snapshot status just before the incident:

![image](https://user-images.githubusercontent.com/32612067/205512009-d962336d-b737-4a43-b765-b189b5beb7f8.png)

one strange thing: you can vi the some snapshots properly, like snap-101:
(path: /var/lib/one//datastores/0/99)

![image](https://user-images.githubusercontent.com/32612067/205512061-e8c3b459-1d6e-43f5-ac87-b022299cc575.png)

but snap-102 looks like this: 

![image](https://user-images.githubusercontent.com/32612067/205512141-bf198cf7-6da1-46ff-9133-59319fa8d7f0.png)

this is a messy output .. (did not go deeply in it - but may this has to do with the issue - crapped xml ?)

**Comment by Githopp192** [comment]
btw - just to the moment of Incident all the (daily) snapshot operations did run without any issue/error:

Sun Nov 27 03:00:11 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sun Nov 27 03:09:45 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Sun Nov 27 03:09:45 2022 [Z0][VM][I]: New LCM state is RUNNING
Mon Nov 28 01:59:17 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Mon Nov 28 02:06:49 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Mon Nov 28 02:06:49 2022 [Z0][VM][I]: New LCM state is RUNNING
Mon Nov 28 03:00:07 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Mon Nov 28 03:04:33 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Mon Nov 28 03:04:33 2022 [Z0][VM][I]: New LCM state is RUNNING
Tue Nov 29 01:59:18 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Tue Nov 29 02:05:21 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Tue Nov 29 02:05:21 2022 [Z0][VM][I]: New LCM state is RUNNING
Tue Nov 29 03:00:07 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Tue Nov 29 03:04:50 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Tue Nov 29 03:04:50 2022 [Z0][VM][I]: New LCM state is RUNNING
Wed Nov 30 01:59:18 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Wed Nov 30 02:07:10 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Wed Nov 30 02:07:10 2022 [Z0][VM][I]: New LCM state is RUNNING
Wed Nov 30 03:00:07 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Wed Nov 30 03:03:25 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Wed Nov 30 03:03:25 2022 [Z0][VM][I]: New LCM state is RUNNING
Thu Dec 1 01:59:18 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Thu Dec 1 02:05:35 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Thu Dec 1 02:05:35 2022 [Z0][VM][I]: New LCM state is RUNNING
Thu Dec 1 03:00:08 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Thu Dec 1 03:05:56 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Thu Dec 1 03:05:56 2022 [Z0][VM][I]: New LCM state is RUNNING
Fri Dec 2 01:59:18 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Fri Dec 2 02:08:24 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Fri Dec 2 02:08:24 2022 [Z0][VM][I]: New LCM state is RUNNING
Fri Dec 2 03:00:17 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Fri Dec 2 03:06:12 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Fri Dec 2 03:06:12 2022 [Z0][VM][I]: New LCM state is RUNNING
Sat Dec 3 01:59:18 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sat Dec 3 02:08:26 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Sat Dec 3 02:08:26 2022 [Z0][VM][I]: New LCM state is RUNNING
Sat Dec 3 03:00:07 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sat Dec 3 03:06:31 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Sat Dec 3 03:06:31 2022 [Z0][VM][I]: New LCM state is RUNNING
Sun Dec 4 01:59:18 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sun Dec 4 02:08:39 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Sun Dec 4 02:08:39 2022 [Z0][VM][I]: New LCM state is RUNNING
Sun Dec 4 03:00:07 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sun Dec 4 03:04:27 2022 [Z0][VMM][I]: VM Snapshot successfully deleted.
Sun Dec 4 03:04:27 2022 [Z0][VM][I]: New LCM state is RUNNING
Sun Dec 4 09:50:56 2022 [Z0][VM][I]: New LCM state is HOTPLUG_SNAPSHOT
Sun Dec 4 09:57:24 2022 [Z0][VMM][I]: VM Snapshot successfully created.
Sun Dec 4 09:57:24 2022 [Z0][VM][I]: New LCM state is RUNNING
Sun Dec 4 10:02:50 2022 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Sun Dec 4 10:03:02 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:03:02 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: shutdown.
Sun Dec 4 10:03:03 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:03:03 2022 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Sun Dec 4 10:03:03 2022 [Z0][VM][I]: New state is POWEROFF
Sun Dec 4 10:03:03 2022 [Z0][VM][I]: New LCM state is LCM_INIT
Sun Dec 4 10:55:54 2022 [Z0][VM][I]: New state is ACTIVE
Sun Dec 4 10:55:54 2022 [Z0][VM][I]: New LCM state is BOOT_POWEROFF
Sun Dec 4 10:55:54 2022 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/99/deployment.13
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/mkdir -p.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one//datastores/0/99/vm.xml.
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:55 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one//datastores/0/99/ds.xml.
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-99 for moment snap-100 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-100 for moment snap-101 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-101 for moment snap-102 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: ExitCode: 0
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: Successfully execute network driver operation: post.
Sun Dec 4 10:55:57 2022 [Z0][VM][I]: New LCM state is RUNNING

**Comment by dann1** [comment]
Can you post the content of the file `/var/lib/one//datastores/0/99/snap-99.xml` for this latest VM ? Basically any of the contents of the first XML file mentioned (parent snap) in these lines

```log
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-99 for moment snap-100 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-100 for moment snap-101 not found
Sun Dec 4 10:55:57 2022 [Z0][VMM][I]: error: invalid argument: parent snap-101 for moment snap-102 not found
```

**Comment by Githopp192** [comment]
ok - for now, do have got all information you need (i also could do a restore of all xml files just before the incident, if this is usefull  4u)

**Comment by Githopp192** [comment]
[one-snap.xml-before-incident.zip](https://github.com/OpenNebula/one/files/10155064/one-snap.xml-before-incident.zip)

..here they are !

**Comment by ONdboca** [comment]
The issue has been resolved. Please see [link](https://github.com/OpenNebula/one/issues/5991).
