### ISSUE TITLE
MACHINE attribute does not yield any change in the libvirt xml when defined in VM template

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5997]
**Description**
Defining the MACHINE attribute in a VM template does not yield any change in the libvirt xml template. 

**To Reproduce**
Deploy a VM, modify the VM template and add `<MACHINE><![CDATA[pc-q35-rhel8.6.0]]></MACHINE>` inside the `<OS>` tab, redeploy the VM.

**Expected behavior**
The MACHINE attribute inside the <OS> tab should be translated into the libvirt xml template of the VM.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
WFM
