### ISSUE TITLE
When a very long label is added, the text is incomplete

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#5998]
**Description**
When a very long label is added, the text is incomplete

interesting would be:

- auto-size
- manually able to slide left/right

**Interface Changes**
Sunstone

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- [Code](https://github.com/OpenNebula/one-ee/pull/2310)

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2441
