### ISSUE TITLE
hide virtual networks from users

### ISSUE THREAD

**Issue by zinikh** [OpenNebula/one#6000]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
All users on OpenNebula are able to see all virtual networks configured.

**To Reproduce**
create a new user and group, assign VM to that user and group, login with the user and try to add NIC to the VM, all the virtual networks are visible to the user even if he does not belong to the group / owner of the virtual network. user is able to select any of them and attach it to the VM.

**Expected behavior**
when a virtual network is assigned to a user / group. only users in that group are able to see it and use it. if user is not assigned to the group he should not be able to see / use the virtual network

**Details**
 - Affected Component: Sunstone
 - Hypervisor: VCenter 6.7
 - Version: 6.2

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by ONdboca** [comment]
Thank your for reaching out regarding your issue. Please confirm that there are no permissions set for "others" group on the VNET you are trying to use.

**Comment by zinikh** [comment]
Hello Daniel,
the only permissions on all the VNETs are set for the "owner" only to use and manage.
the "group" and "other" do not have any permissions selected for them.
1- VNET-A: owner = NOC, Group = NOC
2- VNET-B: owner = oneadmin, Group = oneadmin
3- VNET-C: owner = oneadmin, Group = oneadmin

user NOC is able to see all VNETs when he's logged in.
