### ISSUE TITLE
CLI listing customizability

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6006]
**Description**
When listing elements, such as images and VMs, with `onevm list` and `oneimage list` it would be nice to have the option of customizing what object template attributes are listed and what format is given to those elements. Ideally this behavior would apply to every listing command, however those are likely the most important ones.

**Use case**
Usability, customize exactly what information you want to see/unsee when listing pools of OpenNebula database objects.

**Interface Changes**
none. Configuration of the CLI should be done through a configuration file.

**Additional Context**
The formatting of the supported elements shown on the CLI show and list options can be customized on their respective yaml file at `/etc/one/cli/<cli_command>.yaml`. It could be nice to re-use that file for this feature. Essentially extending its functionality.

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
Turns out we already have this implemented, but I can't find the documentation for it

```
 ~  onevm list                                                                                                                                  1742ms  Tue Jun 20 15:26:58 2023
  ID NAME                             STAT IP                              TIME
9188 minione-9188                     runn 172.20.0.65                 1d 04h38
9184 ubuntu2204-func-6-7-1lbob-0.test poff 172.20.0.61,192.168.150.1   4d 01h20
9183 ubuntu2204-func-6-7-xjz0p-0.test poff 172.20.0.59,192.168.150.1   4d 05h21
9182 ubuntu2204-func-6-7-q1okq-0.test poff 172.20.0.55,192.168.150.1   4d 05h35
8807 CLOUD4C-VR_test                  poff 172.20.0.79                55d 21h55
8705 bots                             poff 172.20.0.20                95d 03h34
6460 tmux                             poff 172.20.0.5                323d 01h40
5947 market-builder-5947              poff 172.20.0.26               358d 05h43
```
