### ISSUE TITLE
Multiple issues with DockerHub 

### ISSUE THREAD

**Issue by ONdboca** [OpenNebula/one#6012]
**Description**

* [BUG-1] RockyLinux DockerHub image fails when trying to be imported into the datastore.

* [BUG-2] Clean function for the images does not remove all temporary directories on failure.

* [Feature-1] A toggle switch to allow the deletion of the Docker images after success or failure.

* [Feature-2] A warning message that alerts the user to set a tag for the Docker image when `latest` tag is not present/available in DockerHub, for the image.

**To Reproduce**

*[BUG-1] Please execute `onemarketapp download 220 test` with the tag set to 9. You will notice that it will fail to copy it to the datastore.
```root@ubuntu2004-25:~# onemarketapp download 220 asd
Remote server error: downloader.sh: sh: 1: -: not found
/var/lib/one/remotes/datastore/downloader.sh: line 82: : No such file or directory
Error copying
```

* [BUG-2] Images are still present in the local Docker repo after they have been imported to the datastore.

* [Feature-1] A toggle switch for the `clean` function in `docker_downloader.sh`.

* [Feature-2] When executing 'onemarketapp download 220 asd` with no tag, it will default to latest, however not all images allow this flag, hence the user must be notified that the latest tag is not available in the Docker repo.

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
Closing this issue as it is poorly written

* [BUG-1] RockyLinux DockerHub image fails when trying to be imported into the datastore #6196 

* [BUG-2] Clean function for the images does not remove all temporary directories on failure. #6197 

* [Feature-1] A toggle switch to allow the deletion of the Docker images after success or failure. Not planned. Request if needed.

* [Feature-2] A warning message that alerts the user to set a tag for the Docker image when `latest` tag is not present/available in DockerHub, for the image. #6198
