### ISSUE TITLE
Extend EJECT_CDROM feature to hypervisors

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6013]
**Description**
The EJECT_CDROM feature is only supported at the moment through the windows contextualization service. This feature can be implemented at a hypervisor level by means of removing the device definition from the VM. In the case of libvirt this is achieved by using the command

```
"virsh --connect $LIBVIRT_URI change-media $DOMAIN $TARGET_DEVICE --eject --force"
```

The goal is to run this action when the contextualization service finishes after the boot process if the VM has the flag set on the template. At the moment the flag is only read internally by the context program running inside the Windows VM. This flag could be re-used, however, the implementation could be done on a disk basis

**Use case**
Contextualization in Guest OS is done by injecting an ISO to the guest OS. After the **one-context** service is run, the ISO is no longer needed, becoming an unnecessary oddity for the end user.

**Additional Context**
- The drive removal should only occur after the contextualization process is finished in the guest
- This feature could also apply to non context disks
- The `one.vm.updateconf` call will trigger a [prereconfigure](https://github.com/OpenNebula/one/blob/master/src/vmm_mad/remotes/kvm/prereconfigure) and [reconfigure](https://github.com/OpenNebula/one/blob/master/src/vmm_mad/remotes/kvm/reconfigure) action that remove and insert the drive. Needs to be considered to avoid in case of absent context ISO.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
duplicated by #805
