### ISSUE TITLE
[Sunstone] Tm mad system back to default value

### ISSUE THREAD

**Issue by rdziwinski** [OpenNebula/one#6015]
**Description**
Hello,
option in Storage tab -> Storage Options -> Deploy mode back to default value after edit template and select this tab again. (/#templates-tab/form url).

**To Reproduce**
Edit template via sunston gui.
Select deploy mode to ssh for example
Save changes.
Edit template again
Move to Storage tab
Option "deploy mode" is "default"

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.4.0 Community Edition

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
Please note that 5.4.0 is no longer supported, closing this until is reported in a more up to date version

**Comment by rdziwinski** [comment]
Misclick, Nebula Version: 6.4

**Comment by rdziwinski** [comment]
Sorry, My misclick. 6.4 instead of 5.4.

**Comment by tinova** [comment]
ok, reopening, we will check

**Comment by FrederickBor** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/2523
Docs: https://github.com/OpenNebula/docs/pull/2514
