### ISSUE TITLE
Renaming image collides with itself

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/one#6016]
**Description**
It is not possible to rename the image to the name which differs from the original name only in letter case.

**To Reproduce**
Have an image with id - say - 1234, name it `test`, and try to rename it to `Test`:
```
$ oneimage rename 1234 'Test'
[one.image.rename] image cannot be renamed to Test because it collides with image 1234
```

**Expected behavior**
Rename should not conflict with the image itself.

**Details**
 - Affected Component: it can be reproduced boty with `oneimage` and in Sunstone
 - Hypervisor: KVM
 - Version: opennebula-6.4.0-1.el8.x86_64
 
**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Case sensitive behavior depends on the DB backend. You should be able to configure mysql to be case-sensitive in oned.conf

https://docs.opennebula.io/6.6/installation_and_configuration/opennebula_services/oned.html

```COMPARE_BINARY (MySQL only): compare strings using BINARY clause makes name searches case sensitive.```
