### ISSUE TITLE
VM stuck in PROLOG state

### ISSUE THREAD

**Issue by odidev** [OpenNebula/one#6018]
Hi Team, I have been working on testing opennebula on AMD64 as well as ARM64.
&nbsp;&nbsp;&nbsp;
**AMD64:-**

- I am running the following steps: https://github.com/odidev/open-nebula/blob/main/Steps-to-run.md 
- The above steps are referenced from the [Build from Source Documentation](https://docs.opennebula.io/6.4/integration_and_development/references/compile.html), [Single Frontend Installation Documentation](https://docs.opennebula.io/6.4/installation_and_configuration/frontend_installation/install.html) and [Opennebula of AWS Bare metal Blog](https://opennebula.io/building-an-opennebula-private-cloud-on-aws-bare-metal/) 
- When I launch the VM, it gets stuck into “PROLOG” state with error `/var/tmp/one/kvm/deploy Cannot create domain. No such file or directory Disk.0`. Since the recovery method `RETRY` gives error that it cannot be performed on `PROLOG` state. 
- When the recovery method `SUCCESS` (onevm recover --success) is used it goes into `BOOT_FAILURE` or `POWEROFF` state. 

**ARM64:-**

- I am following the same steps as of amd64 platform. 
- When I launch the VM, it gives error `var/tmp/one/kvm/deploy  Cannot create domain. The IDE controllers are not supported for the qemu binary or machine platform`. 

Please provide some pointers for the above issue and suggest if any more steps or dependencies are required while installing from source.

**Comment by OpenNebulaSupport** [comment]
ARM64 is currently not supported as a platform.

Please check your DataStore configuration for the AMD64 deployment, and make sure everything is setup as described in the official documentation, and if the problem persists, submit the configuration in a thread in the [OpenNebula forum](https://forum.opennebula.io)

**Comment by OpenNebulaSupport** [comment]
ARM64 is currently not supported as a platform.

Please check your DataStore configuration for the AMD64 deployment, and make sure everything is setup as described in the official documentation, and if the problem persists, submit the configuration in a thread in the [OpenNebula forum](https://forum.opennebula.io/).
