### ISSUE TITLE
RSunstone advanced filters special characters issue

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6021]
**Description**
When using the advanced filters in RSunstone is not doing correctly for strings with special regex characters such as `+`, `*`, etc.

**To Reproduce**
Try to use advanced filters with texts that have special regex characters.

**Expected behavior**
Filters to bring the current data.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4.2, development

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2357
- Docs: https://github.com/OpenNebula/docs/pull/2427
