### ISSUE TITLE
Locked VM by Admin may unlock by User

### ISSUE THREAD

**Issue by kvakanet** [OpenNebula/one#6022]
**Description**
Locked VM by Admin may unlock by User, but if simple unlock VM return error:"[one.vm.unlock] Cannot unlock: Lock is owned by another user"

**To Reproduce**
1. Lock VM by oneadmin ` onevm lock <VM_ID>`
2. Unlock VM by user `onevm unlock <VM_ID> --user oneuser --password onepassword`
3. Get output: [one.vm.unlock] Cannot unlock: Lock is owned by another user
4. Lock same VM by user `onevm lock <VM_ID> --user oneuser --password onepassword`
5. Unlock VM by user `onevm unlock <VM_ID> --user oneuser --password onepassword`
6. And VM unlocked by user.

**Expected behavior**
A lock set by an administrator should not be overwritten by a user lock and removed later by user. 

**Details**
 - Affected Component: Oned
 - Hypervisor: KVM
 - Version: 6.4

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
Only lock owner can change the lock level. Fix ``--all`` flag, it now equals ``--use``
PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2427)
* [tests](https://github.com/OpenNebula/development/pull/2119)
* [docs](https://github.com/OpenNebula/docs/pull/2459)
