### ISSUE TITLE
Sunstone is not considering changes for oneflow-server configuration attribute

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6026]
**Description**
When changing `:oneflow_server:` on `sunstone-server.conf` it is not considering the value for this. Instead, it is using the zone endpoint and changing the port to 2474

**To Reproduce**
Change the attribute on sunstone server conf and try to use the Service tab.

**Expected behavior**
Service tab to work correctly based on the URL specified by `sunstone-server.conf`

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4.2, development

**Additional context**
As a workaround, you can set `ONEFLOW_ENDPOINT` on the Zone with `onezone update`

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2385
- Docs: https://github.com/OpenNebula/docs/pull/2433
