### ISSUE TITLE
NUMA Usage

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6027]
**Description**
Free pages are not properly rendered. The monitor message includes information about the free pages:

```
$ ./numa_usage.rb
HUGEPAGE = [ NODE_ID = "0", SIZE = "2048", FREE = "0" ]
HUGEPAGE = [ NODE_ID = "0", SIZE = "1048576", FREE = "123" ]
MEMORY_NODE = [ NODE_ID = "0", FREE = "131050996", USED = "133014972" ]
HUGEPAGE = [ NODE_ID = "1", SIZE = "2048", FREE = "0" ]
HUGEPAGE = [ NODE_ID = "1", SIZE = "1048576", FREE = "119" ]
MEMORY_NODE = [ NODE_ID = "1", FREE = "131367644", USED = "132827044" ]
```

But this information is not properly parsed and stored (only linux_usage is considered):
https://github.com/OpenNebula/one/blob/master/src/host/HostMonitoringTemplate.cc#L30

This is the information of the linux_usage probe:

```
HYPERVISOR=kvm
USEDMEMORY=265371308
FREEMEMORY=262889348
FREECPU=5320
USEDCPU=280
NETRX=8690767563
NETTX=118132282926
```

Then this monitor data has to be used to show the monitor usage, like CPU/MEMORY. In the CLI:

https://github.com/OpenNebula/one/blob/master/src/cli/one_helper/onehost_helper.rb#L631

Also monitorization (System information mesage) does not include FREE information, this should be remove
https://github.com/OpenNebula/one/blob/master/src/host/HostShareNUMA.cc#L815
 
For rendering we should include USAGE also, current indormation is:
```
        <HUGEPAGE>
          <FREE><![CDATA[0]]></FREE>
          <PAGES><![CDATA[125]]></PAGES>
          <SIZE><![CDATA[1048576]]></SIZE>
          <USAGE><![CDATA[4]]></USAGE>
        </HUGEPAGE>
```

In this example FREE should be removed and set in MONITORING, and USAGE should be also presented to the user

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
- Code (Ruby Sunstone): https://github.com/OpenNebula/one-ee/pull/2470
- Code (FireEdge Sunstone): https://github.com/OpenNebula/one-ee/pull/2471
- Development: https://github.com/OpenNebula/development/pull/2141
- Docs: covered by https://github.com/OpenNebula/docs/pull/2470
