### ISSUE TITLE
Retention for incremental backups

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6029]
**Description**
Backup interface provides retention (``KEEP_LAST``) to only keep the last N backups. This feature is not implemented for incremental chains.

This feature needs to implement a "rebase" or "commit" action in the backup drivers that takes an increment (or a set of increments) and commit the changes to the previous one. This way we can opt to rebase on the FULL backup or an arbitrary increment for performance reasons.

**Use case**
Control backup datastore usage without the need of doing a reset of the incremental chain

**Interface Changes**
None (or add a new parameter to KEEP_LAST_INCREMENTS, to be able to keep some separated FULL backups). Driver new actions required. 

**Additional Context**
NONE

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by nachowork90** [comment]
This idea is something as synthetic_full, merging the incr#1  in the previous full#0.

The active_full already implemented activating the reset flag. 

Will be good if the reset backup chain flag were a separated function, and not inside the same backup execution.

**Comment by FrederickBor** [comment]
Sunstone:
- Code:
  - https://github.com/OpenNebula/one-ee/pull/2493
  - https://github.com/OpenNebula/one-ee/pull/2505
  - https://github.com/OpenNebula/one-ee/pull/2506
