### ISSUE TITLE
Graceful stop of ongoing backup operations

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6030]
**Description**
Provide an API call to cancel an ongoing backup operation. The API call should not break any existing backup chain. 

**Use case**
Reset long lasting backup operations

**Interface Changes**
New API call to cancel a backup opration. (`one.vm.backupcancel`)

**Additional Context**
None

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
missing tests
