### ISSUE TITLE
new Backups part 1 - the configuration

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#6036]
**Description**
The Community edition has no configuration for the rsync based backup backend

**To Reproduce**
no DATASTORE_MAD configuration in oned.conf (with miss-leading comments)
no DS_MAD_CONF configuration in oned.conf

**Expected behavior**
the oned.conf file should be populated with configuration for the rsync backup backend

**Details**
 - Affected Component: [core]
 - Hypervisor: [KVM]
 - Version: [6.5.80]

**Additional context**
There is a misleading comment in the oned.conf file:

```
#*******************************************************************************
# Datastore Driver Configuration
#*******************************************************************************
# Drivers to manage the datastores, specialized for the storage backend
#   executable: path of the transfer driver executable, can be an
#               absolute path or relative to $ONE_LOCATION/lib/mads (or
#               /usr/lib/one/mads/ if OpenNebula was installed in /)
#
#   arguments : for the driver executable
#       -t number of threads, i.e. number of repo operations at the same time
#       -d datastore mads separated by commas
#       -s system datastore tm drivers, used to monitor shared system ds.
#       **-b backup datastore drivers**
#       -w Timeout in seconds to execute external commands (default unlimited)
#*******************************************************************************
```
There is no 'backup datastore drivers' configuration option available - providing this argument leads to not starting service.
Looking at the sources, the rsync driver is in the 'datastore_mad/remotes' . So adding rsync to the '-d' arguments leads to the next level: the missing DS_MAD_CONF.

The minimal configuration for DS_MAD_CONF that is working for me is

```
DS_MAD_CONF = [
    NAME = "rsync", REQUIRED_ATTRS = "RSYNC_HOST,RSYNC_USER", PERSISTENT_ONLY = "YES"
]
```

And lead to running opennebula service.

Continuing with the bugs in the code...

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by onenhansen** [comment]
This was left out previously but should be included with this commit now - https://github.com/OpenNebula/one/commit/f14b423e223dfe55bf829ba64697e8055f8e5b0f

**Comment by rsmontero** [comment]
@atodorov-storpool you are right configuration is in place (not actual implication in runtime) and files will be missing. This way you can just drop driver files without touching a running oned.
