### ISSUE TITLE
Duplicated code and failure to use a single environment configuration file

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#604]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 1475, https://dev.opennebula.org/issues/1475
Original Date: 2012-09-14

---

From a mail by Matthew Patton:

> Seems every script has the same 10 lines to find common scriptlets to include. Things would be a hell of a lot simpler to maintain if there was a 'env.conf' in /etc/one (or the $ONE_LOCATION equivalent).

Posible solution:

```
if [ -z "${ONE_LOCATION}" ]; then
    . /etc/one/env.sh
else
    . $ONE_LOCATION/etc/env.sh
fi

```

**Comment by rsmontero** [comment]
Fixed
