### ISSUE TITLE
Improve VM Template attributes of restored backup, e.g. DEV_PREFIX 

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#6044]
**Description**
When restoring a VM Backup, I expect the VM to have the same configuration as the master VM from which the backup was taken.

**To Reproduce**
Create a VM with two disks - one with DEV_PREFIX=sd, the other with DEV_PREFIX=vd (so we have VM with virtio-blk and virtio-scsi disks.
Take a backup
Restore from the backup
The VM template has no definition for DEV_PREFIX. The Images recovered from the backups had both DEV_PREFIX=sd
so the instantiated VM will have both disks as sd (sda, sdb)

**Expected behavior**
The instantiated backup VM should have the same disk definition as the one from what the backup was taken

**Details**
 - Affected Component: [Backup]
 - Hypervisor: [KVM]
 - Version: [6.5.80]

**Additional context**

Original VM metadata:
```
DISK = [
  ALLOW_ORPHANS = "YES",
  CLONE = "YES",
  CLONE_TARGET = "SYSTEM",
  CLUSTER_ID = "0",
  DATASTORE = "ssh-IMAGE",
  DATASTORE_ID = "102",
  DEV_PREFIX = "vd",
  DISK_ID = "0",
  DISK_SNAPSHOT_TOTAL_SIZE = "0",
  DISK_TYPE = "FILE",
  DRIVER = "qcow2",
  FORMAT = "qcow2",
  IMAGE = "Alpine-ssh",
  IMAGE_ID = "0",
  IMAGE_STATE = "2",
  LN_TARGET = "SYSTEM",
  ORIGINAL_SIZE = "256",
  READONLY = "NO",
  SAVE = "NO",
  SIZE = "256",
  SOURCE = "/var/lib/one//datastores/102/6738451d4156300c558907bec5c3d8b0",
  TARGET = "vda",
  TM_MAD = "ssh",
  TYPE = "FILE" ]
DISK = [
  ALLOW_ORPHANS = "YES",
  CACHE = "none",
  CLUSTER_ID = "0",
  DATASTORE = "ssh-SYS",
  DATASTORE_ID = "101",
  DEV_PREFIX = "sd",
  DISCARD = "unmap",
  DISK_ID = "2",
  DISK_TYPE = "FILE",
  DRIVER = "qcow2",
  FORMAT = "qcow2",
  FS = "ext4",
  IO = "native",
  SIZE = "100",
  TARGET = "sda",
  TM_MAD = "ssh",
  TM_MAD_SYSTEM = "ssh",
  TYPE = "fs" ]
```
backup VMTemplate contains:
```
DISK = [
  IMAGE_ID = "31" ]
DISK = [
  CACHE = "none",
  DISCARD = "unmap",
  FS = "ext4",
  IMAGE_ID = "32",
  IO = "native",
  TM_MAD_SYSTEM = "ssh" ]
```

On another note - as you can see, one of the VM disks is volatile. I'd expect that the recovered VM had a volatile disk too, but I think it is not possible with the implemented workflow. Is there a description of the workflow to verify? I am mostly reading/reversing the sources.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
I think it is because DEFAULT_DEVICE_PREFIX = "sd" in /etc/one/oned.conf takes precedence when no option is provided in the template for the image_create call.

**Comment by rsmontero** [comment]
https://github.com/OpenNebula/one/blob/master/src/tm_mad/lib/backup.rb#L67 

Change is as easy of adjusting this keys here. I'm keeping this issue to tune for any other parameters we may have overlooked; as is difficult to test every possible combination.

I will also take the liberty to broad the scope of the issue and change the subject

**Comment by atodorov-storpool** [comment]
What about extracting the definitions to configurable variables? That way, there will be no need to do a new release to alter the changes (well, yes, without hacking the code ;-) ) 

[OffTopic] - there are a few more places where a configuration could help instead of hard-coded restrictions, but I need some more time to summarise what of the qcow2-related restrictions are irrelevant with StorPool. (almost all is irrelevant, TBH ;) )

**Comment by rsmontero** [comment]
yes that could be also a good idea. Meantime for 6.6.0 added a note to known issues, and a complete list to what is removed from templates.

* https://docs.opennebula.io/6.5/intro_release_notes/release_notes/known_issues.html#backups

* https://docs.opennebula.io/6.5/management_and_operations/backups/operations.html#vm-backups-restore

**Comment by tinova** [comment]
https://github.com/OpenNebula/docs/pull/2500
