### ISSUE TITLE
Restore opertion should preserve MAC for Ethernet AR types

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#6048]
**Description**
The recoverd VM will have different MAC addresses to the NICs.

**To Reproduce**
Create VM backup
Restore Backup VM template
Instantiate a VM from the backup template

The VM will preserve the IPs but the NIC will have different MACs

**Expected behavior**
The restored VM should have the same NIC/MAC as the original one.

**Details**
 - Affected Component: [core]
 - Hypervisor: [KVM]
 - Version: [6.5.80]

**Additional context**
It is possible to have software in the VM that depends on the interface MAC address, like licensing or other dependencies.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
Yep, but still believe it is missing, because if it is an ethernet-only NIC? Then there is no IP...

Let's have VM with network related metadata as
```
NIC = [
  AR_ID = "0",
  BRIDGE = "virbr0",
  BRIDGE_TYPE = "linux",
  CLUSTER_ID = "0",
  FILTER_IP_SPOOFING = "YES",
  FILTER_MAC_SPOOFING = "YES",
  GATEWAY = "192.168.122.1",
  IP = "192.168.122.3",
  MAC = "02:00:c0:a8:7a:03",
  MODEL = "virtio",
  NAME = "NIC0",
  NETWORK = "192.168.122-virbr0",
  NETWORK_ID = "0",
  NETWORK_UNAME = "oneadmin",
  NIC_ID = "0",
  SECURITY_GROUPS = "0",
  TARGET = "one-4-0",
  VN_MAD = "fw" ]
NIC = [
  AR_ID = "0",
  BRIDGE = "virbr0",
  BRIDGE_TYPE = "linux",
  CLUSTER_ID = "0",
  FILTER_MAC_SPOOFING = "YES",
  MAC = "02:00:2d:85:d1:23",
  MODEL = "virtio",
  NAME = "NIC1",
  NETWORK = "eth-virbr0",
  NETWORK_ID = "2",
  NETWORK_UNAME = "oneadmin",
  NIC_ID = "1",
  SECURITY_GROUPS = "0",
  TARGET = "one-4-1",
  VN_MAD = "fw" ]
NIC_DEFAULT = [
  MODEL = "virtio" ]
```

The created Backup Template will have
```
NIC = [
  FILTER_IP_SPOOFING = "YES",
  FILTER_MAC_SPOOFING = "YES",
  GATEWAY = "192.168.122.1",
  IP = "192.168.122.3",
  MODEL = "virtio",
  NETWORK = "192.168.122-virbr0",
  NETWORK_UNAME = "oneadmin",
  SECURITY_GROUPS = "0" ]
NIC = [
  FILTER_MAC_SPOOFING = "YES",
  MODEL = "virtio",
  NETWORK = "eth-virbr0",
  NETWORK_UNAME = "oneadmin",
  SECURITY_GROUPS = "0" ]
NIC_DEFAULT = [
  MODEL = "virtio" ]
```

Note that the MAC of the second NIC will be lost...

**Comment by rsmontero** [comment]
OK, so this is only happening for AR of Type ETHER

**Comment by tinova** [comment]
https://github.com/OpenNebula/docs/pull/2500
