### ISSUE TITLE
Sunstone private/public FireEdge endpoint should not be case sensitive

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6051]
**Description**

This works:

```
:public_fireedge_endpoint: https://mycloud.atmy.domain/
```

This doesn't (and should):

```
:public_fireedge_endpoint: https://Mycloud.atMy.DOMAIN/
```

*insert spongebob meme*

**Details**
 - Affected Component:  Sunstone,
 - Hypervisor: ALL
 - Version: 6.4.x

**Additional context**

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2432
- Docs: https://github.com/OpenNebula/docs/pull/2463
