### ISSUE TITLE
Not check real size image from marketplace for download

### ISSUE THREAD

**Issue by kvakanet** [OpenNebula/one#6058]
**Description**

In my lab on frontend node disksize 10Gb used 5Gb. 
Downloaded one image rockylinux8 size 4G, but realsize file qcow2 360Mb.
I have get download image almalinux8 size 10G and get error ```[one.image.allocate] Not enough space in datastore```

**To Reproduce**
Get download app(image) where image size more free space on datastore(image)

**Expected behavior**
May be set checkbox = not check image size downloaded or
set new value for image COMPRESSED_SIZE = real qcow2 file size.(and check this value with free space on datastore)
**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.4 CE

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
OpenNebula reserves the capacity the image may take, only consider the compressed size would lead to an inaccurate capacity control.

If you want to bypass this feature you can disable it per datastore with [DATASTORE_CAPACITY_CHECK](https://docs.opennebula.io/6.4/management_and_operations/storage_management/datastores.html#basic-configuration)

I'm closing this as works for me, we'll reopen if other use cases need to be considered.

THANKS for your feedback!
