### ISSUE TITLE
Automatically perform prune operations on Restic

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6062]
**Description**
Currently prune must be performed out-of-band, this issue is to sync delete and prune operations. It needs to check, if this can be performed with active locks on the repo.

In this issue we'll also improve the current locking recovery of the restic repo.

**Use case**
Ease operations on backup repos

**Interface Changes**
None

**Additional Context**
None

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
Fixed as part of #6029
