### ISSUE TITLE
2 broken links (404) in the README.md 

### ISSUE THREAD

**Issue by Lab-Brat** [OpenNebula/one#6065]
**Description**
There are 2 broken links in the [OpenNebula/one](https://github.com/OpenNebula/one) repository's readme. Both return **404 Not Found** Error.
Link 1: [documentation section](https://docs.opennebula.io/stable/deployment/index.html)
Link 2: [reference about the main OpenNebula daemon configuration file](https://docs.opennebula.io/stable/deployment/references/oned_conf.html)

Both links work when `stable` is replaced by `5.12` in the URL, which suggests that the documentation structure was changed in OpenNebula >= 6.0.

**To Reproduce**
Click on the links from the Description section.

**Expected behavior**
Links pointing to the relevant sections in the documentation.

**Details**
N/A

**Additional context**
N/A

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
THANKS, updated the links to point to the sections under the new structure
