### ISSUE TITLE
Issue with RECOVERY_SNAPSHOT_FREQ using Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6067]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When we enable `REPLICA_HOST` on the Datastore and enable inside template `SNAPSHOT FREQUENCY in Seconds = 3600` then once deploying vm from `RECOVERY_SNAPSHOT_FREQ="3600"` is not part of the Context field. VM not replicated.

**To Reproduce**
* enable `REPLICA_HOST` on the Datastore
* enable inside template `SNAPSHOT FREQUENCY in Seconds = 3600`
* `RECOVERY_SNAPSHOT_FREQ="3600"` is not part of the Context field

**Expected behavior**

**Details**
 - Affected Component: Context, Sunstone
 - Hypervisor: all
 - Version: 6.6

**Additional context**

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by onenhansen** [comment]
Bug is confirmed in version 6.6 using Ruby Sunstone.  The issue does not exist in FireEdge Sunstone for this version.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2429
- Docs: https://github.com/OpenNebula/docs/pull/2461
