### ISSUE TITLE
Update VM templates after renaming the components referenced

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6070]
**Description**
After issuing a rename API Call, like `one.image.rename`, the object new name doesn't appear updated on the VM Templates that reference it. 

**Use case**
The calls could issue the name update for consistency purposes. Even though the operation remains fully functional due to the object ID being used for it.

**Additional Context**
This behavior can be implemented with API Hooks triggering on the rename calls.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
OpenNebula uses ID as cananonical references. Names are provided for convenience, scoped to the the user namespace. As an image can be potentially shared  across users (e.g. ACLs) updating original templates will not be always possible. We recommended to use ID's in such cases

We'll close this as won't fix, if another use cases show up we'll reopen....
