### ISSUE TITLE
Isolated Network Ports Configuration

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6071]
**Description**

https://libvirt.org/formatnetwork.html

Since 6.1.0. The port element property isolated, when set to yes (default setting is no) is used to isolate the network traffic of each guest on the network from all other guests connected to the network; it does not have an effect on communication between the guests and the host, or between the guests and destinations beyond this network. This setting is only supported for networks that use a Linux host bridge to connect guest interfaces via a standard tap device (i.e. those with a forward mode of nat, route, open, bridge, or no forward mode).

**Use case**

Some Virtual Machines should be isolated from network traffic from the other machines sharing the same network interface on a host for security purposes.

**Interface Changes**

There should be a configurable attribute for either virtual machines or network interfaces to enable isolation of network interfaces via the vm's libvirt deployment file.

**Additional Context**

Linux bridges which are isolated will also need `bridge link set dev one-<VM_ID>-<NIC_ID> isolated yes` in order to be properly isolated on the host.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
> **Some** Virtual Machines should be isolated from network traffic from the other machines sharing the same network interface on a host for security purposes.

From https://libvirt.org/formatdomain.html#isolating-guests-network-traffic-from-each-other

> Since 6.1.0. The port element property isolated, when set to yes (default setting is no) is used to isolate this interface's network traffic from that of other guest interfaces connected to the same network that also have <port isolated='yes'/>. This setting is only supported for emulated interface devices that use a standard tap device to connect to the network via a Linux host bridge. This property can be inherited from a libvirt network, so if all guests that will be connected to the network should be isolated, it is better to put the setting in the network configuration. (NB: this only prevents guests that have isolated='yes' from communicating with each other; **if there is a guest on the same bridge that doesn't have isolated='yes', even the isolated guests will be able to communicate with it.**)

**Comment by rsmontero** [comment]
After looking into this issue, we think the functionality is already covered by the OpenNebula security groups implementation. Note that you can put as ingress/egress target a Virtual Network. Also, it does not have the limitation pointed by @atodorov-storpool .

Closing this for now as works for me
