### ISSUE TITLE
Restore specific incremental in the chain

### ISSUE THREAD

**Issue by nachowork90** [OpenNebula/one#6074]
**Description**
The user will chose the appropriate id to restore in the incrementalàs chain. 

**Use case**
With this feature the user can control the specific point in time to recover, even if this point is in the middle of the incrementalàs chain. 

- [ ] F and R Sunstone need to extend dialog to restore VM with NAME and INCREMENT_ID 

**Interface Changes**
In susnstone, when the restore interface is showed, add the value to chose the id from the chain to restore/create the image.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by heller785** [comment]
Hi,

Do you have any manual procedure to restore a specific incremental backup ? 
I don't understand why you have add the feature of incremental backup on 6.6.0 if it's not possible to choose a specific date...

I hope you have a manual procedure to resolve this BIG issue.

kind regard

**Comment by nachowork90** [comment]
Hi,

As workaround, you can customize this behavior in the downloader.sh script inside remotes folder for datastores_mad.
You can download as many pieces as you want to rebase the first full.  

Sadly can't be done by the Sunstone Web page nor Fireedge, because is not implemented yet on the XML-RPC.

**Comment by rsmontero** [comment]
@nachowork90 is completely right, We are working to get this ready for 6.6.1. This feature was postponed to 6.6.1 to not delay 6.6.0 more. 

The snippet refer by @nachowork90 is:
https://github.com/OpenNebula/one/blob/master/src/datastore_mad/remotes/downloader.sh#L600

Didn't try myself but if you create an image using PATH in that URL format:

```rsync://100/0:8a3454,1:f6e63e//var/lib/one//datastores/100/6/8a3454/disk.0.0```

And include the increments of interest in the list it will only restore those. You need to manually gather the IDs, though


We understand this is an important feature and we'll do our best to include it in 6.6.1
