### ISSUE TITLE
Deployment fail because VNC password length is higher than 8 characters 

### ISSUE THREAD

**Issue by nachowork90** [OpenNebula/one#6085]
**Description**
An error appear on the VM logs and Deployment or power on actions are interrupted with the error:
unsupported configuration: VNC password is 64 characters long, only 8 permitted Could not create domain from ....

**To Reproduce**
Deploy a new VM or PowerON one in a new Hypervisor using the generate password function in the template Using VNC.  

**Expected behavior**
The VNC password get cropped to 8 chars and deployment get done. 

**Details**
 - Affected Component:  VirtualMachineParser Class, parse_graphics function 
 - Hypervisor: KVM
 - Version: [6.6.0]

**Additional context**
If the modification are handled by Sunstone wizard, the attribute for GRAPHICS TYPE is saved in capital letters "VNC", but in the code the conditional is comparing with lower case "vnc", as consequence the password is not cropped to 8 chars. 

https://github.com/OpenNebula/one/blob/107c0c9aa1a42c851f873523fc5c51d304f9654b/src/vm/VirtualMachineParser.cc#L439

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
Fixed both VNC/SPICE, trim the random generated password and also user set password.
PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2460)
* [tests](https://github.com/OpenNebula/development/pull/2134)
