### ISSUE TITLE
VM backup using qemu-guest-agent cannot be enabled via sunstone wizard

### ISSUE THREAD

**Issue by nachowork90** [OpenNebula/one#6086]
**Description**
VM backup using qemu-guest-agent cannot be enabled via sunstone wizard.

**To Reproduce**
Modify the VM template
Modify the config of one already deployed VM

**Expected behavior**
Modifications persist for agent based backups. 

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [6.6.0]

**Additional context**

In the following reference the value is "QEMU-AGENT" for the select fs-freeze, and the accepted one must be only "AGENT".

https://github.com/OpenNebula/one/blob/107c0c9aa1a42c851f873523fc5c51d304f9654b/src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/backup/html.hbs#L39

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/2455
Docs: https://github.com/OpenNebula/docs/pull/2476

**Comment by rsmontero** [comment]
Fixed in d42ee8a1e003f24e81eaa672eafdd4fccabd02c1
