### ISSUE TITLE
Sunstone backup dialog never shows up after deleting backups

### ISSUE THREAD

**Issue by sk4zuzu** [OpenNebula/one#6088]
**Description**
When backup is created for a VM (FULL or INCREMENTAL) and then removed, the backup dialog (it asks for selecting a backup datastore) never shows up unless the browser tab is refreshed. In the browser's (Chromium) console log this exception appears:
```
foundation.js:294 Uncaught ReferenceError: We're sorry, 'open' is not an available method for this element.
    at jQuery.fn.init.foundation (foundation.js:294:1)
    at Dialog._show [as show] (dialog.js:56:1)
    at call (actions.js:475:1)
    at _runAction (sunstone.js:1042:1)
    at HTMLAnchorElement.<anonymous> (sunstone.js:562:1)
    at HTMLDocument.dispatch (jquery.js:4737:1)
    at elemData.handle (jquery.js:4549:1)
```    
    
**To Reproduce**
1. Setup a restic datastore https://docs.opennebula.io/6.6/management_and_operations/backups/restic.html
2. Open single browser tab with Sunstone
3. Create two VMs
4. Backup the VMs
5. Remove one of the backups for any of the VMs
6. Try creating another backup for any of the VMs (this doesn't work, the backup dialog does not appear unless you refresh the page)

**Expected behavior**
The backup dialog should appear without the need for refreshing the page.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.6

**Additional context**
NA

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@tinova: PR to approve:
- CODE: https://github.com/OpenNebula/one-ee/pull/2509
- DOCS: https://github.com/OpenNebula/docs/pull/2504
