### ISSUE TITLE
Make the Sunstone dashboard editable

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#609]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 1580, https://dev.opennebula.org/issues/1580
Original Date: 2012-10-24

---

Each dashboard box could be a widget. Users could edit their own dashboard view, moving, resizing or deleting different widgets.

**Comment by rsmontero** [comment]
Configuration options to some extent added to yamls. We'll reopen if new options are needed in the future
