### ISSUE TITLE
Separate Vms and vm views

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#6092]
**Description**
in the VMs view there should be an option in the configuration (fireedge views) so that, when clicking on one of the Vms, you can navigate to a view where you only see the content of the VM, without the datatables of the Vm.

It should have the actions button panel and a back button to return to the VMs table.

**Interface Changes**
Fireedge

**Additional Context**
Add any other context or screenshots about the feature request here. Or any other alternative you have considered to addressed this new feature.

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by lgrawet** [comment]
Hello,

This could (should ?) be extended to other views like virtual networks, hosts, images..

Best regards,

Laurent

**Comment by jloboescalona2** [comment]
Yes, because they end up being the same components
