### ISSUE TITLE
typo in capacity-inputs.js

### ISSUE THREAD

**Issue by adriant1978** [OpenNebula/one#6094]
**Description**

There is a typo in the following file which causes JavaScript errors on the client:

src/sunstone/public/app/tabs/templates-tab/form-panels/create/wizard-tabs/general/capacity-inputs.js

**Details**

 - Affected Component: Sunstone
 - Version: Observed in 6.2.0.1 and present on GitHub at time of writing

**Additional context**

Offending typo is on line 202:

if(element && element.TEMPLATE && element.TEMPLATE.TOPOLOGY && element.TEMPLATE.TOPOOGY.CORES) {

Should be:

if(element && element.TEMPLATE && element.TEMPLATE.TOPOLOGY && element.TEMPLATE.TOPOLOGY.CORES) {

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
thanks to both, [added to resolved issues](https://github.com/OpenNebula/docs/commit/6ebc7b77525d026397d87448a255c7ac98051f46) 6.4.3, closing.
