### ISSUE TITLE
Configurable Symlinks in shared datastore

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6098]
**Description**
Currently the Shared Datastore will create a Linked Clone to the base image when deploying a virtual machine to decrease instantiation time.  There should be a configurable option to change this behavior so the transfer manager will completely copy or move the image rather than creating a Linked Clone.

**Use case**
This removes a dependency for the image datastore to remain available as backing images for the system datastore

**Additional Context**
It should be a configurable option in either the datastore attributes or a separate configuration file that tells the shared/qcow2 transfer manager to fully clone the image rather than create a linked copy to the original image, then copy back any persistent disks on termination.

**FireEdge Sunstone**

Expose functionality in DS creation dialog, in Image DS with "Filesystem - shared mode"

* attribute name: QCOW2_STANDALONE
* Sunstone name: "Standalone qcow2 clone"
* Sunstone hint: "Clone qcow2 without a backing chain and no dependencies with Image datastore files"
* Values: "Yes / No (defaults to No)"

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Related PR:
- Code: https://github.com/OpenNebula/one-ee/pull/2592

**Comment by xorel** [comment]
Finished:
code core: https://github.com/OpenNebula/one/commit/8f1d95040cf2daaa45a3653f4f56c19b758e2585
code sunstone: https://github.com/OpenNebula/one/commit/d9f94fa9b26c9167bf67bd8ad5a762951a708c4f
docs: https://github.com/OpenNebula/docs/commit/ee53ab2f98fb902f3b35788a882165cd80a1b50a
tests: https://github.com/OpenNebula/development/commit/6a44fddd52e670a62913d1bf5c81a1b5b2ed06e0
