### ISSUE TITLE
Fault Tolerance hook script improvements

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6099]
**Description**
Improve the handling of local datastore VMs with the Fault Tolerance hook script.

**Use case**
When using VMs on a hosts which have mixed shared and local datastores the only options right now are to have the virtual machines be recreated or deleted during a failure.  This would allow the script to migrate shared VMs while ignoring locally stored VMs.

**Additional Context**
The script will need to check all disks of a virtual machine to determine if it is shared or local, which will determine behavior. When the fault tolerance script is configured to migrate any VMs on the failed host, this should skip over any VMs which contain at least one locally stored disk while still migrating any VMs which are fully on shared storage.

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by onenhansen** [comment]
PR for script: https://github.com/OpenNebula/one-ee/pull/2583
PR for docs: https://github.com/OpenNebula/docs/pull/2550
