### ISSUE TITLE
Sunstone is not configuring correctly HTTPS proxy

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6100]
**Description**
When having an HTTPS proxy, sunstone is not working as it should.

**To Reproduce**
1. Configure HTTPS proxy 
2. Set `:proxy:` variable on `sunstone-server.conf`
3. Try to log in to the support portal

**Expected behavior**
Log-in can be performed.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4, 6.6, development

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2467
- Docs: https://github.com/OpenNebula/docs/pull/2486
