### ISSUE TITLE
[FSunstone] IPv6 are not shown correctly

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6106]
**Description**
When having an IPv6 network FireEdge Sunstone is only showing the MAC address.

**To Reproduce**
1. Create an IPv6 network
2. Attach the network to a VM

**Expected behavior**
IPv6 GLOBAL and ULA  to be displayed

**Details**
 - Affected Component: FireEdge Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4, 6.6, development

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2474
- Docs: https://github.com/OpenNebula/docs/pull/2492

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2487
