### ISSUE TITLE
[FSunstone] Display more than one IP on VM info tab

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#6107]
**Description**
When having more than one IP it will be nice to display on the VM info tab more than one with a considerable maximum (TBD).

**To Reproduce**
Attach more than one IP to a VM

**Expected behavior**
VM info tab to display more IP information.

**Details**
 - Affected Component: FireEdge Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.4, 6.6, development

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
Already implemented in devel, 6.8 & 6.4

![image](https://github.com/OpenNebula/one/assets/134925555/e59ffaba-fd89-46d7-bdbd-65687b6c2b27)
