### ISSUE TITLE
GOCA: Vm migration error -501

### ISSUE THREAD

**Issue by asd2003ru** [OpenNebula/one#6108]
OpenNebula 6.0.0.2
github.com/OpenNebula/one/src/oca/go/src/goca v0.0.0-20230130124959-3c9bfecbd197

Try
	if err := n.controller.VM(134).Migrate(1, true, true, 0, 0); err != nil {

		return err
	}
but have err:
Code: -501
String: "Parameter that is supposed to be integer is not"

**Comment by asd2003ru** [comment]
I add in vm.go vc.ID as Call parameter and error gone.

// Migrate a VM to a target host and/or to another ds
func (vc *VMController) Migrate(hostID int, live, enforce bool, dsID int, migrationType int) error {
	_, err := vc.c.Client.Call("one.vm.migrate", vc.ID, int(hostID), live, enforce, int(dsID), migrationType)
	return err
}

**Comment by sk4zuzu** [comment]
Fix implemented in https://github.com/OpenNebula/one/commit/123af006688cbcbbef1036c735069a422cfea10c
