### ISSUE TITLE
Fireedge: Image download to datastore use wrong user ID

### ISSUE THREAD

**Issue by danielbolsson** [OpenNebula/one#6110]
**Description**
When choosing to download template from marketplace with image, then image user is set to UID 0

**To Reproduce**
Download template "Ubuntu 22.04" with image to datastore as oneadmin user (uid 0). Then try to do the same with another user. This time there will be an error with a conflict with error:

Thu Feb  2 08:40:35 2023 [Z0][ReM][E]: Req:9040 UID:0 one.image.allocate result FAILURE [one.image.allocate] Error allocating a new image. NAME is already taken by IMAGE 20.

**Expected behavior**
By doing the same using Sunstone it works fine.

**Details**
 - Affected Component: Fireedge
 - Hypervisor: No hypervisor
 - Version: 6.6 community edition

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by danielbolsson** [comment]
I noticed that if I download for instance "Debian 12" from apps (OpenNebula Public) using Fireedge as a normal user (not in group oneadmin), then it is possible to download template + image to datastore as owner oneadmin group oneadmin. After download, the template and image is not visible to the user but exists when checking as admin. 

The group that the user belongs to has create

This should not be possible, right? 

User in group 101. Here is complete ACL list:
```
oneadmin@opennebula-sunstone:~$ oneacl list 
  ID     USER RES_VHNIUTGDCOZSvRMAPt   RID OPE_UMAC  ZONE
   3       @1     -H----------------     *     -m--    #0
   4       @1     --N---------------     *     u---    #0
   5       @1     -------D----------     *     u---    #0
   0       @1     V--I-T---O-S----P-     *     ---c     *
   6     @100     -H----------------     *     -m--    #0
   7     @100     --N---------------     *     u---    #0
   8     @100     -------D----------     *     u---    #0
  10     @100     V--------O--------  @100     u---     *
   9     @100     V--I-T---O-S-R----     *     ---c     *
  48     @101     -H----------------     *     um--     *
  43     @101     -------D----------    #1     u---    #0
  42     @101     -------D----------  #110     u---    #0
  41     @101     -------D----------  #111     u---    #0
  47     @101     -H------C---------     *     u---     *
  15     @101     V--------O--------  @101     u---     *
  36     @101     ------------v-----  #100     u---     *
  52     @101     -H----------------  %106     -m--    #0
  53     @101     --N---------------  %106     u---    #0
  54     @101     -------D----------  %106     u---    #0
  80     @101     -H----------------  %105     -m--    #0
  81     @101     --N---------------  %105     u---    #0
  82     @101     -------D----------  %105     u---    #0
  83     @101     --N---------------    #4     u---    #0
  84     @101     --N---------------    #9     u---    #0
  85     @101     -H----------------    #6     -m--    #0
  87     @101     -H----------------    #7     -m--    #0
  89     @101     -H----------------    #9     -m--    #0
  59     @102     V--------O--------  @102     u---     *
  60     @102     -H----------------  %106     -m--    #0
  61     @102     --N---------------  %106     u---    #0
  62     @102     -------D----------  %106     u---    #0
  63     @102     -H----------------  %105     -m--    #0
  64     @102     --N---------------  %105     u---    #0
  65     @102     -------D----------  %105     u---    #0
  67     @102     --N---------------    #9     u---    #0
  77     @102     -------D----------    #1     u---    #0
  78     @102     -------D----------  #110     u---    #0
  79     @102     -------D----------  #111     u---    #0
  86     @102     -H----------------    #6     -m--    #0
  88     @102     -H----------------    #7     -m--    #0
  90     @102     -H----------------    #9     -m--    #0
  91     @102     -H------C---------     *     um--     *
   1        *     ----------Z-------     *     u---     *
   2        *     --------------MA--     *     u---     *
```

**Comment by FrederickBor** [comment]
- Code: https://github.com/OpenNebula/one-ee/pull/2483
- Docs: https://github.com/OpenNebula/docs/pull/2501

**Comment by tinova** [comment]
@danielbolsson this seems to be unrelated, please check the DS permissions and the image + template permissions and ownership, if you still think there is something fishy please open a new ticket with all the relevant info (including this ACLs). Thanks!

> I noticed that if I download for instance "Debian 12" from apps (OpenNebula Public) using Fireedge as a normal user (not in group oneadmin), then it is possible to download template + image to datastore as owner oneadmin group oneadmin. After download, the template and image is not visible to the user but exists when checking as admin.
> 
> This should not be possible, right?
> 
> User in group 101. Here is complete ACL list:
> 
> ```
> oneadmin@opennebula-sunstone:~$ oneacl list 
>   ID     USER RES_VHNIUTGDCOZSvRMAPt   RID OPE_UMAC  ZONE
>    3       @1     -H----------------     *     -m--    #0
>    4       @1     --N---------------     *     u---    #0
>    5       @1     -------D----------     *     u---    #0
>    0       @1     V--I-T---O-S----P-     *     ---c     *
>    6     @100     -H----------------     *     -m--    #0
>    7     @100     --N---------------     *     u---    #0
>    8     @100     -------D----------     *     u---    #0
>   10     @100     V--------O--------  @100     u---     *
>    9     @100     V--I-T---O-S-R----     *     ---c     *
>   48     @101     -H----------------     *     um--     *
>   43     @101     -------D----------    #1     u---    #0
>   42     @101     -------D----------  #110     u---    #0
>   41     @101     -------D----------  #111     u---    #0
>   47     @101     -H------C---------     *     u---     *
>   15     @101     V--------O--------  @101     u---     *
>   36     @101     ------------v-----  #100     u---     *
>   52     @101     -H----------------  %106     -m--    #0
>   53     @101     --N---------------  %106     u---    #0
>   54     @101     -------D----------  %106     u---    #0
>   80     @101     -H----------------  %105     -m--    #0
>   81     @101     --N---------------  %105     u---    #0
>   82     @101     -------D----------  %105     u---    #0
>   83     @101     --N---------------    #4     u---    #0
>   84     @101     --N---------------    #9     u---    #0
>   85     @101     -H----------------    #6     -m--    #0
>   87     @101     -H----------------    #7     -m--    #0
>   89     @101     -H----------------    #9     -m--    #0
>   59     @102     V--------O--------  @102     u---     *
>   60     @102     -H----------------  %106     -m--    #0
>   61     @102     --N---------------  %106     u---    #0
>   62     @102     -------D----------  %106     u---    #0
>   63     @102     -H----------------  %105     -m--    #0
>   64     @102     --N---------------  %105     u---    #0
>   65     @102     -------D----------  %105     u---    #0
>   67     @102     --N---------------    #9     u---    #0
>   77     @102     -------D----------    #1     u---    #0
>   78     @102     -------D----------  #110     u---    #0
>   79     @102     -------D----------  #111     u---    #0
>   86     @102     -H----------------    #6     -m--    #0
>   88     @102     -H----------------    #7     -m--    #0
>   90     @102     -H----------------    #9     -m--    #0
>   91     @102     -H------C---------     *     um--     *
>    1        *     ----------Z-------     *     u---     *
>    2        *     --------------MA--     *     u---     *
> ```
