### ISSUE TITLE
[FSunstone] Remote Authorization Support in FireEdge Sunstone

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6112]
**Description**

FireEdge Sunstone needs to exhibit support for Remote Authentication In order to integrate with external authentication systems (such as Kerberos or SAML based ones like Shibboleth). This will allow the deployment of FireEdge Sunstone in environments where a user can be authenticated in several services, including FireEdge Sunstone, using a Single Sign On mechanism. 

**Use case**

Remote Authorization in FireEdge Sunstone assumes that users are precreated in OpenNebula using the ‘public’ authorization driver. These users should exist in the OpenNebula DB for the authentication to succeed, regardless of the authentication coming from the SSO auth backend.

The interaction with the remote authentication backend (SAML Identity Provider, IdP) is delegated to a higher level proxy, like for instance [apache httpd shibboleth module](https://shibboleth.atlassian.net/wiki/spaces/SP3/pages/2065335062/Apache). Upon successful authentication the proxy must pass onto FireEdge Sunstone the username as a header (X_AUTH_USERNAME) or environment variable (REMOTE_USER).

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@tinova PR to approve:
- [CODE] one-6.6: https://github.com/OpenNebula/one-ee/pull/2558
- [CODE] master: https://github.com/OpenNebula/one-ee/pull/2557
