### ISSUE TITLE
Sunstone quick search shortcuts

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#612]
---

Author Name: **Jan Horacek** (Jan Horacek)
Original Redmine Issue: 1638, https://dev.opennebula.org/issues/1638
Original Date: 2012-11-06

---

It would be fine to have buttons with quick search filters like

Search: [T][Y][M] [...............]

where the tokens will be
T today
Y yesterday
M month

Almost all of the time i'm working with just the images/vms/templates created during last couple of days and pasting part of the date.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Jan Horacek** (Jan Horacek)
Original Date: 2012-12-11T17:11:14Z

---

another nice feature would be [clear] icon in the input box, for reseting the search without manualy deleting the box content

**Comment by rsmontero** [comment]
We have extended the search box, it includes now filters. If the current functionality does not cover this request we'll reopen it
