### ISSUE TITLE
FireEdge VCPU shouldn't not be %

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6131]
**Description**
Not exactly a bug, but still something wrong. When stating the VCPU of a VM in the capacity definition, the correct units are positive integers, not a percentage or a decimal since VCPU translates to CPU cores on the VM.

![image](https://user-images.githubusercontent.com/16429804/218577299-2498f547-2a1d-4716-81ac-1e15093b2982.png)

**To Reproduce**
Define VM capactiy

**Expected behavior**

Virtual CPU should have no measurement unit specified

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
already solved in master

**Comment by FrederickBor** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/2490
