### ISSUE TITLE
[FSunstone] VM Template clone doesn't clone image

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6137]
**Description**
Title

**To Reproduce**
1. Select vm template to clone and check "Clone with images"
2. The cloned template is still pointing to the source image
3. The source image is not cloned

**Expected behavior**
The image cloning should be done if specified

**Details**
 - Version: 6.4+
 

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Code: https://github.com/OpenNebula/one-ee/pull/2524
Docs: https://github.com/OpenNebula/docs/pull/2516
