### ISSUE TITLE
Parse error when update VM in custom vars

### ISSUE THREAD

**Issue by harsxv** [OpenNebula/one#6139]
**Description**
When you want to update the VM configuration using custom vars

**To Reproduce**
Update `PASSWORD` in **Custom Vars** using some special characters at the last string: `$` `\`

**Expected behavior**
VM Configuration updated successfully.

**Details**
 - Affected Component: Sunstone error notification, `opennebula` service crash.
 - Hypervisor: KVM
 - Version: 6.2.0.1

**Additional context**
I believe this bug is typical with the following issue: https://github.com/OpenNebula/one/issues/3232
Error log on Sunstone when :
- Last string `\`:
```
[one.vm.updateconf] Parse error: syntax error, unexpected VARIABLE, expecting COMMA or CBRACKET at line 59, columns 1842:1845
```

- Last string `$`:
```
[one.vm.updateconf] Error parsing: DISK_ID=1@^_^@PASSWORD=thisispasswordwith$@^_^@TARGET=hda. syntax error, unexpected EOA, expecting $end or VARIABLE or RSTRING at line 0, columns 29:30
```

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
does this also happen in 6.4.0 or 6.6.0? please note that 6.2 is no longer supported

**Comment by harsxv** [comment]
Well noted.
Unfortunately, we're still planning on upgrading ONE, I can't reproduce the bug in 6.40 or 6.6.0.

**Comment by tinova** [comment]
Ok, thanks for the feedback. Closing until further notice on 6.4 or 6.6

**Comment by harsxv** [comment]
Hello, 

I reopen this issue.
I upgraded ONE to 6.4.0.1 and the issue still exists.

**To Reproduce**
Update PASSWORD in Custom Vars using some special characters at the last string: $ \

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/32115753/223383286-f2d8f53f-0fd7-4a2d-a948-266235fb74a0.png">
<img width="1040" alt="Screenshot 2023-03-07 at 4 38 21 PM" src="https://user-images.githubusercontent.com/32115753/223383382-cfb3e32e-7e36-401a-9020-0afc4e660b19.png">
