### ISSUE TITLE
Unable to deploy VMs with ISO images from logical volumes

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6140]
**Description**
When using a VM that references an ISO image from a SAN LVM image datastore. The deployment of the VM will always fail with the error being

```log
Wed Feb 15 14:53:00 2023 [Z0][VMM][E]: DEPLOY: error: Failed to create domain from /var/lib/one//datastores/0/4/deployment.0 error: internal error: process exited while connecting to monitor: 2023-02-15T14:53:00.220610Z qemu-kvm-one: -blockdev {"driver":"file","filename":"/var/lib/one//datastores/0/4/disk.1","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}: 'file' driver requires '/var/lib/one//datastores/0/4/disk.1' to be a regular file Could not create domain from /var/lib/one//datastores/0/4/deployment.0 ExitCode: 255
```

This happens due to the following libvirt configuration generated for such VM

```xml
		<disk type='block' device='disk'>
			<source dev='/var/lib/one//datastores/0/4/disk.0'/>
			<target dev='vda' bus='virtio'/>
			<driver name='qemu' type='raw' cache='none' discard='unmap'/>
		</disk>
		<disk type='file' device='cdrom'>
			<source file='/var/lib/one//datastores/0/4/disk.1'/>
			<target dev='hda' bus='ide'/>
			<readonly/>
			<driver name='qemu' type='raw' cache='none' discard='unmap'/>
		</disk>
		<disk type='file' device='cdrom'>
			<source file='/var/lib/one//datastores/0/4/disk.2'/>
			<target dev='hdb' bus='ide'/>
			<readonly/>
			<driver name='qemu' type='raw'/>
		</disk>
```

The CDROM which is the ISO, is coming from a logical volumen, which is a BLOCK, has the type set to `file`.

**To Reproduce**
- Deploy a SAN LVM datastore
- Import an ISO image onto the datastore
- Reference the ISO image on a VM Template
- Deploy

**Expected behavior**
The ISOs stored on logical volumes should be treated as BLOCK devices.

**Additional context**
This problem affects the use case of VM Templates used for the installations of Operating Systems from an ISO, like a standard Windows or Linux install. The workaround would be to perform the setup with file type datastores, like the SSH/Shared/qcow/NFS datastores and then once the OS image with the installed Operating System is read, import it onto the fs_lvm datastore.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
I thought the issue was discussed/resolved with 
https://github.com/OpenNebula/one/issues/3245 and https://github.com/OpenNebula/one/issues/5681

**Comment by dann1** [comment]
> I thought the issue was discussed/resolved with #3245 and #5681

Hi Anton. I read both issues and even though they are kinda related to this one, I don't see how this case could be handled with the changes made. The issue here is related to ISO images stored on fs_lvm image datastores. The issues you mentioned cover the cases of volatile disks and the context ISO. 

Am I missing something 🤔 ?

**Comment by atodorov-storpool** [comment]
Hi @dann1,
Well, `fs_lvm` is defined as a [System Datastore driver](https://github.com/OpenNebula/one/blob/c68c81a86e3ed363cfbb3ea09f116c28e399431d/share/etc/oned.conf#L665) ;-)

But you are right - it is a variation of the matter. I just thought that having several issues on the topic is clear that _every_ VM disk with `DISK_TYPE=BLOCK` must have a block type definition in the domain XML.

Also, could you let me know if you're considering the escalate it to a patch release of the currently supported versions?

**Comment by dann1** [comment]
> But you are right - it is a variation of the matter. I just thought that having several issues on the topic is clear that _every_ VM disk with `DISK_TYPE=BLOCK` must have a block type definition in the domain XML.

For sure, the goal is to respect and not assume the block device dictated by the TM used on the datastore, now we have all of the issues referenced 😉 We have it planned for 7.0 along with other TM changes. We will backport it to 6.4 since it is LTS when it is fixed.
