### ISSUE TITLE
Update backup dialog [only for FSunstone]

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6146]
**Description**
Incremental backups reuse the actual datastore (and image) to store the backups in the chain.  Therefore it is not needed to specify the target datastore when:

* The backup is in INCREMENT mode
* It is not the the first increment in the chain (INCREMENT_ID = -1)
* And we are not resetting the chain (box not checked) 

If this conditions are met we should disable the datastore selection and pass -1 to the API call

**Use case**
Not ask for unneeded inputs.

**Interface Changes**
Sunstone Backup dialog

**Additional Context**
NaN

## Internal issue:
https://github.com/OpenNebula/one-ee/issues/2547

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
* Doc: https://github.com/OpenNebula/docs/commit/26c590dff68c041074b39daa1065a413fe8cabf5
