### ISSUE TITLE
Scheduler: DEFAULT_NIC_SCHED pack and stripe policies are not working as expected

### ISSUE THREAD

**Issue by brodriguez-opennebula** [OpenNebula/one#6149]
**Description**
When the VNET assigned to a NIC is defined as auto, the default `sched.conf` NIC scheduling policy is set to stripe across the VNETS  ranking them depending on which one has more available leases (`-USED_LEASES`), but instead the VNETS are not getting ranked, thus assigning the NICs always to the same VLAN

To make it work as expected, lines [213 to 221 of src/scheduler/src/sched/SchedulerTemplate.cc](https://github.com/OpenNebula/one/blob/master/src/scheduler/src/sched/SchedulerTemplate.cc#L213-221) should be updated switching the values of the case 0 and case 1:

```c++
    switch (policy)
      {   
          case 0: //Packing
              rank = "USED_LEASES";
          break;
  
          case 1: //Striping
              rank = "- USED_LEASES";
          break;
          ...
```

**To Reproduce**
- In `sched.conf` the configuration should be the default
```
DEFAULT_NIC_SCHED = [
   POLICY = 1
]
```
- In a VM template, this should assign the NIC evenly to VNETS 0,1,2 
```
NIC=[
  NETWORK_MODE="AUTO",
  SCHED_REQUIREMENTS="ID=0|ID=1|ID=2" ]
```
But it doesn't work:
```
$ onetemplate instantiate 0 -m 6
VM ID: 300
...
VM ID: 305

$ onevnet list                                                                                                                                                               
  ID USER     GROUP    NAME   LEASES OUTD ERRO
   2 oneadmin oneadmin test2       6    0    0
   1 oneadmin oneadmin test1       0    0    0
   0 oneadmin oneadmin test        0    0    0
```

**Expected behavior**
- If `SCHED_RANK="-USED_LEASES"` is added to the template it works correctly
```
NIC=[
  NETWORK_MODE="AUTO",
  SCHED_RANK="-USED_LEASES",
  SCHED_REQUIREMENTS="ID=0|ID=1|ID=2" ]
```  

```
$ onetemplate instantiate 0 -m 6    
VM ID: 334
...
VM ID: 339

$ onevnet list
  ID USER     GROUP    NAME   LEASES OUTD ERRO
   2 oneadmin oneadmin test2       2    0    0
   1 oneadmin oneadmin test1       2    0    0
   0 oneadmin oneadmin test        2    0    0
```

**Details**
 - Scheduler
 - Hypervisor: KVM (probably others)
 - Version: development

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2539)
* [tests](https://github.com/OpenNebula/development/pull/2171)
* [doc release notes](https://github.com/OpenNebula/docs/pull/2520)
