### ISSUE TITLE
Scale button does not show on service role tab

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#6164]
**Description**
For some reason, the scale button is not showing up in the Services -> role tab on RSunstone.

**To Reproduce**

1. Create a service
2. Go to the role tab
3. The button won't show up

**Expected behavior**
The button to scale the service to show and work properly as in previous versions.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: [e.g. KVM]
 - Version: 6.6 and development

**Additional context**
[Link to the documentation to scale the service](https://docs.opennebula.io/6.6/management_and_operations/multivm_service_management/appflow_elasticity.html#interaction-with-individual-vm-management)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
The problem is because it is not in the view of `mixed/admin.yaml` you must place it in the following position: 
tabs.oneflow-services-tab.panel_tabs_actions.service_roles_tab
`Role.scale_dialog: true`

**Comment by tinova** [comment]
* Code https://github.com/OpenNebula/one-ee/pull/2624
* Doc https://github.com/OpenNebula/docs/commit/4612f9c82f372dd5c9e917c105c8dfb6d9b4bc81
