### ISSUE TITLE
[Sunstone] Remote Auth fails at login

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6165]
**Description**
When using `remote_auth` in Sunstone, the `request.env['HTTP_AUTHORIZATION']` does not exist and this gives a login error, avoiding any connection.

**To Reproduce**
Configure Sunstone using a `remothe_auth` login. Next, try to log in to Sunstone. The server will return an error code 500. The server logs are as follows:

```
POST /login HTTP/1.1 204 - 0.6390
GET / HTTP/1.1 500 - 0.1631
GET /favicon.ico HTTP/1.1" 401 - 0.0008
```

**Expected behavior**
Users should be able to log in through Sunstone.

**Details**
 - Affected Component: Ruby Sunstone
 - Version: 6.6.1

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
solved through https://github.com/OpenNebula/one/issues/6112
