### ISSUE TITLE
Vcenter Driver Error while Attaching NIC

### ISSUE THREAD

**Issue by mehmetaydogduu** [OpenNebula/one#6166]
**Description**
Attaching a network card to a vm not working on vCenter Driver. Rbvmomi gem causes an error 'cant-parse-int'

**To Reproduce**
Clean installation of vOneCloud 6.6.0 & vCenter 8.0.0

**Expected behavior**
It should complete without an error.

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler, or Storage]
 - Hypervisor: vCenter
 - Version: vOneCloud 6.6.0 & vCenter 8

**Additional context**
I shared logs on the forum: https://forum.opennebula.io/t/attach-nic-error-rbvmomi-cant-parse-int/11151

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by mehmetaydogduu** [comment]
Also consider switch to [rbvmomi2](https://github.com/ManageIQ/rbvmomi2) gem.

**Comment by tinova** [comment]
cannot reproduce in vSphere 7. Will reevaluate when vSphere 8 support is added to OpenNebula
