### ISSUE TITLE
Separate context scripts into early and late start

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#617]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 1703, https://dev.opennebula.org/issues/1703
Original Date: 2012-12-20

---

Some services need to be started early in the boot process and others are better started at the end. Separating them in two directories and calling them at different times will be good for some configuration.

**Comment by vholer** [comment]
Already done.
