### ISSUE TITLE
Improve queries pattern for LinuxContainers Marketplace

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6171]
**Description**
Current markeplace drivers issues multiple http request to get a list of all available images. This imposes too much load on the linux containers servers.

This issue is to change this pattern and use https://images.linuxcontainers.org/streams/v1/images.json file that contains all the images. 

**To Reproduce**
NaN

**Expected behavior**
NaM

**Details**
 - Affected Component: Martkeplace - LinuxContainers
 - Hypervisor: -
 - Version: All

**Additional context**

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by albert0marti** [comment]
Many thanks for the heads-up, @stgraber!

**Comment by brodriguez-opennebula** [comment]
Code written and tested in an lxc-ssh microenv. It worked OK

https://github.com/OpenNebula/one-ee/pull/2603

**Comment by rsmontero** [comment]
Merged across branches. Fix should be delivered in next patch releases.
