### ISSUE TITLE
Missing onegate html man

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6172]
**Description**

The onegate html man is not generated during OpenNebula build process. This leads to a not found link when clicking on [its reference](https://docs.opennebula.io/6.6/management_and_operations/references/cli.html#onegate-commands).

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
* Doc https://github.com/OpenNebula/docs/commit/be5f5c3ee045d2096d5ef5697d86524a6f21cad7
