### ISSUE TITLE
VM Template instantiate should add hypervisor as automatic sched requirement

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6176]
**Description**
When a new VM Template is created, hypervisor *must* be selected. This value is saved in the HYPERVISOR attribute only for compatibility purposes (FireEdge always retrieves the VMM driver from the host where the VM is running to ascertain the hypervisor).

Additionally, we need to add the selected hypervisor as a SCHED_REQUIREMENT:

`SCHED_REQUIREMENT="HYPERVISOR={kvm, firecracker, ...}"`

This sched_requirement *must* appear in the Placement "Advanced Options" subtab, as an editable part of the expression. End user can delete it completely or add another boolean conditions to it.

![Screenshot 2023-04-10 at 17 52 58](https://user-images.githubusercontent.com/5102/230939778-36ac6237-4b49-40a2-8e75-59eafbd9ac98.png)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
Already implemented
