### ISSUE TITLE
[FSunstone] UPPERCASE forced on Context custom variables

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6177]
**Description**
When adding a custom context variable, the content of the template attribute is forced as UPPERCASE when entering the text.

**To Reproduce**
VM Template -> Advanced Options -> Context -> Context Custom Variables

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/16429804/231104438-eaa508b1-efd9-47a3-9c47-2e0c3005ecd4.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/16429804/231104987-cfccd8f8-4af3-4ff8-bed6-008bd2133798.png">

**Expected behavior**
casing should not be changed

**Additional context**
The casing is forced even before the template is saved. So core hasn't intervened. When it is saved, core also doesn't validate/reformats/intervenes and is saved as UPPERCASE as well.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
solved in https://github.com/OpenNebula/one/issues/6201
