### ISSUE TITLE
Add support for "Console Output"

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#618]
---

Author Name: **Ricardo Duarte** (Ricardo Duarte)
Original Redmine Issue: 1710, https://dev.opennebula.org/issues/1710
Original Date: 2012-12-31

---

Some hypervisors (KVM, Xen) support dumping the console output to a file.
The console output includes the boot sequence output.
OpenNebula can easily be extended to make the file available from CLI, Sunstone and Self-service, by using the same functionality that supports the "VM Log" tab.
Changes required would be:
- Add the option for console output to the "new" template form, and translate that into hypervisor specific configuration
- Add a "Console Output" tab to the virtual machine details
- Create a get-console-output CLI action

This will then be used to implement the GetConsoleOutput EC2 action.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ricardo Duarte** (Ricardo Duarte)
Original Date: 2013-04-07T13:26:40Z

---

Here is a simple patch that implements console output to file.
Currently it will always create a file based serial port, but can be easily changed to be conditional (ex.: only create the console if parameter X is set).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2013-05-09T12:51:28Z

---

maybe the console output could be gathered during the monitor phase or boot and attached to the vm template (base64 encoded)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ricardo Duarte** (Ricardo Duarte)
Original Date: 2013-05-18T17:49:19Z

---

Ruben S. Montero wrote:
> maybe the console output could be gathered during the monitor phase or boot and attached to the vm template (base64 encoded)

Making it part of the VM template seems like a great idea, as it will simplify getting the console output from all the OpenNebula endpoints/APIs. We just have to keep it truncated to some number of lines, as I assume there is a limitation on how much data you can reasonably put inside the vm template. The raw console.log file can still be kept under the datastore, if the user really needs it.

Gathering it (only) as part of the boot process does not seem to fit tho, because the console output can change during the lifetime of the instance. Doing it during monitoring will also have some problems, because users generally want the data to be available as soon as the instance boots/fails. Can you speed up the first monitoring so that it runs shortly after an instance boots?

**Comment by rsmontero** [comment]
Close because of duplicate
