### ISSUE TITLE
Toggle Automatic Network Selection option in instantiation dialog

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6183]
**Description**
Have a customizable option on the VM instantiation dialog to disable the Automatic Network Selection toggle.

**Use case**
To prevent having the attribute on the template. Turning on Automatic Selection could create an instance template that is not supported by further automation code/script.

**Interface Changes**
Remove the button for Automatic Network Selection without having to disable the whole Network section

![image](https://user-images.githubusercontent.com/33811723/233426364-f002dcd5-d315-4c93-9320-5283977e849c.png)

**Additional Context**
This feature will also need implementation on FireEdge since Sunstone will be eventually deprecated.

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Related PRs (Sunstone):
- Code (master): https://github.com/OpenNebula/one-ee/pull/2585
- Code (one-6.6): https://github.com/OpenNebula/one-ee/pull/2586
