### ISSUE TITLE
Support use of huge pages without CPU pinning

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6185]
**Description**
OpenNebula < 6.6 requires to set a Pin policy for using huge pages. With the implementation of NUMA pinning it should be posible to just specify the desired huge page size, so: 

* OpenNebula will look for a NUMA node with enough free huge pages
* The scheduling will pick the node with more free pages (i.e. try to balance load across NUMA nodes)
* The VM will be configured with CPU affinity to the selected NUMA node
* 
**Use case**
Simply use of huge pages (also easier use of DPDK with Open vSwitch)

**Interface Changes**
Templates can be defined with just HUGEPAGE_SIZE

**Comment by feldsam** [comment]
Hello @rsmontero, I created PR for this issue. In the issue description there is "The VM will be configured with CPU affinity to the selected NUMA node", but if no affinity is selected, them huge pages are pinned to some numa node, but vCPUs are not. This PR fix this, so all vCPUs will be pinned to auto-selected numa node
