### ISSUE TITLE
Review NUMA settings for VM Templates

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#6192]
**Description**
On FireEdge Sunstone, all the NUMA settings must be reviewed to verify they work properly.

**Expected behavior**
NUMA settings work as expected

**Details**
 - Affected Component: FireEdge Sunstone
 - Hypervisor: All
 - Version: development, 6.6.1

**Additional context**
For testing, when using dummy VM templates and trying to click on `NUMA Topology`  under the `NUMA` tab FireEdge interface stops working on a blank screen.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
Solved as part of OpenNebula/one#6376
