### ISSUE TITLE
Can't schedule a reset action for backups

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6193]
Dear OpenNebula Team

**Description**
I am not able to schedule a reset for the current chain of incremental backups for a given VM (in this case, Vm `15`). I will show the steps, in order to arrive to this conclusion.

**To Reproduce**
Sechule a backup action, specifying the option of `--reset`:
```bash
onevm backup --reset --schedule "01/28 11:19" -d 100 15
VM 15: backup scheduled at 2023-01-28 11:21:00 -0500
```

Watching the logs of the VM `15`:
```bash
tail -f /var/log/one/15.log
Fri Apr 28 11:19:33 2023 [Z0][VM][I]: New LCM state is BACKUP
Fri Apr 28 11:19:37 2023 [Z0][VMM][I]: Successfully execute transfer manager driver operation: prebackup_live.
Fri Apr 28 11:19:39 2023 [Z0][VMM][I]: Successfully execute  operation: backup.
Fri Apr 28 11:19:40 2023 [Z0][VMM][I]: Successfully execute transfer manager driver operation: postbackup_live.
Fri Apr 28 11:19:40 2023 [Z0][VMM][I]: VM backup successfully created.
Fri Apr 28 11:19:40 2023 [Z0][VM][I]: New LCM state is RUNNING
Fri Apr 28 11:19:40 2023 [Z0][LCM][I]: Removing 1 backup increments
```

- The action was supposed to take place at the 11:21:00 hrs, but the logs below show that the backup started seconds after the executed the las command.
- The action was successfully executed, but it was not a reset for the current chain, it just created another increment for the current chain.
- From the CLI you can use this options with the `--schedule`, but from the Sunstone you cant specify that the schedule is going to be for a reset.
- With this action, OpenNebula just created a backup, without consider the options `--schedule` nor `--reset`.

**Expected behavior**
A new chain of backups should have been created at the specified time (`2023-01-28 11:21:00 -0500`).

**Details**
 - Affected Component: [Sunstone, Scheduler, Storage]
 - Hypervisor: [KVM]
 - Version: [6.6.0, 6.6.1]

**Use case**
This issue could be considered as an issue for the CLI or a feature request for both, CLI and Sunstone actions (**Add support for schedule reset backups**). This is important, because you may want to create a new chain of incremental backups every X time, automatically without do it from Sunstone, marking the checkbox for it on the backups section, or executing from the CLI `onevm backup --reset -d 100 15`.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
Solved for 6.6.3 release.
For master it was solved in #6063
