### ISSUE TITLE
Change 2-states Switches to a 3-states toggle or switch

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#6194]
**Description**
Currently, FireEdge sends all the information collected from the interface. However, the core does not require all the attributes to be specified, so the less the better.

**Use case**
Not to overcharge the OpenNebula Core with unneeded information.

**Interface Changes**
Two options to evaluate:
- Change the switches for toggles with 3 states: `YES`, `-`, `NO`
- Change the behavior of the switch component to have 3 states: `OFF`, `NEUTRAL`, `ON`

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dcarracedo** [comment]
Closed after commenting with the team
