### ISSUE TITLE
onedb fsck is deleting the references between VMs and their backup images

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6195]
**Description**

As part of the OpenNebula upgrade procedure , the command `onedb fsck` is executed during every OpenNebula upgrade. Even if is not an upgrade, sometimes you need to fix some inconsistencies in the DB. Right now this could be a problem, because is deleting the references of each one of the VMs with their respective backup images. The following snippet is from an output after run `onedb fsck` during upgrade from `6.6.0` to `6.6.1`, but as I said before, you just need toi make use of command, to make unsusefull all your backups in the cloud. They will be physically there, on your `REMOTE_HOST`, but they are no longer usefull in the cloud.

The output after run `onedb fsck`:

```bash
WARNING: Forcing protocol to  TCP  due to option specification. Please explicitly state intended protocol.
MySQL dump stored in /var/lib/one/mysql_localhost_opennebula_2023-4-11_16:44:45.sql
Use 'onedb restore' or restore the DB using the mysql command:
mysql -u user -h server -P port db_name < backup_file


Image 2001 is in Datastore 102 image id list, but it should not
Cluster 0 has not the proper reserved VNC ports
VM 122 is in Image 1964 VM id list, but it should not
VM 158 is in Image 1968 VM id list, but it should not
VM 237 is in Image 1970 VM id list, but it should not
VM 124 is in Image 1990 VM id list, but it should not
VM 247 is in Image 1996 VM id list, but it should not
VM 273 is in Image 2003 VM id list, but it should not
VM 238 is in Image 2008 VM id list, but it should not
VM 251 is in Image 2012 VM id list, but it should not
VM 248 is in Image 2013 VM id list, but it should not
VM 119 is in Image 2017 VM id list, but it should not
VM 123 is in Image 2019 VM id list, but it should not
VM 121 is in Image 2020 VM id list, but it should not
VM 120 is in Image 2021 VM id list, but it should not
VNet 12 AR 0 has leased 10.7.2.250 to VRouter 1, but it is actually free
VNet 12 has 17 used leases, but it is actually 16
VNet 13 AR 0 has leased 10.7.1.15 to VRouter 1, but it is actually free
VNet 13 has 7 used leases, but it is actually 6

Total errors found: 19
Total errors repaired: 19
Total errors unrepaired: 0
A copy of this output was stored in /var/log/one/onedb-fsck.log
```

All those images were backups. This is very dangerous, to lose all those references.

> **NOTE** <br />
> Until OpenNebula team fix this issue, I recommend to use one of the following actions: <br />
> - Execute `onedb fsck` knowing that this will make unusefull all your backups in the cloud, in order to fix other inconsistencies in the database. <br />
> - Dont run ever `onedb fsck`, even after an OpenNebula upgrade, going against the official documentation. <br />

**To Reproduce**

Execute:

```bash
onedb fsck
```

**Expected behavior**

Fix inconsistencies on the database, but backups images should not be considered as an inconsistency.

**Details**
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [6.6.0, 6.6.1]

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2599)
* [tests](https://github.com/OpenNebula/development/pull/2197)
* [release notes](https://github.com/OpenNebula/docs/pull/2560)
