### ISSUE TITLE
OpenNebula Sunstone + SimpleSAMLphp integration

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#620]
---

Author Name: **Milán Unicsovics** (Milán Unicsovics)
Original Redmine Issue: 1731, https://dev.opennebula.org/issues/1731
Original Date: 2013-01-17

---

Hello,

this is a new authentication system for OpenNebula Sunstone, it is designed to work with SimpleSAMLphp, and so the authentication of the users is SAML-federated. On the IDP side you can either use SimpleSAMLphp or other SAML-based software as well. We are using this solution within our institute together with Virtual Organization Management software. Since we have introduced this system user management become much easier. 

This authentication system contains an OpenNebula patch, and two standard SimpleSAMLphp modules. The OpenNebula extension part of the patch based on the XML-RPC API, and works together with SimpleSAMLphp SP. When a user authenticated in SimpleSAMLphp, it transfers an attribute, which informs the OpenNebula authentication module about the user's group. This method allows the user to belong to more groups, and its group can be switched at the login.

*Features:*

* simplified login with SAML
* users can belong to more groups

More info at: "SSP for OpenNebula homepage":http://ssp-for-opennebula.sztaki.hu/

We hope this will be as useful for others as it is for us.
SZTAKI ITAK

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2013-02-14T18:06:22Z

---

We are moving this integration to 4.2 as we think we won't have time to do it. It's not only adding the code to the repo, we also have to create tests for it, integrate other parts that require authentication appart from Sunstone, etc.

Anyway, we think it will be great to have the drivers ready for 4.0 and that could be installed easily on top of it. We can discuss the best method to do it here or by any other means.

Thank you!

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Milán Unicsovics** (Milán Unicsovics)
Original Date: 2013-06-14T13:19:31Z

---

Here is the updated patch for Sunstone + SimpleSAMLphp integration module. It can be applied to OpenNebula 4.1 source code.

Please let us know, if we can help in writing tests or in any other task!

**Comment by terafirmanz** [comment]
Defiantly keen for this and a quick search shows others are. Hope it is not abandoned.

**Comment by tinova** [comment]
Thanks for your interest in a SAML auth backend. We've opened a new ticket (#3824) to reevaluate this, since PHP is not one of the languages used in OpenNebula currently.
