### ISSUE TITLE
Improve LinuxContainers marketplace auto-contextualization process

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6205]
**Description**
When importing an app from the LinuxContainers marketplace, an auto-contextualization process, executed via chroot is triggered to automatically install the contextualization package on the selected distro. The process is slightly different depending on each distro and each distro version.

The process is written on the [lxd_downloader.sh](https://github.com/OpenNebula/one/blob/master/src/datastore_mad/remotes/lxd_downloader.sh#L164-L332) script. There is a lot of duplicated chroot code.

**Use case**
Ease of maintenance. Faster new application support. Mitigate copy/paste errors.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
wontfix
