### ISSUE TITLE
Ceph persitent image "loses" modifications

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/one#6207]
**Description**
When I make an image from non-persistent to persistent, make some changes,and return it to non-persistent again, the modifications made during the persistent state are lost.

**To Reproduce**
```
one# oneimage create -d cephds --persistent --size 1 --name 'persistence test'
ID: 1894
one# onevm disk-attach --image 1894 7258
vm7258# echo AAAAAAAAAAAAAAAAAAAAAA > /dev/sdb; sync
one# onevm disk-detach 7258 2

one# oneimage nonpersistent 1894
one# onevm disk-attach --image 1894 7258
vm7258# dd if=/dev/sdb bs=8 count=1
AAAAAAAA
vm7258# echo BBBBBBBBBBBBBBBBBBBBBB >/dev/sdb; sync
one# onevm disk-detach 7258 2

one# oneimage persistent 1894
one# onevm disk-attach --image 1894 7258
vm7258# dd if=/dev/sdb bs=8 count=1
AAAAAAAA
# OK, the BBBBBBB written while non-persistent indeed did not persist
# Lets make another write, which will hopefully persist:
vm7258# echo CCCCCCCCCCCCCCCCCCCC >/dev/sdb; sync
one# onevm disk-detach 7258 2

one# onevm disk-attach --image 1894 7258
vm7258# dd if=/dev/sdb bs=8 count=1
CCCCCCCC
one# onevm disk-detach 7258 2
# OK, the last persistent modification is still there

one# oneimage nonpersistent 1894
one# onevm disk-attach --image 1894 7258
vm7258# dd if=/dev/sdb bs=8 count=1
AAAAAAAA
one# onevm disk-detach 7258 2
# what? I do not expect A's anymore, they should be C's instead!

one# oneimage persistent 1894
one# onevm disk-attach --image 1894 7258
vm7258# dd if=/dev/sdb bs=8 count=1
CCCCCCCC
```

**Expected behavior**
There should be `CCCCCCCC` all the time since the first time the C's are written to the disk.

**Details**
 - Affected Component: storage
 - Hypervisor: kvm
 - Version: 6.4.0 CE
 - Ceph 17 Quincy
 - CentOS Stream 8

**Additional context**
This was previously reported here in 2016, and is said to be fixed, but it looks like the bug appeared again:
https://dev.opennebula.org/issues/4878.html
https://forum.opennebula.io/t/non-persistent-to-persistent-and-back-again-ceph/2199/5

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Yenya** [comment]
@xorel: this  is a minimal test case. I spent several hours before that trying to update an OS image which has previously been used as non-persistent by some VMs. And only then I created the above test case. So yes, I am pretty confident this is not an oversight at my side.

In the meantime, I have upgraded my OpenNebula to 6.6.0 CE, and tried to reproduce this with the commands above. Yes, the problem is still there.

I tried to look at this at the Ceph level, using the `rbd` command: `rbd snap ls one/one-1896` displays a single snapshot, while there shouldn't be any.

So, even smaller test case is:

```
one# oneimage create -d cephds --persistent --size 1 --name 'persistence test 2'
ID: 1897
one# rbd snap ls one/one-1897
one# oneimage nonpersistent 1897
one# rbd snap ls one/one-1897
one# onevm disk-attach --image 1897 7258 
one# rbd snap ls one/one-1897
one# onevm disk-detach 7258 2
one# rbd snap ls one/one-1897
SNAPID  NAME  SIZE   PROTECTED  TIMESTAMP               
  2411  snap  1 MiB  yes        Fri May 12 21:30:48 2023
```

Note that I did not touch the image from the VM #7258 at all (unless the OS of that VM did it itself, it is Fedora 38 with opennebula-context-linux 6.6.0).

So it seems that `onevm disk-detach` creates a superfluous snapshot of the RBD image. And maybe making the image persistent or non-persistent selects the base image or the last snapsot of it.

-Yenya

**Comment by xorel** [comment]
Thank you for more details, however, I still could not reproduce the issue.

The snapshot (2411) created in the example above is created when attaching the non-persistent disk (clone)
`onevm disk-attach --image 1897 7258 `
but it may take a few seconds to appear. 

I found a bug where the snapshot is not properly deleted on disk-detach or VM terminates but it still does not explain the persistent disk change that you observed. The snapshot created by the clone is always deleted when the disk is switched to persistent and then attached via [ln](https://github.com/OpenNebula/one/blob/master/src/tm_mad/ceph/ln#L94)

**Comment by Yenya** [comment]
@xorel: yes, I cpnfirm that we have CEPH_TRASH configured.
