### ISSUE TITLE
Remove old marketplace documentation

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6208]
**Description**

Appliance documentation is now on the main OpenNebula docs

**Interface Changes**

- [x] https://docs.opennebula.io/appliances/, redirect to https://docs.opennebula.io/stable/marketplace/appliances/index.html
- [x] ~~remove doc link from here http://marketplace.opennebula.io/appliance (upper right doc button)~~
- [x] remove references to https://docs.opennebula.io/appliances/ doc in opennebula main doc and appliances metadata

## Progress Status
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by saiteja13427** [comment]
@tinova can I work on this issue?

**Comment by tinova** [comment]
Thanks for the offering @saiteja13427 , however this is more a infrastructure maintenance related task so it's better if someone from the opennebula team handles it.

If you are willing to, I'd appreciate if you could review the [Apps new doc](https://docs.opennebula.io/6.6/marketplace/appliances/index.html). Corrections can be made as a PR in the [doc github](https://github.com/OpenNebula/docs/tree/master/source/marketplace).

**Comment by saiteja13427** [comment]
Sure @tinova, I will look into it and raise a PR if I get any corrections!
