### ISSUE TITLE
Make context package work on installation phase

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#621]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 1746, https://dev.opennebula.org/issues/1746
Original Date: 2013-01-29

---

The context packages rely on runlevel discovery to symlink the context start script to rc<runlevel>.d. This method does not work when installing the package in the linux installation phase. The postinstall script should be changed so this works.

**Comment by rsmontero** [comment]
closing as worksforme
