### ISSUE TITLE
metallb's oneke service doesn't work due to changes in metallb (and posible solution(?))

### ISSUE THREAD

**Issue by kCyborg** [OpenNebula/one#6210]
**Description**
[MetalLB ](https://metallb.universe.tf/) doesn't give ExternalIP when try to create service type LoadBalancer. It keeps stuck on `Failed to allocate IP for "default/nginx-lb": no available IPs`

**To Reproduce**
Deploy a oneke kubernetes cluster using the official appliances. Steps to deploy are easilly found [here](https://docs.opennebula.io/6.6/quick_start/usage_basics/running_kubernetes_clusters.html) and [here](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#load-balancing-metallb). The only difference is that in the instantiation time I put the values: `172.20.0.50-172.20.0.70` under the **MetalLB IP range (default none)** option.

1. I create a an nginx deployment like in the [tutorial](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#create-an-nginx-deployment).
2. I create a svc type **LoadBalancer**, like in the [tutorial](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#create-a-metallb-loadbalancer-service), when I type `kubectl describe svc ngix-lb` I get:

![image](https://github.com/OpenNebula/one/assets/37458643/e27116af-7627-43b7-a464-3d9aeb2c13f4)

**Expected behavior**
I expect the MetalLB service gives me an IP from the configured pool IP, from where I can reach the services exposed. Something like:

![image](https://github.com/OpenNebula/one/assets/37458643/87d4112c-0c40-494a-93cd-4dc503a0c6c5)

**Details**
 - Affected Component: Not any OpenNebula components are affected
 - Hypervisor: KVM
 - Version: OpenNebula 6.4.0, **OneKE version 1.27 EE**

**Additional context**
I tried to debug the situation here:

3. If I check the MetalLB [configmap](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#load-balancing-metallb) (provided by the OneKE service) I get:

![image](https://github.com/OpenNebula/one/assets/37458643/8003f608-c3e3-4ed5-b0d2-8d4a178a68cf)

So I guess the configmap it's ok.

4. I try to check the logs of the `metallb-controller` and I got this:
![image](https://github.com/OpenNebula/one/assets/37458643/8408e8f0-f61d-44d2-9477-80fce96fdb45)

5. Reading in MetalLB official doc, they claim that they retire support for `configmap` deployments and it's new deprecated (as you can red [here](https://metallb.universe.tf/configuration/migration_to_crds/)). Which it's a little bit confusing because the docx in the [tutorial claim to be using v0.13.9](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#oneke-1-27-1-6-6-1-1-20230511-current) (latest to this day):

(![image](https://github.com/OpenNebula/one/assets/37458643/1d1fefd7-5cf9-4bc5-be38-a8249064493e))

Which lead me to think that current OneKE deployment it's perhaps having and old configuration type (configmap) and maybe it has not been updated to the [latest configuration type](https://metallb.universe.tf/configuration/#layer-2-configuration) 

_______________________________________________________

# How to fix it?
The way around I found to fix the it's just remove the `metallb-system` namespace and all it's resources:

```bash
kubectl delete namespace metallb-system
```

Installing the latest version with:

```bash
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
```

And then creating the new configuration:

```bash
cat << EOF > resources.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nat
  namespace: metallb-system
spec:
  addresses:
    - 172.20.0.50-172.20.0.70
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
EOF

# And then applying it:
kubectl apply -f resources.yaml
```

It's ok, it works, but I would like to count on a version ready to deploy. The solution it's a little bit easy tbh, just a little bit more of love to this, **already awesome**, appliance (I really mean it!!!)!!!

___________________________________________

# Further questions

As I couldn't make it work out of the box and I needed to make a work around the official OneKE deployement I have a question: 

- If I create a new service (LoadBalancer type), should I be able to connect to it directly from the external IP (my public vNET has a public IP). In the [tutorial](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#create-a-metallb-loadbalancer-service) doesn't seem very clear.

Doing a curl to the public IP instead of the private assigned by the LB will it work?
![image](https://github.com/OpenNebula/one/assets/37458643/79d0c8af-84c4-4078-9caf-917ca5f641ad)

Related to this question: I think I might have a work around, but I will need to code it and the master nodes (the ones with the roles `control-plane,etcd,master` will need to have ssh access to the VNF in order to update the `haproxy.cnf` and open a new haproxy instance (to create both *frontend* and *backend* configurations in the `haproxy.cfg`)... 

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by kCyborg** [comment]
Hi there @sk4zuzu !!!

Thanks you for your reply...

> I tested your fix and it worked, but I didn't see the need to undeploy the helm chart. What I did was just 1. deleted the config map, 2. created those CRD documents in the metallb-system namespace 3. created some LodBalancer type service and that worked for me.

Ohhh, I tried it but without deleting the **configmap**, that's where I might have been mistaken. Thanks!


> As for your question, we found MetalLB L2 working only in on-prem scenarios. That is the TCP client that wants to connect to LB's backends has to have correct routing table entries. So if you want to connect from the Internet using this public IP and connect to backends that is not going to work with L2, because this LB is not a normal reverse proxy, it does not "proxy" the traffic it "redirects" it (by answering to ARP requests). 🤔

Ohhh, I think I get it now... 
Altought, in order to have access to this LoadBalancer service from the public IP (in the VNF) I needed to check what IP the scheduler assing to my svc and create a new instance in the VNF's haproxy configuration file (`/etc/haproxy/haproxy.cfg`) redirecting the traffic from the public IP to the IP:Port of the LoadBalancer
I do know that this might be a little recursive, I mean a LoadBalancer svc going throught another LoadBalancer (haproxy), but sometimes users just wanna experience the real world applications, and hey, if it is already there (I mean the MetalLB) why not use it?

_______________________________________

### I have another question:
- When I start a new cluster using the provided OneKE, how can I resize the original storage role vm's disk? I mean, by default it just has 10GB (I'm talking of the `/dev/vdb` disk) and I would wanna make it, 50GB from the very start.

- If I resize the storage role, I mean by adding more VMs to the storage role (Scaling up), how can I set those VMs the disk size to fit the 50GB in the previous question?

- Let's say I have a cluster already with production applications running on top of it, but my monitoring system alert me that my applications are space hunger and I only have 10% free space... What's the recommended way to increase the cluster's space?
 

Once again, **thanks**!!!

**Comment by sk4zuzu** [comment]
Hello! :)

> When I start a new cluster using the provided OneKE, how can I resize the original storage role vm's disk? I mean, by default it just has 10GB (I'm talking of the /dev/vdb disk) and I would wanna make it, 50GB from the very start.

In 1.24 it is 60GB, we made it smaller in 1.27 so the space requirement is weaker for initial deployment, then people can deploy it in smaller OpenNebula datastores.

The 10GB image is just an empty qcow2 disk, you can:

1. Create bigger one (`qemu-img create ...`) and modify VM templates (so they point to the image) after you downloaded everything from the Marketplace. Then you deploy new cluster.

2. Wait for cluster to deploy then use API or CLI to resize the disk (it will hotplug and the filesystem inside will be resized/extended automatically without reboot/downtime).

3. You can "easily" (:thinking:) mock the whole Markeplace using those 2 public repos https://github.com/OpenNebula/appmarket-simple and https://github.com/OpenNebula/marketplace and by modifying the `ENDPOINT` url https://docs.opennebula.io/6.6/marketplace/public_marketplaces/opennebula.html. Then you can basically do whatever you want with templates.. :)

> If I resize the storage role, I mean by adding more VMs to the storage role (Scaling up), how can I set those VMs the disk size to fit the 50GB in the previous question?

I think the only way is to replace the image just like in 1. :thinking: 

> Let's say I have a cluster already with production applications running on top of it, but my monitoring system alert me that my applications are space hunger and I only have 10% free space... What's the recommended way to increase the cluster's space?

Assuming your datastores can hold more data, you can resize/extend disks just like in 2. :thinking:

**Comment by kCyborg** [comment]
> In 1.24 it is 60GB, we made it smaller in 1.27 so the space requirement is weaker for initial deployment, then people can deploy it in smaller OpenNebula datastores.

Understandable




> The 10GB image is just an empty qcow2 disk, you can:
> 
>     1. Create bigger one (`qemu-img create ...`) and modify VM templates (so they point to the image) after you downloaded everything from the Marketplace. Then you deploy new cluster.
> 
>     2. Wait for cluster to deploy then use API or CLI to resize the disk (it will hotplug and the filesystem inside will be resized/extended automatically without reboot/downtime).
> 
>     3. You can "easily" (🤔) mock the whole Markeplace using those 2 public repos https://github.com/OpenNebula/appmarket-simple and https://github.com/OpenNebula/marketplace and by modifying the `ENDPOINT` url https://docs.opennebula.io/6.6/marketplace/public_marketplaces/opennebula.html. Then you can basically do whatever you want with templates.. :)

So I should just edit the VM's template once downloaded from the MarketPlace... Thanks!!!



> Assuming your datastores can hold more data, you can resize/extend disks just like in 2. 🤔

It's recommended to add disks to the storage VMs and then using the Longhorn cli/webUI add those disks? If I do it this way, will I break something?

I don't know if this escape the context of this issue or if it is even possible (because to be honest, I'm that related with ON Services) but: what are the chances to put a new [deployment customization variable](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#deployment-customization) regarding to the disk size of the storage roles' VMs?

**Comment by sk4zuzu** [comment]
Hi @kCyborg

> It's recommended to add disks to the storage VMs and then using the Longhorn cli/webUI add those disks? If I do it this way, will I break something?

What we currently do is a single disk, that can be resized in OpenNebula, then the filesystem's capacity is automatically extended. I believe you should be able to reconfigure Longhorn to use multiple disks, we don't provide this functionality in this applicance (at least yet, maybe someday..). What this applicance deploys is a (let's say) starting configuration, that you can and should customize.

> I don't know if this escape the context of this issue or if it is even possible (because to be honest, I'm that related with ON Services) but: what are the chances to put a new [deployment customization variable](https://docs.opennebula.io/6.6/marketplace/appliances/oneke.html#deployment-customization) regarding to the disk size of the storage roles' VMs?

This is unlikely, because those variables are handled by the one-context daemon inside VMs. A VM cannot resize disk by itself, it'd have to use [OpenNebula's API](https://docs.opennebula.io/6.6/integration_and_development/system_interfaces/api.html?highlight=api#one-vm-diskresize) to resize the disk, so connection from VMs / Hosts to FEs would have to be provided (you could make this work, but this is quite impractical TBH and should not become a requirement). Maybe this should be a discussion about different, tighter integration of Kubernetes with OpenNebula and not in a form of a simple OneFlow appliance :thinking: .

**Comment by sk4zuzu** [comment]
Closing for now, because we released a version with a fix -> https://docs.opennebula.io/6.6/marketplace/appliances/oneke_changelog.html#oneke-s-features-changelog :thinking:
