### ISSUE TITLE
Sunstone overrides DISK SIZE attribute on instantiation

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6215]
**Description**
When instantiating a VM Template through Sunstone, the `one.template.instantiate` API Call is overridden with information. If the target VM Template contains SIZE, within the DISK definition, then the attribute is ignored.

**To Reproduce**

Have a template like

```
root@minione-8898:~# onetemplate show 1 | grep "TEMPLATE CONTENTS" -A 99
TEMPLATE CONTENTS
CONTEXT=[
  NETWORK="YES",
  PASSWORD="2n5pZ6hLu+AsimG/B+ZuEw==",
  REPORT_READY="YES",
  SSH_PUBLIC_KEY="$USER[SSH_PUBLIC_KEY]",
  TOKEN="YES" ]
CPU="1"
DISK=[
  IMAGE_ID="0",
  SIZE="30000" ]
GRAPHICS=[
  LISTEN="0.0.0.0",
  TYPE="VNC" ]
HOT_RESIZE=[
  CPU_HOT_ADD_ENABLED="NO",
  MEMORY_HOT_ADD_ENABLED="NO" ]
LOGO="images/logos/linux.png"
LXD_SECURITY_PRIVILEGED="true"
MEMORY="128"
MEMORY_UNIT_COST="MB"
NIC=[
  NETWORK="vnet",
  NETWORK_UNAME="oneadmin",
  SECURITY_GROUPS="0" ]
NIC_DEFAULT=[
  MODEL="virtio" ]
OS=[
  ARCH="x86_64",
  FIRMWARE="",
  FIRMWARE_SECURE="YES" ]
```

Instantiate that template through sunstone without altering any parameter. The resulting VM will contain the following SIZE attributes

```
root@minione-8898:~# onevm show 0 -j | grep -i size
    "NAME": "resize_boot_issue-0",
      "DISK_SIZE": [
          "SIZE": "3"
          "SIZE": "1"
          "DISK_SNAPSHOT_TOTAL_SIZE": "0",
          "ORIGINAL_SIZE": "256",
          "SIZE": "256",
      "HOT_RESIZE": {
```

**Expected behavior**

When issuing the template instantiation through CLI, the results are the expected ones. The command `onetemplate instantiate 1` results in the following

```
root@minione-8898:~# onevm show 1 -j | grep -i size
    "NAME": "resize_boot_issue-1",
      "DISK_SIZE": [
          "SIZE": "29"
          "SIZE": "1"
          "DISK_SNAPSHOT_TOTAL_SIZE": "0",
          "ORIGINAL_SIZE": "256",
          "SIZE": "30000",
      "HOT_RESIZE": {
```

**Details**
 - Version: 6.4.3

**Additional context**
- The problem didn't happen on 6.4.2
- The API call issued when instantiating through sunstone
```log
Wed May 24 22:16:14 2023 [Z0][ReM][D]: Req:6544 UID:0 IP:127.0.0.1 one.template.instantiate invoked , 1, "", false, "DISK=[
  IMAGE_ID="0"
]

NIC=[
  NETWORK="vnet",
  NETWORK_ID="0",
  NETWORK_UNAME="oneadmin",
  SECURITY_GROUPS="0"
]

OS=[
  ARCH="x86_64",
  FIRMWARE="",
  FIRMWARE_SECURE="YES"
]

NIC_ALIAS = []
SCHED_REQUIREMENTS = []
SCHED_DS_REQUIREMENTS = []", false
```
- The API Call issued when using the CLI

```log
Wed May 24 22:16:50 2023 [Z0][ReM][D]: Req:4432 UID:0 IP:127.0.0.1 one.template.instantiate invoked , 1, "", false, "", false
```

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@tinova Pr to approve:
- Docs: https://github.com/OpenNebula/docs/pull/2590
- Docs: https://github.com/OpenNebula/docs/pull/2589
- Code: https://github.com/OpenNebula/one-ee/pull/2623
