### ISSUE TITLE
6.6.1 debian 11 repository have no Release File

### ISSUE THREAD

**Issue by binooetomo** [OpenNebula/one#6216]
Hi.
I just jump to opennebula and want to start trying it.

**Description**
Failed 'apt update'
```
Err:5 https://downloads.opennebula.io/repo/6.6.1/Debian/11 stable Release
  404  Not Found [IP: 139.162.168.171 443]
Reading package lists... Done
E: The repository 'https://downloads.opennebula.io/repo/6.6.1/Debian/11 stable Release' does not have a Release file.

```

**To Reproduce**
Follow step on https://docs.opennebula.io/6.6/installation_and_configuration/frontend_installation/opennebula_repository_configuration.html#id2

**Expected behavior**
no error

**Details**
- Instalation step
- Repository og 6.6.1 debian 11

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by xorel** [comment]
The correct url is with 6.6 not 6.6.1, it should be fixed now.
Thanks for reporting it
