### ISSUE TITLE
FSunstone currency change is not working

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6222]
**Description**
Changing the currency to USD (by default EURO) doesn't work.

**To Reproduce**
- [Change currency](https://github.com/OpenNebula/one/blob/master/src/fireedge/etc/sunstone/sunstone-server.conf#L68) to USD at `/etc/one/fireedge/sunstone/sunstone-server.conf`
- restart fireedge

![image](https://github.com/OpenNebula/one/assets/33811723/3e4a50d7-9183-4bdc-9480-f9301747b629)

**Expected behavior**
Values should be displayed on USD

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
- code: https://github.com/OpenNebula/one-ee/pull/2631
- docs: https://github.com/OpenNebula/one-ee/pull/2631
