### ISSUE TITLE
New API to add, update or delete VMGroup role

### ISSUE THREAD

**Issue by bartisan** [OpenNebula/one#6227]
**Description**

VM group configuration update evaluated as successful even though configuration change isn't performed.

**To Reproduce**
Steps to reproduce the behavior.

1. Create a new VM Group

```
$ cat vmgroup-example
NAME = "vmgroup-example"

ROLE = [
  NAME = "redis-placement",
  POLICY = "ANTI_AFFINED",
  HOST_AFFINED = "21,23"
]

$ onevmgroup create vmgroup-example
ID: 8
```

2. Update existing role's properties e.g., `HOST_AFFINED`.

```
--- vmgroup-example     2023-06-12 14:10:13.688849783 +0000
+++ vmgroup-example-update      2023-06-12 14:10:03.457843456 +0000
@@ -3,6 +3,6 @@
 ROLE = [
   NAME = "redis-placement",
   POLICY = "ANTI_AFFINED",
-  HOST_AFFINED = "21,23"
+  HOST_AFFINED = "21,22,23"
 ]
```

3. Update VM Group with or without `--append`

```
$ onevmgroup update 8 vmgroup-example-update && date
Mon Jun 12 14:14:16 UTC 2023
```
```
$ onevmgroup update 8 vmgroup-example-update --append && date
Mon Jun 12 14:22:22 UTC 2023
```

Check the API logs:

```
Mon Jun 12 14:14:16 2023 [Z0][ReM][D]: Req:8112 UID:0 IP:127.0.0.1 one.vmgroup.update invoked , 8, "NAME = "vmgroup-exam...", 0
Mon Jun 12 14:14:16 2023 [Z0][ReM][D]: Req:8112 UID:0 one.vmgroup.update result SUCCESS, 8
```

```
Mon Jun 12 14:22:22 2023 [Z0][ReM][D]: Req:8592 UID:0 IP:127.0.0.1 one.vmgroup.update invoked , 8, "NAME = "vmgroup-exam...", 1
Mon Jun 12 14:22:22 2023 [Z0][ReM][D]: Req:8592 UID:0 one.vmgroup.update result SUCCESS, 8
```

4. Listing VM Group properties shows old configuration

```
$ onevmgroup show 8
VM GROUP 8 INFORMATION
ID             : 8
NAME           : vmgroup-example
USER           : oneadmin
GROUP          : oneadmin
LOCK           : None
PERMISSIONS

OWNER          : um-
GROUP          : ---
OTHER          : ---

ROLES
ID   NAME     POLICY       AFFINED_HOSTS      ANTI_AFFINED_HOST  VIRTUAL_MACHINES
0    redis-pl ANTI_AFFINED 21,23              -

TEMPLATE CONTENTS
NAME="vmgroup-example"
```

**Expected behavior**
`onevmgroup update 8 vmgroup-example-update` updates `AFFINED_HOSTS` to `21,22,23` or fails with an appropriate message.

**Details**
 - Affected Component: oned vmgroup.update
 - Hypervisor: KVM
 - Version: 6.4.0.1-1.el8.x86_64

**Additional context**

Initially tried management of the VM group via the Terraform provider and got this behavior; only then tried to reproduce it with `onevmgroup`.

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
The Role is not part of the `TEMPLATE`, so it can't be updated by the `onevmgroup update` command. Unfortunately, there is no way how to change the ROLE attributes. Changing this issue to a Feature request.

New xml-rpc API calls and corresponding commands for CLI, Java and go:
* one.vmgroup.roleadd
* one.vmgroup.roleupdate
* one.vmgroup.roledelete
