### ISSUE TITLE
Error in configuration cores/sockets in vCenter

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6228]
**Description**
When a CPU modification is made with the running machine, vCenter modifies the sockets of the machine (it does not allow the modification of cores). The order is launched from ONE and the CPU of the vm is modified correctly, however ONE keeps the number of sockets constant and increases the number of cores. So we find a discrepancy between the actual configuration of the machine and what ONE says.

**To Reproduce**
- We start from 1 machine arranged with 1 cpu, 1 core and 1 socket
- We changed the hot setting to 2 cpus.
- We see that in ONE the config is 2 cores x 1 socket
- We see that in vCenter the config is 1 core x 2 sockets

**Expected behavior**

**Details**
 - Affected Component: []
 - Hypervisor: [vCenter]
 - Version: [master, 6.6, 6.4]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
wontfix
