### ISSUE TITLE
Clean metrics in Prometheus collectors

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6236]
**Description**
Collectors use a client library for Prometheus based on a Ruby rack application. This application uses an  internal store (synchronized datastore) that index metrics by label in a Hash object. There is no interface to clean entries on the Hash, so the information of past VMs are reported always till a restart of the collector. 

**To Reproduce**
Create delete a VM, information is reported always

**Expected behavior**
Remove metrics for past VMs

**Details**
 - Affected Component: Prometheus
 - Hypervisor: all (KVM specially)
 - Version: 6.6

## Progress Status
- [X] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment]
@rsmontero Hi Mr. Montero

After upgrade to ON EE `6.6.3` I am still getting deleted VMs available to select on the opennebula-vms.json dashboard.

## Steps to reproduce

- Create a VM: `46`
- Delete the VM.
- Create a new VM: `47`

Waited almost 15min and the deleted VM `46` was still there available to select on the dashboard:

![imagen](https://github.com/OpenNebula/one/assets/56793015/a3553c34-4509-4fcc-a36d-286ceafe7492)

**Comment by rsmontero** [comment]
Please make sure that the service has been restarted and it is using the new version.

Also please check directly with the exporter curl localhost at port 9925. Then you can match one_vm_id; there should be no one_vm_id reported by the exporter.

I'm note sure about how the select dropdown of the Graphana dashboard is updated. Maybe you can tune the query for that.

**Comment by Franco-Sparrow** [comment]
Noted Sir. For next time I will force the restart of the services, but I am pretty sure that I did that when I upgraded the cluster. Anyways, I will leave the cronjob for restart the opennebula exporters and prometheus service, just in case, at least a daily execution.
