### ISSUE TITLE
Customisable drop-down lists in sunstone webif

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#624]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 1764, https://dev.opennebula.org/issues/1764
Original Date: 2013-02-10

---

Hi,

Some values are not easy to remember or are prone to syntax errors (bootloader, driver, device model...) while creating a new template with wizard. It would be great to be able to customize some drop/down lists. Those lists would be used to prefill text fields. So user still have the possibility to fill those fields by hand.

Regards,

Laurent

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlos Martín** (Carlos Martín)
Original Date: 2013-05-09T16:01:14Z

---

Maybe this drop down values could depend on a radio button to show options only for kvm, xen, vmware.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2013-09-30T17:34:51Z

---

+1

It could provide some kind of templating templates, disabling some options or forcing others, the ideal would be to make it contextual.

For example:

* when uploading a new ISO:
** if *@type@* is *@CDROM@* then force *@datastore@* to *@ISO@*
** if *@type@* is *@OS@* then enable *@datastore@* *@qcow images@* and *@raw images@*, with *@qcow images@* as default
** if the selected *@datastore@* is *@qcow images@* then set *@driver@* to *@qcow2@*
* when creating a new VM template:
** force architecture *@x86_64@*
** enable *@acpi@*
** disable *@pae@*
** enable VNC console by default

Today I create a basic template and clone it to create new ones, but my users are not as strict as me and they often create VM templates from scratch, forgetting the VNC setting, or other things.

A toggle button to set a template *@as default@* could be interesting in such case.

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2013-09-30T17:37:12Z

---

Daniel Dehennin wrote:

> A toggle button to set a template *@as default@* could be interesting in such case.

Even better, setting the template *@as default for group XXX@*, then we can have different default settings per group.

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2016-11-07T14:21:32Z

---

Today we are generating template from jenkins jobs, so users rarely create their own templates, but as they mostly never create template, they never remember which parameters to set ;-)

Regards.

**Comment by rsmontero** [comment]
We have worked on adding this drop downs. It may be some left, closing this issue to address additional input fields in specific issues
