### ISSUE TITLE
Allow Stdin input on CLI commands

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6242]
**Description**

Currently templates for resouces cannot be input as stdin, only files allowed

**To Reproduce**

Try to create a resource in OpenNebula with the CLI on a bash pipe

**Expected behavior**

Allow Stdin in the CLI, instead of awkward workarounds like temp files.

**Details**
 - Affected Component:  CLI
 - Hypervisor: All
 - Version: development

## Progress Status
- Code committed
  - [x] onevm create
  - [x] onevm disk-attach
  - [x] onevm nic-attach
  - [x] onevm resize
  - [x] onevm updateconf
  - [x] onedatastore create
  - [x] oneimage create
  - [x] onemarket create
  - [x] onemarketapp create
  - [x] onetemplate create
  - [x] onetemplate instantiate
  - [x] onevnet create
  - [x] onevrouter create
  - [x] onevrouter instantiate
  - [x] onevrouter nic-attach 
  - [x] oneflow-template create
  - [x] oneflow-template instantiate
- Testing - QA
  - [x] onevm create
  - [x] onevm disk-attach
  - [x] onevm nic-attach
  - [x] onevm resize
  - [x] onevm updateconf
  - [x] onedatastore create
  - [x] oneimage create
  - [x] onemarket create
  - [x] onemarketapp create
  - [x] onetemplate create
  - [x] onetemplate instantiate
  - [x] onevnet create
  - [x] onevrouter create
  - [x] onevrouter instantiate
  - [x] onevrouter nic-attach 
  - [x] oneflow-template create
  - [x] oneflow-template instantiate
- Documentation
  - [x] Release notes 
  - [x] compatibility
  - [ ] bash symbols escaping

**Comment by paczerny** [comment]
stdin for `update` methods not implement, the method is used for almost all commands. The processing of all commands [is here](https://github.com/OpenNebula/one-ee/blob/master/src/cli/one_helper.rb#L1648)
Add
```
elsif STDIN.wait_readable(0)
    STDIN.read
```
in front of `elseif append` should fix it.
