### ISSUE TITLE
Setting REMOTE-USER or X-AUTH-USERNAME does not work.

### ISSUE THREAD

**Issue by TafkaMax** [OpenNebula/one#6252]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
I am trying to integrate a authentication proxy for sunstone access. I have tested it throroughly and it seems that something is amiss.

https://github.com/OpenNebula/one/blob/master/src/cloud/common/CloudAuth/RemoteCloudAuth.rb

This remotecloudauth says it tries to look for 'REMOTE-USER' or 'HTTP_X_AUTH_USERNAME'

I have tried to set this variable in my proxy requests and the header is present.

```
2023-06-26T15:19:05.321792+03:00 REDACTED openresty-modsecurity-proxy[285259]: {"time":"26/Jun/2023:12:19:05 +0000","client":"","method":"POST","request":"POST /login HTTP/1.1","request_length":2203,"status":500,"bytes_sent":245,"body_bytes_sent":0,"referer":"REDACTED/","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.134 Safari/537.36","request_time":0.026,"request_body":"remember=false&two_factor_auth_token=","resp_body":"","req_headers":"{\"cookie\":\"session=REDACTED\",\"content-type\":\"application\\/x-www-form-urlencoded; charset=UTF-8\",\"remote-user\":\"admin\",\"accept\":\"*\\/*\",\"sec-fetch-site\":\"same-origin\",\"sec-fetch-mode\":\"cors\",\"user-agent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/114.0.5735.134 Safari\\/537.36\",\"sec-fetch-dest\":\"empty\",\"sec-ch-ua\":\"\",\"sec-ch-ua-mobile\":\"?0\",\"sec-ch-ua-platform\":\"\\\"\\\"\",\"x-user\":\"REDACTED\",\"accept-encoding\":\"gzip, deflate\",\"connection\":\"close\",\"accept-language\":\"en-US,en;q=0.9\",\"referer\":\"https:\\/\\/REDACTED\\/\",\"content-length\":\"37\",\"host\":\"REDACTED\",\"origin\":\"https:\\/\\/REDACTED\",\"x-requested-with\":\"XMLHttpRequest\"}","resp_headers":"{\"cache-control\":\"no-store\",\"content-type\":\"application\\/json;charset=utf-8\",\"content-length\":\"0\",\"x-content-type-options\":\"nosniff\",\"connection\":\"close\"}"}
```

As you can see the header called REMOTE-USER is present. I have tried many variations and the result is the same.

The logs are the following for sunstone:

```
Mon Jun 26 15:19:03 2023 [I]: 10.192.10.125 - - [26/Jun/2023:15:19:03 +0300] "GET / HTTP/1.1" 200 - 0.0022
Mon Jun 26 15:19:03 2023 [I]: 10.192.10.125 - - [26/Jun/2023:15:19:03 +0300] "GET /css/app.min.css?v=6.6.0 HTTP/1.1" 200 - 0.0144
Mon Jun 26 15:19:04 2023 [I]: 10.192.10.125 - - [26/Jun/2023:15:19:04 +0300] "GET /dist/login.js HTTP/1.1" 200 - 0.0139
Mon Jun 26 15:19:04 2023 [I]: 10.192.10.125 - - [26/Jun/2023:15:19:04 +0300] "GET /images/opennebula-5.0.png HTTP/1.1" 200 - 0.0040
Mon Jun 26 15:19:05 2023 [I]: Updating user pool cache.
Mon Jun 26 15:19:05 2023 [E]: [one.userpool.info] User couldn't be authenticated, aborting call.
Mon Jun 26 15:19:05 2023 [I]: 10.192.10.125 - - [26/Jun/2023:15:19:05 +0300] "POST /login HTTP/1.1" 500 - 0.0080
```

To debug more I would need to compile sunstone with changes to the  RemoteAuth.rb file and I don't know how to do that.

I have setup a corresponding user called 'admin' in opennebula beforehand and set it to auth driver 'public'.

**To Reproduce**
Set up a reverse proxy that authenticates and sets corresponding headers.

**Expected behavior**
The header in the request is read.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.6

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
Note that the header needs to be REMOTE_USER and not REMOTE-USER.

Closing until we can confirm there is a bug in the code.

**Comment by TafkaMax** [comment]
I tested it with the exact correct header passed to the sunstone listener.

This is a picture log output of one of those requests from the proxy to the backend. 

I have enabled NGINX header and body logging for each response for this exact purpose to debug it and see every header that is passed.

![image](https://github.com/OpenNebula/one/assets/46354923/9a72beb6-9fcb-45e9-9512-7ac998116f39)

The logs are still the same for sunstone.

```
ue Jun 27 12:52:20 2023 [I]: Updating user pool cache.
Tue Jun 27 12:52:20 2023 [E]: [one.userpool.info] User couldn't be authenticated, aborting call.
Tue Jun 27 12:52:20 2023 [I]: REDACTED - - [27/Jun/2023:12:52:20 +0300] "POST /login HTTP/1.1" 500 - 0.0054
```

**Comment by TafkaMax** [comment]
As the user oneadmin@HOST, you can see I have an account called admin with the public driver present.

```
 oneuser list
  ID NAME                                                                                                                                                                                                                          ENAB GROUP    AUTH            VMS     MEMORY        CPU
   2 admin                                                                                                                                                                                                                         yes  oneadmin public      0 /   -      0M /   0.0 /   -
   1 serveradmin                                                                                                                                                                                                                   yes  oneadmin server_c    0 /   -      0M /   0.0 /   -
   0 oneadmin                                                                                                                                                                                                                      yes  oneadmin core              -          -          -
```

**Comment by TafkaMax** [comment]
Does the oneadmin user also need to have "remote" access permissions? I planned to let it stay 'default' in that sense. I guess chaning it to public driver would bork lots of things. Because using XMLRPC is not allowed with the public driver?

**Comment by TafkaMax** [comment]
I added a new user to test it with something else and create the user using:
```
```
oneuser create testuser "testuser" --driver public
```
```
oneuser show testuser
USER 3 INFORMATION                                                              
ID              : 3                   
NAME            : testuser            
GROUP           : users               
PASSWORD        : testuser            
AUTH_DRIVER     : public              
ENABLED         : Yes                 

TOKENS                                                                          

USER TEMPLATE                                                                   
TOKEN_PASSWORD="REDACTED"

VMS USAGE & QUOTAS                                                              

              VMS               MEMORY                  CPU     SYSTEM_DISK_SIZE
      0 /       -        0M /        -      0.00 /        -        0M /        -

VMS USAGE & QUOTAS - RUNNING                                                    

      RUNNING VMS       RUNNING MEMORY          RUNNING CPU
      0 /       -        0M /        -      0.00 /        -

DATASTORE USAGE & QUOTAS                                                        

NETWORK USAGE & QUOTAS                                                          

IMAGE USAGE & QUOTAS                                                            


Now when I try to login I get this message.

```
Tue Jun 27 14:01:29 2023 [I]: Updating user pool cache.
Tue Jun 27 14:01:29 2023 [E]: REMOTE_USER not found in local environment
Tue Jun 27 14:01:29 2023 [I]: REDACTED - - [27/Jun/2023:14:01:29 +0300] "POST /login HTTP/1.1" 500 - 0.1863
```

 Which seems correct. Because the headers are as following.
 
![image](https://github.com/OpenNebula/one/assets/46354923/ae8a13ec-13fa-464e-82b4-ead23ae3154b)

They have a space inbetween.

**Comment by TafkaMax** [comment]
I then corrected it to not have the space and now I get this ambigious message again:

```
Tue Jun 27 14:09:12 2023 [I]: Updating user pool cache.
Tue Jun 27 14:09:12 2023 [E]: [one.userpool.info] User couldn't be authenticated, aborting call.
Tue Jun 27 14:09:12 2023 [I]: REDACTED - - [27/Jun/2023:14:09:12 +0300] "POST /login HTTP/1.1" 500 - 0.0399
```

**Comment by TafkaMax** [comment]
Hmm attempting direct auth: `oneuser show --user testuser`

```
Tue Jun 27 15:02:51 2023 [Z0][AuM][E]: User: testuser attempted a direct authentication.
Tue Jun 27 15:02:51 2023 [Z0][ReM][D]: Req:1120 UID:-1 IP:127.0.0.1 one.user.info invoked , -1, false
Tue Jun 27 15:02:51 2023 [Z0][ReM][E]: Req:1120 UID:- one.user.info result FAILURE [one.user.info] User couldn't be authenticated, aborting call.
```

**Comment by TafkaMax** [comment]
I put on the full debug mode in remotecloudauth.

Inside RemoteCloudAuth.rb
```
        logger.info{ "#{ENV.to_h.to_yaml}" }
        remote_user   = env['REMOTE_USER'] || env['HTTP_X_AUTH_USERNAME']
        remote_user_new = env['X-USER']
        logger.info{ "Remote user variable from HTTP request before nil: #{remote_user}"}
        logger.info{ "Remote user X-USER variable from HTTP request before nil: #{remote_user_new}"}
        remote_user   = nil if remote_user == '(null)'
        remote_user_new   = nil if remote_user_new == '(null)'
        logger.info{ "Remote user variable from HTTP request: #{remote_user}"}
        logger.info{ "Remote user X-USER variable from HTTP request: #{remote_user_new}"}
```

As you can see the ENV variable does not contain any of my headers, which is weird.
```
Wed Jun 28 10:23:53 2023 [I]: ---
LANG: C
LANGUAGE: en_US:en
PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
HOME: "/var/lib/one"
LOGNAME: oneadmin
USER: oneadmin
SHELL: "/bin/bash"
INVOCATION_ID: REDACTED
JOURNAL_STREAM: 8:22421274
ONE_XMLRPC: http://localhost:2633/RPC2
ONE_XMLRPC_TIMEOUT: '60'
TMPDIR: "/var/tmp"
ONE_CIPHER_AUTH: "/var/lib/one/.one/sunstone_auth"

```

**Comment by TafkaMax** [comment]
NVM when i changed ENV in caps to env then I got some headers, debugging some more!

**Comment by TafkaMax** [comment]
I think I found something. It seems 'HTTP' is added to every request and just adding REMOTE_USER does not work.
```
HTTP_REMOTE_USER: testuser
HTTP_X_REMOTE_USER: testuser
HTTP_HTTP_X_AUTH_USERNAME: testuser
```

**Comment by TafkaMax** [comment]
It seems something else is amiss, the headers are OK.

```
Wed Jun 28 10:46:52 2023 [I]: Updating user pool cache.
Wed Jun 28 10:46:52 2023 [I]: Remote user variable from HTTP request before nil: testuser
Wed Jun 28 10:46:52 2023 [I]: Remote user variable from HTTP request: testuser
Wed Jun 28 10:46:52 2023 [I]: Remote user testuser is present in database and header was present in request.
Wed Jun 28 10:46:52 2023 [I]: REDACTED - - [28/Jun/2023:10:46:52 +0300] "POST /login HTTP/1.1" 500 - 0.3648
```

Full code with all the loggers to show header is present, but somehing is amiss further down the authentication line.
```
    def do_auth(env, params={})
        # For Kerberos, the web service should be set to include the remote_user in the environment.
        remote_user   = env['REMOTE_USER'] || env['HTTP_X_AUTH_USERNAME']
        logger.info{ "Remote user variable from HTTP request before nil: #{remote_user}"}
        remote_user   = nil if remote_user == '(null)'
        logger.info{ "Remote user variable from HTTP request: #{remote_user}"}

        # Use the https credentials for authentication
        unless remote_user.nil?
            # Password should be REMOTE_USER itself.
            username = get_username(remote_user)
            if username
                logger.info{ "Remote user #{username} is present in database and header was present in request."}
                return username
            else
                raise "Username not found in local database: " + remote_user
            end
        else
            raise "REMOTE_USER not found in local environment"
        end

        return nil
    end

```

**Comment by TafkaMax** [comment]
It seems to be a problem somewhere in the authentication part of opennebula.

In `/var/log/one/oned.log` the following info is displayed

```
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:960 UID:3 IP:127.0.0.1 one.user.info invoked , -1, false
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:960 UID:3 one.user.info result SUCCESS, "<USER><ID>3</ID><GID..."
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:4736 UID:0 IP:127.0.0.1 one.user.info invoked , 3, false
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:4736 UID:0 one.user.info result SUCCESS, "<USER><ID>3</ID><GID..."
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:2512 UID:3 IP:127.0.0.1 one.group.info invoked , -1, false
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:2512 UID:3 one.group.info result SUCCESS, "<GROUP><ID>1</ID><NA..."
Wed Jun 28 12:18:00 2023 [Z0][AuM][D]: _authenticate: -
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:8656 UID:1 IP:127.0.0.1 one.system.config invoked 
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:8656 UID:1 one.system.config result SUCCESS, "<OPENNEBULA_CONFIGUR..."
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:1392 UID:1 IP:127.0.0.1 one.system.config invoked 
Wed Jun 28 12:18:00 2023 [Z0][ReM][D]: Req:1392 UID:1 one.system.config result SUCCESS, "<OPENNEBULA_CONFIGUR..."
```

I have no idea what to make of this.

**Comment by TafkaMax** [comment]
Please look at https://forum.opennebula.io/t/authentication-problems-using-auth-method-remote-and-driver-public/11384

`HTTP_AUTHORIZATION` header needs to be set aswell FYI. Also webauthn seemed to intervene, but I don't have to waste anymore on that topic, so I just made webauthn an option to disable it in the `sunstone-server.conf`.
