### ISSUE TITLE
Change the use of Internal Snapshots to External Snapshots

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6259]
**Description**
The disk snapshot and VM snapshot actions both use internal snapshots for their functions.  External snapshots are now recommended as the internal snapshots are no longer being developed any further.

**Use case**
This would allow snapshots to be taken of disks which are not of QCOW2 format and can be taken without any guest downtime.

**Interface Changes**
No interface changes should be required, this would be a backend change.

**Additional Context**
Migrators may be necessary for upgrading to this feature from previous Internal Snapshots.
Currently External Snapshots are not fully implemented but there is a workaround for recovering from them:

https://access.redhat.com/documentation/fr-fr/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-troubleshooting-workaround_for_creating_external_snapshots_with_libvirt
https://wiki.libvirt.org/I_created_an_external_snapshot_but_libvirt_will_not_let_me_delete_or_revert_to_it.html

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
IT does not apply, OpenNebula uses external snapthos
