### ISSUE TITLE
create hooks for API actions on network and image resources

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#626]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 1783, https://dev.opennebula.org/issues/1783
Original Date: 2013-02-26

---

Apart from the create, delete hooks, add basic hooks for network and image API calls. The image resource should also include the saveas hook (one.vm.saveas). 

This is also to include hooks on update operations

**Comment by rsmontero** [comment]
Done
