### ISSUE TITLE
Action schedule is not setting the right day of the week in Sunstone on checkmark box

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6260]
**Description**
If you add a new action to the VM, no matter what kind of action, it will not set the right day of the week in Sunstone.

**To Reproduce**
Create a new action, for example, for backups:

```bash
onevm backup --schedule "07/03 01:00" --weekly 6 -d 100 27
```

> NOTE
> This was also donde vie Sunstone and same error was achieved at the end of the test.

```bash
onevm show 27
```

```bash
# [...]
SCHEDULED ACTIONS
   ID ACTION  ARGS   SCHEDULED   REPEAT   END STATUS
    0 backup   100 07/03 01:00 Weekly 6  None Next in 15.04 hours
# [...]
```

But if you go to Sunstone, apparently everything is fine:

![imagen](https://github.com/OpenNebula/one/assets/56793015/ecbab99e-578b-4d70-a2e3-f3f5ac27c242)

Try edit the recently created action:

![imagen](https://github.com/OpenNebula/one/assets/56793015/4e593b06-dbd8-473b-b512-95149d8bc287)

You will see that Sunstone is not setting the right day for the current created action (no matter if you created the action via Sunstone or CLI):

![imagen](https://github.com/OpenNebula/one/assets/56793015/0dc7ed49-907b-46a3-af1e-707f00b25b42)

Another example with multiples days schedulled on a week:

![imagen](https://github.com/OpenNebula/one/assets/56793015/5fb9061b-3d62-4144-9c78-ccff90137a76)

Another example specifying Sunday (0):

![image](https://github.com/OpenNebula/one/assets/56793015/30bd8c56-f264-42c9-888c-f599566d16e5)

It will allways display, on the checkmark box, a day after the one specified in the creation of the action.

**Expected behavior**
Once created the action, if you try to edit it, Sunstone should display, on the checkmark box, the right day of the created action.

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [6.6.2]

**Additional context**

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by nachowork90** [comment]
Yes @Franco-Sparrow, I have experienced the same issue, I have made a PR to fix the issue, you can check the commit (88267fa).

**Comment by Franco-Sparrow** [comment]
@nachowork90 thanks buddy, it works. Mr. @jloboescalona2 the patch recomended by nacho it works. This is what I did for an already deployed sunstone.

**On the orchestrator leader**

Modify the files `/usr/lib/one/sunstone/public/dist/main.js` and `/usr/lib/one/sunstone/public/dist/main-dist.js` and leave both with the following lines as follow:

```js
# [...]
75197                   dataDays.forEach(function(dataValue){
75198                     if(days[dataValue]){
75199                       if (dataValue > 0){
75200                         $(days[dataValue - 1]).prop("checked", true);
75201                       } else if (dataValue == 0){
75202                         $(days[6]).prop("checked", true);
75203                       }
75204                     }
75205                   });
# [...]                      
```

Restart Sunstone:

```bash
systemctl restart opennebula-sunstone
```

Apply the changes on the followers:

```bash
follower1=orchestrator2
follower2=orchestrator3
rsync -avP /usr/lib/one/sunstone/public/dist/main.js $follower1:/usr/lib/one/sunstone/public/dist/main.js && \
rsync -avP /usr/lib/one/sunstone/public/dist/main-dist.js $follower1:/usr/lib/one/sunstone/public/dist/main-dist.js && \
rsync -avP /usr/lib/one/sunstone/public/dist/main.js $follower2:/usr/lib/one/sunstone/public/dist/main.js && \
rsync -avP /usr/lib/one/sunstone/public/dist/main-dist.js $follower2:/usr/lib/one/sunstone/public/dist/main-dist.js && \
ssh $follower1 "systemctl restart opennebula-sunstone" && \
ssh $follower2 "systemctl restart opennebula-sunstone"
```

![image](https://github.com/OpenNebula/one/assets/56793015/8926244e-9683-4673-a1e0-030c4f3edea2)

**Comment by jloboescalona2** [comment]
In master, this issue was solved with this one: https://github.com/OpenNebula/one/issues/6063
