### ISSUE TITLE
Delete external disk snapshots using blockcommit

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6265]
**Description**
OpenNebula disk snapshots creates external disk images that allow in general any backing file layouts.  This prevents the commit of changes to snapshots with children as it will break the whole chain. 

For example: 
```
┌──────────┐     ┌──┐     ┌──┐    ┌─────────┐
│Base Image│◄────┤1 │◄────┤3 ◄────┤ WR SNAP │
└──────────┘     └──┘     └──┘    └─────────┘
                   ▲        ▲
                   │        │
                   │        │
                 ┌─┴┐     ┌─┴┐
                 │ 2│     │ 4│
                 └──┘     └──┘
```
In this case we cannot commit snap3 on top of snap1 as it will break snap2. However usually snapshots does not requiere such a generic layout and follow a linear approach.

In this case we can implement the delete operation of any snapshot by commiting the changes on the parent one:
```
┌──────────┐     ┌──┐     ┌──┐    ┌─────────┐
│Base Image│◄────┤1 │◄────┤3 ◄────┤ WR SNAP │
└──────────┘     └──┘     └──┘    └─────────┘
```

We can delete snap 3 by committing changes into snap 1.

**Use case**
Delete snapshots in a linear chain

**Interface Changes**
It should not involve any 

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
This has been implemented, and ready for release

**Comment by heller785** [comment]
Hi,

i've upgrade my opennebula to the last version 6.6.3 but isn't possible to delete a disk snapshot when the disk is in persistent. Can you explain why ?

[one.vm.disksnapshotdelete] Cannot delete snapshot 0 for persistent disk images

Regards

**Comment by rsmontero** [comment]
Hi @heller785 ,

For persistent disks snapshot 0 is not an actual snapshot but the base disk, and in general that would mean pulling the whole disk. But the main problem we had is that the drivers create a link to the 0 file (representing snapshot 0) in the image repo as well that would require to be updated (some times after terminating the VM depeding on the driver)

Taking all this considerations we opted to limit the delete to snap > 0 for persistent images. Performance wise, as I said there is no real snapshot if that's a concern.

I hope it is clear the rationale behind the decision. 

Thanks for trying the new feature, and additional feedback is more than welcome :)

**Comment by heller785** [comment]
I understand that your blockage is at the level of your development. But I find it completely incomprehensible to have this type of behavior..

A snapshot is a temporary image that allows us to rollback in the event of a problem but also to be able to set up agentless backup. We always take one step forward and 10 steps back with opennebula upgrades.

I don't understand why we still have this type of blockage.
Thank you for the update but it still doesn't meet our need.

Cordially

**Comment by rsmontero** [comment]
Sorry but is not an snapshot it's a link to the base image registered in the image repo. So it's not an snapshot is a link to the base image, you can take a look to the driver action:

https://github.com/OpenNebula/one/blob/master/src/tm_mad/qcow2/ln#L94

(so it's linking to what you registered in the image repo). So for the first "snapshot" 0, it is just the base image + any modification you did till you decide to checkpoint that. 

If you want a temporary snapshot, simply take another snapshot, that way you can remove snapshot 1 (or revert to original point) whenever you want. It's quite a simply workaround. I don't see how this new feature will not fit your needs, using this work around. 

I hope you understand now the underlying file structure.

Thanks again for your comments

**Comment by heller785** [comment]
Hi,

With this behavior, it isn't possible to extend the disk in running state... because you need to have a first snapshot.
How i can say to my customer, that if they want to extend their disk, they need to shutdown heir VMs ? 

I hope you understand my case.

Regard
