### ISSUE TITLE
[FSunstone] Deploy VM after instantiate casues React app to crash

### ISSUE THREAD

**Issue by dcarracedo** [OpenNebula/one#6276]
**Description**
If you try to deploy a VM after instantiate it (with scheduler service stopped), the VM will be deploy ok but the React app crash.

![Screenshot from 2023-07-20 19-47-14](https://github.com/OpenNebula/one/assets/134921994/b42324a0-c004-4fc1-b8fe-d3b69f314105)

[Screencast from 20-07-23 19:27:52.webm](https://github.com/OpenNebula/one/assets/134921994/ff7696c7-47ed-4f2d-9292-4214a3ee8436)

**To Reproduce**

1. Stop opennebula-scheduler service.
2. Log in with "oneadmin" user.
3. Go to Instances > VM.
4. Create a new VM.
5. Wait until the VM is at PENDING state.
6. Select the VM
7. Click on Deploy action
8. A form to deploy the VM is showed.
9. Select a host.
10. Select (or not, is optional) a datastore.
11. Click finish. 

**Expected behavior**
The React app has not to crash and VM lists are showed.

**Details**
 - Affected Component: Fireedge Sunstone, Scheduler
 - Hypervisor: KVM
 - Version: 6.6.3

**Additional context**
If the VM is on running state, you undeploy it, and after that, you try to deploy it, React app works fine and there is no error.

Staktrace from Console of Chrome:

`bundle.sunstone.js:254 Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ua (bundle.sunstone.js:254:59605)
    at Object.Aa [as useMemo] (bundle.sunstone.js:254:63665)
    at t.useMemo (bundle.sunstone.js:278:5745)
    at g (bundle.sunstone.js:220:416391)
    at r (bundle.sunstone.js:220:418167)
    at useQuery (bundle.sunstone.js:220:420686)
    at De (7829.bundle.sunstone.js:1:15161)
    at sa (bundle.sunstone.js:254:59054)
    at za (bundle.sunstone.js:254:68572)
    at qs (bundle.sunstone.js:254:112109)
overrideMethod @ console.js:213
cs @ bundle.sunstone.js:254
r.callback @ bundle.sunstone.js:254
hi @ bundle.sunstone.js:254
gs @ bundle.sunstone.js:254
Nl @ bundle.sunstone.js:254
t.unstable_runWithPriority @ bundle.sunstone.js:286
Wo @ bundle.sunstone.js:254
Ml @ bundle.sunstone.js:254
bl @ bundle.sunstone.js:254
(anonymous) @ bundle.sunstone.js:254bundle.sunstone.js:254 Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ua (bundle.sunstone.js:254:59605)
    at Object.Aa [as useMemo] (bundle.sunstone.js:254:63665)
    at t.useMemo (bundle.sunstone.js:278:5745)
    at g (bundle.sunstone.js:220:416391)
    at r (bundle.sunstone.js:220:418167)
    at useQuery (bundle.sunstone.js:220:420686)
    at De (7829.bundle.sunstone.js:1:15161)
    at sa (bundle.sunstone.js:254:59054)
    at za (bundle.sunstone.js:254:68572)
    at qs (bundle.sunstone.js:254:112109)
overrideMethod @ console.js:213
cs @ bundle.sunstone.js:254
r.callback @ bundle.sunstone.js:254
hi @ bundle.sunstone.js:254
gs @ bundle.sunstone.js:254
Nl @ bundle.sunstone.js:254
t.unstable_runWithPriority @ bundle.sunstone.js:286
Wo @ bundle.sunstone.js:254
Ml @ bundle.sunstone.js:254
bl @ bundle.sunstone.js:254
(anonymous) @ bundle.sunstone.js:254
t.unstable_runWithPriority @ bundle.sunstone.js:286
Wo @ bundle.sunstone.js:254
Yo @ bundle.sunstone.js:254
Ko @ bundle.sunstone.js:254
Sl @ bundle.sunstone.js:254
notify @ bundle.sunstone.js:262
notifyNestedSubs @ bundle.sunstone.js:262
o @ bundle.sunstone.js:262
g @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:220
(anonymous) @ bundle.sunstone.js:213
dispatch @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
dispatch @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
dispatch @ bundle.sunstone.js:213
S.updateCachedData @ bundle.sunstone.js:213
t @ bundle.sunstone.js:220
r.emit @ bundle.sunstone.js:213
emitEvent @ bundle.sunstone.js:286
onevent @ bundle.sunstone.js:286
onpacket @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
ondecoded @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
add @ bundle.sunstone.js:286
ondata @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
onPacket @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
onPacket @ bundle.sunstone.js:286
onData @ bundle.sunstone.js:286
ws.onmessage @ bundle.sunstone.js:286
bundle.sunstone.js:254 Uncaught Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ua (bundle.sunstone.js:254:59605)
    at Object.Aa [as useMemo] (bundle.sunstone.js:254:63665)
    at t.useMemo (bundle.sunstone.js:278:5745)
    at g (bundle.sunstone.js:220:416391)
    at r (bundle.sunstone.js:220:418167)
    at useQuery (bundle.sunstone.js:220:420686)
    at De (7829.bundle.sunstone.js:1:15161)
    at sa (bundle.sunstone.js:254:59054)
    at za (bundle.sunstone.js:254:68572)
    at qs (bundle.sunstone.js:254:112109)
t.unstable_runWithPriority @ bundle.sunstone.js:286
Wo @ bundle.sunstone.js:254
Yo @ bundle.sunstone.js:254
Ko @ bundle.sunstone.js:254
Sl @ bundle.sunstone.js:254
notify @ bundle.sunstone.js:262
notifyNestedSubs @ bundle.sunstone.js:262
o @ bundle.sunstone.js:262
g @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:220
(anonymous) @ bundle.sunstone.js:213
dispatch @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
dispatch @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
(anonymous) @ bundle.sunstone.js:213
dispatch @ bundle.sunstone.js:213
S.updateCachedData @ bundle.sunstone.js:213
t @ bundle.sunstone.js:220
r.emit @ bundle.sunstone.js:213
emitEvent @ bundle.sunstone.js:286
onevent @ bundle.sunstone.js:286
onpacket @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
ondecoded @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
add @ bundle.sunstone.js:286
ondata @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
onPacket @ bundle.sunstone.js:286
r.emit @ bundle.sunstone.js:213
onPacket @ bundle.sunstone.js:286
onData @ bundle.sunstone.js:286
ws.onmessage @ bundle.sunstone.js:286
bundle.sunstone.js:254 Uncaught Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ua (bundle.sunstone.js:254:59605)
    at Object.Aa [as useMemo] (bundle.sunstone.js:254:63665)
    at t.useMemo (bundle.sunstone.js:278:5745)
    at g (bundle.sunstone.js:220:416391)
    at r (bundle.sunstone.js:220:418167)
    at useQuery (bundle.sunstone.js:220:420686)
    at De (7829.bundle.sunstone.js:1:15161)
    at sa (bundle.sunstone.js:254:59054)
    at za (bundle.sunstone.js:254:68572)
    at qs (bundle.sunstone.js:254:112109)`

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
https://github.com/OpenNebula/one/assets/47326048/6adcc4b2-998e-4b02-9c6d-eb2d19c478d0
