### ISSUE TITLE
Refactor VNF Appliance

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6280]
!! TO BE COMPLETED

**Description**
Brief description of the new functionality

**Use case**
How are you going to use this new feature? Why do you need it?

**Interface Changes**
Describe any changes you'd like to see to current interfaces including Sunstone, CLI, or/and API

**Additional Context**
Please feel free to add any other context or screenshots about the feature request here. Or any other alternative you have considered to address this new feature.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
- [ ] Finish DHCP, configuration - parse env var and generate configuration based on that
- [ ] Review redundant code for load-balancers as it is now implemented with Keepaliave
- [ ] Consolidate VNF (OneKE) + VR so we use just one appliance. Needs a minor change in OneGate server code.
- [ ] Review tests (VNF tests) in context and adapt to new code 
- [ ] Review documentation, to update small changes needed to align with new code. (Keepalive LB)
