### ISSUE TITLE
Update SPICE integration to include ctrl+alt+delete button

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6294]
**Description**
There is no easy way to send the ctrl+alt+delete signal through SPICE. 

<img width="1363" alt="image" src="https://github.com/OpenNebula/one/assets/33811723/654b0ec6-8994-48b1-a765-99b866c658d9">

At the moment the only way is to do that is to go to the hypervisor node and issue the command

```
virsh send-key one-<vm_id> KEY_LEFTCTRL KEY_LEFTALT KEY_DELETE
```

**Use case**
This is important when using Windows VMs when triggering the task manager.

**Interface Changes**
A button should be added like VNC does.

<img width="1208" alt="image" src="https://github.com/OpenNebula/one/assets/33811723/1735ca69-9c9e-473f-a1d5-7270d96681ef">

**Additional Context**

The feature is [already supported](https://forum.opennebula.io/t/button-send-ctrlaltdel-for-spice-like-vnc/3525) by SPICE.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
won't fix as we'll deprecate SPICE and RSunstone in 7.0
