### ISSUE TITLE
Extend Group Quotas on Cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6295]
**Description**
On Sunstone, in the cloud view. The user quotas display 6 values

- Running VMs
- CPU
- Memory
- IP Leases
- System Disk
- Datastore

<img width="968" alt="image" src="https://github.com/OpenNebula/one/assets/33811723/5a305622-0bf2-483f-840d-c15e9c12fde2">

The group quotas only display the first 3 of those values. The information should be on par with the user specific information.

<img width="965" alt="image" src="https://github.com/OpenNebula/one/assets/33811723/a699b097-4099-41ce-a740-6900455c847f">

**Use case**
Better user experience

**Additional Context**
Consider FireEdge as well.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
won't fix as RSunstone set to be deprecated in 7.0
