### ISSUE TITLE
onedb fsck may break resources with local characters

### ISSUE THREAD

**Issue by paczerny** [OpenNebula/one#6297]
**Description**
`onedb fsck` for some resources doesn't respect DB encoding and breaks the resource. Then commands `onevm show <id>`, `onevnet show <id>` doesn't work. It may cause crash of Scheduler.

**To Reproduce**
MySQL DB:
* the DB use latin1 charset
* resources contains local characters like `èář`...
* the `onedb fsck` do some update on the resource
* onevm show <id> doesn't work, Scheduler may crash
* Valid only for Virtual Machines, Virtual Networks, Hosts, Virtual Router and History

**Expected behavior**
Respect DB encoding

**Details**
 - Affected Component: MySQL DB
 - Version: 6.4+

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
Well, I could chime in that the migration from SQLite to MySQL  (`onedb migrate ...`) has similar issues...
