### ISSUE TITLE
Improve timers for windows VMs

### ISSUE THREAD

**Issue by brodriguez-opennebula** [OpenNebula/one#6298]
**Description**

Windows VMs performance gets improved when the following libvirt options are added to the domain

```
<clock offset='localtime'>
<timer name='hypervclock' present='yes'/>
<timer name='rtc' tickpolicy='catchup'/>
<timer name='pit' tickpolicy='delay'/>
<timer name='hpet' present='no'/>k
</clock>
```

**Use case**
Add the previous options to template VMs 

**Interface Changes**
(optional) Add fields to set up the values of the options

**Additional Context**
Thanks to Laurent, from the university of Louvain, for identifying this behaviour

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)
- [ ] Sunstone (ruby, fireedge)

**Comment by lgrawet** [comment]
Hello,

Please, also note hypervclock goes along with stimer, vpindex and synic Hyper-V enlightenments for full benefit.
More information in [qemu documentation](https://www.qemu.org/docs/master/system/i386/hyperv.html)

Best regards,

Laurent

**Comment by atodorov-storpool** [comment]
Hello,
I am feeling happy about the possibility of adopting upstream some extra features that our customers benefit from as a side effect of the use of our driver for OpenNebula ;) 
https://github.com/OpenNebula/addon-storpool/blob/master/docs/deploy_tweaks.md#hyperv-clockpy
https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks.d.example/hv-enlightenments.py

**Comment by lgrawet** [comment]
Hello Anton and Storpool people,

I was just looking at your scripts and your very nice optimization work, thank you!
Maybe you should introduce a feature request for another of your scripts : virtio-scsi queues = number of VCPUs. This should also be extended to virtio-block which now also supports multiple queues.

**Comment by rsmontero** [comment]
This has been merged into master for the next release.  The final list of pre-selected HYPERV and TIMERS are (this can be fine tuned in vmm_kvm_exec.conf):

NOTE: This are added when the template includes `FEATURES = [ HYPERV = "yes" ]`
```
HYPERV_OPTIONS = "
    <relaxed state='on'/>
    <vapic state='on'/>
    <spinlocks state='on' retries='8191'/>
    <vpindex state='on'/>
    <runtime state='on'/>
    <synic state='on'/>
    <stimer state='on'/>
    <reset state='off'/>
    <frequencies state='on'/>
    <reenlightenment state='off'/>
    <tlbflush state='on'/>
    <ipi state='on'/>
    <evmcs state='off'/>"

HYPERV_TIMERS = "
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>"
```
