### ISSUE TITLE
Unattended run of install_gems

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#630]
---

Author Name: **Giovanni Toraldo** (Giovanni Toraldo)
Original Redmine Issue: 1815, https://dev.opennebula.org/issues/1815
Original Date: 2013-03-18

---

Would be nice if the install_gems script could be run in a script (without requiring a confirmation from user for installing dependencies and gems).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Arnold Bechtoldt** (Arnold Bechtoldt)
Original Date: 2014-04-19T14:18:05Z

---

+1

Ticket could be related to #2433.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Hector Sanjuan** (Hector Sanjuan)
Original Date: 2015-06-15T14:13:01Z

---

+1 to this or #2433

**Comment by rsmontero** [comment]
Already implemented in current versions
