### ISSUE TITLE
Segmentation fault in oned service when configured to cache mode.

### ISSUE THREAD

**Issue by alonbo2001** [OpenNebula/one#6302]
**Description**
After setting federation mode to be "CACHE" the XML RPC server crash on segmentation fault.

**To Reproduce**
- Configure "CACHE" API server - in /etc/one/oned.conf set federation mode to "CACHE" and set DB and MASTER_ONED.
- sudo systemctl start opennebula
- send "one.zone.raftstatus" request to server.

**Expected behavior**
XML RPC server return valid response to one.zone.raftstatus

**Details**
 - Affected Component: API server (oned)
 - Hypervisor: KVM
 - Version: 6.4.0

**Additional context**
Program crash because bug in request.cc, I created PR that fix it: #6301 

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Fix has been merged d74ace5244e1c35f85be8a273c0e152652b7e7f8

THANKS! :smile:
