### ISSUE TITLE
Add auto setting for virtio-blk and virtio-scsi queues

### ISSUE THREAD

**Issue by lgrawet** [OpenNebula/one#6303]
**Description**
Hello,

As discussed in issue [#6298](https://github.com/OpenNebula/one/issues/6298), Storpool has a very nice optimization for virtio-scsi queues. Their tweak set num-queues=num-vcpus.

Here is what they say about it: "We have observed that optimal performance is achieved when the number of virtio-scsi queues matches the number of vCPUs. "

https://storpool.com/blog/vm-performance-optimization-for-opennebula-with-kvm

https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks.d.example/scsi-queues.py

It would be nice to add an "auto" setting for virtio-scsi queues. Moreover virtio-blk also supports multi-queue so it would be great to have an equivalent setting.

From the release notes of qemu 2.7 :
"virtio-blk now supports multiqueue through a "num-queues" device property."

Thank you,
Best regards,

Laurent

**Use case**
Storage performance improvement for all VMs

**Interface Changes**
* Add a "virtio-blk queues" drop-down list to Sunstone VM template wizard  -> Features -> OS&CPU tab
* Add "Auto" setting to "virtio-blk queues" and "virtio-scsi queues" 

**Additional Context**
The following script from Storpool implements the feature :
https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks.d.example/scsi-queues.py

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)
- [x] Sunstone (Ruby version)
- [x] Sunstone (Fireedge)
- [x] FireEdge Testing

**Comment by rsmontero** [comment]
Implemented for API/OpenNebula core, missing the new attribute (`VIRTIO_BLK_QUEUES`) to be exposed in Sunstone as well as the `auto` option for both attributes.

The implementation allows to set the `VIRTIO_BLK_QUEUES` per disk, overriding any default value in `FEATURES/VIRTIO_BLK_QUEUES`.
