### ISSUE TITLE
Removing an IP_ALIAS (VM.detachnic) removes VM virtual network interface on the hypervisor bridge (OVS)

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#6310]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When an IP_ALIAS is removed from a VM, the corresponding virtual network interface is removed as well. At least this is the behavior when OpenvSwitch driver is in use.

**To Reproduce**
Add an IP_ALIAS to a VM network interface. Remove the IP_ALIAS. Network traffic stops flowing as the virtual interface has been removed from the virtual switch.

**Expected behavior**
I would expect only the IP_ALIAS to be removed inside the virtual machine and that the virtual interface on the hypervisor is not touched at all.

**Details**
 - OpenvSwitch driver
 - Hypervisor: KVM
 - Version: 6.4.2, 6.6.2

**Additional context**

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Preliminary patch, can be appliad to the Ruby file, and tested after doing a onehost forceupdate:
```
--- a/src/vnm_mad/remotes/ovswitch/OpenvSwitch.rb
+++ b/src/vnm_mad/remotes/ovswitch/OpenvSwitch.rb
@@ -147,6 +147,12 @@ class OpenvSwitchVLAN < VNMMAD::VNMDriver
         @bridges = list_bridges

         attach_nic_id = @vm['TEMPLATE/NIC[ATTACH="YES"]/NIC_ID']
+        nic_alias     = false
+
+        if !attach_nic_id
+            attach_nic_id = @vm['TEMPLATE/NIC_ALIAS[ATTACH="YES"]/NIC_ID']
+            nic_alias     = true if attach_nic_id
+        end

         process do |nic|
             if attach_nic_id && attach_nic_id != nic[:nic_id]
@@ -158,6 +164,8 @@ class OpenvSwitchVLAN < VNMMAD::VNMDriver
             # Remove flows
             del_flows

+            next if nic_alias
+
             # delete port from bridge if exists. Some virtualization
             # technologies might clean the port itselves.
             del_bridge_port(@nic[:target])
@@ -445,8 +453,7 @@ class OpenvSwitchVLAN < VNMMAD::VNMDriver

     def del_flow(filter)
         filter.gsub!(/priority=(\d+)/, '')
-        run "#{command(:ovs_ofctl)} del-flows " <<
-            "#{@nic[:bridge]} #{filter}"
+        run "#{command(:ovs_ofctl)} del-flows #{@nic[:bridge]} #{filter}"
     end

     def run(cmd)

```

**Comment by rsmontero** [comment]
Fix and merged in master
