### ISSUE TITLE
Error restoring virtual machine template (rsync datastore)

### ISSUE THREAD

**Issue by dganic** [OpenNebula/one#6317]
**Description**
When we try to restore a virtual machine from a backup (rsync backup datastore), 
we get an error when restoring the VM template:

```
[one.image.restore] Error creating VM template: [one.template.allocate] 
Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 1633891217, columns 1561:1571 
The following images were restored: 155
```

**To Reproduce**

- Add rsync backup datastore
- Create a backup copy of the virtual machine via Sunstone 
- Try to restore the VM

**Expected behavior**
The VM template has been restored

**Details**

```
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```
```
opennebula-tools-6.6.0-1.el8.noarch
opennebula-libs-6.6.0-1.el8.noarch
opennebula-gate-6.6.0-1.el8.noarch
opennebula-node-kvm-6.6.0-1.el8.noarch
opennebula-common-onecfg-6.6.0-1.el8.noarch
opennebula-rubygems-6.6.0-1.el8.x86_64
opennebula-provision-6.6.0-1.el8.noarch
opennebula-fireedge-6.6.0-1.el8.x86_64
opennebula-guacd-6.6.0-1.2.0+1.el8.x86_64
opennebula-sunstone-6.6.0-1.el8.noarch
opennebula-flow-6.6.0-1.el8.noarch
opennebula-common-6.6.0-1.el8.noarch
opennebula-provision-data-6.6.0-1.el8.noarch
opennebula-6.6.0-1.el8.x86_64
```

**Additional context**
vm.xml is generated with an empty line at the end of the file, I don’t know how correct this is and can affect the error:

![image](https://github.com/OpenNebula/one/assets/795809/924b5832-cca4-4e10-9bf5-ac9723180968)

In the template generated in the backup copy (vm.xml), several places without values were found during parsing:

![image](https://github.com/OpenNebula/one/assets/795809/1ba54335-5176-489a-8516-ae6290252337)

![image](https://github.com/OpenNebula/one/assets/795809/2559444e-61fb-4d74-9282-724097da95ed)

The problem is reproducible on two different installations of version OpenNebula 6.6.0

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Aletibazo** [comment]
Failed to reproduce on OpenNebula 6.8 with AlmaLinux 8, closing. If needed, please reopen with detailed instructions on how to reproduce on OpenNebula 6.8.
