### ISSUE TITLE
Oneprovision: Equinix facility no longer exists

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#6318]
**Description**
Equinix provision templates became obsolete due to changes related to facility and metro
https://feedback.equinixmetal.com/changelog/bye-facilities-hello-again-metros

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Details**
 - Affected Component: OneProvision
 - Version: 6.4+

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by xorel** [comment]
master + one.6.6
- https://github.com/OpenNebula/one-ee/pull/2735
- https://github.com/OpenNebula/packages/pull/308
- https://github.com/OpenNebula/development/pull/2327

docs:

- https://github.com/OpenNebula/docs/pull/2694

**Comment by enkelprifti98** [comment]
https://docs.opennebula.io/6.8/provision_clusters/providers/equinix_provider.html

The docs need a small refresh to reference `metro` instead of `facility`.

**Comment by enkelprifti98** [comment]
The available facilities hyperlink should point to this instead:

https://deploy.equinix.com/developers/docs/metal/locations/metros/#metros-quick-reference
