### ISSUE TITLE
Make installation work

### ISSUE THREAD

**Issue by montao** [OpenNebula/one#6336]
After installation, it fails totally:

```
~$ oneuser show
ONE_AUTH file not present
```
I'm not going to guess why.I'm not going to try and read "you can..." I'm not going to google and try to read booze talk that "You can..." I won't work for free to fix your broken installer. I'm deleting your project and will save me time with something that at least can install itself.

**Comment by dann1** [comment]
Try installing the packages instead, I'm sure it's gonna be easier for you. Ask for help on the [forum](https://forum.opennebula.io/), perhaps with a touch of kindness.
