### ISSUE TITLE
Pin VMs from the same service (or role) in the same host 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#634]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 1869, https://dev.opennebula.org/issues/1869
Original Date: 2013-04-08

---

Give the ability to tell AppFlow to deploy VMs from the same service or the same role within a service to be deployed in the same physical host.

**Comment by rsmontero** [comment]
This can now be implmented with VM Groups
