### ISSUE TITLE
[FSunstone] VM speed graphs always incrementing

### ISSUE THREAD

**Issue by danielbolsson** [OpenNebula/one#6347]
**Description**
1. Graphs showing speed are always incrementing
- Disk read and write IOPS
- Network download and upload speed
2. Wrong heading for "Disk write IOPS" graph. It is now: "Disk write bytes"

**To Reproduce**
Deploy VM and check graphs

**Expected behavior**
Graphs should show correct values (up and down slopes).

**Details**
 - Affected Component: FireEdge Sunstone
 - Hypervisor: KVM
 - Version: 6.6.3 enterprise

**Comment by vichansson** [comment]
After a quick analysis it seems like this might be core related and not an issue directly in Fireedge. The values sent to Fireedge from the core seem to be cumulative across timestamps, thus producing these kinds of graphs.

**Comment by danielbolsson** [comment]
> After a quick analysis it seems like this might be core related and not an issue directly in Fireedge. The values sent to Fireedge from the core seem to be cumulative across timestamps, thus producing these kinds of graphs.

The legacy Sunstone shows the same graphs correctly. I would guess that it receives values from the same source?
