### ISSUE TITLE
Hot resize not imported from vCenter wild vm

### ISSUE THREAD

**Issue by dcarracedo** [OpenNebula/one#6350]
**Description**
When import a vm from vCenter with a vm that has be configured with hot resize on vCenter, the vm template that is imported on ONE has not the attribute HOT_RESIZE.

**To Reproduce**
1. Configure a vm on vCenter cheking the CPU Hot Plug and Memory Hot Plug checks.
2. Import that vm on ONE with Sunstone.
3. Check the template of the vm imported.

**Expected behavior**
The VM template needs to have the following attributes:
```
HOT_RESIZE = [
  CPU_HOT_ADD_ENABLED = "YES",
  MEMORY_HOT_ADD_ENABLED = "YES" ]
```

**Details**
 - Affected Component: Sunstone, Templates
 - Hypervisor: vCenter
 - Version: 6.8

**Additional context**
Video with the steps to reproduce the problem:
[Screencast from 16-10-23 16:58:34.webm](https://github.com/OpenNebula/one/assets/134921994/7aa19825-6beb-4c75-a0b4-857eb726cf25)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
wontfix
