### ISSUE TITLE
`custom_attrs` attribute is not applied correctly

### ISSUE THREAD

**Issue by vickmp** [OpenNebula/one#6359]
**Description**
The content of `custom_attrs` applies to the Service body but doesn't apply to the VM attributes themselves.

**To Reproduce**
Try to create a Service with several custom attributes. These attributes will appear in the body of the Service but will not apply to the `vm_template_contents` attribute.

**Expected behavior**
The attributes in `custom_attrs` are applied to `vm_template_contents` per role.

**Details**
 - Affected Component: OneFlow
 - Hypervisor: KVM
 - Version: 6.6

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
[Documentation](https://docs.opennebula.io/6.8/management_and_operations/multivm_service_management/appflow_use_cli.html#using-custom-attributes) needs to be reviewed as well

- inconsistencies
- old sunstone pictures
- discern `custom_attrs` and `custom_attrs_values`
