### ISSUE TITLE
[FSunstone] Implement labeling system

### ISSUE THREAD

**Issue by vichansson** [OpenNebula/one#6362]
**Description**

Fully implement labeling system, currently most resources have the ability to display different labels through the MultiTags component, but there's no direct way for actually applying them through the UI. In order to apply a label currently, you need to add it as a custom attribute on the resource like:
`Labels="Some Label`

**Use case**
Easily apply and edit new labels through the UI.

**Interface Changes**
Add a button similar to that of the `Filter` button that you can use to apply labels to the select resources.

**Additional Context**
All functionality is already present, all we need is a list-like component that can take in one or multiple resources at a time and append a `Labels = <INPUT>` attribute to them...

## Progress Status
- [x] Code committed
- [x] Testing - QA (functionality covered by existing tests)
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
Follow the GMAIL convention 

teSt == TEST
