### ISSUE TITLE
Error when importing the same app in different DS

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#6370]
**Description**
When importing a marketplace app for the second time using another datastore, the core returns the following error:

2023-10-27 13:44:44 - NoMethodError - undefined method `[]' for Error deleting image 11:opennebula::error:
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:272:in `export_vm_template'
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:80:in `export'
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:651:in `block in export_recursive'
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:614:in `each'
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:614:in `export_recursive'
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:294:in `export_service_template'
        /usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:82:in `export'
        /home/jorge/Documents/projects/one-ee/src/sunstone/models/OpenNebulaJSON/MarketPlaceAppJSON.rb:178:in `export'
        /home/jorge/Documents/projects/one-ee/src/sunstone/models/OpenNebulaJSON/MarketPlaceAppJSON.rb:54:in `perform_action'
        /home/jorge/Documents/projects/one-ee/src/sunstone/models/SunstoneServer.rb:228:in `perform_action'
        sunstone-server.rb:1242:in `block in <main>'

**To Reproduce**
1. import a marketplace app to a datastore.
2. re-import the same marketplace app to another datastore.
3. in the case of sunstone the requests data an error 500, since it is the propagation of the OCA error.

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Core]
 - Hypervisor: [e.g. KVM]
 - Version: [6.6, master]

**Additional context**
the error may be related to the following file (https://github.com/OpenNebula/one/blob/master/src/oca/ruby/opennebula/marketplaceapp_ext.rb#L269)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
https://github.com/OpenNebula/docs/commit/0a79bbbd6b822f441f42374bb4d4e778082188f4
https://github.com/OpenNebula/one-ee/commit/9c0877d30de62f95053af52282b6e308c2acd3f2
