### ISSUE TITLE
Error importing a marketapp with the same name

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#6371]
**Description**
When you want to import a markerplace App with an already used name, an error is generated, because the name of the image is already in use

**Interface Changes**
Before sending the request to the server, in the step (Fireedge), a request or pool check must be made to verify that the name is not being used.

**Additional Context**
This check should also be in the FireEdge API.
This will also help to avoid errors of the following issue: https://github.com/OpenNebula/one/issues/6370

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
solved in  #6370
