### ISSUE TITLE
Monitoring overview

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#638]
---

Author Name: **Cyrille Duverne** (Cyrille Duverne)
Original Redmine Issue: 1892, https://dev.opennebula.org/issues/1892
Original Date: 2013-04-11

---

Hello dear ONE team !

I was just wondering, while browsing sunstone, why VM monitoring information are shown only by VM ?
It could be really interesting to have an overview (more graphical and intuitive) of all physical machines and the VMs running on them. (see Ganglia interface etc...)

I know that OpenNebula isn't a monitoring tool, but since it has to manage an infrastructure, it could be useful to have a cartography showing the overview of the machines and basic monitoring (CPU, NET, Storage, RAM etc...)

Do you foresee such a feature ?

Kind regards
Cyrille

**Comment by rsmontero** [comment]
The dashboard addressed this request
