### ISSUE TITLE
MarketPlace Returning "string is not valid UTF-8"

### ISSUE THREAD

**Issue by gbonfiglio** [OpenNebula/one#6390]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
Navigating to the Storage > MarketPlaces tab results in the following error:

```
Unexpected error executing code for particular method, detected by Xmlrpc-c method registry code. Method did not fail; rather, it did not complete at all. 443490-byte supposed UTF-8 string is not valid UTF-8. Unrecognized UTF-8 initial byte value 0x96
```

No apps are displayed.

**Expected behavior**
No error is displayed, MarketPlace can be navigated.

**Details**
 - Affected Component: oned
 - Hypervisor: N/A
 - Version: 6.8.0

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by gbonfiglio** [comment]
Note this already appears in https://github.com/OpenNebula/one/issues/3610 but it seems to be a completely different situation.

**Comment by gbonfiglio** [comment]
The issue seems to have disappeared. Was it server-side?

**Comment by tinova** [comment]
not that we are aware of
