### ISSUE TITLE
Ruby Sunstone - Service Custom Attributes are ignored in Cloud view

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6398]
**Description**
In the Cloud view when instantiating a Service, any Custom Attributes are ignored when the form is submitted.

**To Reproduce**
Create a service template with any custom attribute(s) defined.  Sunstone will show an error "Verify that every custom attribute have its corresponding value defined", and in the Browser Console the payload will have `custom_attrs_values: {}`.  This works fine in the other views.

**Expected behavior**
The Custom Attributes should be submitted with the instantiation form properly.

**Details**
 - Affected Component: Ruby Sunstone ( Cloud view )
 - Version: 6.8 

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
wontfix
