### ISSUE TITLE
VMs with a custom number of virtio queues does not start with a CDROM drive

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6401]
**Description**
Setting the number of virtio queues does not allow a VM with an attached CDROM

**To Reproduce**
Adding any CDROM type image and setting up the VIRTIO block and scsi queues fails with the following error

`[VMM][E]: DEPLOY: error: Failed to create domain from /var/lib/one//datastores/0/400/deployment.4 error: unsupported configuration: queues attribute in disk driver element is only supported by virtio-blk Could not create domain from /var/lib/one//datastores/... ExitCode: 255`

The VM template must have the following sections

```
...
DISK=[                                                                                                          
  IMAGE="cdrom_image",
  IMAGE_UNAME="oneadmin" ]
...
FEATURES=[
  VIRTIO_BLK_QUEUES="auto",
  VIRTIO_SCSI_QUEUES="auto" ]
```

**Expected behavior**
Vm should start with no problems

**Details**
 - Version 6.8

**Additional context**

Looks like the problem is because the ide bus (used for CD ROMS) does not allow setting the queues setting

```
<disk type='file' device='cdrom'>
...
   <target dev='hda' bus='ide'/>
   <driver name='qemu' type='raw' cache='none' discard='unmap' queues='2'/>
</disk>
```

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
[Code](https://github.com/OpenNebula/one-ee/commit/9b9f7196bf4d3f90fe49cf2f1c11772cfe02cf53)
[Docs](https://github.com/OpenNebula/docs/commit/24e8ea60ae79d855e7f60810a67017d07f625860)
