### ISSUE TITLE
Opennebula 6.8 Ubuntu 22.04

### ISSUE THREAD

**Issue by fadjar340** [OpenNebula/one#6404]
**Description**
Before it, I have Ubuntu 20.04 without issue then I upgrade the OS to ubuntu 24.04.
Then Opennebula can not start with segmentation fault.
I use MariaDB version 11.1.3-MariaDB as Opennebula backend

Also the onecfg have problem with git from the ruby
```
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- git (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/bin/onecfg:65:in `<main>'
```
also I have this message:
`[Warning] Aborted connection 2668 to db: 'opennebula' user: 'oneadmin' host: 'localhost' (Got an error reading communication packets)
`

The segfault from dmesg is below:
```
[18054.562981] oned[1070424]: segfault at 563bc0042e18 ip 0000563ea381a99f sp 00007f2753ffea50 error 4 in oned[563ea37b8000+299000]
[18054.563025] Code: cf 00 00 00 4d 8b bd 38 01 00 00 48 8d 6c 24 40 4c 8d 74 24 50 48 8d 35 07 eb 23 00 48 89 ef 4c 8d 64 24 20 49 8b 07 48 89 f2 <48> 8b 58 18 4c 89 74 24 40 e8 93 9a 22 00 4c 8d 64 24 20 48 89 e9

```
Below the result when I rin oned -f
```
root@frontend:/etc/mysql/mariadb.conf.d# oned -f
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Segmentation fault (core dumped)

```
**Expected behavior**
Make my Opennebula run again

**Details**
 - Affected Component: opennebula oned also to all services
 - Hypervisor: KVM
 - Version: 6.8.0-1

**Additional context**
Fortunately , I have mysql backup before upgrade, and I can use onedb restore

Is there any workaround to make it running again?

Regards,
Fadjar

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by fadjar340** [comment]
I can rectified this issue:
1. backup the database using onedb backup
2. Uninstall MariaDB
3. Install Mysql 8.0
4. Create the database from scratch
5. Restore the database using onedb restore <file_backup.sql>
6. Safe all opennebula configuration to other folder, including /etc/one , /var/lib/one/.one
7. Remove all opennebula installation
8. Install the opennebula following documentation
9. Run /usr/share/one/install_gems
10. Copy the backup of /etc/one 
11. Upgrade the db using onedb upgrade
12. Copy the backup of the /var/lib/one/.one/, escpecially all key and auth files
13. run this command: `oneuser passwd --sha256 serveradmin `cat /var/lib/one/.one/sunstone_auth|cut -f2 -d':'``, following this [https://docs.opennebula.io/6.6/intro_release_notes/upgrades/upgrade_58.html](https://docs.opennebula.io/6.6/intro_release_notes/upgrades/upgrade_58.html)
14. Copy the value of the serveradmin to other auth file
15. Restart the opennebula opennebula-sunstone and other service
16. Now my Opennebula working again without any segfault
17. All VM shown at the oned.log
18. Sunstone working as expected :) 
19. Upgrade all kvm with opennebula 6.8 version

I think this bug can be close...

Regards,
Fadjar

**Comment by rsmontero** [comment]
THANKS for the update! closing :)
