### ISSUE TITLE
Change of groups by the user

### ISSUE THREAD

**Issue by dcarracedo** [OpenNebula/one#6405]
**Description**
Add functionality to let an user change his group or select all groups.

**Use case**
An user that belongs to more than one group could change his primary group. When an user select a group:
- The primary group of the user has to be changed.
- The user can only see resources of the group selected.

Also, the user could select the All option to see all the resources of all the groups that the user belongs.

**Interface Changes**
FireEdge Sunstone will have a menu (as the views menu) to select beetween All option and the groups that the user belongs. If a groups it's selected:
- Make a request to change primary group of the user.
- Filter every resources GET request with filter=-4 to get only the resources of the primary group.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
developed in #6122
