### ISSUE TITLE
Datastore "system" shows wrong capacity

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6409]
## 1. Description

OpenNebula does not show the right capacity for datastore `0` (system). This was working for me, until I upgraded to `6.8.0`. Thinking that was a problem due to the upgrade, I built new cluster from scratch, this time using `6.8.0` directly, and got same issue. On `6.6.3` it works.

## 2. To Reproduce

Deploy OpenNebula `6.8.0` or upgrade from previous release `6.6.3`. Configure the cluster to use Gluster (tested on `gluster-10.4` and Distributed volume).

Demonstrating that opennebula default datastore path are symlinked to gluster volume:

```bash
ls -l /var/lib/one/datastores/
total 4
lrwxrwxrwx 1 root     root       43 Nov 23 21:14 0 -> /var/lib/datastores/gluster_mount/0
lrwxrwxrwx 1 root     root       43 Nov 23 21:14 1 -> /var/lib/datastores/gluster_mount/1
```

Another proof:

```bash
df -hT /var/lib/one/datastores/{0,1}
Filesystem                        Type            Size  Used Avail Use% Mounted on
DEV-node1-stor:/vol1.tcp fuse.glusterfs  205G  3.7G  202G   2% /var/lib/datastores/gluster_mount
DEV-node1-stor:/vol1.tcp fuse.glusterfs  205G  3.7G  202G   2% /var/lib/datastores/gluster_mount
```

A VM was created to check where exactly OpenNebula was creating it:

```bash
onevm list
  ID USER     GROUP    NAME                                                                                         STAT  CPU     MEM HOST                                                                 TIME
   0 oneadmin oneadmin test                                                                                         runn    1    128M DEV-node1-kvm                                           0d 00h06
```

The image file and the VMs files were created under gluster volume:

```bash
tree -a /var/lib/datastores/gluster_mount/{0,1}
/var/lib/datastores/gluster_mount/0
├── .monitor
└── 0
    ├── deployment.0
    ├── disk.0 -> disk.0.snap/0
    ├── disk.0.snap
    │   ├── 0
    │   └── disk.0.snap -> .
    ├── disk.1
    ├── ds.xml
    └── vm.xml

/var/lib/datastores/gluster_mount/1
├── .monitor
└── 86036760ffb31d6249d2a75d8783e37e
```

TM `shared` on both, ds `0` and ds `1`:

```bash
cat /var/lib/one/datastores/{0,1}/.monitor
ssh
ssh

cat /var/lib/hypercx/datastores/gluster_mount/{0,1}/.monitor
ssh
ssh

ls -l /var/lib/one/datastores/{0,1}/.monitor
-rwxr-xr-x 1 oneadmin oneadmin 4 Nov 23 17:19 /var/lib/one/datastores/0/.monitor
-rwxr-xr-x 1 oneadmin oneadmin 4 Nov 23 16:14 /var/lib/one/datastores/1/.monitor
```

Datastore `0` info:

```bash
onedatastore show 0
DATASTORE 0 INFORMATION
ID             : 0
NAME           : system
USER           : oneadmin
GROUP          : oneadmin
CLUSTERS       : 0,100
TYPE           : SYSTEM
DS_MAD         : -
TM_MAD         : shared
BASE PATH      : /var/lib/one//datastores/0
DISK_TYPE      : FILE
STATE          : READY

DATASTORE CAPACITY
TOTAL:         : 97.9G
FREE:          : 55.6G
USED:          : 37.3G
LIMIT:         : -

PERMISSIONS
OWNER          : um-
GROUP          : u--
OTHER          : ---

DATASTORE TEMPLATE
ALLOW_ORPHANS="FORMAT"
DISK_TYPE="FILE"
DS_MIGRATE="YES"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
SHARED="YES"
TM_MAD="shared"
TYPE="SYSTEM_DS"

IMAGES
```

Datastore `1` info:

```bash
onedatastore show 1
DATASTORE 1 INFORMATION
ID             : 1
NAME           : images
USER           : oneadmin
GROUP          : oneadmin
CLUSTERS       : 0,100
TYPE           : IMAGE
DS_MAD         : fs
TM_MAD         : shared
BASE PATH      : /var/lib/one//datastores/1
DISK_TYPE      : FILE
STATE          : READY

DATASTORE CAPACITY
TOTAL:         : 204.9G
FREE:          : 201.2G
USED:          : 3.6G
LIMIT:         : -

PERMISSIONS
OWNER          : um-
GROUP          : u--
OTHER          : ---

DATASTORE TEMPLATE
ALLOW_ORPHANS="FORMAT"
CLONE_TARGET="SYSTEM"
CLONE_TARGET_SSH="SYSTEM"
DISK_TYPE="FILE"
DISK_TYPE_SSH="FILE"
DS_MAD="fs"
LN_TARGET="NONE"
LN_TARGET_SSH="SYSTEM"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
TM_MAD="shared"
TM_MAD_SYSTEM="ssh"
TYPE="IMAGE_DS"

IMAGES
0
```

I think this is the command that is being used to get the TOTAL_MB space:

```bash
df -B1M -P /var/lib/one/datastores/0 2>/dev/null | tail -n 1 | awk '{print $2}'
209802

df -B1M -P /var/lib/one/datastores/1 2>/dev/null | tail -n 1 | awk '{print $2}'
209802
```

Its working for both, but even after all this, OpenNebula keep showing the wrong capacity thorugh the CLI and thorugh Sunstone, for the system datastore:

```bash
onedatastore list
  ID NAME                                                                                                                                                    SIZE AVA CLUSTERS IMAGES TYPE DS      TM      STAT
   1 images                                                                                                                                                204.9G 98% 0,100         0 img  fs      shared  on
   0 system                                                                                                                                                 97.9G 57% 0,100         0 sys  -       shared  on
```

No error on database:

```bash
cat /var/log/one/onedb-fsck.log
Total errors found: 0
Total errors repaired: 0
Total errors unrepaired: 0
```

No errors on the `monitor.log`:

```bash
cat /var/log/one/monitor.log
Thu Nov 23 17:51:48 2023 [Z0][MON][I]: Init Monitor Log system
Thu Nov 23 17:51:48 2023 [Z0][MON][I]: Starting Monitor Daemon
----------------------------------------
       Monitor Configuration File
----------------------------------------
DATASTORE_LOCATION=/var/lib/one//datastores
DB=CONNECTIONS=15
HOST_MONITORING_EXPIRATION_TIME=43200
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 kvm,EXECUTABLE=one_im_ssh,NAME=kvm,SUNSTONE_NAME=KVM,THREADS=0
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 qemu,EXECUTABLE=one_im_ssh,NAME=qemu,SUNSTONE_NAME=QEMU,THREADS=0
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 lxd,EXECUTABLE=one_im_ssh,NAME=lxd,SUNSTONE_NAME=LXD,THREADS=0
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 lxc,EXECUTABLE=one_im_ssh,NAME=lxc,SUNSTONE_NAME=LXC,THREADS=0
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 firecracker,EXECUTABLE=one_im_ssh,NAME=firecracker,SUNSTONE_NAME=Firecracker,THREADS=0
IM_MAD=ARGUMENTS=-c -t 15 -r 0 vcenter,EXECUTABLE=one_im_sh,NAME=vcenter,SUNSTONE_NAME=VMWare vCenter
LOG=DEBUG_LEVEL=3,SYSTEM=FILE
MANAGER_TIMER=15
MONITORING_INTERVAL_HOST=180
NETWORK=ADDRESS=0.0.0.0,MONITOR_ADDRESS=192.168.10.70,PORT=4124,PRIKEY=,PUBKEY=,THREADS=8
PROBES_PERIOD=BEACON_HOST=30,MONITOR_HOST=120,MONITOR_VM=30,STATE_VM=5,SYNC_STATE_VM=180,SYSTEM_HOST=600
VM_MONITORING_EXPIRATION_TIME=43200
----------------------------------------
Thu Nov 23 17:51:48 2023 [Z0][ONE][I]: Set up 15 DB connections using encoding utf8mb4
Thu Nov 23 17:51:48 2023 [Z0][ONE][I]: Using 5.5.5-10.6.12-mariadb-0ubuntu0.22.04.1 (100612) with:
Thu Nov 23 17:51:48 2023 [Z0][ONE][I]:  FTS enabled
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading drivers.
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading driver: kvm
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]:  Driver loaded: kvm
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading driver: qemu
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]:  Driver loaded: qemu
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading driver: lxd
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]:  Driver loaded: lxd
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading driver: lxc
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]:  Driver loaded: lxc
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading driver: firecracker
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]:  Driver loaded: firecracker
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]: Loading driver: vcenter
Thu Nov 23 17:51:48 2023 [Z0][DrM][I]:  Driver loaded: vcenter
Thu Nov 23 17:51:53 2023 [Z0][HMM][I]: Raft status: SOLO
Thu Nov 23 17:52:08 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:52:22 2023 [Z0][HMM][I]: Successfully monitored host: 0
Thu Nov 23 17:52:39 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:53:09 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:53:40 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:54:10 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:54:22 2023 [Z0][HMM][I]: Successfully monitored host: 0
Thu Nov 23 17:54:41 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:55:11 2023 [Z0][HMM][I]: Successfully monitored VM: 0
Thu Nov 23 17:55:42 2023 [Z0][HMM][I]: Successfully monitored VM: 0
```

The monitoring of the datastores is OK:

```bash
cat /var/log/one/oned.log | egrep "datastore system| datastore images|Datastore system|Datastore images"

# [...]
Thu Nov 23 19:16:40 2023 [Z0][InM][D]: Monitoring datastore system (0)
Thu Nov 23 19:16:40 2023 [Z0][InM][D]: Monitoring datastore images (1)
Thu Nov 23 19:16:41 2023 [Z0][ImM][D]: Datastore system (0) successfully monitored.
Thu Nov 23 19:16:41 2023 [Z0][ImM][D]: Datastore images (1) successfully monitored.
```

This is the gluster volume info:

```bash
gluster volume info vol1

Volume Name: vol1
Type: Distribute
Volume ID: 620b90d5-7d7b-47b2-b0bb-924f0f33bb0e
Status: Started
Snapshot Count: 0
Number of Bricks: 3
Transport-type: tcp
Bricks:
Brick1: DEV-node1-stor:/data/glusterfs/vol1/brick0/data
Brick2: DEV-node1-stor:/data/glusterfs/vol1/brick1/data
Brick3: DEV-node1-stor:/data/glusterfs/vol1/brick2/data
Options Reconfigured:
features.quota-deem-statfs: on
features.inode-quota: on
features.quota: on
user.cifs: off
performance.read-ahead: off
performance.quick-read: off
performance.io-cache: off
cluster.eager-lock: enable
network.remote-dio: enable
features.shard-block-size: 64MB
server.allow-insecure: on
features.shard: enable
storage.owner-gid: 9869
storage.owner-uid: 9869
storage.fips-mode-rchecksum: on
transport.address-family: inet
nfs.disable: on
```
 
## 3. Expected behavior

OpenNebula showing the same capacity for system datastore as images datastore capacity, due to the storage backend configuration. Datastores `0` and `1` are using the same storage backend and the same capacity should be shown for both. I have this working on previous releases.

## 4. Details
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [6.8.0]

**Additional context**

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by nachowork90** [comment]
I have the same situation, even trying to change TM_MAD I got no different results.

But the TM code hasn't changed in 8 months!

So, must be elsewhere

**Comment by Franco-Sparrow** [comment]
Hi, may we have a follow up on this? Thanks in advance.

**Comment by Franco-Sparrow** [comment]
Sorry I havent said before. I want to give my deep gratitud to OpenNebula team, for the effort of maintain this wonderful cloud solution and improve with every new release. This new version `6.8.0` introduced the jobs for backups, which seems to be very interesting and more friendly to the user, showing the status of the backup and a qeue for it.

Just wanted to add this, as we allways push for your quick response without think first that you guys has a lot in hands and the development of this solution is not as simple as open an issue. From my side and the friends that work with me, using this cloud solution, if it helps to OpenNebula team, we will keep opening issues as long as they be validated and demostrated first.

Thanks and appologize if we push allways for a quick solution from your side :)

**Comment by Franco-Sparrow** [comment]
Hello team

We still have this bug after repeated a deployment to confirm this.

**Comment by paczerny** [comment]
I found the bug for qcow2/shared datastore, the datastore ID is not considered in the ``monitor`` [script](https://github.com/OpenNebula/one/blob/master/src/tm_mad/qcow2/monitor#L53). The $2 is empty, should be $DS_ID

Fix should be easy, I'll try to push it to 6.8.1

**Comment by oscaromar1** [comment]
Hi Pavel,

I have made the changes you mention but it still does not work, I made it for qcow and shared, I also made the change in the TMP, and the same result, I share evidence with you:

![image](https://github.com/OpenNebula/one/assets/53238820/62ee8cfe-a781-4fa4-a124-2c80465b17b1)

I restarted ON and Sunstone services, same result, additional DS take the size of DS ID 0.

![image](https://github.com/OpenNebula/one/assets/53238820/89810f82-bef5-4aa1-9c86-08eff6ecb027)

**Comment by atodorov-storpool** [comment]
@oscaromar1 
You should change line 53 (the script is called with one argument; the rest is provided via stdin)
```BASE_PATH="${XPATH_ELEMENTS[i++]}/$DS_ID"```

**Comment by Githopp192** [comment]
btw ... 

for myself i'm using "shellcheck" for qualifying my bash-scripts .. may be this could be a help for OpenNebula Team, too to get to a more stable code ?

https://github.com/koalaman/shellcheck

shellcheck notes ==>

/var/lib/one/remotes/tm/qcow2/monitor|31 col 3| note: Not following: ./sh/scripts_common.sh was not specified as input (see shellcheck -x). [SC1091]
/var/lib/one/remotes/tm/qcow2/monitor|31 col 3| note: Double quote to prevent globbing and word splitting. [SC2086]
/var/lib/one/remotes/tm/qcow2/monitor|33 col 23| note: Double quote to prevent globbing and word splitting. [SC2086]
/var/lib/one/remotes/tm/qcow2/monitor|34 col 8| note: Not following: ./../../datastore/libfs.sh was not specified as input (see shellcheck -x). [SC1091]
/var/lib/one/remotes/tm/qcow2/monitor|34 col 8| note: Double quote to prevent globbing and word splitting. [SC2086]
/var/lib/one/remotes/tm/qcow2/monitor|38 col 12| note: Use $(...) notation instead of legacy backticked `...`. [SC2006]
/var/lib/one/remotes/tm/qcow2/monitor|125 col 10| note: Use $(...) notation instead of legacy backticked `...`. [SC2006]
/var/lib/one/remotes/tm/qcow2/monitor|129 col 10| note: Double quote to prevent globbing and word splitting. [SC2086]
/var/lib/one/remotes/tm/qcow2/monitor|137 col 10| note: Double quote to prevent globbing and word splitting. [SC2086]
/var/lib/one/remotes/tm/qcow2/monitor|143 col 6| note: Double quote to prevent globbing and word splitting. [SC2086]
/var/lib/one/remotes/tm/qcow2/monitor|145 col 6| note: Double quote to prevent globbing and word splitting. [SC2086]
