### ISSUE TITLE
Add support for incremental backups in Ceph

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6411]
**Description**
This feature is to implement incremental backups in Ceph. The overall process would be:

* Create a snapshot to mark the start of the increment
*  Use rbd diff to get the blocks changed since the snapshot was created
* Read blocks and write them to a qcow2 file
* Store the qcow2 increment files in the backup server

**Interface Changes**
None

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment]
Hi @rsmontero 

I think that a better approach for Ceph Incremental Backups could be achieved using known projects like Backy2. Store the increments in `qcow2` files will require to convert from `raw` to `qcow2`, so a backup uising Ceph will take more time. An rsync host could be prepared with backy2 and sharing its storage with the opennebula cloud. Backy2 driver should be prepared to create, delete, ls and some other actions required for a backup.

This is just my humble opinion, which is aligned with @nachowork90 proposal.

**Comment by rsmontero** [comment]
Hi @Franco-Sparrow 

Agree, in fact the final implementation in 6.10.1 **does not** stores deltas in qcow2 format but in native rbd diff format. Don't know the internals of other tools but directly implementing this incremental backups on top of the OpenNebula backup framework is aimed to provide the best experience for our user base.

Thanks for your comments
