### ISSUE TITLE
[FSunstone] Enhance placement tab

### ISSUE THREAD

**Issue by vichansson** [OpenNebula/one#6419]
**Description**

Enhance the placement tab in FSunstone to look more like the one in RSunstone. Currently in FSunstone there's only an expression text box, compared to in RSunstone where you get a pool view of both hosts & datastores.

Also, there is a section in the NIC form that needs the same behavior.

**Use case**

Make the placement tab more intuitive and user friendly.

**Interface Changes**

Add a pool view similar to the one in RSunstone (in placement section of vm templates and in Network auto section of NIC form in vm templates).

**Additional Context**

Placement section on vm templates:

![image](https://github.com/OpenNebula/one/assets/134925555/dd853a6e-62f6-40a5-8302-8a227f6c2676)
_RSunstone placement tab_

![image](https://github.com/OpenNebula/one/assets/134925555/0a1875f9-8b04-4dad-9344-16a92849d913)
_FSunstone placement tab_

Network auto on NIC form (check Automatic select virtual network previously):

![Screenshot from 2024-05-07 15-49-18](https://github.com/OpenNebula/one/assets/134921994/d550882f-c1b9-4a78-b6db-48c4f0bc39b5)
_RSunstone NIC tab_

![Screenshot from 2024-05-07 15-48-34](https://github.com/OpenNebula/one/assets/134921994/f6342afc-023a-442c-8521-2cc3cbceb89b)
_FSunstone NIC tab_

## Progress Status
- [x] Code committed
- [x] Testing - QA
    - Tested by templateAdvanced
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
Also apply smart filters on datastore selection like in #6447
