### ISSUE TITLE
Possible handle leak

### ISSUE THREAD

**Issue by Bbulatov** [OpenNebula/one#6424]
Good day!
I noticed that in the file src/svncterm_server/svncterm_server.c, in the add_cmd() function on line 1984, a socket is created and until the end of the entire function it can remain open, and is closed only by individual conditional blocks. Do we actually need to close it before returning 0? Will this be considered a leak?

**Comment by paczerny** [comment]
The socket descriptor ``sd`` is stored as an index to the ``client_fds`` at the end of the method.
The socket is closed by ``del_cmd``, line 1947

Notice in other parts of the code:
```
        for (int i = 0; i < MAX_CLIENT_FD; ++i)
        {
            if ( client_fds[i] != NULL )
```
* if the client_fds[i] == NULL the socket `i` is closed
* if the client_fds[i] != NULL the socket `i` is opened

This is a very unusual construction, I suppose some static analysis tools may report leak of the socket handle.
