### ISSUE TITLE
[FSunstone] Image upload not working

### ISSUE THREAD

**Issue by vichansson** [OpenNebula/one#6426]
**Description**
Uploading an image from the browser machine fails.

**To Reproduce**
- Click create image
- Select image from your computer
- Next + Next + Create

![image](https://github.com/OpenNebula/one/assets/16429804/79341b71-97be-41c0-b460-8b17cce1cfb5)
![image](https://github.com/OpenNebula/one/assets/16429804/aa78c688-b7fa-416e-baf6-ecf9d85e4ff9)
![image](https://github.com/OpenNebula/one/assets/16429804/9449cd66-e723-4286-bfc1-fd5dd634f55a)
![image](https://github.com/OpenNebula/one/assets/16429804/934f9e09-d350-4a09-b1eb-deb4083c1f01)
![image](https://github.com/OpenNebula/one/assets/16429804/d1d11c9d-67ad-4fe9-b1ca-fceb31de0516)

After the image is uploaded, it goes into the `Error` state. With the follow reported error:
```
Error copying image in the datastore: ERROR: cp: Not allowed to copy images from /var/lib/one/ /etc/one/ /home/oneadmin/ / Not allowed to copy image from /tmp/aad502e89a40ecd9e9f88ae34b4c539e, check RESTRICTED_DIRS in your datastore
```

**Expected behavior**

Image should be uploaded normally. 

![image](https://github.com/OpenNebula/one/assets/16429804/0a440d49-dcad-4f56-a11b-87e3344c372c)

**Additional context**

Issue seems to only be affecting FSunstone. A workaround to this issue is setting the `SAFE_DIRS` attribute for the datastore in question to `/tmp` from `/var/tmp`. 

Potentially works with smaller images (<17MB), but fails with larger images, around ~100MB.

Appears to be version independent.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
repeated in this issue: https://github.com/OpenNebula/one/issues/6423
