### ISSUE TITLE
Adjust CPU ratio on running instances

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#643]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 2002, https://dev.opennebula.org/issues/2002
Original Date: 2013-05-07

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Laurent Grawet** (Laurent Grawet)
Original Date: 2013-05-07T09:45:00Z

---

Hi,

Sorry, I've hit the return key too quickly... 
There should be a way to adjust CPU ratio on running instances to manage CPU overcommitment.

Best regards,

Laurent

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2013-05-07T11:04:34Z

---

You can do it in 4.0 if the instance is not running (poweroff, undeployed, pending...) Is this for VMs in RUNNING state or is this:

http://opennebula.org/documentation:rel4.0:vm_guide_2#resizing_a_vm

enough?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Laurent Grawet** (Laurent Grawet)
Original Date: 2013-05-07T11:42:16Z

---

I would like to to adjust the CPU parameter (not VCPU) for VMs in running state. According the new documentation, the VM can't be active.

As the CPU parameter is just for accounting purpose, it could be changed while the VM is running. This is the kind of parameter we would like to adjust while observing real CPU usage on the VM.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Laurent Grawet** (Laurent Grawet)
Original Date: 2014-03-13T17:58:25Z

---

Hi,

Is it possible to add this feature to 4.6 roadmap ?

Thanks,

Laurent

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-03-17T10:57:42Z

---

Beta is going to be released today, there are still some glitches with sunstone. The core changes are more or less straightforward (quotas need to be checked), but we need to propagate the feature upwards. These changes cannot be made for 4.6 Final. Very sorry for the inconvenience. Moved to high priority.

**Comment by rsmontero** [comment]
This should be implemented in current versions
