### ISSUE TITLE
Creating image on CLI with URL source can throw timeout

### ISSUE THREAD

**Issue by onenhansen** [OpenNebula/one#6431]
**Description**
When creating a URL-sourced image, `Net::ReadTimeout with #<TCPSocket:(closed)>` may be displayed, but the image will still be created correctly. 

**To Reproduce**
Using curl > 7.17.0
```
oneimage create --name cdrom-testing2398uf --type cdrom --path http://tinycorelinux.net/8.x/x86/release/Core-current.iso -d 100 
Net::ReadTimeout with #<TCPSocket:(closed)>
```

**Expected behavior**
Should output the ID of the created image

**Details**
 - Affected Component: Storage
 - Hypervisor: vCenter, KVM
 - Version: 6.8.1 ( Running curl > 7.71.0 )

## Progress Status
- [x] Code committed
- [ ] ~~Testing - QA~~
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
I don't think this issue depends on the curl version. The default timeout for all CLI actions is 30 seconds. If you are downloading big image, this can be exceeded.

You can increase the timeout by setting [ONE_XMLRPC_TIMEOUT](https://docs.opennebula.io/6.8/management_and_operations/references/cli.html?highlight=one_xmlrpc_timeout#shell-environment) environment variable

In case of timeout, we may add a warning message, that the download continues in background, similar to [showback calculation](https://github.com/OpenNebula/one/blob/master/src/cli/oneshowback#L193)

**Comment by Franco-Sparrow** [comment]
@onenhansen Hi Sir, thanks for your solution...but this will also sacrifice the possibility of retries for downloads. Is there any other solution in the feature that include `--retry-all-errors` option and avoid this message error on Sunstone when downloading an image?

**Comment by onenhansen** [comment]
@Franco-Sparrow It does not remove all the retries, but forces it to retry even on failures where it should not be retrying.

In the `downloader.sh` script we pipe the `curl` output to `head -c ${MAX_SIZE}` and we set MAX_SIZE to 64KB to check the file type and size that we are about to download(a form of `stat`).  

When curl is piped to a command which stops accepting input it returns the code `curl: (23) Failure writing output to destination` which normally would just fail.  That would be correct, as we only want the first 64KB and don't need the whole file. However, with `--retry-all-errors` this will retry the command up to the maximum retries(3) delaying 3 seconds each time.  

So, in certain cases, this added up with all the other stuff running to create the image will take up to and over 30 seconds which triggers the timeout on the CLI.  This caused failures where there should not have been any.

If you do see failures please send us any errors you encounter so we can improve this further if necessary!

If the image you're trying to download is on a server which has many transient errors, then you may want to consider an alternate form of downloading the image and then FTP/SCP upload the image to the frontend in order to add the image via a local path rather than downloading via a URL.

**Comment by Franco-Sparrow** [comment]
Thanks @onenhansen, I will keep you updated about this modification. The cluster is on LA with a good DC and internet provider, with no problem to access the internet. In this case, removing these lines should not affect the download of the image via URL.

**Comment by Franco-Sparrow** [comment]
Hi @onenhansen 

This means that if `verlte "7.71.0" >= "$CURL_VER"` then `RETRY_ARGS+=" --retry-all-errors"`...right?
```bash
    if verlte "7.71.0" "$CURL_VER"; then
        RETRY_ARGS+=" --retry-all-errors"
    fi
```

In my case I am using Ubuntu 22.04, then curl version is `7.81.0`:

![imagen](https://github.com/OpenNebula/one/assets/56793015/a5096ae8-1da5-4517-87c8-62ed02748d5e)

So, I am not using `RETRY_ARGS+=" --retry-all-errors"`, instead of that I am onnly using `RETRY_ARGS="--retry 3 --retry-delay 3"`

```bash
# Returns curl retry options based on its version
function curl_retry_args {
    [ "$NO_RETRY" = "yes" ] && return

    RETRY_ARGS="--retry 3 --retry-delay 3"

    CURL_VER=`curl --version | grep -o 'curl [0-9\.]*' | awk '{print $2}'`

    # To retry also on conn-reset-by-peer fresh curl is needed
    if verlte "7.71.0" "$CURL_VER"; then
        RETRY_ARGS+=" --retry-all-errors"
    fi

    echo $RETRY_ARGS
}
```

**Comment by Franco-Sparrow** [comment]
The problem is related with the use of the option `--retry-all-errors`.If the command does not use this option, the image will be created and no error will be prompted in the sunstone. I tested this with:

- lines commented and it works (what @onenhansen proposed before).
- original lines uncommented but changing `7.71.0` to `7.81.0` and same error.

**Comment by onenhansen** [comment]
@Franco-Sparrow Just for clarity, the line `if verlte "7.71.0" "$CURL_VER"; then` checks if the first version is lower than or equal the second version, so this would be read as `if "7.71.0" <= "$CURL_VER"; then`.  This feature showed up in version 7.71.0 of curl.

**Comment by Franco-Sparrow** [comment]
Good day @onenhansen 

Thank for the clarity of the bash logic. As you can see on my previous comment, I tested all three possibilities on ubuntu 22.04 with curl `7.81.0` >= `7.71.0`, then `RETRY_ARGS=--retry 3 --retry-delay 3 --retry-all-errors` and the creation of the image fail. Removing this lines fixed the problem. i think that we should not be using this option for curl `7.81.0` or just remove those lines as you suggested.
