### ISSUE TITLE
Possible segmentation fault

### ISSUE THREAD

**Issue by Bbulatov** [OpenNebula/one#6432]
Good day!
A possible segmentation error was detected during the analysis. In the file src/lcm/LifeCycleStates.cc in the function LifeCycleManager::trigger_disk_resize_failure(int vid) on line 2406 * disk is initialized. Is it necessary to additionally check this value for dereference, since in other cases there is a check for nullptr? Could this lead to a segmentation fault?

**Comment by paczerny** [comment]
Added the safety check of the pointer and also output to VM log, so user can detect that the VM is in inconsistent state. Although I think this situation should never happen.
