### ISSUE TITLE
Allow to set CPU_MODEL[FEATURES] on host and cluster level

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#6437]
**Description**
Actually, CPU Features can be set only in VM template. Would be fine to allow to set it on host and cluster level.

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
All merge, thanks for the contribution :heart:
