### ISSUE TITLE
make sunstone animations configurable

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#644]
---

Author Name: **Rolandas Naujikas** (Rolandas Naujikas)
Original Redmine Issue: 2018, https://dev.opennebula.org/issues/2018
Original Date: 2013-05-10

---

Many dialog windows reveals with default animation (fadeAndPop).
Please make some way to configure it as user settings, with system default also.

As a workaround this patch works (after sunstone server restart):
```
diff --git a/src/sunstone/public/vendor/4.0/foundation/jquery.foundation.reveal.js b/src/sunstone/public/vendor/4.0/foundation/jquery.foundation
index 4972931..ae63a52 100644
--- a/src/sunstone/public/vendor/4.0/foundation/jquery.foundation.reveal.js
+++ b/src/sunstone/public/vendor/4.0/foundation/jquery.foundation.reveal.js
@@ -54,7 +54,7 @@
            * @type {String}
            * @default fadeAndPop
            */
-          animation: 'fadeAndPop',
+          animation: 'none',
           /**
            * Speed at which the reveal should show. How fast animtions are.
            *

```

**Comment by rsmontero** [comment]
We'll address some branding as part of #1510
