### ISSUE TITLE
Ceph datastore stops working, when CEPH_CONF parameter pointing to other name or location distinct from /etc/ceph/ceph.conf

### ISSUE THREAD

**Issue by roamingengineer311** [OpenNebula/one#6440]
**Description**
When I need to add ceph datastore to Opennebula with another location or name of ceph.conf file Datastore is not working.

``
Wed Dec 20 13:11:52 2023 [Z0][ImM][E]: Error cloning from Image 9: ERROR: clone: Command "rbd --conf /etc/c
epheq/ceph.conf --id libvirt copy equinix/one-9 equinix/one-16" failed: global_init: unable to open config
file from search list /etc/cepheq/ceph.conf Error cloning equinix/one-9 to equinix/one-16 in kvm38
``

While at the same time command that ended with error under oneadmin user executed correctly from shell

``
oneadmin@one:/home/admin$ rbd --conf /etc/cepheq/ceph.conf --id libvirt copy equinix/one-9 equinix/one-15
Image copy: 44% complete...^C
``

**To Reproduce**
Copy folder /etc/ceph/ to another location for example /etc/ceph1/ and update datastore CEPH_CONF to /etc/ceph1/ceph.conf or
rename ceph.conf in /etc/ceph/ to /etc/ceph/ceph1.conf and try to clone, create or upload any image on target datastore.

**Expected behavior**
Datastore working as expected and supports changing CEPH_CONF argument

**Details**
 - Affected Component: Drivers - Storage
 - Hypervisor: KVM
 - Version: 6.8

**Additional context**
In Opennebula 6.4 I dont have problem like this, has two ceph clusters and two separate datastores one of them has CEPH_CONF argument that is distinct from /etc/ceph/ceph.conf

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by mkutouski** [comment]
The issued confirmed. Documentation with required set of steps to configure custom location for ceph.conf file properly was updated.
