### ISSUE TITLE
Virtual Router add support to allocate only floating IPs

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6441]
**Description**
VR can use multiple VMs to implement redundancy. The VR allocated a floating IP (configured in the active instance) to address the router as well as an additional IP in the same network to run VRRP.

This requirement leads to a waste of public IPs, as VRRP can run on private networks attached to the router.

This feature is to implement a FLOATING_ONLY attribute to instruct OpenNebula to not allocate additional IPs in the NIC. Keepalived will only configure the FLOATING_IP to the active instance. Also:

* A random MAC address will be generated for the NIC and not an actual lease from the Virtual Network.
* IP attribute will not be set for the NIC (only FLOATING_IP)

**Use case**
Not waste public IPs for Virtual Routers

**Interface Changes**
New NIC parameter FLOATING_ONLY for Virtual Routers(valid if FLOATING_IP is set). The VR appliance will be updated accordingly

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)
- [x] FireEdge Sunstone

**Comment by tinova** [comment]
Implemeting FSunstone part in https://github.com/OpenNebula/one/issues/5899
