### ISSUE TITLE
Automatic testing OpenNebula Federation on FireEdge Sunstone

### ISSUE THREAD

**Issue by dcarracedo** [OpenNebula/one#6442]
**Description**
Create automatic tests with Cypress to test an installation of OpenNebula with federation.

**Use case**
When OpenNebula is federated.

**Interface Changes**
N/A

**Additional Context**
To achieve this issue we have to decide which option will be better:

- Create a new microenv to test FireEdge Suntone in a federation
- Extend an existing microenv (kvm-fed), install Cypress and run tests here

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
Is resolved in this issue https://github.com/OpenNebula/one/issues/6120
