### ISSUE TITLE
Cant change backupjob execution mode from `SEQUENTIAL` to `PARALLEL` on rsync backups

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6464]
## Description

Hi team and @rsmontero.

I testing the new backupjob feature (using rsync driver) and I like this new way to schedule backups, as longs as it allow multiple backups at the same time, following the global configuration in the `/etc/one/sched.conf`. The problem is that Sunstone does not give you the option to create a new job with execution mode `PARALLEL` (Backups are executed in parallel subject to the available slots). Tried to modify the execution mode attribute, but it always return to `SEQUENTIAL` mode. I did this from Sunstone and from CLI, once created the backupjob from Sunstone, it creates the job with execution mode `SEQUENTIAL` by default and cant be changed.

## To Reproduce

**Using CLI**</br>

Create a file with the backupjob configuration:

```bash
cat << EOF > /tmp/job.txt
NAME = "job_increment_cbt_agent_parallel"

BACKUP_VMS   = "33,34,35"
DATASTORE_ID = 100

FS_FREEZE = "AGENT"
KEEP_LAST = "3"
MODE      = "INCREMENT"

PRIORITY  = 51
EXECUTION = "PARALLEL"
EOF
```

Create the backupjob using the previous file:

```bash
onebackupjob create /tmp/job.txt
```

In this case, the output was as follow:

```
ID: 3
```

Check the backupjob details:

```bash
onebackupjob show 3
```

The output was as follow, and you can see that execution mode is still `SEQUENTIAL`:

```bash
BACKUP JOB 3 INFORMATION
ID             : 3
NAME           : job_increment_cbt_agent_parallel
USER           : oneadmin
GROUP          : oneadmin
LOCK           : None
PERMISSIONS
OWNER          : um-
GROUP          : ---
OTHER          : ---

LAST BACKUP JOB EXECUTION INFORMATION
TIME           : -
DURATION       :   0d 00h00m00s

VIRTUAL MACHINE BACKUP STATUS
UPDATED        :
OUTDATED       :
ONGOING        :
ERROR          :

TEMPLATE CONTENTS
BACKUP_VMS="33,34,35"
BACKUP_VOLATILE="NO"
DATASTORE_ID="100"
EXECUTION="SEQUENTIAL"
FS_FREEZE="AGENT"
INCREMENT_MODE="CBT"
KEEP_LAST="3"
MODE="INCREMENT"
```

**Using Sunstone**</br>

![imagen](https://github.com/OpenNebula/one/assets/56793015/39a1606b-6db9-4057-b402-4d046108af84)

![imagen](https://github.com/OpenNebula/one/assets/56793015/d27cdbe4-db24-4b21-ad9b-06b3841b6505)

![imagen](https://github.com/OpenNebula/one/assets/56793015/f4c40848-c3ce-4733-aa15-24e25ae1b400)

![imagen](https://github.com/OpenNebula/one/assets/56793015/2c2f1506-6e10-46e5-9923-13ce00a5060d)

These pictures follow the creation of the new backupjob and the edition of the attribute `EXECUTION`. Same result as CLI way.

## Expected behavior

A new backupjob created with the chance to change the execution mode from `SEQUENTIAL` to `PARALLEL` for rsync backups.

**Details**
 - Affected Component: [Sunstone, Storage]
 - Hypervisor: [KVM]
 - Version: [6.8.1]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
It is an obvious typo.
Usually it is not recommended but as it is a string I'd try fixing it in the binary until it is fixed upstream ;-).

```bash
cp /usr/bin/oned /usr/bin/oned-$(date +%s)
sed -i.bak 's|PARALELL|PARALLEL|' /usr/bin/oned
```
Checking what was changed in the bynary:
```bash
diff <(xxd /usr/bin/oned.bak) <(xxd /usr/bin/oned)
265232c265232
< 0040c0f0: 4c45 4c4c 0042 4143 4b49 4e47 5f55 505f  LELL.BACKING_UP_
---
> 0040c0f0: 4c4c 454c 0042 4143 4b49 4e47 5f55 505f  LLEL.BACKING_UP_
```

Let's try the new binary
```bash
systemctl restart opennebula
```

Hope this helps.

Best Regards,
Anton

**Comment by Franco-Sparrow** [comment]
@atodorov-storpool Thanks Sir, this solved the issue :)

**Comment by nachowork90** [comment]
The typo is in the line that is referenced:

https://github.com/OpenNebula/one/blob/41461d4c03c9d3eae13ef6b0ce60a5dd9b64c8e4/include/BackupJob.h#L95

I have compiled the packages with this fix and work perfectly.
