### ISSUE TITLE
Few LUKS-related issues

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6467]
**Description**
Few issues:
1) There are two LUKS-related attributes mentioned in oned.conf:
```
$ grep -i luks /etc/one/oned.conf
IMAGE_ENCRYPTED_ATTR = "LUKS_PASSWORD"
INHERIT_IMAGE_ATTR      = "LUKS_SECRET"
```

but only `LUKS_SECRET` is used in the OpenNebula code.
It looks like `LUKS_PASSWORD` should be removed from the `oned.conf` file. 

2) A value for LUKS_SECRET is UUID registered in libvirtd on the hypervisor nodes but not secret itself which is confusing. Shouldn't LUKS_SECRET be renamed into LUKS_UUID?

3) There is no LUKS_SECRET attribute description in the OpenNebula documentations.

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: development

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by mkutouski** [comment]
It looks like LUKS_PASSWORD will be needed for implementing [that](https://github.com/OpenNebula/one/issues/6488) feature.
