### ISSUE TITLE
Remove -V|--version from onecfg help and man page

### ISSUE THREAD

**Issue by mkutouski** [OpenNebula/one#6481]
**Description**
`onecfg` help says:
`        -V, --version             Show version and copyright information`
whereas that tool doesn't have own version. An execution of `onecfg -V` and `onecfg --version` produces the help output.

**To Reproduce**
Check the onecfg man page or its help (`onecfg -h` or `onecfg --help`).

**Expected behavior**
The help on that tool doesn't have to contain mentioned info because there is no such options for that command.

**Details**
 - Affected Component: CLI
 - Version: 6.8.1

**Additional context**

## Progress Status
- [x] Code committed
- [ ] ~~Testing - QA~~
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by xorel** [comment]
I think all the CLI is actually wrong, e.g. with `onevm --version` I would expect to return just the version, not the full help, at least the help says so

```
     -V, --version             Show version and copyright information
```

**Comment by tinova** [comment]
ok, @mkutouski can you please check all the other one* commands?
