### ISSUE TITLE
Disable users

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#649]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2030, https://dev.opennebula.org/issues/2030
Original Date: 2013-05-13

---

Add disable/enable functions for users. A disable user will not:

1. be able to make any api call
1. log in sunstone interface

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2013-05-17T18:57:59Z

---

DON'T FORGET EC2 and OCCI

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **John Noss** (John Noss)
Original Date: 2017-01-25T20:33:25Z

---

This would be a great feature to have, +1 from me! Also, to confirm, will this revoke any existing sessions (sunstone or xmlrpc cli authenticated)? (And, will this work for ldap users, as well?)

**Comment by paczerny** [comment]
PRs (merge to master):
* src: https://github.com/OpenNebula/one-ee/pull/545
* tests: https://github.com/OpenNebula/development/pull/1233
* doc: https://github.com/OpenNebula/docs/pull/1381

**Comment by tinova** [comment]
Needs Sunstone to expose:

  - User state in the datatable
  - Add enable/disable button

This can be mimicked from the host tab.

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- [code](https://github.com/OpenNebula/one-ee/pull/727)
- [docs](https://github.com/OpenNebula/docs/pull/1433)

**Comment by tinova** [comment]
needs testing

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Tests](https://github.com/OpenNebula/development/pull/1391)
