### ISSUE TITLE
Update drop-downs to datatables

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#651]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2038, https://dev.opennebula.org/issues/2038
Original Date: 2013-05-14

---

In some places, Sunstone still uses the 3.8 drop-downs; e.g. in a deploy operation, a list of host is used instead of a datatable.

**Comment by rsmontero** [comment]
Already done
