### ISSUE TITLE
[FSunstone] Add LDAP Support

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6514]
**Description**

Same functionality as RSunstone

Need to add a note in the [FireEdge Auth guide](https://docs.opennebula.io/6.8/installation_and_configuration/authentication/fireedge.html) 

## Progress Status
- [ ] ~~Code committed~~
- [x] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
No additional configuration is required, since the core use of the LDAP driver and fireedge use of XMLRPC, it is already a function of the oned to authenticate a user.
