### ISSUE TITLE
Update SSH public key on virtual machine

### ISSUE THREAD

**Issue by dcarracedo** [OpenNebula/one#6519]
**Description**
Update SSH public key in Update configuration form is not working if user clicks on the Add user SSH public key. The value that is stored is an empty string.
[Screencast from 26-02-24 14:19:04.webm](https://github.com/OpenNebula/one/assets/134921994/0f277e19-3b86-4d4d-a1c9-f1c93123aea8)

**To Reproduce**

1. Select a running VM
2. Click on the vm and select the tab Configuration
3. Click on Update vm configuration
4. Click on context tab
5. Click on Add SSH user public key
6. Click accept

**Expected behavior**
That in the template the SSH public key will be added.

**Details**
 - Affected Component: FireEdge
 - Hypervisor: N/A
 - Version: 6.8

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
works for me
