### ISSUE TITLE
Support graceful VM deletion from UNDEPLOY

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#652]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2042, https://dev.opennebula.org/issues/2042
Original Date: 2013-05-14

---

Currently, an undeployed VM can only be resumed or deleted.
We should add an operation to remove the VM, but saving the persistent images back to the datastores.

**Comment by rsmontero** [comment]
Done for example via save as
