### ISSUE TITLE
Direct backup on remote server

### ISSUE THREAD

**Issue by mkutouski** [OpenNebula/one#6540]
**Description**
Make possible backup operations when files are copied to backup server directly  skipping a creation of temporary files on local CN's FS.

**Use case**
Some VMs disks can have larger size. Temporary backup files for such disks may fill out the whole free space on CN local file system. That may lead to CN misbehavior.

**Interface Changes**
Probably some kind of additional configuration parameter is needed e.g. TEMP_FILES= (yes, no}.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by nachowork90** [comment]
Posible related to  FR https://github.com/OpenNebula/one/issues/6202

**Comment by mkutouski** [comment]
duplicates #6202
