### ISSUE TITLE
Check VM status before scheduling backup operation

### ISSUE THREAD

**Issue by mkutouski** [OpenNebula/one#6542]
**Description**
It's possible now to schedule backup action for VM in status ``DONE`` what is wrong. It shouldn't be possible.

**To Reproduce**
```
onetemplate instantiate 0 --name test-backup-vm_done
VM ID: 4

onevm show 4 |grep -i "lcm_state"
LCM_STATE           : RUNNING 

onevm terminate --hard 4

onevm show 4|grep -i ^state
STATE               : DONE                

onevm backup --schedule now -d 101 4
VM 4: backup scheduled at 2024-03-15 12:24:32 +0000

onevm show 4|grep -i backup
NAME                : test-backup-vm_done 
    6 backup 101,0 03/15 12:24             Overdue!
```

**Expected behavior**
It shouldn't be possible to schedule backup operation on VM in status ``DONE``.
The command `onevm backup --schedule now ...` should fail.

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [6.8.2]

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
While implementing this, fixed a removing of Scheduled Actions during Virtual Machine transition to done state.
