### ISSUE TITLE
Sunstone: Scheduled Action Edit page selects periodic checkbox for non-periodic actions

### ISSUE THREAD

**Issue by paczerny** [OpenNebula/one#6551]
**Description
Sunstone `Edit Scheduled Action` page doesn't read the actual value of ``REPEAT`` from Scheduled Action correctly. It always selects the periodic checkbox

**To Reproduce**
![SA_edit](https://github.com/OpenNebula/one/assets/28096759/69f9fb80-2846-4717-8fec-a0f7befd77df)

**Expected behavior**
periodic checkbox not selected

**Details**
 - Affected Component: Sunstone
 - Version: 6.8

**Additional context**
For non periodic actions Sunstone sets ``END_TYPE`` to ``DATE`` .The ``END_TYPE`` can be omitted or set to END_NONE (-1).
Setting the ``END_TYPE`` is not a bug, it's just not necessary, the oned doesn't expect the ``END_TYPE`` for non-periodic actions

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
closing, please reopen if this is reproducible in FireEdge Sunstone
