### ISSUE TITLE
Updateconf API Call may lead to inconsistent CONTEXT attributes

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6552]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**
When using the updateconf command/API call if a network attribute is set (e.g. `ETH0_METHOD=1234`) the value get's the NIC/VNET default.  However `onevm show` renders the wrong vale `1234`.

**To Reproduce**
As described above

**Expected behavior**
consistent attribute values

**Details**
 - Affected Component: oned
 - Hypervisor: -
 - Version: 6.8

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
Fixed by disabling updates of ``CONTEXT->ETH*`` attributes by `onevm updateconf` These attributes should be updated in NIC
Also fixed disapearing of all ``CONTEXT->ETH*``, in case of ``onevm updateconf`` in replace mode, if ``CONTEXT->NETWORK=YES``
