### ISSUE TITLE
Improve Scheduler feedback

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#656]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2073, https://dev.opennebula.org/issues/2073
Original Date: 2013-05-22

---

This is for:
* Sunstone and CLI should make more clear that the scheduler cannot be scheduled
* Error message should be as clear as possible
* The scheduler will record the number of tries and fail the VM after a given number

**Comment by rsmontero** [comment]
Additional information was included. Also this information was added to the VM information so it can be checked through sunsonte
