### ISSUE TITLE
Monitoring of system datastore is not working when used ceph with ceph quota

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6564]
**Description**

When using ceph with quota, the image datastore is updated while the system remains unchanged. SDS should not be configured to use more than its 85% of capacity. The monitoring works fine without ceph quota, but not when using ceph quota. Once applied the configuration and having passed the monitoring cicle, only one driver action is executed (the one belonging to the images datastore), while the other is not executed.

![imagen](https://github.com/OpenNebula/one/assets/56793015/1e2e8344-5944-4906-9d94-ba3250fa05d2)

![imagen](https://github.com/OpenNebula/one/assets/56793015/dcdeac14-5b66-4666-82ac-20d18a762353)

![imagen](https://github.com/OpenNebula/one/assets/56793015/c0397637-f564-4a04-9d91-deee12f7777a)

**To Reproduce**

This is the configuration of the images datastore:

```bash
onedatastore show 102
DATASTORE 102 INFORMATION
ID             : 102
NAME           : images-hdd
USER           : oneadmin
GROUP          : oneadmin
CLUSTERS       : 0
TYPE           : IMAGE
DS_MAD         : ceph
TM_MAD         : ceph
BASE PATH      : /var/lib/one//datastores/102
DISK_TYPE      : RBD
STATE          : READY

DATASTORE CAPACITY
TOTAL:         : 1.8T
FREE:          : 1.8T
USED:          : 0M
LIMIT:         : -

PERMISSIONS
OWNER          : um-
GROUP          : u--
OTHER          : ---

DATASTORE TEMPLATE
ALLOW_ORPHANS="mixed"
BRIDGE_LIST="Cluster-LA-DEV-node1 Cluster-LA-DEV-node2 Cluster-LA-DEV-node3"
CEPH_HOST="Cluster-LA-DEV-node1 Cluster-LA-DEV-node2 Cluster-LA-DEV-node3"
CEPH_SECRET="45362778-1dc7-4252-a9b9-d9ead80d5338"
CEPH_USER="libvirt"
CLONE_TARGET="SELF"
CLONE_TARGET_SHARED="SELF"
CLONE_TARGET_SSH="SYSTEM"
DISK_TYPE="RBD"
DISK_TYPE_SHARED="RBD"
DISK_TYPE_SSH="FILE"
DRIVER="raw"
DS_MAD="ceph"
LN_TARGET="NONE"
LN_TARGET_SHARED="NONE"
LN_TARGET_SSH="SYSTEM"
POOL_NAME="hcx_pool1"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
TM_MAD="ceph"
TM_MAD_SYSTEM="ssh,shared"
TYPE="IMAGE_DS"

IMAGES
```

This is the configuration of the system datastore:

```
onedatastore show 103
DDATASTORE 103 INFORMATION
ID             : 103
NAME           : system-hdd
USER           : oneadmin
GROUP          : oneadmin
CLUSTERS       : 0
TYPE           : SYSTEM
DS_MAD         : -
TM_MAD         : ceph
BASE PATH      : /var/lib/one//datastores/103
DISK_TYPE      : RBD
STATE          : READY

DATASTORE CAPACITY
TOTAL:         : 3.1T
FREE:          : 3.1T
USED:          : 0M
LIMIT:         : -

PERMISSIONS
OWNER          : um-
GROUP          : u--
OTHER          : ---

DATASTORE TEMPLATE
ALLOW_ORPHANS="mixed"
BRIDGE_LIST="Cluster-LA-DEV-node1 Cluster-LA-DEV-node2 Cluster-LA-DEV-node3"
CEPH_HOST="Cluster-LA-DEV-node1 Cluster-LA-DEV-node2 Cluster-LA-DEV-node3"
CEPH_SECRET="45362778-1dc7-4252-a9b9-d9ead80d5338"
CEPH_USER="libvirt"
DISK_TYPE="RBD"
DS_MIGRATE="NO"
POOL_NAME="hcx_pool1"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
SHARED="YES"
TM_MAD="ceph"
TYPE="SYSTEM_DS"

IMAGES
```

Enable ceph quota:

```bash
ceph osd pool set-quota hcx_pool1 max_bytes 2000000000000
```

**Expected behavior**

Monitoring of system datastore working as expected, and updating the system datastore, like images datastore do.

**Details**
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [6.8.2]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
Not sure if this is an issue, but is there a space between the hostnames 1 and 2?

> CEPH_HOST="Cluster-LA-DEV-node1Cluster-LA-DEV-node2 Cluster-LA-DEV-node3"

**Comment by Franco-Sparrow** [comment]
Sorry, that was me renaming the hosts from their original hostname.
