### ISSUE TITLE
Remove docker machine add-on from distribution

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6586]
**Description**
This issue is to remove docker-machine addon from the OpenNebula distribution including:

- [x] source code
- [x] packages
- [x] documentation
- [x] QA

**Use case**
How are you going to use this new feature? Why do you need it?

**Interface Changes**
Describe any changes you'd like to see to current interfaces including Sunstone, CLI, or/and API

**Additional Context**
Please feel free to add any other context or screenshots about the feature request here. Or any other alternative you have considered to address this new feature.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by albert0marti** [comment]
@rsmontero what about this? https://github.com/OpenNebula/docker-machine-opennebula

**Comment by rsmontero** [comment]
@albert0marti thanks for the heads up, I've archived the original repo as well :)

**Comment by albert0marti** [comment]
What about this? https://github.com/OpenNebula/boot2docker-one Still makes sense?

**Comment by rsmontero** [comment]
archived as well :)

**Comment by feldsam** [comment]
@rsmontero @albert0marti Hi guys! Why you removed docker-machine driver? There is still use for it. I know, that original docker-machine project is archived, but there is still maintained fork from gitlab https://gitlab.com/gitlab-org/ci-cd/docker-machine and also from rancher https://github.com/rancher/machine

So docker-machine opennebula driver should be still included at least as separate addon repository. In past I contriubuted enhancements to this driver.

**Comment by feldsam** [comment]
Hi again guys @rsmontero @albert0marti ,

I did changes in fork of this archived repo https://github.com/feldsam/docker-machine-opennebula

I updated code from latest 6.8 version and then fixed startup script and removed boot2docker support. 

Now it is working with latest docker-machine fork from Gitlab - still maintained. I tested it on latest EL9 with latest docker version.

I think, this driver should be still kept maintained.

Would you then unarchive repo or create new one - addon please?
