### ISSUE TITLE
Handle permissions required by apache2 when upgrading

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6591]
**Description**
When performing an upgrade of OpenNebula, the new packages place files with stock permissions, replacing the existing ones. Normally, this is not a problem but when serving Sunstone, on apache, [certain filesystem permissions](https://docs.opennebula.io/6.2/installation_and_configuration/large-scale_deployment/sunstone_for_large_deployments.html#deploy-in-webserver) need to be set such that the apache user can run Sunstone. When the upgrade is performed, naturally "these files" will get their permission "reset" and the user will run into this problem

```log
[Mon Feb 14 11:10:09.133702 2022] [core:error] [pid 668659:tid 140354620548864] [client 10.141.18.116:60062] AH00037: Symbolic link not allowed or link target not accessible: /usr/lib/one/sunstone/public/dist/main.js, referer:
```

2 tasks must be performed
- [ ] detect if sunstone is being served by apache and ensure required permissions at the package install scripts level
- [ ] add a note on the [upgrade section](https://docs.opennebula.io/6.8/intro_release_notes/upgrades/upgrading_single.html#step-10-start-opennebula) for the user to make sure that this requirement is met

**Use case**
Having this problem effectively disables the Web interface for users with large deployments when an upgrade is performed. Automatically handling/noting this case during an upgrade will result in less panic overall.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by apiconc** [comment]
Please, @dann1, add this requirement to the upgrade documentation as a short term measure to assure consistent updates

**Comment by xorel** [comment]
@dann1 can you also add the path of the file with the wrong permission?

**Comment by rsmontero** [comment]
We have:
1. Included an extra step in the upgrade guide to spell this out
2. Check folder permissions on postinst phase in packages to warn the user
