### ISSUE TITLE
Reference parameters within a context

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#662]
---

Author Name: **Steffen Claus** (Steffen Claus)
Original Redmine Issue: 2117, https://dev.opennebula.org/issues/2117
Original Date: 2013-06-12

---

I am trying to dynamically define needed files for a template as follows:

CONTEXT[
 FILES_DS="$FILE[IMAGE=\"testfile\"] $FILE[IMAGE=\"$MY_NAME\"]"
]
MY_NAME="image-name"

This doesn't work at the moment, as the parameter $MY_NAME is not expanded.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2013-06-12T12:36:24Z

---

This makes sense indeed. I am moving this to the backlog to implement it in a future release. This issue will deal with this and a more general situation where substitutions may happen in other variables.

Additionally we may consider it in relation with flow, so variables can be substitute in multiple service templates.

THANKS for your feedback

**Comment by rsmontero** [comment]
Already implemented in current versions
