### ISSUE TITLE
Make appflow templates self-contained, adding the option to define VM and VNet templates

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#663]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2125, https://dev.opennebula.org/issues/2125
Original Date: 2013-06-14

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2013-10-28T17:20:51Z

---

I add here what I put in my "email":http://thread.gmane.org/gmane.comp.distributed.opennebula.user/12728 for records.

I would like to manage some kind of “infrastructure libraries” with VMs templates and networks.

For example, an “infrastructure” could declare:

* 1 network called *@internet@*, shared between all infrastructures to have network access with outside
* 1 network called *@DMZ@*
* 1 network called *@LAN@*
* 1 *@router@* VMs with:
** its first interface on *@internet@*, configured as DHCP or contextualized
** its second interface on *@DMZ@*
** its third interface on *@LAN@*
* X *@server@* VMs with one interface on *@DMZ@*
* Y *@workstation@* VMs with one interface on *@LAN@*

When a user instanciate this “infrastructure”:

1. 2 new networks are created:
** DMZ-<UNIQ NUMBER>
** LAN-<UNIQ NUMBER>
1. a temporary clone of *@router@* is created with:
** its first interface network untouched
** its second interface network set to *@DMZ-<UNIQ NUMBER>@*
** its third interface network set to *@LAN-<UNIQ NUMBER>@*
1. *@1@* VMs is started from that temporary *@router@* VM template
1. a temporary clone of *@server@* is created with its interface network set to *@DMZ-<UNIQ NUMBER>@*
1. *@X@* VMs are started from that temporary  *@server@* VM template
1. a temporary clone of *@workstation@* is created with its interface network set to *@LAN-<UNIQ NUMBER>@*
1. *@Y@* VMs are started from that temporary *@workstation@* VM template

This would be a great addition for us for a testing framemork, we can instanciate complete infrastructures for our functional tests.

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2016-01-11T14:13:13Z

---

Hello,

This request is partially managed with "Role Dynamic Networks":http://docs.opennebula.org/4.14/advanced_administration/application_flow_and_auto-scaling/appflow_use_cli.html#configure-dynamic-networks.

It requires the user to manually map the *@Dynamic Networks@* to OpenNebula networks.

For information, we workaround by creating per user networks with the same name and associate VM template to network *@NAME@* without the *@UNAME@* to let oned look for a network of this *@NAME@* owned by the user who instantiate the VM template.

The disadvantage of this workaround is that a user can not start two time the same service since we get conflicts with some network services like DHCP or samba (we test complete network infrastructure since we edit a linux distribution ;-))

For example, she must poweroff the service for version X of the distribution to start the same network infrastructure service for version Y.

Regards.

**Comment by al3xhh** [comment]
This is already implemented, in the OneFlow, the following operations can be done with VNets:

- You can use an existing virtual network (this was implemented in the past)
- You can instantiate a Virtual Network Template.
- You can reserve a new Virtual Network from an existing one.

All the documentation can be found [here](http://docs.opennebula.io/5.11/advanced_components/application_flow_and_auto-scaling/appflow_use_cli.html#configure-dynamic-networks).

Closing it as the functionality is already implemented.
