### ISSUE TITLE
Support for OneFlow Services in the Marketplace

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#664]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2127, https://dev.opennebula.org/issues/2127
Original Date: 2013-06-14

---

The marketplace could contain services. Or service templates could use Images stored in a marketplace.

**Comment by tinova** [comment]
First we need support for VM Templates in marketplace

**Comment by al3xhh** [comment]
We will consider also adding support for VM templates with more than one image associated to it

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- one: https://github.com/OpenNebula/one-ee/pull/509

**Comment by tinova** [comment]
- Needs (at least Sunstone) testing @FrederickBor 
- Needs documentation and Whats new @al3xhh

**Comment by FrederickBor** [comment]
Needs Sunstone support for `onemarketapp vm import`

**Comment by FrederickBor** [comment]
@tinova PR to be approved: 
- [code](https://github.com/OpenNebula/one-ee/pull/739)

**Comment by tinova** [comment]
Needs testing

**Comment by FrederickBor** [comment]
@tinova PR to be approved:
- [Tests](https://github.com/OpenNebula/development/pull/1281)

**Comment by sbbarragan** [comment]
PR to merge:
-one: https://github.com/OpenNebula/one-ee/pull/934/files
