### ISSUE TITLE
Implement OneGateProxy in VN drivers

### ISSUE THREAD

**Issue by sk4zuzu** [OpenNebula/one#6641]
**Description**
Implement improved OneGateProxy that would use TPROXY, without the requiremnt for VNET bridge to have an IP address assigned. The legacy standalone proxy must be decomissioned #6281.

Planned changes:
1. This proxy solution must NOT depend on IP addresses set on VNET bridges.
2. Each VNET should get a dedicated lightweight proxy process (likely written in ruby) running on each HV node (parameterized with an unique SO_MARK value).
3. VNET drivers should (on per VNET basis) accordingly configure the following entities on HV nodes: ebtables rules, policy routing, rp_filter settings for involved interfaces, TPROXY rules.
4. VNET templates should be extended with a “GATEPROXY” or similar attribute (boolean, false by default).
5. The predefined static route 169.254.16.9 must be removed from one-context.
6. The old standalone proxy must be decomissioned.

**Use case**
Completely transparent access to OneGate from any VM.

**Interface Changes**
Additional options in VNET templates to include OneGateProxy on/off (TBD).

**Additional Context**
N/A

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by feldsam** [comment]
Hello @sk4zuzu, what about removing also rubygems `etc` and `rb-ionotify` from Gemfile https://github.com/OpenNebula/one/blob/5f7b370c5274434804726c3feb435c98af761963/share/install_gems/Gemfile#L44

Looks like they are not anymore used.
