### ISSUE TITLE
Remove Postgresql dependencies

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6653]
**Description**
This issue is to drop support for Postgresql. We have seen some but limited interest in another DB backend and team prefer to focus on one main production DB (MySQL/MariaDB) and Sqlite for small scale and testing purposes:

-  [x] Documentation (installation guide, removed components, oned.conf options)
- [x] OpenNebula oned dependencies
- [x] Testing and QA environment 
- [x] One-deploy references

**Use case**
-

**Interface Changes**
Drop option in oned.conf

**Additional Context**
-

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
One-deploy dependencies will be addressed in a separate issue in that project.

**Comment by evili** [comment]
There is no documentation on how to proceed from OpenNebula <= 6.8 + PostgreSQL to OpenNebula 6.10 + MariaDB.

Is there some recommended action / path (apart from keeping ON 6.8 for ever)?

Was it really necessary to Postgres?
:(
