### ISSUE TITLE
MAX_BACKUPS and MAX_BACKUPS_HOST typo in `sched.conf`

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6655]
**Description**
The options for `MAX_BACKUPS` and `MAX_BACKUPS_HOST` in the `sched.conf` file differs from those in the `oned.conf` and the commented lines for the help at the begining of both files. After installed opennebula packages, the `sched.conf` has `MAX_BACKUP` and `MAX_BACKUP_HOST` without the `S`. The service dont fail after restart, with or without the `S`, but which is the right configuration?

**To Reproduce**
Install opennebula packages and check `sched.conf` file. Compare it with same options insde `oned.conf` and with the commented lines an the begining of both files.

**Expected behavior**
Both optiones should be the same on both files (`oned.conf` and `sched.conf`). 

**Details**
 - Affected Component: [Scheduler, Storage]
 - Hypervisor: [KVM]
 - Version: [6.8.2]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment]
Hi

May I have a follow up on this?

Thanks

**Comment by paczerny** [comment]
For version 6.8, the only valid configuration for `MAX_BACKUPS` and `MAX_BACKUPS_HOST` is in `oned.conf`.
The values in `sched.conf` are not used and you can safely remove them.

**Comment by paczerny** [comment]
I'm closing this as we can't modify configuration files in Maintenance (bug fix) release and it's already fixed for 6.10 release
