### ISSUE TITLE
Add merge functionality when creating a new VM from a given template

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#666]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2149, https://dev.opennebula.org/issues/2149
Original Date: 2013-07-04

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2013-10-02T08:04:39Z

---

Hello,

I wonder if this issue could cover the addition of a field in template wizard with an ordered list of template it inherits.

The wizard could show inherited values as inactive fields, requiring a user action like double click to change the value.

Such a feature could be related to my comments on #1764.

Regards.

**Comment by rsmontero** [comment]
Done through several features: user inputs, inherited attributes...
