### ISSUE TITLE
VLAN trunking and QinQ  support for Linux Bridges

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6669]
**Description**
This issue it to implement VLAN trunking support in Linux bridging.  As the  implementation of QinQ uses this bridge functionality we will implement support for it in this issue.

**Use case**
This will allow to restrict the VLANs that a VM can access to and use trunking mode in a secure way, as we'll as easily define QinQ networks.

**Interface Changes**
The implementation should use the attributes already present in OpenvSwitch

* VLAN trunking, uses ``VLAN_TAGGED_ID`` to specify a range of VLANs to tag, for example: 1,10,30,32,100-200.
* QinQ uses 2 different attributes to set the customer and service vlan ids:
  - ``CVLANS`` Customer VLAN IDs, as a comma separated list
  -  ``VLAN_ID`` Service 802.1Q VLAN ID.  (current setting)

**Additional Context**
A different feature will address access control to the VLAN sets

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by cliffalbert** [comment]
Looking forward to this feature, it would make my life a lot easier! :)

**Comment by rsmontero** [comment]
This is now implemented and will be released in the next maintenance versions, more details in:

* [QinQ in 802.1Q driver](https://docs.opennebula.io/6.99/open_cluster_deployment/networking_setup/vlan.html#using-802-1q-driver-with-q-in-q)

* [VLAN trunking in bridge driver](https://docs.opennebula.io/6.99/open_cluster_deployment/networking_setup/bridged.html#vlan-filtering-and-trunking)

**Comment by Franco-Sparrow** [comment]
Thanks for this new feature. Feliz Navidad!
