### ISSUE TITLE
Scheduled policy start_time cannot be defined as a POSIX time number

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#668]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2155, https://dev.opennebula.org/issues/2155
Original Date: 2013-07-05

---

None

**Comment by al3xhh** [comment]
PR to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/20)

PR to merge in 5.12

- [docs](https://github.com/OpenNebula/docs/pull/1209)
