### ISSUE TITLE
Check VMGroupRole in VMGroupXML.cc

### ISSUE THREAD

**Issue by sminux** [OpenNebula/one#6692]
**Description**
Return value of a function 'VMGroupRoles::get' is dereferenced at VMGroupXML.cc:
https://github.com/OpenNebula/one/blob/1ae1de46dc59b1c277a205fbe16dd7618e6aa57b/src/scheduler/src/pool/VMGroupXML.cc#L177-L179
without checking for NULL, but it is usually checked for this function (4 of 5).
Like that:
https://github.com/OpenNebula/one/blob/1ae1de46dc59b1c277a205fbe16dd7618e6aa57b/src/scheduler/src/pool/VMGroupXML.cc#L428-L433

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler, or Storage]
 - Hypervisor: KVM
 - Version: 6.9.8 or development

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Merged in [1607b4a](https://github.com/OpenNebula/one/commit/1607b4a0145c97fbb43f621822dd452d10a1dd5f)
