### ISSUE TITLE
Download repo folder missing the "6.10" version with release file

### ISSUE THREAD

**Issue by DanielLopezDiaz** [OpenNebula/one#6702]
Hi,

I was trying to try out the new release 6.10 but found that the documentation and repo are not in line with the specific version in the command line and repo directory structure. 

https://downloads.opennebula.io/repo/6.10/Ubuntu/22.04

if you verify the URL path the version 6.10 directory is not seen in the repo, and it complains about the release file as well so something seems to be off or has gone wrong.

**Comment by tinova** [comment]
should be now correctly aligned, 6.10 is already out
