### ISSUE TITLE
backups of VM with volatile disks doesn't work

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#6715]
**Description**
There is an option(checkbox) to do VM backup with the volatile disks included but it breaks the entire backup.

**To Reproduce**
instantiate a VM with a persistent/non-presistent disk (doesn't matter)
add a volatile disk
issue a VM backup
the vmbackup will fail with error ```undefined method `text' for nil:NilClass```

**Expected behavior**
The VM backups should complete

**Details**
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [6.10]

**Additional context**
Hint: The volatile disks had no "SAVE" element...
Still can't understand the overall idea of the backup implementation to be more constructive on the matter :-/

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
Duplicate #6505
