### ISSUE TITLE
Replace VNC Server

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#6727]
**Description**
Kasm workspaces has an opensource VNC server named [KasmVNC](https://github.com/kasmtech/KasmVNC) which is configurable, has a dashboard and generally is rather modern. it's of course also faster and all that.

**Use case**
Faster / reliable access to VMs. Less keymap problems.
Be able to work in VM consoles (also from cloud view)

**Interface Changes**
Things like automatic resize...
It would be nice if we had a reset / reset hard button in the VNC tab at last, too, so it's not as much a competitive clicks per second task to get into a boot menu.

**Additional Context**
Take 20 minutes to try it out (the whole kasm thing is up in less.). The Sunstone VNC feature has rarely seen improvements, there's a mountain of tech debt, it would be viable to replace it with a already done better version instead of overhauling. i know you just refreshed UI, but it doesn't have to stay a missed opportunity. 

Also I'm very sorry I can't find how to apply labels to the issue.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
FireEdge Sunstone currently uses Guacamole. We are deprecating Ruby Sunstone and noVNC, which won't be present in the next major OpenNebula version.

I'm closing this for the time being, but we can use it to discuss KasmVNC vs Guacamole, so see if the benefits justify the effort.

> It would be nice if we had a reset / reset hard button in the VNC tab at last, too, so it's not as much a competitive clicks per second task to get into a boot menu.

This is a convenient feature indeed, we will tackle it in the context of #5766

**Comment by FlorianHeigl** [comment]
Hi Tino,

FYI: it is just the same set of advantages compared to Guacamole. Look at the feature list if possible.
(It's day and night)

**Comment by vichansson** [comment]
Hi @FlorianHeigl,

KasmVNC looks awesome when glancing over their feature set, we've opened another issue specifically in regards to this. You can keep track of it from here OpenNebula/one#6731

**Comment by tinova** [comment]
Quick question @FlorianHeigl , we are trying to make copy&paste work, but it looks like a limitation on the qemu VNC server unfotunately. Let us know if you have some insights on this, this prevents using the nice features of kasmvnc, since we need to rely on the qemu VNC server.
