### ISSUE TITLE
`onevm restore` not detecting disks from the backup when restoring specific disk through FSunstone

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6739]
## Description

Restoring specific disk of the Virtual Machine (in POWEROFF state) from the backup Image, is not detecting disks on FSunstone when restore directly to VM disks. You cant restore specifying the disk to restore, directly to the VM.

## To Reproduce

- Create a new VM with more than one disk: `vda` and `vdb`.
- Partitionate and format the 2nd disk.
- Mount the 2nd disk and make it persistent (`/mn/vdb/data/`).
- Configure the VM fort Single VM backups: `BACKUP_VOLATILE: YES`, `INCREMENT_MODE: CBT`,  `FS_FREEZE: AGENT`, `KEEP_LAST: 3`, `MODE: INCREMENT`.
- Before create a backup, create the following files in the VM:
```bash
touch inc0 && touch /mnt/vda/data/inc0
```
- Perform the first backup.

- Perform the 2nd backup.

- Poweroff the VM, in order to restore directly on same VM.
- Restore the backup directly to same VM using FSunstone.
![WhatsApp Image 2024-09-26 at 5 08 13 PM](https://github.com/user-attachments/assets/e8f34ffb-aee0-49a7-ba5c-007bb5c64794)
![WhatsApp Image 2024-09-26 at 5 08 41 PM](https://github.com/user-attachments/assets/1bbc3aa3-3981-4347-a339-c7acb5a610d2)

- There is no disk detected to select for restore:
![WhatsApp Image 2024-09-26 at 5 09 01 PM](https://github.com/user-attachments/assets/5c5ad490-4f04-4836-b3ee-5cfee2467045)

## Expected behavior

There should be enable the selection of disks to restore. It works using the CLI:

![WhatsApp Image 2024-09-26 at 5 00 59 PM](https://github.com/user-attachments/assets/3e8fcd39-c3bf-4dda-92d1-0dc517fb6055)

## Details
 - Affected Component: [e.g. Sunstone, Storage]
 - Hypervisor: [KVM]
 - Version: [6.10.0]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
Hi @Franco-Sparrow!

This was indeed a bug when invoking the restore dialog from the VM action menu. However it works as expected if you try to restore a backup image from the Storage->Backups tab.

Fix will be included in 6.10.1, thanks for reporting!
