### ISSUE TITLE
Fireedge is not showing Datastore limit on `system` datastore and is not showing right limit on `images` datastore

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6746]
## Description

Fireedge (FSunstone) is not properly showing datastore limit. For `system` datastore limit is not shown and for `images` datastore is not showing the right value. The limit is working, as is on the CLI output for the datastores. Old Sunstone also shows the right limit on both datastores. The problem is on FSunstone.

Working on CLI for `system` datastore:

![WhatsApp Image 2024-10-07 at 7 05 01 PM](https://github.com/user-attachments/assets/753b947e-190a-4294-adcd-b98c16d9aa97)

Working on CLI for `images` datastore:

![WhatsApp Image 2024-10-07 at 7 06 28 PM](https://github.com/user-attachments/assets/cf8620ef-f127-4d11-9cc1-eb269d8fe528)

Working on OLD Sunstone for `system` datastore:

![WhatsApp Image 2024-10-07 at 7 14 46 PM](https://github.com/user-attachments/assets/b6d00ff8-3244-4ac1-ac09-99308cd57cfb)

Working on OLD Sunstone for `images` datastore:

![WhatsApp Image 2024-10-07 at 7 14 55 PM](https://github.com/user-attachments/assets/d1f6da74-c91e-445d-ad4b-6c0716808955)

NOT working on FSunstone for `system` datastore:

![WhatsApp Image 2024-10-07 at 7 07 46 PM](https://github.com/user-attachments/assets/8a2abcac-d74c-49bc-b0f9-4ade94f347cc)

NOT working on FSunstone for `images` datastore:

![WhatsApp Image 2024-10-07 at 7 08 50 PM](https://github.com/user-attachments/assets/e5faf436-1afa-4a8b-8791-0b554ff714c8)

## To Reproduce

Configure `LIMIT_MB` datastore attribute on `system` and `images` datastores. Update those datastores with this attribute.

## Expected behavior

FSunstone showing the right datastore limite on both datastores.

**Details**
 - Affected Component: [FSunstone]
 - Hypervisor: [KVM]
 - Version: [6.10.0]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment]
Hi @vichansson 

I have you another FSunstone issue. Just a cosmetic one. Sorry to call directly on this, but as you assisted my previous FSunstone issue, I wanted to let you know this bug on first hand.

Cheers

**Comment by vichansson** [comment]
Hi @Franco-Sparrow !

Thanks for the heads up. I just tried this myself and FSunstone does indeed round up the DS limit pretty aggressively. Added a fix to 6.10.1 where the number precision is increased to one decimal place, which should replicate the behavior of RSunstone.


Best regards,
Victor

**Comment by Franco-Sparrow** [comment]
Hi @vichansson 

Did you also checked the limit on the `system`datastore? In this case is omitted by Sunstone, while is aggressively roundup on the `images` datastores, as you can witness.

Thanks for you quick support.

**Comment by vichansson** [comment]
Hi @Franco-Sparrow ,

Yes, the limit should be displayed on all kinds of datastores. The only issue I could find with the limit not being displayed properly on `system` datastores was if the `Filesystem - shared mode` storage backend was being used. This adds the `SHARED` property which FSunstone used to dynamically render  the limit. This check has however been removed from 6.10.1.

Cheers,
Victor
