### ISSUE TITLE
Issue with RAW swtpm context in Sunstone / FireEdge GUI for WIndows

### ISSUE THREAD

**Issue by jkritzen** [OpenNebula/one#6751]
**Description**
Fireedge instanciation of WIndows VM with swtpm enabled doesn't work via GUI. If you wan't to finish the instanciate from template you can clisk the finsh button but nothin happens. With `onetemplate instantiate 9` the same template get's deplyoed.

**To Reproduce**

1. Add the swtpm to the RAW section of the Template:
```
  "RAW": {
    "DATA": "<devices><tpm model='tpm-crb'><backend type='emulator' version='2.0'/></tpm></devices>",
    "TYPE": "kvm",
    "VALIDATE": "YES"
  },
```
2. Save the Template
3. Try to instantiate the template from the GUI, you can't press finsish (eg. nothing happens)!

**Expected behavior**
The VM will be instanciated, as with `onetemplate instantiate`

**Details**
 - Affected Component: [e.g. Sunstone Fireedge]
 - Hypervisor: [KVM]
 - OpenNebula Version: [6.10.0]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
Hi @jkritzen!

Thanks for reporting this. Tried this out myself and confirmed it was indeed a bug in how the template was being handled in FSunstone. Just added a fix which will be included in 6.10.1.


Cheers,
Victor
