### ISSUE TITLE
On the sunstone hosts info pane, please provide a graphs that displays the data for all the vms on the host

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#676]
---

Author Name: **Adam Heath** (Adam Heath)
Original Redmine Issue: 2240, https://dev.opennebula.org/issues/2240
Original Date: 2013-07-28

---

For each host, it'd be nice to see what all the vms are have been doing with their cpu and memory(and maybe network) usage, over the last little bit of time.  So that when the inevitable performance problem starts to happen, it'd be possible to track down the problem suspects.  Currently, I have to do a lot of guess work to figure out which vm might be abusing the resources, or causing a swap storm.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2013-07-29T22:09:19Z

---

This makes sense indeed, as we already have this for other resources (datastores have a tab with images, clusters tabs with hosts, vnets; vnets a tab with leases, and so on.)

**Comment by rsmontero** [comment]
Already include a list to running VMs and lint to them
