### ISSUE TITLE
Backup job failed 

### ISSUE THREAD

**Issue by nookeist** [OpenNebula/one#6766]
**To Reproduce**
Hello. I create backup datastore by rsync. If i start backup from VM menu everything works fine, but if i set backup job it get fail.
Also if backup job exist, backup from VM menu does not start

**Details**
 - Affected Component: Backup job
 - Hypervisor: KVM
 - Version: 6.8

**Additional context**
VM Log
```
New LCM state is BACKUP
Command execution failed (exit code: 255): /var/lib/one/remotes/tm/ssh/prebackup_live
server.contoso.com:/var/lib/one//datastores/0/4099 0: 5f9178c4-506b-409d-9747-46d828916ea0 13 4099 0

BACKUP: ERROR: prebackup_live: Command failed: export LANG=C export LC_ALL=C set -ex -o pipefail # ------------------------
---------- # Prepare the tmp and backup folders # ---------------------------------- [ -d /var/lib/one//datastores/0/4099/tmp ] 
&& rm -rf /var/lib/one//datastores/0/4099/tmp [ -d /var/lib/one//datastores/0/4099/backup ] && rm -rf 
/var/lib/one//datastores/0/4099/backup mkdir -p /var/lib/one//datastores/0/4099/tmp mkdir -p 
/var/lib/one//datastores/0/4099/backup echo ...

 -------------------------------------- # Create backup live # -------------------------------------- 
/var/tmp/one/tm/lib/backup_qcow2.rb -l -d "0:" -x /var/lib/one//datastores/0/4099/backup/vm.xml -p 
/var/lib/one//datastores/0/4099 Error: Error executing 'virsh --connect qemu:///system backup-begin --reuse-external --
backupxml /var/lib/one//datastores/0/4099/tmp/backup.xml --checkpointxml 
/var/lib/one//datastores/0/4099/tmp/checkpoint.xml 5f9178c4-506b-409d-9747-46d828916ea0': error: internal error: unable to 
execute QEMU command 'nbd-server-start': Failed to bind socket to /var/lib/one//datastores/0/4099/backup.socket: Permission 
denied Error preparing disk files: Error executing 'virsh --connect qemu:///system backup-begin --reuse-external --backupxml 
/var/lib/one//datastores/0/4099/tmp/backup.xml --checkpointxml /var/lib/one//datastores/0/4099/tmp/checkpoint.xml 
5f9178c4-506b-409d-9747-46d828916ea0': error: internal error: unable to execute QEMU command 'nbd-server-start': Failed to 
bind socket to /var/lib/one//datastores/0/4099/backup.socket: Permission denied Failed to add the host to the list of known 
hosts (/var/lib/one/.ssh/known_hosts). + '[' -d /var/lib/one//datastores/0/4099/tmp ']' + '[' -d 
/var/lib/one//datastores/0/4099/backup ']' + mkdir -p /var/lib/one//datastores/0/4099/tmp + mkdir -p 
/var/lib/one//datastores/0/4099/backup + echo  ...

.. /var/tmp/one/tm/lib/backup_qcow2.rb -l -d 0: -x /var/lib/one//datastores/0/4099/backup/vm.xml -p 
/var/lib/one//datastores/0/4099

```
In the auth.log on the backup server, I do not see any connection attempts.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment]
Hi @nookeist 

Check what the error says: 

```
[...] Permission denied Failed to add the host to the list of known hosts (/var/lib/one/.ssh/known_hosts) [...]
```

Make sure that your orchestrator (frontend) and host can access SSH passwordless to the RSYNC remote host, using oneadmin user.

Also, remove this VM from the backupjob and try to configure the VM Single Backup, this will let you know if there are any errors with the rsync backup datastore driver on `v6.8.0` base code.

**Comment by nookeist** [comment]
> Hi @nookeist
> 
> Check what the error says:
> 
> ```
> [...] Permission denied Failed to add the host to the list of known hosts (/var/lib/one/.ssh/known_hosts) [...]
> ```
> 
> Make sure that your orchestrator (frontend) and host can access SSH passwordless to the RSYNC remote host, using oneadmin user.
> 
> Also, remove this VM from the backupjob and try to configure the **Single VM Backup**, this will let you know if there are any error with the **rsync backup datastore** driver on `v6.8.0` base code.

If i start backup from VM menu everything works fine

**Comment by Franco-Sparrow** [comment]
> If i start backup from VM menu everything works fine

Thats strange. I see is failing in the `prebackup_live`.

BTW, if the VM belongs to a backupjob, the Single VM Backup wont work, until you remove the VM from the backupjob. Try this:

- Remove the VM from the backupjob.
- Execute a reset backup, using the Single VM Backup.
- Move the VM again to the backupjob.
- Execute the backupjob again.

This is because backjobs doesnt have a reset backup, and this is the only way I have found to reset the chain of incremental backups, on a given VM that belongs to a backupjob.

**Comment by nookeist** [comment]
> > If i start backup from VM menu everything works fine
> 
> Thats strange. I see is failing in the `prebackup_live`.
> 
> BTW, if the VM belongs to a backupjob, the Single VM Backup wont work, until you remove the VM from the backupjob. Try this:
> 
> * Remove the VM from the backupjob.
> * Execute a reset backup, using the Single VM Backup.
> * Move the VM back to the backupjob.
> * Execute the backupjob again.
> 
> This is because backjobs doesnt have a reset backup, and this is the only way I have found to reset the chain of incremental backups, on a given VM that belongs to a backupjob.

I have do so, and after that when start backup job - nothing happens. only last backup time changes

**Comment by nookeist** [comment]
> > If i start backup from VM menu everything works fine
> 
> Thats strange. I see is failing in the `prebackup_live`.
> 
> BTW, if the VM belongs to a backupjob, the Single VM Backup wont work, until you remove the VM from the backupjob. Try this:
> 
> * Remove the VM from the backupjob.
> * Execute a reset backup, using the Single VM Backup.
> * Move the VM back to the backupjob.
> * Execute the backupjob again.
> 
> This is because backjobs doesnt have a reset backup, and this is the only way I have found to reset the chain of incremental backups, on a given VM that belongs to a backupjob.

I have do so, and first backup of increment job was full, then second gave me fail as in op post

**Comment by Franco-Sparrow** [comment]
If you execute a reset backup on the Single VM Backup and you move the VM back to the Backupjob and Start it, it will realize that this VM already have an `INC0` (first backup on the chain of incremental backups) and will create a new increment `INC1`. In your case is not working the increments on the backupjob, which is strange because it use same code for prebackup_live (where is failing) as in the Single VM backups.

If this is `6.8.0`, there are maintenance patchs (up to `v6.8.3`) that improve the backupjobs utility. If you are using CE repos, I would suggest you to upgrade to `v6.10.0` where this works perfectly.

**Comment by nookeist** [comment]
> If you execute a reset backup on the Single VM Backup and you move the VM back to the Backupjob and Start it, it will take in count that this VM already have an `INC0` (first backup on the chain of incremental backups) and will create a new increment `INC1`. In your case is not working the increments on the backupjob, which is strange because it use same code for prebackup_live (where is failing) as in the Single VM backups.
> 
> If this is `6.8.0`, there are maintenance patchs (up to `v6.8.3`) that improve the backupjobs utility. If you are using CE repos, I would suggest you to upgrade to `v6.10.0` where this works perfectly.

I have 6.8.0, yea i think you right and update  is required

**Comment by rdziwinski** [comment]
Hi
I have 6.10 and the same problem.
I made full backup - succes. I want to make incremental backup and get the same error. I checked ssh connectivity via oneadmin user and all good. But i don't think it's problem with it. I see in DMESG:

`[Thu Nov 28 14:40:36 2024] audit: type=1400 audit(1732801250.218:3956): apparmor="DENIED" operation="mknod" profile="libvirt-62df2098-0c8b-4c7a-90fa-48db7f8d21a1" name="/var/lib/one/datastores/167/1504/backup.socket" pid=3407205 comm="qemu-kvm-one" requested_mask="c" denied_mask="c" fsuid=0 ouid=0`

It's corresponding with apparmor, i'm still in investigation.

**Comment by nookeist** [comment]
@rdziwinski, you provided me with the right direction in solving the problem. The following actions resolved it for me:

Please add the following line to /etc/apparmor.d/abstractions/libvirt-qemu:

/var/lib/one/datastores/*/*/backup.socket rw,

Then, restart AppArmor with:

systemctl restart apparmor

Thank you for your help!
