### ISSUE TITLE
 Invalid 'Date' entry in Release file

### ISSUE THREAD

**Issue by tanaseav** [OpenNebula/one#6776]
**Description**
I have 2 fresh ubuntu 24 server instalation and i get an error while "apt update"
"W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/downloads.opennebula.io_repo_6.10_Ubuntu_24.04_dists_stable_Release"
 
**To Reproduce**
1. install Ubuntu 24.04.1 LTS
2. add opennebula repo to sources
3. run apt update and you get the above error

**Expected behavior**
update should work

**Details**
 - Affected Component: instalation
 - Hypervisor: NA
 - Version: 6.10 stable release
![ubuntu-bug](https://github.com/user-attachments/assets/f21cde3a-f845-4190-934a-1df96bcf121d)

**Additional context**
The OpenNebula repo does not seem to respect Ubuntu 24 requirements.
https://wiki.debian.org/DebianRepository/Format?action=show&redirect=RepositoryFormat#Date.2C_Valid-Until
They only want +0000 and not +0200

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by xorel** [comment]
We re-indexed the repository.
Thank you for reporting.
