### ISSUE TITLE
Environment variable http_proxy may make the scheduler not work

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#678]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2301, https://dev.opennebula.org/issues/2301
Original Date: 2013-09-05

---

A solution may be
1. The scheduler clears the http_proxy variable (in the C++ code)
1. If http_proxy is needed it can be passed as a command line option

**Comment by paczerny** [comment]
http_proxy is specified in sched.conf, overrides http_proxy environment variable
PRs for merge (only to master):
* src: https://github.com/OpenNebula/one-ee/pull/584
* doc: https://github.com/OpenNebula/docs/pull/1395
