### ISSUE TITLE
Allow resize of QCOW2 disks with snapshots for 6.4.*

### ISSUE THREAD

**Issue by dgarcia18** [OpenNebula/one#6787]
**Description**
Backporting this functionality (https://github.com/OpenNebula/one/issues/6292) to OpenNebula 6.4.*

**Use case**
Client request

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
done merged to 6.4.7
