### ISSUE TITLE
Possible negative value error

### ISSUE THREAD

**Issue by Bbulatov** [OpenNebula/one#6801]
Hello!
I thought that this was not a security vulnerability, so I am writing here.
During the static analysis was found possible mistake:
1) Variable 'sd', which might receive a negative value at svncterm_server.c:1984 by calling function 'socket', is used without checking at svncterm_server.c:1993 by calling function 'setsockopt'.
![изображение](https://github.com/user-attachments/assets/0cdc8893-9381-498f-9acd-8f58901c2f14)
Could you please clarify if there could be a situation where the value is sd = -1? Does this need fixing?
2) The handle 'sd' is created at svncterm_server.c:1984 by calling function 'socket' and lost at svncterm_server.c:2018.
Do I need to add a socket closing here?

**Comment by paczerny** [comment]
1) Yes, ideally we should test for `sd < 0`, to have a clearly readable code. In this case there is no harm, the next call `setsockopt` with `sd = -1` will fail anyway and the resources will be freed.

2) No, you can't close the socket. It's stored as an index of `client_fds` and will be closed in `del_cmd` (line 1947)

Duplicate #6424
