### ISSUE TITLE
make VM listing scale better

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#682]
---

Author Name: **Felix Schüren** (Felix Schüren)
Original Redmine Issue: 2338, https://dev.opennebula.org/issues/2338
Original Date: 2013-09-26

---

I have a need to efficiently receive specific subsets of the currently existing VMs. For example:
a) list of all VMs running on a specific hypervisor
b) list of all VMs attached to a specific virtual network

The current implementation becomes very slow & inefficient at large numbers of virtual machines, having to transfer essentially the full list of all VMs for most queries. I would recommend some additional query options that efficiently return just the wanted data, in essence changing the internal SQL queries to be more specific dependent on API query options.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2014-01-22T14:14:41Z

---

It's not exactly what you've asked for but some changes are made to the codebase that will become 4.6 that will alleviate your problem:

* Big pools can be sent paginated and are parsed using SAX. This makes the parsing faster and take less memory
* It's able to use Ox library for XML parsing. This library is much faster parsing xmlrpc and its payload (the pool).

Using a newer ruby version greatly increases the speed of the tools. 2.1.0 runs much faster that 1.8.7

http://dev.opennebula.org/issues/2371

**Comment by rsmontero** [comment]
Already implemented in current versions
