### ISSUE TITLE
Change from LXD to Incus

### ISSUE THREAD

**Issue by rudiservo** [OpenNebula/one#6837]
**Description**
Change the container stack to Incus project.

**Use case**
Seems there was a bit of an issue with Cannonical and LXD maintainer, so he created Incus.

**Interface Changes**
Just change `lxd` commands to `incus`, it does not require any API changes so it should be a drop in replacement.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
LXD support was dropped in support of the simpler LXC, which is the actual container runtime. As LXD grew in ambition, it became more than a REST API to manager LXC to the point where it started to have too much duplicated functionality and actually managing KVM as well.

**Comment by rudiservo** [comment]
Ok I didn't know LXD was dropped.
Yes Incus is a fork of LXD, and it kind of an API manager to LXC and KVM.
It's not a bad one TBH, but if it it duplicating functionality I guess the choice would be OpenNebula being a GUI for Incus/LXD or being it's own thing.
Thanks.
