### ISSUE TITLE
Sunstone: disable buttons for actions the user can't perform

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#686]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2369, https://dev.opennebula.org/issues/2369
Original Date: 2013-10-10

---

Request made during the OpenNebulaConf

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2013-12-10T13:17:47Z

---

Hello,

I think this could be generalized by managing views more dynamically.

Today, I needed to pass the *@vnets-tabs: actions: Network.create_dialog@* to *@True@* in *@user.yaml@* view after adding the required @ACL@.

Regards.

**Comment by rsmontero** [comment]
done
