### ISSUE TITLE
Allow to filter CLI output by hidden columns

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#687]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2372, https://dev.opennebula.org/issues/2372
Original Date: 2013-10-10

---

For example, this command fails:
```
$ onevm list --filter HOST=host01 --list ID,NAME
    ID NAME           
Column 'HOST' not found

```

Request made during the OpenNebulaConf

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-28T22:04:18Z

---

This issue would be for improving CLI filter options, it should consider issue #2684

**Comment by roumano** [comment]
Issue still exist on the OpenNebula 5.6.1 version

**Comment by al3xhh** [comment]
PRs to merge in master:

- code: https://github.com/OpenNebula/one/pull/4748
- docs: https://github.com/OpenNebula/docs/pull/1123
