### ISSUE TITLE
Add CLI list options to allow better parsing

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#688]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2373, https://dev.opennebula.org/issues/2373
Original Date: 2013-10-10

---

Namely:
* Skip headers
* Set field delimiter
* Do not crop some columns to the fixed column length (ID,BRIDGE,...)
* Extend selected columns to fill the remaining space (NAME?)

Request made during the OpenNebulaConf

**Comment by al3xhh** [comment]
PRs to merge in master:

code: https://github.com/OpenNebula/one/pull/3311
docs: https://github.com/OpenNebula/docs/pull/613
