### ISSUE TITLE
Hooks for OneFlow Services

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#691]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2378, https://dev.opennebula.org/issues/2378
Original Date: 2013-10-10

---

Request made during the OpenNebulaConf

**Comment by tinova** [comment]
this can be included in the 5.10 hook revamp

**Comment by al3xhh** [comment]
With the new hook systems you can use API hooks, these apply to all calls made in OpenNebula, so you can create hooks for **document** API calls.

Closing this as this functionality has been already implemented.

**Comment by al3xhh** [comment]
Reopen it to support state hooks for services.

**Comment by tinova** [comment]
closing, duplicated in #6346
