### ISSUE TITLE
Ability to lock VM from accidental actions

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#694]
---

Author Name: **Andrey Perminov** (Andrey Perminov)
Original Redmine Issue: 2412, https://dev.opennebula.org/issues/2412
Original Date: 2013-10-25

---

It would be nice to have an ability to lock a VM to prevent it from accidential deletion / alternation.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-20T15:49:41Z

---

Thanks for the suggestion!

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-21T15:20:32Z

---

Also, as suggested by Ricardo Duarte in the list:

"One feature I would like to see would be a "recycle bin".
Instead of deleting instances and their disks immediately after they terminate you could delay the actual operation to a different time, and allow the user to recover the instance."

Although the implementation is different the goal is the same, do not accidentally lose VMs.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Andrey Perminov** (Andrey Perminov)
Original Date: 2014-01-21T16:58:00Z

---

I think that locking should lock it from all operations, may be with exception to boot, reboot, poweroff. No alternation, no shutdown, no redeploy.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-22T11:15:27Z

---

Also adding to this request #2668:

>>No confirmation was asked when VM snapshots is deleted/reverted.

If we lock the VM, also the snapshots would be deleted.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-22T15:59:10Z

---

Seems this is being popular lately. A similar request from #2670:

>> We, FermiCloud have been using onevm delete in a different way
>> by asking for user's confirmation
>> since one user accidentally deleted a VM that was not meant to be deleted.
>> I thought this could be useful to others too.

Adding the issue as related to this one, to keep the discussion here.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Sledge Sulaweyo** (Sledge Sulaweyo)
Original Date: 2017-08-21T05:39:18Z

---

Just wanted to bump this request as i managed to kill an instance accidentally in my environment recently and would love to have an option to make sure this does not happen again. (Obviously my fault but a safety net would be great)

**Comment by rsmontero** [comment]
This could be implemented to also address #649

**Comment by rsmontero** [comment]
Implemented finally for 5.6
