### ISSUE TITLE
Compatibility with heartbeat 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#696]
---

Author Name: **novid Agha Hasani** (novid Agha Hasani)
Original Redmine Issue: 2429, https://dev.opennebula.org/issues/2429
Original Date: 2013-11-05

---

heartbeat for detect problem checks exit code, so when openebula will fail, must return exit 3 instead 0 

we must change init script opennbula 

1. /etc/init.d/opennebula

changing 

  status)
       status_of_proc "oned" "$NAME" && exit 0 || exit $?
       ;;

to 

 status)
        # NEEDS to be heartbeat friendly...
        # so: put some "OK" in the output.
        process=$(ps -ef | grep "/usr/bin/oned" | grep -v "grep" | wc -l)
        if [ "$process" -gt 0 ]; then
            echo "opennebula loaded OK"
           # drbd_pretty_status $PROC_DRBD 2>/dev/null
            exit 0
        else
            echo >&2 "opennebula not loaded"
            exit 3
        fi
      # status_of_proc "oned" "$NAME" && exit 0 || exit $?
       ;;

2. /etc/init.d/opennebula-sunstone

        # NEEDS to be heartbeat friendly...
        # so: put some "OK" in the output.
        process=$(ps -ef | grep "/usr/lib/one/sunstone/sunstone-server.rb" | grep -v "grep" | wc -l)
        if [ "$process" -gt 0 ]; then
            echo "sunstone loaded OK"
            drbd_pretty_status $PROC_DRBD 2>/dev/null
            exit 0
        else
            echo >&2 "sunstone not loaded"
            exit 3
        fi
       ;;

3.  /etc/init.d/appmarket

I am writing new init script for 'appmarket' too that attach it 

file source related from github is : https://github.com/OpenNebula/one/tree/1a70cffab08276a6019fb876b3ce5f20875d1256/share/pkgs/Ubuntu

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2013-11-05T18:21:59Z

---

Thanks!

We will take a look a these but seem OK.

I am adding a related ticket.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **novid Agha Hasani** (novid Agha Hasani)
Original Date: 2013-11-05T18:44:00Z

---

Javi Fontan wrote:
> Thanks!
> 
> We will take a look a these but seem OK.
> 
> I am adding a related ticket.

thx man

you can safely remove *drbd_pretty_status $PROC_DRBD 2>/dev/null* too :)

I used part of the init drbd script and  mistake paste it here !

**Comment by vholer** [comment]
Since the services are managed by the systemd these days, the systemd can detect itself crash of the service and do the automatic recovery. Also at least for the `oned`, we have an integration with systemd which is reporting back when the oned is fully ready-to-use.

https://github.com/OpenNebula/one/blob/ec43d184d13955700cb7a4a8073fa721abc62be6/src/nebula/Nebula.cc#L1150-L1154

Closing the issue.
