### ISSUE TITLE
Validate filesystem type (FS type) when creating datablock image in sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#698]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 2458, https://dev.opennebula.org/issues/2458
Original Date: 2013-11-13

---

At the moment the FS type in the "Create Image" dialog is "free form". Tooltip hints indicate you can use any fs mkfs command understands. The user however does not know which fs types are supported on $system. If a non-existent fs is chosen for $system (reiserfs for example on stock ubuntu saucy) the response is "image created" ... while actually it's not and the datablock is in error state. This can be prevented by checking the capabilities of mkfs command one oned server. Or by making it a configuration option: what file system types are supported. Ideally the wizard validates the option chosen or instead of free from make it a pull down menu from wich a fs can be chosen".

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2013-11-14T09:31:39Z

---

This is more a feature than a bug, thanks for your feedback!

**Comment by abelCoronado93** [comment]
Not apply anymore
