### ISSUE TITLE
deleting image in locked state leaves current operation in progress and files not cleaned

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#702]
---

Author Name: **Rolandas Naujikas** (Rolandas Naujikas)
Original Redmine Issue: 2502, https://dev.opennebula.org/issues/2502
Original Date: 2013-11-27

---

We can delete image in locked state, when some operation, for e.g. clone is still in progress.
The results - operation is still running and destination file left in datastore.
Solutions:
1) don't allow delete image in locked state - dangerious if image is stuck in locked state.
2) cancel datastore operation and after do cleanup.
What would be if long running image operation is interrupted by reboot or crash ?

**Comment by rsmontero** [comment]
This is done, as suggested, to let the admins delete images stuck while copying.  Possible solutions, needs to be address driver-wise (e.g. check after cloning the image that it actually exists). We'll reopen this issue if the current behavior turns out to be problematic
