### ISSUE TITLE
Create an opennebula-node-xen package

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#704]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 2508, https://dev.opennebula.org/issues/2508
Original Date: 2013-11-27

---

To configure a xen node from a package

**Comment by vholer** [comment]
XEN is supported only as an add-on, not part of the official OpenNebula code. There is nothing to package now. Closing.
