### ISSUE TITLE
Interactive feedback for Sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#708]
---

Author Name: **Gareth Bult** (Gareth Bult)
Original Redmine Issue: 2555, https://dev.opennebula.org/issues/2555
Original Date: 2013-12-11

---

Daniel asked me to post this :

"What I'm thinking is that if you hooked every database update, each action could be filtered and passed
back to the client via websockets. This would not be difficult to implement and would keep the display
completely in sync with the system."

At the moment the interface it to a degree confusing because unless you sit with your finger on the refresh button, you don't know whether your actions have been successful or not. Points to note here, firstly repeatedly clicking on the refresh button does nothing for the efficiency of the system as each click consumes resources, and secondly the user had to be focussed on the task, rather than letting the computer get on with it and watching from afar while doing something else.

--

I worked on a project (using ExtJS as it happens - gratuitous screenshot attached for your amusement) a couple of years ago with a completely interactive monitoring system, drag and drop panels etc, all coupled to a live Mongo back-end. Having something that feels interactive and gives immediate feedback on results as they happen makes a huge difference to a user's perception of the software they're using.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-02-04T14:38:57Z

---

This is very nice indeed, it won't fit in the current time frame for 4.6, so moving it to backlog.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Gareth Bult** (Gareth Bult)
Original Date: 2014-02-04T16:36:21Z

---

Ruben S. Montero wrote:
> This is very nice indeed, it won't fit in the current time frame for 4.6, so moving it to backlog.

Well, I'm currently unemployed if you're looking for developers .. ;)

**Comment by tinova** [comment]
considered in FireEdge Snstone
