### ISSUE TITLE
Improve log messages from drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#710]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2566, https://dev.opennebula.org/issues/2566
Original Date: 2013-12-13

---

Probably as discussed in the mailing list

http://lists.opennebula.org/pipermail/users-opennebula.org/2013-November/025175.html

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2014-01-12T17:21:31Z

---

Hello,

I think this issue could be retitle something like “improve log messages from drivers”.

As explained in the thread:

* action messages should be logged when *@debug_level=INFO@*
* commands to execute should be logged when *@debug_level=DEBUG@*

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-12T22:22:31Z

---

Agree!

**Comment by juanmont** [comment]
Should be ok in current version, reopen if needed
