### ISSUE TITLE
Snapshot-delete action / retention policy in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#716]
---

Author Name: **Kiran Ranjane** (Kiran Ranjane)
Original Redmine Issue: 2634, https://dev.opennebula.org/issues/2634
Original Date: 2014-01-13

---

As we have snapshot-create action in one, so we should also have snapshot-delete action in schedule action tab in Sunstone.
It is really frustrating when we have to delete the snapshots one by one on each vm.
The snapshot-delete action should have a retention policy when defined for example: "1 week" then it should keep all the snapshots that are within 1 week and rest should be deleted.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-17T09:03:36Z

---

Moving temporarily it to Request track

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-02-04T14:37:34Z

---

This requires some support from oned. Moving it to backlog. THANKS for your feedback

**Comment by rsmontero** [comment]
Closing as duplicate for #1548
