### ISSUE TITLE
Cron style scheduling actions

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#717]
---

Author Name: **Kiran Ranjane** (Kiran Ranjane)
Original Redmine Issue: 2635, https://dev.opennebula.org/issues/2635
Original Date: 2014-01-13

---

Scheduling action should be in cron style format so that we can submit repeative tasks, For example I want to add action of snapshot-create for every hour for a particular vm then I have to add action for every hour, (Imagine if I have 20 VMs) Howerver if cron style format is used then I can do this in just submitting one action of snapshot-create per Virtual Machine.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-17T08:52:17Z

---

Moving temporarily it to Request track

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlos Martín** (Carlos Martín)
Original Date: 2014-01-17T16:04:27Z

---

Definitely useful, that's how it works for the oneflow auto scaling. We'll have to see how it fits with the current scheduler code.

**Comment by tinova** [comment]
Already implemented in 5.8
