### ISSUE TITLE
VMs, CPU and MEMORY of STOPPED VMs are not deduced from users monitoring

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#720]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 2646, https://dev.opennebula.org/issues/2646
Original Date: 2014-01-16

---

Hello,

Trying to look at “Who is taking all that resources?” of our little cluster, I saw the report per user of VMs/CPU and MEMORY:

```
oneadmin@nebula:~$ oneuser list
  ID NAME            GROUP      AUTH           VMS            MEMORY         CPU
   0 oneadmin        oneadmin   core             -                 -           -
   1 serveradmin     oneadmin   server_c   0 /   0      0M /      0M   0.0 / 0.0
   2 user1           users      ldap       7 /   0    5.5G /      0M   0.7 / 0.0
[...]
```

The problem is that @user1@ has only 3 *@RUNNING@* VMs, with 512MB memory each, other are in *@STOPPED@* state.

I think this report could make the difference between VMs with allocated resources and VMs without.

Maybe something like:
```
oneadmin@nebula:~$ oneuser list
  ID NAME            GROUP      AUTH               VMS                   MEMORY         CPU
   0 oneadmin        oneadmin   core                 -                        -                 -
   1 serveradmin     oneadmin   server_c   0     /   0      0M        /      0M   0.0       / 0.0
   2 user1           users      ldap       3 (7) /   0    1.5G (5.5G) /      0M   0.2 (0.7) / 0.0
[...]
```

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlos Martín** (Carlos Martín)
Original Date: 2014-01-17T16:00:26Z

---

It makes sense, maybe a VM in stopped or undeployed states should not be accounted for the VM quotas (nº of vms, cpu, mem).

**Comment by dann1** [comment]
There are real CPU and Memory values monitored by the IM drivers
