### ISSUE TITLE
Add libvirt options at deployment time:

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#726]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2658, https://dev.opennebula.org/issues/2658
Original Date: 2014-01-19

---

Investigate the need to add "sharable" to live-migrate. Also add configuration variables to set other options. More information here:

http://lists.opennebula.org/pipermail/dev-opennebula.org/2014-January/000092.html

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Javi Fontan** (Javi Fontan)
Original Date: 2014-03-03T13:55:49Z

---

Added a tip in the documentation to use --unsafe parameter for migration in case shareable is needed.

https://github.com/OpenNebula/docs/blob/master/source/administration/virtualization/kvmg.rst#considerations--limitations

**Comment by rsmontero** [comment]
Duplicate #972
