### ISSUE TITLE
OpenId for Sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#729]
---

Author Name: **VIVOSS company** (VIVOSS company)
Original Redmine Issue: 2675, https://dev.opennebula.org/issues/2675
Original Date: 2014-01-24

---

This patch adds OpenID feature for OpenNebula 4.4.0 Sunstone server.
1. Gem requirements
 - omniauth
 - omniauth-openid
 - ruby-openid

2. Third party software
Jquery-ui is required for OpenID login page.
It should be placed into sunstone/public/vendor/4.0/jquery-ui-1.10.3
Visual theme is smoothness. If any other version or theme is to be used,
corresponding changes should be made to the login.erb

3. Installations
This patch adds some new files, but OpenNebula setup is not modified.
So these files have to be copied to due places manually.

sunstone/
.
├── etc
│   └── sunstone-server.conf
├── public
│   ├── js
│   │   └── openid.js
│   └── vendor
│       └── 4.0
│           └── jquery-ui-1.10.3
├── sunstone-openid.rb
└── views
    ├── _login_standard_new.erb
    ├── _openid_check.erb
    └── _openid.erb

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-01-30T20:37:59Z

---

We have also to devise a general method to easily add new extensions, and/or contribute this as an addon.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Dehennin** (Daniel Dehennin)
Original Date: 2014-07-19T15:08:11Z

---

Ruben S. Montero wrote:
> We have also to devise a general method to easily add new extensions, and/or contribute this as an addon.

+1 for pluggable authentication.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **VIVOSS company** (VIVOSS company)
Original Date: 2014-07-21T06:16:38Z

---

Daniel Dehennin wrote:
> +1 for pluggable authentication.

Omniauth that used in the attached patch already uses authentication plugins. But some specific changes for GUI, plugin activation and query processing are also required.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-21T14:47:36Z

---

This will be considered for the next release, after 4.8

**Comment by tinova** [comment]
implemented in https://github.com/OpenNebula/one/issues/3591
