### ISSUE TITLE
Add documentation about env variables (ONE_XMLRPC, etc...) to the cli guide

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#735]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 2730, https://dev.opennebula.org/issues/2730
Original Date: 2014-02-14

---

ONE_XMLRPC and other env variables are explained in http://docs.opennebula.org/4.4/administration/users_and_groups/manage_users.html, however it would be interesting to add them to the CLI guide as well (or add a link) http://docs.opennebula.org/4.4/user/references/cli.html

Also, it would be interesting to recommend adding them to .bash_profile (as it gets called once) and not to .bashrc (as it gets called once per bash instance)

**Comment by rsmontero** [comment]
http://docs.opennebula.org/5.8/operation/users_groups_management/manage_users.html?highlight=one_auth#shell-environment
