### ISSUE TITLE
Make noVNC proxy work in a federation to access VMs in any zones

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#738]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 2757, https://dev.opennebula.org/issues/2757
Original Date: 2014-02-26

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EDUARDO IGNACIO SERRANO** (EDUARDO IGNACIO SERRANO)
Original Date: 2016-01-25T22:50:12Z

---

Good morning
How to solve this problem.
I do not understand how to solve "We will work Sunstone Directly With The workaround for each Zone as"
Could you explain me please!
-Federation Master-> Slave
Failed to connect to VNC server (code: 1006)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-12-19T18:42:43Z

---

To address this issue we may integrate the following patches:

* https://github.com/rkeene/one/commit/2d0a7f249f88c47c29ef4fa0ddad0f111534313c

* https://github.com/rkeene/one/commit/270875c5e26ae41972179df1f7691e1454fdf947

The basic idea is to get the IP:Port from an external script that forwards it to the target zone VNC proxy server. This can be done by setting up an SSH tunnel. We can integrate the changes and provide a template script to let people forward traffic using any VPN to the zones. An ssh tunnel based will be provided as an example (http://www.rkeene.org/viewer/tmp/zone-vnc-proxy.sh.htm)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Roy Keene** (Roy Keene)
Original Date: 2017-04-23T13:53:33Z

---

One additional change that I've found useful is that supplying the VM's name in addition to the hypervisor name, port, and zone ID to the script.  This can be done by adding it as a 4th argument, e.g:

```
vnc_proxy_info = `opennebula-zones-vnc-proxy '#{host}' '#{vnc_port}' '#{vm_zone_id}' 'one-#{vm_resource['ID']}'`

```

This lets the script make other determinations -- such as how to interpret "vnc_port", which another patch I'm using can be "auto" if the hypervisor is managing the VNC port rather than OpenNebula.

**Comment by tinova** [comment]
noVNC deprecated, closing in favor of #5763
