### ISSUE TITLE
Multiple network interfaces support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#741]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 2768, https://dev.opennebula.org/issues/2768
Original Date: 2014-02-28

---

From the list (Stefan Kooman stefan@bit.nl)

"If a VM has more than one network interface it does not show up in
sunstone network tab / oneacct as a seperate network interface.[...]
 I would like to be able to differtiate between
interfaces for monitoring and billing purposes. One interface might be a
"internet uplink" while another one might be "internal traffic" or
"storage traffic (nfs, iSCSI)" each with different cost per MB(ps)
traffic."

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-03-04T21:58:22Z

---

This may require, update accounting schema as well as monitoring probes

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2016-01-07T15:04:49Z

---

At at technical level this seems to be related to #2921 as it requires similar monitoring info (probes) / logic as DISK IO / Throughput monitoring does.

**Comment by tinova** [comment]
closing a multi NIC is present in sunstone. please comment if there is any missing functionality
