### ISSUE TITLE
Translate dataTable texts using oLanguate option

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#746]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 2815, https://dev.opennebula.org/issues/2815
Original Date: 2014-03-28

---

The dataTable oLanguate option is only used in the clusters tab, and it is failing with the message:

Uncaught TypeError: Cannot read property 'sSortDescending' of undefined

It will be removed for 4.6, but we should consider using it properly for all dataTables in future versions.

**Comment by rsmontero** [comment]
Already support translations
