### ISSUE TITLE
Sunstone template update does not select images without User Name

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#754]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 2867, https://dev.opennebula.org/issues/2867
Original Date: 2014-05-05

---

When the image name in a VM template is specified but not its owner it can not find the image in the list. For oned an empty owner means the same user. Sunstone should search for the image in the user's images.

**Comment by rsmontero** [comment]
Should work now
