### ISSUE TITLE
Make 802.1q tagged bridge only if VLAN identifier is greater than 1

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#760]
---

Author Name: **Vladislav Gorbunov** (Vladislav Gorbunov)
Original Redmine Issue: 2919, https://dev.opennebula.org/issues/2919
Original Date: 2014-05-14

---

On bridges, VLAN 1 (the default VLAN ID) is often reserved for a management VLAN. The patch make bridge with untagged network if user set VLAN_ID parameter to 0 or 1. This comply IEEE 802.1Q.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-05-16T11:00:19Z

---

Makes sense, scheduling it for 4.8. THANKS!

**Comment by rsmontero** [comment]
Fixed
