### ISSUE TITLE
Ability to filter in sunstone on resource usage (CPU, RAM, NETWORK, DISK)

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#761]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 2925, https://dev.opennebula.org/issues/2925
Original Date: 2014-05-16

---

Besides the current possibility to filter on "ID, Owner, Group, Name, Status, Host, IP" it would be nice to be able to filter on (REAL/UTILIZED) Resources as well (CPU, RAM, NETWORK, DISK).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Molina** (Daniel Molina)
Original Date: 2015-01-21T11:19:54Z

---

Now a hidden columns has been included in the vms datatable, therefore you can use the search input to filter by any attr of the vm. For example, you can define the following expression CPU="[0-4]?\d" (lower than 50), the search input now supports repexps)

**Comment by rsmontero** [comment]
Should be done alreay, as explained
