### ISSUE TITLE
Use VM instance name for CURRENT_VMS variable in SCHED_REQUIREMENTS

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#767]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 2962, https://dev.opennebula.org/issues/2962
Original Date: 2014-06-04

---

Hi,

We would like to place VM in a Host where other VMs are not running. This is the purpose of CURRENT_VMS special variable but it seems we have to use VMIDs. As the ID is changing on each instantiation, it is not really helpful for us.

It would be really useful to be able to use VM name with CURRENT_VMS or maybe with a new variable.
As the VM name is suffixed with VMID, the use of wildcards to match name is needed.

Thanks

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-06-24T18:41:42Z

---

It makes sense, this is related to #2347. Moving it to backlog

**Comment by tinova** [comment]
Is this covered by the VM Groups functionality? If so, please let us know to close this issue
