### ISSUE TITLE
Allow group renaming

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#769]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 2981, https://dev.opennebula.org/issues/2981
Original Date: 2014-06-13

---

Title says it all

**Comment by joergludwig** [comment]
You can use this command, but I do not know about the side effects:

```
onedb update-body group -i 100
```

**Comment by rsmontero** [comment]
There should be some cross-reference names not updated, showing he previous group name
