### ISSUE TITLE
Enable Hybrid drivers to pass along CONTEXT data

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#771]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 2986, https://dev.opennebula.org/issues/2986
Original Date: 2014-06-16

---

Hybrid VM templates define two 'contexts':

 -- For local deployments

CONTEXT = [
  ATTR1   = "VALUE1",
  ATTR2   = "VALUE2"
]     
 
 -- For cloud deployments

PUBLIC_CLOUD= [
   USERDATA=<Base64Blob>,
   ...
]

Ideally, the same info in CONTEXT should be used for USER DATA

**Comment by jmelis** [comment]
The idea is to dynamically generate the USERDATA contents based on the attributes defined in CONTEXT

**Comment by tinova** [comment]
hybrid drivers are no longer supported
