### ISSUE TITLE
Multi (domain) LDAP authentication support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#777]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 3015, https://dev.opennebula.org/issues/3015
Original Date: 2014-06-30

---

In order to utilize the LDAP server of an external organisation for authenticating users "multi domain" support is needed. This seems escpecially useful for virtual Data Center users. Instead of having to create local accounts (local ldap or opennebula built-in) the authentication could be relayed to the organisation itself. The organisation has full control over password policies, enabled/disabled accounts etc. A possible way of implementing this in OpenNebula (with only minor adjustments and backwards compatibility) User names should have a "@domain.tld" appended if they want to make use of the (external) LDAP of organisation $some.domain.tld. The "@domain.tld" part has to be split from the "user" part. In /etc/one/auth/ldap_auth there should be a "$some.domain.tld" section to be used for user "user@some.domain.tld". So instead of a "ordered" list (array) a lookup should be done if "some.domain.tld" exists in the array. If so -> use that server, if not, default to local ldap.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-03T17:49:48Z

---

Make sense, moving this to backlog with high priority to evaluate this after 4.8

**Comment by xorel** [comment]
This feature is already implemented. See LDAP auth [order vs regex](https://docs.opennebula.io/6.0/installation_and_configuration/authentication/ldap.html#multiple-ldap-servers-order-vs-regex-match)
