### ISSUE TITLE
OpenNebula should check the available space in the frontend before doing an undeploy

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#778]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 3020, https://dev.opennebula.org/issues/3020
Original Date: 2014-07-02

---

Undeploy copies the image to the frontend when the datastore is not shared. It should check that there is enough free space before doing it.

**Comment by rsmontero** [comment]
Already implemented in current versions
