### ISSUE TITLE
Build Optimizations

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#779]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 3022, https://dev.opennebula.org/issues/3022
Original Date: 2014-07-07

---

SConstruct files do not add @-O@ parameter to optimice code:

```
1. Compile flags
main_env.Append(CPPFLAGS=[
    "-g",
    "-Wall"
])

```

The flag can be added on build time setting @CFLAGS@ environment variable:

```
export CFLAGS=-O3

```

**Comment by vholer** [comment]
The idea of following changes in packaging is not just set the higher build-time optimizations, but more to
- build packages with **standard parameters proposed on each platform** and
- enable the features which **make the binaries more "secure"**.

## Current state

Right now, we depend

a) mainly on defaults of GCC on each target

b) just very simple CFLAGS, CXXFLAGS we set right before the build
https://github.com/OpenNebula/packages/blob/0a53c1e0d1401ff6a36fd2d61f36651278266bdd/sources/build_opennebula.sh#L14-L18

c) general defaults we set in SConstruct (`-g`, `-Wall`, `--std=c++11`)
https://github.com/OpenNebula/one/blob/7b03f719d69c171319d89e7378331d074eb585e5/SConstruct#L116-L124

Today, it's pretty standard to enable security features like PIE or stack protector (see https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc/). On some platforms, these things are already enabled in defaults of the GCC, on some it's necessary to enable them.

Following table shows how binaries are currently compiled on each platform:

| Feature                  | C7 | D9 | D10 | U1604 | U1804 | U1810 | U1904 |
|--------------------------|----|----|-----|-------|-------|-------|-------|
| PIE                      | N  | Y  | Y   | N     | Y     | Y     | Y     |
| Stack protector          | N  | N  | N   | Y     | Y     | Y     | Y     |
| Fortified source         | N  | N  | N   | Y     | Y     | Y     | Y     |
| Read-only relocations    | Y  | Y  | Y   | Y     | Y     | Y     | Y     |
| Immediate binding        | N  | N  | N   | N     | Y     | Y     | Y     |

The results above were gathered by tool `hardening-check` (https://wiki.debian.org/Hardening#Validation).

## Proposed state

The following PRs don't set any particular compiler / linker options, but allows to pass the options proposed by the distribution packages build tools. Moreover, they also request using hardening options everywhere (although some platforms use them by default).

As a result, the produced binaries have ALL features on ALL targets listed on the table above.

Note: related to `-O3` optimization requested originally, no platform builds packages with `-O3`, but just `-O2`. So, I'm not enforcing higher optimization levels.

PRs to merge into **master**:
- one: https://github.com/OpenNebula/one/pull/3707
- packages: https://github.com/OpenNebula/packages/pull/103
- development: https://github.com/OpenNebula/development/pull/719
- docs: https://github.com/OpenNebula/docs/pull/761

**Comment by vholer** [comment]
Example of single `gcc` invocation on CentOS 7

- before
```
g++ -o src/host/HostPool.o -c -DGITVERSION='"not known"' -fPIC -Wno-error=format-security -g -Wall -std=c++11 -DSQLITE_DB -DMYSQL_DB -DSYSTEMD -Iinclude -Isrc/parsers -I/builddir/build/BUILD/xmlrpc-c/install/include -I/usr/include/mysql -I/builddir/build/BUILD/xmlrpc-c/install/include -I/usr/include/libxml2 src/host/HostPool.cc
```

- after
```
g++ -o src/host/HostPool.o -c -DGITVERSION='"not known"' -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -Wall -std=c++11 -DSQLITE_DB -DMYSQL_DB -DSYSTEMD -Iinclude -Isrc/parsers -I/builddir/build/BUILD/xmlrpc-c/install/include -I/usr/include/mysql -I/builddir/build/BUILD/xmlrpc-c/install/include -I/usr/include/libxml2 src/host/HostPool.cc
```

(parameters are specified twice as they are set both in CXXFLAGS and CPPFLAGS)

**Comment by rsmontero** [comment]
Nice!!!!!!! :smiley:
