### ISSUE TITLE
Hugepage backed memory support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#783]
---

Author Name: **海涛 肖** (海涛 肖)
Original Redmine Issue: 3042, https://dev.opennebula.org/issues/3042
Original Date: 2014-07-15

---

The memory page size of your system influences the overhead of virtual to physical memory translations, increasing your memory page size would reduce this overhead. HugePages is a feature that makes it possible for the operating system support memory pages larger than the default 4KB, assuming HW support. Hugepage support can deliver a significant improvement in memory access throughput, especially in memory intensive and database workloads.

This feature enables libvirt configure virtual machines to use hugepage backed memory.

This feature can be used Intel DPDK vSwitch and NFV workloads.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-15T09:52:45Z

---

moving to backlog for the next release. This issue will expose the memory attributes to the guest as described here:

http://libvirt.org/formatdomain.html#elementsMemoryBacking

**Comment by rsmontero** [comment]
#3256 (Implemented as part of it)
