### ISSUE TITLE
Colorize on the Virtual Machine Display for each Machine

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#784]
---

Author Name: **Jose Angel Diaz Diaz** (Jose Angel Diaz Diaz)
Original Redmine Issue: 3046, https://dev.opennebula.org/issues/3046
Original Date: 2014-07-15

---

*This feature is implemented by labels*

Could be a good feature the posibility to colorize the Machines on the Virtual Machines section from SunStone.

On this way you could make groups based on the color for cluster machines o services.

We'll keep open to color the status of VMs

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-15T09:03:10Z

---

Very interesting in deed, moving it to backlog to consider its implementation in a future release

**Comment by rsmontero** [comment]
Implemented with label
