### ISSUE TITLE
new monitoring attributes

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#785]
---

Author Name: **Drazen Ferencic** (Drazen Ferencic)
Original Redmine Issue: 3059, https://dev.opennebula.org/issues/3059
Original Date: 2014-07-17

---

If you could monitor libvirt and qemu version on each host, you could put up a warning in VM template wizzard when selected feature is not available.

For example trim/discard support for Ceph RBD requires at least qemu 1.5 and libvirt 1.0.6, and IDE or SCSI driver (virtio doesn't support trim/discard for Ceph rbd).

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-17T19:14:24Z

---

The problem here is that VM template are created before the allocation phase, in this way it cannot be known before hand. On the other hand the probe can be added and used by the scheduler, i.e. you could add LIBVIRT = "1.0.6" in the requirements. 

Moving it to backlog to plan it after 4.8

**Comment by rsmontero** [comment]
It seems this is no longer need, we can reopen if this is useful
