### ISSUE TITLE
Add ability to modify disk target bus

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#786]
---

Author Name: **Matthew Richardson** (Matthew Richardson)
Original Redmine Issue: 3061, https://dev.opennebula.org/issues/3061
Original Date: 2014-07-17

---

ONE provides a TARGET option in the Disks section of a VM definition.  This results in libvirt XML:

<disk ...>
<target dev='[TARGET]'/>
...
</disk>

libvirt will automatically determine the bus type from the target name, i.e hd = ide, sd = scsi, vd = virtio etc* However the bus can also be explicitly specified.

Can ONE provide an explicit BUS option in the DISK section of a vm definition to allow this to be set?  This would give access to other BUS types such as 'sata' which are needed for some OS, especially some versions of Windows:

<target dev='[TARGET]' bus='[BUS]'/>

* From http://libvirt.org/formatdomain.html

"The optional bus attribute specifies the type of disk device to emulate; possible values are driver specific, with typical values being "ide", "scsi", "virtio", "xen", "usb", "sata", or "sd" "sd" since 1.1.2. If omitted, the bus type is inferred from the style of the device name (e.g. a device named 'sda' will typically be exported using a SCSI bus)."

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-17T18:34:57Z

---

Moving it to backlog to plan it after 4.8

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Matthew Richardson** (Matthew Richardson)
Original Date: 2014-07-18T09:28:24Z

---

Looking at the code there used to be a BUS option, but it was removed when DEV_PREFIX was added - presumably with the idea that libvirt would always pick the bus automatically, so there was no need to explicitly specify it?

The relevant commit is: a26fad7fe510269ba3072e9e67a936c6b1440cd0

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-07-18T10:04:20Z

---

Matthew Richardson wrote:
> Looking at the code there used to be a BUS option, but it was removed when DEV_PREFIX was added - presumably with the idea that libvirt would always pick the bus automatically, so there was no need to explicitly specify it?
> 
> The relevant commit is: a26fad7fe510269ba3072e9e67a936c6b1440cd0

Yes that was the idea, but maybe there are options that cannot be selected otherwise, e.g. sata/scsi would be sd for both?

**Comment by rsmontero** [comment]
This is fixed
