### ISSUE TITLE
Show log information for services

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#796]
---

Author Name: **Daniel Molina** (Daniel Molina)
Original Redmine Issue: 3116, https://dev.opennebula.org/issues/3116
Original Date: 2014-07-30

---

If the user quota is exceeded while deploying a service, the user will not know why the service is in FAILED

**Comment by al3xhh** [comment]
PR to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/24)

PR to merge in 5.12:

- [docs](https://github.com/OpenNebula/docs/pull/1214)
