### ISSUE TITLE
Implement a consistent way to store Sunstone's user preferences

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#800]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 3124, https://dev.opennebula.org/issues/3124
Original Date: 2014-07-31

---

Now this can be done at the group level, and it is not dynamic. This filter could be switched by the user

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-08-05T10:42:04Z

---

This could allow to define:
#Filter options (all - mine) in cloud view
#table columns
#Deal with current language, view options
...

**Comment by rsmontero** [comment]
Already done
