### ISSUE TITLE
Service templates with dynamic networks do not work from the CLI

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#803]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3134, https://dev.opennebula.org/issues/3134
Original Date: 2014-08-07

---

Although the oneflow-template instantiate method allows a template file to merge, it does not ask for the dynamic networks, so the deployment fails.
The command should ask for the inputs, or the server should complain before creating the Service.

**Comment by al3xhh** [comment]
This feature has been already implemented. In the new OneFlow the CLI asks for the value of the networks existing in the templates.

Closing it.
