### ISSUE TITLE
Configuration option to enable the automatic deletion of disks after detach

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#806]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 3152, https://dev.opennebula.org/issues/3152
Original Date: 2014-08-14
Original Assignee: Javi Fontan

---

The current behaviour skips disk deletion and leaves it to the epilog phase of the VM, where all the VM dir structure is deleted

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2014-08-15T10:26:18Z

---

This can  be either by:

* Adding a new operation delete_detach
* Adding a new parameter/option to the TM command so a regular delete can be differentiated from a detach one

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Tino Vázquez** (Tino Vázquez)
Original Date: 2015-07-24T09:03:42Z

---

Check delete of detached disks in ssh drivers

**Comment by rsmontero** [comment]
Fixed
