### ISSUE TITLE
Add buttons to move to previous/next resource

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#809]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 3164, https://dev.opennebula.org/issues/3164
Original Date: 2014-08-27

---

Hello,

In Sunstone 4.8, when selecting a resource, its informations are displayed in dedicated “page”.

It's more difficult to review several resources, one after the other, or apply to changes on small list of resources:

* change the *@TYPE@* of 4 *@DATABLOCK@*
* look for differences between two templates

I propose to add two buttons *@prev@* and *@next@* at the right of the *@back@* one, here is the use case:

1. User selects a list of resources, for examples templates
1. User selects the template with *@ID@* *@105@* in the list (from *@100@* to *@110@*)
1. Sunstone display the template information
1. User click on the *@template_template_tab@* button to review the template definition
1. User click on the *@next@* button
1. Sunstone display the template definition of the template *@ID@* *@106@*
1. User click two times on the *@prev@* button
1. Sunstone display the template definition of the template *@ID@* *@104@*

The *@next@* button is then equivalent for the user to:
1. Click on the *@back@* button
1. Select the next resource in the list
1. Click on the *@template_template_tab@* button

**Comment by tinova** [comment]
FireEdge Sunstone pins the card view so VMs can be navigated, closing
