### ISSUE TITLE
onevnet updatear should have a --append option

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#810]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3172, https://dev.opennebula.org/issues/3172
Original Date: 2014-09-04

---

None

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/22)
- [tests](https://github.com/OpenNebula/development/pull/1099)

PR to merge in 5.12:

- [docs](https://github.com/OpenNebula/docs/pull/1212)
