### ISSUE TITLE
VM snapshots are always linearly displayed

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#811]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 3173, https://dev.opennebula.org/issues/3173
Original Date: 2014-09-04

---

Hello,

Using ONE 4.8, I made some tests on "snapshots":http://docs.opennebula.org/4.8/user/virtual_resource_management/vm_guide_2.html#snapshotting:

1. Take a snapshot of an *@initial state@*
1. Do some modifications
1. Take a new snapshot for the *@first option@*
1. Revert to snapshot *@initial state@*
1. Do other modifications
1. Take a new snapshot for the *@second option@*
1. Revert to snapshot *@first option@*
1. Do other modifications
1. Take a new snapshot for continuation after *@first option@*

This result in the following flat list of snapshots:

* *@0 init 16:29:53 04/09/2014 Revert Delete@*
* *@1 first option 16:33:54 04/09/2014 Revert Delete@*
* *@2 second option 16:39:48 04/09/2014 Revert Delete@*
* *@3 fix something 16:45:52 04/09/2014 Revert Delete@*

A hierarchical list could be better to understand:

* *@0 init 16:29:53 04/09/2014 Revert Delete@*
** *@1 first option 16:33:54 04/09/2014 Revert Delete@*
*** *@3 fix something 16:45:52 04/09/2014 Revert Delete@*
** *@2 second option 16:39:48 04/09/2014 Revert Delete@*

Regards.

**Comment by rsmontero** [comment]
This is done and should be configurable by snapshot type
