### ISSUE TITLE
Suggest disk snapshot name in Sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#816]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 3190, https://dev.opennebula.org/issues/3190
Original Date: 2014-09-17

---

Fill the form with a meaningful name for disk snapshots. Something like "<vm name>-<disk target>-<date>". It could also be changed by the user.

**Comment by rsmontero** [comment]
The dialog is now different it does not apply
