### ISSUE TITLE
Authorize user/group to create restricted networks

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#826]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 3224, https://dev.opennebula.org/issues/3224
Original Date: 2014-10-03

---

Hello,

I would like to permit some groups to manage their internal network topology.

The use case is the following:

1. the ONE admin create an internal bridge on the nodes usable by the user/group
1. the ONE admin declare the bridge name as useable by the user/group
1. the user/group has access to the Vnet creation dialog but with limited possibilities:
** the network type must be forced and not settable (even displayed)
** the bridge name must be forced and not settable (even displayed)
** the *@VLAN@* may be force to yes, depending if the ONE admin share the bridge with other user/group
** the *@VLAN_ID@* may be disabled and not displayed to let ONE manage it

Maybe something like a *master network* defined by the ONE admin and useable by the user/group, and the user/group can create some *slave networks* using the predefined fields of the master.

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlos Martín** (Carlos Martín)
Original Date: 2015-03-27T16:12:12Z

---

Hi,

I think this was implemented by the VNet reservations:
http://docs.opennebula.org/4.12/user/virtual_resource_management/vgg.html#vnet-self-provisioning-reservations

Can we close this ticket?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2015-09-29T14:37:24Z

---

Carlos Martín wrote:
> Hi,
> 
> I think this was implemented by the VNet reservations:
> http://docs.opennebula.org/4.12/user/virtual_resource_management/vgg.html#vnet-self-provisioning-reservations
> 
> Can we close this ticket?

Sorry, mail issues prevent me from being notified of your comment.

The original use case was the following:

* we have a bridge called *@physical@* with a trunk on the physical switches to pass “official” VLAN to some VMs
* we have a bridge called *@nebula@* where we plug virtual networks (networks not related to physical infrastructure)
* we want some VDC admins to create their own virtual networks on bridge *@nebula@* without conflicting with others

To achieve this, we need:

* to restrict the bridge name to *@nebula@*
* to force the *@VLAN@* to *@yes@* since the bridge is shared between several groups
* to disable the *@VLAN_ID@* to let OpenNebula manage it automatically (*@:start_vlan@* + *@:network_id@*)
* to let the VDC admins manage their address range pool

The reservation requires the ONE admin to pre-create the networks and their address ranges and make reservation delegated to users which is great to give limited range of IP on the *@physical@* network to groups.

Thanks.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Kristian Feldsam** (Kristian Feldsam)
Original Date: 2016-11-14T09:06:33Z

---

Hello, I have related request https://forum.opennebula.org/t/allow-groupadmin-to-create-manage-own-802-1q-networks/3260

but instead of bridge, I like to preddefine physical device to use with 802.1q driver. I can't create vlans on bridge, because of not working gvrp dynamic vlan registration, which works only on physical device. My request is little bit simplier, I just need to predefine and force:

* Network type to 802.1q
* Physical device to custom, for ex. "team0"
* Automatic VLAN_ID on

So basicly it is "template" which user picks and create netwrok from it.

No need to do something with address ranges...

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Kristian Feldsam** (Kristian Feldsam)
Original Date: 2016-11-14T09:08:29Z

---

Please add this to 5.4 roadmap, thank you.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Bernhard J. M. Grün** (Bernhard J. M. Grün)
Original Date: 2017-01-09T16:09:13Z

---

I would also benefit from that feature.

A perfect addition to this would be the possibility to use VXLAN (IDs) instead of the specialization to (only) VLANs.
I also assume that using VXLAN is easier to use for many installations because it is mostly independent of the switch configuration.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-04-24T18:15:29Z

---

I agree too, it is extremely necessary feature.

I think Network templates is very good idea.

**Comment by rsmontero** [comment]
May be also related to #1301
