### ISSUE TITLE
Add LOCATION tag to vCenter drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#831]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 3253, https://dev.opennebula.org/issues/3253
Original Date: 2014-10-20
Original Assignee: Tino Vázquez

---

Same as in the hybrid drivers, to allow:

PUBLIC_CLOUD=[TYPE="vcenter", LOCATION="vCenterA", VM_TEMPLATE="uuid1"]

PUBLIC_CLOUD=[TYPE="vcenter", LOCATION="vCenterB", VM_TEMPLATE="uuid2"]

**Comment by rsmontero** [comment]
This is implemented
