### ISSUE TITLE
Improve usability of hybrid section of the Template wizard

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#832]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3279, https://dev.opennebula.org/issues/3279
Original Date: 2014-10-31
Original Assignee: Abel Coronado

---

For example, in ec2 the host should be a drop-down with the existing ec2 hosts.

And other fields should have examples. It's not clear if a yes/no or true/false is required for some inputs.

**Comment by tinova** [comment]
won't be pursuing this
