### ISSUE TITLE
Ceph driver tuning

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#844]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 3362, https://dev.opennebula.org/issues/3362
Original Date: 2014-11-18
Original Assignee: Jaime Melis

---

This  patch moves the 'snap' and 'protect' operations from VM disks to VM images, leaving only the 'clone' operation for VM disks.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2015-02-17T16:32:43Z

---

I see two problems with this patch:

1.- It introduces an arbitrary number of snapshot layers, i.e. when an image is copied multiple times; this will probably impact in performance. Using snapshots for rapid VM disk image provisioning is already in use in the TM (i.e multiple 1st layer snapshots of the golden image)

2.- We will require a migration path as most of the operations now need to refer to snapshots (@snap sources), current registered images won't work.

Although it may help when dealing with copying and registering images, this is normally a one-time operation and something probably you want to settle down before firing VMs. Probably reducing snapshot layers and having already the snapshots in the TM code is better for the overall performance.

I'm holding down this patch to further discuss this.

**Comment by rsmontero** [comment]
Fixed
