### ISSUE TITLE
Improve kvm im error messages

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#845]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3375, https://dev.opennebula.org/issues/3375
Original Date: 2014-11-21

---

When libvirt is not running, the error in the host template is:
```
Error monitoring Host localhost (0): Error executing probes

```

It should say something similar to the actual problem:
```
$ ./kvm.rb 
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

```

**Comment by tinova** [comment]
duplicated by 5906
