### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#848]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3394, https://dev.opennebula.org/issues/3394
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Christian Hüning** (Christian Hüning)
Original Date: 2015-04-14T05:51:31Z

---

Would like that as well!

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Dirk Estenfeld** (Dirk Estenfeld)
Original Date: 2016-08-31T11:07:46Z

---

was this feature added in the meanwhile? --> http://opennebula.org/docker-machine-and-opennebula/

**Comment by tinova** [comment]
Integration with Docker Machine is being addressed in #1838
