### ISSUE TITLE
More fine-grained control over element visibility

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#851]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3398, https://dev.opennebula.org/issues/3398
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf.

This request is to implement a way to hide parts of sunstone. For example, the capacity (cpu and memory sliders) in the new template wizard.

The proposal was to have certain element groups labeled, and then hide things by css.

**Comment by rsmontero** [comment]
Implemented through yamls views
