### ISSUE TITLE
Control the individual actions allowed for each user

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#852]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3399, https://dev.opennebula.org/issues/3399
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf.

Similar to the sunstone yaml files, the core could have a way to define each allowed call for a user. For example, have onevm poweroff allowed but shutdown defined.
This configuration would apply at the core level, and it could also be used by Sunstone to hide the buttons for the denied actions.

**Comment by juanmont** [comment]
duplicated: #823

**Comment by rsmontero** [comment]
This partially implemented with the new configurable actions and #1401
