### ISSUE TITLE
Add custom buttons

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#853]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3400, https://dev.opennebula.org/issues/3400
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf.

The request is to have a way to define extra buttons in Sunstone that can trigger any external scripts.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlo Daffara** (Carlo Daffara)
Original Date: 2014-12-05T16:38:55Z

---

I strongly second this. We already have to maintain a separate webapp for many actions on hosts (like IPMI actions) that we would love to integrate directly within sunstone.

**Comment by rsmontero** [comment]
To be considered in #1510
