### ISSUE TITLE
Add time frame to quotas

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#856]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3403, https://dev.opennebula.org/issues/3403
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf.

This feature would allow to set an amount of resource-hours for a time frame.
For instance, a user will have 400 cpu-hours for this month. This means he can decide to create small VMs and run them more time, or create bigger one for less time.

OpenNebula needs a way to manage consumable quotas, like a credit system. Ideally these credits can be consumed when a VM is fired or transferred to other users (e.g. group admin to her users)

**Comment by rsmontero** [comment]
Closing this as duplicate for #1549
