### ISSUE TITLE
Ceph disk snapshots

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#858]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3405, https://dev.opennebula.org/issues/3405
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf.

Similar to the current system snapshots, but only for the ceph disks. Each disk has a list of snapshots with a name and a date, and users can restart the VM with the disk reverted to a previous state.

**Comment by rsmontero** [comment]
Implemented
