### ISSUE TITLE
Cloudbursting to other OpenNebula instance

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#859]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3406, https://dev.opennebula.org/issues/3406
Original Date: 2014-12-05

---

Requested during the OpenNebulaConf.

Just like we have cloudbursting drivers for ec2, develop a new set to interact with a remote ONE installation.

**Comment by tinova** [comment]
available in 5.8: http://docs.opennebula.org/5.8/advanced_components/cloud_bursting/oneg.html
