### ISSUE TITLE
Support non alphanumeric characters for templates

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#867]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 3452, https://dev.opennebula.org/issues/3452
Original Date: 2014-12-15
Original Assignee: Javi Fontan

---

Importing vCenter templates with characters #$& result in error as OpenNebula does not allow names with those characters. Also, some characters are escaped by vCenter so % and / become %25 and %2f. They should be unescaped when importing into OpenNebula.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **James Dingwall** (James Dingwall)
Original Date: 2015-01-07T12:58:54Z

---

Similarly in the add datastore wizard special characters cannot be used without being escaped in the path fields and when they are the then the escaped character is passed in the xml to the driver scripts.  The result returned from the server when not escaped includes:

<div id="summary">
        <h1><strong>ArgumentError</strong> at <strong>&#x2F;datastore
          </strong></h1>
        <h2>invalid %-encoding ({&quot;datastore&quot;:{&quot;name&quot;:&quot;one system&quot;,&quot;tm_mad&quot;:&quot;mydriver&quot;,&quot;disk_type&quot;:&quot;block&quot;,&quot;type&quot;:&quot;SYSTEM_DS&quot;,&quot;base_path&quot;:&quot;percent%opennebula&quot;},&quot;cluster_id&quot;:&quot;100&quot;,&quot;csrftoken&quot;:&quot;f30efa53fe6671e90fecdb83e820fde5&quot;})</h2>
        <ul>
          <li class="first"><strong>file:</strong> <code>
            common.rb</code></li>
          <li><strong>location:</strong> <code>decode_www_form_component
            </code></li>
          <li class="last"><strong>line:
            </strong> 898</li>
        </ul>
      </div>

Version 4.10.1

**Comment by rsmontero** [comment]
This should be working in current releases
