### ISSUE TITLE
Add list of authorized/denied instance types/networks per template

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#868]
---

Author Name: **Daniel Molina** (Daniel Molina)
Original Redmine Issue: 3478, https://dev.opennebula.org/issues/3478
Original Date: 2014-12-23

---

Daniel Dehennin wrote:
> Ruben S. Montero wrote:
> > This issue is to:
> > * add option to enable/disbale the capacity and network sections (create dialog).
> 
> +1
> 
> In our use case, most of the time a user clone a VM template is to increase the capacity or run the VM on its own network, so cloud view is great for us, even if not completely used (#3414).
> 
> This could be a *@true@* / *@false@* or a list of authorized/denied capacities or networks, or two settings, a *@true@* / *@false@* flag, and when flag is *@true@* check a list, for example:
> 
> [...]
> 
> In which case, just switching the *@CAPACITY_SELECT@* value to *@FALSE@* disable all capacities.
> 
> For networks, if a user have the *@USE@* ACL on a shared network, but a VM has a built-in DHCP server, the admin could opt-in or opt-out the networks usable with this VM, for example:
> 
> [...]
> 
> The selection should include the *@_ENABLED@* list first and then exclude the *@_DISABLED@* list.
> 
> These parameters should be saved if the user save the VM.
> 
> The capacities could be set in the VM template but I see it more useful at user groups, for example:
> 
> - every body is authorized to use *@small-x1@*, *@small-x2@* and *@medium-x2@*
> - group *@need_power@* can use *@medium-x4@* and *@large-x4@*
> - group *@prod_admin@* can use *@large-x8@*
> 
> I understand that all of this is useless if the user can update its own VM templates:
> 
> # user clone a VM
> # user update the VM template to remove the VM limitations
> 
> but the per group limitations stays
> 
> Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2016-07-19T09:41:04Z

---

I think the *@CAPACITY@* part of this request is irrelevant with latest 5.0 capacity management.

Regards.

**Comment by rsmontero** [comment]
already done
