### ISSUE TITLE
MAC spoofing rule does not filter ARP traffic

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#869]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 3480, https://dev.opennebula.org/issues/3480
Original Date: 2014-12-29

---

The Security Groups filter rules to prevent MAC spoofing does not handle ARP requests/responses. Probably the driver should use arptable command.

**Comment by atodorov-storpool** [comment]
Looking at the current code it looks like the ARP requests/responses are still not handled? Stealing traffic is not possible, true, but a DOS case is still valid (IMO):
Instantiate some VMs with IPs from a VNET, bring up all VNET IPs manually inside a rogue VM, observe connection issues when the rogue VM mess with the ARP table on the other VMs/switches...
