### ISSUE TITLE
Command to manage hooks without restarting OpenNebula

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#879]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 3542, https://dev.opennebula.org/issues/3542
Original Date: 2015-02-02

---

Hooks are now defined in oned.conf. This feature will allow users to manage hooks using a specific tool, such as 'onehook'. This feature would allow administrators to:

    * Create and register a hook
    * Manually trigger a hook
    * Enable and disable a hook
    * Modify a hook

This implies removing the hook definitions from the oned.conf file.

**Comment by vholer** [comment]
Duplicate to implemented #3380 . Closing.
