### ISSUE TITLE
Flag to clear guestinfo after consumption

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#883]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 3549, https://dev.opennebula.org/issues/3549
Original Date: 2015-02-02

---

Ideally controllable through the CONTEXT section, to avoid leaving sensitive information.

CONTEXT=[CLEAR_GUESTINFO="YES"]

defaulted to NO

This can be achieved with the VMware tools info-set command.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Date: 2017-06-08T10:43:32Z

---

check if context is stored in the filesystem somehow

**Comment by sergiojvg** [comment]
Not supported on every hypervisor. Closing issue.
