### ISSUE TITLE
Document required ports for OpenNebula services to set up firewalls

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#889]
---

Author Name: **Jaime Melis** (@jmelis)
Original Redmine Issue: 3602, https://dev.opennebula.org/issues/3602
Original Date: 2015-02-17

---

None

**Comment by 3pns** [comment]
The required ports to open is not documented in the Front-end Installation resulting in " Cannot contact oned, will retry... Error: libcurl failed to execute the HTTP POST transaction, explaining:  Connection timed out after 60062 milliseconds" after strictly following the tutorial if the firewall is set with policy DROP.
It worked for me after I opened ports 9869, 29876 and 2633.
