### ISSUE TITLE
Add deffered VM resize

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#892]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 3626, https://dev.opennebula.org/issues/3626
Original Date: 2015-02-20

---

Hello,

Sometimes, I would like to resize a VM but I must *@POWER OFF@* it first, which can't be done when it's used.

I would like to:

1. set the future capacities when the VM is running
1. plan an action to reboot the VM at night at apply the new capacities

Regards.

**Comment by rsmontero** [comment]
This maybe covered by scheduled actions, e.g. poweroff, resize at a given time. Closing
