### ISSUE TITLE
User Input in service template

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#894]
---

Author Name: **Edouard Bourguignon** (Edouard Bourguignon)
Original Redmine Issue: 3637, https://dev.opennebula.org/issues/3637
Original Date: 2015-02-26

---

Hi,

is it possible to add user input in the service template? It works at the VM template level but it's not efficient when you need to set variables for the whole service (like domain name etc) or when you have dozens of VMs in the template.

Best regards,

Edouard

**Comment by trenton42** [comment]
It also appears that any user input that is set up on the templates is ignored when instantiating a service (the variables are set, but they are blank).

**Comment by al3xhh** [comment]
This new feature has been already added to the new OneFlow. No now the flow can have multiple custom attributes (user inputs) and the CLI or Sunstone will ask for the value.

Closing it.
