### ISSUE TITLE
Change the concurrency model of drivers

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#898]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 3676, https://dev.opennebula.org/issues/3676
Original Date: 2015-03-12

---

Right now the drivers create a new thread for each action they execute. This was OK for ruby 1.8 as it used green threads and they are really cheap. From 1.9 and upwards real threads are used and the creation is more expensive. This make the driver slower for a high amount of tiny actions.

The proposed solution is creating a thread pool where the threads will be reused for new actions.

**Comment by jmelis** [comment]
fixed
