### ISSUE TITLE
Create Arch Linux Contextualisation Package

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#899]
---

Author Name: **Nico Schottelius** (Nico Schottelius)
Original Redmine Issue: 3684, https://dev.opennebula.org/issues/3684
Original Date: 2015-03-16

---

Hello,

we are at the moment looking at providing an Arch Linux image for Opennebula. It is likely that we create a contextualisation package (maybe based on the deb/rpm). Would you be interested in adding it to the files section afterwards?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2015-03-16T16:34:31Z

---

I think it is more natural for Arch users to add a link to the documentation to the AUR package. In any case, it is quite interesting.

THANKS for contributing :)

**Comment by vholer** [comment]
Currently, the Arch package is very old and also the related code in OpenNebula/addon-context-linux is not maintained. I have opened a separate bug to bring back the Arch Linux at some point https://github.com/OpenNebula/addon-context-linux/issues/96 . Closing this issue here.
