### ISSUE TITLE
Downloads can fail, but still not return in error

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#903]
---

Author Name: **Roy Keene** (Roy Keene)
Original Redmine Issue: 3727, https://dev.opennebula.org/issues/3727
Original Date: 2015-03-30
Original Assignee: Javi Fontan

---

If the downloader.sh script is used in a pipeline, as is common:

$DUMP | ssh host dd...

Then the exit status of the pipeline is the exit status of the last command in the pipeline (ssh, in this case) which often is not sufficient.

Downloading from the Marketplace can or other URLs can fail (for a variety of reasons) and this error will go unreported, since "ssh" did not fail.

To workaround this, "set -o pipefail" should be done before calling this idiom.

Attached is a patch that does this in the places I could find it.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Roy Keene** (Roy Keene)
Original Date: 2015-03-30T19:32:28Z

---

The originally included patch does not work, testing errors out.

A new patch will be tested and attached to this ticket.

**Comment by vholer** [comment]
I believe this is not issue anymore, the fix was introced by https://github.com/OpenNebula/one/commit/bdda84262f2447c9f6bfe946bfdf1ad42785aa44. Closing.
