### ISSUE TITLE
Downloader does not quote URLs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#904]
---

Author Name: **Roy Keene** (Roy Keene)
Original Redmine Issue: 3728, https://dev.opennebula.org/issues/3728
Original Date: 2015-03-30

---

The downloader does not quote URLs appropriately and things can leak because of this.

Attached is a partial patch, a more intrusive patch requires the "set_downloader_args" function to be made safe, which requires modifying everything that calls it as well...

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2015-05-07T10:51:31Z

---

Thanks!

**Comment by rsmontero** [comment]
Already implemented in current versions
