### ISSUE TITLE
FORMAT attribute for volatile swap images can misslead

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#910]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 3773, https://dev.opennebula.org/issues/3773
Original Date: 2015-04-23

---

I am marking as sunstone but probably core is related too...

How to reproduce in sunstone - attach volatile disk of type *swap* and fill *Format* field with for example 'ext3'
On the storage tab there is a line:
```
ID 	Target 	Image / Format-Size 	Persistent 	Save as 	Actions 	
0 	vda 	CentOS-7 	        NO 		- 		Snapshot  Detach
2 	sda 	2GB - ext3 	      NO 		- 		Detach

```

Here I added second swap disk with emty *Format' field and there is no clue that it is swap:
```
ID 	Target 	Image / Format-Size 	Persistent 	Save as 	Actions 	
0 	vda 	CentOS-7 	        NO 		- 		Snapshot  Detach
2 	sda 	2GB - ext3 	      NO 		- 		Detach
3 	sdb 	2GB 	             NO 		- 		Detach

```

I would like swap disks *Format* to be always 'swap'.

And one little glitch - the header says Format-Size but data in the column is Size-Format.

Best Regards,
Anton

**Comment by rsmontero** [comment]
Working now
