### ISSUE TITLE
Include active group of the logged user

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#915]
---

Author Name: **Daniel Molina** (Daniel Molina)
Original Redmine Issue: 3791, https://dev.opennebula.org/issues/3791
Original Date: 2015-05-04

---

@Is it possible to configure Sunstone in order to besides the login user it also appears the group to which the user belongs?

This can be useful if an user belongs to different groups, so if the user changes between between groups, he/she always can see with what group he/she is operating by seeing the group used on the sunstone in the same way that it is showed the login user.@

**Comment by al3xhh** [comment]
Sunstone already shows the user group by clicking on the username, closing it.
