### ISSUE TITLE
sunstone ignores the no_proxy environment variable

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#916]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 3796, https://dev.opennebula.org/issues/3796
Original Date: 2015-05-06

---

Hi,

Sunstone ignores the no_proxy environment variable 
```
no_proxy="localhost,127.0.0.0/8"

```
and tries to connect to oneflow
```
"http://localhost:2633/RPC2"

```
through proxy (http_proxy environment variable).
The proxy is used to connect marketplace.

Thanks for your help,

Laurent

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Laurent Grawet** (Laurent Grawet)
Original Date: 2015-05-06T13:14:38Z

---

One small mistake in my description regarding the oneflow url, it is of course
```
"http://localhost:2474/service"

```

**Comment by carloshm91** [comment]
[ONE]
* https://github.com/OpenNebula/one/pull/3896
[DOC]
* https://github.com/OpenNebula/docs/pull/822
