### ISSUE TITLE
oneflow and oneflow-template ignore the no_proxy environment variable 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#917]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 3797, https://dev.opennebula.org/issues/3797
Original Date: 2015-05-06
Original Assignee: Javi Fontan

---

Hi,

This is related to #3796
oneflow and oneflow-template ignore the no_proxy environment variable 
```
no_proxy="localhost,127.0.0.0/8"

```
and try to connect to oneflow
```
"http://localhost:2474/service"

```
through proxy (http_proxy environment variable).
The proxy is used to connect marketplace.

Thanks for your help,

Laurent

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-09-06T15:18:38Z

---

It seems that the Ruby Net::HTTP does not support no_proxy env variable.

**Comment by al3xhh** [comment]
This variable is not longer available in OpenNebula, so closing this ticket.
