### ISSUE TITLE
Make VCPU first class citizien

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#922]
---

Author Name: **Nico Schottelius** (Nico Schottelius)
Original Redmine Issue: 3833, https://dev.opennebula.org/issues/3833
Original Date: 2015-06-11

---

VCPU (= cores emulated in the VM) is at the moment a second class citizien:

* cloud views display only CPU
* accounting is based on CPU

However CPU only defines the reserved CPU space on the host.

Our users are more interested in being able to select (and charged!) by the number of VCPUs they have in the VM then CPU reservation (our hosts are underutilized due to networking constraints anyway).

I would like to see opennebula to be able to:

* Allow users to create/book VMs and have VCPU displayed instead of CPU
* Have accounting include VCPU usage, so we can bill by Disk space used + RAM + VCPU usage

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Nico Schottelius** (Nico Schottelius)
Original Date: 2017-06-10T20:52:05Z

---

Hello,

is there any possibility to raise the priority of this and include it in one of the next releases?

**Comment by rsmontero** [comment]
I think there is a misunderstanfing of vCPU, that's related to the virtual hardware configuration and CPU that's related to the capacity allocation. Closing this.
