### ISSUE TITLE
Set image format per datastore

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#928]
---

Author Name: **Javi Fontan** (Javi Fontan)
Original Redmine Issue: 3867, https://dev.opennebula.org/issues/3867
Original Date: 2015-07-08

---

Some datastores only accept one image format. For example, LVM and Ceph use RAW. Add the option to automatically set this format for each datastore.

This can be done setting an inherited parameter in the OpenNebula configuration file:

```
INHERIT_DATASTORE_ATTR = "DRIVER"

```

And then adding a @DRIVER@ value to the datastore template.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2015-07-10T07:39:29Z

---

+1

This could be related to part of #1764#note-5.

Regards.

**Comment by rsmontero** [comment]
Fixed
