### ISSUE TITLE
Redesign UI for CPU attribute, include overcommit section 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#930]
---

Author Name: **EOLE Team** (EOLE Team)
Original Redmine Issue: 3870, https://dev.opennebula.org/issues/3870
Original Date: 2015-07-09

---

Hello,

The dashboard display *@REAL CPU USAGE@* and *@ALLOCATED CPU@* as integers numbers like *@2020 / 4780@*.

The VM *@CPU@* configuration is a float with a correspondence *@1@* CPU in template *@==@* *@100@* CPU on dashboard.

This is quite confusing for users.

This should be also considered for cloud view

Is it possible to only use integers as on dashboard?

Regards.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2015-11-25T15:04:10Z

---

Hi

You are right the values for CPU in hosts are in percentage while the VM templates are not. These definitions affects multiple components from the UI, CLI, oned, scheduler down to the monitoring drivers for each hypervisor KVM, EC2, vCenter... So it is really difficult to change the definition of one of these two (VM Template CPU or Host CPU). We've been thinking of how we can avoid confusion and improve the dashboard, but we could not find a solution good enough (we prefer to keep consistency for the same metric across views and tabs, i.e. host FREECPU always in percentage). So, considering this, do you have a proposal?

Cheers and thanks for the feedback.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2016-01-04T11:18:48Z

---

After discussing this, we think that the best option is to hide the CPU value from the user input, and move it to an Overcommit section, which is actually the purpose of this attribute. 

Updating the issue subject to reflect this.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Date: 2016-07-11T15:03:47Z

---

- Cloud View should present the value of VCPU, not CPU
- Evaluate as well fine grained definitions of CPU per SOCKET (at least in vCenter)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2016-07-11T15:06:59Z

---

OpenNebula Systems Support Team wrote:
> - Cloud View should present the value of VCPU, not CPU

This one could be configurable to make capacity resizing available?

**Comment by rsmontero** [comment]
Already done with slider
