### ISSUE TITLE
An image can be used twice by a VM, but this breaks the used/ready logic

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#937]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 3888, https://dev.opennebula.org/issues/3888
Original Date: 2015-07-24

---

If an image is used twice by the same VM, the image still has RUNNING_VMS = 1, because the list of VM IDs is a set.

If one of the disks is detached, the image now has 0 running VMs, and its state is set to ready.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **EOLE Team** (EOLE Team)
Original Date: 2016-07-22T14:36:27Z

---

I confirmed on 5.0.2

**Comment by paczerny** [comment]
Only 7 years to solve this simple issue, we are like a flash :-/
PRs to merge:
* [src](https://github.com/OpenNebula/one-ee/pull/2262)
* [tests](https://github.com/OpenNebula/development/pull/2003)
* [docs](https://github.com/OpenNebula/docs/pull/2378)
