### ISSUE TITLE
split os image and datablock image in sunstone

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#945]
---

Author Name: **alan zhang** (alan zhang)
Original Redmine Issue: 3930, https://dev.opennebula.org/issues/3930
Original Date: 2015-08-10

---

when we create datablock image，we need fill in more blank. it's not easy to use.

maybe we can design datablock image like AWS  split images  and ebs.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Daniel Molina** (Daniel Molina)
Original Date: 2015-08-17T13:44:24Z

---

In OpenNebula 4.14 you will be able to resize any of the disks when a template is instatiated, would that be enough?

**Comment by rsmontero** [comment]
Seems done already
