### ISSUE TITLE
Online resize memory for VM

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#949]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 3954, https://dev.opennebula.org/issues/3954
Original Date: 2015-08-28

---

QEMU/KVM/LIBVIRT offer the possibility to resize the amount of memory when in the libvirt XML specification the <currentMemory unit='KiB'></currentMemory> is specified besides the "<memory unit='KiB'></memory>" for a running VM. For example:

<memory unit='KiB'>1048576</memory>
<currentMemory unit='KiB'>4194304</currentMemory>

This Would set the amount of available memory for a VM to 1 GB, with a max of 4GB. If OpenNebula would generate deployment files with both memory specifications VM's can be resized online (without) downtime as far as memory is concerned.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2015-08-28T08:00:58Z

---

related to [[http://dev.opennebula.org/issues/3395]] VM capacity resize for running VMs

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Roy Keene** (Roy Keene)
Original Date: 2017-06-27T15:36:53Z

---

Perhaps a better approach:  https://medium.com/@juergen_thomann/memory-hotplug-with-qemu-kvm-and-libvirt-558f1c635972

This is similar to what VMware does with ESXi, though libvirt makes you do more work to figure out how to manage your DIMMs.

**Comment by rsmontero** [comment]
Currently working on it for next version on #1660 Closing this one
