### ISSUE TITLE
Custom attributes for network section (NIC) in VM template

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#959]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 4066, https://dev.opennebula.org/issues/4066
Original Date: 2015-10-16

---

In some cases you want to perform some special action in a VM or on the frontend / hypervisor based on some property of a network adapter. As far as I know it's currently not possible to add a custom attribute to the "NIC=[]" section. It would make life easy if a custom attribute could be added. Example use case: configure a special source based route for the specific nic if LB=TRUE is configured. Or setup special openflow rules on the vnet if OPENFLOW_SPECIAL=TRUE.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlos Martín** (Carlos Martín)
Original Date: 2015-10-19T08:26:42Z

---

You can actually add any attribute inside the NIC.

Furthermore, you can even configure in oned.conf if any attribute should be restricted to be used only by oneadmin:
http://docs.opennebula.org/4.14/administration/references/oned_conf.html#restricted-attributes-configuration

Or set the attributes in the vnet template, and copy it to the NICs using that vnet:
http://docs.opennebula.org/4.14/administration/references/oned_conf.html#inherited-attributes-configuration

Can you give it a try to see if your request is already covered?

**Comment by rsmontero** [comment]
Seems this issue was implemented. Closing...
