### ISSUE TITLE
implement snapshot_flatten for VM disk snapshots

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#961]
---

Author Name: **Anton Todorov** (Anton Todorov)
Original Redmine Issue: 4075, https://dev.opennebula.org/issues/4075
Original Date: 2015-10-21

---

Currently it is implemented only for persistent snapshots.

The procedure to flatten should be

check 
if the current disk is NOT based on the selected snapshot to flatten to; then 
   shutdown VM if RUNNING
   revert/rebase to snapshot
   boot VM if was RUNNING
fi
flatten/rebase/delete all other snapshots and delete them from the DB

**Comment by juanmont** [comment]
duplicated: #1004
