### ISSUE TITLE
Two Step Authentication

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#962]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 4078, https://dev.opennebula.org/issues/4078
Original Date: 2015-10-23

---

This issue is to add the capability of OpenNebula to integrate with multi-step authentication methods. Usually this involves sending user identification to the driver and make the driver contact a service to request an auth token. This last step needs user interaction (e.g. Google ID platform and the like)

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlo Daffara** (Carlo Daffara)
Original Date: 2015-10-23T11:10:46Z

---

Totally second this. We are already looking into the Latch addon ( https://github.com/carlosms/opennebula-latch-addon ) to modify and use with U2F/FIDO authentication usb keys, so a more standardised way of working would be great.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Boris Parak** (Boris Parak)
Original Date: 2015-10-25T16:32:02Z

---

Ruben S. Montero wrote:
> This issue is to add the capability of OpenNebula to integrate with multi-step authentication methods. Usually this involves sending user identification to the driver and make the driver contact a service to request an auth token. This last step needs user interaction (e.g. Google ID platform and the like)

I agree, even a (more) generic mechanism where the driver responds with a redirect URL would be useful. This redirect URL would point the user to an external authentication service, this service can implement an arbitrary authentication mechanism. After the authentication process has been completed, the user will get a token (opaque, its actual format or content is not important) and return back to OpenNebula.

So, this redirect driver could be a special implementation of the 'default' driver. If nothing else succeeds, it will redirect the user. When the user returns, a different driver in the driver chain will succeed and let the user in.

What do you think?

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2015-10-26T16:29:53Z

---

Hi Boris

Yes I think it make sense. We could extend the current login token  (OpenNebula oneuser login) two implement a two step one, the first step will return the URI. The client goes to the target auth URL and authenticates, in the second step the result of the authentication (the opaque token) sent to the driver to validate. Once validated a full OpenNebula token (<user_name>:<token>) is generated and could be used to authZ. We need to think how to make this process happen from desktop usage (i.e. kind of pinentry?) or Suntone. 

Cheers

**Comment by dfelsch** [comment]
Hi,

I have implemented a two factor authentication using WebAuthn for Sunstone. This allows to use e.g. U2F/FIDO2 authentication keys (#4545)

![Zwischenablage01](https://user-images.githubusercontent.com/17570892/79547312-feb45380-8093-11ea-99d9-41cee884a996.png)

![Zwischenablage02](https://user-images.githubusercontent.com/17570892/79547353-12f85080-8094-11ea-9523-67adde642ecb.png)

There are some things I would like to mention:
* This patch requires the `webauthn` gem, which requires ruby >= 2.4. To keep OpenNebula's ruby >= 1.8.7 requirement, I detect whether the gem is available and disable Webauthn otherwise.
* I wanted to keep Sunstone's existing user templates. However, those are quite limited. Storing multiple authenticators with their keys, IDs, and counters hits limits very fast. Therefore I'm storing this data in a JSON format (with single quotes instead of double quotes to avoid bugs).
* This patch also fixes issue #4321 

Cheers

**Comment by tinova** [comment]
wow, this is an amazing contribution!! we'll do our best to vet it and add it to the next stable release

**Comment by dfelsch** [comment]
Thanks!

One more thing that came to my mind: WebAuthn requires to temporarily store ephemeral challenges on the server. Ideally one would store these values in the server's session. However, when being called from the UserJSON class, I did not see a way to access the Rack session hash (i.e. without rather disruptive changes). Therefore, I'm using [my own hash for the challenges](https://github.com/dfelsch/one/blob/5abd5dae999a5ae24525cebf39977b8c74365b99/src/sunstone/models/OpenNebula2FA/SunstoneWebAuthn.rb#L25). Maybe somebody with a better overview over the code of Sunstone can come up with a better solution.

**Comment by sbbarragan** [comment]
PRs to merge:
- one: #4545
- docs: OpenNebula/docs/pull/1081

**Comment by tinova** [comment]
thanks for the amazing contribution and thanks for the fix!
