### ISSUE TITLE
Implement log rotate for all the opennebula services

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#963]
---

Author Name: **Daniel Molina** (Daniel Molina)
Original Redmine Issue: 4079, https://dev.opennebula.org/issues/4079
Original Date: 2015-10-23

---

* Sunstone
* Oneflow

https://forum.opennebula.org/t/logrotate-doesnt-work-for-econe-server-or-sunstone/304

**Comment by rsmontero** [comment]
Already implemented in current versions
