### ISSUE TITLE
Allow FILES in vCenter context

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#964]
---

Author Name: **Tino Vázquez** (Tino Vázquez)
Original Redmine Issue: 4086, https://dev.opennebula.org/issues/4086
Original Date: 2015-10-23

---

None

**Comment by sergiojvg** [comment]
PR: https://github.com/OpenNebula/one/pull/3351 --> master, --> one-5.8
Context: https://github.com/OpenNebula/addon-context-linux/pull/162 --> master

**Comment by tinova** [comment]
Testing will be done in the context of OpenNebula/infra#191
