### ISSUE TITLE
Image uploads with OCA

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#965]
---

Author Name: **Boris Parak** (Boris Parak)
Original Redmine Issue: 4089, https://dev.opennebula.org/issues/4089
Original Date: 2015-10-25

---

Would it be possible to add image upload (actual image data transfer) to OCA (& client libraries)?

**Comment by rsmontero** [comment]
This is handled indirectly through OpenNebula drivers.
