### ISSUE TITLE
Reduce vm information stored for each VM in a service document

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#967]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 4096, https://dev.opennebula.org/issues/4096
Original Date: 2015-10-26

---

Currently, all the vm info is stored in the service document. Probably, the code could be modified to store only the VM ID

**Comment by al3xhh** [comment]
Currently the information stored in the document has been reduced to the following:

```
"vm_info": {
  "VM": {
    "ID": "0",
    "UID": "0",
    "GID": "0",
    "UNAME": "oneadmin",
    "GNAME": "oneadmin",
    "NAME": "A_0_(service_1)"
  }
}
```

If you want to check more information about the VM, you need to make an info of it using the ID. And in the OneGate component the option `--extended` has been added to the command `onegate service show`.

Closing it as the functionality has been already implemented.
