### ISSUE TITLE
Fix Group Membership requirement in LDAP/AD

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#969]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4107, https://dev.opennebula.org/issues/4107
Original Date: 2015-10-29
Original Assignee: Javi Fontan

---

Patched provided by Mark Mercado, needs evaluation

1. diff -u /usr/lib/one/ruby/opennebula/ldap_auth.rb.dist /usr/lib/one/ruby/opennebula/ldap_auth.rb
--- /usr/lib/one/ruby/opennebula/ldap_auth.rb.dist      2015-10-08 11:32:53.000000000 +0100
+++ /usr/lib/one/ruby/opennebula/ldap_auth.rb   2015-10-28 18:02:16.382568605 +0000
@@ -147,9 +147,9 @@

     def is_in_group?(user, group)
         result=@ldap.search(
-                    :base   => group,
+                    :base   => @options[:base],
                     :attributes => @options[:group_field],
-                    :filter => "(#{@options[:group_field]}=#{user.first})")
+                    :filter => "(#{@options[:group_field]}=#{group})")

         if result && result.first
             true

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Mark Mercado** (Mark Mercado)
Original Date: 2015-10-29T11:52:10Z

---

So, I had to make two changes, and things seem to be working now (with respect to group membership and AD):

```
1. diff -u /usr/lib/one/ruby/opennebula/ldap_auth.rb.dist /usr/lib/one/ruby/opennebula/ldap_auth.rb
--- /usr/lib/one/ruby/opennebula/ldap_auth.rb.dist      2015-10-08 11:32:53.000000000 +0100
+++ /usr/lib/one/ruby/opennebula/ldap_auth.rb   2015-10-29 11:50:14.979641389 +0000
@@ -147,9 +147,9 @@
 
     def is_in_group?(user, group)
         result=@ldap.search(
-                    :base   => group,
-                    :attributes => @options[:group_field],
-                    :filter => "(#{@options[:group_field]}=#{user.first})")
+                    :base   => @options[:base],
+                    :attributes => @options[:attributes],
+                    :filter => "(&(objectClass=user)(sAMAccountName=#{user})(#{@options[:group_field]}=#{group}))")
 
         if result && result.first
             true

```
```
1. diff -u /var/lib/one/remotes/auth/ldap/authenticate.dist /var/lib/one/remotes/auth/ldap/authenticate
--- /var/lib/one/remotes/auth/ldap/authenticate.dist    2015-10-08 11:32:54.000000000 +0100
+++ /var/lib/one/remotes/auth/ldap/authenticate 2015-10-29 11:47:50.714720051 +0000
@@ -76,7 +76,7 @@
     end
 
     if server_conf[:group]
-        if !ldap.is_in_group?(user_group_name, server_conf[:group])
+        if !ldap.is_in_group?(user, server_conf[:group])
             STDERR.puts "User #{user} is not in group #{server_conf[:group]}"
             next
         end


```

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Mark Mercado** (Mark Mercado)
Original Date: 2015-10-29T11:55:20Z

---

I realize that it'll probably break OpenLDAP (since I'm guessing sAMAccountName probably isn't an attribute), so it's not a good fix or anything. But, I have AD so it got me going.

**Comment by tinova** [comment]
please reopen if it still applies to 6.4+
