### ISSUE TITLE
Depend onruby-mysql2 instead of ruby-mysql

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#974]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 4144, https://dev.opennebula.org/issues/4144
Original Date: 2015-11-10

---

This issue is to evaluate the migration to ruby-mysql2, in particular the sequel (change prefix to "mysql2://") interaction or other libraries dependencies.

**Comment by rsmontero** [comment]
Done
