### ISSUE TITLE
after cold migration custom vnc password is lost

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#977]
---

Author Name: **Tobias Fischer** (Tobias Fischer)
Original Redmine Issue: 4154, https://dev.opennebula.org/issues/4154
Original Date: 2015-11-13

---

after a cold migration the VM cannot be accessed anymore via vnc with the custom password set in template (also random pw). this also affects the vnc connection via sunstone.
the only possibility to connect via vnc to migrated VM is via a external VNC Program and the default vnc PW.
a live migration works as expected - the custom vnc pw is still working after the migration.

**Comment by juanmont** [comment]
This bug is already fixed for the currents versions of opennebula.

If you needed, we can reopen this issue.
