### ISSUE TITLE
Shared disk between VMs

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#979]
---

Author Name: **Peter Loeffler** (Peter Loeffler)
Original Redmine Issue: 4168, https://dev.opennebula.org/issues/4168
Original Date: 2015-11-18

---

KVM has the possibility to share a disk between 2 VMs.
Would be nice to have this feature in OpenNebula.

**Comment by rsmontero** [comment]
This should be implemented by configuring VM services.

**Comment by MATPOCKuH** [comment]
I'm sorry, but how it can be done by configuring VM services?
IMHO VM services are not related to sharing one image between two (or more) VM's.

**Comment by amenendezASAC** [comment]
vCenter has this possibility too. Widly used feature, ie NFS servers.

**Comment by rsmontero** [comment]
Yes we have revaluated this, and we plan to support this KVM and vCenter

**Comment by tinova** [comment]
Duplicated by #1602
