### ISSUE TITLE
sunstone: Change boot order from cloud and groupadmin views

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#982]
---

Author Name: **Laurent Grawet** (Laurent Grawet)
Original Redmine Issue: 4171, https://dev.opennebula.org/issues/4171
Original Date: 2015-11-19

---

Hi,

Users need to change boot order (PXE, HDD...) in cloud and groupadmin views.
This could be activated from yaml files. It would be a nice feature!

Thanks,

Laurent

**Comment by tinova** [comment]
Relevant for Cloud View refactor

**Comment by FrederickBor** [comment]
@tinova PRs to be approve:
- [Code](https://github.com/OpenNebula/one-ee/pull/811)
- [Docs](https://github.com/OpenNebula/docs/pull/1472)
- Tests: Pending
