### ISSUE TITLE
Move all the hardcoded styles to css

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#986]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 4200, https://dev.opennebula.org/issues/4200
Original Date: 2015-11-25

---

There are many html elements with hardcoded styles, spread across different files, what prevents us from updating them easily.

**Comment by rsmontero** [comment]
Closing as duplicat of #1453
