### ISSUE TITLE
Support better translations with gettext

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#990]
---

Author Name: **Carlos Martín** (Carlos Martín)
Original Redmine Issue: 4213, https://dev.opennebula.org/issues/4213
Original Date: 2015-11-26

---

To support sprintf like strings, and plural forms. One example:
```
i18n.translate("There is one running VM.")
    .ifPlural( num, "There are %d running VMs." )
    .fetch( num );

```

One possible js lib: https://slexaxton.github.io/Jed/

**Comment by rsmontero** [comment]
All moved to transifex
