### ISSUE TITLE
Support for Content Libraries in vCenter integration

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#995]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 4243, https://dev.opennebula.org/issues/4243
Original Date: 2015-12-14

---

https://www.vmware.com/products/vsphere/features/content-library

**Comment by tinova** [comment]
Not enough demand, closing.
